\mainmatter

# 现时政治斗争中之我们

中文马克思主义文库 -> 周恩来
现时政治斗争中之我们
（一九二六年十二月十一日）

一

我们既肯定而且坚信目前的政治争斗是应为打倒半封建势力〔1〕而争斗，为实现民主政治而争斗，于是就有人怀疑到目前的革命工作既无差别，何以于国民党〔2〕之外还有共产党的存在和活动；既有了共产党的存在和活动，便定会与国民党发生冲突和分裂。

本来关于这个问题的解释，三年来已经写得说得很多了。只是我们为目前政治争斗做得更有意义，革命分子愈加团结和互相了解起见，仍须有以下的回答：

（一）国民革命原是中国各被压迫阶级共同的出路。不过在这革命过程中，各阶级却有他们各自的出发点，尤其是在民主政治的实施期中，他们更有各自所欲获得的利益。阶级的利益既不同，被压迫最苦的工农阶级自然需要有专门为他们阶级谋利益的共产党为之奋斗，为其前驱。共产党为工农阶级奋斗并引导其参加国民革命，决无碍于国民党领导各阶级努力国民革命，转而在实际工作上更可收相成相助之益。

（二）各被压迫阶级的共同目的虽在国民革命，但在革命的长期争斗中，民族资产阶级总是富于妥协性，小资产阶级也常摇摆不定，只有无产阶级是最不妥协的革命阶级。要靠他携同农民、手工业工人督促小资产阶级、民族资产阶级不妥协地与敌人争斗，才能达到国民革命的真正目的——民族解放和民主政治的实现。所以为工农阶级奋斗的共产党的活动，当然不外领导工农群众的革命力量推进国民革命，以防止其他阶级的妥协性在革命中发生不良影响。这种活动，只有于领导国民革命的国民党有利，使他革命成份更加充实，决无与他有冲突和分裂的危险。因为要有冲突，必是革命的工农群众与和帝国主义敌人妥协的资产阶级冲突；要有分裂，必是革命的国民党左派和共产分子与不革命的右派分子分裂。国民党是革命的，是站在国民革命的领导地位的，自无须怕这种冲突和分裂。而且证之事实：五卅运动〔3〕以来，革命的工农群众，尤其是无产阶级，坚持其反帝精神、罢工策略，时时与想和英帝国主义妥协的资产阶级冲突；廖案〔4〕发生以后，国民党左派和共产派，曾联合一致地与廖案有关的以至反共、反俄、反农工运动的分子争斗，更分裂出许多不革命分子。结果不但于国民革命以至国民党无损，而革命势力转因是而愈加团结，国民革命才得有今日的发展。
二

我们的解释既完，而我们的态度亦更有较具体地表明之必要。

（一）我们共产党领导工农群众参加国民革命，其目的是在打倒国外帝国主义和国内半封建势力，其要求不能超过民主政治的范围。但当着资本家压迫工人谋生活改善的正当要求，或是地主联合一切旧势力摧残农民谋解放的运动时，共产党必须站在工农群众方面，为解除他们的痛苦奋斗到底。为实现民主政治，共产党站在工农方面，其争斗、其要求亦自较他人为急迫。这并非超过国民革命，而实是推进国民革命。

（二）我们知道，国民革命的唯一目的是解放目前的中国，同时中国国民革命又是世界革命的一部分，所以我们承认革命的中国国民党是中国国民革命的领导者，中国共产分子必须加入国民党共同奋斗。但这不是说中国共产党便失其独立性质而不应再有何种独立主张。国民党的联共政策和共产分子加入国民党，事实上是表示了两党的密切关系和国民党的领导地位。在这个原则之下，共产党除赞助国民党和国民政府之外，他还应为工农阶级在民主政治范围内提出政治上、经济上的要求，并督促国民党政府次第实施。

（三）我们很希望国民党能成为一个无左右之分的革命的中国国民党，但事实上不能尽如我们所想。国民革命是各阶级联合的革命，不同的阶级性反映到国民党内自也形成了各派。过去，右派很显然地做了许多反共、反俄、反工农以及勾结旧势力的工作，而左派很坚决地努力于国民革命和民主政治之实现，实行联俄、联共和拥护工农利益的三大革命政策。在这种不同的倾向上，共产派是时时刻刻帮助左派同右派作理论上和事实上的争斗，从中山先生改组国民党直到现在。同时共产派还希望右派能彻底了解民主政治，日趋左倾，忠实的国民党党员都成左派。我们态度如此，既不是要分裂国民党，更不是不愿造成整个的革命的国民党。

（四）我们为了上述三种原故——为工农阶级的利益，为共产党在政治争斗中的主张，为对于国民党的希望，均不能不有公开的意见发表。马克思说，“共产党最鄙薄隐蔽自己的主义和政见”〔5〕，所以我们除宣传主义外，还时时有将政见宣布的必要。不过在现在国民党政府的统治下，我们的政见和批评是属于善意的，希望党政府能予以容纳，这与帝国主义、军阀以及一切半封建势力的敌意攻击和破坏宣传根本相反。若国民党同志竟以此善意的批评和帝国主义反动派的造谣离间等量齐观，或竟以批评一些不法官吏军人的谬误设施和批评国民党政府中有些不合宜的处置，便将事实置之不论，而硬说这是污蔑整个国民党，破坏国民政府，均未免近于武断，故陷人罪。譬如近几月来有几件压迫工人摧残农民运动的案件，工农群众的要求，我们的批评，都是希望党政府能惩办这些不法官吏军人，以拥护国民党农工政策。就是左派同志的《国民周刊》上从前亦曾说过：“在党政府下，是不应该有这种不助进农工运动，不能利用政治力量去运动的官吏，在本党内是绝对不容那些摧残农工运动或轻视农工运动的党员。党政府应要有铁的纪律去受理。”“我们日夕希望民众接近本党，拥护本党，不料这种党员执政权者的一切设施，已使民众退避三舍，这是何等痛恨的事！”“……我们正为着本党民众基础着想，我们更是为一般所谓护党派日夕忧虑亡党的着想，在已逐渐觉悟的民众不是能够以革命帽子戴了去盲目的冲动，在已有组织的民众，我们更不能用什么口惠而实不至的假面具去蒙骗他，何况我们在有组织的民众，我们现在急须民众认识的本党，发生这种摧残，不特民众不为我有，那时如你们所认为该死的程庚，一定不绝起来收拾民众，我们党只有损失，你们杀也杀不尽，杀也杀不来。那是事实，那是十分可虑的。”〔6〕这些严厉的批评持与我们的批评较，我们的岂得谓过？至若摭拾市上的流言，莫须有的事实，以至绝无关系的各种风潮，都硬指为共产党在挑拨，在捣乱，则三年来我们已受尽如此之骂，左派同志亦曾为此受了许多冤枉，我们又何必置辩！只要国民党革命的同志能了解我们批评的立场，继续努力，国民革命将终归胜利。

我们最后高呼：

一切革命分子团结起来！

一切被压迫阶级团结起来！

＊一九二六年冬，随着北伐战争的节节胜利和工农群众运动的迅猛发展，国民党右派势力加紧进行反革命活动，掀起一股反对国共合作和工农运动的逆流。中国共产党内以陈独秀为代表的右倾机会主义者被这股反动潮流所吓倒，不敢坚持无产阶级的领导权，对国民党右派迁就退让。这篇文章就是在这种背景下写的，发表于中共两广区委机关刊物《人民周刊》第三十七期。

