# 坚决肃清党内一切非无产阶级的意识

中文马克思主义文库 -> 周恩来
坚决肃清党内一切非无产阶级的意识
（一九二八年十一月十一日）

同志们：党的政治路线上许多不正确思想的来源，固然是客观环境的反映，然而党的组织还没有布尔什维克化，党内还存在许多非无产阶级的意识，也是一个主要的原因。中国共产党产生于五四运动以后，当时国民党只是一个官僚政客的集团，此外则别无革命的政党，因此许多急进的小资产阶级分子甚至资产阶级分子都进入我们党内来；尤其在国共合作时代，又加入了许多小资产阶级的群众。所以革命形势一经变动，许多党员动摇消极，甚至公然叛党，投降敌人，陷害同志。“八七”会议〔15〕以后，提出改造党的口号，坚决洗刷一切动摇的分子，改造指导机关，的确使党渐渐加强了无产阶级的意识，这是党走向布尔什维克化的道路。但是，到现在党的组织仍然还没有强大的无产阶级的基础，仍然存在有许多小资产阶级的意识。尤其在党员成份上，农民占百分之七十五。因此，这种小资产阶级意识还有大大发展的可能。要使党布尔什维克化，第一要加强无产阶级的基础，同时要继续改造党的组织，尤其要坚决地反对小资产阶级的意识。所以我们在检查了政治路线之后，必须把组织观念上的错误严密检查一下。

第一，极端民主化的倾向。从前组织上有一种“家长制”的形式，党员群众对于党部，下级机关对于上级，只有机械的服从，而无活泼的党的生活。及到改造党的时候，许多地方又走向极端民主化的方向。党员对于党的决议，可以随便不执行。上级机关发一传单，没有交支部通过，支部居然提出质问。党员不得党的许可，可以自由行动。这种小资产阶级极端自由的思想，可以把党的组织打得粉碎，以至于消灭。还有一种不正确的平等观念，如用钱，不管工作的重要与环境，要机械地平均分配，用人要按地域区分，更完全是农民意识均产思想的反映，尤须严厉地肃清。

第二，反机会主义的认识上的错误。反机会主义主要的是要肃清机会主义的政治路线和组织路线，但有些同志竟专门攻击个人，因此而放轻了对于机会主义观念的批评。仿佛某几个人如果打倒了，机会主义便可肃清。殊不知机会主义的来源很深，决不是排除了几个人就能把机会主义肃清的。诚然，党对于那有系统的执迷不悟的机会主义分子，只有尽情驱逐，才能坚固本身壁垒；但是主要的还在批判一切机会主义的观念，使全党同志有明白的认识，然后党的政治路线才能走上正确的道路。至于因私人感情而借题发挥，那更是一种政客式的行为，这是与无产阶级的党绝对不相容的。

第三，个人的意气之争。反对机会主义与盲动主义，在政治上何等重要，但是一把对政治变成专门对人，便成了闹不清的意气之争了。因意气而攻击他人，因意气而不接受他人的批评，甚至不站在党的立场去考查同志的意见与工作，专以意气去推测他的动机，而造成党内无穷的纠纷，这是充分的小资产阶级之意识的表现。

第四，小组织的倾向。现在党内许多小组织的倾向，都是由私人感情的结合，或部落的观念形成的。少数有领袖欲的人想造个人地位，利用这些结合，攻击地位较高或地位相等的人，因此资产阶级种种政客官僚的卑污恶浊手段一同发生了。这是破坏党的最恶劣的倾向。

第五，工学界限。因反机会主义而变成反知识分子，这是很错误的。知识分子虽然有很多动摇的，但是能站在无产阶级的立场来奋斗的人亦不少。在无产阶级中，也有不少丧失了无产阶级的意识而染有小资产阶级意识的。许多同志不明这个道理，于是放着反对小资产阶级意识不谈，专门反对小资产阶级出身的个人，而造成了党内的工学界限，增加了党内的纠纷。这种观念根本上仍是小资产阶级意识。

第六，怀疑改造党的路线。不坚决地引进新的积极分子，尤其是工人分子。保存一种旧的组织观念，使党始终停留在一种命令委派的“家长制”形式之下。分配工作，始终只相信脑筋中几个熟悉的人，而不相信下层中产生出来的新的积极分子，尤其是工人同志。这样会使党的机体日益腐化，永远没有生机，永远不能肃清一切小资产阶级的意识。

第七，改造党的形式主义。引起工农分子是改造党的重要方法。但许多党部执行起来，又陷于形式主义的错误。只是机械地找些工人分子进来，而不加以积极的教育，或则机械地规定指导机关中工人成份的比例，结果还不是由原来那些人——知识分子包办？甚至闹成秘书长专政的笑话。这种引进工农分子的方法，是毫无意义的。

第八，雇佣革命的观念。党只需要少数的革命职业家担负日常的党务，至于在群众中工作的党员，应当不离开社会的职业而为党工作，方能深入群众。然而有些同志，竟有一种雇佣劳动的观念，做工作就要钱，不拿钱就不做事的现象，支部干事也要津贴，以求利益均沾，这是严重的错误。

第九，把党看成救济会。许多同志因失业穷无所归，专门找党来解决生活问题。殊不知党并不是救济的机关，党的工作主要的是在群众中，而不是在党部，决不能人人都派作党部工作。加之同志们如果继续不断地脱离社会的职业，而不去找社会的职业，则党成了和群众没有联系的党，怎样能组织群众领导群众呢？

第十，消极怠工。许多同志观念动摇，在政治上找不到出路，或者看了党内有些个人的意气之争和政客式的结合挑拨，于是心灰意懒，不愿积极工作，这完全是一种小资产阶级的悲观主义。其实革命每天都在向前发展，只要我们能够深刻地去了解群众的情绪，便可以引导我们走向积极的道路。至于我们的党，已经是一个群众的党，只要全党同志坚决地一致地奋斗，少数坏蛋断乎不能破坏党的组织。消极观念，只是一种堕落的倾向。

同志们！上面指出的这些小资产阶级的意识，的确还时时在破坏党的组织，妨碍党的工作。全党的同志，应坚决地起来奋斗，肃清一切小资产阶级的意识。

中央受党的第六次全国代表大会〔16〕的委托，坚决地执行六次大会的决议，与机会主义、盲动主义等不正确的倾向继续猛烈争斗，尤其在党内要把一切小资产阶级意识扫除干净。中央对于党内的纠纷，反对弥缝敷衍的妥协办法，而要坚决地肃清一切非无产阶级的意识。只有这样，才能使全党的同志团结在布尔什维克的精神之下一致奋斗。

同志们！中央有决心继续改造党的组织。对于闹私人意气的同志，无论其历史的长短和工作的好歹，一律不客气地排除，决不让我们无产阶级的政党保留着一毫小资产阶级的意识。中央要求全党同志共同负起这个责任，一致奋斗，完成党的布尔什维克化。

中央指出下面几点为全党同志一致奋斗的标准：

第一，强固党的无产阶级的基础。要使党的无产阶级的意识加强，首先要扩大党的无产阶级的组织基础。到产业工人中去，建立强固的工厂支部，增加党的工人的成份，集中注意于全国产业区域的党的组织的健全，造成党的新生命，这是目前党的布尔什维克化主要的道路。

第二，发展党内政治的讨论，提高政治的水平线。各级党部都要尽可能地讨论一切党的政治问题，引导每个同志都尽量发表对于政治问题的意见。同时加紧党内的政治教育，提高党的理论水平。这是从积极方面消灭小资产阶级意识的正确的出路。

第三，党员的职业化。失业同志应当设法找到职业。党部应当帮助同志去谋职业，无职业技能的还要学习，特别注意到工厂中去做工，同志间也应互相介绍职业。要使党员不依赖党生活，而且能深入群众，把党的影响扩大到群众中去，同时能把群众的意见正确地反映到党里来，使党成为真正群众的党。

第四，支部生活的改进。政治的宣传鼓动，群众的组织，只有支部才能深入；日常的斗争，只有支部才能灵敏地领导。如果仅仅高级党部订几个空架子的计划，发布几种宣传的文书，而支部不起作用，党和群众终究没有接近的时候。所谓支部生活，并不是仅仅开会听政治报告、交纳党费就算完事，最要紧的是讨论当地的政治问题、工作问题。无论是一工厂、一学校、一军营、一农村、一街道，范围虽小，都有它的不同的政治环境与工作方法。要能把党的政策正确地运用，首先要了解实际的情形。这是每个支部的任务，每个同志的任务。必须充分执行这些任务，然后支部才能成为群众的核心，党员才能成为群众的领导者。

＊这是中共中央为贯彻执行中国共产党第六次全国代表大会决议而发布的《告全体同志书》的第四部分，这部分是周恩来同志起草的。周恩来同志当时任中共中央组织部部长。

