# 关于湘鄂西苏区发展的几个问题

中文马克思主义文库 -> 周恩来
关于湘鄂西苏区发展的几个问题
（一九二九年三月十七日）


　　去年年底卢冬生同志〔17〕来，得到你们的报告，当即进行了研究，写信作出答复，并将党的第六次代表大会〔16〕决议案中规定的我党总的政治路线、目前革命的形势以及游击战争的主要任务告诉你们。信系由冬生同志带回去的，想现在已经收到了。
　　兹又得你们去年旧历十二月初七日信，得悉你们不畏困难，带领同志及士兵忍饥耐寒地作了英勇的武装斗争，发动了不少的群众，并夺取了敌人许多武装，肃清了一些反动的民团，这些都是对的。
　　根据你们这次来信，中央尚有下列的指示：
　　（一）暴动问题。暴动是革命斗争发展到了最高峰的一种群众武装推翻反动阶级、夺取政权的直接行动。现在，在全国范围内，还没有一种直接革命的形势，故工农兵士贫民武装暴动夺取政权，在目前还是一个宣传的口号。在农村斗争中，自然不能说没有从日常生活斗争发展到武装斗争以至暴动推翻豪绅政权、建立农村苏维埃政权的可能和事实。海陆丰、琼崖、万安、黄安、醴陵等区域的苏维埃虽然失败了〔18〕，但土地革命在农村中的发动与深入，仍然使农民有由日常斗争走到武装暴动的需要。故农民暴动的直接行动，我们不但不应加以阻止，且应对农民自发的暴动极力加以领导，对农民的武装斗争极力加以扩大，使群众对于推翻豪绅乡村统治、建立农村苏维埃的观念日益明了与热望其实现，并使这一行动能渐渐与城市工作配合起来，得到城市的领导。这样的农民暴动才真是群众创造的，才较易持久，才能发动和影响更广大的群众来拥护，才能从群众的直接行动中建立起苏维埃政权。
　　假使你们所领导的群众斗争，统治乡村的豪绅地主还没到动摇恐慌的时候，还有大批武装力量来镇压你们，群众斗争还没转变到没收地主土地的要求，还只是一些日常生活的微小要求，甚至还没做抗债、抗租、抗粮的行动，群众的发动亦不广大，则这种斗争即便是有了武装冲突，仍然是一个游击战争的局面，还不是建立农民乡村政权的武装暴动。对此，你们应分别认清。
　　（二）游击战争。从建始与鹤峰两次战争〔19〕经过看来，你们发动了群众，镇压了豪绅，收缴了反动民团和警察的枪枝，这些都是合乎游击战争的原则的，是对的。不过，游击战争最重要的是要有组织性，要与群众有密切的联系。过去各处的游击战争，发生过一些不好的倾向，今后尚容易犯而应注意者：第一是脱离群众，使群众完全不了解游击战争的意义是为发动群众进行土地革命。第二是毁灭城市及大烧、大杀、大抢的倾向。这种倾向是一种游民无产者心理的反映，它足以妨害党在一般群众中甚至工人群众中的影响的发展，我们在党内必须极力肃清这种不正确的观念。当然农民群众打倒地主豪绅削弱反革命势力的斗争，党应积极去领导。第三是散漫而缺乏组织。至于游击战争的主要任务，是实现农民斗争的口号，削弱反动派的力量及建立红军，这些当然是你们能够了解而且正在进行的。关于没收土地问题，六次大会已将没收一切土地的口号，改为没收地主阶级土地归农民，这点你们在工作中亦须注意。
　　（三）游击区域内党的组织与群众的组织问题。我们游击队势力所达到的区域，自然必须发展党的组织，扩大群众的组织，推动并帮助群众的斗争，扩大我们的宣传。不过，在革命空气高涨的时候，很容易把一切组织公开，而不保留一部分秘密组织。及至游击队一走，一切组织随之瓦解，甚至一切革命的群众，都要牺牲于清乡军的白色恐怖之下。这无异于自己向敌人告密。过去，有许多地方的游击战争都犯过这种错误，所以你们必须特别注意。无论游击到什么地区，必须告知当地党部及当地的革命群众的组织，注意保存秘密，预备在红色势力被白色恐怖压迫时，还可以继续工作。
　　（四）游击队中党的组织问题及训练问题。你们现在在前委之下组织一个支部，管理全军党的组织，只要工作上感觉方便，也不是不可以的。在朱、毛军队中，党的组织是以连为单位，每连建立一个支部，连以下分小组，连以上有营委、团委等组织。因为每连都有组织，所以在平日及作战时，都有党的指导和帮助。据朱、毛处来人说，这样组织，感觉还好。将来你们部队建党时，这个经验可以备你们参考。此外尚应注意者，是红军中的党组织，仍须保存组织上的秘密性。至于训练问题，党的训练是加强军队纪律的，党的纪律也是帮助军队纪律无障碍地执行的。自然，红军的军事训练不能同于军阀军队的方式，施行强迫的和机械的军事纪律，应在党员以身作则的影响下，得到全体兵士的拥护。正因为这样，党的训练应多带教育性，党的组织要发展党员的自觉性，比较明了的同志应在思想上帮助尚不明了的同志，使一般同志咸能注意自觉地遵守纪律。党训练、教育同志，应用很浅近的理论，很容易明白的事实，提高他们的阶级意识，增进他们的革命情绪，使他们不但自己严格地遵守军队纪律，还能成为士兵的模范。对杨维藩的问题〔20〕，如你们所云，杨是犯了不少的错误，你们决定开除他的党籍是对的。不过以后训练同志，应特别注意教育方法。
　　（五）目前政治局面及你们今后的出路问题。目前，反动的统治阶级内部各派势力的冲突，正由酝酿而加紧而准备更大的破裂——军阀战争。关于目前政治局面的详细情形及我们应付的策略，中央有两个政治通告〔21〕，兹另抄录寄上，此地不多说。在这个政局之下，虽然可与你们一个很好发展的机会，不过你们的实力还很微弱，同时湘西、鄂西一带党的组织及群众的组织还缺乏基础，此时欲图大的发展，亦尚困难。你们来信说，红军拟向下游发展，将来以湘西之常德或鄂西之宜昌为目的地，这种计划还太大而不切实。目前所应注意者，还不是什么占领大的城市，而是在乡村中发动群众，深入土地革命。故你们此时主要的任务，还在游击区域之扩大，群众发动之广大，决不应超越了主观的力量（主要的还是群众的力量，不应只看见武装的力量），而企图立刻占领中心工商业的城市。
　　（六）发展的区域问题。鄂西、湘西发展区域究竟以何处为最好，这个问题，因为我们对湘西、鄂西的实际情形尚不十分明了，不能具体地答复。在原则上说，游击战争的发展，应该是向农村阶级矛盾与斗争到了更激烈的地方，党与群众的组织有相当基础的地方，以及给养丰富、地势险峻的地方为最宜。不过这些条件很难俱备，你们可斟酌实际环境，取这些条件最多者而选择之。
　　（七）派遣军事人才问题。你们军事人才缺乏，我们亦久想多派军事工作同志到你们那边工作，不过因为交通的阻碍，你们的驻防地又无一定，所以尚未派人去。以后有可能时，自然可以多派些人前去。


　　＊这是为中共中央起草的给贺龙同志及湘鄂西前委的指示信。



