# 在白色恐怖下如何健全党的组织工作

中文马克思主义文库 -> 周恩来
在白色恐怖下如何健全党的组织工作
（一九二九年三月二十五日）

关于山西党的组织，中央最近依据全国组织的变动，有一新的决定，特分项说明如下：

一、自“八七”会议〔15〕至今一年有半，在白色恐怖压迫之下，各省组织几经破坏，干部牺牲不计其数，而自首告密叛变的事亦由南而北渐渐遍及于全国上级党部。于是党的无产阶级基础日益削弱，党的组织日益脱离群众、隔绝社会，上级党部机关尤多形成空架子，完全与群众生活相隔绝。因之自中央至支部有层层机关，而工作效能极其微弱。有时且因党的上级机关一再破坏，各地党部唯一的办法，便是要求中央派人前往恢复。中央过去确也循着这个路线，派人至各省恢复组织。结果不但工作不能推动，新的关系不能发生，甚至旧的基础也日益缩小。工作既没做起，而机关已立，于是这个架空的组织，在社会中便极易为敌人发现，屡遭破坏，在党内因有了这些不落实际的机关，反足以助长同志依赖机关、忽视下层群众工作的错误观念。因此，中央特改定，各级党部的设立，必须其所管辖区域的下层组织已经建立起来，工作已有开展，然后才能由此种下层组织成立上层组织。嗣后凡是下层组织没有工作，或是破坏之后，主要的路线应是领导同志走入工厂农村社会中，寻找职业，深入群众，以恢复和建立党的组织。党的组织必须在此种基础上才能谈到恢复和建立。如果超越了这一基础工作而谈恢复，而先立一上级机关，则必致基础没有，徒然发生一些个人的关系，牵引这些同志围绕在党的机关左右，无职业，无社会关系。这种人越多，越妨碍党的下层基础的恢复和建立，于是这一机关越隔离群众，越隔绝社会，形成一架空而不合实际需要的组织。

二、依照上项说明的组织路线运用到北方党部、山西省委便成为目前最不必要的组织。如强行组织起来，必成为一空　；架子机关。汪铭同志〔22〕来信还主张调一批人到太原，结果必如上项所说，因为有了省委这一级空架子机关，于是又团聚了许多同志离开社会的关系而围绕在党的机关左右，这是最妨碍深入群众工作的。故中央决定，目前山西可不成立省委，先着手于地方工作的恢复和建立，山西工作改归顺直省委〔23〕兼管。

整顿地方工作的程序，应先从中心区域做起，如太原、阳泉、绛州、榆次、河东诸地（大同由京绥路方面建立关系）。目前第一步工作，便应先在这些地方寻找有社会关系的同志，建立党的基础。工作恢复开始，党员的线索并不求多，重在质量的选择，要有一人能得一人之用。主要的还在产业工人，即无产业工人之地，亦应注意寻找手工业工人及乡村中雇农贫民。知识分子，必求能在社会中生活活动的人，如与社会一无关系而又畏怯深入社会，不努力寻找职业，这种人从前即便是同志，现在找到也无甚利于党，这种人越多，反而越易使党停留在这些与社会隔绝的流落分子圈中，而不能建立社会基础——党的阶级基础。

假使在太原、榆次这类地方，仅只找到几个同志，最初便须以支部的形式开始他们党的生活。主要的工作自然须依照中央前次致山西的信去做。要能在群众中注意日常生活的痛苦所在，鼓动起日常斗争的要求和情绪，以发展到行动，并在这一艰难困苦的工作中训练我们的战斗员。假使我们能在每一地方，得到几个能深藏在群众中、能领导群众斗争的同志，则便是仅仅这几个同志，便是仅仅一两个工人支部，也会使这一些组织成为山西工作发展的核心。要在一个地方有了几个健全的支部后，再成立地方党部——县、市委的组织。务使这一组织，能从几个有群众基础、有社会关系的支部基础上建立起来，县、市委负责同志也要多由在业同志选出担任，这样才能避免空架子机关的毛病。在县、市委没有成立前，几个支部并存时，可指定一个较健全的支部为特支，指导其他支部的工作。中心县、市委须指导其他邻近县份。

三、根据上述的办法，目前山西实无集中一部分同志到太原的必要。便是太原的工作，也只能设法在当地找有社会职业或下决心找社会职业的同志，去开始恢复党的工作和建立党的基础。

顺直省委应根据此信所指示的办法，函知汪铭同志至天津面商；依指示的区域，速即计划如何用巡视方法去寻找各地在业的同志，开始恢复中心区域的工作。汪铭同志得此信后，亦应速至顺直省委处面商。　　

河东有七县范围〔24〕，工作不可忽视。在目前春荒期中，主要的斗争固在扩大借粮分粮运动，但斗争的对象宜多领导着向地主方面进攻，尤其重要的是不要使农民斗争专停顿在这一运动上，宜从抗债分粮运动发展到农民反抗地主的日常斗争。只有斗争的范围日益扩大，斗争有继续不断的小胜利，然后农民运动才会深入，土地革命的阶段才得在北方开始进行。这一点很重要的指示，望你们于指示河东工作时特别注意。

对士兵运动和土匪、民团等工作，也望依照中央的工作计划指示河东特委。

＊这是为中共中央起草的给顺直省委并汪铭同志的指示信。

