# 中共中央给红军第四军前委的指示信

中文马克思主义文库 -> 周恩来
中共中央给红军第四军前委的指示信
（一九二九年九月二十八日）


四军前委并转全体同志：
　　陈毅同志来〔32〕，详谈一切。中央于其口头及书面报告后，决定给前委以下列之指示：

目前军阀混战的形势
　　中国政局自蒋桂、蒋冯战争〔33〕后，表面上蒋系的南京政府得了胜利，资产阶级的政治影响加大了些，但实际上一切引起战争的矛盾并未解决，且日益加深地向前发展，因此反蒋的军阀混战又由酝酿至于爆发。美帝国主义与中国定了航空合同〔34〕，英帝国主义定了中英海军协定〔35〕，日本帝国主义满蒙计划〔36〕的急进，各帝国主义都努力在华的军事布置，这都表示帝国主义间互相冲突的尖锐化。中东路问题〔37〕是帝国主义联合进攻苏联的露骨表现，亦是各帝国主义在开始战争前之首先要解决的问题。帝国主义冲突的激烈成了军阀混战的主要动因。再则蒋桂、蒋冯战争后，并没能在这些战争中获得什么实际利益，固然一方面削弱了封建势力的一部分，但另一方面的封建势力却又抬起头来，这乃资产阶级本身力量微弱必须拉拢封建势力以自固的必然命运。资产阶级利用封建势力去打击封建势力的这种企图，不但不能解决两个阶级的矛盾，而且成为军阀混战的又一动因。又中国军阀因数个帝国主义的唆使，中国经济破产的加速，庞大军队需要财源维持，因此为各自争夺地盘与饷源又推动着军阀混战的危机。上面这三种矛盾，是军阀混战的动因，亦是军阀混战所不能解决的。每一次混战只有使这三种矛盾加深。目前反蒋的军阀战争〔38〕就是上次蒋桂冯混战的继续，这次混战爆发后，也当然要继续发展下去，除工农兵暴动的力量而外，绝没有第二种方法可以解决引起军阀混战的各种矛盾。这是我们应该坚决认定的。
　　目前蒋系政府把持南京反革命政权，对外得了帝国主义承认，想独揽出卖民族利益的特权，对内把持长江下游财权及重要军械制造所，自然要成为众矢之的，造成全国其他军阀各派的反蒋联合。蒋系除浙江比较统一外，其余各省都有着反蒋的势力。蒋的嫡系军队号称九师，此九师有些还系改编别人的部队，同时有改组派〔39〕从中活动，所以亦包含有反蒋的分子。这些，是蒋本身的弱点。在反蒋方面以汪陈派的改良主义〔40〕的理论为旗帜，但没有一个中心势力。南方各省散布着不少的反蒋力量，在表面上可以为改组派利用，但实际上还各怀鬼胎，如张发奎、俞作柏都想攻下广东，而彼此则不相下。冯、唐、朱诸系军阀〔41〕则想攻下南京、武汉，而本身的利害又各冲突。北方阎、张两派〔42〕则自知无力统治南京，故始终有在北京建立中央政权的企图，对于拥护改组派便不十分积极。同时各派部下都有被蒋收买之事，阎部下另成系统与蒋不无关系。奉张内部有新旧之争〔43〕，新派自杨、常〔44〕死后势力大衰，张学良对于派已不能如意支配，旧派则忠顺于日本帝国主义，因此入关的企图十分积极。中东路问题发生后，显然与蒋有冲突。这都是军阀间不能协调互相排挤的实况。张发奎事件〔38〕发生，显然是改组派反蒋运动开始爆发的第一声，武汉战争、两广战争都有扩大为全国混战的可能。如蒋得一时胜利，混战局面并不能因之消灭，且必然要继续发生；如改组派胜利，则小军阀割据局面更要加多。军阀战争的目的只是争夺反革命政权以便于出卖民族独立利益，夺取地盘以加紧剥削工农，反蒋与护蒋两方皆是如此的。党在军阀混战中，应该采取失败主义的策略，发动广大群众，反对军阀混战。这一工作须与群众日常斗争相联系。这是走向以工农兵暴动的力量消灭军阀战争的正确道路。
　　在军阀混战中，我们不可过分去估量，专空想一些大的斗争到来而忽略许多切实的群众日常斗争工作，尤其在红军中更要注意到敌人的“会剿”。应付敌人“会剿”是红军经常应注意的问题，不可因为军阀混战爆发，便松懈起来疏忽起来，尤不可因军阀混战暂时休止，便恐慌起来。我们应认清军阀“会剿”红军，有其必然要遇到的困难，常常使“会剿”不能完局反而便利于我们的发展，但并不因此便使我们不注意“会剿”，不下决心去与敌人作艰苦斗争了。前委过去尝根据红军近邻军阀的行动来判断整个统治局面的稳定与动摇，这样的分析是不对的。前委要十分注意纠正军事同志以红军为革命本位的狭隘观念。根据红军部分的环境去观察整个革命形势，这是万分不够的，而且一定要陷于错误。军阀对红军曾三次“会剿”，每次都含着两方面的意义：一面固然是在共同进攻革命势力，一面却又是军阀为了准备自己战争，必须先求解决红军以固后防，过去湘、赣、粤三省“会剿”以及最近闽、赣、粤三省“会剿”皆是如此。最近蒋派刘和鼎入闽〔45〕，固然为的进攻朱、毛，但还有一个解决张贞〔46〕的任务，因此闽军每一部分都互相戒备，对于进攻红军反互相推诿起来。粤军在二陈冲突〔47〕、两广冲突的形势下面，虽然有入闽部队，现亦急急撤退。金汉鼎〔48〕部自朱培德失掉江西地盘〔49〕、王均〔50〕调蚌埠后，独处赣南，此次又参加改组派运动，对红军几月来皆采取防御性质。这就是三省“会剿”的实际。红军应该采取坚决斗争的前进精神，认识整个的敌人的形势，团结广大群众来打破敌人的“会剿”，不要存丝毫退却苟全的犹豫念头。红军存在于反动政局走向崩溃及土地革命向前发展的过程中，中国的地势辽阔也是一个条件，从你们过去的艰苦经验中就可以证明。先有农村红军，后有城市政权，这是中国革命的特征，这是中国经济基础的产物。如有人怀疑红军的存在，他就是不懂得中国革命的实际，就是一种取消观念。如果红军中藏有这种取消观念，于红军有特殊的危险，前委应该坚决地予以斗争，以教育的方法肃清。在目前反动政局走向崩溃过程中，在全国革命高潮未来时，红军此时主要地采取粤、湘、赣、闽四省边界游击的策略是对的，但要注意使这四个区域的赤色势力联系起来。红军尤要加紧帮助发动群众斗争以取得广大群众拥护。有了广大群众在红军的周围，红军的一切困难及本身发展便将较顺利地得以解决。

红军的根本任务与其前途
　　目前红军的基本任务主要的有以下几项：一、发动群众斗争，实行土地革命，建立苏维埃政权；二、实行游击战争，武装农民，并扩大本身组织；三、扩大游击区域及政治影响于全国。红军不能实现上面三个任务，则与普通军队无异。红军第四军两年来对于上述任务克尽了一部分，在全国政治局势中有极大影响，这证明了统治阶级在乡村力量的薄弱，证明了革命势力的存在与发展。红军四军有此种伟大意义是我们不能否认的，继续努力下去，将必然要成为全国革命高潮的动力之一，这是无疑义的。红军四军的同志务要明了自己的任务的重大。
　　至于红军是否应该固守一个地区的割据，这个问题你们在行动中常常碰见。要知在统治阶级政权未崩溃以及革命高潮未到来的时期，红军应该是采取经常游击的政策，若停留在一个地区，或企图固守一个地带，求其继续存在，这不但不可能而且必然陷于失败。过去罗霄山脉政权的经验告诉了我们。在一省或几省以上的政权就不然，因为它有一个比较足以维持的经济基础，自然有可能作为一个发展或保持的根据。总之，农村的政权或游击队应该是一个斗争的单位，实行游击四向发展的策略，保守必然要失败。反之，预定一年内夺取江西全省政权的决定，也是错误的。

红军发展方向及其战略
　　红军发展的方向，应该向着群众有发展斗争可能的地方，去扶助其发展，使当地的革命斗争深入。若经常停滞在边境，在缺乏斗争的某些边境，将减少红军的政治意义。对于敌人军事力量空虚地带或乡村中白色势力范围，应实行游击，以驱逐反动势力，发动群众斗争。对于较小于我的敌人，应该坚决地去歼灭他，非如此不能扩大本身及群众武装，绝不可有保存实力观望时局的等待倾向。固然亦决不应以较小兵力硬与较强之敌人作殊死战，致非牺牲偌大兵力，不能有胜利把握，而敌人又可从容退去，丝毫不能扩大红军武装，这种打硬仗的办法是无益于游击战争的，但这决不能动摇围缴敌人武装以扩大自己的必要信念，红军不从斗争中锻炼自己绝不能发展。我们有了避免战斗的观念，必然要错过许多可以使自己发展的良机。这是关于红军发展的主要几点，是最值得注意的。
　　关于红军战争中之分兵与集中问题，过去四军各级党部讨论中间曾有分散红军，分兵后不必要有联络，集中怕目标太大等不正确观念。分兵与集中只是某一个时期中工作方式的利便问题，绝不能把红军四军分成几路各不相属的部队，这样就是分散而不是分兵，或者把红军四军分小，化成无数的游击队而不相联属。两者皆是取消观念，皆原于对政局的估量不正确，恐惧反动势力稳定，红军会被消灭，才发生减少目标各个自了自己的右倾思想。这种倾向于红军发展及对全国政治影响有极大危险。红军四军此时的主要任务是如何去实行游击以求本身的扩大，如何集中力量去实现党的政治口号以发动群众斗争。分兵游击集中指导是不可移易的原则。分兵时应密切联络互相策应，应防敌人各个击破。红军四军两年来集中奋斗，渡过各种难关，此种艰苦的经验不应为全体同志忽视。至于全军如集中行动，当然有一些困难，如行军、宿营、给养等之不轻便，但这大部分是一些属于技术上的困难，绝不能因此而取消集中指挥的必要条件与忽视了对于全国政治影响的伟大作用。
　　关于一般战术问题，如前委来信所提出之波浪式推进，兜圈子以及十六字诀等办法，应就实际情况去运用，不能定为一个原则。前委在两年奋斗中已有不少经验可以运用，中央在此不作机械的指示。

红军与群众
　　前委在过去忽略了所到地区之群众的日常斗争。红军本身是一种阶级的集聚力量，所到地区豪绅等多已闻风逃窜，群众在军事力量掩护下勇气倍增，一切行动自然是政治的或军事的，但党的指导绝不要忽略群众日常生活上许多未解决的问题。全国有苏维埃区域的党均忽视了这个问题。红军四军经过许多群众未曾发动的地方，不要只是提出一般的政治口号，应该细心去了解群众日常生活的需要，从群众日常生活斗争引导到政治斗争以至武装斗争。这种斗争才是群众本身所需要的，才不是单纯军事力量的发动，才不是少数个人英勇的硬干，才会团结广大群众在党的周围。对于地方党部工作之帮助，特别要指示这一点。
　　红军到一地区不要只是找地方党部，应该与地方的群众组织工会、农会开联席会，发生密切关系。在政治上，在宣传上，在斗争上，都要与工农会协议共同去做，红军不要单独去干或者只是发命令，然后才可以扩大红军在工农中的政治影响，提高群众对于自己组织的信仰与效能。如群众尚未组成工农会，则更应帮助群众建立自己的群众组织。
　　红军对于苏维埃政权应帮助群众去建立并扶助其工作之发展，从一切斗争中帮助群众建立自己政权的基础。要提高对农会的信仰，一切问题都拿到农会去解决，做成转变为苏维埃的基础。例如一切政治布告等要与农会共同联名发出，增加群众组织的威信，使群众相信自己政权的力量。
　　红军的群众工作，四军过去有相当努力，兹特别指出重要几点：第一，关于调查工作应切实去做。过去有许多调查成绩，因没人统计以致放弃，甚属可惜。前委应指定专人去做，这个工作做得好，对于了解中国农村实际生活及帮助土地革命策略之决定有重大意义。第二，关于宣传工作务求其扩大，不要只限于红军游击区域以内，可用寄信方法及于大都会的群众，则影响更大。第三，关于组织工作，如反帝组织、拥护苏联组织、雇农工会及其他的平常有助于革命的临时组织都很重要，要用各种方法去建立。第四，关于肃清反革命工作要经过群众组织来执行，才有群众的意义，而且这一工作要特别加深。第五，关于筹款工作，亦要经过群众路线，不要由红军单独去干。此时固然做不到由群众组织来担负红军给养，但在筹款时要用群众组织去执行才有意义。党与红军有时可斟酌情形在群众中募捐，尤其红军的给养，更应在群众中举行盛大的募集以扩大红军影响。关于经费支配亦要顾及群众组织，与其共同支配，一切经费的开支应多用在群众工作之支付上，绝不要大半作为党费开支，养成党之腐化。第六，对于武装工农问题，四军同志中尚保存有许多不正确的观念，以致工作没有做好。好枪不发给地方，坏枪尽数送给农民，把群众与红军分做两个东西，有根本不相信群众力量的危险。须知红军与工农的武装力量是相成的而不是相消的。固然有些地区群众斗争尚未起来，先发给以武装不能有多大作用，或者红军枪不够分配时，是可以暂不发给的，但需要发给时，一定要纠正过去的不好倾向。同时，派人去担任农军的训练，亦甚重要。

红军的组织与训练
　　（1）红军扩大问题。红军扩大与红军生存问题有莫大关系。扩大红军，在红军中在群众中应该是一个普遍而深入的口号。扩大的路线，应该从广大群众斗争中去取得帮助。红军所到区域，应举行扩大红军的宣传大会，鼓动工农群众自动参加红军，同时，如能有机会收缴敌人枪械时，不要轻易错过。
　　（2）红军的成份与来源。红军的来源只有收纳广大的破产农民，此种农民固然有极浓厚的非无产阶级意识表现，但只有加强无产阶级意识的领导，才可以使之减少农民意识，决不是幻想目前红军可以吸收广大工人成份来改变红军倾向的。
　　（3）组织系统与编制。红军由前委指挥，对外用军部、政治部号召，目前是可以的，但到了各苏维埃区域扩大时，则必须召集各地苏维埃代表会成立几省边境苏维埃政权，公开指挥红军，免除党军的毛病，更可以使群众认识红军是自己的阶级军队。这一个办法目前不必马上执行，以免徒为一个空心机关，至少应在闽西、赣南、东江三地区域工作扩大能开联席会时，再设法执行。关于红军编制，最要紧的是使之能适合于游击动作，指挥单位不要过多，军事组织及名称不必拘于一个固定形式。
　　（4）党代表制度。党代表名称应立即废除，改为政治委员，其职务为监督军队行政事务，巩固军队政治领导，副署命令等。军政治委员可由前委书记兼，军政治委员可不兼任政治部主任。
　　（5）兵委的组织。四军中兵委过去有成绩，其组织路线也很正确。其职权规定为监督军队经济，参加军队管理，厉行士兵政治教育，做群众工作，与军事机关的关系用报告建议而不能直接管涉。发生特别事件，政治委员有解散兵委之权；兵委开会政治委员列席为顾问等。这些规定虽然较之俄国红军兵委权力扩大得很多，但在目前红军游击时期是可以适用的；不过要注意军队中民主化要有限度，否则于斗争是有害的。
　　（6）政治工作。军与纵队设政治部，营连只设政治委员，这是可以的，其任务为对内管理政治教育，对外作政治宣传以至管理地方政务，发动群众斗争，扶助群众组织等。
　　（7）军事训练。红军的军事技术要特别注意，决不应附和不爱严格训练与组织的农民意识，红军有好的军事技术，有严格的军事训练，才能加强自己的战斗力。
　　（8）军队中民主化问题。红军不是与工会农会同等的组织，他是经常与敌人在血搏状态中的战斗组织，他的指挥应该集中。固然，对红军的兵士应该以政治教育发动他们自觉向上，但绝不能动摇指挥集中这个原则。军队中民主化只能在集中指导下存在，并且实行的限度必须依据客观条件来决定伸缩，不应漫无限制，以妨害军纪之巩固。
　　（9）妇女参加红军的问题。对于革命妇女可引导她们参加农村斗争，不必加入红军，四军过去对这个问题已经解决了。但对于农村的妇女运动，红军应扶助之。
　　（10）红军的纪律与处罚。应做到使士兵自动守纪律，以群众的力量与影响来裁制违犯纪律的人，坚决地废除肉刑。至于军事上所规定之一般纪律，可以斟酌实施。

红军给养与经济问题
　　（1）没收地主豪绅财产是红军给养的主要来源，但一定要经过群众路线，在最短促时间中也要注意这一工作方式的运用。
　　（2）筹款标准，主要的是不要侵犯工农及小有产者的一般利益，这一点，四军执行得很好，可应用到其他游击队伍中去。
　　（3）募捐亦是红军筹款的一个办法，四军要应用这个办法，可以在群众中组织募捐委员会，特别要向富农及中小商人募捐。
　　（4）对中小商人及富农态度。我们为实现党的政纲所规定及为工农经济流通与贫民利益，在城市不举行经济没收，这是对的。城市的政治没收应该执行。对富农及中小商人要向其募捐，并要防止其反动。
　　（5）红军给养及需用品问题。红军中废除军饷，只发零用钱与吃饭钱，这是对的。对于需用品可渐次做到由群众路线去找出路，红军自己办固然好，但同时要能由群众供给与募集才能建立红军与群众的更密切关系。
　　（6）经济组织。对红军的给养费用可由兵委审查，其他特别开支不必要由兵委审查，将来应由群众政权组织决定和审查。

红军中党的工作
　　（1）党的组织系统可保存现在状态，前委委员不要过九人，前委下面不需要成立军委。党在军队中采取秘密形式，党的机关设在政治部内，党的机关的人员不要过多，要尽量利用群众组织中的人做事。一般的可以不必设立营委，营部可成立直属小组，一营单独行动时，可委托营的支部来指挥，但此点前委可斟酌采用。
　　（2）党的工作路线。党对军队的指挥尽可能实现党团路线，不要直接指挥军队，经过军部指挥军事工作，经过政治部指挥政治工作。以后成立上层政权，则组织党团，经过党团指挥之。党的系统，军事系统，政治系统，要弄清楚。
　　（3）集权制问题。党的一切权力集中于前委指导机关，这是正确的，绝不能动摇。不能机械地引用“家长制”这个名词来削弱指导机关的动力，来作极端民主化的掩护。前委对于一切问题毫无疑义应先有决定后交下级讨论，绝不能先征求下级同意或者不作决定俟下级发表意见后再定办法，这样不但削弱上级指导机关的权力，而且也不是下级党部的正确生活，这就是极端民主化发展到极度的现象。前委在前次党的争论问题，即表示这个弱点，这是一个损失。
　　（4）团的小组。团应该成立小组，现在指定成年人做青年工作即以之为团的小组，这个办法是不好的。红军中团员与党员应有划分，连支部中设CY〔51〕小组属于连委管理。纵委前委中设青年工作科，表面归政治部，计划并指导CY小组如何在群众中做青年工作。前委更须帮助所到地区的CY工作。
　　（5）组织上的争论问题。党管一切这口号，在原则上事实上都是不通，党只能经过党团作用作政治的领导。目前前委指挥军部、政治部，这是一个临时的办法。前委对日常行政事务不要去管理，应交由行政机关去办，由政治委员监督，前委应着眼在红军的政治军事经济及群众斗争的领导上。一切工作归支部这个口号是对的，是作经过支部去工作的解释，但不是与党的民主集权制相对立。
　　（6）纠正一切不正确的倾向。红军中右倾思想如取消观念、分家观念、离队观念与缩小团体倾向，极端民主化，红军脱离生产即不能存在等观念，都非常错误，皆原于同志理论水平低，党的教育缺乏。这些观念不肃清，于红军前途有极大危险，前委应坚决以斗争的态度来肃清之。
　　（7）成立边界特委问题。在几省边界工作可以联系，能够指挥时，可以成立特委，目前则尚不需要。如今后工作发展，前委即可负责特委的责任，届时再报告中央指定名单，或开边界各县代表会议选定。
　　（8）前委在红军经过区域应与地方党部有密切联络，一切地方政治问题应与地方党部开联席会议决定。如所经地区无党的组织时，前委应尽可能从发动群众斗争中帮助建立地方党部组织。

红军目前的行动问题
　　在军阀战争开始爆发之际，红军应以全部力量到韩江上游闽、粤边界游击，以发动群众斗争。至两广军阀混战爆发东江空虚时，红军可进至梅县、丰顺、五华、兴宁一带游击，发动广大群众斗争，并帮助东江各赤色区域的扩大，相机围缴敌军枪械，集中东江各县赤卫队建立红军。如两广军阀混战成相持局面而且蔓延及于全国，红军即可向潮汕方面游击，建立苏维埃政权，并向惠属方面逼近。如蒋系军队失败，红军应位置于粤、赣大道左右或其败退所经之路围缴其枪械。如军阀战争结束较快或蒋系军队得胜时，红军仍留粤、闽、赣边界一带游击，以发动群众。
　　凡红军一切行动务要避免单纯的军事行动，要与群众斗争取得密切联系。前委对赣南、闽西的游击工作亦要同时注意，要与该地方党部有密切联系，然后才能使其与红军四军及东江斗争相策应。
　　凡此各项，概指其大要，详细解释及具体办法已向陈毅同志面谈，当由其口达前委及全军同志。
　　专此。
革命的敬礼！
　　中央


　　＊这封信是陈毅同志按照周恩来同志多次谈话和中共中央会议的精神代中央起草并经周恩来同志审定的，收入本书时个别段落没有选入。



