# 托洛茨基反对派在中国发生的原因及其前途

中文马克思主义文库 -> 周恩来
托洛茨基反对派〔52〕在中国发生的原因及其前途
（一九二九年十月）

中央第四十四号通告〔53〕上说：固然我们不必夸大反对派〔31〕在中国党内之政治上组织上的作用，但是他们的活动情形与反党现象的发展，实不容许党丝毫忽视。

反对派在中国发生的主要原因，是中国大革命之失败与新的革命浪潮之复兴，存留在党内落后的小资产阶级“同路者”形成了反对派发展的基础。有人说，反对派在中国的发生是因为有了“莫斯科回来的学生”。这是错误的，他们只是起了反对派的介绍作用。现在，我们指出反对派发生的几种主要的客观的原因。

第一，南京政府在初成立时，很注意如何引俄国反对派到中国来，以分裂中国共产党。托洛茨基反对派这个“宝贝”不但为欧洲的资产阶级所利用，即中国的统治阶级也一样地看上了。在联共的反对派坚决地固执他们的路线时，欧洲资产阶级即非常之注意，想利用他们分裂联共的组织，破坏联共的正确路线。在中国，胡汉民〔54〕、戴季陶〔55〕、周佛海〔56〕，都企图借着宣传反对派以分裂中国党。中国的统治阶级恨不得抓住中国党内的这一工具，以达到消灭中国革命领导者的目的。中国的政治环境的确容许反对派在中国活动。这是反对派在中国发生的第一个客观原因。

第二，在革命失败之后，必然有许多失败的情绪，引起许多争论的问题。俄国在一九○五年以后，德国在革命失败后，都有过这样的情形。中国大革命失败后，亦是如此。中国党自“八七”会议〔15〕以后，对于机会主义的纠正，在组织上有相当成功、但在理论上思想上的斗争，并未完成，直到六次大会〔16〕，才有相当成功；然党内种种不良的倾向，以及大革命失败以来的不同的政治倾向，尤其是机会主义的倾向，还都是待机而动。这是中国发生反对派的第二个原因，也就是所以形成中国党内机会主义——反对派结合之思想上组织上的根本原因。

第三，中国党的党内生活，到现在还不能说是完全健全。虽然在组织上肃清机会主义，引进工人分子入党，但尚未把支部生活坚固地建立起来。因此，党的生活上，常发生动摇的现象。党的正确路线还未得到有些支部全体热烈的讨论，因之，党的政治路线在组织上遂尚未得到完全巩固。有些支部对某一问题，常不能在正确路线下予以回答，常因某一问题不能回答而表现动摇。在上海，有些中心的产业支部并不巩固，有些产业支部非常缺乏政治生活，因此，斗争胜利了，支部就活跃；斗争失败了，支部就消沉，甚至有瓦解的。这表明政治路线还没有得到组织上的完全巩固，不但反对派可以借此活动，即机会主义者亦容易去活动。这是第三个客观原因。

第四，大革命失败以后，许多国共合作时代的动摇分子，有脱离工作的，有坚持地方观念的，有固执自己错误的，这些在组织上并未克服。他们专以个人的小问题闹无原则的纠纷，而反对派就抓住了这些不满意党的路线的分子，利用这种无原则的斗争，以进行其反党的活动。这是第四个客观原因。

尽管过去没有发生过反对派的活动，然而有了这四个原因，就必不可免地使中国有反对派暂时活动的可能。自然直接的原因，还是回国的学生与机会主义的复活。

至于托洛茨基反对派活动的策略路线，我们可以看出有下列四点：

第一，必然不可免地要与统治阶级勾结。《新生命》〔57〕已经登过关于反对派的文章。将来反对派更要利用统治阶级的宣传机关，以进行其帮助统治阶级反党的活动。如果在党内斗争中失败了，他们必然会整个卖给统治阶级。这是必不可免的前途。

第二，在一切当前实际问题上表现他们的反党路线的宣传与活动。他们在“五卅”〔3〕纪念时，宣言号召同志向党斗争，要比反帝国主义斗争更重要，客观上毫无疑义地是帮助敌人。“八一”示威〔58〕，他们又认为是盲动主义，反映出许多失败的情绪。在论调上表现出极右的悲观的取消主义。

第三，利用某些不健全的支部生活，以实行其停留在支部内活动的策略。他们借着停留在支部内，以动摇下层群众，并专门找斗争失败的支部，专利用失败的事实，以攻击党的路线。当斗争困难时，反对派在宣传上可以说出极左的口号，如“没收工厂”，以使工人阶级孤立，并引导工人群众幻想未来的天国而忽略了目前斗争的实际意义；反之，在实际问题上却又提出极右的策略，使工人支部走到无出路的消沉状态。

第四，与中国的机会主义者结合。这些机会主义分子因为固执自己的路线，现在既不能深入群众，又不能不找一新的政纲，以掩饰自己的错误。这样，反对派的政纲，正好在掩饰自己过去的错误上，在口头上“左”的革命口号而实际上右的革命形势的估计与策略上，恰恰脾胃相合，于是就被他们利用了。而反对派的策略，也正是要利用这些分子帮助他们进行反党的活动。机会主义者与反对派在“惺惺惜惺惺”〔59〕的情形之下，便结合起来了。

此外，托洛茨基反对派抛开原则，专门利用些小的问题小的纠纷，进行非事实的毁谤与有意的造谣诬蔑，企图用这些卑劣无耻的手段以破坏同志对党的指导机关的信仰。这除了帮助敌人破坏革命的指导者以外，简直没有任何意义。

在上海、香港、北方，都发现有反对派的活动。他们在组织上对党是秘密的。惟其如此，就更应该将这一问题提到下层去，指导同志们讨论与坚决地肃清一切机会主义——反对派的活动。反对派有些并不公开表示自己的意见，有些我们已知道他们有反对派的倾向，有些尚不知道。因此，这一问题必须提到支部中，运用这一机会教育同志，树立党的正确路线的基础。务使每个同志认识以正确的路线同不正确的路线斗争之必要，使党的正确路线得到组织上的巩固。所以，除了组织上的制裁之外，思想上理论上的斗争是绝对必要的，这是目前巩固党的很重要的武器！

＊这是在中共中央直属支部干事会上所做的报告。

