# 关于武汉工作问题

中文马克思主义文库 -> 周恩来
关于武汉工作问题
（一九三○年九月四日）

第一，我们要决定武汉的工作计划，不仅要从客观形势上去了解目前工作发展的可能及其趋势（这一点我们已无可怀疑与争辩），更其重要的还是目前我们究在何种主观的可能上去发动工作。依据你们许多来信，都证明在今天的武汉，我们的主观力量的确还是很弱。严重的是，党员团员及赤色工会〔60〕会员总共不出三百人，支部生活多数没有，主要部分的产业工人组织微弱到万分，各级党部的关系非常隔阂。尤其严重的是，下层群众的实际情形还不能反映到指导机关中来。在这样模糊的主观情形之下，要想定出一个切实而具体的计划，是万万不可能的。因此，钧兄〔61〕几次来信都说，不能知道下层群众情形是最苦痛的事。中央因此更加严重指出：如不能知道下层群众实际情形，不仅工作计划定不好，便连你们所说的政治影响的扩大，群众革命情绪的高涨，也还与实际行动离着很远，因为这中间还找不出党的领导作用与组织力量，而没有这些，是不能达到革命的胜利的。所以你们的第一个任务，便是要将武汉工人群众的实际生活与要求弄清（不仅是先进的分子的要求，最重要的是广泛的、落后的群众的一般要求都要计及）。不仅要注意一些先进勇敢分子或是少数干部所说的“现在不是谈工钱的事，而是大干问题”，“现在只有拿武装来干，才有用处”等等，而更加要注意的，还是大多数群众现在还没有人领导他们去作任何的斗争，大多数群众现在还没有造成可以干的组织力量。即使这种只要大干不要小干的情绪是大多数群众的，我们也还不能说，大多数群众有了这种情绪，革命便可达到胜利。相反，我们必须从这样的观点去了解，即群众不愿小干只愿大干的情绪，是对于极端白色恐怖的反感，是对于广大农民战争发展的同情；从这种反感引导到坚决的斗争上，还须我们做极艰苦的工作，从这种同情引导到工人群众领导和参加农民战争的决心上，还须做很多的宣传工作与组织工作。工人阶级只愿大干，而没有可以大干的斗争力量和组织基础，尤其是没有党的坚强领导，大干是绝对不可能实现的。要造成大干的斗争力量和组织基础，不是仅仅以党的政治口号去动员便可以造成的，尤其不是仅仅以大干的口号即是以武装暴动的口号便可以造成的。少数分子的要武装，多数群众“普遍地希望红军来到武汉，一切事情都好了”的观念，这不但不是群众决心要大干的表示，且反而是依赖红军的怯弱表示了。所以斗争力量和组织基础必须从日常斗争、罢工与示威之不断开展中培植起来，以联系到党的政治口号。绝对不是没有这些日常斗争、罢工与示威之不断开展与锻炼，斗争力量与组织基础便会突然存在的；也绝对不是没有这些日常斗争、罢工与示威之不断领导与发动，党的领导便会自然巩固的。这是你们决定一切策略与工作计划的根本观点，望你们对这一点多加注意。

第二，因为你们在主客观上有了上述的缺点与困难（缺点是你们注意力偏向一方，困难是对下层情形还很隔膜），所以你们所定的“目前党在工人中主要的策略”还是偏于原则，还是偏于在“准备武装暴动”本身上做文章，而没有注意于策略运用的实际意义，没有注意于在武汉特殊情形下做一些具体办法的规定。所以你们决定的几条办法，与中央通告无异，可以适用在任何地方。现在，我们指出这几条办法中的缺点与错误。

第一条，你们说：“党只有在政治上去动员，才能迅速夺取广大工人群众去实际组织武装暴动。”这样的解释，显然将日常斗争与准备武装暴动对立起来。这样的解释，显然忘记了发动群众的部分的政治经济要求以联系到党的政治口号，正是积极准备武装暴动中争取广大群众的最基本的方法。

第二条，你们主张由省总制定武汉工人及各业工人的要求的纲领来组织同盟罢工，这是绝对不够的。假使没有各厂各业的工人日常斗争的发动与领导，假使没有不断的各部分工人的罢工与示威，而只注意于总的纲领的号召与鼓动，总同盟罢工是不会突然而至的。尤其重要的是失业工人中的工作。特别在现在武汉形势下，失业工人的数量一天一天增加，在准备武装暴动中，他们更将成为主要的动力之一，故你们必须加重此种工作。

第三条，你们将“参加黄色工会去争取群众”与消灭国民党工会的策略对立起来，这更是不妥的。如果国民党工会有群众，我们还是要参加进去，去争取群众大多数，直做到推翻这个工会为止。如果它是没有群众的，则我们便根本不必去参加了。不能因为现在黄色工会一天天国民党化与法西斯化，就认定对黄色工会的策略已根本改变。这是不实际的，而且会使一般党员机会主义地去了解过去加入黄色工会不是要消灭黄色工会〔62〕的了。

第四条，猛烈地发展赤色先锋队〔63〕是对的，但如果离开群众斗争，离开组织广大群众，专门等待武装暴动，拿枪就干，与群众日常斗争、实际生活一点也不联系，则赤色先锋队就会变成招兵式的武装别动队的组织。这不仅不能成为群众的先锋，而且必将离开群众很远，成为孤立的组织。现在上海就有这种危险现象发生。

你们累次来信提到武器的事，假使以此为中心来团结赤色先锋队，这将失掉赤色先锋队的群众性与夺取敌人武装推翻国民党政权的决心。在这一工作上，你们必须注意到兵工厂工人中的工作。武装要从敌人方面想法子，这是武装工人的根本出路。

第五、第六两条，你们提到党与团的发展，丝毫没有联系到斗争问题。这将埋伏着一种危险倾向，即是在猛烈地为准备武装暴动而发展党与团的组织时，将助长一些机会主义分子接受“左”倾的空谈武装暴动，而不去领导群众实际斗争的危险倾向。上海已有这种倾向发生，武汉必须预先看到。必须知道，在只谈武装暴动只要枪来训练而不去领导群众日常斗争，说只有大干不要小干的动员之下，也同样会聚集一些机会主义分子在“左”倾的形式上表现出来。

第七条，你们提到产业委员会的工作，你们必须注意，产业委员会是一种临时的组织，是要聚集党内一些工运干部去推动与组织产业的赤色工会的。当产业的赤色工会以及各厂的分会已经吸收群众正式成立起来的时候，产业委员会便须立刻取消，退居党团地位，取消其在党内的直接指挥系统，推动各级工会发挥其独立的工会作用。所以产委只是党发展赤色工会的一种动力，赤色工会一成立，即须集全力于工会的独立系统的运用，绝对不容许再以党的产委来代行赤色工会的指挥职权。现时上海在这一组织方式中也正犯着使赤色工会退居无权地位的错误，望能引起你们预先注意。

第八条，你们提出加强反右倾的斗争是对的，同时“左”倾的危险也在党内继续发生。你们应坚决反对这一观念：“左”倾会比右倾好些，在现时只怕右倾不怕“左”倾。要知右倾会障碍革命与断送革命，而“左”倾也同样会障碍革命与断送革命的。自然，在目前右倾还是党内主要的危险〔64〕，尤其是在一般旧的干部分子中。

除了你们决定的八条外，还有行动委员会的组织问题。过去将党与团合并在行委组织之中，不再存在团的独立组织系统，这是错误的。团是非党的组织，必须容许其存在独立的组织系统与工作。团从支部起直到中央，参加党的行委组织是加重其政治责任，而不是与党合并。团本身的组织与工作系统，仍应存在。过去的办法，你们应有所改正。尤其是青年工作，更须督促团加紧注意。团的工作人员要尽可能地不调动。

支部工作的建立，是目前武汉工作中的最中心问题之一。如何建立支部工作，你们已知道很多。中央要特别指出的是，你们对于干部的分配与吸引，要特别注意于下层。许多中央派出的干部可以选择得力分子派他们到支部中去，即使不能立即入厂参加生产，也要他们能脱下长衫到工人群众中去，帮助工人党员建立支部生活。另一方面，你们要迅速地从工人斗争中吸引新的党员，吸引新的干部并引进他们到指导机关中来。所以，你们向中央要得力的干部，中央当然还要派人给你们，但最主要的还是要从下层支部中坚决地吸引新的干部上来。

你们关于示威的意见是正确的。只有少数先进分子的单独示威是失策，应准备发动广大的群众性的示威。从这点上也可推论到：只以准备武装暴动为号召，而不注意群众的日常斗争，不注意群众的部分的政治经济要求，不注意从日常斗争中发展赤色工会与赤色先锋队的组织，不注意从一切部分的要求联系到政治总要求，则组织总罢工示威也是不可能实现的。

总之，你们一切工作计划，最中心的缺点是在布置暴动上做文章，而忘掉积极准备武装暴动是要动员最广泛的群众，从斗争中锻炼自己，从斗争中组织自己，从斗争中认识党的领导与接受党的口号。只有这样，才能造成伟大的群众斗争力量与组织基础，才能造成党的坚强的领导。而所谓斗争又必须从各部分的要求发展到总要求，从各种日常斗争、罢工、示威发展到总罢工。党的领导，尤其是在目前形势中的领导，便在于抓紧这些斗争，联系到总的政治要求，联系到总的行动，以准备最后的决战。

在这一原则下，我们要求你们，对于武汉工作要有最切实的计划与办法，要特别着重于中心工作之建立。在武汉，我们提出，铁路、海员、兵工厂、码头、市政、纱厂、黄包车夫是你们指导武汉工作的中心对象。

＊一九三○年六月，党中央政治局在李立三同志领导下通过了《新的革命高潮与一省或数省的首先胜利》的决议案，要求全国各地都要准备马上起义，从而形成了第二次“左”倾路线。“八一”、“八三”会议上，李立三同志又要求在南京、武汉举行暴动，在上海举行总同盟罢工，并将党、青年团、工会合并为各级“行动委员会”。周恩来同志于一九三○年五月出国，八月下旬回国，九月中、下旬出席并参与主持了六届三中全会，会议停止了立三路线的执行。这篇文章是在三中全会前起草的中共中央给长江局的指示信的第一部分。

