# 立三路线的理论基础

中文马克思主义文库 -> 周恩来
立三〔65〕路线的理论基础
（一九三○年十二月一日）


　　我们要纠正立三路线的错误，不仅是复述国际〔66〕的路线，必须对立三路线有彻底的揭发与批评。立三路线之形成不是偶然的，如果在党内没有形成这一路线的基础，则它不会在党的领导机关起领导作用。因此，我们必须在下面三个条件之下来认识立三路线之形成：1.历史的条件，六次大会后有些根本问题没有得到适当的解释；2.党内无产阶级成份薄弱，小资产阶级成份占了很大的数量，这使党的路线有忽“左”忽右的表现；3.立三的思想，在过去的讨论中没有受到强烈的反对。这三个条件，帮助了它在领导机关中起了领导作用。
　　同时，我们在这里，必须认识立三路线之理论的基础：
　　（1）不懂得正确地估计阶级斗争力量的对比。国际来信所指出的，立三路线不懂得正确地分析客观形势及正确地估计阶级斗争力量的对比，这完全是正确的。我们可以从他的文章、报告以及他起草的六月十一日的决议案〔67〕中得到充分的材料来证明。当初立三同志分析敌人的力量时，总是只注意敌人的弱点，或将敌人的某一弱点特别夸大；估计主观的力量时，则只看到强点而掩盖了自己的弱点。所以六月十一日决议案对世界革命及中国革命的进展问题，估量到帝国主义及统治阶级时，把他们看成是无能为力、只有等待崩溃的状态，对于革命力量的估计，不仅夸大了红军的发展，尤其对于城市工人斗争的发展及其觉悟性与组织性夸大了，不合实际。这两方面的会合，对于革命形势的估量自然变成为不正确的了。这是立三同志之非马克思列宁主义的分析问题之观点。
　　（2）否认革命发展之不平衡的特点与对革命高潮认识的错误。不仅在中国问题上，在世界革命形势的估量上也是如此。中央七十号通告〔68〕中提出中国革命的发展将走向平衡。这一句话，在表面看来是没有问题的，但已经种下了以后错误的根源。在立三同志起草的向国际的报告中说：中国革命之发展，不平衡其表面，平衡其实质。这完全否认了革命发展的不平衡，所以当时中央工作人员会上与陈韶玉〔69〕的争论，对这一点也完全错误了。立三同志的观点，认为中国革命爆发必然地引起世界革命之同时的爆发。对长沙事件〔70〕，党的宣言说，中国革命之爆发必然掀起世界之普遍的武装暴动。立三同志想以世界革命第三时期〔71〕的特点来取消革命发展的不平衡。这是他对于世界革命的观点，同时也就是他对于中国革命的观点。他否认不平衡的观点，是将革命高潮解释成为直接革命形势。六次大会〔16〕的决议案中说，“将来的新的高潮，更加要使党将准备武装暴动以至实行武装暴动，认做当前的实际任务”。这就表明由高潮到直接革命形势，虽然中间没有万里长城隔着，但是有一个过程的。而回国后的第一号通告却说，将来新的高潮的到来，武装暴动的口号将要从宣传的口号变成为行动的口号，这便已经将革命高潮与直接革命形势模糊了。去年中国党接到国际十次大会的决议〔72〕，说中国革命运动已开始了新的高潮。在江苏省的代表大会上我曾说明这一问题，所谓新的高潮与直接革命形势是不同的，现在已经有了新的高潮，但还不是直接革命形势。这个问题当时并未引起政治局热烈的讨论，只是在文件上有一点修正，这也足以证明中国党之理论基础的薄弱，同时也就助长了立三路线的形成。立三同志说，坡的阿姆（подъём）的意义不应译作高潮，革命高潮与直接革命形势是一个东西。如果这样，那末，六次大会的决议案中“在总的新高潮之下，可以使革命先在一省或数省重要省区之内胜利”一句话，便应改作“在总的直接革命形势之下，可以使革命先在一省或数省重要省区之内胜利”了。既是总的直接革命形势之下，那里还有什么革命先在一省或数省重要省区的首先胜利呢！当然，在他这样的认识之下，所谓今天是湘鄂赣之首先胜利，但必须得到武汉，武汉之首先胜利也就是全国革命胜利之开始的理论，是一点不奇怪的。所以他会提出组织西伯利亚的华侨回国，要蒙古出兵参加中国苏维埃联邦，要苏联出兵打日本。当然，这不仅是由于否认革命发展之不平衡一点，一切盲动主义、命令主义都同时爆发。
　　（3）组织观念不正确。立三同志对于组织的解释，常常以加强主观力量来回答，他完全是站在机会主义的观点上。他在全国苏维埃区域代表大会〔73〕的报告中，将主观力量放在革命发展的条件以外，而只分析客观的条件。他说革命形势一到，主观力量不成问题，例如“五卅”时期〔3〕与武汉时期。他虽然在“八一”、“八三”的会〔74〕上提出要“加强组织”，但这一“加强组织”，他是认为革命形势已经一般的成熟，只要一组织便起来了。所以他只要用武装暴动的口号来号召，在上海则以四次暴动的口号来号召。这完全将组织力量放在革命形势成熟条件以外，实际上必然走到取消组织的路上去。总行动委员会的组织不仅取消了团，实际也取消了党。
　　（4）在估量斗争形势与布置工作中含有军事投机与军事冒险的观点。立三同志对于红军及农民斗争之发展与组织，有奇怪的意见。这一方面是由于由农村来的人随便报告一些数目字可以帮助他，但根源还不在于此。在“八一”、“八三”的会上他认为：红军进攻武汉，工人必然会起来暴动。另一个政治局同志在《红旗》上说：单纯用红军进攻武汉，我们是反对的；但如果说红军逼近了武汉，工人斗争还不能起来，这也是错误的，工人一定会起来。立三同志之另一观点是建筑在南京士兵暴动的身上，他以为南京士兵一暴动，一定可以占领南京，响应武汉，引起上海总同盟罢工。因此，他以为红军逼近了武汉，武汉工人暴动，南京占领，上海暴动；同时蒋介石在陇海路的军阀战争中失败，冯玉祥〔75〕在河南也因农民暴动而失败；北方军队南下，北方空虚，则北方农民也可以起来暴动，因此要求蒙古出兵，苏联出兵。用这样的分析来决定与布置举行武装暴动，这完全是军事投机的观点，是想在军阀战争中取巧的观点。
　　（5）用托洛茨基的理论来补充他革命转变的理论。立三同志在六月十一日的决议案中说：一省数省胜利的开始，也就是革命转变的开始。这实际上是取消了民主革命政纲之中心的任务。所以他影响到苏代会关于土地问题的决议，用过早的办法，企图在现在的苏维埃区域实行社会主义的政纲。


　　＊这是在中共中央机关工作人员会议上所做的批判立三路线的报告节录。



