# 关于粉碎第四次“围剿”的电报

中文马克思主义文库 -> 周恩来
关于粉碎第四次“围剿”〔76〕的电报
（一九三三年一月——三月）


一　一月二十七日的电报
　　（甲）金溪战役〔77〕后，我军继取备战姿势，调动敌人与征集资材，即三军团开往贵溪亦本此旨。敌此次被我调动，一方企以信江之敌吸引我军，以抚州来敌截击我于金溪之北，一方则又因对我情况不明，深惧前辙，故抚州之敌前进极缓，且向北靠，至今日吴、罗、周三师〔78〕仍在浒湾、琉璃冈、黎墟一线。我方面军集中南移，只一天便达金溪东南部，以备战姿势吸引敌人。但敌今日已侦知我主力不在金溪以北，故又改变计划，以吴、周两师集中浒湾附近，罗师退回抚州，二十三师仍西移乐安，回复其原定进攻部署。
　　（乙）我军决利用此两日时机，发动战斗员将金溪南之七八百病伤员一律后运至黎川地域，以便后方来运。俟敌二十三师明后日向西移动后（最好罗师也西移），我军即以十一军一部游击浒湾，一部佯攻南城，迷惑并牵制敌人。以十二军牵制邵武之敌，另以全力渡河，直攻南丰城，并准备在抚河西消灭敌人增援队，以突破抚河围攻线。
　　（丙）本来依现时敌情，即抚河流域敌之两个较强的“进剿”军还未组织完备以前，我军能在抚河东岸会合十一军求得运动战消灭敌人主力，确比围攻南丰暴露我军企图去打敌增援队为好，且抚河东这一地域，幅员并不窄，地形尤好，尤便征集资材，只是后方连络远不便运输，主要还由于南丰、广昌、建宁、黎川的赤化工作差。但我之利即敌之不利。敌几次想在河东岸以一翼吸我一翼截击我之战略求战，但南丰、南城、金溪三次战役〔79〕，都因被我集中力量迅速击破或消灭其一翼而失败。故敌在抚河东岸作战，非俟其强有力之两个“进剿”军组织完备后，才敢猛进。上次礼西赵（南城）胜利后我以备战姿势在黎川待机，这次金溪胜利后我在金溪待机，都因敌不敢冒进坚守城防致不得在运动战中连续战斗而必须转移地区，因此由南丰东而南城东而浒湾东。我军万分谨慎地弄清敌情，以迟迟进逼的战略调动敌人，求得运动战的胜利，决无忽视敌之进攻与截击的观念。上次东出邵武引敌，因我恐敌截击回师过早，致敌吴、周两师已半至硝石又复缩回，这证明一切战略决定都与敌情、地形、任务有关。假使敌之抚河两强有力纵队已成，又如这次三军团逼近贵溪处于不利阵势，则战略便须改变。故十军渡河时，曾、邵、唐〔80〕等主张三军团过河攻贵溪，我们便立电反对。
　　（丁）现时敌既执行其组织三个“进剿”军与“清剿”军坚守城防的进攻部署，我自须夺取先机，立即转移作战地区，调动敌人以破坏其进攻部署，转移抚河西岸即由此。但须说明，这次宜黄、乐安战役〔81〕以后，敌对城防已更坚守，其虽有主张放弃机械城防的，但必在我进攻与胜利调动敌人和消灭野战敌人条件下。我独立师两次袭击入崇仁，便由于我东岸的胜利和进攻。因此转到抚河西，须攻城才能立即调动敌人，因南丰、南城、宜黄、抚州都在河西岸，不能如东岸一直深入抚州附近去威胁与调动敌人。攻城与消灭增援队一有暴露企图二有易受夹击的不利，故不如在东岸自如。因此在东岸目前如不能求得运动战，决不应轻易过河。这须请你们注意。

二　一月三十日的电报
　　甲、二十七日夜得确报，罗、周、吴三师企图乘我军南移，压迫我军于远距离外，定二十八日开金溪、左坊、琅琚之线，二十九日开珀圩、黄狮渡、琅琚之线，三十日罗师经礼西赵回南城，周、吴两师回浒湾。因此，我方面军乃更集中，准备在其三师分开时，首先消灭罗师。但二十八日敌仅达肖公庙、浒坊、琅琚之线，陈诚〔82〕更以“进剿”尚未准备完毕停止远追，于是二十九日敌复向回缩。今日十一师又开回浒湾、河西之东馆待命，十四师、九十师集中浒湾附近，二十三师已西移乐安，五师到贵溪，八十三师二月半后来赣。蒋介石二十九日已抵南昌，其进攻布置当更加紧加速。
　　乙、敌不愿在布置完毕前，轻易冒进与分兵损实力，已甚明显。周至柔师现正急图补充，吴奇伟师正在整理，吴本人已往见蒋。在此敌情下，连续的残酷的战斗转眼就到。我如立即转到抚河西，只有攻城才能调动敌人。攻城除前电所述，一暴露企图，二易受夹击之不利外，还有三损伤大，四不能筹款，五耗费时日的不利。在大战前如蒙此不利，而坚城又攻不下，增援军三个师并进又不便打，则不仅未破坏敌人进攻部署，且更便利于敌人的进攻。因此在敌人部署完毕前，如能在抚河东岸连续求得运动战解决敌人，我都不主张立即过河攻城。即使敌暂不出击，仍可筹一笔款（金溪胜利后共得现款二十万），以利大战经费，并可加强十一军的赤化金溪、资溪，以更利于牵制敌五、六两师之编入“进剿”军。如敌因蒋来与我在抚河东岸，立即向苏区深入截击，我军自当迅速移转至苏区边境，背靠苏区决战。
　　丙、上述意见，朱、王〔83〕等同志大都同意。只中央累电催我们攻破城防，与我两电所陈战略实有出入。但我终觉消灭敌人尤其主力，是取得坚城的先决条件。敌人被消灭，城虽坚，亦无从围我，我可大踏步地直入坚城之背后，否则徒损主力，攻坚不下正中敌人目前要求。中央局诸同志同意此意见否，望于明日简电复，过期因时机不容再缓，我当负责决定，同时仍请中央给以原则指示。

三　二月七日的电报
　　甲、中央局命令攻南丰，我们部署意见：
　　（一）乘敌第八师有两团欠一营在新丰街，一营在里塔圩之时，我以一部兵力袭击新丰，以主力由南丰下游渡河，断新丰之敌向南丰退路，并直扑南丰城。城内外敌仅四团，有被我强袭入可能，在强袭时，南丰东岸亦配置一部兵力。
　　（二）以十一军主力逼近浒湾，一部向南城对岸游击，威胁并牵制敌人，其工作团则努力赤化金溪、资溪。二十一军向永丰逼近。独四、五师在宜黄、乐安以南行动。
　　（三）如强袭不成，而已驱逐城外工事中敌人，则可一面坑道作业，一面准备打击增援队。
　　（四）如城外工事中敌人尚未驱逐，而敌增援队已至，则只能准备打击增援队。
　　（五）如我牵制敌人兵力不奏效，敌以增援队三四师由马路并进，迎击则我受夹击，侧击则便于城内外敌人会合，如此则便须转移地区，攻宜黄、乐安调动敌人，于山地运动战中解决。因山地易于牵制一部，消灭一部，而由马路并进，便甚难牵制。
　　乙、上述部署不是呆板的，敌情地形有变尚须活用。万一南丰下游因雪水下融不便徒涉，而须改由南丰上游渡河，则我之企图易先暴露，新丰两团便无法截断，南丰城防便可增至六团，且敌可以十一、九十两师先向南丰开来策应。如是将更不便我强袭，便须经过苏区改攻宜黄或乐安去调动敌人，求得运运战中解决敌人。
　　丙、这一部署与中央局命令原旨有出入。我认为攻下南丰最好，但攻下宜黄、乐安，在运动战中消灭增援敌人，仍然可乘胜直胁抚州，且更便运转。你们同意否？或仍坚持唯一是猛攻南丰，虽大损失亦所不惜，虽敌三四师由马路并进亦非与之决战不可？请于今日十八时前立电复，以便明日行动。
　　丁、不攻南丰或宜黄、乐安，先攻南城，在目前敌情与地形上是不可能的事，请中央注意。

四　二月十三日的电报
　　甲、昨日继续侦察南丰堡垒工事，只西北门外堡垒利用夜色可接近强袭。黄昏后我军开始攻击，与敌激战一夜，夺取敌人大小重要堡垒十数个。但城外仍有二十多个堡垒在敌人手中，且极险要，堡垒后又有开旷地。已夺得工事离城边尚远，城墙上又有炮楼。敌守堡垒多一班一排，最重要的不过一连，我攻堡垒费时久，险要的须围困。整夜激战结果，我缴获不足一营，损失却过三百。三军团为主攻，师长彭鳌〔84〕及两团长均阵亡。攻城激战虽夜雨，士气极旺。
　　乙、十日，我十一军已牵制敌八师之一团于新丰街，十一日，二十二军又伸出里塔圩断其归路，故南丰敌为五团。今日，南丰敌在河南之一团，因夜中十二军在河东占第一个堡垒，亦撤回城内，并断浮桥，显示其守城待援之决心。敌对增援部署约以三路分进：两师由南城，一师由宜黄，两师由乐安。敌十一师已向宜黄开动。
　　丙、据此情况，我们遂改强袭南丰为佯攻，决心先消灭增援队。现部队正在南丰西部一带集结，今明两日弄清敌军行进路线后，当求得于预期遭遇的运动战中消灭敌之一翼，以各个消灭之。

五　二月十五日的电报
　　甲、确报，当我军在黎川时，敌大举部署为陈诚领中路军分三个纵队：第一纵队罗卓英，为第十一、五十二、五十九三个师，集中宜黄、棠荫；第二纵队吴奇伟，为第十、第十四、九十三个师，集中抚州、龙骨渡；第三纵队赵观涛〔85〕，为第五、第六、第九、第七十九四个师，集中浒湾、金溪，以一部出资溪。四十三师集中宜黄、乐安间，为预备队。都限二十日前集中完毕。第四、第八十三师为总预备队。
　　乙、我军围攻南丰既急，敌即提前集中，以十一师十四日开至宜黄、棠荫，以五十二、五十九两师开乐安，准备由东陂、黄陂、新丰市截击我军，现均向乐安前进。以第二纵队向南丰前进，十四日九十师到东馆，十四师亦有开动讯，十师尚未动。第三纵队集中时间与地点未变。四十三师向宜黄开，十四日到公陂，宜黄原有其一团。二十七师已集中永丰、新淦。
　　丙、我们现改强攻为佯攻与监视南丰之敌，准备消灭其增援队。敌又有改变进击路线可能。敌对我军猛攻坚城，认为可以损伤与疲劳我兵力，并吸引我于坚城之下，便于其增援队之截击与连续战斗，已定十八日开始“进剿”。
　　丁、现我军集结兵力于南丰城、里塔圩以西地域，背靠苏区，更积极佯攻南丰，引致敌仍依原定路线“进剿”，以便我首先迎击与消灭其右翼。
　　戊、猛攻南丰我军伤亡全数过四百人。

六　三月二日的电报
　　甲、我军与敌激战三昼夜，第三日本可将敌十一师继续消灭或击溃，只因山地战各军联络与我指挥均不易达到，故在第二日消灭五十二师及五十九师大部后，各军位置不利于出击十一师增援队，致昨日战斗未完全解决，只继续消灭五十九师，但胜利是空前的。本日，因敌二纵队三个师已于昨日西向增援，今日可到新丰市、东陂、黄陂，截我归路，我将陷于被包围中，且战场未清理，伤兵未撤，战利品到处堆积，故于今日在胜利中撤退，开始向小布、南团、东韶、水口地区集中，准备继续战斗。
　　乙、因此胜利，敌已纷纷调动，除十一师、二十八师已来河口外，第九师由南城今日抵杏坊，二纵队由南丰、里塔圩、新丰移至永兴桥、饶坊之线，明日逼近东陂、黄陂，三纵队一部一日已占领硝石，今日五师又被调龙骨渡，六师、七十九师则改在南城河西集中。

七　三月四日的电报
　　甲、这几天，敌完全处于被动。二纵队三个师原拟由新丰市截击我归路，嗣知五十二、五十九两师消灭，乃改向黄陂开进。及闻我军已离黄陂，敌十四师急由党口、饶坊北开演口，十师、九十师停在崇五都，十一师进黄陂，九师赶到河口，今日均未动。三纵队之第五师被调龙骨渡，今日又令由岳口回南城。三纵队现已改向南丰进，先头明日可到。
　　乙、闽敌刘和鼎〔45〕昨日率一旅一团进太宁。十九路军以区寿年师及张炎旅三日集中永安为右翼，以沈光汉及张贞师为左翼。右翼定八日进连城。这一部署是黄陂战役前预定的。
　　丙、陈诚中路军的进攻路线已改变。三纵队改走南丰，一、二纵队（现只五个师）或将更靠近，出东陂、黄陂、新丰市，求我主力决战于东韶、河口，而以三纵队趋广昌，出头陂、东山坝，截我归路。
　　丁、我军拟俟集中后（一军团带胜利品，经招携路较远）仍选敌一翼，求于运动战中消灭之。

八　三月十六日的电报
　　甲、北面敌两纵队各三个师靠拢并梯次轮番向东南搜索前进。今日其前纵队十四师始达新丰市，九十师达侯坊，十师达草台冈；后纵队九师达东陂，五师达黄陂，十一师达安槎、蛟湖。预备队七十九师在宜黄，有两团在河口，六师在抚州，许克祥全师在南城，刘绍先师在乐安、崇仁，余无变动。
　　乙、我们已调十一军，十八日可至广昌西北，配合独立师、团及地方武装，牵制并抑留敌进攻广昌之前纵队。我主力决以待机姿势，准备侧击敌之后纵队，并首先消灭其行动中后卫部队，以便连续作战，各个击破敌人。
　　丙、我方面军昨日已开始移动，因敌两纵队太靠拢，故尚在待机中。但这是四次战役决定胜负的战斗，已下最大决心，准备一切牺牲，部署与敌三个师决战的阵势和动员。

九　三月二十日的电报
　　甲、敌情另电告。
　　我十一军已于十八日到广昌附近，拟于二十日起领导地方武装牵制向广昌去的敌人前纵队，并以主力阻敌回援，以掩护我军右侧背。
　　乙、我军拟于二十一日拂晓，采取迅雷手段，干脆消灭草台冈、徐庄附近之十一师，再突击东陂、五里排之敌。
　　丙、五军团、十二军、宜黄独立团为右翼队，归董、朱〔86〕指挥，应于二十一日拂晓以主力进攻草台冈、徐庄敌左侧背，以一部从摇篮寨方面牵制东陂之敌，其预定动作如次：
　　（1）第十二军（附宜黄两独立团）应于二十日黄昏时到斜蕃附近，二十一日取捷路到侯坊上游适当地点渡河，占领灵埂山、三角砦一带，侧击侯坊、徐庄、雷公嵊之敌，并以一部领导宜黄老独立团，往石背、摇篮寨游击东陂之敌。新独立团往新丰市西南地带，挖毁由东向西的交通路（防敌回援），并警戒我右侧背。
　　（2）第五军团应于二十日到端溪附近，并派队伪装逼近侯坊游击。二十一日拂晓沿落马山、霹雳山进攻侯坊、徐庄、雷公嵊之敌。
　　丁、第三军团、第一军团、二十一军、独立第五师为左翼队，归彭、滕〔87〕指挥，应于二十一日拂晓先迅速消灭草台冈附近之敌，再突击东陂之敌，其预定动作如次：
　　（1）第三军团应于二十日以掩护队占领界上、雷母山之线，掩护其主力于黄昏时到东边岭、亮溪附近，二十一日拂晓由西南向东北进攻草台冈之敌。
　　（2）第一军团应于二十日以掩护队占领三溪附近，掩护其主力于黄昏时到大坪、徐坊、沚洲之线，二十一日拂晓即由西向东突击铁石坳附近之敌，以截断东陂与草台冈敌人之联系。
　　（3）二十一军（直受林〔88〕、聂〔89〕指挥）应于二十日以掩护队占领王都、上堡附近，掩护其主力于黄昏时到达古王坑、邱坪附近，二十一日拂晓即由西向东进攻东陂之敌。
　　（4）独立第五师（直受林、聂指挥）应于二十一日拂晓由吴城出秀山，由北向南佯攻五里排之敌，并警戒我左翼侧。
　　戊、两翼队战斗分界线由东边岭到东陂大路之右侧（道路归左翼队）。
　　己、第二十二军为总预备队，二十日在现地不动，二十一日随第一军团左后方前进，必要时由林、聂直接指挥。
　　庚、第一军团卫生部准备在长罗开设野战医院。三军团卫生部准备在徐庄、荫水开设兵站医院。后方联络线仍照作战计划规定。
　　辛、总部拟明（二十一）日到亮溪附近。


　　＊一九三三年二月至三月，蒋介石调集四五十万兵力对中央革命根据地进行第四次“围剿”。这时，以王明为代表的第三次“左”倾机会主义路线已统治中央领导机关。他们不仅提出了一条“左”倾的政治路线，而且提出了一条错误的军事路线。在第四次反“围剿”开始时，毛泽东同志已被排挤离开了红军。周恩来、朱德等同志在前线指挥作战，他们在实践中认识到中央和苏区中央局要求红军先发制人、攻占敌人重兵驻防的坚城南丰和南城的命令是错误的。周恩来同志向中央和苏区中央局提出了集中兵力在运动战中各个歼灭敌人的方针。在周恩来、朱德同志的指挥下，第四次反“围剿”取得了胜利。这次战役先后歼敌五十二师、五十九师和敌主力十一师，缴枪万余枝。这里收入的电报，前八件是周恩来同志给中央和苏区中央局的，第九件是和朱德同志联合署名发布的命令。



