# 关于西安事变的三个电报

中文马克思主义文库 -> 周恩来
关于西安事变的三个电报
（一九三六年十二月）

一　与宋子文谈判情况

（一九三六年十二月二十三日）

（甲）宋子文、宋美龄、蒋鼎文〔90〕昨到西安。蒋暗示宋改组政府，三个月后开救国会议，改组国民党，同意联俄联共。

（乙）今日我及张〔91〕、杨〔92〕与宋谈判。

第一部分，我提出中共及红军六项主张：

子、停战，撤兵至潼关外。

丑、改组南京政府，排逐亲日派，加入抗日分子。

寅、释放政治犯，保障民主权利。

卯、停止剿共，联合红军抗日，共产党公开活动（红军保存独立组织领导。在召开民主国会前，苏区仍旧，名称可冠抗日或救国）。

辰、召开各党各派各界各军救国会议。

巳、与同情抗日国家合作。

以上六项要蒋接受并保证实行。中共、红军赞助他统一中国，一致对日。宋个人同意，承认转达蒋。

第二部分，宋提办法及讨论情况：

子、宋提议先组织过渡政府，三个月后再改造成抗日政府。目前先将何应钦、张群、张嘉璈、蒋鼎文、吴鼎昌、陈绍宽〔93〕赶走。推荐孔祥熙为院长，宋子文为副院长兼长财政，徐新六或颜惠庆长外交，赵戴文或邵力子（张、杨推荐）长内政，严重〔12〕—或胡宗南长军政，陈季良或沈鸿烈长海军，孙科或曾养甫长铁路，朱家骅或俞飞鹏长交通，卢作孚长实业，张伯苓或王世杰长教育。我们推宋庆龄、杜重远、沈钧儒、章乃器〔94〕等入行政院。宋力言此为过渡政府，三个月后抗日面幕揭开后，再彻底改组。我们原则同意，要宋负责；杜、沈、章等可为次长。

丑、宋提议由蒋下令撤兵，蒋即回京，到后再释爱国七领袖〔95〕。我们坚持中央军先撤走，爱国领袖先释放。

寅、我们提议在这过渡政府时期，西北联军先成立，以东北军、十七路军、红军成立联合委员会，受张领导，进行抗日准备，实行训练补充，由南京负责接济。宋答此事可转蒋。

卯、在蒋同意上述办法下，我们与蒋直接讨论各项问题（即前述六项）。宋答可先见宋美龄（子文、学良言她力主和平与抗日）。

（丙）如你们同意这些原则，我即以全权与蒋谈判，但要告我，你们决心在何种条件实现下许蒋回京。请即复。

二　与宋子文、宋美龄谈判结果
（一九三六年十二月二十五日）

（甲）与宋子文、宋美龄谈判结果。

子、孔、宋组行政院，宋负绝对责任保证组织满人意政府，肃清亲日派。

丑、撤兵及调胡宗南等中央军离西北，两宋负绝对责任。蒋鼎文已携蒋手令停战撤兵（现前线已退）。

寅、蒋允许归后释放爱国领袖，我们可先发表，宋负责释放。

卯、目前苏维埃、红军仍旧。两宋担保蒋确停止剿共，并可经张手接济（宋担保我与张商定多少即给多少）。三个月后抗战发动，红军再改番号，统一指挥，联合行动。

辰、宋表示不开国民代表大会，先开国民党会，开放政权，然后再召集各党各派求国会议。蒋表示三个月后改组国民党。

巳、宋答应一切政治犯分批释放，与孙夫人商办法。

午、抗战发动，共产党公开。

未、外交政策：联俄，与英、美、法联络。

申、蒋回后发表通电自责，辞行政院长。

酉、宋表示要我们为他抗日反亲日派后盾，并派专人驻沪与他秘密接洽。

（乙）蒋已病，我见蒋，他表示：

子、停止剿共，联红抗日，统一中国，受他指挥。

丑、由宋、宋、张全权代表他与我解决一切（所谈如前）。

寅、他回南京后，我可直接去谈判。

（丙）宋坚请我们信任他，他愿负全责去进行上述各项，要蒋、宋今日即走。张亦同意并愿亲身送蒋走。杨及我们对条件同意。我们只认为在走前还须有一政治文件表示，并不同意蒋今天走、张去。但通知未到张已亲送蒋、宋、宋飞往洛阳。

（丁）估计此事，蒋在此表示确有转机，委托子文确具诚意，子文确有抗日决心与改院布置。故蒋走张去虽有缺憾，但大体是转好的。

（戊）现在军事布置仍旧，并加紧戒备。

（蒋临行时对张、杨说：今天以前发生内战，你们负责；今天以后发生内战，我负责。今后我绝不剿共。我有错，我承认；你们有错，你们亦须承认。）

三　关于西安事变和平解决后的局势和我们的方针
（一九三六年十二月二十九日）

我们以下的意见供你们参考：

一、西安事变之和平解决，意味着中国的政治生活走入一个新的阶段的开端。就是：

子、进攻红军战斗走向停止；

丑、对外退让政策将告终结；

寅、国内统一战线初步局面的形成；

卯、陕甘两省变成抗日根据地之现实的可能性。

二、西安事变及其和平解决，指示着阶级力量之分化及重新结合，特别是资产阶级营垒之决定性的分化过程，其意义就在推动和加速了资产阶级营垒中左派之集中，打击了中间道路之思想。然而分化过程没有终结，大致的情况仍然存在着三个营垒：抗日、降日、中间。新的变动就在：

子、抗日力量的增强与合法化（至少部分地）；

丑、亲日派遭受一致命打击；

寅、中间派开始接近于左派（虽然依旧不免动摇地缓慢地，即保存中间之基础）。

方针：打击亲日派，巩固以西北为中心之左派，影响与吸收中派。

三、孔、宋政府是一个过渡的政府。这个政府在目前基本问题——对日问题上将采取较强硬的态度，在民主问题上或许可有一小步之前进，但显然在许多方面仍然会继续着旧的路线。我们对孔、宋政府，应当以过渡政府看待，即是：推动与赞助其抗日倾向，争取逐步的即使不大的民主改革，同时丝毫不放松对他的批评。如一切过渡政府一样，有着必然的摇摆与不同可能的前途，我们应与他每一个摇摆斗争，而争取他过渡到抗日政府。

四、在这个情况下召集抗日救国会议的运动，在发动、觉醒、组织群众及推动时局的进展上，均具有重大之意义。应该把要求南京召集和平会议和人民的促进运动联结起来。但会议召集的时期及胜利的保证，依靠于促进运动之开展，这是局势开展之一个重要的环节，加强抗日统一战线的群众性的关键。

五、局势开展之另一个中心环节是巩固西北，将西北变成抗日根据地和统一战线的模范地区的可能性变为现实性。这需要：

子、规定和实现三方面共同合作的纲领和西北的军事计划；

丑、张、杨两部之巩固与改造，红军的休整与在新的基础上之正规化，以及三方面的休戚相关的互相尊重的合作和互助；

寅、群众运动之开展和发动，在这个基础上地方政权之民主化与改造；

卯、宁、青、甘西之解决回民问题。

六、坚持全国团结一致抗日的组织者与发动者的立场：一方面，在抗日与打击亲日分子的基础上，和南京左派合作，吸取中间派到我们方面来；另一方面，结合南京之外的各派，以西北为中心，以抗日为目的和条件，为推动南方向左之力量。

七、转变党的全部工作，使之适合于新的环境，成为全国政治生活中的主导者。

子、恢复在大城市，首先在工人阶级中的党的工作。

丑、改变各地零散的游击队为农民自卫武装，并成为农民运动之策源地。

寅、迁移中央至便于领导全国政治生活之地区。

卯、教育与重新教育干部。

＊在日本帝国主义要把中国变为它的殖民地的严重形势下，以张学良将军为首的国民党东北军和以杨虎城将军为首的国民党第十七路军，受红军和人民抗日运动的影响，要求蒋介石停止内战，一致抗日，被蒋介石拒绝。一九三六年十二月十二日，张、杨联合行动，在西安逮捕了蒋介石。以汪精卫、何应钦为首的亲日派，准备乘机发动大规模内战，除掉蒋介石并取而代之。当时，中共中央坚持了反对新的内战、和平解决西安事变、逼蒋抗日的方针，并派周恩来、博古（秦邦宪）、叶剑英同志为代表去西安。经过周恩来等同志艰苦的工作，西安事变终于和平解决。西安事变的和平解决成了时局转换的枢纽，在新形势下的国内合作形成了，不久，全国的抗日战争发动了。这三份电报是在谈判过程中发给中共中央的，其中后两份是和博古同志联合署名的。

