# 现阶段青年运动的性质和任务

中文马克思主义文库 -> 周恩来
现阶段青年运动的性质和任务
（一九三七年十二月三十一日）


今日青年运动的性质
　　根据今天抗战的形势，我们来说一说目前青年的环境。
　　今天，无疑是个变动的战斗的历史上从未有过的大时代。敌人要我们每个人、每个人的子子孙孙都做亡国奴。我们要求生路，便只有抗战，便只有坚持抗战到底。这时代是战斗的。这时代不能与过去“五四”、“五卅”〔3〕、一九二五年大革命时代相比。过去是对内的局部的政治斗争，这一次却是对外的全面的反法西斯侵略的抗战。现在是整个被压迫、被屠杀、被奸淫、被侵略的中华民族的人民起来反抗的时候，所以现在的形势全变了。在国家环境整个的变动下，青年在这时代里所占的地位是最困难而又最重要的。如今我们青年再不能如过去那样地学习，找工作，结婚……再也不能依照平常的生活程序过日子了。战争了，我们再不能安心求学了。文化中心的京、沪、平、津、粤、汉，已去其四；后方的学校，也多半停了课；成千成万的青年人无家可归，无学可求，尤其是东北的青年朋友，一再地飘泊流浪，一再地尝受人世间的惨痛。一支名叫《松花江上》的歌曲，真使伤心的人断肠。然而我们应该骄傲，应该自豪。我们这一代青年应该庆幸恰好生活在这样大的动乱的时代里。我们要在这时代里学习得充实起来，锻炼得强健起来。
　　我们青年不仅仅有今天，而且还有远大的未来。他不仅管自己的一生，而且还要管及他的子孙，他的后代。今天的青年不仅要问，怎样争取抗战最后的胜利；而且要问，在抗战的胜利取得后，怎样改造中国，使它成为一个自由的、民主的、共和的国家。
　　因此，我们想，在积极方面，这是一个最好的时期。它可以把我们这一辈的青年锻炼得更伟大，前程更远。这机会在平常是很难找到的。

今日青年运动的任务
　　我们中国的青年，不仅要在救亡的事业中复兴民族，而且要担负起将来建国的责任。救国，建国，我想“任重道远”这四个字，加在中国青年的身上是非常恰当的。
　　我们今天应该努力的方向是什么？我贡献给诸位青年朋友的有四个：
　　第一，到军队里去——这是在今天挽救民族危亡的最有效的方法。建立生力军，充实我们的旧队伍，责任都在我们青年朋友的肩上。我想，一个人不能自卫，便不能做人，国家也是这样。所以我们最好受正规的军事训练，随时到直接杀敌的战场上去。
　　第二，到战地服务去——战地的民众缺乏组织，到处在流浪着，彷徨着。要起来自卫，要起来斗争，却没有人领导。我们得去把他们组织起来，武装起来，领导着他们去打游击战，去配合正规军的行动，去封锁消息，坚壁清野，破坏敌人必经的交通线……至少也得做到军民合作，使汉奸活动不易。
　　第三，到乡村中去——我们虽然失去了许多地方，但后方还有广大的城乡。今天的后方民众，有许多还不知道抗日是什么一回事。我们要继续作战，继续加强军队的战斗力，必须动员起广大的群众到军队中来。我们要改良过去那种不合理的动员方式。有作为的青年们，因此必须有组织地、直接地下乡动员群众，使农村壮丁勇敢地、自动地到前线去。在工作的时候，我们得注意优待抗日军人家属的问题。最好能够做到有钱的出钱，有力的出力，让乡下有钱而不愿当兵的人切实负责赡养抗日军人的家属，使他们没有后顾之忧。这样，我相信会造成政府与人民的合作，减去许多磨擦的。再，我们还可以进行许多人民自卫的工作，准备将来配合着政府军的抗战。
　　第四，到被敌人占领了的地方去——我们再不能让华东、华南象东北四省〔116〕一样，给敌人安安稳稳地拿去了。我们要艰苦地在那残暴的统治之下锻炼我们自己，秘密地把我们的救国组织发展起来，把我们被压迫的同胞暗地里武装起来，准备迎接我们正规军的反攻，与我们的正规军取得里应外合。
　　我们的青年朋友们分散到群众中去，分散到全国各个角落里去，那我们的力量是无比的！
　　工作和学习是分不开的。如今我们只有在不断地学习中，我们的工作才能够顺利地展开。我相信，只要我们肯，在任何地方都可以学习的。我们要各找一个适合于自己的地方，去发扬我们自己的长处，去学习，去工作。
　　这并不是说我们得抛弃以往的学习，而是根据以往的那点根基，去发扬光大，去使理论适合于实际，去把知识活用。
　　中国的青年运动有着最光荣的传统。今天，我们青年面对着民族解放的斗争，我们的使命是伟大的。
　　我们去工作，我们要克服任何的困难，我们要解除任何的疑团，我们是勇敢的，沉毅的，艰苦的，深刻的……我们是抗战的支柱。
　　我们的前程是光明的，远大的。
　　青年朋友们，努力去争取抗战的最后的胜利，努力去争取独立的自由的幸福的新中国的来临！


　　＊这是在武汉大学的演讲的第二、三部分，刊载于武汉《战时青年》第一期。



