# 抗战军队的政治工作

中文马克思主义文库 -> 周恩来
抗战军队的政治工作
（一九三八年一月十日）

一　革命的政治工作是民族革命的生命线

两个月全国抗战的教训，很清楚而迫切地把改造军队使之适合民族抗战需要的大问题，提在全国人民的面前，特别是尖锐地提在国民党的面前。

改造军队最重要的一环，就是建立革命的政治工作制度。只有在抗战军队中把政治工作实际地建立起来，才能把民族抗战的战斗力提高，才能把官与兵、军与民联结成一条心，象一个人一样，为民族的独立自由而战斗到底！

当着一九二四年国民党在广州改组〔2〕，国民政府成立前，当时旧的军队尚未改造，革命军队还未建立，所以虽有二十余万粤、湘、滇等军与陈炯明等部酣战于东江、西江、北江、南路〔117〕各地，而胜负不决。在黄埔军校〔118〕第一期毕业，新的国民革命军成立了两个团后，仅仅以新成立这两个团为骨干，举兵“东征”〔119〕，即得着东江民众的热烈欢迎与帮助，克复潮汕，直抵闽境，并迅速扫平杨、刘〔120〕。如果从单纯的军事观点上说，以二十万众的粤、湘、滇军血战经年不能打败陈炯明，后来只加两个团，以数千之众，即起了全部胜负决定的作用，这不是奇迹吗？这是由于新成立的两个团，是新的革命军队，是有着革命的三民主义作政治工作基础的军队。政治力量超过了敌人，提高了战斗力，保障了军队本身及军队与人民的团结。当时国民党正因为有了这一铁的事实的教训，才决心以建立革命的政治工作为中心，继续成立新的革命军队，改造旧的军队，如是才有北伐〔121〕的胜利。

苏联红军所以能够团结全国工农在残破困苦之中击败白党与外国的进攻，中国红军在过去十年所以能团结苏区人民进行残酷的战斗，西班牙政府军所以能团结人民与法西斯德、意侵略军及佛朗哥叛军进行坚决持久的战斗〔122〕，这些“奇迹”的主要原因之一，就是由于革命军队有坚强的革命政治工作！

因此，我们可以肯定地说，以革命主义为基础的革命政治工作是一切革命军队的生命线与灵魂！

有人说，政治工作是空谈，是“卖狗皮膏药”的。又有人说，政治工作徒然增加军队中上下级的磨擦，军官带兵更困难了；军队对民众关系“太好”，就更难指挥人民了。

我们必须坦白诚恳地说，这些非难政治工作的理由，不是不了解政治工作的实际意义，就是故意反对军队中的革命政治工作，而不想军队革命化。政治工作之变为空谈，这决不是政治工作的本身错误，而是由于政治工作人员没有实行真正的革命的政治工作。如果一方面空谈革命主义与革命政纲，另一方面在实际上却又多方阻碍革命主义与政纲见诸实行；如果一方面在宣言、广播谈话、训练中，向军队官兵与人民空喊全民族大家要参战，但另一方面在实际上又处处不给人民参战的权利与机会，处处阻碍人民与军队的联系，甚至人民慰劳抗战军队都被禁止；如果一方面高谈抗战，空喊士兵要勇敢上前线，但是实际上高级军官临阵不前，甚至化装先逃：这一切的一切，与革命主义、革命政纲、革命军队的行动都背道而驰。这样的政治工作，也就不得不变成点缀、凑趣、捧场的东西了。这样的政治工作必然会变成空谈，变成“卖狗皮膏药”的东西了。

政治工作，原是以革命主义、革命政纲来团结和联系军与民、官与兵的。如果官与兵、军与民之间没有这种为民族为国家而团结一致、坚决牺牲奋斗的最高原则来联系，没有“在上者”的提倡与做模范，而继续军队中的军阀制度，继续官压迫兵、军压迫民的离心作用，要想指挥如意，打成一片，是不可能的。欲使军队真正成为为民族解放的前卫战士的革命军队，也是不可能的。

另外又有人说，现在全国国民革命军中不是也有继承大革命时代所建立的政治工作么？对于这一问题，我们也必须坦白诚恳地答复说，大革命时代军队的政治组织与制度已不复存在于现在的所谓政训处〔123〕中。中山先生的革命的三民主义，革命的三大政策，已经不是十年来的政治工作内容了。这样没有革命制度与革命内容的政治工作，还能适合现在民族革命军队的需要么？一九二七年后，十年来保持与发扬了大革命时代革命制度与革命内容的政治工作的，只有现在的第十八集团军，即红军。

二　抗战军队政治工作的任务与内容

革命军队的政治工作的基本目的，是提高革命军队的战斗力，保证战争的胜利，是使军队本身团结起来，军队与人民结合起来。

中华民族处在生死存亡的决定关头，迫切需要抗战军队的牺牲奋斗到底的战斗力，迫切需要军队与人民团结共赴国难，争取持久抗战的最后胜利。而今天要消除现有军队的一切派系，要消灭保存实力及把军队作为个人工具的观念，要消灭上压迫下、官压迫兵、军压迫民的一切军阀制度，要消灭一切畏缩不前、借故推诿、友军遇危险而不援、望风而逃的恐日病等等可耻的现象，只有发挥大革命时代的革命政治工作，使全国军队成为为民族解放而坚持奋斗到底的革命军队。

全国军队的革命的政治工作，必须恢复以中山先生革命的三民主义为基础，革命的三大政策为骨干，使每个指挥员、战斗员，每个人民懂得而且确信我们今天的抗战是为国家，为民族，为自己，为子孙，为着争取民族解放、民生幸福、民权自由这三大目的而奋斗，而且深刻了解与坚决执行联俄、联共、联工农三大政策，认识这是达到革命三民主义的唯一方策。只有这样的政治工作与革命政策的实际执行配合起来，才能使全国军民上下一心，军民一体，抱着抗战胜利的信心，望着民族解放的光明而坚固团结起来，不怕艰难挫折，不受威迫利诱，不迷惑于挑拨离间，坚持争取抗战的最后胜利。

根据这样的目的与基础，我们在政治工作的实施方面应做些什么呢？我以为革命政治工作应分为军队、居民、敌军三方面的工作。

在军队内部方面的政治工作，目前亟需做的是：

（一）向每个部队的全体官兵实施革命的政治教育，发挥革命的三民主义，把理论与实践相联系，使每个官兵有着革命的前进的人生观，使之了解国际大势、国内形势、日本状况，以及如何争取抗战最后胜利，高度地提高战士的民族觉醒与自我牺牲精神。因此军队的政治教育，必须与军事教育并重，必须有经常的政治教育时间，必须有革命内容的政治教育材料，必须开展指挥员、战斗员中的充分讨论，耐心解释一切疑难与误解，反对政治教育的形式主义与宗教仪式，提高战士们学习研究的兴趣。只有这样，政治教育才能深入。

（二）努力注意改善士兵待遇与生活。必须承认，旧军队中士兵的待遇与生活是极不好的，如果不努力尽可能地改善，是不能把士兵的战斗积极性提高，消除官与兵的隔阂的。必须禁止肉刑与打骂，禁止克扣军饷，这些均应明令规定，由政治机关监督实行。设置各种必要的组织，如抗战室、俱乐部、晚会等等，发展官兵中的正当娱乐与体育运动，发展士兵文化识字运动，保证部队的给养，由士兵自己选举伙食委员会，注意改善伙食。民众的一切慰劳品，主要的应尽量分给下级官佐与士兵，并应使慰劳的民众亲密地接近士兵。只有这样，才能使官兵生活愉快与兴奋。如果政治机关的政治工作不能和改善士兵生活与待遇密切联系起来，政治工作就成为“卖狗皮膏药”。

（三）建立革命军队自觉的革命军风纪。民族革命军队的军风纪的建立，部队的巩固，是建筑在政治的民族的觉悟上的，而不是依靠皮鞭、军棍、打骂及肉刑的。军队与人民的团结是建筑在每个官兵自觉地爱护民众、保护民众利益上的，而不是依靠压迫、摧残、强迫、命令所能成功的。对于犯错误犯纪律的分子，主要是要采取说服教育的方式，只有在万不得已时才执行纪律条令。因此，只有充分的政治教育，官兵间互相的了解与信任，军民间互相爱护，才有革命军队的自觉纪律。政治机关的政治工作，必须从加强政治教育与改善士兵待遇中，来建立革命的军风纪。

（四）保障军事指挥员在军事行政上命令的贯彻执行。军事指挥员为着抗日的民族利益、为着发挥部队作用和巩固部队组织的一切命令，政治机关应经过政治工作，依靠下级官兵的高度民族觉悟与自觉的军风纪来贯彻执行，并向一切违犯命令的倾向作严肃的斗争，来教育全体官兵。

（五）全体政治工作人员以身作则的模范作用。政治工作人员本身必须在思想上政治上行动上能够做全体官兵的模范，忠实于革命主义，以百折不挠的意志，艰苦耐劳的作风，去影响全体官兵；以谦逊和睦的态度，耐心说服的精神，去团结全体官兵。只有这样，才能提高政治工作的威信，推动政治工作的前进，发展政治工作的效果。一切高傲的出风头的空谈的恶习，以至贪污腐化的生活，必须克服与排除。

对地方居民的政治工作，目前迫切需要的是：

（一）保护人民的利益，使军民打成一片。军队所到之地，必须禁止拉伕拉车和征粮征草。买卖要公平，不扰民，不害民。在军事上必须人民帮助时，要召集民众的真正代表会议，说服人民，鼓动人民，使人民自愿地帮助军队。

革命军队所经之地，不仅要保障自己不扰民，不害民，而且还要为民除害。军队政治机关必须坚决站在保护人民利益的立场上，为人民解除痛苦。只有这样，才能使人民从自己的实际生活中认识军队是人民自己的军队，是为民族利益而战的军队，军民才能坚固地联结起来。

（二）组织人民，武装人民。抗战军队所经之地，政治机关必须给人民自主权利，宣传与动员人民，帮助与领导人民组织起来，武装起来。使各界各业人民都自动地组织抗日救国的团体，组织抗日的武装，一切不适合于动员广大人民参战的、限制人民行动的旧有组织，应给以改造，充实其民众基础，发挥民众的作用。只有这样，抗日的军队才能取得千千万万的民众力量的配合，抗战军队的一切需要与补充才能依靠人民的力量来解决。

（三）发动人民肃清汉奸。日本特务机关散布全国，汉奸到处横行。抗日军队为着巩固自己作战的战场与后方，为着提高军队与人民的政治警觉性，政治机关必须注意动员人民，配合人民进行锄奸运动。对日寇、汉奸的仁慈，即是对民族的犯罪。培养军民的力量，用坚决的手段，扑灭间谍、奸细的活动，是政治机关保障抗战的主要工作之一。

对敌军的工作，也应当进行：

（一）经常地对敌军宣传煽动，抓住敌军中每一个可能利用的机会，使敌军瓦解和涣散，因而减弱敌人的战斗力量。

（二）在火线上，即在战斗中，也要进行对敌军的喊话或散放传单，使敌军动摇。

（三）应当极力禁止虐待俘虏，经过优待、教育、解释后，立即把他们放回去。

三　政治工作的组织与方法

要进行革命的政治工作，获得政治工作的完满效果，必须建立严格的政治工作制度与健全的政治工作组织。这里，首先就应排除一切忽视政治工作，把政治机关看成点缀品装门面的错误观念。

政治工作，必须在军队的各级，从最高的全国的总政治部直到连队的政治指导员，建立其独立的组织系统。除各级部队的指挥员可指导同级的政治工作机关外，下级政治机关必须服从上级政治机关的指挥。政治机关对同级指挥官的指导有异议时，有向其上级机关申诉之权。各级军事长官必须给同级政治机关实施政治工作的一切便利，而不应予以干涉与阻碍。各级政治机关的官长，对其同级及下级官佐违反革命主义、革命政纲与革命纪律的行动，有向上级政治机关弹劾之权。只有这样，才能使政治机关有达到其政治工作目的与任务的保障。

正因为政治工作人员有这样严重的责任与不能逃避的负担，所以对于政治工作人员的选择与培养必须慎重。必须集中全国优秀的政治工作人材，必须不断地培养全国前进的青年干部，分到全国军队的政治工作的组织中去，才能保障政治工作任务的完成。一切对人员安排位置滥竽充数的观念，都是危害政治工作的。

正因为政治工作机关与人员负有如此重大的责任，所以必须注意实施政治工作的方法。要根据每一部队的历史、组织、习惯、组成成份、官兵关系等等不同的情况，要根据各地的社会、经济、政治、人民等等不同的复杂条件，采取灵活的方式去进行，不要造成军事与政治对立，不要造成格格不入的现象，不要脱离军民。要以耐心说服诱导的精神，争取官兵和人民的信仰，团结他们在革命主义与政纲的领导下而坚决奋斗。

全国一切抗战的武装队伍，迫切需要以最大决心迅速实行革命的政治工作，才能争取抗战的最后胜利。对于这一紧迫的重大问题，特将此刍议提在全国各军队之前。

＊本文刊载于一九三八年一月十日上海出版的《抗战政治工作纲领》小册子，未标明写作时间。

