# 目前形势和新四军的任务

中文马克思主义文库 -> 周恩来
目前形势和新四军的任务
（一九三九年三月）

一　目前的形势与新四军的环境

今天，抗战正向新的阶段过渡，敌方、我方、国际三个方面，出现了一些新的情况。

一、敌人的政策明显地表示了三个特点：

（1）认定扫荡敌后方是它的中心。不论军事政治文化经济各方面，特别是军事的行动，都把主要的力量放在敌后方，所以四个月来敌人没有进攻与深入内地的形势。

（2）实行政治为主、军事配合的政策。敌人要拿这个政策来利用我沦陷区的人力物力财力资源。

（3）无论如何还是继续战争的局面。不是以政治为主了，战争就可以停止。除非是中国胜利或者是中国屈服，战争决不会停止，敌人也不会因扫荡后方就停止进攻。

二、我方的政策已转到要重视敌人后方。在新阶段中，我们抗战的中心放在敌后，在敌人占领地区开展游击战，实施新的施政纲领，整理地方武装，跟敌人在政治上经济上文化上军事上争胜负。我党总结了一年抗战的经验，在六中全会〔124〕决议案中讨论了敌后工作问题。在武汉危急时，我们强调了全国军民和各党派应重视敌后工作。在我们共产党领导的军队占优势的地方，欢迎各抗日党派共同到敌后去工作。

三、国际上也是极注意中国问题的：

（1）非常注意敌人占领地区的情况和敌人在占领地区的政策。

（2）非常注意游击战争的发展。

（3）非常注意中国共产党在游击区的政权。都想看一看中国共产党所领导的军队在游击区能不能坚持到最后的胜利，看一看中国共产党所实施的政策是否侵犯各国的利益，看一看中国共产党所领导的军队在游击区是否能真正破坏敌人的政治经济文化各方面的实施，还要看这些军队能不能壮大起来成为正规军与敌人进行更大的胜利的战斗。

根据敌人、我们、国际三方面的情况可以看出，今天新阶段的中心问题是在敌人占领区，在中国的东部，在黄河以东、平汉路粤汉路以东的广大地区。不仅仅是因为中国东部被敌人占领了，而且更主要的是，这是中国人口最多的地区，是交通便利、土地肥沃、经济发达、文化程度高的财富地区。整个的中国东部，代表了中国走向近代化的最有力的地区。中国的西部当然不如东部，尽管西北、西南可以成为我们的大后方，但是，假如中国东部完全被敌人统治，我们的西部就要一天一天地贫弱危困起来，困难就要无形地加深，而敌人就能够利用中国的人力物力财力来克服自己的困难。我们要认识这个环境，这就是新四军的环境。新四军就处在敌人占领的中国东部。新四军今天所处的客观环境恰恰使得新四军的地位更加提高，落在新四军肩上的任务也就更加重要。

二　新四军的发展与困难的克服

正是因为这样的形势和环境，所以我们新四军是有发展前途的。为什么这样说呢？

一、我们愈向敌人的后方，愈能够得到发展的机会。

二、愈在困难的条件底下，愈能够显出我们的特长，愈能够锻炼我们。我们不求在安逸的地区发展。因为安逸的地区谁也要来，谁也能够存在。我们主要地要向困难的地区发展。因为困难危险，国民党的许多部队和工作人员克服不了，忍耐不了。而我们新四军能吃苦耐劳，不怕困难。

三、愈深入到民众中间，愈能够创造根据地。我们如果打算把新四军所在的地方建立成根据地，就要依靠这个地方的广大群众，深入到群众中去。深入群众才能够保障我们的发展。

四、愈复杂，愈能够使我们的统一战线发展。中国统一战线的特点就是复杂。只有在复杂的情形下，我们才能够造成民族统一战线的模范区域。

五、愈有竞赛，愈能够使我们本身进步。国民党五中全会提出了彼此竞赛，我想江南江北地区特别是江南地方政府、民众团体各方面同我们竞赛，更能够锻炼我们，使我们进步。

六、愈坚持，愈能够影响全国全世界。我们要坚持游击战争，创造大江南北的根据地，给敌人看，给全国全世界看：我们绝不退后，绝不逃避。在这样困难的地区，我们能够发展游击战争，就用事实证明游击战争在中国的自卫抗战中是能够发展的。

虽然我们有发展的有利条件，但困难还是存在的：

一、敌人的政策和他的军事技术在不断变化。我们绝不要满足于现在能够克服敌人的进攻。敌人遭到挫折就会改变，他们在军事政治经济各方面都在研究新的政策。所以，虽然今天的困难我们能够克服，还有明天的困难需要我们研究怎样克服。

二、我们活动的地区是有限的。大江南北和华北的情形不同，北方是一个广大的地区，而大江南北敌人所占领的地区是有限的。而且敌人要加紧造成电线公路网，在北岸要造铁路，以缩小我们的活动范围。

三、地形交通条件不利。

四、江南的社会环境和历史条件，不十分有利。

五、我们的力量还小。虽然一年的战斗锻炼了我们，坚强了我们，我们还是游击队。

六、友党友军不会放弃江南，这个重要地区是他们誓死必争的。

这些困难我们如何来克服呢？

一、要坚持游击战争。拿战争的胜利来克服困难。只有我们胜利的扩大，胜利的增加，才会使友党友军重视我们，使敌人畏惧我们，使国际友邦尊重我们。

二、要坚持统一战线。拿统一战线的发展来击退敌人的一切造谣中伤，团结我们周围的友党、友军、地方政府和广大民众，造成有利的工作环境。

三、要坚持强大自己。要使我们的部队发展，使我们的地位提高，使我们的力量增强，这样才便于我们在大江南北进行工作。

四、要坚持深入群众。要使大江南北广大群众知道我们是为民众谋利益，为民族谋解放的，环绕在我们周围。由劳苦群众以至上层分子，只要不当汉奸，都是我们要团结的。我们要到群众中间去埋头苦干，扩大我们的影响。

五、要坚持帮助友党友军。我们采取帮助的方法，影响的方法，使友党友军感到我们是可以合作的朋友。

这些就是我们克服困难的基本条件和基本方针。只要坚持这样的方针，我们就能够基本上克服困难。至于克服困难的具体办法，那全靠我们各级领导同志的实际运用。

三　新四军的战略、方针和任务

讲四个问题：

一、发展的方向。

我们在江南敌后地区确定发展的方向，有三个原则：

（1）那个地方空虚，我们就向那个地方发展。

（2）那个地方危险，我们就到那个地方去创造新的活动地区。

（3）那个地方只有敌人伪军，友党友军较不注意没有去活动，我们就向那里发展。这样可以减少磨擦，利于抗战。

根据过去三年游击战争的经验，我们认为，现在在跟民族敌人作斗争的时候，大江南北游击根据地的创造是完全可能的。尽管敌人封锁严密，只要我们能够深入广大的群众，善于进行游击战争，我们就不会让敌人完全占领这个地区。

二、作战的方针。

根据全国在新阶段的任务，根据新四军所处地区的情况，游击战仍然是我们新四军主要的作战方针。我们要适合所处地区的特点，对游击战术有新的发展，新的研究，新的发扬。我们的游击战术应不同于华北，也不能只运用过去三年游击战的经验，应该更加灵活，更加机动，更加出没无常，更加变化无穷。

三、建军工作。

以强大为原则，也就是说，第一要精，第二要发展。我们不能忽略精的方面，因为我们的扩充是有限制的。我们要使一个人有十个人的用处，一个干部当一百个干部用。我们走向正规军不能采取跳跃的方式，不是一下子可以成功的。干部在我们成为强大的新四军上有决定的意义。干部健全才能使工作发展。在这一方面，新四军要用很大的力量，因为现在干部的水平在军事上文化上技术上政治上都是不够的，要很好地培养和教育。

战斗动作的教育很重要，特别是夜战、白刃战。要学习跳跃、游泳，这是打游击战特别要学会的，比如攻据点时跳铁丝网，携枪游泳袭击敌人。将来我们要在长江上打击敌人，破坏敌人的运输，发扬水上游击队的特长对我们游击队的发展有重要的意义。爆炸的方法也要研究。还要学习爬城，这也是我们必须掌握的基本动作。在游击战中我们要把体育运动提倡起来。

我们要以政治工作保证建军工作的完成，巩固党的新四军的领导，保持并发挥我们的优良传统。

四、对敌人的政治经济斗争。

过去我们的中心任务，是争取游击队胜利地集中，迅速开赴前线，转入敌人后方作战。我们完成了这个任务。现在我们要与敌人进行艰苦的政治经济斗争。敌人实行以政治为主、军事为辅、开发占领区资源的政策，针对这个情况，我们有许多工作要做：

（1）尽量摧毁敌伪政权。能够破坏的应该去破坏它，能够推翻的应该去推翻它。

（2）保障恢复我抗日政权。在敌后，应该尽量帮助地方，配合地方自卫武装，恢复和保护抗日政权，并帮助地方群众团体进行工作。

（3）用一切方法动摇敌军军心，使他们部队里面反战情绪高涨，不愿意打仗，到最后五分钟不拚命。

（4）瓦解伪军。敌人从本国抽调部队到中国来是非常困难的，主要的是利用伪军，以华制华，来弥补他兵力不足的缺陷。因此，我们应该把瓦解伪军的工作放在很重要的地位，不仅在军事上消灭他，而且在政治上瓦解他，使敌人不敢运用伪军。

（5）利用维持会、伪军等做内线，为我们侦察敌情，通报消息，将来时机成熟可以里应外合。

（6）彻底破坏敌人的交通要道。这不仅有军事上的作用，而且有政治经济上的作用。

（7）爆炸敌人的矿山、工厂。

（8）封锁敌人的商业。

（9）敌人发行的伪币，我们的地区不能使用。

（10）研究在游击战中怎样加强我们自己的经济力量，譬如江南有许多棉花，应研究怎样自纺自织，供给自己的需要。

（11）组织民众，训练民众，尽一切可能的力量提高民众的文化程度、政治认识，使他们的政治军事文化水平一天天地提高起来，加强地方自治的能力。

（12）发展地方自卫武装，由不脱离生产的自卫队进而发展到游击队。

（13）争取青帮、大刀会〔125〕的群众。我们应研究这些组织，进行政治工作，争取他们。

（14）适当地改善民生。凡是跑到敌人那方面去的地主，不可以回来收租。

（15）坚决肃清汉奸。在伪军伪政府中是有两面派的，我们做这个工作的时候，要注意策略。

（16）加强宣传工作。对我们的胜利消息应该尽量地宣传，对敌人的欺骗宣传应该不放松地驳斥。敌人贴了一个布告，我们也应该贴一个布告，揭穿敌人的欺骗。这项工作是非常重要的，决不要迟疑。我们政治部以后应该听敌人的广播，好来研究对策。

（17）在大城市中建立秘密的工作。

我只能够提出这些大纲，请大家来研究讨论。在跟敌人作政治经济斗争中，有这许多工作要我们做，这方面的工作很重要，不亚于拿刀枪跟敌人斗争。我所说的是很浅薄的，仅仅是过去的一点经验和现在的一些问题。希望我们新四军的政治工作人员来共同努力，提出更多的具体材料和具体办法，表示出我们新四军不仅有模范的游击战争，而且在游击战争中有模范的政治工作，模范的和敌人作政治经济斗争的成绩。

＊这是在皖南新四军军部干部大会上的讲话摘要。

