# 在延安欢迎会上的演说

中文马克思主义文库 -> 周恩来
在延安欢迎会上的演说
（一九四三年八月二日）


同志们：
　　感谢大家的欢迎。我这三年在外，做的事实在太少了。可是在这三年中间，国际的国内的变化，我们党内的进步，却特别的多，特别的大，我们在外边也看得格外分明。
　　在国际方面，我们从法兰西投降〔193〕后欧陆所遭受的法西斯浩劫起，看到希特勒德国对于苏联所进行的背信弃义的疯狂进攻〔194〕，一而再，再而三；看到太平洋上日本强盗对于英美所进行的闪击〔195〕；看到全世界除苏联外都有法西斯第五纵队〔196〕的猖獗活动。同时，我们看到苏联红军和人民在斯大林领导之下奋起抵抗希特勒进攻的英勇战绩和生产热忱；从列宁格勒、莫斯科保卫战到斯大林格勒保卫战〔197〕，从两年的冬季反攻到今年的夏季反攻，获得了举世称赞的辉煌战绩。我们也看到同盟国抵抗法西斯侵略的阵线的形成和进步：从罗斯福、丘吉尔大西洋宪章〔198〕的公布到苏英同盟、苏美协定的缔结〔199〕，到二十六国公约在华盛顿的签字〔200〕；从英美盟军在北非的反攻和胜利直到西西里的登陆。我们又看到全世界反法西斯统治的斗争的兴起和扩大：从欧陆被侵占国中反法西斯游击战争的发展到德意国内反法西斯的罢工示威和游行的兴起；从法兰西民族解放委员会的合作〔201〕到“自由德国”民族委员会的建立〔202〕；从美国、印度共产党合法地位的恢复或被承认到日本共产党领袖冈野进〔203〕同志的来延。三年来，同盟国反法西斯的解放战争是由危而安，转败为胜，由被动的作战转为主动的进攻。这种变化主要地倚靠于苏联红军和人民的两年抵抗和三次反攻，同时，也倚靠于英美同盟军在北非的胜利和在南太平洋的积极行动，倚靠于美国的巨大生产和盟国的战争动员，倚靠于中国抗战的坚持，尤其是敌后游击战争的发展。
　　现在，墨索里尼倒台了〔204〕，意大利法西斯党解散了，世界法西斯统治在其最薄弱的一处开始崩溃了，世界法西斯主义正走向死亡。全世界反法西斯战争的胜利曙光已现，曾经猖獗一时的法西斯党徒及其第五纵队的死期是一天一天逼近了。不看见意大利法西斯党员的末路么？不看见德国第五纵队在意大利的抱头鼠窜么？这就是世界法西斯主义信徒的活榜样！这就是中国法西斯主义信徒的活榜样！
　　在国内方面，这三年来，我们依然是处在抗日战争的相持阶段中。三年来，有人以为苏德战争、太平洋战争既已先后发生，日寇今后不攻印必攻苏，决无余暇余力来打中国，于是便以消极抗战来暗示日寇不打中国，以积极反共来推动日寇移兵攻苏。可惜此计虽巧，日寇并不完全听话。日寇有日寇的国策。他虽赞成你消极抗战，毕竟你还未投降，而且武装也未解除，所以一有间隙，一有必要，他就要打到中国头上来了。他虽更赞成你积极反共，可是你尚未全面“剿共”，而且也无法“灭共”，所以日寇还得以其在华半数以上的兵力在敌兵进行“治安强化运动”〔205〕，自己来“扫荡”八路军和新四军。
　　三年来，又有人以为太平洋战争既起，美英若不是很快地打败日寇，便要以大力来援助中国，如此，中国便可坐享其成。殊不知美英不能很快地战胜日寇，已为事实所证明。而美英援助中国，固为我们大家所切望，但他们生产不易，他们首先要援助那直接参战的部队和作战有效的地方，若作战迟疑、心怀二用的部队，必然会成为他们慎重考虑的对象。而且自从吴开先由宁奔渝〔206〕，两方特务勾勾搭搭，直到昨日日寇广播竟公开地提出条件诱降〔207〕，更不能不使同盟友邦有所顾虑。
　　三年来，还有人以为抗战只要能拖，就可拖到胜利。殊不知你要拖，敌人却不让你拖。敌人要在希特勒垮台以前，至迟要在太平洋决战以前，解决中国问题，这是很明显的，而这次公开诱降，主要的就是由于墨索里尼倒台所引起。不仅敌人不让你拖，就是国内情形也不会让你拖。许多军队不开到前线，不积极作战，士气能提高么？兵役制度不改善，军队待遇不提高，战斗力能加强么？财政经济政策不改变，官僚资本不打倒，贪污腐化不惩办，囤积居奇不肃清，财政经济的破产能避免么？人民自由不取得，人民生活不改善，劳动生产力不提高，官僚政治不肃清，排除异己的压迫政策不取消，抗战后方能够安定么？这些现象不改变或消灭，中国抗战的局面能拖到胜利么？我们的回答：要胜利，不是拖而是打！要胜利，不是消极的抗战而是积极的抗战！要胜利，不是国内的分裂而是国内的团结！要胜利，不是政治的压迫而是政治的民主！
　　三年来，更有人以为内政虽坏，只要特务统治加强，便可维持抗战局面到胜利。殊不知抗战是要争取民族解放、民主政治的胜利，决不是为的法西斯化的特务制度的胜利。如果特务统治加强，那只是为日本法西斯军阀的统治开道路，决不是为中国抗战的胜利开道路。
　　照这样，三年来，国民党当局中这些想法既都错了，那末，要争取中国抗战的胜利，还有没有办法呢？我们回答：有办法！办法就出在陕甘宁边区！办法就出在八路军、新四军和敌后抗日根据地！办法就出在中国人民的身上！办法就出在真正抗日的党派和军队中间！办法就在中国共产党，尤其是我们的毛泽东同志的手中！
　　谈到抗战，我们八路军、新四军在敌后，三年来没有外来枪弹的补充，没有外来粮服的供给，没有外来医药器材的接济，全凭人民和自力更生，终年打仗，支持着这抗日的战略根据地，吸引着半数以上的在华敌人。八路军、新四军有了这种抗战成绩，就连敌人也不得不承认这是最坚强最可怕的抗日力量。这种抗日力量，难道还不值得全国其他愿意抗日的军队照样学么？凡是要想进攻和取消这种抗日力量的人，难道还不是亲日的第五纵队么？
　　谈到民主，三年来，我们党在边区抗日根据地，宣布施政纲领，实行人民普选的“三三制”〔208〕，实行保护人权财权政权的民主法令，实行减租减息、交租交息和合理负担的农村政策，实行十小时工作制，适当地改善工人生活和提高劳动生产率的劳动政策，实行志愿兵制和民兵制度，实行正确的财政经济政策和文化教育政策，并允许任何外人在尊重主权、遵守法令的原则下，得在边区参加抗日工作，进行实业、文化和宗教的活动，由此做到各根据地的自给自足直到丰衣足食的地步。这种边区，这种抗日根据地，难道还不值得全国真正愿意实行孙中山先生的三民主义和民主政治的地方照样学么？凡是要想进攻和取消这种边区、这种根据地的人，难道还不是反民主、反三民主义的法西斯么？所以凡是真正抗日的党派和军队，凡是爱国的同胞，必定会不满意于现在国民党当局中对抗战的摇摆政策，对内政的错误政策，尤其是又抗战又反共的两面政策；必定会愿意同八路军、新四军做朋友结同盟，从边区根据地采取民主政治的经验，尤其会愿意同中国共产党结成真正的统一战线。
　　所以这三年中，在全中国人民面前，在全世界同盟国家面前，我们国中究竟那个是抗战积极的军队？那个是抗战消极的军队？那里是民主政治的区域？那里是反民主政治的区域？大家心里明白。而且不仅在心里，国内外的舆论，也已经表现出来了。
　　说到这里，我们就必须提到我们党在这三年来的伟大进步。我们党在这三年做了比过去二十年还要伟大、还有更多成就的工作。对全国说，我们党两度制止了内战的危机（皖南事变〔209〕和这次进攻边区的阴谋的揭露〔210〕），坚持了敌后最艰苦的游击战争，坚强了八路军、新四军的领导及各抗日根据地的撑持。因此稳定了沦陷区人民的抗日情绪和意志，维系了大后方对抗战前途的信心和希望。对国际说，我们党不仅预见三年来的国际事变而指出世界法西斯主义必趋死亡民主国家必然胜利的前途，并且也使同盟国家认识了中共领导的八路军、新四军及其抗日根据地，才是真正反攻大陆日寇心脏的力量和基地。对全党全军全边区说，我们党领导的整风运动，收获了从来没有的思想上改造的成绩；精兵简政，收获了力量上巩固的成绩；统一领导，收获了政治上一致的成绩；拥政爱民，收获了党政军民联成一体的成绩；发展生产，树立了真正自力更生的楷模；最后，审查干部，使我们党达到了空前的巩固和团结。这一切成绩，是怎样得到的呢？是全党依靠人民的力量得到的！是全党团结在中央领导之下得到的！尤其有决定意义的，是全党团结在毛泽东同志领导之下得到的！
　　有了毛泽东同志的领导和指示，在这三年来许多紧急时机、许多重要关键上，保证了我们党丝毫没有迷失了方向，没有走错了道路。
　　没有比这三年来事变的发展再明白的了。过去一切反对过、怀疑过毛泽东同志领导或其意见的人，现在彻头彻尾地证明其为错误了。
　　我们党二十二年的历史证明：毛泽东同志的意见，是贯串着整个党的历史时期，发展成为一条马列主义中国化，也就是中国共产主义的路线！
　　毛泽东同志的方向，就是中国共产党的方向！
　　毛泽东同志的路线，就是中国的布尔什维克的路线！
　　同志们，我们有了这样的党，不应该骄傲么？我们有了这样的领袖，不应该骄傲么？但是国内有些反共分子，竟敢无耻高叫取消中国共产党，解放中国共产党，难道他们还不是日寇汉奸的第五纵队么？他们早不提迟不提，偏偏在现在公开提出。他们故意说共产国际解散〔66〕了，共产主义便不适用于中国，中国共产党便失掉靠山，中国共产党内部便要分裂了。他们这种鬼话，有人相信么？
　　共产主义是不适用于中国么？马列主义的普遍真理可以适用于全人类，可以改造全世界，为什么中国会独独除外？反共分子所以要这样胡说，就是因为他们最怕我们用马列主义的照妖镜，在中国人民面前，照出他们第五纵队的原形。反共分子所以要这样胡说，就是因为他们最怕我们用马列主义的世界观，在中国人民面前，解释中国政治经济社会诸现象，指出中国革命的真正道理。我们敢正告反共分子：共产主义不但适用于中国，而且它经过我们党的领袖毛泽东同志的运用和发展，已经和中国民族的解放运动、中国人民的实际利益结合起来，而成为在中国土地上生根的共产主义了。谁要想来摇撼它，谁就会自趋死亡。
　　中国共产党是失掉了靠山么？不错，中国共产党的产生及其发展，是得到了共产国际不少的指导和帮助的，但是中国共产党的靠山却不是共产国际，而是中国的人民。中国共产党是从中国劳动人民中生长起来的，它是存在在中国人民中间。我们党是群众的党，在今天，已有了八十万的党员，五十万的军队，并与近万万的群众在实际的战争的生活中血肉相连起来了。中国民族需要他，中国的人民需要他，谁能取消他、解散他？我们敢正告反共分子：中国共产党不仅不会取消，而且要永久地存在下去！在世界法西斯主义走向死亡的道路上，应该取消、应该解散的倒不是中国共产党，而是那些法西斯化的中国特务组织。
　　中国共产党的内部是要分裂么？反共分子一年到头日以继夜地梦想我们党会象他们一样，分成许多派系，于是遂制造许多谰言蜚语，想来中伤我们。殊不知我们党的组织是统一的，是基于主义的信仰、阶级的觉悟和革命的锻炼的，并有自觉的纪律来巩固他，决不同于国民党可以派别分歧，毫不统一。不错，我们党内曾经有过不少的错误，有过不少犯错误的分子，但是我们党正是在反对和克服这些错误的斗争中成长起来，党的思想才趋于一致，党的组织才趋于巩固。犯错误而肯改的人，自然会与党的正确路线复归一致。屡犯而不肯改的人，自然会被党所唾弃。陈独秀〔170〕、张国焘〔169〕还不是中共的创始者么？但当他们怙恶不悛，为党所开除的时候，他们何尝能分裂党，反而使党更加巩固了。这三年，我们全党的团结，在毛泽东同志领导下，经过整风学习到干部审查，已达到空前巩固的程度。我们敢正告反共分子：中国共产党不仅不会因为你们的造谣中伤而分裂，反而会因为你们的阴谋破坏而更加警觉，更加团结，更加巩固起来！我们想，抗战愈艰难，革命愈向前发展，分裂的倒不会是中国共产党，而会别有所在，并且这种例子，历史已不止一次重复了。
　　共产国际解散，有一事却须要特别说明，即是中国共产党将要更负责地更独立地解决中国革命问题。
　　我们是坚持抗战到底的。我们认为只有用自己的力量才能将日寇赶出中国去！消极的抗战，两面的政策，必致半途而废，有招致投降妥协的危险。并且只有积极的抗战，才配争取外援，才能协同盟国取得战争的胜利。
　　我们是坚持国内团结的。我们仍然准备与国民党继续进行协商，共同消灭内战的危机，解决已经存在的问题。但这种协商必须是真诚的平等的互让的，而不应一面谈判一面磨擦，一面信使往还一面调兵遣将，一面讲团结一面又要取消解散我们。若国民党有人将国共合作看作国共合一，以为非逼不能就范，这就是内战的动机，决非团结的道理。
　　我们是坚持民主进步的。我们仍然希望国民党当局改变内政的错误政策，真正实行孙中山先生的三民主义。我们也愿意在民主政治的基础上，与其他各抗日党派各抗日力量进行合作，以坚持抗战，以推动进步。
　　这就是我们党的方针！
　　同志们！我现在回来了。我要为这个方针，在毛泽东同志的领导下，继续努力，奋斗到底！


　　＊本文刊载于一九四三年八月六日延安《解放日报》。



