# 关于党的“六大”的研究

中文马克思主义文库 -> 周恩来
关于党的“六大”〔16〕的研究
（一九四四年三月三日、四日）

同志们：近半年来，大家都在学习两条路线斗争问题。在学习大革命时期的文件中，大家对党的第六次全国代表大会的看法有很多争论，而且争论得很激烈。这是启发思想的一种争论。党内思想从来没有象今天这样解放。这是毛泽东同志领导整风学习的结果，是思想上很大的进步。

我参加了“六大”的工作，是当时的主要负责人之一，按理应当比别人认识得更清楚些。我觉得，研究“六大”要有合乎历史实际情况的眼光，要有今天整风的思想方法，两者缺一，就不能得出正确的结论。对“六大”的历史情况，有些我已经记得不很清楚了，有些我已经忘记。现在在延安还有十个同志参加过“六大”，我同有些同志谈了一下，不过没有都找到一起对一对。我分六部分来讲，先说事实，事实是对的，就说对，不对的，就说不对，结论放在后面。

一　中国革命的性质、任务和前途

讲到中国革命的性质，今天似乎是老生常谈了，因为毛泽东同志在《中国革命和中国共产党》、《新民主主义论》等著作中，已经讲到中国革命是无产阶级领导的人民大众的反帝反封建的资产阶级民主革命。可是在“六大”时，这却是个很严重的问题。什么叫革命性质？革命性质是以什么来决定的？这些在当时都是问题。后来才知道：应以革命任务来决定革命性质，而不是以革命动力来决定革命性质，这个问题还是一个新的问题。本来，在共产国际第七次执行委员会扩大会议〔237〕上已经确定中国革命是资产阶级民权革命，更早，在党的第二次全国代表大会〔238〕也提出过。中国是资产阶级民主革命，可是又要反对资产阶级，这在当时就成为很难理解的问题，虽然俄国一九○五年的革命〔239〕就是这样的，但我们没有很好地研究。当时无论从莫斯科中山大学〔240〕或从西欧回来的同志又都轻视理论，所以对革命的性质问题搞不清。在今天看来是很幼稚的问题，但在当时却是严重问题。共产国际第九次执行委员会扩大会议〔241〕的精神刚传到中国，我们都去出席“六大”。开会之前，斯大林同志找我们谈话。他主要谈两个问题，一个是中国革命的性质，一个是革命的高潮与低潮。他指出，中国革命是资产阶级民主革命，不是“不断革命”，也不是社会主义革命，并以俄国的二月革命〔242〕为例说明。这样，我们才懂了。“六大”前，中国党是不懂这个问题的。从党的第二次全国代表大会到第五次全国代表大会，承认中国革命是资产阶级民主革命。而陈独秀的机会主义的观点，认为资产阶级革命是资产阶级领导的，无产阶级不是领导而是帮助资产阶级，是替资产阶级抬轿子的，无产阶级在资产阶级革命中不要争取领导权；认为帮助资产阶级革命成功，无产阶级可以得到自由、八小时工作制，以后再搞自己的无产阶级革命。这种观点实质上是旧民主主义的，是十八、十九世纪的西欧资产阶级革命的观点。用这种观点来看中国革命，领导权问题就很久得不到解决。关于参加国民党〔2〕的问题，当时有争论。有的主张参加，这是对的，但认为参加进去只是帮忙，又是错的。另外，张国焘〔169〕开始是反对参加，后来又主张至少产业工人要留在外面。他不了解广大工农群众参加进去，可以改造国民党，争取领导权。在党的第四次全国代表大会上，彭述之〔179〕认为领导权是天然地落到了无产阶级身上，是“天然的领导权”，不用无产阶级去争。这就是没有看到资产阶级在争领导权。所以在国民党第二次全国代表大会后，一九二六年三月二十日蒋介石来了个反共〔226〕，我们毫无准备。一九二六年冬的共产国际第七次执行委员会扩大会议的精神传到中国时，资产阶级已经叛变。我们党开了第五次全国代表大会，才承认了领导权要争，批评了天然领导权的说法。但争的方法是到处贴标语，喊口号，说要争领导权。这只是空的，没有实际意义。另外，有一个中国革命非资本主义前途的问题，在共产国际也发生了争论。托派认为在武汉时期就要组织苏维埃，把工会变为政权，推翻武汉政府。这是把俄国二月革命到十月革命的经验搬到中国来。斯大林同志和共产国际的多数同志则认为我们应在武汉政府中夺取领导权，而不应马上和武汉政府分裂。虽经斯大林同志的反对，托派在共产国际第八次执委会〔243〕上还是提出了他们的意见交大会讨论。当时曾在中国工作过的印度人罗易、法国人多里欧〔244〕都同意托派的意见。陈独秀虽然没有公开同意托派的意见，却认为共产国际的决议是错的，但又没有组织工农与武汉政府破裂。及至武汉政府叛变后，托派主张中国革命是社会主义革命，陈独秀〔170〕则受了这个影响。那时，共产国际派罗米那兹〔245〕来中国。罗米那兹认为中国是“不断革命”，说中国是民主革命，但一直发展下去就是社会主义革命。他说广州时期是四个阶级联合，武汉时期是三个阶级联合，南昌起义〔246〕时只有工农，是两个阶级，中间不经任何停留，不经任何阶段，一直发展下去，就是社会主义革命。这是与托派调和的论调，实质上是托派的观点。一九二七年十一月中央扩大会议〔247〕接受了这种观点，认为当时虽不是社会主义革命，但一直发展下去就是社会主义革命。罗米那兹的意见，在我们党员中间是有影响的。

当时之所以搞不清中国革命是民主革命，是因为：第一，对什么叫革命性质，革命性质是以什么来决定的搞不清；第二，中国党历史上没有从理论方面搞清这个问题；第三，国际上托派的影响以及同托派调和的观点的影响。这些问题都须要“六大”解决，“六大”正确地解决了这些问题。为什么在决议中写得这样简单呢？因为当时在党内已经有宣传：中国革命现阶段的性质是资产阶级的民权革命，如认为中国革命目前已转变到社会主义性质的革命，这是错误的；同样，认为中国现在的革命是“不断革命”，也是不对的。

讲到革命任务，就要联系到性质、动力等问题。任务是反帝反封建，建立工农民主专政。这个问题当时讨论过，工农民主专政是包括小资产阶级在内的，并不是将小资产阶级除外。以工农民主专政的政权，实现反帝反封建两个任务，基本的力量是依靠工农。这个政权是反对资产阶级的，但不是消灭资本主义。这个性质和任务的确定，基本上没有错，但不如毛泽东同志后来概括的无产阶级领导的人民大众的反帝反封建的资产阶级民主革命明确。这个阶段是很长的。毛泽东同志分析，中国自鸦片战争后就开始旧民主主义的革命，自“五四”以后是新民主主义的革命。“六大”提出中国革命的十大要求〔248〕，就是党在民主革命阶段的党纲。当时详细的党纲还产生不出来。详细的党纲应该有两部分，最高纲领和最低纲领。恰巧那时通过了共产国际纲领，就作为我党的最高纲领。“六大”的十大要求是我党在民主革命阶段中的纲领，也就是民主革命阶段的战略任务。作为战略任务来看，十大要求没有什么不妥的地方。作为策略任务来看，有些就不妥当。如第一条，反帝，是对的。第二条，没收外国资本的企业和银行，是对的，但策略上不一定采取强力没收的办法。第四条，推翻军阀国民党政府，现在抗战时期当然不提，但在整个新民主主义革命的过程中，要使革命彻底胜利，必须推翻它，这是不言而喻的。新民主主义革命的胜利，就是人民大众的胜利，国民党一党专政的政权是不能存在的。第五条，关于苏维埃，不管名词是否妥当，但苏维埃是工农代表会议，它与资产阶级的议会制度是有原则区别的。列宁说苏维埃政权不仅可以用于资本主义国家，而且可以用于殖民地国家〔249〕。毛泽东同志发展了这种思想，把它发展成为中国的代表会议制。这种政权是一元化的，不是两权并立〔250〕的。我们现在实行的“三三制”〔208〕就是各级代表会议制，是真正的民主制度。关于实行八小时工作制，是战略任务，今天在边区还实行十小时工作制，是策略问题。关于发给士兵土地，过去认为是很难实现的，今天在南泥湾就实现了。关于联合世界无产阶级和苏联，没有提到被压迫民族的问题，当然是缺点。十大要求基本上没有多大错误，就是将来到“七大”，也不会有多大的修正，不能只以抗战时期为限，因为抗战时期是民主革命的一个阶段。

关于非资本主义前途的问题，现在无产阶级领导的资产阶级民主革命将来转变到社会主义革命的问题，“六大”作了原则的决定。至于怎样转变，要看我们将来力量是否占优势和革命发展的程度而定。不能犯急性病。这与后来李立三同志〔65〕的意见完全不同。李立三同志认为只要一省或数省首先胜利，就可以转变为社会主义革命了。关于这个问题，毛泽东同志在《〈共产党人〉发刊词》中讲得很清楚。

但“六大”对中国革命的性质、任务、前途的决定中也有缺点，这就是没有把中国的情况搞得很清楚。共产国际第九次执行委员会扩大会议已经指出了中国革命发展不平衡的问题，“六大”时本来可以对这点做具体的研究，但做得不够。什么是中国的情况？半封建、半殖民地，经济上农业占主要地位，地大物博，人口众多，社会是两头小中间大，政治上是军阀战争，国家的不统一，历史上有不断的农民战争如太平天国等。如果分析了这些问题，就可得出中国革命的主要特点是武装的革命反对武装的反革命的结论。列宁、斯大林、毛泽东都是这种思想，认为殖民地问题就是农民战争问题。在中国政治经济发展不平衡的条件下，农民革命战争是可以长期存在的。当时我们不理解这个问题，没有把不平衡的问题同农民战争联系起来，对中国革命的长期性估计不足。

二　中国革命的动力和阶级关系

“六大”时阶级阵营有了新的变化，帝国主义、军阀都是反革命，资产阶级分化到反革命方面。大革命时，民族资产阶级是反对北洋军阀的，带有革命性。大革命失败，蒋介石同帝国主义勾结，同买办资产阶级勾结，并同江浙的财阀南四行〔251〕勾结，在上海、广州屠杀革命的工农〔252〕，所以共产国际第九次扩大会议指出当时的反革命是三个：帝国主义，封建势力，资产阶级。在革命的方面也有分化，城市小资产阶级动摇，有的跑到改组派〔39〕与第三党〔253〕方面。反映到党内，党员有的脱党，有的畏缩，有的则拚命、发狂。因此革命的力量主要依靠工农，当然也不是把小资产阶级除外。共产国际第九次执行委员会扩大会议说中国向两个极端急剧分化，中间阶层是动摇的。毛泽东同志在井冈山给中央的报告中也指出主要是依靠工农。当时，在城市主要依靠先进的工人，一般的大多数的工人也有些畏惧；在农村，农民也有畏惧的；城市小资产阶级（小业主、小商人、学生等）也是畏惧的。“六大”把资产阶级算成反革命，但没有主张消灭资本主义。主要依靠工农，这是对的，不能把城市小资产阶级看成是革命的主要力量，否则便会使我们的思想混乱。但“六大”对城市小资产阶级的认识是不清的，虽然承认城市小资产阶级的革命作用，在动力上又认为只有工农，小资产阶级被除掉了，把当时某些上层小资产阶级分子参加资产阶级反对派，误认为全体小资产阶级背叛革命，因而在策略观点上错误了。

“六大”对反革命方面没有分析，特别是对民族资产阶级的认识与共产国际第九次执行委员会扩大会议不同。共产国际第九次执行委员会扩大会议认为反革命内部有矛盾，可以利用。“六大”则把这一点翻过来，认为他们虽然有矛盾，但反共是共同的，因此他们的矛盾无法利用。这种认识是错的。毛泽东同志说，把敌人看成铁板一块，这是关门主义的分析方法。事实上，南京政府是大地主大资产阶级的政府。另外还有不满意大地主大资产阶级的反对派，这是当时的第三营垒。这个第三营垒不是动摇于资产阶级与无产阶级之间的中间力量（这在当时的情况下是不可能的），而是统治阶级营垒中的反对派，是政府的反对派。第三营垒开始是改组派，以后改组派跑进政府，又有史量才、杨杏佛〔254〕等代表人物。蒋介石和汪精卫在一九二八年三四月本来要一起回南京，桂系反对汪精卫，汪精卫被阻在上海反桂系、反胡汉民，那时蒋、汪的矛盾不明显，但他们之间是有矛盾的。毛泽东同志的分析是正确的。

“六大”对农村阶级关系的分析基本上没有错，但不象毛泽东同志说的那样明确。“六大”决议中说对地主是没收一切土地，对富农不要故意加紧反对，在雇农反对富农时，我们要站在雇农方面（这同后来的加紧反对富农是不同的），但对小地主、富农没有进一步分析。

大革命时是四个革命阶级（无产阶级，农民，小资产阶级，民族资产阶级）。在新民主主义革命阶段中，这四者有区别：无产阶级是领导阶级；工农是基本的革命力量；小资产阶级有动摇性；资产阶级有两重性，有时参加革命，有时反对革命。大革命时，有些带买办性的资产阶级也投机参加了，这是国共合作初期的国民党右派，不能算作革命的动力。中国的民族资产阶级在反北洋军阀时是革命的，但也有软弱性，他们同帝国主义封建势力有联系。

武汉政府当时不是工农小资产阶级的政府，还有谭延闿〔160〕、孙科〔255〕、唐生智〔256〕等代表地主资产阶级的人物坐在政府中，汪精卫则是代表资产阶级的。当时我们应把改变武汉政府为工农小资产阶级联盟当作努力的方向，当时实现这一种方向也是可能的。共产国际〔66〕把国民党看做阶级联盟，内分左、中、右三派，右派是大资产阶级，中派是民族资产阶级，左派是工农和小资产阶级，包括我们党。但是那时我们党内的机会主义者却把我们从左派划出来，叫共产派，没有根据共产国际的指示在国民党中改造国民党，争取领导权。

现在我举出几个典型人物来研究一下。

（一）胡汉民〔54〕。他是彻头彻尾的右派，是买办阶级的思想。他在广东时反对工农很厉害，反对农民组织武装队伍，站在机器工会〔257〕方面反对工人群众。他下面的大将有吴铁城〔258〕、马超骏〔259〕、古应芬〔176〕。刺廖仲恺〔4〕便是他的弟弟胡毅生〔260〕干的，而他知道。

（二）蒋介石。他在大革命时主要是买办资产阶级的思想，但也不否认他有一点民族资产阶级的思想。在一九二四年国民党第一次全国代表大会时，蒋介石的民族资产阶级性多些，是中派，但与地主买办资产阶级有关系。在国民党第二次全国代表大会到“四一二”这期间，群众起来，他便反共。一九二六年“三二○”事件时他的立场已转到大地主大资产阶级方面，变为新右派，其灵魂便是戴季陶〔55〕。“四一二”〔26〕后他便成了反革命，代表大地主大资产阶级，在表面上却仍以民族资产阶级改良主义进行欺骗。

（三）汪精卫。他在大革命时主要是资产阶级的思想，虽有时很“左”，却不赞成没收地主土地，对工农有戒心。汪精卫在大革命初期并不积极，孙中山曾说：精卫、展堂已不能代表俄国式的革命〔261〕。国民党第一次全国代表大会的宣言，是孙中山先生委托鲍罗廷〔168〕起草，由瞿秋白〔262〕翻译，汪精卫润色的。孙中山先生逝世后，汪精卫乘机积极起来，在广东又被选为国民党和国民政府主席。一九二七年汪精卫由俄国回来，并没有想反蒋。他一到上海，蒋介石就找他开会。这时陈独秀找他写了个“汪陈宣言”〔263〕，此事被蒋介石知道了，汪精卫又想不发表，而报馆已上版来不及抽回。第二天汪精卫又去开会，吴稚晖〔264〕在会上大骂，汪精卫一怒，拔腿就跑到武汉去了。就这样他成了左派的领袖，大叫革命的向左边来，这完全是投机的。抗战期间他投降日本侵略者，成为卖国贼。

（四）廖仲恺。他是民族资产阶级的激进的代表，没有买办性。他是华侨，但不大富有，对帝国主义很仇视，反对封建势力，同情农民减租减息，但对工人反对中国资本家却采取调和的态度，对反对外国资本家则是赞助的。在黄埔军校〔118〕，当我们青年军人联合会〔157〕反孙文主义学会〔140〕时，他采取调和的态度。他是激进的资产阶级革命家。

（五）邓演达〔146〕。他是小资产阶级的激进的代表，赞成土地革命，能与我们长期合作，是国民党中的左派。开始他相信无政府主义。当他从苏联回来，在讨论土地问题时，他和毛泽东同志的意见一致。他积极主张摧毁封建势力。他是农村出身的知识分子，与军队有些关系。在武汉时，若以邓演达为中心，不以汪精卫为中心，会更好些，而当时我们不重视他。大革命失败，他很苦闷，同俄国顾问一起走了，后来回国组织了第三党。虽然他在思想上是反对我们的，应该批评斗争，但在策略上应该同他联合。这人的人格很高尚，对蒋介石始终不低头。在“九一八”以后，蒋介石把他杀了。

在阶级关系的分析上，过去我们的缺点，一是公式化，一是定型化。所谓公式化，是教条地搬用俄国一九○五年反对沙皇和资产阶级立宪民主党的公式到中国来，对中国的资产阶级特别是民族资产阶级不能正确地认识，不能分析统治阶级内部的矛盾，把中国的小资产阶级看成与西欧资本主义国家的小资产阶级一样。所谓定型化，是把人定死了，不懂得人是会变的。蒋介石代表过民族资产阶级讲话，但不能把蒋介石的叛变看成整个民族资产阶级的叛变。对汪精卫也一样。看不到中国的阶级关系的复杂与变化，这是错误的。第三党是代表小资产阶级的。一九三○年邓演达回国后，曾找我们谈判合作反对蒋介石，可是我们没有理睬他，这是不对的。

至于大革命失败后，是否还可以用国民党和三民主义的旗帜问题，我也讲一下。假如邓演达没有走，仍与他合作，是还可以用国民党旗帜的。但在南昌起义之后，只有共产党是革命的，国民党叛变了，这时再用国民党和三民主义的旗帜，就会使群众的认识发生混乱。对三民主义不革命的方面应该批驳，对三民主义革命的方面应该保留下来，而我们当时却是对它全部否定了，没有给以历史的科学的分析。

三　大革命经验的教训

“六大”开会时，革命正处在转变关头，当时对许多问题是有很热烈的争论的，如对过去的主要错误机会主义、盲动主义的认识等。但时间不够，大会总共开了十天，接着就开共产国际第六次大会，没有象现在我们为开党的“七大”做准备这样多的时间。会上没有解决的问题，决定组织专门委员会来解决。当时组织了研究秋收起义〔265〕、南昌起义、广州起义〔266〕三个委员会，由共产国际东方部领导。可是许多代表已经回国，事实上也研究不出什么东西来。“六大”是把一些基本问题提出来了，做了结论，但因为研究不够，不能抓住问题的本质和中心，把问题平列了。

第一，对机会主义的分析。虽然指出了它是大革命失败的主要原因之一，但没有抓住要点。布哈林〔267〕在大会上的报告，对机会主义的错误曾指出以下三点：一、中共在与国民党合作中没有保持自己的独立性；二、对同盟者不敢作正面的批评；三、动员群众的力量不够。这三点是机会主义的错误，但当时的情况也并不完全如此。从整个大革命的过程来看，特别是一九二五年到一九二六年中，党的两次中央扩大会议都强调了我们组织上的独立性；对国民党的批评是有的，甚至有些批评是不恰当的；群众是动员起来了，在一九二七年初，我们就组织了二百万以上的农民协会会员，以后更多，工人有工会及纠察队的组织，从毛泽东同志的《湖南农民运动考察报告》也可看到群众是动员起来了。只有武汉时期，机会主义者才说群众运动过火了。当时是群众革命运动的高潮，是历史上空前的，就是在抗战期间也没有过。所以，虽然这三点是机会主义的错误，但大革命的失败，主要是没有按照共产国际的指示在国民党、政府、军队中争取领导权，搞土地革命，以武装斗争为中心。共产国际第八次全体执行委员会议对中国问题的决议包括这四点：改造国民党使工农分子大批参加进去，这就是争取党权；把农民协会变成为乡村的政权，这就是争取政权；组织七万军队，其中要包括二万共产党员，这就是争取军权；再就是要没收土地，搞土地革命。共产国际在没有把这个决议送来之前，先用电报把这四点告诉了共产国际驻中国的代表罗易。罗易收到这个电报后，不给我们党中央看，却拿给了汪精卫。汪精卫看了后大怒，骂共产国际有阴谋。罗易这种叛卖阶级的行为是和十月革命前夕加米涅夫的行为〔268〕一样的。后来中央也知道了这个电报的内容。这时离国共分裂还有两个月，如果按照共产国际的指示努力去做，还不失时机，但当时中央不重视这个指示，反觉得没有办法。身任国民政府农政部长的谭平山〔269〕以“不能纳农运入正轨”而辞职，希望国民党去整顿、改革下层政权，而不把农民协会变为乡村政权。关于军队，我们当时已经有一个军、两个师和武汉的警卫团，以当时的军校作骨干，再加上湖南、湖北的工农武装和武汉的工人纠察队，组织五万到七万军队是有可能的。还有朱德同志在江西有一个军官教育团，他兼南昌市公安局长。有这些条件不去运用，是不对的。后来军校被张发奎解散了〔270〕。对于土地革命问题，当时曾有争论，是扩大还是深入？主张深入的要在湖南、湖北搞土地革命；主张扩大的却不要在湖南、湖北搞土地革命，而要向西北发展，首先打通西北国际路线，将来经过地方自治、减租减息再解决土地问题。讲到西北国际路线，也是有历史的。在广东时鲍罗廷就主张向西北发展，不要过早与帝国主义冲突，与国际打通后，再与帝国主义作战。在当时，这个意见是值得考虑的。可是到武汉之后形势变了，当时有两个敌人，一个是蒋介石，一个是北洋军阀张作霖〔271〕。在中央内部有东下还是北上的争论。多数人的意见不主张东下，理由首先是蒋介石的欺骗在群众中还有影响，他也高喊北伐；其次是东下会与帝国主义过早发生冲突；第三是如果我们东下打蒋介石，张作霖可能从后面来打武汉。所谓北上的中心思想，是想避开湖南、湖北的农民运动，接冯玉祥〔75〕出来，与国际打通。所以四五月间，唐生智带兵继续北伐。那时对冯玉祥的认识比对蒋介石的认识更错误。当打下武汉，以武汉为革命中心来对抗在南昌的蒋介石时，听说驻中央的共产国际代表伍廷康〔272〕还跑到南昌去见蒋介石，想同他妥协。冯玉祥在北平驱逐溥仪出了皇宫以后，跑到苏联大吹自己，说自己是工农合种生出来的。共产国际对他也弄不清，相信他是农民军队的领袖。当时，武汉的环境是困难的，在敌人封锁、内部动摇的情况下，把最后的希望押在冯玉祥身上，所以对“马日事变”〔273〕并不重视。在郑州打下后，什么人都跑到郑州去会冯玉祥了。鲍罗廷、加伦〔171〕也去了。可是这时蒋介石也派吴稚晖到了郑州。冯玉祥一面与武汉来的这些人应付，一面宣布他要去徐州会蒋介石。于是武汉去的这些人一连串地跑回来。这时汪精卫、谭延闿、孙科、顾孟余〔274〕等态度全变了，国民党的人更加动摇了。共产党领导人六月三十日的让步（承认国民党在民主革命中的领导，承认共产党员参加政府是以国民党员资格，共产党员可以请假退出，工农武装应在国民党领导之下，武汉工人纠察队编入军队，取消纠察队）是投降式的让步，企图以此来挽回局面，结果更糟。从整个过程来看，党的领导在大革命初期对的多，错的少；中期有对的，也有错的，有些还是原则的错误，如对中山舰事件及北伐等问题；到大革命的后期，机会主义路线形成。说大革命时期党的领导完全错误是不对的。如果当时坚决执行共产国际的四点指示，局面不是不可以挽救的。“六大”决议对机会主义错误的总结，虽然指出它的最高表现是“不去发展土地革命和群众的阶级斗争，却只做上层勾结功夫，蒙蔽阶级的矛盾，不去夺取军队，不去武装工农，不能利用参加政权机关的机会，去为群众谋利，所以在紧急关头不去打破敌人的包围，而被敌人包围”，但与其他的错误平列，没有指出主要的问题。所以从决议来看，不能给人以深刻的印象。

第二，对“八七”会议〔15〕的总结。指出了“八七”会议的成功与成绩，也指出了有两个缺点：一是对国民党左派还保存了些幻想，一是对土地问题还不大彻底。这两点也不是中心问题。“八七”会议后，南昌起义的部队仍用国民党左派的旗帜，并不是最主要的错误。土地革命当时是决定要干的，但经验证明实行土地革命的初期是不能够彻底的，总要有一个过程。我认为“八七”会议的主要缺点是：一、“八七”会议把机会主义骂得痛快淋漓，指出了要以起义来反对国民党的白色恐怖，但到底怎样具体办，没有明确地指出，以作为全党的方向；二、“八七”会议在党内斗争上造成了不良倾向，没有让陈独秀参加会议，而把反对机会主义看成是对机会主义错误的负责者的人身攻击。所以发展到后来，各地反对机会主义都找一两个负责者当做机会主义，斗争一番，工作撤换一下，就认为机会主义没有了，万事大吉了，犯了惩办主义的错误。我认为这是主要的缺点。

第三，对一九二七年十一月中央扩大会议也总结了。我看十一月扩大会议的错误方面多于正确方面。正确方面是放弃国民党的旗帜，打出苏维埃的旗帜。事实上在十一月扩大会议以前，海陆丰已经打起苏维埃的旗帜。毛泽东同志领导的秋收起义，也不是用国民党的名义，而是用工农革命委员会的名义。这个问题实际上已经解决了。我认为十一月扩大会议的主要错误：一是认为中国革命是“不断革命”，一直发展下去没有间断地达到社会主义；二是对革命形势的估计认为是一直高涨上去；三是认为革命的方针是全国总暴动。“六大”决议对这些都批评了。“不断革命论”是那时共产国际驻中国的代表罗米那兹提出来的，我们当时并不知道。对革命形势的低潮，“六大”没有严重地指出来。十一月扩大会议还有个错误就是规定了政治纪律，这也是国际代表提出的。我们当时觉得这一条很新鲜。政治纪律是为了处罚领导起义失败的同志，当时认为毛泽东同志领导秋收起义〔275〕是失败的，曾给他处罚，解除他临时中央政治局候补委员的职务，还处罚了其他同志。事实上毛泽东同志领导的秋收起义是成功的。他把起义的农民武装和武汉的警卫团带出来，到了井冈山，创造了井冈山根据地和以后的中央苏区。南昌起义时，谭平山是共产党员，是国民党革命委员会委员长，他也因犯错误被开除出党。他被开除党籍的原因，是张国焘反对南昌起义，谭平山对一位师长说，张国焘若反对起义就把他杀掉。当时我任前委书记，这位师长来征求我的意见，我说党内斗争不能这样做。后来有人把这事告诉了共产国际代表，共产国际代表就决定把谭平山开除了。今天看来，这个处分是不完全妥当的。如果给他别的处分或送他到莫斯科去，是会好些的。当然谭平山是有错误的，但张国焘也是有错误的。张国焘当时也受了处分。我和李立三也受了处分。

第四，“六大”对于南昌起义，总结也不够。南昌起义是反对国民党的一种军事行动的尝试，中央虽指出了南昌起义五点错误，但没有指出它的主要错误。我觉得它的主要错误是没有采取就地革命的方针，起义后不应把军队拉走，即使要走，也不应走得太远。当时如果就地进行土地革命，是可以把武汉被解散的军校学生和两湖起义尚存的一部分农民集合起来的，是可以更大地发展自己的力量的。但南昌起义后不是在当地进行土地革命，而是远走汕头；不是就地慢慢发展，而是单纯的军事进攻和到海港去，希望得到苏联的军火接济。假使就地革命，不一定能保住南昌，但湘、鄂、赣三省的形势就会不同，并且能同毛泽东同志领导的秋收起义部队会合。

第五，秋收起义。各地的秋收起义，有成功的，也有失败的。农民自动起来把农会变成政权的情况，当时在湘、鄂、赣三省到处都有。后来毛泽东同志到平江、浏阳等地，起义就搞起来了。他把队伍带到井冈山。鄂豫皖、赣东北等地也都受到秋收起义的影响而搞起来了。但也有些地方失败了，如鄂西、鄂北等地，失败的原因是由于当时中央领导上还有盲动主义的错误。主要的盲动主义是在一九二七年十一月中央扩大会议以后，但“八七”会议就已有了盲动主义的因素。例如“八七”会议以后普遍提出杀土豪劣绅的口号，甚至有些地方把杀土豪劣绅当作动员的口号，以致发展为烧城市。小资产阶级革命家的狂热性，在秋收起义时，在中央领导机关中就发生了。当时一部分人由于大革命失败而产生了愤慨、报复、拚命的情绪，这也是造成盲动主义发展的因素。

第六，广州起义。这时正是反革命猖獗的时候，全国的城市在反革命手里。广州起义是广州工人与革命军人联合起来的英勇尝试。“六大”指出广州起义是大革命失败后退兵时的一战，这是正确的。当时正是汪精卫继李济深〔143〕之后统治广州，汪精卫要解散罢工委员会。工会还有一部分武装。跟张发奎从武汉回到广州的教导团的一部分，已由叶剑英同志当了团长，叶剑英同志说他们也将要被解散。同时，张发奎的军队正好开去挡黄绍竑〔276〕去了，如再等一个短时期，他们就会调一师兵力回广州解散工会和教导团。我们乘这空子把部队拖出来，并且根据情况估计，要起义是可能的，但坚守不容易。当时在广州的共产国际代表是德国人纽曼，他主张起义后坚守广州，建立苏维埃。起义的总指挥叶挺同志〔369〕是起义的前夜才请去的。叶剑英同志刚入党，搁在一旁没有被用。叶挺在起义的当夜主张把队伍拖出去，纽曼大骂叶挺动摇，说广州起义是进攻的，应该“进攻进攻再进攻”。第二天张太雷同志〔173〕牺牲。第三天大败，仓皇退出。结果张发奎回到广州，来了个大屠杀。那时如果采取退却的方针，实行有计划的退却，或同海陆丰农民运动会合，或同在曲江的朱德同志会合，都不会如此仓皇，可以保持更大的革命力量，可以保存更多的干部。

广州起义失败后，叶挺到了莫斯科，共产国际代表还说他政治动摇。共产国际没有人理他，东方大学〔277〕请他作报告，共产国际也不允许他去。这样，他就离开党跑到德国去了。这件事我们应该给叶挺伸冤。在皖南事变〔209〕时他是非常英勇的，想以个人的牺牲来保存革命的力量，比某些共产党员表现还坚决，而且迄今还未向国民党低头。

“六大”对这些问题的总结有缺点，没有抓住基本的问题，但一般的都总结了。在总结起义的经验时，反映出各地代表的一些地方倾向，即今天的所谓山头倾向。假如说到某地起义搞得不好时，某地的代表就很激动，总希望把自己的起义说得好一点。因此，就不易冷静地去总结这些经验教训。

中国党在策略的运用上所犯的错误是：在革命处于高潮应当进攻的时候，不善于进攻，如在武汉时期；在革命处于低潮应当退却的时候，不善于退却，如在广州起义时期。

四　革命形势和党的策略

关于对革命形势的估计问题，当时有过争论。中国代表曾争论到斯大林同志面前。斯大林同志说，现在的形势不是高潮，是低潮。李立三同志则说，现在还是高潮，因为各地还存在工人、农民的斗争。斯大林同志说，在低潮时也有几个浪花。

关于土地问题，当时也争论得很厉害。有人以为蒋介石也可能在中国实行俄国斯托雷平式的土地政策〔278〕。斯大林同志指出，中国不可能实行斯托雷平式的土地政策，因为蒋介石是依靠帝国主义、勾结封建势力的，他不可能实行这种改良的土地政策。

“六大”指出当时中国革命的形势是处在两个高潮之间，因为当时所有能够引起革命的矛盾，没有一个得到解决。农民的武装斗争还部分地存在，是新的革命高潮的微弱的象征，但它并没有说新的革命高潮已经到来。以后事变的发展证明，当时指出农民斗争将成为新的高潮的重要组成部分的预见是对的。一九三○年红军打下了长沙。不管红军打长沙的政策对不对，但它可以说明当时的农民游击战争处在高潮中。“六大”指出民族革命运动又在生长，是指高潮快要到来，这在“九一八”事变后也证明了。所以，我们还不能说“六大”对革命高潮快要到来的预见是性急或过早。

“六大”的争取群众、准备起义的基本策略方针是对的，同一九二七年十一月中央扩大会议的不同。“六大”当时反倾向斗争中的主要锋芒是反对左倾盲动主义与命令主义，因为机会主义已经过去了，陈独秀、彭述之又没有到会，只有张国焘一人到了，而犯盲动主义错误的人到得比较多，受批评最多的是李立三同志。虽然如此，“六大”还有它“左”的错误。

首先，对于革命高潮与低潮，有几个问题一直是模糊的：一、对革命高潮的客观条件与主观力量区分不清楚，不知道主观的群众运动对促成革命高潮到来的作用。所以后来对革命高潮的估计，往往强调有利的客观条件，而不知道主观力量薄弱是不能真正造成革命高潮的。二、没有把革命高潮与直接革命形势区分清楚，不知道革命高潮是说明起义的条件正在甚至已经成熟，但仍不是说全国可以马上到处起义。如一九三○年农村革命形势是高潮，但不能马上到处起义。立三路线的失败就因为要到处起义。三、没有把局部的高潮与全面的高潮区分清楚。所以当时虽然肯定了是低潮，但并没有很清楚地去了解这个问题。正因为没有把这几个问题弄清楚，所以我们一九二八年十月回国后，对革命高潮问题还是空洞地争论浪潮与浪花的问题。

其次，在策略方针问题上，也有几点是模糊的：一、虽然当时决定了我们是退却，争取群众，但是“六大”对于高潮是进攻，低潮是退却，并没有斩钉截铁地分别开来。二、没有弄清在总的退却中，还可以在局部的地方举行进攻与攻势防御。例如当时在井冈山就是局部的进攻，但在全国是退却的。三、没有弄清在进攻中也有退却。如毛泽东同志在井冈山时，在进攻中有时还采取退却的办法。由于对这些问题没有清楚认识，所以不能使策略更具体明确，而当时是有可能去认识这些问题的。这是“六大”的缺点。

我们对革命发展不平衡的问题没有很好分析，同这个问题相联系的“乡村中心”、“乡村战胜城市”的观点也没有产生。依据当时的实际情况与理论水平，要求“六大”产生一个以无产阶级为领导、以乡村作中心的思想是不可能的。当时虽然有了农民游击战争，但我们这种经验还不够，还在摸索。我也根据历史的经验与当时的情况研究了一下，太平天国是从乡村中发动的，占了南京才有以后的局面。还有一种“流寇”式的农民游击战争，没有占城市，终归失败。这些使我感到要以城市作中心方能长期存在。俄国一九○五——一九○七年革命失败后，农村也没有高潮，而且农村的革命运动比城市的工人运动更快地低落下去。至于其他的小国家更不用说。所以在历史上无论中外都找不到农村包围城市的经验。从我国当时的实际情况来看，正是处在整个农村革命的游击运动非常困难的时期，蒋桂战争〔33〕还未爆发，想在这种情况下肯定以乡村作中心是不可能的。

讲到乡村中心的时候，还必须联系到一个问题，即农民必须由无产阶级政党领导。但当时要党不去用主要的力量与城市无产阶级联系，而把主要力量放在农村，这是史无前例的。共产国际的一切文献，一讲到无产阶级政党的领导，就是同工人运动联系在一起的。只有中国党经过长期的实践，证明在脱离城市无产阶级的情况下，也能够锻炼成为一个坚强的布尔什维克党，这才能得出这个结论来。我们研究这个问题，不妨再从反面想一下，如果没有坚强的无产阶级政党的领导，即使以“乡村为中心”，也难免要失败，事实上也是有许多地方失败了的。当时海陆丰的力量比井冈山大，各种条件都比井冈山好，但结果还是失败了，一个重要的原因，就是由于那里无产阶级领导的思想没有展开，由于领导上还带有小资产阶级革命家的气味的缘故。

当然，我不是说乡村中心的思想永远不会产生，在“六大”以后，一九二九、一九三○年，应该产生这种观点。但一九四○年我到共产国际去，共产国际的领导同志都还担心我们离开工人阶级太远了。我说我们在农村里经过长期斗争的锻炼，有毛泽东同志的领导，完全可以无产阶级化。共产国际的一些同志听了之后大哗，不以为然。

毛泽东同志对这个问题的认识也是有其发展过程的。大革命前，有一次恽代英同志〔279〕看到陶行知〔280〕他们搞乡村工作，写信给毛泽东同志。毛泽东同志回信说：我们现在做城市工人工作还忙不过来，那有空去做乡村工作。一九二五年他回家养病，在湖南作了一些农村调查，才开始注意农民问题。在“六大”那时候，关于要重视乡村工作、在农村里搞武装割据的重要与可能等问题，毛泽东同志是认识到了的，而“六大”则没有认识。但是，关于把工作中心放在乡村，共产党代表无产阶级来领导农民游击战争，我认为当时毛泽东同志也还没有这些思想，他也还是认为要以城市工作为中心的。开始他还主张在闽浙赣边创造苏区来影响城市工作，配合城市工作，到给林彪〔88〕的信中才明确指出要创造红色区域，实行武装割据，认为这是促进全国革命高潮的最重要因素，也就是要以乡村为中心。所以，毛泽东同志的思想是发展的。斯大林同志的思想也是发展的，例如他把中国红军问题放在中国革命问题的第一位，不是在一九二八年，而是在一九三○年红军打长沙的前夜，这是接受了一九二九年红军发展的经验。

五　党的各项政策

“六大”对党的各项政策，大体上有了规定，如关于苏维埃区域的红军问题、工人工作、农民工作、土地政策等，都有单独的决定。但以现在的眼光来看，这些政策是缺乏策略观点的，深入地研究实际情况与群众观点非常不够，最明显的是不重视农村武装割据，搞军队和政权，其次是关于建党问题。毛泽东同志当时已经重视这些问题，这在一九二八年十月湘赣边界党的第二次代表大会的决议和一九二九年十二月红四军第九次党的代表大会的决议中，已经明白表现出来。

第一，关于建党问题。大革命失败以前，党的组织都是处在半公开或公开的状态。大革命失败后，在国民党区域的党要转为地下秘密党，在游击区域的党则要公开领导群众进行武装斗争。当时的建党问题，在白区是如何把公开半公开的党转为地下秘密党，在游击区域是如何以武装来建党的问题。“六大”对党的组织问题并未很好地讨论。记得我曾做了关于组织问题的报告，但那时所知道的材料也仅限于白区城市党的问题。“六大”没有认识到白区党应以积蓄力量为总的方针，只注意在组织形式上改变和缩小。但事实上党的组织仍是半公开的，如上下级关系仍是那样密切，领导机关庞大，支部仍以领导斗争为中心，不是象列宁所说的为着积蓄力量保存干部甚至可以不作声息。当时并没有这种思想。如果谁有这种意见，那时一定会说他是机会主义。工作作风是“跑街主义”的，谁跑得最多谁就是好党员，谁要坐下来多研究一些问题，谁就会被当作坏党员看。后来刘少奇同志到北方，曾批评过这种作风，当时许多同志还认为他这种批评是不正确的。关于领导机关工人化的问题，在“八七”会议后，就把与机会主义作斗争看成了简单的人事撤换，这种形式主义影响到后来关于领导机关的工人化，把工人干部当作偶像，对知识分子干部不分别看待。那时李立三同志当广东省委书记，曾说：知识分子的作用完了，今后只有依靠工农干部。所以到广州起义失败后，教导团有几百学生退到海陆丰，就没有把他们当作干部来使用，而把他们编到第四师去当兵，后来绝大多数在作战中牺牲了。关于思想斗争问题，也没有象毛泽东同志给林彪的信中那种循循善诱耐心说服的精神。在“六大”会议上是有“山头”倾向的，不能完全平心静气地讨论问题，特别是与自己有关的问题，把反对机会主义与盲动主义看成人身攻击。那时机会主义的代表是张国焘，盲动主义的代表是瞿秋白同志，两人争论不休。后来布哈林出来讲话，说就是你们这两个大知识分子在吵架，再吵就把工人干部提拔起来代替你们。他这话在当时和以后影响都非常不好，使工人干部与知识分子干部相互对立。

第二，关于工人运动。当时提出争取工人阶级的大多数是对的，并且写在决议上了。可是如何去争取？是组织赤色工会〔60〕去争取工人阶级大多数呢，还是到黄色工会里去工作来争取工人阶级大多数呢？“六大”决议对这个问题没有作明确的规定。后来在关于职工运动的决议上，决定以组织赤色工会为主。这是错误的。大革命时期，我们在上海、武汉、广州等大城市是组织了广大的工人群众的，可是大革命失败后，这些工人组织差不多都被摧垮了，即使有留下来的工会，会员数量与党员差不多，已经很少。当时存在的还有这样几种工会：一种是原来的工会，到国民党部那里去登了记，成为合法的组织；一种是原来的工会，没有到国民党部那里去登记，也还存在；还有一种是国民党派人组织的工会。当时这些工会中有的还是有群众的，再去组织赤色工会的可能性已经很小，应该是到黄色工会里去工作。关于职工运动的决议确定以组织赤色工会为主，这与中国党内对工人运动“左”的倾向和职工国际〔281〕一贯的“左”倾是有关系的，对后来党的职工运动过左起了很大影响。关于工厂委员会的组织，是企图在工人斗争中建立既非赤色工会亦非黄色工会的工人统一组织，今天看来在当时也是不可能的。

第三，关于农民运动。“六大”写了关于农民与土地问题的两个决议。关于如何解决农民土地问题是要经过一个长期摸索过程的，而且要有许多具体的办法，如毛泽东同志提出的抽多补少，抽肥补瘦，这就是很好的办法。如果根据“六大”的原则，没收地主阶级的一切土地，只分给贫苦的农民，那就必然发展到从肉体上消灭地主或驱逐地主出苏区。这样对斗争是不利的。

第四，关于苏维埃问题。从决议中看不出象毛泽东同志那样的在农村中创造苏区长期割据的思想，而是抄袭苏联的经验，看重城市苏维埃，所以仍是教条主义的。

第五，关于反帝反军阀斗争。军阀和帝国主义我们都是要反对的。但“六大”是把他们看成铁板一块，没有矛盾可以利用，不是象毛泽东同志那样特别看重利用敌人之间的矛盾来发展我们的力量。

第六，对其他党派的政策。没有加以区别，把他们一律看成敌人。如改组派当时是反对我们的，但他们同南京的矛盾是可以利用的。再如第三党，对他们在思想上瓦解我们这一点应该反对和批评，但在反蒋问题上仍是可以与他们合作的。再就是毛泽东同志所说的那时应该在城市中间发动广泛的民权主义斗争，“六大”没有着重指出这一点。

第七，关于军事运动。“六大”有一个秘密的关于军事工作的决定，没有宣布，里边有一部分是关于白军工作的。当时对这一工作的重视是非常不够的，而且把白军工作完全放在士兵当中也是一个偏向。不错，在大革命失败后，国民党军队中许多军官是反动的。但中国雇佣式军队的特点，军官在军队中是有很大作用的。“六大”认为在官长中进行工作就是军事投机。后来的事实证明，敌军大部队的哗变和投降红军，都是由于我们在军官中进行了工作。如广西李明瑞的一个师变为红军〔282〕，江西第二十六路军的起义〔283〕，都是由军官领导的。

六　“六大”本身及其影响

（一）共产国际对“六大”的影响。“六大”是直接在共产国际领导下召开的，今天对它应有个分析。我上面说的“六大”正确的地方，主要是斯大林同志的影响。这里有两点证明：一是一九二八年二月间共产国际第九次执行委员会扩大会议关于中国问题的决议，是经过斯大林同志看过、改过的，它成了“六大”的基本根据。主要的问题都是这个决议上有的，如革命的性质、动力等。二是斯大林同志在“六大”前夜曾和中国党的几个负责人谈话，具体地解释了革命性质与革命形势这两个问题。

当时在“六大”做实际工作和做报告的是布哈林、米夫等人。布哈林是共产国际书记，米夫是共产国际东方部副部长，他们对“六大”当然也会有影响。如布哈林在大会上做报告骂张国焘和瞿秋白同志，说他们是大知识分子，要让工人干部来代替他们，这是一。二、布哈林对中国苏维埃、红军运动的估计是悲观的。他认为只能分散存在，如果集中，则会妨害老百姓利益，会把他们最后一只老母鸡吃掉，老百姓是不会满意的。他要高级干部离开红军，比方说，要调朱德、毛泽东同志去学习。所以我们回国后就指示要调朱德、毛泽东同志离开红军。朱德、毛泽东同志不同意。后来蒋桂战争起来了，我们觉得红军有可能发展，就作罢了，但没有认识到这种调动是错误的。三、至于对中国富农的问题，布哈林在苏联对富农问题虽然犯了错误，但是“六大”对农民问题的决议强调了富农的封建性，又说不要故意加紧反对富农，所以没有多大坏的影响。

“六大”决议是瞿秋白同志起草的，米夫、布哈林都修改过，拿回来后秋白同志又改过。米夫的作用在这里还不大。他起的主要作用是：一、散布了一些对中国党负责人轻视、不相信的话，有影响。在“六大”筹备选举时，他在筹备选举的委员会中说过，中国党负责人理论上很弱，现在有些较强的同志如王明〔69〕、沈泽民〔284〕等，暗示可以提拔他们参加中央。当然，当时是没有什么人理他的（后来传出去说，米夫要提他们当中央委员），可是这种说法却起了影响，造成了东方大学等校学生对党的负责人轻视，以致后来发生了反中共驻共产国际代表团的斗争。二、造成了工学界限。例如他对向忠发〔285〕极力地捧，利用他放炮，要他反“江浙同乡会”等。在“六大”会后，有的代表没有走，还召集了几个报告会，王明还报告了反“江浙同乡会”的斗争。一般地说，代表们对米夫印象不好。三、在组织上起了些作用，但不是主要的。例如，在“六大”工作人员的人选上，东方部的人员多，这是有宗派的意味的。

（二）代表成份。今天看来是不很健全的。代表有七十五人，各地方的都有。到会的代表，连工作人员旁听的，共有一百十二人。不健全的地方在于：一、太重视工人成份。工人代表要占多数，这是可以的。但是，大革命中工人干部牺牲很多，有些做实际工作的领导同志又调不出来，所以很多是从支部中找来的代表。大革命后，支部负责人都是新的，老的都牺牲或离开了，所以许多人是很弱的。七十五个代表中，工人有四十一人，经过大革命锻炼的人不多。二、没有把当时有革命经验的干部集中起来参加“六大”。共产国际三月底来电通知，四月代表就要走。当时要毛泽东同志去是有困难的，但还有许多同志是可以去的，如刘少奇、任弼时〔286〕、恽代英、陈潭秋〔127〕、李富春〔287〕等同志。如果多去一些做实际工作的同志，就可以多反映一些实际问题和意见。但当时觉得国内工作更重要，所以没有去。三、有失败情绪、“山头”倾向和人身攻击等。所以讨论问题不能深入，一讨论到实际问题就闹起来。例如，当检讨到两湖起义的错误时，两湖的代表们便觉得他们的工作中也有些成绩而极力争辩。但必须说明，当时各地代表团中并没有宗派小组织的活动。

这是三个主要的弱点。代表成份不健全，问题就不能深入讨论。加之在领导上又没有少奇、泽东等更正确的同志参加。

在选举中，有多选工人为中央委员的倾向。三十六个中央委员中就有二十一个是工人。过去大革命中涌现出来的工人领袖虽然不少，但党对他们的教育不够，而知识分子干部中有许多是五四运动中涌现出来的，做了许多实际工作，有经验的不少。由于太强调工人成份，很多较好的知识分子干部参加中央工作就受到了限制，如刘少奇同志只被选为审查委员会的书记，没有被选为中央委员。恽代英同志也没有选上，到二中全会才补上。这和后来中央很弱是有关系的。但当时对选举的态度并没有什么宗派主义，如毛泽东同志和关向应同志〔288〕等得票是很多的，而张国焘和瞿秋白同志等犯过错误的，票数最少。

（三）大会时间。大会没有充分时间来研究讨论问题。代表在思想上没有什么准备，代表又不是各地选来的（只有广东来的是开会选出的，其他大多数是中央指定的），对许多决议的讨论也不充分，只是所谓原则通过交委员会在文字上修改。如果时间多一点，可能好些。

总起来说，“六大”关于革命的性质、动力、前途、形势和策略方针等问题的决定基本上是对的，所以说“六大”的路线基本上是对的。但错误的方面也不少，就是说，在具体的实际的问题上犯了许多错误：一、不认识中国革命的特点是农民斗争与武装割据，中国革命的中心问题是农民土地问题。二、不认识中国阶级关系变化的复杂性，没有把策略观点着重放在争取中间阶级上。三、不认识革命形势发展的不平衡性，因而没有重视农村工作与建党工作，虽然当时还不可能产生乡村包围城市的观点。四、没有更认真地总结过去的经验教训，从而认识武装的重要，以武装建党、建政、做群众工作，这些，毛泽东同志当时已经做了。所以说，“六大”是有原则性的错误，对以后发生了坏的影响。毛泽东同志是正确的，但是，“六大”决议在当时的影响更大，因为“六大”是全党性的，毛泽东同志还没有成为全党的领导，这是党的不幸。

我们党的布尔什维克化，是从党一产生就开始的，是逐步发展的，毛泽东同志是一个代表。“六大”正确的东西属于这方面。“六大”也有毛病，犯了一些错误。但这些错误没有形成路线错误，没有形成宗派主义，虽然一些倾向是有的。这些，对以后立三路线、宗派主义的形成是有影响的，但不能负直接责任。这是我个人的看法。

＊这是在延安中央党校所做的报告。

