# 论统一战线

中文马克思主义文库 -> 周恩来
论统一战线
（一九四五年四月三十日）


　　同志们：我想讲两个问题，一个是抗日民族统一战线的问题，着重讲国共关系，一个是统一战线的经验教训问题。合起来说，都是关于统一战线的问题。

一　关于抗日民族统一战线的
　　自从我们党提出抗日民族统一战线的主张，到去年提出联合政府的主张，有了发展，实际上是一个东西。联合政府就是抗日民族统一战线在政权上的最高形式。国民党对于我们的主张，不管是抗日民族统一战线也好，民主共和国也好，联合政府也好，总是反对的。因为他是站在极少数人的利益的立场上，反对我们代表的极大多数中国人民的利益。毛泽东同志在《论联合政府》的政治报告中告诉我们，这是两条路线的斗争。一方面是国民党政府压迫中国人民实行消极抗战的路线，另一方面是中国人民觉醒起来团结起来实行人民战争的路线。我们知道，抗日民族统一战线的酝酿时间很长，差不多“九一八”以后就逐渐向着这个方向发展。从“九一八”到现在，可以分成五个阶段。第一个阶段，是从“九一八”到西安事变〔232〕；第二个阶段，是从西安事变到“七七”事变；第三个阶段，是从“七七”事变到武汉撤退；第四个阶段，是从一九三九年国民党五中全会到去年国民参政会开会；最后一个阶段，是从我们联合政府口号的提出一直继续到现在。在这五个阶段中，国共两党在全国抗日与民主的问题上，长期地存在着原则的分歧和严重的斗争。

　　第一个阶段，从“九一八”到西安事变，有五年多时间。国共两方面斗争的中心，是抵抗日本侵略还是不抵抗日本侵略。我们这方面，在全国人民面前所提出的，是要求停止内战，一致抗日。而国民党当局，在全国人民面前所提出、所坚持的，是“攘外必先安内”，实际上就是内战的方针。“九一八”以后，我们向全国国民党的军队提议，在停止进攻、给予人民以自由权利和武装人民三个条件之下，订立停战协定，以便一致抗日。毛泽东同志在报告中已经写了。我们的号召得到了若干国民党军队的响应。例如察北同盟军〔292〕、福建人民政府〔293〕和十九路军，以后的东北军、十七路军，都响应我们，跟我们合作。其他一些地方系的军队虽然不是完全同意我们的口号，也和我们有某些合作。就连国民党中央系的军队，在江西打我们时，也有主张开到华北去抗日的。但是那时国民党蒋介石怎样对付呢？对于我们，是不断的“围剿”，更加猖狂的内战。对于那些和我们合作的友军，是进攻他们，解散他们，消灭他们。对于自己的嫡系军队，他发过这样一个命令，“侈言抗日者，杀无赦”。就是谁敢多说抗日的话，就杀了他。以后，一九三五年华北事变发生了，我们的红军主力北上了，我们就提出了抗日民族统一战线的口号和民主共和国的主张，并且在一九三六年给国民党的信〔294〕中，提议召集国防会议，发动抗战，召集民选的国民大会，实现民主共和国。在行动上，我们东渡黄河抗日〔295〕，响应那时华北的“一二九”运动〔296〕，掀起了全国的救亡运动。这时候国民党当局却调了大兵到山西阻拦我们抗日，目的是想把我们消灭在西北地方。在西安事变时，我曾经问蒋介石：“我们要求停止内战，为什么不停止？”他说：“我等你们到西北来。”我说：“我们已经到西北一年多了。”他就没有话说了。他的意思很清楚，是要在西北消灭我们。所以在西安事变前，还有山城堡的一仗〔297〕。东边也堵，西边也堵，就是要消灭我们。对于全国的救亡运动，他是极力地压迫，最后发生七君子〔95〕入狱的事。所以那时毛泽东同志写的我们党给国民党的信里说：“爱国有罪，冤狱遍于国中；卖国有赏，汉奸弹冠相庆。”虽然这样，但是因为我们不断地要求，全国人民不断地呼吁停止内战，一致抗日，所以国民党先派了两个代表到瓦窑堡来谈判，以后我们就派了代表潘汉年〔298〕同志去跟他们谈判。国民党蒋介石对谈判的想法是怎样呢？那时他是把我们当投诚看待，想收编我们，直到西安事变以前，还是这样的想法，要把我们的军队顶多编三千人到五千人。至于对国民党军队中很多愿意抗日的军队，特别是东北军，就压迫他们。蒋介石对张学良将军曾经说过这样的话：“你的责任就是剿共，不许到绥远抗战。若要不然，就把你换掉。”以后召集西安会议，陈诚〔82〕来了，蒋鼎文〔90〕也来了，是准备以蒋鼎文代替张学良的。这样就逼出来一个西安事变。对西安事变，我们党坚持了和平解决的方针，取得了张学良〔91〕、杨虎城将军〔92〕的同意，把蒋介石放回去。蒋介石本人当时具体的诺言是什么呢？就是“决不打内战了，我一定要抗日”。但是张学良送他到南方以后，他就把张学良扣起来，把杨虎城送出洋。这样一来，就激动了东北军、十七路军，几乎把和平破坏。而且他又拿军队来压迫，派特务挑拨，闹出了杀王以哲〔299〕的事情。从此可见，西安事变和平解决以后，他的内战思想还没有死，并且一直没有死过。现在还可以说一件事，宋子文〔90〕也是当时谈判的所谓和平使者，那时他答应在蒋介石出去以后，负责改组南京政府。结果这话一直到今天，已经有八年，仍没有兑现。去年我在重庆见他时，说过这样一句讽刺话，我说：“西安事变时你答应的诺言，我还没有给你宣布过。”事实证明他一直没有兑现。所以在这第一个阶段，虽然内战是停止了，和平是取得了，但这是逼出来的。这就是我们党中央、毛泽东同志的方针：逼蒋抗日。但蒋介石内战之心并没有死。

　　第二个阶段，从西安事变到“七七”抗战，大概有半年多时间。两方面争论的中心，是真正准备抗战，还是空谈准备抗战。当时我们党在给国民党三中全会的电报中，毛泽东同志在党的苏区代表会议的报告〔300〕中，都是这样说：要真正地实行民主自由，真正地准备抗战。要真正准备抗战就要有民主。我们的中心口号是以民主来推动抗战。国民党当时的方针是什么呢？是“根绝赤祸”，拖延抗战。就是要把共产党的活动消灭、根绝，就是在准备抗战的借口下把抗战拖下去。这是当时蒋介石的思想。

　　我们来看事实。在一九三七年二月，我们给国民党三中全会的电报上，提出了四项诺言、五项要求。四项诺言大意是，答应改编我们的军队，把我们的苏区改为民主的边区，停止武装暴动推翻国民党政权，停止没收地主土地的政策。五项要求大意是，要求国民党停止内战，给人民自由和释放政治犯，召集各党派会议，真正实行抗战的准备，改善民生。而国民党的回答是什么呢？就是来一个“根绝赤祸”的决议案。那决议有四条：取消红军，取消苏维埃政权，停止赤化宣传，停止阶级斗争。这个东西是双关的，因为红军改了名称，也可以说是取消红军，但红军还存在；苏区改了名称，也可以说是取消苏区，但苏区还存在。所谓停止阶级斗争，停止赤化宣传，就是不许我们在国民党统治区有政治活动。那时候一方面和平了，一方面又埋伏了文章。这个文章一直埋伏到现在，还是要取消我们的军队和政权。那时候国民党内也发生了一部分人跟我们合作的运动。这一部分人，孙科〔94〕、冯玉祥〔75〕等也在内，提出了恢复孙中山先生三大政策的决议案，但是没有被通过。那时我们曾经主张召开民选的国民大会，成立民主的政府。毛泽东同志在五月代表会上做了报告，我奉中央命令也写了一篇文章〔301〕，国内国外的民主分子都很赞成。但是国民党的回答是什么呢？搞包办的国民大会代表选举。现在准备召开的国大的祸根，就是那时候种下的。那时我们主张召开各党派会议，但国民党来了个庐山谈话会〔218〕，不是大家坐下来开圆桌会议，一道商量，而是以国民党作主人，请大家谈话一番。这个谈话会的方式，一直到上次王世杰〔302〕同我谈判时，还想采用，提议组织什么政治咨询会，结果还是谈话会。不过庐山谈话会的时候，共产党没有份，我同林伯渠〔303〕、博古同志〔368〕三个人不露面，是秘密的，现在他们提议的办法，是给个“公开”，我看就是差了这一点。我们同国民党的谈判一次在西安，一次在杭州西湖，两次在庐山进行〔304〕。谈判的对象是顾祝同〔305〕、蒋介石等人。谈判的内容是要他们承认我们的军队，承认我们的边区，承认各党派的合法地位，组织各党派的联盟，就是统一战线。国民党蒋介石的回答是什么呢？他只准我们编三个师（四万五千人），一直到现在还是这样，而且无论如何不给建立统帅部，他要直接指挥。对边区呢？开始承认了，但是抗战以后又推翻了。蒋介石有一次对朱总司令说：“你抗战了还要边区！”他想给个总司令的名义，就可以取消边区。结果平型关打了一个胜仗〔306〕，他又承认了，那是在行政院第三百三十三次会议通过的。到南方撤退，他又把这个决议束之高阁，直到现在还没有承认。对我们的党，就更荒唐了。我们要求各党派的合法地位，建立各党派的联盟，但他在庐山第一次谈话会上居然敢说：“请毛先生、朱先生出洋。”你看，他竟会这样想！我们这样好好地同他谈判，他却以送杨虎城出洋的办法来对付我们。关于发表国共合作的宣言问题，在第二次庐山谈话会上，我们带去起草好的宣言，他要动手改两句，那时候我们还客气，同意他修改了两点。但修改了他也不发表，总想把共产党合法这一点抹杀掉。要不是“八一三”打响了，就不会允许我们建立八路军总指挥部和十八集团军总司令部的组织。朱总司令和我同叶剑英参谋长到南京，开始蒋介石还没有决定给八路军的名义，但是到上海打响了，他从庐山跑回来，觉得这是全面战争了，才发表了八路军的番号，紧跟着又发表了十八集团军的番号，要我们的军队去打仗。后来宣言也发表了，但蒋介石又发表了一个谈话，一方面是承认我们，可是另一方面，还是说要取消红军，取消苏区。他说我们是一个派，不承认我们是一个党，强调要集中在国民党领导之下，还是以阿Q的精神来对付我们。

　　这些经历证明，我们的主张把全国人民振奋起来了。西安事变的和平解决，推动了全国抗战。这样，抗战是逼成了，谈判也算逼成了，统一战线也算逼成了。同时又证明，只有人民有力量才能逼成。而且还证明，蒋介石的反共思想是不变的。

　　第三个阶段，从“七七”抗战到武汉撤退，大概有一年半时间。这个时期斗争的中心，是全面抗战还是片面抗战。我们党的口号，是持久战争、人民战争，就是全面的抗战、全民族的抗战。而国民党方面呢？他们是要速决战，只许政府抗战，不许人民起来，以此来对抗我们的持久战争、人民战争的方针。首先是“八一三”后发生的对出兵问题的争论。我们党中央、毛泽东同志的方针，是要分批出兵，不要一下子开出去。我们主要是到华北开展独立自主的山地游击战争，去创造华北战场，作持久战的准备，这样才能取得胜利。而国民党要求我们一次开出去，并只指定五台山东北边的小块地方（如涞源、蔚县）为我们的防区，企图在那个山屹崂里叫日本人把我们包围消灭。

　　在全国范围内，党中央和毛泽东同志的方针是坚持持久战。而国民党呢？是幻想速胜。他们觉得，只要打几个胜仗，就可以引起国际的干涉。最大的希望是苏联出兵，次之就是英美在上海干涉。所以他们就打阵地战，把一二百万军队都调到上海，拿去拚，牺牲极大。在南京快丢失之前，蒋介石曾打电报给斯大林说：啊呀！我这个地方已经不能苟安了，请你赶快出兵吧！他还要求同苏联缔结军事协定。事实上，苏联已经帮助了中国的抗战，帮助了军火、飞机，还和中国签订了一个互不侵犯协定〔307〕，在政治上给以帮助。蒋介石实行阵地战的结果，把主力拚掉了很多，所以在南京撤退的时候曾一度动摇过，想议和，不过没有搞成，因为日本的条件很苛刻，主要的还是全国的抗战高潮已经起来了，他不敢投降。由于国共双方采取这样不同的方针和做法，结果我们在华北就创造了游击战场、根据地，而他就失掉了华北和华中的大块土地，一直到武汉撤退，在许多次的阵地战中，损伤了很大的兵力。这是战略方面不同的意见。当然那个时候在武汉，我们自己也有错误。就是说，当时在武汉做领导工作的同志，我也在内，着重在相信国民党的力量可以打胜仗，而轻视发展我们自己的力量；在战争上强调运动战，轻视游击战。所以在武汉时期，我们在长江流域的工作，没有能象华北一样，利用国民党军队撤退的时候，到农村去，发动农民，广泛发展游击战争。在武汉谈判当中，我们还是继续坚持各党派联盟的主张，就是建立统一战线组织，制订共同纲领，改革那时的政治机构。而国民党方面呢？他们提出一个政党、一个主义、一个领袖的口号，想把我们吸收到国民党里头去，加以溶化。他们那时叫“溶共政策”，好象要拿水把我们化了。国民党是水做的林黛玉，但是我们没有做贾宝玉，化不了。另外，他们提议，只要你们加进来就好了。我们说，组织一个联合的同盟是可以的，你们是一份，我们也是一份，各有独立的组织。我们进到国民党里面去，要保持我们共产党的独立的组织，也可以象大革命时期第一次国共合作一样。但蒋介石又不干，他说，党外不能有党。我们说，你那个党内就有派，党外有党有什么关系！他说，你们可以进党来作为共产派，不要在外面。他就是想把我们溶化，当然用这个办法是谈不通的。他组织三青团，我们也主张共同参加，发展青年运动，但蒋介石也不干，他就是要拿三青团把一切青年组织都取消，统一到他那里，不许有别的党派在里面活动。这当然也就谈不通。他对我们在敌后的政策，就是让我们到敌后打敌人，削弱我们。正如朱德同志那天说的，国民党在华北很快地就退走了，不能不让我们去。所以武汉时期，他答应要我们到华北、山东去发展游击战争。徐向前同志〔308〕带一一五师到山东去，还得到了他的同意。但是他看到我们的游击战争有发展，人民力量有发展，建立了根据地，就害怕，所以紧跟着就派鹿钟麟、张荫梧〔309〕带兵同我们磨擦。我们在政治上主张要改革政治，成立民意机关。他那个时候，一方面搞参政会，另方面还是一党专政，参政会只是一个“作客的机关”，并且还解散了一些人民团体。

　　在这个阶段我们可以看出，国民党蒋介石速胜论失败了，依赖外国参战也落空了，投机不成，投降又不敢。他被八路军的力量、人民的力量逼得不能不走向持久战，不能不在政治上表示一点进步。但他的投机性、反动性还是继续保留的。

　　第四个阶段，从一九三九年国民党五中全会一直到去年参政会国共两党公开谈判为止，时间整整有六年之久。我们党跟国民党争论的中心，也就是象我们党一九三九年“七七”宣言上所说的，我们是坚持抗战、团结、进步，而国民党则是要妥协、分裂、倒退。这种斗争到现在还继续进行着。我们在这六年当中，主张积极抗战，求进步，靠自己。我们一方面要求国民党能够这样做；另方面我们在敌后做出了成绩，创造了十九个解放区，发展了很多的军队，证明了我们的办法是对的，这样才支持了国民党的正面战场，推动了全国的民主运动。可是国民党在这六年中怎么样呢？是相反的，也就是我们常说的消极抗战，积极反共。毛泽东同志在这个会议的报告中，也分析了他们依靠外国帮助，等待胜利，勾结敌人伪军来制造内战的这一套。正因为这样，所以在这六年中，就有三次反共高潮，进行过三次谈判。

　　关于这两个“三”，也可以说一说。开头有一个帽子，就是国民党的五中全会。五中全会是一九三九年一月武汉撤退以后开的。我们党在那个时候去了一个电报，态度是要求进步，反对汪精卫投降，主张严整抗战阵容，刷新政治，改革政府。但是国民党五中全会的回答是，来一个《限制异党活动办法》，会上原则通过，会后国民党蒋介石又对我们军队，对边区，对共产党，对人民的活动等等，订了许多限制的办法。总起来就是：首先，抗战只有一个领导，军令政令必须统一。一直到现在还是这样主张。第二，取消“特殊化”，反对所谓“封建割据”，对边区要包围要封锁。这也是一直搞到现在的。第三，不许再叫八路军，只能叫十八集团军。这是什么意思呢？八路军是平时的军队编制，就是说平常的时候也是有的，而十八集团军是抗战时期的军队编制，既然是战时编制，那么战后就可以取消了！文章在此。但是华北的老百姓回答了他：还是八路军这个名字便当，十八集团军字多不好念。蒋介石订这一条就是他准备取消八路军的一个步骤。以后他就不断地把队伍开到华北，跟我们磨擦。先后有朱怀冰、石友三〔310〕、高树勋〔311〕、汤恩伯〔312〕这些人。并且还要取消我们的办事处，只许西安和重庆的办事处存在，其他的都要取消。因此，平江惨案〔313〕发生了，竹沟惨案〔314〕发生了，广东韶关办事处、桂林办事处也取消了。这些都是那个时期的事情。第四，不许国民党区域有共产党的组织。所以以后发现了共产党的秘密组织就破坏。不许有秘密的人民运动，而且不许宣传。所以《新华日报》〔290〕常常被检查、扣留，党中央和毛泽东同志的许多文章不许登。一九三九年国民党五中全会这个方针，一直贯彻了七个年头。我们说国民党消极抗战，积极反共，就是从那个时候开始的。当然，根子是从历史上来的。

　　有了这个帽子，底下就有了三次反共高潮。第一次，朱德同志已经说了，是从打边区、取消我们的办事处和制造平江惨案开始。最主要的是在华北，从新军事变〔315〕一直到朱怀冰和我们磨擦。以后蒋介石打不下去了，失败了。朱德同志说得很对，蒋介石就是怕一个东西，怕力量。你有力量把他那个东西消灭得干干净净，他就没有说的。朱怀冰被消灭完了，蒋介石从来没有提过这个事情。他只好捏住鼻子叫卫立煌〔98〕和朱总司令谈判，划漳河为界。第一次反共高潮过去了，就来了个第一次谈判。我们的方针是有理、有利、有节。我们打了胜仗不骄傲，还是和他谈判。我们是相忍为国。那次是我出去谈判的〔316〕。我们和他一谈判，他就想讨一点便宜。那时谈判有四件事：党的合法，边区的承认，军队的增加，还有作战地区的划分。中心是在第四条。他就是想把我们赶到黄河以北，不要新四军在长江以南。那个时候有几个“北”：山东是鲁北，山西是晋北，还有一个黄河以北。他是想把我们都往北送，这真是“投畀有北”〔317〕。那我们就不干，所以发生了严重的争论。他毫无让步。我们作了一点让步，答应皖南部队退到长江以北，也是一个“北”，叫做江北。但是他还不干，来了一个何白《皓电》〔318〕，要我们到黄河以北，也是一个“北”。他坚持《中央提示案》〔319〕，因此引起了第二次反共高潮。这是一九四○年冬天开始，是从苏北战争埋伏下来的。苏北战争是他的阴谋，他原来想先从苏北下手，后打皖南。因为苏北我们的力量小，而他有韩德勤、李守维两个军〔320〕在那里。他们企图北面一压，南面一打，我们就只有“喝水”了！那晓得他搞错了，因为苏北有刘少奇同志的领导，改正了项英同志〔61〕的错误。陈毅同志〔321〕领导军队，执行了中央的正确方针，来了一个“退避三舍”。他打来了我们就先退。后来在黄桥来了个反击，消灭了他们两个师。蒋介石捏住鼻子没有说话，但他是要复仇的。在苏北战争结束后，王懋功〔155〕就到顾祝同〔305〕那里去，布置皖南事变〔209〕，但是表面上他还想麻痹你一下。那时候我在重庆。十二月二十五日圣诞节那一天，就是当年西安事变后蒋介石被放回去的那个日子，他忽然请我去他那里，大谈我们是患难朋友，大灌米汤。我看米汤不好喝，引起我的警惕，赶紧打电报给毛泽东同志，说这里面有文章。果然不过十天，他就动手包围皖南的部队，来了第二次反共高潮。因为当时皖南领导部队的同志犯了错误，所以受了损失。他就更加蛮横起来，宣布取消新四军的番号。但是我们党在毛泽东同志领导下来了一个回击，他不承认我们承认。从此新四军变成只受共产党领导、指挥的军队，不受蒋介石领导了，于是就麻雀满天飞，从十万人发展到三十万人，从三个省的地区发展到现在七八个省。这就是第二次反共高潮。等到第二届参政会的斗争取得胜利，第二次反共高潮就结束了。从第二次反共高潮到第二次谈判，中间隔的时间很长，因为这时候正是一个复杂时期，有日苏协定〔322〕，德苏战争〔194〕，太平洋战争〔195〕，以及新疆问题〔323〕。第二次谈判是在一九四二年的下半年，但事前也有些小的接触。日苏协定订立以后，紧跟着有中条山战役，蒋介石怕中条山守不住，希望我们配合，但主要是试探我们还打不打日本，当然这完全是他的糊涂想法。我们表示配合作战，但是蒋介石又怕我们，不要我们过漳河之线，要限制我们作战，这就很难配合。他在中条山，我们在漳河北怎么样打呢？同时他又不给我们下作战命令，要我们自己打。我们要一点补充，他说，只要打，我不会辜负你们的。我们打了，他又取消诺言，食言而肥。这是一次接触。后来，太平洋战争前夜，中国的情势很紧张，日本和美国有妥协的可能，这时要开参政会，他又表示要举国一致。我们为了阻止日美妥协，表示在抗日问题上还是和他一致，所以参加了参政会。那时候有一个条件，就是要把叶挺将军〔369〕放出来（皖南事变中叶挺将军很勇敢，站在最前线和国民党斗争）。蒋介石答应了这个条件，并由张群〔324〕担保。我们要求参政会以前就放出来，他不干。我们也打个折扣，那时候董必武同志〔325〕和邓颖超同志〔326〕都在重庆，两个人就只出席一个人，他来这一手，我们也来这一手。参政会开了，他仍不放。根据最近的消息，叶挺将军被蒋介石搞到重庆戴笠的特务机关里去了。世界上最不守信义的莫过于蒋介石。这是这个时期小的交涉。到一九四二年下半年谈判以前，蒋介石还想来一套手法，因为那时候新疆问题解决了，有点得意忘形，他说：“我到西安去请毛泽东先生出来谈一谈。”后来林彪师长去进行第二次谈判。当时我们还是希望在抗战中能找到一个团结的办法，所以在一九四二年党的“七七”宣言中表示出团结的态度。蒋介石以为我们有点可以让步的样子，提出的条件更苛刻，坚持我们的军队不能多编，仍是八个师，军队编了以后党才能合法，边区要改为行政区，作战地区还要向北移动。这个谈判拖了很久，实际上是他不想解决问题。他是想继续投机，希望那时候有一个日苏战争，一旦日苏打起来，就把我们赶到北边去，实行他原来的计划，所以他就要拖。我和林彪〔88〕去见张治中〔327〕，他公开说“还不是拖”！这里头又有文章，结果拖出来一本《中国之命运》，拖出来一个第三次反共高潮。那个时候正遇上共产国际解散〔66〕，蒋介石以为我们党内会有争论，于是就投这个机，来了一个取消中国共产党，而且还来了一个包围边区，打我们的心脏。第一次反共高潮打华北，第二次反共高潮打华中，第三次反共高潮打西北。我们揭露了他，全国人民都同情我们。在国际舆论上，不管苏联也好，英美也好，都反对中国的内战。所以就把蒋介石的第三次反共高潮压下去了。国民党十一中全会以后，蒋介石在国民参政会上又表示愿意政治解决，可是来了个八字由头，说我们“破坏抗战、危害国家”。第三次反共高潮过去了，我们表示，如果他愿意政治解决，我们总是可以谈的。所以去年林伯渠同志又出去进行第三次谈判。这次谈判正值宪政运动〔328〕之期，我们就表示要实行民主和宪政，提出了政治问题三条，具体问题先是十七条，以后改为九条，其他的八条改为口头的，这样正式文件共有十二条。从西安谈到重庆，一直谈了差不多半年，还得不到结果。蒋介石就来了第二次《中央提示案》，集中起来就是要我们做三件事：第一，十个师以外的队伍全部限期取消。第二，规定要十个师集中到那里就必须到那里。第三，敌后解放区所有的政府一律都交给流亡重庆的省政府接收。这样的条件我们当然不能接受，谈判就在林伯渠同志在国民参政会报告后告一个段落。

　　从这三次反共高潮和三次国共谈判中可以看出来，国民党继续反共和内战的方针，在第四个阶段中特别明显，所以谈判时他们充满着反共思想，反共高潮时就打起来了，这就是内战。虽然这样，文章还没有了结，还有新文章：不是再来第四次反共高潮，就是再来第四次谈判。结果，不是反共高潮而是继续谈判。这个谈判不仅有第三方面的民主人士参加，而且有外国人参加；同时，谈判又是公开的。这是和过去谈判不同之点，是一个新的阶段。

　　第五个阶段，从我们联合政府口号的提出到现在。这个谈判有一个中心，就是我们提出成立民主的联合政府，而国民党要继续一党专制的政府。这是一个斗争，就是毛泽东同志报告里说的两条路线的斗争。我们的方针是，立即召开党派会议，成立临时的联合政府，战后召集国民大会成立正式的联合政府。国民党的方针是，不放弃一党专政，包办国民大会，继续一党专制。半年来斗争更加尖锐。这样的斗争更振奋了全国的民主运动，更使成立联合政府的主张为国际国内民主人士所拥护，所同情。正因为这样，所以谈判也就继续下去，于是有了赫尔利〔329〕到延安以及我的两次出去〔330〕。赫尔利在延安和我们签定了五条协定，同意我党毛泽东同志所提的联合政府的方针。这五条内容主要是：为共同打败日本强盗建设新中国，要在联合政府之下统一起来；要成立各党各派无党无派的联合政府，要成立代表所有抗战力量的联合统帅部；要给人民自由，要实行民主的改革；要承认所有抗日的力量，装备所有抗日的力量，统一所有抗日的力量（用联合政府来统一）；承认所有党派的合法地位。这样五条不仅我们提出，而且美国大使赫尔利也是签了字的。这五条他承认了，所以我到了重庆，就是为实现这个方针——联合政府的方针。但是蒋介石又拒绝了。我回延安以后，赫尔利又继续邀请，我就又出去一次，提出为实现联合政府，办法可以采取一个准备的步骤，先开一个各党各派的会议，就是国民党、共产党、民主同盟〔331〕三方面和无党无派分子的代表人物的会议，来讨论如何改组国民政府成为联合政府，如何起草共同纲领，如何废止一党专政。这一次谈判国民党蒋介石还是不同意，反而叫嚷什么“你们要联合政府就是要推翻政府，开党派会议就是分赃会议”。完全把我们的主张抹杀了。他还是要继续原来的方针。从《根绝赤祸案》到《限制异党活动办法》，历来的主张，就是要我们把军权、政权交出来。这从蒋介石今年三月一日的演说上就可以完全看出来，要我们把军队和敌后的政府都移交给他。他给我们什么呢？不是联合政府。他能够给我们的，就是参加政府去作客。这个客我们作了八年，我们还稀罕作这个客？要把军权、政权交出去，当然是绝对做不到的事。但是蒋介石还是要你这样做，他说可以给共产党合法，但那是把我们手脚捆起来的合法，手脚捆起来还有什么合法！当然很清楚地可以看到，这样的主张后面还有一手，就是三月一日宣布的要在今年十一月十二日召开国民大会，但这还是八年以前国民党包办选举的国民大会〔332〕。他名义上要还政于民，实际上是要经过召开一党包办的国民大会，通过一党专制的宪法，来承认国民党专制的合法。假使谁出来反对，他就说你是分裂，他就要统一你，你不受他统一，他就要讨伐你，这就是他所准备的全国规模的内战。他这条方针完全是和我们对立的。今天除了抗战这点上还可说是相同之外，至于如何抗战，完全是两套。我们是要胜利——彻底的胜利，要民主——新民主主义的民主，要团结——民主的团结，不但要国内的团结而且要国际的团结。国民党是另外一套，不是要彻底的胜利而是企图妥协投降，将来能用日本的资本和武器来打内战，把伪军收编过来打内战，不是要民主而是要维持独裁，不是要团结而是要分裂，在国际上是挑拨离间，企图英美帮助来一个“斯科比”〔333〕，国民党就是这一条路线。

　　从“九一八”以来的国共关系发展到今天，一般地是停止了大规模的内战，发动了抗战，这是统一战线的成功。我们创造和扩大了解放区，振奋了中国人民，推动了中国的民主运动。但是，就是在抗战之下还是有局部的内战，还是充满了反共、反人民、反民主的行动，这是国民党所实行的。这个对立斗争现在还是继续着。我们一方面反对这种反动的消极抗战的路线，另方面还是留有余地，不关谈判之门。三次反共高潮三次谈判，三次谈判后又继续谈判。谈判是为了胜利，为了民主，为了团结，这样的谈判才有作用，否则那真是谈话会了，那就不会有结果。这是长期以来抗日民族统一战线的经过情形。

二　关于统一战线的经验教训问题
　　谈到经验教训，不能不联系到十年内战时期，甚至大革命时期的一些错误问题。大革命时期我们有一个反帝反封建的民族统一战线，后来因为国民党反动集团背叛了革命，使这个统一战线破裂了。共产党——无产阶级的先进部队被打败了，不得不退入乡村，发动广大群众实行土地革命，建立工农兵代表会议形式的红色政权和工农红军。这个时期的统一战线，是反封建压迫、反国民党统治的工农民主的民族统一战线。“九一八”以后我们才转向抗日民族统一战线。所以，大革命、十年内战和抗日战争三个时期的统一战线，是有不同的形式和性质的。但是这三个时期的统一战线又都是属于新民主主义的统一战线，因为新民主主义是我们三个时期统一战线的政治基础。新民主主义的统一战线，就是无产阶级领导的人民大众的反帝反封建的统一战线。毛泽东同志说得很清楚，要建立一个巩固的新民主主义的统一战线，就是要认清楚敌人、队伍和司令官这三个问题。在革命发展过程中，由于敌我关系和斗争营垒时常发生变化，形势时常变动，所以统一战线的问题就很复杂。我们应当根据毛泽东同志所指出的这三个方面，来研究统一战线的经验教训。

　　现在先说敌人方面。

　　新民主主义革命的敌人是帝国主义、封建势力。这在整个新民主主义革命时期是不变的。可是帝国主义不仅是一个，而国内的大地主、大资产阶级又有不同的派别和集团，这些敌人又常常不一致，所以敌人营垒又是变化的。这样，我们要认清敌人就不是一件简单的事情，就成了复杂的问题。有时候敌人是合在一起压迫人民大众的。例如大革命失败，南京和武汉的反动势力合作，即所谓“宁汉合作”〔227〕的时候，帝国主义站在他们后面一致地压迫革命。但是这种情形在整个二十多年当中并不很多，许多时候敌人是分开的。“九一八”以后就很明显，日本用武力侵占中国，他们就分开了。抗战以后更加明显，英美站在反对日本方面，成为中国抗战的同盟军。所以帝国主义是有分有合，分开的时间还是长的。从国内大地主、大资产阶级来说，北伐战争反对北洋军阀的时候，南方就有些封建势力、大资产阶级和军阀到革命阵线里来投机，夺取领导权。十年内战时候，敌人对红军的进攻也是不一致的。抗战时期，英美派大资产阶级翻过来站在抗战方面反对日本，但同时又和日本勾结。这样，敌人有分有合，情况就更复杂了。特别是各阶级的代表人物更不是固定不变的。代表性改变了，本来不是敌人也可以变成敌人，常常使我们搞不清楚。蒋介石在大革命初期，起了一些一般资产阶级代表人物的作用，但在一九二六年三月二十日中山舰事件〔226〕以后，很快地就转到大地主、大资产阶级方面。汪精卫〔111〕在大革命初期，是资产阶级的代表，在大革命中期，他很激进，接近小资产阶级，但是在武汉时期，他又转到大地主、大资产阶级方面去了。总之，各阶级代表人物是能变化的。在中国整个新民主主义革命时期，帝国主义、封建势力方面变动很大，尤其以抗战时期为最。在这二十五年革命奋斗当中，我们所遇到的统一战线的变动是这样多，这样大，又这样复杂，因此就要求我们有一个清醒的头脑，善于调查研究，分析问题。以毛泽东同志为代表的思想，能够正确地认识历史发展进程中的矛盾变化，能够随时地认识敌人、分析敌人，能够提出战胜敌人的正确方针。而各种“左”右倾机会主义，就是弄不清楚这些，首先在认识和对待敌人这个问题上发生了很多错误。右的错误常常把敌人当成朋友。最明显的是北伐到了武汉，蒋介石在江西杀了陈赞贤〔334〕，向共产党开了刀以后，一天天地走向反动，很清楚的是要走到敌人方面去，但是那时候我们党内象陈独秀〔170〕这样的人，还主张继续和蒋介石合作，就没有认识这个转变关头的变动。“左”的错误常常把朋友当成敌人。内战时期，小资产阶级甚至小资产阶级的上层分子是我们的朋友，特别在“九一八”以后，就是中产阶级都可以做朋友，而“左”倾观点认为他们是敌人，并且是最危险的敌人，竟错到这样的程度。

　　有些敌人在一定条件下是有两面性的。在同他们结成统一战线的时候，有右倾观点的同志，只注意他们可以联合的一面，忘记了他们的反动性。比如抗战初期，大地主、大资产阶级的蒋介石集团参加了抗战，但还保有他的反动性。右倾的错误是替他擦粉，把他的反动性抹杀了。在一九三八年第二个武汉时期，说蒋介石集团不是法西斯，不是军阀，这就错了。蒋介石确有反动性，他是军阀，是法西斯，一定时候我们不去强调这方面是可以的，但是替他擦胭脂抹粉就错了。有“左”倾观点的同志，在转变的关头看不到变化，只注意这些敌人的反动性，看不到他们可以联合的方面。比如一九三五年在瓦窑堡会议〔335〕的时候，毛泽东同志估计到中国的资产阶级，甚至部分的大资产阶级，有转向抗战的可能，那时候“左”倾观点的同志就不相信，不懂得联合他们来推动抗战。

　　对统治阶级营垒中的不一致，要分别清楚是那一种性质的。比如说现在的大后方，反对蒋介石法西斯独裁专制的，有许多地方实力派，在这一点上当然可以跟他们联合。但是一定要懂得他们本身还是代表大地主、大资产阶级的，他们同蒋介石在反对民主这一点上没有根本的区别，在抗战不彻底上也没有根本的区别。所以，他们同蒋介石的矛盾是统治阶级营垒中间的矛盾。“左”的观点不承认这种矛盾，认为凡是敌人，在一个时期内都要一律打倒。但是，要打倒一切，就一切打不倒。

　　敌人营垒是会变化的。右的观点把昨天是朋友而今天已成为敌人的人仍当作朋友。例如刚才说的第一次武汉时期的汪精卫，以前他的确是代表资产阶级同我们合作的，但是到了武汉以后，一天一天地受到大资产阶级影响，走向反动，走到敌人方面去。有右倾观点的同志却还认为他是可靠的朋友，相信他，依靠他。“左”的观点把昨天是敌人而今天可能成为朋友的人当作敌人。例如“九一八”以前，十九路军代表大地主大资产阶级的利益在江西进攻我们，但是到了“九一八”以后，民族革命高潮来到了，在福建和我们合作。有“左”倾观点的同志还把他们当作敌人，反对他们。这些都说明了敌人营垒极不统一、极不一致，变动极大。我们应该很好地分析，运用毛泽东同志的利用矛盾、争取多数、反对少数、各个击破的方针，才不会犯“左”的右的错误。

　　再说队伍方面。

　　新民主主义统一战线，有无产阶级，有农民，有小资产阶级，有自由资产阶级，甚至有时有些大地主、大资产阶级也来参加，所以这个队伍很大，很复杂，力量不平衡，不容易统一。对这样一个队伍要弄得很清楚，要会分析，懂得怎么争取队伍的大多数，反对这个队伍中和我们争领导权的少数人，同他们斗争。不懂得这一点就要犯错误。

　　无产阶级是这个队伍的骨干。无产阶级的觉悟高，本事大，可是人数少，力量小，在新民主主义革命中必须依靠一个最可靠的同盟军——农民。农民是这个队伍的主要力量，象毛泽东同志说的，五个指头占四个。中国的战争实际上就是农民战争，离开了农民就打不好仗。北伐战争〔121〕时，军队本身也好，军队以外的配合力量也好，最大多数是农民。内战时候更清楚，完全依靠农民。抗战时期还是一样。有了农民，我们就能进能退；没有农民，进是少数孤军前进，退则没有地方可退。“左”倾的也好，右倾的也好，恰恰都是不认识农民，忘记了农民。“左”倾的错误是不依靠农民，只凭无产阶级打冲锋，结果使自己孤立。右倾的错误是依靠资产阶级，甚至依靠大资产阶级。大革命后期，在武汉时期，认为资产阶级可靠，甚至把唐生智〔256〕、冯玉祥〔75〕这些大地主大资产阶级的力量当成依靠，而不去依靠农民。第二个武汉时期，抗战初期，有一部分同志不是依靠农民，而是依靠大资产阶级，以为国民党领导的军队能够打胜仗，把主要的力量农民忘记了。这种依靠法很危险，不仅要打败仗，还会被人家俘虏。第二个武汉时期，由于中央路线是正确的，我们主要的力量在华北，所以没有象第一次大革命时候那样失败，但是危险还是有的。后来，大后方工作存在一个弱点，就是民主运动没有深入到农村。

　　城市小资产阶级在新民主主义革命的队伍中也是一个基本的力量。有了这个力量，还要跟农民结合，假使不跟农民结合，仅仅依靠工人和城市小资产阶级，也不能使革命取胜。右的观点以为依靠城市小资产阶级和工人，就可以取胜。这是不对的。“左”的观点就是连城市小资产阶级都不要。城市小资产阶级的典型代表是知识分子，认为知识分子没有作用。这也是不对的。大革命失败前后，曾经只依靠工人和城市的知识分子。譬如广州起义〔266〕，只把城市工人和以知识分子为主要成份的教导团动员起来，发动起义，没有依靠农民，也没有打算退到农村中去，所以广州起义失败了。上海起义〔336〕也是如此，想依靠城市的工人和一部分城市知识分子，在敌人力量最强的上海硬坚持，结果失败。现在我们又到了要进大城市的时候了，当然我们现在的主力军是在农村。做沦陷区城市工作的同志应该认识，要与农村配合才能进退自如，工农小资产阶级结合起来才能有力量。

　　新民主主义的统一战线队伍里面，还有一个自由资产阶级，我们叫他中间力量。毛泽东同志告诉我们，这是个软弱的动摇的阶级，无产阶级应该争取他，联合他，至少可以使他中立，但是不能依靠他。右的观点忘了农民，忘了工农群众，去依靠自由资产阶级，是错误的。“左”的观点否定与自由资产阶级的联合，也是错误的。

　　大地主大资产阶级的一部分，有时也会参加到统一战线队伍里来，但是他们带着很明显的两面性。资产阶级有他的两面性，小资产阶级也有他的两面性，但是大地主大资产阶级的两面性是更明显的，他们的反动性的那一面是根深蒂固的。因此，在与他们合作时，要随时提防他们，反对他们的反动性，绝不能依靠他们。大革命末期，武汉时期，不仅依靠汪精卫，还依靠唐生智，依靠冯玉祥，结果落了空。这是大革命失败的教训之一。当时有两种武装力量。一种是我们党的武装力量，有叶挺〔369〕的二十四师等，这是我们党直接领导的，同时还有广大的工农群众的武装，从广东到武汉，特别是湖南的工农群众有了武装，这是我们的力量。另一种是大地主大资产阶级的武装力量。那时候我们党的政策，不是面向自己的力量，而是面向大地主大资产阶级的力量，唐生智的军队，冯玉祥的军队。我记得最明显的是在武汉危急、“马日事变”以后，我们党的中央还仰望所谓农民领袖、基督将军的冯玉祥。那时共产党也好，国民党也好，就连外国的同志也好，大家都仰望他。当冯玉祥从潼关打到郑州的时候，武汉国民政府的头子就坐专车去接他，我党也派张国焘〔169〕接他去了。结果，冯玉祥在徐州和蒋介石会面，来了一个大反动，把所有的武汉的人都出卖了，于是武汉全面落空了。这就是依靠大地主大资产阶级武装力量不依靠自己武装力量的恶果。当然还有土地革命问题，不过武装是一个中心问题，这在当时是可以看出来的。第二个武汉时期，以为国民党军队不改造也可以同他很好地合作，这同样是机会主义的错误。

　　从这里可以看到，我们的抗日民族统一战线，包括无产阶级、农民、小资产阶级、自由资产阶级和一部分大资产阶级，这样大、这样复杂的队伍，如果不搞清楚，就会发生“左”的右的错误。我们党中央、毛泽东同志的领导，分析了这个队伍，把这个队伍里面的人分作三类：一类是进步力量，就是工农小资产阶级；一类是中间力量，就是中间阶层；一类是顽固力量，或者反动力量，就是大地主大资产阶级。地方实力派近乎中间，或者是中间和顽固之间，在阶级性上是接近反动派的，在反蒋这一点上又起了中间力量的作用。根据这三种力量的分析，我们订出了发展进步力量，争取中间力量，孤立、分化和打击顽固力量，也就是联合大多数，反对少数，打击最顽固的力量的方针。右的观点就不是这样。大革命末期，陈独秀主张不分左中右，怕人家说我们分化他们。大地主大资产阶级不喜欢我们分左中右，陈独秀就作了大地主大资产阶级的应声虫。不分左中右，结果左派就要跑到中间，最后跟右派跑了。第二个武汉时期重复了这个错误。一九三七年的十二月会议上，又有人主张不要分什么左中右，只要抗日与不抗日之分，抗日与亲日之分，除了亲日派以外，剩下的就是铁板一块，都是坚决抗日的〔337〕。这是受了大地主、大资产阶级的影响。所以第二个武汉时期，就把国民党蒋介石的军阀性、法西斯性都抹杀了，认为站在一起，一般高、一般美、一般漂亮。左中右是应该分的，分才对，不分不对。“左”的观点是只相信无产阶级，只相信无产阶级先锋队，脱离一切群众，自己队伍里的人不去联合。这也是不对的。所以不管是“左”的错误或右的错误，都是不懂得毛泽东同志关于左中右的分析，不懂得如何发展进步力量，争取中间力量，孤立顽固、反动力量，结果孤立了自己。这是我们对统一战线队伍的分析，我们应有这样的认识，没有这样的认识就会犯错误。

　　但是队伍光分左中右还不够，还要有进一步的严格的区别。这样大的队伍，在无产阶级以外，有农民、小资产阶级、自由资产阶级，甚至有时候还有大地主大资产阶级来参加，就应该有一个严格的区别。无产阶级在这个队伍里是带队的，起领导作用的，其余的阶级都同他有区别。不但大地主大资产阶级和自由资产阶级，就是小资产阶级和农民，也都同无产阶级有区别。所以毛泽东同志就指出，在统一战线中应该坚持独立自主。独立自主，就是指无产阶级的独立性，他有自己独立的政策、独立的思想。他是去联合人家，而不是同化于人家。有了区别，就有斗争。无产阶级在统一战线中的团结，是在坚持独立自主的条件下同人家讲团结，而不要受其他阶级的影响。毛泽东同志常说，我们在统一战线中最容易受别的阶级的影响，所以不主张区别是不对的。右的观点就是不主张区别。抗战的武汉时期，有人主张我们是“求同而非异”，就是说只有同而没有异。这是不知道我们无产阶级和别的阶级不同。有些同志不懂得这个统一性和区别性的道理。假如不区别，那就是和人家混合在一块，一定受人家的影响。“左”的观点是天天讲区别，不去和人家共同行动，急于搞社会主义，土地革命时期就要进行共产主义教育，要使一切人都具有社会主义的思想，不懂得应该进行新民主主义教育，就是无产阶级领导的人民大众的反帝反封建的新民主主义教育。右的不区别，“左”的强调区别而不去求得今天统一的方法，都是不正确的，都是受了别的阶级的影响，不是真正的无产阶级的思想。右的错误是受了大资产阶级的影响。因为和他合作，就容易受他的影响。他们的态度好一点，请我们作客，吃茶吃饭，就不去区别了，就把大资产阶级大地主的主张当作自己的主张提出来了。毛泽东同志说过，右的错误，一般地说，在与资产阶级联合的时候比较容易发生；“左”的呢？一般地说，在与资产阶级分裂的时候比较容易发生。这在我们党的《关于若干历史问题的决议》上也这样指出了。同时，因为我们党内小资产阶级出身的成份多，在我们困难的时候，在受了大资产阶级压迫的时候，容易受小资产阶级直接的影响，容易有“左”倾情绪。这些都是受了别的阶级的影响而产生的错误。

　　再说领导权的问题。

　　无产阶级比别的阶级先进，是应当领导别的阶级的，这就是毛泽东同志说的“司令官”。但无产阶级也不是天然的司令官，不是从农民一直到大资产阶级都公推你、公认你为司令官。大革命时期有一个彭述之〔179〕，他写了一篇文章，说无产阶级的领导权是天然的，不要争！这和毛泽东同志关于争领导权的思想完全相反。领导机要用力量来争，因为领导权是有人和无产阶级争，和共产党争的。不但大资产阶级争，自由资产阶级也争，小资产阶级也争。他们总要照他们的思想来领导这个队伍。但是和我们争领导权最主要的力量，还是代表大地主、大资产阶级的国民党这个统治集团。所以在统一战线当中，互争领导权的主要是国共两党，大资产阶级就成为我们斗争的主要对象。因为一个队伍有两个司令官，就要打架，两个中间总要下去一个。在大革命初期，国共两党曾经联合成一个队伍，大革命失败以后，就分了家，成了两个队伍。一直到现在还是两个队伍。一个是无产阶级，共产党为代表，所领导的队伍，发展到今天有了解放区，有了人民的武装。另一个是大地主大资产阶级，国民党为代表，所领导的队伍，十八年来国民党实行一党专政的统治。这两个队伍在那里斗争，双方争取的对象就是农民、小资产阶级、自由资产阶级。有人说我们只争取农民和小资产阶级，这是不对的。我们还要争取自由资产阶级。双方进行争取和领导的方法是不同的。国民党是采取压迫的方法，不但压迫工农，也压迫小资产阶级、自由资产阶级。我们的方法是同一切可以争取的力量合作。我们和农民的关系搞得最好，和小资产阶级的关系也很好。至于对自由资产阶级，领导的方法有所不同，就象和友军的关系一样。大革命初期、中期就是这样的方法。这里头有一个问题，就是自由资产阶级并不那样听话，常常闹独立性。所以我们对自由资产阶级的领导，只能是主要问题上的领导，而不可能是完全的领导。当然，在另一种条件下，我们对自由资产阶级，不但实质上可以领导，而且形式上也可以领导。如在解放区，自由资产阶级就可能在形式上也受我们的领导，但他的独立性还是要保持的。

　　大地主大资产阶级有时是不是可以受我们领导一下呢？从历史的经验看，一时的或一个问题上的领导也是可能的。一般地说，当他们的力量小的时候可以受我们领导。譬如蒋介石在一九二六年三月二十日以后，就不愿受我们的领导了，但他没有力量北伐，就叫我们帮助他，叫苏联帮助他。这时还受我们领导，但这是靠不住的，因为他表面上受你领导，实际上他准备和你分裂。又如那一天朱德同志报告中讲的，当华北敌人九路围攻的时候，国民党的军队处在很困难的地位，他就要我们朱总司令领导。但那是一时的，一旦他和他的后方打通，就要跑掉，反而来打我们。所以我们应该时常警惕。在要不要抗战的问题上，蒋介石受了我们的领导，就是我们推动了他抗战。但是如何抗战，他要按他的办法，不愿意照我们的办法，不受我们的领导。大地主大资产阶级仅在不得已时、在某一个问题上能受我们领导，他们一旦有了力量，有了外援，就会立刻和我们分裂。所以在领导权的问题上，无产阶级领导农民、小资产阶级，可以搞得很好，很亲密。对自由资产阶级，虽然他闹独立性，但是还可以领导。对大地主、大资产阶级，一般地说不能领导，只能在某个问题上、某个时期内领导。

　　我们党在历史上几个时期的许多成功，都是因为执行了毛泽东同志关于领导权问题的思想和路线。“左”右倾机会主义在领导权问题上翻的跟头最厉害。可以说“左”倾右倾都不懂得领导权问题，不懂得争取这个领导权。

　　右倾观点是不要领导权。大革命后期的陈独秀，就是不要领导权，认为只要说一句风凉话，所谓天然领导权就够了，实际上他觉得既是资产阶级革命，领导权就是资产阶级的，无产阶级顶多是抬轿子的，顶多搞一些集会、结社、言论、罢工的自由。在农民问题上，陈独秀连减租减息都不赞成，更谈不到解决土地问题了。那时贴了很多标语，有两个口号，一个是要建立无产阶级的领导权，一个是要争取非资本主义的前途。我们党的第五次代表大会，这样的口号也有很多。但口号是口号，而实际上是放弃领导权，认为领导权是天然的，用不着争。所以在政策上就不发展工农武装，不建立工农领导的政府。虽然那时候湖南、江西、湖北等省，还有一些县政权是归武汉政府的，但是陈独秀压制工农斗争，一切都退让，退让的结果使大革命失败了。这是第一个武汉时期的错误。

　　第二个武汉时期的错误也是不懂得这个领导权问题。那时有一种解释，说只要抗战就是统一，说蒋介石的政府已经是统一的政府，蒋介石的大资产阶级的政府已经开始民主化，人民已经得到充分自由。这就是说，大资产阶级很好，很民主，很统一，也就是承认大资产阶级的领导权，因而在政策上也就不要民主改革，不要改善民生。但当时党中央是很强调民主改革、改善民生这两点的。武汉时期放弃领导权，还表现在不重视敌后的发展，不主张建立敌后政权，主张一切经过统一战线。假若这个统一战线是我们领导的，当然很好。但实际上，国民党并不承认我们的领导。他所承认的统一战线，就是把我们领导的队伍统一到他的军令、政令里去。所以一切经过统一战线，实际上就是一切经过国民党的军令、政令。那时提出了七个统一〔338〕，就是统一指挥，统一编制，统一武装，统一纪律，统一待遇，统一作战计划，统一作战行动。这不是都统一于国民党的军令吗？还不是都统一给他吗？又如提出晋察冀边区也必须经过国民党批准才能成立。这还不是统一于国民党的政令吗？这样退让政策的结果，在武汉被解散了三个群众团体〔339〕，后来在华中弄出来一个皖南事变〔209〕。这就是没有照毛泽东同志说的要时刻提防人家反对我们，不是把国民党的主张提高到我们的主张上来，而是把我们的主张降低到国民党那方面去，也就是争取领导权上犯的右倾错误。

　　“左”倾机会主义也在领导权问题上翻了很多跟头。简单说来，就是他们不懂中国革命的新民主主义性质，以为已经越过俄国一九○五年到一九○七年的阶段，急于转变，争取非资本主义前途，空喊无产阶级领导。政策“左”了，不仅脱离了小资产阶级群众，而且脱离了工农群众，造成了严重的损失。抗战时期的某些“左”倾观点，也是在这些问题上弄不清楚，只要斗争，不要团结，没有认识毛泽东同志关于在统一战线中有团结有斗争，在斗争中有理、有利、有节的策略原则。

　　所以领导权的问题，是统一战线中最集中的一个问题。右的是放弃领导权，“左”的是把自己孤立起来，成了“无兵司令”、“空军司令”。可以说右倾是把整个队伍送出去，“左”倾是把整个队伍推出去。

　　以上是从历史经验检讨中得出来的全面认识。我自己在三个时期特别是后两个时期中，犯了不少的错误。今天我讲统一战线的经验，觉得应该看到错误的严重性。当然这些错误已经改正了。假使今后对敌人、队伍、司令官这三方面不能清楚认识，不管在那一点上还存在着不自觉或盲目性，那一点上就会犯错误。我个人是如此，对我们全党同志也是如此。



　　＊这是在中国共产党第七次全国代表大会上的发言。



