# 关于国民党二中全会的谈话

中文马克思主义文库 -> 周恩来
关于国民党二中全会的谈话
（一九四六年三月十八日）


　　诸位先生：在政治协商会议〔345〕之后召开的国民党二中全会，我们曾寄以很大的希望，但二中全会的结果实令人失望，因二中全会的决议动摇了政治协商会议的决议。国民党内为数不少的顽固派利用二中全会通过了很多重要的违反政协决议的议案，这不足为怪，而可怪的是这两个会议的决议既如此相反，却都是在蒋主席主持和领导之下通过的。
　　一、关于保障人民权利问题。在政协开会时，蒋主席曾作了保障人民权利的四项诺言〔346〕，但在政协开会后，就连续不断地发生了沧白堂打人〔347〕、较场口事件〔348〕、捣毁新华报馆〔349〕、捣乱西安第十八集团军办事处〔350〕，一直到捣乱执行停战决议的北平执行部事件〔351〕。这许多事件至今没有一件得到解决。如言论、出版的自由问题，限制言论自由的法令名义上虽已废止，但实际上仍限制重重，并且采用了极不平等的限制办法。象中共在北平出版的《解放》三日刊受到非法的禁止，而别的新出版的报纸在上海则得到许可。又如释放著名的政治犯，除叶挺〔369〕、廖承志〔352〕外，不论中共或其他党派及无党派被捕的人和青年学生，至今仍毫无消息。现在的政府仍然是国民党一党政府，这些违反保障人权的事件，国民党负有责任，但二中全会对这些问题一字未提，所有决议案中，没有一字谴责这些妨害人权的罪恶行为。
　　二、关于改组政府问题。改组政府是件大事，究竟是否结束训政〔340〕走向宪政，在此过渡期间成立举国一致的各党派合作的政府，二中全会无明确态度。它不仅避开结束训政不谈，反而要把各党派推选的国府委员拿到国民党中常会去选任，这是完全违反政协决议的。这不能不令人怀疑到二中全会后将要“恢复”的中央政治委员会的性质，很可能“恢复”到从前指导国民政府的政治委员会去〔353〕。果如此，国府委员由国民党中常会选任，中政会又要指导国民政府，这说明政府仍是一党的政府，决不是民主的各党派合作的政府，与政协会议、各党各派、社会贤达、全国人民以及友邦的期望完全背道而驰。
　　三、更重要的是关于宪草问题。宪法关系中国今后是民主或仍是一党独裁的大问题。政协修改宪草的原则〔354〕是各党派及无党派代表全体起立通过的，对这些原则如有任何变动，一定要经过政协各方代表的一致协议。国民党中有些人特别指责宪草修改原则不合于五权宪法〔355〕。我们且不说这些修改原则是在蒋主席主持下，经政协代表（包括政府代表在内）全体起立赞成通过的。即从五权宪法本身来说，五权宪法，第一是主张五权分立，孙先生是反对中央集权于一人或一院的。第二是地方均权，某些权应归中央，某些权应归地方，故孙先生主张实行省自治并得制定省宪。可见政协的修改原则是与孙先生的五权宪法原则完全符合的。至于根据这些原则如何规定政府组织，那就要因时间与条件而定，过去的办法不一定适合现在。如说孙先生遗教的一个字也不能修改，那么，国民党今天所做的，就违反了建国大纲〔356〕。根据建国大纲的程序先实行县自治，然后实行省自治，在全国有过半数省自治后，才可以召开国大，实行宪政。现在政府并没照这程序做，可见政府的组织程序是可以变动的。虽然如此，我们还是与国民党协商。为了减少国民党内主张民主和平团结统一的人士在其党内所遇到的困难，最后各方又商得了三个协议〔357〕。但这种让步，反而增加了顽固派的嚣张。二中全会对于宪草通过了五点修正原则，所增加之两点半关系至大〔358〕，其目的就是推翻政协修改宪草的原则，不受政协拘束。另外，吴稚晖先生〔264〕又提出了三点反对意见，立即在二中全会上成为决议。他主张“五五宪草”〔142〕，政协协议事项，二中全会决议……一并提交国大参考，这是与政协决议完全相反的。按政协决定，只能将宪草审议委员会的修正案提交国大，并无其他，国大代表个人虽自由，但各党派要负责约束其自己的党员，使这个民主的宪草得以通过，这样，包括十年前一党包办的旧代表的国大〔332〕就不是重要的了，重要的还是要保证能通过一个真正民主的宪法，所以在国大问题上，各党派曾向国民党作了极大的让步。但今天，国民党却想利用各党派承认的国大，反转来反对政协决定的宪草修改原则，来动摇民主宪法的产生。这种违反民主的做法，是任何人不能忍受的。
　　四、国大问题。国大代表中地区代表还未最后确定，国大组织法也还没有修改，根据政协决议，国大的职权只限于制宪，而宪法要有四分之三的多数才能通过，但国大组织法如再迟迟不改或改而不当，就很有可能被利用，只有三分之二的多数就可以通过决议，来做更多其他不利于民主的事情。这样，将来的国民大会就会更便于做一党专政的保镖。
　　五、整军问题。在政协会议中，军政部次长林蔚氏报告，政府军队现有三百八十万，要减到一百八十万，编为九十个师。但在二中全会中，同一人的报告则说政府军队及机关学校现有四百九十万，将来只减到三百四十七万，仍编九十个师，这和在政协报告中的数目比较，多出了一百六十七万。即去掉机关学校，仍然会多出很多，那就是所谓兵工总队，成为正规军的后备队或补充队。这是违反政协决议和整军方案〔359〕中复员计划的，因这既不能减少国库开支，且将保持额外的一部分队伍，完全与复员精神相反。
　　六、停战问题。国民党二中全会在宣言上要求中共部队即速停止继续攻袭，但实际上究竟是谁不遵守停战命令〔360〕实行继续攻袭？只要听到方才林、郑两位〔361〕关于广东、湖北情形的报告，就很清楚了。在山西，任何人都可看到，太原、大同的日军到现在还没有被解除武装，因为阎锡山氏〔96〕还在利用他们攻打中共和解放区的军民。在华北、华中其他地方，继续进攻和蚕食中共地区的村镇的事，还在不断发生。
　　关于东北的情形，马歇尔将军〔362〕在两个月前曾提议派遣执行小组去东北调处军事冲突，当时我们立即赞成，政府却在最近才同意了这个提议，可是又发生了执行小组的任务问题。我们曾提出了两个解决办法：一个是无条件派遣执行小组去，立刻停止一切军事冲突，并调查当地实际情况，把问题带回来提供三人会议〔363〕解决。另一个更好的办法是先在重庆谈判关于军事、政治问题解决方法的一般原则，然后再派遣执行小组根据已经谈好的原则去具体执行。这两个办法，都还没商得结果。我们向来主张东北的内政与外交问题应分开解决：外交问题，过去一直是政府负责的，现在依然如此；但是内政问题，大家都有责任，必须用政治方法和平解决。这不仅仅是中共的意见，这也是其他民主党派和东北人民的意见。
　　以上所说的绝大部分，都是国民党二中全会所表现的。国民党内顽固派有意识地破坏政协整个决议，并不奇怪。但是，亲自主持政协的蒋主席，竟使顽固派的要求得在国民党二中全会中通过，实使我们奇怪。虽然，国民党二中全会的决议中也有表示要执行政协决议的话，但是容许了上述反政协的决议存在，实际上就等于取消了前一可能。同时，国民党二中全会的决议又着重于反共，说中共如何如何。中共愿坚决实行自己签了字的停战协定、政协决议和整军方案，也愿意朋友们善意地（而不是恶意地）来督促我们。但是我们要反转来问问国民党朋友，你们一方面要求人家来做，另一方面又把违反政协决议的东西写在国民党二中全会的决议上，这不能不说其中包含了欺骗。骗什么呢？就是想模糊过去。要是在这种情况下，各党派参加了政府，国大开成，宪法照国民党二中全会的要求通过，中国不就是“民主”了吗？！然而这是不可能的！我们不受骗，也决不去骗人民。我们要向人民说真话，谈实事，一定要先弄清楚国民党二中全会的决定是想做些什么？这不是一个人或一党的问题，而是要不要欺骗老百姓的问题。我们不能把没有完全和平对人民说成有了完全和平，还没有民主说成有了民主，还没有稳定说成已经稳定。
　　我们同意马歇尔将军说的：中国在今后几个月内，将是一个极严重的时期。照国民党二中全会决议发展下去，将会更加严重，不能象某些国内外舆论那样的乐观。但情势不是不能更改，这须要全国人民的努力，友邦的帮助，特别是政协各方代表要努力来维护政协决议。
　　此外，亦如马歇尔将军在华府招待记者席上所说：国民党当权一派，不愿把大部分权力交出来。其实政协决议并未要求国民党交出大部分的权力，只是要求人民能有自由权利，如各党派在政府中能有充分代表性。现在国民党无论在中央政府，在各省乃至在国大中，仍占第一大党地位。可是就是这一点点民主，顽固派还是不愿意让人民享有，只是压迫和打击人民与其他党派的民主运动。而且照杜鲁门总统的声明〔364〕及三国外长会议公报〔365〕中所指的内容来看，也可见政协决议还没达到那样的民主要求。现在军队整编统编方案是有了，但是组成一个有充分代表性的政府仍未做到，就连政协决定的这样一点点民主，国民党还不愿实行，还要由国民党中常会来选任国府委员。
　　因此，我觉得政协的一切决议不能动摇或修改，这是由五方面代表〔366〕起立通过的，应成为中国的民主契约。谁要破坏，谁就是破坏今天中国的民主和平团结统一。对三人会议关于停止冲突与军事小组关于整军方案的协定，也是一样的。人权若无保障，就无法改组政府成为真正的民主合作的政府。修改宪草，各党派如不受约束，如不照五方通过的修改原则制成修正案，国大一定开不好。军事冲突，若不在全国范围内停止下来，和平也无保障。我们要求的是一个真和平、真民主、真稳定的中国。
　　我们愿号召全国人民、盟邦朋友、各党派朋友，一致来拥护并监督政协全部协议的实现。特别希望国民党内主张民主团结的朋友，在蒋主席领导之下，来纠正和推翻党内这种反政协的企图。且这种企图现在已成为决议，快要实行了。我们应提醒国民党的朋友，因为国民党对今天的政治是负有最大的责任的。由于这一缘故，在国民党二中全会闭幕之后，来做这一声明，是有必要的。我们不愿蒙蔽舆论，而愿诉诸舆论。


　　＊这是在重庆中外记者招待会上的谈话，刊载于一九四六年三月十九日重庆《新华日报》。



