# “四八”烈士永垂不朽

中文马克思主义文库 -> 周恩来
“四八”烈士永垂不朽
（一九四六年四月十九日）

若飞〔367〕！博古〔368〕！希夷〔369〕！邓发〔370〕！黄老先生〔371〕以及一切遇难的中美朋友、同志和扬眉〔372〕！你们集体牺牲，你们已成了“四八”烈士。

十天过去了，沉重的十天！沉痛的心，悲愤的泪，残酷的回忆，还有，你们遗留下来的沉重的担子，抑压得我们还只在默默无言中悼念你们。

二十多年来，成千成万的战友和同志，在共同奋斗中牺牲了，但没有一次象你们死得这样突然，这样意外。突然的袭击，意外的牺牲，使我们更加感觉到这真是无可补偿的损失！

二三十年为中国人民解放事业的奋斗生涯，已经把你们锻炼成为人民的英雄，群众的领袖，青年的导师和坚强不屈的革命战士。你们中，象若飞等七位同志，都经过一二十年共产主义党的教育，已成为久经考验永远忠于人民事业的党的优秀领导者和党的骨干。你们是中国人民的瓌宝，你们是中国共产党的光辉。现在竟活生生地把你们从我们中间夺去，从中国人民中间夺去，这是中国共产党的最大不幸！这是中国人民的最大不幸！

抗战胜利后，若飞等同志为中国的和平团结民主统一的事业，努力奋斗，奔走呼号，从未息止。双十国共会谈纪要〔373〕、政协五项决议〔345〕、停战协定〔360〕、整军方案〔359〕，直至三月二十七日的东北停战协定〔374〕，都有着若飞同志的共同筹划以及其他同志的后来参加。尤其近两月来，为保障人权，为保护政协五项决议，为坚持宪草修改原则〔354〕，为反对破坏停战协定，若飞、博古两同志更站在斗争的前线，与一切破坏分子的反动阴谋作最坚强的搏斗。四月八日飞回延安，也正是为保护政协决议、坚持宪草修改原则而向我党中央报告和请示的，不幸竟遭大难。你们是为国奔波、为人民事业奋斗到最后一口气的。你们的功绩，在人民历史中，将永垂不朽！你们的精神，激励着千百万群众、党员向着你们的奋斗目标，补上你们的岗位前进。

如果没有反动派破坏政协决议的阴谋活动，也就没有你们这次冒着恶劣天气飞回延安的必要。但是“道高一尺，魔高一丈”。政协决议、停战协定和整军方案的实施，是决不会顺利的。中国人民为求和平民主的实现，已付了极大代价，没料到还付上这样惨重的代价，并且还未付完；反动派正在改组政府、召开国大和接收主权等表面文章后面，进行着更大的独裁、分裂和屠杀的阴谋活动呢！

烈士们！同志们！你们的责任已尽。我敢向你们保证：有中国人民在，有中国共产党在，有中国一切民主党派和力量在，我们决不让反动派破坏政协、破坏停战、破坏整军的阴谋活动成功。你们坚持的方针，是全中国人民的方针。和平、民主终必会在全中国实现。

若飞！你最后一夕话，是为中国人民及其代表所受到统治者的压迫鸣不平的。我记住，我永远记住。我敢向你保证：万万以上的中国人民已经觉醒了，已经起来了，中国共产党在毛泽东同志思想领导下永远不会离开他们的。我们要为人民的中国、人民的世纪奋斗到底！

博古！你是为修改宪草而粉身碎骨的。我记住，我永远记住。我敢向你保证：我们要为坚持完成一部民主宪法、建立民主中国而奋斗到底！

希夷！你是人民队伍的创造者，北伐抗战，你为新旧四军立下了解放人民的汗马功劳。十年流亡，五年牢监，虽苍白了你的头发，但更坚强了你的意志。一出狱，你就要求重新入党。一见面，你就提到皖南死难同志，检讨皖南事变〔209〕，要我交涉继续放人。我记住，我永远记住。我敢向你保证：我们要为保护人民队伍和释放一切政治犯而奋斗到底！

邓发！你是工人队伍里培养出来的领袖，最后，你为中国工人阶级联合战线同时也是为世界工人阶级联合战线，建立了光辉的成绩。但是这成就刚刚开始，你竟一去不返。为继续和发扬这一成就，我敢向你保证：我们要为中国和世界的职工联合运动的彻底成功而奋斗！

一切飞延遇难的中美朋友、同志！你们每一个人的优点和成就，都是人民中的希望。我们要向你们学习。我们要继续你们遗留下来的为人民教育服务、为革命工作努力、为培养革命后代而自我牺牲、为努力中美合作而奋不顾身的精神，并把它们永远坚持下去。

我们要将一切悲痛化成团结的力量，向一切反动派搏斗！

和平民主，就是你们的旗帜！

“四八”烈士永垂不朽！

＊这是在重庆各界举行追悼“四八”烈士大会的同一天，为《新华日报》写的署名文章。

