# 对国民党召开“国大”的严正声明

中文马克思主义文库 -> 周恩来
对国民党召开“国大”的严正声明
（一九四六年十一月十六日）


　　国民党政府一手包办的“国民大会”，已于昨天开幕了。这一“国大”，是违背政协决议与全国民意，而由一党政府单独召开的。中国共产党坚决反对。不但这一“国大”的开会日期未经政协协议，更重要的它是一党召开的分裂的“国大”，而不是各党派参加的团结的国大。政协协议的国大，依照政协决议及其程序与精神，必须将政协决议次第付诸实施之后，在改组后的政府领导之下，始能召开。
　　政协各项决议〔345〕，是各党派协议的临时大宪章，是一个整体而不可分割的。十个月来，政协决议不但未曾丝毫付诸实施，而且被国民党当局破坏无遗。停战协定是经过政协决议批准的，但内战从东北大打到关内，政府当局已彻底破坏了一月间停战令〔360〕的位置。政府当局在政协开幕时所宣布的四项诺言〔346〕，从较场口大打〔348〕直到李〔377〕、闻〔378〕暗杀案，已被国民党特务统治破坏得一干二净。政府改组迄未协议成功，和平建国纲领遂亦无从实行，而对许多解放区的地方政府，国民党当局不仅不准其依照纲领规定维持现状，且欲实行“接收”，不允则实行武力占领。军事决议的基本精神是军民分治，但现在国民党政府的各省主席几无不以现役军人充当。宪草审议在重庆既未完工，中共代表当即有全部保留之声明；政府迁南京后，国民党当局更将其一搁至今，从未再议。国大问题的协议，是政协开会期中最后一个妥协。国民党当局保证不开一党包办的分裂的“国大”，并保证通过政协审议完成的宪草，其他党派方允许十年前一党包办的代表〔332〕得保留在区域与职业的代表名额之中，且必须增加各党派代表与解放区代表。在内战完全停止、政协决议已付诸实施、人民自由权利已获保障及政府改组之后，才能够召开国大。这样的国大，才算是各党派参加的团结的国大。现在开幕的所谓国大，不只违背上述决议及其精神，而且连开会日期或延期也由一党政府决定。代表名额，据十一月十五日上午已公布者竟达一千五百八十人，在原协议二千零五十人中，已侵占其他党派名额四百一十人，尤其是已侵占解放区二百人代表名额至一百四十人之多。可见这一“国大”是彻头彻尾一党包办的分裂的“国大”。所谓空出名额等待中共参加，既系破坏政协，又属完全骗局，实际上只是想骗取中共以外的其他党派参加，以粉饰国民党当局个人独裁的面目而已。
　　一月来，南京商谈经第三方面人士的辛勤努力，中共方面曾不断提议商谈形式可以不拘，但必须依照政协决议及其程序办事，惟均被政府当局拒绝。一党“国大”的会议期愈近，我们愈主张停开一党“国大”，方有可能使军事三人会议〔363〕、政协综合小组及宪草审议委员会得以同时开会，根据停战协定、整军方案〔359〕与政协决议，分别解决当前的军事政治问题，并立付实施，然后方能在和平的环境中，从容召开各党派参加的团结的国大。但急于粉饰独裁的政府当局，对此根本不予考虑。
　　现在开幕的一党“国大”，不但使中共及第三方面最近在商谈中的协议成为不可能，并且最后破坏了政协以来的一切决议、停战协定与整军方案，隔断了政协以来和平商谈的道路，同时也很快地彻底揭穿了政府当局十一月八日“停战令”〔383〕的欺骗性。这一党“国大”还要通过一个所谓宪法，把独裁“合法”化，把内战“合法”化，把分裂“合法”化，把出卖国家与人民利益“合法”化。照这样做下去，中国人民一定要陷入苦痛的深渊。我们中国共产党人坚决不承认这个“国大”。和谈之门已为国民党政府当局一手关闭了。一党“国大”中将要玩的一切把戏，乃至改组政府，我们决无一顾之必要。参加了这一个“国大”，承认了这个把戏，就必然推翻了政协决议，破坏了政协以来和平民主团结统一的轨道。中间的道路是没有的。进攻解放区的血战方殷，美国政府援蒋内战的政策依然未变，假和平假民主绝对骗不了人。我们中国共产党愿同中国人民及一切真正为和平民主而努力的党派，为真和平真民主奋斗到底。


　　＊一九四六年十月十一日国民党军占领张家口之后，蒋介石立即发布命令，单独召开“国民大会”，妄图通过一个所谓的宪法，使其内战、独裁、卖国的路线“合法”化。“国大”召开的第二天，周恩来同志在南京举行记者招待会，发表了这个书面声明，刊载于一九四六年十一月十七日重庆《新华日报》。



