# 在延安各界举行的“双十二”纪念会上的讲演

中文马克思主义文库 -> 周恩来
在延安各界举行的“双十二”〔232〕纪念会上的讲演
（一九四六年十二月十二日）


　　诸位先生，诸位同志：“双十二”事变过了整整十年了，中国从内战转入抗战，现在又不幸地回到内战，这是值得大家研究的一段历史教训！不管现在又回到内战中，中国总经历了八年的抗日战争阶段：日本法西斯被打倒了，抗日的人民军队强大起来了，一万万四千万人口的地区，在中国共产党领导之下得到了真正解放，在那里，人民实行民主，农民获得土地，而全中国人民在这种鼓舞之下，变认识了一个强大的帝国主义是可以被打倒的。这就是“双十二”事变的历史收获。“双十二”事变本身的意义，是在它成为当时停止内战、发动抗战的一个历史上的转变关键。“九一八”事变以后，人民已日渐不满于国民党当局的对日不抵抗政策，尤其在中国共产党领导人民武装北上抗日与号召全国建立抗日民族统一战线之后，全国人民要求停止内战，实行抗日的呼声更因之日益广泛，并影响到当时的“剿共”军队，首先影响到在内战前线的东北军与十七路军。经过“一二九”学生运动〔296〕、全国救亡运动、七君子之狱〔95〕，尤其是中国人民红军完成二万五千里长征转向东渡黄河抗日〔295〕，全国抗日高潮必然要走向抗战。大势所趋，人心所向，这已无可阻止。唯独蒋介石先生别具心肠，硬要在日寇进攻绥东〔385〕之际，拒绝东北军请缨抗日，强迫张学良〔91〕、杨虎城〔92〕两将军继续进行内战。但他这种倒行逆施，不仅未能达到目的，反而激起了西安事变，而他自己也因此一逼，才勉强抗日。历史应该公断，西安事变是蒋介石自己逼成的，蒋先生抗战是张、杨两将军顺应人民公意逼成的；张、杨两将军从此就获得人民的谅解与拥护，不是偶然的。现在抗战已经胜利一年多了，然而张、杨两将军却被蒋介石先生幽囚了十年。这段公案，人民会起来给以正当裁判，也只有人民才会真正坚持释放张、杨，那些担保张、杨无事的大人先生和太太们却早已忘恩负义，食言而肥。在纪念“双十二”十周年的今天，我们要求立即释放张、杨两将军，他们是有大功于抗战事业的。
　　蒋介石的抗战既是被逼的勉强的，所以在抗战的全部过程中，都存在着两条路线的斗争：一条是抗战、团结、民主的路线；一条是妥协、分裂、独裁的路线。前者为中共所坚持，得到人民的拥护；而后者则为蒋介石所坚持，得到敌伪与反动分子的喝采。中共及人民是主张积极抗战、坚持胜利的；而蒋介石在抗战初期则联合德意，企图妥协，在抗战后期则勾结敌伪，消极抗战。中共及人民是主张团结一切抗日力量，以便击败日寇的，而蒋介石则分裂抗日阵线，利用抗战不断地削弱乃至消灭非嫡系军队，首先是东北军和十七路军。对中共领导的抗日军队更不惜实行内战。中共及人民是主张实行民主，以便能动员人民的一切力量坚持抗战的，而蒋介石则厉行独裁，压迫人民，使抗战陷于无力。在这种情形下，要不是中共在敌后努力，人民在全国坚持，中国的抗战早已被蒋介石断送了。所以日寇一经投降，蒋介石便利用日俘，收编伪军，进行更大规模的反共反人民的内战。今年一月在全国人民渴望和平、民主声中，蒋介石又曾被逼地勉强地接受过停战协定〔360〕与政协决议〔345〕，但不久便被他所指使的南京二月“整军会议”与重庆三月“二中全会”或明或暗地推翻了。等到东北大打与关内大打，更证明他接受政协决议与停战协定决非心甘情愿。内战发展到最近，五个月侵占我解放区这样多的地方，现在又在开着一党包办的非法的分裂的“国大”，蒋介石的一切欺骗作用都被他自己揭穿无遗了。
　　就这一年多的情况看来，蒋介石与中国人民之间依然继续着西安事变以前及西安事变以后的两条路线的斗争。抗战胜利后，中共及人民是主张依照政协路线实现和平民主与独立，坚决拥护一月停战令，主张政协决议的依序实施，反对美帝国主义干涉中国内政，要求撤退驻华美军，停止援蒋内战。而蒋介石则不惜破坏政协路线，坚决走上内战、独裁与卖国的道路。他企图以武力消灭解放区，以“宪法”形式使他的独裁合法化，以亡国的“中美商约”〔386〕出卖民族利益，换取美帝国主义更多的援助来进行内战，但他这种企图，一定会如十年前进行内战时一样遭遇到悲惨的失败。现在的大势所趋，人心所向，是和平、民主与独立。美帝国主义独霸世界、奴役人民的企图，将引导自己到众叛亲离。蒋介石独霸中国、奴役人民的企图，亦将引导自己到众叛亲离。蒋介石想追随美帝国主义之后寻找出路，结果必走到悬崖绝壁。只有政协的路线才是康庄大道。人民的世纪已经降临。中国的民主新高潮不可避免地要到来。解放区人民自卫战争的坚持和胜利，反动统治区爱国民主运动的发展，各国人民的进步，将促进这一新高潮的到来。历史的发展会警告反动统治者：内战、独裁、卖国的道路是不是要走到底？
　　就在目前，蒋介石还高谈“政治解决”，然而，多数人已经知道这是骗局，或者叫做“和平攻势”。为辨别这一“政治解决”的真伪，我们只要求他立刻解散正在开会的一党包办的非法的分裂的“国大”，承认恢复一月停战令所规定的双方军队的位置，国共谈判便可重开。蒋介石如果肯这样做，那才有回到政协路线上的可能。不然，中国人民就会看得更清楚：对于蒋介石，“武力消灭解放区”才是他的目的，“政治解决”不过是他的欺骗口号而已。我们相信：经过西安事变以来的十年经验教训，中国人民是再不会上当的了。


　　＊本文刊载于一九四六年十二月十三日延安《解放日报》。



