# 一年来的谈判及前途

中文马克思主义文库 -> 周恩来
一年来的谈判及前途
（一九四六年十二月十八日）


　　一年来的情况很复杂，变化多端，现在只能把几个主要的问题说一说，把中国人民与国民党反动派的斗争分析一下，同时讲讲前途。

一　一年来的谈判情况
　　日本投降后，国共谈判可分三个阶段来说：从去年八月二十五日党中央发表宣言〔387〕、毛泽东同志去重庆直到年底，这是第一个阶段；第二阶段从政协到六月休战；第三阶段从七月大打到现在。三个阶段有很多区别：第一阶段是国共直接谈判，没有结果，打了三个月的内战；第二阶段各党派协商，得到结果，但由于国民党的反动，实际上已被推翻；第三阶段，谈判成为烟幕，实际上大打，证明谈判失败。这就是谈判各阶段的特征。现在分开来看：
　　第一个阶段。
　　抗战八年，赢得了日本的投降，当时的情况是：（1）日本投降后，人民非常希望和平，这是我们不能忽视的；（2）中共所领导的人民主力，还不能产生一个全国的民主政府，但又有部分的在我们领导下的民主政府；（3）只要中国人民团结起来，任何强大的帝国主义都可以打倒，这是八年抗战所证明了的。所以这三种要求——和平、民主、独立成为中国人民的愿望，我们根据此愿望，在去年八月二十五日发表了宣言，以适应这种要求，这是完全正确的。在过去大革命、十年内战、抗战三个阶段，我党就贯串了这个新民主主义的方针，那么在第四个历史阶段，我们更一定要贯串它。这是我党的历史方针，也就是毛泽东同志去年《论联合政府》报告的方针，在今后一个较长的历史时期要贯串它与实行它。
　　根据以上方针，毛泽东同志去重庆，在去年十月十日发表了双十会谈纪要〔373〕。在此纪要中，解决了许多问题，但同时还有几个重要问题没有解决。
　　解决的最重要的有三点：
　　一、承认了中共的地位。尽管到现在，国民党在各地还捉杀我们的人，我们的党在蒋管区还处在地下，但中共在全国全世界的地位，从双十会谈纪要发表后，是不同了。我们的地位已为国内外人民所承认，这是历史上一个很重要的问题。十年前西安事变〔232〕后，蒋还在庐山向我提出要朱、毛出洋的要求，把我们看成是地方军阀，污辱我党；抗战，我们向蒋提出国共共同纲领〔388〕，他不理，自己发表了抗战建国纲领〔233〕；抗战八年中，蒋对共产党无论在形式上本质上，都不是放在平等的地位。但在日本投降后，因为经过我们八年的努力，解放区有了一万万四千万人口，共产党军队达到了一百四十万的人数，中国的问题，要没有共产党的过问是不行的，因此，蒋也不能不一而再再而三地打电报请毛泽东同志去。毛泽东同志的去重庆是关系着中共在中国及在世界上的地位的问题，去年这一次去是完全需要的，对我们没有任何损失。虽然力量的发展是八年的成绩，但毛泽东同志去后就不同了，取得能适合我党现在力量的地位。所以今年九月蒋在庐山训话中说，中共已不象过去江西时代那样容易剿灭的，他是有了国际地位了。
　　二、承认了各党派的会议。在这以前，蒋根本不承认各党派的地位，而此后却承认了，提高了各党派的地位。历史的发展是非常之快的。党派会议、联合政府都是中共提出的，各党派今天之所以有地位，是共产党与人民的努力取得的，连青年党〔389〕也不得不暗自说，因为有共产党才能有他们的地位。张君劢〔390〕虽参加了“国大”，但在其见记者时，还说希望共产党原谅。这样使国民党不能一党包办，中国的事情，一定要经过各党派协商，这也就是实行了毛泽东同志的“三三制”〔208〕思想。“三三制”有两个特点：一个就是共产党不一定要在数量上占多数，而争取其他民主人士与我们合作。任何一个大党不应以绝对多数去压倒人家，而要容纳各方，以自己的主张取得胜利。第二个特点就是要各方协商，一致协议，取得共同纲领，以作为施政的方针。这两特点是毛泽东同志“三三制”的思想。
　　三、承认了中共领导的人民军队的地位与数目。在此方案中，承认了我军二十个师。但抗战初期只给我们三个师；林彪同志〔88〕去时，我们要九个师，蒋只给六个师；林伯渠〔303〕主席去时，我们要十六个，蒋只给八个；毛主席去，一下就给了二十个师。
　　以上三点是双十会谈纪要的收获。我们并不因为蒋破坏了这些协定，就以为没有了收获。因为全中国人民都承认了这样的事实，认为中共的地位是不容抹杀的。国民党虽背叛了协议，但他还不敢放弃党派协商。
　　另一方面，没有达到协议的是地区问题与政权问题。在那时，我们的方针是要争取承认我们已有的民主政权，由此推向其他地方使之民主化。这对蒋来说，比前面的三个问题重大得多，因为凡是民主的地方，就没有独裁者的份儿。这对蒋是一个根本的威胁，因此蒋不承认。同时这也是与赫尔利〔329〕闹翻的中心。毛泽东同志回来后，我与若飞同志〔367〕还同国民党谈了一个半月。我们用各种方法想使他们承认，但他们还是不承认，中心就是他们不愿中国人民得到一个民主的根据地。中国这样大的国家，革命不可能是平衡前进，中国的革命就是这样的走出来，起起伏伏，一个阵地一个阵地地发展。所以对中国人民来说，根据地比什么都重要。武装固然重要，但武装毕竟是保持根据地的工具，武装脱离了根据地就无法生存。蒋看清了这点，他也特别懂得这个问题的重要性，因此，他无论如何不承认。
　　还有形式上承认而实质上未执行的问题，就是受降、遣俘、改编伪军三个问题。原则上虽已承认，但实际上他干他的。受降，他要经过美国人，而这样他的军队才由西南到了各大城市，同时又利用日俘、伪军打我们，把内战重新打起来了。
　　所以，在第一阶段谈判中，我们有不可磨灭的成绩，同时又有第二类没有承认的问题，还有第三类形式上承认而实际上又被破坏了的问题，这样使谈判不能有结果，打了三个月的内战。
　　三个月的内战，证明蒋当时还没有准备好。他的主要力量在西南，虽然美国尽一切可能帮他运了五个军到山海关，两个军到华北，两个军到山东等，但他的绝大部分军队还在西南，东北、华北广大地区还被我们解放着，使蒋不可能继续打下去。同时，在国际上有杜鲁门声明〔364〕、莫斯科三国外长会议公报〔365〕，马歇尔〔362〕来华等。因此，使内战暂停，进入第二个阶段。
　　第二个阶段。
　　在这一阶段初期应该说有成绩，如一月十日停战令〔360〕、一月底政协决议〔345〕、二月整军协议〔359〕、三月东北停战协议〔374〕等四个文件的签订。这里有四个问题，需加以说明：
　　一、战争在全国范围的确是停止了一个时期，给中国人民一个希望，战争可能停止，这也不能不影响我们解放区的人民与党的方针。当然，如果我们把它夸大了，那就是幻想了。但中央当时估计和平的可能也确有许多根据。蒋在被逼下把战争暂时停下来了，在当时的协议中，不允许双方军队移动，假使蒋不动，他的大部分军队还在西南，华北不多，的确打不起象过去五六个月来那样的大仗。所以当时我们签了字。但到后来蒋大的调动，使此协议被破坏（大的调动还是在五六月）。我党在当时也需要停战整顿，特别在东北是日本投降后才搞起来的。就是在华北，过去也没有这样大，所以当时党签订停战协议是对的。这，一直到今天还成为我们的斗争口号。我们拥护停战协定，并不要因蒋破坏而不去拥护，如果照停战令作下去，对人民还是有利的。
　　二、政协就是党派会议，在政协决议中承认了联合政府。照政协的决议改组的政府，就是联合政府。蒋虽不愿承认联合政府这名词，但实际上如翻成英文，还是联合政府。当然这与我们的新民主主义还有很长的距离，但如照政协做下去，则是向新民主主义的方向发展。因此，蒋不敢这样做，所以破坏它。但直到今天蒋还不敢公开否认它，因为政协是得到全国人民的拥护的。在一年前的“七大”，我们也还没有预料到这样快就会有这样一个党派会议，产生这样一些决议。因此，这个决议还要成为我们的奋斗目标。这个决议实际上也就是实现了毛泽东同志的路线，我们对此要有个深刻的认识，政协路线就是毛泽东同志《论联合政府》的路线，这将是今后长时期的奋斗目标。为什么我们现在的口号不叫政协决议而叫政协路线呢？因为政协决议已被他们破坏。当时许多问题都协议了，就是国大问题也妥协了，我们还承认国民党圈定的九百五十名代表，因为如依决议去做，国大只是形式，一切问题需经党派会议协商解决。但国民党现在开“国大”，已破坏了政协宪草〔354〕，国大问题我们就无法妥协。如果将来再谈判，我们决不承认他过去的“国大”。如谈改组政府，在政府的成份名额条件上也不能象过去那样了。整军方案也是如此，条件是要变更的。将来的整军我们绝不能接受五比一了。所以决议是要变的，但路线不能变，党派协商、共同纲领、联合政府是不能变的。中国的事情对蒋介石来说签了字也是没有用的，但我们不管他将来谈得好谈不好，政协这一条路线，我们还是不变的，不能放弃的。
　　三、整军方案。这件事，许多同志比较不大容易了解。整军方案是使中国人民的武装受束缚的，但也受保障的，这有它的两面性。在数目上，五十比十，对我们是一个束缚，但也还不是主要的，主要的是规定要经过美国装备，我们的十个师也包括在内。装备虽好，但可把你集中起来，不给你汽油弹药，那你就没有办法，而且这些东西都是美国来的，如果打起来是废铁一堆。美国人是想经过这些东西来控制我们，但这是否能把我们完全困死了呢？不会的。整军方案还有它好的一面，这就是地方自治。人民的武装是地方自治的东西，六十个师只是用在国防上的。地方自治要依靠人民的武装的自卫，我们这里已经自治了，不再需要国家的军队来防匪了，这样就保障了我们解放区人民自己的武装不受国家军队的干涉。这样一看人民并不吃亏。受束缚的就是美国人插进来一只手，但也不要紧，我们就准备着把那十个师变为废铁好了。
　　四、在整军方案中，我们在军事上取得了与蒋军的平等地位。抗战八年，蒋以他的统帅地位来压我们，但在谈判过程中，马歇尔来后，为了套我们，在地位上也不得不承认我们与蒋军的平等地位，结果蒋成了一方面的统帅，而不是两方面的统帅。
　　所以，第二个阶段的成绩，主要就是上述的四项成就，尽管蒋很快就破坏了协定，但这四项成就是不能否认的。对停战协定，蒋从二月南京军事会议时便开始破坏它。当时在该会上有两句口号：“为领袖任劳任怨，为国家死里求生。”实质上就是：“破坏政协任劳任怨，反动集团死里求生。”此会后，在重庆为了欺骗，还命令张治中〔327〕与我们签订了整军方案。三月召开二中全会，又从政治上破坏政协，大骂国民党政协代表，集中到宪草问题向我进攻，经过综合小组提出三点修改：要使国大变无形为有形；取消立法院对行政院的不信任权〔391〕；取消省宪法，改为省自治法等。我们当时不慎重，同意作三点修改。但国民党的企图是要把自治缩小到县，使省没有权力，实行中央集权，变内阁制为总统制，扩大国大的权力，使国会无权，其中心就是“中央集权个人独裁”八个大字。所以从国民党的整军会议后，证明国民党是采取上面谈判下面破坏的方针。这样，五月五日国大就无法开，同时东北三四五月大打，从沈阳打到长春，停战、政协都被破坏了。但为什么又有六月休战呢？因为国民党占了长春后，兵力分得很散，没有兵再进。当时我们在东北占了有利的地位，山东、山西收复了几个伪军占领的城市，这样国民党需要在东北实行几个月的休息，而在关内动手大打，于是有东北休战。二十三天的谈判，讨论了许多问题，我们还打算再让一二个地方以保全广大的解放区。在停止东北战争、恢复交通、整军等问题上，都作了许多的让步，但结果还是破裂，中心问题仍是政权问题，根据地问题。蒋在形式上是要我退出苏、皖、承德、安东、冀东等地，但他承认的只是黑龙江、兴安两省及嫩江半省，华北只是临沂、大名、上党等几个地区，想把我们完全隔开，先限制在这几个地区，然后再来消灭我们。所以六月争论的还是根据地问题，这与第一阶段破裂的关键是一样的。
　　第三个阶段。
　　这个阶段是表面谈判，实际大打，也就是拖中大打。一方面是我们坚持政协路线，另方面是蒋不断地破坏它。我们把谈判作为教育人民的工作，这个方针，连马歇尔也对叶剑英参谋长说：周将军最近几个月来，并不是为谈判而谈判，而是为宣传而谈判。这句话有一半道理，但责任并不在我，因为对方不愿解决问题，我们就告诉人民是他不愿解决，用以教育人民。从七月到我回来以前就是这样一个方针。七月时，马歇尔说各党派谈不好，国共直接谈，我们说也好，于是就开五人会议〔392〕，但还是那样不能解决问题。后来又要司徒雷登〔382〕参加，司徒雷登就上庐山，但蒋的条件更高了，除以前提的条件外，还要我退出山东、山西六月七日后占领的城市。司徒雷登从庐山下来问我们，我们问他看我们能否接受，他不表示意见。我们说，连你都知道困难，我们怎能接受。第三次，马歇尔、司徒雷登又说先谈改组政府，我说也好，但要保证停战，但蒋介石、马歇尔、司徒雷登都不能保证停战，所以就无可谈。我们就主动提出恢复三人会议〔363〕，恢复一月十三日位置。马歇尔不召开会议，我就到上海，马歇尔又急了，来找我。这时正打张家口，我们认为，三人会议既不开，又打张家口，这等于国民党造成全面破裂。于是他又来了停攻十天，要我们交国大代表名单，交十八个师的驻地，我们如何能接受，这样谈判又破裂了。最后一幕戏，就是第三方面出来调解，因为他们还没有单独试验过。我们为了使第三方面得到教育，懂得谈判不会有结果，就同意他们调解。蒋提八条，我们提两条，第三方面想试试，要我回南京，我们就跟着第三方面之后，一道回南京。第三方面想来个折衷方案。他们内部大部分很动摇，我们也料想到青年党〔389〕、民社党〔393〕一定要参加“国大”，只要把民盟〔331〕拉住不参加，“国大”开了就很臭。这个目的达到了，这是八年抗战和最近一年来谈判的成果，第三方面大部分人居然敢于反对蒋记国大，跟着我们这条路走了。
　　关于“国大”，有些无党派的人被蒋套住。十一月十一日，有些“社会贤达”本来是去请求蒋允许“国大”延期的，蒋吓唬说：“明天不开就要亡国了。”“贤达”又请再延几天。蒋说：“好，为了尊重你们意见，延长三天，那你们一定要参加了，问题在请你们劝青年党、民社党也参加'国大'。”消息传出，结果社会贤达四字加了引号，从此开会躲在角落里，生怕记者照像。胡政之〔394〕说：“不参加，《大公报》会受压迫，参加了又怕没有销路。”青年党说：“左右为难，内外夹攻。”黄炎培〔395〕又替他们加上一句：“天人交战。”所以第三方面都知道参加不光荣，但不参加又怕。到了“国大”开幕后，谈判全部破裂，无事可做。蒋及青年党、民社党、一部分“贤达”破坏了政协，被人唾弃。
　　由此看出，七月以来谈判的本身不会有什么结果，但马歇尔、蒋介石还在欺骗。假如那时我们不谈就会孤立，因为人民不了解，我们只有在“国大”开了之后才能走，一定要在第三个阶段结束后才能走，这样才能完成教育人民的一课。

二　一年谈判的经验教训与将来的前途
　　总结三个阶段的经验教训，可以得出这样的结论，斗争的双方，在斗争的基本方针上是绝不会让步和变动的。基本方针，对蒋来说，是要用各种迂回方法消灭中共；对中共来说，是要用各种方法来实现民主，将反动阵营压下去。不过反动集团的反动方针，不能公开地提出来，这是对他不利的，任何的反动集团都没有勇气公开号召，因为反动力量削弱，人民的力量起来了。而我们共产党却公开把我们的和平民主独立的方针拿出来，光明正大地动员全国人民来实现，这是我们的基本方针。但是否双方没有谈判可能与妥协的余地呢？这就要根据形势来决定策略。策略是根据形势的变动而变动的，但策略又是为着实现基本方针的。联合政府是取消独裁政府的方针，在我们区域，大地主大资产阶级集团没有法子站得住，这是事实。所以联合政府的实现，大地主大资产阶级当然不会赞成，因为与他的方针是相反的。因此反动集团的基本方针任何时候不会改变，他一有机会就要实现他的方针，但客观形势常常不让它实现，那就要走些迂回的道路。我们也是同样的，联合政府的方针，要搞垮大地主大资产阶级，这个方针也是定了的，但也因为客观形势与主观力量的对比，我们有时也不得不走些迂回的道路。所以斗争就非常复杂，变化就很大，有很多困难需要克服，但策略又不能违背方针。我们的基本方针当然仍是“七大”的方针，武装斗争、和平谈判都是为着政协路线亦即联合政府的实现。
　　从第三阶段起，关内就大打了，美国更大量援蒋了。今天的斗争不仅是解放区，而且蒋管区，不但下层群众，而且工业家，都反对美蒋的独占独裁。我们可以相信，如再打半年到一年，就以过去的条件，至少可以再去掉他四十到六十个旅，这样他就再没有进攻的能力，我们就可与他平衡。所以我们在今后的半年到一年内，的确是最紧张的一个时期。假使再打半年到一年，战局一定要改观，这也就会影响到蒋管区的爱国民主运动与农村的武装斗争。这三种斗争的汇合，在不久的将来，将会造成民主的新高潮。


　　＊这是在延安的一次干部会议上的报告，其中第二部分是摘要。



