# 评马歇尔离华声明

中文马克思主义文库 -> 周恩来
评马歇尔〔362〕离华声明
（一九四七年一月十日）

去年今日，正是全国停战协定〔360〕签字与政治协商会议开幕的日子。在整整一年中，情形的变化与人民的觉悟发展得真快。一年前的今天，全国人民都在欢呼和平停战，但是为时不久，全国又陷入内战的深渊。大家已明白：不取消军阀主义的统治，中国永远得不到和平。去年一二月间，全国人民都在庆祝政协成功，但是为时不久，政协全部决议〔345〕都被国民党反动派推翻了。大家已明白：不取消个人独裁的制度，民主的政协路线是永不会实现的。一年前，全中国人民都在欢迎杜鲁门总统的对华声明〔364〕与马歇尔将军的来华调解，但是为时不久，美帝国主义的对华政策已原形毕露，蒋介石政府的卖国外交亦暴露无遗。于是全中国各大城市，从几十万学生一直到广大市民，都喊出“美军退出中国”、“反对美国干涉中国内政”、“反对奴才外交”、“反对中美商约”等口号。

去年一年的变化，不仅国民党反动派重新挑起了内战，破坏了政协，便连一同签字于停战协定上的美国调人也不再提起去年一月的停战令了，一同参加政协的青年党〔389〕、民社党〔393〕及大部分所谓“社会贤达”也竟参加了彻底破坏政协路线的一党包办的非法“国大”，制定完全违背政协原则的独裁“宪法”，以加深全国的分裂局面。所以，现在只有中国共产党与真正民主党派、真正社会贤达及最广大的人民群众，才一直为坚持去年一月停战协定与政协路线而奋斗，为要求美军退出中国与反对美国干涉中国内政而奋斗。回顾这一年的奋斗，不由得想起去年为停战、政协夺走的“四八”遇难烈士及闻一多〔378〕、李公朴〔377〕、陶行知〔280〕诸先生。他们与破坏停战、破坏政协的反动集团搏斗的精神，一直在激励着我们。

就在这一年正满，马歇尔将军于他离华前夜，发表了关于一年调解之总结性的声明。我现在借着他这个声明，略论一下一年谈判中的几个主要问题。

马歇尔将军承认国民党内有反动集团，在国民党政府中占优势，而且包括军事与政治领袖，他们反对联合政府，不相信国内合作，只信武力可以解决问题，对实施政协决议显无诚意，这都是说得对的。但遗憾的是他并未指出蒋介石就是这个反动集团的最高领袖。蒋介石说，联合政府就是推翻政府，党派会议就是分赃会议。去年北平执行部成立后，蒋介石反对派执行小组到东北调处。三月二十七日东北停战协议〔374〕方签字，蒋介石便命令杜聿明〔396〕在东北大打。六月休战谈判未成，是蒋介石硬违背政协决议要求中共退出苏北、热河等四个解放区破坏了的。接着，他便在关内大打，直到现在。一年来，他违背停战协定，调动了二百一十八个旅（或师）占其全兵力百分之九十来进攻中共领导的解放区，至去年年底止，还侵入解放区十七万九千多平方公里的土地，侵占解放区一百六十五个城市，这不是武力进攻是什么？去年召开的一党“国大”，彻底破坏了政协路线，自始至终都是蒋介石一人决定的。所以破坏停战协定，破坏政协决议的罪魁祸首，不是别人，正是蒋介石自己。

蒋介石反动集团用武力“维持其自身的封建控制”，但结果连马歇尔将军也不得不承认，“又使其政府的力量愈益薄弱”。至于“经济破坏”与“交通破坏”，都是蒋介石进行内战所造成的结果。蒋介石政府以其预算的百分之八十用在军费上，加以官僚资本的盘剥统制，独裁政府的腐败无能，金融如何不乱，经济如何不溃？

这样的坏政府，在同一个蒋介石领导之下，换上几个去年一月曾经参加政协，后来又背叛政协，并积极参加蒋记“国大”的某些所谓国民党内自由分子与少数党派如青年党、民社党之流的人，便可以一变而为好政府，马歇尔将军的想法，未免太廉价了罢。没有中共参加的所谓联合政府，蒋介石的个人独裁制度是无法取消的，也绝不会成为自由主义政府。

马歇尔将军明知去年召开的蒋记“国大”，是破坏了政协决议及其程序的，但他却故意说它通过的独裁宪法是“民主宪法”，其中主要部分均与政协原则相符合，且似已包括中共要求在内。这真是欺人之谈。去年蒋记“国大”通过的独裁宪法，其主要部分均与政协原则相反。政协主张保障人民自由，蒋宪则限制人民自由。政协主张保障少数民族自治权，蒋宪则取消少数民族自治权。政协主张省为地方自治最高单位，自订省宪，实行地方均权主义，蒋宪则取消省宪，实行中央集权主义。政协主张中央政权实行联合政府的责任内阁制，蒋宪则恢复“五五宪草”〔142〕的总统独裁制。马歇尔将军想以实行蒋宪、改组政府的办法，算作结束一党训政〔340〕，为蒋介石独裁政府找出路，结果只会使它更加失信，更加孤立，绝对得不到人民拥护。

那么，中共这样反对蒋宪，反对在现在情况下参加政府，要求恢复去年一月十三日的双方军事位置，要求取消蒋宪与重开党派会议，是否如马歇尔将军所说不愿促成公允的妥协呢？恰恰相反，这些要求，正是最公允的妥协，也是最低限度的和平民主要求。连马歇尔将军也承认中共在去年一二月间是愿意妥协的。而二三月起，破坏政协、破坏停战的一切行动，又显然出之国民党反动集团。故中共直到现在，还是坚持在去年一月的停战协定与政协路线的基础上求妥协，其根据正是马歇尔所称赞的“自由而且远大的宪章”。两相比较，蒋介石是在破坏停战协定，破坏政协路线，中共是在维持停战协定，维持政协路线，究竟是蒋介石在企图消灭解放区，还是中共在追求推翻政府，岂不十分明显了么？若说蒋介石可以不接受取消蒋宪与恢复一月十三日军事位置之最公允的妥协，难道中共就应承认破坏政协的蒋记“国大”、“宪法”与破坏停战协定的进占位置，才算“公允的妥协”么？中共不承认这些无理要求，就说中共党内有激烈分子，不顾国家利益与人民痛苦，这是最不合事实而且企图污辱中共的说法，中国人民决不会相信。因为中共为人民服务，二十六年来如一日，一切依靠人民，才有今天的威信。如果中共同意蒋介石进占解放区这些地方，让他自由压迫人民，承认蒋记“国大”、“宪法”，让他继续独裁，那才真是不顾人民痛苦与国家利益呢！而且也必然得不到真正和平。

有许多渴望和平的天真朋友，不去研究停战的可靠根据和最低保障，不愿为坚持原则而奋斗，只痴等和平之赐予。于是蒋介石看透了这点，在他进攻有利的时候，便决不停战；在他进攻失败，需要取得时间整顿军队，以便重新进攻，如象去年一二月间那样，他便赞成停战，举行所谓“和谈”。请问，这样怎能得到公允妥协呢？永远不能。公允妥协必须建立在一个对人民有利而可靠的基础上，这个基础就是去年一月为马歇尔及蒋介石代表张群〔324〕所签字的停战协定与蒋介石所主持通过的政协决议。马歇尔将军的声明只提政协决议，不提停战协定，这不是偶然忘记，而是有意规避他签字在上边的责任，并为三人会议〔363〕及北平执行部的美方代表寻求解脱，但反而愈加证明美国政府是在有意助长蒋介石大打内战了。

因此，马歇尔将军对中共宣传工作最为怀恨，也可得到证明。的确，在过去一年中，中共对去年三月以来美国政府对华政策的改变，曾不断揭发其错误，尤其对美军驻华，干涉中国内政，侵扰解放区（马歇尔所提之安平事件〔397〕，不过此中三十余件之一件而已），运送蒋军，及美政府以租借物资、剩余物资、经济借款、军舰、飞机、军事顾问、技术训练等等援助蒋介石政府军队，更不断予以暴露和抗议。而美帝国主义殖民地化中国政策的本质及国民党政府卖国外交的事实（如缔结“中美商约”〔386〕、“航空协定”〔398〕等），又常为我们揭露无遗。七月以后，中共在蒋介石大举进攻之下，犹与美国调人不断寻求妥协之道，乃蒋介石得寸进尺，贪得无厌，无理要求，层出不穷，而美国调人始终无片言相责，反两次声明，深怪中共未能接受其调解，这自不能不引起我方的驳斥。马歇尔将军认为上述各种宣传，足以激发世人对美政府的痛恨心理，故有“罪恶性质”。其实，能激发人的并不是抽象宣传，而是活生生的事实。如果上述的事实不改，在爱好独立自由的民族看来，都是罪恶。

现在马歇尔将军回去任美国国务卿了。我很希望他能站在故罗斯福总统对华政策的立场上，为着中美两大民族的传统友谊和利益，重新检讨美国政府近一年来的对华政策，不再继续过去的错误，停止援助蒋介石政府进行内战，撤退驻华美军，不再干涉中国内政，重新调整中美关系，那一定会有大助于中国人民对于和平、民主与独立的努力，也更有助于远东和平与国际合作。

停战协定签字和政协会议召开一周年，我们不能忘怀于这一伟大的纪念日，并且要为停战协定与政协路线继续奋斗。我们相信一切民主人士、全国同胞都愿为它一道奋斗，以求其完全彻底实现，不达目的不止。

＊这是在延安各界代表声援全国学生爱国运动及纪念政治协商会议一周年大会上的演说，刊载于一九四七年一月十四日延安《解放日报》。

