# 关于在蒋管区的工作方针和斗争策略的两个文件

中文马克思主义文库 -> 周恩来
关于在蒋管区的工作方针和斗争策略的两个文件
（一九四七年二月二十八日、五月五日）


一
　　（一）目前，蒋顽在前线大败、后方危机重重及莫斯科会议趋向于解决国际问题的情况下，竟于其统治的城市，大施镇压，赶走我方人员，威胁民主运动，捕打人民学生。其企图不外：一、如我及人民团体、社会舆论默不作声，彼正好得寸进尺，加强镇压；二、如我及进步群众受其挑衅，实行硬碰，彼正好以有准备的打击，挫我锐气，加强恐怖；三、如我只动员少数进步分子提出中间分子尚不能接受的口号，进行反抗，正好中其暴露我方力量之计，便于其分化挑拨，各个击破。因此，蒋的镇压政策仍具试探性。尤其是使人活不下去的财经危机，人民既忍受不了，而前线继续大败，人民也吓唬不了，故蒋管区群众斗争，固然要经过一些迂回起伏，但总的趋势必然会继长增高，问题就要看我们领导的斗争策略如何，组织力量如何，以决定群众斗争增长的快慢与可否避免一些挫折。
　　（二）针对目前蒋的镇压政策，我们应扩大宣传，避免硬碰，争取中间分子，利用合法形式，力求从为生存而斗争的基础上，建立反卖国、反内战、反独裁与反特务恐怖的广大阵线。在宣传上，我们对蒋之任何一个反动设施、恐怖行为，都要尽情揭露，宣告中外，只要我们善于抓住其弱点，击中其要害。蒋美的反动阴谋是最怕被人揭穿的。在行动上，我们应避免在不利的条件下去硬碰，这不是保守，而是领导群众变换方式，绕过暗礁。去年底，各地学生反美示威，由于一年多美军横行，半年多反美宣传，加之沈崇事件〔399〕的激动，而蒋美于事前又毫无准备，故运动成功，收获至大。此次蒋特捕人打人，是其预定计划，我如不管条件如何，仍在学生中号召游行示威，有遭其屠杀的危险。且一般学生对捕人事件，有愤激的，也有畏缩的，我应顾及此种不同情绪，联合大多数学生首先向学校当局要求生命保障与释放同学，继之联合学校当局向地方当局要求生命保障与释放同学。如仍捕人，则在校内实行自保，如集体出入，互相联保，在条件成熟时，亦可实行罢课，要求释放同学等。同时在斗争中要联系到、有时要转移到经济斗争上去，才能动员更广大群众参加，而且易于取得合法形式。有了经济斗争的广大基础，也易于联系到反特务反内战的斗争上去。在组织上，学生的抗暴联合会虽已在京、沪、平、津、渝学生中有了基础和联络，但也要建立可以自保的防线，即在名称上与行动上，在蒋特发现施以高压后，不妨改换名称或分开作战，使我损失不大，而仍能继续斗争，继续联络。在工人与城市贫民（如小贩）中，更要着重经济斗争的领导和发展。现在沪津一带，工人反对一月指数、要求加薪的斗争已起〔400〕，我应善为领导，求得局部胜利，以便巩固阵地，利于今后发展。
　　（三）今后数月，蒋管区的变化必大，望你们依照具体情况，善于运用斗争策略为要。吴、张〔401〕在撤退前，望尽可能将此种意见转告隐蔽的同志。
二
　　近日，蒋顽因军事、经济、政治种种危机难以解脱，于是大造谣言，捏造所谓“中共地下斗争路线纲领”，企图一方面借此陷害民主人士和群众团体，另方面借此捕杀我党秘密人员和进步分子，以镇压蒋管区的人民运动。在此情况下，你们在蒋管区统治尚严的地方尤其是蒋管区大城市中的工作方针，就是要保护我党及民主进步力量，以继续加紧开展人民运动。为此目的，既要坚定勇敢，又要机警谨慎。要时时注视情势的发展，坚持我党放手动员群众进行反美反蒋的方针，灵活地既结合又分别合法与非法的斗争。将适合群众迫切要求、提高群众斗争情绪的口号，均经过群众面目提出，以发动群众；将党的宣传工作，侧重于以群众中有职业有地位人物，利用公开刊物、报纸、集会，批评时政，增强不满；而将党的广播言论、解放区胜利消息，经过极可靠关系，辗转秘密散布。党与民主团体、群众组织及进步人士等关系，亦要多发展极端隐蔽党员及同情分子，成单线领导，居中工作，不要以党的公开面目经常来往，尤要避免书信文件来往，以防牵涉。党的组织要严守精于隐蔽，平行组织，单线领导，不转关系，城乡分开，上下分开，公开与秘密分开等原则。从城市派人往外县乡村去发动、组织与领导武装斗争，必须与城市其他任何工作及人员分开，免致牵连。高级领导机关更须十分隐蔽，少开会，少接头，多做局势研究与策略指导的工作。总之，蒋管区城市工作，一切要从长期存在打算，以推动群众斗争，开展统一战线，如此，方能配合解放区胜利，推动全国新高潮的到来。


　　＊一九四七年春，周恩来同志根据中国革命将要出现新高潮的形势，对蒋管区的爱国民主运动多次为中共中央起草指示，这是其中的两份。



