# 全国大反攻，打倒蒋介石

中文马克思主义文库 -> 周恩来
全国大反攻，打倒蒋介石
（一九四七年九月二十八日）

现在已进入大反攻时期。自卫战争是从去年大打起来的，为什么那时不提出大反攻，不提出打倒蒋介石，现在才提？这是同志们所关心的问题。全国大反攻，打倒蒋介石，不是随随便便提出来的，而是有根据的。我们先讲一讲过去一年自卫战争的总结。

日本投降后，党的方针是要建立一个独立、和平、民主的新中国。用什么方法实现？大家记得，毛泽东同志到重庆去谈判，签订停战协定〔360〕，召开政治协商会议〔345〕，通过政协决议，那是用的和平方法。党在日本投降后的一个时期，在决不放松武装自卫的条件下，曾经想用和平的方法实现建立新中国的目的。那时和今天是不同的，今天要用武力才能实现这一目的。这两个方法不同，是不是有一个对，有一个不对？大家知道现在这个方法对，只有用武力打垮蒋介石，才能有独立和平民主。那末，过去就不对？我们答复：现在对，过去也对。同志们会以为讲不通。讲得通的。那时，和平就是要在我们这边巩固解放区，在国民党统治区那边动员人民。那时用和平方法实现我们的目的，可能性大不大？不大，但要试一试。全国大部分人民要和平，全世界要和平，这个呼声，党不能不考虑。党是人民的先锋队，看得远，但先锋队不能脱离群众，要尊重人民的意见。经过十年内战、八年抗战，人民要和平。因为人民有这种想法，所以要去试一试和平的但也是麻烦的方法。于是就有了重庆谈判和《双十协定》〔373〕，有了停战协定，有了政协决议，蒋介石也签了字，可见也是有可能的。这样做，我们没有吃亏。在这期间，我们的军队开进东北，不是胜利吗？对大部解放区的巩固，部队的整理，也是有好处的。另外，我们照协议办事，蒋介石破坏协议，这就证明给人民看：蒋介石不要和平。不仅一次证明，而且几次（一月停战、六月关于东北问题的谈判〔402〕等）都证明蒋介石不要和平。这就把人民的认识提高一步：和平不是靠几个协议就能实现的，要靠武力保卫自己的利益，要用武力才能取得和平。从和平到要用武力，其间有个过程，有个变化，就是人民认清了一个道理：只有靠武力才能解决问题。

在去年七月就指出打倒蒋介石，行不行？还不行。当时提的口号是武装自卫，还不能公开提出打倒蒋介石的口号，因为当时主客观条件还不具备。蒋介石号称四百万军队，这么多部队，一下子不容易打倒。过去有人说，“国民党打不垮共产党，共产党也打不垮国民党”，“谁也消灭不了谁”。这种说法很流行。大打起来后，在人民中，民族资产阶级、小资产阶级，以及其他一部分中间分子，不是都与我们的想法相同，还有很多人以为是谁也消灭不了谁。如果我们那时就提出打倒蒋介石，他们会不相信，不接受。同时，去年蒋介石刚开始大打，我们如提出“打倒蒋介石”，他就会反过来说共产党要打他，进攻他。如果我们把自卫口号变成进攻口号，那末就成为国共两方面都要进攻，就抵销了。我们说自卫，就是抵制他的进攻。但是怎样表明我们要打倒蒋介石呢？就是讲我们一定胜利！讲胜利信心，蒋必败，我必胜！而不是正面说谁消灭谁。我们这样讲，人民中许多人还要想一想，成不成？我们就拿事实来证明。我们人民解放军有把握，因为我们是新生力量，茁壮如青年，蒋介石犹如垂死的肺病鬼。去年一年的自卫战争，就证明了这个道理——蒋必败，我必胜！

去年一年自卫战争，蒋介石用三百万军队进攻我们。一年作战，死伤和被俘一百一十多万，就是说被消灭了三分之一以上。这是从人数上说。从建制上看，蒋介石共有二百四十八个旅，被我消灭九十七个半旅，平均一个月八个旅，还多出一个半旅，也超过三分之一。蒋军建制被打垮这样多，把打垮的再补充起来，就没有战斗力。如胡宗南〔376〕有几个旅就被消灭过两次，被我消灭一次以后，再来就容易打了。不少俘虏军官在放回去时说，再碰到我们一定举手缴枪。敌军的新兵是绑来的，象我们在《抓壮丁》那个戏中看到的一样，他们没有经过训练，战斗力弱，逃亡的比老兵更多。蒋军被我俘虏和击毙的将级军官就有二百多，新提拔上来的军官，战斗经验少。武器方面也是如此，美造装备有许多缴获到我们手里来了。所以无论从人力上、战斗力上、装备上看，蒋介石都不行。粮食也是如此，胡宗南军队打到解放区来，每天要用十架飞机运粮，才够他十万人吃。蒋介石的种种困难，证明他是无法长期打下去的。蒋介石不能消灭我们是定了的。这一点甚至已成为蒋军军官相当普遍的看法。不仅被俘军官这样看，就是现在蒋介石下面的军官，见到蒋介石时腰挺得很硬，说一定消灭共产党，但一背过蒋介石就摇头。开始大打时，蒋军是一旅一旅地被消灭，后来成为一师一师地被消灭。蒋介石说我们专门打他们的司令部，所以，旅长、师长都被我活捉了。那有这样的事？！他们的司令部都是在自己队伍的紧紧围护中，部队全部被我歼灭了，旅长师长当然被我活捉。对这样的消灭，那有不寒心不害怕的？所以，一年自卫战争的结果，就是蒋介石的军队承认不能消灭我们，而且他们是要失败的。在人民中，去年下半年还有许多人不相信蒋必败、我必胜，但自今年山东等地胜利以后就相信了。这是一个发展，这个发展很快，仅仅一年，变化就这样大。因此，经过一年战斗取得的胜利，我们有根据有把握地在“七七”口号中提出，要坚决彻底干净全部地消灭一切蒋介石进犯军。九月又提出大反攻，提出打倒蒋介石的口号，对这个口号，人民已经能够接受了。

蒋介石一年来做了许多蠢事，也证明他已无法统治下去。他单独召开“国大”，中共不参加，民盟〔331〕不参加，立刻就使它不能起作用，人民就不拥护它。人民不高兴他的“宪法”，就叫它伪宪法。蒋介石一不做，二不休，又在四月改组政府〔403〕。政协规定组织联合政府要有中共参加。他改组政府不要中共参加，中共当然也不会去参加。他拉拢了民社党〔393〕、青年党〔389〕，这两个党，人民很熟悉，臭得很，没有人相信他们。蒋介石的办法用完了，戏法变完了，再来一个没有了。单靠政治手法也不顶用，人民还要看一看：有没有饭吃？黄金涨不涨，美钞涨不涨？现在蒋管区不仅工农劳苦大众没法生活，就是小资产阶级、公务员也没法生活。美货滚滚来，入口大大超过出口，入口货半数以上为美国货，这在国民党统治区域，那一个人会欢迎？蒋介石靠借钱过日子，四十亿美元早用完了，又伸手向美国借。人民已看到他靠借款也挽救不了军事上的大败、政治上的破产和经济上的崩溃。因此，城市里的青年学生到处示威，反对美军强奸中国妇女，反对美军打死中国人，有的直接起来反对蒋介石。蒋介石出席参政会议时，南京中央大学学生到礼堂闹起来，使蒋介石下不了台〔404〕。蒋介石遭到人民反对，政治上破了产，所以我们应当提出打倒蒋介石的口号。一方面，我们已用事实证明给老百姓看，我们有力量打倒蒋介石；另一方面，老百姓也不要蒋介石，就连上层分子（除了少数反动集团外）、中产阶级也不想给蒋介石抬轿子了，也要推翻他了。所以这个时候提出打倒蒋介石正合时宜。

为什么我们取得这样大的胜利？为什么说我们一定能够成功？

第一，人民拥护我们作战，相信我们是为他们做事的。土地改革，平分土地，把地主的土地分给无地少地的农民，推翻封建势力，贫苦农民当家作主。抗日战争时期，我们实行减租减息，是争取地主一道抗日。现在日本打败了，大地主拥护蒋介石。要打倒蒋介石的势力，就要消灭地主阶级，使他们都变成自食其力的劳动者。土地问题解决得好，人民就拥护我们，仗就打得好。全国人口中有百分之八十是农民，其中得到土改利益的占百分之九十以上，这样大的力量，能不打胜仗吗？

第二，我们的军队，是为人民的，是人民的子弟兵。他从诞生的时候起，就是为人民谋利的。他有坚强的骨干，坚持执行三大纪律八项注意，同人民有密切的联系，经过艰苦奋斗流血牺牲的锻炼，官兵一致，善于战斗。我们的军队有光荣传统，是战无不胜的。

第三，党中央和毛泽东同志领导得好。去年以来，我们的方针，就是消灭蒋军在解放区内，就是在内线作战中诱敌深入，让他占些地方，把兵力分散，我们把人民动员起来，找机会消灭他，由此转到反攻。所以一年来，我们是战略防御，战术进攻，消灭敌人在解放区内。结果，他占我百余城，我们消灭他百余万军队，包括近七十万俘虏。这也就是毛泽东同志所说的防御中的进攻，消灭他的有生力量。蒋介石的战略是进攻，而战术却是防御的。这个战术与日本人的差不多。如在陕北的作战就是如此，蒋军开始凶得很，但到了岔口时，他五个旅，我用同等兵力就把他围住了。他动也不敢动，没有一点攻击精神。这就是蒋介石、陈诚〔82〕用的战术。他们定的办法，专说如何防卫，如何突围，如何待援，如何警戒，如象一个人害了肺病，专门讲究如何防感冒，防咳嗽，防消化不良，防这防那，这样的人距死期也就不远了。

这是一年战争的总结。从这里可以看出，第二年提出大反攻、打倒蒋介石的口号，是适当的。

现在再讲讲如何达到打倒蒋介石的目的。

打倒蒋介石，这是早就定了的。十年内战是如此；抗日是一个时期，要他共同抗日；日本投降后一个时期，是要用和平方法打倒他；现在是要打出去，全国大反攻，不是消灭蒋介石在解放区内，而是要消灭蒋介石在蒋管区。去年一年我们是战略防御，战术进攻，现在战略也是进攻。蒋介石不仅战术是防御，而且战略也是防御了。光在解放区内作战消灭不了他，因为在全国他还占有四分之三的土地、三分之二的人口。只有战略进攻，才能彻底消灭他。口号一提出，战争行动就要配合，就是全国性反攻，就是打出去，突破解放区的界线，我们的行动完全是为实现这个口号的。刘邓、陈谢、陈粟三路大军南下〔405〕，过黄河，过陇海路，直到长江以北。黄河是蒋介石的“外壕”，陇海路是他的“铁丝网”，长江是他的“内壕”。蒋介石总想赶我们过“外壕”，而我们已过了“铁丝网”，打到他的“内壕”了。形势变动了，我们是在黄河、长江之间来发展。中国中部有江、淮、河、汉四条大水，现在要在这之间来打。这是南线，我们已有三路大军。西北解放军也要打出去。东北解放军已经出击。这是全国反攻的形势。我们的方针就是：打到蒋管区，发展解放区，消灭蒋介石的部队在蒋管区。这个方针在今后一年到两年间要实现。有把握没有？有把握的，有根据的。从三方面看：

先从敌人方面看，他有三个弱点：兵力不足，后方空虚，人民反对。

第一，兵力不足。蒋介石共有正规部队一百八十万，被打乘一百五十万，非正规军一百一十万，剩下九十万。今后一年，敌人减员数目还会大。就算和过去一年一样，每月平均被歼八个旅，还将有九十六至一百个旅被消灭，这是没有疑义的。他是否还能象去年补充那样多呢？肯定会更少。就算他一切照去年一样，再只减少三十万正规军，明年不就只剩下一百二十万了！这样，蒋介石的兵愈打愈少。第一年，他的机动兵力多，开始用半数进攻，到今后四月份只有四十个旅进攻，现在则更少了。先看南线，这是他的主要方面。他的全部兵力二百四十八个旅，在南线用了一百五十七个旅，其中只有胶东十五个旅是进攻，其余都是防御。如我各路大军再获胜利，这十五个旅也会转为守势。北线七十个旅，只有孙连仲和傅作义〔406〕的二十九个旅能作点地方性的进攻。除去南北线二百二十七个旅，后备只剩二十一个旅。从各方面看，他的兵力不足。

第二，后方空虚。后方剩二十一个旅，当然空虚。而且其中有八个旅在新疆和甘西，新疆有民族问题，现在又闹起来，八个旅出不来了。另外的十三个旅，放在长江以南，云南两个，川康七个，广东两个，台湾两个，其他地方都依靠民团、保安队。保安队只能守，而且数量也不多，那好打得很。所以蒋介石的后方空虚不可言状。我们到了江北，江南就恐慌起来了。

第三，人民反对。上面已讲到蒋管区经济破产、政治黑暗，到处表现出来。那里的人民运动象海潮一样，时起时落，反对蒋介石的日益增多，连大学教授、开明一点的绅士商人也会参加。我们愈向外打出去，愈能促使蒋管区人民运动的高涨。

敌人方面的这三个弱点，是我们打出去的好条件。

我们方面充分具备了大反攻的条件。

首先是我军愈战愈强。过去，我们消灭敌人一个团一个营就算胜仗，现在消灭他个把旅都不在话下了。战斗力强了，人数也增加了。我们队伍的来源，除了大量的翻身农民参加以外，同时还有大量的俘虏参加进来。在我们部队里，解放战士占半数以上。经过诉苦教育，他们就调转枪口打蒋介石。例如这次打陕州的炮兵，前一天才从灵宝解放过来，第二天原人原炮就参加了战斗，这是历史上世界上所少有的。我们的正规部队，从去年到今年，差不多增多了一半，野战军和地方部队已接近二百万人，蒋军总数也只有二百五十万，我们与他差不了多少，我们的主力走了以后，地方武装也能打下运城，围困汾阳。大的走了，小的就长大起来了。这真叫做大的不走，小的不长。

第二是土地改革。土地改革的影响，不仅在解放区，而且蒋管区的人民听了也喜欢。近来在华北开土地会议，要宣布一个新的土地纲领〔407〕，用彻底的办法平分土地。中国农民翻身，只有依靠共产党。要打倒蒋介石，土改和打仗，二者不能缺一。

第三是扩大解放区。去年一年，消灭敌人是在解放区以内，好处是我们有群众帮助。但是打一年可以，长此下去人民负担太重。只有打出去，才能吃蒋管区的饭，扩蒋管区的兵，打翻蒋介石的征兵计划，破坏他的总动员。当然也有困难，在新区地形不熟，人民还没有与我们打成一片。但困难是可以克服的。我们为人民办事，领导人民进行土地改革，就可以得到人民的积极拥护，解放区就可以更加扩大。

举行大反攻，国内条件都成熟了，再从国际形势看，许可不许可？关起门来计算可以有把握，但是美国人来了怎么办？对这个问题，我们要看世界大势，要分析，不要一提到美国就给吓住了。美国不可能用原子弹来对付农民战争。美帝国主义能给蒋介石什么东西？第一是给军火。过去他给了蒋介石多少？先是说给三十九个师的装备，后来给了四十五个师的装备，东北、山东给的最多，但是我们在这两个地区的缴获也最多，有什么可怕？第二是给钱。美国究竟能给他多少？从抗日以来共给了四十亿美元〔408〕，日本投降以来，占二十多亿，但是都被蒋介石用光了。美国还能再给多少？美帝国主义是“阔少”，很多国家都向他要钱，但他有多少钱？能给蒋介石多少？马歇尔〔362〕刚走不久，魏德迈〔409〕就来。为什么来？是想进一步控制蒋介石的军队与经济，经营台湾。宋子文〔410〕主张修铁路，建军事基地，筑海港，由美国控制。现在蒋介石卖国，让美帝国主义侵略，我们更容易动员人民反对蒋介石。第三，再厉害一些，就是美国出兵。那末美国共有多少兵？一百一十万。全世界许多地方他都要出兵，要多少？算他拿出二十万来中国，占全部兵力的五分之一。但二十万人放在中国算什么？顶多只能放在大城市，放在台湾。日本人在华北放过一百万，美国兵是少爷兵，就算他放上五十万，又算什么？同志们的确要打破以为美国了不起这样一个观念。如果美国真的出兵，那就完全暴露他的侵略面目，更利于我们动员人民。他顶多占几个城市。我们围困他，他不被歼灭就只有逃走。美国是可以打败的。不要以为我们在神泉堡这样落后的小地方不行，中国共产党就是这样，在落后的小地方干大事情！美国的困难多得很，他的政治、经济危机不能避免。世界人民的力量一天天大起来，美帝国主义的日子更不好过。

总之，我们打倒蒋介石是有把握的，第二年打出去，实行大反攻的决定是正确的。无论国内条件、国际条件，都是有根据的，是能够实现的。当然不是再打一年就能解决的，要到第三年，可能到第四年。今后两年我们将要登上山顶，还要鼓两年劲，蒋介石的力量已是下降的，但还没有下降到最低点。现在是运动战，将来还要打阵地战，太原等城市还放在那里，最后如果美帝国主义守上海，我们还是要收回，所以火力要发展，要打阵地战。我们还有困难，如军事工业基础薄弱、干部不足、粮食不宽裕等等，这些困难都要我们来克服。战胜蒋介石，也就是把美帝国主义在中国的根子挖去，所以战争不是小规模的。中国地区这样大，四万万五千万人翻了身，革命胜利了，对世界革命有很大意义。所以打倒蒋介石，不要说还要两年，就是五年也划得来。同志们大都是二三十岁的青年，还怕等不到成功？我还有这个信心呢！

同志们会问，我们现在还在乡村，蒋介石、美国人仍占着城市，如何取得城市取得全国胜利呢？中国革命就是农村包围城市而后夺取城市。主力打出去以后，地方武装起来“拔钉子”。不要看胡宗南今天还占了陕北多少城镇，一旦我们大军到了大关中，他不走也要被我们拔去的。城市要在最后取得，才是牢靠的。要从局部到全国，就是这样发展。我们是从井冈山起来的，现在要到处建立解放区，解放全中国，整个形势的发展趋势是定了的。这个规律，党的领导同志是熟悉的，现在全党同志都要熟悉这个规律。

全国大反攻，打倒蒋介石，是我们最兴奋最高兴的。无论在那个部门工作的同志，都要在自己的岗位上努力，都要做一个有用的螺丝钉，都要发挥自己的作用

打到南京去，活捉蒋介石！

＊一九四六年六月底，蒋介石发动大规模内战，对解放区实行全面进攻。我解放区军民奋起反击，经过八个月的激战，迫使蒋介石不得不改取重点进攻的方针。一九四七年七月至九月，蒋介石的重点进攻也被粉碎，我人民解放军转入了全国规模的大反攻。本文是在陕北佳县神泉堡对中共中央直属单位干部、战士所做的关于时局问题的报告。

