# 关于当前民主党派工作的意见

中文马克思主义文库 -> 周恩来
关于当前民主党派工作的意见
（一九四八年一月）

一、民主同盟〔331〕一部分中委已集会香港，恢复活动。国民党反对派已在香港成立革命委员会〔411〕，宣言反蒋。冯玉祥〔75〕在美组成“旅美中国和平民主同盟”，反对美援蒋内战，要求美助民盟获致中国和平。国民党已宣布开除冯玉祥党籍。另一方面，宋子文〔410〕确曾至港与李济深〔143〕、蔡廷锴〔412〕接洽。民盟及国民党民主人士多对冯、李、蔡等估计高，且有对两广反动当局伪装反蒋的阴谋感兴趣者。这一切，都需要我党对蒋管区民主党派问题根据中央去年十月二十七日指示〔413〕作进一步的具体的分析，并规定对待他们的明确方针。

二、自民盟在蒋管区被迫并由其一部分领导人接受国民党的命令自行宣布解散后，全国性的第三大党运动已经失败，第三条道路的想法已经破产。中国的民主运动，由于历史的发展，武装斗争成为主要形式。到了大革命后，就只有两个全国性大党，经过二十多年的斗争和战争，一天天证明中间道路即第三条道路已成为不可能。民盟由于抗战特别由于政协〔345〕的机缘，客观上一时造成了他在全国的第三党地位，使他中间许多领导人物代表着中产阶级的想法，企图在国共对立的纲领之外，寻找出第三条道路。但一接触到实际斗争，尤其是内战重起，就使他只能在靠近共产党或靠近国民党中选择道路，而不能有其他道路。青年党〔389〕、民社党〔393〕分子依其本来面目先后分裂出去，跟随国民党走了。其他民盟大多数分子在一个时期内，特别是在不参加“国大”、国民党政府和反对伪宪〔414〕的斗争中，是靠近共产党的，这就使民盟在人民中获得了信任。可是国民党威胁一来，民盟有的领导人就表态宣布解散，这又使民盟在人民中赢得的信任跟着丧失，从而也证明要想在国共之间建立起中间道路的第三大党运动是失败了。

三、指出第三大党运动的失败，中间道路想法的破产，并不等于说民盟不再恢复活动，国民党不可能分裂，各地小党派或其他人民政治团体从此也不存在了，也不等于说中间道路的想法就从此消失了。相反，在香港，在海外，乃至在蒋管区许多大城市中，现在已经有，将来还会有代表某些资产阶级集团，或地方性上层集团，或进步的民主分子集团的小党派出现。美蒋愈失败，他们会出现愈多。我们愈胜利，他们会愈要求到解放区来活动。这些党派之所以小而且常为地方性所局限，一方面由于他们在任何时候都不做或很少做群众工作，另方面由于斗争的尖锐，特别是长期地处在战争中，使他们很难在国共双方阵线之外有多少活动余地。因此，这些党派，除在纲领和行动上明显地靠近国民党或靠近共产党易于使我党决定对策者外，最值得注意的，还是些带中间性的民主党派及其所代表和影响的中产阶级、海外侨商及其他爱国分子。这些党派虽带中间性，但其组织成份又常从统治阶级内部的反对派一直包含到进步分子，如民主同盟、国民党革命委员会、民主建国会〔415〕等皆是，而其中政治倾向又从君主立宪〔416〕一直到新民主主义革命都有。尤其因为这些党派，现在多数处在香港或海外，无更多实际行动来证明其政治倾向，而美蒋正在华南运用伪装分裂的阴谋，冯、李、蔡等又是最易为美英政府所选择的对象。于是情势发展的复杂性，使我党在发展进步、争取中间、孤立右翼的统战政策上，在鼓吹好的、批评错的、揭露坏的宣传工作上，都需要有合乎马克思主义的认识和分析。

四、在革命战争和阶级变化的发展上，需要我党有领导的预见，但证实这个预见的正确，还需动员全党领导群众在实际工作中循着这个预见的方向努力奋斗，否则，预见便会落空。所以，宣传只能起原则启示和一般推动的作用，最主要的还靠群众自己切身经验来证明。如果空谈某某为君主立宪派，而不去争取民主同盟、国民党革命委员会、旅美中国和平民主同盟等走向进步，并在实际斗争中揭露美蒋阴谋，反对对美蒋的任何幻想与保存美帝侵略及中国大地主大资产阶级统治的任何企图，以证实和孤立这些君主立宪的右翼分子，那末，群众的觉悟不但不会提高，甚至还会反对我们的宣传，以为是无的放矢。可以说，这种宣传有不如无。应该记得，我党代表团在与民主同盟关于不参加南京“国大”的合作和斗争中，当时对于张君劢〔390〕等右翼分子乃至对青年党所采取的成功策略，并不在预言民社党、青年党一定参加“国大”，而在强调参加“国大”就一定破坏政协，成为蒋介石发动内战的帮凶，并欢迎任何人拒绝参加“国大”，连国民党代表在内。当时，我党及左派报纸刊物是配合这一宣传的。这样，就在群众面前孤立并抛弃了民社党、青年党，并阻止了民主同盟以后对于伪宪及改组政府的动摇。尤其应该记住毛泽东同志的统战方针：争取多数，反对少数，利用矛盾，各个击破。这在任何时候任何斗争场合都是坚定不移的原则。要了解那个多数一直要包含到敌人营垒中的少数开明分子（即封建买办阶级中的开明士绅、爱国分子等），均须以我党的行动纲领（即去年十二月二十五日毛泽东同志《目前形势和我们的任务》的报告及十月十日解放军宣言〔417〕、土地法大纲〔407〕）争取之。在利用敌人矛盾上，当其还只是反动统治内部的反动派及反蒋的地方实力派时，我们只能看做是间接同盟军；但当其已经改变立场，拥护我党行动纲领，公开反对美蒋时，我们就须采取欢迎态度，促其在行动中改造自己，证明其为直接同盟军。自然，这中间的不稳定性与投机性还会很大，我们应持若干保留态度，但也只有在加强我党领导和又团结又斗争中才能解决。

＊这是为中共中央起草的指示稿的节录。

