# 关于土改和整党问题给阜平中央局的电报

中文马克思主义文库 -> 周恩来
关于土改和整党问题给阜平中央局的电报
（一九四八年二月二十三日）


　　阜平局关于平分土地的指示，一般很好。中央发表了一个关于老区半老区的土地改革工作和整党工作的指示，除在那个文件中已经说到者外，另有几点与你们的指示有关者，告如下：
　　（一）关于土改，你们在乙项二节中，原已依据不同情况，规定各种地区的不同方针。但在乙项三、四、五三节中，却显得实现这个方针的分类和办法不够明确。在第三节土改较彻底区，规定一般土地不平差额如都在平均数百分之十以下，就不再分，至多把差额较大者加以调剂，但对差额如在平均数百分之十以上，则无规定。在第四节所指地区，规定如缺地农户在百分之四十或五十以下，平分时需抽出土地的户数在百分之二十以下，即不要平分，而采取中间不动两头动的办法。实际上，这种地区如是土改不彻底区，中间可能有小动，而缺地农户在百分之五十以上，抽地户数在百分之二十以下，仍可用调剂办法解决。如系土改极不彻底区，则又应平分，无所谓调剂。我们认为可以有这样两类地区，主要均由于土地已经变动，地富封建剥削已不存在或只存残余，而占有较多较好土地者，是干部、军属、烈属及一部分地富，故原则上，不应再来一次平分土地，而应是调剂土地。在第一类土改较彻底区，中农多，贫雇农少，故调剂范围就小。在第二类土改不彻底区，中农少，贫雇农多，故调剂范围就大。因中农多，其所有土地的平均数，就不可能与贫雇农所有土地的平均数相差太大，贫雇农少，其所需抽补的土地就不多，故应尽可能不动或少动中农的土地。反之，因中农少，其所有土地的平均数，就可能与贫雇农所有土地的平均数相差较大，贫雇农多，其所需抽补的土地就较多，故不得不动一部分中农的土地。照中央指示，在这后一类地区，凡中农所有土地的平均数，超过贫雇农所有土地的平均数在一倍上下者，在取得其本人同意后，可以抽出中农一部分土地，但以不超过其全部土地的四分之一为限度，似较合理些。望你们根据实情，加以斟酌。但这类地区，即使需要平分，也应当作是特殊的而不是一般的规定。在这类地区，你们规定了其他一些具体办法很好，在较彻底地区也一样适用。在土改极不彻底地区的主要情况，应是土改一般并未实施，地富封建剥削仍然存在，故原则应是平分土地，不是调剂土地，但办法仍应是抽补，而不是完全打烂。你们第四节第五节，如均系指这类地区，就无须划一界限，规定缺地农户在百分之五十以上抽地户数又在百分之二十以下时才平分，否则不平分而两头动。实际上，地富土地多，贫雇人数多，在实行抽补平分时，就是中间不动两头动。在这类地区，再规定某些中农占有土地不超过平均数百分之十者即不动，那对中农动的就会更少，你们在第四第五两节规定两种标准（百分之十与百分之五），也不甚妥。
　　（二）关于春耕生产问题，关系确是很大。但如为满足农民分地要求，而不问工作是否做到，条件是否成熟，只靠一股劲，就将三类地区的土地都调剂好或平分好，这恐怕是不可能的。凡是靠一股劲，就想完成这样细致的土改工作，最多象东北煮成夹生饭，还要再煮，否则，就会搞错了，还要纠正。贫雇农欲罢不能，而中农无心生产，大吃大喝，地富则对生产怠工，故意破坏，正证明我们工作尚未深入。如就在这样的基础上调剂土地，平分土地，其结果，可以想象得到不会很好。你们要研究绥德黄家川调剂土地的典型〔420〕，那样土改较彻底地区，还需要那样“深耕细作”的群众工作，那不彻底或很不彻底的地区，更可想而知。群众中此种情绪，你们还应在宣传上检查其影响，是否由于过去强调为贫雇农撑腰将中农冷落了，划分阶级有错误，宣传平分土地又没在抽补上定出办法，致中贫农情绪如此不同。而组织上又一下子停止几万村级地富党员的党籍，是否也起了副作用。凡此，你们应从造成这一心理现象的各种因素分析它的根源，迅速采取正确的领导和办法去纠正这些现象。同时，应根据中央的指示，并采用晋绥分局二月十日紧急通知及晋绥行署、农委会以命令保证的办法，使农民愿意加紧春耕，敢于发展生产，劳动致富。
　　（三）几万村级地富党员不加区别不分地区地一下子都停止党籍，也值得考虑。因为在地富党员本身，固然坏的投机的异己分子会多，但也不能说没有自愿放弃或脱离剥削关系的人，这是一。划成份既有错误，不能使中农党员不受影响而被当成富农党员处置，这是二。在抗战、自卫战期中，地方党吸收了这么多村级地富党员，党的高级领导毫无警觉，现在一下子全部停止党籍，乡村支部不会毫无影响，而且有可能是一种带普遍性的震动，这是三。各地方县、区、村领导者及工作团，是否都很健全，又处在战争中，对于这件事可能发生的副作用，能否应付裕如，这是四。这些，当然不是地富党员原则上是否还应留在党内的问题，而是实行步骤是否应该如此急促，如此不加区别的问题。你们对这件事的决定和实行，是否已筹划妥当，执行后的情形和影响又如何，均望你们搜集材料仔细研究后电告。你们既已下令停止地富党籍，如果现在又说不停止，当然不好。我们不是要你们取消过去停止党籍的规定，而是要你们研究停止后的结果如何，如果结果不好则应采取适当处理办法。在这里，我们认为平山用党内外民主结合的办法来整党审干是一个新创造，是最健全的整党方法。


　　＊这是为中共中央起草的指示。



