# 在部队中试验组织士兵委员会

中文马克思主义文库 -> 周恩来
在部队中试验组织士兵委员会
（一九四八年三月八日）


　　三查与诉苦的新式整军运动〔422〕，在我各野战军各军区部队中都已实行或正在实行着，其成绩已逐渐从部队的觉悟、巩固、团结、学习和作战上表现出来，其本身就是部队中政治经济军事三方面的民主精神的新创造新发扬。如果运动中尚有若干错误与偏差，大多由于领导者没能很好地掌握三查运动的正确方向，开始时不敢放手发动，发动后又未能预见一些“左”的偏向加以防止。但一般地说，这次新式整军运动的成绩却是极大，各战略单位都是有领导地有计划地有秩序地在进行。为巩固和发扬这一成绩，现在确实需要将这一民主精神的新运动转为部队中集中领导下的经常的民主生活。中共四军九次代表大会决议案上规定了的士兵会的组织，似较适宜。在名称上，究用士兵会与士兵委员会，或革命军人大会与革命军人委员会，可由各部酌定，主要的是其权限及其工作方式究应如何方为适当。现在这一组织，除在少数部队已开始建立外，大多数部队都还未着手组织。中央认为必须经过各军自己的实践，才能更有把握地对于这一组织作出适合于今天各种条件的具体规定。为此，中央特责成各野战军、各军区政治部于最近数月内，利用作战间隙，选择几个不同情况的连队，一两个不同情况的营以上的直属队或机关，试行这一组织，并派负责人员亲去指导，以便取得经验，报告中央。所谓不同情况，是指要选择连队中俘虏兵成份多或少、新兵多或少、连队或机关的行政领导强或弱、党的支部健全或不健全、前方或后方、火线上或休整中等的不同情况，得出不同的工作方式的规律。进行这一组织的基本原则大致是：
　　（一）这一组织不论在连队中，在机关中，必须在其直接的行政首长领导之下进行其政治经济军事文化的民主生活；
　　（二）这一组织的任何决定，必须得其行政首长批准后，方得实施；
　　（三）上级命令，这一组织必须绝对服从，无权变更，只在情况许可和需要时，得由其行政首长提交讨论这一命令中的实施办法；
　　（四）这一组织如欲对其行政上领导干部进行思想检讨，必须在情况许可和需要时，得到上级政治部的批准和领导，方准定期进行；
　　（五）这一组织中的一般批评与自我批评，亦必须领导其向着有利于战争胜利和部队巩固的方向进行。
　　各政治部在试行时，可根据自己所遇到的实际情况，使这些基本原则具体化，或加以新的补充。试行的经验不论好坏（而且必须看到好坏两方面），几个月后由各野战军、各军区政治部负责向中央提出意见，以便集中起来，规定最后办法。


　　＊这是为中共中央起草的指示。



