# 击破敌人假和平运动的阴谋

中文马克思主义文库 -> 周恩来
击破敌人假和平运动的阴谋
（一九四八年七月二十七日）

（一）在我人民解放战争日益胜利面前，国民党区域各阶级、党派、团体、个人都在为自己前途作打算。进步的及中间偏左的分子，多已表示赞成我党“五一”口号中召开新的政协会议〔423〕的主张。国民党反动统治中，则有不少的派别及个人，已在美帝国主义当权派的策动和鼓励下，进行一种假和平运动，企图利用国民党区域一部分人民中尚存在的对于和平的幻想，准备在蒋介石军队更加失败、国民党局势更加危急的时机发起政变，表面上牺牲蒋介石，宣布停战议和，实际上是为整个国民党反动统治取得喘息时间，以便休整兵力，卷土重来，消灭人民力量。在这一活动当中，许多地方系军阀政客，以李宗仁〔424〕为首，企图取蒋介石而代之。一部分中间派右翼分子，亦企图倒蒋取得权位，使中国革命限制于他们所要求的范围，避免彻底的改革。此外，确有一部分人民天真地认为在蒋倒之后会有和平，他们对于美帝、李宗仁及中间派右翼分子尚存幻想。至于蒋介石及其死党则将尽力挣扎，非至万不得已，不肯轻易下台。这样，就使在目前的革命战争和反美反蒋的人民运动之外，有一种复杂的情况和趋势在发展着。这一可能的发展，中央在去年十月曾经告诉你们，要你们在群众中进行准备工作，现在这种工作应当加紧进行。你们必须认识，美帝与某些国民党反动派所进行的和平阴谋，是对革命不利的，因为它能够欺骗群众。但在另一方面，倒蒋的活动，显示着国民党反动统治的极大分裂。蒋介石一倒，不管政变者使用什么法术，总是无法挽救反动派的命运，而且会加深国民党分崩离析的局面，这是对革命有利的。

（二）你们必须注视这一局势的发展。在人民中，在民主党派及民主分子中，根据事情的演变，不断地揭露美帝与中国反动分子的阴谋。你们必须注意具有说服性地而不是笼统地武断地分析这一阴谋的企图及其所具有的危险性，以打破他们对于倒蒋和平的幻想。同时，又要区别反动统治内部的倒蒋和平阴谋与人民群众及民主分子中的和平要求两者之间的不同性质。如果后者把自己的要求混同于前者，必致为反动分子所骗而阻碍革命的发展。如果后者把自己的要求严格区别于前者，则可利用反动统治内部的分裂而有助于革命的开展和胜利。所以，你们在国民党区不应笼统地反对和平，反对某些人倒蒋，而应利用各种倒蒋活动分化反动统治，便我各个击破，并准备将敌人的假和平运动转变为人民群众的真和平运动。这就是说，在凡有群众的地方，或在某些民主分子的集会中，当着反动派的倒蒋和平阴谋与人民的和平要求尚混杂在一起时，我们不要害怕和逃避，而应积极参加，领导群众，坚持人民对于和平民主独立的革命要求，以区别和揭破反动派的阴谋。同时，对于企图发动政变的国民党反蒋派别，当着他们找我们商谈时，你们亦不要拒绝商谈。一旦反动统治内部的政变果真爆发，我们便能有准备地将敌人的欺骗口号转变为群众的行动口号，这即是向代替蒋介石上台而依然是美国走狗的人们要求人民自由，保障生活，逮捕战犯，解散蒋军，取消伪宪伪国大，停止美援，撤退美军，没收官僚资本，实行土地改革等等，以推动人民革命运动的高涨，以配合人民革命战争走向全国胜利。同时，也只有这样做，才有可能使那些口头上反美反蒋分子即中间派右翼分子在行动上有所表现，或者跟着我党前进，或者暴露他们的虚伪而在人民面前破产。但你们必须注意，对于一切中间派右翼分子，只要他们尚处在中间地位，尚未公开站在美帝及其走狗一边，直接妨碍人民革命的发展时，我们还必须联合他们一道前进，不要不适当地和过分地打击他们。

（三）如果你们对于上述这一策略方针能有清楚的认识，并坚定而又灵活地执行下去，你们将有可能配合解放战争的胜利，在国民党区域进行活动，击破敌人的一切阴谋诡计。

＊这是为中共中央起草的指示稿，经毛泽东同志修改过。

