# 蒋管区斗争要有清醒头脑和灵活策略

中文马克思主义文库 -> 周恩来
蒋管区斗争要有清醒头脑和灵活策略
（一九四八年八月二十二日）

蒋近已决心撕破民主伪装的最后残余，实行疯狂的法西斯独裁的最后挣扎。其表现在经济方面的，已有财经紧急处分令〔425〕。其表现在政治方面的，已有特种刑事检举〔426〕。现北平已发出拘捕学生传票二百四十份，南京已发出传票一百四十份，上海、天津、广州、昆明及全国各蒋管区城市必将接着大行检举，必将由学生发展到工人、文化工作者及一切民主进步人士。在紧急处分令中，已禁止罢工、怠工，不久必将禁止其他一切群众活动。这是蒋在我人民解放军愈加胜利面前必然要采取的步骤和手段，这是蒋愈加接近死亡的表现。但蒋愈接近死亡，他的统治内部便会愈加分崩离析，各找生路，他统治下的群众便会愈加不能生活而走向革命化。到那时，蒋及其死党仍有可能在其最后据守的城市，继续其疯狂的法西斯的最后挣扎。但这种挣扎不是将自己的统治直接送进坟墓，便是被其统治内部在美帝国主义策动之下进行和平阴谋的政变所代替，从而也使代替者进入坟墓。因此，我党在国民党统治区的目前工作，必须有清醒的头脑和灵活的策略，必须依靠广大群众而不要犯冒险主义的错误。

在此原则下，针对当前紧急情况及可能发展的情势，除乡村在条件成熟的地区尽量发展武装斗争、在条件不成熟或我工作薄弱的地区坚持群众工作和隐蔽党的组织以待解放军的到来外，在城市方面，应坚决实行疏散隐蔽、积蓄力量、以待时机的方针。在国民党统治的城市，单独进行工人、市民的武装起义，肯定地说，一般地是不可能的。故城市的工人、学生及一切人民斗争的发展，在国民党反动武装力量尚能控制的地方，是有其一定限度的。超过这个限度，就是说要提出或接近于提出打倒蒋介石、推翻国民党反动政权的口号，采取或准备采取武装斗争的直接行动，都是不许可的，都有使少数先锋队脱离广大群众、遭受严重摧残与招致一时失败的危险。尤其是将城市中多年积聚的革命领导力量在解放军尚未逼近、敌人尚未最后崩溃之前过早地损失掉，这是最失策的事。根据最近上海来的材料，党的准备工作及学生运动情形，都有此冒险倾向，这对于今天的坚持，明天的配合解放军进城，或在反动统治内部举行政变时所需发动的人民革命运动，都是不利的。

现在敌人已向你们发出最后警号了。一切蒋管区的城市，尤其是上海，应实行有秩序的疏散。不论党内党外，凡是已经暴露或为敌特注意的分子，都应设法离开岗位，首先向解放区撤退。其已进入解放区受训者（如泊头），目前绝不容许再出去。如一时无法进入解放区而又有可能回至家乡者，即回家乡进行隐蔽工作；不能回家者，即须转移地区，另找职业隐蔽。凡未暴露而又未为敌特注意的分子，应继续深入隐蔽，在检举风浪过去后，再谋有步骤的发展，以便积蓄新的力量，等待时机。在这次大检举中的斗争策略，要依据各个单位自己群众的觉悟程度和人数，实行合法斗争（尽量利用统治内部的矛盾），如要求学校保护，反对特种刑事检举，在特种刑庭上据理力争，组织社会营救等。如果大多数学生已发生恐慌，不敢或不愿进行斗争，则不要使少数觉悟者单独去斗争。必须注意争取中间派，凡脱离中间派的群众行动必须力求避免。隐蔽后的组织形式，应采取抗战后期经验，实行平行组织、单线领导、转移地区不转关系的方针。在蒋管区城市中的党的领导机关，亦须严格遵守单线联络、分散领导的原则，不得违犯。必须认识敌人所欲打击的中心是我党组织，必然从公开检举当中寻找打击我党组织的线索，你们应特别注意党组织尤其领导机关的保护。对已经破坏的组织，不要急于恢复。对其中发生了叛变分子的关系，应暂时隔绝，待弄清情况，再谋处理。

无论反动派如何疯狂镇压，只要我党能有清醒的头脑，灵活的策略，并坚决依靠广大群众，而不犯冒险主义错误，我们是一定能够对付反动派的进攻，保持并发展自己的阵地的。

＊这是为中共中央起草的指示，经毛泽东同志修改过。

