# 关于和平谈判问题的报告

中文马克思主义文库 -> 周恩来
关于和平谈判问题的报告
（一九四九年四月十七日）


　　各位朋友：今天特别请诸位来此聚会。我们虽然来了二十多天，但因为忙，未及分头拜访和请教，很感不安。昨天我们请了住在北京、六国二饭店的朋友来谈，今天又请了各大学的教授及外面的朋友，向大家请教。
　　要谈的问题很多，今天只能把最近的和平谈判问题向诸位报告一下。这样的报告，我已经做过很多次。但这一次，我相信是与以前不同了。过去与蒋介石谈判，正如陈嘉庚先生〔432〕在一九四六年打给我的电报中所说，是“无异与虎谋皮”。但是又不能不谈，因为人民切望和平，而当时象陈嘉庚、张奚若〔433〕二先生这样的人还不多，广大人民还不了解蒋介石的和平骗局。今天情况变了。今天可以说，如果诸位赞成这次谈判所拟定的国内和平协定的话，不论和也好，打也好，我们有信心、有力量使它一定实现。我们要尽可能用和平方法来实现，但如果不能用和平方法，用战斗也一样要把它实现。这个变化是由于中国人民力量的壮大，由于国民党统治区民主运动的发展和人民解放军奋战的结果。关于民主运动，诸位知道的比我还多，我今天只把军事的胜利说一下。
　　蒋介石敢于撕毁政协决议发动战争，是靠着武装力量和美国援助。他当时的武装力量上的确占着优势。他有正规军四百三十万人，二百四十八个旅。这些都是在抗战中未受损失的，因为他实行的是消极抗战。一九四六年七月大打开始，他以为几个月就可以消灭人民解放军。但在两年零九个月中，却完全变了。头两年，战争平稳发展，我们每年消灭敌军一百五十万人，第三年起就起了突变，七个月（截至今年一月）就消灭敌军二百多万人。造成这个突变的是济南战役、辽沈战役、淮海战役及平津战役〔434〕。现在蒋介石的兵力，连后方机关如学校、后勤等在内，只有二百二十万人，正规军则只有一百多万人，其中不少是受过歼灭而又补充起来的，战斗力更弱。所以，蒋介石自己也知道，这个战争是失败了，他的反革命企图是失败了。
　　与此同时，我们的人民解放军壮大了。两年零九个月以前，人民解放军是一百二十万人，现在则发展到四百万人以上，并且大部分都美械化了。美帝国主义给了我们许多装备（当然，这是用不着打收条的），蒋介石做了很好的运输大队长。我们的战士有很大部分是俘虏过来的，称为解放战士，有的部队，解放战士竟占百分之八十，少的也占百分之五十至六十，平均约占百分之六十五至七十。对于俘虏，我们实行即俘、即查、即补、即训、即打的办法，就是说士兵一俘虏过来就补充到部队，经过诉苦教育，就参加作战。在打黄伯韬〔435〕时，情形竟发展到上午的俘虏下午就参加作战。当时的解放战士现在有许多已经做了排长、连长。这种情形是世界战史上所少有的，若没有高度的政治训练是不可能的。今天我们部队民主化程度之高，连我们指挥的人都没有想到。虽然毛泽东同志在井冈山时期就提出了在部队中建立民主集中制的制度，但今天的发展的确出乎我们的意料之外。在三评运动中，革命士兵委员会可以批评干部，可以推荐下级指挥员，推荐得对的就批准，而且多数是批准的。为什么可以这样做呢？因为士兵们很了解，指挥员必须是能勇敢作战的，并且必须有智慧，单单勇敢是不够的，然后才是态度。所以士兵们的推荐多数是对的。这是评干部。其次是评党员。公开党员，让群众来批评党员，使党真正受群众监督。第三是评战功。谁有功，群众知道得最清楚，群众来评，自然可以评得最确当，也只有这样，才能真正做到赏罚分明。民主扩大了，纪律加强了，指挥员们说现在的部队可好带了，士兵们说指挥员的态度变好了。我们的军队不但在政治方面是民主的，而且在军事方面也有民主。我们有时甚至还准许士兵讨论作战命令。每个战斗小组都开“诸葛亮会”，取“三个臭皮匠赛过一个诸葛亮”之意。上级命令不可能很具体，下到连队后，战斗小组就开“诸葛亮会”讨论如何具体执行，这样充分发挥了士兵的积极性和创造性。这在短兵相接的今天，更是特别需要。淮海战役中，敌人的工事星罗棋布，但一夜之后，情形变了，我们的工事包围了他们的工事。士兵们设法钻过敌人的工事，破坏它，而建立起自己的工事。打仗还要靠炸药，但这些物质的死的东西要靠活人来使用。没有士兵的勇敢和智慧，炸药也就没有用处。我们的士兵又勇敢又有智慧，没有炸不了的堡垒。即便是水泥工事做得好，一斤炸药不行，就用五斤、十斤、一百斤、二百斤，终归可以炸毁的。矿山石头都可以炸开，何况工事？敌人称这为“土飞机”。这种“土飞机”需要靠下面，单靠上面是不行的。王耀武曾问我们，为什么蒋介石飞到那里，他们那里就打败仗，毛主席天天坐在陕北，却处处打胜仗？这是因为人民觉悟了，因为我们这个部队是中国共产党领导的，是人民大众的，是我们大家的。人民解放军今天的水平，比我们想象的还要高。所以，敌人也不能不承认失败了。
　　这样一来，南京反动政府在一月一日不得不提出和平建议〔436〕。尽管建议是虚伪的，条件是不能接受的，但和平建议我们却要拿过来。人民要真和平，我们也要真和平，毛泽东同志一月十四日声明中提出的八项条件〔437〕，就是真和平的条件。蒋介石不接受，天津一解放，他只好下台〔438〕，让李宗仁〔424〕代替他，这就表示南京统治集团内部已开始分裂出一个主和派。李宗仁接受八项条件作为谈判基础，派私人代表团〔439〕来平，最后我们接待了南京国民党政府代表团〔440〕。我们为什么这样做呢？因为今天胜利局面已定，用战斗方式可以解决是毫无问题了，只是时间早迟而已。我们现在要考虑的是如何用和平方式来达到胜利，以便使国家少受破坏，多保存一些人力物力，使将来的和平建设多一份物质力量。中国太落后，现代性工业在国民经济中只占百分之十左右〔441〕，需要用极大的努力才能使国家现代化。中国人民在战争中已经付出了很大的代价，战场上敌我的伤亡和人民群众的损失都很大。例如淮海战场上几百个村落全都毁了，现在我们正在进行救济。这样的损伤自然是以就此终止为最好。但是，和平需要双方同意。李宗仁既然表示愿意接受，和平总算有了可能，我们就要抓紧，并将这一可能性加以发展。我们不但看到了人民力量的壮大，也看到了敌人的分化。我们要争取主和派力量的发展，争取他们和我们合作。美国帮助蒋介石打了三年内战，现在也承认失败了，所以他要制造某种和平局面，派代理人钻进人民国家内部来活动。这也助长了南京政府和平谈判的意愿。国民党反动集团的大肆搜刮，刮得上海资产阶级也受不住了，他们要求和平。除此以外，国民党统治区广大的公教人员也是一个和平因素，金元券〔442〕实在弄得他们活不下去了。由于以上的各种因素，才有这次和平谈判。在谈了十多天后，我们已经将一个最后的和平方案交给南京代表团，由他们送交南京国民党政府。
　　国内和平协定八条二十四款，中心问题是接收和改编。南京代表团和我们固然是有距离，但他们有一个概念是好的，即国民党的失败是一定的，人民解放军的胜利是一定的，他们承认错误，承认失败，因而愿意交出政权，交出军队。不过，南京代表团虽有此认识，南京政府却还没有这个认识，至于广州、溪口〔443〕就更不用说了。
　　关于接收。今天的革命，决不能再如辛亥革命〔147〕和北伐战争〔121〕那样，由于中途妥协而使反动派最后又得到胜利。历史经验证明，革命如不能进行到底，则一定失败。今天我们决不能再蹈此覆辙。南京代表团说，国共两党历史上的争论是兄弟之争，我们给了他们严正的批评。这不能叫做兄弟之争。难道孙中山与袁世凯之争是兄弟之争吗？不，这是革命与反革命之争。我们近二十年来与国民党之争也是如此。不过，南京代表团和我们之间在为和平民主的共同基础上的争论，还可以算是兄弟之争。在这种场合，我们必须坚持严肃的原则性，决不能混淆是非。我们之所以坚持要用人民解放军去接收，因为这是关系革命到底不到底的问题。辛亥革命后，督军等等还是一概仍旧，只是换了一面旗。大革命时，北伐军到长江下游后，连国民党都说，是“军事北伐，政治南伐”。这样，革命就变了质。张治中〔327〕说起“前车之鉴”，那么，这就是“前车之鉴”。如果今天也是只换一面旗，让各色反动派依然压迫人民，照样滥发金元券，则人民的痛苦如故，人民就要骂我们。这不是对人民负责的做法。不推翻旧的，就不能建立起革命的新秩序；人民解放军不去，政权的性质就不能变更，反动军队就不能改编，生产就搞不起来。但接收也不简单，需要时间和人才，我们要有组织地接收。接收将是先城市而后乡村。人才方面，单是共产党绝对不够，必须各方人士大家来做。等到渡了江，北京、六国二饭店恐怕不免就要“人去楼空”。我们兢兢业业，怕搞不好，但我们不能放弃责任。将来在联合政府中也是如此。正因为我们人力不够，有些地方一时还接收不了。苏、浙、皖、鄂、陕、陇东将最先接收，其他地方只好缓一下。南京代表团总希望我们慢一点渡江。当我把和平协定草案交给他们时，他们问我有没有渡江的条款，我说没有，他们顿觉惊喜交集。但我说，虽没有“渡江”，却有“接收”。其实，渡江根本不能算是一个条件，许多接收的地方都在江南，何况长江在历史上也从来没有阻止过中国的统一。南京和溪口还没有完全割断，即所谓“藕断丝连”。他们说要等我们去割，我们则要他们先从政治上割断，军事上可以由我们来割。南京代表团不能反对我们过江，因为既然承认我们去接收，当然就必须承认我们渡江。但他们总希望慢一点。至于广州、溪口则希望划江而治。我们指明，慢一点渡江，无异给广州、溪口以掩护，使他们获得喘息机会。这一点，南京代表团无法反驳。
　　关于改编，即改编军队。不如此就不能根绝内战因素。但又不能急躁，条件要宽大。我们的改编条件，甚至比南京代表团所提出的还要宽大。例如，他们曾主张裁兵复员，我们则主张一律集中整训。毛泽东同志对这一点尤其强调。初看起来，这好象是违背民意，所以对这一点就不能不多加解释。国民党军队二百多万人，一听到裁兵，就会发生动摇，各作打算，于是不免要造成骚乱，到处危害人民。我们要采取对人民负责的态度。所以我们提出在第一阶段中，按照原人数、原编制、原番号集中整训，并且一律与解放军同等待遇（每人每日四斤半小米）。毛泽东同志还说：“你报多少就算多少。”多支付几个月的空额饷不算什么。我们不会象从前国民党对待八路军那样，对他们有所歧视。这样，应该说已经做到仁至义尽，中国人民没有什么对不起他们之处了。如果还要闹，就严正制止。经过集中整训，士兵有了觉悟，军官得到学习，就可以改编为人民解放军。但我们不能急躁，集中后要分别对待，等待觉悟。觉悟有快有慢，相信他们大部分都会转变过来的。当然，也会有捣乱的。
　　有了政权的接收和军队的改编，才能实现真正的和平。这就是国内和平协定中的四、八两条。
　　关于第一条，惩办战争罪犯，南京代表团争得厉害。我们尊重他们的意见未将战犯名单列上去，“元凶”、“首恶”等字眼也都勾去，而且说，“一切战犯，不问何人，如能认清是非，翻然悔悟，出于真心实意，确有事实表现，因而有利于中国人民解放事业之推进，有利于用和平方法解决国内问题者，准予取消战犯罪名，给以宽大待遇”。有人问，对蒋介石怎么办？如果他能做到这一条，那么也照这样办。
　　关于二、三两条，废除伪宪法、伪法统，没有多大争论。但这自然是不大容易的。
　　关于五、六两条，没收官僚资本，改革土地制度。我们对没收官僚资本作了解释，即没收南京国民党统治时期取得的官僚资本，凡是不大的企业且与国计民生无害者，就不没收了。若有私人股份，经查明并非官僚资本转移的，一律承认。不如此，就会牵涉太广，影响生产的进行。
　　关于第七条，废除卖国条约。对于这个问题，我们是很谨慎的。对外条约有的要废除，有的则要加以修改，有的还可以保持。
　　我们对外交问题有一个基本的立场，即中华民族独立的立场，独立自主、自力更生的立场。自鸦片战争以来，中国一向受着外国侵略者的压迫。多少先烈为了民族的解放流血牺牲，但这种压迫一直未能除去。今天，中国人民站起来了，扬眉吐气了！这是中国共产党领导中国人民奋斗的结果。日本帝国主义在中国失败了，美国帝国主义也正在失败。美帝国主义固然还是强大的，但他是外强中干的。我们与美帝也交过手，文仗武仗都打过。文仗和马歇尔〔362〕打了一年，最后他还是失败而去。帝国主义就是纸老虎，你硬一点，他就软些，你软一点，他就骑到你的头上。在原则性的问题上我们是不让的，决不让。对于美帝国主义，我们一定要采取严肃的态度，使他了解中国是不可欺侮的。任何国家都不能干涉中国的内政。我们就是为此而奋斗了一百多年！我们要自力更生，然后才能争取外援。外援如有利于中国，当然要，但不能依赖。即使对于苏联及各人民民主国家，我们也不能有依赖之心。如果只依赖外援，那还能办什么事？蒋介石失败的主要原因之一，就是一切依赖外援，这是“前车之鉴”。我们愿意和一切以平等待我之国家合作。我们不排外，不挑衅，但必须站稳立场，否则就只能倒在外国人的怀里。中国共产党就是带着打倒军阀、打倒帝国主义的伟大气概开始的。虽然当时只有五十多个人，其中李大钊同志〔132〕英勇壮烈，血洒北平。但任何新生事物在开始时都不过是一枝幼苗，一切新生事物之可贵，就因为在这新生的幼苗中，有无限的活力在成长，成长为巨人，成长为力量。这是自然的规律。一切腐朽的东西，尽管是一大堆，但必然一天一天死亡，没有什么了不起。我们站稳了立场，又要很谨慎，有理有利有节地去处理问题。这和五四时代的反封建有相同之处，那时反对封建很坚决，提出打倒孔夫子、对封建家庭斗争的口号。但今天看来，孔夫子的话若是好的，我们也可引用。我们的父母来了，也还得照顾照顾。对封建要划清界限，站稳立场，同时采取分析态度，对帝国主义也要如此。
　　在军事上，美国军队驻在中国无论如何总是缺理的。我们叫他们退出去，这是全中国人民的呼声。他们国家的事我们管不了，但在中国的领土上，美军若不退出，我们就有权消灭他们。美国若是大规模出兵，我们也不怕。中国是吓不倒的。中国是古老的民族，也是勇敢的民族。中华民族有两大优点：勇敢，勤劳。这样的民族多么可爱，我们爱我们的民族（当然其他民族也有他们可爱之处，我们决不忽视这一点），这是我们自信心的泉源。美军若真敢侵略到中国来，占领我们的大城市，我们就用乡村包围城市，叫他们什么军需品（包括大便纸和冰淇淋）都必须从美国运来，还要背上大城市这样的包袱，负责供养。美国人生活程度高，他们是不愿打仗的。俄国十月革命后，美国也闹过出兵干涉，结果还不是“自动撤退”〔444〕？就因为吃不了苦。我们打败了日本侵略军，难道还怕美国兵？
　　在政治上，我们的立场仍然是民族独立，平等相待。美国国会在吵嚷承认不承认中国。其实，这有什么了不起！即使你承认我，我承认不承认你还尚待考虑。不过我们不挑衅。我们虽未与他们建立外交关系，但对侨民还是保护的。美国驻天津总领事以总领事的资格递来一封信，我们就退回去，说没有外交关系，恕不来往。后来他用铁路职员的名义写信来，我们就让他登记。其实，美国也不是不要和中国往来，司徒雷登〔382〕一直到处找我们拉关系。傅泾波〔445〕在香港老是给我和邓颖超及其他的人写信。美国人是两面做法，想用各种办法来试探，要看看中共动向如何。中共的动向是容易明白的，只要听一次报告或看几个文告就知道了。至于将来和平实现后的情形，我们会实事求是地处理，反正各国大使馆在那里，我们既不断绝，也不急于建立外交关系。如果急于要求承认，就会陷于被动。帝国主义若要同我们建立外交关系，就要按平等原则进行谈判。我们在政治上不排外，在军事上不挑衅，有理有利有节，我们又何惧之有呢？
　　在经济上，有买卖就做，国际贸易要开展，这是于双方都有利的。帝国主义的特权，我们不承认，但此中问题很复杂，不能遽然解决。
　　在文化上，帝国主义有许多侵略机构，如学校、医院及教堂等，这些都应该由中国人来办，但不能急躁，要谨慎地一步步地来。这些文化机构有坏的一面，但还有好的一面，例如协和医院，我们的人生了病还去那里就医。对于这些机构，我们可以从内部来改造，使它们变成民族的。
　　关于第八条，再补充一点。在联合政府成立之前，我们允许南京政府还存在一个时期。起先我们想用革命军事委员会来指挥它，南京代表团觉得不好，我们取消了这个主张，而使二者平列。若南京政府签订了和平协定，并且履行了，则我们保证负责向政协筹备会提出让他们参加新政协。当然，通得过与否，那是另一问题。
　　这八条二十四款，南京代表团表示可以接受。我们限定南京国民党政府在二十日以前答复，如不接受，则二十日我们一定打过江去。再不过江，连南京代表团都说，江南人民实在受不住了。所以不能再延了，再延就太对不起那里的人民了。当然，打过江后，如果他们又愿意签字也可以。总之，门是开着的。南京代表团以为我们老是要和平，一定有弱点。第一，他们见我们快要当家了，以为我们很怕破坏，老鼠蹲在花瓶上，投鼠要忌器。第二，面对滔滔长江，他们以为我们一定很怕牺牲。所以，他们老是讲价钱。其实，他们只知其一，不知其二。和平也不免有破坏，战争也不见得就把一切都打碎，总有打不碎的，或者我们去得快些，他们来不及破坏。我们不过是争取愈少破坏愈好罢了。所以，这是吓不了人的。我们明白告诉他们：战，他们就要完蛋，和，他们还可以有出路，当然不是什么南北朝，而是改造。
　　各位朋友，中国新民主主义政治是四个阶级合作的。即使是地主，在劳动几年之后，也可以变为农民。过去因为环境不同，我们不在一起，今天既然到了统一的环境，就可以大家一起来干。非共产党人也照样能工作，甚至做得更好。共产党人不是天生的。我的先代是“绍兴师爷”〔446〕，什么“少有大志”，那是鬼话。
　　国内和平协定八条二十四款一定要实现，不论用战斗或是用和平的方法。用和平方法比战斗还要忙，要大家帮助。希望在小组讨论或座谈会中提出意见。我们长期在农村，对城市已经很生疏了，希望大家多多指教。


　　＊这是向来北平参加即将召开的新政治协商会议的部分爱国民主人士、北平一些大学教授做的报告。



