# 学习毛泽东

中文马克思主义文库 -> 周恩来
学习毛泽东
（一九四九年五月七日）

中国人民的大革命已经走向全国胜利，我们青年要加紧参加建设新中国的事业。我们必须有一个大家共同承认的领袖，这样的领袖能够带着我们前进。三十年革命运动的实践使中国人民有了自己的领袖，就是毛泽东。我们这次全国青年代表大会〔448〕的口号也是“在毛泽东的旗帜下前进”。我们决心举着这面旗帜前进。在今天这个会上，我想把毛泽东同志如何值得我们尊敬和我们如何向他学习的主要的几点给大家说一说。

学习毛泽东不是一个简单的口号，而是有极其丰富的内容的。我们青年代表回去，要向全国广大青年——农村、工厂、城市、解放区、国民党统治区的青年，宣传我们代表大会的主张，动员和争取千千万万的青年群众跟着我们一道前进。在这一点上，毛泽东的旗帜就是我们最好的号召。我们号召全国青年跟着这个旗帜走，就必须认识这个旗帜是怎样发展到今天的。毛泽东是在中国的土壤中生长出来的巨大人物。在座的朋友们向全国青年宣传的时候，或者是自己学习的时候，决不要把毛泽东看成一个偶然的、天生的、神秘的、无法学习的领袖。如果这样，我们承认我们的领袖就成了空谈。既然是谁也不能学习，那么毛泽东不就被大家孤立起来了吗？我们不就把毛泽东当成一个孤立的神了吗？那是封建社会、资产阶级社会所宣传的领袖。我们的领袖是从人民当中生长出来的，是跟中国人民血肉相联的，是跟中国的大地、中国的社会密切相关的，是从中国近百年来和“五四”以来的革命运动、多少年革命历史的经验教训中产生的人民领袖。因此，学习毛泽东必须全面地学习，从他的历史发展来学习，不要只看今天的成就伟大而不看历史的发展。

毛主席常说，他是从农村中生长出来的孩子，开始也是迷信的，甚至某些思想是落后的。他最不同意晋察冀一个课本描写他在十岁的时候就反对迷信，说他从小就不信神。他说恰恰相反，他在小时候也是相信神的，而且信得很厉害。当他妈妈生病的时候，他去求神拜佛。你看这样还不够迷信吗？那个课本写毛主席的故事，把事情反过来，说他从小就不迷信，打破迷信，生而知之。毛主席说，这是不合事实的。而且一般地说，在那样的封建社会里，不管农民家庭出身的也好，工人家庭出身的也好，一下打破迷信是不可能的。毛主席生长在十九世纪末的农村里，不可能没有一点迷信。为什么要说明这个问题呢？就是我们在广大青年队伍中，不要因为有的人还迷信就认为他不可教育，就排斥他。昨天迷信的孩子可以变成今天的毛主席（当然我不是说所有的孩子都可以成毛主席）。迷信是可以打破的。早两年你还不是迷信！你年轻时还不是有丑鼻涕！不要进步了对小孩时的丑事就不愿正视了。

毛主席常说，他也是读古书的人。读古书看你会读不会读。毛主席开始很喜欢读古书，现在做文章、讲话常常运用历史经验教训，运用得最熟练。读古书使他的知识更广更博，更增加了他的伟大。“五四”那天我看到范文澜同志〔449〕写的一篇文章，说五四运动前后他就专门研究汉学〔450〕，学习旧的东西。但是当他一旦脑子通了，对编写中国历史就有帮助，就可以运用自如。所以在我们青年中，也不要因为有一部分人喜欢读旧书、研究旧东西就认为他们不可以进步，不要因为他有旧观念就不去团结他教育他，不要因为他落后一点就不理他。只要他愿意进步，就有改造的可能。毛主席说，他自己就是这样改造过来的。

毛主席还常说，他开始研究东西也是先搞一个方面，没有通就钻进去，先把这方面搞清楚。“五四”以后，毛主席参加了革命运动，就先在城市专心致志地搞工人运动。那时陶行知先生提倡乡村运动。恽代英同志〔279〕给毛主席写信说，我们也可以学习陶行知〔280〕到乡村里搞一搞。毛主席说，现在城市工作还忙不过来，怎么能再去搞乡村呢？这就说明毛主席当时没有顾到另一方面。但后来毛主席很快就转到乡村，又把农民运动搞通了，使城市和乡村的革命运动结合起来。以后又搞军事，都搞通了，并且全面了。这也就告诉我们，有些青年人研究问题还没有进到全面，喜欢专心致志地搞一面，我们不要去打消他的兴趣；即使他不愿参加政治活动，我们也不要排斥他，可以慢慢地教育。

我讲这三个例子是说明：毛主席也是封建社会农民家庭出身的一个孩子，也曾经迷信过，也曾经读过古书，也曾经研究问题开始只注重一个方面。他之所以伟大，在于他能够从迷信中觉悟出来，否定旧的东西；他之所以伟大，更在于他敢于承认旧的过去。我们看到在旧社会里有这样的人，乃至在人民统治的社会里也有这样的人，一旦有了进步，就觉得自己过去什么都了不起，是“天生的圣人”，把自己说得简直什么错误都没有，什么缺点都没有。人家这样说他，他也喜欢听。那就危险之至。所以对那些有迷信的青年，落后的青年，只认识片面不认识全面的青年，我们不要抛弃他们，要去教育他们。我们青年要互相学习，要让这些人跟着我们学习，同时我们也跟着他们学习。毛主席是从几千年的历史经验教训、近百年的革命运动、近三十年来的直接奋斗中生长出来的人民领袖。我们大家要从这方面来看毛主席的历史发展。这样，同志们中有了骄气就可以压下去了。毛主席都是如此，我们还有什么可以骄傲的呢？那一个人没有错误没有缺点？还值得骄傲？比毛主席差得远！

我们要学习毛泽东，还因为他是最能坚持原则又最能灵活运用的领袖。中国的革命自从他参加领导以后，方向就一天天地端正起来。毛主席在中国革命的四个阶段都是正确的，都是代表中国人民的正确方向的。开始的时候，党中央也好，一部分革命群众也好，常常自己弄错方向，迷失方向，但是毛主席的方向始终是正确的。大革命时期毛主席的主张是对的，但是没有被当时的领导上接受。十年内战时期他是对的，当时也有一些同志搞错了，没有完全同意他的意见。抗战时期，全党承认毛泽东同志的领导，抗战成功了。到这次解放战争，更加证明其正确。所以毛主席的方向就是中国人民正确的方向。他不断地指出真理，坚持真理。这就是我们常说的：毛主席把世界革命的真理——马克思列宁主义的普遍真理运用到中国，同中国的革命实践结合起来，成为毛泽东思想。毛泽东是这样指出真理的人，坚持真理的人，发挥真理的人。在中国革命三十年中的许多历史关键时刻，他的方向都是正确的。

毛主席坚持原则之中有两点值得我们学习：一、坚持方向；二、实现方向。方向的实现，只有一个人懂或者少数人赞成是不成的，要在群众中实现。要实现原则，就要使它具体化，使它能得到多数人的同意，多数人都来执行。坚持真理是会遇到困难的。毛主席不仅指出了原则，而且还制定具体的政策、策略来实现这个原则，每个历史时期的政策都是适合这个时期的。这一点，青年们在研究《毛泽东选集》时就可以看到。大革命时期，必须使农民运动深入发展到解决农民的土地要求。毛主席的《湖南农民运动考察报告》就说明了这个真理，拥护农民提出的办法，并加以发挥，不但有理论，而且有实践的办法。不过当时共产党的领导机关没有接受，大革命失败了。内战时期，毛主席提倡军队中的政治工作。你们去研究毛主席在红四军第九次党的代表大会上提出的决议案，今天人民解放军中所实施的政治工作就是从那时一直发展下来的。但是毛主席的主张经过多年才逐步实现，中间遇到许许多多的挫折。当时大家虽然在形式上接受了，但是要经过很长的时间，真正到实际中具体化了，大家才能懂得它的威力。抗战中要团结蒋介石的政府来抗日，明知道他动摇、消极，但是必须推动他抗日，才能动员全民族的力量。既要团结他，又要防备他，同他的反动的一面作斗争，所谓“有团结有斗争”。用这样的策略来进行抗战，使人民自己的力量壮大，这就需要说服很多人同意。在抗日民族统一战线中就有一些人说，既然要团结就不要批评。党内也有人有这样的意见。所以要使这个原则真正实施，就要经过许多曲折的斗争。解放战争比较顺利，但也还有小的挫折和错误，譬如土地改革中，也曾发生过“左”的错误，一直等到毛主席一九四七年十二月二十五日的报告〔451〕出来了才得到全面的纠正。这都说明，一个原则、真理、政策在实际中实施，是要费很大的力量，做许多的具体工作的。毛主席不但能够坚持真理，指示方向，而且还拟定了许多具体政策、策略来贯彻这个真理、原则。不如此就无法使革命达到胜利。所以毛主席不是空谈真理，而是使真理和实践相结合，使它具体化。这样才能有今天的胜利。我们青年人学习毛泽东，不仅要懂得毛主席指示的方向、原则、真理，还要研究他的具体的政策、策略，才能使我们的工作深入实际。我们青年人不是要空谈，而是要实行。世界无产阶级的伟大的革命领袖列宁也说过，“少说些漂亮话，多做些日常平凡的事情”〔452〕。这对于我们青年正是一个宝贵的教训。毛泽东思想的特点，就是把普遍真理具体化，运用到中国的土壤上。我们青年要在这上边来学习。

毛主席使普遍的真理具体化，实现在中国土壤上的时候，并不是说，定出办法来就算了，不管大家懂不懂，接受不接受，说做就由几个人孤立地去做。不是这样的。毛主席总是再三再四地舌敝唇焦地讲，反复地讲，使这个真理为大家接受，变成了力量。所以要想把领导者的觉悟、领导者的智慧变成群众的力量，需要经过教育的过程，说服的过程，有时需要经过等待的过程，等待群众的觉悟。毛主席当着他的意见没有被大家接受时，他就等待，有机会他就又讲，又教育，又说服。毛主席在党内也碰到过这样的情形，他的意见不为大家所接受，如我刚才说的，在十年内战的时候就是如此。我们主张打大城市，毛主席认为我们的力量小，不应该打大城市，应该集中力量建设根据地。但是毛主席的意见大多数不赞成，大家要打，他也只好跟着打。结果打败了，毛主席赶快在会议上提出：打败了证明这个办法不行，换一换吧！大家还不接受，他只好再等待，又跟着大家走。象刚才说的万里长征，就因为在江西打败了，硬拚消耗，拚到最后挡不住了，不得不退出江西。在长征路上，毛主席又提出了他的正确意见，在遵义会议上纠正了错误路线，带着红军爬雪山、过草地，冲出了危险的局面，到达了陕北。最后证明毛主席的主张是对的，多数是错的。这都说明，正确的意见不为大家所接受的时候，怎么办？就要等待，就要说服。大多数人通过的决定，组织上还要服从。当着群众被蒙蔽的时候，不容易接受真理，等他们慢慢地觉悟起来以后，就会拥护正确的意见。所以正确的意见常常是要经过许多等待、迂回才能取得胜利，为大家所接受。当然这个等待过程是痛苦的。假使那时党的领导机关很早就接受了毛主席的正确意见，革命就不会受那么大的损失，我们的力量就会更加壮大。但是我们这个落后的中国社会，反映到党内，反映到革命团体里，正确的意见常常不容易被大家立刻认识。这样就要等待、说服，就要经过痛苦的过程。不过，这种情形在今后的工作中遇见的会少了。因为今天共产党的中央不象当年了，绝大多数同志都承认毛泽东这个领袖，都心悦诚服地信服这个领袖；在人民中也拥护这个领袖。但是，这也仅仅在大的方向上。譬如说，今天要把革命进行到底，要进行新民主主义建设，在这样大的方向上大家都同意，而在具体的政策、工作上还是会有很多争论的。所以就需要学习，学习毛主席这种坚持真理，指示原则方向并将其具体化，成为人民的力量的过程。这不是急躁所能做好的，要有很大的坚持性忍耐性，不屈不挠地把革命推向前进，这样才能达到最后的胜利。我们不能认为把一个简单的口号提出来就算了，就够了；也不能行不通就失望，行得通就自满，不再前进。那就不是毛主席的好学生。毛主席坚持把马克思列宁主义的普遍真理具体化在中国土壤上，生长出来成为群众的力量，所以中国革命得到如此伟大的胜利。到今天，不仅中国共产党尊敬他，凡是得到革命胜利果实的人民，一定都会逐渐心悦诚服地信服他。

毛主席在坚持真理、实现真理中还有一个经验，就是他所提出的原则总是照顾大多数，为着大多数人民的利益。不错，毛主席是中国共产党的领袖，同时今天大家也都承认他是全国人民的领袖。从中国共产党的范围来说，他是代表无产阶级的。中国的无产阶级数量只有几百万，在全中国的人口中连百分之一还不到。代表这样一个阶级的共产党怎样才能取得中国革命的胜利？毛主席的根本着眼点就是把无产阶级的马克思主义思想运用到中国，争取最广大的人民大众团结在无产阶级周围来取得革命的胜利，而不是把自己缩小到最小的圈子里来空谈革命。毛主席懂得，为把最反动的敌人消灭，就需要集合一切可能集合的力量，而不是只靠先锋队办事。无产阶级是先锋队，但不能仅靠先锋队。在大革命时，毛主席就看到农民是最广大的同盟军，不依靠农民，人民革命是不能胜利的。果然，不听他的话，革命就失败。后来我们到了农村，毛主席又看到革命不但要依靠农民，而且还要争取中小资产阶级，因为当时蒋介石反革命的恶迹更加暴露，只有买办官僚地主封建阶级才拥护他。但是在共产党内有一部分人又犯了“左”倾错误，眼光狭小得很，认为中小资产阶级都不可靠。他们不听毛主席的话，致使革命又受到一次挫折，走了一个两万五千里。以后，毛主席提出团结蒋介石上层分子抗战。有人就说，要团结就不要斗争。毛主席说，这些人是我们国内的敌人，为了打民族敌人，要团结他，但他并不是可靠的合作者、同盟者，还要提防他，如果不加提防，他反过头来就会咬你。当时毛主席就防止了右，防止了无条件妥协。这一次解放战争，在乡村搞土改，工作中又犯过“左”倾错误。因为要消灭地主，就不给地主土地，或者给地主坏地，使他们不能生活，或者定的封建富农、地主的数量过多。另外，在杀人问题上，本是除怙恶不悛、人人痛恨的要杀外，其他可以不杀，但是有时候在群众愤恨之下，没有加以区别，领导没有说服群众，以致杀人过多。这样就使我们阵线中的农民，首先是中农受到影响。这个错误，也是毛主席把它纠正了。从这四个革命阶段可以看出，毛主席统一战线的观点是要团结最广大的同盟军，各个击破敌人。在抗日时期，就是打倒日本帝国主义。日本帝国主义被打走后，再打倒国民党反动派，推翻中国的反动统治。在乡村中，打倒封建地主阶级——这是反动统治的根基。在国际上，反对美国帝国主义对中国的侵略。围绕着这些口号，把更广大的农民团结在一起，把百分之九十以上的人民团结在一起。所以毛主席对我们共产党的许多干部谈：你们每天写日记不要写别的，就只写一句“团结百分之九十”就行了。我想，在毛主席领导下，争取大多数，为着共同事业奋斗，消灭反动统治，这一政策的运用，是我们最大的成就。这一点我们青年要学习。要使马克思列宁主义的普遍真理在中国胜利实现，一定要结合中国的实际，做许多艰苦的具体工作，不屈不挠地前进，长期地奋斗，努力争取大多数的人民，争取大多数的青年群众跟着我们走，而不是靠着我们这个小队伍。

青年联合会最大的作用就是组织全国广大青年，推动与教育他们，共同学习，共同提高，共同前进。我们联合青年，不包括反动青年，不能让他们钻进来。但是超我们必须把愿意为新民主主义事业奋斗的青年完全包括在内。这些愿意为新民主主义服务的青年，思想虽然还不是一致的，但是今天他们愿意学习马列主义、毛泽东思想。他们之中有些人虽然还有迷信观念，落后观念，或单纯的技术观念和片面的观点存在着，我们也要把他们包括进来。因为我们可以教育改造他们。因此，我们提出一个学习的口号和目标，即“学习毛泽东”。这个口号和目标是大家都能接受的。不仅是进步的青年能接受，其他青年也能接受。当然，团结教育青年，并不是只给大家讲共产党的好主张，不讲共产党犯过的错误。在这个青年会议上，我们不但不向同志们隐蔽共产党的错误，相反，有好多错误在今天都讲出来了。我今天讲的一些党内的事情，你们过去是不晓得的，甚至党内有的同志也还不晓得，可是你们今天就晓得了。今天你们所代表的，不是几百万青年，而是几千万上万万青年。那就要请你们考虑，共产党不能冒昧地把他的主张压在成千成万的青年头上。这样的思想是国民党的统治的思想，人家不能接受硬叫人家接受，把帽子在人家头上一戴，象观音菩萨的紧箍咒一下子箍在孙悟空头上。学习毛泽东，我们不是用压迫的方法。这只是我们提出来的口号，这口号很响亮，能使广大青年接受。因为毛主席在今天不单单是中国青年的领袖，而且是中国人民的领袖，是中国共产党的领袖，是我们的一面旗帜。

这里需要解释一个思想自由的问题。反动派常常说他们主张思想自由，蒋介石就是这样说的。大家知道这是鬼话，在蒋介石的统治下还有什么自由呢？人民普遍地受压迫受剥削，只有少数的地主官僚资本家反动分子有自由，他们可以自由地剥削、压迫、屠杀人民。资产阶级民主国家，只有资产阶级的思想自由，广大工人农民没有思想自由。在我们新民主主义的国家，人民大众是有充分的思想自由的。只要不是反动思想，其他思想都可以存在。不仅是进步的社会主义思想、共产主义思想可以存在，就是相信宗教的思想也可以存在。除了反动的思想不允许宣传外，其他言论、出版、集会、结社都是自由的。共产党认为他的历史唯物主义思想是最正确的，毛泽东思想是最正确的。这个当然要讲。但也不是不让这个思想以外的思想存在。我们以我们的思想教育大家，但是你可以听，也可以不听，可以接受，也可以不接受，可以自由选择。这样才是一个教育的态度，领导的态度，才是一个共同工作的态度，合作的态度。

我们提出的口号是“学习毛泽东”，但也不限于这个口号。在这个口号之下，我们青年还要分门别类地学习，比如新民主主义的建设，经济的政治的文化的知识，各种专门科学技术，都需要学习。学习，也正是毛主席的一个特点。他就是日夜不息地学习，他从来也没有感到满足过，他常常说这方面不会还要学习，那方面不会还要学习。我们要做他的学生，就要学习他这个精神。

我讲这样几点当然不是介绍毛主席的全部功绩和主要学说，我说的仅仅是毛泽东思想的很少的一部分。毛主席创建人民军队方面的成就，他在军事上的战略战术，在政治上的《新民主主义论》、《论联合政府》，在经济上的一些文章，在文化上的《在延安文艺座谈会上的讲话》，在哲学上的创造，他的马克思主义的思想体系等等，多得很。毛主席的成就不仅广，而且专，而且精，在这里不多说了。毛主席的学习态度，他自己的口号是“实事求是”。他是最老实的，是则是，非则非。他是最反对骄傲反对急躁的。在三十年的革命运动中，他就是在反对骄傲反对急躁的斗争中成熟起来的。他的作风也是谦虚而又谨慎的。正如斯大林的《论列宁主义基础》所说，既有着革命的胆略，又有着求实的精神。所以我们要学习他的实事求是的精神，在态度、作风上，也就应该老实，不要沾染浮泛与骄傲急躁的习气。中国共产党在人民革命运动中有过这样的经验。我在过去也是急躁的。当然这不是青年一代很容易学成功的。我们要兢兢业业，力求少犯错误。错误是不可避免的，但是不要重复错误。青年人没有不栽几个筋斗的，没有不碰几个钉子的。碰了钉子后，不要气馁。我们在革命斗争中不知流过多少血，遭受过多少挫折，有多少人倒下去了。在最困难的时候，不要丧气，正如毛主席所说的，从地下爬起来，擦干净身上的血迹，掩埋好同伴的尸体，继续前进。要有这样的志气，要有这样的勇气。我们今天即将夺取全国的胜利，光明在照耀着我们。但是我们不能因胜利而骄傲起来，觉得不可一世，而忘掉了过去的经验教训。毛主席说，夺取全国胜利才走完万里长征的第一步，还有很多很艰苦困难的工作等待我们去做。这里有两种教训值得注意：一种教训是看不起别人，脱离群众；一种教训就是蜕化了。这是我们青年的“敌人”。我们应该排除急躁、骄傲、气馁、灰心、丧气，学习毛泽东的学习作风和工作作风，老老实实，实事求是，脚踏实地，稳步而又勇敢地前进。只有这样，我们才能带动上万万的青年前进，才能真正实现我们全国人民的民主解放和民族独立，建设一个新民主主义的新中国，并且为世界的持久和平而奋斗。我们的口号是：“全国青年团结起来，在毛泽东的旗帜下前进！”

＊这是在中华全国青年第一次代表大会上的报告第三部分的节录，一九七八年十月八日曾在《人民日报》发表，收入本书时根据原记录重新进行了整理。

