# 在中华全国文艺学术工作者代表大会上的政治报告

中文马克思主义文库 -> 周恩来
在中华全国文艺学术工作者代表大会上的政治报告
（一九四九年七月六日）


　　各位代表：让我首先向你们庆贺全国文学艺术工作者代表大会〔453〕的成功，庆贺从中国第一次大革命失败以来逐渐被迫分离在两个地区的文艺工作者在今天的大会师。从五四运动以后，我们的新文艺大军在跟敌人作战上，曾经取得很多的胜利。我们打败过封建文艺，二十年来我们又打败过国民党反动派的法西斯文艺和为帝国主义服务的汉奸文艺。在新民主主义的文艺方向下，我们建立了广泛的文艺战线。在解放区，许多文艺工作者进入了部队，进入了农村，最近又进入了工厂，深入到工农兵的群众中去为他们服务，在这方面我们已看到初步的成绩。在以前的国民党统治区，革命的文艺工作者坚持着自己的岗位，在敌人的压迫之下决不屈服，保持着从“五四”以来的革命的文艺传统。抗日战争期间在国民党统治区成立的中华全国文艺协会〔454〕，也就是今天的大会发起团体之一，除了很少几个反动分子被淘汰以外，那个团体的文艺工作者几乎全部都团结在新民主主义的旗帜之下，并且他们的主要代表人物也几乎全部都来参加了这个大会。 
　　对于文艺界大团结的胜利，我们不能不归功于在各方面坚持岗位艰苦奋斗的朋友们，不能不归功于全国广大人民对于新文艺运动的支持，但是尤其不能不归功于人民解放军在军事战线上的伟大胜利。没有军事战线上的胜利，那么我们今天这样七百多人的大团结大会合，就是不可能的。所以在我的讲话的第一部分，我想向大家说说我们这三年人民解放战争胜利的情况和根源，以及文艺工作所应当由此得到的教训。

一　三年人民解放战争的胜利
　　从一九四六年的七月算起，人民解放战争已经进行了整整三年。这三年的战绩，在中国历史上是空前的。三年以前，在美帝国主义支持下，国民党反动派动员了四百三十万军队来进攻。那时候我们只有一百二十万的人民解放军，与敌人相差三百一十万之多。反动分子和他们的美国主人在当时满以为一定可以打垮人民解放军。多少好心肠的朋友也曾经为我们担心。我们感谢这些朋友，但是我们坚定地告诉他们，战争的胜利是一定属于我们的。在一九四六年十一月我率领中共代表团离开当时国民党首都南京的时候，许多的新闻记者问我：“你们还回来不回来？”我说：“我们总有一天会回来的。”朋友们！我们今天果然回南京了，不过进入南京的不是我们当时的代表团，而是胜利的人民解放军！
　　战争的第一个年头，敌人是处于进攻阶段，但是因为受到了我们的重大打击，敌人的全面进攻很快就变成了局部的进攻或重点的进攻。第二个年头，我们开始反攻，华北和华东的野战大军渡过黄河向南前进到长江北岸，同时东北的人民解放军也由北满向南满进攻。在战争的第三年，我们的进攻取得了决定性的胜利。经过一九四八年九月的济南战役〔434〕，一九四八年九月至十一月的辽沈战役〔434〕，一九四八年十一月到今年一月初的淮海战役〔434〕，一九四八年十二月到今年一月底的平津战役〔434〕，蒋介石的军事力量就从此基本上被消灭了。因此，在今年四月人民解放军渡江南进的时候，蒋介石已经不可能组织一条有实际意义的防线。从一九四六年七月到现在的三年中，国民党的军事力量从开始的四百三十万人减到现在的一百四十九万人，这一百四十九万人当中，还有很大一部分是属于机关、学校和后勤部门，战斗的部队大约只占半数。我们人民解放军却从一百二十万人增加到今天的四百万人以上。巧得很，他们少了二百八十万，我们多了二百八十万。在我们四百万以上的大军中，二百二十多万的野战部队正在前进，扫荡着已经只剩八十多万并丧失了战斗力的敌人的残余部队。我们已经解放了两万万七千九百万人口，占全国人口百分之五十九；解放了一千零六十一座城市，占全国城市百分之五十三；解放了两万一千六百多公里铁路，占全国铁路百分之八十。敌人除了在海军空军方面暂时还占有优势以外，一切方面的优势已经都属于人民了。这个情况，使我们相信人民解放战争的第四年，将是我们取得全国胜利的一年。
　　在这三年当中，我们的伤亡一共是一百四十三万人，而消灭的敌人是五百六十九万人，就是说我们伤亡一个人，消灭他们四个人。在敌人所损失的五百六十九万人当中，被我们俘虏的人数达到百分之七十，即四百一十五万，而俘虏中又有二百八十万变成了解放军。三年中间，消灭了敌人正规编制的军队四百九十五个师，连非正规部队算在一起，消灭了敌人二千一百五十个团。俘虏的将级军官，加上上校级的师长，达到九百二十七人。三年中间缴获的武器，有各种炮四万四千多门，轻重机枪二十五万多挺，长短枪二百多万支，飞机一百三十四架，军舰一百二十三只，坦克车五百八十二辆，装甲车三百六十一辆，马十三万匹，步机枪子弹三万万七千多万发，炮弹三百一十一万发。我们就依靠这批由敌人手中解放过来的战士，依靠这批由敌人手中缴获过来的武器弹药，回过手来战胜了敌人。
　　人民解放军为什么能够取得这样伟大的胜利呢？当然，这首先是因为人民解放军所进行的战争乃是正义的爱国的人民革命战争，因为他代表了全国人民的利益，为全国人民的利益而战。但在这里，我们应当指出人民解放军本身的素质，这就是：人民解放军经历了二十二年的锻炼，已经具有高度的政治觉悟、严格的纪律，坚强的战斗力、成熟的战略战术。尤其最近三年来，人民解放军又经过了一次改造。我为什么要用改造这两个字呢？因为他的绝大部分战士，不久以前还是俘虏兵，不经过改造就不能遵守解放军的纪律。最有效的改造武器，就是唤起他们的阶级觉悟，实行诉苦运动和查阶级、查工作、查斗志的三查运动，评干部、评党员、评战功的三评运动，使他们感觉到大家的出身都是劳动人民，都曾经受过反动派的压迫剥削，人民解放军是劳动人民自己的军队，大家应该团结一致，为自己的利益，向曾经压迫他们、剥削他们的仇人作战。人民解放军是一个有严格纪律的军队，但是这个纪律是建筑在自觉的基础之上的。人民解放军在部队内部实施了军事民主、政治民主和经济民主的制度，在部队外部进行了瓦解敌军工作、拥政爱民工作和地方群众工作，这就使得人民解放军指挥员、战斗员得以密切地联系群众，使得他们的觉悟程度不断地提高，使得人民解放军获得无上的战斗力量。
　　文艺界的同志们和朋友们！你们要写作，就一定不要忘记表现这个伟大的时代的伟大的人民军队。我提议我们人民革命军事委员会的政治部、共产党中央的宣传部以及所有解放军代表同志，你们应当利用战争还在进行的时候，热烈招待没有看到过人民解放军的文艺家到部队里去参观，给他们调查和写作的便利。
　　人民解放军在作战中不是孤立的。在三年的人民战争的高潮中，两万万农民是最伟大的支持力量。一万万以上的农民进行了土地改革的斗争，分得了土地，另外一万万以上的农民正在准备着解决土地问题。在不久的将来，又会有两万万的农民将要进入到土地改革的浪潮中来。这在农业的中国是一件翻天覆地的事情。在土地改革的基础上，伟大的中国农民贡献给战争的是些什么呢？他们把他们的子弟、丈夫送去参加人民解放战争，他们把生产节约的粮食供给我们的前方后方，他们当民兵，当民工，不但在后方维持秩序，并且大批地随着部队出发到前线去做种种协助战争的工作。只要那个地方的战事过去之后，那个地方就掀起了生产热潮。同志们！朋友们！我们依靠了伟大、勤劳、勇敢的中国农民，这才有今天的胜利。我们应当感谢伟大的中国农民，特别要感谢老解放区的农民。尽管农民有他们的落后的方面，要待我们耐心地改造，然而他们的勇敢、勤劳、艰苦、朴素的本质，是值得我们歌颂的，值得我们记录和宣扬的。所以我们希望已经习惯于乡村生活的文艺工作者，继续深入乡村工作，为他们服务；同时也欢迎没有到过农村的、没有习惯于农村生活的文艺工作者，去学习农民，与农民做朋友，以便于写下他们的艰苦卓绝、英勇奋斗的业绩。
　　人民解放战争的胜利，还不能不归功于工人阶级的努力。尽管我们二十二年斗争的很大部分时间是在乡村，在农民和部队里面，但是我们的斗争是与工人阶级相联系着进行的。从政治上说，是在工人阶级通过他的先锋队即中国共产党的领导之下进行的。事实上就是在乡村中间，我们也不能离开工人。大规模的战争首先不能离开兵工生产。武器主要是敌人输送给我们的，但弹药还需要我们自己的补充。我们依靠工人。我们把大的锅炉从矿山从机器厂用几千人抬到太行山上，抬到五台山上，抬到沂蒙山区，在山上建设了工厂，几千万的手榴弹，几百万的迫击炮弹，几十万的山野炮弹，便这样生产出来了。到了去年下半年，我们的手榴弹、迫击炮弹、山野炮弹和炸药的生产数字，已经超过了国民党反动派。除了兵工，我们在乡村中还发展了各种小规模的轻工业，供给军需民用。今天我们进入大城市以后，情况更不同了。我们必须依靠工人阶级，才能恢复和发展工业。工人阶级正在一天比一天成为中国建设事业的主要力量，也正在一天比一天成为我们的文艺创作的重要主题。
　　文艺工作者是精神劳动者，广义地说来也是工人阶级的一员。精神劳动者应该向体力劳动者学习。一般精神劳动的特点之一是个人劳动（当然歌咏队、剧社、电影厂等的许多活动是集体的），这就容易产生一种非集体主义的倾向。在这一个方面，文艺工作者应当特别努力向工人阶级的集体主义的精神学习。
　　人民解放战争的胜利，依靠人民解放军，依靠农民、工人、革命知识分子和一切爱国民主人士所形成的人民民主统一战线。但是从根本上说，造成这个胜利的最有决定性的因素，却是中国人民革命的组织者中国共产党的正确领导，却是中国人民领袖毛泽东同志的正确领导。中国共产党从产生到长大，曾经经历过错误和失败，但是毛泽东同志却始终是站在正确的方面。大家知道，中国革命的敌人不是一个简单的敌人，几千年的封建统治，一百年来的外国资本主义和帝国主义的侵略，集中表现为国民党蒋介石的反动统治。我们应当感谢毛泽东同志，他把马克思列宁主义的普遍真理正确地应用到中国革命的实践中来，因而造成了伟大的力量，战胜了中国革命的强大敌人。我们号召大家学习毛泽东同志，把革命理论和革命实践结合起来。我们同时号召一切进步的文艺工作者努力认识中国共产党，因为中国共产党已经与中国人民的生活和斗争形成了不可分离的联系，不认识中国共产党，也就不能够正确地认识和表现今天的中国人民的生活和斗争的主要部分。刘少奇同志常常说，我们每一级的党委应该交几个文艺界的朋友，以便于互相帮助、互相学习。我们希望大家在这个目标上共同努力。
　　最后，我们必须指出世界人民力量对于中国人民解放斗争的影响和援助。不但中国人民抗日战争的胜利，得到了以苏联为首的世界反法西斯阵线的伟大的援助，而且在中国人民解放战争中间，以苏联为首的世界和平民主阵营也给了中国人民以伟大援助。帝国主义阵营把主要的力量放在西方，把次要的力量放在东方，这对于中国革命就是一个首先重要的有利条件。苏联的存在，人民民主国家的存在，亚洲和其他地方被压迫民族反帝国主义斗争的存在，资本主义国家中无产阶级的革命运动和爱好和平的人民的反对新战争运动的存在，这一切力量的总和大于帝国主义和各国反动派力量的总和，因而阻止了新世界战争的爆发，阻止了美帝国主义进一步武装干涉中国。
　　我们的文艺工作者的任务之一，就是向全国人民传播这个真理。我们要分清敌我，暴露帝国主义的罪恶，打击战争贩子的叫嚣，揭穿他们的恐吓、挑拨和欺骗。这个庄严的工作，是中国民族利益所要求的，也是世界人民利益所要求的，这正是爱国主义和国际主义的结合。

二　文艺方面的几个问题
　　我在讲话的第二部分，想讲几个关于文艺方面的问题。
　　第一，团结问题。我们现在开的是文艺界的团结大会。应该说，出席这个大会的七百五十三位代表是有很大的代表性的。现在在人民解放军四大野战军加上直属兵团，加上五大军区〔455〕，参加文艺工作的，包括宣传队、歌咏队在内，有两万五千人到三万人的数目。解放区的地方文艺工作者的数目，估计也有两万以上。两项合计有六万人左右。这就是解放区的四百多代表所代表的文艺工作者。前国民党统治区的新文艺工作者的数目比较难算，大概总有一万人以上。这就是说，你们七百五十三位代表，代表着七万上下的新文艺部队，平均每一个人代表着一百个人。此外还有大量的旧艺人。希望代表们回去以后，能领导各方面的文艺工作者发扬这次大会的团结精神，并且希望大家经常地密切地联系这支广大的文艺军队，使你们真正不愧为他们的代表。
　　第二，为人民服务的问题。这个口号大家都赞成，现在的问题是怎样实现。我们应该首先研究一下我们熟悉什么，不熟悉什么。部队文艺工作者熟悉部队，部分地熟悉农村，但对工人和城市的情形就不熟悉。解放区地方文艺工作者熟悉农民，不完全熟悉部队，对城市情况也不熟悉。我们从新区来的朋友，过去限于环境，不可能深入广大的群众，但今天的情况变了，有了深入群众的机会了。总之，应该首先去熟悉工农兵，因为工农兵是人民的主体，而工农兵又是今天在场的绝大多数所不熟悉或不完全熟悉的，至于小资产阶级的生活、思想、感情，则是你们的绝大多数所已经熟悉的。
　　我们首先需要熟悉工人。现在各方面的文艺工作者一般地都不熟悉工人，所以反映工人的作品还很少。我们希望能有一批文艺工作者深入工厂。自己不能到工厂去的，也应该宣传这个号召，把它变成一个运动，推动成千成万的文艺工作者向这方向走去。
　　这几年有一部分同志已经开始熟悉了农民和兵士，兵士基本上是拿枪的农民。应该继续熟悉他们，并帮助不熟悉的人去熟悉。熟悉工农兵的生活，把自己的思想感情和他们打成一片，那是一个长期的过程，因此希望已经下过农村的文艺工作者不要自满。农民是中国人口中的最大多数。中国的历史长期以来基本上是一部农民战争史，而近二十几年来乃是工人阶级领导下的农民战争史，所有的文艺工作者都有熟悉农民、了解战争的任务。
　　我们主张文艺为工农兵服务，当然不是说文艺作品只能写工农兵。比方写工人在解放以前的情况，就要写到官僚资本家的压迫；写现在的生产，就要写到劳资两利；写封建农村的农民，就要写到地主的残暴；写人民解放战争，就要写到国民党军队里的那些无谓牺牲的士兵和那些反动军官。所以我不是说我们不要熟悉社会上别的阶级，不要写别的阶级的人物，但是主要的力量应该放在那里必须弄清楚，不然就不可能反映出这个伟大的时代，不可能反映出创造这个伟大时代的伟大劳动人民。
　　第三，普及与提高的问题。现在还是不是普及第一呢？还是普及第一。解放区做了一些普及工作，但是离开普及的需要还很远。至于说现在产生的普及性的文艺作品还很粗糙，需要改进，需要提高，这是事实，但是这并不是值得担心的事情。如因此而轻视普及工作，更是完全错误的。任何一个新生的东西那有不粗糙不幼稚的？我们对于新生的东西不要责备过甚，对它要爱护帮助，象对自己的孩子一样。对孩子需要批评教育，但是不能打骂，否则就把孩子打坏了，骂傻了。新生的事物常常大喊大叫，它要改造这个旧世界，这是一种革命气概。脱离人民的旧文艺已经是腐朽了，尽管外表如何好看，内部已经烂了，希望是属于新的方面。我们的普及性的文艺作品虽然还不高，但它们确是为广大人民所喜闻乐见的。所以我们必须重视新文艺在普及方面的生长和成就，即使是一些小的生长，小的成就。
　　第四，改造旧文艺的问题。我感到我们对于旧文艺的改造的重视是不够的。凡是在群众中有基础的旧文艺，都应当重视它的改造。这种改造，首先和主要的是内容的改造，但是伴随这种内容的改造而来的，对于旧形式也必须有适当的与逐步的改造，然后才能达到内容和形式的和谐与统一。使我们高兴的，就是旧文艺界许多有成就的朋友，愿意参加这个改造的工作，而且希望同新文艺界的干部团结在一起来进行这个工作。我们应当用很大的热情来欢迎他们。旧社会爱好旧内容旧形式的艺术，但是又瞧不起旧艺人，总是侮辱他们。现在是新社会新时代了，我们应当尊重一切受群众爱好的旧艺人。尊重他们方能改造他们。我们过去做了一些改造工作，但是成绩还很小。今后一定和全国一切愿意改造的旧艺人团结在一起，组织他们，领导他们，普遍地进行大规模的旧文艺改革。如果不团结广大的旧艺人，排斥他们，企图一下子代替他们，是不可能的。应该使包含几十万艺人并影响几千万观众、听众、读者的旧文艺部队的巨大力量，动员起来积极地参加这个改革运动。实在说，现在这个工作刚才开始。有些人觉得旧文艺没有什么前途，以为它总是要消灭的，因此就发生不重视它，让它自生自灭的心理。但是，今天的事实是广大的人民还在看它，听它，喜欢它，难道对人民负责的文艺工作者应当对这样的事实视为等闲吗？旧文艺会不会消灭呢？我说这个问题应该这样回答：它是会消灭的，它又是有前途的。旧文艺里的一切坏的部分、一切不适合于人民利益人民要求的部分一定就会消灭，比如宣传封建思想和其他反革命思想的东西，就应该加以消灭；另外有一些合理的、可以发展的东西就会慢慢地提高、进步，逐渐变为新文艺的组成部分，这一部分就是有前途的，而不是被消灭的了。我们要这样看，问题才能得到正确的解决。我们如果认为旧文艺什么都好，什么都保存，那样就会走到复古的路上去了；另外我们如果认为什么都不好，什么都否定，或置之不管，那样就是对于民族传统和群众感情采取错误的态度，就是违背了我们的普及第一的主张，同时也不合于我们的历史观点。改造旧文艺也跟创造新的普及文艺一样，开始也会是粗糙的。但我们不能因为粗糙就轻视它，因为你一轻视它，它就很难生长，很难壮大。这种改造工作无疑地将是长期的巨大的工作，希望一下子改造得尽善尽美，是不可能的。但我们也不能因为这是长期的巨大的工作，而不去紧张地努力。
　　第五，文艺界要有全局观念的问题。我们文艺界的朋友来自各方，譬如解放区的，就有一部分是从部队来的，他们是长期地在部队工作，另一部分是从解放区各地方组织来的，他们过去限于环境，工作也带局部性，现在聚会一堂，来商讨今后全国的文艺工作，那就不能不要求我们大家有全局观念。我们不只是看到我们那一个工作部门，或者只看见我们个人的工作环境，我们要看到我们今天整个的解放事业，看到我们今天全国的文艺工作，我们的工作才能安排妥当。今天全国接近于完全解放，我们的后方最重要的任务是发展生产。我们文艺工作者要了解，建设新民主主义新中国的初期是一个艰难缔造的过程，尽可能要求我们的每一个部门、每一个人、每一项工作都能很快发展，同时又要求有计划地适合全局的需要与可能，各部门中的分工安排就需要我们根据轻重缓急来定了。
　　我们这个文艺界的团结大会，开得确实不坏。但是如果以为它一切都美满，或者以为今后的工作一切都会美满，那么一接触实际，便会有很多地方、很多工作感到不满和失望。假若我们各部门的文艺工作者都有全局的想法，能够和今天的建设联系起来，和我们的政治运动密切结合起来，我们的工作发展就会更快。比如我们的部队还要继续前进到南方、西北、西南，广大的部队文艺工作者就要向新区前进，去推广文艺的普及工作，和部队配合前进，解放尚未解放的两万万的人口，这是我们部队文艺工作的最重要的方向。因此尽管部队文艺工作者要求提高，也有可能一部分回来受训练，但是，这只是极少数，甚至开始还不可能，在这样的时候，个人要求就要服从全体的利益。解放区地方的文艺工作者也是一样，也可能从老解放区调到新区去工作，去组织那个地区的文艺部队，推广那个地区的文艺工作。这也是文艺与政治的一种结合。
　　今天要把事情的困难估计多一些，在什么困难条件下都能工作，那样，将来好一点当然更好了。我这样说，就是为了大家精神上有准备。
　　最后一个问题，是组织问题。因为这次文代大会代表大家都感到要成立组织，也的确需要解决这个问题。不仅我们要成立一个中华全国文学艺术界的联合会，而且我们要象总工会的样子，下面要有各种“产业工会”，要分部门成立文学、戏剧、电影、音乐、美术、舞蹈等协会。因为只有这样，我们才便于进行工作，便于训练人材，便于推广，便于改造。这一点是大家所赞同的，现在就需要开始，因为我们不可能常开这样的大会。希望在会中或会后，就把各部门的组织成立。这是群众团体方面。
　　同时，新政治协商会议〔423〕将要产生全国性的民主联合政府，而在这个政府机构之中，也要有文艺部门的组织。这个文艺部门的组织，那就要依靠我们上面说的那些群众团体来支持，因为这个部门是为我们广大人民及群众团体服务的，也为广大文艺工作者服务。我们的国家是人民的国家，政府是人民的政府，是民主集中制的、由下而上同时又是由上而下的人民政权，是无产阶级领导的人民民主专政。所以我们文艺界也要关心这一方面的工作，也要推出代表来参加新的政治协商会议。我们新民主主义的政权机构里面的文艺部门，也需要我们全体文艺工作者来积极参加工作。
　　我们的文艺工作者，过去在部队里，有的一个野战军多到八千多人，有的很少。当然这是由于环境的限制，各自发展的结果。地方上也是这样，有的一个县有一个文工团，有的没有。这种不平衡的发展，今后一个时期还会继续，但是城市和乡村，部队和地方，慢慢地调整是需要的。尤其是新区，我们要派出大批的人员去。过去我们在国民党统治区的朋友，各自为战，互不联系，在反动派的统治下有空隙就要钻进去，控制它一块，被压迫就藏起来。现在不同了，现在是人民的国家，要自己来安排。所以文艺工作在政府方面也好，在群众团体方面也好，我们都要来有计划地安排。这就靠你们将要推选出来的领导机构来安排这些事情。
　　这是在文艺方面我想说的几件事情，提供诸位研究参考。
　　同志们！朋友们！这次文艺界代表大会的团结是这样一种情形的团结：是从老解放区来的与从新解放区来的两部分文艺军队的会师，也是新文艺部队的代表与赞成改造的旧文艺的代表的会师，又是在农村中的，在城市中的，在部队中的这三部分文艺军队的会师。这些情形都说明了这次团结的局面的宽广，也说明了这次团结是在新民主主义旗帜之下，在毛泽东同志新文艺方向之下的胜利的大团结，大会师。
　　在全国接近于最后胜利这样的局面下，我们七百多位代表能够有这样的大团结、大会师，我们应该感谢毛泽东同志，他把中国革命领导到今天这样伟大的胜利；我们应该感谢毛泽东同志，他给予了我们文艺的新方向，使文艺也能获得伟大的胜利。



