# 恢复生产，建设中国

中文马克思主义文库 -> 周恩来
恢复生产，建设中国
（一九四九年七月二十三日）

同志们：我们全国工会工作会议开幕了。刚才朱总司令讲了工会工作的许多问题，大家在会议中还要讨论许多具体问题，我在这方面就不多说了。我把目前的政治形势和工作重心讲一讲。

现在人民解放战争已经取得基本胜利，但是还没有完全胜利；我们已经开始建设，但是还没有结束战争。革命还在向着彻底胜利前进。我们现在正是处在这样一个复杂的过渡的发展的形势当中！我们要把战争进行到底，把革命进行到底。我们要打到台湾去，打到海南岛去，打到昆明去，打到新疆去。我们要赶走帝国主义侵略势力，同帝国主义封锁作斗争，把殖民地半殖民地的中国经济变为自力更生的独立的中国经济。我们的一切工作，首先要为着把战争、把革命进行到底。工会工作也必须把这个问题放在主要地位。

在目前这样的形势下，我们工会动员全体工人阶级的口号是：恢复生产，建设新中国。现在我们接收的生产机构这么大，这么多，要把生产恢复起来，要把经济调整好，是个艰巨的工作。原封不动地接收是比较容易的，天津、北平、南京、上海、武汉，一个城市比一个城市接收得好。进一步来管理就难得多。而且还要改革旧制度。中国的半殖民地经济结构，是服从于帝国主义的意志的，现在要把它改变过来。我们要有信心地稳步地重新组织中国经济结构。当前的问题，首先是城市与乡村的经济不协调，加上帝国主义对我们进行封锁。过去，城市工厂主要是依靠帝国主义的原料和运输来生产的，象上海的纱厂，主要是依靠美帝国主义的棉花纺成纱织成布，用外国的运输工具运到外国市场去推销，为帝国主义的利益服务。今天不同了，条件完全变了，也应该变了，应该依靠自己的原料和运输来生产了。但经济结构还是原样，是畸形的，不合理的。这就给我们带来了困难。第二是我们接收的官僚资本企业，冗员很多，原来敌伪的一套人员再加上国民党的人员组成官僚主义的管理机构，人力浪费，开支庞大。这也给我们添了很大的负担。第三是国民党统治区农村的极大破产，没办法给城市工业提供原料。拿棉花生产来说，凡是国民党统治区的棉田都减产，因为有美棉的倾销。其他原料也是这样。所以城市解放以后，我们会看到原料缺乏，生产降低，销路减少，运输困难，不少人失业。这种情况在一定时期是不能避免的。但是我们要认识，这种困难和革命失败时期的困难不同，和帝国主义国家的经济困难也不同。革命失败时期的困难比现在不知要大多少倍，我们还能转败为胜。帝国主义的经济困难是帝国主义的经济制度造成的，无法克服。我们的困难是革命胜利中所遇到的，是以前帝国主义和国民党官僚资本主义给我们遗留下来的，而不是新民主主义制度带来的。正是在新民主主义制度下，我们能够克服这些困难。

我们要恢复生产，首先就得恢复农业生产。农村解放和进行土地改革以后，只要经过一年时间，农业生产就能增加。这种经验在华北、东北、西北都有过。东北去年全部解放，今年就计划增产粮食一百五十万吨，这是一个很大的数目。华北今年春天全部解放，明年就可以增产。接着，华东、华中、华南都会这样发展。而且，现在我们的战争进行得很顺利，农村破坏很少，第一步先做到不减产，第二步就可以增产。农业生产提高了，原料增加了，工业生产就更有基础。第二是恢复交通运输。首要的是恢复铁路。中国两万多公里铁路，今年要恢复百分之八十，明年不仅要恢复余下的百分之二十，而且还要有新的发展。我们要恢复生产，必须靠交通运输畅通。比如淮南的铁道恢复了，就可以使淮南的煤产量增加，保证上海工业的恢复。将来平汉、粤汉都要这样地恢复。此外就是钢铁工业、机械工业，先要为铁路制造钢轨、火车头、车厢、车皮；还要增产农业工具，如水车等，使农村得到帮助。这些，都是我们恢复生产争需要做的，当然我们要做的不仅仅是这些方面。

所以从全局来看，我们的事业是发展的。在局部，譬如上海，或者在某一方面，生产确实是减少了一些。大城市的那种殖民地商业，外国货充斥的商业，是会少一些的，有些买卖是会关闭一些的。特别是那些人民不需要的消费品的制造厂和商店是要关闭的。由于这些生产的减少，就会有一部分工人失业。但是，这只是生产发展中的减产，商业发展中的萧条，交通恢复中的停滞，工作增加中的失业。这是全局与局部、主流与支流的关系。对此，我们要有一个正确的估计。

我们的革命要彻底胜利，要把帝国主义加在我们身上的锁链统统去掉，必然会遇到他们留给我们的困难，我们要准备迎接和克服这些困难。我们要继续保持和发扬长期在农村中建立起来的艰苦奋斗的革命传统。现在到了一个新环境，要精兵简政，节衣缩食。接收一些机关，不要把官僚机构的坏东西也接收下来，而是要加以改造。我们现在虽然生活在城市里，但旧衣裳还是要穿，不要向剥削阶级造成的奢侈腐化的生活看齐，要向我们历来的艰苦朴素的生活看齐。这样才能节省国家的经费，使人民尤其是工人阶级生产的东西，首先用到革命当中、战争当中去。这样才能使我们有力量增加生产，克服帝国主义和国民党反动派给我们遗留下来的困难。这是我们在恢复生产的工作中对于我们工人阶级的一个号召，也是对于我们人民的一个号召。

我们的党在农村中依靠农民，领导他们进行了八年的抗日战争，三年的解放战争，他们对国家的贡献是特别大的。在人力上，农民单是送自己的子弟、丈夫参军，先后加起来就有七百多万人。还要有多少民工支前！还要有多少民兵打游击战！在公粮的负担上，每一个农民每年平均收入大概是四百斤小米，要拿出八十斤给公家，这就是全部收入的百分之二十。现在到了城市，我们的开支更大了。譬如上海、天津、北平三个大城市，有一千万人口，生产还没有恢复，我们要支出多少人民券？这些支出加在谁身上？还是加在我们工人阶级最可靠的同盟军农民身上了。因此，我们城市工作的同志要想到农民。我们工人阶级今天也要负担同样的辛苦，起到我们应该起的作用。

我们工人阶级要参加新中国的各种建设工作。全国总工会和各地工会都要派代表参加即将召开的新政治协商会议〔423〕，这样就参加了新中国的政权建设。不但工会的代表，而且我们革命的职员，从事革命工作几十年了，也是工人阶级的一部分，他们的代表就是工人阶级的代表，也要来领导全国政权的建设工作。现在各个地方也正在建设地方的人民政权，工人阶级要在其中起领导作用。工人阶级还要参加今后的国防建设。过去，我们是从游击战发展到正规战，把敌人的武器缴获过来，装备自己，消灭敌人。今后对付帝国主义的侵略，武器装备必须依靠我们自己生产，这就需要我们工人阶级作出更大的努力。工人阶级还要参加文化建设。总之，我们工人阶级要参加各种建设工作，而最基本的任务就是恢复和发展生产。只要我们有步骤有计划有组织地把生产恢复起来，发展起来，我们就有把握建设新中国。

最后，讲一讲团结问题。为了把革命进行到底，恢复生产，建设新中国，我们要团结起来。有四个方面的团结：

首先是我们工人阶级本身要团结起来。据说现在有组织的工人已经有一百万以上，如果把全国一切工人、职员、手工业工人统统组织起来，把农村的农业工人也组织起来，会达到一千万以上。工会是工人阶级的群众组织，是教育工人的地方，是为工人阶级谋利益的机构，也是代表工人阶级来参加领导和参加各种建设的组织。工人阶级团结不仅要看到工人中先进的部分，还要看到落后的和中间的部分。对于落后的和中间的部分，我们要帮助他们，教育他们，把他们组织起来，团结在一起，领导他们向前进，而不能搞关门主义，挑剔他们，冷淡他们，排斥他们。我们要有明确的团结全国工人阶级的认识，这样工人阶级的力量才是伟大的，才能担负起刚才所说的任务。

第二是公营企业中工人与职员要团结起来。工人和职员都是工人阶级，他们有的是处在管理的地位，有的是直接生产的体力劳动者，但只是分工的不同，没有阶级的对立。以前是官僚资本主义的工厂，工人对管理者有对立、反抗、斗争的情绪那是必然的。现在情况完全不同了，我们要把过去旧的对立的观念和态度改变为新的团结的观念和态度。实现这种团结的最好的机构就是工厂管理委员会。我们的工厂一切管理人员，不要把旧的官僚主义那一套拿过来，要实行民主，工人代表和管理人员、工程师在一起，民主地具体地来讨论工厂中的一切问题，如关于生产的方针、计划等等，同时要给厂长以最后决定权。有民主，有集中，全体团结起来，才能把生产搞好。

第三是在私人企业中我们要团结民族资本家。中国民族资产阶级受帝国主义的压迫，愿意脱离帝国主义的经济束缚来建设中国的企业，所以他们还有进步性和建设性；同时他们又是软弱的、动摇的，并且有投机破坏性，因为过去他们只有投机才能生存。今天应该把这个投机破坏性去掉，这就需要斗争；同时要承认他们的进步性，鼓励他们的建设性，这样才能够团结他们。要实现劳资两利，中心环节是要订立各行各业的集体合同，解决各行各业的劳资问题，否则两方面的斗争就不能限制，弄不好罢工也可能发生，生产就要受到破坏。订立集体合同，双方就可以安心生产了。

第四是中国工人阶级和国际工人阶级的团结。有了这个团结，才能制止帝国主义侵略者的战争冒险。中国革命的胜利得到了世界工人阶级的欢迎和拥护，更增加了整个世界和平的力量。

团结就是力量，团结起来才能够实现我们的一切任务！

＊这是在全国工会工作会议上的讲话摘要。

