# 《周恩来选集》上卷　注释

中文马克思主义文库 -> 周恩来
《周恩来选集》上卷　注释


　　〔1〕当时党中央的一些文件，把军阀、官僚、洋行买办、地主土豪统称为半封建势力。这里沿用了这一提法。——第1页

　　〔2〕国民党是孙中山创立的政党。一九○五年，孙中山领导的兴中会与华兴会、光复会联合组成中国同盟会，由孙中山任总理。同盟会领导了辛亥革命。一九一二年同盟会联合几个小党派改组为国民党，和北洋军阀袁世凯实行妥协，基本上成了官僚政客集团。一九一四年，为了反对袁世凯的统治，孙中山领导一部分国民党员组织中华革命党，一九一九年十月，又改为中国国民党（简称国民党）。一九二四年一月在中国共产党的帮助下，孙中山改组了中国国民党。改组后的中国国民党接受中国共产党提出的反帝反封建的政治主张，重新解释三民主义，确定联俄、联共、扶助农工三大政策，从而实现了第一次国共合作，并依靠这一合作进行了北伐战争。这个时期的国民党，具有工人、农民、小资产阶级、民族资产阶级的民主革命联盟的性质。一九二七年四月蒋介石发动反革命政变后，国民党基本上变成为代表大地主、大资产阶级的反动集团。——第1、92、112、159页

　　〔3〕“五卅”运动指一九二五年上海“五卅惨案”激起的全国人民的反帝爱国运动。一九二五年五月三十日，上海群众近万人到“公共租界”进行反对帝国主义的游行示威，遭到英帝国主义的血腥屠杀。这次惨案激起了全国人民的公愤，广大的工人、学生、商人和农民在各地举行游行示威和罢工、罢市、罢课，形成了全国规模的反帝爱国运动。——第2、46、57、88、117页

　　〔4〕一九二五年八月二十日，国民党右派在帝国主义指使下，在广州暗杀了坚持国共合作的国民党左派领袖廖仲恺。为了调查这一重大暗杀事件的真象，由有关方面人士组成了“廖案检查委员会”。周恩来是这一委员会的委员。——第2、117、165页

　　〔5〕见《共产党宣言》，《马克思恩格斯选集》第1卷第285页。新的泽文是：“共产党人不屑于隐瞒自己的观点和意图。”——第4页

　　〔6〕见《国民周刊》第3期（一九二六年十月二十三日出版）所载范谔写的《从海康案说到农运问题》一文。这篇文章揭露和谴责了广东海康县军政当局勾结地方土豪劣绅枪杀农民运动工作人员程庚的罪行。——第5页

　　〔7〕郭沫若（一八九二——一九七八），北伐战争时期任国民革命军总政治部副主任。一九二七年三月下旬，奉武汉国民政府之命从九江去上海组织总政治部分部，四月十四日到达上海。他目睹了蒋介石一手制造的九江、安庆的反革命事件。三月三十一日在南昌撰写了《请看今日之蒋介石》，声讨蒋介石背叛革命的罪行。——第6页

　　〔8〕一九二七年三月十七日，蒋介石嗾使暴徒在九江捣毁并派兵强占左派领导的国民党市党部和市总工会；同年三月二十三日，又在安庆捣毁左派领导的安徽省、安庆市国民党党部和全省总工会、省农民协会等筹备处，打伤多人。——第6页

　　〔9〕一九二七年三月二十日，蒋介石反动派在宁波捣毁了市总工会和店员工会；四月九日捣毁了左派领导的国民党市党部和《民国日报》社，逮捕了市党部常委杨眉山（共产党员）、市总工会委员长王鲲（共产党员）和《民国日报》社长庄禹梅。三月三十日蒋介石反动派在杭州袭击了市总工会，三十一日又开枪杀伤参加抗议游行的工人八十多人。四月九日蒋介石反动派在南京捣毁了左派领导的江苏省和南京市国民党党部；四月十日逮捕、殴打游行的革命群众，杀害省党部常委侯绍裘（共产党员）。四月十二日蒋介石反动派在上海血腥屠杀共产党人和革命群众。从此，蒋介石和他的追随者完全背叛革命，公开投降了帝国主义和封建势力。——第6页

　　〔10〕一九二七年四月十五日，国民党反动派在广州发动反革命政变，解除黄埔军校和省港罢工委员会纠察队的武装，包围中华全国总工会广州办事处、省港罢工委员会，逮捕、屠杀共产党员和工人积极分子两千多人。——第6页

　　〔11〕薛岳（一八九六——），当时任国民革命军第一军第一师师长。后来追随蒋介石积极反共。——第6页

　　〔12〕严重（一八九二——一九四四），曾任黄埔军校教官、总教官，北伐战争时任国民革命军第二十一师师长。“四一二”反革命政变后，拒绝蒋介石任命的职务。抗日战争期间被国民党反动派谋害。——第6、71页

　　〔13〕陈调元（一八八六——一九四三），当时任国民革命军第一集团军第三军团（北路）总指挥兼三十七军军长。——第6页

　　〔14〕指当时由国民党左派和共产党领导的武汉国民政府。——第7页

　　〔15〕“八七”会议即一九二七年八月七日在汉口召开的中国共产党中央紧急会议。出席这次会议的有党的中央委员、监察委员等二十一人。瞿秋白在会上作了《将来工作方针》的报告。会议通过了《告全党党员书》和农运、工运及组织问题等决议案，改选了中央领导机构。这次会议在中国革命的危急关头坚决地纠正和结束了陈独秀的投降主义，确定了土地革命和武装反抗国民党反动派屠杀政策的总方针，号召党和人民群众坚持革命斗争，这些都是正确的，是它的主要方面。但是，在反对右倾投降主义的时候，不认识当时应当根据各地不同情况，组织恰当的反攻或必要的策略上的退却，在组织上开始了宗派主义的过火的党内斗争，因而为后来的“左”倾错误开辟了道路。——第8、19、45、171页

　　〔16〕一九二八年六月十八日至七月十日在莫斯科召开了中国共产党第六次全国代表大会。会上，瞿秋白作了《中国革命与共产党》的报告，周恩来作了组织问题和军事问题的报告，刘伯承作了军事问题的补充报告。会议通过了政治、军事、组织等问题的决议案。这次大会肯定了中国社会是半殖民地半封建社会，中国当时的革命依然是资产阶级民主革命，指出了当时的政治形势是在两个革命高潮之间和革命发展的不平衡，党在当时的总任务不是进攻，不是组织起义，而是争取群众。会议在批判右倾机会主义的同时，特别指出了当时党内最主要的危险倾向是脱离群众的盲动主义、军事冒险主义和命令主义。这次大会的主要方面是正确的，但也有缺点和错误。它对于中间阶级的两面性和反动势力的内部矛盾缺乏正确的估计和适当的政策；对于大革命失败后党所需要的策略上的有秩序的退却，对于农村根据地的重要性和民主革命的长期性，也缺乏必要的认识。——第12、14、45、56、157页

　　〔17〕卢冬生（一九○八——一九四五），一九二七年参加中国共产党。一九二八年担任党中央联系湘鄂西苏区的交通员。一九二九年参加湘鄂西苏区红军，历任连长、营长、团长、师长、师政委等职。参加了长征。抗日战争初期任一二○师三五八旅旅长。抗日战争胜利后任东北松江军区司令员。——第14页

　　〔18〕一九二七年蒋介石、汪精卫相继背叛革命后，许多地方的工农群众在共产党领导下举行武装起义，先后建立了称为苏维埃的革命政权。广东海陆丰等地的农民，在四月、九月和十月三次举行起义，建立革命政权。海南岛的定安、琼山、万宁、乐会等地的农民，十月举行起义组成了红三师。江西的万安、延福、东固、雩都等地的农民，十二月举行起义，万安建立了革命政权，成立了游击队。湖北的黄安（今红安）、麻城、孝感等地的起义农民，十一月占领了黄安县城三十多天，建立了革命政权。湖南东部的农民，九月举行起义，占据过浏阳、平江、醌陵、株洲一带。醴陵农民一九二八年初建立过农村革命政权。——第15页

　　〔19〕指贺龙领导的红军一九二八年十二月攻下湖北省建始县城、一九二九年一月攻下湖北省鹤峰县城的两次战斗。——第15页

　　〔20〕杨维藩，曾是中国共产党恩（施）鹤（峰）临时特委书记，一九二九年初，因工作消极被停止党籍。鹤峰战斗后，因拖枪叛逃被处决。——第17页

　　〔21〕指一九二九年一月发布的《中央通告第二十五号——反对军阀战争和争取群众》和一九二九年二月发布的《中央通告第三十号——目前政治形势的分析与党的主要路线》。——第17页

　　〔22〕汪铭（一九○三——一九三一），一九二五年参加中国共产党。一九二八年任中共山西省委书记。一九二九年被国民党逮捕，一九三一年十月就义。——第20页

　　〔23〕中共顺直省委，先后称北方局、顺直省委、河北省委。顺直指北京（曾名顺天府）和河北（曾名直隶省）。顺直省委曾领导河北、山西、北平（北京）、天津、察哈尔、绥远、热河、河南北部、陕北一部的党的工作。——第20页

　　〔24〕河东七县，指山西南部黄河以东的安邑、闻喜、夏县、解县、猗氏、绛州（即新绛）和绛县。——第22页

　　〔25〕彭，即彭湃，即杨殷；颜，即颜昌颐；邢，即邢士贞。他们是一九二九年八月三十日在上海龙华被敌人杀害的烈士。

　　彭湃（一八九六——一九二九），我党最早的农民运动领袖。一九二二年七月在海丰县赤山创建了全国第一个农会。一九二三年一月当选为海丰总农会会长。一九二四年参加中国共产党。同年创办广州农民运动讲习所，并任中共两广区委委员。一九二五年五月当选为广东省农民协会副委员长。一九二七年参加南昌起义，任中共前敌委员会委员。南昌起义失败后，领导了海陆丰第三次武装起义，创立海陆丰苏维埃，任委员长和中共东江特委书记。一九二八年任中共中央农委书记兼江苏省委军委书记。在党的第五、六次全国代表大会上当选为中央委员，在“八七”会议上被选为政治局委员，在党的第六次全国代表大会上当选为政治局候补委员。第23、118页。杨殷（一八九三——一九二九），早年参加同盟会。一九二三年参加中国共产党。第一次国内革命战争时期担任中共两广区委委员，是省港罢工的领导者之一。一九二七年十二月十一日广州起义时任广州苏维埃政府肃清反革命委员会主席，并曾代理人民委员会主席。一九二八年在党的第六次全国代表大会上当选为中央委员、政治局候补委员、中央常委，并任中央军事部长。第23页。颜昌颐（一八九八——一九二九），一九二一年参加中国共产党。一九二五年在中共中央军委、湖南省委军委工作。一九二六年十月到一九二七年三月参加上海工人三次武装起义。一九二七年参加南昌起义，任二十四师党代表。南昌起义失败后，和彭湃一起发动海陆丰第三次起义，创建海陆丰苏维埃，任红军党代表。一九二八年任中共中央军委委员兼江苏省委军委委员。第23页。邢士贞（？——一九二九），一九二七年参加中国共产党。当时是中共江苏省委军委干部、士兵运动负责人。——第23页

　　〔26〕指蒋介石一九二七年四月十二日在上海发动的反革命政变，参见注〔9〕。——第23、166页

　　〔27〕张际春（？——一九三三），共产党员。一九二九年任上海总工会纠察队副总指挥，同年参加领导上海五月三十日和八月一日两次反帝大示威，八月二十四日被捕，一九三一年冬出狱。——第24页

　　〔28〕《布尔塞维克》杂志，中共中央机关刊物。一九二七年十月二十四日创刊，一九二八年十一月前为周刊，后改为半月刊。现在查到的最后一期是一九三二年七月出版的第五卷第一期。《红旗》，中共中央机关报。一九二八年十一月二十日创刊。共出一二六期，前二十三期是周报，后一○三期是三日报。一九三○年八月二日停刊，同月十五日和《上海报》合并为《红旗日报》。一九三一年二月十四日《红旗日报》改为中共中央和中共江苏省委机关报。同年三月九日改名《红旗周报》，为中共中央机关报。现在查到的最后一期是一九三四年三月一日出版的第六十四期。——第24页

　　〔29〕熊式辉（一八九三——一九七四），当时任国民党军第五师师长兼淞沪警备司令。——第25页

　　〔30〕《少年先锋队歌》，苏联诗人别塞勉斯基填词的革命歌曲，原名《青年近卫军》，曾定为苏联共产主义青年团团歌。第一次国内革命战争时期传入中国，改称《少年先锋队歌》。——第25页

　　〔31〕指当时中国共产党内出现的由一小批托洛茨基分子组成的反党小集团。第一次国内革命战争失败后，中国的托洛茨基分子以“左”的面目山现，不承认当时中国革命的性质是资产阶级民主革命，主张立即没收资本家的工厂企业，进行社会主义革命。他们在组织上进行分裂党的派别活动。一九二八年八月，党中央决定开展反对托派的斗争，号召全党在思想理论上驳斥托派的谬论，对托派骨干分子一律清除出党，对一般分子，主要采取教育方法，争取他们放弃托派观点，回到马克思主义立场上来。——第25、44页

　　〔32〕陈毅（一九○一——一九七二），一九二三年参加中国共产党。一九二九年六月在红四军第七次党代表大会上当选为前敌委员会书记，八月到上海参加中共中央召开的军事会议。——第29页

　　〔33〕指一九二九年三月蒋介石与桂系军阀李宗仁、白崇禧之间和同年五月蒋介石与西北军冯玉祥之间为争夺地盘、扩展势力进行的军阀战争。——第29、178页

　　〔34〕一九二九年四月十七日，国民党政府的中国航空公司与美国航空发展公司订立航空邮务合同，允许美国公司经营南京至汉口、南京至北平、汉口至广州三条航线的航空邮政业务，给予邮件运输的专利权，并允许以后可以延长和开辟新的国内航线。——第29页

　　〔35〕一九二九年六月二十日国民党政府与英国订立海军援助协定，英国答应帮助国民党政府训练海军。——第29页

　　〔36〕指日本帝国主义侵略我国东北和内蒙地区，进而侵略全中国的计划。据当时中外报纸揭载，日本首相兼外相田中又一在一九二七年给日本天皇的秘密奏折中称：“惟欲征服支那，必先征服满蒙，如欲征服世界，必先征服支那。”——第29页

　　〔37〕中东路是一八九六年清政府与沙皇俄国签订“中俄密约”后，由俄国投资在我国东北地区修建、经营的一条铁路。一九二四年中苏协定改为两国共同经营管理。一九二七年国民党反动政权建立后，执行亲帝反苏的外交政策，制造了一系列反苏事件。一九二九年七月十日，国民党政府单方撕毁一九二四年的中苏协定，以武力手段夺占中东铁路，驱逐任职的苏方人员。七月十七日，苏联宣布同国民党政府断绝外交关系。十月，蒋介石命令东北军八万余人开赴绥芬河，发动对苏联的进攻。这一进攻因苏联军队的回击而失败。——第29页

　　〔38〕指一九二九年九月开始的国民党军第四师师长张发奎与桂系军阀、广西省政府主席俞作柏联合反对蒋介石的战争。这次战争又称两广战争或两广冲突。——第30、31页

　　〔39〕改组派，是二十年代末期到三十年代初期的国民党派系之一。一九二七年“七一五”反革命政变后，武汉汪精卫的国民党和南京蒋介石的国民党合流。汪精卫、陈公博、顾孟余等不满蒋介石独揽权力，一九二八年底在上海成立“中国国民党改组同志会”，形成了国民党中的“改组派”。——第30、163页

　　〔40〕汪精卫、陈公博为首的国民党改组派的改良主义，主张发展“国家资本”，兴办“合作事业”，实行工人“红利制”和农村“自治”，“以反对共产党和党内外的军阀”。——第30页

　　〔41〕冯，指冯玉祥；唐，指唐生智；朱，指朱培德。——第30页

　　〔42〕阎，指阎锡山；张，指张学良。——第31页

　　〔43〕指奉系军阀张作霖部属中土匪出身的以张景惠、张作相为首的旧派与留日士官学校出身的杨宇霆、韩麟春为首的新派之间的斗争。——第31页

　　〔44〕杨，指当时东北兵工厂督办杨宇霆；常，指当时黑龙江省省长常荫槐。他们是张作霖的重要部属。张作霖死后，张学良为了加强自己的统治地位，一九二九年一月十一日枪杀了杨、常。——第31页

　　〔45〕刘和鼎，当时任国民党军第五十六师师长，驻浦口一带，一九二九年被蒋介石调往福建“围剿”红军。——第32、67页

　　〔46〕张贞，当时任国民党军暂编第一师师长。——第32页

　　〔47〕指一九二九年夏天国民党广东省政府主席陈铭枢和国民党军第八路军总指挥陈济棠为争夺广东的军政大权而发生的冲突。——第32页

　　〔48〕金汉鼎，当时任国民党军第三十一军军长。——第32页

　　〔49〕朱培德，当时任国民党军第五方面军总指挥兼江西省政府主席，一九二九年被蒋介石调离江西，省主席一职为鲁涤平所取代。——第32页

　　〔50〕王均，当时任国民党军第三军军长。——第32页

　　〔51〕CY，共产主义青年团（CommunistYouthLeague）的英文缩写。——第41页

　　〔52〕托洛茨基（一八七九——一九四○），十月革命时，任俄国社会民主工党中央政治局委员、彼得格勒苏维埃主席，十月革命胜利后，曾任最高军事委员会主席等职，在一九一二年联络过孟什维克等机会主义派别，组织八月联盟，反对列宁领导的布尔什维克。第一次世界大战期间和十月革命后，托洛茨基在战争、和平以及革命等基本问题上以“左”的立场反对列宁的正确方针政策。一九二三年秋集结同伙，提出反对派纲领，要求派别活动的自由。列宁逝世后，反对列宁关于在苏联建设社会主义的理论和路线，进行反党的派别活动和破坏活动。一九二七年十一月，托洛茨基和托洛茨基分子在联共（布）第十五次代表大会上被清除出党。一九二九年托洛茨基被驱逐出苏联。在国际共产主义运动中，托洛茨基进行了许多分裂和破坏活动。——第44页

　　〔53〕中央的第四十四号通告，指一九二九年八月十三日中共中央发布的《关于中国党内反对派问题》的通告。——第44页

　　〔54〕胡汉民（一八七九——一九三六），第一次国内革命战争时期曾任代理广州大元帅府大元帅兼广东省长等职，著名的右派首领，是一九二七年蒋介石发动“四一二”反革命政变的同盟者。后来同蒋介石集团争权夺利，长期对立。——第44、115、165页

　　〔55〕戴季陶（一八九○——一九四九），第一次国内革命战争期间，歪曲孙中山学说的革命内容，散布反对共产党、反对工农运动的谬论，为蒋介石发动反革命政变进行思想上的准备。“四一二”反革命政变后继续忠实追随蒋介石。——第44、113、151、166页

　　〔56〕周佛海（一八九七——一九四八），一九二一年曾参加中共第一次全国代表大会，一九二四年叛党。蒋介石叛变后曾任国民党中央宣传部长等职。抗日战争开始后随汪精卫叛国投降日本侵略者，任汪伪政府行政院副院长等职。——第44页

　　〔57〕《新生命》是周佛海主编的反动月刊，一九二八年在上海创刊。——第46页

　　〔58〕一九一九年七月，在第一次世界大战中支持帝国主义战争的第二国际，议决八月一日在瑞士卢赛恩召开代表大会。共产国际执行委员会号召全世界工人在这一天举行游行，向第二国际示威。一九二九年七月，共产国际执行委员会第十次全会决定八月一日为国际反对帝国主义战争日。这一天，中国共产党在上海组织了反帝示威。——第46页

　　〔59〕原意是聪慧的人爱惜聪慧的人。这里借用这句成语，形容机会主义者和反对派同类相聚。——第47页

　　〔60〕指当时我党领导下的革命工会，与国民党领导下的黄色工会相区别。——第48、181页

　　〔61〕钧，即项英（一八九八——一九四一），化名江钧。一九二二年参加中国共产党。一九二八年在党的第六次全国代表大会上当选为中央委员、政治局委员。一九三○年八月任长江局书记。同年十二月到江西革命根据地，历任苏区中央局代理书记、苏区军委主席、中华苏维埃共和国临时中央政府副主席等职。一九三四年十月红军主力长征后，留在原地坚持游击战争。抗日战争爆发后任中共中央东南局书记兼新四军副军长。一九四一年一月，皖南事变时牺牲。——第48、201页

　　〔62〕周恩来在这封信中主张中国共产党人要参加黄色工会去争取群众，但沿用了当时中央文件中流行的“消灭黄色工会”的不正确提法。——第51页

　　〔63〕一九三○年四月，中共湖北省代表大会决定成立工人赤色先锋队，作为城市暴动的中心队伍，后来并未建成。——第51页

　　〔64〕周恩来在这封信中主要是反对“左”倾，特别提出要反对“‘左’倾会比右倾好些”的错误观点。但沿用了当时中央文件中流行的“党内主要的危险是右倾机会主义”的不正确提法。——第52页

　　〔65〕立三，即李立三（一八九九——一九六七），一九二一年参加中国共产党。一九三○年六月至九月犯了“左”倾机会主义（即立三路线）错误。当时任中共中央常委兼秘书长、宣传部长。一九三○年九月六届三中全会后离开了中央领导岗位。后来改正了自己的错误观点，在党的第七和第八次全国代表大会上继续当选为中央委员。——第55、162页

　　〔66〕指共产国际，即第三国际，成立于一九一九年三月，是各国共产党的联合组织。一九二二年中国共产党参加共产国际成为它的一个支部。一九四三年五月共产国际执委会主席团通过决定，宣布解散。——第55、138、151、165、203页

　　〔67〕指中共中央政治局在一九三○年六月十一日通过的《新的革命高潮与一省或数省的首先胜利》决议案。这个决议否认中国革命发展的不平衡性，认为中心城市爆发的工人斗争必然形成全国革命高潮，而且中国革命必将掀起全世界的大革命。决议批评以农村包围城市是一种农民意识的地方观念与保守观点。决议不承认中国民主革命的长期性，认为一省数省首先胜利就是革命转变的开始。这个决议案的通过使立三路线统治了中央的领导机关。——第55页

　　〔68〕指一九三○年二月二十六日发布的《中央七十号通告——目前政治形势与党的中心策略》。——第56页

　　〔69〕陈绍玉，即陈绍禹（一九O四——一九七四），又名王明，党内第三次“左”倾机会主义路线的主要代表。六十年代后堕落成为中国革命的叛徒。——第56、184页

　　〔70〕一九三○年七月二十七日，中国工农红军第五军占领长沙，七月二十九日宣布成立湖南省苏维埃，八月五日退出长沙。这次事件被称为长沙事件。——第56页

　　〔71〕一九二八年八月召开的共产国际第六次代表大会，把第一次世界大战后国际形势的发展分为三个时期：战后至一九二三年为第一时期，是资本主义经济发生尖锐危机和无产阶级革命直接发动时期；一九二四至一九二七年为第二时期，是资本主义经济相对稳定时期；一九二八年第三时期，即资本主义经济“稳定”结束、总危机尖锐化、“大规模阶级搏斗”的时期。——第56页

　　〔72〕指一九二九年七月召开的共产国际执行委员会第十次全会的决议。——第57页

　　〔73〕是由中共中央和中华全国总工会发起，一九三○年五六月间在上海秘密召开的。——第57页

　　〔74〕指中共中央政治局一九三○年八月一日、八月三日在上海召开的会议。在“八一”的会上决定把党、凤、工会的领导机构合并成为中央行动委员会（简称总行委）。在“八三”的会上决定举行武汉暴动、南京暴动与上海总同盟罢工，规定总行委是全国暴动的最高领导机关。当时周恩来不在国内。李立三在会上错误地批评周恩来“在政治上组织上都暴露他右倾的危险”。——第57页

　　〔75〕冯玉祥（一八八二——一九四八），北洋军阀时期曾任旅长、师长、督军、督办等职。一九二四年十月发动北京政变，并将部队改组为国民军。十一月五日取消清废帝溥仪的皇帝称号，将溥仪逐出皇宫。一九二六年九月宣布脱离北洋军阀参加国民革命。一九二七年“四一二”后曾参加蒋介石、汪精卫反对共产党的活动。一九三一年“九一八”事变后赞成抗日。一九三三年五月同共产党合作，在察哈尔省（现在分属山西、河北和内蒙）组织民众抗日同盟军，抵抗日本帝国主义的侵略。以后，继续采取和共产党合作的立场。一九四八年初参加中国国民党革命委员会，任中央政治委员会主席。同年九月一日在由美国回国参加新政协途中遭遇火灾逝世。——第58、120、170、194、211、283页

　　〔76〕一九三二年底蒋介石调集四五十万人的兵力，对中央苏区进行第四次大规模“围剿”。一九三三年二月，蒋军十二个师，采取“分进合击”的战略，分三个纵队由乐安、南城、金溪等地向广昌进攻。红军以一部伪装主力东渡抚河，将敌主力第二、第三两纵队向黎川方向吸引，主力秘密转移到敌军右翼，集中于广昌以西的东韶、洛口地区隐蔽待机。二月二十六日，敌第一纵队三个师由乐安、宜黄向广昌前进。红军先以地方部队不断阻击、袭扰、迷惑敌人，当敌右翼第五十二、第五十九两师进至宜黄南部的黄陂、大龙坪地区时，红军在二十七日拂晓突然发起猛攻，经两天激战，将其全部歼灭。敌军遭此打击后，即改变部署，三月十五日以六个师分成两个梯队由宜黄地区出发，经东陂、甘竹直扑广昌。红军放过敌人先头四个师，在二十一日晨突然向进至草台冈、东陂地区的敌人后尾两个师发起攻击，激战一日，歼敌第十一师大部和第九师一部。余敌仓惶撤退。红军两战共缴枪万余支，这次“围剿”就基本被打破了。（附略图）——第59页

　　〔77〕金溪战役,指一九三三年一月四日至八日红一方面军在江西金溪西南黄狮渡、浒湾地区进行的战役。——第59页

　　〔78〕吴、罗、周三师，指国民党军吴奇伟的第九十师、罗卓英的第十一师、周至柔的第十四师。——第59页

　　〔79〕南丰战役，指一九三二年十一月一日至二日红一方面军在江西南丰城以东石沟墟地区进行的战役。南城战役，指一九三二年十一月二十一日至二十二日红一方面军在江西南城以东礼西赵地区进行的战役。金溪战役，见注〔77〕。——第60页

　　〔80〕曾，即曾洪易，当时任中国工农红军闽浙赣军区政治委员。一九三五年叛变投敌。邵，即邵式平（一八九八——一九六五），当时任中国工农红军闽浙赣军区政治部主任。唐，即唐在刚（一九○三——一九三五），当时任中国工农红军闽浙赣军区司令员。一九三五年一月，在北上抗日途中牺牲。——第61页

　　〔81〕宜黄、乐安战役，指一九三二年八月十六日至二十日红一方面军攻占江西乐安、宜黄的战役。——第61页

　　〔82〕陈诚（一八九六——一九六五），一九二二年在粤军任连长。一九三三年第四次“围剿”时任国民党军第二路军总指挥。西安事变时任国民党政府军政部常务次长。解放战争期间任国民党军参谋总长等职。——第61、114、192、277页

　　〔83〕朱，即朱德（一八八六———一九七六），当时任中共中央委员、政治局委员、中国工农红军总司令和中华苏维埃共和国临时中央政府革命军事委员会主席。王，即王稼祥（一九○六——一九七四），当时任中央苏区中央局委员、红军总政治部主任、中华苏维埃共和国临时中央政府革命军事委员会副主席。——第62页

　　〔84〕彭鳌（一九○四——一九三三），一九二六年参加中国共产党。第四次反“围剿”时任中国工农红军第三军团第三师师长。一九三三年二月十三日牺牲。——第64页

　　〔85〕赵观涛，当时任国民党军第八路军总指挥。——第65页

　　〔86〕董，即董振堂（一八九五——一九三七），曾在国民党军任连长、营长、团长、师长。一九三一年十二月十四日同赵博生一起率部举行宁都起义，参加中国工农红军，任第五军团第十三军军长。一九三二年参加中国共产党。后任中国工农红军第五军团军团长。一九三七年一月二十日在甘肃高台战役中牺牲。朱，即朱瑞（一九○五——一九四八），一九二八年参加中国共产党。当时任中国工农红军第五军团政治委员。抗日战争时期历任北方局军委书记、山东分局书记、延安炮兵学校校长等职。抗战胜利后任东北人民解放军炮兵司令员等职。一九四八年十月在解放义县的战斗中牺牲。——第68页

　　〔87〕彭，即彭德怀（一八九八——一九七四），一九二八年参加中国共产党。当时任中共中央军委副主席、中国工农红军第三军团军团长。滕，即滕代远（一九○四——一九七四），一九二四年参加中国共产主义青年团，一九二五年转入中国共产党。当时任中国工农红军第三军团政治委员。——第69页

　　〔88〕林，即林彪（一九○七——一九七一），一九三○年一月任中国工农红军第四军第一纵队司令。一九三三年第四次反“围剿”时任中国工农红军第一军团军团长。抗日战争时期任八路军一一五师师长。一九六六年后组织反革命阴谋集团，企图篡党夺权，阴谋败露后，一九七一年九月十三日叛国出逃，机毁丧命。——第69、179、203、253页

　　〔89〕聂，即聂荣臻（一八九九——），当时任中国工农红军第一军团政治委员。——第69页

　　〔90〕宋子文（一八九四——一九七一），当时任国民党中央执行委员、国民党政府经济委员会主席。第70、193页。宋美龄（一九○一——），蒋介石的妻子。蒋鼎文（一八九六——一九七四），当时任国民党政府福建绥靖公署主任。西安事变前蒋介石准备调他任西北“剿总”前敌总司令。——第70、192页

　　〔91〕张，即张学良（一九○一——），东北军爱国将领。当时任国民党西北“剿总”副司令。一九三六年十二月和杨虎城一起发动西安事变，要求蒋介石停止内战，一致抗日。后被蒋介石长期扣押。——第70、193、248页

　　〔92〕杨，即杨虎城（一八九三——一九四九），西北军爱国将领。当时任国民党军第十七路军总指挥、西安绥靖公署主任等职。一九三六年十二月和张学良一起发动西安事变，要求蒋介石停止内战，一致抗日。一九三七年四月，被蒋介石迫令去职出国。同年十一月回国参加抗日工作，随即被蒋介石长期囚禁。一九四九年九月在重庆国民党集中营惨遭杀害。——第70、193、248页

　　〔93〕何应钦（一八八九——），当时任国民党政府军政部长、军事委员会总参谋长。

　　张群（一八八九——），当时任国民党政府外交部长。

　　张嘉璈（一八八八——），当时任国民党政府铁道部长。

　　吴鼎昌（一八八四——一九五○），当时任自民党政府实业部长。

　　陈绍宽（一八八八——一九六九），当时任国民党政府海军部长。中华人民共和国成立后，曾任国防委员会委员等职。——第71页

　　〔94〕孔祥熙（一八八○——一九六七），当时任国民党政府行政院代院长兼财政部长。

　　徐新六（一八九○——一九三八），当时任浙江兴业银行总经理、复旦大学校长。

　　颜惠庆（一八七七——一九五○），曾任北洋政府的外交总长和中国出席国联第十六届大会的首席代表。

　　赵戴文（一八六七——一九四三），当时任国民党山西省政府主席。

　　邵力子（一八八一——一九六七），当时任国民党陕西省政府主席。中华人民共和国成立后，曾任政务院政务委员等职。

　　胡宗南（一八九六——一九六二），当时任国民党军第一军军长。

　　陈季良（一八八三——一九四四），当时任国民党政府海军部政务次长。

　　沈鸿烈（一八八二——一九六九），当时任国民党政府青岛市长。

　　孙科（一八九一——一九七三），当时任国民党政府立法院长。

　　曾养甫（一八九八——一九六九），当时任国民党政府广州市长。

　　朱家骅（一八九三——一九六三），当时任国民党浙江省政府主席兼民政厅长。

　　俞飞鹏（一八八四——一九六六），当时任国民党政府交通部代理部长。

　　卢作孚（一八九四——一九五二），当时任民生实业公司总经理。中华人民共和国成立后，曾任中国人民政治协商会议全国委员会委员等职。

　　张伯苓（一八七六——一九五一），当时任南开大学校长。

　　王世杰（一八九二——），当时任国民党政府教育部长。

　　宋庆龄，当时任国民党中央执行委员、全国各界救国联合会执行委员。

　　杜重远（一八九七——？），当时任上海进步刊物《新生周刊》主编，一九三五年五月，曾因刊登爱国文章，被国民党政府判刑。西安事变前曾帮助张学良接受我党提出的抗日民族统一战线政策。抗日战争时期在新疆被军阀盛世才秘密杀害。

　　沈钧儒（一八七五——一九六三），当时是上海文化界救国会和全国各界救国联合会主要领导人之一。一九三六年十一月与章乃器、邹韬奋、李公朴、沙千里、史良、王造时一起被国民党反动派逮捕，抗日战争爆发后始出狱。一九四八年到解放区参加新政协筹备工作。中华人民共和国成立后，曾任最高人民法院院长、全国人民代表大会常务委员会副委员长等职。

　　章乃器（一八九七——一九七七），当时是全国各界救国联合会主要领导人之一。中华人民共和国成立后，曾任粮食部长等职。——第71页

　　〔95〕七领袖，指当时在上海领导各界抗日救亡运动被国民党反动派逮调的沈钧儒、章乃器、邹韬奋、李公朴、沙千里、史良、王造时等七人，也称“七君子”。——第71、192、248页

　　〔96〕阎，指阎锡山（一八八三——一九六○），长期统治山西的军阀。一九三七年八月起任第二战区司令长官。——第79、85、229、236页

　　〔97〕教导团的全称是山西国民兵军官教导团，决死队的全称是山西青年抗敌决死队，少先队的全称是山西少年抗敌先锋队。一九三六年秋，中共中央北方局派薄一波等到山西开辟工作，在取得阎锡山同意后，相继组织了这些人民抗日武装，统称为山西新军。——第79页

　　〔98〕黄，指黄绍竑（一八九五——一九六六），国民党桂系军人。当时任第二战区副司令长官。中华人民共和国成立后，曾任政务院政务委员等职。卫，指卫立煌（一八九六——一九六○），当时任第二战区副司令长官。一九五五年由香港回到北京，曾任国防委员会副主席等职。——第79、200页

　　〔99〕刘湘（一八八九——一九三八），四川军阀。当时任第七战区司令长官。——第79页

　　〔100〕许旅，指西北军十七路军九十六军一七七师五二九旅。旅长许权中（一八九四——一九四三），共产党员。一九二八年参加陕西渭华暴动。一九三三年在察哈尔民众抗日同盟军中任第十八师师长。抗日战争开始后曾参加易县、曲阳阻击日军的战斗和忻口战役。一九四三年在陕西（眉）县被胡宗南部暗杀。赵师，指十七路军十七师。师长赵寿山（一八九三——一九六五），西安事变后在党的领导下从事秘密工作。一九四二年参加中国共产党。一九四六年三月到解放区。一九四八年一月任中国人民解放军第一野战军副司令员。中华人民共和国成立后，任国防委员会委员等职。  孙军，指十七路军三十八军。军长孙蔚如（一八九六——一九七九），西北军爱国将领。长期和中国共产党保持联系，同情和支持人民革命事业。中华人民共和国成立后，曾任国防委员会委员等职。——第79页

　　〔101〕总动会，指第二战区民族革命战争战地总动员委员会。它是在共产党的组织和推动下建立的带有战时政权性质的组织，当时的工作任务是在雁北、绥远、察南战地发动和组织群众参加抗日活动。主任委员是续范亭。——第80页

　　〔102〕胡服，即刘少奇（一八九八——一九六九），当时任中共中央代表，领导北方局工作。——第80页

　　〔103〕宋任穷（一九○九——），当时任第十八集团军一二九师政治部主任。——第80页

　　〔104〕彭真（一九○二——），当时任中共中央北方局组织部长。——第80页

　　〔105〕雪枫，即彭雪枫（一九○七——一九四四），一九二六年参加中国共产党。当时任八路军太原办事处主任。一九四一年任新四军第四师师长兼淮北军区司令员。一九四四年九月在河南夏邑和日伪军作战中牺牲。——第80页

　　〔106〕九国公约，是一九二二年二月美、英、法、日、意、比、荷、葡与中国北洋军阀政府在华盛顿会议上签订的。公约主要反映美、英帝国主义和日本帝国主义在中国问题上的矛盾，提出“中国门户开放”、列强在华利益“机会均等”。一九三七年十一月在布鲁塞尔召开了“九国公约”缔约国会议，日本拒绝参加。出席会议的除原缔约国家外，还有苏联、印度等共十九个国家。由于美英对日采取绥靖政策，拒绝讨论苏联提出的集体安全原则，会议没有取得积极结果，助长了日本的侵略气焰。——第81页

　　〔107〕据英国伦敦《标准晚报》一九三七年十月三十日报道，日本政府当时曾向蒋介石提出了六项议和停战条件：一、中国承认内蒙为独立国；二、华北五省有决定自治之权；三、上海日军占领区域改为日本科界，并须取得通海道路；四、中国沿海自山海关起至越南界止所有各岛附近之捕渔权让给日本；五、中国退出国联；六、中国不得设立军用航空。——第82页

　　〔108〕华北自治政府，指当时日本侵略军正在华北制造的汉奸政权。这一傀儡政权于一九三七年十二月十四日在北平成立，称为“中华民国临时政府”，主要头目是王克敏、主揖唐等。——第82页

　　〔109〕维持会是抗日战争期间日本侵略者在我国沦陷区利用汉奸建立的临时性的地方傀儡政权组织。——第82页

　　〔110〕一九三七年十月，在日本侵略者的策划和操纵下，蒙奸德穆楚克栋鲁普（即德王）集团把原“蒙古军政府”改组为“蒙古联盟自治政府”，宣称“蒙古自治”——第82页

　　〔111〕汪，即汪精卫（一八八三——一九四四），一九二五年任广州国民政府主席。一九二七年在武汉发动“七一五”反革命政变。一九三一年“九一八”事变后主张与日本帝国主义妥协。抗日战争爆发后任国民党副总裁。一九三八年底公开投降日本。一九四○年在南京成立傀儡政权。——第83、115、208页

　　〔112〕特殊化，是日本帝国主义侵华的一个策略步骤。一九三五年四月，日本策划在中国华北五省（河北、察哈尔、山西、山东、绥远）建立脱离国民党政府、听命于日本帝国主义的特殊区域。同年六月，国民党政府在华北的代表何应钦与日本华北驻屯军司令官梅津美治郎签订《何梅协定》，接受了日本的要求，使中国在河北和察哈尔两省的主权大部分丧失。十月，日本又策动汉奸进行所谓“华北五省自治运动”，并成立“冀东防共自治政府”。国民党政府则指派来哲元等成立“冀察政务委员会”，以适应日本关于“华北政权特殊化”的要求。——第83页

　　〔113〕南怀化现属山西省原平县王家庄公社。——第84页

　　〔114〕这里讲的“三三制”是军队的一种编制，指每级直辖三个单位，如每团下辖三个营，每营下辖三个连，每连下辖三个排，每排下辖三个班。——第86页

　　〔115〕一九三七年八月二十五日，中共中央政治局在陕西洛川召开的扩大会议上提出抗战十大纲领：一、打倒日本帝国主义；二、全国军事的总动员；三、全国人民的总动员；四、改革政治机构；五、抗日的外交政策；六、战时的财政经济政策；七、改良人民生活；八、抗日的教育政策；九、肃清汉奸卖国贼亲日派，巩固后方；十、抗日的民族团结。——第87、154页

　　〔116〕东北四省，指辽宁、吉林、黑龙江和热河（热河省一九五五年撤销，辖区分别划归河北、辽宁二省和内蒙古自治区）。一九三一年日本帝国主义在沈阳发动“九一八”事变，随即派兵向辽宁、吉林、黑龙江三省进攻。由于蒋介石坚持不抵抗政策，仅仅百余日，辽、吉、黑三省即为日军所占领。一九三三年二月，日军又进攻热河，前后不过十天，热河全境沦陷。——第90页

　　〔117〕一九二二年六月曾任粤军总司令的陈炯明背叛孙中山，被许崇智等逐出广州后退踞广东东江（惠州、潮汕一带）。东江战争指一九二三年夏至一九二四年夏，孙中山调集许崇智的粤军，谭延闿、程潜的湘军，杨希闵的滇军和刘震寰的桂军，进攻陈炯明部的战争。西江战争指一九二三年一月和五月在广东肇庆一带滇桂粤联军先后与军阀陈炯明、沈鸿英部的战争。北江战争指一九二三年五月至十一月在广东韶关一带，滇桂粤联军与军阀沈鸿英部的战争。南路战争指一九二三年九月和一九二四年七月在广东廉州、雷州等地，粤军与陈炯明部邓本殷的战争。——第92页

　　〔118〕黄埔军校，是一九二四年孙中山在中国共产党和苏联的帮助下，在广州黄埔创办的军官学校。中国共产党派周恩来、挥代英、肖楚女、聂荣臻等在该校担任过各种职务，学员中也有很多共产党员和共青团员。一九二七年蒋介石背叛革命以前，这是一所国共合作的学校。——第92、114、166页

　　〔119〕为了巩固广东革命根据地，准备北伐，一九二五年二月至三月，中国共产党和国民党合作组织的以黄埔军校学生为骨干的革命军从广州出发东征，打败了盘踞在东江的军阀陈炯明的主力。六月回师广州，平息了盘踞广州的滇、桂军阀杨希闵、刘震寰的叛乱。十月至十一月举行第二次东征，最后消灭了陈炯明的军队。——第92、117、118页

　　〔120〕杨，即杨希闵，当时任驻粤滇军总司令兼第一军军长、广州革命政府委员。刘，即刘震寰，当时任驻粤桂军总司令兼广西省长、广州革命政府委员。一九二五年六月，杨、刘勾结在一起，发动叛乱，企图颠覆广州革命政府。国民革命军从东江回师广州，迅速平定了这一叛乱。——第93、117页

　　〔121〕一九二六年七月，为了推翻北洋军阀的统治，国民革命军从广州出师北伐。由于有中国共产党的政治领导和广大工农群众的积极支持，国民革命军迅速地占领了长江中下游广大地区，严重地打击了帝国主义和封建势力。一九二七年四月十二日，以蒋介石为代表的国民党右派发动反革命政变，第一次国内革命战争遭到失败。——第93、124、211、246、318、366页

　　〔122〕一九三六年二月西班牙共和国进行国会选举，西班牙共产党领导的人民阵线获胜，成立共和政府。同年七月西班牙将军佛朗哥在德、意法西斯军队直接参与下发动了内战。世界进步力量积极支援西班牙政府，组织国际纵队同西班牙人民并肩作战。英、法政府在“不干涉政策”名义下对西班牙共和国实行封锁。经过三年苦战，一九三九年三月首都马德里沦陷，共和国政府失败。佛朗哥夺取政权，建立了法西斯统治。——第93页

　　〔123〕蒋介石发动“四一二”反革命政变后，国民党军队的政训处大多变成了特务机构。它的任务是进行反共宣传，侦察和监视官兵的思想行动，以利于蒋介石个人对军队的控制。——第94页

　　〔124〕六中全会指一九三八年十月在延安召开的中国共产党第六届中央委员会第六次全体会议。——第102页

　　〔125〕青帮，民间秘密团体。清初从漕运行业中发展起来，其成员主要是船工、手工业者、城市贫民、流氓无产者及破产农民等，其组织带有浓厚的宗教迷信和封建宗法制色彩。常为官僚军阀所收买和利用。但在辛亥革命中曾起过一些作用。一九二七年蒋介石举行反革命政变时，上海、武汉等地的青帮头子充当了蒋介石屠杀共产党人、破坏革命的工具。大刀会，民间秘密团体。清末产生时是白莲教支派，主要活动在山东、苏北、皖北一带，成员绝大多数是贫苦农民，带有浓厚的封建迷信色彩。曾在一些地区进行反抗封建压迫和外国传教士的斗争，并参加了义和团的反帝爱国运动。但也常被封建地主利用来镇压农民的反抗。——第108页

　　〔126〕董必武（一八八五——一九七五），中国共产党创始人之一。一九二四年任中共武汉地委书记、湖北省委委员，领导筹建了中国国民党湖北省党部，任常务委员。——第112页

　　〔127〕陈潭秋（一八九六——一九四三），中国共产党创始人之一。一九二四年后历任中共武汉地委书记、湖北区委委员兼组织部长，曾参加中国国民党湖北省党部的筹建工作。一九三九年任中国共产党驻新疆代表和八路军新疆办事处主任。一九四二年被军阀盛世才逮捕，一九四三年九月被秘密杀害。由于情况隔绝，在一九四五年党的第七次全国代表大会上被选为中央委员。——第112、185页

　　〔128〕何叔衡（一八七五——一九三五），中国共产党创始人之一。当时是中共湘区委员会负责人之一，湘江中学校长，曾参加改组中国国民党湖南省党部的工作。一九三一年任中华苏维埃共和国临时中央政府工农监察委员、最高法院院长等职。一九三四年红军长征后留根据地坚持斗争。一九三五年二月在福建长江突围战斗中牺牲。——第112页

　　〔129〕夏曦（一九○○——一九三六），一九二一年参加中国共产党。北伐战争时任中共湘区委员会委员，在国民党第二次全国代表大会上当选为候补中央执行委员。参加中国国民党湖南省党部的筹建工作，任常务委员。——第112页

　　〔130〕宣中华（一八九八——一九二七），一九二三年参加中国共产党。当时是中共杭州地委负责人之一，一九二四年参加筹建中国国民党浙江省党部，当选为执行委员和常务委员。一九二七年四月十一日在上海被蒋介石反动派逮捕，十二日就义。——第112页

　　〔131〕侯绍裘（一八九六——一九二七），一九二三年参加中国共产党。一九二六年任中国国民党江苏省党部常务委员。一九二七年四月十日在南京被捕就义。——第112页

　　〔132〕李大钊（一八八九——一九二七），中国共产党创始人之一。当时是中共北方区执行委员会负责人，在中国国民党第一次全国代表大会上当选为国民党中央执行委员，领导筹建国民党北京市、天津市、直隶省党部，主持国民党在北方的最高领导机关——国民党中央政治委员会的工作。一九二七年四月六日在北京被军阀张作霖逮捕，二十八日就义。——第112、322页

　　〔133〕于树德（一八九四——），一九二二年曾参加中国共产党。当时是北京大学教授。现任中国人民政协全国委员会常务委员。——第112页

　　〔134〕李永声（一八七二——一九五二），又名李锡九。一九二二年参加中国共产党。同年在天津参加筹建中共顺直省委。一九二四年出席中国国民党第一次全国代表大会，会后参加筹建和领导国民党直隶省党部。中华人民共和国成立后，曾任中央人民政府委员等职。——第112页

　　〔135〕于方舟（一九○○——一九二八），一九二二年参加中国共产党。一九二三年任中共顺直省委组织部长。一九二四年出席中国国民党第一次全国代表大会，被选为候补中央执行委员。参加筹建和领导中国国民党直隶省党部。一九二七年秋领导河北玉田农民暴动时被俘，一九二八年春就义。——第112页

　　〔136〕一九二四年十一月，孙中山从广州经上海到北京，准备同当时战胜了直系军阀、控制了北京政府的段祺瑞、张作霖等谈判。他在北上宣言中主张对内“推倒军阀”，对外“推倒帝国主义，废除不平等条约”，并主张召集国民会议来解决这些问题。他在到达天津时已病重，一九二五年三月十二日在北京逝世。——第113页

　　〔137〕一九二三年八月和一九二四年十一月，中国共产党先后两次发表宣言，提出召开国民会议，以代替北洋军阀的反动统治。这一号召得到全国人民的响应，孙中山对此采取积极支持态度。在全国范围内很快形成了一个以“召集国民会议”、“废除不平等条约”为内容的人民运动。各地先后成立了国民会议促成会。一九二五年三月间，国民会议促成会代表大会在北京召开。——第113页

　　〔138〕冯自由，当时是国民党中央委员。  谢持，当时是国民党中央监察委员。一九二四年六月与张继等联名发出“弹劾共产党书”。一九二五年与邹鲁等发起两山会议。——第113页

　　〔139〕一九二五年十一月，国民党右派邹鲁、谢持、居正、张继、林森等十余人，在北京西山碧云寺召开“国民党一届四中全会”，通过反苏、反共、反对国共合作等反动议案，在上海成立国民党“中央党部”，在北京成立“地方党部”。这批人被称为西山会议派。——第113页

　　〔140〕孙文主义学会，是国民党内的一批右派分子为对抗黄埔军校革命军人团体——“青年军人联合会”而建立的反动组织。主要头目有戴季陶、王柏龄、陈诚、贺衷寒、缪斌等。——第114、155、166页

　　〔141〕孙科，当时任国民政府广州市长。一九二四年国民党第一次代表大会后，曾提出弹劾共产党。——第114页

　　〔142〕五五宪章，是一九三六年五月五日国民党政府颁布的《宪法草案》的简称。这个“宪草”的主旨是维护国民党一党专政。——第114、228、265页

　　〔143〕李济深（一八八六——一九五九），早年曾任奥军第一师参谋长、师长。北伐战争时任国民革命军总司令部参谋长，留守广州，一九二七年参加国民党反动派反共反人民的活动。一九三三年联合十九路军在福建组织反蒋抗日的“中华共和国人民革命政府”。抗日战争爆发后，支持中国共产党一致抗日的主张，联络国民党内的爱国民主力量，反对蒋介石的独裁政策。一九四八年组织中国国民党革命委员会，任主席。中华人民共和国成立后，任中央人民政府副主席等职。——第114、174、283页

　　〔144〕邓铿（一八八六——一九二二），早年参加同盟会。一九一七年起任粤军参谋长、第一师师长等职。——第114页

　　〔145〕张发奎（一八九六——一九八○），曾任粤军第一师团长，一九二五年任国民革命军第四军第十二师师长。——第114页

　　〔146〕邓演达（一八九五——一九三一），国民党左派领袖之一。一九二○年参加孙中山组织的粤军，历任营长、团长。一九二六年任黄埔军校教育长。北伐战争期间任国民革命军总政治部主任、湖北省政府主席等职。一九二七年三月与宋庆龄、何香凝、吴玉章等在武汉召开国民党二届三中全会，这次会议通过了限制蒋介石权力的决定。“四一二”反革命政变后，被蒋介石下令通缉。汪精卫和蒋介石合流后，邓流亡苏、德等国。一九三○年回国。一九三一年十一月，被蒋介石秘密杀害于南京。——第114、166页

　　〔147〕辛亥革命，指一九一一年（辛亥年）推翻清朝专制朝廷的中国资产阶级民主革命。这年十月十日，一部分驻在湖北武昌的“新军”在革命团体策动下，发动了反对清朝统治的起义。由于各省相继响应，清政府的统治迅速瓦解。一九一二年一月一日在南京成立了中华民国临时政府。——第114、151、246、318页

　　〔148〕新军，指清朝末年编练的新式陆军。辛亥革命前夕，由于革命党人的积极活动，各省新军中的下级军官和士兵倾向革命的人日益增多，新军就成为武昌和各地起义的重要力量。会党，指哥老会等旧中国的民间秘密团体。孙中山领导的同盟会曾利用会党举行武装起义。——第114页

　　〔149〕陈其美（一八七八——一九一六），早年参加同盟会，曾在江浙一带策动反清革命运动，同时在上海加入青帮为大头目。辛亥革命后任沪军都督。一九一二年初，指使蒋介石刺杀光复会著名领袖陶成章。——第115、151页

　　〔150〕中华革命党，参见注〔2〕。——第115页

　　〔151〕黄克强，即黄兴（一八七四——一九一六），一九○四年组织反清革命团体华兴会，任会长。一九○五年华兴会与兴中会、光复会联合组成中国同盟会，黄是同盟会中仅次于孙中山的重要领袖。一九○七年起，多次参与或领导反清的武装起义。武昌起义后任革命军总司令。一九一二年任南京临时政府陆军总长。一九一三年任江苏讨袁军总司令。——第115页

　　〔152〕永丰舰，是广州革命政府的最大军舰。一九二二年陈炯明叛乱时，孙中山曾在此舰避难。孙中山逝世后改名“中山舰”。——第115页

　　〔153〕一九二二年六月十六日，陈炯明勾结英帝国主义和直系军阀，背叛孙中山，炮击设在广州的总统府。——第115页

　　〔154〕王柏龄，当时任黄埔军校教授部主任，积极反对孙中山的三大政策，是“孙文主义学会”的发起人之一。一九二五年代理黄埔军校教育长。——第116页

　　〔155〕王懋功，一九二五年任广州卫戍总司令，一九二六年二月被蒋介石免职。后投靠蒋介石，任国民党中央委员、江苏省政府主席、第十战区副司令长官等职。——第116、201页

　　〔156〕鲁易（一九○○——一九三二），一九二一年参加少年共产党，一九二二年转入中国共产党。第一次国内革命战争期间历任黄埔军校政治部副主任、国民革命军第一军第三师党代表。一九三二年八月在洪湖战斗中被俘就义。——第116页

　　〔157〕青年军人联合会是周恩来在黄埔军校领导组织的革命军人团体。成立于一九二五年二月一日。以黄埔军校的共产党员和共青团员为骨干，联合粤军讲武学校、滇军干部学校、桂军军官学校等校的青年军人组成，主要成员有蒋先云、周逸群等。联合会积极宣传革命理论和共产党的统一战线政策，团结革命力量，打击国民党右派势力，同反动的孙文主义学会进行了针锋相对的斗争。一九二六年三月二十日“中山舰事件”后被蒋介石解散。——第116、166页

　　〔158〕一九二四年，英帝国主义用大量金钱、军火支持广州大买办陈廉伯所控制的反革命武装组织商团，企图颠覆广东革命政府。八月，广东革命政府扣留了陈廉伯为组织武装叛乱而偷运的军火。陈指使商团向孙中山请愿，并在全省各地煽动罢市。十月十日，广州群众为庆祝辛亥革命举行游行，遭到商团的射击，参加游行的十六个团体成立了“工农兵学革命大同盟”，发表宣言，坚决要求解散商团，严惩凶手。在中国共产党、广大工农群众和国民党左派的影响和支持下，孙中山采取断然措施，调集工农武装、黄埔学生及其他军队，在十五日消灭了这一反革命武装。——第116页

　　〔159〕为了声援“五卅”运动，香港工人在一九二五年六月十九日开始举行总罢工，参加人数达二十五万；六月二十一日，广州沙面租界的中国工人也开始举行罢工。这两处反英的罢工合称为省（指省城广州）港罢工。六月二十三日，两处罢工工人合组省港罢工委员会，并成立纠察队，封锁香港和沙面租界，使英帝国主义在政治上和经济上受到严重打击。这次罢工坚持了一年零四个月。一九二六年十月北伐军占领武汉后，胜利结束。——第116页

　　〔160〕谭延闿（一八八○——一九三○），一九二四年任国民党中央执行委员、中央政治委员会主席。一九二五年任国民政府常务委员兼军事委员会委员、国民革命军第二军军长。一九二七年任国民党中央常务委员、中央政治委员会主席团成员、武汉国民政府常务委员等职。——第117、165页

　　〔161〕朱培德（一八八九——一九三七），当时任国民党中央执行委员、中央政治委员会委员、国民革命军第三军军长等职。——第117页

　　〔162〕程潜（一八八一——一九六八），当时任国民革命军第六军军长。中华人民共和国成立后，曾任全国人民代表大会常务委员会副委员长等职。——第117页

　　〔163〕一九二四年，彭湃创办广东省农民协会农民运动讲习所。第一至第五期由彭湃、阮啸仙等主办。一九二六年五月第六期由国民党中央农民部主办，改名为中央农民运动讲习所，由毛泽东任所长，肖楚女、彭湃、恽代英、周恩来、阮啸仙、赵自选等共产党人担任教员。这一期学员来自全国二十个省区，共三百二十七人，同年九月结业。一九二七年三月，毛泽东在武昌又举办过农民运动讲习所，训练过一期学员。——第117页

　　〔164〕一九二五年六月二十三日，广州各界人民和黄埔学生军约十万人为抗议帝国主义在上海制造“五卅”惨案，举行声势浩大的游行示威。游行队伍行经沙基时，遭到沙面租界内英法军队机枪扫射，当场被打死五十二人，重伤一百七十多人。这次事件被称为沙基惨案。——第117页

　　〔165〕许崇智（一八八六——一九六一），当时任粤军总司令。——第118页

　　〔166〕彭湃的哥哥彭汉垣，受彭湃的影响投身革命，一九二五年第一次东征后任海丰县长。一九二八年三月被捕，后在广州就义。——第118页

　　〔167〕陈延年（一八九八——九二七），一九二二年参加中国共产党。一九二四年任中共两广区委书记。一九二七年四月在党的第五次全国代表大会上当选为中央委员、中央政治局候补委员。“五大”后，任中共江苏省委书记。一九二七年六月被捕，七月在上海龙华就义。——第118页

　　〔168〕鲍罗廷（一八八四——一九五一），第一次国共合作时苏联政府派到广州革命政府的代表和国民党的政治顾问。一九二三年十月来华，一九二七年“七一五”政变后回国。——第118、166页

　　〔169〕张国焘（一八九七——一九七九），一九二一年参加中国共产党第一次全国代表大会。在党的第二、四、五、六次全国代表大会上当选为中央委员，在党的六届一中全会上当选为政治局委员。一九三一年到鄂豫皖苏区第四方面军工作，任中央分局书记、中华苏维埃共和国临时中央政府副主席等职。一九三五年中央红军长征到达川西和四方面军会合后，任红军总政委。反对中央关于红军北上的决定，进行了分裂党和红军的罪恶活动。一九三八年四月背叛革命，投入国民党特务集团，随即被开除党籍。——第119、140、159、213页

　　〔170〕陈独秀（一八八○——一九四二），一九一五年九月起主编《新青年》，一九一八年和李大钊创办《每周评论》，提倡新文化，是“五四”新文化运动的主要领导人之一。“五四”运动后，接受和宣传马克思主义，是中国共产党的主要创始人之一。在党成立以后的最初六年担任党的总书记。在第一次国内革命战争后期，犯了严重的右倾机会主义路线错误。其后，对于革命前途悲观失望，否认无产阶级应继续完成中国民主革命的任务，在党内成立小组织，进行反党活动，一九二九年十一月被开除出党。后和托派组织相结合，一九三一年五月曾被自称为“中国共产党左派反对派”的托派组织推为总书记。一九三二年被国民党逮捕，一九三七年八月出狱。——第119、140、160、209页

　　〔171〕加伦（一八九○——一九三八），即布留赫尔，当时是苏联政府派到广州革命政府的军事总顾问。一九二四年来华，一九二七年“七一五”政变后回国。——第120、170页

　　〔172〕张静江（一八七七——一九五○），当时任国民党中央执行委员会常务委员会代理主席。一九二七年帮助蒋介石筹划了“四一二”反革命政变，并促成了蒋、汪（精卫）间的反革命联合。——第120页

　　〔173〕张太雷（一八九九——一九二七），一九二○年参加共产主义小组。一九二五年在党的第四次全国代表大会上当选为候补中央委员，同年在共青团第三次全国代表大会上当选为书记，并任苏联顾问鲍罗廷的翻译、中共两广区委常委、宣传部长。一九二七年四月在党的第五次全国代表大会上当选为中央委员，八月出席“八七”会议当选为政治局候补委员，十月主持中共中央南方局工作兼任广东省委书记，十二月领导广州起义时牺牲。——第120、174页

　　〔174〕李福林，当时任国民革命军第五军军长。——第120页

　　〔175〕欧阳格，当时任国民革命军海军总指挥、舰队司令。——第121页

　　〔176〕古应芬，一九二四年起历任国民党中央执行委员、中央监察委员、广东省民政厅长等职，一九二七年参与镇压广州起义。——第121、165页

　　〔177〕蒋先云（一九○二——一九二七），一九二一年参加中国共产党。一九二二年领导湖南水口山铅锌矿罢工。一九二四年入黄埔军官学校，毕业后留校任秘书，是青年军人联合会主要负责人之一。一九二六年任国民革命军总部秘书、补充第五团团长、湖北省总工会工人纠察队总队长。一九二七年任第十一军二十六师七十七团团长兼党代表，五月二十八日在河南临颖战役中牺牲。——第121页

　　〔178〕李默庵，当时任国民革命军第一军第一师第三团党代表办公室少校干事。——第121页

　　〔179〕彭述之（一八九六——），一九二一年参加中国共产党。一九二四年在上海大学任教并任《新青年》、《向导》编辑。第一次国内革命战争后期，执行陈独秀的右倾机会主义路线。革命失败后，成为取消主义分子，采取了托洛茨基的反动立场，在党内成立小组织，进行反党活动。一九二九年十一月被开除出党，后成为托洛茨基分子。——第123、159、216页

　　〔180〕陈果夫（一八九二——一九五一），当时任国民党中央监察委员、组织部代部长。一九二七年南京国民党政府成立后，与其弟陈立夫一起组织“中央俱乐部”（即“CC”），控制国民党中央党部“调查统计局”的特务系统。——第123、151、155页

　　〔181〕丁惟汾，当时任国民党北京执行部党务部主任；王法勤，当时任国民党中央政治会议北京分会委员。

　　“大同盟”，是丁惟汾在“五四运动”以后组织的。一九二四年国民党改组后，“大同盟”一度成为国民党北方执行部领导的组织。孙中山逝世后，“大同盟”逐步走上拥蒋反共的道路。——第123页

　　〔182〕李富春（一九○○——一九七五），一九二二年参加中国共产党。北伐战争期间，任国民革命军第二军党代表兼政治部主任。——第123页

　　〔183〕朱克靖（一八九五——一九四七），一九二二年参加中国共产党。北伐战争期间任国民革命军第三军党代表。抗日战争期间任新四军政治部顾问、苏浙行署主任等职。抗日战争胜利后任新四军联络部部长。一九四六年在我党争取郝鹏举部起义后任该部政治委员。一九四七年郝叛变时被扣，同年秋被国民党反动派在南京秘密杀害。——第123页

　　〔184〕罗汉，曾参加中国共产党，一九二七年在莫斯科学习时参加托派组织。——第123页

　　〔185〕林伯渠（一八八五——一九六○），一九二一年参加中国共产党。北伐战争期间任国民革命军第六军党代表。——第123页

　　〔186〕一九一一年（辛亥）十月十日，武昌起义取得胜利。一九一二年中华民国参议院议定将这一天作为国庆节，通称“双十节”。——第124页

　　〔187〕缪斌，当时任国民革命军第一军党代表。——第124页

　　〔188〕柯棣华（一九一○——一九四二），原名德瓦卡纳思·桑塔拉姆·柯棣，印度人。一九三六年毕业于格兰特医学院。一九三八年九月参加印度援华医疗队，来华支援中国人民的抗日战争。一九三九年二月随印度援华医疗队突破国民党的阻拦到达延安。同年十二月赴晋东南抗日前线。一九四○年八月到晋察冀军区白求恩学校和白求恩国际和平医院工作。一九四一年一月任白求恩国际和平医院院长。一九四二年七月七日参加中国共产党。同年十二月九日在河北唐县逝世。——第126页

　　〔189〕两岩，即红岩、曾家岩。红岩，指重庆市郊区化龙桥红岩嘴十三号，抗日战争期间是中共中央南方局和第十八集团军重庆办事处所在地。曾家岩五十号是中共中央南方局和第十八集团军重庆办事处在市内的办公地点。——第128页

　　〔190〕斯大林说过的三点，见斯大林《论党的工作缺点和消灭托洛茨基两面派及其他两面派的办法》。原文是：“正确领导，这就是说：第一、正确地决定问题，而要正确地决定问题，就非考虑群众的经验不可，群众能亲身体验到我们领导的结果；第二、组织对正确决定的执行，但是要做到这一点，就非有群众方面的直接帮助不可；第三、组织对这种决定的执行情况的检查，要做到这一点，还是非有群众的直接帮助不可。”（《斯大林文选》，人民出版社一九六二年版第145—146页）——第129页

　　〔191〕参见斯大林《论党的工作缺点和消灭托洛茨基两面派及其他两面派的办法》（《斯大林文选》，人民出版社一九六二年版第139一140页）。——第131页

　　〔192〕参见斯大林《论党的工作缺点和消灭托洛茨基两面派及其他两面派的办法》（《斯大林文选》，人民出版社一九六二年版第141页）。——第131页

　　〔193〕一九四○年六月，法西斯德国侵占巴黎后，以当时法国总理贝当为首的卖国分子向德国投降，七月一日将政府迁至维希，组织维希傀儡政府。——第133页

　　〔194〕一九四一年六月二十二日，法国片面撕毁苏德互不侵犯条约，未经宣战向苏联发动突然进攻。苏联人民在斯大林为首的党和政府领导下，开始了卫国战争。——第133、202页

　　〔195〕一九四一年十二月七日晨，日本未经宣战，以海空军突然袭击美国在太平洋地区的主要海空军基地珍珠港，使美国太平洋舰队遭到惨重损失。十二月八日，美英对日、德国对美正式宣战，太平洋战争从此开始。十二月十日，日本空军又在新加坡附近海面袭击英国远东舰队，使英舰队遭到重大损失。——第133、202页

　　〔196〕西班牙内战期间（一九三六至一九三九年），在共和国后方有许多叛徒、间谍和破坏分子进行反革命活动。一九三六年十月，西班牙叛军和德、意法西斯联合进攻西班牙共和国首都马德里时，叛军将领摩拉在广播中扬言，他的四个纵队正在进攻马德里，而第五纵队已在首都等待着。后来，第五纵队就成了帝国主义在别国进行颠覆、破坏活动时收买的叛徒和派入的间谍的通称。——第133页

　　〔197〕列宁格勒保卫战：一九四一年九月德国侵略军包围列宁格勒，苏联军民展开了英勇的列宁格勒保卫战，历时十六个月，消灭了德军及其仆从军二十五万人。一九四三年一月十八日苏军击破德军的包围封锁，列宁格勒解围。莫斯科保卫战，一九四一年九月至十一月间，德军集中七十多个师向莫斯科大举进攻。苏军以三个方面军的兵力和广大人民一起进行了顽强的防御，十二月六日转入反攻，到一九四二年一月共歼灭德军五十个师，粉碎了希特勒的“闪击战”计划。斯大林格勒保卫战，一九四二年七月十七日德国侵略军开始猛攻斯大林格勒，先后使用一百五十万以上的兵力，企图占领该城，切断伏尔加河，控制高加索地区，北攻莫斯科。苏军先后以三个方面军的兵力同广大人民一起艰苦奋战，在顽强的防御战中消灭了大量敌人。十一月十九日转入反攻，二十三日包围了三十三万德军，一九四三年二月二日将其全部歼灭。这一战役是苏德战争的转折点，也是第二次世界大战的转折点。——第133页

　　〔198〕大西洋宪章，指美国总统罗斯福同英国首相丘吉尔一九四一年八月十四日在大西洋的纽芬兰海面会谈后发表的联合宣言。当时德、日法西斯的侵略已使英、美两国受到损失，中国、苏联和全世界人民的反法西斯斗争空前高涨。英、美两国在宣言中宣称：两国不追求领土或其他方面的扩张；尊重各民族自由选择其政府形式的权利；赞同摧毁德国纳粹暴政和解除侵略国家的武装等。——第133页

　　〔199〕苏英同盟，全称《苏英战时反对希特勒德国及其欧洲与国并在战后合作互助同盟条约》，一九四二年五月二十六日在伦敦签订。主要内容是：苏、英两国在反对德国法西斯战争中结成互助同盟；战后采取一切措施防止德国重新侵略；双方决不参加反对另一方的任何同盟或集团。第二次世界大战后，由于英国参加了北大西洋集团和北大西洋集团成员国同德意志联邦共和国签订了巴黎协定，一九五五年五月七日苏联宣布废除这个同盟条约。苏美协定，亦称苏美贸易协定。一九三七年八月四日苏、美以互换照会的办法签订，并规定每年展延有效期。一九四二年苏、美双方达成协议，将协定的效力一直维持到它被更广泛的协定所代替或一方声明希望停止生效时为止。根据这个协定，两国在有关货物输出输入各项问题上享有无条件的和无限制的最惠国待遇。第二次世界大战后，美国在一九五一年六月二十二日宣布一九三七年的协定无效，同年十二月二十三日中断美、苏原来的互惠贸易关系。——第133页

　　〔200〕二十六国公约，指一九四二年一月一日，中国、苏联、美国、英国、波兰、印度和加拿大等二十六个参加对德、意、日轴心国作战的国家在华盛顿发表的共同宣言。到一九四五年三月一日止，法国、墨西哥和菲律宾等二十一国陆续表示赞同这一宣言。这一宣言后称《联合国宣言》。宣言的主要内容：（一）签字国保证使用全部军事和经济资源，共同对抗德、意、日法西斯的侵略；（二）各国保证不同敌国单独缔结停战协定或和约。——第133页

　　〔201〕一九四○年六月，法西斯德国侵占巴黎，法国贝当政府投降后，法国共产党在国内领导人民进行反法西斯斗争，从组织怠工、罢工到建立游击队进行武装斗争，至一九四四年六月，游击队已发展到二十多万人。戴高乐将军在国外组织自由法国运动，建立民族解放委员会。一九四三年一月法国共产党和民族解放委员会签订合作协定，六月三日统一的法兰西民族解放委员会在阿尔及尔宣告成立，法共议员密台尔、法戎以个人名义参加。一九四四年四月一日民族解放委员会第二次改组，法国共产党正式派出代表参加。——第134页

　　〔202〕自由德国民族委员会是第二次世界大战期间旅居国外的德国人建立的反法西斯组织。一九四三年七月在莫斯科召开第一次代表大会，参加的有德国反法西斯的国会议员、省议会议员、科学家、工程师和德国战俘营代表，正式成立自由德国民族委员会，通过了宣言，选举出著名作家怀尔纳特为委员会主席。——第134页

　　〔203〕冈野进，即野坂参三（一八九二——）。一九四○年三月到延安，组织和领导了“日本在华士兵反战同盟”。抗日战争胜利后回国，任日共主席、名誉主席。——第134页

　　〔204〕墨索里尼（一八八三——一九四五），意大利法西斯独裁者，法西斯主义的创始人。一九二二年用暴力夺取政权，建立了法西斯专政。一九三九年同德国缔结政治、军事同盟，次年追随德国参加第二次世界大战。一九四三年七月，由于军事失败和国内反法西斯运动的高涨，墨索里尼的独裁政权垮台；墨逃到意大利北部，充当德占区傀儡政权头子。一九四五年四月二十八日，被意大利游击队处死。——第134页

　　〔205〕一九四一年三月起，华北的日军和汉奸推行所谓“治安强化运动”，对解放区进行“扫荡”，在游击区实行“大检举”，在敌占区实行保甲制度，调查户口，扩组伪军，以镇压抗日力量。——第135页

　　〔206〕吴开先，曾任国民党中央组织部副部长，后投降日本侵略者，一九四三年五月带着日本招降蒋介石的条件，由南京到重庆，蒋介石曾亲自接见。——第135页

　　〔207〕一九四三年八月一日，日本大本营报道部部长谷萩那华雄发表对蒋介石的诱降谈话，内容是：倘同意停止抵抗，参加反美、英之战线，则日军将由中国撤退，承认中国之独立。——第135页

　　〔208〕解放区的抗日民主政权，根据中国共产党的抗日民族统一战线政策，在人员的分配上，规定共产党员占三分之一，非党的左派进步分子占三分之一，中间派占三分之一。简称为“三三制”。——第136、154、161、253页

　　〔209〕一九四一年一月，取得国民党当局同意由皖南北移的新四军，在安徽泾县茂林镇遭到国民党军队发动的突然围攻。经过八昼夜的浴血战斗，叶挺军长负伤被俘，九千多名指战员大部英勇牺牲。这就是震惊中外的皖南事变。蒋介石在一月十七日宣布新四军“叛乱”，取消新四军番号，将叶挺军长交“军法审判”。二十日中共中央革命军事委员会发布命令，任命陈毅为新四军代理军长，张云逸为副军长，刘少奇为政治委员，赖传珠为参谋长，邓子恢为政治部主任。二十二日中共中央革命军事委员会发言人发表谈话，针锋相对地驳斥了国民党反动派对新四军的诬蔑，提出取消一月十七日的反动命令、惩办皖南事变祸首等十二条严正要求。——第137、175、201、219、235页

　　〔210〕一九四三年六月，在蒋介石发动第三次反共高潮期间，胡宗南从担任河防的三个军中调出两个军，准备闪击陕甘宁边区，发动内战。延安人民举行大会，动员保卫边区。毛泽东写了《质问国民党》一文，历数蒋介石消极抗日、积极反共的罪行，揭露其进攻边区的阴谋。蒋介石被迫停止对陕甘宁边区的进攻。——第137页

　　〔211〕一九三七年五月二日至十四日在延安举行中国共产党苏区代表大会，毛泽东在会上作了题为《中国共产党在抗日时期的任务》的报告。报告中指出：“一九二四年至一九二七年的经验，表明了当资产阶级追随着无产阶级的政治领导的时候，革命是如何地前进了；及至无产阶级（由共产党负责）在政治上变成了资产阶级的尾巴的时候，革命又是如何地遭到失败。这种历史不应当重复了。”（《毛泽东选集》第1卷第241页）——第143页

　　〔212〕见《在共产国际第七次代表大会上》，原文是：“法西斯是资本家对劳动人民大众的最猖狂的进攻；法西斯是肆无忌惮的沙文主义和侵略战争（旧的译文是：‘法西斯主义——就是横行无忌的民族侵略主义和强盗的战争’。本文引用的是旧译文——编者注）；法西斯是疯狂的反动和反革命；法西斯主义是工人阶级和全体劳动人民的最恶毒的敌人！”（《季米特洛夫选集》，人民出版社一九五三年版第45—46页）——第143页

　　〔213〕我国边疆的少数民族在历史上往往被称为“藩部”，历代都有职官专管或兼管民族事务，例如清代专设了理藩院，掌管蒙古、西藏、新疆等地的少数民族事务。历代封建统治阶级主要是用镇压和笼络的两手政策对待边疆各少数民族。蒋介石在民族问题上继承了这种政策，甚至否定少数民族的存在，把各少数民族称之为汉族的大小宗支。——第144页

　　〔214〕见斯大林《在第十七次党代表大会上关于联共（布）中央工作的总结报告》，《列宁主义问题》，人民出版社一九五三年版第566页。——第144页

　　〔215〕见古文《尚书二大禹谟》。这段引文是书中舜教导禹的几句话。意思是：民心很危险，危则难安；道心很幽微，幽则难明；要专心致志地研究，以掌握其中的奥妙。——第145页

　　〔216〕见孙中山《建国方略》，《孙中山选集》，人民出版社版第105页。——第145页

　　〔217〕见《礼记·中庸》。原文是：“诚者，物之终始，不诚无物。”

　　《中庸》把“诚”说成是人人具有的天赋道德，同时又是客观事物的总规律。有了诚，才会有万物的存在；如果不诚，就没有客观事物。这是一种主观唯心主义的观点。文中的“无物不诚”、“有物不诚”是引申“不诚无物”一语，用唯物主义观点对蒋介石进行揭露与讽刺。蒋介石否认共产党必然存在的客观事实，妄想消灭共产党，所以说他是“无物不减”。人民革命力量迫使蒋介石不得不公开承认了边区存在的客观事实，但他仍然想一手取消，所以说他是“有物不诚”。——第145页

　　〔218〕庐山谈话会，指一九三七年七月国民党政府在庐山召开的“各党派及无党派人士”座谈会。——第146、194页

　　〔219〕蒋介石鼓吹的力行哲学，是割裂知行关系，孤立强调“行”的作用的主观唯心主义愚民哲学，是极端反动的法西斯主义哲学。——第146页

　　〔220〕连坐法是旧社会统治阶级残酷镇压人民的一种法律。它规定一人有罪，家属、亲友甚至邻居也连带给予治罪。《史记·商君列传》：“令民为什伍，而相牧司连坐”。蒋介石为巩固法西斯统治，一九三二、一九三三年分别在地方和军队中推行连坐法。——第146页

　　〔221〕希特勒（一八八九——一九四五），德国法西斯头子。一九一九年参加德意志工人党（次年改为国社党），其后成为该党党魁。一九三三年在德国垄断资产阶级支持下出任总理，次年总统兴登堡死后自称国家元首，实行法西斯统治，积极扩军备战。一九三九年九月入侵波兰，挑起第二次世界大战。一九四一年六月大举进攻苏联。一九四五年苏军解放柏林时自杀。——第146页

　　〔222〕四维八德是封建统治阶级提倡的道德规范。四维，指礼、义、廉、耻；八德，指忠、孝、仁、爱、信、义、和、平。——第146页

　　〔223〕《皇朝经世文编》，清贺长龄编，共一百二十卷，选辑清初至道光以前的官方文书、论著、奏疏、书札等，包括学术、治体、吏政、户政、礼政、兵政、刑政、工政八部分。陈弘谋，一作宏谋，清雍正进士，东阁大学士兼工部尚书。所编《五种遗规》，采辑历代有关修身、治家、处世、居官、教育等方面的著作、言论和事迹，分为五类，即《养正遗规》、《训俗遗规》、《教女遗规》、《从政遗规》和《在官法戒录》。——第147页

　　〔224〕曾，即曾国藩（一八一一——一八七二），晚清官僚，镇压太平天国革命运动的主将。一八五二年为镇压太平军，开始在湖南招募、训练地主武装——团练。因士兵和将领大多用其家乡湘乡人，故名湘军。湘军自上而下有严密的封建隶属关系，全军只服从曾国藩一人统领。中国近代军阀军队从湘军开始，以后袁世凯、段祺瑞直到蒋介石，都继承了这个传统。

　　胡，即胡林翼（一八一二——一八六一），在贵州任知府期间镇压苗民起义，一八五四年后到湖北、江苏等地镇压太平军，是湘军中仅次于曾国藩的首领。

　　左，即左宗棠（一八一二——一八八五），一八六○年任湖南巡抚的幕僚时，招募人马组成左系湘军，又叫楚军，在江西、安徽镇压太平军。一八六六年后又连续镇压捻军和西北回民起义，成为著名的湘军军阀。

　　李，即李鸿章（一八二三——一九○一），淮军军阀。一八六一年受曾国藩之命，回安徽原籍将淮南团练按湘军方式加以改编，组成淮军，参与镇压太平天国运动。——第148页

　　〔225〕拿破仑·波拿巴（一七六九——一八二一），即拿破仑第一，法国资产阶级政治家和军事家。一七九九年在法国大资产阶级支持下雾月十八日（十一月九日）政变，自任第一执政。一八四年称帝，建立法兰西第一帝国。——第148页

　　〔226〕“三二○”事变，参见本书《关于一九二四至二六年党对国民党的关系》一文（第120—121页）。——第148、159、208页

　　〔227〕“宁”，指南京政府；“汉”，指武汉政府。一九二七年蒋介石发动“四一二”反革命政变后，武汉国民政府迫于革命群众运动的声势，在共产党和国民党左派人士的推动下，采取了“联共反蒋”的态度。四月十七日武汉国民党中央执行委员会决议，开除蒋介石党籍；同日武汉国民政府发布命令，罢免蒋介石的国民革命军总司令等全部职务，并申讨蒋介石。四月十八日蒋介石在南京另组国民政府，自任主席，并通过“清党”等反革命决议案，通缉共产党员，宣布武汉国民政府及在武汉的国民党中央一切决议为非法。这时出现的南京与武汉两个国民政府对峙的局面，称为“宁汉分家”。同年五月汪精卫为首的武汉国民政府逐步公开走上反共的道路。七月十五日汪精卫举行“分共”会义，正式决定与共产党分裂，公开屠杀共产党员。从此“宁汉合作”，蒋汪反革命合流。——第148、208页

　　〔228〕《礼运》大同篇，指《礼记·礼运》篇中对于“大同”之治的论述。“大同”是儒家宣传的理想社会，是小生产者的空想。——第150页

　　〔229〕张宗昌（一八八一——一九三二），一九二四年到一九二七年统治山东的军阀。早年在上海陈其美部下当团长。一九一三年投靠直系军阀，后投靠奉系军阀。——第151页

　　〔230〕陶成章（一八七八——一九一二），一九○四年在上海参加组织光复会，是该会领导人之一。一九○六年参加同盟会。一九一一年十月武昌起义后，发动上海、浙江等地的反清起义。一九一二年一月被陈其美、蒋介石暗杀于上海。——第151页

　　〔231〕《曾胡治兵语录》是蔡锷编辑的曾国藩、胡林翼关于治兵言论的小册子。——第151页

　　〔232〕西安事变，参见本书《关于西安事变的三个电报》一文的题解。——第152、191、247、252页

　　〔233〕一九三八年三月国民党在汉口召开的临时全国代表大会上通过了抗战建国纲领，内容包括抗战的军事、政治、经济、外交等方面的政策。这是一个两面性的纲领。一方面被迫对人民作了某些形式上的让步，如规定组织国民参政机关，许诺给予人民言论、出版、集会、结社自由；同时又继续坚持国民党一党专政。由于蒋介石推行消极抗战、积极反共的政策，纲领中对人民的某些形式上的让步也成为一纸空文。——第152、252页

　　〔234〕一九三五年十一月国民党政府规定由官僚资本控制的中央、中国、交通银行（后来又加上农民银行）所发行的纸币为法定的全国统一流通的货币，称为法币。——第153页

　　〔235〕一九二六年“三二○”事件后，蒋介石为加强对黄埔军校学生的控制，四月解散了青年军人联合会（同时也取消了孙文主义学会），七月成立黄埔军校同学会，自任会长。一九二七年“四一二”反革命政变后，这个同学会成为蒋介石笼络和控制嫡系军事骨于的组织。——第155页

　　〔236〕康泽（一九○六——一九六七），原国民党特务头子。曾任国民党军委会别动队总队长、三青团中央团部组织处长等职。一九四七年任国民党军第十五绥靖区司令长官，一九四八年七月在襄樊战役中被我军俘虏。一九六三年被特赦后，任中国人民政协全国委员会“文史资料研究委员会”专员。——第155页

　　〔237〕共产国际执行委员会第七次扩大会议一九二六年十一月二十二日至十二月十六日在莫斯科举行。会上讨论了中国问题，并作出了决议。决议指出：“中国革命在目前发展阶段上是资产阶级民主主义的性质”。——第158页

　　〔238〕中国共产党第二次全国代表大会，一九二二年七月在上海召开。大会宣言明确指出：“各种事实证明，加给中国人民（无论是资产阶级、工人或农人）最大的痛苦是资本帝国主义和军阀官僚的封建势力，因此反对那两种势力的民主主义的革命运动是极有意义的。”——第158页

　　〔239〕俄国一九○五革命，指一九○五——一九○七年俄国第一次资产阶级民主革命。这次革命的任务是推翻沙皇专制制度，建立民主共和国。当时，在要不要彻底推翻沙皇制度和革命的领导权问题上，各党派之间发生了重大分歧。一贯支持沙皇政府内政外交政策的立宪民主党，欺骗工农，散布不经过革命和起义就可以实现人民所需要的制度的幻想；社会革命党和社会民主党内的孟什维克，主张把领导权让给资产阶级，反对武装起义，对沙皇政府实行妥协，以列宁为首的布尔什维克坚决反对孟什维克和社会革命党的错误路线，揭露立宪民主党维护沙皇制度的反革命实质，指出只有无产阶级的领导才能保证革命的彻底胜利，并号召和领导无产阶级举行武装起义。这次革命由于阶级力量对比悬殊和没有形成巩固的工农联盟，遭到了失败，但它成为十月革命的预演。——第158页

　　〔240〕莫斯科中山大学，全称为“孙中山中国劳动者大学”，一九二五年成立于莫斯科，一九二九年改称中国劳动者共产主义大学，一九三○年秋停办。——第158页

　　〔241〕共产国际执行委员会第九次扩大会议，一九二八年二月九日至二十五日在莫斯科举行。会上讨论了中国问题，并作了决议。——第158页

　　〔242〕二月革命，指俄国的第二次资产阶级民主革命。一九一七年二月（俄历）彼得格勒的工人举行反沙皇制度的罢工。在布尔什维克领导下，罢工很快转为起义，首都卫戍部队也参加了起义，全国各地纷纷响应，推翻了沙皇专制制度。革命后，成立了工兵代表苏维埃，资产阶级则在小资产阶级妥协派支持下成立临时政府，形成两个政权并存的局面。因此，布尔什维克又领导人民为准备和实现社会主义革命而斗争。——第158页

　　〔243〕共产国际执行委员会第八次全会，一九二七年五月十八日至三十日在莫斯科举行。由于蒋介石背叛革命，屠杀共产党人，全会专门讨论了中国问题，并通过了《中国问题》的决议。——第159页

　　〔244〕罗易，曾是印度共产党领导人之一和共产国际执行委员会委员，一九二七年作为共产国际代表来过中国。后来成为叛徒，一九二九年被开除出印度共产党和共产国际。

　　多里欧当时是共产国际执行委员会的候补委员，一九二七年曾来过中国。——第159页

　　〔245〕罗米那兹（一八九七——一九三五），苏联人。一九二七年作为共产国际国际代表来中国。武汉“七一五”政变后，参加中共“八七”会议的领导工作，提出中国革命是“不断革命”，认为不经任何阶段一直发展下去就是社会主义革命。共产国际执行委员会第九次扩大会议批判了这种错误观点。——第160页

　　〔246〕第一次国内革命战争失败后，中国共产党为了反击蒋介石、汪精卫为代表的反革命势力，一九二七年八月一日，在周恩来、贺龙、叶挺、朱德、刘伯承等直接领导下，在南昌发动武装起义，占领了南昌。这次起义，打响了中国人民武装反对国民党反动派的第一枪。参加起义的部队是贺龙率领的国民革命军第二十军，叶挺率领的国民革命军第十一军和朱德率领的国民革命军第三军军官教导团等部三万余人。起义部队八月五日撤离了南昌南下广东。九月底在潮汕一带遇到优势敌军的围攻而失败。保存下来的起义部队，一部分在彭湃、颜昌颐等率领下，同海陆丰起义和广州起义撤出的武装力量相会合，在东江地区继续活动，另一部分在朱德、陈毅等率领下，一九二八年四月到达井冈山和毛泽东领导的工农革命武装会合，合编为工农红军第四军。——第160、246页

　　〔247〕一九二七年十一月中旬中共中央临时政治局在上海召开扩大会议，会议通过了《中国现状与共产党的任务决议案》、《关于第六次全国党代表大会的决议》等。会议否认革命处于低潮，认为“现时全中国的状况是直接革命形势”，“敌人的屠杀进攻，反而证明革命潮流之高涨”，规定党的任务是“努力鼓动各地城乡革命的高潮，创造总暴动的局面”。会议还认为“中国革命的进程，必然要彻底解决民权主义任务而急转直下的进于社会主义的道路”。——第160页

　　〔248〕十大要求，指一九二八年中国共产党第六次全国代表大会提出的十条政纲：一、推翻帝国主义的统治；二、没收外国资本的企业和银行；三、统一中国，承认民族自决权；四、推翻军阀国民党的政府；五、建立工农兵代表会议（苏维埃）政府；六、实行八小时工作制，增加工资、失业救济与社会保险等；七、没收地主阶级的一切土地，耕地归农；八、改善兵士生活，给兵士以土地和工作；九、取消一切苛捐杂税，实行统一的累进税；十、联合世界无产阶级和苏联。——第161页

　　〔249〕参见列宁《共产国际第二次代表大会。民族和殖民地委员会的报告》。文中说：“被剥削者苏维埃这种形式不仅适用于资本主义国家，也适用于还保有资本主义前的关系的国家，而且必须指出，在落后国家和殖民地，……只要条件允许，就应该立即设法建立劳动者苏维埃。”（《列宁全集》，第31卷第213页）——第161页

　　〔250〕两权并立是资产阶级创立的一种政治制度，即立法权和行政权分立的议会制。议会行使立法权，政府行使行政权，两者互相制约。——第161页

　　〔251〕南四行，指当时的中国银行（总经理张嘉珑）、上海商业储蓄银行（总经理陈光甫）、浙江兴业银行（总经理徐寄底）、浙江实业银行（总经理李铭）。——第163页

　　〔252〕这两次屠杀，参见注〔9〕、〔10〕。——第163页

　　〔253〕一九二七年“七一五”反革命政变后，邓演达等国民党左派分子在上海组织中国国民党临时行动委员会，即第三党。他们反对蒋介石控制的国民党，同时也不赞成中国共产党。一九三五年第三党改名为中华民族解放行动委员会，响应中国共产党关于各党各派合作抗日、共赴国难的号召，积极参加抗日活动。一九四一年参加发起中国民主政团同盟。一九四七年改称农工民主党。一九四九年参加中国人民政治协商会议第一届全体会议。中华人民共和国成立后，农工民主党拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。——第163页

　　〔254〕史量才（一八七八——一九三四），一九一三年起任《申报》总经理。蒋介石统治初期采取拥蒋立场，“九一八”以后政治态度逐步改变。上海“一二八”抗战时，曾捐款支持抗日，并任抗日群众组织上海地方协会会长，后来又积极支持中国民权保障同盟。一九三四年十一月，被蒋介石特务暗杀。

　　杨杏佛（一八八三——一九三三），一九二五年随孙中山北上，任秘书。后任东南大学工学院院长、国民党政府中央研究院总干事等职。一九三二年同宋庆龄、蔡元培、鲁迅等在上海发起组织中国民权保障同盟，任总干事，进行反蒋抗日的进步活动。一九三三年六月十八日被蒋介石特务暗杀。——第164页

　　〔255〕孙科，一九二七年任武汉国民政府常务委员。——第165页

　　〔256〕唐生智（一八八九——一九七○），当时任国民革命军第八军军长、第四集团军总司令、湖南省主席、国民党中央执行委员等职。中华人民共和国成立后，任全国人民代表大会常务委员会委员等职。——第165、211页

　　〔257〕机器工会，原名“广东机器研究公会”，后改名为“广东机器工会”，是国民党右派利用的工具。一九二四年国共合作后，反对和破坏共产党领导的工人运动。一九二六年一月公开发表宣言反对共产党。一九二七年“四一五”反革命政变时，协助反革命政权搜捕共产党员和进步群众。同年十二月参与镇压广州起义。——第165页

　　〔258〕吴铁城（一八八八——一九六三），一九二四年任广东革命政府东路讨贼军第一路军司令、广东警卫军司令、国民党广州市党部执行委员，一九二六年任国民党候补中央委员、国民革命军第六军第十七师师长。——第165页

　　〔259〕马超骏（一八八六——一九七七），第一次国内革命战争期间是国民党控制的黄色工会头子。——第165页

　　〔260〕胡毅生，胡汉民堂弟。一九二五年在广州参加创办国民党右派报纸《国民新闻日报》，积极反共。廖仲恺被刺后，潜逃香港。——第165页

　　〔261〕参见孙中山《致蒋介石手札》（见《孙中山选集》第876页）。精卫，即汪精卫；展堂，即胡汉民。——第166页

　　〔262〕瞿秋白（一八九九——一九三五），一九二二年参加中国共产党，是党的早期主要领导人之一。曾主编中共中央机关刊物《新青年》、《向导》。在中国共产党第四、五、六次全国代表大会上均当选为中央委员。一九二七年国民党叛变后，主持了八月七日的中共中央紧急会议，这次会议结束了陈独秀右倾机会主义在党内的统治。在这次会议上当选为中央政治局委员和中央书记。一九二七年冬至一九二八年春主持中央工作时，犯过“左”倾盲动主义错误。一九二八年当选为共产国际执行委员会委员和主席团委员。一九三○年九月主持召集的六届三中全会，纠正了李立三“左”倾机会主义路线。在一九三一年一月六届四中全会上，遭到王明等“左”的教条主义宗派主义分子的打击，被排斥于党的中央领导机关之外。此后，在上海同鲁迅合作从事革命文化运动。一九三四年到江西革命根据地，担任中华苏维埃共和国临时中央政府人民教育委员。同年十月红军主力长征后，被留在江西革命根据地坚持斗争。一九三五年二月在福建游击区被国民党军逮捕，六月十八日在福建长汀就义。——第166页

　　〔263〕汪陈宣言，指一九二七年四月五日汪精卫和陈独秀在上海发表的联合宣言。这个宣言极力掩盖国民党右派的反革命活动，声称“国民党……决无驱逐友党摧残工会之事”，同时又表示“中国共产党无论如何错误，也不至于主张打倒自己的友党……国民党”。宣言使工人阶级解除思想上的武装，放松对蒋介石背叛革命的警惕。——第166页

　　〔264〕吴稚晖（一八六六——一九五三），当时任国民党中央监察委员，一贯支持蒋介石的反革命活动，坚决反苏反共。——第166、228页

　　〔265〕中共中央在一九二七年八月七日紧急会议上决定，利用当年的秋收时节在湘、鄂、粤、赣四省举行农民武装暴动。会后，在各地党组织领导下，举行了多次农民起义。参见注〔18〕、〔275〕。——第168页

　　〔266〕一九二七年十二月十一日至十三日，在张太雷、苏兆征、叶挺、挥代英、叶剑英、杨殷等领导下，以国民革命军第四军教导团和广州工人赤卫队为主力在广州发动起义，起义部队曾占据市内绝大部分地区，一度成立了中国共产党领导的人民政权——广州苏维埃政府。起义失败后，起义武装中的一部分与彭湃领导的东江农民起义武装会合；一部分转移到广西，以后参加了左、右江的农民武装起义；一部分参加朱德、陈毅率领的南昌起义部队转战到了井冈山。——第168、212页

　　〔267〕布哈林（一八八八——一九三八），当时任共产国际书记处书记。——第168页

　　〔268〕十月革命前夕，俄国社会民主工党中央召开扩大会议，选出领导起义的党总部。会上中央委员季诺维也夫和加米涅夫反对起义。他们在自己的意见遭到否决后，竟在孟什维克的《新生活报》上发表声明，宣称反对布尔什维克准备起义的冒险行动，公开向敌人泄露了党中央关于在最近期间举行起义的决定。——第169页

　　〔269〕谭平山（一八八六——一九五六），一九二○年组织广州共产主义小组，在中国共产党的第三、四、五次全国代表大会上都当选为中央委员。第一次国内革命战争期间，历任中国国民党中央执行委员会常务委员、中央组织部长、农民部长和武汉国民政府委员等职。曾参加南昌起义，任革命委员会主席团成员。以后脱离中国共产党，参加组织中国国民党临时行动委员会（即第三党）。抗日战争时期，反对蒋介石的卖国独裁政策。一九四五年发起组织三民主义同志联合会，一九四八年参加组织中国国民党革命委员会。中华人民共和国成立后，任中央人民政府委员等职。——第169页

　　〔270〕一九二七年七月武汉中央军事政治学校被国民党军第二方面军总指挥张发奎解散，军校学生被改编为第二方面军军官教导团。——第169页

　　〔271〕张作霖（一八七五——一九二八），北洋奉系军阀首领。曾在日本帝国主义支持下长期统治东北。一九二四年打败直系军阀后，他的势力伸入关内。一九二六年又联合直系军阀吴佩军入据北京。后来和日本帝国主义发生利害冲突，一九二八年六月在退回东北的路上，被日本关东军预埋炸弹炸死。——第170页

　　〔272〕伍廷康（一八九三——一九五三），原名魏金斯基，苏联人，共产国际派驻中国的代表。一九二○年春来中国了解情况，并帮助建立中国共产党。一九二六至一九二七年作为共产国际东方部的代表第二次来中国。——第170页

　　〔273〕一九二七年五月二十一日，蒋介石、汪精卫唆使湖南的国民党反革命军官许克群、何键等，在长沙围攻湖南省工会、省农民协会等革命群众组织，捕杀共产党人及革命的工农群众。这次事变是汪精卫为首的武汉国民党反革命派和蒋介石为首的南京国民党反革命派公开合流的前奏。当时的文电习惯以通行的诗韵目代替日期，以诗韵第二十一前的“马”字来代替二十一日，所以这次事变又称为“马日事变”。——第170页

　　〔274〕顾孟余（一八八九——一九七二），当时任武汉国民政府教育部长。——第170页

　　〔275〕指湖南江西边界地区修水、萍乡、醴陵、平江、浏阳等县的人民武装在一九二七年九月举行的起义。后来这次起义的工农武装和原武汉国民政府警卫团组成工农革命军第一军第一师，转战到井冈山，建立了农村革命根据地。——第172页

　　〔276〕一九二七年九月初，国民党广州政治分会主席李济深为防贺龙、叶挺部入粤，让国民党广西省政府主席兼广州政治分会委员、军事委员会委员黄绍竑率军驻守北江。当时统治广州的汪精卫，担心黄绍竑的势力伸展到广东，派张发奎率第四军回粤挡截黄的军队。——第174页

　　〔277〕东方大学，全称是“东方劳动者共产主义大学”。一九二一年创办于莫斯科。它的任务是为苏联东方各共和国培养干部和为帝国主义殖民地、附属国培养革命干部。三十年代末停办。——第175页

　　〔278〕斯托雷平的土地政策，指一九○六年由沙皇政府大臣斯托雷平颁布的土地法令。主要内容是：允许农民退出村社，可以把自己的份地变成私产。这个法令的实行，使村社瓦解，富农可以用贱价收买土地，从而地位加强，少地农民和贫民的状况恶化，农民的分化加剧。——第176页

　　〔279〕恽代英（一八九五——一九三一），一九二一年参加中国共产党。一九二三年任中国社会主义青年团中央宣传部长，创办《中国青年》。一九二六年在国民党第二次全国代表大会上当选为中央执行委员。同年三月任黄埔军官学校政治总教官。在党的第五次全国代表大会和六届二中全会上均当选为中央委员。一九三○年五月六日在上海被国民党逮捕，一九三一年四月二十九日在南京就义。——第179、333页

　　〔280〕陶行知（一八九一——一九四六），人民教育家，爱国民主人士。早年留学美国。一九一六年回国，先后任南京高等师范学校教务主任、中华教育改进社总干事，发起组织中华平民教育促进会，在南京、上海郊区创办晓庄学校和山海工学团，推行平民教育和乡村教育运动。一九三五年“一二九”运动后，参加发起组织上海文化界抗日救国联合会、上海各界抗日救国联合会。抗日战争期间，积极参加抗日斗争和国民党统治区反独裁反内战的政治活动，并在重庆创办育才学校和社会大学。一九四五年春参加中国民主同盟，被选为中央常务委员兼教育委员会主任委员。抗战胜利后在国民党统治区继续从事民主运动。——第179、238、263、333页

　　〔281〕职工国际，又称赤色工会国际。一九二一年成立，一九三七年底解散。——第182页

　　〔282〕李明瑞（一八九六——一九三一），一九二九年任国民党广西绥靖公署主任、军事特派员。同年十二月和一九三○年二月，他率领所属部队在邓小平、张云逸等领导下相继举行右江、左江起义，先后成立红七军、红八军，李任两军总指挥。一九三○年二月参加中国共产党。一九三一年率红七军转战到达中央苏区，同年牺牲。——第183页

　　〔283〕一九三一年十二月十四日国民党第二十六路军在参谋长赵博生（共产党员）、七十三旅旅长董振堂等领导下，在江西宁都县举行武装起义。起义部队编为红军第五军团。——第183页

　　〔284〕沈泽民（一九○二——一九三三），中共早期党员。曾在我党领导的上海大学社会科学系任教。一九三一年在党的六届四中全会上被选为中央委员，任中央宣传部长。——第184页

　　〔285〕向忠发，一九二八年在党的第六次全国代表大会上当选为总书记。一九三一年六月二十二日被捕叛变，二十四日被国民党枪杀。——第184页

　　〔286〕任弼时（一九○四——一九五○），一九二二年参加中国共产党。当时是中共中央政治局委员，共青团中央总书记。——第185页

　　〔287〕李富春，一九二八年任中共江苏省委宣传部长、代理书记、上海法南区委书记等职。——第185页

　　〔288〕关向应（一九○二——一九四六），一九二五年参加中国共产党。当时任共青团中央组织部长。在党的第六、七次全国代表大会上当选为中央委员。——第186页

　　〔289〕文委，指中共中央南方局文化工作委员会。——第188页

　　〔290〕《新华日报》，是中国共产党在国民党统治区公开出版的报纸。一九三八年一月十一日在汉口创刊，同年十月二十五日迁到重庆继续出版。一九四七年二月二十八日被国民党反动派强迫停刊。——第188、200页

　　〔291〕延安文教大会，即一九四四年十月三十日在延安召开的陕甘宁边区文教工作者会议。——第188页

　　〔292〕察北同盟军，即一九三三年五月冯玉祥和中国共产党合作在察哈尔省组织的民众抗日同盟军。主要领导人还有吉鸿昌（共产党员）、方振武等。同盟军在张北、沽源等地与日本侵略军进行了激烈战斗，把日伪军完全逐出察哈尔省境。由于蒋介石和日本侵略军的双重压迫，同盟军的抗战活动于同年十月失败。——第191页

　　〔293〕福建人民政府，是国民党内同蒋介石分裂的李济深、陈铭枢、蒋光鼐、蔡廷锴等人一九三三年十一月在福州成立的“中华共和国人民革命政府”。这年十月，蒋光鼐、蔡廷锴领导的十九路军同红军签订了抗日反蒋协定。福建人民政府成立后又同中华苏维埃共和国临时中央政府和工农红军签订了停战协定。在蒋介石的军事压力下，福建人民政府在一九三四年一月间失败。——第191页

　　〔294〕这封信指一九三六年八月二十五日《中国共产党致中国国民党书》。信中对国民党的反动统治和国民党五届二中全会决定的反动方针，作了义正词严的批判，同时申明了中国共产党关于建立抗日民族统一战线和准备重新实行国共合作的政策。——第192页

　　〔295〕中国共产党为了以实际行动促成全国抗日的实现，由工农红军第一军团和第十五军团组成中国人民红军抗日先锋军，在一九三六年二月二十日东渡黄河抗日，遭到了蒋介石、阎锡山的武力阻拦。中华苏维埃共和国临时中央政府和中国抗日红军革命军事委员会鉴于国难当前，应以实现全国抗战为根本，不愿和阻拦我抗日去路的国民党部队进行战斗，五月五日发表回师通电，将抗日东征军撤回黄河西岸。——第192、248页

　　〔296〕一九三五年十二月九日，北平学生数千人，在中国共产党领导下举行爱国示威游行，提出“停止内战，一致对外”、“打倒日本帝国主义”等口号。游行的学生遭到国民党政府镇压。次日，北平各校学生宣布总罢课。十六日，学生和市民一万余人，再度举行示威游行。这次爱国运动得到全国人民的热烈响应，形成了中国人民抗日救亡运动的新高潮。——第192、247页

　　〔297〕一九三六年十一月二十一日在宁夏环县山城堡，红军第一军团和第十五军团一部歼灭国民党军胡宗南部七十八师二三二旅全部和二三四旅两个团，这是第二次国内革命战争时期的最后一战。——第192页

　　〔298〕潘汉年，一九二五年参加中国共产党，一九三六年任我党代表与国民党进行谈判，同年秘密叛变，成为国民党潜藏在中国共产党内的奸细。一九四六至一九四八年在上海、香港等地我党情报、统战部门工作。中华人民共和国成立后任上海市副市长。一九五五年他的反革命面目被揭露。——第192、238页

　　〔299〕王以哲（一八九六——一九三七），东北军爱国将领。西安事变时任东北军第六十七军军长。由于张学良被蒋介石扣留，东北军内部在如何营救张的问题上发生分歧。部分少壮派军官主张用武力解决，王以哲等主张和平解决。在反动势力的挑动下，一九三七年二月二日王以哲被少壮派刺杀。——第193页

　　〔300〕这个报告，指毛泽东一九三七年五月三日所作题为《中国共产党在抗日时期的任务》的报告，见《毛泽东选集》第1卷。本文内所说毛泽东在五月代表会上作的报告，也是指这篇文章。——第193页

　　〔301〕这篇文章指《我们对修改国民大会法规的意见》一文。载一九三七年五月一日出版的《解放周刊》第1卷第2期。——第194页

　　〔302〕王世杰，当时任国民党中央宣传部长。——第194页

　　〔303〕林伯渠，从一九三六年到一九四八年任陕甘宁边区政府主席。抗日战争期间曾作为中国共产党代表与国民党进行谈判。——第195、253页

　　〔304〕一九三七年二月中旬至三月中旬，中国共产党代表周恩来、叶剑英在西安同国民党代表顾祝同、贺衷寒、张冲谈判，重申了中共中央致国民党五届三中全会电中提出的五项要求和四项保证。五项要求是：（一）停止一切内战，集中国力，一致对外；（二）保障言论、集会、结社之自由，释放一切政治犯；（三）召集各党各派各界各军的代表会议，集中全国人材，共同救国；（四）迅速完成对日抗战之一切准备工作；（五）改善人民生活。四项保证是：（一）在全国范围内停止推翻国民政府之武装暴动方针；（二）苏维埃政府改名为中华民国特区政府，红军改名为国民革命军（改编为一个军四个师，每师一万五千人），直接受南京中央政府与军事委员会之指导；（三）在特区政府区域内，实行普选的民主制度，（四）停止没收土地之政策，坚决执行抗日民族统一战线之共同纲领。在谈判中周恩来还提出恢复张学良的自由、复职授权等问题。因国民党的阻挠，谈判无结果，最后只达成了在西安设中共办事处的协议。  三月下旬周恩来到杭州同蒋介石谈判，就我党的五项要求和四项保证，提出具体实施方案，蒋介石则要求拟定民族统一战线纲领和确认他的领袖地位。双方商定谈判继续进行。  六月周恩来到庐山同蒋介石、宋子文谈判。在红军改编后的总指挥部、军队和边区的人事任命等问题上，双方争论很久未得解决。  七月十五日中共中央向国民党递送了《中国共产党为公布国共合作宣言》，十七日周恩来、博古、林伯渠同蒋介石、邵力子、张冲在庐山继续谈判。国民党承认陕甘宁边区，同意红军改编为八路军。“八一三”以后，蒋介石被迫在九月二十二日公布上述宣言并同意八路军设立总部。——第195页

　　〔305〕顾祝同（一八九二——），一九三七年任国民党军事委员会委员长重庆行营主任兼西安行营主任。皖南事变时任第三战区司令长官。——第195、201页

　　〔306〕一九三七年九十月间，八路军的三个师先后开抵山西抗日前线。九月二十五日，一一五师在平型关伏击日军，歼敌板垣师团一部约三千人。这是抗战开始后中国军队所取得的第一个大胜利。——第195页

　　〔307〕这个协定，指一九三七年八月苏联和国民党政府签订的中苏互不侵犯条约。——第197页

　　〔308〕徐向前（一九○二——），一九三九年被中共中央派往山东，任第一纵队司令、中共中央山东分局委员。——第198页

　　〔309〕鹿钟麟（一八八六———一九六六），当时任国民党政府河北省主席，在蒋介石的指令下曾和八路军进行摩擦。中华人民共和国成立后，任国防委员会委员等职。

　　张荫梧，当时任国民党河北省民军总指挥，不断制造摩擦，进攻八路军，一九三九年六月率部袭击河北深县八路军的后方机关，惨杀八路军干部和战士四百余人。——第198页

　　〔310〕朱怀冰，当时是国民党军第九十九军军长。一九四○年二三月间，蒋介石指令其纠合庞炳勋、张荫梧、侯如墉等部，三路进攻太行区域的八路军，被八路军彻底击败。

　　石友三，当时任国民党军第十军团总司令，在河北省南部联合日军进攻八路军，摧残抗日民主政权，屠杀共产党员和进步分子。——第200页

　　〔311〕高树勋（一八九八——一九七二），当时任国民党军新八军军长。曾奉蒋介石命令在河北一带同八路军摩擦。一九四五年十月三十日率领一个军和一个纵队在邯郸内战前线起义。一九四六年参加中国共产党。中华人民共和国成立后，任国防委员会委员等职。——第200页

　　〔312〕汤恩伯（一八九八——一九五九），当时任第一战区副司令长官、国民党军豫鲁苏皖边区总司令，驻守河南，积极推行反共反人民政策。——第200页

　　〔313〕一九三九年六月十二日，国民党第二十七集团军奉蒋介石的密令，派兵包围新四军设在湖南平江嘉义镇的通讯处，惨杀新四军参议涂正坤、八路军少校副官罗梓铭等六人，这就是平江惨案。——第200页

　　〔314〕一九三九年十一月十一、十二两日，河南确山、信阳、泌阳等县的国民党反动武装一千八百余人，围攻确山县竹沟镇新四军留守处，惨杀新四军伤员和他们的家属以及群众共二百余人，这就是竹沟惨案。——第200页

　　〔315〕一九三九年十二月，阎锡山在蒋介石的指使下集中六个军的兵力，向驻在山西西部的新军进攻。这次进攻被新军的反击所粉碎。同时，阎军又在山西东南部进攻新军，摧残阳城、晋城、长治、沁水等地抗日民主政府和人民团体，屠杀大批共产党员和进步分子。——第200页

　　〔316〕这次谈判是指一九四○年六月在重庆同国民党进行的谈判。——第200页

　　〔317〕参看《诗经·小雅·巷伯》：“取彼谮人，投畀豺虎；豺虎不食，投畀有北。”谮，进谗言，说人的坏话；畀，给予；北，指北方寒冷的不毛之地。——第201页

　　〔318〕“皓电”是蒋介石以国民党政府军事委员会正副参谋总长何应钦、白崇禧的名义，在一九四○年十月十九日（皓）发给八路军和新四军领导人的电报。“皓电”对坚持敌后抗战的八路军、新四军大肆污蔑，强迫命令黄河以南的抗日部队限期撤到黄河以北。为了顾全大局，中共中央以十八集团军总司令朱德、副总司令彭德怀和新四军军长叶挺、副军长项英的名义，在十一月九日（佳）电复何、白，除据实驳斥“皓电”的造谣以外，答应将皖南新四军部队移到长江以北。——第201页

　　〔319〕一九四○年七月十六日国民党提出所谓“中央提示案”，主要内容是：取消陕甘宁边区，代以陕北行政区公署，归陕西省政府领导；缩编八路军、新四军，并限制其防地。十月十九日蒋介石以何应钦、白崇禧的名义，在“皓电”中将所谓“中央提示案”以最后决定的形式向我党提出。——第201页

　　〔320〕两个军，指国民党军苏鲁战区副总司令韩德勤所属苏鲁皖游击总队总指挥李明扬的部队和李守维的八十九军。——第201页

　　〔321〕陈毅，一九三八年至一九四六年先后任新四军第一支队司令员、代理军长。——第201页

　　〔322〕日苏协定，指一九四一年四月十三日苏日双方代表在莫斯科签订的《苏日中立条约》。一九四五年四月五日苏联政府发表声明废除这一条约。——第202页

　　〔323〕新疆问题，指一九四二至一九四三年间，新疆独裁统治者盛世才为了投靠蒋介石，抛弃革命伪装，大肆逮捕和杀害在新疆工作的共产党员和进步人士的反革命事件。——第202页

　　〔324〕张群，从一九四○年起任国民党军成都行辕主任、四川省政府主席。——第202、266页

　　〔325〕董必武，抗日战争时期是中国共产党参加国民参政会的参政员之一。——第202页

　　〔326〕邓颖超（一九○四——），抗日战争时期是中国共产党参加国民参政会的参政员之一。——第202页

　　〔327〕张治中（一八九○——一九六九），抗日战争时期，历任国民党湖南省政府主席、军事委员会政治部部长、三民主义青年团书记长等职。一九四五年任国民党军西北行营主任兼新疆省主席，国共谈判的国民党代表。一九四六年代表国民党参加军事三人小组。一九四九年任国民党政府和谈代表团首席代表，同中国共产党代表团在北平进行谈判，双方代表拟定的国内和平协定为国民党政府拒绝后，张留住北平。中华人民共和国成立后，任全国人民代表大会常务委员会副委员长等职。——第203、257、319页

　　〔328〕一九四四年春，国民党统治区的民主党派和民主人士先后在重庆、成部、昆明、桂林、西安等地组织各种群众团体，利用报刊和集会讨论宪政，抨击国民党的法西斯专政，要求民主自由，主张开放政权，实行宪政，得到全国各界人士的广泛响应。——第204页

　　〔329〕赫尔利，美国共和党政客。一九L四四年九月以美国总统私人代表身份来华，十一月间曾到延安同我党商讨和国民党成立联合政府等问题。同年底任美国驻中国大使，因支持蒋介石的反共政策，遭到中国人民的坚决反对，一九四五年十一月离职。——第205、254页

　　〔330〕一九四四年十一月十一日和一九四五年一月二十四日，周恩来两次山延安赴重庆，同国民党进行谈判。——第205页

　　〔331〕民盟，是“中国民主同盟”的简称。一九四一年成立，原名“中国民主政团同盟”，一九四四年改今名。成员主要是文教界知识分子。一九四七年被国民党政府宣布为非法团体。一九四八年一月在香港重建组织。同年五月响应中国共产党提出的召开新政治协商会议的号召，一九四九年参加了中国人民政治协商会议。中华人民共和国成立后，民盟拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。——第205、259、275、283页

　　〔332〕国民党政府曾决定在一九三六年召开“国民大会”。一九三六年五月五日颁布了“宪法草案”（即五五宪草），并规定自七月起选举国大代表，十一月十二日开会。但这次大会没有开成。——第206、228、243页

　　〔333〕斯科比，英国人，第二次世界大战后期驻希腊盟军司令。一九四四年十月，德军在欧陆败退，斯科比率领英军，带着流亡在伦敦的希腊反动政府进入希腊，指使并协助希腊反动政府向长期英勇抵抗德军的希腊人民解放军进攻，屠杀希腊爱国人民。——第206页

　　〔334〕陈赞贤（一八九四——一九二七），一九二五年参加中国共产党。一九二七年一月被选为赣州总工会委员长和江西省总工会副委员长。同年三月六日在赣州被蒋介石反动派杀害。——第209页

　　〔335〕瓦窑堡会议，指一九三五年十二月中共中央在陕北子长县瓦窑堡举行的政治局会议，二十五日通过了《关于目前政治形势与党的任务决议》。这个决议全面地分析了当时国内外的形势和阶级关系的变化，确定了建立抗日民族统一战线的政策，批判了成为当时党内主要危险的关门主义，同时也指出了在新的革命时期预防右倾机会主义复活的必要性。——第210页

　　〔336〕第一次国内革命战争期间，上海工人在一九二六年十月二十二日，一九二七年二月二十一日两次举行武装起义，均遭失败。一九二七年三月二十一日在周恩来、罗亦农、赵世炎等领导下举行第三次武装起义，推翻了北洋军阀在上海的统治，建立了上海市民代表政府。——第212页

　　〔337〕这是针对王明一九三七年十二月九日在中共中央政治局会议报告中的错误观点的批评。——第214页

　　〔338〕七个统一，是王明在一九三八年三月十一日中共中央政治局会议的总结中提出的主张。——第219页

　　〔339〕一九三八年八月二十日国民党武汉卫戍司令部政治部宣布解散中国共产党领导的中华民族解放先锋队和进步的群众组织青年救国会、蚁社。——第219页

　　〔340〕孙中山在所著《建国大纲》中，把建设民国的程序划分为军政、训政、宪政三个时期。按孙中山的设想，训政时期需由政府选派考试合格人员，协助各县筹备自治，即进行县政建设和训练民众行使权利、履行义务，在达到规定的标准后，始能实行县自治。一省全数县已实行自治时，始可结束训政，实行宪政。全国过半数省份开始实行宪政时，才能召开国民大会，颁布宪法。以蒋介石为首的国民党反动派长期以训政为名，剥夺人民的民主权利和自由，实行法西斯统治。——第222、227、265页

　　〔341〕一九四五年八月十一日蒋介石给第十八集团军朱德总司令的命令中称：“所有该集团军所属部队，应就原地驻防待命”，不得向敌伪御自行动”。——第223页

　　〔342〕一九四五年八月十日，日本政府向对日作战的同盟国中、苏、美、英发出照会，接洽投降。八月十二日，中国、苏联、英国政府同意美国提出的以美国太平洋陆军部队统帅麦克阿瑟为同盟国占领日本的最高统帅，中国、苏联、英国都派遣高级将领参加盟军最高统帅部，接受日本的投降。——第223页

　　〔343〕一九四五年一月周恩来代表中共中央向国民党政府提议：召开党派会议，作为国事会议的预备会议，以便正式商讨国事会议和联合政府的组织及其实施的步骤问题。蒋介石在三月一日的演说中，拒绝了中国共产党的这一主张。同年七月四日，中共代表与来延安的褚辅成、黄炎培、冷通、傅斯年、左舜生、章伯钧六参政员，达成了向国民党政府提出“停止国民大会进行，从速召开政治会议”的建议。蒋介石在七月七日的参政会开幕词中，竟把中共和各民主党派对国民党坚持召开独裁包办的国民大会的合理批评，诬指为“肆意攻击”。七月十九日国民党控制的参政会通过决议案，再次拒绝召开党派会议、废止一党专政、成立联合政府等要求。——第223页

　　〔344〕邹韬奋（一八九五——一九四四），杰出的新闻记者、政论家和出版家。从一九二六年在上海主编《生活》周刊起，毕生从事新闻出版工作。一九三一年“九一八”事变后，反对蒋介石的不抵抗政策。一九三二年创办生活书店。一九三三年初参加中国民权保障同盟，七月被迫流亡国外。一九三五年回国，参加中国共产党领导的救亡运动，先后在上海、香港主编《大众生活》周刊、《生活日报》、《生活星期刊》，并担任上海各界救国会和全国各界救国联合会的领导工作。一九三六年与沈钧儒等被国民党反动派逮捕。抗日战争开始后获释，先后在上海、武汉、重庆主编《抗战》、《全民抗战》等刊物，积极参加反对蒋介石反动政策的政治斗争。皖南事变后被迫流亡香港，重新刊行《大众生活》。日军侵占香港后赴广东东江游击区，一九四二年到苏北解放区。一九四四年七月二十四日因病逝世。中共中央接受他遗书中的申请，追认他为中共正式党员。——第225、238页

　　〔345〕一九四六年一月，蒋介石在全国人民要求和平民主的压力下，被迫同意在重庆召开有国民党、共产党、其他党派和社会贤达代表参加的政治协商会议。会议从一月十日开始，至三十一日结束，通过了关于政府组织问题的协议、和平建国纲领、关于国民大会问题的协议、关于宪法草案问题的协议、关于军事问题的协议等五项决议，合称“政协决议”。——第226、234、242、249、255、262、272、283、367页

　　〔346〕蒋介石的四项诺言是：（一）保障人民自由；（二）保障各党派合法地位；（三）实行普选；（四）释放政治犯。——第226、243页

　　〔347〕一九四六年一月政治协商会议开会期间，重庆各界人民组成政治协商会议协进会，每天在沧白堂集会，邀请政协代表报告会议进展情况。国民党反动派多次派遣特务捣乱会场，殴打会议主持者及与会群众，跟踪、威胁到会讲演的政协代表。——第226页

　　〔348〕一九四六年二月十日，重庆各界二十多个团体的群众在较场口广场举行庆祝政治协商会议成功大会，国民党特务捣乱会场，打伤李公朴、郭沫若及新闻记者等六十多人，这就是较场口事件。——第226、243页

　　〔349〕一九四六年二月二十二日，国民党特务操纵重庆沙磁区部分学生举行反苏游行，并乘机捣毁《新华日报》、《民主报》（民主同盟机关报）的营业部，打伤两报工作人员多人。随后，《新华日报》成都营业分处也被特务捣毁。——第226页

　　〔350〕一九四六年三月一日，国民党特务在西安煽惑部分学生举行反苏游行，并乘机袭扰十八集团军驻西安办事处。——第226页

　　〔351〕一九四六年二月二十日，国民党反动派在北平以“河北难民还乡请愿团”名义，纠集逃亡地主、特务、流氓等千余人，举行反共游行，骚扰北平军事调处执行部。——第226页

　　〔352〕廖承志（一九○八——），当时是中共中央委员。——第226页

　　〔353〕国民党反动派为达到一党专政的目的，在一九二八年十月公布的“训政纲领”中规定，国民党中央执行委员会政治委员会负责“指导监督国民政府重大国务之施行”，决定国民政府主席及委员、各院院长及各政务官的人选。——第227页

　　〔354〕政治协商会议规定的宪草修改原则的主要内容是：“立法院为国家最高立法机关，由选民直接选举之，其职权相当于各民主国家之议会”。“行政院为国家最高行政机关”，立法院对行政院有同意权与不信任权。“监察院为国家最高监察机关”，行使同意、弹劾和监察权。“省为地方自治之最高单位”，省得制定不与国宪相抵触的省宪。——第227、234、256页

　　〔355〕五权宪法是孙中山提出的实行行政、立法、司法、考试、监察五权分立制度的宪法原则。——第227页

　　〔356〕建国大纲，是孙中山一九二四年提出的建立资产阶级共和国的纲领。见《孙中山选集》第569—571页。——第228页

　　〔357〕一九四六年三月十五日在政协综合小组会与宪草审议会协商小组举行的会议上，中共代表团在宪草修改原则问题上作了让步，商得了三个协议：一、无形国大改为有形国大；二、政协商定的宪草修改原则第六项第二条条文取消（这一条文是“如立法院对行政院全体不信任时，行政院或辞职，或提请总统解散立法院，但同一行政院长不得再提请解散立法院”）；三、省得制定省宪改为省得制定省自治法。——第228页

　　〔358〕为了维护蒋介石的法西斯独裁统治，国民党二中全会通过了推翻政协商定的“宪草修改原则”的五项决议：一、“制定宪法应以建国大纲为最根本之依据”；二、“国民大会应为有形之组织，用集中开会之方法，行使建国大纲所规定之职权”；三、“立法院对行政院不应有同意权及不信任权；行政院亦不应有提请解散立法院之权”；四、“监察院不应有同意权”；五、“省无须制定省宪”。这里讲的“所增加之两点半”，指上述五项决议中的第一项、第四项和第二项的“用集中开会之方法，行使建国大纲所规定之职权”。——第228页

　　〔359〕整军方案，即国共双方一九四六年二月二十五日签订的《关于军队整编及统编中共部队为国军之基本方案》。全文共八条，主要内容是规定全国陆军为一百○八师（每师不超过一万四千人），其中中共部队十八师；双方编余人员应在十二个月内全部复员；此外还对国共双方部队的统帅权、统一编制的时间、地区配置以及地方部队的组织等作了规定，并确定以军事调处执行部作为实施本方案的执行机关。——第229、234、244、255页

　　〔360〕一九四六年一月十日国共双方签订停战协定，同日下午下达了停战令。停战协定和停战令规定，双方军队应在一月十三日午夜就各自位置停止军事行动。但蒋介石在下达停战令的同时，密令国民党军队“抢占战略要点”，接着又不断地调动军队，向解放区进攻。同年七月蒋介石公开撕毁了停战协定，向解放区发动全面进攻。——第229、234、242、249、255、262、272页

　　〔361〕林，即林平（现名尹林平），当时任广东东江抗日纵队政治委员。郑，即郑绍文，当时任新四军第五师江汉军区政治委员、八路军新四军中原军区武汉办事处处长。——第229页

　　〔362〕马歇尔（一八八○——一九五九），美国职业军人，政客。一九四五年十二月任美国总统杜鲁门的驻中国特使，以“调处”为名，参与国共谈判，支持国民党政府发动反共反人民的内战。一九四六年八月宣布“调处”失败，一九四七年一月八日离华回国。——第229、238、255、262、281、321页

　　〔363〕三人会议又称军事三人小组会议，是一九四六年一月由国民党代表张群（后为张治中）、共产党代表周恩来和美国总统杜鲁门特使马歇尔参加组成的停战机构，马歇尔担任主席。北平军事调处执行部和各地执行小组都受其领导与指挥。由于蒋介石坚持内战独裁政策，蓄意破坏停战协定，美国又执行助蒋内战政策，同年六月以后三人小组会议停止活动。——第230、244、259、266页

　　〔364〕一九四五年十二月十五日美国总统杜鲁门发表对华政策声明，宣称：“美国竭力主张中国国内各主要政治党派的代表举行全国会议从而商定办法，使他们在中国国民政府内得享有公平和有效的代表权。美国政府认为此举就需要修改…一党训政制度。”——第231、255、262页

　　〔365〕一九四五年十二月十六日至二十六日苏、美、英三国外长在莫斯科举行会议，二十七日发表会议公报。公报在中国实现民主政治问题上提出：“在国民政府领导下有一团结的与民主的中国之必要，并且必须广泛地吸收国内一切民主分子到国民政府的一切（各级）机构中。”——第231、255页

　　〔366〕五方面代表，指参加政治协商会议的中国国民党、中国共产党、中国民主同盟、中国青年党和社会贤达五个方面的代表。——第231页

　　〔367〕王若飞、博古、叶挺、邓发、黄齐生等都是一九四六年四月八日由重庆飞返延安时因飞机失事在山西兴县黑茶山遇难的烈士。王若飞（一八九六——一九四六），一九一九年赴法勤工俭学，一九二一年发起组织少年共产党，一九二二年参加中国共产党。一九二五年以后，历任中共豫陕区党委书记、中共中央秘书长、中共江苏省委常委等职。一九二八年任中共驻共产国际代表。一九三一年回国，在绥远被国民党政府逮捕，狱中坚持革命斗争。一九三七年夏出狱后历任中共陕甘宁边区党委宣传部长、十八集团军副参谋长、中共华北华中工作委员会秘书长、中共中央秘书长和中央党务研究室主任等职。一九四四年五月任中共代表参加国共谈判。在党的第五、七次全国代表大会上当选为中央委员。一九四六年任中共出席政治协商会议的代表。——第233、254页

　　〔368〕博古，即秦邦宪（一九○七——一九四六），一九二五年参加中国共产党。一九三一年四月任共产主义青年团中央书记，同年九月至一九三五年一月为中共临时中央总负责人，犯过严重的“左”倾路线错误。遵义会议后任中国工农红军野战政治部主任。一九三六年同周恩来、叶剑英等作为中共中央代表参加和平解决西安事变。一九三七年任党中央组织部长。抗日战争爆发后任中共驻南京代表。一九三八年起先后任中共长江局、南方局委员兼组织部长。一九四一年起在延安主持《解放日报》和新华通讯社。一九四五年在党的第七次全国代表大会上当选为中央委员。一九四六年任中共出席政治协商会议宪草审议委员会的代表。——第195、233页

　　〔369〕叶挺（一八九六——一九四六），字希夷，中国人民解放军创始人之一。一九二四年参加中国共产党。一九二五年任国民革命军第四军参谋处长和独立团团长。北伐战争中率部在湖北汀泗桥和贺胜桥两次战斗中获胜，为第四军赢得了“铁军”的称号。一九二六年十月任第十一军二十四师师长兼武汉警备司令。一九二七年参加领导“八一”南昌起义，任前敌总指挥兼第十一军军长。同年十二月又参加领导广州起义，任起义军总司令。广州起义失败后出国。抗日战争爆发后回国。一九三七年底到延安，后任新四军军长。一九四一年一月皖南事变中负伤被俘。一九四六年三月四日出狱，七日由中共中央批准重新入党。——第114、174、202、213、226、233页

　　〔370〕邓发（一九○六——一九四六），一九二二年参加香港海员大罢工。一九二五年参加中国共产党。同年参加省港罢工和东征战役。一九二七年参加广州起义。一九二八年后历任中共香港市委书记、广州市委书记、广东省委组织部长、中华苏维埃共和国临时中央政府政治保卫局局长等职。长征时任军委二纵队副司令员。一九三八年起历任中国共产党驻新疆办事处主任、中共中央党校校长、中共中央职工委员会书记、民运委员会书记等职。在党的六届三中全会和第七次全国代表大会上当选为中央委员，在党的六届五中全会上当选为政治局候补委员。一九四五年九月代表解放区职工出席在巴黎召开的世界工会代表大会。——第233页

　　〔371〕黄老先生，即黄齐生（一八七九——一九四六），教育家。清末在贵阳创办达德学校，曾参加辛亥革命。一九二一年赴法勤工俭学。回国后主办遵义中学。一九二九年后在晓庄学校任教。一九三一年“九一八”事变后，积极为抗日运动奔走。一九四五年赴延安。一九四六年较场口事件发生后，代表延安各界赴渝慰问被殴打的民主人士。——第233页

　　〔372〕一九四六年四月八日与王若飞等同机遇难的还有八路军中校参谋李绍华，副官赵登俊、魏万吉，叶挺夫人李秀文、女儿叶扬眉、儿子阿九，女工高琼，黄齐生先生的孙子、延安鲁迅艺术学院教员黄晓庄和美军驾驶员兰奇上尉等四人。——第233页

　　〔373〕双十国共会谈纪要，参见本书《一年来的谈判及前途》一文（第252—254页）。——第234、252、273、367页

　　〔374〕一九四六年一月国共双方签订停战协议时，国民党反动派为了抢占东北，坚持停战协议不包括东北地区。在遭到我军的沉重打击和全国人民的反对后，蒋介石被迫同意于一九四六年三月二十七日在重庆签订东北停战协议。但协议签订才三天，国民党军队就在美国的援助下，向我营口、鞍山、四平街等地发动了新的进攻。——第234、255、263页

　　〔375〕一九四六年上半年，根据中共中央和中央军委的指示，组成了中原军区，李先念为司令员、郑位三为政治委员。六月二十六日国民党反动派撕毁停战协定，以三十万军队向中原军区大举进攻。为了保存力量，争取主动，中原解放军在六月底分路突围，实行战略转移，牵制了大量敌人，有力地配合了其他解放区的作战。——第236页

　　〔376〕胡宗南，解放战争期间任国民党西北军政长官公署8副长官兼西安绥靖公署主任等职。——第236、274页

　　〔377〕李公朴（一九○○——一九四六），爱国民主人上。一九三一年“九一八”事变后积极参加抗日救国运动和群众文化教育工作。一九三六年参加全国各界救国联合会，被推为负责人之一。同年十一月与沈钧儒等一起被国民党反动派逮捕，抗战开始后获释。一九四五年任中国民主同盟中央委员。一九四六年七月十一日在昆明被国民党特务暗杀。——第237、239、2413、263页

　　〔378〕闻一多（一八九九——一九四六），爱国民主人士，著名诗人、学者。一九四三年以后，由于痛恨国民党政府的独裁和腐败，积极参加争取民主的斗争。一九四五年任中国民主同盟中央委员。一九四六年七月十五日在昆明被国民党特务暗杀。长子闻立鹤为掩护闻一多也受重伤。——第237、239、241、243、263页

　　〔379〕一九四六年三月一日国民党特务捣毁西安民办报纸《秦风工商阳合报》。四月逮捕并杀害该报法律顾问、民主同盟盟员王任律师。四月三十日夜，国民党特务绑架枪杀西安民主同盟青年部长、《民众导报》主编、中共党员李敷仁（当时伤重未死，经群众抢救掩护辗转到达延安，任延安大学校长）。这就是西安血案。一九四六年三月十八日军调部淮阴执行小组到达江苏南通，受到群众热烈欢迎，执行小组离开后，国民党反动派秘密逮捕、杀害参加欢迎的群众二十余人，随同执行小组到南通的新华社记者孙平天同时遇难，这就是南通血案。——第237页

　　〔380〕小超，即邓颖超，当时是中国共产党出席政治协商会议的代表。——第238页

　　〔381〕伍云南（一九○四——一九六九），一九二六年参加中国共产党。一九四六年任解放区救济总会秘书长。——第238页

　　〔382〕司徒雷登（一八七六——一九六二），当时任美国驻中国大使。——第238、259、323页

　　〔383〕国民党反动派在撕毁政协协议、召开分裂的“国民大会”的前夕，一九四六年十一月八日单方面颁布所谓“停战令”，以掩盖其政治上分裂的阴谋，推卸扩大内战的责任。——第244页

　　〔384〕云南起义，指一九一五年十二月二十五日在云南爆发的反对袁世凯称帝复辟的起义。蔡锷等在这一天通电各省，宣告云南独立，并组织护国军发动讨袁战争，随即得到贵州、广西、广东、浙江等省的响应。次年六月，袁世凯病死。——第246页

　　〔385〕一九三六年十一月，日本侵略者嗾使伪蒙军李守信、王英等部，配合日军向绥东（现在内蒙古自治区乌兰察布盟一带地区）进攻，为当地军民所击溃。——第248页

　　〔386〕“中美商约”即《中美友好通南航海条约》，是一九四六年十一月四日国民党政府和美国政府在南京签订的大量出卖中国主权的条约。——第249、266页

　　〔387〕这个宣言，指一九四五年八月二十五日发表的《中共中央对目前时局宣言》。“宣言”提出在和平民主团结的基础上，实现全国统一，建设独立自由与富强的新中国的方针；针对反动派阴谋发动内战、破坏团结、压制民主的活动，向国民党政府提出六项紧急措施，主要内容是：（一）承认解放区的民选政府和抗日军队，撤退包围和进攻解放区的军队；（二）划定八路军、新四军及华南抗日纵队接受日军投降的地区，并给与参加处置日本的一切工作的权利；（三）严惩汉奸，解散伪军；（四）公平合理地整编军队，办理复员，救济难胞，减轻赋税；（五）承认各党派合法地位，取消一切妨碍人民集会结社言论出版自由的法令，取消特务机关，释放爱国政治犯；（六）立即召开各党派和无党派代表人物的会议，制定民主的施政纲领，结束训政，成立举国一致的民主联合政府，筹备普选的国民大会。——第251页

　　〔388〕一九三七年四月，中国共产党起草了《国共共同纲领》，提出开放民众运动、释放政治犯、承认革命根据地和红军改名为国民革命军等项内容，建议国民党用两党名义向全国人民发布，但为国民党拒绝，没有发布。——第252页

　　〔389〕青年党是“中国青年党”的简称，其成员是一些地主、资本家、政客和知识分子。一九二三年在法国成立，初名“中国国家主义青年团”，一九二九年改名为“中国青年党”，鼓吹国家主义，反对共产主义。抗日战争期间曾参加中国民主同盟，后又依附国民党，参加了一九四六年十一月国民党包办的“国民大会”。一九四九年随国民党逃往台湾省。——第253、259、262、275、284页

　　〔390〕张君劢（一八八七——一九六九），当时是中国民主社会党主席。——第253、285页

　　〔391〕取消立法院对行政院的不信任权，参见注〔357〕。——第258页

　　〔392〕五人会议，指一九四六年七月一日蒋介石指定陈诚、王世杰、邵力子代表国民党与中共代表周恩来、董必武进行的谈判。——第259页

　　〔393〕民社党是“中国民主社会党”的简称。一九四六年由“国家社会党”与“民主宪政党”合并组成，其主要成员是地主、资产阶级的代表人物。一九四六年十一月参加了国民党包办的“国民大会”。一九四九年五月在香港召开常务委员会议，宣布继续追随国民党，同年随国民党逃往台湾省。——第259、263、275、254页

　　〔394〕胡政之（一八八九——一九四九），当时是《大公报》总经理。——第260页

　　〔395〕黄炎培（一八七八——一九六五），当时是参加政治协商会议的民主同盟的代表，中国民主建国会召集人。中华人民共和国成立后，任政务院副总理等职。——第260页

　　〔396〕杜聿明（一九○四——），当时任国民党军东北保安司令长官。后任国民党军徐州“剿总”副总司令，一九四九年一月淮海战役中被我军俘虏。一九五九年被特赦释放，现任中国人民政协全国委员会常务委员。——第263页

　　〔397〕一九四六年七月二十九日，在天津的美国海军陆战队和国民党军各数十人，“巡逻”到天津西北七十公里的河北香河县安平镇附近，侵入冀东八路军防地，并向当地守军攻击。守军被迫自卫。国民党反动派借此大肆煽动，竭力想把美军牵入中国内战漩涡。我党及时揭露了美军的侵略行为和国民党反动派的阴谋活动，严正要求美国海军陆战队道歉赔偿，要求美国驻华的一切海陆空军立即撤出中国。——第266页

　　〔398〕航空协定，指一九四六年十二月二十日国民党政府和美国政府在南京签订的出卖中国领空权的“空中运输协定”。——第266页

　　〔399〕一九四六年十二月二十四日，北平发生了美军强奸北京大学女生沈崇的事件。蒋管区几十个大中城市的学生，分别成立“抗议美军暴行联合会”，举行反美反蒋的示威游行，要求美军退出中国。学生群众的这一行动得到社会各界的响应。——第269页

　　〔400〕一九四七年二月，国民党反动政府公布“经济紧急措施方案”，宣布“冻结生活指数”，即不管物价如何飞涨，工人工资只能维持在一月份的水平，不能相应增加。（以上海米价为例，一月初每担售伪法币六万元，同年六月已上涨到每担五十万元。）上海工人、店员在五月间举行大规模游行示威，坚决反对这一反动措施。国民党政府被迫在六月宣布解除对生活指数的冻结。——第270页

　　〔401〕吴，即吴玉章（一八七八——一九六六），一九二五年参加中国共产党。当时任中共四川省委书记。张，即张友渔（一八九九——），当时任中共四川省委副书记、宣传部长兼新华日报社社长。——第270页

　　〔402〕一九四六年六月六日起，国共双方在南京举行关于结束东北冲突、恢复交通、整编军队三个问题的谈判。参加谈判的除国共双方代表徐永昌、周恩来外，还有美国政府代表马歇尔。美蒋方面对谈判毫无诚意，拒绝了我方提出的长期停战、恢复交通、整军复员、重开政协四项建议。——第273页

　　〔403〕这次改组政府，指蒋介石在一九四七年四月收买民社党、青年党和某些无党派的政客参加国民党政府。蒋介石宣称，这次改组后的国民党政府是“自由主义”和“多党”的政府，用以粉饰其独裁统治。——第275页

　　〔404〕一九四七年五月二十日国民党控制的第四届第三次参政会开幕，蒋介石出席讲话。南京中央大学等校学生和苏州、杭州、上海赴南京学生七千多人到参政会的会址国民大会堂前游行，要求停止内战。国民党反动派逮捕、打伤学生百余人。——第276页

　　〔405〕刘伯承、邓小平领导的晋冀鲁豫野战军主力五个纵队十三万余人，从一九四七年六月三十日起，强渡黄河，向大别山进军，揭开了人民解放军战略进攻的序幕。陈赓和谢富治领导的晋冀鲁豫野战军太岳兵团两个纵队一个军八万余人，在同年八月二十二日由晋南强渡黄河，挺进豫西。陈毅、粟裕领导的华东野战军八个纵队十八万人，同年九月上旬挺进鲁西南，进军豫皖苏地区。——第278页

　　〔406〕孙连仲（一八九三——），当时任国民党军保定绥靖公署主任。傅作义（一八九四——一九七四），当时任国民党军张垣绥靖公署主任，后任国民党华北“剿总”总司令。一九四九年一月率部起义，对北平和绥远的和平解放作出了贡献。中华人民共和国成立后，任中央人民政府委员、水利部和水利电力部部长等职。——第279页

　　〔407〕一九四七年九月中国共产党在河北省建屏（今平山）县西柏坡村召开了全国土地会议，会议通过《中国土地法大纲》，同年十月十日由中共中央公布。土地法大纲规定：“废除封建性及半封建性剥削的土地制度，实行耕者有其田的土地制度”。——第280、286页

　　〔408〕美国政府给蒋介石的军事、经济援助，截止一九四九年的统计数字，抗日战争期间为十五亿六千七百八十万美元，解放战争期间为四十六亿四千零四十九万美元。两项共计六十二亿八百二十九万美元。——第281页

　　〔409〕魏德迈，美国职业军人。一九四七年七月以美国总统特使的身分来华，寻求支持与控制蒋介石集团的办法。——第281页

　　〔410〕宋子文，一九四五年五月至一九四九年一月，先后任国民党政府行政院长、广东省政府主席。——第281、283页

　　〔411〕抗日战争胜利前后，国民党内一部分爱国民主人士为了反对蒋介石的卖国独裁政策，先后成立三民主义同志联合会、国民党民主促进会等民主组织。一九四七年，国民党内各民主组织的领导人和一些爱国民主分子先后到达香港，十一月举行国民党民主派第一次全国代表大会，一九四八年一月一日在香港正式成立了中国国民党革命委员会，选出领导机构，推宋庆龄为名誉主席，李济深为主席，何香凝、冯玉祥、李意达、谭平山、蔡廷错、朱蕴山等为常务委员。同时发表成立宣言，明确提出“推翻蒋介石卖国独裁政权，实现中国独立、民主与和平”。——第283页

　　〔412〕蔡廷锴（一八九二——一九六八），当时任中国国民党革命委员会中央常务委员。中华人民共和国成立后，任中央人民政府委员等职。——第283页

　　〔413〕这个指示，指一九四七年十月二十七日中共中央关于必须将革命进行到底，反对刘航琛等人的假和平阴谋的指示。当时在美帝国主义和蒋介石的策动支持下，少数地方系政客、军阀及资产阶级右翼的代表，企图发动一场假和平运动，使面临总崩溃的国民党政权取得喘息时机，使人民革命半途而废。刘航琛是其中的一个代表。中央的这个指示揭露了这一阴谋，坚持将革命进行到底。——第283页

　　〔414〕伪宪，指蒋介石撕毁“政协决议”、发动全面内战后，在一九四六年十一月非法召开的国民大会上通过的反共反人民的《中华民国宪法》。——第284页

　　〔415〕中国民主建国会，主要由民族工商业者组成。一九四五年成立。一九四八年响应中国共产党提出的召开“新政协”的号召。一九四九年参加中国人民政治协商会议第一届全体会议。中华人民共和国成立后，拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。——第285页

　　〔416〕君主立宪制，是保留君主的资本主义国家君主权力受宪法限制的政治制度。这里是指保留大地主大资产阶级统治，只进行某些改良的民族资产阶级右翼的主张。——第285页

　　〔417〕这个宣言，指一九四七年十月十日公布的《中国人民解放军宣言》（见《毛泽东选集》第1179—1183页）。宣言提出“打倒蒋介石，解放全中国”的口号，宣布了中国人民解放军的也就是中国共产党的八项基本政策。——第286页

　　〔418〕“五四指示”，即一九四六年五月四日中共中央《关于土地问题的指示》。这一指示将党在抗日战争时期实行的减租减息的土地政策，改为没收地主土地分配给农民。——第288页

　　〔419〕陕甘宁边区是一九三七年九月建立的。在一九三五年中央红军到达陕北之前，陕北和陕甘两个革命根据地的工农民主政府曾领导人民先后进行了平分地主土地，废除农民债务的工作。一九三七年三月，中共中央和中华苏维埃共和国临时中央政府为团结全国各党派各阶级结成抗日民族统一战线，宣布暂时停止没收和平分地主的土地，实行减租减息的政策，但对于农民已经从土地改革中取得的果实则坚决予以保障。由于国民党反动派的破坏和我们工作上的一些错误，陕甘宁的部分地区出现了强迫农民交还已经分得的土地和房屋的现象。针对这种情况，一九三八年五月毛泽东起草了《陕甘宁边区政府、第八路军后方留守处布告》（见《毛泽东选集》第370页），宣布取缔这种违反团结抗日原则的破坏行为。在这以后直到一九四○年的一个时期内，陕甘宁边区人民根据“布告”精神，坚决地进行斗争，使土地又陆续归还了农民。——第288页

　　〔420〕陕西省绥德县黄家川，当时属于陕甘宁边区。它的典型经验是：在已进行过土改的基础上，用抽肥补瘦、抽多补少的方法调剂上地，使土地分配更为合理，既满足了贫雇农对土地的要求，又巩固地团结了中农。——第289、299页

　　〔421〕河北省平山县，当时属于晋察冀解放区。平山典型经验，是指这个县在上地改革运动中，采取邀请党外群众列席党的会议整顿党在农村的基层组织的经验。——第295页

　　〔422〕用三查与诉苦方法进行的新式整军运动，是我党在解放战争时期结合土地改革进行的一个重要运动。“三查”和诉苦是在部队中发动广大指战员查阶级、查工作、查斗志，诉旧社会和反动派所给予劳动人民的痛苦。——第303页

　　〔423〕新政治协商会议，即中国人民政治协商会议。一九四八年四月三十日中共中央发布的纪念“五一”劳动节口号中，号召“各民主党派、各人民团体、各社会贤达迅速召开政治协商会议，讨论并实现召集人民代表大会，成立民主联合政府”。这里提出的政治协商会议，当时被称为“新政协”，以区别于一九四六年一月国民党召开的那次政治协商会议。一九四九年九月中国人民政治协商会议举行第一届全体会议，代行全国人民代表大会的职权，制定了《中国人民政治协商会议组织法》、《中国人民政治协商会议共同纲领》、《中华人民共和国中央人民政府组织法》，选举了以毛泽东主席为首的中央人民政府委员会，宣告了中华人民共和国的成立。一九五四年九月召开第一届全国人民代表大会第一次会议之后，中国人民政治协商会议不再代行全国人民代表大会的职权，但仍然是在中国共产党领导下，团结全国各民族、各民主党派、各人民团体、国外华侨和其他爱国民主人士的人民民主统一战线组织。——第307、357、363、366页

　　〔424〕李宗仁（一八九○——一九六九），原为国民党桂系首脑。一九四八年四月任国民党政府副总统，一九四九年一月任代总统。国民党政权崩溃后去美国。一九六五年七月回到北京。——第307、317页

　　〔425〕蒋介石反动集团崩溃前夕，为了进一步搜刮人民，一九四八年八月十九日颁布“财政经济紧急处分令”。主要内容为发行“金元券”，并限期以一比三百万的比价收兑法币；限期收兑民间黄金、白银、银币和外国币券，禁止任何人持有；限期登记管理民间存放在国外的外汇资产。——第310页

　　〔426〕一九四八年四月，国民党反动派成立“特种刑事法庭”，八月十七日以行政院名义发布命令，发动所谓特种刑事检举。由特务、暗探开列进步的工人、学生的“黑名单”，并自八月十九日起陆续在报上公布学生的黑名单，限令他们在名单公布的第二天到特种刑事法庭“投案”，同时进行大规模的逮捕。——第310页

　　〔427〕郑洞国（一九○三——），当时任国民党军东北“剿总”副总司令兼第一兵团司令。一九四八年十月十九日率领所部在长春放下武器。现任中国人民政协全国委员会常务委员等职。——第313页

　　〔428〕曾泽生（一九○二——一九七三），当时任国民党军第一兵团副司令兼六十军军长。一九四八年十月十七日在长春率部起义。中华人民共和国成立后，任中国人民解放军军长、国防委员会委员等职。——第513页

　　〔429〕王耀武（一九○三——一九六八），当时任国民党军第二绥靖区司令官兼山东省政府主席。一九四八年九月在济南战役中被我军俘虏。一九五九年十二月被特赦释放。一九六四年任中国人民政协全国委员会委员。范汉杰（一八九五——一九七六），当时任国民党军东北“剿总”副总司令兼锦州指挥所主任。一九四八年十月在锦州战役中被我军俘虏。一九六○年十一月被特赦释放。一九六四年任中国人民政协全国委员会委员。——第313页

　　〔430〕吴化文（一九一四——一九六二），当时任国民党军整编第九十六军军长。一九四八年九月在济南战役中起义。中华人民共和国成立后，任中国人民解放军军长等职。——第313页

　　〔431〕肖劲光（一九○三——），当时任中国人民解放军东北野战军副司令员兼第一兵团司令员。

　　肖华（一九一四——），当时任中国人民解放军第一兵团政治委员。——第313页

　　〔432〕陈嘉庚（一八七四——一九六一），爱国华侨领袖。抗日战争期间拥护中国共产党的抗日民族统一战线政策，倡议组成“南洋华侨筹赈祖国难民总会”，并任主席，曾到延安慰劳边区抗战军民。解放战争期间积极参加反蒋的爱国民主运动。中华人民共和国成立后，任中央人民政府委员等职。——第314页

　　〔433〕张奚若（一八八九——一九七三），爱国民主人士。从抗日战争后期起，反对蒋介石的独裁统治，拥护中国共产党提出的成立民主联合政府的主张，积极参加国民党统治区的爱国民主运动。中华人民共和国成立后，任中央人民政府委员等职。——第314页

　　〔434〕济南战役，是一九四八年九月十六日至二十四日华东野战军解放济南的战役。这次战役全部歼灭守敌（内有一个军起义）十一万人，俘虏国民党军第二绥靖区司令官王耀武。

　　辽沈战役是指一九四八年九月十二日至十一月二日东北野战军在辽宁省西部和沈阳、长春地区进行的一次巨大战役。辽沈战役迫使敌东北“剿总”副总司令郑洞国放下武器，俘虏东北“剿总”副总司令范汉杰、兵团司令卢港泉、廖耀湘，共歼敌四十七万人，解放了东北全境。这一胜利，连同当时其他战场上的胜利，使全国的军事形势出现了根本的变化，我军不但在质量上早已占有优势，而且在数量上也转入了优势。

　　淮海战役是指一九四八年十一月六日至一九四九年一月十日由华东野战军和中原野战军在以徐州为中心，东起海州，西至商丘，北起临城（今薛城），南达淮河的广大地区进行的一次决定性的战役。中共中央决定由刘伯承、邓小平、陈毅、粟裕、谭震林组成总前委，邓小平为书记，领导淮海前线我军的一切行动。这次战役毙敌兵团司令黄伯韬、邱清泉，俘虏徐州“剿总”副总司令杜聿明，兵团司令黄维。兵团副司令吴绍周，共歼敌五十五万人，解放了长江以北广大地区，使蒋介石的精锐主力丧失殆尽，反动统治的中心南京、上海、武汉等地，处于我军直接威胁之下。

　　平津战役是指一九四八年十二月上旬至一九四九年一月底，由华北野战军和东北野战军在西起张家口东至塘沽、唐山，包括北平、天津地区共同进行的一次巨大战役。中共中央决定由林彪、罗荣桓、聂荣臻组成总前委，领导平津前线我军的一切行动。战役中先后歼灭新保安、张家口、天津守敌，俘敌天津警备司令陈长捷；由于我方的努力争取，经过谈判，在敌华北“剿总”总司令傅作义率领下，北平守敌接受我军改编，北平获得和平解放。全战役共歼灭和改编敌军五十二万余人，基本上解放了华北地区。——第315、346页

　　〔435〕黄伯韬，参见注〔434〕。——第315页

　　〔436〕一九四九年一月一日蒋介石发表元旦文告，提出愿意与中国共产党进行和平谈判的虚伪建议，主张以保存伪宪法、伪法统和反动军队等项为全国人民所不能接受的条件为和平谈判的基础。——第317页

　　〔437〕一九四九年一月十四日中共中央主席毛泽东发表关于时局的声明，揭露了蒋介石的假和平阴谋，提出了和平谈判的八项条件：一、惩办战争罪犯；二、废除伪宪法；三、废除伪法统；四、依据民主原则改编一切反动军队；五、没收官僚资本；六、改革土地制度；七、废除卖国条约；八、召开没有反动分子参加的政治协商会议，成立民主联合政府，接受南京国民党反动政府及其所属各级政府的一切权力。——第317页

　　〔438〕一九四九年一月十五日人民解放军解放天津，国民党反动统治面临全面崩溃，蒋介石一月二十一日以“因故不能视事”为名，宣布“引退”，把职务交给副总统李宗仁“代理”，自己退居幕后指挥。——第317页

　　〔439〕李宗仁代理国民党政府总统职务以后，一九四九年二月上旬在上海组织了以颜惠庆、章士钊、江庸为代表的“上海人民代表团”。邵力子以私人资格参加了代表团。这个代表团二月十四日到北平与我党商谈和平谈判问题，又到西柏坡受到毛泽东、周恩来的接见，二月二十七日返回南京。——第317页

　　〔440〕一九四九年四月一日起，国共双方代表在北平举行和平谈判。南京国民党政府和平谈判代表团的成员是：张治中、邵力子、黄绍竑、章士钊、李蒸、刘斐，张治中为首席代表。中国共产党代表团的成员是：周恩来、林伯渠、林彪、叶剑英、李维汉、聂荣臻，周恩来为首席代表。——第317、328页

　　〔441〕据国家统计局一九五九年在《伟大的十年——中华人民共和国经济和文化建设成就统计》一书中公布的资料，一九四九年中国现代性工业占工农业总产值的百分之十七左右。——第317页

　　〔442〕参见注〔425〕。——第318页

　　〔443〕广州，当时是国民党政府行政院所在地。溪口，在浙江省奉化县。蒋介石自宣布“引退”后，便住在溪口，幕后操纵国民党反动派破坏和谈，继续与人民为敌。——第318页

　　〔444〕一九一七年十月革命后，英、法、日、美等帝国主义国家对苏俄发动了武装干涉。美军曾在苏俄北部和东部登陆，侵占了阿尔汉格尔斯克、牟尔曼斯克和海参崴等地，直到一九一九年和一九二○年才被迫分批撤离。——第323页

　　〔445〕傅泾波，当时是美国驻华大使司徒雷登的私人顾问。——第323页

　　〔446〕师爷，是旧时对官署中幕僚的称呼，如刑名师爷、钱谷师爷等。旧时绍兴人在官署中担任幕僚的较多，因有“绍兴师爷”的说法。——第325页

　　〔447〕见《联共（布）党史简明教程》，人民出版社一九七五年版第117页。——第329页

　　〔448〕中华全国青年第一次代表大会一九四九年五月四日至十日在北平召开，会上成立了中华全国民主青年联合总会，后改称中华全国青年联合会。——第331页

　　〔449〕范文澜（一八九三——一九六九），马克思主义历史学家。当时任华北大学副校长兼研究部主任。在党的第八、九次全国代表大会上，先后当选为候补中央委员、中央委员。——第333页

　　〔450〕汉学，亦称“朴学”，指汉儒考据训诂之学。清朝的一部分学者用汉德的方法研究经典，注重一字一句的考订，称为汉学，以与宋儒空谈义理的“宋学”相对立。汉学对整理古籍，辨别真伪，有不少贡献，但往往流于为考据而考据的倾向。——第333页

　　〔451〕这是指毛泽东在中共中央会议上作的题为《目前形势和我们的任务》的报告（见《毛泽东选集》第1187—1204页）。——第336页

　　〔452〕见列宁《伟大的创举》（《列宁选集》第4卷第17页）。——第336页

　　〔453〕全国文学艺术工作者代表大会一九四九年七月二日至十九日在北平召开。大会总结了毛泽东一九四二年《在延安文艺座谈会上的讲话》发表以后的文艺工作经验，确定了新形势下文艺工作的方针和任务，建立了全国统一的文学艺术界组织——中华全国文学艺术界联合会。——第344页

　　〔454〕中华全国文艺协会，即中华全国文艺界抗敌协会，简称“文协”，一九三八年三月成立于汉口，是中国共产党领导下的团结文艺界一切抗日力量的统一战线组织。周恩来被选为名誉理事，郭沫若、茅盾、老舍等四十五人为理事。“文协”广泛地开展了抗战文艺活动，出版《抗战文艺》杂志，在坚持团结抗战、争取届主进步的运动中起了重要作用。一九四九年召开的第一次全国文学艺术工作者代表大会，“文协”是发起团体之一。——第344页

　　〔455〕根据中共中央指示精神，中央军委一九四八年十一月一日通令全军进行整编，实行统一的编制、番号。通令规定，中国人民解放军分为野战部队、地方部队、游击部队。一九四九年春，各野战军先后进行了整编。西北、中原、华东、东北野战军，依次改编为第一、第二、第三、第四野战军。华北野战军的第十八、十九、二十兵团，直属中国人民解放军总部。陕甘宁、晋绥联防军区改为西北军区，华北、东北、华东、中原军区番号不变。——第351页

　　〔456〕一九四九年九月二十九日中国人民政治协商会议第一届全体会议通过的《中国人民政治协商会议共同纲领》，简称《共同纲领》。全文共七章六十条。它是在中国共产党领导下，各民主党派、各人民团体和各族各界人民的代表共同制订的建国纲领，是全国人民在一定时期内共同的奋斗目标和统一行动的政治基础，在我国正式颁布宪法以前起过临时宪法的作用。——第366页

　　〔457〕三次反共高潮，参见本书《论统一战线》一文（第200—204页）。——第367页

　　〔458〕杨杰（一八八八——一九四九），国民党爱国将领。解放战争期间参加反内战、反独裁活动。一九四九年应邀参加中国人民政治协商会议第一届全体会议，九月十九日由云南赴北平途中，在香港被国民党特务暗杀。——第369页

　　〔459〕这里指的是消灭剥削阶级。一九三六年十一月，斯大林在全苏苏维埃第八次非常代表大会上所作的《关于苏联宪法草案》的报告中指出：“地主阶级已因国内战争胜利结束而完全消灭了。其它剥削阶级也遭到了与地主阶级同样的命运。在工业方面已经没有资本家阶级了。在农业方面已经没有富农阶级了。……因而，所有的剥削阶级都被消灭了。”——第369页

　　〔460〕新民主主义五种经济，指社会主义的国营经济、私人资本主义经济、农民和手工业者的个体经济、半社会主义性质的合作社经济、国家与私人合作的国家资本主义经济。——第370页



