# 抗美援朝，保卫和平

中文马克思主义文库 -> 周恩来
抗美援朝〔26〕，保卫和平
（一九五○年十月二十四日）

朝鲜反侵略战争胜利地开始，大家看到了朝鲜人民的英勇，同时也看到了美帝国主义的残暴。

七月半以后，美帝国主义向南撤退，迅速地把军力集结在朝鲜半岛南方大邱地区，意图引诱朝鲜人民军向其进攻。年轻的朝鲜人民军是勇往直前的，要一直把美国兵赶下海去。当时的形势已表现出战争将长期化。

朝鲜民主主义人民共和国是一个新的国家，朝鲜人民军是一支年轻的部队，他们战斗非常英勇，真使我们感动。敌人依仗暂时的强大，有意制造阴谋。现在朝鲜是困难的，但他们英勇地坚持着，在南方打游击，在北方抵抗，斗争仍在继续，只要坚持下去，就可以生长出新的力量来打败敌人。朝鲜地方较小，所依靠的基础是九百万人口，以这样的力量，抵抗这么强大的敌人，下了长期抵抗的决心，是难能可贵的，我们应当赞佩。

朝鲜问题是一个国际问题，它同国际上的其他问题是不可分割的，朝鲜人民的长期抵抗，将更增加问题的国际性。同时，朝鲜要胜利，也必须得到国际的援助。尤其是在困难的时候，更需要国际的援助。我们应该发扬革命的道义。只有朝鲜胜利了，和平阵营才不会被打开一个缺口。如果朝鲜这个缺口被打开，则其他方面要相继被打开。东方阵线门户洞开，敌人打进我们的大门来了，怎么还能谈建设？

中朝是唇齿之邦，唇亡则齿寒。朝鲜如果被美帝国主义压倒，我国东北就无法安定。我国的重工业半数在东北，东北的工业半数在南部，都在敌人轰炸威胁的范围之内。从八月二十七日到昨天这两个月间，美帝国主义的飞机已侵入我国十二次。最近不仅在鸭绿江，而且已飞到宽甸来示威、侦察、扫射和轰炸。如果美帝打到鸭绿江边，我们怎么能安定生产？

我们国家的建设需要有三年五年时间先恢复生产，我们也正在进行恢复工作。最近拟定了一九五一年的经济计划，总想减少军费，增加经济建设费和文教费，把军费由今年占预算的百分之四十三减为明年占预算的百分之三十，以全部概算的百分之七十投入经济建设、文教事业等，并考虑改善公教人员的生活，收购农民的余粮，发展日用品的生产。但敌人不让我们这样做。不久以前华莱士〔27〕给毛主席一封信，他说，愿中国造拖拉机，不要将造拖拉机的力量造了坦克车。实际是敌人不许我们建设，逼得我们不能造拖拉机。

假如我们采取消极防御的办法，那是不行的。消极防御也要花许多钱，例如改装一个飞机场就要一亿斤小米，东北修八个，关内修三个，就要十多亿斤小米，飞机场外还有许多设施，所费甚大。再有工厂搬家，许多工业无法按计划生产下去。军事上，除装备之外，还有兵力问题，鸭绿江一千多里的防线，需要多少部队！而且年复一年，不知它哪一天打进来。这样下去怎么能安心生产建设？况且敌人如果将朝鲜侵占了，也不会就此罢手。所以，从朝鲜在东方的地位和前途的展望来说，我们不能不援助；从唇齿相依的关系来说，我们也不能不援助。这是敌人把火烧到了我们的大门口，并非我们惹火烧身。

一个月前，就是说美军在仁川登陆以前，我们曾经考虑过，美帝打到三八线〔28〕后是否会停止，而后转为外交的谈判。在敌人占领汉城以后，尼赫鲁〔29〕曾经对我们说，三外长会议〔30〕已经说好，不过三八线，如要过三八线也要提到联合国来决定。但我们得到的情报是，我们要稳住中国，过三八线，过了以后，再搞中国。我们看穿了骗局，所以在九月三十日声明：对美帝侵略朝鲜我们不能置之不理〔31〕。十月一日、二日的消息是美军已过三八线，南朝鲜军则在三八线以北深入很远。我们曾找印度驻华大使指出，以上情况与尼赫鲁所说不同，我们对朝鲜问题不能不管，要他通过尼赫鲁转告贝文〔32〕。过了几天，敌人的推进并不停止。不久，贝文通过尼赫鲁向我表示，过了三八线到距鸭绿江四十英里时即可停止。当时敌人已进到平壤。目前，敌人又由平壤北进。这显然是对我们第二次欺骗。如此下去，我们如坐视不救，敌人必然继续前进，咄咄逼人，直到鸭绿江边，然后再做第二步文章。

所以，我们要理，要管。但如何理？如何管？要有进一步的决策。过去我们是管过理过的，例如向联合国控诉等。现在这样已经不够了，应有新的决策。美帝国主义的政策是一步步地制造并扩大战争。如果我们予以打击和斗争，它可能缩回去，否则它必然照计划继续推进。

美帝国主义在东方实行麦克阿瑟〔33〕的政策，利用日本的基地，继承日本军国主义的衣钵，沿袭着甲午战争〔34〕以来的历史，走吞并中国必先占领东北，占领东北必先占领朝鲜的老路。不过日本帝国主义是用四十多年的时间逐步进行的，而美帝国主义则要在四五年内来完成。

历史的教训是：对于日本帝国主义的侵略，我国一派主抗，一派主让，让到七七事变〔35〕，如果没有中国共产党和中国人民的抵抗，还抗不起来。甲午之战也是抗，不过那是在统治者中的抵抗，由腐败的朝廷领导，没有人民的支持，结果失败了。如果是人民的国家，就不会如此。

现在对美帝如果不抵抗，一着输了，就会处处陷于被动，敌人将得寸进尺。反之，如果给以打击，让它在朝鲜陷入泥坑，敌人就无法再进攻中国，甚至会影响它派兵到西欧的计划。这样，敌人内部的矛盾也会发生。总之，如果我们让，只会缓和敌人内部的矛盾；管，则会促使敌人内部矛盾加深。只有管，才能使敌我力量的对比发生变化。不过，我们过去的管法现在已经无效，只有拿出力量来管，才能起作用。

朝鲜问题对于我们来说，不单是朝鲜问题，连带的是台湾问题。美帝国主义与我为敌，它的国防线放到了台湾海峡，嘴里还说不侵略不干涉。它侵略朝鲜，我们出兵去管，从我国安全来看，从和平阵营的安全来看，我们是有理的，它是无理的。

美帝国主义用武力压迫别国人民，我们要使它压不下来，给它以挫折，让它知难而退，然后可以解决问题。我们是有节制的，假如敌人知难而退，就可以在联合国内或联合国外谈判解决问题，因为我们是要和平不要战争的。必须由朝鲜人民自己解决自己的问题，外国军队必须退出朝鲜。如果解决得好，美帝国主义受到挫折，也可以改变台湾海峡的形势和东方的形势。我们力争这种可能，使国内外人民一致起来，动员起来。

还有另一种可能，敌人愈打愈眼红，打入大陆，战争扩大。敌人孤注一掷的可能性是存在的，因为美帝有疯狂的一派，我们应该做这方面的准备。我们并不愿意战争扩大，它要扩大，也没有办法。我们这一代如果遇着第三次世界大战，为了我们的子孙，只好承担下来，让子孙永享和平。不过我们绝不挑起世界大战。我们应力争前一种前途，力争和平。但也准备应付后一种可能，应付世界大战。

既然要拿出力量来管，那么我们的力量如何？

我们的陆军是能够解决问题的，但是空军海军不足，因为我们在去年春天才开始建空军和海军。那么是否要等到我们力量强大时再抵抗呢？不行。那样敌人就会把朝鲜压了下去，气焰会更加高涨，敌我力量对比会相距更远。所以我们必须全面地发展地考虑问题，到斗争中去增强自己，在狂风暴雨中锻炼自己。革命的力量有时看起来是劣势，在斗争过程中却会变为优势。当然，这需要一定的时间，要付出一定的代价。另外，我国大陆防卫的力量也要顾到。敌人可能来轰炸，或者用蒋介石的空军来轰炸，或登陆袭扰，我们应增强防卫力量。政治上，我们有同盟国家、友好国家的支援，力争和平。方式上，我们采取志愿军的形式，无须宣战。宣传上，我们应该广泛宣传抗美援朝，保卫和平。同时，我们在国内要镇压敌特的捣乱，巩固广大人民内部的团结，经济建设不能停止，重工业要有重点地恢复，水利、铁道、纺织这几方面的建设要不动摇地进行，并且要照顾到人民生活的改善。

＊这是在中国人民政治协商会议第一届全国委员会第十八次常务委员会上的报告。

