# 加强老根据地的工作

中文马克思主义文库 -> 周恩来
加强老根据地的工作
（一九五一年——一九五二年）

一　下山不忘山，进城不忘乡*
（一九五一年十月九日）

各位同志：

你们从老远的地方来到了北京。南方老根据地的同志是从广东、四川、江西、湖北、安徽、浙江等省来的。北方老根据地的同志是从陕北、东北、华北等地来的。志愿军战斗英雄的代表是从朝鲜前线来的。解放军的战斗英雄是从各大军区来的。这是很不容易的事。今天借这个机会，中共中央、中央人民政府和各大区的负责同志，都来到这里同大家见见面。

今天看到你们真是高兴。我们离别已经好些年了，有十年的，还有二十年的。中国革命进行了三十年。一九二七年大革命失败后，毛主席带着队伍到了井冈山，在农村建立根据地，这样才使我们的力量生长起来，依靠这个力量，我们的党、我们的军队都得到发展。革命由南发展到北，军队由红军、八路军和新四军发展到人民解放军，最后打垮了蒋介石，取得了全国性的胜利，建立了新中国。去年我们的志愿军到了朝鲜，和朝鲜人民军一起打败了美国侵略者。这些胜利是得来不易的。在毛主席的领导下，依靠大家长期的英勇奋斗，才取得今天的胜利。饮水思源，我们应该向你们致敬，向你们代表的各老根据地的人民致敬，致谢。在这三十年当中，不知牺牲了多少人，我提议，大家起立为这些烈士志哀。

同志们，你们来到北京是不容易的。你们不只看到了毛主席，看到了我们的首都，还看到了我们军队的力量，看到了人民对我们党、我们领袖的热爱。希望你们回去以后，把这些告诉广大的人民和军队，进一步增强胜利的信心。

这次中央人民政府派遣访问团到各个老根据地，听到了一些意见。有的同志说，革命胜利了，不要下了山就忘了山，进了城就忘了乡。我们应不应该下山，应不应该进城呢？应该的。假若不下山、不进城，就不能够取得今天全国性的胜利，革命就不会成功，那我们作了那么大的牺牲，付出那么多的代价，就没有意义了。有些代表大概还记得，在我们离开瑞金以后，老根据地的人民遭到白匪的残杀。假若没有今天的胜利，我们能够回去吗？同志们，山是应该下，城也应该进。我们的胜利是依靠了农村的，但今后农民生活的改善，还必须依靠城市。革命就是为了使全国人民不再过苦日子，要过上好的生活。应该下山，应该进城。但是正如老根据地的同志所说的那样，下了山不应该忘了山，进了城不应该忘了乡。如果忘了，就是忘本。中国革命过去是以农村为根据地的，如果忘了这些根据地，就不是毛主席的好学生，就应该受到批评。毛主席这次特别派访问团去，就是为了关心老根据地的人民。访问不只是为了看看，而是想尽力解决一些问题，当然不可能一下子把所有的问题都解决。现在战争尚未结束，志愿军还在朝鲜作战，国家还有困难。在取得全国性胜利后的今天，我们还不能够转过手来大力改善生活，还须进一步克服困难，努力恢复和发展生产，并加强我们军队的力量，使美帝国主义不敢发动大战。我想老根据地的同志们是会理解这一点的。

我们有些干部对改善老根据地的群众生活关心不够，应该承认错误。今后各省的省委和政府要关心老根据地的事，每省应该有一个副主席专门负责老根据地的工作，每年至少要到各地看一两次，帮助老根据地的人民解决一些困难。各级人民代表会议〔22〕要有一定数量的军烈属代表参加。如果下面不这样做，你们可以给政府写信，给我写信，给党中央写信，我们一定予以答复。这样做，也会使我们声息相通，更加了解。

你们提出来的几个具体问题，如贷款、修路、兴修水利、城乡交流等，已交政务院财政经济委员会讨论，帮助你们解决一些问题。

文教方面，要在老根据地增设小学、中学，还要办些工农学校，开展成人教育和干部教育。有的同志说，大干部到了北京，小干部到了省，乡下无干部。这句话是有一定道理的。老根据地为全国培养了干部，这是很大的光荣。现在乡下干部少了，应该很好地培养新干部，并且帮助现有干部提高政治文化水平，以适应工作的需要。

卫生工作也要作为重点。最近我看到一个报告，反映陕北保安县的婴儿死亡率很高，这是多么令人痛心的事！当年我们在瓦窑堡站不住脚退到了保安，保安人民为革命出了力。现在知道那个地方的婴儿死了那么多，于心何安！我们已命令卫生部派医疗队到那个地方去。象这样的事，今后是不应该发生的。

还听说在乡下轻易看不到戏和电影。我们也下了命令，先让北京的剧团十一月份到乡下去，为农民群众演出，争取大家都能看一看。

在优抚方面也要规定更好的办法，不要发生“优新不优老，优生不优死”的现象。

参加人民代表会议的军烈属代表，应该在农村中由大家评选，再报上面批准。

以上这些事我们要发个文件〔61〕，传达到各地。

今天是老根据地代表和战斗英雄代表两部分人联欢。没有老根据地就不会有我们的解放军，解放军是老根据地人民的子弟兵。子弟兵看见老根据地的人就象看见了自己的叔叔、伯伯、兄弟、姐妹。大家可以在一起叙叙知心话，彼此给予安慰和鼓励。

最后，希望你们象毛主席说的那样：“发扬革命传统，争取更大光荣。”〔62〕

＊这是在中国人民解放军总政治部举办的来京参加国庆节观礼的战斗英雄代表和老根据地代表联欢会上的讲话。

二　大力扶植老根据地的经济和文化建设*
（一九五二年一月二十八日）

（一）中央人民政府派遣访问团访问各老根据地并邀请各老根据地人民代表来京参加国庆节观礼，加强了中央人民政府及各级人民政府与老根据地人民的联系，表扬了老根据地人民伟大的革命功绩，提高了老根据地人民热爱祖国和建设祖国的积极性。这一收获是很大的。

老根据地人民长期对帝国主义、国民党匪帮、封建地主的残酷压迫进行斗争，贡献最大，牺牲和受到的摧残也最大。解放后经过积极生产，部分地区已经恢复，有的地区甚至超过战前水平，但大部分老根据地因遭受战争创伤太重，且地处山区，交通不便，生产恢复很慢；其中若干地区又遭到水旱灾害的侵袭，特别是南方老根据地因重获解放为时较晚，荒芜现象仍多数存在，人民生活极为困难。因此，无论从政治上或经济上都必须十分重视加强老根据地的工作，大力领导与扶植老根据地人民恢复与发展经济建设与文化建设。

（二）加强老根据地的经济建设，是加强老根据地工作的中心环节。老根据地多系山地，生产条件比较困难，应该本着解决群众当前生活困难与长期建设相结合的方针，因地制宜，有计划地有重点地逐步恢复与发展农林畜牧与副业生产。一般地区应以农业为主，不宜耕耘的山岳地带应以林业与畜牧业为主，但均须同时极力注意利用当地一切条件发展当地有可能发展的手工业和副业，以增加群众收入。

1.恢复与发展农业生产：首先要补充农具，增加耕畜，养猪养羊，以克服当前缺乏农具、耕畜和肥料的困难。从长期与全局打算，山地应不再开荒，但凡能修成梯田的坡地，要尽快地逐步修成梯田，并集中力量提高现有耕地的单位面积产量。在有条件的地区，修塘，筑坝，开渠，打井，扩大灌溉面积；治河，防洪，闸山沟，修水库，做好水土保持。在粮食缺乏的地区，应提倡增种多产作物如红薯、马铃薯、南瓜等；在不缺粮食的地区应有计划地提倡栽种经济作物如棉、麻、烟等，以增加群众收入。

2.发展林业：提倡封山育林，禁止烧山燎荒，滥伐林木，挖掘树根，但必须照顾群众当前生产与生活的需要，反对机械的封死，进行合理的砍伐。在有条件地区应积极发展茶、桑、桐、橡、茶油、漆、果树等经济林木及其他用材林、薪炭林，并根据当地条件发展采集药材及竹木编制等副业。

3.发展畜牧：为增加老区人民收入，增加畜力、肥料，并供应毛纺制革原料，应大力增殖牛、羊、马、驴、骆驼、猪、鸡等。提高饲养技术，奖励繁殖。加强畜疫防治，畜种改良。为此，应有计划地建立防疫组织与繁殖场、配种站。

4.发展手工业与副业：许多老根据地农村副业收入占全部收入的百分之三四十以上，有的甚至超过农业生产的收入。农村副业和手工业是多种多样的，必须因地制宜有计划地加以恢复与发展，合作社和国营贸易机关应尽力帮助他们打开销路，以增加老根据地人民的收入。有些地区应特别提倡土特产与农产品的加工，如造纸浆、缫丝、烧酒、打蛋等。在兽害严重地区应组织群众打猎。

5.开采矿产：老根据地多系山地，各种矿产如煤、铁、石灰、钨、锡等蕴藏丰富，在不破坏矿藏、不影响大规模开采的原则下，可以有计划地扶助当地群众按照开矿的规定作小型开采。

（三）正因为老根据地多系偏僻穷困的山区，要求得老根据地经济建设的迅速恢复与发展和人民生活的改善，就必须首先解决以下几个问题：

1.恢复与开辟交通，这是改善老根据地人民生活的主要关键。必须分级负责，采取发动群众义务劳动为主、国家出资为辅的办法，有计划地修好老区主要的交通干线如公路、大车路、驮骡路、人行路以及河道等，利用当地一切可能利用的交通工具如大车、手推车、船筏等，并扶助群众添置这些交通工具，发展运输业。建立转运货站，把运输工作加以组织，以利推销土产和供应山区人民所需要的生产资料与生活资料。

2.增设国家贸易机构与供销合作社，组织私商上山，建立山区商业网，促进物资交流。合作社应以山区为发展重点之一，指导群众提高产品质量，进行规格教育，使当地土特产得到畅销。贸易公司、合作社应在对老根据地人民不挣钱甚至采取若干贴补办法的精神下，收购山货、土产，并解决油盐等日用必需品。

3.大力组织合作互助。在自愿互利的原则下，采取多种多样的形式，如互助组及养畜、造林、修滩等合作社，逐步把群众组织起来，有条件的地区可适当提倡农业生产合作社。

4.今后一般贷款应将老区列为重点之一。并应依据当地条件举办养牲畜、修水利、修梯田、购买农具等特殊贷款。举办贷款时应注意适当延长期限，简化手续，及时放发。这次拨给老根据地的特别救济费，应结合生产发出，或提出一部作为建设基金。

5.老根据地遭受的战争创伤深重，生产水平较低，人民生活很苦，为帮助老区人民迅速恢复元气，在负担上应以省为单位，适当加以调整。特别困难的老区，可宣布免纳一定时间的公粮。

（四）加强老根据地的文化教育、医疗卫生与优抚工作：

1.老根据地人民的政治水平一般较高，对文化生活的要求尤为迫切，必须提倡文化下乡，电影上山，普及社会教育，并在这些地区增办小学、中学、工农速成中学和各种技术学校，以培养工农出身的知识分子及各种专门人才。为此，应以省为单位适当调剂教育经费与教员。

2.老根据地人民的医药卫生要求也十分迫切。卫生机关应协同有关部门在老根据地大力开展卫生防疫运动，宣传卫生保育知识，设立卫生站与医院，派遣医疗队巡回治疗，开办卫生医疗人员训练班、新法接生训练班，帮助中医学习，设立中药铺，并注意供应海盐、海带等以避免粗脖子、柳拐子等病症，保护群众健康。

3.在优抚工作上，首先是收葬烈士遗骸，收集烈士事迹。老根据地烈军属多，他们缺乏劳动力，生产与生活困难最多，过去有些地方对优抚条例〔63〕的贯彻施行较差，今后必须切实执行优抚条例，加强对缺乏劳力的列军属的代耕工作，保证他们的生活不低于一般农民。县、区应定期召开烈军属、革命残废军人和优抚模范的代表会议，以便检查优抚工作，交流代耕经验，进行政治教育。各级人民代表会议也应有烈军属及革命残废军人的代表参加。

（五）老根据地的工作是一件光荣的任务，应作为有关省、专署考绩中的一项。凡辖区内有老根据地的各级人民政府要把老根据地的恢复与建设工作作为一九五二年的工作重点之一，并组织专门委员会，指定得力干部经常注意老根据地的工作，及时检查、督促。开好老根据地的代表会，并将加强经济建设作为会议的主要内容。除重获解放的时间较晚、土地改革〔10〕尚未完成或刚刚完成不久者外，一般老根据地的县、区、乡人民代表会议均应代行人民代表大会的职权，未建立区、乡人民代表会议者，应迅速建立区、乡人民代表会议，使富有斗争经验与政治认识的老根据地人民自己起来讨论与执行自己的事，选举自己的行政人员，发扬人民的积极性，“发扬革命传统，争取更大光荣”。

必须认识老根据地的恢复工作是长期性的工作。凡辖区内有老根据地的省份，应根据当地具体情况，拟定切实可行的老根据地工作计划，领导群众逐步实现，并予以必要而又可能的经济扶植，争取在三五年内改变老根据地的经济面貌，在经济发展的基础之上提高老根据地人民的物质生活与文化生活的水平。

＊这是由政务院总理周恩来署名发布的《中央人民政府政务院关于加强老根据地工作的指示》，刊载于一九五二年二月一日《人民日报》。

