# 我们的外交方针和任务

中文马克思主义文库 -> 周恩来
我们的外交方针和任务
（一九五二年四月三十日）

一、我们的外交方针

中华人民共和国建国以来，一直坚持和平的外交政策。我们坚持这一政策，相信以和平竞赛的方法来胜过帝国主义是完全可能的。当然，为防备帝国主义发动战争，我们应该在和平斗争中巩固国防，加强经济力量。要使帝国主义不敢发动战争，万一它发动战争，就叫它遭到失败。

我们在执行和平政策中的一些外交方针是：

（一）“另起炉灶”。一九四九年春，毛泽东同志就说过，我们的一个重要外交方针是“另起炉灶”，就是不承认国民党政府同各国建立的旧的外交关系，而要在新的基础上同各国另行建立新的外交关系。对于驻在旧中国的各国使节，我们把他们当作普通侨民对待，不当作外交代表对待。历史上，有在革命胜利后把旧的外交关系继承下来的，如辛亥革命后，当时的政府希望很快地得到外国承认而承袭了旧的关系。我们不这样做。毛泽东同志在《中华人民共和国中央人民政府公告》中宣告，我国同外国的外交关系要建立在平等、互利和互相尊重领土主权的基础上。这是一百多年来旧中国的政府所没有做到的。毛泽东同志宣告后，我们以外交部长的名义把这一公告送达各国政府，向世界各国表明了我们的态度。为了表示外交上的严肃性，我们又提出建交要经过谈判的手续。我们要看看人家是不是真正愿意在平等、互利和互相尊重领土主权的基础上同我们建立外交关系。在和平阵营方面，首先是苏联，然后是各人民民主国家相继承认了我们。这些国家是真诚地愿意在平等、互利和互相尊重领土主权的基础上同我们建立外交关系的。因此，我们同它们很快地建立了外交关系。对资本主义国家和原殖民地半殖民地国家，则不能不经过谈判的手续，看一看它们是否接受我们的建交原则。我们不仅要听它们的口头表示，而且还要看它们的具体行动。例如，它们如果在联合国中不投新中国的票，而去赞成蒋介石反动政府，那我们就宁愿慢一点同它们建交；反之，如印度、缅甸等，能够真的同国民党反动派断绝关系，那就可以在经过谈判之后同它们建交。

这一“另起炉灶”的方针，使我国改变了半殖民地的地位，在政治上建立了独立自主的外交关系。

（二）“一边倒”。在一九四九年党的建立二十八周年纪念日，即在中华人民共和国成立的前夕，毛泽东同志在《论人民民主专政》一文中提出了“一边倒”的方针，宣布了我国站在以苏联为首的和平民主阵营之内。之后，各民主党派、人民团体在七月七日发表了联合声明，拥护这一方针。我国在世界上明确地站在和平民主阵线一边，旗帜鲜明，打破了帝国主义的幻想。如果没有这一明确的宣布，帝国主义者就会胡思乱想地望着我们，如司徒雷登〔65〕在南京时还想钻空子。“一边倒”的方针给这种胡思乱想的人浇了一头冷水。

（三）“打扫干净屋子再请客”。帝国主义总想保留一些在中国的特权，想钻进来。有几个国家想同我们谈判建交。我们的方针是宁愿等一等。先把帝国主义在我国的残余势力清除一下，否则就会留下它们活动的余地。帝国主义的军事力量被赶走了，但帝国主义在我国百余年来的经济势力还很大，特别是文化影响还很深。这种情形会使我们的独立受到影响。因此，我们要在建立外交关系以前把“屋子”打扫一下，“打扫干净屋子再请客”。但是打扫要有步骤，不能性急。我们在美帝侵朝的时候，针对美帝对我国采取敌视政策并冻结我国财产的情况，先接管或冻结美帝在华资产，并接管美帝津贴的文化机关，特别是在抗美援朝运动〔26〕中肃清亲美崇美恐美思想，这在平时恐怕要几年几十年才能做到。

（四）“礼尚往来”。资本主义国家，你对我好，我也对你好；你对我不好，我也对你不好。针锋相对，来而不往非礼也。我们总是采取后发制人的办法，你来一手我也来一手。不怕它先动手，实际上它一先动手就马上陷于被动。开国后我们用“另起炉灶”和“打扫干净屋子再请客”这两手，在整个战略上处于主动地位。至于在具体事情上，是可以后发制人的。

（五）“互通有无”。我们开国以来就根据平等互利的原则同外国做买卖，不能象过去那样把中国作为它们的消费品市场。美帝国主义对我搞禁运，我们就以货易货，不用结汇，这对打破禁运是极有利的。我国出口的主要是农产品，换回来的是工业装备。我国同苏联和人民民主国家的贸易大大增加，对资本主义国家的贸易也增加了，我国的出口贸易额已经超过第二次世界大战前的数字。我们想扭转国民党时期的入超，变为出超，这是好的，但我们当前的目标是出入口平衡。现在我们入口的东西是我们所需要的，出口的东西如鸡蛋、猪肉，是人家所需要的，这种互通有无是互利的。

（六）团结世界人民。我们对苏联和各人民民主国家是“一边倒”的，对原殖民地半殖民地国家，对资本主义和帝国主义国家的人民也要团结争取，以巩固和发展国际的和平力量，扩大新中国的影响。

以上一系列的方针就体现了我们坚持的和平外交政策。

二、外交阵线

（一）建立什么样的外交阵线。外交是国家和国家间的关系，还是人民和人民间的关系？外交工作是以国家为对象，还是以人民为对象？我们要团结世界各国的人民，不仅兄弟国家的人民，就是原殖民地半殖民地国家和资本主义国家的人民，我们也都要争取。但就外交工作来说，则是以国家和国家的关系为对象的。外交是通过国家和国家的关系这个形式来进行的，但落脚点还是在影响和争取人民，这是辩证的。这一点要搞清楚。

（二）要分清敌我友。在建国开始时，我们就提出过这个问题。我和友是一方面，敌又是一方面。具体地分析一下，朋友方面以国家来分有两种：第一种是基本的朋友，第二种是一时的朋友。这后一种朋友也不完全一样，有的只能在某一时期内成为朋友，有的可以在相当长的时期内成为朋友，区别的主要关键是对战争与和平的态度。从国家的性质上来说，它们是属于资本主义世界的，但对战争它们不参加，表示中立，这是可能的。这种情形在第二次世界大战开始时有过，那时苏联争取瑞典保持中立〔66〕，这对当时的局势是有利的。假如那时挪威也被争取保持中立，对苏联会更有利，对欧洲的形势会更好一些。资本主义国家如果在同帝国主义的战争中保持中立，对我们是有利的。所以对这些国家，我们不能采取敌对态度，不要把它们挤到敌人的营垒里去，我们可以和它们做朋友。当然在战争中，问题可以看得更清楚，但在战争爆发前，我们就要有预见，努力做争取工作。在战争一旦发生时，这些国家守中立的可能性是存在的，站在和平阵营方面反对帝国主义的可能性虽然极少，但也不是绝对不可能的，这要看我们和平阵营力量的增长，要看敌人阵营的分化情形。

对帝国主义阵营也要有分析。追随美帝的国家毕竟是少数。在朝鲜战场，和美国在一起的虽然有十五个国家，可是万一战争发生在中国，是否也有那么多国家参加对中国作战呢？这是很值得怀疑的。敢于坚决和我们敌对并走上战场的究竟还是少数。资本主义世界并不是铁板一块，我们应该区别对待。

同我们最敌对的国家，应该对它坚决斗争。

同我国未建交、关系又较坏的国家，不能把它们看成同美帝一样。它们同美帝国主义之间有矛盾。我们应该给一些影响，使它们不过分同我敌对。

同我国正在谈判尚未建交的欧洲国家，它们不愿意同我闹翻，就悬在那里。

同我国已经建交的欧洲国家，对他们要分别对待，做好工作。

同我国已建交的东南亚国家，过去是殖民地，现在不仅形式已经改变，有自己的国会与政府，同时人民的觉醒也使得帝国主义不能不改变过去对殖民地的一套办法，而由当地资产阶级来统治。在这种情形下，如果现在还有人说它们是殖民地，那是不切合实际的。即使是现在的日本也不能说是美国的殖民地。日本人民的主要斗争对象有时是美国帝国主义，有时是本国政府。由帝国主义直接统治的才是殖民地。东南亚国家在战争与和平问题上同帝国主义有矛盾，我们要在战争时争取它们中立，在和平时争取它们同帝国主义保持距离。

伊斯兰教国家，我们同它们关系较少，影响也小。工作可以逐步进行。

我们要依靠进步，争取中间，分化顽固。这样可以使我们的外交工作更灵活一些，不是简单的两大阵营对立，没有什么工作可做。我们要这样来打开我们外交工作的局面。

三、外交工作的思想领导

我们的外交工作要绝对地接受无产阶级思想的领导，不能允许资产阶级和小资产阶级思想的侵蚀，当然更不能允许这些思想占据领导地位。我们的立场必须十分坚定，思想必须十分明确。

（一）坚持国际主义，反对狭隘民族主义。对这个问题，大家在理论上也懂得，但是在工作中，在一些具体问题上，就往往容易带着新中国胜利的骄傲，表现出狭隘的民族主义和大国思想。当然我们应该有民族自信心，可是如果有自大、骄傲的情绪，那就是狭隘的民族主义了，即使有时是不自觉的，也不好。每一个民族都有它的优点，值得我们尊重和学习。要肃清狭隘的民族主义思想，确立国际主义思想。

（二）坚持爱国主义，反对世界主义。我们的爱国主义是社会主义和人民民主主义的爱国主义，不是资产阶级的沙文主义〔67〕。我们反对失去民族自信心的、投靠大国的“世界主义”。美国所说的“世界主义”、“大国领导”，其目的是要小国永远跟它走，永远受它奴役剥削。我们的国际主义是要各国都独立平等。

社会主义的爱国主义不是狭隘的民族主义，而是在国际主义指导下的加强民族自信心的爱国主义。我们有些同志有时表现得失去立场，那是因为我们过去是半殖民地国家，羡慕资本主义国家的文明，不审查其中有无毒素，盲目崇拜。说中国一切都好或一切都不好，都是不对的，应该批判地接受一切中外的文化。《大公报》有一栏叫“中国第一”。中国哪里有那么多第一，这样提就不对，后来这一栏也只好取消了。新中国当然比旧中国好，祖国是可爱的，但我们仍然必须向外国学习。

（三）坚持集体主义，反对个人主义。外交工作是代表国家的，一切必须从集体出发，倘若从个人出发，就一定很危险。任何荣誉都是来自毛泽东思想的胜利和人民群众的努力，都是国家的荣誉。外交工作中不容许有个人打算，不要因为人家一说好就沾沾自喜，应该想这是人民的光荣；如果人家说坏，就要检查一下我们的工作是否做错了，要把个人完全溶化在集体当中。

（四）坚持无产阶级的纪律性，反对自由主义。我们强调高度自觉的、合乎党的利益的纪律性，丝毫不能允许自由主义存在。乱说乱搞就会出乱子。外交是国家与国家的关系，外国工作的一切都必须注意事先请示、事后报告。国家同国家办事，说了就得算数，所以多说不如少说。但是，是不是什么都不说呢？不是。已经宣布的事，已经办成功的事，已经决定了的事都可以说；尚未宣布的，经验还不成熟的不能说。因为这不是在一个党内，而是办国家同国家之间的事。在一定原则下可以有一定限度的机动，也就是临机应变，但对新的问题处理迟缓一些并不是错误。经验不足时，还是慢一些好。

（五）坚持民主集中制，反对官僚主义。我们大家对外交工作的经验都不多，还是要发扬民主。“三个臭皮匠顶个诸葛亮”。多听取大家意见是必要的，但是还要有集中。使馆内的民主一定要做到。光有集中，没有民主，就成为官僚主义了。我们应该提倡民主，才能克服官僚主义。

（六）要求有高度党性，反对政治空气稀薄。政治空气首先要求有高度的党性，锻炼同志们的思想，一切从原则出发。政治化是多方面的。把原则变成教条来背诵不是政治，轻一点说是书呆子，重一点说是教条主义者。要调查研究，分析问题。平时谈生活、谈文艺都要注意从原则出发，这样，庸俗空气就稀薄了，政治空气就浓厚了。当然，并不是说只有张口就是马克思列宁主义才叫做政治空气浓厚。

（七）提倡勤俭朴素的作风，反对资产阶级的铺张浪费思想。我们的外交工作中有不少浪费，这是受了资产阶级思想的影响。我们在生活享受方面处处想跟苏联比是不对的。苏联在十月革命后也是十分俭朴的。毛泽东同志主张不要去提倡那些形式的东西，因为不适合我们现时的经济情况。生活上同他们比是不对的，今天我们的生产还没有发展到他们那样的水平。

＊这是在一次我国驻外使节会议上的讲话节录。

