# 为祖国锻炼身体

中文马克思主义文库 -> 周恩来
为祖国锻炼身体
（一九五四年二月二十一日）


　　体育运动委员会成立一年多来，做了很多工作，全国体育运动的情况起了变化。为了实现过渡时期的总路线，建设社会主义，需要增强人民的体质。我国人民的体质弱，是由于封建制度和帝国主义长期的束缚和压迫造成的。毛泽东同志特别强调要增强人民体质。我们向社会主义、共产主义社会前进，每个人要在德、智、体、美等方面均衡发展。不均衡地发展，一定会有缺陷，不仅影响个人能力的发挥，对国家也不利。均衡发展是要思想和身体都健康。思想健康和身体健康是相互影响的。
　　目前的任务是要发展生产、加强国防，这都需要我们有健康的身体。实践表明，工业越发展，越需要高度的技术，而技术越高，速度越快，越需要劳动者既灵巧又有耐力。我国人民灵巧是有的，耐力则不够。同样，要掌握现代化的武器如飞机、坦克等，也必须有健康的身体。所以，开展“劳卫制”〔93〕运动不只是为了个人的身体健康，而且是为了保卫祖国、建设社会主义，这是一个政治任务。
　　人民体质的增强虽然不容易，但总是可以做到的。只要坚持开展体育运动，五年、十年、十五年，中国人民的体质就会大大改变。我问过专家，他们也说五年至十年左右就可以了。先天体质弱可以锻炼。我自己在未进学校以前，受封建家庭的束缚，身体很弱，进了学校以后就改变了。青年人的体质是可以改变的。我们最大的希望是三十岁以下的青年，他们在国防和生产战线上都是一支重要的力量，掌握高度的科学技术和现代化的武器，主要是依靠他们。要在工厂、学校和农村中提倡和开展体育运动，工作做得好，经过五年时间，人民的体质会起变化。毛泽东同志提出的“三好”，把身体好放在前面，只有身体好才能学习好、工作好，才能均衡地发展。我们一定要把体育运动和国家前途连结起来，这是一个伟大的改造。年纪大一点的人也要锻炼，当然比青年要困难一些。身体健康了，能够多活些年，看看社会主义不是更好吗？中国人民的体质增强了，有了健康的身体，能够掌握现代化的武器，有了这样的国防，帝国主义还敢不敢侵略我们？它就得考虑。所以，健康的身体是建设和保卫祖国的一个重要条件。这样看问题，就可以促进体育运动的发展。
　　当前体育运动的方针是要普及和经常化。在普及的基础上才能提高，经常化了才会出人才。我们的国家大，人口多，要普及比较困难，但如能普及到几千万人，肯定会出很多人才。只要体育运动做到普及和经常化并加以正确的指导，人民的体质一定会大大增强。今后两三年内，我们不可能在国际比赛中得到多少冠军，因为没有经常锻炼的基础。吴传玉〔AA〕是个华侨，他是经过长期锻炼才取得成功的，没有长期的锻炼是不会得到冠军的。后年的奥林匹克运动会，我们不要希望参加太多的项目。我们的体育运动如果发展得当，六年以后，到一九六○年，一定会出现许多好选手。我们的体育运动与资本主义国家的不同。我们的体育运动是有群众基础的，是有远大前途的。
　　实现上面这个方针，关键在于领导，不仅是体委，两个教育部〔95〕、各个行政部门也有责任。政务院可考虑发个通知，提倡早操和工间操，先在北京的中央各机关试行。今天会议的精神，两个教育部、工青妇各团体都要传达。做工作要上下结合，由上而下，由下而上。今天的会议是由上而下。由下而上是群众监督。还要授权体委进行检查，检查出哪个机关妨碍体育运动，就提出来“将他一军”。检查不仅是看他们开展体育工作有无缺点，而且要配合卫生部门检查健康状况，看效果如何。机关干部的身体好坏，部门行政领导起码是办公厅主任要负责任。在体育运动普遍开展的基础上，还可以进行业余比赛。看打球虽好，但主要的是自己参加体育锻炼。宣传也很重要，从政治上到技术上都要广泛宣传。


　　＊这是在政务院第二百零五次政务会议上的讲话。



