# 在亚非会议全体会议上的发言

中文马克思主义文库 -> 周恩来
在亚非会议全体会议上的发言
（一九五五年四月十九日）


主要发言

主席、各位代表先生：
　　举世瞩目的亚非会议〔96〕已经开始。中华人民共和国代表团能同与会的各国代表团一起在这个会议上讨论我们亚非国家的共同问题，感到非常高兴。我们能够在这里会晤，首先要感谢缅甸、锡兰、印度、印度尼西亚和巴基斯坦五个发起国家的倡议和努力，我们还应当感谢这次会议的主人印度尼西亚共和国政府为会议作了很好的安排。
　　亚非两洲有这么多的国家在一起举行会议，这在历史上还是第一次。在我们亚非两洲的土地上生活着全世界半数以上的人民。亚非人民曾经创造过光辉灿烂的古代文化，对人类作出了巨大的贡献。近代以来，亚非两洲的大多数国家在不同程度上遭受了殖民主义的掠夺和压迫，以致被迫处于贫困和落后的停滞状态。我们的呼声受到抑制，我们的愿望受到摧残，我们的命运被旁人摆布，因此我们不得不起而反对殖民主义。由于同样的原因而受到的灾难和为了同样的目的而进行的斗争，使我们亚非各国人民容易互相了解，并在长期以来就深切地互相同情和关怀。
　　现在亚非地区的面貌已经发生了巨大的变化。越来越多的亚非国家摆脱了或正在摆脱着殖民主义的束缚。殖民国家已经不能用过去那样的方式来进行掠夺和压迫。今天的亚洲和非洲已经不是昨天的亚洲和非洲。亚非两洲的许多国家，经过长期的努力，已经把他们的命运掌握在自己手中。我们的会议反映了这一深刻的历史变化。
　　虽然如此，殖民主义在这个地区的统治并没有结束，而且新的殖民主义者正在谋取旧的殖民主义者的地位而代之。不少亚非人民还在过着殖民地的奴隶生活，不少亚非人民还在受着各族歧视，他们的人权遭受着摧残。
　　我们亚非各国人民争取自由和独立的过程是不同的；但是，我们争取和巩固各自的自由和独立的意志是一致的。不管我们每一个国家的具体情况如何不同，我们大多数国家都需要克服殖民主义统治所造成的落后状态，我们都应该在不受外来干涉的情况下按照我们各国人民的意志，使我们各自的国家获得独立的发展。
　　亚非人民曾经长期遭受侵略和战争的苦难。许多亚非地区的人民曾经被殖民主义者强迫充当进行侵略战争的炮灰。亚非人民不能不痛恨侵略战争。他们知道，新的战争威胁不仅危害到他们国家的独立发展，而且还要加强殖民主义的奴役。因此，我们亚非人民更加深切地感觉到世界和平和民族独立的可贵。
　　基于这些情况，保障世界和平、争取和维护民族独立并为此目的而促进各国间的友好合作就不能不是亚非各国人民的共同愿望。
　　接着朝鲜停战〔26〕之后，日内瓦会议〔97〕曾经在尊重民族独立的基础上，得到科伦坡五国会议〔98〕的支持，达成了印度支那的停战〔99〕。当时，国际的紧张局势确曾得到一定程度的缓和，给全世界人民特别是亚洲人民带来了新的希望。但是，跟着而来的国际形势的发展却和人民的希望相反。无论在东方和西方，战争危机都在增加。朝鲜人民和德国人民要求和平统一的愿望受到阻挠。日内瓦会议关于恢复印度支那和平问题的协议〔100〕有被破坏的危险。美国在台湾地区继续制造紧张局势。亚非以外国家在亚非地区建立的军事基地越来越多。他们公开鼓吹原子武器是常规武器，准备原子战争。亚洲人民不能忘记第一颗原子弹是落在亚洲的土地上〔101〕，第一个死在氢弹试验下的是亚洲人〔102〕。亚非各国人民和世界其他地区的人民一样，不能不关切日益增长的战争威胁。
　　但是进行侵略、准备战争的人究竟是极少数。世界上不论是生活在哪一种社会制度中的绝大多数人民都要求和平，反对战争。世界各国人民的和平运动有了更加广泛和深入的发展。他们要求终止扩军备战的竞赛，首先各大国应该就裁减军备达成协议。他们要求禁止原子武器和一切大规模毁灭性武器。他们要求将原子能用于和平用途，为人类创造幸福。他们的呼声已经不能被忽视，侵略和战争的政策已经日益不得人心。战争策划者日益频繁地诉之于战争威胁，作为推行侵略政策的工具。但是，战争威胁是吓不倒任何具有抵抗决心的人的，它只能使威胁者自己陷于更加孤立和更加混乱的地位。我们相信，只要我们同世界上一切愿意和平的国家和人民一道，决心维护和平，和平是有可能维护得住的。
　　我们大多数亚非国家，包括中国在内，由于殖民主义的长期统治，经济上还很落后。因此，我们不仅要求政治上的独立，同时还要求经济上的独立。当然，我们要求政治独立并不是要对亚非地区以外的国家采取排斥的政策。但是，西方国家控制我们命运的时代已经过去了，亚非国家的命运应该由亚非各国人民自己掌握。我们要努力实现各国的经济独立，这也并不是要排斥同亚非地区以外的国家的经济合作。但是，我们要求改变西方殖民国家对东方落后国家的剥削状态，我们要求发展亚非各国独立自主的经济。争取完全独立是我们大多数亚非国家和人民长期奋斗的目标。
　　在中国，自从人民作了自己国家的主人以后，我们的一切努力就是要消除长期的半殖民地社会遗留下来的落后状态，把我们的国家建设成为一个工业化的国家。五年以来，我们恢复了遭受长期战争破坏的国民经济，并且从一九五三年起开始了经济建设的第一个五年计划。由于这些努力，我们在各个主要生产部门，例如钢铁、棉布、粮食的生产量，都已经超过了中国历史上任何一个时期的水平。但是，这些成就比之于我们的实际需要还微小得很，比之于工业高度发展的国家，我们还落后得很。正象其他的亚洲国家一样，我们迫切地需要一个和平的国际环境，来发展我国独立自主的经济。
　　反对殖民主义、维护民族独立的亚非国家更加珍视自己的民族权利。国家不分大小强弱，在国际关系中都应该享有平等的权利，它们的主权和领土完整都应该得到尊重，而不应受到侵犯。所有附属国人民都应该享有民族自决的权利，而不应遭受迫害和屠杀。各族人民不分种族和肤色都应该享有基本人权，而不应该受到任何虐待和歧视。但是，我们不能不注意到：对突尼斯、摩洛哥、阿尔及利亚和其他争取独立的附属国人民的暴力镇压还没有停止；在南非联邦和其他地区进行着的种族歧视和种族主义的迫害还没有制止；巴勒斯坦的阿拉伯难民问题还没有解决。
　　现在，应该说，反对种族歧视、要求基本人权，反对殖民主义、要求民族独立，坚决维护自己国家的主权和领土完整，已经是觉醒了的亚非国家和人民的共同要求。埃及人民为收复苏伊士运河地区的主权和伊朗人民为收复石油主权而进行的斗争，印度对果阿和印度尼西亚对西伊里安岛恢复领土权利的要求，获得了亚非地区许多国家的同情。同样，中国解放自己领土台湾的要求也获得了亚非地区一切具有正义感的人民的支持。这证明我们亚非各国人民是互相了解、互相同情和互相关切的。
　　只有互相尊重主权和领土完整，和平才有保障。对于任何一个国家主权和领土的侵犯，对于任何一个国家内政的干涉，都不可避免地要危及和平。如果各国保证互不侵犯，就可以在各国的关系中创造和平共处的条件。如果各国保证互不干涉内政，各国人民就有可能按照他们自己的意志选择他们自己的政治制度和生活方式。日内瓦会议关于恢复印度支那和平的协议就是在有关各方保证尊重印度支那各国的独立、主权、统一和领土完整并对其内政不予任何干涉的基础上达成的。据此，日内瓦会议并规定，印度支那各国不参加军事同盟和建立外国军事基地。这就是为什么日内瓦会议能够为建立和平地区创造了有利的条件。但是在日内瓦会议之后，我们却看到了一种相反的情况在发展，这是不利于印度支那各国人民的利益的，也是不利于和平的。我们认为，日内瓦会议关于恢复印度支那和平的协议应该严格地和忠实地予以履行，任何方面不得加以干涉和阻挠。朝鲜的和平统一问题也应该按照同样的原则予以解决。
　　我们亚非国家需要在经济上和文化上合作，以便有助于消除我们在殖民主义的长期掠夺和压迫下所造成的经济上和文化上的落后状态。我们亚非国家之间的合作应该以平等互利为基础，而不应该附有任何特权条件。我们相互之间的贸易来往和经济合作应该以促进各国独立经济发展为目的，而不应该使任何一方单纯地成为原料产地和消费品的销售市场。我们相互之间的文化交流应该尊重各国民族文化的发展，而不抹煞任何一国的特长和优点，以便互相学习和观摩。
　　在我们亚非地区的各国人民日益掌握了自己命运的今天，即使我们在目前经济和文化的合作规模还不可能很大，但是，可以肯定地说，这种建立在平等互利的基础上的合作是有远大的发展前途的。我们深信，随着我们亚非国家工业化的发展和人民生活水平的提高，随着各国间贸易关系中人为的外来的障碍的消除，我们亚非各国间的贸易来往和经济合作将会日益增进，文化交流也将日益频繁。
　　根据互相尊重主权和领土完整、互不侵犯、互不干涉内政、平等互利的原则，社会制度不同的国家是可以实现和平共处的。在保证实施这些原则的基础上，国际间的争端没有理由不能够协商解决。
　　为了维护世界和平，我们处境大致相同的亚非国家首先应该友好合作，实现和平共处。过去殖民统治在亚非国家间所造成的不和和隔阂，不应该继续存在。我们应该互相尊重，消除互相间可能存在的疑虑和恐惧。
　　中华人民共和国政府完全同意南亚五国总理在茂物会议〔103〕联合公报中所确定的关于亚非会议的目的。我们并认为，为了对于促进世界和平和合作作出贡献，亚非各国应该首先根据共同的利益，谋求相互间的亲善和合作，建立友好和睦邻的关系。印度、缅甸和中国曾经确定了和平共处五项原则〔104〕作为指导相互关系的原则。这些原则获得了越来越多的国家的支持。本着这些原则，中国同印度尼西亚关于两国侨民国籍问题的初步谈判已经取得了良好的结果。在日内瓦会议时，中国也曾表示愿意在这五项原则的基础上同印度支那各国发展友好的关系。根据这五项原则，中国同泰国、菲律宾等邻国的关系没有理由不能获得改善。中国愿以严格遵守这些原则作为它同亚非其他国家建立正常关系的基础，并愿促进中国和日本关系的正常化。为了增进我们亚非各国间的相互了解和合作，我们建议亚非各国的政府、国会和民间团体实行互相的友好访问。
　　主席，各位先生，任意摆布亚非人民命运的时代已经一去不复返了。我们相信，如果我们决心维护世界和平，就没有人能够把我们拖入战争；如果我们决心争取和维护民族独立，就没有人能够继续奴役我们；如果我们决心友好合作，就没有人能够分裂我们。
　　我们亚非国家所需要的是和平和独立，我们并无意于使亚非国家同其他地区的国家对立，我们同样需要同其他地区的国家建立和平合作的关系。
　　我们的会晤是难得的。尽管我们中间存在着许多不同意见，但是这不应该影响我们所具有的共同愿望。我们的会议应该对于我们的共同愿望有所表示，使它成为亚非历史值得珍贵的一页。同时，我们在这次会议中建立起来的接触应该继续保持，以便我们对于世界和平能够作出更大的贡献。
　　印度尼西亚共和国总统苏加诺阁下说得对，我们亚非人民必须团结起来。
　　让我们预祝会议成功。


补充发言

主席，各位代表：
　　我的主要发言现在印发给大家了。在听到了许多代表团团长的一些发言之后，我愿补充说几句话。
　　中国代表团是来求团结而不是来吵架的。我们共产党人从不讳言我们相信共产主义和认为社会主义制度是好的。但是，在这个会议上用不着来宣传个人的思想意识和各国的政治制度，虽然这种不同在我们中间显然是存在的。
　　中国代表团是来求同而不是来立异的。在我们中间有无求同的基础呢？有的。那就是亚非绝大多数国家和人民自近代以来都曾经受过、并且现在仍在受着殖民主义所造成的灾难和痛苦。这是我们大家都承认的。从解除殖民主义痛苦和灾难中找共同基础，我们就很容易互相了解和尊重、互相同情和支持，而不是互相疑虑和恐惧、互相排斥和对立。这就是为什么我们同意五国总理茂物会议所宣布的关于亚非会议的四项目的，而不另提建议。
　　本来，对于美国一手造成的台湾地区的紧张局势，我们很可以在这里提出如同苏联所提出的召开国际会议谋求解决的议案，请求会议加以讨论。中国人民解放自己领土台湾和沿海岛屿的要求是正义的，这完全是内政和行使自己的主权，并得到许多国家的支持。我们也很可以提议会议讨论承认和恢复中华人民共和国在联合国的合法地位问题。去年，科伦坡五国总理会议，还有亚非其他国家，都曾经支持中华人民共和国在联合国的地位。而且，中国在联合国所受的不公正待遇，也可以在这里提出批评。但是，我们并没有这样做。因为这样一来，就很容易使我们的会议陷入对这些问题的争论而得不到解决。
　　我们的会议应该求同而存异。同时，会议应将这些共同愿望和要求肯定下来。这是我们中间的主要问题。我们并不要求各人放弃自己的见解，因为这是实际存在的反映。但是不应该使它妨碍我们在主要问题上达成共同的协议。我们还应在共同的基础上来互相了解和重视彼此的不同见解。
　　现在，我首先谈不同的思想意识和社会制度问题。我们应该承认，在亚非国家中是存在有不同的思想意识和社会制度的，但这并不妨碍我们求同和团结。第二次大战后，亚非两洲兴起了许多独立国家，一类是共产党领导的国家，一类是民族主义者领导的国家。前一类国家并不多。但是某些人所不喜欢的，就是六万万中国人民选择了中国共产党领导的、属于社会主义体系的政治制度，而不再为帝国主义所统治了。后一类国家很多，象印度、缅甸、印度尼西亚和亚非许多国家都是。我们这两类国家都是从殖民主义的统治下独立起来的，并且还在继续为完全独立而奋斗。我们有什么理由不可以互相了解和尊重、互相同情和支持呢？五项原则完全可以成为在我们中间建立友好合作和亲善睦邻关系的基础。我们亚非国家，中国也在内，不论在经济上或文化上都很落后。我们亚非会议既然不要排斥任何人，为什么我们自己反倒不能互相了解、不能友好合作呢？
　　次之，我要谈有无宗教信仰自由的问题。宗教信仰自由是近代国家所共同承认的原则。我们共产党人是无神论者，但是我们尊重有宗教信仰的人。我们希望有宗教信仰的人也应该尊重无宗教信仰的人。中国是有宗教信仰自由的国家，它不仅有七百万共产党员，并且还有以千万计的回教徒和佛教徒，以百万计的基督教徒和天主教徒。中国代表团中就有虔诚的伊斯兰教的阿訇。这些情况并不妨碍中国内部的团结，为什么在亚非国家的大家庭中不能将有宗教信仰的和没有宗教信仰的人团结在一起呢？挑起宗教纷争的时代应该过去了，因为从挑起那种纷争中得到利益的并不是我们中间的人。
　　第三，我要谈所谓颠覆活动的问题。中国人民为反对殖民主义所进行的斗争超过一百年。中国共产党领导的民族、民主的革命斗争也经历了近三十年的艰难困苦的过程，才终于达到了成功。中国人民在帝国主义、封建主义和蒋介石统治下所受的苦难是数也数不尽的，最后才选择了这个国家制度和现在的政府。中国革命是依靠中国人民的努力取得胜利的，决不是从外输入的，这一点连不喜欢中国革命胜利的人也不能否认。中国古话说：“己所不欲，勿施于人。”　我们反对外来干涉，为什么我们会去干涉别人的内政呢？有人说，中国在国外有一千多万华侨，可能利用他们的双重国籍来进行颠覆活动。但是，华侨的双重国籍问题是旧中国遗留下来的，蒋介石至今还在利用极少数的华侨进行对所在国的破坏活动。新中国的人民政府却准备与有关各国政府解决华侨的双重国籍问题。又有人说，在中国境内有傣族自治区威胁了别人。中国境内有几十种少数民族共四千多万人，其中傣族和相同系统的壮族将近千万人。他们既然存在，我们就必须给他们自治权利。好象缅甸有掸族自治邦一样，在中国境内各个少数民族都有他们的自治区。中国少数民族在中国境内实行自治权利，如何能说威胁邻邦呢？我们现在准备在坚守五项原则的基础上与亚非各国，乃至世界各国，首先是我们的邻邦，建立正常关系。现在的问题不是我们去颠覆别人的政府，倒是有人在中国的周围建立进行颠覆中国政府的据点。比如在缅甸边境就存在着蒋介石集团的残余武装分子，对中缅两国进行破坏。因为中缅友好，我们一直尊重缅甸的主权，信任缅甸政府去解决这个问题。
　　中国人民选择和拥护自己的政府，中国有宗教信仰自由，中国决无颠覆邻邦政府的意图。相反的，中国正在受着美国政府公言不讳地进行颠覆活动的害处。大家如果不信，可亲自或派人到中国去看。我们是容许不知真相的人怀疑的。中国俗语说：“百闻不如一见。”我们欢迎所有到会的各国代表到中国去参观，你们什么时候去都可以。我们没有竹幕，倒是别人要在我们之间施放烟幕。
　　十六万万亚非人民期待着我们的会议成功。全世界愿意和平的国家和人民期待着我们的会议能为扩大和平区域和建立集体和平有所贡献。让我们亚非国家团结起来，为亚非会议的成功努力吧！


　　＊这两个发言分别刊载于一九五五年四月二十日、二十一日《人民日报》。



