# 台湾的解放一定能够实现

中文马克思主义文库 -> 周恩来
台湾的解放一定能够实现
（一九五六年六月二十八日）

中国人民一定要解放台湾，这是我国六万万人不可动摇的共同意志。

我国政府曾经再三指出：中国人民解放台湾有两种可能的方式，即战争的方式和和平的方式；中国人民愿意在可能的条件下，争取用和平的方式解放台湾。毫无疑问，如果台湾能够和平解放，那么，对于我们国家，对于我们全体中国人民，对于亚洲和世界的和平，都将是最为有利的。

现在，和平解放台湾的可能性正在增长。这首先是因为目前国际形势肯定地趋向和缓，美国使用武力侵占台湾和干涉中国内政的行为，遭到了越来越多的爱好和平的国家和人民的反对。从国内形势说，我们伟大的祖国是更加壮大和巩固了，它比过去任何时候都更加使所有爱国的中国人感到自豪。现在，不但具有革命传统的台湾同胞，已经不愿意继续过那痛苦的奴隶生活，而希望早日回到祖国的怀抱；就是在那些从大陆上跑到台湾去的国民党军政人员当中，也有越来越多的人看到，只有实现祖国的和平统一，才是他们的唯一出路。自从我们发出争取和平解放台湾的号召〔118〕以后，在台湾和海外的国民党军政人员中，已经有不少人表示了他们的爱国愿望。我们相信，愿意促成台湾和平解放和祖国完全统一的人，必然会一天比一天增加，这将是不可抗拒的趋势。

大势非常清楚，台湾当局追随美国苟延残喘的局面是决不能持久的。他们所追随的外国势力，决不是什么可以指靠的力量；相反地，引狼入室的结果，不但会使他们失掉自己所有的一切，并且随时有被人暗算和遗弃的可能。人们可以从中美两国在日内瓦会谈〔119〕的不同态度中，得出重要的教训。中国政府始终坚持，只有中美两国在台湾地区的国际争端，才能由中美两国讨论和解决；至于台湾回到祖国的问题，不论采取什么方式，都只能而且完全可以由我们中国人自己处理，决不容外国干涉。可是，美国在谈判中却完全采取另外一种态度。它把台湾当作自己的殖民地，同中国讨价还价。人们还可以看到，现在美国不但侵占了台湾，把它的势力渗透到台湾的政治、军事、经济、文化各个方面，并且还在施展它所惯用的分裂阴谋，在台湾内部制造猜疑倾轧，企图加强控制，从中渔利。但是，美国侵略势力的这种愚弄中国人民、干涉中国内政和分裂中国民族团结的行为，已经引起了台湾国民党军政人员愈来愈强烈的不满。他们当中有不少人，已经表示再也不能忍受那种寄人篱下、随人俯仰的生活。他们要求提高民族自尊心，维护民族尊严，摆脱美国控制，并且要以独立自主的精神，处理自己的内部问题。我们欢迎他们的这种爱国主张。

我们是一贯主张全民族团结、一致对外的。为了我们伟大祖国和人民的利益，中国共产党人和国民党人曾经两度并肩作战，反对帝国主义。在抗日战争结束以后，我们也曾经努力争取实现国内的和平。中国人民即使在被迫拿起武器进行国内解放战争期间，甚至在大陆解放以后，也没有放弃和平谈判的努力。尽管这些年来，由于美国的武装干涉，我们和台湾的国民党军政人员走上了不同的道路，但是，只要大家以民族和祖国的利益为重，我们仍然可以重新携手团结起来。我们相信，我们久经忧患的伟大民族一定能够依靠我们自己的努力，实现祖国的完全统一。

现在，我代表政府正式表示：我们愿意同台湾当局协商和平解放台湾的具体步骤和条件，并且希望台湾当局在他们认为适当的时机，派遣代表到北京或者其他适当的地点，同我们开始这种商谈。

为了团结一切爱国力量早日实现祖国的完全统一，我愿意在这里再一次宣布，我们对于一切爱国的人们，不论他们参加爱国行列的先后，也不论他们过去犯了多大罪过，都本着“爱国一家”的原则，采取既往不咎的态度，欢迎你们为和平解放台湾建立功勋，并且还将按照他们立功大小，给以应得的奖励和适当的安置。

台湾的同胞从来就是中国人民不可分离的一部分。我们不但时时刻刻关怀着他们，从各方面支持他们反抗外国统治的斗争，而且随时准备欢迎他们参加祖国的社会主义建设，共享我们民族的荣誉。

我们了解一切家在大陆、身在台湾的国民党军政人员的处境，希望他们能够早日实现同家人团聚的愿望。他们可以同大陆上的亲友通讯，他们也可以回到大陆来作短期的省亲会友，我们准备给以各种方便和协助。

我们希望台湾的国民党军政负责人员，在和平解放台湾的事业中，发挥重要的作用。只要朝着这个方向努力，他们将来的地位就会得到肯定的保证。如果他们还有疑问的话，他们可以通过大陆上的亲友得到解释，或者派人来大陆考查，我们保证他们来去自由。

我们希望台湾的国民党军队人员积极地促成台湾的和平解放。如果这样做，他们就一定能够得到祖国和人民的信赖和照顾。过去在大陆上和平起义的将士所得到的待遇，可以作为先例。

我们也同样希望一切身在海外其他地方的国民党军政人员，为促进和平解放台湾而努力。只有这样，他们才能使自己免于流落异乡、受人轻视的命运。

我们重视海外广大的爱国侨胞在推动和平解放台湾的事业中所发挥的积极作用。我们希望曾经或者还在对祖国采取对立态度的少数海外华侨，认清是非，省察大势，跟广大的爱国侨胞站在一起，为促进和平解放台湾的爱国事业作出贡献。

祖国的大门对于所有的爱国分子都永远是敞开着的。任何一个中国人对于祖国统一的神圣事业都有权利和义务作出自己的贡献。依靠全民族的团结和全国人民的努力，台湾的解放是一定能够实现的。

＊这是在第一届全国人民代表大会第三次会议上的报告的第三部分。报告全文刊载于一九五六年六月二十九日《人民日报》。

