# 经济建设的几个方针性问题

中文马克思主义文库 -> 周恩来
经济建设的几个方针性问题
（一九五六年十一月十日）

八大〔126〕以后，对明年的计划数字已经修改多次。明年是很难安排的一年。必须早一点把明年计划的方针定下来，取得全会同意。今天，我想讲一讲几个方针性的问题。

第一个问题，根据刚才少奇同志的政治报告，我们从国际事件中所取得的教训，联系到我们的建设，有两点值得注意。

第一点，就是社会主义国家也可能犯而且有的已经犯了沙文主义〔67〕的错误。按照毛泽东同志的分析，这种错误，就是对外的大国主义，对内的大民族主义，对人民的专制主义。这样的错误在有的社会主义国家已经产生，那么，在我们这个社会主义国家是不是也可能产生呢？当然可能避免，而且应该尽力避免，但是也有可能产生，并且有些萌芽在过去的工作中已经发现。例如，对周围兄弟国家的大国主义的个别事件，对兄弟民族还有大汉族主义倾向，也产生过领导脱离群众不关心群众利益的事情，我们领导者的生活和工作制度有些特殊化官僚化。这就不能不使我们在建设中时常注意这些问题。

第二点，也就是刚才少奇同志说的，苏联和其他一些社会主义国家都是优先发展重工业，这个原则是对的，但是在发展中忽视了人民的当前利益。直接与人民利益关系最大的是轻工业、农业，轻视这两者就会带来不好的后果，就会发生经济发展上的严重不平衡。毛泽东同志在这几个月常说，我们又要重工业，又要人民。这样结合起来，优先发展重工业才有基础。发展重工业，实现社会主义工业化，是为人民谋长远利益。为了保卫人民的福利和社会主义成果，必须依靠人民。如果不关心人民的当前利益，要求人民过分地束紧裤带，他们的生活不能改善甚至还要降低水平，他们要购买的物品不能供应，那么，人民群众的积极性就不能很好地发挥，资金也不能积累，即使重工业发展起来也还得停下来。所以，这一经验也值得我们在建设中经常想到。一些社会主义国家发生的事件值得我们引为教训。

此外，在中国还有中国的特点，那就是封建性很大。我们尽管打倒了封建主义，但封建官僚的习俗在社会上还存在着。脱离群众，高高在上，生活特殊，讲究排场，中国的统治阶级过去是这样的，我们也很容易这样做。从上到下，凡叫“长”的，就容易被人家看得特殊一点。所以，社会主义制度在中国的土壤上实现以后，如果不有意识地经常地排除某些旧的社会习俗，它就会经常来侵蚀我们。

要重工业，又要人民。人民的问题对我们来说是人口众多，这有它的好处；但是人口众多也有一个困难，人多消费需要的量就大。衣食住行，首先是食。我国人口现在平均每年增长百分之二左右，每年增加一千多万人，这是一个可观的数目，而我们的粮食平均每年增长百分之三左右，增长量并不大。农业合作化可以使我们提高单位面积产量，增加复种面积。今年这么大的灾荒，我们的收成还是比去年增加了，这就是合作化的优越性，社会主义的优越性。可是我们也要看到，耕地面积、粮食产量总是增加得慢。不能把这方面的工作看得那么容易。昨天我在政治局会议上说了，要提倡节育。这个问题的发明权本来是邓小平同志的，后来邵力子〔127〕先生在人民代表大会上讲了。我们的党和青年团要用一定的力量宣传这个问题。这实际上是广大人民所需要的，首先是城市人民所需要的。现在看得很清楚，我们在短时期内还不可能使大家都就业，工资的增长也不可能使职工养活很多的家庭人口。我觉得甚至提倡晚婚也是有好处的。

第二个问题，毛泽东同志提出的十大关系〔128〕是党的八大的指导方针。在三大改造〔129〕高潮出现以后，全国人民的社会主义积极性空前高涨，各部门、各省市向中央提出了各种报告和要求。毛泽东同志到各地同各省市的同志接触，少奇同志在北京跟各部的同志接触，以后毛泽东同志又跟各部的同志谈话，觉得需要正确地解决这十大关系问题，我们的社会主义建设才能够安排得更恰当。这些关系的许多方面在八大报告中都提到了。但是我们要认识，这十大关系问题并不是一提出来就能解决得了的，具体的解决还需要今后在实践中、在采取具体措施中、在反对错误的倾向中不断努力。前五种关系直接联系到建设。比如农、轻、重的比例究竟如何才恰当？现在还不可能回答得很完满，必须经过多次反复摸索，才能使这三者的比例安排得比较恰当。一个时候恰当了，过一个时候还要修改。

第三个问题，八大规定的建设方针是，“为了把我国由落后的农业国变为先进的社会主义工业国，我们必须在三个五年计划或者再多一点的时间内，建成一个基本上完整的工业体系”。这个方针，把过去的为社会主义工业化而奋斗的提法具体化了，提出了建设一个基本上完整的工业体系的要求。我们的工业化，就是要使自己有一个独立的完整的工业体系。任何一个国家建设社会主义总要有一点独立的能力，更不用说象我们这样一个大国。太小的国家，原料很缺，不可能不靠旁的国家。而我们这样的大国，就必须建立自己的完整的工业体系，不然一旦风吹草动，没有任何一个国家能够支援我们完全解决问题。我们所说的在我国建立一个基本上完整的工业体系，主要是说：自己能够生产足够的主要的原材料；能够独立地制造机器，不仅能够制造一般的机器，还要能够制造重型机器和精密机器，能够制造新式的保卫自己的武器，象国防方面的原子弹、导弹、远程飞机；还要有相应的化学工业、动力工业、运输业、轻工业、农业等等。但是，应该指出，基本上完整并不是说一切都完全自足。就是大国也不可能什么都有。美国算是一个有完整工业体系的大国吧，但是有的东西它也没有，橡胶就没有。苏联也有它没有的东西。另外，所谓完整的工业体系，是不是一定要有很高的产量呢？当然，产量是要高一点，但是不一定很高，这个任务的实现是决定于东西的有无，不决定于是否有很高的产量。从这样的要求来看，我们觉得八大的决议上写三个五年计划或者再多一点的时间是恰当的。现在看，时间可能要长一点。

过去设想的远景规划，发展速度是不是可以放慢一点？经过八大前后的研究，我们觉得可以放慢一点。比如，原来设想钢产量在第三个五年计划的最后一年要达到年产三千万吨，肯定地说，照现在这个速度是不可能实现的。八大的建议已经把这个要求改变了。我们设想第三个五年计划的指标定在二千万到二千五百万吨上，将来如果执行得好，有可能超过，但是现在不能定到三千万吨。因为定到三千万吨，其他就都要跟上去。那就会象我们常说的，把两脚悬空了，底下都乱了，不好布局，农业、轻工业也会受影响，结果还得退下来。要达到原来远景规划设想的生产指标，肯定时间要更长一些，有可能要四个五年计划，或者在第四个五年计划期间。陈云〔78〕同志曾经在中央政治局会议上说，既然达不到，就应该允许在三个五年计划以外再加两年。我说，甚至可以设想加两年不够再增加一两年。这样一个大国，数量上的增长稍微慢一点，并不妨碍我们实现工业化和建立基本上完整的工业体系。这样，我们的计划就好安排了。不然，讨论起来，远景规划的几个数字就把自己框住了。

此外，还有两点也想提出来请大家考虑：

第一是关于八大建议的数字。这只是个建议，有某些达不到的指标是不是可以修改？我觉得是可以的。过去说计划就是法律，这实际上行不通。当然，计划成为废纸也不对。计划不合实际就得修改，实际超过了计划也得承认，计划不能一成不变。建议中有些数字当时觉得是恰当的，现在发现还有矛盾需要解决，那就应该解决，我想这是许可的。

第二是关于农业发展纲要四十条。这也是一个建议，是一个草案。在草案提出的时候毛泽东同志说，有些东西在实际执行中还要修改。实际上，某些数字已经勾掉了。草案现在执行快一年了，事实证明有些是需要重新研究的，这些并不是不可以修改的。比如扩大耕地面积，要求十二年内开垦一亿四千万亩显然是有困难的。如果每年开垦一千万亩，就要投资五亿元。这五亿元的投资，明年度无论如何也挤不出来，今后也不是每年都可以挤出来的。至于其他的组织工作、动员工作、各种条件的配合，还不去说它。

八大的建议和农业四十条，是规定了每年进度指标的。这两个文件经过我们研究以后觉得可以修改。上不去，就不能勉强，否则把别的都破坏了，钱也浪费了，最后还得退下来。凡是不合实际的都可以修改，这样就把我们的思想解脱了，不然自己圈住了自己。

第四个问题，对第一个五年计划的估计。八大已经作了简单的估计，在制定明年计划的时候，大家又很容易联想到究竟应该怎样估计第一个五年计划。经过国务院常务会议多次讨论，大家认为，第一个五年计划基本上是正确的，成绩很大，但是错误不少。这好象也是老套子了，但从实际中摸索到最后，觉得还是这样说好。

第一，从生产指标方面看，今年的多数指标都接近了五年计划的指标。到明年，四十六种工业指标中有三十九种一定会超额完成预定的计划，估计只有七种完不成，实际上，真正完不成的就是石油。完成了第一个五年计划的生产指标，这不就是一个成绩吗？当然，农业比工业差一点，值得我们重视。但是，尽管有两年特大的灾害，粮食和棉花还是可以完成计划的。八种农产品中主要是麻、大豆、油料作物不能完成，这是我们没有安排好。同工业相比，我们对农业的重视和安排不够，农业量大面广，有时也不容易考虑得很恰当。

第二，从基本建设方面看，投资超过了计划数字。设计项目中，苏联设计的主要项目多数是完成了，我们自己设计的主要项目多数也都完成了。苏联设计的有一部分没有完成，主要是国防工业，我们推迟了，当然也有其他的项目。至于自己设计的项目，有些是不应该设计那么多的，这是我们工作上有错误。但总起来说，在这方面基本上也是有成绩的。

第三，从预算上看，我们打得比较更稳当一点。财政支出超过得不多。

所以，整个看起来，第一个五年计划大体上是正确的，成绩很大，这方面不多说了。

另一方面应该承认，错误也不少。这一点，我想多说几句。第一次制定五年计划，不可能一下子制定得很恰当。一九五二年提出的五年计划是粗线条的，然后一九五三年、一九五四年、一九五五年不断地修改，而且每年的年度计划还要修改。计划不那么准确是很自然的，因为我们缺乏经验和知识，是在不断地发现错误、修正错误的过程中前进的。一九五三年小冒了一下，今年就大冒了一下。去年的基本建设搞得少了一点，还有一点余力，结果是多余的器材减价出卖，钢材出口，水泥减产，木料也减价出卖了。这当然是不恰当的，是比较大的错误。至于小错误，各个部门都会有的。计划问题是值得我们研究的，就是到现在提出明年年度计划的时候，也不能说我们的缺点就都发现了。希望在全会分组讨论的时候，大家能揭发出更多的错误缺点，这对明年度的计划和今后的建设工作有好处。明年的计划到执行的时候，还会发现有些订得不恰当，还要在摸索中不断地改正。在第一个五年计划完成以后做全面总结的时候，就可以得出更多的经验教训，就会比八大时的认识更完全更深入。

现在看来，第一个五年计划中的一些变化，有的是由于形势的变化而需要修改，有的是由于经验和知识不足而犯了错误。我觉得这两点值得谈一谈。

首先是形势的变化。当我们开始订第一个五年计划的时候，朝鲜战争〔26〕还在进行，那时候设想，应该加紧发展的不仅是重工业，国防工业也要平行发展。一九五三年停战以后，一九五四年、一九五五年又出现台湾海峡局势的紧张，整个世界局势怎样还要看一看。直到日内瓦会议〔97〕、万隆会议〔96〕以后，到去年年终和今年年初，才慢慢感到国际局势是缓和下来了。在这样的情况下，我们才设想今年、明年把国防工业步子放慢，有些生产规模可以缩小。这也是很自然的。毛泽东同志在政治局会议上提出，现在把国防工业步子放慢，重点加强冶金工业、机械工业和化学工业，把底子打好；另一方面，把原子弹、导弹、遥控装置、远程飞机搞起来，其他的可以少搞，比如炮，有一个厂也行，现在先打底子，将来再发展数量。设想可能有一个和平时期，容许我们把完整的工业体系建设起来，这是最好的，我们把方针摆在这上面。但是我们还要准备另外一种可能，即发生战争，这决定于敌人是否要冒险。如果今后十二年内发生了战争，那怎么样呢？那不是我们犯了错误吗？到时候打起来军火少了，后备力量动员起来又没有军火，大家就哇哇叫了。可以设想一下，战争就是来了，敌人也不能马上解决问题。敌人打来了我们会先受一点损失，但他们爬上大陆以后，还是要打长期战争的。我们顶多犯那样的错误。毛泽东同志把这个问题提到政治局，我根据毛泽东同志的说法，把它提到中央全会，大家也想一想这个问题。如果算错误，我们大家一道犯，到那时候将功折罪，戴罪图功。只有这个办法，不然就徘徊歧路，东边走几步又回到西边走。把器材、资金统统集中搞国防工业，别的生产少了，人民的生活也不能改善，各方面紧张，而武器制造出来，仗又不打，炮不能吃，枪也不能吃，子弹生产多了还不利。所以非下决心不可。中央政治局谈到明年计划和第二个五年计划时就下了这个决心。这是由于形势的变化，我们有的步子加快了，有的步子放慢了。

第二是由于我们的经验和知识不够，在有些项目上犯了错误。现在看起来有些错误犯得有点可笑，但是当时的确没有弄清楚。比如说，请苏联设计的项目，以为能够提早给我们设备、提早一两年完成总是好的，而没有分清哪几种快对我们有好处，哪几种快会给我们背上包袱，凡是各部提出要加快的，报到国务院，报到中央，总觉得应该批准。象汽车厂就加快了，明年度可以生产一万八千辆到两万辆，可是这就要有很多的器材进口，同时要供应很多的汽油，这就要花外汇。现在汽油没有那么多，就得减少汽车产量。减少生产，劳动力就要闲置。外国朋友参观长春汽车厂时说，你们生产能力多了，一定要闲置。内行人一看就懂。原来还打算建设第二个汽车厂，现在要推迟了。再比如铝加工厂和机械厂，军工部门有的，民用工业部门可以不搞，可以结合起来共用，现在和平时期可以用作普通的民用的机械生产。过去没有很好地考虑，这样就闲置了一些资金。

因此，第一个五年计划尽管成绩很大，可是应该承认，缺点错误也不少。缺点错误已经知道的固然不少，但可能还有我们不知道或者没有揭露出来的，希望参加这次会议的同志在这方面多提一些意见。

＊这是在中国共产党第八届中央委员会第二次全体会议上做的关于一九五七年国民经济计划的报告节录。

