# 进一步提高军队的政治素养

中文马克思主义文库 -> 周恩来
进一步提高军队的政治素养
（一九五七年十二月二十四日）


　　中国人民解放军从建立以来，经过了多年革命战争的锻炼，在各方面都有了很大的提高。从一九五三年朝鲜停战〔26〕到现在的四年半中，情况起了变化，我们已不是在战争中进行锻炼，而是在保卫和平、保卫建设、保卫祖国边防的和平环境中进行锻炼。这对于二十多年来天天拿着武器和敌人作战的解放军来说，是个新的情况。当然我们已经在政治工作、党的组织等方面做了不少的精神准备。但是，对一种新情况的认识和适应，总要经过本身的体验，要有个摸索的过程。四年多来，我们做了一些新的部队建设工作，如实行了兵役制度、军衔制度，颁布了各种条令等，这些都促使我们的军队在正规化方面前进了一步。同时，经过朝鲜战争的锻炼，我们的军事装备逐渐走向现代化，部队的军事素养也得到新的提高。这就要求我们必须在另一个最重要的最基本的方面，也就是说要在军队的政治素养方面，在现有的基础上更加提高，在政治思想工作方面更为加强。这四年多，我过问军事工作比较少了，但也看了一些报告，知道在这方面有进步的地方也有减弱的地方，因此我今天想讲一讲进一步提高军队政治素养的问题。
　　第一，加强敌情观念。因为我们是军队，战时要打仗，平时就应该进行战斗准备，眼睛对着敌人，思想上警惕着敌人，准备战争。我们的人民解放军在党和毛泽东同志的领导下，从无到有，从小到大，从少到多，经过整整三十年，锻炼成为这样一支坚强的人民的军队，社会主义的军队。我们可以说，三十年中，有二十五年多都在打仗。现在情况有了变化，但我们还必须经常加强敌情观念。如果丧失了对敌人的警惕，就不能成为一个军人，尤其不能成为一个革命的军人。我们今天还处在两个制度对立、社会主义与帝国主义斗争的时代。毛泽东同志说“东风压倒西风”〔135〕，但并不是说我们可以坐等全世界共产主义的胜利。胜利是要用斗争夺取的。帝国主义不会等待死亡，甘心死亡，它还要挣扎。帝国主义存在一天，战争的土壤也就存在一天，总会有一部分战争狂人要冒险。所以我们革命军人就要时刻警惕着敌人，军人如果丧失了敌情观念，那就要犯很严重的错误。
　　我们是主张和平的，但和平必须通过斗争去争取。比如说，我们的外交工作是和平斗争，军事工作是武装斗争，这两种斗争是互相配合的。外交斗争需要有后盾，这主要是军事力量。没有这样一个后盾，日内瓦会议〔97〕也好，万隆会议〔96〕也好，我们就起不了那样的作用。当然，力量的源泉是人民，归根到底，一切胜利的取得是依靠人民的力量。由人民中的一部分优秀分子在共产党领导下组织成一支武装，这就是我们的人民解放军，这是一个非常重要的力量。这个力量丝毫不能懈怠，只有这样，敌人才不敢为所欲为。第二次世界大战以后，社会主义取得的一系列胜利，都是由于社会主义力量的强大、团结和巩固。朝鲜停战，印度支那停战〔99〕，不是敌人不想打下去，而是敌人不敢或不能打下去。所以说，力量是重要因素，只有我们的力量强大，不怕威胁，敌人才会知难而退，和平运动才能不断高涨。因此我们军人必须要有牢固的敌情观念。有国家，就需要有军队保护；帝国主义存在一天，军队的任务就一天也不会轻松。特别是你们处在祖国的东南前线，更应该加强敌情观念，时刻保持高度的警惕。
　　最近我了解了一下情况，我们的军队在这方面有一些弱点。有些同志的敌情观念不那么强了，工作也有些松懈。这是不应该的。当然我们不制造人为的紧张，也不被敌人制造的紧张所吓倒，但是应该紧张工作的时候还是要紧张地工作。大家知道，最近敌机乘隙窜入我们的上空，盘旋很长时间，一直到接近我们的首都。我还听总参的同志说，有些单位的军纪比较松懈，这很不应该。我们是拿武器来保卫和平建设的，必须有严格的纪律。
　　近年来，我们军队基层的情况改变了。实行了义务兵役制，战士都是新兵，基层骨干也很新。他们年轻力壮精神饱满，但没有经过战争锻炼，象暖室里培养的花朵，没有经过风霜。他们不仅没有土地革命战争、抗日战争和解放战争的经验，就连抗美援朝战争的经验也没有。如果我们的指挥员和政治工作人员不去教育他们，他们就会松懈。松懈是不允许的，因为帝国主义还存在，我们要准备应付突然事变。如果帝国主义不存在了，那就是另外一种情况了，但在我们这一辈子不可能如此，所以我们就必须随时准备着。尽管现在整个形势是“东风压倒西风”，和平的可能性更大了，战争推迟的可能性更大了，可是我们不能不警惕突然事变。这是你们的主要任务，是根本任务。爆发突然事变的可能性不论有多大，百分之十也好，百分之二十、三十也好，你们都要保持警惕，要准备坏的那一面。在和平时期要警惕坏的情况的到来。不论什么时候都要记住，这是最重要的一点。这是我们政治工作的责任，是首要的一课。
　　我们军队中基层干部的战斗经验也不是那么丰富了。营长以下的干部恐怕很多都是解放战争胜利后提拔起来的，有的参加过朝鲜战争，有的就没有参加过。时光过得很快，和平的时间已经不短了，从一九四九年算起已经八年，如果从朝鲜停战算起，也有四年半了，再争取五年、十年的和平时间，那就更长了。和平的时间越长，战争的警惕性就越容易松懈。我们现在处于建设的时期，和平生活惯了，是会有惰性的。在过去战争年代，几个月不打仗手就发痒，那时我们多少干部和战士到了后方医院，住不久总是急于回到前方。现在不同了，整个环境象后方似的，空气也变了。不仅有军队内部的影响，而且还有军队外部的影响，所以就更要加强战斗准备。我们的政治工作者、政治委员、政治部主任，应该经常讲这个问题，讲敌情观念问题，要教育部队时刻警惕着敌人的挑衅，经常加强战斗准备。这是我们保卫和平的首要问题。
　　第二，加强党对军队的领导。我们的军队是党领导的。三十年来，在党和毛泽东同志的领导下，我们建立了这样一支战斗的部队，胜利的部队。在取得革命胜利以后，这支部队又执行着保卫祖国、保卫和平的历史任务。这几年来，我们党更多地注意了建设工作，注意了阶级斗争，对军队工作管得少了些，这是个缺点。对这一点，你们可以给我们提意见。党一定要管军队。当然是管大事，不是管小事。毛泽东同志说，大权独揽，小权分散。如果什么事情都要中央政治局去管，那就要变成包办代替，就会形成小权多揽，大权不揽，把大的事情丢掉了。地方党委要管所在地区军队的事情，也应该是大权独揽，小权分散。上海市委应该讨论上海部队的重大问题，这是一方面。另一方面，军队的同志也要参加上海市委，出席重要会议。我们是共产党领导的军队，要了解党的大政方针和重要政策。如果你不了解党的方针政策，怎么会知道整个国家的发展呢！因此，对两方面都要有要求，党要管军队的重大问题，军队的负责人也要参加党的重大事情的决定。不仅上海一地如此，各地都应该这样。在这一方面，我们还要规定一些更具体的办法。但是你们不要等待，现在不是要整改吗，能改的就要先改起来。
　　我们军队如果没有党的领导，要使它成为一支既有高度军事素养又有高度政治觉悟的革命军队是不可能的，因此一定要加强党对军队的领导。
　　第三，加强军政联系。我们军队是人民的军队，是保卫国家的社会主义建设的，因此对国家建设和人民政府的各项措施都应该关心，有的要争取直接参加。关于我国的社会主义建设情况，我在上海市党代表大会上讲过了，大概你们的负责同志已经向你们作了传达，这里不详细讲了。我们国家的工业建设已经有相当的规模了，很值得看一看，应该组织起来去参观一下。
　　军队和地方的界限不要分得太清了。界限分明，互不相干，这对我们国家的建设非常不利。
　　军队应该关心国家建设，过去这方面做得不够。就拿国防建设来说，我看校级以上的军官也不一定都完全清楚，可能军事工程学院的同志知道一些，旁的人就不大了解了。你们有多少同志知道飞机是怎样制造的？坦克是怎样制造的？我看你们就不大了解。我们不是讲现代化吗，对现代化装备不仅要懂得运用，还要懂得它的性能、原理。尤其是在座的中级指挥员，年轻得很嘛，你们应该懂得这些，学会它，一旦有事，你们就能指挥。至于高级指挥员，如大将、上将、中将等，就更应该懂得这些。可以组织起来到各地去参观，政府方面给你们一些方便。当然，加强军政关系不只是关心社会主义建设一项，我只举此一端加以说明。其他的如征集兵员、复员转业、工程建筑、义务劳动等等，许多事情都要双方协作。军队过去帮助地方发展生产，做了许多工作，这种精神应该发扬，今后更要多做些。
　　第四，改进军内关系。主要是改进上下关系、左右关系、官兵关系。相互之间，不要因为实行了军衔制度、规定了礼节等而拘束起来。我们的军队是革命的军队，应该保持与发扬上下一致、官兵一致的优良传统。工作、打仗要强调按级服从，平时互相交往应该有同志式的友爱，象兄弟一样，不必过分拘泥于形式。我们军队的纪律是自觉的纪律，从井冈山时期以来，毛泽东同志就一再强调这一点。军队内部生活近年来有些呆板，讲求形式的东西多了，应该讨论改进。军队的民主是我们的优点，应该发扬这个光荣传统，进一步增强军内团结。
　　第五，密切军民关系。近几年，军队与人民的关系有些疏远了。我们回想一下，在革命战争年代，人民完全把我们当作自己的子弟兵。解放战争胜利时，全国人民对我们解放军那真是衷心拥护，军民之间的关系非常密切。但是近几年来，我们有了营房，有了严格的军事勤务以后，军队和人民群众的关系就比较疏远了，这是要注意改进的。我们是从人民中来的，我们过去的胜利都是在人民的支援下取得的，不能忘本。今后一定要进一步加强军民之间的联系，要结合整风整顿军民关系。
　　军队也要进行劳动锻炼。军队工作本身当然也是一种艰苦劳动，体力劳动很多，但总不同于工厂和农村的生产劳动。同时，部队的指战员虽然大多数是劳动人民出身，但也有不少知识分子。即使是劳动人民出身的，几年不参加生产劳动，也就生疏了，也需要通过劳动锻炼，进一步加强劳动观念和群众观念。因此要多组织义务劳动，帮助人民群众生产，使人民看到今天的解放军还是当年的子弟兵，还是抗美援朝战争时期的最可爱的人。我们军队要永远保持人民子弟兵的光荣称号，永远保持最可爱的人的光荣称号，永远保持同人民的血肉联系。
　　上面讲的这五个问题，我们应该根据形势和军队的任务，在整风中认真加以解决。
　　最后说一下，现在提倡勤俭持家，许多军官动员家属回到乡下去，回到生产中去，这是好事情，值得称赞。我在北京看到北京部队军官家属回乡的数目很大，我相信其他地方也会做得很好。


　　＊这是在中国人民解放军驻上海陆海空军军官大会上的讲话。



