# 把知识和经验留给后代

中文马克思主义文库 -> 周恩来
把知识和经验留给后代
（一九五九年四月二十九日）

这是个别开生面的会，只请了年满六十岁的政协委员参加。陈毅和彭真两位副主席例外，他们是“候补老人”。我也只有到今年才敢召开这个会，因为今年刚过六十岁。陈毅同志喜欢用《秋江》里的一句台词，说过了六十岁又是一个新花甲。老道理新解，很好。

这几天我参加了政协分组会，见大家精神很饱满，在新中国大家都获得了新生。现在六十岁以上的委员有三百八十三人，占全体委员的三分之一还多。老年人占的比例很大也证明我国人民民主统一战线扩大了。老年人得到了新生是可喜的事，但也要辩证地看问题。按照自然规律，人满了六十岁，今后的日子总是比中青年人少一点了。有些人不服老，我就是其中的一个，但有时熬夜多了就会出点小毛病。陈叔老〔147〕也不服老，最近得了流行性感冒以后，才说服老了。老年人不能和充满生命力的年轻人比，但要做到人老精神不老。据说过去中国人的平均寿命不超过四十岁。现在人民群众的物质生活条件改善了，医疗卫生条件也比旧社会好得多，大家精神愉快，长寿的人也越来越多。希望大家在新社会多活几年，多做些事，即使多看几年也是好的。

在分组会上听了几位老先生的发言，很有感触，觉得有必要和大家谈谈工作安排的问题，希望过了六十岁的委员都能把自己的知识和经验留下来，作为对社会的贡献。这是从已故的程砚秋〔134〕同志那里得到的启示。程砚秋同志的艺术修养很高，解放后在政治上和作风上也有很大进步，但总还是有点孤僻。在旧社会，他是孤身奋斗出来的，养成了洁身自好的习气，不大收徒弟，因此他的唱腔也就流传不广。解放以后，我曾劝他收徒弟。今年纪念他逝世一周年时，算了一下，他的徒弟不过十几个。程派唱腔又难学，徒弟们还没有学得好，他就去世了，录下来的唱片也不多。从这个问题联想到，凡有一技之长的老年人，总是多给社会留下一些东西好。

在座的委员有两种情况。一种是有具体工作岗位的，担任着科学、医药、工程、教育等方面的工作。这部分同志很忙，有的连写东西的时间也没有。老舍〔116〕同志有一次在全国人民代表大会上“将”了我一“军”，要求给他安排些时间搞业务。对这部分同志要加以照顾，不要弄得太紧张。高龄的委员精力集中使用，工作的年头可以更长一些。到各地视察既是政协委员的权利，也是他们的义务，但是要量力而行，有的可以不去，也可以就近视察。这次张文白〔148〕先生提出在北京附近视察，我们就赞成。以后，可以把老年人组织在一起视察，少看多休息，不能和年轻人一样对待。另一种是年老体弱没有具体工作岗位的，但他们都有一定的知识和经验。过去这方面的工作组织得不好，没有能使他们的力量发挥出来。许多人在历史、科技、文化、艺术或其他方面是有研究的，如果自己不能动笔，可以带徒弟写点东西。

我们都是过六十岁的人了，至少是戊戌年出生的。戊戌以来是中国社会变动极大的时期，有关这个时期的历史资料要从各方面记载下来。在座的都经历过四个朝代：清朝、北洋军阀政府〔6〕、国民党政府和新中国。新中国成立以前的史料很值得收集。时间过得很快，开国至今已经十年了，如果不抓紧，有些史料就收集不到了。五四运动〔39〕距今才四十年，那时候的事情现在的青年们已经不大了解了，对甲午战争〔34〕、戊戌变法〔149〕的情况他们就更不熟悉了。现在当然首先要研究现实问题，反映新的情况，但对过去的东西也需要研究，新的东西总是从旧的基础上发展起来的。过去编的府志、县志，保留了许多有用的史料。收集旧社会的典型事迹也很有价值，如近百年来有代表性的人物、家庭和家族的情况就值得研究，看看他们是如何产生、发展和衰亡的。那些典型人物，他们所代表的那个社会虽然灭亡了，有的本人也死亡了，但事迹可以作为史料记载下来。我国大小凉山有过半奴隶制，现在已经进行了民主改革。西藏是农奴制，再过几年也要改革的。有些东西不赶快记载下来就会消失。从最落后的到最先进的都要记载下来。要勇于暴露旧的东西，五四时代就提倡叛逆精神。一个人的转变不是偶然的。我如果有时间，也愿意写点东西暴露自己的封建家庭。对袁世凯〔43〕我不熟悉，谁要写蒋介石的历史，我还可以供给一些资料，两次国共合作我和他来往不少。暴露旧的东西，使后人知道老根子，这样就不会割断历史。人们都赞扬我国的古代文化，其中就包括很丰富的历史记载，不仅有正史，还有野史、笔记等。汉文在这方面起了很大的作用。我们要把自己所掌握的历史遗产贡献出来。

顾颉刚〔150〕先生说他想做些考据，但是政治运动很多，虽然有所得，却把时间都占了，在考据方面的贡献就少了。做考据工作只靠个人不行，要组织起来，也可以带点徒弟。

写东西不一定只限于文化史。在座的有搞军事的，可以写军事史，如从八旗〔151〕、绿营〔152〕、湘军〔153〕、淮军〔154〕、新军〔155〕一直到国民党军队的发展史，都可以写。在座的还有不少工商业者，可以写我国资本主义的发展史，也可以写其中的一个行业，如银行、纺织业等。其他如政治史、经济史、外交史也都可以写。

政协是联系各方面的，要注意组织这项工作。全国政协要开常委会，成立工作组，其中有收集历史资料的组。各位委员回去，可以利用地方政协和文史馆两个机构做做这项工作。在具体做法上要从容一点，不要象青年人那样，喜欢放“卫星”〔156〕，也不要规定一个月写多少字，有精力的时候可以多做些。收集史料的工作一定要从容一点。

昨天有两个黄埔军校〔157〕的朋友讲起三二○事变〔158〕和皖南事变〔159〕，听起来很有味，但我因有事只听了一个半小时就告辞了。有些朋友的观点不一定正确，那可以共同研究，但先要把史料记载下来。例如昨天两个朋友讲的三二○事变的情况就可以补充已有史料的不足。他们说，在事变发生前一星期蒋介石想走。乍一听不容易理解，这次事变是蒋介石向共产党的进攻，怎么他又想跑走呢？青年人听了根本不会相信，但根据蒋介石一贯的作风来看，这是可能的。蒋介石在陈炯明〔160〕、孙中山手下时都曾拂袖而去。在黄埔军校时他同苏联顾问闹翻了，也是走了又请回来的。他当权后，这种事又有过三次：一九二七年下野去日本，一九三二年一二八淞沪抗战前躲回奉化，一九四九年和平谈判时退居幕后要李宗仁代总统。他常以退为进。三二○事变前他可能想走，等到摸清我们毫无戒备的时候，就大举进攻。历史是曲折的。我早说过蒋介石是最好的反面教员。蒋介石这一集团是很有些东西可写的，在座的不少人熟悉这方面的情况。

今天梁思成〔161〕先生没有来，康同璧〔163〕先生来了，他们二位如果对维新派〔163〕有兴趣也可以写。去年学术界对戊戌变法作了评价〔164〕，也还可以重新估量。国外有专门研究戊戌变法的，但我国研究这个问题的人很少。

现在先提一提这件事，大家好作安排，具体的组织工作由政协常委会秘书处与各方面联系。

上面这些话可能对六十岁以上的人有些用，所以耽误大家不少时间。

＊这是在中国人民政治协商会议全国委员会举行的茶话会上的讲话。

