# 共产国际和中国共产党

中文马克思主义文库 -> 周恩来
共产国际和中国共产党
（一九六○年七月十四日、十五日）


　　中央常委要我讲一下国际关系，主要是共产国际〔165〕和我们党的关系。
　　我先概括地讲六点看法：
　　一、共产国际的成立和解散，都是必要的。共产国际从成立到解散共存在二十四年（一九一九——一九四三），三个八年。毛泽东同志说它是两头好，中间差。两头好，也有一些问题；中间差，也不是一无是处。共产国际的成立，当然是必要的。它对各国党的建立和成长起了很大的作用。后来各国党成长了，成熟了，共产国际就没有存在的必要了。
　　共产国际在建立的初期，阐明了马克思列宁主义的原理原则，推动了世界共产主义运动的发展。那时，尽管列宁有那么高的威望，但共产国际是民主集中地决定问题的，各国党的代表可以纷纷议论，各抒所见，非常活跃。共产国际划清了共产党和社会民主党的界限，也批判了“左”派幼稚病，发扬了国际主义精神，动员了各国革命人民拥护苏联，支持了各国人民的革命斗争和民族革命运动。
　　共产国际的解散也很适时。一九三五年，共产国际作了一个决议，说对各国党的内部事务不要去干涉，以后也的确放手了一些。但是这时，共产国际的存在还需要，它在反法西斯和建立统一战线的斗争中起了积极的作用。苏德战争爆发之后，到了一九四三年六月，共产国际就解散了。
　　共产国际的缺点和错误，特别在中期的缺点和错误，概括地说是：一般号召不与各国实践相结合，具体布置代替了原则的指导，变成了干涉各国党的内部事务，使各国党不能独立自主，发挥自己的积极性、创造性。
　　这是对共产国际的一个粗浅的总评。
　　二、各国的革命和建设，要靠各国人民自己的实践。只有把马克思列宁主义的普遍真理和本国革命的具体实践相结合，才能使马克思列宁主义得到补充和发展。要在实践中总结自己的正面和反面的经验。中国党的经验很丰富。中国党虽然犯过几次“左”的和右的路线错误，但也有很重要的正面的经验。
　　三、各国的革命和建设，要靠各国党自己独立思考。只有独立思考，才有可能避免国际的坏的经验在本国重犯，使国际的好的经验在本国得以发展。据我所了解，不独立思考、盲从迷信的人是很多的，破除迷信、独立思考是很不容易的。当然独立思考并不等于狂妄自大，唯心武断，拒绝国际提出的好的意见。陈独秀〔40〕是狂妄自大、唯心武断的。李立三〔166〕同志也是这样，他提出夺取武汉，争取一省数省的首先胜利；一省数省的胜利就是全国胜利的开始；打下武汉再和共产国际算帐；中国革命起来了，要苏联出兵；中国革命胜利，英、美、法等国的资产阶级都要濒于末日，世界革命就会起来。现在立三同志看一看这些话，他自己也会发笑的。
　　四、各国的革命和建设，要靠各国自己独立自主和自力更生。毛泽东同志说，两个大国的革命胜利，即俄国十月革命的胜利和中国革命的胜利，都是在没有共产国际的时候取得的。在现在的情况下，成立国际组织，相互间总是不容易做到平等。不仅在政治上，就是在经济上也是如此。
　　五、研究国际的经验，要全面地看问题。斯大林管事的时间长，缺点错误多一些，但是在斯大林那个时期也并不都是不好的。就是在共产国际中期和斯大林的晚年，他也是支持革命的多，不许革命的少。我们顶一顶，他还是可以接受一点意见，也可以含蓄地承认一点错误。他的怀疑一经实践证明不对，看法也可以改变。例如他怀疑我们不是真正的马克思主义者，怀疑我们对于帝国主义不斗争，一到抗美援朝〔26〕，他的看法就改变了。斯大林还是讲理的。当然，斯大林在中国革命问题上有错误，但中国革命中的错误主要应该由中国同志负责，犯不犯错误主要还是决定于我们自己。我们过去犯的错误已经认识了，纠正了，革命已经胜利了。六、团结高于一切，国际主义万岁。这是原则，过去如此，现在也应该如此。所谓团结，是在原则基础上的团结。有分歧，我们要从团结的愿望出发，经过适当的批评或斗争，在新的基础上达到团结。同时批评要注意场合，要心平气和，摆事实，讲道理。如果批评或斗争都不生效，也需要等待，需要时间。中国党在这方面有很丰富的经验。第二次国内革命战争时期八年中犯了三次“左”倾错误〔167〕，从遵义会议〔92〕开始到七大〔15〕，经过十年之久才解决了问题。一个党如此，何况国际？我们要举团结的旗帜。这主要是对于苏联千百万党员、两亿人民，各兄弟党的党员，世界上百分之九十以上要革命的人民。
　　下面分几个时期讲一讲共产国际和我们党的关系。
　　（一）共产国际的初期（一九一九年三月——一九二七年七月）。
　　这个时期，共产国际的工作对于中国革命，还是有益的多。当然，也有个别的原则问题的错误。
　　一九一九年三月共产国际成立后，就派人到各国访贤，做工作。在中国，他们不仅找了陈独秀、李大钊〔46〕，还找过江亢虎〔168〕、黄介民〔169〕和戴季陶〔170〕；在北方找过吴佩孚〔171〕，在南方找了孙中山。中国有五四运动〔39〕的基础，在共产国际的帮助和推动下，很快成立了中国共产党。中国党很快地走到了群众斗争中去。这时共产国际讨论中国问题的次数也逐渐多起来了。一九二○年的第二次代表大会，一九二一年的第三次代表大会，都讨论了东方革命问题。一九二二年共产国际第四次代表大会认真讨论了中国革命问题，以后就大量吸收中国的知识分子到莫斯科去学习。一九二三年共产国际作了关于国共合作的决议，决定中国共产党员加入国民党，同时共产党保持自己的独立性；还讨论了中国搞土地革命的问题，并发来了指示。一九二三年六月，中共召开三大〔172〕。当时党内有“左”的和右的两种思想：一种以陈独秀为代表，认为中国现在是资产阶级民主革命，这种革命应该由资产阶级领导，无产阶级只是帮忙，民主革命中无产阶级领导权的问题根本没有提；一种以张国焘〔173〕为代表，认为中国共产党员只能少数人加入国民党，工人不能参加。实际上，这两种思想都是不要无产阶级领导权的。党的四大的决议对这两种思想都批评了，但是并没有解决问题。现在看来，批评也没有重点。当时群众斗争已经轰轰烈烈地开展了，但是在陈独秀机会主义的领导下，在关键问题上掌不好舵。国民党第二次代表大会时，国民党内的右派已经比过去嚣张得多，如西山会议派〔174〕。但在此以前广东打商团〔175〕，东征陈炯明〔160〕等等，左派力量大大发展。当时的政策应该是支持左派，排斥右派，这是有可能实现的。但陈独秀却要让右派回去，并且要保证他们在国民党二大上当选，结果右派的气焰高涨。在军事上，我们也让步。蒋介石进攻，我们党没有警惕，他制造了三月二十日的中山舰事件〔158〕，把我们党在军队中的力量搞掉了一部分。当时我们并不是没有力量，应该反击，但是没有反击。结果使我们党在军队中的力量仅仅留下了一个独立团〔176〕，这个团到了武汉发展成两个师。北伐的时候，我们应该争取群众，争取军队。可是，这边北伐，那边上海的《向导》反映陈独秀的主张，反对北伐，说现在是军阀战争，广东不应该北伐，应该防御，应该搞群众斗争。我们党放弃了对北伐战争的领导。土地革命轰轰烈烈起来了，毛泽东同志的文章〔177〕之后，但是党中央不支持。当时，陈独秀的确有点怕革命，怕群众。当时共产国际执行委员会也对我国阶级力量的分析都有错误。特别是一九二七年五月第八次会议，认为资产阶级都叛变了。到了武汉政府叛变〔178〕之后，共产国际又认为，小资产阶级也离开革命了。在领导权问题上，一九二四年国共合作的时候，无产阶级的领导已经有了雏形，国民党第一次代表大会的召开，共产党已经起了领导作用。本来我们应该在广东革命政权的时候就抓军队，而且这是完全可能的，但是党中央在那个时候放弃了领导权。这时列宁去世了，斯大林跟他们党内的反对派斗争很激烈，对中国革命的情况不大了解，方针也不大明确。当时我国革命的中心在广东，党的中心也应该在广东才好领导。但是党的中心在上海。请陈独秀到广东去，他也不去。两个中心常常发生矛盾。直到打下武汉很久，党的中心才移到武汉。所以，第一个时期还是中国党的领导人应负更多的责任。那时，毛泽东同志的威信还没有建立，也不可能建立。当时党的领导人员马克思列宁主义的水平也不高，还有各种派别性，陈独秀的家长制作风更助长了派别性，这就影响了党在政治、思想上的发展。
　　（二）共产国际的中期（一九二七年七月——一九三五年七月）。
　　这个时期，共产国际基本上是错误的，对我们中国党影响最大。一九二七年七月，武汉政府叛变革命，陈独秀投降主义路线破产。在这样一个紧要关头，七月，共产国际执行委员会给中央来信。这封信强调了革命的前途，而对革命的动力和阶级关系分析得不正确，说中国的资产阶级、小资产阶级都叛变了。对革命的任务，提出了七条：第一，退出武汉政府；第二，发表宣言；第三，不要退出国民党，在国民党内搞左派；第四，工人斗争；第五，武装工农；第六，党可能转入地下；第七，反机会主义。这七条，对搞军队、搞地方政权和深入土地革命没有重视，而当时恰恰应该是搞军队、搞地方政权和深入土地革命。
　　反对陈独秀的机会主义，联系到组织问题。共产国际派来的鲍罗廷〔179〕直接干涉中国党的内部事务，在一次政治局会议上组织了一个临时中央常委。这是仓促通过的。七月十三日中央有个声明，只提了退出武汉政府。当时我们党还有一点武装力量，如叶挺的部队〔180〕，所以决定举行南昌起义〔181〕。南昌起义的目的是南进汕头，占领海口，然后到广州。南昌起义本身是正确的，但在领导思想上有错误：单纯军事行动，中心是城市观点，没有跟当地农民结合起来建立根据地的思想。当时，共产国际派了几个人来，在罗米那兹〔182〕的指导下，在汉口召开了八七会议〔183〕。八七会议在反对机会主义这一点上是痛快淋漓的，但在怎样跟土地革命结合起来，深入群众斗争，建立军队、政权、根据地这些重要问题上没有作出正确的总结和指示，没有提出明确的任务。张太雷〔184〕到汕头给我们传达八七会议，只批评了机会主义，没有提出如何做的问题。我自己当时是城市观点，没有从上海起义和南昌起义中取得经验，上山搞农村斗争。
　　中国革命失败，反对派攻击斯大林更凶。斯大林在一九二七年，连写了几篇文章〔185〕驳反对派，其中对中国革命的理论的分析，形势的估计，许多是不合实际的。他认为中国的资产阶级、小资产阶级先后都离开革命阵营了，但是中国的革命高潮很快就要到来，并且有很快转入社会主义革命的趋势。在共产国际、斯大林的理论分析和形势估计的影响下，一九二七年十一月党中央扩大会议就搞了盲动主义，号召到处暴动，认为革命形势还是高潮。在组织上，处分了不少人，最主要的是开除谭平山〔186〕，对毛泽东同志和我们这些人都有处分。十一月中央会议决定组织广州暴动〔187〕，也没有明确的方向。参与指导广州暴动的有一个德国人，还有一个苏联人。广州暴动失败，太雷同志牺牲后，中央把立三同志派到香港去领导广东的工作，这时是盲动主义的最高峰。盲动主义在广东搞得最厉害，广东干部牺牲得最多。当时的路线，根本没有接受上海、南昌、广州暴动的教训，仍然要到处搞暴动，结果使革命力量特别是白区革命力量受到了很大损失。当时在组织上还搞了一条，叫作领导干部工人化，使领导机关更加混乱，宗派性增加了。这个根也是从共产国际的指示来的。
　　现在讲一下中共六大〔188〕。六大是根据共产国际执行委员会第九次全会的决议召开的。中共有一个代表团，其中有向忠发〔189〕等人，出席共产国际执行委员会第九次全会。六大的召开，首先去的代表就有问题。当时强调工人化，在七十五个代表中，有四十一个工人，后来叛变的十六个代表中，有十四个工人。当时共产国际指导六大工作的人，一个是布哈林〔190〕，还有一个法国同志，还有陶里亚蒂〔191〕，但做实际工作的是米夫〔192〕。在选举中央委员的时候，只强调工人成份，中央委员二十几个人中，很多是工人，而当时党内真正有威信的同志有些没有被选入。会后，瞿秋白〔193〕、张国焘留莫斯科做共产国际执行委员。六大的决议，对中国革命的性质（资产阶级民主革命）和任务（反帝反封建）等的分析是正确的，但是对于阶级关系等问题则作了不正确的分析，认为资产阶级和上层小资产阶级都叛变革命了。在土地问题上，只提了没收地主阶级的土地交农民代表会议处理；对军事问题没有强调指出。六大后，中山大学里以王明〔194〕为首的宗派，集中力量反对驻共产国际的中共代表团。中山大学是一九二五年在莫斯科创办的，米夫做副校长，吸收了大革命时期党的一些干部和青年去学习，其中有王明这么一些人，还吸收了国民党的一些左派。在中山大学内，宗派斗争很厉害。六大后，中山大学的宗派斗争继续发展。王明宗派反对中国代表团，实质是反对党中央，认为中国党的中央不行了，要换人。到了一九二九、一九三○年，再加上联共（布）清党的影响，就搞得更混乱了，对有一点可疑的就开除，还流放了一部分。
　　六大以后，共产国际派了一个波兰同志和一个德国同志来中国。到了一九二九年，共产国际陆续来了四封信。第一封信的内容是反右倾，第二封信的内容是反对联合富农，第三封信的内容是赤色工会公开，第四封信的内容是反改组派（汪精卫、陈公博）〔195〕和第三种力量。这四封信，对立三路线都有影响。第四封信就号召中国搞政治罢工，准备革命，说直接革命形势快到了。
　　我一九三○年三月动身去共产国际。七月，我见了斯大林，斯大林对在中国进行的军事斗争很重视。当时产生了共产国际执委会政治秘书处关于中国问题的决议案。共产国际的决议还附了东方部的六个决议〔196〕。斯大林说，这么多决议拿到中国太多了，作为草案拿去吧。国内，六月十一日产生了立三路线。立三路线提出，要争取一省数省的首先胜利，一省数省的胜利就是全国革命的开始。同时在全国布置暴动，并提出夺取武汉、南昌、长沙等大城市的计划。后来打下了长沙，于是在八月一日、三日，在上海连着开了两次中央政治局扩大会。立三说，打下武汉再和共产国际算帐。立三路线持续时间只有三四个月，但使很多地方的党组织受到很大损失，所以，九月就开了三中全会。三中全会还有“左”的东西，因为三中全会是传达共产国际上述决议案的。会上，向忠发和我做了报告，秋白做了结论，立三发了言。会上对立三的批评很尖锐，不过后来在会议决议上写的并不那么尖锐。三中全会在组织上也有些错误，例如批评了何孟雄〔197〕，也批评了陈绍禹（王明），这些批评，也有对的，也有错的。三中全会补了一批中央委员，就是没有补何孟雄，其实那个时候他的意见还是对的居多。向各地派“钦差大臣”，从三中全会就开始了。当时，共产国际说中共中央不重视苏区，所以中央就往苏区派了不少人，使苏区受到了影响。
　　一九三○年十月共产国际来信，说中央不对，是调和路线。王明他们就闹起来了。米夫一来，更造成了党内的危机。王明写了小册子〔198〕，要求中央召开紧急会议，撤换中央的领导。所以，召开了四中全会。四中全会，我们起草了决议，不被采用，米夫自己起草了决议。三中全会是贯彻共产国际执委会政治秘书处关于中国问题的决议案的。四中全会也是根据这个决议案的，再加上国际的信，用极左反对立三路线的“左”，作了决议。四中全会后，王明的小册子更加发挥了作用。他站在更“左”的立场来反对立三的“右倾”和三中全会的“调和路线”，形成了更“左”的路线，再加上中央几个负责人叛变，使我们党受到了很大的破坏。
　　一九三一年八月，米夫回去了。共产国际的八月决议批评了三中全会，说四中全会中，中国党更加健全了。实际上，四中全会后，中国党更加混乱了。四中全会把我保留在政治局，把秋白去掉了。以后，王明到了共产国际，张国焘、陈昌浩〔199〕到了鄂豫皖苏区，我到了中央苏区。当时，中央只留少数人，多数派到各地去，抓各地的权。在上海组织了一个临时中央。这个临时中央，共产国际是批准了的。临时中央有一个关于九一八事变的决议，一九三二年一月又有一个争取一省数省首先胜利的决议。当时要求争取一省数省的首先胜利，要求攻打中心城市，对于正确的同志，如毛泽东同志，刘少奇同志，指责他们“右倾”。宁都会议〔200〕以后，毛泽东同志对军队的领导被取消了。一九三三年又反对罗明路线〔201〕，反对邓、毛、谢、古〔202〕，正确的同志都受到打击。搞得最凶的是江西，因为临时中央一九三三年初到了江西，执行国际路线。结果使党在白区的力量几乎损失百分之百，苏区的力量损失百分之九十。当时在军事上有个李德〔203〕，他虽然是个顾问，却成了太上皇，他说了算。他和博古〔204〕的军事路线相合，一直搞到遵义会议。当时的军事路线执行的结果是退出江西，被迫长征。现在看来，当时不退出江西是不可能的。到了遵义会议，毛泽东同志才在军事上纠正了错误路线，挽救了中国革命。没有遵义会议，中国革命不知道要推迟多久。有了遵义会议，虽然长征中受了损失，又遇到了张国焘分裂党另立“中央”，但是在毛泽东同志的领导下，战胜了狂风巨浪，克服了党内的危机。
　　共产国际对中国党的指导在中期是有很大错误的。中国党在这个时期犯了那么多错误，使中国革命受到了那么大的损失，我们中国人当然要负责，但与共产国际有很大的关系。
　　（三）共产国际的后期（一九三五年——一九四三年）。
　　这个时期，中国党与共产国际联系少了。一九三五年七八月，共产国际召开了第七次代表大会。斯大林更多地注意国内问题，共产国际由季米特洛夫〔206〕领导。当时通过了一个决议，说国际执委会要把工作重心转到规定国际工人运动基本政治路线及策略路线方面去，一般不干涉各国党的内部事务。当时，共产国际搞反法西斯统一战线，和中国搞抗日民族统一战线相合。西安事变〔206〕张学良、杨虎城把蒋介石抓起来，共产国际公开说张是日本帝国主义的走狗，抓蒋介石是适应日本的要求。这个判断是完全错误的。西安事变，我们处理得还是比较好的。
　　这个时期，中国党由毛泽东同志当家了，但是共产国际对我们中国党还有影响。主要的问题是第二次王明路线〔207〕。一九三七年年底王明从共产国际回来，说他跟斯大林谈过话。他打着共产国际的招牌，提出“一切经过统一战线”，说国民党和共产党都是中国优秀青年的总汇。王明回来后，主持了长江局，蒙蔽了一批人，搞了第二次王明路线。第二次王明路线虽然时间不长，但对北方，对新四军，对上海，都有影响。第二次王明路线与共产国际不无关系。斯大林信任王明，季米特洛夫和王明的关系也好。后来我去莫斯科对季米特洛夫谈王明的错误，季米特洛夫听了还表示惊讶。遵义会议后，毛泽东同志的领导在我们党内形成了一个新的局面。党的六届六中全会批判王明，很多干部逐渐觉悟了，王明就逐步地孤立了。当时蒋介石也不要王明，连个部长都没有给他当。毛泽东同志说，要是给他一个部长当，也许情形更坏。
　　一九三九年，希特勒德国发动的第二次世界大战打起来了，由于苏德签订了互不侵犯条约，资本主义各国党处境很不利，思想也很混乱。毛泽东同志九月一日有个《关于国际新形势对新华日报记者的谈话》〔208〕，我把它带到共产国际，发给各兄弟党。共产国际很称赞，说中国党领导正确，给了他们很大支持。
　　在这个时期，共产国际对我们党的内部事务还是有些干涉，甚至在组织上也还有些干涉。但这个时期比共产国际初期对我们党的干涉少，比中期就更少。后来战争打起来，对我们党的干涉就很少了。我们中国党这时已经成熟，和共产国际的来往不多了。到了一九四三年，共产国际就解散了。


　　＊这是在中共中央于北戴河召开的省、市、自治区委书记会议上所做报告的节录。



