# 加强调查研究

中文马克思主义文库 -> 周恩来
加强调查研究
（一九六一年三月、五月）


调查研究，实事求是*
（一九六一年三月十九日）


　　毛泽东同志这篇关于调查工作的文章〔209〕，讲的是世界观，也是方法论。我们要以辩证唯物主义和历史唯物主义的观点来读它。这篇文章现在读起来，还是对症下药的。毛泽东同志一向提倡调查研究和实事求是。从延安整风〔14〕到七大〔15〕，到全国解放，我们发扬了这种精神，取得了全国胜利。进城以后，特别是这几年来，我们调查研究较少，实事求是也差，因而“五风”〔210〕刮起来就不容易一下子得到纠正。
　　毛泽东同志最近几次讲到大兴调查研究之风，讲究实事求是；又说，右要反，“左”也要反，有“左”就反“左”，有右就反右。是好是坏，要从客观存在出发，不能从主观想象出发。进行调查研究，必须实事求是。我们下去调查，必须对事物进行分析、综合和比较。事物总存在内在的矛盾，要分别主次；总有几个侧面，要进行解剖。各人所处的环境总有局限性，要从多方面观察问题；一个人的认识总是有限的，要多听不同的意见，这样才利于综合。事物总是发展的，有进步和落后，有一般和特殊，有真和假，要进行比较，才能看透。下去调查，要敢于正视困难，解决困难。一个困难问题解决了，新的困难问题又来了。共产党人就是为不断克服困难，继续前进而存在的。畏难苟安，不是共产党人的品质。
　　我们下去调查要坚守毛泽东同志的三条原则：从群众中来，到群众中去；集中起来，坚持下去；坚持真理，修正错误。这就是民主集中，它不但是组织原则，也是工作原则。智慧是从群众中来的，但对群众的意见领导方面还要加工，然后回到群众中去考验，在这基础上再加工。脱离我们的基本阶级群众，就会丧失党的基础。尾巴主义，随着群众跑，就会放弃党的领导。目前的毛病，还是我们发号施令太多，走群众路线太少。


　　＊这是在中共中央工作会议中南、华北小组会议上的讲话节录。



关于食堂和评工记分等问题的调查
（一九六一年五月七日）


　　主席给李井泉和陈正人同志的信〔211〕六日早上我就看到了。我到邯郸之后，听了三天汇报，就到武安县伯延公社，现在已经有五天了。五天中，我找了公社、大队、生产队的干部和社员群众谈了话，开了座谈会。现在有下面四个问题简要地向主席汇报一下。
　　（一）食堂问题。绝大多数甚至于全体社员，包括妇女和单身汉在内，都愿意回家做饭。我正在一个食堂搞试点，解决如何把食堂散好和如何安排好社员回家吃饭的问题。
　　（二）社员不赞成供给制，只赞成把五保户〔212〕包下来和照顾困难户的办法。现在社员正在展开讨论。
　　（三）社员群众迫切要求恢复到高级社〔84〕时评工记分的办法，但是已有发展。办法是：包产到生产队，以产定分，包活到组。这样才能真正实现多劳多得的原则。因此，这个办法势在必行。只有这样，才能提高群众的生产积极性。
　　（四）邯郸专区旱灾严重，看来麦子产量很低，甚至有的颗粒不收，棉花和秋季作物还有希望。目前最主要的问题是恢复社员的体力和恢复畜力问题。
　　我明天还要看一个食堂，八日返回北京，帮助陈总〔213〕解决出席日内瓦会议〔214〕的一些问题。以后再给主席写报告。问题解决了之后，我还要返回邯郸。
　　我到邯郸之前，已经派许明〔215〕同志带领一个工作组在这里工作了二十天。


　　＊这是在河北省邯郸地区农村调查期间给毛泽东的电话汇报记录。




