# 接见嵯峨浩、溥杰、溥仪等人的谈话

中文马克思主义文库 -> 周恩来
接见嵯峨浩〔216〕、溥杰〔217〕、溥仪〔218〕等人的谈话
（一九六一年六月十日）


　　听说嵯峨尚子〔219〕夫人同宫下明治〔220〕先生后天就要走了，本来想晚一点见你们，这样就不能不提前。

　　欢迎你们到中国来！你们在日本可能听说中国的生活很困难，其实也没有什么。两年来的灾荒，是带来些困难，粮食少了一些，以农产品为原料的商品比以前少一些，但是经过两年来的努力，恢复了不少。

　　听说嫮生〔221〕来后讲中国人面孔黑。溥仪先生、溥杰先生的面孔的确比过去黑了一些，身体也结实了一些。黑是健康的表现，不管怎么样，我们都是黄种人，被称为有色人种，不会变成白种人。世界上有黑种人、黄种人、白种人和棕种人。不管是哪种人，相互间都应该是平等的。但现在还有差别，还存在着种族歧视。从另一个意义上说，最黑的人最受压迫，最有前途，最有希望。非洲有两亿多人口，是未开发的处女地，资源很丰富，现在经济发展不如欧洲，但后来居上，将来会赶上的。世界上开发较早的地方是欧洲，但很多资源快开发完了。开发最少的地方是非洲，非洲有煤、铁砂、石油和稀有金属等，很丰富。北美的加拿大也开发了不少，美国的石油开发早，浪费也大。亚洲和拉丁美洲则是半开发的地区。这些未开发和半开发的地区，民族独立了，外国不能干涉了，自己管理自己了，是统统要开发的，所以说是后来居上。到那一天，我们的态度仍然是平等待人，有无相通。地不分南北，人不分肤色，四海之内皆兄弟。到那时帝国主义不存在了，世界大同了，不过这大概要到二十一世纪以后才可以看到。我是看不到了，载涛〔222〕先生你大概也看不到了，老舍〔116〕先生与我同年，大概也看不到了，年轻的人有希望看见。我们共产党的目的就是要把世界搞得美好，使大家都能活下去，而且过得好。

　　今天在座的有过去的皇帝、皇族，现在都生活在一起，这有一个条件，大家平等。以前日本也有贵族，比如西园寺〔223〕就是公爵的后代，但他不愿意要这个爵位了。尚子夫人、浩夫人、干子〔224〕夫人都是侯爵的后代。载涛是贝勒〔225〕，他是光绪的弟弟，宣统的叔叔。溥仪先生是皇帝，“满洲国”〔226〕我们不承认，但宣统我们是承认的。溥杰是皇帝的弟弟，嫮生是日本贵族的外甥女，又是中国皇族的女儿。溥仪、溥杰的弟弟妹妹过去也都是皇族。现在变化了。溥仪先生研究热带植物，还能劳动，自愿参加劳动，对劳动有兴趣。溥杰先生在景山公园研究园艺，半天工作，你还要照顾一下你的家庭?弟弟妹妹的情况，那是你们都知道的了。三妹是东城区的政协委员，我是全国政协的主席，从这一点说，我们还是同事。五妹曾做过服务员，现在做会计，她完全是自我奋斗，过去我们不知道。六妹是画家，字写得很好，现在是艺术家了。七妹是小学校的教导主任，模范工作者。你们在街上走，谁能认出来是过去的皇族呢？妹夫们也都有了变化。过去这些皇族、官僚、贵族，今天都变化了，当了工人、职员或教员。

　　现在介绍一下满族的杰出人物老舍先生。他是一位名作家。辛亥革命〔73〕后，若讲自己是满族人就会受欺侮，受歧视，所以他就不愿意讲。他有许多著名作品，如《骆驼祥子》、《龙须沟》等等。老舍夫人是位画家，中年学画，拜齐白石〔227〕为师，现在和陈半丁〔228〕、于非闇〔229〕等画家合作绘巨幅的国画。

　　再介绍一下，这是程砚秋夫人。程砚秋〔134〕是中国著名的京剧演员，也是满族人。解放后他非常努力，要求加入中国共产党，一九五七年我和贺龙〔230〕元帅介绍他入了党，可惜第二年他就去世了。浩夫人你有听唱片的爱好吗？（浩：很喜欢。）我可以送几张程砚秋的唱片给你，我很喜欢听他的唱片，睡不好觉时，就听一听。旧社会他们被叫作戏子，受人歧视，我们称他们是艺术家，都是平等的。

　　我还介绍一位照顾我们夫妻的护士，她也是满族人，自己不说，被我认出来了。在座的汉族同志很多，就不一一介绍了。中国旧社会，等级森严，不平等。清朝时我们这些人要见溥仪非下跪不可，也根本见不到。辛亥革命后就变了，但只变了一点，推翻了清政府的压迫，代之以少数汉人的统治，而且更凶。北洋军阀〔6〕是年年打仗，国民党统治也是战争不断，搞得民不聊生。只有中国革命胜利了，社会才变了，全中国人民都平等了。中国现在的社会制度是中国人民自己选择的，自己奋斗出来的，不是外来力量强加的。我们觉得这样做很心安，很高兴。请大家想想，世界上有哪一个国家在推翻了封建制度、建立了共和国以后，以前的皇帝还能存在，还给以平等地位？例如英国的查理一世〔231〕、法国的路易十六〔232〕、德国的威廉二世〔233〕、埃及的王室〔234〕等等，他们哪里去了呢？可以比较一下。（溥仪：世界有史以来没有过。）这是我们国家的政策，当然也要本人努力争取，大家合作。浩夫人请放心，我们不会歧视你的，尚子夫人和宫下先生回国以后请告诉日本朋友，浩夫人是不会受到歧视的。（尚子：在总理的帮助之下，浩才能到中国来，非常感谢。）这不是我个人的帮助，这是国家的政策。（对嵯峨浩）你的死去的女儿慧生给我写过信，我同意她和她父亲通信。她是一个很勇敢的青年，是否有她的照片，送给我一张作纪念。

　　现在谈谈满族的问题。满族统治阶级入关统治中国近三百年，奴役各族人民，虽然曾使中国一度强盛，但最终还是衰败了，这应由清朝的皇帝和少数贵族负责，满族人民是不用负责的，他们也同样受到灾难。孙中山先生领导辛亥革命推翻清政府是对的。溥仪先生当时才几岁，他也不能负责。载涛先生当时是大臣，要负一部分责任。至于“满洲国”时代，溥仪、溥杰都应该负责，当然更大的责任应由日本军国主义来负。溥仪、溥杰合作的书〔235〕揭露了这一点。你们的书应该修改一下再出版，书里自我批评太多了。那些事情都过去了。新中国成立十一年啦，中国人民对清朝的残酷统治和压迫，印象已经淡了，记得的人也不多了，但历史还是要按照事实来写。清朝亡了，说明它不好，这一点历史已经做了结论。

　　现在的问题，是要恢复满族应有的地位。辛亥革命以后，北洋军阀和国民党反动政府歧视满族，满人不敢承认自己是满族，几乎完全和汉人同化了，分不清了。民族将来是要互相同化的，这是自然发展的结果，但不能歧视，不能强制。因此现在还要把满族恢复起来，事实上一九四九年以后已开始这样做了。

　　清朝是中国最后一个王朝，它做了许多坏事，所以灭亡了。但也做了几件好事：第一件，把中国许多兄弟民族联在一起，把中国的版图确定下来了，九百多万平方公里。第二件，清朝为了要长期统治，减低了田赋，使农民能够休养生息，增加了人口，发展到四万万人，给现在的六亿五千万人口打下了基础。第三件，清朝同时采用满文和汉文，使两种文化逐渐融合接近，促进了中国文化的发展。清朝在确定版图、增加人口、发展文化这三方面做了好事。康熙懂得天文、地理、数学，很有学问。俄国彼得大帝和康熙是同时代的人，因为俄国地处欧洲，手工业比较发达，他汲取了西欧的经验，发展了工商业。中国当时封建经济的统治比较稳固，工商业不发达，康熙只致力于发展封建文化。清朝所做的坏事，历史已经做了结论，用不着多提，做的好事是应该讲一下的。汉族是个大民族，也做了很多好事，这就不用提了。这个思想不是我的，是毛主席多次讲过的。我说这些话的意思，是要说明就是和满族人结婚了也用不着自卑；我称赞了清朝做的好事，也不要骄傲。

　　浩夫人是日本人，同中国人结了婚，现在已经是中国人了，我欢迎你做中国人，参加中国的社会活动。

　　我讲的这样多，浩夫人还要再看一看，看一年、三年、五年、十年，看看是不是这么回事。哪一年觉得不适宜了，什么时候都可以回去。如果回到日本，比较一下，觉得中国好，还可以再来。来去自由，我可以保证，我可以签字，我相信你不会要我签字的。嫮生愿意回去，可以让她回去，不要勉强她留下。青年人变化多，以后想来，随时都可以申请护照。如果不来中国，同日本人结婚，又有什么不好？唐太宗把公主嫁给西藏王，汉藏通婚。嵯峨家把女儿嫁给爱新觉罗家。爱新觉罗家的女儿又嫁给日本人，有什么不好呢？

　　现在再来谈谈日本问题吧。浩夫人想致力于中日友好事业，其实，你和中国人结婚，今天又到中国来，这就是中日友好的象征。日本军国主义从一八九四年至一九四五年，损害了中国人民。日本经过明治维新〔57〕前进了一步，从封建社会到资本主义社会。搞明治维新的人物是有功劳的。日本比中国前进了一步，但是日本的资产阶级还有封建尾巴，后来逐步发展到军国主义，侵略朝鲜、中国，向外扩张，这是坏事。一八九四年〔236〕、九一八〔237〕、七七〔35〕，再加上“满洲国”，使中国人民受到很大损害。最近以大谷莹润〔238〕为首的代表团把中国在日本殉难的烈士名单送来，我们很感谢。解放十年来，有上万的日本朋友见到毛主席、刘主席和我，表示谢罪。我们说这已经过去了，中日两国有近两千来的来往，发展了经济文化交流，同近两千年比起来，五十年的时间是很短暂的，而且已经成为过去。我们应该往前看，应该努力促进中日两国的友好关系，恢复邦交，发展经济文化交流。我们并不总盯着过去的事情。毛主席说日本军国主义侵略中国是一件坏事，但它唤起了中国人民的觉悟。日本军国主义者认为中国人民是蠢才，是可欺侮的。事实并不如此。中国人民觉醒了，掀起了抗日运动，进行了抗日战争，一盘散沙团结起来了，睡狮觉醒了。这就是说，日本军国主义的侵略使中国人民团结组织起来了。土肥原〔239〕、冈村宁次〔240〕、东条英机〔241〕、板垣征四郎〔242〕等都不能破坏中国人民的团结，中国人民从来没有这样团结过。我们对日本人民毫无怨恨，日本人民也同样是军国主义的受害者。皇族、华族〔243〕也好，资产阶级也好，劳动人民也好，只要愿意同中国友好，我们都和他友好。参加过日本侵略政府的成员，只要他们赞成中日友好，我们仍然欢迎他们，如远藤三郎〔244〕先生、辻政信〔245〕先生、高碕达之助〔246〕先生和久原房之助〔247〕先生，我们都欢迎过他们。日本朋友来中国的，左、中、右都有，我们对日本朋友是门户开放的。我们不但欢迎共产党、社会党，就是为日本政府做情报工作的人，我们也让他来。

　　浩夫人回来了，愿意做个中国人，愿意为促进中日两国友好、恢复邦交而努力，我很欢迎。关于你回来的问题，你的丈夫和溥仪是踌躇的，他们担心中国目前有困难，比日本的生活水平低，但是少数人的生活是可以照顾的。你刚从生活水平高的日本来，还不习惯，需要照顾，将来习惯了，就不用照顾了。西园寺先生是贵族，但他不愿意过贵族生活，愿意到生活水平低的中国来，这还不是为了和平吗？



