# 说真话，鼓真劲，做实事，收实效

中文马克思主义文库 -> 周恩来
说真话，鼓真劲，做实事，收实效
（一九六二年二月三日）

我们检讨的目的，是为了增强团结。这里，最重要的是毛泽东同志讲的实事求是，也就是说真话，鼓真劲，做实事，收实效。

这几年来，党风不纯，产生了浮夸和说假话的现象。我们要提倡说真话。怎样才能做到这一点呢？要大家讲真话，首先要领导上喜欢听真话，反对说假话。如果你乱压任务，结果象同志们所说的，他就会准备两本帐，揣摩一下才讲，看你喜欢听什么再讲什么。这的确是一个党风问题。大家都说假话，看领导的颜色说话，那不就同旧社会的官场习气一样了吗？你们反映的情况我听起来觉得很痛心。你们说假话当然不对，但更重要的是我们压你们。从现在起，不要乱压任务、乱戴帽子了。要提倡讲真话，即使是讲过了火的也要听。唐代皇帝李世民，能听魏征〔263〕的反对意见，“兼听则明”，把唐朝搞得兴盛起来。他们是君臣关系，还能做到这样，我们是同志关系，就更应该能听真话了。

鼓真劲。有的劲就不是真劲。象你们所说的两个工厂，一个厂踏踏实实地干，说他“没劲”，“冷冷清清”，一个厂在那里造假，却说他是“轰轰烈烈”。这是庸俗地理解了毛泽东同志讲话的精神。毛泽东同志说，要鼓足干劲，力争上游。因为有上游，你才争上游。主观能动性要和客观可能性结合起来。我们提倡鼓干劲，不是鼓假劲，而是鼓真劲。鼓干劲也要实事求是，有的就是鼓假劲。比如有的提倡苦干几天几夜，过年也不休息。你在那里鼓劲，他就苦战，你走了，劲也没有了，他照样休息，照样过年。

做实事。做了实事，就有实效，否则强迫命令，就会搞一些不实在的东西。这几年《人民日报》宣传了许多不恰当的口号，如拔白旗〔264〕等，他们已经做了检讨。我在这几年也开过几次大会，发了不少奖状，如果表扬的事迹是假的，你就把“奖状”摔掉。我们要做实实在在的事，做实事，收实效，才会对人民有利。

说真话，鼓真劲，做实事，收实效。这四句话归纳起来就是：实事求是。实事求是是一句成语，毛泽东同志做了新的解释，它代表了毛泽东同志的一个根本思想。这四个字，话虽简单，却包含着丰富的内容。如何做到实事求是？首先要通过认真的调查研究。要调查研究得好确实是不容易的，因为现在已经有四年的浮夸风气，不易一下子改变过来。少奇同志去年回湖南家乡，开始群众不敢讲真话，有人封锁了真相。我也曾到一个地方搞调查，去之前，先派了办公室的同志去，后来发现反映的材料与实际情况还是有出入。你要了解真实情况，就要与老百姓平等相待。在战争年代，我们与老百姓住在一起，天天见面，不分彼此，和群众的关系很密切。现在就不一样了。比如我参加你们这个会议，一进会场，你们就站起来鼓掌，我就不舒服，但是又不好阻止你们。昨天下午你们没有鼓掌，我心里就很舒畅。因为有了那么一些形式，就显得不那么亲切，不是平起平坐，而是隔了一层。当然这一层不是一道墙，是一张纸。你们也都是老革命了，参加革命都有十几年、二十几年了，为什么还会产生这个隔阂呢？我想就是因为国家大了，“官”大了，和根据地的情况不一样了。所以你们鼓掌，我心里就不安。现在造成的这种形势，一定要改变，下决心改变。要搞好调查研究，就要真正联系群众。

我们要发扬民主，恢复和加强党内正常的民主生活。在战争年代，军队讲民主，就能打胜仗。规模最大的是解放战争，那时军队也最讲民主，仗怎么打法，作战方案怎么定，允许连队讨论，提出意见。这是毛泽东同志的创造，也是全军的创造。军队能够讲民主，为什么党内不能讲民主呢？我以为要按党章办事。少奇同志在七大做的修改党章报告，小平同志在八大做的修改党章报告，都讲到党内民主生活问题，但这几年有的同志把它搁到一边去了。当然有些事情是中央带的头。比如开电话会议，是中央先开的，以后一层一层开下去，电话会议又无法讨论，只能层层下压，这是不对的。少奇同志和小平同志的修改党章报告，对党内民主生活都有过说明。乱斗争行吗？不行。随便撤职，随便开除党籍，随便捕人、打人，都是不行的。当然有些是属于违法乱纪性质的，这不只是党内问题了。违犯了国家法律的，要按国法处理。

我们党内正常的民主生活要尽快恢复起来，毛泽东同志的建党思想要恢复起来，现在被搁在一边的党的优良传统和作风通通都要恢复起来。党内要有正常的民主生活，要实事求是，要按照党章办事。

＊这是在中共中央扩大的工作会议福建组会上讲话的第四个问题：检讨的目的。

