# 论知识分子问题

中文马克思主义文库 -> 周恩来
论知识分子问题
（一九六二年三月二日）


　　这几年，特别是近两年，从事科学工作和戏剧创作的同志很勤劳，很辛苦。虽然生活供应差，工作条件受到限制，甚至精神上也有些不愉快，但在科学工作、戏剧创作方面仍然取得了显著成绩，值得庆贺。我特别要向你们致敬。

　　今天能有机会和全国高级的优秀的有成就的科学工作者、戏剧写作者聚在一起谈一谈，对我个人来说是很高兴的事。因为时间关系，我只谈一个问题：知识分子问题。这个问题也包括我在内，我也是知识分子出身，谈起来会更亲切些。

一　知识分子的定义和地位
　　这个问题在党内部分干部中常常有不同的解释，在知识分子中也有些疑惑。现在尽我的能力作个初步解释，不能担保今天讲的都是成熟的，如讲得不恰当就改正。

　　知识分子不是独立的阶级，而是脑力劳动者构成的社会阶层。一般地说，这个阶层的绝大部分人在一定的社会条件下是附属于当时的统治阶级并为其服务的。在奴隶社会为奴隶主服务，在封建社会为地主阶级服务，在资本主义社会为资产阶级服务。在剥削阶级占统治地位时，知识分子多数是剥削阶级家庭出身的，出身于劳动人民的很少；只有剥削阶级才有条件求得知识，求得更高的知识。当时的大多数知识分子，常常容易接受并传播剥削阶级的旧观点和占统治地位的思想体系。在奴隶社会、封建社会或资本主义社会，尽管也有朴素的唯物主义，但总是唯心主义占上风。在旧社会，也会有一小部分知识分子能预见到真理，敢于反抗当时反动阶级的黑暗统治和压迫，为新兴的进步的阶级说话，成为革命的知识分子。马克思、恩格斯、列宁生长在资本主义社会，他们都是知识分子，敢于反抗当时的统治阶级，投入到新的阶级队伍中来，为新的阶级说话。他们背叛了原来的阶级，投降了进步的阶级。欧洲文艺复兴〔70〕时期，中国从鸦片战争〔141〕到辛亥革命〔73〕，都有一部分进步知识分子传播新的思想、新的学说。这些知识分子同样也遭到反动统治阶级的迫害，遭受反动知识分子的歧视和压迫。只有在社会主义制度下，劳动人民已经处在统治地位，知识分子才转变到为广大人民服务。一方面旧的知识分子得到了改造，一方面又培养出了新的知识分子，两者结成社会主义的知识界。现在还存在工人、农民、知识分子的差别。将来到共产主义社会，阶级和党派消灭了，脑力劳动者和体力劳动者的差别消灭了，工人、农民、知识分子的差别也就不存在了。

　　以上讲的是一般情况，是从整个社会历史发展阶段说的。

　　资本主义后期产生了殖民主义体系和帝国主义的统治。亚洲、非洲、拉丁美洲的许多国家成为帝国主义的殖民地半殖民地。这个广大地区的知识分子，同帝国主义国家的知识分子相比，有很大的特殊性。他们大多数站在民族立场上，反对外国殖民者和本国的卖国贼、民族叛徒以及帝国主义直接或间接豢养的走狗，成为革命的、爱国的知识分子。就连受外国欺压的民族资产阶级中的绝大多数人，也或先或后地站到了反帝爱国的立场上。所以毛主席再三地说，我们要团结世界上百分之九十以上的人来反对帝国主义。百分之九十以上的人，具体地说，是指工人、农民、进步的知识分子、进步的民族资产阶级分子和进步的民主人士（有一些还是封建阶级出身的）。中国现代知识分子就属于这种特定范围的社会阶层。

二　中国现代知识分子的发展过程
　　中国什么时候有知识分子？讲起来很远，远在奴隶社会就有。这是属于郭老〔265〕、范文澜〔266〕等历史学家们研究的问题。我只讲中国现代知识分子的发展过程。

　　（一）从旧社会来的知识分子，无疑地都受到帝国主义、反动统治阶级的种种影响。我也是其中的一个，是封建家庭出身，头上留过辫子。存在决定意识，怎么能没有影响？

　　（二）我们曾为旧社会服务，纵然不是为北洋军阀〔6〕或国民党直接服务，也是为旧社会服务，不能说没有受旧社会的影响。

　　（三）我们都受过资产阶级教育，甚至一部分人还受过封建教育，如上塾馆，拜过“天地君亲师”〔267〕，磕过头，手心挨过打，罚过跪，封建教育嘛！不过现在也还有些用处，知道些诗云子曰。解放后我去天津，回到曾读过书的南开中学，第一句话就说：“我在这里受过资产阶级的教育，但是也要感谢，当时对我有启蒙作用。”受到资产阶级教育，不能光说不好，它对我也有启发。这样说才全面一点。

　　这三条是从旧社会来的知识分子的“根”，这种“根”，不能否认。

　　还是以我为例。有人问我是哪里人，我说原籍绍兴，生在淮安，江浙人。为什么这样罗嗦呢？因为我的亲兄弟、堂兄弟都是绍兴人，我不能不说原籍是绍兴，否则就有企图摆脱这种关系的嫌疑。我生在淮安，祖父当过淮安县知事，外祖父是淮阴县知事，现在还有家属在淮安，如果我不说生在淮安，和他们的历史关系也无法交代清楚。一个人的历史关系要交代清楚，这样没有坏处。不管现在情况如何，不能抹掉过去的历史。我经过革命锻炼，现在当然不再是资产阶级知识分子，应该说是革命知识分子了，但写历史不能把过去那一段抹掉。毛主席很不满意有人写他的传记时，说他从小就懂得很多，什么都知道。毛主席说他小时候还烧过香。我小时候也迷信过菩萨，后来还相信过无政府主义〔268〕。五四运动〔39〕时，我们组织了觉悟社〔269〕。后来有人问邓颖超〔270〕：那时你们是不是共产主义小组？她回答说：还不能称为共产主义小组，是研究新思潮的一个组织。我们的社员有研究无政府主义的，有研究基尔特社会主义〔271〕的，也有研究共产主义的。以后有不少人加入了共青团和共产党。青年人不了解，以为这样说太谦虚了，其实历史是发展的，个人也是发展的。一九二○年我到法国，还对费边社会主义〔272〕有过兴趣，但很快就抛弃了。我感谢刘清扬〔273〕和张申府〔274〕，是他们两人介绍我入党的。张申府的思想很杂，研究罗素〔275〕哲学着了迷，他想把孔子、罗素、马克思、弗洛依德〔276〕、爱因斯坦〔277〕的思想熔于一炉。

　　总之，有一点要肯定，大家是从旧社会来的，不管现在如何，过去都属于资产阶级知识分子类型。

　　但是另一方面，也是更重要的一方面，应该看到中国绝大多数知识分子受帝国主义、封建主义、官僚资本主义的统治和压迫，因而有一部分人参加了革命，一部分人同情革命，多数人开始时对革命观望、中立，以后逐渐靠近革命。反革命的知识分子是极少数。直接为清朝、北洋军阀、国民党反动派服务，真正成为他们的工具压迫人民的只是少数。从鸦片战争到辛亥革命是如此，从旧民主主义革命到新民主主义革命也是如此。从鸦片战争到现在一百二十多年的历史事实证明，为帝国主义、封建主义、官僚资产阶级服务的知识分子，都是没有前途的。溥杰〔217〕过去到日本留学过，有什么作为？还是新中国改造了他，才有了用。他的叔父载涛〔222〕过去做过军谘大臣，不如现在当人大代表，可以为人民服务。在我们这里有不同等弟的人，沈衡老〔278〕是进士公，黄任老〔79〕是举人公，董老〔279〕是秀才公，还有翰林公〔147〕。秀才、举人、进士、翰林都有。过去想做点事业，可是做不成，有什么办法？北洋军阀时代的李根源〔280〕是我的“同行”，当过国务总理，能为国家民族做什么有益的事？国民党时代的行政院长翁文灏〔60〕回来了，也是高级知识分子，当时跟他们走有什么出路？死心塌地为美帝国主义服务的胡适〔281〕，直到了结生命，还是没有出路。反过来，历史的发展证明，知识分子只有同无产阶级，同劳动人民，同共产党一道前进才有出路。革命时期和社会主义建设时期都证明了这一点。

　　不论是在解放前还是在解放后，我们历来都把知识分子放在革命联盟内，算在人民的队伍当中。解放前，毛主席在《论联合政府》中讲过。解放后，刘少奇同志在一九五六年党的八大一次会议上也讲过，他说：“无产阶级只有同广大的可以接受社会主义的群众结成联盟，才能形成最大多数人对于反动阶级的专政。”我们是团结全国的最大多数人，在民主的基础上实行集中，是最大多数人对少数人实行专政。人民民主专政不同于资本主义社会、封建社会、奴隶社会的少数人对多数人的专政，剥削阶级对劳动阶级的专政。他还引用列宁的话：“无产阶级专政是劳动者的先锋队――无产阶级同人数众多的非无产阶级的劳动阶层（小资产阶级、小业主、农民、知识分子等等）或同他们的大多数结成的特种形式的阶级联盟，……是为最终建成并巩固社会主义而成立的联盟。”〔282〕列宁在对“非无产阶级的劳动阶层”的说明中包括了知识分子。这是讲的无产阶级同其他劳动者的联盟。中国又扩大了联盟，一直扩大到同民族资产阶级的联盟。中国是半封建半殖民地国家，有反对帝国主义、封建主义、官僚资本主义的任务，要同民族资产阶级保持政治上的联盟。同民族资产阶级的联盟是无产阶级同非劳动者的联盟。坚持这两种联盟是我们的战略方针和长期的历史任务，在我国的统一战线中将长期起作用。对知识分子的估计要以这个为纲。这一点，党内不少干部常常不注意，解释不清楚。无产阶级根据这个既要同其他劳动者结成联盟又要同非劳动者结成联盟的方针，就提出了一个改造的任务。

　　（一）无产阶级首先要进行自我改造。天下没有完人，觉悟程度是逐步提高的，认识也是不断发展的，因此要经常进行自我改造。无产阶级有自己的阶级本性，反抗剥削压迫，思想先进，但要发展成为有高度觉悟性、战斗性、组织性的阶级，也要进行自我改造。无产阶级和资产阶级生活在一个社会里，不能不受资产阶级思想意识和习惯势力的影响，而且还有封建的影响。所以，无产阶级、共产党要不断消除自己队伍中的非无产阶级思想影响，把旧的东西剔除掉。只有能自我改造的人，才能改造别人。在延安整风〔14〕时，毛主席就首先要求党内进行学习和改造。

　　（二）无产阶级对其他劳动者实行团结、教育、改造的方针，这主要是对农民和从旧社会来的知识分子说的。改造什么呢？改造非无产阶级的思想意识和习惯势力，使他们接受无产阶级的思想和观点。要求农民同农村中资本主义自发势力的影响作斗争，要求知识分子改造资产阶级的思想体系和习惯势力。这样，才能使他们和无产阶级一道建设社会主义，将来还要建设共产主义。

　　（三）无产阶级对民族资产阶级又团结又斗争。在经济上采取利用、限制和改造的方针，利用其有利于国计民生的方面，限制其不利于国计民生的方面，从加工定货到定股〔283〕定息〔124〕，进而取消定息，消灭其阶级的经济基础。在政治上思想上则要改变其阶级立场和观点。这要经过长期的工作。这种工作的目的是要使他们成为社会主义的新人。当然，民族资产阶级也是我们的同盟者，但是属于另外一个方面的同盟者。

　　总起来说，无产阶级对其他劳动者或非劳动者的改造，是为了最后消灭阶级和阶层。只有这样，才能实现共产主义。到那时，工农差别、体力劳动和脑力劳动的差别都不存在了。这需要一个很长的时期，中间要经过许多阶段。

　　两种联盟的矛盾性质不一样。无产阶级同其他劳动者之间不存在对抗性的矛盾，同非劳动者之间还存在着对抗性矛盾的一面。无产阶级要消灭资产阶级，不是对抗性的吗？但我们改变资本主义所有制采取的是赎买的政策，而不是没收的办法。对农民则是逐步引导他们从个体所有制进入集体所有制，这是非对抗性的矛盾。解决非对抗性的矛盾是一个长期的过程，要采取说服、教育、示范、提高的办法。同样，体力劳动者与脑力劳动者之间的差别，也要经过长期的过程，在生产发展的基础上，通过互相学习，逐步接近，才能逐步消除的。这样看，我们同知识分子的联盟与同民族资产阶级的联盟是有根本区别的。

　　由于中国知识分子有上述的发展过程，使得他们也有两重性：一方面是脑力劳动者，可以为人民服务；另一方面又与旧社会有千丝万缕的联系。因此，党和国家有必要与可能对他们采取团结、教育和改造的方针，知识分子也有必要与可能摆脱旧社会的影响，成为适应新社会需要的知识分子。所以说，党和国家对知识分子的根本政策，也是知识分子本身的根本任务。

　　根据这样的方针和自我改造的任务，十二年来，我国大多数知识分子已有了根本的转变和极大的进步。一九五六年我曾作过关于知识分子问题的报告，对知识分子的状况作了初步估计。刘少奇同志在一九五六年党的八大一次会议上也说，“知识界已经改变了原来的面貌，组成了一支为社会主义服务的队伍”。毛主席的《关于正确处理人民内部矛盾的问题》，是一九五七年二月二十七日在最高国务会议上讲的，到一九五七年六月才发表，那时已有右派进攻〔249〕，但并不因此而改变原来的分析。他说：“我国知识分子的大多数，在过去七年中已经有了显著的进步。他们表示赞成社会主义制度。他们中间有许多人正在用功学习马克思主义，有一部分人已经成为共产主义者。这部分人目前虽然还是少数，但是正在逐渐增多。当然，知识分子中间有一些人现在仍然怀疑或者不同意社会主义，这部分人只占少数。”毛主席对知识分子的估计，是很清楚的。

　　从一九五七年到现在，知识分子受到了锻炼和考验，特别是最近两年，全国人民除少数反动分子外都经住了这种考验。我们一方面在建设中取得了伟大的成绩，另一方面在工作中也出现了偏差和错误，加上三年来农村灾荒，粮食和经济作物减产，城市工业生产也有些下降，市场物资供应减少，物价部分上涨，实际工资有所下降。这种情况还要持续一个时期。中国知识分子的大多数同工人、农民一样经得起考验。我们不能说没有人对这种情况有意见，意见是应该有的，大多数人是出于关心提出改进意见，希望情况有所改善。只有极少数人幸灾乐祸。工人、农民、知识分子大多数是热爱祖国的。科学工作会议的《简报》我都看了。《简报》上反映了这样的情况，大家工作努力，生活上克服困难，甚至遇到心情不怎么舒畅的事情还能克制自己。你们热爱祖国，使我们很受感动。这是中国知识分子的骄傲！中国人民是从民族苦难的日子里熬出来的。在座的有的是经过几个朝代的人，看到了民族解放，人民胜利了，参加了社会主义建设，经受了困难，对前途充满了信心。

　　从《简报》中还看到大家提出了一些善意的批评，不能不使我高兴。经过十多年的努力，知识分子队伍壮大了，从老一辈知识分子手里培养出了新的一代知识分子，文化、教育、卫生等方面都培养出了新的力量。饮水思源，是党的政治思想工作起了作用，也是知识界共同努力的结果。青年人的成长是老一辈亲手培养的，这一点要很好地向青年人讲清楚。从老知识分子身上找毛病是很容易的，但要看主导方面，要看到各有所长。比如我讲话可能不如青年人讲得流利，但是谈问题、论经验则比他们深些。如果说要互相尊重，首先要教育青年知识分子尊重老年知识分子。老年知识分子中许多人努力学习马克思列宁主义、毛泽东思想，有些人加入了党，这是可喜的现象。

　　但是，十二年当中，甚至很长时期内，总有一小部分人怀疑或者不同意社会主义，保持原来资产阶级知识分子的立场，拒绝改造甚至进行反对社会主义的活动。这些人是资产阶级知识分子，甚至是右派。毛主席对民主党派领导人曾经讲过，现在资本主义的经济基础消灭了，“皮之不存，毛将焉附”，资产阶级知识分子不要做“梁上君子”〔284〕，这部分知识分子应该投到无产阶级方面来，承认共产党的领导，这才有出路。这话是有所指的，是在一九五七年五一前后说的，但是到六月，右派还是进攻。当时反击是必要的，但这决不会动摇我们党在整个历史时期对知识分子的根本政策和战略方针，决不会改变无产阶级同其他劳动人民的联盟。我们党内有一部分同志对这些认识不清楚。

　　在知识分子内，也和党内一样有左、中、右。任何党派、社会团体内都有左、中、右，这是规律，是客观存在。左、中、右或者说进步、中间、保守，他们之间也会相互转化，保守可以转向进步、中间，中间、进步也会变成保守。但是有些部门和机关用左、中、右去排队就不好了。人的思想状态是会变化的，政治思想、主张经常有变化，特别是对科学上生产上许多问题的看法不同，不属于政治思想上的分野，更不能用左、中、右去划分。如在建设工作中，有个时期说高指标是正确的，低指标是保守的，这是不对的。现在钢的产量定在一千万吨以下，这不是保守，不是右倾，这样可以搞得扎实些，对建设更为有利。指标能高就高，该低就低，不能拿这些来作政治分野。

　　就是对一小部分坚持资产阶级立场的知识分子，只要他们不进行反党反社会主义活动，我们在政治上还是把他们算在联盟之内，对他们进行教育。进行反党反社会主义活动的则作别论，那就是反革命，就是犯法了。对右派，还要给他们工作，还要容纳在统一战线之内，有的还在政协嘛。我们要团结最大多数的人，能改造的改造过来，不能改造的孤立起来。

　　这是对中国知识分子发展过程应有的认识。党没有低估知识分子的作用，党的政策是明确的。知识分子也应心安理得地知道自己的作用。

三　如何团结知识分子
　　毛主席在《关于正确处理人民内部矛盾的问题》中说：“我国的艰巨的社会主义建设事业，需要尽可能多的知识分子为它服务。凡是真正愿意为社会主义事业服务的知识分子，我们都应当给予信任，从根本上改善同他们的关系，帮助他们解决各种必须解决的问题，使他们得以积极地发挥他们的才能。我们有许多同志不善于团结知识分子，用生硬的态度对待他们，不尊重他们的劳动，在科学文化工作中不适当地干预那些不应当干预的事务。所有这些缺点必须加以克服。”现在看来，毛主席这段话仍然是击中要害的，完全适合当前的情况。如何团结知识分子，应该根据毛主席的这段话去做。

　　首先谈一谈我们党能否领导一切。一九五七年以后，党对科学文化工作的领导进一步确立了。知识分子承认和接受党的领导，是党和人民的胜利，也是知识分子的光荣。必须肯定，党应该领导一切，党能够领导一切。现在的问题是如何领导一切？什么是一切？这个问题正在逐步解决。我们已经制定科学工作十四条〔285〕、高等教育六十条〔286〕、工矿企业七十条〔287〕，文艺方面也提出了几个初稿〔288〕。关于党如何进行领导，存在着各种想法。解决这个问题，必须在中央领导下提出一套办法来，征求党外朋友的意见。

　　下面我谈谈关于党的领导方面的几个问题。

　　第一，党的领导范围。我们说党领导一切，是说党要管大政方针、政策、计划，是说党对各部门都可以领导，不是说一切事情都要党去管。至于具体业务，党不要干涉。人家熟悉，要信任他们。如果他们做不好，可以检查，有意见可以讲，但党委的意见不一定都是对的。如果什么都管，连发戏票、导演戏都去管，结果忙得很，反而把大事丢掉了。小权过多，大权旁落，党委势必成为官僚主义、事务主义的机构。

　　第二，党的领导不是党员个人领导。党是一个集体，是有组织的。党的领导是组织领导，不是个人领导。党员个人怎么能领导？一个单位的个别党员，怎么能说他就是党的领导？党章没有规定党员有这样的权利，实际上也不可能有这样的本事。尤其是一些年轻党员，应该向有经验的知识分子学习。我们过去在广州搞革命时，少年气盛，有点“乱指挥”，这种不好的传统不要学。要学毛主席好的传统――调查研究，从实际出发。个人没有权力领导一切，不管是谁。如果把我下放到剧团，虽然我也曾演过戏，现在必定是个蹩脚的演员，只有向人家虚心学习，哪能领导？我们到下层单位最怕听“请指示”。就有这样的党员，人家请他指示，他就俨然以领导者自居，摆出领导者姿态，发号施令。这是最坏的官僚主义者。要平等待人才是好勤务员，才不是官僚主义者。

　　第三，上下级要有区别。例如一个学校，党的领导是指学校党委领导，有些事情学校党委也不能解决，要请示上级党委决定。至于支部，如系支部、剧团支部、车间支部，只是起保证监督作用，不是指挥，下命令还得要行政首长才行。

　　第四，党委领导是集体领导，不是书记个人领导。没有经过党委讨论的大事，书记不能随便决定。行政上的事由行政决定，书记也无必要去干涉。

　　第五，外行领导内行要有个范围。以前我们讲过外行能领导内行，这是讲的政治上思想上组织上的领导。党委书记、委员有些不懂专业，但可以超脱专业，看到全局，通过党委集体研究作出贯彻党的方针政策的决定或贯彻上级指示的决议。我们说外行能够领导内行，不是要外行去干涉业务，对业务确实不懂嘛。外行变成内行，要经过学习，就是学会了，也要尊重专家，尊重群众意见。有些同志说，科学研究要走群众路线，不要搞群众运动，这个说法比较恰当。科学研究不是靠突击和群众运动能解决问题的。

　　关于如何正确对待知识分子，我以为有六个问题要解决好：

　　第一，信任他们。他们承认和接受党的领导，愿为社会主义服务，愿意自我改造，党就要信任他们。你信任他，他也就信任你，彼此有了信任，就可以团结在一起工作。

　　第二，帮助他们。知识分子所处的环境需要党的帮助，以诚心诚意的态度去帮助他们，对工作才有好处。

　　第三，改善关系。过去关系不好的，应该改善，先从党委、党员方面做起，先检查自己，不能只责备人家。检查了自己就能引起共鸣。党的具体政策你在执行中有偏差和错误的，要作检查。党团结知识分子的政策，要通过党员和党组织实现。

　　党内有些术语不合适，每次看到心理就不安，如在一些登记表上分“党员”、“群众”。这两个词不是同一组概念，党员、非党员才是同一组的概念。党员也是群众中的一员，包括领导人在内，不能自居于群众之上。“党员”、“群众”的分类，使党员居于群众之外、群众之上。我们犯官僚主义，一方面由于自己脱离群众忙于事务，另一方面是别人把我们封锁起来。我们也很苦。希望领导同志要自觉，不要把自己置于群众之外，不要被封锁。

　　第四，要解决问题。不解决问题使人感到诚意不够。问题能够解决的，一定要解决。现在问题成堆，不能一下都解决。科学工作会议的《简报》，快出到五十期了，其中提到的有些问题不可能马上都解决。但要负起责任来，力求逐步解决。

　　第五，一定要承认过去有错误。对于党与非党的关系、领导与被领导的关系、上级与下级的关系、各部门之间的协作关系，会上有些意见批评得很对。各级领导要以老老实实、实事求是的态度，承认错误，改正错误，有则改之，无则加勉。过去对同志们批评错了的、多了的、过了的，应该道歉。党内我已道过歉，现在利用这个机会，再作个总的道歉。

　　第六，承认了错误还要改。只承认错误，不去改正，还是空话。凡是党和政府方面犯的错误都要改正。改要有实际行动。

　　以上六个问题要解决好。

四　知识分子的自我改造
　　（一）所有的人包括共产党员在内都要自我改造。改造有性质上和程度上的不同。对地主、富农、反革命分子、坏分子的改造，是带有强迫性的，这与人民内部通过劳动、生产、学习进行的改造有性质上的不同。人民内部的改造，只有程度上的不同，没有性质上的不同。旧东西多的多改，旧东西少的少改，去掉坏的影响。

　　（二）思想改造是长期的。把资产阶级世界观转变为无产阶级世界观，需要一个过程。首先是爱祖国，进一步愿为社会主义建设服务，更进一步接受党的领导，逐步改变旧的立场和思想体系。就是长期在党内锻炼的同志，无产阶级世界观也不见得那么巩固。

　　（三）改造靠自觉。自我改造的程度如何主要决定于自觉性。

　　（四）改造的方法要和风细雨，不能粗暴。这样气才能顺，心情才能舒畅，才能接受帮助。帮助人不能给人“上大课”，知识分子最怕别人给他“上大课”，要促膝谈心。

　　（五）改造要互相帮助，互相学习。没有人是专门改造别人的。自居于领导，自居于改造别人的人，其实自己首先需要改造。要对这种人大声疾呼：“请你自己先改造！”任何共产党员都不是十全十美的，不可能什么都懂。人生有限，知识无限，到死也学不完，改造不完。帮助人家，首先要学习人家的长处。

　　（六）人总有缺点的，世界上没有完人，永远不会有完人。事物总是有矛盾的，有矛盾就能促进事物发展，如果停止发展，就会灭亡。

　　自我改造是为了进步，是光荣的事情。现在大家肚里有气，是我们工作没有做好，帮助不够，要把这个扣子解开。毛主席说，我们的目标，是想造成一个又有集中又有民主，又有纪律又有自由，又有统一意志、又有个人心情舒畅、生动活泼，那样一种政治局面。过去科学、文艺工作方面成绩是主要的，希望今后要不断改进，取得更大的成就。



　　＊这是对在广州召开的全国科学工作、戏剧创作等会议代表的讲话。同月二十七日、二十八日，周恩来同志在第二届全国人民代表大会第三次会议上做的《政府工作报告》，进一步阐明了知识分子在社会主义时期的地位和作用，明确肯定了我国知识分子的绝大多数是“属于劳动人民的知识分子”。



