# 国民经济的调整工作和当前任务

中文马克思主义文库 -> 周恩来
国民经济的调整工作和当前任务
（一九六二年三月二十八日）


　　中共中央在一九六○年下半年，对国民经济工作提出了以调整为中心的调整、巩固、充实、提高的方针。这个方针，是在当前的条件下，具体贯彻执行党的鼓足干劲、力争上游、多快好省地建设社会主义的总路线〔289〕的方针，是一个既从当前实际情况出发、又为长远打算的积极的方针。它包含着多方面的内容，主要的是，要适当地调整农业、轻工业和重工业的相互关系，生产和基本建设的相互关系，经济事业和文教事业、国防事业的相互关系，积累和消费的相互关系，以及财政、信贷和物资的相互关系。各个经济部门和文教部门的内部，也要进行适当的调整。

　　在社会主义建设经过了一个非常大的发展以后，进行全面调整是十分必要的。在我国前几年社会主义建设的大发展中，出现了许多不协调的现象。为了改变这种不协调的现象，为了巩固已有的成绩，为了给以后的国民经济的新的大发展创造条件，就必须用一个较长的时间，即用几年的时间，通过综合平衡、全面安排，进行较大幅度的调整。

　　在当前的国民经济调整工作中，恢复和发展农业生产是一个中心环节。我国国民经济中出现的不协调现象，农业生产下降的影响最大。没有农业的恢复和发展，就不可能有国民经济的协调发展。多年来的经验完全证明，我国国民经济的发展，必须以工业为主导，而以农业为基础。我国有广大的农业，农业现在的生产水平又是很低的。在这种情况下，工业的发展不能不受农业的限制，也就是说，工业的发展规模，绝不能超过农业提供商品粮食、工业原料和其他农副产品的可能性，也绝不能挤掉农业所需要的劳动力。只有当农业生产提高以后，我国工业的发展才能得到更有利的条件。我们应该充分发挥农民的生产积极性，改进农业的生产条件，适当地增加对农业的投资，加强各方面、特别是重工业对农业的支援。这样，农业生产力就能够逐步地恢复和发展，农业生产就能够逐步地提高。所以，我们必须遵照毛泽东主席的指示，把农业放在发展国民经济的首要地位，按照农业、轻工业、重工业的次序来安排经济计划。重工业必须为农业提供越来越多的各种农具、农业机械、化学肥料、木材、燃料等等，来不断地提高农业的劳动生产率，使农业能够为工业和城市提供越来越多的粮食、原料和其他农副产品。轻工业必须尽可能为农村提供越来越多的日用品，以利于发展城乡交流，逐步改善城乡人民的生活，增加国家建设资金的积累。

　　一九五八年以后几年，重工业有了巨大的发展，这是大家感到高兴的事。但是，重工业内部各行各业的发展是很不平衡的。在进行国民经济调整工作中，为了恢复和发展农业，为了适当地发展轻工业，为了协调重工业内部各行各业的关系，我们必须放慢重工业的发展速度，有些重工业部门的生产指标，必须大幅度地下降。这样做，是十分必要的。这是因为：第一，如果继续采取过去那样高的速度发展重工业，势必妨害农业的恢复和发展，妨害轻工业的发展，这不但对人民的生活不利，而且重工业本身也不可能继续高速度发展。第二，重工业内部的填平补齐，要花很大的力量，只有把那些过分突出部分的生产指标降下来，才能加强那些薄弱的部分。第三，某些产品产量的下降，是为了提高它的质量和增加它的品种。质量提高了，品种增加了，即使数量较少，也会得用得多。例如钢材，就是这样。第四，维修好国民经济各部门急需维修的设备，是目前的一项重要工作。而要维修好设备，也必须适当减少某些产品的生产，以便腾出一些材料和生产能力，生产必要的部件、配件和零件。所以，我们在一段时间内降低重工业的某些生产指标，正是为了使整个国民经济在长远时期内能够更好地前进，使现有的生产能力真正发挥它的作用。

　　这几年，我们施工的建设项目很多，有些已经建成和部分建成，有些已经停建，有些还在施工。即使那些已经建成和部分建成的项目，有许多还没有建立必要的协作关系，或者设备还不配套，或者还缺乏原料、材料，都需要有一个较长的时间，进行大量的工作，才能逐步地发挥作用。因此，现在一般地不应该再增加新的项目，而且，对还在施工的项目必须逐个地进行审查，坚决地停建一切应该停建的项目，推迟一切应该推迟的项目，以便集中力量，建成那些十分必要的重要项目，并且使那些已经建成和部分建成的项目配起套来，逐步地发挥作用。今后几年内，我们都要根据这个方针来安排基本建设，这是调整工作的一个重要方面。

　　随着农业、工业生产和基本建设的调整，商业方面，财政金融方面，文化教育事业方面，也都必须进行一系列的调整工作。

　　一九六○年以来国民经济的调整工作进行的情况，大体如下。

　　在农业方面，一九六○年下半年，我们除了在改进农村人民公社的工作方面，进行了巨大的努力以外，还采取了一些支援农业生产第一线的有效措施。一九六一年，我们继续进行这些方面的工作，并且从城市动员了约一千万人下乡，他们中的绝大多数，是最近几年从农村到城市来的，他们回去以后，加强了农业生产战线。由于贯彻执行农村人民公社工作条例草案六十条〔290〕，由于实行以生产队为人民公社的基本核算单位，农民的生产积极性大为提高，农村的形势就开始好转。虽然由于自然灾害，一九六一年的夏收很差，但是全年的粮食产量比上一年要多一些。在许多地方，家禽、家畜的数量，目前正在逐渐上升。

　　工业的调整工作是从一九六一年开始的。我们在这一年较大幅度地减少了重工业的生产任务，缩小了基本建设规模。我们努力增加日用品的生产，恢复了手工业生产合作社。中共中央制订的国营工业企业和手工业的工作条例草案〔291〕，对于改进工业企业的经营管理工作，对于改进手工业生产，有着重要的作用。目前，工业生产下降的情况已经基本停止，产量开始稳定，有的开始上升，不少产品的质量有所提高，品种有所增加。

　　这几年，我国职工人数增加了很多，就业面扩大了，使一部分家庭增加了收入。但是，职工人数和城市人口增加过多，工资总额增长过快，而农业和轻工业又减产很多。这样，商品供求之间就出现了差额，城乡供应都比较紧张，职工的实际工资有所下降，人民生活发生困难。

　　在商品不足的情况下，国营商业部门和有关部门做了不少的工作，加强了农副产品和工业日用品的收购；在灾区和非灾区之间组织了某些生活必需品的调剂；压缩了企业、事业单位、机关、团体、学校、部队的集团购买力，腾出了一部分商品供应市场；基本上保证了城镇居民最必需的粮食、蔬菜、食油、食盐、煤炭、日用品等的定量供应。定量供应城乡居民的商品，价格基本上是稳定的。

　　由于连续三年灾荒，一九六○年和一九六一年，我们减少了粮食的征购数量。一九六一年我们从国际市场进口了五百万吨粮食。大家知道，全国解放以后，我国不仅不再进口粮食，而且每年有一定数量的粮食出口。现在进口粮食，虽然一时是必要的，但是，这种状况必须尽快地努力加以改变。

　　一九六○年冬天，各地方有计划、有领导地开放了农村集市贸易，这对于促进农副业生产发展，活跃农村经济，起了一定的作用。现在，各地方正在根据这一段时间的经验，加强对农村集市贸易的管理。一九六一年，许多地方又恢复了农村中的供销合作社。

　　一九六一年，在城市中，国营商业除了平价供应的商品以外，开始出售糖果、糕点等少数几种高价商品。这是在物资不足、购买力和商品供应量之间差额过大的情况下的一种临时性措施。

　　随着经济各部门调整工作的逐步展开，我们对教育、科学和其他文化事业也进行了必要的调整，适当地降低了它们的发展指标。在科学研究、高等教育方面，由于试行关于自然科学研究机构当前工作的十四条规定草案〔285〕和教育部直属高等学校暂行工作条例草案〔286〕，工作开始有了改进。

　　应该指出，我们对于调整工作的认识是有一个发展过程的。在中共中央提出调整、巩固、充实、提高的方针以后，政府虽然做了许多工作，但是，在有些方面贯彻不力，调整不够全面，没有迅速地在应该后退的地方退够，没有迅速地在应该加强的地方足够地加强。现在，经过一段时间调整工作的实践，我们更加清楚地认识了调整工作的必要性和应该采取的措施、步骤。

　　在一九六二年，我们必须采取更有力的措施，切实按照农业、轻工业、重工业这样的次序，对整个国民经济进行全面调整，合理安排，以便集中主要力量，逐步地解决人民的吃、穿、用方面的最迫切的问题，并且逐步地在国民经济各部门之间建立新的平衡。当然，这并不是说，全部调整工作今年就可以做好。我们应该在今后几年中，把调整作为经济工作的主要任务。但是，今年的工作做好了，就能够为以后的调整工作打下可靠的基础，就有可能争取较快地完成调整任务。从这个意义上说，一九六二年是调整国民经济的极关紧要的一年。

　　当一九六○年实现第二个五年计划所规定的一九六二年主要工业产品的生产指标的时候，国家计划委员会即着手拟订第二个五年计划后两年的国民经济调整计划。由于在一九六一年继续遇到了严重的自然灾害，而且灾情更重，由于在调整工作的过程中，发生了许多新的问题，还有许多情况没有摸清楚，需要进一步研究，所以，我们编制两年调整计划的工作，还没有全部完成。国务院请求全国人民代表大会同意：国务院在第二个五年计划后两年的国民经济调整计划确定以后，把这个计划连同财政预算，提交全国人民代表大会常务委员会，由人民代表大会授权常委会审议批准。

　　这里要说一说当前调整工作的任务。这些任务，是在一九六二年要做的事，其中有些也是在一九六二年以后还要继续进行的。

　　为了做好一九六二年国民经济的调整工作，国务院要求各级政府机关、各行政部门的全体干部，加强调查研究，继续摸清情况，按照中共中央既定的方针、政策，在中央集中统一的领导下，扎扎实实地进行工作，特别要抓紧完成增产节约、精兵简政、稳定市场、改善供应这几个方面的任务。具体说来，有下列十项。

　　第一，争取农业增产，首先是争取粮食、棉花、油料的增产。

　　一九六一年，我国农业生产的情况已经开始好转，但是，好转的情况，在全国各地是很不平衡的。有一部分地区生产上升，大部分地区生产已经稳定下来，还有一部分灾情特别严重的地区，生产情况仍然不好。从现在的条件看，全国大多数地区要恢复到原来最高的生产水平，还需要作艰巨的努力。我们应该用一切可能的力量，争取一九六二年有一个比较好的收成。

　　恢复和发展农业生产，首先必须增产粮食。有了粮食，才能比较迅速地恢复经济作物的生产，才能保护和增殖耕畜，发展家畜和家禽。在努力增产粮食的同时，要适当安排棉花、油料等经济作物的播种面积，保证它们逐年有所增产，以便逐步增加城乡人民的布匹、食油等生活必需品的供应。合理安排种植面积和人力、畜力，是一件很重要的事情。各级政府和农村人民公社，在安排的时候，要很好地同生产队商量。

　　农村人民公社、生产大队和生产队，要继续贯彻执行农村人民公社工作条例修正草案，实行以生产队为基本核算单位的规定，更好地调动广大农民的生产积极性。要把一切可以利用的零星小块的土地尽量利用起来，力争多种多收。要抓紧水利、积肥、选种、修补中小农具、田间管理和防治病虫害等工作，尽力提高单位面积产量。要切实保护好耕畜，做好牲畜的配种繁殖和兽疫的防治工作。农村人民公社的各级干部，都要正确地领导生产，在推行各种增产措施的时候，一定要根据当时当地的条件，吸取群众的经验。

　　国营农场必须加强管理工作，严格实行经济核算，努力提高劳动生产率和农、牧业产品的商品率，完成和争取超额完成国家计划。

　　应该注意保护林木，努力植树造林。应该努力发展畜牧业和渔业。

　　各级政府应该组织各方面的力量，加强对农业的支援。对于农业所急需的生产资料，特别是制造和维修中小型农具、车、船的材料，制造化肥、农药的原料，要尽可能优先保证供应。

　　各级政府在安排农产品征购任务的时候，要同时安排好群众的生活。

　　第二，合理安排轻重工业生产，尽一切可能多增产日用品。

　　为了适当满足城乡人民生活的需要，扩大城乡之间的商品交换，改善市场供应的状况，我们在安排工业生产的时候，应该首先注意安排日用品的生产。轻工业部门和手工业部门，当然要努力增产日用品；重工业部门，凡是有条件的，也应该尽可能地增产适合市场需要的日用品。

　　由于农产品原料不足，在日用品的生产中，应该尽可能利用重工业部门生产的原料、材料。有些轻工业和重工业都需要的原料、材料，在分配的时候，应该先照顾轻工业的需要。轻工业部门和手工业部门，应该使那些原料、材料消耗低而产品质量高、品种多的企业，能够优先得到供应。

　　一切轻工业企业和手工业单位，一切重工业企业，都要厉行节约，争取用较少的原料、材料，生产更多更好的产品。对于一切可以利用的废气、废物，应该注意回收，充分利用。

　　重工业部门当前的首要任务，是保证农业生产资料的生产，增产更多的化肥和农药，增产更多的中小型农具和适合需要的、质量更好的农业机械。同时，还应该为轻工业多提供原料、材料。重工业部门应该努力增产目前特别感到不足的原料、材料和燃料，并且要根据国民经济各部门设备维修和配套的需要，有计划地安排急需的备品、配件、零件和必要的辅机、主机的生产。

　　重工业各部门应该根据上述任务和可能条件，进行调整工作。对于那些不是当前急需、原料材料供应不足的产品，应该降低它们的生产指标，并且对生产这些产品的企业进行必要的裁并。对于那些当前各方面急需、而又供应不足的产品，应该努力增产。对于煤炭、木材等，为了保证它们能够在一定水平上持续生产，应该妥善安排它们所必需的材料、设备和投资。重工业各部门在调整工作中，都必须注意生产能力的填平补齐、成龙配套。

　　工业部门对于国防建设所必需的材料和设备，要注意组织生产。

　　一九六二年工业方面一项重要的工作，是切实按照国营工业企业工作条例草案，改进企业的经营管理。一切工业企业，都要加强责任制，加强技术管理，加强经济核算，加强劳动保护，在提高产品质量、增加产品品种、提高劳动生产率、降低成本这几个方面，做出显著的成绩。

　　交通运输部门，应该进一步整顿好运输秩序，并且切实安排好短途运输。对于车、船和铁路、公路、航路，要做好维护的工作。

　　第三，进一步缩短基本建设战线。

　　目前基本建设战线仍然过长的情况，对国民经济的调整工作是不利的，我们计划再减少一些不是十分必需的基本建设项目。这样做，不仅可以腾出一定数量的材料、设备和人力，用到最急需的方面，特别是农业生产方面，而且可以集中力量，使那些最重要的建设项目，能够建成投入生产，发挥作用。

　　鉴于过去对基本建设项目和投资的管理不严而造成战线过长的教训，今后，一切基本建设项目和投资，都要列入国家计划。基本建设项目，都要按照国家规定的程序，逐项地分级地审查、批准；没有经过审查、批准的，一律不准动工。列入国家计划的项目，各部门、各地方也要根据设备制造情况、需要的缓急和施工技术力量，进行排队，依序完成，并且保证质量。

　　过去两年中，我们已经停建了一些基本建设项目，今年又将停建一些项目。建设项目中途停建，是会造成一些损失的。但是，如果应该停建的还不停下来，就势必分散力量，使许多重要的工程不能迅速发挥投资效果，就会造成经济上更大的损失。当然，对于那些中途停建的项目，必须切实做好维护工作，避免损失。一切停建项目的设备和材料，必须由国家统一调剂使用。

　　第四，压缩城镇人口，精简职工。

　　压缩城镇人口，精简职工，这是调整工作的一个重要环节。目前的城镇人口仍然过多，农业可能提供的商品粮食和其他农产品，供养现有的城镇人口还有困难。工业生产和基本建设的指标降低以后，现有的职工人数也还显得过多。我们的机关、企业和事业单位，仍然存在着机构庞大、人浮于事的现象。为了改变这种状况，我们计划在一九六二年继续压缩城镇人口和精简职工。

　　动员城镇的人口和职工，首先是动员从农村来的职工，回到农村参加生产，不仅可以加强农业生产战线，提高企业的劳动生产率和机关的工作效率，而且可以减轻城市供应的困难，节省国家的开支。各个部门、各个单位，应该做好动员工作和组织工作，城镇乡村密切配合，妥善安置精简下来的人员。我们希望到农村去的职工，在农业生产和建设的光荣岗位上，为国家做出新的贡献。

　　现在有些企业、有些部门的负责人，还没有从全局利益出发，下最大的决心精简职工。他们总想把一些以后可能有用的人力都保留下来。这种想法是不对的。当然，企业在精简职工的时候，要注意保留必要的技术骨干，但是，有些技术工人，如果目前没有适当的工作，也应该动员他们回到农村去，农村很需要他们。将来企业单位技术力量不足的时候，还可以把他们调回来参加工业生产。

　　在城镇和人口密度大的农村，要认真地提倡节制生育。

　　第五，彻底清理仓库，重新核定资金。

　　目前物资不足，给生产建设和人民生活带来了不少的困难，但是，许多地方、部门、企业、事业单位中还积压着大量的属于全民所有制的物资，不能统一调度，合理使用。为了改变这种不合理的状况，国务院已经决定，要在全国范围内进行一次清理仓库、调剂物资的工作。所有的企业、事业、机关、学校、部队各单位的仓库，都要进行一次彻底清理。清查出来的物资，由有关部门按照国家的统一规定，分别处理。企业的流动资金，将根据新的情况，由国家财政机关重新核定；多余的资金，一律收归国库。这样，就可以使积压的物资和资金活动起来，用在当前调整工作最必需的方面。根据初步统计，仅积压的钢材一项，至少有一百多万吨。这些积压的物资，只要我们统一调剂使用，就会逐步地发挥作用。

　　第六，改善市场的供应状况。

　　各级商业部门和商业企业，在稳定市场方面担负着艰巨的任务。在一九六二年，必须切实做好商品的收购工作和供应工作，扩大城乡物资交流，使市场供应的状况有所改善。

　　国营商业和合作社商业对于农副产品和三类物资〔292〕的收购，要兼顾国家、集体、个人三方面的利益，恰当地规定购留比例，并且努力改进收购办法。国营商业对于日用工业品，要及时地进行收购，按照国家的规定统一调度。国营商业对于一部分日用工业品，合作社商业对于一部分手工业品，可以采取加工、定货的办法，增加货源。

　　在商品不足的情况下，合理地分配商品是一项很重要的工作。国营商业部门要尽可能多地组织切合农村需要的工业品下乡，凡是农村急需的生产资料和生活资料，应该优先供应农村，以适当满足农民的生产和生活的需要，促进农业生产的恢复和发展，并且多换回一些农副产品，供应城市居民的需要。在城市中，要改善商品的供应办法。为了尽可能挤出更多的商品供应市场，企业、事业单位、机关、团体、学校、部队要进一步节约行政开支和事业费用，压缩集团购买力。

　　为了适应工业生产多方面的需要，改变某些企业之间以物易物和采购人员过多的现象，国务院确定恢复和加强一些专业公司的业务，统一组织有关物资、特别是三类物资的供应。

　　一切国营商店、供销合作社、消费合作社和合作商店，都要接受人民群众的监督，切切实实地为城乡人民的生活服务，为农业和工业的生产服务。所有的商品，都要按照正常的商业途径出售，彻底纠正和防止开“后门”的现象。

　　国营商业应该切实改善经营管理工作，加强对整个市场的领导，使农村中的供销合作社、城市中的消费合作社和合作商店发挥它们应有的作用。国营商业今年要把一部分人员，包括原来的小商小贩，转到合作商店；对于他们要加以妥善安排。

　　商业部门和税收机关必须加强对农村集市贸易的管理，并且同投机倒把现象作斗争。

　　第七，保证完成对外贸易任务，偿还外债，努力承担国际义务。

　　建国以后，苏联给予我们的贷款，对于我国的社会主义建设起了很好的作用。这一部分贷款，我们已经偿还了大部分，还有一小部分没有偿还。最近几年，我们在同苏联和东欧社会主义国家的贸易中，对他们又有一部分欠款。所有这些外债，我们将争取在几年内逐步还完。今后，我们应该继续发展同各兄弟国家的互助合作。同时，在平等互利的原则下同资本主义国家发展贸易。

　　胜利了的中国人民，在进行社会主义建设的同时，还要根据可能的条件，给兄弟国家和民族主义国家以援助，这是我们不可推卸的国际义务。事实上，并不光是我们援助他们，他们也援助了我们。我们对兄弟国家和民族主义国家的援助，现在还不是很多，但是，这种援助，是他们所需要的。他们的建设工作做好了，他们的反帝国主义的力量增强了，这就是对我们社会主义建设事业的重要支持。

　　为了有计划地偿还外债，承担必须承担和可能承担的国际义务，为了换取我国所需要的进口物资，尽管国内工农业产品不足，我们还是应该挤出一些来出口。各地方、各有关部门，都必须努力按质、按量、按时地完成国家规定的出口商品的生产任务和收购任务。

　　第八，提高文化、教育、科学研究、卫生等工作的质量。

　　为了使文化、教育、科学研究、卫生等各项事业的发展同经济建设的发展相适应，这些部门，也应该贯彻执行调整、巩固、充实、提高的方针，并且以调整为中心，来安排自己的工作。

　　一九六二年，各级学校都要努力提高教学的质量。全国的高等学校，凡是具备条件的，都应该试行教育部直属高等学校暂行工作条例草案。

　　科学研究部门，应该适当调整现有的机构和研究人员，充实重点的科学研究单位，并且加强各个科学研究单位之间的协作。

　　卫生事业方面，要切实改进医疗工作，加强疾病的预防，增产中西药品，增加城乡药品的供应。

　　文艺、新闻、出版、广播、体育等事业，也都要进行适当的调整，提高质量，更好地为国家建设和为人民服务。

　　第九，节约支出，增加收入，加强现金管理，保证财政收支平衡。

　　保证财政收支平衡和信贷的平衡，是政府当前的一项重要工作。所有的经济部门和企业单位，都要改进经营管理，加强经济核算，加强财务管理，努力降低生产成本，努力降低商品流通费用，尽可能增加收入，减少支出。

　　现金管理不严的情况，应该彻底改变。一切企业、事业单位和机关团体，都要严格遵守国家的现金管理制度、信贷管理制度和财政管理制度。企业从银行借的款，应该按期归还。企业的流动资金，只能用于生产周转和商品流通的需要，不能用于基本建设、弥补亏损和其他财政性开支。一些企业的亏损现象，应该迅速改变。财政金融部门应该加强对国民经济各部门的财政监督。

　　各部门，各地方，各企业、事业单位，各机关、团体，都应该继续坚决贯彻执行勤俭建国的方针，反对铺张浪费，努力节约开支。

　　第十，进一步改进计划工作。

　　为了适应国民经济调整的需要，国务院责成政府的各级计划机关，把主要的注意力，从工业交通方面移到农业和市场方面来，切实按照农业、轻工业、重工业的次序和调整的具体任务，安排国民经济计划。

　　计划机关在拟订国家计划的过程中，应该进行系统的调查研究，根据准确的资料，集中各部门、各地方的初步计划，精打细算，不留缺口，做好综合平衡，力求使国家计划指标符合实际，并且适当留有余地，保持必要的后备。

　　我们的计划工作必须走群众路线，倾听群众的意见，吸取各方面的专家、科学家们的意见。

　　各部门、各地方，都应该及时地如实地提供情况和统计数字，提出关键性的问题，拟订有可靠根据的计划草案，帮助国家计划委员会制订切实可行的国家计划。在国家计划确定以后，都要严格执行，保证实现，不得随意改变。对于计划的执行情况，要严格检查。

　　调整国民经济的任务是十分艰巨的。目前，我国国民经济还有相当大的困难，人民吃的东西、穿的东西、用的东西，都还不足。这种情况，需要一个时间的艰苦努力，才能够根本改变。在实现调整任务的过程中，我们还可能遇到这样或者那样的新的困难。对于这些，都应该有足够的估计。但是，困难从来没有吓倒过勤劳勇敢的中国人民。我们有着战胜困难的许多有利条件。这些条件主要的是：

　　第一，我们有在中国共产党领导下的巩固的工农联盟和以工农联盟为基础的广泛的人民民主统一战线。全国各族人民同党和政府密切合作，这是战胜困难的最大的保证。

　　第二，社会主义建设的总路线已经进一步发展和完备起来，这对于促进全国人民在社会主义建设问题上的思想统一和行动统一，有重大的意义。

　　第三，在过去几年的伟大实践中，广大干部和人民群众所取得的丰富的经验，包括许多正面的经验和一些反面的经验，使我们有可能进一步地认识和掌握社会主义建设的客观规律，把工作做得更好。

　　第四，农业生产正在逐渐上升，农村形势正在开始好转，这对于克服目前的困难，对于活跃整个国民经济，对于进一步巩固工农联盟，都有重要的作用。

　　第五，这几年扩大了的工业生产能力，新增加的农田水利建设，正在逐步地越来越大地发挥作用。这是我们克服困难的重要的物质条件。

　　只要我们能够充分地运用这些有利条件，善于依靠群众，同群众商量办事，发挥群众的积极性和创造性，就一定能够一步一步地战胜我们面前的困难，胜利地完成国民经济的调整任务。



　　＊这是在第二届全国人民代表大会第三次会议上所做的《政府工作报告》中“国内形势和我们的任务”部分的第二节。



