# 我国人民民主统一战线的新发展

中文马克思主义文库 -> 周恩来
我国人民民主统一战线的新发展
（一九六二年四月十八日）


　　今天，讲一讲我们国内人民民主统一战线的新任务和新发展。我国人民民主统一战线，不仅在新民主主义革命中取得了全国的胜利，而且在社会主义改造的过程中继续取得了胜利，现在面临着社会主义建设的伟大任务。因此，在人民民主统一战线这个组织、这个力量面前又提出了新的任务，它又要有新的发展。前天我在全国人民代表大会的会议上也说了，对一切事物的发展都有一个认识的过程，我们的统一战线也是一样。在新民主主义革命阶段，统一战线由建立、扩大、缩小、再扩大，一直到胜利，在这中间，我们就有反复的经验。革命胜利以后，在社会主义改造的过程中，人民民主统一战线是起了作用的，动员了社会上一切可以团结的力量来参加社会主义改造的工作，使我们的社会主义改造进行得比较顺利、比较快。进入了社会主义建设阶段，人民民主统一战线的任务就更重了，就要负起新的任务（当然，同时还有社会主义改造的任务），就要有新的发展。就是说，它在社会主义改造和社会主义建设取得伟大成果的基础上，现在要团结一切可以团结的力量，动员更多可以动员的因素，来参加社会主义建设，扩大我们的民主生活。这就是我们的新任务。不要把我们人民民主统一战线看成只是进行社会主义改造的，它的作用，不但表现在社会主义改造方面，而且表现在社会主义建设方面。我们要把建设的任务担当起来。

　　为着更好地实行民主集中制，我们首先要扩大和发扬民主生活，这也是我们人民民主统一战线要担当的任务。在人民民主统一战线中间，不能说一切参加的成员和所动员起来的力量对我们党和国家的方针、政策都是同意的，会有一部分人不同意的。在这个问题上，我们应当具体分析，区别对待。如果有人违背了毛主席所说的“六条标准”〔293〕，站在敌视和破坏社会主义建设的立场，甚至进行破坏活动，那么，他就是自外于人民，变成非人民内部矛盾了，当然不能把他当作人民内部的问题来对待了。“六条标准”更集中地说就是：接受共产党领导，积极为社会主义服务，愿意进行自我改造。如果采取了这样的立场和态度，在具体政策上持有不同的意见，与其说应该允许，毋宁说我们欢迎。在人民内部有一些对立面的意见，这对我们的进步是有好处的。我们不可能设想，人民民主统一战线是铁板一块，大家都是一个想法，对任何问题的看法都一样。如果我们的统一战线是这样，它就不能发展，就会停止不前，甚至要后退。不要说一个组织、一个团体、一群人不能有这样的情况，就是一个人的头脑里面，也不能有这样的情况。每天的客观存在，反映到人的头脑里面，在思维的过程中，经常有不同的意见产生。自己肯定了的东西，后来自己又否定了。这样看对了，那样看又不对了，几个侧面看完全了，才掌握了全面。原来没有认识到的，后来认识到了，以后又有了更加新的认识。这样，一个人的思想才能发展，一个党的政策也才能完备，一个团体的工作也才能在这个过程中间得到改进。我们的统一战线组织也要在这样的发展过程中间前进。所以我们说，毛主席提出的两类矛盾，特别是人民内部矛盾，是会长期存在的。正确处理人民内部矛盾，是指导我们统一战线民主生活的原则。因此，我们应该肯定统一战线的任务是加重了，有了新的发展。同时，我们应该在统一战线的内部，提倡在“六条标准”的原则下发表各种不同的意见，彼此讨论、研究、切磋，以求得更好的认识，求得更符合于真理，不断推动我们的事业前进。从这一点上看，我们这一次的会议，可以说是初步反映了这个要求，是一个开端。

　　这一次我们开了二十多天的会，有二百多位委员发言，提了四百多件提案。我们不能说，大家的意见都说完了，要说的都说出来了。如果这样看，就把问题看死了。不可能的，还会有一些保留的意见没有说出来，先说一点看看，看党和政府机关能不能接受。这样的想法是允许的，也很自然。因为过去一个时期说得少，批评得少。现在我们大开言路，开了以后，是否会发生问题呢？有这种想法的人，我们应当允许他们保留意见，应当等待。的确，我们也得看看。大家提了这么多的意见，其中有的是好的，有的是要斟酌的，有的是不能成立的。党和政府机关是否真正采纳？提案审查委员会提出来的审查意见，交到有关机关去，它是否做？我想，应该观察一个时期。比如昨天胡先骕〔294〕先生的讲话，我当时就把他的讲话稿送到科学技术委员会去了，请聂荣臻副总理去研究办理。我也要保留一点意见，也要看一个时期，晓得科委是否真正研究照办呀！所以，不仅是发言人本身要看看，就是我们主持事务的人也要看看。当然，不是所有的意见都能够马上做的，有的还要斟酌，有的还要准备条件，但都要认真进行研究。我们这个统一战线，要动员广大的力量来发扬民主生活，参加建设。不单是政协应该做，各民主党派、各人民团体、各民族、各方面都要把它所联系的人们动员起来参加，这才是把统一战线的全部成员动员起来了。所以我们说，这是一个开端。我希望这是一个良好的开端。根据这样一个认识，我想分别说说以下几方面的问题。

　　第一，有关政协的工作问题。

　　今后政协的工作，责任更重了。政协过去的工作，应该说做得不错。这一次陈叔通副主席关于政协工作的报告，内容就比过去更丰富，说明我们各方面工作更发展了。但是，我们觉得还不够，还要求更好地发展。首先，政协要多组织一些调查研究工作。要使我们的建设搞得更好，首先就要实地调查，才能知道实际情况，如实反映情况，才有具体材料、具体经验可供讨论和研究。不要面临政协开会了，才到下面去视察访问，平常也可以分期去，比如说一年下去几次，不一定都要同时去。现在是调整阶段，更需要多知道实际情况。政协这个机构，应该参加这个工作，到农村和城市去进行调查研究工作，再回到政协里面来时，就可以交换意见了。不管中央的、全国的、地方的，都可以交换意见，交换经验。这样，我们的座谈会、报告会就有生动的事例来讨论，就能够产生一些提案、意见和建议，使得各方面的力量都动员起来。其次，政协过去的工作，偏重于政治学习、国际活动和文史资料的收集，今后要多开展学术性的报告和讨论，要有意识地多邀请学术界的朋友参加。这一次会议反映这方面的意见多起来了，发言的同志在这方面也提供了很多宝贵的意见。从建设的要求来看，我们也需要发展这方面的工作。过去一个短时期里，全国政协也曾经组织过学术性的报告会，但是做得不多。今后除去政治学习和文史资料的收集工作还应继续进行外，应该更多地进行学术性的报告和讨论。我们是政协机关，可以同时提出各种不同的意见，争论的结果，不一定得出一致的结论，可将不同的意见提交有关方面，如政府机关、科学研究机关、教育机关或者其他学术团体。这些不同意见的提出，表现了“百花齐放、百家争鸣”的方针在这里的贯彻。多有些不同的意见，就使执行机关能从多方面去考虑，利于选择比较更恰当的方案来执行。

　　第二，共产党在政协的责任。

　　大家都承认共产党是领导党，共产党的领导是指党的集体领导，党的中央和党的各级领导机构（省、市、县委员会等）的领导。起着领导作用的，主要是党的方针政策，而不是个人。个人都是平等的，如果从工作上说，大家都是人民的勤务员，彼此平等地交换意见，决不能个人自居于领导地位。个人离开了集体，就无从起领导作用。个人的意见不能代表政策，必须制定成政策，才能算为集体的意见、领导的意见。所以，个人平常讲点意见，包括我今天在这里的讲话，是个人的意见。不能说今天我所讲的每段话，都经党中央集体讨论过，当然有些是讨论过的，但有些只是个人的意见，只能作为建议供大家参考研究。所以，共产党员必须首先把这个界限划清楚。在政协里边，在我们个人的来往当中，没有领导与被领导的关系，只有领导机关和政策才是代表领导的。不然的话，我们的民主生活、民主风气就不能够发扬，我们之间就有隔阂，中间本来没有墙，就会有一座精神的墙隔着，妨碍民主集中制的贯彻。其次，要实现民主生活，还要求共产党员多交党外的朋友。既然我们扩大了统一战线，共产党又在这里起领导作用，我们党员应该把许多党外的意见集中起来，集中到党的领导机关来。这就要和党外的朋友来往，就要听到一些不同的意见。共产党员在一起也会有不同的意见，但是由于工作环境相同，政治生活相同，这些人的意见总是比较容易接近。因此，所反映的总不会那么全面，一定要听取各方面的意见才能全面。同样，党外朋友如果听不到共产党的意见，也会想得不那么全面。所以，党内外应该相互多交朋友，特别是共产党员应该主动多交党外的朋友。每个共产党员都得有几个党外朋友来往，可以多交新朋友，也可以有些固定的朋友，能够反映一些意见，敢于提出意见的。陈毅副总理昨天谈到，要有畏友。就是说，他敢于提出不同意见，敢于批评对方的短处，习惯了就不是畏友而是诤友了。我们共产党员要多听不同的意见，才能多知道各方面的意见。不同的意见不一定都对，但你要听了才有比较。当然，在不同的意见中，更重要的是广大群众的意见，就是在公社、工厂等基层组织里从事生产活动的广大群众的意见，还有学校里的群众的意见。这些直接从群众中来的意见更加宝贵。我们共产党员既然参加了政协，那就要特别注意多接触自己不熟悉的事情和不熟悉的人物。你既然不熟悉，就证明你在这方面有缺陷，你去接触了，才能认识，才能了解，才会得到有益的东西，即使是反面的意见，甚至不对的意见，你也可以作比较。习惯于只限在自己的小圈子里，只喜欢听相同的意见，听不到不同的意见，对不熟悉的事也不愿意去熟悉，把自己局限起来，这样工作就会越做越窄了。所以，我们首先要求党员多交朋友，希望参加会议的各省、市、自治区的党员回去后将上述的精神向在地方政协的党员传达。这次会议上，有朋友说，希望共产党员多和党外人士接触。我想这个要求是合理的，你们有权利提出这个要求，因为每次会议相隔一年，这次更长，有一年多不会面，有这么个机会，朋友们当然有权利要求同共产党员多接触，多交换意见，多谈心。

　　总之，党员要承认我们有很多事情还不知道，知识还有限。我们的确是要做到老学到老，改造无止境。有这样的精神，才能有进步。我们难道都改造好了吗？不可能的，总有些渣滓，总有点需要改造的，有自觉我们才能进步。这方面要求共产党员应该严一些。如果说“严于责己，宽于责人”，对共产党员就应该要求严些。党外的同志们也应该责备我们严一点。我想责备严是好事，是统一战线中的好朋友。当然这是为了把国家搞好，把社会主义事业搞好，而不是对个人的攻击。

　　第三，各民主党派的责任。

　　各民主党派在统一战线中的责任，应该说不是轻了，而是更重了。有不少朋友参加了最高国务会议，说了我们工作中的缺点和错误。刘主席说：责任在共产党，在共产党中央，民主党派没有责任，或者很少责任。毛主席也这么说。而民主党派的许多朋友说：民主党派也有一定的责任。我看这样说法很好，把责任引为己任。那么，好了，过去的已经过去了，我们取得了教训。今后要把事情搞得更好，大家要共同负责，长期共存，互相监督，民主党派要负起监督的责任。我们把事情报告出来，也作了初步的经验总结，今后根据大家同意的方针和任务去执行。在执行过程中，民主党派要进行监督、提意见。所以我们说：民主党派在社会主义改造和社会主义建设中的责任是更重了，而不是轻了。各民主党派都是为社会主义事业服务的。为社会主义事业服务，本身就锻炼各党派和他们的成员。各党派的成员中总是有进步、中间和落后的，正如共产党员一样也有进步、中间和落后的。各党派就要在组织中不断地以为社会主义服务这个标准，把自己的成员锻炼成忠实于社会主义事业的人，不断地推动他们进步，使中间状态的转向进步，摆脱落后。除原有的成员外，一个组织总还有新的成分进来，党派总还有发展，吸收进来的也有进步、中间和落后的，所以党派本身就具有不断改造不断推进的作用。对于我国的社会主义改造，由于存在的各个阶段、阶层的状况比较复杂，不能设想得太容易。我们过去有一段时间设想得太容易一点，以为经过社会主义三大改造〔129〕，我们的社会不是属于全民所有制就是属于集体所有制，好象社会主义改造很快就能完成。不仅农村，城市都得进入人民公社，把街道里弄都改造过来，成员都改造过来。而且还有一部分人，认为很快地就能从集体所有制转到全民所有制。现在看来这些想法是不恰当的。我们这样一个经济落后的国家，人口这么多，地区这么辽阔，民族这么多，尽管民主革命进行得彻底，社会主义改造进行得顺利，但是，整个社会的改造是不可能一下子就完成的。因为它的经济水平比较低，在这样的经济水平的基础上，上层建筑不可能那样快地完整地改造好，总是参差不齐，不平衡现象总是长期存在的。社会主义改造要随着整个社会主义建设的进展才能相应地完成。如果说我们中国实现现代化需要几十年的时间，那么，整个社会主义社会完全建成，就得花更长时间，然后才能向共产主义的高级阶段前进。我们一定要有一个比较长期的想法，认识社会主义改造需要一个很长的时期。因为不仅是经济，而且各种旧的政治影响和习惯势力，对我们仍有影响，虽然占统治地位的旧东西被打倒了，但一些旧的政治影响也还是依靠旧的习惯势力而存在着，至于思想作风上的问题就更多了，这种改造就要更长时期。广大的劳动人民尽管从本质上说是有建设社会主义的积极性的，但旧的习惯、思想作风在他们的头脑里还起影响，也要进行改造。何况我们的社会存在着各界、各阶层的分子，更加需要努力改造。因此，各党派要动员所代表的方面，不仅参加社会主义建设，并且努力改造。各党派代表的方面不一定相同，在比较接近的那一方面多做工作，就更可以促进社会主义的改造，使整个社会主义改造的发展更健康一些。这就是说，不仅从建设的意义上，而且从改造的意义上，也需要各党派的合作，根据长期共存、互相监督的方针来进行工作。

　　第四，工会的作用。

　　工会是统一战线中的人民团体，是工人阶级的阶级组织。工人阶级是领导阶级，他不仅要把自己的成员教育好，还要影响其他阶级阶层；不仅自己的组织要健全，还要影响其他方面。现在我们面临着调整的任务，首先在工人队伍本身就要进行一些人员调整。工会要在调整中对它的成员做工作。工业、交通、基本建设系统和各种企业事业、国营农场，都是工会活动的范围，都要搞好增产节约。工人生活现在有一定的困难，如何保证生活供应，如何帮助解决生活上的困难，工会负有很大的责任。因此，在国家任务面前，工会今天的责任更重大更复杂，要做的事比以前更多而不是更少。工会要配合党和政府去进行工作，因为工会是党的主要助手，统一战线的主力军。工会不仅要注意解决工人生活困难问题，而且要把生活问题提到政府面前。中央和地方上的精简工作如果做不好，工会有权把问题提出来，要起监督作用。当然不是与政府对立，是协助政府办事。政府没做好的事，工会可提意见。党派互相监督，工会也可以同其他方面互相监督，这要作为任务，大家一条心，朝着一个方向，把工作做好。

　　第五，青年团的作用。

　　青年团任务也加重了。别的不说，就拿青年学生的教育，我前天在人大会议上讲了，我们今年高等学校和中等学校要少招生，因此高小和初中毕业生就会有一部分不能升学。在这方面，青年团就有工作可做，可以在城市和农村组织和推动补习教育，使青少年不至于因无学校可上而到处乱转。帮助他们自修自学，也可以培养出一批人才。不一定人人都是从正规学校毕业才能到社会劳动，有一部分没有进大学的也可以一样做事。我们同辈党员中有很多专家并没有进过正规的大学。我们这一代是如此，后一代是不是一定都要在大学或高中毕业？我看在目前经济情况下还不可能要求这么高。将来要求人人至少达到中学毕业，但现在还不可能实现。这就需要青年团在这方面进行教育，提倡自修自学，帮助补习，不仅可以公办，也可以自办。一个人在家开业帮助几个青年补习功课，收点学费是允许的。这是全民所有制和集体所有制以外的一种辅助的方式。甚至于某些手工业者、文艺家收几个徒弟学习，也是许可的。我们应该开这方面的路。

　　还有，在城里征兵，去年是第一年实行，有成效，打算今年还继续实行，特别是在大、中城市。青年团要在这方面好好宣传。我们提倡“好男当兵，四海为家”，社会主义社会培养教育出来的有了选举权的青年要积极报名入伍，造成一种空气。特别是干部子弟更要做模范，要带头入伍，入伍后也不要因为是干部子弟就要求受优待。

　　第六，妇女组织的作用。

　　妇联在一些方面也要负责任。例如，要在居民委员会和农村中提倡补习教育。要帮助做母亲的鼓励成年的儿子入伍。有时候，干部子弟入伍，做母亲的反而更舍不得，当然这是个别现象，但是也值得提出来。我前天讲到，在城市和人口密度大的农村中，要提倡节制生育。希望妇联也来提倡一下。过去做过，证明是有效的。

　　第七，工商联的工作。

　　工商联的责任也加重了。一方面，我们对工商业者的定息〔124〕，延长三年，到时再议。另一方面，工商业者也面临着调整的情况。工商业者里面有民族资产阶级分子，小业主等上层小资产阶级分子，也有小商小贩，其中一部分要回到集体经营或者是个体经营的商业中去，一部分还保留在国营的企业、事业单位里面，也有一部分年老的可以实行退休制度。这些人如何安置，政府要负责，但是工商联可以协助政府来进行工作，调查这方面的情况。我觉得目前的情况，不但全国的工商管理局要加强，省、市的工商管理局也要加强，好跟工商联联系。对工商业者的安置要适当，例如有些人不适合到农村去，家又在城市，就不能勉强，应该在城市里面安置。在这一方面，问题比较多。工商业者中间也有一些生活困难的，工商联可以从定息中抽取一定的比例作互助金，如果不够，政府也可以协助。我跟陈叔老〔147〕谈过这个问题，要在这方面研究一些具体的办法。工商联协助政府在工商业者的改造、参加社会主义建设和生活安置等各方面做工作，更要加紧，不要放松，事情会更多，不会更少。

　　第八，文教科学团体。

　　在这次会议上，大家的提案和发言讲得最多的是这一方面的问题，从数量上和质量上来看都很重要。陈毅〔213〕同志昨天在发言中答复了很多，我不想在这里再多说了。总之，我们进行社会主义建设要拿出自己的力量来，这就需要使文教、科学队伍更加强、更发展，质量更提高，教学制度搞得更好。这方面的工作，过去一个时期注意得不够。今后不仅要从政府系统、教育系统、科学研究系统和生产系统来加强，就是政协系统，也要来加强。要使我们的文教科学事业的发展适应经济建设的要求，把过去的追求数量转到重视质量、重视科学技术水平的提高，真正使我们在文教科学方面的“百花齐放、百家争鸣”能够做得更好，不仅是形式，而且是有内容的。拿政协来说，担任副主席的各位，从文教出身的就占多数。昨天陈毅同志自告奋勇，这一方面如果有意见可以向他反映。不仅陈毅同志，我们管科学、管文教的其他同志也在这里，希望这一方面被重视起来。

　　至于思想上拔白旗、插红旗〔264〕的问题，昨天陈毅同志讲得很好。思想上怎么来拔白旗？红旗怎么能插进去呢？解决思想问题，这需要逐步提高认识，通过自我学习、自我认识、自我改造的过程，才能办到。昨天陈毅同志说，中共中央对这一提法没有责任，是下边搞的。我要给他改正一下，他可能忘记了。昨天文教办公室的张际春〔295〕同志给我写了一个条子，他说中央有一个文件上面有这么一句话。我今天查了一下，果然是这样。中共中央应该承担这个责任。这个话说得很生硬，可以作几种解释。属于头脑中的事情，怎么能一下子拔白旗、插红旗呢？这样是插不进去的。有时候对一种估计或者一种情况，随便一说，文字上没有注意，就会引起不好的后果。我们应该承认这种缺点错误。

　　第九，兄弟民族的关系问题。

　　这一点在政府工作报告中已经回答了。关于民族自治区的一些问题，需要在会后经过政府的程序来解决，还可以在政协的民族组来讨论，人大的民族委员会和政府的民族事务委员会还准备合起来开会讨论。有一些需要政府执行的，一定尊重各个兄弟民族的代表人物所提出的好的意见，经过考虑和研究来执行。例如过去在行政编制上、民族干部问题上，有许多处理是有缺点错误需要改正的，这里就不去多说了。

　　第十，宗教问题。

　　政协里有宗教单位。过去一个时期，这方面的工作有些缺点错误，一些宗教界的朋友提出来批评，有许多好的意见是值得我们重视的。我们把宗教信仰问题常常看得太简单了，拿共产党员马列主义的认识来要求所有的人，要求所有人的人生观、世界观都一样，这是不可能的。思想认识是逐步改变的，而且思想认识问题是人民内部的问题。就宗教信仰来说，更是一个长期的问题。我们只是希望，爱国的宗教界人士，热爱祖国，愿意为社会主义服务，也愿意努力学习。这样，他们思想上还有宗教信仰，这并不妨碍我们整个人民民主统一战线的扩大和团结，并不妨碍我们祖国的社会主义建设。

　　第十一，华侨问题。

　　这一次参加人大、政协会议的华侨代表，都是在国内工作的。政协只有几位委员在港澳工作，人大只有两位代表在香港工作。联系华侨要通过我们的华侨事务委员会。华侨工作有两个方面：一个方面是侨居在国外的；一个方面是他的眷属在国内，或者回国来工作、学习的。党和国家有关这一方面的政策，已经讲过多次。目前也发生了一些问题。例如照顾眷属的问题，华侨干部在城市工作怎样下放的问题。有很多人原来在城市，适合于在城市安置。这些问题，我们的华侨事务委员会应该注意，政协的华侨组也可以研究。

　　政协所包含的还有其他的方面，我就不一一去说了。

　　总之，我们政协包含各个党派、各个人民团体，是由这些单位的成员组成的，通过这些单位的成员，联系全国的各个方面，联系全国的人民，以至联系到海外的侨胞。通过这次会议，使得我们的统一战线更扩大、更深入了，工作更加重了。人大所批准的政府工作报告和我们的方针任务，通过我们政协，向国内的广大人民讲清楚，我相信是会收到我们预期的效果的，正如《人民日报》在昨天的社论中所号召的：“团结奋斗争取新胜利”。我们肯定了成绩，批评了缺点错误，也提出了解决问题的方针任务，这样就可以增强我们建设的信心，保证我们能够克服面临的困难。我们团结奋斗，争取新的胜利，是有把握的，是有信心的。



　　＊这是在中国人民政治协商会议第三届全国委员会第三次会议上的讲话。



