# 认清形势，掌握主动

中文马克思主义文库 -> 周恩来
认清形势，掌握主动
（一九六二年五月十一日）


　　刘少奇同志在扩大的中央工作会议〔296〕的报告中分析了全国的形势。他说，我们最困难的时期已经基本度过了，但目前还处在一个严重困难的时期。对于这一点，我在那次会上作了分析。现在看来，总的情况还是那样，但需要作进一步的说明。

　　为什么说我们的政治形势和经济形势，从总的方面看最困难的时期已经基本度过了呢？

　　在政治上，全党全国人民的绝大多数，党外人士的绝大部分，高举三面红旗〔297〕，取得了成绩，经历了困难。经过这次考验，大家是团结的，这在和平建设时期，是一件了不起的事情。同时，这几年对各项具体政策，我们也在逐步补充和完备。

　　在经济方面，我们开始高举三面红旗前进的时候，对于新的事物缺乏经验，在执行中犯了很多错误，有很多缺点，而且有很多是原则性的、很严重的。但是在这个过程中，我们从正面反面初步总结了经验，逐步地认识和掌握了新情况下的发展规律，不象过去那样懵里懵懂了。从这一点说，我们比过去也清楚了一些。

　　现在，农村中连续三年灾荒造成的困难正在克服中，农业生产下降的趋势，除部分地区还在继续外，大多数地方已经停止并开始回升。这四年，工业和基本建设的计划指标本身就没有综合平衡，结果一面是跃进，一面又被迫地大调整，被迫地后退。年终的产量跟年初的计划数字差得很大。工业问题，可以说是在逐渐认清形势，逐步掌握主动。现在，我们主动地调整指标，大家在数字上基本没有争论了。前几年如果提出今年这样的调整指标，是不可设想的。这就说明，现在大家的认识比较一致了。

　　所以，从总的方面说，不论政治形势或经济形势，最困难的时期的确是度过了。如果现在还是懵里懵懂，后果还要严重。当然，现在影响还没有完全消除，但我们总是能够预见发展趋势了。

　　为什么说目前情况还很严重呢？因为我们主观上的失误造成的经济发展不平衡的后果，不是短时期能够消除的，只能逐步解决。经济工作千头万绪，毛泽东同志说要越做越细，而我们在这个时期恰恰是越做越粗，过去几年甚至可以说是越做越乱。工作上造成这样的后果，影响就比较长远，直到现在还没有结束。灾荒的后果也是严重的，虽然我们克服了许多困难，但是受灾面积这样大，影响这样深，也不是一时能够扭转过来的。

　　有些地区和部门的情况还很严重。部分地区工作中的错误还没有纠正过来，或者灾荒还很严重。工业、基建部门过去工作中的错误所造成的后果还继续存在，并影响到其他部门，现在在调整中就看出来了。当然，这些地区和部门绝大多数也在纠正中，只有个别的还没有纠正。

　　要做好工作，应该情况明，决心大，办法对。要做到这样是很不容易的。

　　首先是情况明。这是毛泽东同志提出调查研究的时候特别强调的。目前我们对困难的情况是不是看得够了？我想要有分析。困难的发展趋势我们是看出来了。前年经济调整的时候，觉得很快就可以调整过来了，去年也还是这样想。今年七千人大会之后，在西楼开会〔298〕，陈云〔78〕同志讲了话，少奇同志作了结论，毛泽东同志也同意，就是说，调整时期要成为一个阶段，主要的内容就是恢复。不仅农业要恢复，工业也要恢复。因为不仅农业生产力被破坏了，工业也是这样，有些生产设备被破坏了，部分的生产秩序弄乱了，规章制度也不存在了，都要重新恢复起来。教育方面也有这个问题。现在看，这个调整时期要相当长。一般设想，第三个五年计划时期恐怕就是个调整阶段，甚至于还不够。把这个时期看得长一些，现在大家争论不大了，看法比较一致了。

　　是不是我们现在对困难的情况都弄清了呢？还不能这样说。趋势是看清了，调整的时期会长一些也看清了，但是具体情况常常是由极复杂的因素形成的，往往是现象发生了我们才看到。这类事情很多。例如三门峡的水利枢纽工程到底利多大，害多大，利害相比究竟如何，现在还不能作结论。原来泥沙多有问题，现在水清了也有问题。水清了，冲刷下游河床，乱改道，堤防都巩固不住了。上游清水灌溉，盐碱就不能统统洗刷掉。洪水出乱子，清水也出乱子。这个事情，本来我们的老祖宗有一套经验，但是我们对祖宗的经验也不注意了。三门峡水利枢纽工程既要防洪，又要灌溉，又要发电，又要运输，综合利用。修三门峡的方针是对的，但是办法不对，现在不能发电，泥沙又淤塞，还要大调整。类似这样的例子很多。所以，我们不能认为现在对困难的情况都估计够了。每个部门，每个地区，大家都要警惕这一点。

　　少奇同志说，把困难说多一点有什么坏处呢？领导上把困难指出来，然后找出办法来克服，只有好处，没有坏处。懵里懵懂，怕说困难，一听说困难就泄气，这不是马克思主义者。革命就是要认识困难，摆出困难，提出办法，克服困难。共产党就是在克服困难中取得胜利的。革命战争是这样，社会主义改造是这样，社会主义建设也应该是这样。不管哪一个问题，都是千头万绪。姚依林〔299〕同志讲了物价政策，他是经过一番研究的，但那只是一个设想。情况复杂得很，还会出现购买力超过商品供应量、财政赤字、货币难以回笼等情况。教育、政治方面，都会出现一些新的问题。我们宁可承认对困难估计得还不大够，多看一看，这不仅不会使我们在困难面前低头泄气，反而会使我们团结起来，依靠群众，克服困难。

　　这两年的调整中，我们觉得，我们总是对困难估计不够，总是希望好一点，好得快一点。我个人经手的事情几乎没有一件不是如此。你说我愿意慢一点呀？总还想快一点的。当年搞钢铁，别的让路，也是我在那里督战的，结果把大家搞垮了，现在回过头来，钢铁只好让路。这还不是自己的错误？当然，有外在的因素，但外在的因素不能成为借口，还是我们不冷静。钢的产量要求达到一千八百万吨，现在退到六百万吨。你总不能说那个一千八百万吨是对的。问题不在于后悔不后悔。不怨天，不尤人，主要是要得到经验教训。我们主观上想快一点，是好心肠，争取快，但是要准备慢。毛泽东同志说，对于社会主义建设，我们的经验还不够，还有许多未被认识的必然王国，从必然王国飞跃到自由王国，要有一个过程。

　　现在我们领导的意见接近一致了，但这还不行，还要把我们的意见传达到广大的干部中去，并且适当地向群众说清楚。当然，领导是起决定作用的，可是要把领导的意见变为群众的行动，说服群众和我们一道去做，那就需要做艰苦的工作，要经过群众的体验。现在省一级同志的意见大概跟我们比较接近了，地委就差一点，县、社、队，厂矿、各种事业单位就更差。这不能怪下面，还是七千人大会上说的，责任首先在中央，因为许多错误的东西是我们发起和创议的。当然，有的是他们做过了头，做走了样子，但这样做也是上面逼的。所以，上下认识的接近，需要一个过程，必须做艰苦的工作，不能希望很快。调整的具体工作要有步骤，要通气。党内的七千干部通了气，通过人大、政协，也跟党外人士初步通了气，但是还没有全部通气。要全部通气，也需要有个过程。

　　其次是决心大。现在我们决心大不大？我想，基本上是大的。当然，去年已经是下大决心了，一千多万人下乡，八百七十多万职工精简下来，这是一个大决心。但是去年我们还不能设想关这么多厂，拆这么多“庙”，精简这么多人。这件事情，在中国，没有哪个政权能够这样做，只有我们才有这样做的群众基础。去年没有出大乱子，今年会做得更好一些。原来不敢下那么大决心，觉得去年下了那么多人，今年再下那么多人，不大可能。我对这个问题，一方面主张多下人，可是如何下法，要走一步看一步。所以，最初决定下七百万城市人口，其中包括五百万职工。后来许多地方要求一步走，就提出一千三百万城市人口下乡，其中包括九百多万职工。现在经过政治局常委讨论，下了更大的决心，就是下乡职工超过一千万人，下乡城市人口相应地可能争取超过二千万人。这个决心，的确也是逐步酝酿出来的，去年不可能，前年更不可能。现在下这个决心，目的就是要把我们的经济生活来一个大幅度的调整，使它在新的基础上来一个大改组。这是领导的决心，也是全民族的决心，几乎要震动我们全民的生活，不是一件简单的事情。

　　再次是办法对。办法现在只能有那么多，更多的办法还要依靠群众创造。革命战争是如此，建设也是如此。大家来想办法，一定有出路。各地各部门的领导同志不要怕把话说多了，不要怕我们的干部知道。你把问题说清楚了，他们的办法会比我们还多。你不说清楚，他们不晓得你葫芦里卖的什么药，反而互相猜疑，议论纷纷。我们现在把决心传达到下面去，就可以找出办法来，经过一年到一年半的时间，就能在初步调整的基础上前进。时机紧迫，不应该犹豫了。可是另一方面，今天的情况又是千头万绪，动一根头发就要牵动全身，稍一不慎就会出乱子，我们应该有准备。一方面是力争不出乱子，另一方面也要有准备，万一出了乱子也没有什么可怕。我们只要把情况跟干部、群众讲清楚，大乱子可以克服，可是办事不能急躁，不能草率，必须谨慎从事。

　　在目前形势下，关键是如何处理好毛泽东同志在《论十大关系》中提出的农轻重关系、城乡关系、中央和地方的关系。现在的农业基础没有办法负担这样规模的工业。工业本身也不平衡，没有办法继续均衡生产，也没有办法支援农业，支援市场，兼顾国防，比例的失调极其严重。城乡比例也失调。现在我们农业生产的各种因素，劳力、畜力、地力、水利、肥料、种子、农具、运输工具等等，都有不同程度的削弱或减少。在这样的情况下，农业的恢复要有一个相当的时间。拿粮食来说，总要三五年，少的三年，多的五年，有一部分地区也许要超过五年。至于农业的全面恢复，包括经济作物，农、林、牧、副、渔，那要超过五年。所以，我们首先就应该抓住农轻重关系、城乡关系这个关键来调整。调整不是今年一年就可以就绪的。工业也存在这个情况，工业和基本建设三年调整，就必然影响以后的三年。因为基本建设三年踏步，重点又放在支援农业上，那么，工业的后备力量，扩大再生产的能力，比如煤炭、木材、有色金属、化工材料的增长都不会很大，这就必然影响第三个五年计划的后三年。我们在七千人大会上提出的指标，还是尽量压下来的，但是现在看来，那些指标还高了。一九六七年钢产量一千八百万吨，煤三亿五千万吨，看来都达不到。粮食产量一九六七年能不能达到三千七百亿斤，还要看两年。棉花产量一九六七年显然到不了三千七百万担。现在我们应该更冷静地看问题。我们对新的发展，总的规模，还没有完全摸清楚，要承认自己不行。

　　我们这样一个人口多、经济落后的国家要在经济上翻身，这是一个艰巨的任务。我们应该有临事而惧的精神。这不是后退，不是泄气，而是戒慎恐惧。建设时期丝毫骄傲自满不得，丝毫大意不得。

　　目前的中心工作，还是我在七千人大会上提出的四句话：精兵简政，增产节约，保证市场，整顿秩序。

　　要增产，首先农业要增产，这不是一件简单的事情。如果不把农业这个基础恢复起来，现在这个工业基础也站不住，城市就是减了二千万人口也站不住。这个经济形势，大家看得很清楚。

　　抓粮食要抓两头，一头是商品粮食基地，一头是灾区。还要认真抓棉花。棉花产量不能再减了，每年总要增产才好。每人每年供应三尺布的情况不能再继续了。棉花生产的恢复比粮食还要慢。除国家注意棉花集中产区以外，地方上还可以提倡在自留地上种点棉花。自留地种的棉花不要收购。返销农村的粮食，首先要照顾棉农。

　　在这样的农业基础上，工业必须有一个大幅度的调整。现在工业的秩序是乱的，有些产品的指标很高，很不平衡，这种情况是难以为继的。我们的方针是按照短线平衡，不留缺口，并且留有余地。这个方针不可能一步实现，但是必须坚持，要逐步实现。至于缺门，那是任何一个国家都有的，任何国家都有些缺门短线，都要互通有无，这是另外一个问题。当然，万一世界各国都封锁我们，那我们就要搞一部分代用品，有些就要停止生产。直到现在，合金钢材、橡胶我们还是缺门，靠进口。我们国内能够生产成套设备的，就不要只生产出主机，没有副机，不配套，积压起来。到去年年底，设备积压接近一百亿元，这是一个最大的浪费。

　　我们现在调整工业的政策是采取关厂、并厂、缩小规模、改变任务、转业这样五个办法。全国六万多个工业企业，可能关掉一半以上。这好象是消极的，实际上，这样就可以把原材料、电力、煤炭集中到消耗少、质量好、品种多、成本低、劳动生产率高的工厂去使用。从全国来看，一个时候产量会低一些，但最后会使工业品的数量多起来，质量好起来，有一部分还可以增加出口。当然，这要经过调整，要有一个过程。

　　我们调整的目的，就是为了精兵简政，增产节约，保证市场，整顿秩序。缩短工业生产和基本建设的战线，相应地缩短其他方面的战线，精兵简政，减少城市人口，减少职工，达到增加农业生产和工业生产的目的，这是一个积极的方针，是一个经过调整、改组，然后前进的方针。



　　＊这是在中共中央工作会议上讲话第一部分的节录。



