# 建成社会主义祖国，关键在于实现科学技术现代化

中文马克思主义文库 -> 周恩来
建成社会主义祖国，关键在于实现科学技术现代化
（一九六三年一月二十九日）

我对自然科学是外行。这次来到上海，碰到各位正在讨论制定十年科学规划，借这个机会我谈谈下面几个问题。

首先，我们要正确认识科学技术现代化在社会主义建设中的重大意义。

我国过去的科学基础很差。我们要实现农业现代化、工业现代化、国防现代化和科学技术现代化，把我们祖国建设成为一个社会主义强国，关键在于实现科学技术的现代化。

实现科学技术现代化的主要要求是：实事求是，循序前进，相互促进，迎头赶上。前两点是指要有科学的态度。毛主席在一九四二年整风〔14〕时就提出了实事求是，这同样适用于自然科学。我国是一个人口最多的社会主义国家，我们不仅要实事求是，循序前进，还要有雄心壮志，尽快赶上世界先进水平。我们的四个现代化，要同时并进，相互促进，不能等工业现代化以后再来进行农业现代化、国防现代化和科学技术现代化。我们落后于世界先进水平，但是我们有先进经验可以学习，有最新科学技术成果可以利用，这样可以扩大我们的眼界，所以我们前进的步伐可以加快。当然不会一点弯路不走，但总可以少走弯路。我们应该迎头赶上，也可以赶上。我们不应该跟在别人后面把所有的程序都走一遍，那样，我们将永远落在后面。只有把实事求是、循序前进和相互促进、迎头赶上统一起来，才能使我们科学技术的发展适应二十世纪六十年代的要求，比较快地赶上世界先进水平。

第二，我们要看到我们实现科学技术现代化的各方面的有利条件。

我们有辩证唯物主义思想作指导。我们不是以主观唯心主义作指导，也不是以机械唯物主义作指导，而是以辩证唯物主义思想作指导。辩证唯物主义思想能够帮助我们更好地认识客观规律，更好地发挥主观能动性。

我们有广大的人力和丰富的资源做基础。我国是多民族的国家，人口众多，物产丰富，天然给我们带来的任务是：对祖国、对人类应该做出较大的贡献。历史上，我们的祖先有过许多发明，为什么到现代就不能有所发明呢？后来居上，我们是应该超过自己的祖先的。

我们有优越的社会主义制度做保证。在旧社会，某些科学家赤手空拳，单枪匹马，也还能做出一些贡献；在新社会，社会制度有了根本变化，生产力解放了，人们思想解放了，单枪匹马变为群策群力，科学家有充分发挥自己才能的广大的自由天地。当然这要有一个过程。另外，把集体需要与个人自由辩证地结合起来，也需要有一个实践和认识的过程。我们在座的一些同志，经过清末、北洋军阀政府〔6〕、蒋介石反动统治和社会主义四个时期，比较一下四个时期的情况，就可以清楚地看出我们社会主义制度的优越。

我们已经有了一支比旧中国大许多倍的知识分子队伍和科学技术力量。从清末派出留学生到中华人民共和国成立时为止，全国一共只有二十多万大学生。新中国建立后到去年为止，我们有了九十六万大学毕业生，几百万中级知识分子。再过十年，我们又会有一百多万大学毕业生。这是旧时代所不能比拟的。我们现在已经有了一支不小的技术力量和一批科学研究机构，这是国家的宝贝。

我们现在有了工业化的初步基础。一般设备和原材料绝大部分自己能够制造或生产。这就为我们科学技术的发展创造了条件。只要我们在党的领导下，把这些条件运用好，群策群力，自力更生，就一定能够后来居上，做出超过前人的贡献。

第三，如何多快好省地实现科学技术现代化的要求，我讲几点具体意见：

一、加强科技界人士的主人翁责任感。就是要做到接受党的领导，为社会主义服务，自愿地坚持自我改造。我们应该做到老、学到老。只有认识到自己需要不断地学习和改造，才会愉快。不自满，有了缺点就改，就会进步；如果自满了，那就要退步。人总是要不断地前进。大家要互相勉励，共同进步。

二、集中和加强科学技术力量。科学研究部门、教育部门和工厂要密切结合，有分工有合作，而不是把力量全部集中在科学研究部门，也不是全部集中在教育部门或工厂。如上海要集中力量突破半导体技术，别的地方如有这方面的力量就可以调来。

三、改进各方面的关系。首先是党群关系、领导与被领导的关系。我这里讲的领导是指集体而言，不是讲党员个人。当然，党员个人的讲话有些时候是根据党的指示，传达党的意见。但是，人总是有个性的，某个人在某一方面兴趣大一些，因此在传达党的意见时，在某一方面多讲一些，发挥一些，这是有可能的。领导者讲话也有不是指示性的，如果一讲话就是指示，那么这日子如何过？所以我总是不大赞成讲“指示”。传达党的意见是一方面。更重要的是党群之间的融洽相处。还有青老关系、师徒关系。应该把老放在前面，是老青关系，不过这样讲不顺口。带路的是老的，但青年人有活力，能够推动事业进步。还要正确处理理论和实践、任务和学科的关系，认真实现领导、专家和群众的三结合，以及科学研究机关、学校和生产部门的紧密协作。安排好这些关系是科委的责任。加强思想工作，组织科技力量，调整各方面的关系，是科委要做的事。

四、适当改善科学技术研究的工作条件和工作环境。国家科委和政府有关部门应该给大家便利。研究和教学要有实验室，生产要有车间。上海有些设备不够，必不可少的要补充，需要进口就进口一些吧，总要相当满足你们的要求。关于原材料，可以相互支援，图书也可以相互支援。订购外国书刊，开始时掌握得松了一些，因此重复的很多，但后来又太紧了。必要的图书资料还是要订。必要的交换刊物要给人家，否则人家也不给你。关于助手、技术工人的问题，上海是能解决的，需要从别处调的，个别的可以支持。总之，条件有利，就能创造出新的成绩来。

关于工作环境问题，真正的科学家在生活方面的要求并不高，但生活问题、居住问题也不能完全不考虑，如有的科学家住得太远，就要给予便利。有些科研项目需要协作完成，所以集体活动是必要的，但不要因此而排除个人钻研。科学家专业外的事情应该少一些，这是科委要安排的，每个单位也要注意。我们过去习惯于搞突击工作，对于经常的工作不是安排得很好，大家可以提意见。

我相信你们一定能够订出很好的十年科学规划。

我们的任务是艰巨的，心情是愉快的；责任是重大的，精神是饱满的。上海，作为我国最大的工业城市和科学技术的重要基地，我们对上海科学技术界寄予深切的期望。希望上海的科学技术界在实现四个现代化中做出应有的成绩。

＊这是在上海市科学技术工作会议上的讲话。

