# 过好“五关”

中文马克思主义文库 -> 周恩来
过好“五关”
（一九六三年五月二十九日）


　　我现在讲一讲领导干部过“五关”的问题。过“五关”，就是过思想关、政治关、社会关、亲属关和生活关。
　　第一，过思想关。过思想关就是我们常说的思想改造，是解决世界观和人生观的问题，也就是要树立马克思列宁主义或者说辩证唯物主义和历史唯物主义的世界观和人生观，学会运用毛泽东同志的《实践论》、《矛盾论》和最近讲的认识论〔302〕。这是一辈子的事。我们知道，时代是不断前进的，思想改造就是要求我们的思想不落伍，跟得上时代，时时前进。事物的发展是没有止境的，因此我们的思想改造也就没有止境。一万年后，在人们的头脑里，还会有先进和落后的矛盾，新和旧的矛盾，个人和集体的矛盾，还会有思想改造的问题。所以我们现在怎么能说到哪一年哪一月思想改造就完成了？没有这样的事。即使参加革命多年的同志，如果忽视了改造，革命意志衰退了，还是要落伍的。所以，我们要把思想改造看成是长期的无止境的工作。这样认识问题，大家的心胸就开阔了。既然一万年后还有思想上的矛盾，还要改造，为什么现在就觉得自己的思想改造已经完成了，就满足了呢？我们永远不能满足。
　　过思想关要联系到自身的阶级关系，还要看我们现在工作周围环境的阶级关系怎么样，接触事物中的阶级关系怎么样。比如说，你的家庭出身和本人成份很好，历史上也是革命的，可是现在把你派到香港去工作，你就要想一想周围环境的问题了。不到香港，就在北京做外交工作，跟外国人打交道，或者做外贸工作，跟外国商人打交道，那么你对接触的人和事就要研究研究了。我们跟资本主义国家做的买卖很多，现在又要引进成套设备，有的同志总是跟外国商人打交道。接触的是这些人，你就要研究呀。我也常常接触这些人，我也得想一想呀。总之，阶级关系是要注意的。还是以我为例吧。我出身于一个封建家庭，我个人受过资产阶级教育，不过经过改造现在是个革命知识分子了。历史上我做过统一战线工作，跟蒋介石打过多次交道，跟美国的马歇尔〔303〕也打过交道，在台湾有那么多的国民党同学和朋友，在美国也有很多朋友，我的关系可复杂了。从周围的环境看，我接触党内外的人和事很多，也接触外国人，有时候要出国访问，还到资本主义国家，跟那些国家的领导人打交道。这么一个复杂的情况，我就得注意自己的思想。我今年六十五岁了，是不是已经修养得很好不必改造了？我不敢这样说。廖鲁言〔304〕同志用了我的话，他说，周总理都要思想改造，何况我们？他的这句话是句好话，我很欣赏。我的确常说我也要改造这句话，现在还在改造中。我愿意带头。我希望大家承认思想改造的重要性。要承认各种关系各种事物都会影响个人的思想。要经常反省，与同志们交换意见，经常“洗澡”。要把思想改造看成象空气一样，非有不可。不然，你的思想就会生锈，就会受到腐蚀。每个党员从加入共产党起，就应该有这么一个认识：准备改造思想，一直改造到老。还没有加入党的朋友，凡是参加革命，参加社会主义建设和社会主义改造的，也应该这样。
　　第二，过政治关。最重要的是立场问题。不要以为我们是干革命的，立场就一定是稳的。立场是抽象的，要在具体斗争中才能看出你的立场站得稳不稳。可能在这个斗争中站得稳，在那个斗争中又站不稳了。所以，立场究竟稳不稳，一定要在长期斗争中才能考验出来。同时还要看我们的工作态度、政策水平、群众关系，看我们的党性，没有入党的看是不是把无产阶级作为先进的阶级，接受它的思想领导。特别是看我们的批评和自我批评精神，是不是知过能改。可见，过政治关不是简单的事，不能认为只要参加了革命，打了多少年的仗，过去有过功绩，立场就可以保险了。没有这样的事。为什么陈独秀〔40〕、王明〔194〕的立场不保险，高岗〔305〕的立场也不保险？在陈独秀身上，马克思列宁主义的东西就极少，更没有成为他的指导思想。王明直到现在对自己的错误还不认帐。所以，我们要认真对待立场问题，过好政治关。
　　第三，过社会关。一般总是讲思想、政治两关，我特别提出后三关，是因为中国这个社会极其复杂，我们还有改造社会的任务。在这个社会里，旧的封建的资本主义的习惯势力，很容易影响你，沾染你，侵蚀你，如果失去警惕，这些东西就会乘虚而入。所以改造社会的任务是很艰巨的，处在领导地位的同志担子更重。旧社会的习惯势力不是一下子就会消除的，改造是长期的，哪能一次改造就成功呢？旧社会的习惯势力存在于各个角落里，各种机关团体都有。一个北京城，你只要去看一看，到处可以看到旧的习气。要把北京这个社会改造好，需要几十年或者更长的时间。我看，在座的六十岁以上的人恐怕不容易看到了。所以，过社会关也不是那么简单的事，你能把社会改造好，自己也就得到改造了。不然，是你影响它，还是它影响你？《霓虹灯下的哨兵》中说，是资产阶级改造我们，还是我们改造资产阶级？这段剧词说得好。你改造了它，它又影响了你，互相改造，这是个长期的反复的斗争。而且，你在这个地方过好了社会关，换一个环境，那个地方的旧势力、旧习惯又影响你。你在国内过好了社会关，到了香港或是到外国去又变化了。所以过社会关要有精神准备，要有长期奋斗的决心。
　　第四，过亲属关。不只是直系亲属，还有本家，还有亲戚。对亲属，到底是你影响他还是他影响你？一个领导干部首先要回答和解决这个问题。如果解决得不好，你不能影响他，他倒可能影响你。我看，解决亲属问题的最好办法主要是依靠社会，由社会去锻炼他，改造他。要相信社会的力量。过亲属关说起来容易，做起来就不那么容易了。天天跟你生活在一起的总有这么几口子。特别是干部子弟，到底是你影响他，还是他影响你？这个问题十分重要。我呼吁我们的领导干部，首先是我也在内的这四百零七个人〔306〕应该做出一点表率来。不要造出一批少爷。老爷固然要反对，少爷也要反对，不然我们对后代不好交代。我们是社会主义社会，不象封建社会和资本主义社会那样，但是历史也可以借鉴。秦始皇能够统一中国，可是他溺爱秦二世，结果秦王朝就亡在秦二世。我们决不能使自己的子弟成为国家和社会的包袱，阻碍我们的事业前进。对于干部子弟，要求高、责备严是应该的，这样有好处，可以督促他们进步。
　　第五，过生活关。生活关分两种：物质生活和精神生活。物质生活方面，我们领导干部应该知足常乐，要觉得自己的物质待遇够了，甚至于过了，觉得少一点好，人家分给我们的多了就应该居之不安。要使艰苦朴素成为我们的美德。这样，我们就会心情舒畅，才能在个人身上节约，给集体增加福利，为国家增加积累，才能把我们的国家更快地建设成为一个社会主义强国。精神生活方面，我们应该把整个身心放在共产主义事业上，以人民的疾苦为忧，以世界的前途为念。这样，我们的政治责任感就会加强，精神境界就会高尚。当然，我们不是说一天到晚只搞政治斗争，只干工作。人的生活要丰富一点，精神更要舒畅一点。文艺生活总是要有的，但是，我们的文艺生活是为了活跃人的思想，提高人的修养，把教育寓于文化娱乐之中。我们的文艺节目要有教育意义。那种庸俗低级的、野蛮恐怖的、堕落腐化的东西，是资产阶级和封建阶级的产物，我们应该坚决批判，坚决反对，不能用官僚主义态度对待它，容忍它。这些东西不仅对我们不利，对青年一代的成长更为不利。还应该看到，资本主义国家的某些文艺思潮和文艺作品是颓废的没落的，决不能让那些糟粕影响我们的干部，影响我们的青年一代。我们要在这方面加以整顿。上一次我在文联谈过这个问题，要整顿我们的文艺队伍，加强我们文艺界的思想改造。
　　总之，对个人来说，这“五关”不是一次就能过了的，而是长期的。我们的领导干部要认真对待，严格要求自己，一步一步地过好“五关”。


　　＊这是在中共中央和国务院直属机关负责干部会议上的报告的一部分。关于过“五关”问题，周恩来同志还对知识分子、民主人士和亲属多次讲过。



