# 在治理黄河会议上的讲话

中文马克思主义文库 -> 周恩来
在治理黄河会议上的讲话
（一九六四年十二月十八日）

这次会议是国务院召开的，我本来想用半个月到一个月的时间去现场看看，由于临时有国际活动，回国后又忙于准备三届人大，离不开北京。

对三门峡水利枢纽工程改建问题，要下决心，要开始动工，不然泥沙问题更不好解决。当然，有了改建工程也不能解决全部问题，改建也是临时性的，但改建后情况总会好些。

治理黄河规划和三门峡枢纽工程，做得是全对还是全不对，是对的多还是对的少，这个问题有争论，还得经过一段时间的试验、观察才能看清楚，不宜过早下结论。只要有利于社会主义建设，能使黄河水土为民兴利除弊，各种不同的意见都是允许发表的。旧中国不能治理好黄河，我们总要逐步摸索规律，认识规律，掌握规律，不断地解决矛盾，总有一天可以把黄河治理好。我们要有这样的雄心壮志。

黄河治理从一九五○年开始到现在将近十五年了。但是我们的认识还有限，经验也不足，因此，不能说对黄河的规律已经都认识和掌握了。我们承认现在的经验比十五年前是多了，比修建三门峡枢纽工程时也多了，但将来还会有更多的未知数要我们去解答。不管持哪种意见的同志，都不要自满，要谦虚一些，多想想，多研究资料，多到现场去看看，不要急于下结论。

改建规模不要太大，因为现在还没有考虑成熟。总的战略是要把黄河治理好，把水土结合起来解决，使水土资源在黄河上中下游都发挥作用，让黄河成为一条有利于生产的河。这个总设想和方针是不会错的，但是水土如何结合起来用，这不仅是战术性的问题，而且是带有战略性的问题。比如说，泥沙究竟是留在上中游，还是留在下游，或是上中下游都留些？全河究竟如何分担，如何部署？现在大家所说的大多是发挥自己所着重的部分，不能综合全局来看问题。任何经济建设总会有些未被认识的规律和未被认识的领域，这就是恩格斯说的，有很多未被认识的必然王国。我们必须不断地去认识，认识了一个，解决一个，还有新的未被认识。自然界中未被认识的事物多过人们已经认识了的。即使有那么多有关黄河的历史资料，当时也许看着比较好，现在再看就不够了，因为情况变了，沧海桑田，要变嘛！即使古书都查了，水文资料积累更多了，也还不能说我们对治理黄河的经验已经够了。这样说是不是永远无法做结论呢？那也不是。一个时期有一个时期内掌握得比较全面、比较成熟的东西，能够做结论的先做，其他未被认识的或未掌握好的，经验不成熟的，可以等一等，可以推迟一些时间解决。推迟是为了更慎重，更多地吸收各方面的意见，有利于今后的规划工作。

治理黄河规划即使过去觉得很好，现在看到不够了，也要修改。农村工作六十条〔290〕要修改，农业发展纲要四十条〔105〕也要改。象这些摸熟的东西还要不断地改，何况黄河自然情况这样复杂，哪能说治理黄河规划就那么好，三门峡水利枢纽工程一点问题都没有，这不可能！因此，希望所有行政领导同志、专家要和群众相结合，做出符合实际的结论。允许大家继续收集资料，到下面去观察、蹲点、研究。大家可以分工从各方面用力。观察问题总要和全局联系起来，要有全局观点。谦虚一些，谨慎一些，不要自己看到一点就要别人一定同意。个人的看法总有不完全的地方，别人就有理由也有必要批评补充。要破也要立。不要急躁，慢一点做结论。这是不是调和的意见呢？当然不是。而是集中对的，去掉不对的，坚持真理，修正错误。这样，才能不断前进。

基于这个原因，我们对治理黄河规划和三门峡水利枢纽工程既没有全面肯定，也没有全面否定。至于设想，可以大胆些。我曾经说过，可以设想万一没有办法，只好把三门峡大坝炸掉，因为水库淤满泥沙后遇上大水就要淹没关中平原，使工业区受到危害。我这样说，是为了让大家敢于大胆地设想，并不是主张炸坝。因为我不这样说，别人不敢大胆地想。花了这么多投资又要炸掉，这不是胡闹吗！我的意思是连炸坝都可以想一想。不过不要因为我说了，就不反对，就认为可以炸了。毫无此意。我也是冒叫一声，让人家想一想。如果想出理由来，驳倒它，就把它取消，不必顾虑。专门性的问题，就是要大家互相发现矛盾，解决矛盾，有的放矢，这样，才能找出规律，发现真理。

三门峡水利枢纽工程，原来苏联专家是按正常高水位三百六十米设计的。我们把大坝高程和运用水位都压低了，施工时大坝高程改按三百五十米，初期蓄水位不超过三百三十五米。三百三十五米以下库容原为九十六亿立米，现在已经淤了五十亿吨泥沙，只经过五年，已经淤了一半。仅一九六一年和一九六四年两年就淤积了三十多亿吨。如果再经过一个五年，又遇上两场大水，加上平常年度的淤积，三百三十五米以下库容即将淤满。到那时，回水不影响渭河、洛河是不可能的。过去我们曾设想三门峡水库堆沙年限至少维持二十多年到三十年，在这个时期内，大搞水土保持等各种措施。但是，五年已淤成这个样子，如不改建，再过五年，水库淤满后遇上洪水，毫无问题对关中平原会有很大影响。关中平原不仅是农业基地，而且是工业基地。不能只顾下游不看中游；更不能说为了救下游，宁肯淹关中。这不是辩证的说法。做不好，上下游都受害怎么办？为什么不从另一方面想想？如果三门峡水库淤满了，来了洪水，淹了上游，洪水还要下来，遇上伊、洛、沁河洪水，能不能保证下游不决口？即使不决口也有危险。我们看问题要有全局观点，要进行比较。

有的同志主张维持原状。但是，五年之内能不能把上中游水土保住？绝不可能！要求在五年内把西北高原上的水土保住，我看砍了头也没办法。要叫我去，也不能接受这个任务，因为这是不可能办到的。因此，三门峡工程总要改建。

当前的关键问题在泥沙。眼前五年十年内这一关怎么过？即使二洞四管的方案〔307〕批准后就施工，也要到一九六八年或一九六九年才能生效，而且四管只能泄一千秒立米，排沙有限。如果在这期间遇上象一九六一年和一九六四年的情况，库区再淤上三十亿吨，怎么办？这是燃眉之急，不能等。

本来三门峡工程改建的事，请计委批准就可以了，可是有些意见出入比较大，不征求大家的意见还不安心，因此挤出时间来参加这次会。听了大家的意见以后，情况清楚了。现在，大家都认为增加二洞四管还是需要的，对三门峡工程改建问题的争论少了。个别同志反对这个方案，主张上游修三个拦泥库，只拦泥，不综合利用。我看光靠上游建拦泥库来不及，而且拦泥库工程还要勘测试点，所以这个意见不能解决问题。即使说过去水土保持做得不好，上游勘察工作做得不好，黄河水利委员会、水利电力部工作上都有错误，但是眼前的这个病怎么治？要回答五年内怎么办这个问题。反对改建的同志为什么只看到下游河道发生冲刷的好现象，而不看中游发生了坏现象呢？如果影响西安工业基地，损失就绝不是几千万元的事。对西安和库区同志的担心又怎样回答呢？实施水土保持和拦泥库的方案还遥远得很，五年之内国家哪有那么多投资来搞水土保持和拦泥库，哪能完成那么多的工程。那样，上游动不了，下游又不动，还有什么出路！希望多从全局想一想。我也承认三门峡二洞四管的改建工程不能根本解决问题，而是在想不出好办法的情况下的救急办法。改建有利于解决问题，不动就没法解决问题。改建投资可能多一些，但即使需要八九千万元，也不能不花，哪能看着问题不去解决！看问题要有全局观点，要看到变动的情况。三门峡工程二洞四管的改建方案可以批准，时机不能再等，必须下决心。

今天，我只能解决第一步增建问题，其他问题我还要负责继续解决，不是光注意了中游，不注意上游，更不是不注意下游。绝无此意。现在成熟的方案只有这一个，其他的事情还要继续做。

再补充一点，一切问题都要到现场去实践，通过实践，不断总结，取得经验，然后再实践再总结。到现在我还担心二洞四管会不会有什么问题。不要把事情想得太满，还可能会遇到困难，还可能发生预料不到的新问题。设计方面要多研究，施工时要和工人多商量，要兢兢业业地做。如果发现问题，一定要提出来，随时给北京打电话，哪一点不行，赶快研究。不要因为中央决定了，国家计委批准了，就不管了。因为决定也常会出偏差，会有毛病，技术上发生问题的可能性更多。我再重复一句，决定二洞四管不是一件轻松的事，既然决定了，就要担负起责任。大家要时常多想想。因为，黄河的许多规律还没有被完全认识。这一点要承认。我还要再三说一下，不要知道一点就以为自己对其他都了解了。当时决定三门峡工程就急了点。头脑热的时候，总容易看到一面，忽略或不太重视另一面，不能辩证地看问题。原因就是认识不够。认识不够，自然就重视不够，放的位置不恰当，关系摆不好。一九五九年水电部修建了三百多座大型水库，这几年下马了一些，现在还有将近二百座，很大一部分工程没有完成，遗留问题很大。修水库不是一件容易的事，这几年的教训是应该深刻吸取的。

