# 农村卫生工作和计划生育问题

中文马克思主义文库 -> 周恩来
农村卫生工作和计划生育问题
（一九六五年十一月一日）


　　这是林大夫〔309〕和傅连暲〔310〕会长给我出的难题。你们讨论妇产科专门问题，我完全是外行。我讲什么呢？我讲讲卫生工作面向农村和计划生育的问题吧。
　　我国农村人口约占总人口的百分之八十七八，城市人口只不过占百分之十二三。如果我们的卫生工作不把重点放到农村，那怎么为劳动人民服务啊？为绝大多数劳动人民服务的口号等于没有兑现嘛。这个问题直到毛主席再三提出来，才引起卫生部门的注意。当然我们政府要负责，我做国务院总理的首先要负责。虽然有时也说过，但提得不那么着重，不那么尖锐。毛主席这么一提，卫生部门就具体订计划了，现在已经有了初步规划。
　　在五年之内真正把农村中三种卫生人员培养起来，这是一个艰巨而伟大的任务。一种是不脱离生产的卫生员，每个生产队有一名，全国有五百多万生产队，就要训练五百多万卫生员，五年能不能做到，现在还说不定，也许需要十年。要培养这样多不脱离生产的卫生员，使他们成为多面手，既能治一般的病，又能治妇科病，还会接生。这是一项艰巨的工作，你们在座的都有责任，不要把它看得容易了。卫生员不脱离生产，又有一定的本领，生产队非常欢迎。当然不能保证培养这样多的人都是百分之百地合格，不合格就再培养，再进修嘛。第二种是在生产大队和一部分公社能够有半脱产的卫生员，治病时给他记工分，不治病时也去参加体力劳动，这些人由公社或大队管。对他们的本事要求高一点，不仅能治一般的头痛、伤风，还能治一些比较难治的病。全国有八十多万个生产大队，一个大队培养一个人就是八十多万个，有的大队还可能不只一个人。第三种是为公社或区里培养脱离生产的专职医生。全国有七万多个公社，每个公社培养三至五人，总共就要培养大约三十万人。这些人基本上脱离生产，在一年里有些时间能参加一些体力劳动也好。应该说明医务人员的工作也是脑力劳动和体力劳动结合的。林大夫过去忙的时候，一星期要做好几次手术。年轻的大夫每天在手术室做手术一站几个小时，手术前还要做准备，这是脑力劳动，也是体力劳动，是脑力和体力结合的劳动。护士也是一样。除去医生和护士外，还有医院的其他技术人员也都是半脑力劳动半体力劳动。
　　怎样才能帮助农村培养出这三种人，这是个大问题。现在整个卫生队伍除行政人员外，还不到一百万人，要训练这三级卫生人员六百万到七百万人，我看五年不可能实现，也许十年才能实现，可能还要扫尾。计划可以打得宽一些，工作要抓紧，如果不到十年完成当然更好。在座的女同志应该负更多的责任，因为培养上述三种人中人数最多的不脱产的卫生员一级，可能大多数是女同志，六七百万各级卫生人员半数以上是女同志，任务很艰巨。你们如何去培养呢？如何入手呢？一定要组织大中城市、工矿企业、机关、学校以及军队的医务人员，分期分批组成医疗队，到农村去，主要做两件事，一是治病，一是培养医务人员。只要真正为农民治病，为他们培训医务人员，农民就欢迎得不得了。对一部分年老体弱的大夫不能勉强他们去，年纪太大了，走路都要人扶，还不如留在城里。象蒲老，蒲辅周〔311〕先生，是很有名的医生，如果到农村去，受了风寒，反而把他的服务期限缩短了。这样的医生就要留下，他们可以教学生，也可以写点东西，把丰富的经验留下来，对人类对人民都有贡献。城市也不能不管。城市人口占全国总人口的百分之十二三，有一亿多人，将来也许更多，要做好他们的医疗保健工作。要改革医疗制度，还要培养人，这也是很重要的任务。
　　另外，我讲讲计划生育问题。对计划生育要进行宣传教育。一方面要有一些规定，如在工资、住房、供应等方面，对实行计划生育的，要给予优待，一方面要自觉自愿，绝对不能强迫命令。又要自觉自愿又要有所约束。要用各种办法帮助人们避孕。怎样使我国人口能有计划地生育，这是一个伟大的事业。现在全国有七亿人，如果不实行计划生育，人口增长得太快，生产就跟不上，这是一个大问题。要使全社会都能够按照计划生育的要求，在二十世纪以内把人口年纯增率控制在百分之一，这就很了不起。总之，计划生育是一件长期的事情。上述这个要求并不高，如果能够提前做到当然很好了。


　　＊这是接见中华医学会第一届全国妇产科学术会议代表时的讲话。



