# 植树造林是百年大计

中文马克思主义文库 -> 周恩来
植树造林是百年大计
（一九六六年二月二十三日）

林业工作要面向全国，依靠全党全民，要两条腿走路。林业部过去只注意林区采伐，我看主要任务还是造林〔312〕。工业犯了错误，一二年就可能转过来，林业和水利上犯了错误，多少年也翻不过身来。我最担心的，一个是治水治错了，一个是林子砍多了。治水治错了，树砍多了，下一代人也要说你。我国森森覆盖率只有百分之十多一点。十六年来，全国砍多于造，是亏了。二十世纪还剩下三十几年，再亏下去不得了。造林是百年大计，要好好搞。

造林也要两条腿走路，要依靠六亿农民。四旁〔313〕植树也是个大工作。兵团要搞试点。用剃光头的办法采伐森林，采光了就走，修一条林区铁路废一条，这怎么得了！营林是建设社会主义，我们不能吃光了就算，当败家子〔314〕。过去林业部长梁老〔315〕经常讲这个问题。现在抓紧造林还不晚。

林业部要把主要力量放在南北方造林上。要调查公社的造林办法，总结推广经验。

国营与群众营林，重点放在群众；伐木与育林，重点放在育林；前方与后方〔316〕，重点放在前方。重点放对了，才能用得少，造得多。总得在第三个五年计划时期摸出一套林业工作的经验来。

北方八省〔317〕地区大，人口多，树林少，造林工作搞起来能很快发展。南方各省条件好，更要做好。南方本来有林，现在一些地方也有水土流失的现象。南方造林、护林、用林都很重要。

林业部到处提倡植树，可是在眼睛鼻子底下，就是到北京机场这一段路好，北京到天津的路上最难看了。十多年了，要你们在铁路两旁植树，就是不种，可难看了！有人讲公路上好一些，可是我从火车上看公路，也是一样。树本来是容易种的，与公社结合，委托给他们，分段负责，就能种好管好。

西北地区造林要集中在黄河泥沙主要来源地区，不要孤零零地分散搞。分散了，投资很大，功效很小，起不了多大作用。

西北黄土高原搞了多少年造林啦？劳大功小，要很好总结经验。陕北防沙林带有人烟，地下水浅，就可以造林。靖边、定边高原上水位低，不容易成林。要有选择、有阵地地前进。面对黄河流域二十八万平方公里水土流失区，只要有雄心壮志，有愚公移山的精神，就能战胜它。黄土高原是我们祖宗的摇篮地，是民族文化的发源地，但是这个地方的森林被破坏了。我们不仅要恢复森林面貌，而且要发展得更好。

西北局要搞一个领导小组，管农垦、水土保持。农林互相支援有好处。植树造林是百年大计，总得坚持到二十一世纪。华北大有可为，西北更是大有可为。

＊这是同出席全国林业工作会议的西北各省、自治区林业厅（局）长和西北林业建设兵团、林业部负责同志的谈话。

