# 关于保护干部的若干文电*

中文马克思主义文库 -> 周恩来
关于保护干部的若干文电*
（一九六六年——一九七四年）


一份应予保护的干部名单*
（一九六六年八月三十日）
　　宋庆龄　郭沫若　章士钊　程潜　何香凝　傅作义　张治中　邵力子　蒋光鼐　蔡廷锴　沙千里　张奚若〔318〕
　　（1）副委员长、人大常委、副主席
　　（2）部长、副部长
　　（3）政副
　　（4）国副
　　（5）各民主党派负责人
　　（6）两高〔319〕（李宗仁〔320〕）



　　*一九六六年八月二十九日夜，某校红卫兵抄查章士钊先生的住宅。三十日晨，章写信给毛泽东主席。毛泽东同志指示：“送总理酌处，应当予以保护。”周恩来同志严厉批评了有关人员，责令当即送回抄走的全部书籍，并派人前往保护章宅。同时写下了这份名单。九月一日，又命三○一医院准备接收章士钊、程潜、傅作义、蔡廷锴、李宗仁等先生入院，对他们加以保护。



应当尊重宋庆龄*
（一九六六年九月一日）
　　宋庆龄是孙中山的夫人。孙中山的功绩，毛主席在北京解放后写的一篇重要文章《论人民民主专政》中就肯定了的。他的功绩也记在人民英雄纪念碑上。南京的同学一定要毁掉孙中山的铜像，我们决不赞成。每年“五一”、“十一”在天安门对面放孙中山的像是毛主席决定的。孙中山是资产阶级革命家，他有功绩，也有缺点。他的夫人自从与我们合作以后，从来没有向蒋介石低过头。大革命失败后她到了外国，营救过我党地下工作的同志，抗日战争时期与我们合作，解放战争时期也同情我们，她和共产党的长期合作是始终如一的。我们应当尊重她。她年纪很大了，今年还要纪念孙中山诞辰一百周年，她出面写文章，在国际上影响很大。到她家里贴大字报不合适。她兄弟三人姐妹三人〔321〕就出了她一个革命的，不能因为她妹妹是蒋介石的妻子就要打倒她。她的房子是国家拨给她住的。有人说：“我敢说敢闯，就要去。”这是不对的，我们无论如何要劝阻。



　　*这是对首都红卫兵的讲话节录。



不应改变被批斗干部的工资*
（一九六六年九月十八日）
　　吉林省委九月十六日电悉。对被批判斗争对象的工资处理意见：即使已定性的，也暂不改变；如本人少领工资，或捐献一部分工资作党费，听其自愿，但不强求，也不许其由减少用费而致病。凡未定性的，工资仍照旧。



　　*这是为中共中央起草的复中共吉林省委并告各中央局的电报节录。



一定要放出李葆华〔322〕、李任之〔323〕*
（一九六六年十一月十四日）
　　请陶铸〔324〕同志以电话找安徽省委一谈。如情况属实，请找八·二七造反团负责人以电话交涉，无论如何要放出李葆华、李任之两同志，让他们回家休息。



　　*这是在中共中央华东局关于中共安徽省委两位书记被连续批斗的情况反映上的批示。



关于刘澜涛出狱问题〔325〕给西北局的电报*
（一九六六年十一月二十四日）
　　二十三日电悉。请向南开大学卫东红卫兵和西安炮打司令部战斗队同学说明，他们揭发的刘澜涛同志出狱的问题，中央是知道的。如果他们有新的材料，可派代表送来中央查处，不要在大会上公布和追查。



　　*“文化大革命”初期，康生等人制造了“六十一人”案件，诬陷一大批老干部。为保护这批干部，周恩来同志写信给毛泽东同志，明确提出，刘澜涛同志等出狱“当时确为少奇同志代表中央所决定，七大、八大又均已审查过，故中央必须承认知道此事”，并为中共中央起草了给西北局的这份电报。



九大〔326〕代表应包括王恩茂〔327〕*
（一九六九年一月十二日）
　　新疆自治区出席九大的代表应包括王恩茂同志在内。你们已为此做了不少工作，并为他留出名额。现在你们正面临新的困难。如说服党员干部和党内外革命群众需要时间才能选出，可先将王恩茂同志全家送来北京，以便继续工作。
　　你们意见如何，望告！



　　*这是为中共中央起草的给新疆自治区革命委员会的电报。



建议徐海东〔328〕参加九大主席团*
（一九六九年三月三十一日）
　　今晚与主席团预选成员和军队主要负责同志协商徐海东同志为九大代表。如取得大家同意，拟同时提议徐也参加主席团，然后由各组召集人回到各组征求全体代表同意。徐海东同志既已当代表，就以参加主席团为好，我和军委办事组各同志商量都同意。请示主席批准。



　　*这是写给毛泽东同志的信。



陶铸〔324〕应送入医院治疗*
（一九六九年四月五日）
　　拟同意送入三○二医院，进行保密治疗。即呈主席批阅。我是看了四月三日警卫局的报告才知陶的病状较重，经追问后，送来这一报告。



　　*这是在《关于陶铸的病情报告》上的批示，经毛泽东同志圈阅过。



不要斗批民主党派的领导人*
（一九六九年五月四日）
　　派往各民主党派机关的军代表不知已否派去？如已派去，可与他们谈谈政策。
　　机关革命造反派的任务是清理机关干部的队伍，而不要去斗批民主党派的领导人，即他们的中央委员、省市党部委员。如他们中间出现了现行的反革命分子，自当别论，但也需先报告军管代表，得中央或省、市革委会同意后，方能采取行动。
　　机关干部也要在清理队伍时，按具体情况区别对待，不能以中共党内标准要求。
　　附上邓初民〔329〕先生一信，请加注意。



　　*这是给当时国务院直属口党的核心小组负责人转人大、政协军代表的信。



应给华罗庚〔330〕]以保护*
（一九七○年三月四日）
　　首先，应给华罗庚以保护，防止坏人害他。
　　次之，应追查他的手稿被盗线索，力求破案。
　　再次，科学院数学所封存他的文物，请西尧〔331〕查清，有无被盗痕迹，并考虑在有保证的情况下，发还他。
　　第四，华的生活已不适合再随科大去“五七”干校〔332〕或迁外地，最好以人大常委身份留他住京，试验他所主张的数学统筹方法。
　　此事请你们三位办好后告我。



　　*这是就华罗庚同志要求追查被盗手稿的来信，给当时国务院直属口党的核心小组负责人、北京市公安局军管会负责人和周恩来同志派到科学院的联络员的批示。



关于张霖之〔333〕死亡问题*
（一九七○年七月三十一日）
　　国务院业务组于一九七○年七月三十一日会议，审查了煤炭部军代表一九七○年五月二十日和七月三十一日两次报告，以及首都驻北京矿业学院工、军宣队〔334〕专案组一九七○年五月十七日的报告，同时，并阅看了反革命分子戚本禹〔335〕一九六六年十二月二十四日在矿院的公开演说。大家一致认为：张霖之同志的历史是清楚的。张霖之同志在矿院全校广播中听到戚本禹反革命分子这种威胁和煽动的语言，而身体已受到重伤，自不能不陷入极度紧张状态，因此，致张在武斗和逼供的混乱中死去。
　　根据当时情况，矿院专案组的报告只涉及各项经过的表面现象，还需要依照煤炭工业部所掌握的全面材料，认真地予以澄清。
　　兹决定，张霖之同志的死亡，应按人民内部矛盾处理。张霖之同志家属和他的子女不受任何牵连，应按革命干部家属看待。



　　*这是为国务院起草的给煤炭工业部的通知节录。



废除法西斯式的审查方式*
（一九七二年十二月十八日）
　　请你们联合起来办三件事。
　　一、将刘建章〔336〕保外就医。按他身体病状，或送阜外医院，或送工农兵医院，并通知其妻刘淑清及其子女家属去看望刘。
　　二、将刘建章全案结论抽出送国务院先念〔337〕、登奎〔338〕同志批。
　　三、请公安部会同卫戍区将我在国务院当面提出过的要清查北京监狱待遇问题，再在年内做一次彻底清查。凡属毛主席指出的“这种法西斯式的审查方式”和虐待、殴打都需列举出来，再一次宣布废除，并当着在押犯人公布。如有犯者，当依法惩治，更容许犯人控诉。
　　各事办好，请分别报来。附去主席批示件，请随第三事办好退回。



　　*一九七二年，原铁道部副部长刘建章的妻子刘淑清同志写信给毛泽东同志，反映刘建章同志无辜被捕及在狱中受到迫害。毛泽东同志批示：“请总理办。这种法西斯式的审查方式，是谁人规定的？应一律废除。”周恩来同志立即给公安部、交通部和国务院办公室负责人写了这封信。



对参加国庆招待会名单的意见*
（一九七四年九月二十九日）
　　昨晚你交我国庆节招待会拟见报的名单，并告我已经主席一一听过，主席当即提出要加肖华〔339〕、李力群〔340〕、侯宝林〔341〕三人，又问及商震〔342〕是否列入。经政治局昨晚讨论，你告我遵照主席精神，又加刘志坚〔343〕一人。昨夜我匆匆看过名单，便想到齐燕铭〔344〕。
　　今晚又将两千多见报名单细细翻阅。在第十七类爱国人士方面，据统战部提出起义将领四夫人韩权华（卫立煌〔345〕夫人）、郭翼青（程潜夫人）、洪希厚（张治中夫人）、刘芸生（傅作义夫人）及张学铭〔346〕（张学良〔347〕之弟、张学思〔348〕之兄，因吕案解案〔349〕被禁多年，去年已无罪释放）五人。我看，四夫人对国内外影响也不小。至于张学铭，则因林彪利用东北军一案大搞东北民主人士，现吕正操同志已平反，张学思已死（此案亦应弄清），故邀张学铭出席有此必要。



　　*这是写给王洪文和中共中央政治局的一封信的节录。当时，周恩来同志病重住院，政治局日常工作由王洪文主持。

　　**“文化大革命”中，林彪、江青反革命集团为达到篡党夺权的罪恶目的，残酷迫害党内外干部，制造大批冤假错案。周恩来同志在非常困难的情况下，为保护干部作了极大的努力。这里选辑的是有关文电的一小部分。




