# 关于经济工作的几则文电*

中文马克思主义文库 -> 周恩来
关于经济工作的几则文电*
（一九六六年——一九七三年）

工人请愿不要妨碍生产*
（一九六六年十一月二十八日）

欢迎你们派代表（小厂一人，大厂二至三人，总数请不要超过三百人）来北京商谈。

请你们认真考虑：成千的工人同志来北京请愿，既不便于接待和会谈，也会影响你们工厂的生产。如果另一方面工人同志也照样来京，那将更影响生产。

我们希望：在省、市委和工矿企业的领导方面，要保证不得解雇工人，不得扣工资，不得打击报复，不得用党籍、团籍来威胁工人；在工人同志方面，要保证安排好生产，不要妨碍生产和交通运输。

你们来京人数确定后望告，以便通知铁道部配车，车费由所属厂矿解决。廖志高〔350〕同志也同你们的代表一道来京。

*这是由周恩来同志修改和审定以国务院名义发给成都拟来北京请愿工人的电报。

藏富于民*
（一九六七年五月三日）

毛主席说过，农民以多报少是藏富于民。粮食多了百分之十，只有好处，农民是不会乱吃掉的，藏在农民家里比国家收购起来还好。你们不要产生错觉，这不是提倡不老实，毛主席讲这句话的意思是整官僚主义的。官僚主义者不下去，不调查，一九六一年以前实行高指标、高征购，整了农民，现在他们就以多报少。城市也是这样，多报人口，口粮就多算了。

土地以多报少，粮食以多报少，人口以少报多，灾情以少报多。两个以多报少，两个以少报多，这是对付官僚主义的办法。如果我们实事求是，依靠贫下中农，他们就会说真话。

必要的奖励政策不能叫物质刺激。过去实行奖励政策是需要的。对产棉花地区要给些化肥和粮食，使他们的生产恢复得快些。我们出口一吨大米可以换回一点七吨小麦或两吨玉米，换回来外汇，很有利嘛！

粮食工作也有错误。以前有过大进大出。征购多了，必然返销，造成假象，徒劳往返。毛主席主张能少购就少购一点，藏富于民是好事。战争打起来还是藏富于民好，特别是要消灭敌人在国境内，这就更有必要了。

*这是接见十四个省、市夏季粮油征购会议代表时的谈话节录。

不许中断铁路轮船交通*
（一九六七年五月三十一日）

送上铁路中断情况电讯八份，请阅。今午在主席处，已说明铁路轮船关系到全国交通命脉，决不能中断。下午曾约集富春〔351〕、先念〔337〕、剑英〔352〕、肖华〔339〕、成武〔353〕、谷牧〔354〕、秋里〔355〕各同志会商此事，除已报请批发不许中断铁路轮船交通命令外，并拟将全国十八个铁路管理局分给附近驻军实行军管包干，将沿海沿江轮运交海军军管包干，均与当地军分区、武装部分开，不再介入地方支左〔356〕工作，以便统一全国铁路轮船运输，免受干扰。这一计划正由总参草拟，明日当可订出送审。

此外，拟为此事再发一告铁路轮船职工书，定稿后再送阅。

*这是给“中央文革小组”的信。

联合起来，保护海港运输*
（一九六七年十月二日）

据说，由于厦门海关和港务局各分两派，无人检查，致英国商船到来后无法靠岸，而该船有三病号，吃喝均成问题。这种违犯国法、影响祖国信誉的行动，是极端错误的，是绝对不能容忍的。望厦门军管会、调查组接此电话后立即向两派组织号召：对外、对业务必须采取联合行动，如果哪一派响应中央、主席号召并见于行动，中央将通报表扬，如拒不执行，中央定予揭露，并命令军管会采取必要措施，保护海港检查、靠岸装卸。哪一派破坏这一行动，军管会应按《六六通令》〔357〕惩处该派的主使人和肇事头头。

*这是给厦门军管会的电话稿。

制止武斗措施*
（一九六八年）

取消武斗专业队。

按系统归口接受革命大联合三结合。

不许重拉队伍另立山头，革委会、军管代表要保证任何工人职员不得被赶离本生产工作岗位。凡自动脱离不回厂者要限期回厂，逾期不归的扣发工资，半年不回的开除。

凡回厂者要由革委会、军管代表保护，被打的，要追查凶手，送院治疗，按期送工资。

停止脱离生产和工作岗位的自由串连。

不容再运再抢武器弹药。

不许攻夺建筑物，建立据点。

不许抢夺任何公家仓库商品物资。

更不许杀人放火。

*这是周恩来同志的手稿。

合理的规章制度应该保留*
（一九六九年四月十二日）

飞机因质量事故影响到战备和援外，影响到安全。你们都是空军来的，怎么能对同志的性命这样不负责呢？一个军事工厂搞得这样怎么行？四一○厂取消了检验制度你们是不是知道？报告了没有？你们为什么不敢抓？为什么不下命令恢复？你们就是怕事，怕群众。我是早上看到报告的，看后非常难过，军事工厂哪能搞成这样！你们现在还说检验制度正在逐步恢复。什么逐步恢复？你们怎么能这样说话，怎么能用这样的词句？不是逐步恢复，而是应当马上恢复！对的、合理的要马上恢复，不对的不恢复。检验是不能放松的。你们应当下命令嘛！改革不合理的规章制度，合理的还是要保留，一概取消是不符合毛泽东思想的，是不尊重科学的。不能违背科学。应该相信工人阶级，只要把道理给他们讲清，他们是不会同意取消这些合理的规章制度的。有些人要把一切制度砸烂，这是极左思潮。对西北、西南、东北都要派人去检查。二十年来，毛主席的红线还是主要的，不能否定一切，要一分为二，不然二十年的工业生产怎么能发展起来呢！

*这是在召集有关部门负责人解决飞机生产质量事故问题时的谈话节录。

要把质量问题放在议事日程来解决*
（一九七一年十二月十五日、一九七二年一月二十一日）
一

“歼六”四十架，原说是为援外装配的。一经检查，便有七架不能交付，占全数百分之十七点五。只此一端，就可看出我们飞机生产质量下降到什么程度，还不够我们提起警惕么！

二

请秋里〔355〕象剑英同志一样，把长汽、二汽、重汽、南汽〔358〕抓一抓。质量这样下降，如何援外，如何备战？这是路线问题，要在这个月内放在议事日程来解决！

*这是关于飞机、汽车生产质量问题的两件批示。

消除林彪一伙对经济的破坏性后果*
（一九七三年二月二十六日）

一九六九年以后，在经济管理上瞎指挥盛行。南昌把飞机厂最好的工人下放了。景德镇陶瓷窑也给炸了。林彪一伙一直破坏到“九一三”〔359〕，影响到一九七三年，恶果逐步暴露出来了。应把九大〔326〕以来林彪一伙破坏经济计划的情况编个材料，供大家批判。一定要批透，把破坏性后果消除掉。

工业生产指标，煤增长最少，电也少啊！这样，生产怎么能上去。国民经济要按比例发展，但现在根本没有比例！

经济协作区问题怎么提法？到处搞独立经济体系是不行的。

基本建设战线为什么长？一是中央各部的项目多了，一是地方项目也多了，原因就在这里。中央和地方，首先中央收缩一下。中央、地方都不许扩大建设规模，中央先下一些，给地方留点余地。

基本建设要经常检查，全年抓。一九七○年基本建设大膨胀，一九七二年没有抓，鉴于这个教训，以后要全年抓。该停的停，停得不合适的再建。

基本建设中的问题，还要说一条，有人在基建中顺手牵羊，搞非生产性建设。当然必要的可以建，如宿舍、商店、学校要建。但是有很多建筑不是这方面的，要指出来。

地方五小工业〔360〕要整顿的问题说得不够。搞五小工业也要有原料、材料和设备的保证。没有原料也搞，同大厂争原料，变成自由发展了。整顿的方针要写清楚。发展五小工业要有个范围，要对农业有利，破坏计划的无论如何不能发展。

职工人数、工资总额、粮食销售量三项都突破了计划数字。去年我讲了这个问题，但没有抓。确实没有“王法”了。

不只三个突破，货币发行也突破了。这不是那么舒服的。资本主义有经济危机，我们与他们根本不同，但也不那么舒服。商品有差额，货币回笼不了。职工人数多了，工资多了，货币流通量也一定多了。多是一定要多的，但现在超过了实际需要，要研究这个问题。今年市场平衡有三十亿元的商品差额，票子发多了。

林彪一伙破坏经济所造成的恶果这两年表现出来了。票子发多了，到了最大警戒线。三个突破不如这一个突破。你们管财政、银行的也不叫，要随时提醒，这是个寒暑表嘛！湖北货币大投放，去年第四季度预支今年的，安徽、江苏也投放。这样大胆地开支，过去是少有的哩！

全国职工总数突破五千万人，一下子达到五千六百多万人。你们要抓一下。民工好减，五小工业工人、临时工要动员回去，现在就要进行工作。

钢那么多，钢材怎么样？前后左右不衔接，出了钢不能轧材，白白消耗了热能。还是十年前存在的问题，一前一后，前后左右总是个大问题。运输能力也不行，进出口拥挤不堪。这些不建设，光搞大品种不行。

按劳分配的问题，现在是四个一样〔381〕嘛！还有干难干易一个样。“不利于调动职工积极性，也不利于控制职工人数的增加”，这句话说得对！

必要的奖励制度是可以的。

*这是在国家计划委员会汇报一九七三年计划和《关于坚持统一计划，加强经济管理的规定》的草稿时的插话。

农业生产要注意防涝抗旱*
（一九七三年五月十四日）

请你们好好读一下五月十四日的《参考消息》（五二五一期）四版下栏关于世界气象变化的两篇报道，并要气象局好好研究一下这个问题。今年我们可能还会遇到南涝北旱的局面，请告农林部多多提醒各地坚持实行防涝抗旱的措施，不要丝毫松懈。

*这是给李先念等同志的信。

**“文化大革命”期间，林彪、江青反革命集团在全国各地煽动派性，挑动武斗，破坏生产，中断交通，使国民经济遭到巨大损失。周恩来同志在十分困难的情况下，尽力促进职工队伍的团结，稳定局面，维持生产，减少损失。这里选辑的是有关这一方面工作的几则文电。

