# 恢复文教科技部门的正常工作*

中文马克思主义文库 -> 周恩来
恢复文教科技部门的正常工作*
（一九七○年——一九七三年）

不要因人废文*
（一九七○年九月十七日）

王云五〔362〕编的四角号码字典为什么不能用？不要因人废文。一个人有问题，书就不能用了？它总有可取之处嘛！马克思主义的三个来源是德国的古典哲学、英国的古典政治经济学和法国的空想社会主义。这三个来源还不是资产阶级的或受唯心史观限制的学说吗？可是它们都含有合理的因素。任何思想的发展都不是无根的，新社会是从旧社会脱胎出来的。剥削阶级的出身不能改，思想却是可以改造的。这就叫历史唯物主义。要有点辩证法，不要一听封建主义、资本主义就气炸了，那叫形而上学、片面性。

中华书局、商务印书馆就不能要了？那样做，不叫为群众服务。青年一代着急没有书看，他们没有好书看，就看坏书。毛主席在九届二中全会上讲，要学哲学，要反对唯心主义。同志们要好好读马克思、恩格斯、列宁、斯大林的书，读毛主席的书。

要懂得水有源树有根。毛泽东思想是从马克思列宁主义发展来的，马克思列宁主义是毛泽东思想的根。《新华字典》也是从《康熙字典》发展来的嘛！编字典可以有创造，但创造也要有基础。要古为今用，推陈出新。新的出不来，旧的又不能用，怎么办？芭蕾舞是洋的，能说是我们创造的吗？我们编的芭蕾舞剧，基础是原来的，内容却是新的，形式又有了改造，这就叫做洋为中用。芭蕾舞还要发展。你们文化部门的同志要好好读几本马克思列宁主义的书，知道一点根嘛！毛主席的哲学著作，可以先学《实践论》，要通过实践来提高我们的认识。

*这是同文化教育部门一些负责人的谈话节录。

关于外语教学的谈话*
（一九七○年十一月二十日）

你们要研究一下，外语师资短训班的效果到底如何？学的能巩固吗？落实的有多少？也许个别人学得快，多数人是平平或较差，个别人不行。如果五十天效果很差，可以向主管部门提出建议，延长一些时间。要抱着对学员负责的态度，否则误人子弟。师资培训不好，将来学生也教不好。短训班质量不行，人家会骂你草草了事。

学外语要天天练。天天练的时间不要仅限于一个小时。如果硬性规定一小时，其他时间就不许练，这种办法一定要脱离群众的。他们是学外语的，将来要做外语工作。外语教师也好，外事工作人员也好，总是要练，要允许人家抽空练。人家自己挤点时间练，不要去干涉！所以天天练不要限于一小时。别的活动多的时候也不要取消练外语。时间允许的话可以增到两三个小时。

苦练，应当成为原则，毛主席就强调这一点。写字也要苦练才能写得好。要把语言这个工具用得纯熟，还是要苦练。要看一些新的资料，光看课本不够。

翻译工作不是那么好做的。不仅要有现场经验，还要掌握材料，了解背景，真正翻译得恰当是不容易的。

现在有的中学英语课本，只有政治词汇，没有生活词汇，实在不适用，应当修改。政治语言和生活语言可以一并学，实际上也不能分。北大英语教材有一个问句：“你出身工人家庭吗？”这个问题局限性太大，难道除此之外就没有别的出身？

外语教学有个基本功问题。比如京戏有基本功，唱腔、道白、武打等，这都是京戏艺术的基本功。而且，京戏的基本功不限于京戏艺术本身，还有政治、历史、地理等知识。学外语也是如此，不光是要掌握外语的语音、词汇、语法，做好听、说、读、写、译五个字，还要懂得历史、地理。不仅要读中国地理、历史，还要读世界地理、历史。自然科学也要懂一些。马克思、恩格斯懂得很多自然科学知识。毛主席也知道得很多。你不懂这些知识，做翻译时就译不出来。搞翻译不是那么简单的，不是懂几句外国话就行的。不但要有政治水平，同时要有较高的文化水平。没有基本功和丰富的知识不行。基本功包括三个方面：政治思想、语言本身和各种文化知识。

外语教学要造就什么人材？第一是师资，有了好的师资，中学生把外语学好了，进大学或以后自学就有了基础。第二是培养懂外文的干部、技术人员，要使他们能够读外文资料。第三是外事工作人员。这三方面的需要都很急迫，需要量最大的是师资，最急需的是外事人员。因此，要认真搞好外语教学。俄文为什么丢掉呢？一旦需要，量是很大的。

*这是接见北京大学、北京外语学院等校师生代表时的谈话节录。

讲历史，多出书*
（一九七一年四月十二日）

你们管出版的，要印一些历史书。我们要讲历史，没有一点历史知识不行。你们的出版计划中有没有历史书籍？现在书店里中国和外国的历史书都没有。不出历史、地理书籍，是个大缺点。马克思主义的三个组成部分都是从资产阶级的或受唯心史观限制的学说发展来的。不讲历史、割断历史怎么行呢？中国人不讲中国历史总差点劲。毛主席的著作还有不少篇幅是讲历史的嘛！读毛主席的著作也得懂历史。

同志们说，有的地方把封存的图书都烧了，我看烧的结果就是后悔。应该选择一些旧的书籍给青少年批判地读，使他们知道历史是怎么发展来的。都读新的，哪有那么多？要有组织地给他们读一点书，总不能把历史割断吧！否定一切，不一分为二，这是极左思潮，不是毛泽东思想。我们要用历史唯物主义的观点来看问题。那些把书都烧了的，还不是受极左思潮的影响？不一分为二，就是极左思潮。

《鲁迅全集》封起来干什么？这不是滑稽得很吗！普列汉诺夫〔363〕前期是马克思主义者，有好的著作。把有点问题的书都封起来，只有少数人能看，只相信自己不会受影响，其他人就都会受影响？群众总是比我们个人知道得多，他们是能够作出判断的。一面说青年没书读，一面又不给他们书读，就是不相信青年人能判断。无怪现在没有书读了，这完全是思想垄断，不是社会主义民主。

我看现在要出一批书，要广开言路。读马克思、列宁的书和毛主席的书是主要的，但也要读历史、地理，读哲学。有些青年连世界地理位置、重大历史事件都搞不清楚，知识面越来越狭窄，这不行，这样是不可能真正高举毛泽东思想伟大红旗的。毛泽东思想不是孤立产生的，是马克思列宁主义的普遍真理和中国革命的具体实践相结合的产物，是伟大的实践产生的伟大的知识。

*这是在接见全国出版工作座谈会领导小组成员时的谈话节录。

极左思潮破坏艺术质量的提高*
（一九七二年四月九日）

你们报幕的同志，为什么不报独唱、伴奏人员的名字？看来你们的极左思潮还没有肃清。极左思潮不肃清，破坏艺术质量的提高。

你们的歌越唱越快，越唱越尖，越唱越高。

革命激情要和革命抒情结合，要有点地方的色彩。

*这是在广州观看部队文艺演出时的谈话。

加强气象工作*
（一九七二年七月三十日）

请你们乘此由国务院业务组将气象局业务抓起来，体制暂时不管。

总参、海军、空军哪一位管气象？请剑、春、德〔364〕三位指定专人参加国务院业务组会议，整顿气象局全国布局。收听国际气象预报和预测，不知地面卫星站能否通过空中卫星收听更多情报，请打听一下，如行，立即办。凡属空白地区、海岸都要分类补上，对北线西线寒流、东线南线暖流也要管。人不够，要从“五七”干校〔332〕调回，或者将转业或遣散走的调回。要打破军民界限，共同协力，军民两用。预防各种气象变化，特别要防气流、大风突变转向。总结经验，并且要考虑到空气中有无新的因素、元素增变。

妥否，请酌。

*这是针对“文化大革命”中各单位业务工作遭到严重破坏的情况，在中央气象局《关于今年第三号台风预报的初步检查报告》上写给叶剑英、李先念等同志的批语。

重视基础科学和理论研究*
（一九七二年九月十一日）

文裕〔365〕同志交来二机部四○一所一部十八位同志一信〔366〕，已由郭老〔265〕、西尧〔331〕同志处转到。看了很高兴，正是月初我们同见巴基斯坦那位科学家〔367〕时所说的话。

现在请文裕同志将你们今年四月送给二机部和科学院那份报告〔368〕转给我一看。西尧同志请朱光亚〔369〕同志召集有关方面一议事，请不要等我批，先议出办法，供大家讨论采用。

这件事不能再延迟了。科学院必须把基础科学和理论研究抓起来，同时又要把理论研究与科学实验结合起来，高能物理研究和高能加速器的预制研究，应该成为科学院要抓的主要项目之一。所见可能有错，请你们研告。

*这是给张文裕、朱光亚同志的信。同年七月，周恩来同志曾指出，要把综合大学的理科办好，提高基础理论水平，并强调有什么障碍就要拔除。八月，他还对当时的科教组和科学院负责同志指出，要“好好议一下，并要认真实施，不要如浮云一样，过了就忘了”。

中学毕业生可以直接上大学*
（一九七二年十月十四日）

我们小学和中学的学制究竟是十年还是十二年，还没有确定。过去是十二年，是不是要这么长，现在还在研究。对学习社会科学理论或自然科学理论有发展前途的青年，中学毕业后，不需要专门劳动两年，可以直接上大学，边学习、边劳动。当然这总是少数，大多数人要参加劳动，不一定升学。至少在七十年代和八十年代不可能所有的人都进大学，国家没有这个力量。中学毕业后马上进大学的总是少数，大量的要在生产实践中提高。劳动几年后，有升学机会的当然还可以深造。

*这是会见美国哥伦比亚大学教授李政道博士时的谈话节录。

要学外国的长处*
（一九七三年二月二十六日）

最近我们出去了两个代表团。一个医学代表团在国外看了回来，不敢做报告。他们要做报告，有一个军代表说，不要把我们说得一团漆黑。这么老大，随便给人家戴帽子，结果他们不敢讲了。这种风气不好。出去花了不少钱，回来连报告也不敢做。科学家代表团出国回来后，连一个报告都没有写出来，不敢谈人家的长处，也不敢谈我们的短处，这是不符合毛泽东思想的。有些人自己不懂，又随便给人家戴帽子。出国参观、考察，就是为了学习人家的长处。

*这是在国家计划委员会汇报一九七三年计划和《关于坚持统一计划，加强经济管理的规定》的草稿时的谈话节录。

**“文化大革命”中，林彪、江青反革命集团乘机煽动极左思潮，使文教、科技、出版等方面的工作遭到严重破坏。这一组文件，部分地反映了周恩来同志在这几个方面同林彪、江青反革命集团所作的斗争。

