# 《周恩来选集》下卷　注释

中文马克思主义文库 -> 周恩来
《周恩来选集》下卷　注释

〔1〕共同纲领 即一九四九年九月二十九日中国人民政治协商会议第一届全体会议通过的《中国人民政治协商会议共同纲领》。《共同纲领》确定了当时我国在政治、军事、经济、文化教育、民族、外交等各方面的基本政策。它是在中国共产党领导下，各民主党派、各人民团体和各族各界人民的代表共同制订的建国纲领，是全国人民在一定时期内共同的奋斗目标和统一行动的政治基础。一九五四年《中华人民共和国宪法》颁布以前，它起了临时宪法的作用。——第1、15、23、34、82、99、104、132页

〔2〕绥远 是旧省名。这两个字原有安抚平定边远地区的意思。一九四九年一月北京和平解放后，同年九月绥远和平解放。一九五四年该省撤销，其辖区划归内蒙古自治区。——第3、260页

〔3〕党的七届二中全会即一九四九年三月五日至十三日在河北省平山县西柏坡村举行的中国共产党第七届中央委员会第二次全体会议。毛泽东向全会做了报告。会议讨论了彻底摧毁国民党统治，夺取全国胜利，把党的工作重心从乡村转到城市，以生产建设为中心任务的问题。同时着重分析了当时中国经济各种成分的状况和党所必须采取的正确政策，规定了党在全国胜利后，使中国由农业国转变为工业国、由新民主主义社会发展到社会主义社会的总任务和主要途径。全会号召，全党在胜利面前务必保持谦虚、谨慎、不骄、不躁和艰苦奋斗的作风。——第9、123、331页

〔4〕学田是中国旧时属于学校的田地，一般为乡绅所把持。学校以学田的收入作为教师的薪俸和学生的补助等费用。一九四七年九月十三日，中国共产党全国土地会议通过的《中国土地法大纲》中规定废除学校的土地所有权。一九五○年一月十三日，政务院通过的《关于处理老解放区市郊农业土地问题的指示》中又明确规定学田应一律收归国有，对依靠学田收入维持的学校，应拟具妥善的办法，解决其经费问题。一九五○年六月中央人民政府委员会通过的《中华人民共和国土地改革法》，也作了类似的规定。——第20页

〔5〕清朝初年，因郑成功等在东南沿海领导反清的武装斗争，清政府厉行海禁，严禁人民出海，严格限制对外贸易。一六八三年清政府统一台湾后，才允许商民造船出海，并于一六八五年指定广州、漳州、宁波、云台山为通商口岸，允许外商来华贸易。一七五七年，由于英国等殖民者在中国沿海进行非法活动，清政府又下令只准在广州通商，并制定了许多外商来华贸易的禁例，继续实行闭关锁国的政策。一八四○年至一八六○年，英、法等国家先后发动两次鸦片战争，迫使清王朝签订许多不平等条约，开辟广州、厦门、福州、宁波、上海、牛庄（后改营口）、登州（后改烟台）、台南、淡水、潮州（后改汕头）、琼州、汉口、九江、南京、镇江、天津、喀什噶尔等地为商埠，并剥夺了中国关税自主权，取得了深入内地贸易、自由传教和招募华工出国等项特权。这样，它们用炮火打破了清王朝闭关锁国的局面。后来，人们把鸦片战争以后出现的这种形势，称为“海禁大开”或“海禁开放”。——第22页

〔6〕北洋军阀 是清末袁世凯在北方几省首先建立起来的封建军阀集团。一八九五年清政府命袁世凯在天津小站编练“新建陆军”，归北洋大臣节制。一九○一年袁世凯任直隶总督兼北洋大臣以后，培植党羽，自成派系。辛亥革命后，袁世凯窃取中华民国临时大总统职务，组织了代表大地主大买办阶级的第一个北洋军阀政府。一九一六年袁死后，这个集团分别在英、日等帝国主义国家支持下分化为直、皖、奉三系，为争权夺利彼此间进行过多次混战。一九二六年皖系军阀段祺瑞下台，一九二七年直系军阀被国民革命军消灭，一九二八年奉系军阀政府垮台。至此，北洋军阀反动统治时期结束。——第22、62、95、258、297、318、355、413页

〔7〕李仪祉 （一八八二——一九三八），陕西蒲城人，水利专家。一九二二年起，历任陕西省水利局局长、黄河水利委员会委员长等职，曾提出很多治理黄河的意见，主办过陕西省泾惠、洛惠、渭惠和织女渠等灌溉工程。——第22页

〔8〕孔祥熙（一八八○——一九六七），山西太谷人。曾任国民党政府财政部部长、行政院院长、中央银行总裁、中国银行总裁，长期控制国民党政府的财权。一九三八年他在任行政院院长时，颁行“非常时期农矿工商管理条例”，实行所谓战时经济管制政策，大幅度压低棉花价格，对农民进行公开的掠夺。据统计，一九三八年和一九三九年陕西每市担棉花所能换取的生产资料或生活资料，只相当于抗日战争前的百分之四十左右。——第22页

〔9〕花园口的决堤 指抗日战争时期国民党军队炸开黄河大堤的事件。一九三八年五月，日本侵略军攻占徐州，随即沿陇海路西进。六月初，蒋介石下令炸开郑州以北花园口黄河大堤，企图以黄河之水阻止日军西犯。结果不仅未能阻住日军进攻，反而给人民造成空前灾难。河南、安徽、江苏三省四十余县被淹，数十万人溺死，一千多万人流离失所。大水过后，留下了一片连年灾荒的黄泛区。——第23页

〔10〕土改 这里指中华人民共和国成立后，中国共产党领导广大农民废除封建的土地所有制，实现农民的土地所有制的革命运动。一九五○年六月，中央人民政府颁布《中华人民共和国土地改革法》，同年冬起，在新解放区陆续开展了土地改革运动。到一九五二年冬，除台湾省和一部分少数民族地区以外，全国的土地改革基本结束，使三亿元地或少地的农民分得了约七亿亩土地和其他生产资料。——第24、41、55、63、80、93、132、162、264页

〔11〕侯德榜（一八九○——一九七四），福建闽侯人，化学家。一九二二年至一九三四年先后创办塘沽永利碱厂和南京永利硫酸铵厂，一九三九年发明联合制碱的生产技术，称为候氏制碱法。一九五○年时是永利化学工业公司总经理。一九五七年加入中国共产党，次年任化学工业部副部长。——第25页

〔12〕萨福均 （一八八六——一九五五），福建福州人，铁路工程专家。曾参加修建粤汉铁路。一九五○年时是西南军政委员会交通部副部长兼西南铁路工程局副局长。——第25页

〔13〕詹天佑（一八六一——一九一九），广东南海人，铁路工程专家。一九○五年至一九○九年主持修建我国自建的第一条铁路——京张铁路（今京包线的北京至张家口段），后又主持修建粤汉铁路。——第25页

〔14〕整风运动 指中国共产党自一九四二年起在全党范围内开展的一个马克思列宁主义的思想教育运动。主要内容是：反对主观主义以整顿学风，反对宗派主义以整顿党风，反对党八股以整顿文风。经过这个运动，全党进一步地掌握了马克思列宁主义的普遍真理与中国革命的具体实践的统一这样一个基本的方向。——第29、123、313、359、412页

〔15〕党的第七次全国代表大会 于一九四五年四月二十三日至六月十一日在延安举行。毛泽东做《论联合政府》的政治报告，朱德做《论解放区战场》的军事报告，刘少奇做《关于修改党章的报告》；周恩来做《论统一战线》的重要发言。大会总结了我国民主革命二十多年曲折发展的历史经验，制定了正确的纲领和策略，克服了党内的错误思想，使全党的认识在马克思列宁主义、毛泽东思想的基础上统一起来，达到了全党的空前团结。这次大会，为新民主主义革命在全国的胜利奠定了基础。——第29、125、303、313页

〔16〕大禹 是传说中我国古代部落联盟领袖。他率领群众用疏通江河的办法治平水患。——第30页

〔17〕指中苏友好同盟互助条约。一九五○年二月十四日中华人民共和国同苏维埃社会主义共和国联盟在莫斯科签订，同年四月十一日起生效，有效期三十年。一九七九年四月三日举行的中华人民共和国第五届全国人民代表大会常务委员会第七次会议，鉴于国际形势已发生重大变化，决定条约期满后不延长。——第31页

〔18〕盟国对日管制委员会 是第二次世界大战后盟国驻日占领军最高统帅的咨询机构。它根据一九四五年十二月苏、美、英三国外长莫斯科会议的协议在东京设立，由中、苏、美三国代表各一人和英国、澳大利亚、新西兰、印度四国联合代表一人组成。其主要任务是实现《波茨坦公告》的规定，完全解除日本的武装，并使其走向民主化。中华人民共和国成立后，中国在该机构的席位仍由蒋介石集团的代表非法占据着。一九五二年四月该机构由美国单方面宣布解散。——第36页

〔19〕李承晚 （一八七五——一九六五），当时是南朝鲜“总统”。——第36页

〔20〕辽东省，一九四九年设置，辖今辽宁省东部。一九五四年撤销，其大部分地区和当时的辽西省合并为辽宁省，部分地区划归吉林省。——第36页

〔21〕斯德哥尔摩宣言 是世界保卫和平大会常设委员会于一九五○年三月在瑞典首都斯德哥尔摩举行的第三次全体会议上通过发表的。宣言要求无条件禁止原子武器，并号召全世界一切善良的人们在这个宣言上签名。随后，在全世界范围内掀起了一个签名运动。——第37页

〔22〕人民代表会议 即地方各界人民代表会议，是解放初期人民参政的一种形式。其代表由推选、邀请、商定及选举等方式产生。在地方各级人民代表大会召开之前，它先是地方各级人民政府传达政策、联系群众的协议机关，后曾代行地方各级人民代表大会的职权。在各界人民代表会议休会期间，设各界人民代表会议协商委员会，协助人民政府实行各界人民代表会议的决议，以及负责筹备下届各界人民代表会议。——第38、58、74、95页

〔23〕一九五○年三月二十五日中共中央发出的《关于全党学习<斯大林、毛泽东论共产党员要善于和非党群众团结合作）的指示》。指示指出，中国共产党在与非党员亲密团结这一工作上，是有很大成绩的。但是，有一部分党员，特别是负相当领导责任的党员，仍然犯着向党外群众摆党员架子，摆革命老资格，不愿或不善于和党外群众与民主人士合作的关门主义的毛病。指示要求各级党委和全体党员认真学习《斯大林、毛泽东论共产党员要善于和非党群众团结合作》这一文件，以加强共产党员和民主人士及广大非党群众的团结合作。——第39页

〔24〕这里指一九五○年在中国共产党内进行的整风运动。这年五月一日，中共中央发出《关于在全党全军开展整风运动的指示》，指出全国胜利后新党员大量增加，其中很多人思想作风不纯；在老党员中，也有很多人滋长了骄傲自满、命令主义作风，少数人甚至贪污腐化，违法乱纪。指示要求全党在和各项工作任务密切地结合而不是相分离的条件下，用阅读若干指定文件，总结工作，分析情况，展开批评和自我批评等项方法，进行一次整风运动，以整顿全党首先是干部的作风。——第39页

〔25〕这里指当时流通的旧人民币。中国人民银行自一九五五年三月一日起发行新人民币代替旧人民币，按规定人民币新币一元等于旧币一万元。——第45页

〔26〕一九五○年六月二十五日朝鲜内战爆发后，美帝国主义发动侵朝战争，同时派军队侵略我国领土台湾。九月十五日又打着联合国军的旗号，派兵在朝鲜西海岸仁川登陆，随后越过“三八线”大举北犯，并且轰炸、扫射中国东北边境城市和村庄，严重威胁中国的安全。为了援助朝鲜人民的抗美救国战争、保卫刚刚诞生的新中国，中国人民响应毛泽东主席发出的抗美援朝、保家卫国的号召，组织了以彭德怀为司令员兼政治委员的中国人民志愿军，开赴朝鲜前线，同朝鲜人民军并肩作战，抗击美国侵略军。十一月四日，中国各民主党派发表联合宣言，坚决支持志愿军的正义行动。全国人民以增产节约、报名参加志愿军、捐献武器等各种方式全力支援朝鲜前线的作战。在中朝人民军队的沉重打击下，美帝国主义连遭失败，被迫于一九五三年七月二十七日在朝鲜停战协定上签字。至此，朝鲜停战实现，中国人民的抗美援朝战争取得了伟大胜利。——第50、87、93、106、148、162、236、273、302页

〔27〕华莱士（一八八八——一九六五），原为美国共和党人，后加入民主党，在罗斯福任总统期间，曾任农业部长、商务部长和副总统。一九四六年加入美国进步党。一九四八年十一月参加总统竞选失败后，在纽约州经营农业。一九五○年六月朝鲜战争爆发后，他一方面支持美国政府的侵朝战争政策，另一方面又在九月二十九日以农人身份给毛泽东写了一封信，说什么“如果新中国在学会制造卡车和拖拉机之前先学会了制造坦克，这将是一个世界的悲剧”。——第51页

〔28〕一九四五年八月日本投降时，美、苏两国商定在朝鲜国土上以北纬38°线作为两国接受日军投降的临时分界线，分界线以北为苏军受降区，以南为美军受降区。这条线通称三八线。朝鲜战争爆发时，朝鲜人民已在这条线以北地区建立了朝鲜民主主义人民共和国；这条线以南地区还在美帝国主义扶植的李承晚集团统治下。——第52页

〔29〕尼赫鲁（一八八九——一九六四），当时任印度总理。——第52页

〔30〕这里指一九五○年九月十二日至十八日在美国纽约召开的美、英、法三国外长会议。——第52页

〔31〕见本书第37页。——第52页

〔32〕贝文 （一八八一——一九五一），英国工党首领之一。一九五○年时是英国工党内阁外交大臣。当时我国同美国尚未建立外交关系，在关于朝鲜战争问题上同美国政府的一些交涉，是通过与我国已建立外交关系的印度，再由印度通过英国来进行的。——第52页

〔33〕麦克阿瑟（一八八○——一九六四），美国职业军人。一九四五年日本投降后，任盟国驻日占领军总司令，执行美国单独占领日本的任务。一九五○年六月任“联合国军总司令”，指挥侵朝战争。——第52页

〔34〕甲午战争 是一八九四年（甲午年）中国和日本发生的战争。这次战争是日本军国主义者蓄意挑起的。日本军队先向朝鲜发动侵略并对中国的陆海军进行挑衅，继即大举侵入中国的东北。由于清朝政府的腐败，中国方面在陆上和海上都遭到失败，被迫于一八九五年签订了《马关条约》。——第53、297页

〔35〕七七事变 也称芦沟桥事变。芦沟桥距北京城十余公里，是北京西南的门户。一九三七年七月七日，日本侵略军在这里向中国驻军进攻。在全国人民抗日热潮的推动和中国共产党的抗日主张的影响下，中国驻军奋起抵抗。中国人民英勇的八年抗战，从此开始。——第53、321页

〔36〕这里指一九五○年四月十三日中央人民政府委员会第七次会议通过、五月一日由中央人民政府公布施行的《中华人民共和国婚姻法》。全文共八章二十七条。主要内容是：废除包办强迫、男尊女卑、漠视子女利益的封建婚姻制度，实行男女婚姻自由、一夫一妻、男女权利平等、保护妇女和子女合法利益的新婚姻制度。——第55页

〔37〕一九五一年九月起，北京、天津各高等学校的教师进行了有系统的思想改造的学习运动。为了统一领导这一运动，教育部成立了京津高等学校教师学习委员会，北京大学教师学习会是这个学习委员会的分会。——第59页

〔38〕马校长 指马寅初（一八八二——一九八二），浙江嵊县人，经济学家。当时任北京大学校长。——第59页

〔39〕五四运动 是一九一九年五月四日发生的反帝反封建的爱国运动。当时，第一次世界大战刚刚结束，英、美、法、日、意等战胜国在巴黎召开对德和会9决定由日本继承德国在中国山东的特权。中国是参加对德宣战的战胜国之一，但北洋军阀政府却准备接受这个决定。五月四日，北京学生游行示威，反对帝国主义的这一无理决定和北洋军阀政府的妥协。这次运动迅速地获得了全国人民的响应，到六月三日以后，发展成为有工人阶级、城市小资产阶级和民族资产阶级参加的广大群众性的反帝反封建的爱国运动。五四运动也是反对封建文化的新文化运动。以一九一五年《青年杂志》（后改名《新青年》）创刊为起点的新文化运动，坚起“民主”和“科学”的旗帜，反对旧道德，提倡新道德，反对旧文学，提倡新文学。五四运动中的先进分子接受了马克思主义，使新文化运动发展成为马克思主义思想运动。他们致力于马克思主义同中国工人运动相结合，在思想上和干部上准备了中国共产党的成立。——第59、297、303、356页

〔40〕陈独秀 （一八七九——一九四二），安徽怀宁人。一九一五年九月起主编《青年杂志》（后改名《新青年》），一九一八年和李大钊创办《每周评论》，提倡新文化，是五四新文化运动的主要领导人之一。五四运动后，接受和宣传马克思主义，是中国共产党的主要创建人之一。在党成立后的最初六年中是党的主要领导人。在第一次国内革命战争后期，犯了严重的右倾投降主义错误。其后，对于革命前途悲观失望，接受托派观点，在党内成立小组织，进行反党活动，一九二九年十一月被开除出党。后公开进行托派组织活动。一九三二年十月被国民党逮捕，一九三七年八月出狱。一九四二年病故于四川江津。——第61、301、425页

〔41〕章太炎 即章炳麟（一八六九——一九三六），浙江余杭人。早年参加戊戌维新运动，一九○四年和蔡元培等发起成立光复会，一九○六年加入同盟会。辛亥革命前，他先后在《苏报》、《国粹学报》、《民报》等报刊上发表文章，宣传革命思想，公开提出推翻清朝统治。——第62页

〔42〕《国粹学报》是一九○四年成立的学术团体国学保存会的机关刊物，一九○五年二月在上海创刊。它以“发明国学，保存国粹”、“爱国保种，存学救世”为宗旨，是一个阐发民族学术传统、宣传反清思想但有复古主义倾向的刊物。一九一一年武昌起义后停刊。——第62页

〔43〕袁世凯 （一八五九——一九一六），河南项城人。清末曾任山东巡抚、直隶总督兼北洋大臣等职，成为北洋军阀首领。一九一一年辛亥革命时，出任清政府内阁总理大臣。一九一二年在英、美、日等帝国主义国家支持下窃取中华民国临时大总统职务，组织了代表大地主大买办阶级的第一个北洋军阀政府，对内专制独裁，对外投降卖国。一九一五年五月接受日本企图灭亡中国的“二十一条”。同年十二月称帝，一九一六年三月在全国人民的反对下被迫取消帝制。——第62、297页

〔44〕“二十一条”是日本帝国主义利用第一次世界大战的时机在一九一五年一月十八日向袁世凯政府提出的旨在独占中国的秘密条款。这些条款共有五号，分为二十一条。主要内容是；一、由日本接管德国在山东所掠夺的权利，并加以扩大；二、承认日本在南满洲和内蒙古东部享有各种特权；三、将汉冶萍公司改为中日合办；四、中国沿海港湾岛屿概不让子或租予第三国；五、由日本控制中国的政治、财政、警察、军事大权，允许日本在湖北、江西、浙江、广东各省之间修筑重要铁路，并承认日本在福建享有投资修筑铁路、开采矿山、整顿海口等优先权。五月七日，日本提出最后通牒。五月九日，袁世凯政府对日本的这些要求，除声明第五号要求的一部分“容日后协商”外，一概加以承认。后来，因为全国人民的一致反对，以及各帝国主义国家在华利益上存在矛盾，日本的这些要求没有全部实现。——第62页

〔45〕中日军事协定 指一九一八年五月段祺瑞政府与日本政府在北京先后秘密签订的中日《陆军共同防敌军事协定》和《海军共同防敌军事协定》。协定以“共同防敌”为由，保证日本军队可以在共同进行反苏战争的名义下进入中国境内，并支配中国的有关军队。——第62页

〔46〕国家主义 是以抽象的国家概念来掩盖国家的阶级本质的一种资产阶级思想。十九世纪开始在欧洲流行。它标榜“国家至上”，主张放弃阶级斗争，效忠于剥削阶级的国家；有些国家主义者还鼓吹“民族优越论”，制造民族间的矛盾对立，并用保卫祖国的名义鼓动侵略战争。二十世纪二十年代，中国大地主大资产阶级的一些政治代表，组织了奉行国家主义的中国青年党，进行反对共产党和反对苏联的活动。——第62页

〔47〕少年中国学会 是五四时期建立的一个社团。由李大钊、王光祈等人发起，一九一九年七月在北京正式成立。这个学会兼容了共产主义知识分子、小资产阶级知识分子和资产阶级知识分子。出版刊物有《少年中国》、《少年世界》等。由于会员思想的分化日趋明显，一九二五年底停止活动。——第63页

〔48〕李大钊 （一八八九——一九二七），河北乐亭人。曾任《新青年》杂志编辑，并与陈独秀创办《每周评论》，是最早在我国传播马克思主义的先进分子之一。一九一八年参加筹组少年中国学会。一九二○年在北京组织共产主义小组，是中国共产党的主要创建人之一。——第63、303页

〔49〕曾琦（一八九二——一九五一），四川隆昌人。一九一八年参加发起筹组少年中国学会。一九二三年在法国留学期间与李璜等建立中国青年党。一九二四年回国，创办《醒狮》周报，鼓吹国家主义。一九二六年任中国青年党中央执行委员会委员长，一九四五年任该党主席。解放战争时期参加国民党一手操纵的国民大会，并任国民党政府委员、总统府资政等职。——第63页

〔50〕李璜 一八九五年生，四川成都人。曾参加少年中国学会。一九二三年在法国留学期间与曾琦等建立中国青年党。一九二六年任该党中央执行委员，一九四八年任该党代理主席。——第63页

〔51〕左舜生（一八九三——一九六九），湖南长沙人。曾参加少年中国学会。一九二五年加入中国青年党。一九二六年任该党中央执行委员会常务委员。一九三五年任该党中央执行委员会委员长。解放战争时期参加国民党一手操纵的国民大会，曾任国民党政府农林部部长。——第63页

〔52〕基马尔（一八八一——一九三八）是土耳其民族商业资产阶级的代表人物。一九一九年起领导土耳其的民族解放运动和资产阶级民主革命。一九二三年土耳其共和国成立后，当选为第一任总统。基马尔主义是以基马尔为代表的、主张在半殖民地半封建的国家建立资产阶级专政的思潮。中国一些资产阶级分子在一九二七年革命失败后曾高唱基马尔主义，企图在中国建立资产阶级专政的国家。——第63页

〔53〕洪秀全（一八一四——一八六四），广东花县人，太平天国农民革命运动的领袖。一八五一年，他和杨秀清等领导群众在广西桂平县的金田村起义，建号太平天国，同清朝的封建统治坚持斗争十四年之久。——第63页

〔54〕严复（一八五四——一九二一），福建闽侯人。曾在英国海军学校留学。一八九四年中日战争后，主张君主立宪，变法维新。曾译赫胥黎《天演论》、亚当·斯密《原富》、穆勒《名学》和孟德斯鸠《法意》等书，传播了欧洲资产阶级的思想。——第63页

〔55〕康有为（一八五八——一九二七），广东南海人。一八九五年中国在甲午战争中被日本帝国主义打败后，他联合一千三百多个在北京参加科举考试的举人联名向光绪皇帝上“万言书”，要求“变法维新”。他主张改君主专制制度为君主立宪制度。一八九八年光绪皇帝任用他和谭嗣同、梁启超等人参预政事，试图变法。后来顽固派的代表慈禧太后重揽政权，维新运动遂告失败。康、梁逃亡海外，组织保皇会，和孙中山所代表的资产阶级、小资产阶级的革命派相对立，成为反动的政治派别。康有为的著作有《新学伪经考》、《孔子改制考》、《大同书》等。——第63页

〔56〕法国大革命 指一七八九年至一七九四年在法国推翻封建专制制度、确立资本主义制度的资产阶级革命。它是各国资产阶级革命中一次规模最大、最彻底的革命。——第63、94页

〔57〕明治是日本天皇睦仁的年号。明治维新是从一八六八年起在日本明治年间发生的资产阶级性质的改革运动。这次改革虽未彻底消灭封建制度，但废除了封建割据的幕府制度，建立了统一的中央集权国家，并通过一系列措施发展资本主义，使日本很快成为资本主义国家。——第63、321页

〔58〕梁漱溟 一八九三年生，广西桂林人。当时任中国人民政治协商会议全国委员会委员。——第67页

〔59〕张伯苓（一八七六——一九五一），天津人，教育家。一九○四年在天津创办敬业中学堂（一九○七年改名南开学校）。一九一九年任南开大学校长。一九四五年后曾任国民党中央监察委员、国民党政府考试院院长等职。中华人民共和国成立时，致电周恩来总理表示祝贺。——第69页

〔60〕翁文灏（一八八九——一九七一），浙江鄞县人，地质学家。一九四八年曾任国民党政府行政院院长。不久辞职赴法。一九五一年回国，后任中国人民政治协商会议全国委员会委员、中国国民党革命委员会中央委员会常务委员。——第70、358页

〔61〕这是指一九五二年一月二十八日周恩来总理署名发布的《中央人民政府政务院关于加强老根据地工作的指示》，即本文第二部分：《大力扶植老根据地的经济和文化建设》。——第75页

〔62〕这是毛泽东给老根据地人民的题词，载一九五一年八月十一日《人民日报》。——第75页

〔63〕这里指中央人民政府内务部一九五○年十二月十一日公布的《革命烈士家属革命军人家属优待暂行条例》、《革命残废军人优待抚恤暂行条例》等。——第80页

〔64〕指国营经济，合作社经济，国家资本主义经济，私人资本主义经济和个体经济。——第82、100、108页

〔65〕司徒雷登 （一八七六——一九六二），美国人，生于中国杭州。一九四六年七月出任美国驻中国国民党政府大使。一九四九年四月南京解放后，仍然留在那里观望。同年八月离开中国。——第86页

〔66〕一九三九年十一月，苏联与芬兰因边界问题发生战争，为此，英、法两国在美国支持下组织了一支远征军拟经瑞典进攻社会主义苏联。苏联政府警告瑞典政府，希望它不要违反中立政策，以免引起不必要的纠纷。瑞典政府决定同苏联保持正常关系。一九四○年四月初，希特勒军队占领丹麦和挪威后，瑞典面临被希特勒占领的威胁。十三日，苏联政府向德国驻苏大使发表声明说，苏联不能让德国破坏瑞典中立。这个声明引起了德国政府的重视。瑞典政府对苏联这一行动表示感谢。——第89页

〔67〕沙文主义 原指资产阶级反动的本民族至上主义。十八世纪末、十九世纪初产生于法国，因法国士兵沙文狂热拥护拿破仑一世的侵略扩张政策，主张用暴力建立法兰西帝国而得名。它宣扬本民族利益高于一切，主张征服和奴役其他民族。在帝国主义时代，沙文主义成为帝国主义、霸权主义侵略其他国家和压迫其他民族的思想工具。——第91、229、440页

〔68〕镇压反革命 指一九五○年至一九五三年在全国开展的镇压反革命运动。中华人民共和国成立初期，全国各地残存着大量的土匪、恶霸、特务、反动党团骨干和反动会道门头子等反革命分子。他们进行各种破坏活动，危害人民的革命和建设事业。为了迅速建立和巩固革命秩序，根据中共中央《关于镇压反革命活动的指示》和中央人民政府公布的《中华人民共和国惩治反革命条例》，全国开展了镇压反革命运动。这次运动沉重打击了反革命残余势力，巩固了人民民主专政。——第93、132、162、204页

〔69〕王芸生（一九○一——一九八○），天津静海人。曾任天津《商报》总编辑、上海《大公报》总编辑等职。中华人民共和国成立后，任中国人民政治协商会议全国委员会常务委员、中华全国新闻工作者协会副主席。一九五二年二月九日在上海《大公报》上发表了《资产阶级有没有猖狂进攻？是我们“制造阶级斗争”吗？》一文。此文经毛泽东作了个别修改后，同年二月十三日为《人民日报》转载。——第93页

〔70〕文艺复兴 是十四世纪至十六世纪欧洲部分国家在资本主义生产关系逐渐形成的条件下，思想和文化范围内发生的反映新兴资产阶级利益和要求的大变革。十六世纪资产阶级史学家认为它是古代希腊、罗马文化艺术的复兴，所以称为“文艺复兴”。这个时期表现在科学、哲学、文学、艺术、教育方面的人文主义思想，提倡人性，反对神性；提倡人权，反对神权；提倡个性自由，反对中古的宗教桎梏，冲击了腐朽的封建文化，在当时历史上起了很大的进步作用。文艺复兴为近代文学、艺术、教育、哲学和实验科学的发展开辟了道路。——第94、354页

〔71〕美国独立战争 也称北美独立战争。一七七五年起北美十三个殖民地的人民先后进行推翻英国殖民统治、争取独立的资产阶级革命战争。一七七六年七月四日发表了《独立宣言》，正式宣告脱离英国。英国战败后，被迫在一七八三年签订《巴黎和约》，承认美国独立。——第94页

〔72〕南北战争 也称美国内战，是一八六一年至一八六五年由美国南部种植园主奴隶制与北部资产阶级雇佣劳动制之间的矛盾所引起的资产阶级民主革命战争。在战争过程中，代表北部资产阶级利益的联邦政府总统林肯颁布了《宅地法》和《解放黑奴宣言》，并采取其他民主措施，激发了工人、农民和黑人的革命斗志，因而联邦政府取得了战争的胜利。经过这次战争，美国的资本主义得到进一步的发展。——第94页

〔73〕辛亥革命 是以孙中山为首的资产阶级革命政党同盟会所领导的推翻清朝专制王朝的革命。一九一一年（辛亥年）十月十日，革命党人发动新军在湖北武昌举行起义。接着，各省热烈响应，外国帝国主义所支持的清朝反动统治迅速瓦解。一九一二年一月在南京成立了中华民国临时政府，孙中山就任临时大总统。两千多年的中国封建帝制从此结束，民主共和国的观念从此深入人心。但是资产阶级革命派力量很弱，并具有妥协性，没有能力发动广大人民的力量比较彻底地进行反帝反封建的革命。辛亥革命的成果迅即被北洋军阀袁世凯篡夺，中国仍然没有摆脱半殖民地、半封建的状态。——第94、255、290、318、354页

〔74〕“五反”指一九五二年在全国资本主义工商业中开展的反对行贿、反对偷税漏税、反对盗骗国家财产、反对偷工减料和反对盗窃经济情报的斗争。——第96、112、162、331页

〔75〕“五毒”指中华人民共和国成立初期一些资本家的行贿、偷税漏税、盗骗国家财产、偷工减料和盗窃经济情报的五种违法行为。——第96、112页

〔76〕一九五二年一月五日，周恩来在中国人民政治协商会议全国委员会常务委员会第三十四次会议上报告了正在全国范围内开展的反对贪污、反对浪费、反对官僚主义斗争和思想改造运动的情况，号召工商界人士积极参加这一运动，进行自我改造。这个报告的要点即本书《“三反”运动与民族资产阶级》一文。——第97页

〔77〕“三反”指一九五一年底至一九五二年十月在国家机关、部队和国营企业等单位中开展的反对贪污、反对浪费、反对官僚主义的斗争。——第97、112、162、331页

〔78〕陈云，一九○五年生，上海青浦人。一九五二年时是中共中央政治局委员、书记处书记、中央人民政府政务院副总理兼财政经济委员会主任。一九五六年十一月和一九六二年时是中共中央副主席、国务院副总理。——第98、233、405页

〔79〕黄炎培（一八七八——一九六五），字任之，上海川沙人。清末曾考中举人。早年加入同盟会。一九一七年在上海创办中华职业教育社。一九四○年底参与发起组织中国民主政团同盟。一九四五年底发起建立中国民主建国会。中华人民共和国成立后，历任中央人民政府政务院副总理、全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席、中国民主建国会主任委员。——第101、357页

〔80〕这是唐代初期政治家魏征说过的话，见《资治通鉴·唐太宗贞观二年》。毛泽东在《矛盾论》等著作中，曾多次引用过这句话。——第103页

〔81〕毛泽东在一九五二年和一九五三年多次表述过党在过渡时期的总路线。一九五三年六月十五日在中共中央政治局会议上第一次对过渡时期总路线作了比较完整的表述。这里引用的是毛泽东审阅周恩来一九五三年八月在全国财经工作会议上的结论时对过渡时期总路线所作的表述。一九五三年十二月，中共中央批准并转发了经毛泽东修改和审订的中共中央宣传部编写的《为动员一切力量把我国建设成为一个伟大的社会主义国家而斗争——关于党在过渡时期总路线的学习和宣传提纲》。这个提纲对过渡时期总路线作了准确的表述，即：“从中华人民共和国成立，到社会主义改造基本完成，这是一个过渡时期。党在这个过渡时期的总路线和总任务，是要在一个相当长的时期内，逐步实现国家的社会主义工业化，并逐步实现国家对农业、对手工业和对资本主义工商业的社会主义改造。这条总路线是照耀我们各项工作的灯塔，各项工作离开它，就要犯右倾或‘左’倾的错误。”——第105页

〔82〕盛丕华（一八八二——一九六一），浙江宁波人。当时任中国人民政治协商会议全国委员会常务委员、上海市副市长、上海市工商业联合会主任委员等职。——第106页

〔83〕“四马分肥” 是当时对民族资本主义企业的利润分配形式的形象的说法，指企业利润按国家所得税金、企业公积金、职工福利奖金和资方的股息红利四部分分配（参见本书第101页）。一九五六年全行业公私合营后，资方的股息红利被定息代替。——第112页

〔84〕农业生产合作社是当时我国劳动农民在中国共产党领导下自愿联合组成的集体经济组织。按照集体化程度的不同，分为初级农业生产合作社和高级农业生产合作社。初级农业生产合作社实行土地入股、统一经营；收益按土地和劳力比例分配；牲畜、农具等生产资料入股，也取得合理的代价。高级农业生产合作社，土地取消了报酬，归集体所有，牲畜、农具等生产资料作价入社，完全实行按劳分配的原则。——第112、215、264、315页

〔85〕见毛泽东《改造资本主义工商业的必经之路》（《毛泽东选集》第5卷，人民出版社1977年版，第98—100页）。——第112、114、115、116页

〔86〕三大运动 指抗美援朝、土地改革和镇压反革命运动。参见本书注26、10、68.——第112页

〔87〕思想改造 指一九五一年至一九五二年在我国知识分子中开展的思想改造学习运动。这次运动的主要内容是：组织知识分子学习历史唯物论的基本原理，学习《共同纲领》，开展批评与自我批评，清除帝国主义、封建主义和官僚资本主义的政治思想影响，划清敌我界限，建立为劳动人民服务的观点。——第112页

〔88〕指一九五三年五月二日至十一日在北京举行的中国工会第七次全国代表大会。这次大会总结了一九四八年全国第六次劳动大会以后，特别是中华人民共和国成立以后国民经济恢复时期的全国工会工作的经验，确定了有计划的经济建设时期的工会的任务是团结全国人民，积极地完成国家经济建设计划，为逐步实现国家的工业化和过渡到社会主义社会而斗争。——第115页

〔89〕指一九五四年二月六日刘少奇受中共中央政治局的委托向党的七届四中全会所作的报告。——第119页

〔90〕指中国共产党七届四中全会通过的《关于增强党的团结的决议》中提出的、要求全党高级干部遵守的六条规定。原文如下：“（一）党的团结的利益高于一切，因此应当把维护和巩固党的团结作为指导自己言论和行动的标准，即有利于党的团结的话就说，不利于党的团结的话就不说，有利于党的团结的事就做，不利于党的团结的事就不做。（二）党是工人阶级先进分子的统一的集中的组织，党的团结的唯一中心是党的中央，因此，必须把任何地区、任何部门的党的组织及其工作看作是在中央统一领导下的整个党及其工作的不可分割的一部分，反对任何派别思想、小团体习气、地方主义、山头主义和本位主义，反对任何妨碍中央统一领导、损害中央的团结和威信的言论和行动。（三）党的团结的重要保证之一是严格遵守民主集中制，严格遵守集体领导的原则，因此必须坚决反对分散主义和个人主义，反对把自己领导的地区和部门当作独立王国，反对把个人放在组织之上，反对不适当地过分地强调个人的作用，反对骄傲情绪和个人崇拜。（四）全党高级干部的重要的政治活动和政治意见应该经常向所属的党的组织报告和反映，其关系特别重大者则应直接向党中央的政治局、书记处或中央主席报告和反映；如果避开党组织和避开中央来进行个人的或小集团的政治活动，避开党的组织和避开中央来散布个人的或小集团的政治意见，这在党内就是一种非法活动，就是违反党的纪律、破坏党的团结的活动，就必须加以反对和禁止。（五）全党高级干部应根据增强党的团结的原则来检查自己的言论和行动，凡是不利于党的团结的言论和行动都必须改正。（六）对于任何有损党的团结的言论和行动应当进行批评和斗争。”——第120页

〔91〕《甲申三百年祭》是郭沫若一九四四年三月在重庆《新华日报》发表的著名史论著作。文中叙述了一六四四年李自成农民起义军进入北京以后，它的一些首领因为胜利而骄傲起来，生活腐化，进行宗派斗争，以致使这次起义在一六四五年陷于失败。一九四四年四月十二日，毛泽东在延安高级干部会议上说：“近日我们印了郭沫若论李自成的文章，也是叫同志们引为鉴戒，不要重犯胜利时骄傲的错误。”（《毛泽东选集》第3卷，人民出版社1964年版，第902页）——第123页

〔92〕遵义会议 指一九三五年一月长征途中，中共中央政治局在贵州遵义举行的扩大会议。这次会议集中讨论和纠正了军事上的错误，结束了“左”倾冒险主义在党中央的统治，确立了毛泽东在红军和党中央的领导地位，在最危急的关头挽救了红军，挽救了党。——第126、302页

〔93〕“劳卫制” 这里指一九五四年二月十一日政务院政务会议批准，同年五月至一九五八年十月在全国推行的“准备劳动与卫国”体育制度。它规定了当时全国统一的体育锻炼项目和考核标准。——第129页

〔94〕吴传玉 （一九二八——一九五四），祖籍福建石美（今属龙海县），生于印度尼西亚，中国优秀的游泳运动员。一九五一年回国。一九五三年八月在第一届国际青年友谊运动会上获得百米仰泳的第一名，在国际比赛中第一次升起中华人民共和国国旗。一九五四年赴匈牙利途中，因飞机失事遇难。——第130页

〔95〕两个教育部 指当时的高等教育部和教育部。高等教育部的职掌范围是分管全国除高等师范学校、民族学院以外的高等学校；除师范学校以外的中等专业学校，工农速成中学及有关留学生派遣、接受等事项。教育部的职掌范围是分管全国高等师范学校、民族学院、师范学校、中学、小学、幼儿园、成人初等学校、盲哑学校等。——第131页

〔96〕亚非会议 也称万隆会议，一九五五年四月十八日至二十四日在印度尼西亚万隆举行。参加会议的有缅甸、锡兰（今斯里兰卡）、印度、印度尼西亚和巴基斯坦五个发起国，以及阿富汗、柬埔寨、中华人民共和国、埃及等二十九个亚非国家。会议广泛讨论了民族主权、反殖民主义斗争、世界和平以及与会国之间的经济、文化合作等问题，发表了《亚非会议最后公报》，提出了著名的关于促进世界和平与合作的十项原则。——第146、236、274页

〔97〕日内瓦会议 指一九五四年四月二十六日至七月二十一日在瑞士日内瓦举行的讨论和平解决朝鲜问题和恢复印度支那和平问题的国际会议。中、苏、美、英、法五国参加所有两项议题的讨论，朝鲜民主主义人民共和国、南朝鲜李承晚集团及英、美、法以外的其余十二个侵朝国家参加了朝鲜问题的讨论，越南民主共和国、老挝、柬埔寨和南越保大政权参加了印度支那问题的讨论。关于朝鲜问题没有达成任何协议；关于恢复印度支那和平问题，达成了一系列协议，实现了印度支那的停战。——第148、236、274页

〔98〕科伦坡五国会议 指一九五四年四月二十八日至五月二日印度、巴基斯坦、缅甸、印度尼西亚和锡兰（今斯里兰卡）五国总理在锡兰首都科伦坡举行的会议。会议发表公报呼吁立即在印度支那实行停火，欢迎日内瓦会议通过谈判恢复印度支那的和平，并提出了召开亚非会议的问题。——第148页

〔99〕一九四五年日本投降后，法国为在印度支那重建殖民统治，先后侵入越南、柬埔寨和老挝，发动了印度支那战争。印度支那三国人民经过八年多的英勇抗战，迫使侵略者在一九五四年七月签订停战协定。同年八月实现了印度支那停战。——第148、275页

〔100〕关于恢复印度支那和平问题的协议 指一九五四年七月在日内瓦会议上达成的《关于在越南停止敌对行动的协定》、《关于在老挝停止敌对行动的协定》、《关于在柬埔寨停止敌对行动的协定》和《日内瓦会议最后宣言》等文件。协议的主要内容是：与会国尊重越南、老挝、柬埔寨的主权、独立、统一和领土完整，不干涉它们的内政；上述三国交战双万同时、全面停火；三国不参加任何军事同盟，不容许外国在它们的领土上建立军事基地；法国从印度支那撤军等。但美国没有在《日内瓦会议最后宣言》上签字，只声明美国政府将不使用武力去妨碍日内瓦协议的实施。后来美国背弃了自己的诺言，使这一协议遭到了破坏。——第148页

〔101〕指一九四五年八月六日美国第一次使用原子弹轰炸日本广岛。——第148页

〔102〕指一九五四年三月美国在中太平洋的比基尼岛附近的公海上进行氢弹试验时，使日本船员久保山爱吉得“原子病”致死。——第148页

〔103〕茂物会议 是缅甸、锡兰（今斯里兰卡）、印度、印度尼西亚和巴基斯坦五国总理继科伦坡五国会议后于一九五四年十二月二十八日至二十九日在印度尼西亚的茂物举行的第二次会议。会议发表了联合公报，决定联合发起在一九五五年召开亚非会议。公报申明：召开亚非会议的目的，在于促进各国间的友好合作和睦邻的关系；讨论与会各国的社会、经济与文化问题和关系；讨论对亚非各国人民具有特别利害关系的问题，例如有关民族主权的问题、种族主义和殖民主义的问题；讨论亚非国家和它们的人民在世界上的地位，以及它们对于促进世界和平与合作所能作出的贡献。——第152页

〔104〕和平共处五项原则 即互相尊重主权和领土完整、互不侵犯、互不干涉内政、平等互利、和平共处。参见本书《和平共处五项原则》一文及题解。——第152、244、478页

〔105〕《一九五六年到一九六七年全国农业发展纲要（草案）》是中共中央根据毛泽东的倡议提出的，一九五六年一月公布。一九五七年十月公布修正草案。一九六○年四月经第二届全国人民代表大会第二次会议通过并作为正式文件颁发。纲要全文共四十条，提出了我国农业、畜牧业、林业、渔业、副业以及农村商业、信贷、交通、邮电、广播、科学、文化、教育、卫生等方面的发展规划。关于粮食每亩平均年产量，纲要规定从一九五六年开始，在十二年内，在黄河、秦岭、白龙江、黄河（青海境内）以北地区，要达到四百斤；黄河以南、淮河以北地区，要达到五百斤；淮河、秦岭、白龙江以南地区，要达到八百斤。——第160、220、434页

〔106〕即毛泽东《大量吸收知识分子》一文（《毛泽东选集》第2卷，人民出版社1964年版，第581—583页）。——第161页

〔107〕胡风，一九○二年生，湖北蕲春人，文艺理论家和诗人。一九三三年七月在上海参加中国左翼作家联盟。中华人民共和国成立后，曾任中国作家协会理事、中国文联全国委员会委员等职。一九五五年胡风等人被错定为“反革命集团”，一九六五年胡风被判刑。一九八○年九月，中共中央发出通知并经过法律程序，为“胡风反革命集团”和胡风本人平反。一九八一年胡风任中国人民政治协商会议全国委员会常务委员、中国作家协会顾问等职。——第162页

〔108〕布尔加宁（一八九五——一九七五），当时任苏联部长会议主席。下面引用布尔加宁的话，是一九五五年七月四日他在苏联共产党中央委员会全体会议上所做《关于在工业的进一步高涨、技术的进步和生产组织的改进方面的任务》的报告中说的。——第182页

〔109〕见毛泽东《中国人民站起来了》（《毛泽东选集》第5卷，人民出版社1977年版，第6页）。——第189页

〔110〕这是毛泽东在一九五六年一月二十五日最高国务会议上讲的一段话，见同年一月二十六日《人民日报》。——第190页

〔111〕《十五贯》是根据清初戏剧家朱素臣的传奇剧本《十五贯》（又称《双熊梦》）改编的昆曲剧目。主要情节是：赌徒娄阿鼠图财杀死屠户尤葫芦，窃去铜钱十五贯，反嫁祸于尤之养女苏戍娟及身带十五贯钱的路人熊友兰；无锡知县过于执主观地断定熊、苏二人通奸杀人，将熊、苏判处死刑。苏州知府况钟奉命监斩时发现疑点，连夜去见巡抚周忱，请求缓刑复查。况亲赴现场和民间查访，终于查明了真凶，平反了冤狱。——第192、334页

〔112〕指剧中人物江南巡抚周忱。历史上的周忱（一三八一——一四五三），明宣德年间以工部右侍郎巡抚江南。为官清廉，兴利除弊，曾与况钟一起奏请减免江南重赋。——第193页

〔113〕这里指剧中人物苏州知府况钟。历史上的况钟（一三八三——一四四三），明宣德年间任苏州知府。任内抑制豪强，严惩贪官污吏。曾与周忱一起奏请减免江南重赋。——第193页

〔114〕“熊氏二难”指朱素臣著《十五贯》中所写熊家二兄弟相继遭难的情节。剧本写熊友兰、熊友蕙兄弟都为十五贯钱引起的误会而遭祸获罪，苏州知府况钟梦见双熊，疑为冤狱，后亲自查访，终于为二熊昭雪。昆曲《十五贯》在改编时，删去了有关熊友蕙的情节，剔除了梦见双熊等封建性糟粕，突出了况钟实事求是的精神和注重调查研究的作风。——第195页

〔115〕传淞 即王传淞，昆剧演员。当时是浙江昆苏剧团副团长，在《十五贯》中扮演娄阿鼠。传瑛即周传瑛，昆剧演员。当时是浙江昆苏剧团团长，在《十五贯》中扮演况钟。——第196页

〔116〕老舍（一八九九——一九六六），北京人，作家。当时任中国文学艺术界联合会副主席、中国作家协会副主席等职。曾将《十五贯》改编为京剧。——第196、296、317页

〔117〕宋景诗（一八二四——？），山东堂邑（今聊城西）人。一八六○年参加鲁西农民抗粮斗争，次年捻军进入山东时，参加白莲教起义，率领黑旗军，转战直隶（今河北）、山东边界一带。不久被清军包围，投降清钦差大臣胜保。后脱离清军，回到山东家乡一带，重举义旗。一八六五年曾参加围歼清军僧格林沁部的曹州大战，后来下落不明。根据宋景诗的事迹创作的文艺作品有京剧《宋景诗》、电影《宋景诗》。——第197页

〔118〕和平解放台湾的号召 指一九五六年一月三十日周恩来在《中国人民政治协商会议第二届全国委员会常务委员会工作报告》中提出的“为争取和平解放台湾，实现祖国的完全统一而奋斗”的号召。他代表中国人民和中国政府宣布：“凡是愿意回到大陆省亲会友的，都可以回到大陆上来。凡是愿意回到大陆来参观和学习的，也都可以到大陆上来。凡是愿意走和平解放台湾道路的，不管任何人，也不管他们过去犯过多大罪过，中国人民都将宽大对待，不究既往。凡是在和平解放台湾这个行动中立了功的，中国人民都将按照立功大小给以应得的奖励。凡是通过和平途径投向祖国的，中国人民都将在工作上给以适当的安置。”——第201页

〔119〕中美两国在日内瓦会谈 指中国和美国一九五五年八月开始在瑞士日内瓦举行的大使级会谈。双方商定会谈包括两项议程：一是双方平民回国问题，二是双方有争执的其他实际问题。前项议程在同年九月十日达成协议，后项议程一直没有达成任何协议。一九五八年九月至一九七○年二月，中美大使级会谈改在波兰首都华沙举行。——第201页

〔120〕解放战争后期和新中国成立初期，在新解放的地区，为了彻底打垮封建势力，巩固革命秩序，中国共产党领导广大军民开展了大规模的肃清土匪、特务，反对恶霸地主的斗争。一方面展开军事活动，清剿土匪，掩护群众工作；一方面发动群众，进行反恶霸斗争，摧毁反革命统治势力，建立人民民主政权，动员群众力量支援剿匪的军事行动。清匪反霸斗争为以后农村进行土地改革，作好了政治上和组织上的准备。——第204页

〔121〕为了肃清一切暗藏的反革命分子，自一九五五年六月起至一九五六年底，在全国开展了肃反运动。党政机关、团体、工矿企业、部队和学校开展的肃反运动，称作机关肃反或内部肃反；农村、街道和私营企业等方面开展的肃反运动，称作社会肃反。——第205页

〔122〕一九四三年四月中共中央决定在整顿党的作风的同时，进行一次普遍的审查干部的运动。在这次审干中，一度掀起了所谓“抢救运动”，发生了反特扩大化的严重错误。这一年八月十五日中共中央通过《关于审查干部的决定》，总结了这次审干运动的经验。这个决定提出了首长负责，自己动手，领导骨干与广大群众相结合，一般号召与个别指导相结合，调查研究，分清是非轻重，争取失足者，培养干部，教育群众等九条方针，反对“逼、供、信”的主观主义的错误方针。十月九日，毛泽东指出：“一个不杀，大部不抓，是此次反特务斗争中必须坚持的政策。”这样，就及时纠正了反特扩大化的严重错误。——第205页

〔123〕我国在第一个五年计划时期，为了便于各级主管机关对建设项目的计划、设计、施工等工作实行分级管理，按基本建设项目总投资的多少确定一个数额，这个数额称为限额。如一九五四年规定钢铁工业的投资限额为一千万元，纺织工业的投资限额为五百万元，其他各项轻工业的投资限额为三百万元至四百万元。限额以上项目，一般为国家重点建设项目。——第211页

〔124〕定息 是我国在资本主义工商业实行全行业公私合营后，对民族资本家的生产资料进行赎买的一种形式，即不论企业盈亏，统一由国家每年按照资本额发给资本家固定的利息（一般是年息百分之五）。定息从一九五六年起支付，一九六六年九月停止支付。——第215、360、398页

〔125〕定产、定购、定销 又称粮食“三定”，是我国政府在一九五五年为了进一步提高农民的生产积极性，促进农业增产，保证国家和人民对粮食的需要所采取的一项重要措施。定产就是根据田地质量和自然条件，结合经营条件，按正常年景下的单位面积常年产量评定农户的粮食产量，这是计算国家向农户购销粮食的依据。定购是从定产数量中按规定标准扣除农民的口粮、种子、饲料等用粮和实缴公粮后，对剩下的余粮按百分之八十至九十计算收购数量。一九五五年分户核定的余粮户粮食交售任务，在正常的年景下，自同年起三年不变，增产不增购。定销是对各类缺粮地区按规定标准确定统销数量。——第216页

〔126〕八大 即一九五六年九月十五日至二十七日在北京举行的中国共产党第八次全国代表大会。这次大会分析了生产资料私有制的社会主义改造基本完成以后的形势，提出了全面开展社会主义建设的任务。毛泽东致开幕词，刘少奇作政治报告，周恩来作《关于发展国民经济的第二个五年计划的建议的报告》，邓小平作《关于修改党的章程的报告》；朱德、陈云、董必武等作了重要发言。大会通过了《关于政治报告的决议》、《中国共产党章程》和《关于发展国民经济的第二个五年计划（一九五八年到一九六二年）的建议》，并选举了新的中央委员会。八大制定了正确的路线，为新时期社会主义事业的发展和党的建设指明了方向。——第229页

〔127〕邵力子（一八八二——一九六七），浙江绍兴人。当时任全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员、中国国民党革命委员会中央常务委员。——第231页

〔128〕十大关系 指一九五六年四月二十五日毛泽东在中共中央政治局扩大会议上的讲话《论十大关系》中论述的十个问题：一、重工业和轻工业、农业的关系；二、沿海工业和内地工业的关系；三、经济建设和国防建设的关系；四、国家、生产单位和生产者个人的关系；五、中央和地方的关系；六、汉族和少数民族的关系；七、党和非党的关系；八、革命和反革命的关系；九、是非关系；十、中国和外国的关系。——第231页

〔129〕三大改造 指一九五六年基本完成的国家对农业、对手工业和对资本主义工商业的社会主义改造。——第231、395页

〔130〕太平洋战争 指第二次世界大战期间反法西斯联盟国家与日本在太平洋地区进行的战争。一九四一年十二月七日晨，日本未经宣战，以强大的海、空军突然袭击美国在太平洋地区的主要海、空军基地珍珠港，使美国太平洋舰队遭到惨重损失。十二月八日，美、英对日宣战。同日，德、意对美宣战。日本军队先后侵占了东南亚的许多国家和地区以及太平洋上的一些岛屿，后来在太平洋地区各反法西斯国家武装力量的沉重打击下，不断遭到失败。一九四五年八月，日本无条件投降，战争结束。——第241页

〔131〕东土耳其斯坦 指一九三三年十一月英帝国主义在中国直接策动新疆大伊斯兰主义分子萨比提大毛拉在喀什成立的“东土耳其斯坦伊斯兰共和国”。这个政权因分裂祖国，投靠帝国主义，受到新疆各族人民的反对，一九三四年二月瓦解。——第259页

〔132〕一九一一年武昌起义后，湖北军政府提出改政体为五族共和。孙中山曾经宣传过这种思想，主张汉、满、蒙、回、藏五族一家，立于平等地位，通过五大民族平等参与国家政权，实现国家统一和民族统一。——第263页

〔133〕一九四三年蒋介石在《中国之命运》一书中，认为从民族成长的历史来说，中华民族是多数宗族融和而成的；各地的宗族，同源于一个始祖，是同一血统的大小宗支，它们在长期的历史发展过程中，由于生活的互相依赖、文化的交流和累世的婚姻关系，逐渐同化、融和为一个“中华大民族”。蒋介石在这里实质上只承认有汉族，否定少数民族的存在，把各少数民族称之为汉族的大小宗支。——第263页

〔134〕程砚秋（一九○四——一九五八），北京人，京剧表演艺术家、京剧“程派”艺术的创立者。抗日战争期间拒绝为日伪演出，致力于戏曲理论的研究和戏曲教学工作。中华人民共和国成立后，任中国戏曲研究院副院长。一九五七年加入中国共产党。——第272、296、318页

〔135〕这是一九五七年十一月十七日毛泽东在莫斯科对中国留苏学生讲话中的一句话，意思是社会主义力量超过了帝国主义力量。见同年十一月二十日《人民日报》所刊载的通讯《毛主席会见留苏学生》。——第274页

〔136〕《汉字简化方案》中的简化字从一九五六年二月一日到一九五九年七月十五日分四批推行。一九六四年，中国文字改革委员会根据国务院的批示编印了《简化字总表》，应用扩大后的简化偏旁又类推简化了一部分汉字，使简化字的总数增加到二千二百三十八个。——第280页

〔137〕李凤莲 抗日战争时期是延安的被服厂工人、劳动模范。一九五八年时在中华全国总工会工作。——第281页

〔138〕李烛尘 （一八八一——一九六八），湖南永顺人。当时任中国人民政治协商会议全国委员会常务委员、中国民主建国会副主任委员、中华全国工商业联合会副主任委员。——第281页

〔139〕注音字母 是标注汉字读音的一套音标。一九一三年由读音统一会制定，一九一八年由北洋政府教育部公布。后来国民党政府把它改名为注音符号。——第287页

〔140〕见鲁迅《且介亭杂文·门外文谈》（《鲁迅全集》第6卷，人民文学出版社1981年版，第90页）。——第290页

〔141〕鸦片战争 是一八四○年至一八四二年资本主义的英国对中国发动的侵略战争。从十八世纪末期起，英国把大量鸦片走私输入中国，毒害中国人民，并使中国白银大量外流。一八三八年底清政府派林则徐为钦差大臣去广州禁烟。一八三九年六月林则徐下令当众销毁从英、美等国不法商人手中缴获的鸦片二百三十多万斤。一八四○年，英国借口保护通商，发动侵华战争。清政府在战争中动摇妥协，只有部分军队和人民群众奋起抵抗侵略者。英军除先后在广东、福建、浙江沿海骚扰并入侵外，又攻占吴淞，闯进长江，直逼南京，迫使清政府在一八四二年八月签订了丧权辱国的《南京条约》。从此，中国逐步变成半殖民地半封建国家。——第291、354页

〔142〕清末我国邮政由英国人掌管。邮政式指英国人在邮政业务中用拉丁字母拼写中国地名时习用的一套拼写法。——第291页

〔143〕威妥玛式指英国驻中国使馆中文秘书威妥玛在一八六七年发表的汉语官话的拉丁字母拼写法。——第291页

〔144〕卢戆章（一八五四——一九二八），福建同安人，中国文字改革运动最早的提倡者之一。一八九二年发表《一目了然初阶》，提出一种拼切汉字读音的设计方案，他把这种方案称为“中国切音新字”。——第291页

〔145〕国语罗马字 即“国语罗马字拼音法式”，是用罗马字母（也叫拉丁字母）拼写汉语的方案。由“国语罗马字研究委员会”成员钱玄同、黎锦熙（当时均为国立北京师范大学教授）、赵元任（当时是清华学校国学研究院教授）等人制订。一九二六年由国语统一筹备会发表，一九二八年经国民党政府大学院（教育部）正式公布。——第291页

〔146〕拉丁化新文字 是用拉丁字母拼写汉语的方案。瞿秋白在一九二八年起任中共驻共产国际代表团团长期间，经常与当时在苏联学习的吴玉章、林伯渠等人研究中国文字改革问题，并写成了《中国拉丁化字母》的小册子。瞿秋白一九三○年回国后，吴玉章、林伯渠以原有研究成果为基础，和一些苏联语言学家一起研究制订了中国北方话拉丁化方案。一九三一年九月，旅苏华侨在海参崴召开中国新文字第一次代表大会，通过了根据上述研究成果制订的《中国汉字拉丁化的原则和规则》的方案。这一方案于一九三三至一九三四年间传到国内，被称为“拉丁化新文字”。——第291页

〔147〕陈叔老 即陈叔通（一八七六——一九六六），浙江杭州人。曾是清末翰林。参加过反对袁世凯的斗争。一九二七年后担任浙江兴业银行董事。抗日战争时期，支持抗日救亡活动。抗战胜利后，参加上海各界人民团体联合会，从事反蒋民主活动。中华人民共和国成立后，历任全国人民代表大会常务委员会副委员长，中国人民政治协商会议全国委员会副主席，中华全国工商业联合会主任委员等职。——第295、357、399页

〔148〕张文白 即张治中（一八九○——一九六九），安徽巢县人。当时任国防委员会副主席、全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员。——第296页

〔149〕戊戌变法 是一八九八年（戊戌年）发生的资产阶级性质的维新运动。当时，中国面临被帝国主义列强瓜分的严重危机。康有为、梁启超、谭嗣同等人，在清朝光绪皇帝的支持下，企图通过自上而下的变法维新，逐步地在中国推行地主阶级和资产阶级联合统治的君主立宪制度，发展民族资本主义，以挽救民族危亡。但是，当时还没有强有力的资产阶级，以慈德太后为首的顽固派坚决反对变法维新。在宣布变法三个多月以后，慈禧太后发动政变，幽禁光绪皇帝，杀害谭嗣同等六人，变法遭到失败。——第297页

〔150〕顾颉刚（一八九三——一九八），江苏吴县人，历史学家。当时是中国人民政治协商会议全国委员会委员、历史研究所研究员。——第298页

〔151〕八旗 这里指八旗兵。清代常备军之一。它是分别以正黄、镶黄、正白、镇白、正红、镶红、正蓝、镶蓝军旗为标志的八支军队的统称。每旗设都统一人、副都统二人为正副统帅。八旗兵后又分满洲八旗、蒙古八旗、汉军八旗。——第298页

〔152〕绿营 指绿营兵，也称绿旗兵。它是清朝政府接明代军队建制建立的常备军。因这些由汉人组成的军队使用绿色军旗，所以称绿营。——第298页

〔153〕湘军 是曾国藩为镇压太平天国农民革命运动，于一八五二年在其家乡湖南招募、训练的封建军阀武装。因士兵和将领多是湘乡人，所以称湘军。——第298页

〔154〕淮军 是李鸿章为镇压太平天国农民革命运动，在曾国藩的支持下，于一八六一年将其家乡安徽的地主武装按湘军的组织形式加以改编组成的封建军阀武装。因士兵多是淮南一带人，所以称淮军。——第298页

〔155〕新军 指一八九四年（甲午年）中日战争后清朝政府仿照西方资本主义国家军制编练的新式陆军。——第298页

〔156〕一九五七年十月，苏联发射了第一颗人造地球卫星，这是当时世界上最新的科学成就。我国在一九五八年“大跃进”运动中，有人用放“卫星”来比喻各行各业出现的“高产指标”和“最新成就”。但是当时在浮夸风的影响下，不少部门和单位宣布的“高产指标”和“新技术”、“新产品”是不切实际和不合标准的。——第298页

〔157〕黄埔军校 指设在广州黄埔的陆军军官学校，它是一九二四年孙中山在中国共产党和苏联的帮助下创办的。中国共产党曾派周恩来、恽代英、肖楚女、聂荣臻、熊雄等到该校工作。学员中有很多共产党员和共青团员。一九二七年蒋介石背叛革命以前，这是一所国共合作的学校。——第298页

〔158〕三二○事变 即中山舰事件，是第一次国内革命战争时期蒋介石为排挤共产党人而制造的反共阴谋事件。一九二六年三月十八日，蒋介石指使其亲信以黄埔军校驻省办事处的名义，向海军局代理局长李之龙（当时是共产党员）传达命令，要他调中山舰到黄埔待命。当中山舰抵达黄埔后，他们又造谣说中山舰要炮轰黄埔军校、共产党要赶走蒋介石。三月二十日，蒋介石借口共产党阴谋暴动，逮捕了李之龙，扣留了中山舰，并派兵包围省港罢工委员会。随后又强迫共产党员从国民革命军第一军以及黄埔军校中撤出。由于当时中共中央的主要领导人陈独秀、张国焘等人妥协退让，不敢反击蒋介石，遂使他的阴谋得逞。——第298、304页

〔159〕一九四○年十月，国民党军事当局强令长江南北和黄河以南坚持抗日的新四军、八路军全部开赴黄河以北。中国共产党一方面驳斥这一无理要求，一方面从维护抗日大局出发答应将安徽南部的新四军部队调到江北。一九四一年一月，皖南的新四军九千余人，取得国民党当局的同意，向江北转移。部队行至安徽径县茂林地区，遭到七八万国民党军队的突然袭击。经七昼夜浴血奋战，弹尽粮绝，除小部分突围外，大部壮烈牺牲。军长叶挺被扣，副军长项英遇害。这就是震惊中外的皖南事变。——第298页

〔160〕陈炯明 （一八七八——一九三三），广东海丰人。一九一七年护法军政府成立后，任援闽粤军总司令。一九二○年，任广东省省长兼粤军总司令。一九二二年发动反对孙中山的军事政变。一九二五年二月至三月，为了巩固广东革命根据地，国共合作组织的以黄埔军校学生为骨干的革命军从广州出发东征陈炯明，打败了盘踞在东江的陈炯明部的主力。同年十月至十一月，革命军再次东征，最后消灭了陈炯明的军队。——第299、304页

〔161〕梁思成（一九○一——一九七二），广东新会人，建筑学家。清末维新派著名人物梁启超之子。当时任清华大学土木建筑系主任、中国人民政治协商会议常务委员会委员。一九五九年加入中国共产党。——第299页

〔162〕康同璧（一八八一——一九六九），广东南海人，清末维新派著名人物康有为之女。当时任中国人民政治协商会议全国委员会委员。——第299页

〔163〕维新派 指中日甲午战争前后主张向西方学习、实行维新变法的资产阶级政治派别，主要代表人物有康有为、梁启超、谭嗣同、严复等。——第299页

〔164〕一九五八年九月二十八日，中国史学会和中国科学院历史研究所第三所（今中国社会科学院近代史研究所），在北京联合举行学术讨论会，纪念戊戌变法六十周年。会议由范文澜主持。参加会议的有北京的史学工作者和吴玉章、李济深、黄炎培、陈叔通、陈垣、潘梓年、章士钊、康同璧、梁思成等六十余人。参加会议的同志在发言中谈到，一八九八年的戊戌变法是改良主义运动，但在当时代表着中国社会的发展趋势，具有进步的意义，是中国近代史上的一次思想解放运动。——第299页

〔165〕共产国际 又称第三国际，一九一九年三月在列宁领导下成立。一九二二年中国共产党参加共产国际，成为它的一个支部。一九四三年五月，共产国际执行委员会主席团通过决定，提议解散共产国际，同年六月共产国际正式宣布解散。——第300页

〔166〕李立三（一八九九——一九六七），湖南醴陵人。一九二一年加入中国共产党，是中国工人运动的主要领导人之一。他在担负中共中央领导工作期间，于一九三○年六月至九月犯了“左”倾冒险主义错误。后来他接受了党对他所犯错误的批评，认识和改正了错误，在党的第七次、第八次全国代表大会上继续被选为中央委员。——第301页

〔167〕三次“左”倾 错误指一九二七年十一月至一九二八年四月以瞿秋白为代表的“左”倾盲动主义错误，一九三○年六月至九月以李立三为代表的“左”倾冒险主义错误。——第302页

〔168〕江亢虎（一八八三——一九五四），江西弋阳人。早年游历日本和欧洲。一九一一年辛亥革命后，他标榜社会主义，在上海创办中国社会党。一九一三年，该党被袁世凯政府解散。一九二一年六月他以社会党人身份列席共产国际第三次代表大会。一九二四年，他为了投靠北洋军阀，重新组织中国社会党，次年又改组为中国新社会民主党。一九二七年，当北伐战争节节胜利时，他不得不把这个党解散。抗日战争时期，他投身敌伪政府，堕落为汉奸。——第303页

〔169〕黄介民（一八八三——一九五六），江西清江人。早年加入同盟会。一九一九年在上海任中华工业协会总干事，参加过反帝爱国活动。一九二七年国民党反动派叛变革命后，他不满蒋介石的独裁统治，辞去国民党江西省党部候补监委等职务，从事司法和教育工作。中华人民共和国成立后，曾任中国国民党革命委员会中央团结委员会委员、江西省人民政府监察厅副厅长。——第303页

〔170〕戴季陶（一八九一——一九四九），原籍浙江吴兴，生于四川广汉。早年加入中国同盟会。五四运动期间，在上海主编《星期评论》周刊，对社会主义和劳工问题作过一些研究。一九二四年任中国国民党中央执行委员。第一次国共合作期间，歪曲孙中山学说的革命内容，反对共产党，反对工农运动，为蒋介石发动反革命政变进行思想上的准备。一九二七年国民党反动派叛变革命后，继续追随蒋介石，历任国民党政府委员、考试院院长等职。——第303页

〔171〕吴佩孚（一八七四——一九三九），山东蓬莱人，北洋军阀直系首领之一。一九一八年反对皖系首领段祺瑞的“武力统一”政策，主张南北议和。五四运动时，曾以“爱国军人”姿态，通电反对在巴黎和约上签字。一九二○年联合奉系推翻段祺瑞政府，随后曾与苏俄政府建立联系。一九二二年将奉系逐出关外后，支持曹锟控制北京政府。一九二三年残酷镇压京汉铁路工人运动。一九二六年所部在湖北被北伐军击溃。——第303页

〔172〕三大 指一九二三年六月十二日至二十日在广州举行的中国共产党第三次全国代表大会。这次大会的中心议题是讨论同孙中山领导的中国国民党建立革命统一战线的问题。大会正确地估计了孙中山反对帝国主义和封建军阀的民主主义的立场，以及使国民党改造成为工人、农民、小资产阶级、民族资产阶级革命联盟的可能性，批评了怀疑国共合作的“左”倾观点和主张“一切工作归国民党”的右倾观点，并决定共产党员以个人身份加入国民党，同时保持共产党在政治上和组织上的独立性。这次大会为国共合作进行第一次国内革命战争作了必要的准备。——第303页

〔173〕张国焘（一八九七——一九七九），江西萍乡人。一九二一年参加中国共产党第一次全国代表大会。在党内曾先后被选为中央委员、政治局委员、政治局常委。一九三一年任中共鄂豫皖中央分局书记、中华苏维埃共和国临时中央政府副主席等职。一九三五年六月红军第一、第四方面军在四川懋功地区会师后任红军总政治委员。他反对中央关于红军北上的决定，进行分裂党和红军的活动，另立“中央”。一九三六年六月他被迫取消第二“中央”，随后与红军第二、第四方面军一起北上，十二月到达陕北。一九三八年四月背叛革命，投入国民党特务集团，随即被开除党籍。一九七九年死于加拿大。——第304页

〔174〕一九二五年孙中山去世后，国民党右派公开进行反革命分裂活动。十一月二十三日，邹鲁、谢持、林森等十余人，在北京西山碧云寺召开会议，反对孙中山的联俄、联共、扶助农工三大政策，通过反共、反苏、反对国共合作等议案。随后，他们在上海另立“国民党中央党部”，在北京等地设立地方党部，从事反共反人民活动。这批人被称为西山会议派。——第304页

〔175〕一九二四年，英帝国主义用大量金钱、军火支持广州大买办陈廉伯所控制的反革命武装组织商团，企图颠覆广东革命政府。八月，广东革命政府扣留了陈廉伯为组织武装叛乱而偷运的军火。陈指使商团向孙中山请愿，并在全省各地煽动罢市。十月十日，广州群众为庆祝辛亥革命举行游行，遭到商团枪击。参加游行的十六个团体成立了“工农兵学革命大同盟”，发表宣言，坚决要求解散商团，严惩凶手。在中国共产党、广大工农群众和国民党左派的影响和支持下，孙中山采取措施，调集黄埔学生军、工农武装及其他军队，在十五日消灭了这一反革命武装。——第304页

〔176〕独立团 指一九二五年冬在广东肇庆成立的以共产党人叶挺为团长的国民革命军第四军独立团。该团以共产党员和共青团员为骨干，在北伐战争中。英勇善战，战功卓著。——第304页

〔177〕指毛泽东的《湖南农民运动考察报告》一文。一九二七年二月，毛泽东曾将这篇文章送中共中央机关刊物《向导》，但是陈独秀等右倾领导者不予发表。三月五日，这篇文章的一部分首先发表在中共湖南省委机关刊物《战士》第35、36期合刊上，其余部分在第38、39期上续登。三月十二日，《向导》发表了此文的一部分，当时在党中央主管宣传工作的瞿秋白主张全文刊完，被陈独秀等拒绝。四月，瞿秋白将此文交中共在武汉开办的长江书局以《湖南农民革命》为书名出版单行本，并为此书写了序言。——第304页

〔178〕指一九二七年七月十五日汪精卫在武汉发动的反革命政变。这年四月十二日蒋介石在上海发动反革命政变后，以汪精卫为首的武汉国民政府也日趋反动。六月十日，汪精卫同冯玉祥举行郑州会议，策划反共；十九日，冯又同蒋介石举行徐州会议，密谋蒋汪合作，共同反共。中国共产党在以陈独秀为代表的右倾投降主义指导思想的影响下，对国民党的阴谋不加戒备，没有准备应付突然事变。七月十五日，汪精卫公开与共产党决裂，随后封闭工会、农会等革命团体，大批屠杀共产党员和革命群众。至此，第一次国内革命战争遭到失败。——第304页

〔179〕鲍罗廷（一八八四——一九五一），第一次国共合作时是苏联政府派到广州革命政府的代表和国民党的政治顾问。一九二三年十月到广州，一九二七年七月武汉政府叛变后回国。——第306页

〔180〕叶挺（一八九六——一九四六），广东惠阳人。一九二五年加入中国共产党。同年冬任国民革命军第四军独立团团长。叶挺的部队指南昌起义前以独立团为基础组成的国民革命军第十一军二十四师和由独立团一部分骨干编成的第四军二十五师。叶挺当时任第二十四师师长。——第306页

〔181〕南昌起义 是一九二七年八月一日中国共产党为了反击以蒋介石、汪精卫为代表的反革命势力而在江西南昌发动的武装起义。起义部队在中共前敌委员会书记周恩来和贺龙、叶挺、朱德、刘伯承等领导下，经过激烈战斗，占领了南昌城。这次起义打响了中国人民武装反抗国民党反动派的第一枪。从此，开始了中国共产党独立领导革命武装斗争的新时期。起义部队撤离南昌后南下广东。十月初在潮汕一带遇到优势敌军的围攻而失败。保存下来的起义部队，一部分到达海陆丰地区，继续坚持斗争；另一部分在朱德、陈毅等率领下，转移到湘南，发动了湘南起义，一九二八年四月到达井冈山和毛泽东领导的工农革命军会合。——第306页

〔182〕罗米那兹 （一八九八——一九三四），苏联人。一九二七年七月下旬作为共产国际代表来中国。此时，武汉政府已经叛变革命，他参加了中共八七会议的领导工作。第306页。183八七会议指一九二七年八月七日中共中央在汉口召开的紧急会议。这次会议总结了第一次国内革命战争失败的经验教训，结束了陈独秀右倾投降主义在中央的统治，确定了土地革命和武装反抗国民党反动派统治的总方针，并把发动农民举行秋收起义作为当时党的最主要的任务。但是，这次会议在反对右倾错误的时候，不认识应当根据各地不同的情况，组织恰当的反攻或必要的策略上的退却，并在组织上开始了宗派主义的过火的党内斗争，因而为后来的“左”倾错误开辟了道路。关于对八七会议的分析，参见周恩来《关于党的“六大”的研究》（《周恩来选集》上卷，人民出版社1980年版，第171—172页）。——第306页

〔183）八七会议 是一九二七年八月七日中共中央在汉口召开的紧急会议。这次会议总结了第一次国内革命战争失败的经验教训，结束了陈独秀右倾投降主义在中央的统治，确定了土地革命和武装反抗国民党反动派统治的总方针，并把发动农民举行秋收起义作为当时党的最主要的任务。但是，这次会议在反对右倾错误的时候，不认识应当根据各地不同的情况，组织恰当的反攻或必要的策略上的退却，并在组织上开始了宗派主义的过火的党内斗争，因而为后来的“左”倾错误开辟了道路。关于对八七会议的分析，参见周恩来《关于党的“六大”的研究》（《周恩来选集》上卷，人民出版社1980年版，第171-172页）——第306页

〔184〕张太雷（一八九八——一九二七），江苏常州人。一九二○年在北京参加共产主义小组。一九二五年在中国共产党第四次全国代表大会上当选为候补中央委员，并任苏联顾问鲍罗廷的翻译、中共广东区委常委和宣传部长。一九二七年五月在党的第五次全国代表大会上当选为中央委员。同年八月出席党的八七会议，被选为中共临时中央政治局候补委员，后任中共广东省委书记，十二月领导广州起义时牺牲。——第306页

〔185〕指斯大林一九二七年七月二十八日在苏联《真理报》上发表的《时事问题简评》、七月二十九日至八月九日在联共（布）中央委员会和中央监察委员会联席全会上的演说以及九月二十七日在共产国际执行委员会主席团和共产国际监察委员会联席会议上的演说等。见《斯大林全集》第9卷，人民出版社1954年版，第298—325页；《斯大林全集》第10卷，人民出版社1954年版，第3—84页、第132—143页。——第306页

〔186〕谭平山（一八八六——一九五六），广东高明人。一九二○年组织广州共产主义小组。在中国共产党的第三、第四、第五次全国代表大会上当选为中央委员。第一次国内革命战争期间，历任中国国民党中央执行委员会常务委员、中央组织部长、农民部长和武汉国民政府委员等职。一九二七年南昌起义时，是革命委员会主席团成员。同年十一月，在中共临时中央政治局扩大会议上被当时的“左”倾领导者开除党籍，后参与组织中国国民党临时行动委员会（即第三党）。抗日战争时期，反对蒋介石的卖国独裁政策。一九四八年参与组织中国国民党革命委员会。中华人民共和国成立后，曾任中央人民政府委员。——第307页

〔187〕广州暴动 是一九二七年大革命失败后，中国共产党在广州发动的反击国民党反革命势力的武装起义。十二月十一日，在中共广东省委书记张太雷和叶挺、恽代英、叶剑英、杨殷、周文雍、聂荣臻等领导下，驻广州的国民革命军第四军教导团联合广州工人、市郊农民，经过激战，占领了市内绝大部分地区。起义胜利后成立了广州苏维埃政府。十二日，国民党反动军队在帝国主义战舰炮火的掩护下，向广州反扑。张太雷在战斗中壮烈牺牲。起义部队十三日被迫撤出广州。撤出的起义部队，分别与东江、湖南一带的革命武装结合，继续坚持武装斗争。——第307页

〔188〕六大 指一九二八年六月十八日至七月十一日在莫斯科举行的中国共产党第六次全国代表大会。会上，瞿秋白作了《中国革命与共产党》的政治报告，周恩来作了组织问题和军事问题的报告，刘伯承作了军事问题的补充报告。会议通过了政治、军事、组织等问题的决议案，选举了中国共产党第六届中央委员会。这次大会肯定了中国社会是半殖民地半封建社会，中国当时的革命依然是资产阶级民主革命，指出了当时的政治形势是在两个革命高潮之间和革命发展的不平衡，党在当时的总任务不是进攻，不是组织起义，而是争取群众。会议在批判右倾机会主义的同时，特别指出了当时党内最主要的危险倾向是脱离群众的盲动主义、军事冒险主义和命令主义。这次大会的主要方面是正确的，但也有缺点和错误。它对于中间阶级的两面性和反动势力的内部矛盾缺乏正确的估计和适当的政策；对于大革命失败后党所需要的策略上的有秩序的退却，对于农村根据地的重要性和民主革命的长期性，也缺乏必要的认识。——第307页

〔189〕向忠发（一八七九——一九三一），湖北汉川人。一九二七年七月大革命失败后，任中国共产党驻共产国际代表。一九二八年党的六大后，任中共中央总书记。一九三一年六月二十二日被捕叛变，二十四日被国民党枪杀。——第307页

〔190〕布哈林（一八八八——一九三八），一九○六年加入俄国社会民主工党。十月革命后曾任联共（布）中央政治局委员、共产国际执行委员会委员。一九二九年十一月联共（布）中央全会决定撤销其中央政治局委员的职务。一九三七年被开除党籍，次年被处死。——第307页

〔191〕陶里亚蒂（一八九三——一九六四），曾任意大利共产党总书记，一九二八年任共产国际执行委员会主席团委员。——第307页

〔192〕米夫（一九○一——一九三八），苏联人。一九二八年任共产国际东方部副部长兼莫斯科中山大学校长。一九三○年冬到上海任共产国际驻中国代表。在党的六届四中全会上，由于他的支持，王明掌握了党的最高领导权。——第307页

〔193〕瞿秋白（一八九九——一九三五），江苏常州人。一九二二年加入中国共产党，是党的早期领导人之一。在一九二七年大革命失败后的紧要关头，主持召开八七会议。会后任中共临时中央政治局常委，主持中央工作。一九二七年十一月至一九二八年四月犯过“左”倾盲动主义错误。一九三○年九月主持召开党的六届三中全会，纠正李立三“左”倾冒险主义的错误。在一九三一年一月党的六届四中全会上，受到王明“左”倾教条主义宗派主义分子的打击，被排斥于党中央领导机关之外。此后，在上海同鲁迅合作从事革命文化运动。一九三四年到中央革命根据地，任中华苏维埃共和国临时中央政府教育人民委员。一九三五年二月从江西往福建转移途中被国民党逮捕，六月十八日在福建长汀就义。——第307页

〔194〕王明 即陈绍禹（一九○四——一九七四），安徽金寨人。一九二五年加入中国共产党。曾任中共中央委员、政治局委员、政治局常委、长江局书记。他是一九三一年一月党的六届四中全会至一九三五年一月遵义会议前这一时期中国共产党内“左”倾冒险主义错误的主要代表。抗日战争初期，又犯了右倾投降主义错误。他长期拒绝党的批评和帮助。六十年代后堕落成为中国革命的叛徒。——第308、425页

〔195〕改组派 是二十年代末期到三十年代初期国民党内部的一个派系。一九二七年七月武汉政府实行反共后，武汉汪精卫的国民党和南京蒋介石的国民党合流。后来，汪精卫、陈公博、顾孟余等不满蒋介石独揽权力，于一九二八年底在上海成立“中国国民党改组同志会”，形成了国民党中的“改组派”。——第308页

〔196〕指一九三○年共产国际东方部作出的《中国共产党的最近组织任务》、《中国共产党在职工运动中的任务（草案）》、《关于中国农民问题》、《关于中国苏维埃问题》、《关于中国苏区土地农民问题（草案）》、《关于中国苏维埃政权的经济政策（草案）》等六项决议案。——第308页

〔197〕何孟雄（一八九八——一九三一），湖南酃县人。中国早期北方职工运动的组织者之一，曾创建京绥铁路工会。一九二七年大革命失败后，曾任中国共产党江苏省委员会委员、省委农民运动委员会秘书，抵制过李立三和王明的“左”倾错误。一九三一年在上海被国民党反动派逮捕，牺牲于龙华。——第309页

〔198〕指一九三○年党的六届三中全会以后王明写的《两条路线》。这是一本宣扬“左”倾教条主义的小册子，一九三一年二月在上海出版，一九三二年在莫斯科再版，书名改作《为中共更加布尔塞维克化而斗争》。——第309页

〔199〕陈昌浩（一九○六——一九六七），湖北汉阳人。当时任中共鄂豫皖中央分局委员。——第310页

〔200〕宁都会议 是中共苏区中央局一九三二年十月在江西宁都召开的会议。这次会议错误地批评了毛泽东等提出的向敌人统治力量较弱、党和群众力量较强的赣东北发展的正确主张，而要求红军去夺取中心城市，争取江西首先胜利。会后，调毛泽东做政府工作，接着又撤销了他的红军第一方面军总政治委员的职务。——第310页

〔201〕罗明，一九○一年生，广东大埔人。一九三三年任中国共产党福建省委代理书记时，认为党在闽西上杭、永定等边缘地区的条件比较困难，党的政策应当不同于根据地的巩固地区。当时党内“左”倾错误领导者把这种意见说成是“悲观失望的”、“机会主义的、取消主义的逃跑退却路线”，并开展了所谓“反对罗明路线的斗争”。——第310页

〔202〕邓 指邓小平，一九○四年生，四川广安人。当时任中共会（昌）、寻（乌）、安（远）中心县委书记。毛指毛泽覃（一九○五——一九三五），湖南湘潭人。当时任苏区中央局秘书长。谢指谢唯俊（一九○七——一九三五），湖南耒阳人。当时任江西省苏维埃政府委员、江西省军区政治部主任、中共乐安中心县委书记等职。古指古柏（一九○六——一九三五），江西寻乌人。当时任总前委秘书长、江西省苏维埃政府委员等职。他们在敌强我弱的形势下，执行正确的防御路线，被党内“左”倾错误领导者指斥为“罗明路线在江西的创造者”，受到了错误的打击。——第310页

〔203〕李德（一九○○——一九七四），又名华夫，德国人，原名奥托·布劳恩。一九三二年，受共产国际派遣来中国。一九三三年十月到中央革命根据地，担任中国共产党的军事顾问，实际上掌握红军的最高指挥权。第五次反“围剿”期间，他同当时党内“左”倾错误领导者在军事指挥上实行了一系列错误的战略战术，使红军受到重大损失。遵义会议前夕，他被取消了红军的最高指挥权。一九三九年，李德离开中国。——第310页

〔204〕博古 即秦邦宪（一九○七——一九四六），江苏无锡人。一九三一年九月至一九三五年一月，曾是中共临时中央主要负责人、中共中央政治局委员。自一九三三年九月开始的第五次反“围剿”起，掌握了红军的最高领导权，在军事指挥上犯了一系列错误，使红军受到极大损失。遵义会议后，被撤销了红军的最高领导权。抗日战争初期，在党中央的长江局、南方局工作。一九四一年以后，在延安创办和主持《解放日报》和新华通讯社。一九四五年，在党的第七次全国代表大会上继续当选为中央委员。一九四六年四月因飞机失事遇难。——第310页

〔205〕季米特洛夫 （一八八二——一九四九），保加利亚人。一九二一年任工会国际中央理事会理事，一九三五年至一九四三年任共产国际执行委员会总书记。一九四五年十一月回国后，任保加利亚共产党总书记和部长会议主席。——第311页

〔206〕西安事变 也称“双十二事变”。在日本帝国主义加紧侵略中国，要把中国变为它的殖民地的危急形势下，以张学良将军为首的国民党东北军和以杨虎城将军为首的国民党第十七路军，在中国共产党的抗日民族统一战线政策和全国人民抗日运动的影响和推动下，要求蒋介石停止内战，一致抗日。蒋介石拒绝了这个要求，并亲自赶到西安积极部署“剿共”。一九三六年十二月十二日，张、杨联合行动，在西安附近的临潼扣押了蒋介石，这就是著名的西安事变。事变发生后，国民党内以何应钦为首的亲日派准备乘机发动大规模内战，牺牲蒋介石以便取而代之。中国共产党坚持和平解决西安事变的方针，并经过中共代表周恩来以及博古（秦邦宪）、叶剑英等的艰苦工作，终于同张学良、杨虎城等一道使西安事变和平解决，促进了抗日民族统一战线的形成。——第311页

〔207〕第二次王明路线 指抗日战争初期以王明为代表的右倾投降主义错误。一九三七年十二月，从苏联回国不久的王明在中共中央政治局会议上作了《如何继续全国抗战与争取抗战胜利？》的报告，系统地提出了右倾投降主义的主张。随后，在任中共中央长江局书记时，又擅自发表一些包含有原则错误的意见、宣言、决议和文章。他相信国民党超过相信共产党，对国民党的反人民政策让步，不敢放手发动群众斗争，不敢放手发展人民军队，不敢在日本占领区扩大抗日根据地，主张“一切经过统一战线”、“一切服从统一战线”，将抗日战争的领导权送给国民党。由于以毛泽东为代表的正确路线已经在全党占统治地位，王明的这些错误只在部分地区一度得到推行。一九三八年九月至十一月，中共中央召开了扩大的六届六中全会，进一步确立了全党独立自主地领导抗日武装斗争的方针和政策。——第311页

〔208〕见《毛泽东选集》第2卷，人民出版社1964年版，第543—548页。——第312页

〔209〕毛泽东这篇文章原题为《调查工作》，写于一九三○年五月，一九六一年三月曾在中国共产党内印发。一九六四年收入《毛泽东著作选读》时，题目改为《反对本本主义》。——第313页

〔210〕“五风”指“大跃进”和人民公社化运动中发生的共产风、浮夸风、命令风、干部特殊风和对生产瞎指挥风。——第313页

〔211〕指毛泽东主席一九六一年五月六日在上海写给李井泉和陈正人的信（见《毛泽东书信选集》，人民出版社1983年版，第580—581页）。信中要求各中央局、各省、市、自治区党委第一书记在半个月内，下苦功去农村认真做调查研究工作。李井泉当时任中共中央政治局委员、中共中央西南局第一书记。陈正人当时任国务院农林办公室副主任、农业机械工业部部长，在四川作农村调查。——第314页

〔212〕《一九五六年到一九六七年全国农业发展纲要》规定：对农村中缺乏劳动力、生活没有依靠的鳏寡孤独的社员，生产队在生活上给以适当的照顾，做到保吃、保穿、保烧（燃料）、保教（儿童和少年）、保葬。享受这“五保”的社员户，称为五保户。——第315页

〔213〕陈总 即陈毅（一九○一——一九七二），四川乐至人。当时任中共中央政治局委员、中国人民政治协商会议全国委员会副主席、国务院副总理兼外交部部长。一九六一年出席扩大的日内瓦会议，任中国政府代表团团长。——第315、329、399页

〔214〕日内瓦会议，这里指一九六一年五月十六日至一九六二年七月二十三日举行的扩大的日内瓦会议。一九五四年日内瓦会议后，美国违反日内瓦协议，对老挝进行干涉和侵略，并在一九六○年挑起老挝内战。为了和平解决老挝问题，中、苏、美、英、法、老挝、柬埔寨、越南民主共和国、南越（以上为一九五四年日内瓦会议参加者）、印度、缅甸、加拿大、波兰和泰国举行了这次会议。会议最后签署了《关于老挝中立的宣言》和《关于老挝中立的宣言的议定书》，确认尊重老挝的主权、独立、中立、统一、领土完整和不干涉其内政的原则。——第315页

〔215〕许明（一九一九——一九六六），河北沧县人。当时任国务院总理办公室副主任。——第315页

〔216〕嵯峨浩，一九一四年生，原籍日本，溥杰的夫人。——第316页

〔217〕溥杰 即爱新觉罗·溥杰，一九○七年生，清朝末代皇帝溥仪的胞弟。一九三○年至一九四四年先后三次留学日本，曾任伪满宫廷侍从武官等职。一九四五年日本投降后被苏军俘虏，一九五○年八月被移交给中华人民共和国政府。一九五九年十二月被特赦释放。后任中国人民政治协商会议全国委员会文史资料研究委员会专员、第六届全国人民代表大会常务委员。——第316、357页

〔218〕溥仪 即爱新觉罗·溥仪（一九○六——一九六七），清朝末代皇帝。一九一二年中华民国建立后被迫退位。一九三二年任日本帝国主义一手策划的伪满洲国“执政”，一九三四年改称“满洲帝国皇帝”。一九四五年日本投降后被苏军俘虏，一九五○年八月被移交给中华人民共和国政府。一九五九年十二月被特赦释放。一九六四年任中国人民政治协商会议全国委员会委员。——第316、345页

〔219〕嵯峨尚子，日本人，嵯峨浩的母亲。——第316页

〔220〕宫下明治，日本人。一九四五年日本帝国主义投降以前，曾是清东陵守备队的守备人员。嵯峨尚子访华时，他是随行人员。——第316页

〔221〕嫮生 是博杰和嵯峨浩的女儿，已入日本籍。——第316页

〔222〕载涛（一八八七——一九七○），清末曾任军谘大臣。一九六一年时是中国人民政治协商会议全国委员会委员。——第317、357页

〔223〕西园寺 即西园寺公一，一九○六年生，日本政界元老西园寺公望公爵之孙。曾任日本参议员、《日曜新闻》编辑、维也纳世界和平理事会书记处书记。一九五八年至一九七○年任亚洲及太平洋区域和平联络委员会副秘书长，常驻中国。——第317页

〔224〕干子 即町田干子，嵯峨浩的妹妹。——第317页。

〔225〕贝勒 是清代皇室的封爵称号。清代的爵位分亲王、郡王、贝勒、贝子、国公、将军六级。——第317页

〔226〕“满洲国”是一九三一年日本帝国主义侵占中国东北后扶植的傀儡政权。一九三二年三月在长春成立，一九三四年三月改称“满洲帝国”。一九四五年随着中国人民抗日战争的胜利而被摧毁。——第317页

〔227〕齐白石（一八六四——一九五七），湖南湘潭人，画家。中华人民共和国成立后，曾任北京中国画院名誉院长、中国美术家协会主席。——第318页

〔228〕陈半丁（一八七六——一九七○），浙江绍兴人，画家。中华人民共和国成立后，曾任北京中国画院副院长、中国人民政治协商会议全国委员会委员。——第318页

〔229〕于非闇（一八八九——一九五九），北京人，画家。中华人民共和国成立后，曾任中国画研究会副会长、北京中国画院副院长。——第318页

〔230〕贺龙（一八九六——一九六九），湖南桑植人。当时任中共中央政治局委员、国务院副总理兼体育运动委员会主任。——第318页

〔231〕查理一世（一六○○——一六四九），英国斯图亚特王朝国王。一六四○年爆发英国资产阶级革命，一六四二年起他发动内战，两度战败。一六四九年被国会判处死刑。——第318页

〔232〕路易十六（一七五四——一七九三），法国国王。一七八九年法国资产阶级革命爆发后，他表面上接受立宪政体，暗地勾结外敌，纠集王党，企图镇压革命。一七九二年被废黜，次年一月被处死。——第318页

〔233〕威廉二世（一八五九——一九四一），德意志帝国皇帝、普鲁士国王。一九一八年十一月德国革命爆发后逃亡荷兰。——第319页

〔234〕埃及的王室指埃及法鲁克王朝。一九五二年七月二十三日埃及爆发了由自由军官组织发动的革命。二十六日国王法鲁克被废黜，当天他逃往国外。——第319页

〔235〕指溥仪的《我的前半生》一书。这本书溥杰曾帮助整理过。——第319页

〔236〕这里指一八九四年所发生的中日战争，也称甲午战争。见本书注34.——第321页

〔237〕一九三一年九月十八日，日本驻在中国东北境内的关东军进攻沈阳。这次事件被称为九一八事变。随后，日军向辽宁、吉林、黑龙江三省全面进犯。驻守沈阳和东北其他地方的中国军队，执行蒋介石的不抵抗的命令，使日军得以迅速占领了这三个省。——第321页

〔238〕大谷莹润（一八九○——一九七三），曾任日本众议院议员、参议院议员、法务委员会委员。一九五三年起任中国人在日殉难者慰灵实行委员会委员长，一九六一年五月率领日本“中国殉难烈士名单捧持代表团”访问中国。——第321页

〔239〕土肥原 即土肥原贤二（一八八三——一九四八），日本战犯。早年被派到中国进行特务活动。曾任日本在沈阳的特务机关长，参与策动日本侵占我国东北的九一八事变和策划建立伪满洲国的阴谋活动。其后任日本航空总监、驻新加坡的第七方面军司令官和日本军事训练总监。日本投降后被捕，一九四八年被远东国际军事法庭判处绞刑。——第321页

〔240〕冈村宁次（一八八四——一九六六），一九三二年任日本上海派遣军副参谋长，参加侵犯上海的战争。一九三七年至一九四五年，历任日军侵华第十一军、华北方面军、第六方面军司令官和中国派遣军总司令官。在一九四五年八月延安公布的日本战犯名单中，被列为首要战犯。解放战争期间曾充当蒋介石的秘密军事顾问。一九四九年一月被国民党政府宣判“无罪”，释放回国。——第321页

〔241〕东条英机（一八八四——一九四八），日本战犯。九一八事变后历任日本关东军宪兵司令官、关东军参谋长。一九四○年至一九四一年任日本陆军大臣，积极主张扩大侵华战争和准备对美英的战争。一九四一年至一九四四年担任内阁首相期间，发动了太平洋战争，使日本帝国主义侵略战争的范围从中国扩大到太平洋和东南亚地区。日本投降后被捕，一九四八年被远东国际军事法庭判处绞刑。——第321页

〔242〕板垣征次郎（一八八五——一九四八），日本战犯。曾参与策动侵略中国的九一八事变，历任日本关东军参谋长、陆军大臣、中国派遣军参谋长、驻朝鲜日军司令官、驻新加坡的日本第七方面军司令官。日本投降后被捕，一九四八年被远东国际军事法庭判处绞刑。——第321页

〔243〕华族 指除皇族外有爵位的日本贵族。——第322页

〔244〕远藤三郎，一八九三年生，第二次世界大战期间曾任日本关东军副参谋长、陆军航空本部总务部长。自五十年代起，曾多次访华。——第322页

〔245〕辻政信，一九○二年生，第二次世界大战期间先后在我国东北、马来亚、菲律宾、缅甸、泰国指挥日本侵略军作战。战后曾当选为众议员和参议员。一九五七年曾来华访问。一九六一年四月由泰国至老挝考察途中失踪。——第322页

〔246〕高碕达之助（一八八五——一九六四），第二次世界大战期间曾任伪满洲国政府经济顾问、满洲重工业开发公司总裁。战后多次当选为众议员和参议员，并先后任国务大臣和通商产业大臣。他积极推进中日两国民间贸易，曾任日中综合贸易联合协议会会长，一九六二年同我国廖承志签订发展日中两国民间贸易的备忘录。——第322页

〔247〕久原房之助（一八六九——一九六五），曾任日本邮政大臣，政友会总裁。第二次世界大战后，作为日中邦交调整国民会议代表积极参加恢复中日邦交活动。一九五五年任日本“恢复日中、日苏邦交国民会议”会长，并率代表团访问我国。——第322页

〔248〕指一九五九年五月三日周恩来邀请文艺界中的部分全国人大代表和政协全国委员会委员，以及北京的一部分文艺界人士，在中南海紫光阁座谈时所作的《关于文化艺术工作两条腿走路的问题》的讲话。见周恩来《关于文艺工作的三次讲话》，人民出版社1979年版，第1—5页。——第324页

〔249〕指一九五七年开展的反对资产阶级右派分子的斗争。一九五七年四月，中共中央决定在全党进行一次反对官僚主义、宗派主义和主观主义的整风运动。极少数资产阶级右派分子乘机向党和新生的社会主义制度进攻，妄图取代共产党的领导。六月，党中央发出指示，决定对右派进攻实行反击。当时对极少数资产阶级右派分子的进攻进行反击是必要的，但在斗争中犯了严重的扩大化的错误。一九七八年，中共中央决定对被划为右派分子的人进行复查，把错划的改正过来。——第327、361页

〔250〕“五子登科”原指五代后周人窦禹钧五个儿子相继都考中进士（参见《宋史·窦仪传》）。这里借用这个词来说明当时在文艺工作中存在的套框子、抓辫子、挖根子、戴帽子、打棍子等错误做法。——第328页

〔251〕李维汉（一八九六——一九八四），湖南长沙人。当时任中共中央统战部部长、全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席。他在一九六一年第十一期《红旗》杂志上发表了题为《统一战线是中国人民争取胜利的一个法宝》的文章。——第335页

〔252〕参见本书注297.——第335页

〔253〕周扬，一九○八年生，湖南益阳人。当时任中共中央宣传部副部长、中国文学艺术界联合会副主席和中国作家协会副主席。——第336页

〔254〕“的笃班”是越剧形成初期的表演形式。它是清末在浙江嵊县一带的山歌小调基础上发展起来的。演唱时用一个竹节笃鼓、一副檀板伴奏，几个人帮腔伴唱。因角色从“的、笃”声中出场，所以有这个称呼。——第338页

〔255〕绍兴大班 是绍剧的旧称，又称“绍兴乱弹”。明末清初形成于浙江绍兴，后流行于浙江、上海一带。——第338页

〔256〕陈云在一九五九年十一月至一九六一年六月对评弹和其他曲艺发表过多次谈话（现已收入《陈云同志关于评弹的谈话和通信》一书中），指出当时的曲艺创作和演出存在着强调了政治一面，忽略了文化娱乐一面的偏向。他还指出广大群众在劳动之后喜欢听一些轻松愉快的东西，思想教育的目的要通过艺术手段来达到。——第338页

〔257〕梅兰芳（一八九四——一九六一），原籍江苏泰州，生于北京，京剧表演艺术家，京剧“梅派”艺术的创立者。当时任中国京剧院院长、中国戏曲学院院长、中国文学艺术界联合会副主席、中国戏剧家协会副主席、中国人民政治协商会议全国委员会常务委员。一九五九年加入中国共产党。——第341页

〔258〕聂荣臻，一八九九年生，四川江津人。当时任国务院副总理兼科学技术委员会主任。——第342页

〔259〕太平天国时代指一八五一年至一八六四年洪秀全、杨秀清等人领导的反对清朝封建统治的农民革命战争的时代。——第344页

〔260〕章行老 即章士钊（一八八一——一九七三），字行严，湖南长沙人。曾任北京大学教授、北洋政府司法总长兼教育总长等职。中华人民共和国成立后，任中国人民政治协商会议全国委员会常务委员、全国人民代表大会常务委员会委员、中央文史研究馆馆长。——第345页

〔261〕见《续资治通鉴长编·宋太祖开宝八年》。——第345页

〔262〕斯坦尼斯拉夫斯基（一八六三——一九三八），苏联演员、导演和戏剧理论家。著有《我的艺术生活》和《演员自我修养》等。他的戏剧理论概称为“斯坦尼斯拉夫斯基体系”。——第348页

〔263〕魏征（五八○——六四三），唐初政治家。唐太宗在位时，任谏议大夫和秘书监等职。他敢于直言进谏，说过：“兼听则明，偏信则暗。”——第349页

〔264〕在一九五八年开始的“大跃进”过程中，由于“左”倾思想的影响，曾把一些坚持实事求是、反对浮夸的人，以及一些所谓具有资产阶级学术观点的人都作为“右倾保守思想”的反面人物，作为“资产阶级白旗”加以批判、斗争甚至处分。当时把这种作法叫做“拔白旗”。一九六二年四月，中共中央发出通知，要求为在“拔白旗”、“反右倾”等运动中被错误地批判和处分的人进行甄别平反。——第350、400页

〔265〕郭老 即郭沫若（一八九二——一九七八），四川乐山人。当时任全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席、中国科学院院长等职。——第355、473页

〔266〕范文澜（一八九三——一九六九），浙江绍兴人。当时任中共中央候补委员、中国科学院哲学社会科学部委员、中国近代史研究所所长。——第355页

〔267〕我国封建社会传统教育以“天地君亲师”五者为人类至尊，所以并举表示崇敬的意思。——第356页

〔268〕无政府主义 是十九世纪中叶出现于欧洲的一种小资产阶级思潮。主要代表人物有法国的蒲鲁东、俄国的巴枯宁和克鲁泡特金等。它否认任何国家和政权，否认任何权力和权威，鼓吹绝对自由、极端民主，主张建立一个“无命令、无权力、无服从、无制裁”的无政府状态的社会。“五四”时期，无政府主义思想在中国青年中曾有过较大的影响。一些地方先后出现了无政府主义的小团体。最初它们也表现过某些反帝反封建的意愿，随着马克思主义的传播，特别是中国共产党的成立，一些曾经具有无政府主义思想的青年转而信奉科学社会主义，无政府主义的团体则愈来愈趋于反动。——第356页

〔269〕觉悟社 是一九一九年九月周恩来等在天津组织的进步青年学生团体。成员有邓颖超、郭隆真、马骏、刘清扬等二十余人。主要活动是出版《觉悟》杂志，讨论研究新思潮，抨击孔孟之道，积极领导青年学生的爱国运动，反对帝国主义和封建军阀。一九二○年冬，觉悟社社员分散各地，社的活动无形停顿。以后，它的主要成员大部分加入了中国共产党。——第356页

〔270〕邓颖超，一九○四年生，河南光山人。一九一九年五四运动时，在天津和周恩来等一起组织觉悟社。下面引用邓颖超的一段话，是一九四九年她回答《中国青年》杂志记者提问时说的。参见一九四九年五月《中国青年》第七期上的邓颖超《五四运动的回忆》一文。——第356页

〔271〕基尔特社会主义 也称行会社会主义（基尔特是英文“行会”一词的音译），是二十世纪初英国工人运动中出现的一种资产阶级改良主义思潮。主要代表人物是潘蒂、柯尔等。他们主张一个社会应设立两个平行的组织：一个是由工人、工程师等按行业联合组成的产业基尔特，领导和管理生产，一个是作为消费者的组织的国家，负责产品分配和保证全民消费。他们幻想等到基尔特发展到包括全体人民时，就可以和平地代替资本主义国家，从而实现社会主义。——第357页

〔272〕费边社会主义 是以英国费边社的主张为代表的资产阶级改良主义思潮。费边社是英国资产阶级知识分子一八八四年创立的团体，以善于等待时机、实行拖延缓进战术著称的古罗马统帅费边命名。其主要代表人物有维伯夫妇、肖伯纳等。他们以为用温和缓进的办法，通过细小的改良就能使资本主义制度逐步过渡到社会主义。——第357页

〔273〕刘清扬（一八九四——一九七七），天津人。一九二一年在法国勤工俭学时加入中国共产党。一九二七年大革命失败后脱离共产党。一九三一年后从事抗日救亡运动。一九四四年加入中国民主同盟。一九四八年进入华北解放区。中华人民共和国成立后，历任中国人民政治协商会议全国委员会常务委员、中国民主同盟中央常务委员、中华全国妇女联合会副主席、中国红十字会总会副会长。一九六一年重新加入中国共产党。——第357页

〔274〕张申府，一八九三年生，河北献县人。一九二○年去法国、德国留学。一九二一年加入中国共产党。一九二四年任广东大学教授兼黄埔军校政治部副主任。一九二五年脱离共产党。一九四二年加入中国民主政团同盟（一九四四年改称中国民主同盟），任常务委员。中华人民共和国成立后，任北京图书馆研究员、中国人民政治协商会议全国委员会委员。——第357页

〔275〕罗素（一八七二——一九七○），英国唯心主义哲学家、逻辑学家。一九二○年至一九二一年曾来中国讲学，在旧中国学术界有相当影响。——第357页

〔276〕费洛依德（一八五六——一九三九），奥地利心理学家、精神分析学派创始人。——第357页

〔277〕爱因斯坦（一八七九——一九五五），犹太人，出生于德国乌尔姆城，是著名的物理学家。他创建的相对论是现代物理学的理论基础之一。——第357页

〔278〕沈衡老 即沈钧儒（一八七五——一九六三），号衡山，浙江嘉兴人。清末曾考中进士。参加过辛亥革命和反对北洋军阀的斗争，后在上海任律师。抗战前组织上海文化界救国会和全国各界救国联合会。抗战期间，倡议组织中国民主政团同盟（后改称中国民主同盟）。抗战胜利后，任中国人民救国会主席，积极参加争取和平民主的斗争，反对国民党的内战政策。中华人民共和国成立后，曾任中央人民政府委员、全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席、最高人民法院院长、中国民主同盟中央主席。——第357页

〔279〕董老 即董必武（一八八六——一九七五），湖北黄安（今红安）人。清末曾考中秀才。他早年是同盟会会员，参加了辛亥革命和反对北洋军阀的斗争。在俄国十月革命和中国五四运动之后，积极参加了中国共产党的创建工作，出席中国共产党第一次全国代表大会。一九六二年时是中华人民共和国副主席。——第357页

〔280〕李根源（一八七九——一九六五），云南腾越（今腾冲）人。一九○五年加入同盟会。辛亥革命后任云南省军政府军政部总长兼参议院议长，在一九一八年护法战争中被推为驻粤滇军总司令。一九二三年在北洋政府农商总长任内兼署过国务总理。——第358页

〔281〕胡适（一八九一——一九六二），安徽绩溪人。早年留学美国。一九一七年回国，任北京大学教授，宣扬实用主义哲学。五四新文化运动时，主张文学改革，提倡白话文。一九一九年七月发表《多研究些问题，少谈些“主义”》，公开反对马克思主义。随后追随蒋介石，反对人民革命运动。一九三八年任国民党政府驻美国大使。一九四六年任北京大学校长。一九四九年去美国，后到台湾。——第358页

〔282〕见列宁《“关于用自由平等口号欺骗人民”出版序言》（《列宁全集》第29卷，人民出版社1956年版，第343—344页）。——第358页

〔283〕定股 是指资本主义工商业实行公私合营时，对原来私营企业的资产和负债，根据公平合理、实事求是的原则，进行清理、估价，以核定私股股额。——第360页

〔284〕毛泽东在一九五七年四月三十日和民主党派负责人、无党派民主人士谈话中以及后来的一些场合讲到知识分子问题时，曾引用“皮之不存，毛将焉附”（参见《左传·僖公十四年》）和“梁上君子”（参见《后汉书·陈寔传》）作比喻，说明在生产资料私有制的社会主义改造基本完成以后，从旧社会过来的知识分子所依附的经济基础那几张旧“皮”已经不存在了，因此他们不能不依附在公有制这张新“皮”上，即站在无产阶级方面，而不能象“梁上君子”（原意指躲藏在梁上的小偷，这里是借用）那样，上不着天，下不着地。——第363页

〔285〕科学工作十四条 即一九六一年六月国家科学技术委员会党组和中国科学院党组提出、同年七月中共中央批准试行的《关于自然科学研究机构当前工作的十四条意见（草案）》。中央批准这个草案的批语中指出：“做好知识分子工作，很关紧要。”“近几年来，有不少的同志，在对待知识、对待知识分子的问题上，有一些片面的认识，简单粗暴的现象也有所滋长，必须引起严重的注意，以端正方向，正确地贯彻执行党的政策。”草案就正确理解对自然科学工作者的红与专的要求，正确贯彻执行百花齐放、百家争鸣的方针和理论联系实际的原则，明确科学研究机构的根本任务（出成果，出人才），保持科学研究工作的相对稳定，保证科学研究工作的时间，改进研究机构中党的领导方法等问题，作出了一系列具体的政策规定。中央认为这个文件的精神对于一切有知识分子工作的部门和单位都是适用的。——第364、375页

〔286〕商等教育六十条 指一九六一年九月中共中央原则批准的《中华人民共和国教育部直属高等学校暂行工作条例（草案）》，全文共六十条。条例草案总结了一九五八年后三年多高等教育工作的经验和教训，针对当时学校教学质量降低，忽视知识分子作用以及劳动过多等主要问题，规定了高等学校必须以教学为主，努力提高教学质量；正确执行党的知识分子政策和百花齐放、百家争鸣的方针；做好总务工作，保证教学和生活的物质条件；以及改进党的领导方法和领导作风，加强思想政治工作等。——第364、375页

〔287〕工矿企业七十条 即一九六一年九月中共中央制定的《国营工业企业工作条例（草案）》，全文共有七十条。一九五八年“大跃进”后，由于许多企业没有实行严格的责任制，不讲究经济核算，工资、奖励制度上存在平均主义，以及党委包揽企业的日常行政事务等等，相当普遍地出现了生产秩序混乱，瞎指挥、乱操作，设备损坏严重，经济效果很差等问题。针对这些情况，工业七十条草案明确规定了国营工业企业的性质和基本任务，要求建立和健全必要的责任制和各项规章制度，强调计划管理、按劳分配、企业经济效果和职工物质利益等项原则。这个条例草案的讨论和试行，对于总结国营工业企业管理工作的经验，贯彻执行当时提出的调整、巩固、充实、提高的方针，促进我国工业的恢复和发展，起到了积极的作用。——第364页

〔288〕文艺方面也提出了几个初稿，指《关于当前文学艺术工作若干问题的意见（草案）》（简称“文艺八条”）的初稿及《关于剧院（团）工作条例（修正草案）》（简称“剧院（团）十条”）、《关于加强电影艺术片创作和生产领导的意见（草案）》（简称“电影三十二条”）。从五十年代后期起，在政治、经济领域“左”倾错误的影响下，文艺工作也产生了不少缺点和错误，一些文艺领导部门、文艺工作单位和领导文艺工作的党员干部，没有正确执行“百花齐放、百家争鸣”的方针，没有很好地贯彻党的知识分子政策，对一些文学创作和艺术活动进行了简单粗暴的批评、限制和不适当的干涉。为纠正这些偏向，在党中央以及周恩来的直接领导下，中共中央宣传部、文化部和全国文联作了大量调查研究工作，由中宣部起草了《关于当前文学艺术工作的意见（草案）》（简称“文艺十条”），文化部起草了“剧院（团）十条”和“电影三十二条”。“文艺十条”经过充分讨论修改，最后改定为“文艺八条”，于一九六二年四月三十日由中共中央批转，以文化部党组和全国文联党组名义正式下达全国。文艺八条的主要内容是：进一步贯彻执行“百花齐放、百家争鸣”的方针；努力提高创作质量；批判地继承民族文化遗产和吸收外国文化；正确地开展文艺批评；保证创作时间，注意劳逸结合；培养优秀人才，奖励优秀创作；加强团结，继续改造；改进领导方法和领导作风。“剧院（团）十条”和“电影三十二条”没有形成正式文件，只作为草案，分别于一九六一年八月八日和十一月十三日印发各省、市、自治区文化局及有关艺术单位征求意见并先予试行。这三个文艺文件的贯彻，对促进我国社会主义文艺事业的繁荣和健康发展起了积极作用。——第364页

〔289〕参见本书注297.——第370页

〔290〕农村人民公社工作条例草案六十条 指一九六一年三月中共中央制定的《农村人民公社工作条例（草案）》，全文共六十条。条例草案针对人民公社内部严重存在的队与队、社员与社员之间的平均主义，在纠正社、队规模偏大，公社对下级管得太多太死，民主制度和经营管理制度不健全等方面，作了比较系统的规定。同年五六月间，中共中央又对这个草案作了修改，制定了供讨论和试行用的《农村人民公社工作条例（修正草案）》，进一步规定取消分配上的供给制部分，停办公共食堂。一九六二年九月二十七日，中共八届十中全会正式通过了《农村人民公社工作条例（修正草案）》。人民公社六十条的贯彻执行，对恢复农村经济起了重要的作用。——第73、434页

〔291〕国营工业企业工作条例草案，参见本书注287.手工业工作条例草案指一九六一年六月中共中央制定的《关于城乡手工业若干政策问题的规定（试行草案）》，全文共三十五条。一九五八年“大跃进”后，由于手工业盲目过渡到国营工业和公社工业，并改变生产方向，造成大批手工业者改行转业，许多日用小商品减产、停产，供应十分紧张。针对这种情况，草案规定我国手工业应有全民、集体和个体三种所有制，以集体所有制为主；手工业者必须归队；生产经营方式要灵活多样；工资制度应贯彻执行“按劳分配，多劳多得”原则，以及供产销要统筹安排等。——第373页

〔292〕为了加强对物资的管理，做好物资供需的平衡，保证经济建设的顺利进行和市场稳定，国家按各种物资对国计民生的重要程度，分三类管理，即由国家统一分配的物资、中央各主管部门分配的物资和地方管理的物资。根据商品对国计民生的重要程度，国家把商品也分一、二、三类管理。地方管理的物资和第三类商品称三类物资。这类物资品种繁多，生产分散，使用面广，主要是通过市场调节产、供、销之间的关系。——第382页

〔293〕“六条标准”是毛泽东在一九五七年《关于正确处理人民内部矛盾的问题》中提出的。原文是：“在我国人民的政治生活中，应当怎样来判断我们的言论和行动的是非呢？我们以为，根据我国的宪法的原则，根据我国最大多数人民的意志和我国各党派历次宣布的共同的政治主张，这种标准可以大致规定如下：（一）有利于团结全国各族人民，而不是分裂人民；（二）有利于社会主义改造和社会主义建设，而不是不利于社会主义改造和社会主义建设；（三）有利于巩固人民民主专政，而不是破坏或者削弱这个专政；（四）有利于巩固民主集中制，而不是破坏或者削弱这个制度；（五）有利于巩固共产党的领导，而不是摆脱或者削弱这种领导；（六）有利于社会主义的国际团结和全世界爱好和平人民的国际团结，而不是有损于这些团结。这六条标准中，最重要的是社会主义道路和党的领导两条。”——第389页

〔294〕胡先骕（一八九四——一九六八），江西新建人，植物学家。当时是中国科学院植物研究所研究员，应邀列席中国人民政治协商会议第三届全国委员会第三次会议。——第390页

〔295〕张际春（一九○○——一九六八），湖南宜章人。当时任国务院文教办公室主任、中共中央宣传部副部长。——第400页

〔296〕这里指一九六二年一月十一日至二月七日中共中央在北京举行的扩大的中央工作会议。参加会议的有中央、各中央局、各省市自治区党委及地委、县委、重要厂矿企业党委和部队的负责干部共七千多人，所以又称七千人大会。会上刘少奇代表中共中央所作的报告，初步总结了一九五八年“大跃进”以来工作中的经验和教训，分析了工作中的主要缺点错误，指出全党当时的主要任务是做好调整工作。毛泽东在会上作了重要讲话，着重指出要健全民主集中制，在党内、党外充分发扬民主；要在总结正反两方面的经验的基础上，加深对社会主义建设规律的认识。对前几年工作中的缺点和错误，毛泽东承担了责任，作了自我批评。——第403页

〔297〕三面红旗 指“鼓足干劲、力争上游、多快好省地建设社会主义”的总路线、“大跃进”和人民公社。一九五八年五月中共八大二次会议通过的社会主义建设总路线反映了广大人民群众要求改变我国经济文化落后状况的普遍愿望，但是忽视了客观的经济规律。在总路线提出后，没有经过认真的调查研究和试点，就轻率地在全国发动了“大跃进”运动和农村人民公社化运动，以高指标、瞎指挥、浮夸风和“共产风”为主要标志的“左”倾错误严重地泛滥开来，打乱了正常的经济建设秩序，浪费了巨大的人力和资源，造成了国民经济比例的严重失调。这是我国国民经济在一九五九年到一九六一年发生严重困难的主要原因。当时由于党还没有从根本的指导思想上总结经验教训，所以党的文件中都还使用“高举三面红旗”的提法。——第403页

〔298〕指一九六二年二月二十一日至二十三日在北京中南海西楼召开的中共中央政治局常委扩大会议。刘少奇主持了这次会议。会议讨论了财政、金融、市场以及整个经济形势的问题，认为当时财政经济的困难很严重，估计当年的国家预算有很大的赤字。陈云在会上作了关于目前财政经济情况和克服困难的若干办法的讲话。会议一致同意陈云讲话的精神，认为在国民经济的调整阶段主要是恢复经济，要全党集中力量增加农业生产和日用品生产，保证市场供应，制止通货膨胀，坚决缩短基本建设战线。这次会议对扭转当时财政经济状况的被动局面起了重要作用。——第405页

〔299〕姚依林，一九一七年生，安徽贵池人。当时任商业部部长、国务院财贸办公室副主任。——第406页

〔300〕雷锋（一九四○——一九六二），湖南长沙县简家塘（今属望城）人。一九六○年参加中国人民解放军，同年加入中国共产党。一九六一年是中国人民解放军沈阳部队工程兵某部运输连班长。一九六二年因公殉职。他全心全意为人民服务，是在毛泽东思想哺育下成长起来的卓越的共产主义战士。一九六三年三月五日，毛泽东发出“向雷锋同志学习”的号召，随后在全国广泛开展了学习雷锋的群众运动。——第417页

〔301〕指一九六三年三月一日中共中央发布的《关于厉行增产节约和反对贪污盗窃、反对投机倒把、反对铺张浪费、反对分散主义、反对官僚主义运动的指示》。——第422页

〔302〕指毛泽东一九六三年五月在中共中央《关于目前农村工作中若干问题的决定（草案）》（即前十条）中写的一段话。一九六五年收入《毛泽东著作选读》〔甲种本〕时，题为《人的正确思想是从那里来的？》。——第423页

〔303〕马歇尔（一八八○——一九五九），美国民主党人。第二次世界大战期间，曾任美国陆军参谋长。一九四五年十二月被美国总统杜鲁门派任驻华特使，一九四六年一月同国民党代表张群（后为张治中）、共产党代表周恩来组成军事三人小组，他以“调处”为名，参与国共谈判，力图维护国民党反动派的统治地位。一九四六年八月宣布“调处”失败，不久返回美国。——第424页

〔304〕廖鲁言（一九一三——一九七二），江苏南京人。一九六三年时是农业部部长。——第424页

〔305〕高岗（一九○五——一九五四），陕西横山人。曾任中共中央政治局委员、中共中央东北局书记、中央人民政府副主席。一九五三年调中央任国家计划委员会主席后，积极进行反党分裂活动。一九五四年被揭露。一九五五年三月中国共产党全国代表会议通过决议，开除他的党籍。——第425页

〔306〕指当时国务院总理、副总理及国务院七十三个直属机关的主要领导干部。——第426页

〔307〕一九六○年黄河三门峡水利枢纽工程大坝建成蓄水后，发现泥沙淤积严重，威胁上游一些地方及水库本身的安全。为了增加枢纽工程的泄流排沙能力，减轻水库淤积，有关部门提议：在大坝左岸打两条泄流排沙隧洞，把八条发电引水钢管中的四条改成泄流排沙道。这就是后来被批准实施的二洞四管方案。——第436页

〔308〕从“我们不能走世界各国技术发展的老路”起的这一段话是毛泽东在修改周恩来这个报告的草稿时增写的。——第441页

〔309〕林大夫 即林巧稚（一九○一——一九八三），福建厦门人，妇产科专家。当时任中国医学科学院副院长、全国人民代表大会常务委员会委员。——第443页

〔310〕傅连暲（一八九四——一九六八），福建长汀人。当时任卫生部副部长、中国人民解放军总后勤部卫生部副部长、中华医学会会长、中国人民政治协商会议全国委员会常务委员。——第443页

〔311〕蒲辅周（一八八八——一九七五），四川梓潼人。当时任中医研究院副院长、中国人民政治协商会议全国委员会常务委员。——第445页

〔312〕一九六二年十一月，周恩来在一次会议上谈到林业问题时提出：“林业的经营一定要越伐越多，越多越代，青山常在，永续作业。”后来，他这一思想发展为以营林为基础，采育结合，实现青山常在，永续利用，越采越多，越采越好的林业建设的指导思想。——第446页

〔313〕四旁 指村旁、宅旁、路旁、水旁。——第446页

〔314〕从六十年代初起，周恩来针对林业生产中重采伐、轻育林的错误作法多次指出，长此下去，林业生产在几十年后就要出现生产中断的危险，我们将会犯“吃祖宗饭、造子孙孽”的历史错误。——第446页

〔315〕梁老 指梁希（一八八三——一九五八），浙江吴兴（今湖州）人，林学家。中华人民共和国成立后，曾任林业部部长。——第446页

〔316〕前方 指林区和林业生产第一线，后方指林业的领导机关。——第447页

〔317〕北方八省 是指长江以北的河南、山东、河北、山西、陕西以及湖北、安徽、江苏等省。——第447页

〔318〕宋庆龄（一八九三——一九八一），广东文昌人。当时任中华人民共和国副主席。郭沫若（一八九二——一九七八），四川乐山人。当时任全国人民代表大会常务委员会副委员长、中国科学院院长。章士钊（一八八一——一九七三），湖南长沙人。当时任全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会委员、中央文史研究馆馆长。程潜（一八八二——一九六八），湖南醴陵人。当时任全国人民代表大会常务委员会副委员长、国防委员会副主席、中国人民政治协商会议全国委员会常务委员、中国国民党革命委员会中央副主席。何香凝（一八七八——一九七二），广东南海人。当时任全国人民代表大会常务委员会副委员长、中国国民党革命委员会中央主席、中华全国妇女联合会名誉主席。傅作义（一八九五——一九七四），山西临猗人。当时任中国人民政治协商会议全国委员会副主席、国防委员会副主席、水利电力部部长。张治中（一八九○——一九六九），安徽巢县人。当时任全国人民代表大会常务委员会副委员长、国防委员会副主席、中国人民政治协商会议全国委员会常务委员、中国国民党革命委员会中央副主席。邵力子（一八八二——一九六七），浙江绍兴人。当时任全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员、中国国民党革命委员会中央常务委员。蒋光鼐（一八八七——一九六七），广东东莞人。当时任纺织工业部部长、中国国民党革命委员会中央常务委员。蔡廷锴（一八九二——一九六八），广东罗定人。当时任中国人民政治协商会议全国委员会副主席、国防委员会副主席、全国人民代表大会常务委员会委员、中国国民党革命委员会中央副主席。沙千里（一九○一——一九八二），上海人。当时任粮食部部长、中华全国工商业联合会副主任委员。张奚若（一八八九——一九七三），陕西朝邑（今大荔）人。当时任对外文化联络委员会主任、中国人民外交学会会长、中国人民政治协商会议全国委员会常务委员。——第450页

〔319〕这里所说的副委员长，指全国人民代表大会常务委员会副委员长；副主席，指中华人民共和国副主席；政副，指中国人民政治协商会议全国委员会副主席；国副，指国务院副总理；两高，指最高人民法院院长和最高人民检察院检察长。——第451页

〔320〕李宗仁（一八九一——一九六九），广西临桂人，原为国民党桂系首领。一九四八年四月任国民党政府副总统，一九四九年一月任代总统。国民党政权崩溃后去美国。一九六五年七月回到北京。——第451页

〔321〕指宋庆龄和她的弟弟宋子文、宋子良、宋子安及姐姐宋蔼龄、妹妹宋美龄。——第451页

〔322〕李葆华，一九○九年生，河北乐亭人。当时任中共安徽省委第一书记。——第452页

〔323〕李任之（一九一九——一九八三），广东东莞人。当时任中共安徽省委书记处书记、安徽省副省长。——第452页

〔324〕陶铸（一九○八——一九六九），湖南祁阳人。一九六六年十一月时是中共中央政治局常务委员、国务院副总理。后遭受林彪、江青反革命集团迫害，一九六七年一月起被监禁。——第452、454页

〔325〕刘澜涛，一九一○年生，陕西米脂人。当时任中共中央西北局第一书记。一九三一年，刘澜涛被国民党反动派逮捕，判刑后监禁在北平军人反省院。一九三六年，在全国抗日救亡运动高涨的形势下，中共中央北方局为了开展工作，解决缺乏干部的问题，报请党中央批准，决定被捕同志履行手续后出反省院。这样出反省院的共有刘澜涛等六十一人。对此，中央早已有过结论，没有当作问题。“文化大革命”初期，康生、江青伙同林彪等人为了篡党夺权的需要，到处支持一些学校的红卫兵组织揪斗这批老党员。一九六七年三月中共中央发出文件，错误地将这六十一人定为“叛徒集团”。粉碎“四人帮”后，一九七八年中共中央为这一大错案进行了平反。——第452页

〔326〕九大 即一九六九年四月一日至二十四日在北京举行的中国共产党第九次全国代表大会。这次会议使“文化大革命”的错误理论和实践合法化，加强了林彪、江青、康生等人在党中央的地位，在思想上、政治上和组织上的指导方针都是错误的。——第453、464页

〔327〕王思茂，一九一三年生，江西永新人。当时任新疆维吾尔自治区革命委员会副主任、新疆军区第一政治委员。——第453页

〔328〕徐海东（一九○○——一九七○），湖北大悟人。曾任红二十五军军长、红十五军团军团长。一九六九年时是中共中央委员、中共中央军委委员、中华人民共和国国防委员会委员。——第453页

〔329〕邓初民（一八八九——一九八一），湖北石首人。当时任中国民主同盟中央副主席、全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员。——第454页

〔330〕华罗庚，一九一○年生，江苏金坛人，数学家。当时任中国科学院副院长、中国科学院数学研究所所长、中国科学技术大学副校长、全国人民代表大会常务委员会委员。——第455页

〔331〕西尧 即刘西尧，一九一六年生，湖南长沙人。一九七○年时是周恩来总理派往中国科学院的联络员，一九七二年时是国务院科教组组长。——第455、473页

〔332〕“文化大革命”期间，在“左”的思想指导下，以贯彻一九六六年五月七日毛泽东给林彪的信中关于党政机关干部也要学农、学工的指示为名，把干部集中下放劳动的场所称为“五七”干校。林彪、江青反革命集团利用它对一大批干部进行劳动惩罚和迫害。粉碎“四人帮”后，各地“五七”干校陆续停办。——第455、472页

〔333〕张霖之（一九○八——一九六七），河北南宫人。一九五七年起，任煤炭工业部部长。“文化大革命”期间被林彪、江青反革命集团迫害致死。——第455页

〔334〕指当时根据中共中央通知派往北京矿业学院领导该校工作的“工人、解放军毛泽东思想宣传队”。——第455页

〔335〕戚本禹，一九三一年生，山东威海人。“文化大革命”初期是中央文化革命小组成员，积极参与江青反革命集团的犯罪活动。一九六八年一月十三日被关押。一九八三年十一月，因反革命罪被判处有期徒刑十八年，剥夺政治权利四年。——第455页

〔336〕刘建章，一九一○年生，河北景县人。一九五四年起任铁道部副部长，“文化大革命”期间遭受林彪、江青反革命集团迫害，被关押。——第456页

〔337〕先念，即李先念，一九○九年生，湖北黄安（今红安）人。当时任中共中央政治局委员、国务院副总理。——第456、460页

〔338〕登奎，即纪登奎，一九二三年生，山西武乡人。当时任中共中央政治局候补委员。——第456页

〔339〕肖华，一九一六年生，江西兴国人。一九六四年起任中国人民解放军总政治部主任。因受林彪、江青反革命集团的迫害，一九六七年十二月至一九七四年国庆节前夕被关押。——第457、460页

〔340〕李力群，一九二一年生，江苏宿迁人。当时是国务院科教组工作人员。——第457页

〔341〕候宝林，一九一七年生，北京人，相声表演艺术家。“文化大革命”期间遭受迫害，被批判、斗争。——第457页

〔342〕商震（一八八七——一九七八），浙江绍兴人，国民党元老。抗战胜利后，由于不满蒋介石的卖国内战政策和反动统治，一九四九年辞去了国民党政府驻日本代表团团长的职务，留后日本。一九七四年九月正在国内参观访问。——第457页

〔343〕刘志坚，一九一二年生，湖南平江人。一九五七年起任中国人民解放军总政治部副主任。“文化大革命”期间遭受林彪、江青反革命集团迫害，一九六七年一月至一九七四年国庆节前夕被关押。——第457页

〔344〕齐燕铬（一九○七——一九七八），北京人。一九六○年起任文化部副部长、文化部党组书记。“文化大革命”期间遭受林彪、江青反革命集团迫害，一九六六年夏至一九七四年国庆节前夕被隔离审查。——第457页

〔345〕卫立煌（一八九六——一九六○），安徽合肥人，原国民党将领。一九四八年任国民党军东北“剿总”司令，因在辽沈战役中没有积极执行蒋介石的“反攻”命令，被软禁于南京。一九四九年获释后去香港。一九五五年三月回北京，后任国防委员会副主席、中国人民政治协商会议全国委员会常务委员、中国国民党革命委员会中央常务委员。——第457页

〔346〕张学铬（一九○六——一九八三），辽宁海城人，张学良的胞弟。曾任中国人民政治协商会议全国委员会委员。“文化大革命”期间遭受林彪、江青反革命集团迫害，一九六八年至一九七三年被关押。——第457页

〔347〕张学良，一九○一年生，辽宁海城人，东北军爱国将领。一九三六年十二月任国民党军西北“剿总”副司令时和国民党第十七路军总指挥杨虎城一起发动西安事变，要求蒋介石停止内战，一致抗日。后被蒋介石长期扣押。——第457页

〔348〕张学思（一九一六——一九七○），辽宁海城人，张学良的胞弟。曾任辽宁省人民政府主席、中国人民解放军海军司令部参谋长等职。“文化大革命”期间遭受林彪、江青反革命集团迫害，一九六七年起被关押。——第457页

〔349〕吕案解案 即吕正操专案和解方专案。这是林彪、江青反革命集团为了篡党夺权，残酷迫害曾在东北军和东北各界工作过的吕正操、解方、刘澜波、张学思、万毅、阎宝航、高崇民、贾陶等人而蓄谋制造的一个所谓“东北叛党集团”的假案。一大批党、政、军领导干部和民主人士曾受到株连。一九七八年中共十一届三中全会以后，这个案件得到彻底平反。——第457页

〔350〕廖志高，一九一三年生，四川冕宁人。当时任中共四川省委第一书记。——第459页

〔351〕富春 即李富春（一九○○——一九七五），湖南长沙人。当时任中共中央政治局常委、国务院副总理兼国家计划委员会主任。——第460页

〔352〕剑英，即叶剑英，一八九七年生，广东梅县人。当时任中共中央政治局委员、中央军委副主席。——第460页

〔353〕成武，即杨成武，一九一四年生，福建长汀人。当时任中国人民解放军第一副总参谋长、代总参谋长。——第460页

〔354〕谷牧，一九一四年生，山东荣成人。当时任国家基本建设委员会主任。——第460页

〔355〕秋里 即余秋里，一九一四年生，江西吉安人。一九六七年时是国家计划委员会副主任。一九七二年时是中共中央委员、国家计划委员会主任。——第460、463页

〔356〕支左 指在“文化大革命”中派人民解放军支持当时被称为左派群众的人们，是“三支两军”（支左、支工、支农、军管、军训）的一个方面。这在当时的混乱情况下对稳定局势起了积极的作用，但也带来了一些消极的后果。——第460页

〔357〕《六六通令》指一九六七年六月六日颁布的《中共中央、国务院、中央军委、中央文革小组通令》。——第461页

〔358〕长汽、二汽、重汽、南汽指第一汽车制造厂（在吉林长春）、第二汽车制造厂（在湖北十堰）、重庆汽车分公司和南京汽车制造厂。——第463页

〔359〕指“九一三事件”。一九七一年九月十三日凌晨林彪乘飞机外逃叛国，摔死在蒙古温都尔汗。——第463页

〔360〕地方五小工业 是我国地方小型厂矿的统称。六十年代一般是指小钢铁厂、小煤矿、小电站、小化肥厂、小机械厂，后来又包括小水泥厂等。——第464页

〔361〕四个一样 是对当时在分配方面的平均主义做法的概括说法，即干多干少一个样，干好干坏一个样，会干不会干一个样，干与不干一个样。——第465页

〔362〕王云五（一八八八——一九七九），原籍广东中山，生于上海。他首先将四角号码检字法运用于字典。一九四六年后曾任国民党政府经济部部长、财政部部长、行政院副院长等职。一九四九年去香港，一九五一年到台湾。——第467页

〔363〕普列汉诺夫（一八五六——一九一八），前期是俄国马克思主义宣传家。一八八三年创建俄国第一个马克思主义团体“劳动解放社”。翻译和介绍了许多马克思和恩格斯的著作，并先后发表《社会主义与政治斗争》、《我们的意见分歧》、《论一元论历史观的发展》、《论个人在历史上的作用》等论著，为马克思主义在俄国的传播起了重大作用。一九○三年俄国社会民主工党第二次代表大会后，逐渐转向孟什维克，后成为第二国际机会主义的首领之一。——第471页

〔364〕剑、春、德指叶剑英、张春桥、李德生。叶剑英当时任中共中央军委副主席，主持军委办公会议。张春桥、李德生当时是军委办公会议的成员。——第472页

〔365〕文裕 即张文裕，一九一○年生，福建惠安人。当时任第二机械工业部四○一所副所长。——第473页

〔366〕指一九七二年八月十八日第二机械工业部四○一所一部张文裕等十八位科学工作者写给周恩来总理的信。这封信反映了我国高能物理研究的情况，提出了发展高能物理研究的建议。——第473页

〔367〕指物理学家萨拉姆教授，当时是巴基斯坦总统科学顾问。一九七二年九月五日，周恩来在和他谈话中，强调了自然科学理论研究工作的重要性。——第473页

〔368〕指一九七二年四月四日第二机械工业部四○一所一部提出的关于发展高能物理方向任务的请示报告。——第473页

〔369〕朱光业，一九二四年生，湖北武汉人。当时任国防科委副主任。——第473页

〔370〕中国方面提出的中日复交三原则是：一、中华人民共和国政府是代表中国的唯一合法政府；二、台湾是中华人民共和国领土不可分割的一部分；三、“日台条约”是非法的、无效的，应予废除。——第478页

