# 致蒋介石信

中文马克思主义文库 -> 周恩来
致蒋介石信
（一九三六年九月二十二日）

介石先生：
 

自先生楬橥反共以来，为正义与先生抗争者，倏已十年。先生亦以清党剿共劳瘁有加，然劳瘁之代价所付几何？日本大盗已攫去我半壁山河，今且升堂入室，民族浩劫，高压于四万万人之身矣！近者，先生解决西南事变〔３６〕，渐取停止内战方针。国人对此，稍具好感。惟对进攻红军犹不肯立即停止，岂苏维埃红军之屡次宣言、全国舆论之迫切呼吁，先生犹可作为未闻耶？

先生须知，共产党今日所求者，唯在停止内战、建立抗日统一战线与真正发动抗日战争。内战果能停止，抗战果能实行，抗日自由果能实现，则苏维埃与红军誓将实践其自己宣言，统一于全国抗日政府指挥之下，为驱逐日寇而奋斗到底。先生素以继承孙中山先生革命传统为职志者，十年秉政，已示国人对外妥协对内征服之失策。现大难当前，国人抗日之心，甚于"五卅"〔１７〕，渴望各党合作之忱，甚于民十三年改组〔３７〕。先生其亦有志于回到孙先生革命的三大政策之传统而重谋国共合作乎？当先生实行孙先生革命政策时，全国群众闻风景从，先生以之创黄埔，练党军，统一两广，出师北伐，直抵武汉。及先生背弃孙先生遗教，分裂两党统一战线后，则众叛亲离，内乱不已，继之以"九一八"〔３８〕，五年外患，国几不国。先生抚今追昔，其亦有感于内战之不可再长而抗日之不容再缓乎？苏维埃与红军为此呼吁，至再至三，但仍不得先生之坚决同意。前者东向抗日被阻于晋，今者全国主力红军集中西北，目的更全在抗日，乃先生又复增兵相逼。先生岂竟忘日寇已陈兵绥东，跃跃欲动，即欲变西北为殖民地耶？来敢正告先生：红军非不能与先生周旋者，十年战绩，早已昭示国人。特以大敌在前，亟应团结御侮。自相砍伐，非但胜之不武，抑且遗祸无穷。若先生以十年仇隙，不易言欢，停战议和，未可骤信，则先生不妨商定停战地区，邀请国内救国团体各界代表监视停战，必知红军力守信誓，只愿在抗日战争中担任一定防线，以其全力献之于民族解放，他则一无所求也。先生其亦有意于一新此民族壁垒而首先在西北实现乎？天下汹汹，为先生一人。先生如决心变更自己政策，则苏维埃与红军准备随时派遣负责代表与先生协定抗日大计。此共产党、红军确定之政策，将千回百折以赴，不达目的不止者也。

先生为国民党〔１４〕及南京政府最高领袖，统率全国最多之军队，使抗日无先生，将令日寇之侵略易于实现，此汉奸及亲日派分子所企祷者。先生与国民党之大多数，决不应堕其术中。全国人民及各界抗日团体尝数数以抗日要求先生。先生统率之军队及党政中之抗日分子，亦尝以抗日领袖期诸先生。共产党与红军则亟望先生从过去之误国政策抽身而出，进入于重新合作共同抗日之域，愿先生变为民族英雄，而不愿先生为民族罪人。先生如尚徘徊岐路，依违于抗日亲日两个矛盾政策之间，则日寇益进，先生之声望益损，攘臂而起者，大有人在。局部抗战，必将影响全国。先生纵以重兵临之，亦难止其不为抗战怒潮所卷入，而先生又将何以自处耶？

奉上八月廿五日敝党中央与贵党中央书，至祈审察。迫切陈词，伫候明教。顺祝

起居佳胜！不一。

周恩来

九月廿二日

