# 关于哥老会问题

中文马克思主义文库 -> 周恩来
关于哥老会问题
（一九三六年十月六日）


　　本来开山堂是争取哥老会的有效方式，而且是动员和团结哥老会群众的最好方法。马头山开山堂〔４０〕虽然在地点上、日期上和到会的限制上有很大的缺点，但山堂既召开了，我们应赶紧在争取领导、确立工作方针上，打下有力的基础，使这一次山堂会，能如我们所计划的成功，不要如一般哥老会中人所想的要在苏区活动，要在苏区发展。我现向你们提议，采取下述各项具体办法，以确立我们的工作方针：

　　第一，根据党中央过去的指示及实际工作中一些经验和教训，在党内进行解释和教育，使一般党员都了解我党争取哥老会的基本方针是什么。现在最急的是要将这次参加马头山开山堂的党内干部（通知上要"参加过哥老会的区乡两级的党员，务必参加开山堂"，也是不妥的，一因这个数目太大，二因不经选择参加不妥），经过省委的或直接去马头山的，统统加以训练（一两天也好），务使这一批干部能够完全站在党的立场上去参加开山堂，去传达党所给他们的工作方针，树立起党在哥老会中的领导，而不致随波逐流，为一般龙头大 爷所左右，成为凑数的角色。训练的内容，不仅解释党的指示、工作方针，并且要讲到工作方法，特别是领导哥老会的艺术。在哥老会中是等级森严的，但我们同志在哥老会中不要因为自己辈分太小，当说的不敢说；有些不必要说的，也不必抢着说。重要的说话和建议，应由没有参加过哥老会的省委同志，以党和苏维埃代表名义去出席致词。这个规矩，必须取得，以便确立今后党和苏维埃指导哥老会的必要手续。在开山堂时，党团的领导作用非常重要，但形式上可以避免这种党团组织，使龙头大爷不致怀疑我们在破坏他的哥老会，但实际工作中，却必须使这些参加哥老会的党员，为着实现党的主张而努力。去指导这次开山堂的负责同志，必须尽力教育和暗示这些党员的努力方向和方法。负责同志及一般党员在哥老会中间不要高傲自慢，要从取得他的信仰中将我们的主张贯彻下去。

　　第二，在这次开山堂中，必须确定明确的斗争目标和发展对象。我们应该赞扬哥老会过去反抗统治阶级及其革命的传统，发挥哥老会中许多代表民族利益、群众利益的观点和行为，联系地说到今日的苏维埃红军和共产党已实现了他们所渴望的打富济贫、反对贪污的世界，而苏维埃以外的中国，却到处看见日寇横行，卖国贼当道，许多贪官污吏、为富不仁的土豪劣绅、残害同胞的军阀并没有受到制裁。这从哥老会的纲领看来，是应该赞助和拥护这个苏维埃红军和共产党，而反对日寇、卖国贼和一切的贪官污吏、土豪劣绅及残害民众的军阀的。再从哥老会本身来看，哥老会弟兄在苏区都已分得了土地、牲畜、粮食、房屋，解除了破产失业的痛苦，取消了苛捐杂税的剥削和一切政治上的压迫。而在白区呢？哥老会是秘密会社，不能公开，哥老会弟兄被认为三教九流的下层社会，常常受到黑暗的压迫。因此，哥老会应该拥护和保卫这个容许哥老会公开、解放哥老会弟兄的苏区，发展这个苏区，将这个苏区的精神传布到全中国去，改造那个黑暗的中国！如果有人说蒋介石也在西峰镇开山堂了，高桂滋〔４１〕、高双成〔４２〕也容许哥老会公开，那我们就要向哥老会弟兄说明：你们不要忘记左宗棠利用平牌大爷李正官的故事，蒋介石、高桂滋、高双成都在学左宗棠，要想收买一二个龙头大爷，号召哥老会弟兄来破坏苏区，破坏红军。不要说苏区红军原是解放哥老会弟兄的，哥老会弟兄决不愿打苏区红军，即算是真有个把哥老会的败类要做李正官第二，苏维埃和红军也决打不败的。记得蒋介石在上海、武汉曾利用过青红帮头子屠杀工人，但青红帮弟兄得到什么呢？现在还不是在上海、武汉同其他工人一样，受尽剥削、压迫和摧残！所以蒋介石、高桂滋、高双成所能收买的不过是李正官一流的败类，而大多数哥老会弟兄以后反要遭受惨杀。我们要正告哥老会的弟兄：有苏维埃，有红军，哥老会就有了靠山，就得到解放；没有苏维埃，没有红军，哥老会就要同以前一样，永世不得翻身。哥老会弟兄要认清谁是自己的人。那为富不仁的土劣，残害同胞的军阀，抽收苛捐杂税的贪官污吏，决 不会真正解放哥老会，决不是哥老会的朋友！当然，讲到斗争目标，最主要的还是日本帝国主义，"兴中反日"应是哥老会中最中心的口号。环绕着这个口号，应联系到反对卖国殃民的祸首，反对残害同胞的军阀，反对抽收苛捐杂税的贪官污吏，反对为富不仁的土豪劣绅。斗争目标树立清楚了，发展对象自然会向着白区、白军，而不会向着苏区、红军。但这里还需进行组织上的巩固。

　　第三，我现在继续作组织上的建议。在这次马头山开山堂中，斗争的目标确定了，便须紧跟着确定在山堂开过后，要利用各路来的龙头大爷，回到苏区边境，去建立几个方面的哥老会招待处〔４３〕或办事处，招纳四方豪杰、江湖好汉，来商量到白区、白军中发展哥老会和进行斗争的具体计划，从一般的斗争口号、会规、组织直到秘密的交通联络。关于斗争口号，除总的方面如上项所说外，其他部分的日常的斗争口号应按照各地哥老会的实况及其弟兄伙在各阶层中所受的压迫、剥削和痛苦定出，并应引导和联结他们的斗争到一般的工农劳苦大众的斗争之中。哥老会的会规，要将其中迷信的封建的反动的条规，用消极抵制和善意批评的办法，逐渐地将其消除，而对于其中带有进步性革命性的，则应极力宣扬，并向着更正确的道路上领导。如江湖救国会所草拟的十大条规，或将孝悌忠信礼义廉耻解释成新的内容，定为条规，或将红十条、黑十款、九禁令加以新的解释，这都是十分必要的。在组织方面，这次山堂开毕，应引导进山的大爷下山后向苏区以外奔走，去找未到会的或熟识的弟兄，宣扬这次开山堂的宗旨和条规，鼓动和引导他们向着新的斗争目标。对苏区内的大爷、当家、管事的，要吸引其中好的有斗争精神的去参加招待处工作，有愿去白区活动的，更所欢迎。如有愿在苏区内收拜弟的，我们不能以命令方式禁止其收，而应向其解释，在苏区内不论哥老会弟兄或非哥老会弟兄都已一样得到解放，都已分别参加工会、贫农会，都已参加了政权，哥老会没有发展必要，要发展应面孔向着外边，那里有广大的斗争，需要哥老会参加和发展。哥老会不论在白区或苏区，均不必再改名称。一切抗日救国的名称，如江湖抗日救国会之类，不必再给哥老会加上。一因这种名称不应仅限于哥老会员；二因不应将这种名称帮助哥老会发展，而应吸引哥老会弟兄去参加一般的抗日救国运动，乃至工会、农会及市民团体等；三因我们进行哥老会工作，中心在争取它已有的群众，不在替它发展。所以发展哥老会，即是收拜弟，只有在工作必要时才"背票封子下山"（即背公事下山）。一般的是在利用它已有弟兄去进行白区、白军中的工作，利用它秘密社会的关系易于在自区立足、藏身、来往和活动，利用它的宗旨、条规和禁令，易于团结他们与反革命进行斗争。我们是经过哥老会这个桥梁，去打入下层社会，去接近广大群众，而不是要在群众中发展起第二个秘密的革命党，更不应替它成立起独立的武装组织（如江湖抗日救国军等）。党员加入哥老会，也只有在必要时，并须经过党的选择和决定。为使哥老会不能利用其秘密组织在苏区内和红军中进行发展，我们一方面容许其公开，从公开中限制其发展；另一方面要教育我们的党员、团员以及工农会的会员，使他们明白哥老会没有在苏区发展的必要，如果秘密发展，必定会帮助反革命或被反革命利用来进行破坏苏区、破坏红军的活动。为了使哥老会在苏区做得真实公开，首先应教育我们党员和红色军人，要将自己参加过哥老会的事公开出来。特别要我们党员和红色军人警觉，哥老会的基础虽然建立在下层社会，但其龙头大爷不少是豪绅地主军人官吏，他们会自觉地或被收买地出卖其下层群众利益，去帮助反革命来进行前面所说的种种破坏苏区、红军的活动；并且哥老会的思想条规与组织形式，带着极浓厚的封建的迷信的保守的反动的色彩，它无疑地要影响其群众，阻碍其群众前进，发展其群众的落后思想、不良习俗（如吸大烟、充光棍等），这对于共产主义的前进思想及其运动是有极大障碍的。所以，我们站在统一战线的立场上，努力争取哥老会的群众参加抗日救国运动，同时必须注意它的变节的出卖群众利益的领袖，逐渐地扫除与我们接近的哥老会中的一些落后思想和不良习俗，严防他们在苏区、红军中的秘密活动。我们在这次山堂会中应公开声明：苏维埃政府愿意保护一切在苏区的哥老会员，但望哥老会勿在苏区进行秘密活动，勿做违反苏维埃法律的事。凡犯了苏维埃法律的哥老会员或是替反革命做侦探做破坏苏区、红军工作的哥老会员，苏维埃要依法处理，如同处理犯法的共产党员一样。我们党员在这次山堂会中更应该提议，凡在白军当军官的（如高双成、张云衢〔４４〕等），要用龙头大爷及其同辈弟兄的名义，劝其停止内战，勿再自相残杀，并要与红军联合，一致抗日救国。如经过几次劝阻无效，便应联合起苏区、白区的龙头大爷及哥老会弟兄，认为他已违背禁令，开除出会，并布告大众周知。对西峰镇开山堂的，也应派人去联络，要他们一致联名主张红白两军停止内战，一致抗日。谁要不愿停战，继续残害同胞，谁就是哥老会的公敌。庆阳龙头李大爷，如利用西峰镇开山堂，继续进行破坏苏区、破坏红军的工作，应号召各地的哥老会龙头大爷弟兄坚决反对。要与为保护这解放哥老会的苏区与苏维埃红军站在一起，将苏区的哥老会员引导到保卫苏区的任务上来；将边区、白区的哥老会员引导到发展苏维埃运动上来；将一切的哥老会员统一到抗日救国的事业上来，把哥老会的反抗的侠义的精神，发扬光大为哥老会群众的英勇的革命行动；把哥老会的保守的迷信的反动的思想习惯和行动逐渐地消灭下去。这是党在争取对哥老会领导上最实际的最基本的任务。



　　＊　这是给陕北省委的信的节录。



