# 用东北群众的力量来推动东北军的团结

中文马克思主义文库 -> 周恩来
用东北群众的力量来推动东北军的团结
（一九三七年三月十八日）

（一）在执行党今天巩固和平、加速准备抗日的总任务下，东北军与东北流亡人民中的工作仍是最重要的一环。"双二"杀王事变〔５１〕所造成东北军内部的分化，因为亲日派的播弄，还在继续下去。东北军的东调，将更增加亲日派分裂它的危险性。为要克服这个分化，使东北军更加团结起来，我们除掉在东北军中加强秘密党的工作之外，今天最好的方法便是加紧东北各救国团体的统一运动，用东北群众的力量来推动东北军的团结。
 

（二）估计到目前在调赴豫、皖的东北军中工作的困难及一部分左派站不住脚逃避平津，估计到东北军及东北人民在河北有很大的数目并有相当的组织，因此，建立东北群众的统一战线并用群众统一战线来推动东北军的团结这一任务，现在应当主要地由北方党来负担起来。

（三）建立整个东北民众救国团体联合会，在今天可以作为建立东北群众统一战线活动的中心。为要进行这一工作，我提议：

一、把现有北方的东北各种救国团体加以整理并充实其群众基础。首先，把北平、天津等地的东北救国团体的总会建立起来。然后，号召并筹备东北的救国联合会的召集。

二、在这些团体中，用最大力量来吸收并罗致东北名流，特别是东北军官来参加。

三、在进行这一工作过程中，应当采用各种宣传与组织的方法来团结东北军的官长，提高部队抗日情绪。

四、这一工作，应特别注意到团结整个东北人民与军队。否则，只是以团结一部分左倾分子为满足，那不但无益，反而会加深东北军的分裂。

五、应当注意到，把建立整个东北团体联合会的工作和国民代表大会的选举工作联系起来，利用选举运动来团结东北军内部。

（四）关于建立北方东北军中党的工作，我有如下的意见。即是党的基础建筑在中下级官兵身上，但在今天发展的对象，应多注意到团营长，吸收其中个别的先进分子入党。下级官兵中的工作，应当多采取动员群众联欢慰劳提高抗日情绪，以及经师团营长自上而下地组织俱乐部等方法。要使得这些工作易于进行，党必须加紧上层的向军长等的活动。这虽然是困难的，但是对于工作开展上是有很大作用的。

（五）为要担负这一工作，党做东北军工作的干部要大大地加强。尤其在华北，最好的干部应当做军队工作。

我提议把联络局及地方党内的东北干部和群众关系做一次研究，以便适当地配备干部。为着帮助北方东北军工作，现在调宋、袁〔５２〕二同志前来，参加东北军工作。袁同志在五十三军上层有很多关系，宋原在"东委"〔５３〕工作，可做计划与推动东北群众工作。

根据此地"东委"工作的经验，党必须把东北军的上下层工作分开。上层工作由上层工作委员会来负责，党的工作由工委来负责。上层工委书记参加工委。

五天前曾经有一封信给你们，里面有一些建议，未知收到没有。

＊　这是在西安同国民党代表谈判期间，写给中共中央北方局书记胡服（刘少奇）并转河北省委的信。

