# 应立即停止一切破坏抗日的反共活动

中文马克思主义文库 -> 周恩来
应立即停止一切破坏抗日的反共活动
（一九四○年十二月二十一日）

淮南〔５８〕先生勋鉴：
 

承面示关于参政会〔５７〕下届人选问题，甚感。惟叶青〔５８〕与张国焘〔５９〕无丝毫差别，且张之破坏团结过于叶青，而其罪直等于陈炯明〔９〕之于贵党。犹忆当年蒋先生因陈炯明辱及贵党，诬及孙先生，不惜绝裾而去，此等民族气节，正弟等所愿敬谨效法者也。故张国焘虽属江西选出，但为党部所指定，解铃系铃，权在中央。苟为下届参政会示团结，弟敢请兄以弟意转呈委座，当必能蒙俯允也。

又，最近各地反共事件纷起，其目的显欲逼成事变，兹择要告兄数事如下：

一、现在璧山附近，中央机关已发现有"防共即是救国"标语，闻其指令系出自中央党部。

二、《新华日报》〔６０〕被扣、被删之稿件、文句，常至极无理地步，如本月七号中苏文化协会之妇女晚会的特写上有"团结打日寇，团结打汉奸"字句，亦被删去。

三、第十八集团军原驻蓉代表罗世文前为抢米案〔６１〕所陷害，被特务机关捕去。现闻已与中苏文化协会成都分会负责人车耀先〔６２〕先生同时被杀。

四、目前，大后方如川、黔、湘、鄂、赣、皖、陕、甘等省，捕杀中共党员及所谓可疑之抗战分子，日有所闻，各机关、各学校、各团体清洗异党分子更弄得人心惶惶。

五、第十八集团军驻秋林二战区之联络处王世英参谋及其处内人员十余人，全数被中央军六十一师派兵捕去。经交涉结果，该师声明捕王系误会，但联络处人员仍未释放。

六、第十八集团军驻桂林联络处，主要在担任采办、运输军中所需要补充之交通、卫生器材，但最近为军政部驻桂办事处威胁撤销，限期结束。

七、第十八集团军由西安赴延安、绥德之军车及其所载之人员、资材，常被无故拘捕、扣留。最近且闻西安特务机关规定办法多种，专门为难十八集团军之交通运输，使其人员、资材无法补充和转移。

类此事件，多至不可胜数。弟等为团结计，殊不欲扩大范围，但愿其早日归于平息。惟目前最严重之事件，莫过于新四军江南部队已整装上道，而一切补给犹无着落；新四军、八路军在江北部队已听命停止冲突，而山东之东北军与安徽之广西军犹向之着着进逼。其尤甚者，则为李鹤龄〔６３〕主席所指挥之两个师已越淮南而东，新四军支队东退，彼竟直逼滁县，并在该处设立剿共司令部；是李主席直欲切断新四军大江南北之联络，并与江苏方面友军配合，造成对新四军、八路军在苏北之半包围的形势，直逼之于江海之滨，尚有何渡江北移之可能？另一方面，重庆若干报纸已奉命公开反共，而《商务日报》更公开揭载所谓中共脱党分子之宣言，以示挑衅。似此举动，其目的绝不仅限于执行军纪，其意图必更另有所在，纵弟团结有心，亦极难作适宜之解释也。素信先生坚持团结，想对此严重现象，必有以和缓而调解之之道。弟信笔直书，亦唯望先生能转呈于委座之前，而求得其平，殊不胜企盼之至。专此。

敬颂勋祺！

弟

周恩来启

十二月二十一日

＊　这是写给国民党代表张冲，并要他转告蒋介石的一封信。当时，抗日战争处于困难时期，以蒋介石为代表的国民党顽固派对抗日更加动摇，不断制造反共事件，再次掀起反共高潮。这封信是为指斥国民党顽固派，以延长国共合作时间，坚持抗战而写的。

