# 关于一九二四至二六年党对国民党的关系

中文马克思主义文库 -> 周恩来
关于一九二四至二六年党对国民党的关系
（一九四三年春）

国共合作后，孙中山先生在中国共产党的帮助下，重新走向革命，成为资产阶级民主派的代表。他在一九二四年的国民党第一次全国代表大会上，接受了我们党起草的宣言，使三民主义成为革命的三民主义，新三民主义。当时，国民党〔１４〕不但思想上依靠我们，复活和发展他的三民主义，而且组织上也依靠我们，在各省普遍建立党部，发展组织。国民党和他的三民主义，靠着我们才得以把影响扩大到广大的工人、农民、小资产阶级群众中去。国民党改组后，由于我们党的努力，工人运动、农民运动在全国大大发展起来。各省国民党的组织，也由于我们同志的努力而建立和发展起来。当时各省国民党的主要负责人大都是我们的同志，如湖北的董必武〔６６〕、陈潭秋〔６８〕同志，湖南的何叔衡〔６９〕、夏曦〔７０〕同志，浙江的宣中华〔７１〕同志，江苏的侯绍裘〔７２〕同志，北方的李大钊〔７３〕同志、于树德〔７４〕（那时是共产党员）和李永声〔７５〕、于方舟〔７６〕同志等。是我们党把革命青年吸引到国民党中，是我们党使国民党与工农发生关系。国民党左派在各地的国民党组织中都占优势。国民党组织得到最大发展的地方，就是左派最占优势的地方，也是共产党员最多的地方。孙中山先生北上〔７７〕的时候，我们党在全国组织了各界的召集国民会议运动〔７８〕，各地纷纷成立了国民会议促成会和妇女界的国民会议促成会（因为孙中山召开国民会议的宣言中没有明确说应有妇女参加）。这样，孙中山北上才有了群众作后盾，他和国民党的影响才得以更广泛地扩大到北方。

在当时形势下，国民党在组织上自然而然地形成各种派别，对三民主义也自然而然地作各种解释。国民党改组时，反对改组最坚决的是广东买办资产阶级的代表冯自由、谢持〔７９〕这些人。当时，这些人被孙中山痛骂过，并被开除了党籍。改组首先受到他们的反对与破坏是不奇怪的，因为广东是英帝国主义的势力范围，革命在广东的发展，锋芒必然朝向英帝国主义，也就必然侵犯依赖英帝国主义为生的广东买办资产阶级。冯自由等在广东革命势力向上发展时，首先分裂出去，充分地说明了中国买办资产阶级的地域性。孙中山去世以后，公开起来反对国民党革命的，是西山会议派〔８０〕。他们公开分裂出去，成立独立的组织。他们大骂广东的国民党，大骂国民党左派的廖仲恺先生，大骂广东被赤化了，但一般地不反对蒋介石。国民党右派在香港办报纸，公开活动，对广东国民党进行分化工作。他们的策略是打击廖仲恺〔８１〕，拉拢蒋介石。他们对蒋介石是看对了的。这些右派一直到一九二五年全国革命风起云涌地起来以后，始终是反对革命的。右派中最危险的一个家伙是戴季陶〔５５〕。他虽然也在孙中山的遗嘱上签了字，表面上不赞成西山会议派的分裂，也说要维持国民党的统一，但他采用的是打入广东国民党从内部来分裂国民党的阴谋。他从思想上大大发展了孙中山的消极方面，写了《孙文主义之哲学基础》、《国民革命与中国国民党》，完全抽去了孙中山学说中的一切革命的东西。他大讲道统，说孙中山的道统是继承尧、舜、禹、汤、文、武、周公、孔子的。他见着人就痛哭流涕地大讲其"孙文主义"，从上海讲到广东，又从广东讲到上海。他到黄埔军官学校〔３５〕讲演，进行分化工作。在他讲演以后不久，一九二五年四月二十四日，黄埔军校成立了孙文主义学会〔８２〕，这是右派的组织。另一个右派头子是孙科〔８３〕。他是资产阶级两面派，表面上有时赞成革命，实际上反对革命。抗日战争期间，他还是耍两面派，有时主张民主，实际上他的民主是国民党"五五宪草"〔８４〕式的民主。国民党中派表面上与我们合作，赞成革命，但并不是真心和我们合作，而是随时提防和限制共产党的，其代表人物就是蒋介石。蒋介石实际上是与右派合作的，是右派势力的保护者和组织者。在当时特定的条件下，在一个短时期内，他算是国民党的中派，但后来便成了公开的右派。

筹办黄埔军官学校的经过是这样的：一九二三年以前，孙中山部下比较带有一点革命性的部队，是李济深〔８５〕的第一师。这是邓铿〔８６〕系统的部队，大革命时代的张发奎〔８７〕、叶挺〔８８〕、邓演达〔８９〕以至陈诚〔９０〕，都出自这个师。开办黄埔军校应该说是孙中山军事上失败的结果。辛亥革命〔１０〕时，孙中山有两个运动，一个是新军运动〔９１〕，另一个是会党运动〔９２〕。辛亥革命以后，他的活动渐渐变成了拉拢军阀，结果是不断遭到失败。这就教训了孙中山，所以他在苏联和中国共产党的帮助下，懂得了建立革命军队的重要，接受了苏联顾问的建议，一九二三年决策，一九二四年正式开办黄埔军校，并决定由蒋介石当校长。

蒋介石为什么能接近孙中山以至于当了黄埔军校校长呢？蒋与孙的接近首先是因为陈其美〔９３〕的关系。陈其美从事政治活动以后，始终追随孙中山。例如孙中山组织中华革命党〔９４〕，要求参加者在誓词上打手印，许多士家出身的如胡汉民〔９５〕、汪精卫〔５４〕等都不干，黄克强〔９６〕则更是反对，而陈其美却第一个宣了誓，打了手印。因此陈在当时得到孙中山的信任。蒋介石是陈其美的徒弟之一，因而得与孙中山接近。其次一个重要的原因，就是在永丰舰〔９７〕的事情上蒋介石投了一个机。一九二二年陈炯明炮轰总统府〔９８〕，赶走了孙中山。孙中山在永丰舰上与陈炯明相持了五十多天。当时蒋介石在上海交易所做生意失败了，看到这个机可投，特意从上海跑到永丰舰，表示誓与孙中山共存亡。从此蒋介石与孙中山比较密切起来。一直到现在，蒋介石还常以这件事作为他是孙总理忠实信徒的资本，把他与孙中山在永丰舰上的相处，作为他为孙总理赴难的证据。孙中山和苏联建立关系后，因为邓铿等离不开广东，就派蒋介石到苏联去参观，后来叫他当黄埔军校校长。

蒋介石开始办黄埔军校时，表面上赞成革命，但他的思想实际上是反共反苏的，并不是真心诚意地与共产党合作。有一次苏联顾问为革命说了几句话，他就不高兴，拂袖跑到上海去了。当时黄埔军校有六百学生，大部分是我党从各省秘密活动来的左倾青年，其中党团员五六十人，占学生的十分之一。蒋介石对这些人是提防、限制的。他的军阀思想在那时也是发展的。他让最为人所不齿的王柏龄〔９９〕负责训育。他所能用的就是奴才。对有些骨气不愿做奴才的邓演达，他就容不下；对经王柏龄介绍的何应钦，这第二个奴才，他却非常相信。黄埔军校内的队长都是他的私人。有一次我派了几个左派的人当队长，他就大为不满，撤销任命。他用人的方法是制造矛盾、利用矛盾、操纵矛盾，拿一个反动的看住一个进步的，叫一个反左派的牵制一个左派的，用反共的牵制相信共产主义的。例如第一师师长是何应钦，党代表就可用我周恩来。第二师师长王懋功〔１００〕因接近汪精卫而成为当时的左派，我推荐我党的鲁易〔１０１〕同志去当党代表，他就无论如何也不干，用了右派的人。第三师师长谭曙卿是右派，他就用鲁易同志为党代表。第一次东征以前，一九二五年二月，黄埔军校成立了青年军人联合会〔１０２〕，他接着就在四月，在戴季陶的分裂阴谋下，成立了孙文主义学会，以相牵制。

当时广东的国民党内，中派是少数，左派占极大多数。廖仲恺是国民党的左派。因为他是华侨出身，与国内的买办阶级、地主阶级关系较少，所以更多地带着民族资产阶级进步派的倾向。在广州商团事件〔１０３〕上，他开始就是主张坚决镇压的。省港罢工〔１０４〕以后，他是同情工人，站在工人方面的。当时农民运动在广东有发展，他也是和我们站在一起赞助和推动农民运动的。虽然他在政治斗争中有其动摇性，对工人、农民和我党的力量有所畏惧，但他晚年的政治生活是光荣的。他尊重苏联顾问的意见，但他有自己的立场，有自己独立的见解。他是资产阶级左派的坚强的代表。汪精卫是资产阶级的软弱性的代表。当他还革命时，他会把苏联顾问和我们党的意见加以发挥，会做一个很好的留声机。胡汉民从思想上说是右派，虽然有时也可以同左派妥协，但有他地主阶级的独立的立场。因此商团事变时，他是最主张妥协的；而暗杀廖仲恺〔１８〕，他是知情的。谭延闿〔１０５〕实际上也是右派，但在利害关系上，由于蒋介石的军事力量日渐扩张，他想发展自己的实力，所以在行动上有时与左派靠近。朱培德〔１０６〕有时靠近汪精卫，有时靠近蒋介石。程潜〔１０７〕也是因为要想扩大自己的军队而靠近汪精卫。但这些人总是害怕民众。他们在广东之所以还没有公开反对民众，是因为民众运动在广东的发展还没有直接侵害到他们本身的利益。一旦民众运动在他们的家乡湖南、湖北、江西发展起来，他们反对民众的面目便马上暴露了。

一九二五年五卅运动〔１７〕以后，工人运动、农民运动在全国得到空前的大发展，规模之大是过去所从来没有的。从这个运动中，能看到革命的发展是走向农民的革命战争，能看到革命发展这个全局的，在我们党内的代表是毛泽东同志。他接办农民运动讲习所〔１０８〕，进行农民土地问题的调查研究，出了二十几种小册子。历届讲习所的学生后来分散到湖南、湖北和其他各地，发动了广大的农民运动。

对于革命在这一年中的大发展，国民党中派是非常恐惧的。第一次东征〔１０９〕回来，镇压了刘震寰、杨希闵的叛乱〔１１０〕，在沙基惨案〔１１１〕中，我们已看到蒋介石动摇，畏惧帝国主义。一九二五年六月，国民党中央党部通知黄埔军校参加广州的游行示威。我从军队中抽出两个营，学校里抽出一个营去参加。蒋介石后来知道了，非常不满意，认为不应当游行示威。廖仲恺去世以后，他赶走了胡汉民、许崇智〔１１２〕，表面上是反对右派，表示革命，实际上他是为了夺取个人权力。因为胡汉民是代帅，许崇智是军界前辈，他们在，蒋介石无从提高自己在军队与政权中的地位。一九二五年十月第二次东征〔１１３〕时，海陆丰一带的农民运动在彭湃〔１１４〕同志领导下，已有很大发展，农民自卫军在军队到来以前已经占领了县城，选举了彭湃同志的哥哥当县长〔１１５〕。蒋介石去后成了客人，这自然不能不引起蒋介石对民众运动的畏惧。特别是当时在黄埔军校内部，青年军人联合会的发展大大超过孙文主义学会；军队中三个师的党代表，我们党占两个，九个团的党代表，我们占七个，在连、排、班以及士兵中有了我们党的组织；各军又成立了政治部。在革命力量的发展面前，蒋介石更加动摇起来，企图加以限制。所以在一九二五年十一月东征途中，他召集了连以上的军政人员联席会，会上公开表示他的黄埔军校不可分裂，要求把所有在黄埔军校以及在军队中的共产党员的名字都告诉他，所有国民党员加入共产党的名字也都要告诉他。当时我以此事关系两党，须请示中央才能决定，搪塞过去了。后来他同我个别谈话中进一步提出，为了保证黄埔军校的统一，共产党员或者退出共产党，或者退出黄埔军校与国民党，并假惺惺地表示后者是他所不愿意的。

这时正是国民党第二次全国代表大会前夕，我从汕头回广州，和两广区委书记陈延年〔１１６〕同志、苏联派到广东的国民党和政府的顾问鲍罗廷〔１１７〕商量。当时，我们本来确定的政策是打击右派，孤立中派，扩大左派。我们计划在大会上公开开除戴季陶、孙科等人的党籍，在中央执委中我们党员占三分之一，少选中派，多选左派，使左派占绝对的优势。在军队方面，当时的实际情况，蒋介石的第一军只有三个师，第一师是何应钦，第二师王懋功接近当时国民党左派的汪精卫。除第一军以外都不是蒋介石的。因此计划给蒋介石以回击，把我们的党员完全从蒋介石部下撤出，另外与汪精卫成立国共两党合作的军队。我带着这个意见回汕头去，并等待中央回电到后，立即正式向蒋介石提出。当时在国民党第二次全国代表大会代表中，左派占了绝对优势，实现上述计划是完全有保证的。等了好久，中央来电不同意。更可惜的是中央居然在上海与戴季陶大开谈判，请戴季陶等回粤；为了争取右派回粤，还特地拍电报到广州把大会延期一个月，等候他们，对右派采取完全让步的政策。孙科于是代表右派回到广东，把蒋介石的腰撑起来了。中央则派张国焘〔５９〕做这次大会的党团书记，说我们过去把左派包办了，以后应独立形成共产派，使共产派与左派分开，让左派独立起来。在选举上，向右派作了极大的让步。结果，三十六个执委中，共产党只有七个，比我们原来计划的少了将近一半。国民党左派连朱培德、谭延闿等算在内一共才十四人；右派、中派却有十五人。右派孙科、戴季陶、胡汉民、伍朝枢、萧佛成等都当选了。在监委中，右派更是占了绝对优势。国民党的中央执委、监委是常常合在一起开会的，所以结果成了右派势力大，中派壮胆，左派孤立的形势。这是陈独秀〔１１８〕右倾机会主义对国民党右派、中派的第一次大让步。这是政治上的大让步。

这次大会后，在实际行动上也是孤立了左派。大会完了，鲍罗廷回国去了，苏联军事顾问加伦〔１１９〕到冯玉祥〔１２０〕那里去了，执委中的党员大部分都走了，以至汪精卫问我们还帮不帮助他。正在这时，陈独秀因病躺起来，总书记"失踪"，中央无主，陈延年同志又到上海去开紧急会议了。另一方面，右派却纷纷回粤，张静江〔１２１〕、陈立夫都于一九二六年一二月回到广州，同蒋介石进行勾结，挑拨国共关系。这就是三月二十日中山舰事变〔１２２〕的远因，也是三月二十日事变以前的政治形势。

至于三月二十日事变，则完全是蒋介石制造的。二月五日，蒋介石把王懋功赶走，向汪精卫做了第一次示威。他打电报要我回广州。我因为看到他与右派来往密切，并且察觉他的神色不对，报告了张太雷〔１２３〕同志。当时的苏联顾问不重视这事，把一个大问题当做小问题，儿戏对之。陈延年同志因三月二十日前一二天从上海才回到广州，方针上也掌握得不大稳。

李之龙同志当时是中山舰的舰长。他抓住了虎门要塞司令陈肇英走私的事，报告汪精卫。陈肇英是蒋介石的人，自然向蒋介石报告。于是蒋介石在右派的支持下，乘机发动了三月二十日事变，造谣说中山舰要炮轰黄埔军校，共产党要赶走蒋介石。他逮捕李之龙，下令黄埔戒严，监视各师党代表，包围苏联领事馆，监视苏联顾问，解除省港罢工工人纠察队的武装，把我也软禁了一天。蒋介石与右派勾结，打击汪精卫，向共产党进攻，向革命示威。这时谭延闿、程潜、李济深都对蒋介石不满，朱培德、李福林〔１２４〕有些动摇，但各军都想同蒋介石干一下。如果这时党中央的政策是给蒋介石以有力的回击，毫无问题，事情是有办法的。但当时却采取了继续退让的政策，不了解蒋介石这时还没有足够的力量，他是不敢分裂的，却以为蒋介石是要分裂，就向蒋介石说这是误会。蒋介石于是乘机立刻放了人，表示误会。这是陈独秀右倾机会主义第二次向蒋介石的大让步。这是军事上的大让步。

为了解释"误会"，在汪精卫床前开了一个一点钟的政治委员会。汪精卫、谭延闿、苏联顾问都客气地表示了歉意，而蒋介石倒反而一句话都没说，精神上占了优势，政治上得到极大成功。从此以后汪精卫"失踪"了，国民党左派束手无策。蒋介石向革命进攻，我们没有给他有力的回击，蒋介石的地位更加巩固了，于是他回过头来又打击右派，逮捕了欧阳格〔１２５〕，不用陈肇英，不理古应芬〔１２６〕、伍朝枢。胡汉民在三月二十日事变后，回到广东想进行活动，这时又不得不再度离粤，恰好与"失踪"的汪精卫同船到港。蒋介石打击左派以取得右派的支持，又打击右派以表示革命，这就是他的流氓手段阴险刻毒的地方。从此以后，蒋介石实际上成了国民党的右派。这个时候，他乘机把广东的青年军人联合会和孙文主义学会解散了，并压迫我们的党员从国民革命军第一军以及黄埔军校撤出。我们已经暴露了的党员退出国民党和第一师的有二百五十多人，其中有蒋介石最得意的学生蒋先云〔１２７〕同志，他第一个声明退出国民党。只有三十九个人退出共产党，其中第一个就是李默庵〔１２８〕。从此以后，第一军的元气完全丧失，战斗力一落千丈了。

蒋介石在陈独秀机会主义的让步下，巩固了政治上军事上的地位，接着又从党务上对我们展开进攻，这就是五月十五日在国民党二届二中全会上提出整理党务案，目的完全在压共产党。他们定了几条：

一、凡他党党员之加入国民党者，各该党应训令其党员明了国民党的基础为总理所创造之三民主义，对于总理及三民主义，不得加以怀疑及批评。

二、凡他党党员之加入国民党者，各该党应将其加入国民党的党员名册交国民党中央执行委员会主席保存。

三、凡他党党员之加入国民党者，在国民党高级党部（中央党部、省党部、特别市党部）任执行委员时，其额数不得超过各该党部执行委员总数三分之一。

四、凡他党党员之加入国民党者，不得充任国民党中央机关之部长。

五、凡属于国民党籍者，不许在党部许可以外有任何以国民党名义召集之党务集会。

六、凡属于国民党籍者，非得有最高级党部之许可，不得别有有政治关系之组织及行动。

七、对于加入国民党之他党党员，各该党所发之一切训令，应先交国民党、共产党联席会议通过，如有特别紧急事故，不及提出通过时，应将此项训令请联席会议追认。

八、国民党党员未准予脱党前，不得加入其他党籍，如既脱离国民党党籍而加入他党者，不得再入国民党。

九、党员违反以上各项时，应立即取消其国民党籍，或依其所犯之程度，加以惩罚。

在这种情况下，只要我们有正确的政策，蒋介石这个进攻仍然是不难打垮的。当时他的兵力仍占少数，所有民众运动完全在我们和国民党左派的领导下，他在这个时候是不敢决然分裂的。但党中央仍采取机会主义的政策，并且派了彭述之〔１２９〕、张国焘来指导二中全会的中共党团。在党团会上，讨论了接不接受整理党务案。彭述之引经据典地证明不能接受。问他不接受又怎么办？他一点办法也没有，只说大家讨论好了。但当有人提出意见时，他又引经据典地说这个不行，那个错误。如此讨论了七天，毫无结果。后来张国焘用了非常不正派的办法要大家签字接受。这样，又作了第三次大让步。这是党务上的大让步。

右派的蒋介石占了极大的优势。他把张静江捧出来做中央执委会的主席，实际上这人是陈果夫〔３０〕的傀儡。蒋介石亲自做了组织部长，新设军人部长也是由他兼任。组织部实际上由陈立夫代理。原来我们好几个部长（宣传部长、农民部长等）的位置都让出来了。这样，右派在组织上占了极大的优势，我们在党务方面已毫无地位了。陈果夫、陈立夫便利用他们的地位，在各省发展右派。在北方以丁惟汾、王法勤的大同盟〔１３０〕为基础，收买西山会议派。从此各地方党部左派和右派的斗争也更激烈起来。

蒋介石在政治上军事上党务上接连得到三次大胜利，但形势还不是不可挽回的。只要我们善于反击，蒋介石右派的力量还是可以压下去的。因为到这时为止，蒋介石的直系还只有六个师。总共八个军中，他只占一个军。第二军的党代表是李富春〔１３１〕同志，第三军的党代表是朱克靖〔１３２〕同志，第四军的党代表是罗汉〔１３３〕（那时还是共产党员），第六军的党代表是林伯渠〔１３４〕同志。但是，陈独秀机会主义的领导，在北伐〔１３５〕时继续犯了极大的错误。

北伐时，军事上是有绝对把握的。我们有精密的计划，加伦保证在双十节〔１３６〕前打到武汉。出师以前加伦曾请我转问中央，在北伐中是帮助蒋介石呢，还是削弱蒋介石，这一政治问题如何解决？我到上海请示中央。陈独秀说你们开个会商量商量好了（他这时之所以这样谦虚，是因为在北伐前，他在医院里毫无调查研究，不管政治形势有了什么样的变化，竟写了一篇反对北伐的文章，因此受到同志们的批评，也受到国民党的攻击）。开会时，又是张国焘代理主席，也没有真正讨论，只由他说了两句话，说北伐中我们的方针就是：是反对蒋介石，也是不反对蒋介石。所以在北伐战争中，一直到国民党三中全会前，对蒋介石的方针是不明确的，结果就是客观上帮助了蒋介石，而助成了蒋介石地位的提高。然而他的嫡系力量在战斗中是受挫的，第一军与第十七师首败于牛行，王柏龄率部队进攻南昌时全军覆没，王柏龄、缪斌〔１３７〕等被俘虏。这时蒋介石是惨败的。但机会主义者的陈独秀，并没有认识这些事实，并没有终止他的错误。

＊  这是在重庆中共中央南方局干部学习会上所做的报告。

