# 坚持抗日民族统一战线，反对蒋介石的新专制主义

中文马克思主义文库 -> 周恩来
坚持抗日民族统一战线，反对蒋介石的新专制主义
（一九四三年八月十六日）

自从建立抗日民族统一战线和开始抗战以来，党内党外，国内国外，对于蒋介石国民党〔１４〕亦即大地主大资产阶级统治的实质，多缺乏深刻的了解。只有毛泽东同志在抗战前就指出他的动摇性与被动性，抗战初期又指出他的妥协性与两面性，到今天更指出他的法西斯性。这些都是历史发展中的重要启示，而且有其时代意义的。因此，我现在便来讲中国的法西斯主义。
 

在这里，须先回答一些疑问。

有人问：为什么早不说蒋介石国民党是法西斯主义，偏偏现在来说？我们回答：抗战前一段时间里，我们的政策重心在争取他抗战，故强调其可变性与革命性，而只注意其动摇性与被动性就够了。抗战初期，我们的政策重心在争取他长期抗战，全面抗战，故强调持久战，强调团结、进步，反对投降、分裂、倒退，于是就要深刻地认识他的妥协性与两面性。等到现在，他的抗战作用日益减少，

反动方面日益扩大，并且著书立说，出了《中国之命运》一书。这样下去，必致抗战失败，内战重起。故我们就要公开地揭穿其法西斯实质了。过去只是因他的发展还没有象现在这样坏，故未强调，并不是没有什么法西斯派。

于是又有人问：蒋介石国民党既是法西斯主义，为什么又能抗战呢？我们回答：毛泽东同志告诉了我们，他是买办的封建的法西斯主义。因为他带买办性，所以当日本帝国主义打进来的时候，他能依靠别的帝国主义去抵抗，并利用民族救亡高潮，起着抗战的革命作用。同时，他又带封建性，所以当同盟国家渐渐重视中国民族抗战的时候，他又回到复古的排外的思想上去，起着反动的作用。并且正因为他是大地主大资产阶级，所以对内总是反对人民，惧怕人民，压迫人民的。他的抗战是决不会彻底的。无产阶级及其政党必须争取和巩固自己在民族民主革命中的领导权，决不能成为大资产阶级的尾巴。这一点，毛泽东同志在抗战前苏区党的代表大会上就警告了我们〔１３８〕的。

于是又有人问：法西斯主义是民族侵略主义，蒋介石国民党既还抗战以抵抗日本侵略者，为什么叫他做法西斯主义呢？我们回答：正因为这样，所以毛泽东同志叫他做中国的法西斯主义了。民族侵略主义是法西斯主义的一种特征，不是唯一的特征。季米特洛夫〔１３９〕报告中讲的法西斯主义的四种特征〔１４０〕，除了民族侵略主义这一点外，中国法西斯主义都是具有的。蒋介石国民党在历史上在现在，都是向人民向劳动群众施行最残酷的进攻，以至于进行镇压革命的内战，实行疯狂猖獗的反动和反革命，成为全中国人民的死敌。只是因为中国已处在殖民地半殖民地的环境中，中国大地主大资产阶级无力对外侵略。至于他对国内各小民族，还不是充满了大汉族主义的民族优越感和传统的理藩政策〔１４１〕的思想么？即在对外，国民党还不是有人在提倡大中华联邦应该圈入安南、泰国、缅甸、朝鲜甚至南洋群岛么？季米特洛夫曾经说过，因各国历史社会经济条件不同，因各国民族特性及国际地位不同，所以法西斯主义的发展和法西斯专政本身，在各国所采取的形式也是不同的。斯大林也早说过，德国法西斯主义的出现是表明资产阶级的力量已经削弱，资产阶级在内政方面已经不能采用旧的国会制度和资产阶级民主的方法来维持其统治，因此，就只得采用恐怖的手段〔１４２〕。在一定意义上，我们不也可以用于解释中国的大地主大资产阶级的统治么？所以我们也可以说，中国的法西斯主义是中国大地主大资产阶级--实际上就是蒋介石国民党和官僚资本公开的恐怖的专政，亦即特务统治。

于是又有人问：既是这样，为什么只反对国民党内的反动派，而不反对整个国民党呢？为什么只主张取消法西斯主义，而不提取消法西斯主义的头子呢？我们回答：这就因为以蒋介石国民党为代表的英美派大地主大资产阶级的两面性尚存在，尚未走到只有反动性的一面的地步，因为他们的抗战旗帜尚未倒下，国民党尚能影响一部分虽然是日渐减少的人民，尚不敢公开以法西斯主义为号召（不仅因为抗战，而且也由于中国大地主大资产阶级的软弱性而不能独立，因而也不敢公开承认）。故我们只反对国民党中的反动派，并不反对那些愿意抗战愿意民主的国民党员，并且还希望他们和我们一道去反对那些反动派。故我们只主张取消法西斯主义，并且还希望这些国民党员能自动地起来取消法西斯主义而真正实行孙中山的革命的三民主义。故我们只主张解散法西斯的特务组织，并不主张取消国民党组织。由于大地主大资产阶级的法西斯主义日渐抬头，甚至于写出一本《中国之命运》，提出最反动的取消中共的主张，故我们今天乃必须强调中国法西斯主义的危险及其实质。这不仅对于中国人民是一种警醒和教育，首先对于我们党内也是一种警醒和教育，并且这是最实际的肃清党内对于大资产阶级的投降主义的思想。

＊　这是《论中国的法西斯主义--新专制主义》的第一部分的节录，全文刊载于《周恩来选集》上卷。

