# 中国革命的动力和阶级关系

中文马克思主义文库 -> 周恩来
中国革命的动力和阶级关系
（一九四四年三月三日）


　　六大 〔１４３〕时阶级阵营有了新的分化，帝国主义、军阀都是反革命，资产阶级分 化到反革命方面。大革命时，民族资产阶级是反对北洋军阀〔１４４〕的，带有革命性。大革命失败，蒋介石同帝国主义勾结，同买办资产阶级勾结，并同江浙的财阀南四行〔１４５〕勾结，在上海、广州屠杀革命的工农〔１４６〕，所以共产国际〔１４７〕第九次扩大会议指出当时的反革命是三个：帝国主义，封建势力，资产阶级。在革命的方面也有分化，城市小资产阶级动摇，有的跑到改组派〔１４８〕与第三党〔１４９〕方面。反映到党内，党员有的脱党，有的畏缩，有的则拚命、发狂。因此革命的力量主要依靠工农，当然也不是把小资产阶级除外。共产国际第九次执行委员会扩大会议说中国向两个极端急剧分化，中间阶层是动摇的。毛泽东同志在井冈山给中央的报告中也指出主要是依靠工农。当时，在城市主要依靠先进的工人，一般的大多数的工人也有些畏惧；在农村，农民也有畏惧的；城市小资产阶级（小业主、小商人、学生等）也是畏惧的。"六大"把资产阶级算成反革命，但没有主张消灭资本主义。主要依靠工农，这是对的，不能把城市小资产阶级看成是革命的主要力量，否则便会使我们的思想混乱。但"六大"对城市小资产阶级的认识是不清的，虽然承认城市小资产阶级的革命作用，在动力上又认为只有工农，小资产阶级被除掉了，把当时某些上层小资产阶级分子参加资产阶级反对派，误认为全体小资产阶级背叛革命，因而在策略观点上错误了。

　　六大对反革命方面没有分析，特别是对民族资产阶级的认识与共产国际第九次执行委员会扩大会议不同。共产国际第九次执行委员会扩大会议认为反革命内部有矛盾，可以利用。"六大"则把这一点翻过来，认为他们虽然有矛盾，但反共是共同的，因此他们的矛盾无法利用。这种认识是错的。毛泽东同志说，把敌人看成铁板一块，这是关门主义的分析方法。事实上，南京政府是大地主大资产阶级的政府。另外还有不满意大地主大资产阶级的反对派，这是当时的第三营垒。这个第三营垒不是动摇于资产阶级与无产阶级之间的中间力量（这在当时的情况下是不可能的），而是统治阶级营垒中的反对派，是政府的反对派。第三营垒开始是改组派，以后改组派跑进政府，又有史量才、杨杏佛〔１５０〕等代表人物。蒋介石和汪精卫〔５４〕在一九二八年三四月本来要一起回南京，桂系反对汪精卫，汪精卫被阻在上海反桂系、反胡汉民〔９５〕，那时蒋、汪的矛盾不明显，但他们之间是有矛盾的。毛泽东同志的分析是正确的。

　　六大对农村阶级关系的分析基本上没有错，但不象毛泽东同志说的那样明确。"六大"决议中说对地主是没收一切土地，对富农不要故意加紧反对，在雇农反对富农时，我们要站在雇农方面（这同后来的加紧反对富农是不同的），但对小地主、富农没有进一步分析。

　　大革命时是四个革命阶级（无产阶级，农民，小资产阶级，民族资产阶级）。在新民主主义革命阶段中，这四者有区别：无产阶级是领导阶级；工农是基本的革命力量；小资产阶级有动摇性；资产阶级有两重性，有时参加革命，有时反对革命。大革命时，有些带买办性的资产阶级也投机参加了，这是国共合作初期的国民党右派，不能算作革命的动力。中国的民族资产阶级在反北洋军阀时是革命的，但也有软弱性，他们同帝国主义封建势力有联系。

　　武汉政府当时不是工农小资产阶级的政府，还有谭延闿〔１０５〕、孙科〔８３〕、唐生智〔１５１〕等代表地主资产阶级的人物坐在政府中，汪精卫则是代表资产阶级的。当时我们应把改变武汉政府为工农小资产阶级联盟当作努力的方向，当时实现这一种方向也是可能的。共产国际把国民党〔１４〕看做阶级联盟，内分左、中、右三派，右派是大资产阶级，中派是民族资产阶级，左派是工农和小资产阶级，包括我们党。但是那时我们党内的机会主义者却把我们从左派划出来，叫共产派，没有根据共产国际的指示在国民党中改造国民党，争取领导权。

　　现在我举出几个典型人物来研究一下。

　　（一）胡汉民。他是彻头彻尾的右派，是买办阶级的思想。他在广东时反对工农很厉害，反对农民组织武装队伍，站在机器工会〔１５２〕方面反对工人群众。他下面的大将有吴铁城〔１５３〕、马超俊〔１５４〕、古应芬〔１２６〕。刺廖仲恺〔１８〕便是他的弟弟胡毅生〔１５５〕干的，而他知道。

　　（二）蒋介石。他在大革命时主要是买办资产阶级的思想，但也不否认他有一点民族资产阶级的思想。在一九二四年国民党第一次全国代表大会时，蒋介石的民族资产阶级性多些，是中派，但与地主买办资产阶级有关系。在国民党第二次全国代表大会到"四一二"〔１５６〕这期间，群众起来，他便反共。一九二六年"三二○"事件〔１２２〕时他的立场已转到大地主大资产阶级方面，变为新右派，其灵魂便是戴季陶〔５５〕。"四一二"后他便成了反革命，代表大地主大资产阶级，在表面上却仍以民族资产阶级改良主义进行欺骗。

　　（三）汪精卫。他在大革命时主要是资产阶级的思想，虽有时很"左"，却不赞成没收地主土地，对工农有戒心。汪精卫在大革命初期并不积极，孙中山曾说：精卫、展堂已不能代表俄国式的革命〔１５７〕。国民党第一次全国代表大会的宣言，是孙中山先生委托鲍罗廷〔１１７〕起草，由瞿秋白〔１５８〕翻译，汪精卫润色的。孙中山先生逝世后，汪精卫乘机积极起来，在广东又被选为国民党和国民政府主席。一九二七年汪精卫由俄国回来，并没有想反蒋。他一到上海，蒋介石就找他开会。这时陈独秀找他写了个"汪陈宣言"〔１５９〕，此事被蒋介石知道了，汪精卫又想不发表，而报馆已上版来不及抽回。第二天汪精卫又去开会，吴稚晖〔１６０〕在会上大骂，汪精卫一怒，拔腿就跑到武汉去了。就这样他成了左派的领袖，大叫革命的向左边来，这完全是投机的。抗战期间他投降日本侵略者，成为卖国贼。

　　（四）廖仲恺〔８１〕。他是民族资产阶级的激进的代表，没有买办性。他是华侨，但不大富有，对帝国主义很仇视，反对封建势力，同情农民减租减息，但对工人反对中国资本家却采取调和的态度，对反对外国资本家则是赞助的。在黄埔军校〔３５〕，当我们青年军人联合会〔１０２〕反孙文主义学会〔８２〕时，他采取调和的态度。他是激进的资产阶级革命家。

　　（五）邓演达〔８９〕。他是小资产阶级的激进的代表，赞成土地革命，能与我们长期合作，是国民党中的左派。开始他相信无政府主义。当他从苏联回来，在讨论土地问题时，他和毛泽东同志的意见一致。他积极主张摧毁封建势力。他是农村出身的知识分子，与军队有些关系。在武汉时，若以邓演达为中心，不以汪精卫为中心，会更好些，而当时我们不重视他。大革命失败，他很苦闷，同俄国顾问一起走了，后来回国组织了第三党。虽然他在思想上是反对我们的，应该批评斗争，但在策略上应该同他联合。这人的人格很高尚，对蒋介石始终不低头。在"九一八"〔３８〕以后，蒋介石把他杀了。

　　在阶级关系的分析上，过去我们的缺点，一是公式化，一是定型化。所谓公式化，是教条地搬用俄国一九○五年反对沙皇和资产阶级立宪民主党的公式到中国来，对中国的资产阶级特别是民族资产阶级不能正确地认识，不能分析统治阶级内部的矛盾，把中国的小资产阶级看成与西欧资本主义国家的小资产阶级一样。所谓定型化，是把人定死了，不懂得人是会变的。蒋介石代表过民族资产阶级讲话，但不能把蒋介石的叛变看成整个民族资产阶级的叛变。对汪精卫也一样。看不到中国的阶级关系的复杂与变化，这是错误的。第三党是代表小资产阶级的。一九三○年邓演达回国后，曾找我们谈判合作反对蒋介石，可是我们没有理睬他，这是不对的。

　　至于大革命失败后，是否还可以用国民党和三民主义的旗帜问题，我也讲一下。假如邓演达没有走，仍与他合作，是还可以用国民党旗帜的。但在南昌起义之后，只有共产党是革命的，国民党叛变了，这时再用国民党和三民主义的旗帜，就会使群众的认识发生混乱。对三民主义不革命的方面应该批驳，对三民主义革命的方面应该保留下来，而我们当时却是对它全部否定了，没有给以历史的科学的分析。



　　＊　这是在延安中央党校所做的报告《关于党的"六大"的研究》的第二部分，全文刊载于 《周恩来选集》上卷。



