# 关于国共会谈的经验教训

中文马克思主义文库 -> 周恩来
关于国共会谈的经验教训
（一九四六年一月十二日）


　　从这两个时期的商谈〔２１９〕经验中，可以看出多年来两党的对立，要求得一个协议是 怎样的困难。因此我们觉得，从痛苦的经验中能够得到一点教训，来供这次政治协商会议诸位参考，或者比之空论过去较为有益。现就商谈中得到的四点经验教训，特向各位陈说：
 
　　第一点，要互相承认，不要互相敌视。既然商谈了，就是要政治解决，也就应该互相承认，不应互相敌视，尤其是商谈的双方代表，更要常常保持这种态度。我想在这里特别提出一位在抗战前半期奔走团结而故去的国民党〔１４〕朋友张淮南〔５６〕先生，应该对他表示纪念。彼此承认不可敌视，不但两党当事人应该如此，就是两党党员也应该如此。中共方面有这样一个信念，不管冲突怎样严重，我们对于已经承认了的并不改变，举几个主要的说：（一）我们认为孙中山先生的三民主义是今日中国所必需，我们承认，我们拥护，而且在我们自己的工作的区域内努力求其实现，决不因为冲突而抛弃自己已经承认的信念。（二）我们承认蒋先生在全国的领导地位，不仅在过去抗战的八年中，在抗战胜利以后仍然如此，这在民国三十一年中共七七纪念宣言中就提到此点，这句话，相隔四年多，现在证明了。（三）我们承认国民党是第一大党，我们始终尊重国民党在历史奋斗中得来的地位。（四）国民政府虽然是国民党一党统治，且到今天为止还是一党的政府，但是我们既然合作，所以从民国二十五年底以来，就没有不承认国民政府，也没有任何时期想推翻国民政府，而只是要求改组政府。只要看自抗战以来敌后的民主政府是地方性的，始终没有树立另外一个领导的中心政权，就可以证明。就是去年解放区筹备召开的解放区人民代表会议，也只是解放区人民的联合组织。这些承认，我们认为很重要，有此承认，可以证明不是敌视，而且是建立政治解决的基础。因此，我们同样要求国民党方面给我们以应有的承认，如我们过去所常提到的，中共合法地位问题、陕甘宁边区及其他解放区问题、中共领导的武装部队问题，因为承认是一事，承认了并不等于这些部队就不能整编，这些地方政府就不能改选。

　　第二点，要互相商量，不要独断。既然是政治解决，就是要互相协议，而不是一方面决定了，通知别方面去做，这样是无法求得解决的。此次政治协商会议开会，对于这一点若能处理得更好，一定可以树立起一个协商的楷模。过去许多纠纷，常因不能互相协商，徒然引起更多隔阂，树立更多障碍，朋友间处理一件事尚不能如此，何况两党的事，关系国家人民的事！我们希望，在政治协商会议中，对于国家人民的大事，能在协商的空气中求得解决。

　　第三点，要互相让步，不要独霸。既然政治解决，总是要于国家人民事业有利，既然于国家人民事业有利，那么两党之间，各方面之间，有什么不可以让步的？不错，立国的原则，象今天中国所需要的三民主义、民主国家制度，这些是不能让的，没有这种准绳与方针，就不能谈到合作。不过在这种大前提下，许多具体问题应该力求互让。如同过去所争执的军队问题、地方自治问题、人民权利问题，都应该在立国方针和制度之下，求得互让解决，不应要求独霸。有人说：你们只向政府要求民主权力，你们中共所领导的地区怎么样呢？我们诚意地回答，凡是我们向政府提出的，保证在我们活动的地区，不仅是同样实行，而且愿首先实行。假如我们实行得不够，愿意接受各方面的批评，谋更好的改革。假如大家不信，我们愿意欢迎任何人去考察、参观、指教。尤其欢迎因抗战而流亡在外的人士全部回乡，因为他们是那些地方的主人。

　　第四点，要互相竞赛，不要互相抵消。我们觉得既是政治解决，求合作，那么两党也好，各方面也好，总有些意见不同，应该在工作上竞赛，在地方上努力，而不是说你做好了，我不高兴，或者这一方面做好了，那一方面不高兴。因为好的事情都应该欢迎，不管行之何方，出之何党。只有这样，中国人民的力量，民族的精华，才能不互相抵消，才能有益于建国。

　　以上四点，是从九年来双方商谈中得来的痛苦经验与教训，虽似泛论，但很希望各位先生和全国人民了解，这是一种由衷之言。我们诚恳希望在这次政治协商会议上，能够认识到这方面。



　　＊　这是在一九四六年一月召开的政治协商会议第三次会议 上所做的报告的节录。报告全文刊载于一九四六年一月十三日《新华日报》。



