# 团结广大人民群众一道前进

中文马克思主义文库 -> 周恩来
团结广大人民群众一道前进
（一九四九年四月二十二日）


　　团结广大人民群众一道前进的问题，对党来说，就是党与非党人士合作的问题；对青年团来说，就是团员与非团员合作的问题。换句话说，也就是在广大人民中间，大家彼此怎样合作的问题。这是我们进行革命工作的一个很重要的问题。今天，我们要反对帝国主义和国内反动派，绝不是单靠共产党员、青年团员和干部所能做到的。今天，青年团员才二十万，连党员一共也不过三百万，比起全国人口四万万七千五百万来，这个数目是很小的，还没有达到百分之一。我们要带动全国人民前进，如果不同广大党外团外的人士合作，如何能做好呢！毛泽东同志在党的第七次全国代表大会上讲过，不要骄傲和急躁，要谦虚谨慎；同时，要团结广大的非党人士，要同党外人士合作。这几句话说起来容易，做起来就很难。党也好，团也好，过去都有这样一个不好的传统，就是一听说这个人是党员，是青年团员，就放心了，什么问题也没有了；一听说是非党员非团员，马上就另眼相看。这样来划一个鸿沟是非常危险的。因为不管是在工人中农民中和学生中，党员和团员总是少数，少数人自己划个小圈子把自己圈起来，用中国的古话来说，就叫"画地为牢"。
 
　　有的同志以为党内的同志什么都好，其实并不如此。一个同志一旦入党，那只是他在组织上入了党，思想上还不一定完全入党。就拿我来说，我也是团员出身，后来转为党员的。我虽然有二十七八年的党龄了，还不是犯过许多错误，每次谈起来，总觉得自己对革命有所欠缺，总觉得工作做得不很好，不能满意。党内每个人都有长处，我们应该互相学习。党外人士也有许多长处，我们也应该向人家学习。每个党员都要长期锻炼，经过千锤百炼才能成钢，不是一下子就能成功的。首先在生活上思想上作风上需要长期的考验。所以，我们入党入团以后，要很好地学习，开展批评与自我批评，这样才能很好地前进。这是对党员团员起码的要求。党外团外的人，因为他们没有进党进团，当然有些事情不知道，比我们差一点，但并不是没有长处。比如在农村中，许多农民比我们勤劳勇敢，比我们有办法；在工厂中的广大工人，比我们能生产，比我们能创造；广大的劳动知识分子、学生，有的在许多方面比我们强。不过他们当中有些人觉悟得慢一点，或者一时还不愿意入党入团，我们要帮助他们，启发他们，把他们当作朋友看待，互相学习。不要因为他们不是党员团员就另眼看待，而一旦入党入团就什么都放心了，这种态度是幼稚的，这个毛病是青年人容易犯的。

　　我们怎样解决这个问题呢？就是要在观念上，把党外凡是能够争取的、能够和我们合作的人士，当成党内干部一样来看待。我们先划一个最大的圈子，把亿万人民群众团结在一起，共同对付最反动的地主阶级和官僚资产阶级集团，孤立他们，反对他们，打倒他们。人民内部，当然还有不同的阶级和阶层，最跟我们接近的是工人、农民、学生和劳动知识分子，其次是小资产阶级，再次是民族资产阶级、开明士绅及其他爱国分子，我们要分别对待，争取他们，教育他们。共产党青年团要有这样的气概。我们今天是新中国的主人，不能讲起来是无产阶级领导的人民大众的政权，人民民主的国家，可是做起来却是一小圈圈人，不象个领导者，反倒象个孤立主义者，做的跟说的不一样。青年人一定要非常谦虚，不要骄傲，应该觉得自己差得很，事情还做得很少；同时，我们还要团结所有能够争取的人。这就是说，对自己应该自勉自励，应该严一点，对人家应该宽一点，"严以律己，宽以待人"。当然，这个宽不是没有原则的。我们首先是区别革命和反革命，对反革命不能存在任何幻想。我们这个大圈子，就是要把四万万七千五百万人中最反动的几万、几十万、百把万、几百万划出去。同时还要看到，这里边有许多人还可以改造，比如地富分子，一旦土地改革以后，经过三五年的教育、改造，他们是可以慢慢地改变的。当然，不是一下子能够做到，但是前途还是有希望的。我们要有步骤地去做，使他们参加生产，逐渐地改造成为新人，不是囫囵吞枣，一下子都混进来。但是，我们在精神上要有这样的气概，把他们都改造过来，领导起来。

　　最近我们同国民党代表团〔２３４〕谈判。有的同志说，国民党代表团就那么几个人，费这样大的功夫，多麻烦！虽然是几个人，但是他们后边有一群。在他们影响下的军队、政府、党部里边的人以及公教人员，总有几百万，加上这些人家庭里的妻子儿女，就是千把万。对于这些人，他们讲的话比我们讲的影响更大一点。他们有代表性。争取几个头子就影响后边一批，有利于我们渡江，就是渡江以后也会发生作用。所以，对于反动营垒中可能分化出来的人物，要争取他们，教育他们，帮助他们。

　　这样一想，我们就看得广了，不会把自己划在一个小圈子里边了。用这样的精神去做事情，才能团结更多的人和我们一道走，同时反过来，我们还跟他们学习。我们要知道，有不同的意见的人跟我们来讨论、争论，真理才能愈辩愈明。辩证法就它的希腊字源来说，意思就是进行论战，联共党史上不是也讲了这一件事情吗〔２３５〕？在历史上，许多哲学家、政治家也喜欢争辩。圣人都喜欢辩论，何况咱们后生小子乎！为了寻求真理，就要有争辩，就不能独断。什么叫独断？就是我说的话就对，人家说的话就不对，那还辩什么呢？你的意见是神圣不可侵犯的，那谁还跟你辩？即使自己有很多对的意见，但是还要听人家的意见，把人家的好意见吸取过来，思想才能更发展，辩证法就讲矛盾的统一，只有通过争辩，才能发现更多的真理。所以，青年人要学习，就要多听各方面的意见，然后加以集中。也有这样一种人，因为东听一句西听一句，把自己弄得惶惶无主，本来开始他还有主意，这样一听就失掉了主意。我们要听各方面的意见，但是还必须加以思考。一个人生着两个耳朵，能听话；生着两只眼睛，能看东西；生着两个鼻孔，能闻味。听话，能听正面的，也能听反面的；看颜色，能看白的，也能看黑的；闻味，能闻香的，也能闻臭的。所以，人体的机能也是合乎辩证规律的。我们必须听各方面的意见，辨别是非，从青年的时候起，就培养这样的思考力。还有这样的同志，见了党内的人和团内的人不怕，可是怕见生人，就象小姑娘一样。怕什么呢！我们应该去团结他们，教育他们，改造他们。有了这样的精神，在社会上才能团结更多的人一道前进。只有经常接近广大的群众，才能增加自己的勇气。一个人坐在房子里孤陋寡闻，这样不行，应该在千军万马中敢于与人家来往，说服教育人家，向人家学习，团结最广大的人们一道斗争，这样才算有勇气，这种人叫做有大勇。我们青年很需要养成这种作风。



　　＊　这是在中国新民主主义青年团第一次全国代表大会上的报告第四部分的节录，全文刊载于《周恩来选集》上卷。



