# 无党派民主人士的称谓与实质

中文马克思主义文库 -> 周恩来
无党派民主人士的称谓与实质
（一九四九年六月十九日）


　　无党派民主人士，是在中国革命的具体历史条件下发展形成的。他们在形式上没有结成党派，但实质上是有党派性的。
 
　　在抗日战争时期，我们大家所从事的民主运动，受着国民党〔１４〕反动统治的严重压迫。因此，有很多民主人士，在国民党统治区只能单枪匹马地和国民党反动派作斗争。在当时的情况下，若形成一个组织，就要经过许多手续和挫折，那是很困难的。当然也有形成组织的，如民主同盟〔２０８〕、国民党革命委员会〔２３６〕和民主建国会〔２３７〕。这三个大的组织联系了许多组织，还有秘密组织〔２３８〕。但是，也还有许多人一直是孤军奋斗的，比如今天在座的代表中就有：一直领导着一支文化大军的郭沫若〔２３９〕先生，在国民党统治下受着严重压迫的马寅初〔２４０〕先生、李达〔２４１〕先生，在北平遭到拘捕的符定一〔２４２〕先生，在上海一直奋斗的宗教界人士吴耀宗〔２４３〕先生，等等。他们虽然都没有组织一个政党或者政治团体，但却领导着很大一批民主人士，联系着许多方面的人士在奋斗着。奋斗的结果，迫使国民党不得不承认和允许在各党派以外从事政治活动的一些民主人士也参加旧政协。当然，由于当时跟国民党协商时不得不带有若干妥协性，所以在参加旧政协的人中也有不是为民主而奋斗的、由国民党方面邀请的几位"社会贤达"〔２４４〕。这些人后来参加了伪国民大会〔２４５〕，参加了伪国民政府。因此，大家一听到"社会贤达"这个名称就有不快之感，尤其是郭沫若先生就很痛恨这个名称。他在香港同各民主党派首先响应中共去年"五一"号召〔２４６〕的时候，就用了无党派民主人士的称谓。他是以参加民主运动的这样一个身份来领头响应的，事实上也的确有许多位这样的人参加了民主运动。在他们诸位到哈尔滨以后，中共跟他们电报磋商的时候，也觉得有无党派民主人士这一项为好。因为要承认这些不属于各民主党派的先生们过去的确经过了长期奋斗，所以要请他们参加会议。当然，这一方面的代表人物一定要经过各方面的协商。

　　现在有一个分类问题，即把无党派民主人士摆在哪一类代表里为好的问题。就是说甲项里头是民主党派类的代表，把无党派也摆在党派里头，好象在文字逻辑上不大通，这就请大家来讨论。

　　回答文字逻辑问题的时候，我们也不能不想到问题的本质。因为这一部分人士，也是长期参加民主政治活动的，参加反对帝国主义、封建主义和官僚资本主义的斗争的。在阶级斗争的社会里，不管是哪一个社会，总是大 部分人反对一小部分反动派。这种反对反动派的一大群人的活动也就是政治活动。所以从广义上说，这就是一种党派性的活动，只不过有些民主人士没有党派的组织罢了。正确地写出来应该是：没有党派组织的有党派性的民主人士。当然，在座的诸位假使还要把它摆到其他类别里，那也是可以的。我们把政协代表分成四类：第一类是指党派性的；第二类是指区域性的，包括已解放了的地区和待解放的地区；第三类是中国人民解放军；第四类是人民团体。从广义来说，第四类也还不仅是团体，比如海外华侨，不一定是由团体选出的，而是由我们公推的。另外华侨还有地域的性质。不过如果把它摆在地域里面，好象我们的国家要发展到海外了，那就不好。所以还是把华侨摆在团体这一类为好。再如少数民族，凡是在已经解放的地区，现在已形成了政权组织或是自治区的，就摆在区域代表里面了。但是在没有被解放地区的少数民族团体和人士，就摆在团体或民主人士里面。这些分法是大体的分法，广义的分法。严格地说，每一类里面都可以再把它细分成多少小类，但这样做起来就比较不容易。目前这种分法是概括性的，是本着原来同各方面协议的精神来分的，是比较符合实际情况的。这样的解释是不是合适，请大家讨论。

　　关于特别邀请的代表就不同一些。这是根据目前的发展情况来确定的。被邀请的人物当然总是在这一个时期有所表现的，如在人民解放大军胜利推进当中，对推翻反动政权、协助人民解放军和平接管等方面立过功的；或是目前我们认为需要特别邀请他来参加的一些人物。如：在上海主张和平、反对国民党内战，以后到石家庄谈判的颜惠庆〔２４７〕先生、章士钊〔２４８〕先生、江庸〔２４９〕先生；对北平和平解放立过功的傅作义〔２５０〕将军、邓宝珊〔２５１〕将军；这一次南京反动政府派出的代表团到北平后极力赞成和平协商，最后赞成共同商定的和平条款即八条二十四款的张治中〔２０３〕先生、邵力子〔２５２〕先生，等等。这些人物都是考虑在邀请之列的。虽然这些先生并不属于过去的民主运动的人物，但是在这个时期中立了功，或有所表现，是值得我们邀请的。当然也不仅限于这几位。我们要从长计议，由常委会考虑协商，然后拿到全体会议上通过。所以，特邀的人士和无党派民主人士表面上好象可以作为一类，其实并不是一类。这些被邀请的人士，不一定是无党派的，如张治中先生、邵力子先生，你说他无党派行吗？不能那么说。他们是另一种情况。将来邀请的时候应该注意这些情况，把他们摆在无党派是不合适的。整个政治协商会议的基本阵容是五百人左右，一部分特别邀请的人士增加到这个基本阵容里来，更可以增强团结性。



　　＊　这是在新政治协商会议筹备会第一次全体会议上的发言。



