# 关于人民政协的几个问题

中文马克思主义文库 -> 周恩来
关于人民政协的几个问题
（一九四九年九月七日）


　　现在我把新政治协商会议筹备会常委会关于参加中国人民政治协商会议第一届全体会议代表人选的协商情况和中国人民政治协商会议组织法、中华人民共和国中央人民政府组织法的主要内容，向到会的代表做一个报告。
 
　　为什么要做报告呢？因为想在中国人民政治协商会议全体会议开会前，使大家对上面说的几方面的情况有一个全貌的了解，以便能引起大家对这些问题的注意和研究。到开会的时候才把只有少数人了解的东西或者是临时提出的意见拿出来让大家来讨论决定，这是旧民主主义议会中议事的办法。新民主主义议事的特点之一，就是会前经过多方协商和酝酿，使大家都对要讨论决定的东西事先有个认识和了解，然后再拿到会议上去讨论决定，达成共同的协议。

　　第一，关于参加中国人民政治协商会议的单位及其代表名额和人选问题。

　　首先，应该说明政协这个名称有一个改变。原来叫做新政治协商会议，在第一次筹备会全体会议中也这样叫过。后来经过新政协组织法起草小组的讨论，觉得新政协和旧政协这两个名称的分别不够明确，便改成中国人民政治协商会议。筹备会常务委员会同意这个修改意见，将来还要经过筹备会全体会议正式通过决定。

　　从新政协发起到现在，形势有了很大变化。一九四八年五月一日，中国共产党中央委员会发布了"五一"口号〔２４６〕，向全国人民、各民主党派提议召开新政治协商会议，磋商国是，并决定如何召开全国人民代表大会，成立民主联合政府。当时很快得到在香港的各民主党派，在上海、北平和海外的各人民团体、华侨人士的响应，使我们很高兴，于是便邀请各单位参加并筹备召开新政治协商会议。那时我们所设想的这个会议，不过是个百八十人的会议而已，没有想到象今天有这么广大的解放地区和在交通这样便利的情况下来开这样大规模的会。这是由于革命形势发展迅速的缘故。国民党〔１４〕反动政府的统治已经崩溃了。在全国革命战争中，我们取得了基本的胜利。全国的形势和世界的形势都已经改观了。

　　这次中国人民政治协商会议具有全国人民代表大会的性质，所以我们对它不得不更加谨慎。为了扩大政协的代表性，首先要扩大参加政协的成分、单位和名额，使它能够代表全国各民主阶级、各民族人民的愿望和要求。这种谨慎是从政治上考虑的，是以目前政治形势和政治任务的要求为主要根据的。新政协筹备会组织条例规定得很清楚，参加会议成员的条件应该是"拥护新民主主义，反对帝国主义、反对封建主义、反对官僚资本主义及同意动员一切人民民主力量，推翻国民党反动统治，建立人民民主共和国。"这是大家一致通过的意见。我们邀请代表就根据这个政治标准。

　　我们既然是实行新民主主义，反对帝国主义、封建主义和官僚资本主义，代表中当然不能包括一切反动党派和反动分子，即反对新民主主义而拥护帝国主义、封建主义和官僚资本主义的分子。只有这样，才能代表全国人民，而为全国人民所信托。这就是确定代表时的严肃性。毛主席说得很清楚，我们的政权是属于工人阶级、农民阶级、城市小资产阶级和民族资产阶级四个阶级联盟的。此外，政协代表中还包括从封建阶级、官僚资产阶级中分化出来并投向革命阵营的爱国民主人士。这就是确定代表人选时的广泛性和灵活性。

　　我们在确定代表名额和人选的时候，不是平均主义的，而是有重点的。重点在哪里呢？就是"以工农联盟为基础，以工人阶级为领导"。人民政治协商会议中四十六个单位的名额和人选的确定，始终都体现着这一重点。参加这次会议的不仅有各民主党派，有多年来为民主事业而奋斗的无党派民主人士，还有各解放区的代表。各解放区在解放战争中担负了重大的任务。我们还承认解放军的代表权，因为人民解放军不单是军事组织，又是政治组织，不仅是普通军队，而且是工作队。他们消灭敌人，从事政治工作，做人民的勤务员。因此，他们所代表的不仅是军队，而且代表着他们出身的人民，首先是农民。这是来自人民属于人民的队伍。解放军代表的参加也体现了"以工农联盟为基础，以工人阶级为领导"的重点。除此以外，还有待解放区的代表，包括华南解放军的代表。

　　有了重点，同时又照顾到了各个方面。在各人民团体的代表中，除工人代表、农民代表外，还有妇女代表、青年代表、学生代表、文艺工作者代表、新闻界代表、工商界代表、教育工作者代表、自然科学工作者代表、社会科学工作者代表。我们也照顾到还不能立刻组织团体的方面，如自由职业者代表。我们还照顾到海外华侨和少数民族。这就是参加人民政治协商会议的四十五个单位产生的大体情况。但是尽管如此还是不够全面，所以又设了一个特邀单位。其中有在中国整个民主革命阶段中，始终站在正义事业方面的，如孙夫人〔２５３〕和她领导的救济单位。也有从事科学研究和工业建设的人才，如中央研究院陶孟和〔２５４〕先生和资源委员会钱昌照〔２５５〕先生。也有一向或在某一个时期和我们有某种联系和朋友来往，同情人民事业，一旦解放了便站在人民这方面的，如福建萨镇冰〔２５６〕先生，张难先〔２５７〕先生。也有从事民主运动在解放区服务很久的朋友，如陈瑾昆〔２５８〕先生。也有是参加这次和平运动有功的，如上海人民代表团颜惠庆〔２４７〕先生，南京和平代表团张治中〔２０３〕、邵力子〔２５２〕等先生。程潜〔１０７〕先生也是响应和平号召投到人民方面来的。起义的将军有的作为解放军代表参加会议，如吴奇伟〔２５９〕将军，曾泽生〔２６０〕将军，张轸〔２６１〕将军，也有的参加到特邀单位中。海军、空军的代表也在特邀单位中。还有愿意为建设新的人民的艺术而服务的人物，我们也邀请了，如周信芳〔２６２〕、梅兰芳〔２６３〕、程砚秋〔２６４〕几位先生。邀请的代表还有劳动界护厂有功的工人、劳动英雄和在各解放区单位安排不下的，如晋察冀的戎冠秀〔２６５〕先生。

　　总之，决定全部代表人选是根据了人民民主革命的原则。我们重视由革命战争中锻炼出来的朋友，在土地改革和敌后根据地斗争中锻炼出来的朋友，在国民党统治时期的民主运动中锻炼出来的朋友，脱离反动派而起义的朋友，保护国家器材有功的朋友，使这次政治协商会议成为集中代表全国人民力量的大会。

　　在协商当中，除了政治根据外，我们还要从组织方面说几个问题。（一）党派的标准。凡是在去年"五一"前就建立了组织或已开始建立组织，并且很快地响应了"五一"号召的，就可以作为参加单位。现在参加筹备会的十四个党派单位都是按照这个标准决定的。其中有三个单位，一是九三学社〔２６６〕，一是台湾民主自治同盟〔２６７〕，一是新民主主义青年团，需要做些说明。九三学社是在抗战后期成立的，在民主运动中起了很大的作用，并且响应了"五一"号召。因为当时在国民党的统治之下，不能公开发表意见，所以一直到北平解放时才公开活动。台盟是一个革命的组织，"五一"前就从事台湾人民的解放运动。新民主主义青年团早就筹备，今年才成立，它的前身是青年救国会〔２６８〕、民主青年同盟〔２６９〕等革命组织，在共产党的领导下对革命贡献很大。除了这十四个党派外，我们认为有些组织要分别研究对待。如孙文主义革命同盟〔２７０〕，曾在伪立法院进行过斗争，我们就一方面劝说他们加入国民党革命委员会〔２３６〕，另一方面把个别人列入特邀单位。又如民社党革新派〔２７１〕，我们劝他们加入民盟〔２０８〕。当然这样做还要看这两个组织自己的意见。和这类似的其他个别人，也被邀请参加，如汪世铭〔２７２〕先生。（二）个人参加的，我们注意到他在社会上的影响和代表性。（三）各单位有自己的标准。我们要求各代表看名单时，不要连起来比较看，应该看其代表的单位在民主运动中所起的作用如何。青年学生的代表，虽然不能与其他代表来比，但他们在中国学生当中却有代表性。还有一些情况，有些人在这一个单位可能是正式代表，但在另一单位却是候补代表。正式代表和候补代表的差别只是个表决权的问题，但是新民主主义的议事精神不在于最后的表决，主要是在于事前的协商和反复的讨论。（四）代表名单的产生是经过各方面反复协商的。这样能使各方面的意见得到尊重。（五）参加的代表，一般的都请他们到会，不要只是列名，否则就不能集中大多数人的意见。因此，原则上能够来的才确定他为代表，不能来的就不提名。不过也有个别特殊情形经过筹备会常委会的同意可以列名而不来的，如年纪过高的萨镇冰先生。现在的名单一共是六百五十五人，特别邀请的名单中或者还可能增加若干人，将来代表的总数，可能超过六百六十人，当然也可能就是六百六十人。

　　即将开幕的中国人民政治协商会议的确表示了全国人民力量的大团结，从代表性这一点来说，可以说每个人都有他的代表性。但是仍有许多有代表性的人，象彭德怀〔２７３〕同志等，因为他们不能来，所以没有邀请。至于个别的遗漏，也在所难免。不过我们觉得筹备会常委会对于这一工作，一般地说已经尽了责任。

　　第二，关于中国人民政治协商会议组织法草案。这个草案已经在几天前送达各位代表。现在讲几个主要问题。首先，政协是沿用了旧的政治协商会议〔２７４〕的名称，但以它的组织和性质来说，所以能够发展成为今天这样的会，决不是发源于旧的政协。

　　从五四运动〔１３〕以来，中国有了共产党，有了第一次国共合作，有了大革命运动，经过了四个革命阶段即北伐战争〔１３５〕、土地革命、八年抗战和最近三年来的人民解放战争，才形成今天中国人民政治协商会议这样的组织。可以说这是一百多年来民族民主革命运动牺牲奋斗的果实，也可以说是三十年来新民主主义革命运动获得胜利的集中表现。假如没有一百多年来革命运动的历史积累，尤其是三十多年来的新民主主义革命运动，便不可能有今天这样济济一堂的政治协商会议。所以，这个会议可以说是新民主主义运动的一次总结。

　　一九二四年国共两党实现第一次合作，那时中国共产党便提出了统一战线的主张同孙中山先生合作了。不幸蒋介石破坏统一战线，走上反动的道路，造成了二十二年的反动统治。中国共产党被迫转入地下，深入农村，发动了土地革命。后来中国共产党主张团结抗日，多次号召组织统一战线。由于国民党反动派坚持一党专政，所以在革命的后三个阶段内，统一战线没有能够发展成今天这样宏大的规模。但这一政策始终贯彻于四个阶段，直到现在革命战争快接近全面胜利的时候，才有可能召开这个会。肯定地说，这一组织便是中国共产党过去所主张的民族民主统一战线的形式。它绝对不同于旧的政治协商会议，旧的政治协商会议已经让国民党反动派破坏了。可是大家都熟悉这一组织形式，所以今天我们沿用了这个名称，而增加了新的内容。

　　中国人民政治协商会议是一个包含了工人阶级、农民阶级、城市小资产阶级、民族资产阶级和一切爱国民主人士的统一战线组织。既然是这样一个组织，就不应该开一次会议就结束，而应该长期存在。中国人民政治协商会议是个长期性的组织。这一点相信大家都是赞成的。

　　政协组织所包含的成分，是非常广泛的。它的任务是团结工人阶级、农民阶级、小资产阶级、民族资产阶级以及一切爱国民主人士、国内少数民族和海外华侨，共同反对帝国主义、封建主义和官僚资本主义，建设新民主主义的新中国。这也就是中国人民政治协商会议奋斗的目标。凡是同意这个目标的各民主党派、人民团体、少数民族和海外华侨，我们都欢迎他们的代表来参加这个会。而事实上，所有这些人现在都已经团结起来，并共同为这一目标而努力了。

　　中国人民政治协商会议将在最近召开全体会议，全体会议闭幕后将设立全国委员会，领导实行全体会议的决议。另外在全国中心城市、重要地区和省会，根据需要设立地方委员会。现在各地召开的各界代表会议，实际上就是地方的政治协商会议，也可以说就是中国人民政治协商会议的地方委员会。我们要通过这个组织来进行地方的统一战线工作。由于人民政协全体会议的范围太大，不容易经常召集，所以只好拟定三年召开一次。至于地方委员会，可以适当多开一些。

　　在全国各地方未能实行普选以前，中国人民政治协商会议和它的地方委员会分别执行全国和地方的人民代表大会的职权。我们现在即将举行的中国人民政治协商会议第一届全体会议，便是执行全国人民代表大会的职权来通过中国人民政治协商会议的组织法、共同纲领和中华人民共和国中央人民政府组织法，并选举中央人民政府委员会。人民政协全国委员会，便是同中央人民政府协议事情的机构。一切大政方针，都先要经过全国委员会协议，然后建议政府施行。等到将来根据全国革命形势的发展和土地改革的情况及人民进步的程度，才可能把普选由个别地方逐渐推广到全国，召开全国人民代表大会。那时中国人民政治协商会议全体会议，才不再代行全国人民代表大会的职权，但是它仍将以统一战线的组织形式而存在，国家大政方针，仍要经过人民政协进行协商。地方委员会的情形也是如此。由此我们可以看到，中国人民政治协商会议是负有伟大的建国责任的。建设新中国，必须经过参加人民政治协商会议的各民主党派、各人民团体、国内少数民族、海外华侨和一切爱国人士共同努力，必须动员全国人民共同参加。我们要很好地组织起来，团结起来，团结一切人民力量，来完成这一伟大使命。

　　中国人民政治协商会议组织法只打算写出人民政协的组织和任务，而不在工作方法方面详细列举，以免束缚工作的进行。希望各单位对这个草案讨论后提出意见，然后由中国人民政治协商会议第一次全体会议来决定。

　　第三，关于中华人民共和国中央人民政府组织法草案。

　　这个组织法草案首先表明国家的制度是新民主主义，是由工人阶级领导的，以工农联盟为基础的，团结各民主阶级和中国境内各民族的人民民主专政的国家。这是大家所同意的。现在只须解释一个问题，就是国名问题。在中央人民政府组织法的草案上去掉了中华人民民主共和国的"民主"二字，去掉的原因是感觉到"民主"与"共和"有共同的意义，无须重复，作为国家还是用"共和"二字比较好。辛亥革命〔１０〕以后，中国的国名是"中华民国"，有共和的意思，但并不完全，可以作双关的解释，而且令人费解。现在我们应该把旧民主主义和新民主主义区别开来。因为在辛亥革命时期，俄国十月革命尚未成功，那时只能是旧民主主义的。在那以后由不完备的旧民主主义进步到完备的新民主主义。今天，为了使国家的名称合乎国家的本质，所以我们的国名应该是中华人民共和国。我们的国家是属于四个民主阶级的人民民主专政，反动的封建阶级、官僚资产阶级的分子不能列入人民的范围。等到他们彻底悔悟和改造后才能取得人民的资格。中国的少数民族也应该包括在中华人民共和国之内，承认他们的自治权。因此，我们认为中华人民共和国这个国名是很恰当的。

　　既然国名重新定了，是重新纪元呢，还是采用公元纪元？中央人民政府组织法上没有讲到，这将在第一届全体会议上讨论决定。

　　关于国家制度方面，还有一个问题就是我们的国家是不是多民族联邦制。现在可以把起草时的想法提出来，请大家考虑。中国是多民族的国家，但其特点是汉族占人口的最大多数，有四亿人以上；少数民族有蒙族、回族、藏族、维吾尔族、苗族、夷族〔２７５〕、高山族等，总起来，还不到全国人口的百分之十。当然，不管人数多少，各民族间是平等的。首先是汉族应该尊重其他民族的宗教、语言、风俗、习惯。这里主要的问题在于民族政策是以自治为目标，还是超过自治范围。我们主张民族自治，但一定要防止帝国主义利用民族问题来挑拨离间中国的统一。如英帝国主义对西藏及新疆南部的阴谋，美帝国主义对于台湾及海南岛的阴谋。不错，这些地方是有少数民族的，但是他们一向是在中国领土之内。清朝压迫少数民族的政策，是对满族以外的民族进行欺骗和屠杀。北洋军阀政府继续了这样的政策，国民党反动政府更加深了这样的政策。我们应该改变这样的政策，把各民族团结 成一个大家庭，防止帝国主义的挑拨分化。陈嘉庚〔２７６〕先生这次到东北参观，同时也到了内蒙古自治区，他回来后说现在内蒙的汉、蒙二族合作得很好，犹如兄弟一样。这消息我们听了非常高兴，这足以证明我们民族政策的成功。

　　任何民族都是有自决权的，这是毫无疑问的事。但是今天帝国主义者又想分裂我们的西藏、台湾甚至新疆，在这种情况下，我们希望各民族不要听帝国主义者的挑拨。为了这一点，我们国家的名称，叫中华人民共和国，而不叫联邦。今天到会的许多人是民族代表，我们特地向大家解释，同时也希望大家能同意这个意见。我们虽然不是联邦，但却主张民族区域自治，行使民族自治的权力。这一次民族方面的代表的确是比较少，这是一件遗憾的事，原因是有好些少数民族的地方还没有得到解放，不容易找到代表来。内蒙古是解放了的，它便有了双重的代表，少数民族方面的代表和区域代表。

　　关于政权制度方面，大家已经同意采用基于民主集中制原则的全国人民代表大会的制度。现在凡是通过普选方式产生出来的会，我们叫做大会，例如人民代表大会。凡是通过协商方式产生的会，我们就叫做会议，例如人民政治协商会议。大会和会议名称的区别就在这里。将来人民代表大会，是要经过普选方式来产生的。关于普选，本来应该做到普遍的、平等的、直接的、不记名的投票，但这对中国现在的情况来说，是非常困难的。

　　在资本主义国家里，有许多不是普遍选举的现象，例如根据阶级、民族、宗教信仰、教育程度、财产、性别等给普选加以种种限制。这种选举我们不要，我们要做到真正的普选，不分性别，不搞种族歧视，不分宗教信仰，不论财产多寡和教育程度的高低，只要达到适当年龄，没有其他特别原因，便可参加普遍的选举。关于直接选举的问题，中国是全世界人口最多的国家，直接选举目前实在不容易办到。至于平等这一项，假如按人口做比例也不行，农民占全国人口的百分之八十，那么选出来的代表就会大多数是农民，这种情形还不能够适应于今天革命的形势和要求。不记名的秘密投票方式，依照目前人民的文化程度来说，也是做不到的，许多地方只能用举手或投豆的方式。由于有上述种种的情况，我们只能强调提出普选一点，其他各项有待将来条件成熟时再逐步实现。单就普选一点，三年后能不能真正做到，还是一个难题。中国革命的发展是不平衡的，我们只能逐步由客观条件成熟的地区先行普选。

　　关于政府组织问题，中央人民政府的组织系统是在中央人民政府委员会〔２７７〕下面分设许多机构，按照民主集中制的原则来分工的。这一点相信大家不会反对，而我们所要反对的是旧民主主义的议会制度，因为它不是事前协商，只是便于剥削阶级政党间互相争夺，互相妥协，共同分赃的制度。他们幕后分侵略殖民地的赃，分剥削本国劳动人民所得的赃，争夺不休。而我们却是长期合作，不是彼此互相交替。辛亥革命后，袁世凯〔３〕、曹锟〔６〕、段祺瑞〔５〕等都搞过议会制、总统制等方式，结果换来了封建买办的专政。这种痛苦的经验教训，在座的陈叔通〔２７８〕老先生、沈钧儒〔２２２〕老先生，都曾亲自体验过。到了一九二四年，国共合作，中国才找到一条好路，于是便有了轰轰烈烈的大革命。而到了抗日战争时期和解放战争时期情况又不同了，那时，大家为民主拼命奔走，也仅仅得出了一个伪宪法〔２７９〕，真正的民主是没有的。这是我们都亲身经历过的经验教训。

　　现在，根据我们民主集中制的组织系统，在人民代表大会闭幕期间的最高权力机关，是中央人民政府委员会，它是经过民主方式产生的。而对工作的经常指导，又是集中在由民主方式产生出来的主席身上。主席下面的组织，首先是政务院，其他还有人民革命军事委员会，最高人民法院和最高人民检察署。

　　政务院底下，设有三十个单位，这个数目看起来很不少。清朝只有六个部，后来又分为八九个部，北洋军阀政府的国务院，也只有八九个部，但每个部下面却设有许多机关，有些机关连部长也管不了，直接由最高当局来指挥，造成官场上互相冲突、互相牵制的现象。这种情形，我们新中国是不允许的，所以政务院下设有三十个单位。事实上苏联今天有六十个部，比我们更多，当然我们也不是要模仿苏联，一切还是由本身的需要出发。

　　政务院不可能经常领导这三十个单位，所以下面设四个委员会协助办理。这四个委员会是：政治法律委员会，财政经济委员会，文化教育委员会，人民监察委员会。政法委员会下辖五个部门，财政经济委员会下辖十六个部门，文化教育委员会下辖六个部门。另外还有外交部，华侨事务委员会和情报总署，是直属政务院的。一共是三十个单位，重点在于财政经济，其次是文化教育。这样做法会不会降低工作效率呢？根据过去解放区政权建设的经验来说，是不会的，而且还可以把工作推行得既快又好。政务院下面设立人民监察委员会的目的是为了建立监察制度，监察行政部门，如公务人员是否执行了政府的决议和政策，是否有贪污腐化等情形。

　　军事方面，我们估计国内解放战争还要打一年左右，才能全部、彻底、干净地消灭反动派。因此，人民革命军事委员会要继续存在，同时将来也要领导巩固国防的工作。

　　最高人民法院和最高人民检察署，受中央人民政府委员会的领导，这不用多做解释。

　　至于地方的统一制度，目前因为全国还没有完全解放，所以它的组织如何，只好留给将来中央人民政府去决定。

　　现在报告已经完了，请诸位根据这三个文件，多加考虑，提出更多更好的意见来共同商讨。



　　＊　这是在中国人民政治协商会议第一届全体会议召开前向政协代表做的报告。



