# 长期合作，共同建设新中国

中文马克思主义文库 -> 周恩来
长期合作，共同建设新中国
（一九五○年四月十九日）

关于党派问题，包括资产阶级前途问题，我想讲几句话。现在大家有一个问题，究竟什么时候进入社会主义？这个问题在《共同纲领》中没有写明，因为当时条件还不成熟，过早提出来反而会乱了脚步。当然，社会主义的前途并不因此而消失。一个阶级，一个政党都有自己发生、发展和消亡的过程。共产党到共产主义社会也是要消亡的，但我们党并不因此而不努力工作。我今年已经五十二岁，既然还活着，就要努力工作。这不是很好理解的事嘛。社会主义社会，当然是没有资产阶级了。但在今天，民族资产阶级还有它的历史任务。民族资产阶级过去是起过进步作用的，我们不能主观地抹煞历史。一个人也好，一个阶级也好，只要尽了历史责任，历史就会写上一笔，自己也会从中得到安慰的。因此，虽然资产阶级迟早要被消灭，但这并不可怕。

今天我们的任务是共同努力建设新中国，不经过新民主主义就不能达到社会主义，着急是不行的。有些人天天喊共产主义，这当然使资产阶级受到精神威胁。如果有人天天在我面前说，你老了，快要死了，我也不高兴，非躲开他不可。我们要告诉资产阶级的人们要自信，他们不但有历史任务，而且有光明的前途。

现在，中国民族资产阶级是不是应该有一个单一阶级的政党？这不是应不应该有的问题，而是由于客观条件的限制很难产生。旧中国外有帝国主义的侵略，内有封建主义的压迫，民族资产阶级软弱性和动摇性这个"肺病"是先天不足遗传下来的，一开始就没有力量，没有形成强大的政党。中国革命的领导责任不得不落在无产阶级的肩上。共产党在农村搞了二十二年的武装斗争，形成了今天的局面。

在今天，如果搞单一阶级的资产阶级政党，势必走欧美资产阶级的道路：垄断市场，向外侵略，反对共产党。但是这条路在中国是行不通的，是不被许可的。因此，中国的民主党派只能是承认《共同纲领》，接受共产党领导，如现在的民主建国会〔２３７〕那样。但民主建国会并不是单一的资产阶级政党，它里面有进步分子，有社会主义思想。在中国具体历史条件下，民族资产阶级必须走今天这样的路，民主党派也必定是今天这样的类型，这是历史的必然。

各民主党派活动要有所分工。民进〔３０１〕在自由职业者方面开展活动较为适合。职教社〔３０２〕提出为劳苦大众服务，这是好的，但光提为劳苦大众服务还不够，照顾的方面要多些。民主党派的组织也不能太严，要照顾大多数，团结大家一道前进。总之，我们要长期合作，共同努力，建设新中国，完成历史所赋予的任务。

＊　这是在中共中央统战部邀请民主建国会、民主促进会、中华职业教育社部分领导人座谈会上的讲话的第三部分。

