# 关于基督教问题的四次谈话

中文马克思主义文库 -> 周恩来
关于基督教问题的四次谈话
（一九五○年五月）

五月二日的谈话

一、中国不是政教合一的国家。在中国，宗教同政治一向是分开的，所以宗教问题不象欧洲政教合一的国家那样严重。

二、基督教是十六世纪马丁·路德〔３０３〕反抗罗马教皇的专制、实行宗教改革而建立的一个新教会，它在当时的社会上曾起了积极的作用。但是，近百年来基督教传入中国和它对中国文化的影响，却是同帝国主义对中国的侵略联系着的。基督教是靠着帝国主义枪炮的威力，强迫中国清朝政府所签订的不平等条约而获得传教和其他特权的。因此，中国人民对基督教曾产生一个很坏的印象，把基督教叫作"洋教"，认为基督教是同帝国主义对中国的侵略分不开的，因而也就反对基督教。

三、在二十年代，曾有过一个规模很大的非基督教运动。一九二二年至一九二七年，非宗教大同盟〔３０４〕对帝国主义利用基督教所做的许多坏事以及所发生的许多坏影响，清算了一下。这个清算是针对帝国主义文化侵略的。但是应该指出，自五四运动以来，基督教里面有进步分子，在中国革命的过程中，他们是同情中国革命的。比如大革命时期，基督教青年会以及其他宗教团体中的进步民主人士，曾掩护过一些从事职工运动的革命分子和共产党员。在抗日战争时期，基督教青年会等宗教团体也起了很好的作用。在解放战争时期，也有很多基督教进步人士同情并参加了反蒋、反美斗争，反对独裁，反对内战，因而受到国民党反动政权的迫害。解放战争获得基本胜利以后，在北京召开的人民政治协商会议，宗教界的进步民主人士也有代表出席。

四、今天，美帝国主义仍企图利用中国的宗教团体来进行破坏中华人民共和国的活动。

中国的宗教团体应该怎么办？

第一，要把民族反帝的决心坚持下去，割断同帝国主义的联系，让宗教还它个宗教的本来面目。今天宗教界自己发起了一个民族自觉运动，把近百年来同帝国主义的关系清算一下。当然，这种关系有自觉的，有不自觉的。基督教里面有没有甘心情愿做帝国主义走狗的呢？自然是有的。

第二，宗教思想是唯心主义的。唯心主义和唯物主义，不同就是不同，不必隐瞒。我们只要求宗教团体摆脱帝国主义的控制，肃清帝国主义的影响。我们不搞反宗教运动。我们所遵守的约束是不到教堂里去作马列主义的宣传，而宗教界的朋友们也应该遵守约束，不到街上去传教。这可以说是政府同宗教界之间的一个协议，一种默契。

第三，宗教团体本身要独立自主，自力更生，要建立自治、自养、自传的教会。这样，基督教会就变成中国的基督教会了。

五月六日的谈话

一、基督教最大的问题，是它同帝国主义的关系问题。中国基督教会要成为中国自己的基督教会，必须肃清其内部的帝国主义的影响与力量，依照三自（自治、自养、自传）的精神，提高民族自觉，恢复宗教团体的本来面目，使自己健全起来。

二、宗教界（包括基督教青年会在内）要完成自己的历史任务，各宗教之间和各教派之间就应该加强团结，联合起来，研究怎样服务于中国人民；就应该在民主与爱国的立场上，健全自己，使宗教活动有益于新民主主义社会。一个宗教团体，对新中国有无益处，要以爱国与民主两个条件来鉴别。如果这个宗教团体在政治上是拥护《共同纲领》〔２８０〕的，是爱国与民主的，那么这个宗教团体便是对新中国有益的。

三、宗教的存在是长期的。中国人民有宗教信仰的自由。但是，今天的中国是一个新民主主义的国家，并不是一个基督教国家。所以，传教是要受到若干限制的。在土改新区，在乡村，最好慢一点。东北是我国的一个新国防区，在教会同帝国主义的关系没有搞清楚的时候，在基督教还没有成为完全是中国的教会的时候，不要去增加复杂性。

四、关于基督教团体中的外籍人员和外国捐款问题。

我们不再请外国传教士到中国来，因为外国传教士很容易自觉不自觉地做帝国主义的工具，而我们中国人很难看清他们。不请外籍传教士，对基督教本身有好处。至于已经在中国的外国传教士，除了他们自愿要求马上离开中国或者已发现他们有反动行为证据的以外，我们并不马上要他们走，他们可以等到双方合同期满再走。

基督教既然要清算同帝国主义的关系，自力更生办教会，那就不应该再向外国募捐。我们要有自己办教的准备。

现在中国是一个独立自主的国家，我们不向别人低头，不依赖别人。但是，我们也不盲目排外。这个原则也适用于其他教育团体。因此，对每一笔外款，要加以辨别，如果是有附带条件的援助，就不能接受。

五、基督教团体在拥护《共同纲领》的基础上，怎样辅助社会进步，应该研究一些具体的工作。你们对政府有什么要求，可以提出来。

五月十三日的谈话

两星期来，我们是以诚相见，彻底地交谈。这不是清谈，而是为了合作。政府有什么意见，中国共产党有什么意见，我们拿出来；你们也把自己的意见拿出来，目的是求得政府同宗教界实行更好的合作。

你们是有神论者，我们是无神论者，我们无意在这里同诸位展开有神无神的争论。我们认为，唯物论者同唯心论者，在政治上可以合作，可以共存，应该相互尊重。我们之间有合作之道。这是我们衷心的希望。

我们同宗教界朋友的长期合作是有基础的，这一点我们毫不怀疑。我们希望宗教界朋友也有这个信心。这便是所谓"共信不立，互信不生"。当然，我们也不隐讳我们之间的不同点。但是，我们可以在《共同纲领》的基础上实行合作，这是我们一致同意的。《共同纲领》是四个阶级合作的基础。从各界来说，宗教界也是合作者之一。我们要彻底实行《共同纲领》，使四个阶级各得其所。此外，还要照顾到从地主阶级中间，从国民党反动派中间，以及从其他受帝国主义影响的人中间分化出来的要求进步的分子。

中国一向是政教分开的。今天，政府同宗教界人士是根据《共同纲领》所确定的政治方针来合作的。

根据《共同纲领》的要求，我们必须在宗教界肃清帝国主义的影响。这不是谁来约束谁，我们大家都有这个责任。在宗教界肃清帝国主义影响，并不是说宗教界的每一个人都做了帝国主义的工具。在个人来说自己感觉没有被利用，但是帝国主义主观上有所要求，它们利用宗教团体，乃是事实。广大教徒有时不免也被利用。这一点，我们非说清楚不可。这个问题说清楚了，对教会只有好处。

我们的统一战线要扩大，其界限要看是否同帝国主义、封建主义和官僚资本主义割断了联系。

宗教界是有一部分反动分子的。但是，反动分子是少数。宗教界本身要团结，这就是上次我说的宗教界要开展一个民族自觉运动，以增强我们的合作。也就是说，我们要通过反对帝国主义、封建主义和官僚资本主义，清算并且断绝同它们的旧关系，以巩固我们的统一战线。

宗教界人士参加这个反帝爱国运动是有好处的。中国是一个独立自主的国家，宗教团体割断同帝国主义的联系是理所当然的事。中国基督教徒有将近一百万人，不会因为出了少数坏人，我们就抛掉了诸位，那决不符合《共同纲领》的精神。诸位在政治上站稳了脚跟，便毫不会受到歧视，只有这样才是出路。

谁要企图人为地把宗教消灭，那是不可能的。苏联是社会主义国家，它还是有宗教的。我们决不打算这样做。如果我们不想要的东西就认为它不会存在，那是不符合客观实际的。反过来说，我们是专爱基督教吗？也不是的。我们主张，在《共同纲领》的基础上，信教的、不信教的可以共存。我们要团结和照顾到各种社会力量，使大家各得其所，同心协力，建设新中国。只有这样，才能使社会安定，稳步前进。

帝国主义者对中国人民获得解放是仇视的。凡是有良心的人，都看到了美帝国主义的残暴。宗教界刘良模〔３０５〕先生写的《我所看到的美国》一书里，对这一点说得很清楚。一百多年来，我们流了那么多的血，付出了巨大的牺牲，才取得今天的胜利。我们决不忍心让人民的事业再受破坏。这次诸位所拟文件的基本方针是很好的。我们要把宗教界的害群之马、极少数的走狗、犹大〔３０６〕，清除出去，使广大宗教界人士在《共同纲领》的基础上团结起来，引导广大教徒一道前进。这是一个长时期的工作。

我再重复一次，帝国主义利用宗教团体的问题，我们要做这样的解释：分清主观与客观，客观上是存在了的；分清少数与多数，事实上反动分子是极少数。宗教界内部要通过自我批评，把自己的工作与组织进行检讨和整理。这是个原则性的工作。我们搞清楚这些原则，把这件工作做好了，帝国主义就不能再利用宗教团体了。这也就是宗教界的自卫。

我们认为，宗教界开展加强团结运动是去腐创新。对于帝国主义的骂，我们不怕。至于宗教界本身的反响，我们要注意，要逐步地提高他们的觉悟。我们希望，大家团结起来，争取主动，解决问题，使基督教在中国人民的心目中观感一新。

五月二十日的谈话＊

吴耀宗〔２４３〕所拟定的第五次修正的宣言，比过去多了一个序言，把基督教同帝国主义的关系说得很偶然，就让他那样吧。一个字不改，照样发表。宣言里说的话和我们说的话不一样，我们也不需要宣言和我们说的一样。这样便于团结群众。

对基督教，一方面不能无原则地团结，另一方面不要脱离广大群众。这是政策问题，不是策略问题。

大家认识要一致，要团结多数，争取中间分子，打击极少数反动分子，但也不能过急。要不疲倦地工作下去。只有懒惰的人才感到束手无策或推卸责任。基督教客观上是被帝国主义利用的，也有不少天真的人曾被利用过。这就要我们有意识地做好工作，具体地帮助他们提高认识，分清是非，解决问题，共同前进。

＊　这是在中共中央、政务院有关单位负责人座谈会上的谈话要点。

