# 人民政协全国委员会会议党组活动的方针

中文马克思主义文库 -> 周恩来
人民政协全国委员会会议党组活动的方针
（一九五○年六月十四日）


　　这次人民政协全国委员会第二次会议是定期例会。
 
　　这次会议增加了一些列席代表，其中有各地政协委员会的代表。人民政协组织法规定地方设立政治协商委员会，但以前全国委员会与地方委员会没有建立联系，这次确定从组织上联系起来。党外人士对这一规定很注意。联系起来有好处。现在有党的系统，有政权的系统，再加上政协的系统，这就更能反映各个方面的意见，并有利于决议的贯彻执行。

　　最近，中央召开了七届三中全会，讨论了准备提交政协第一届全国委员会第二次会议的主要报告和议案。现在，根据三中全会的精神讲一讲这次政协全国委员会会议党组活动的问题。

　　一、对共产党员的要求。毛泽东同志说，对共产党员与党外人士应一视同仁，又要有所不同。一般来说，在政治待遇、物质生活方面应一视同仁，对党外人士不得歧视，这是一方面。但还有另一方面，我们的党是工人阶级的先锋队，要率领人民走向社会主义，因此党员在政治见解上、思想意识上，要比别人水平高，这一点是有所不同。我们一些同志却有与此相反的情形，不是在政治上、思想上严格要求自己，而是在政治待遇、物质生活上争名誉，闹地位，这是不好的。我们党创建了军队，创建了解放区，领导了人民民主统一战线，夺取了全国政权。对这些，大家是承认的。正是由于这种情况，我们就更应谦虚谨慎，注意这个问题。

　　二、要上下一致，内外一致。凡是中央决定了的，地方上就要执行，上面是什么意见，下面也是什么意见，不要使党外人士批评我们"中央好，地方糟"，感觉我们上下不一致。内部决定的方针，要贯彻到外面去，不要使人感觉我们对外是一套，内部又是一套，内外不一致。毛泽东同志的作风是，对问题一经考虑成熟，决定了的就公开出去。凡是要在广大群众中做的事情，就应该真诚坦白地向党外人士谈清楚。对党外人士要和蔼真诚，不要虚伪。毛泽东同志同党外人士谈话，真是和同党员谈话差不多。这是值得我们学习的。

　　三、要让党外人士做到"知无不言，言无不尽"，使他们在各种会议上敢于说话。民主人士，尤其是从旧社会来的上层分子，说话是有保留的，这是不奇怪的。他们要看一看。特别是新同我们接触的人，有些观望，是可以理解的。我们有责任去打破这种观望，循循善诱，使他们敢于把话都说出来。他们说的话不一定都对，但只要有一点好的，我们就应当重视。愿听意见不是一件容易的事，但必须去听，特别是要能听不同的意见。资本家、自由职业者有什么意见，我们应当听；地主有什么想法，也应当了解。这需要有两个条件：第一，要有听得进去的胸怀；第二，要有辨别是非的本领。这不是每个党员都能办得到的，这就需要锻炼。最近关于财经问题，各方提了一些意见，毛泽东同志叫印成小册子，发给全国委员会及政府中一些高级人员看。有人不了解，说为什么把一些错误的意见也印出来？这就是敢于放手让人家讲话。我们的态度是：对的意见加以接受，不对的也不要马上打回去，适当的时候加以批评。其实，有的人当他自己觉悟以后，也会做自我批评的。如上海开会时，党外人士对我们的工作提出了五十几条缺点，陈毅〔１９４〕同志在讲话中举出的缺点比他们提的还多，并且进行了分析，指出原因，然后对他们的某些错误看法加以批评。这种做法就很好。对党外人士的意见，哪怕只有一分是对的都应接受，然后再对不正确的部分加以分析批评。这就是以斗争求团结的方法。对愿意同我们合作的朋友，应实行"言者无罪"。对别有阴谋者，则应揭穿。

　　以上所谈三点，可作为我们这次会议党组活动的方针。



　　＊　这是在中国人民政治协商会议第一届全国委员会第二次会议第一次党组会上的讲话。



