# 关于西北地区的民族工作

中文马克思主义文库 -> 周恩来
关于西北地区的民族工作
（一九五○年六月二十六日）


　　西北的工作，做得不错，下面谈几个问题。

一　民族问题

　　我们根据《共同纲领》规定的民族政策来办事，基本上是成功的。我们的政策与国民党那种压迫少数民族的政策有本质的不同，按我们的政策去做，各民族必定能够日益团结，必定会有美好的前景。

　　同时也应该指出，民族问题在西北是严重的，方针、政策虽然对了，但一不小心，还会出偏差，还要出乱子。我们的干部，在处理民族问题的时候，大汉族主义常常会不自觉地表露出来。就是很注意这个问题了，有时也不免会有一些疏忽。所以，我们在工作中要处处谨慎，否则小事情会变成大事情，局部性问题会变为全局性问题，即刻就会闯出乱子来。

　　我国历史上，各民族之间矛盾很大。在汉族同少数民族的关系上，是汉族对不起少数民族。今后我们汉族同志要代为受过，向他们赔不是。要多做解释工作，说明今天的中国和过去不同，不会再去压迫少数民族了。说一次不行就再说一次，不怕多说几次。人家终究会知道你的话是对的。

　　西北的民族工作有成绩，方向是对的，但事情不能操之过急。比如土地改革，可以推迟三五年再说，如果条件不成熟，那就十年八年以后再进行。少数民族只有三千万人。在五亿人口的中国，这三千万人的地区晚一些时候土改，对全国来说起不了决定性的作用。慢一点搞，比闯出乱子来要好得多。少数民族地区和汉族地区情况不同，不能照搬汉族地区的做法。

　　对于少数民族的宗教，我们现在也还不能提出改革的口号，以免引起人家的反感。对伊斯兰教，对喇嘛教，都应该尊重。假如少数民族中有积极分子提出要改革，应该好言相劝，劝他们不要着急。这个问题现在还不能提，慢些改比快些改要妥当得多。

二　经济问题

　　汉族多年来对不起少数民族，今后无意中还可能犯错误，应该多想想自己的错处。凡事都"求其在我"，不要只说人家的错处。

　　对少数民族地区的贸易，不能剥削人家，也不能只做到平等互利。由于过去对不起人家，今后就应该多补贴、多支出一些，让少数民族同胞多得一些利益。汉族同志应该抱着这样的精神和少数民族通商。

　　在税收方面，喜饶嘉错〔３０７〕主张减一些税。这个意见可以考虑，不要因为收那一点税款而引起不好的效果。

　　在物资方面，前些时候新疆的同志出国订购了一批货物，如肥皂等日用品。现在因为自己已经有了，又想不要了。我想花点外汇不要紧，还是要把这批货买回来。东西多了，价钱就便宜点，使新疆人民多用一些，国家可以给他们补贴些外汇。甘肃的交通很不便，日用品自然很贵，以后应该设法解决交通问题。

　　要多在少数民族地区搞水利，用雪山的流水来灌溉。要办一些轻工业工厂。明年的财政计划，应该多照顾少数民族，要让他们逐步从游牧变成定牧。

　　救济问题。西北除灾区以外，粮食还算丰富。今后如果什么地方粮食发生困难，中央一定尽力帮助。

三　其他问题

　　干部问题。培养少数民族干部是今后的一项重要任务。有关各省应积极创办干部学校，汉族学生应把学习少数民族的语言文字作为必修课程。要把这件事当作一项政治任务来完成。

　　区域自治问题。我们主张实行民族区域自治。这样做对国家统一、民族团结有好处。各自治区政府应有少数民族人士担任领导职务。在各族各界人民代表会议中，应包括各方面少数民族的代表，人数的比例要有原则规定，少数民族代表的比例可以大一些。

　　纪律问题。凡是涉及民族问题，比较重要的应该请示大行政区，更重大的必须请示中央。许多事情要请示，办事自然会慢一些，但慢一些比出乱子好。

　　开发柴达木盆地问题。这个地区是很适合于开垦的，但当地的少数民族可能误会我们要强占他们的地方而引起冲突，所以这件事最好慎重一些，不要冒失。

　　货币问题。新疆币和东北币不同于人民币。东北因为过去关内财经情况不稳定，怕影响东北的生产，而另出了一种票子。以后全国的货币都要统一起来。新疆改用人民币的问题，今天不作决定，但新疆省人民政府可以先考虑一下，做些准备工作。

　　当前对银元还不能禁止流通，因为纸币威信还不高。将来纸币威信提高了，自然可以解决银元流通问题。对于银元，我们已经在几个地方打过几仗〔３０８〕，证明它并不可怕。

　　新疆需要技术人员，希望提出具体方案。比如需要哪几方面的人才，要多少人等等。提出后，我们再同有关方面研究抽调。

　　各省回去应该想想明年的计划。十一月份要开政协全国委员会，准备提出明年的经济概算，各省应该提出计划来。计划也不能订得太高了，我们只能搞一年的计划。五年计划之类的东西，现在条件还不成熟，还是慢一步好。



　　＊　这是在政务院第三十七次政务会议上讨论西北地区民族工作时的总结发言。



