# 民主党派的工作要同国家的中心任务相配合

中文马克思主义文库 -> 周恩来
民主党派的工作要同国家的中心任务相配合
（一九五三年三月一日）

中国国民党革命委员会〔２３６〕的三中全会扩大会开得很好。民革几年来的工作是有成绩的，当然也有缺点，大家在会上已经做了检查和讨论，并做出了结论，在这方面我提不出更多的意见。《人民日报》元旦社论指出，今年的三大任务是抗美援朝〔３１０〕、国家建设和召开人民代表大会。下面，我就谈谈各民主党派如何配合这三大任务的几个问题。

一　抗美援朝

如何支持抗美援朝的斗争，两年来已经取得了丰富的经验。开始时，大家还缺乏经验和胜利的信心，有些人甚至采取了保留的态度。经过两年来的广泛动员和深刻教育，这种情况已经发生了很大的变化。

全国人民从抗美援朝的斗争中得出一个重要的认识，就是处在两个阵营对立的世界中必须分清敌我友。这在国际和国内都是一个重要的问题。国内的敌人虽然已打倒，但反革命分子并没有完全肃清，即使完全肃清了，帝国主义还存在，各种阴谋集团还可能产生出来。搞暗杀、搞阴谋破坏是没落阶级必然要走的亡命之路。美帝国主义长期在中国搞特务活动，过去它与戴笠〔２０１〕合作杀害革命分子和民主人士。直到现在，美国还支持郑介民〔３４３〕在香港大肆进行特务活动。蒋介石失去了中国大陆，是不会甘心的。应该提高警惕。中共方面应该多提供一些特务活动的材料给各友党的朋友们看看。

分清敌我。我们的敌人首先是美帝国主义，而帝国主义不是孤立的，是同国内的敌人有联系的。我们不应麻痹，要互相提醒，以先觉觉后觉。中共在这方面的经验比友党要多一些，而在这方面友党经验就少一些。如李任潮〔８５〕先生有一个时期还对蒋介石认识不足，认为可以和他谈判，但一到南京就被蒋介石囚禁起来了。余心清〔３４４〕不听我的劝告，去和孙连仲〔３４５〕、美国领事馆谈兵变问题，结果几乎送命。我讲这些话对诸位可能有些刺激，但刺激一下可以提高警惕性。在我们党内也发生过叛变的事，如顾顺章〔３４６〕的叛变。当时我还在上海，好在消息知道得快才免遭大的破坏。共产党也上过当、受过骗，不过少一点。蒋介石搞特务活动有经验，加上美国的帮助，今后他还会来搞，这一条不能忘记。公开的战争，志愿军在朝鲜打得很好；隐蔽的战争，要大家来打，不参加这个战争就不是爱国分子，不是革命党员。民盟出了个张东荪〔３４７〕，他在解放后还供给美国情报，这件事是不可饶恕的。任潮先生曾写信给毛主席要求严办，这是正气。张东荪在解放前与美、日、蒋、共四方面都有联系，有人说他是"押四宝"。过去的事情以一九四九年为限，一九四九年以前的就不追究了，以后仍在搞这些活动就不可饶恕了。说毛主席厚道，共产党宽大，这是对好人、对能改过自新的人而言的，如果对敌人宽大就是对人民的残忍。张东荪事件应引起严重注意。

民革〔２３６〕是革国民党反动派之命，坚持中山先生主张的。蒋介石破坏中山先生的主张，也会来破坏民革，会来钻空子，很值得民革朋友们注意。我以民革的朋友的身份提醒大家注意这件事情。上面讲的这些是说要警惕敌人的阴谋破坏，不是说我们不愿和帝国主义国家和平共处，但和平共处不能高枕无忧。对帝国主义一定要划清界限，对于崇美、亲美、恐美的思想一定要给以批评和教育，教育别人也教育自己。中山先生太厚道，与共产党合作之前常上敌人的当，受帝国主义的骗，就是因为他有时把敌人也当成朋友，如头山满〔３４８〕曾帮助过同盟会〔１２〕，中山先生就认为他是朋友，而不知道他帮助同盟会是别有用心的。由此可见，国内国外都必须分清敌我友。毛主席说分清敌我友是一个战略上的问题。这个关键问题必须搞清楚。

关于朋友问题。我们的朋友遍及全世界。资本主义国家和原殖民地国家的人民，都是我们的朋友。朝鲜人民是我们的朋友，所以我们要援助朝鲜，不抗美援朝我们也就不能进行和平建设。

敌人的矛盾可以利用。不管什么政府，只要它反对侵略战争，我们就和它联合，因为这样暂时的联合对人民有利。但这种朋友是临时的策略上的朋友。这类国家一方面和我们作朋友，一方面又对我们进行破坏，我们只有提高警惕才不会上当。我们真正可靠的朋友是全世界的人民，这是战略上的朋友。两种朋友不能混淆，混淆就要吃亏。在国内公开的敌人是台湾的蒋介石，大家都认识得比较清楚，但还有一种人面目不清，还藏在我们的朋友里面，大家要警惕。这种人，民主党派不能吸收他们做党员。民主党派是我们的友党。作朋友一定要做畏友，在大的关键问题上要互相提醒，才是真正的朋友。

二　国家建设

民革有很大数量的成员在机关工作，对国家建设将有很大的贡献。如何配合国家建设呢？第一，要保证完成国家建设任务。在国家建设中，每个螺丝钉都有作用。特别在今天，我们正处在国家走上工业化，农业走上集体化，国防走上近代化，文教走上大众化的伟大时代，需要动员每个人都来积极参加这些巨大的工作。各党派要动员自己的成员在各自的岗位上保证完成国家的建设任务，要他们身体力行，起模范带头作用，在共产党领导下 一道前进。第二，要严格遵守国家纪律，大家要步调一致。国家建设一开始还不能实行全面计划，乡村的个体农业和城市的小工商业是两个大海，要把他们纳入国家建设计划的轨道，不是轻而易举的事，因此，要稳步前进。国民经济做到有计划、按比例地发展，需要一个比较长的时间。现在，我们国家的建设还面临着敌人破坏的危险。因此，我们要严格遵守国家纪律，保守国家机密，不然，工作上就会出偏差，政治上也会出乱子。

三　人民代表大会的召开和实行普选

人民代表大会制属于苏维埃工农代表大会制的体系，完全不同于资产阶级的议会制。议会制实际上是资产阶级专政，是假民主，而人民代表大会，是经由人民选举出来的，是代表广大人民利益的。

人民代表大会和苏维埃也是有不同的。苏联是两院平行制，除联盟院外，还有民族院。这是因为苏联是个多民族的国家，少数民族的数量很大，如不成立民族院将不能完备地表现出民族平等。而中国的少数民族的人数只占全国人口的十四分之一，可以不成立民族院，但在人民代表大会中，少数民族代表按人口的比例数要大于汉族代表的比例数。此外，苏联只是工人和农民两个阶级的联盟，而中国是四个阶级的联盟，这也是不同的。

各党派的成员怎样才能被选为人民代表？我们应该把普选看作是检查工作和考验干部的机会，不要为选举而选举，不要采取资产阶级竞选那一套。资产阶级往往是为了竞选而组党，在竞选的时候讲的是好话，但那是骗人的，他们并不真正为人民服务。我们应该通过选举来检查工作和考验干部。能不能选得上决定于人民的态度，如果你工作做得好，人民当然会选你。有人认为只有共产党员才能被选上，这是不对的。即使是共产党员，如果人民不信任你，也选不上。

对民主党派的要求，当然不能象对共产党员那样严格。在考虑人民代表时，既要掌握原则的严肃性，还要有实际的灵活性，对友党要宽些，但原则是一致的，要选出肯为人民服务的人。只要真心为人民服务，民主党派朋友是可以得到照顾和安排的。

人民在四年中才考验我们一次，我们一定要努力做好工作。

＊　这是在招待中国国民党革命委员会三中全会扩大会议代表时的讲话。

