# 民主党派成员学习和参加建设的问题

中文马克思主义文库 -> 周恩来
民主党派成员学习和参加建设的问题
（一九五三年六月四日）


　　现在各民主党派都强调学习，大家也很热心于学习，这是很好的事情。在过去三年多的时间里，一般地说，我们的政治学习是有进步的。最主要的学习是参加了许多革命运动，完成了许多革命任务。比如抗美援朝、土地改革、镇压反革命、"三反""五反"、思想改造、工厂里面的民主改革、生产改革和最近领导机关开展的新"三反"运动〔３４９〕、社会上贯彻婚姻法运动等等，各民主党派都参加了。虽然每个人参加运动有多少的不同，但都受到了锻炼。就文教界来说，参加思想改造运动也是一种学习。这个运动把大家震动了一下，是必要的。共产党在过去的三十多年当中，最大的震动是延安整风。经过了一九四二到一九四四年的整风运动，才有一九四五年中国共产党第七次全国代表大会的成功，这次大会为我们取得全国胜利做了准备。

　　共产党并不是生下来就那么健康的，也曾经犯过多次错误。所以说，各民主党派在这几年中经过一些震动也是必要的，这就为我们今后的进步打下了基础。但是，仅靠这些运动还不能把学习成果巩固下来，还需要有经常的学习。

　　这里有两个问题，一个是各民主党派的领导思想问题，一个是如何号召学习的问题。

　　首先讲各民主党派的领导思想问题。过去中央统战部曾经和各民主党派研究过，各民主党派应该以"承认工人阶级为领导"的思想作为领导思想。但是，这并不等于说，各民主党派的思想就是工人阶级思想。为什么这样说呢？因为各民主党派里面事实上还存在着资产阶级思想和小资产阶级思想，现在还不能取消，而是要逐步地改造。因为阶级还存在，你怎么能够取消这些思想呢？如果取消的话，就不符合马列主义了。

　　在民主党派里面允许资产阶级思想和小资产阶级思想合法存在，但这些思想要受《共同纲领》的限制，不能让它自由泛滥。如果这些思想跟工人阶级的思想对立，敌视共产党，就要受到批判。我们并不否认这种斗争。现在民盟的一些进步朋友学习马列主义，大家都愿意进步，这是一种好现象。然而，我们却不能要求民盟的思想跟共产党一样。那样就把自己弄得很狭窄，失掉民主党派的作用了。

　　那么，为什么在共产党里面只许有马列主义的思想呢？因为共产党是工人阶级的政党，是我们国家的领导党，它的指导思想是马列主义的，它领导我们国家逐步过渡到社会主义社会去。所以，共产党里面的思想就只能是马列主义的思想。如果在共产党里面允许别种思想存在，共产党就不能成为国家的领导党，我们的国家就失掉前进的方向了。当然，共产党员也会受到资产阶级思想的影响，但是，这种思想在共产党内是非法的，一冒出来马上就要受到批判。

　　在新民主主义社会里，需要各民主党派把各种分子团结起来，不断地教育他们，改造他们，使他们逐步地过渡到社会主义去。当然，我是说使民主党派的分子逐步进入社会主义，而不是说资产阶级进入社会主义，如果资产阶级能够进入社会主义，那就不叫社会主义了。各民主党派要有个分工，分别去教育和改造各种分子，使他们的思想逐步提高，逐步进步。但是，在民主党派里面，就不能象共产党那样，不允许资产阶级和小资产阶级思想存在，而是要辨明哪种思想对于今天的社会有利，哪种不利，然后分别对待。

　　有些民主党派朋友急躁地说："与其这样麻烦，还不如使我们这个党成为马列主义的党，这不是很省事吗？"省事是省事，但是不符合实际，不实事求是。我们承认，民主党派的工作是麻烦一些。难道怕麻烦就不革命，就不建设了吗？跟帝国主义斗争很麻烦，可是还要斗下去。这是为咱们的子孙幸福着想。所以，在民主党派里面，既要允许资产阶级思想、小资产阶级思想存在，又要区别情况，加以限制和批判。至于如何区别，这是一个复杂的问题。要我一下子定出许多规矩来，我也定不出来。在座的朋友读马列主义的书也不少，你们要负起这个责任。比如说，资产阶级的"五毒"〔３３７〕思想就不能允许存在，资产阶级的极端个人主义、极端自由主义的思想，就是在民盟里面也要受到批判。因为有这种思想，就不能积极参加国家的建设，就会敌我不分，泄露国家机密，这是不行的，是要受到限制的。

　　现在我们处在这样一个复杂的时代，中国又是这样一个复杂的社会，我们不能够冒进。当然，最痛快的是现在就宣布我们中国是社会主义国家，没收私营工厂。但是那就违背了《共同纲领》，就要闯大乱子。在中国，小资产阶级的成分很多，农民、小手工业者、小商人等等，这个数量是大海大洋，工人阶级并不占多数，资产阶级的人数也不多。自从帝国主义势力侵入中国以后，资产阶级思想经过小资产阶级，经过知识分子，在中国产生了很大的影响。在抗美援朝运动中，资产阶级的崇美、亲美、恐美的思想受到了批判。但是，要肃清资产阶级的思想影响还是一项长期的工作。对各民主党派来说，这是一个长期而复杂的任务，不能急躁。中国社会就是这样一种复杂的状态，因此我们的工作也就是一项很复杂的工作。

　　再讲如何号召学习的问题。我们可以号召各民主党派的成员来学习马列主义，但是我们不能够号召所有的人都来学习。因为有些人一时还不能接受这样一个号召，即使参加了这种学习，也是口头上同意，思想上并不赞成，这就不好，不实事求是。学习要根据自愿，如果他不愿意学习马列主义，可以学习《共同纲领》。《共同纲领》也是根据马列主义的指导原则写出来的，是我们在新民主主义阶段的共同政治纲领。

　　我们的学习是不是要有重点呢？应该有重点。对民主党派在国家机关、文教机关工作的成员，应该强调学习马列主义，以便跟国家的领导思想相一致，跟国家的经济建设、文教建设的方针相一致，使我们写的东西，编写的教科书等等，眼国家机关制定的政策相一致。

　　关于参加国家建设的问题。

　　现在我们开始进行国家建设了。民盟的成员很多是在经济建设和文化建设岗位上工作的，应该在各自的岗位上积极地参加建设。民主党派的责任，就是要推动自己的成员积极地参加各自岗位上的建设工作，而不是由每个党派都直接领导建设。如果那样，我们的国家建设就成为多头领导了，就变成无政府状态了。就是工人阶级、共产党也不能是任何一个工人、一个党员都去领导国家建设。不是曾经有过这样的笑话吗？有一家私营商店里的一个东家和一个店员，两方面争辩谁领导谁，店员说，我是工人阶级，我领导你；东家说，我是店东，还不是我领导你嘛！结果是吵不清。这就不对头。工人阶级领导并不是任何一个工人都去领导，如果任何一个工人都去领导，那就是多头领导了，那就不成为一个国家了。所以无论工人阶级也好，共产党也好，必须经过国家，经过人民代表大会，经过政府机关，经过经济领导机关去进行领导。国营经济领导私营企业，并不是任何一个国营企业都去领导私营企业。如王府井大街的一个国营商店对 隔壁一家私营商店说，我领导你，我让你关门你就得关门。那就不行。如果那样就乱了。所以，一定要经过国家经济领导机关去领导。学校也是如此，共产党对学校的领导只能经过校务委员会或它的上级领导机关教育部。这就叫作民主集中制，也就是一切从群众中集中起来，然后再到群众中贯彻下去。这是我们新民主主义的特点。没有集中就没有民主，有民主就需要集中，没有集中的民主就是极端民主，就是无政府主义；只有集中没有民主那就是专制主义，个人独裁。我们要反对这两种倾向，实行民主集中制。所以，民主党派在各个机关、企业、学校参加建设工作的成员，都要服从那个机关、企业、学校的领导，一直到中央人民政府这个最高的领导。这样，整个国家才能有计划地、有组织地、有步骤地进行建设。

　　民主党派在机关、企业、学校的基层组织的任务，就是要推动自己的成员在这个机关、企业、学校里面起积极分子的作用，同共产党合作，并且教育推动它所联系的群众跟我们一起前进。推动了别人进步，也就教育了自己。

　　各民主党派既要积极参加各种建设工作，同时也要参加各种政治活动。因为我们是政党，政治觉悟总是高一些，所以就应该积极参加各种政治活动，并在其中起推动作用。过去各民主党派参加了各种革命运动，起了积极的作用。今后参加国家建设，还要进一步提高政治觉悟，发挥更大的作用。

　　当然，这里面也有一个矛盾。听说有的民主党派成员因积极参加各种政治运动而放松了业务，或者忙上了业务就不问政治，把政治和业务两者对立起来了。这里也有客观原因。建国三年来，政治运动很多，工作很紧张，大家忙于运动，而把业务放松了。在座的很多位教授就吃过这个苦，政治运动参加得多，课教不好，学生不满意，结果是过去的名教授，现在变成了受批评的教授。另一方面，我们现在要进行建设，过去学的那一套很多都不适用了，这就要求每个人都要钻研业务，而钻研业务，就需要更多的时间。据说许多位教授最近很紧张，清华大学的教授平均每人每星期要有六十个小时的工作，每天要工作十个小时。用脑筋的工作每天十小时是够累的了。

　　这种情况很多学校都同样存在，我们政务院讨论高等教育的时候研究了这个问题，准备作适当的调整。过去大家搞政治运动很紧张，现在搞建设又很紧张，如果一直这样紧张下去，不作适当的调整，那就会使大家都得神经衰弱病。听说现在年老一点的教授都失眠，不吃安眠药就睡不着觉。如果大家都吃安眠药那就成问题了，所以必须作适当的调整。现在政府机关把每天一个半小时的学习取消了，机关干部对这件事很赞成，过去的确是疲劳得很。这是一大德政。本来，政治与业务不是对立的，而是结合的，但是要结合得好，时间就不能太紧。

　　现在，开会太多也是一个问题，要设法调整。我们应该看到，业务里面也有政治。使业务有利于人民，这就是政治，研究如何使业务有利于人民，这也是政治学习。今后如何把紧张情形改变过来，是我们领导机关应负的责任。



　　＊　这是在中共中央统战部招待中国民主同盟七中全会代表的茶话会上的讲话节录。



