# 社会主义改造与国家资本主义

中文马克思主义文库 -> 周恩来
社会主义改造与国家资本主义
（一九五三年九月十一日）


　　《共同纲领》已经规定："在必要和可能的条件下，应鼓励私人资本向国家资本主义方向发展"。这次会议全面地提出社会主义改造的问题，指明国家资本主义是引导私营工商业走上社会主义的必经之路，为的是把改造的性质和目标更加明确起来。

　　改造当然不限于经济方面，整个社会都在改造，政治、经济、文化各方面都在改造。整个国家在建设中，在改造中，这就是新民主主义社会的特点。

　　为什么要着重提出经济改造？因为经济是基础，其他都是上层建筑，如果经济不得到改造，新中国的政治、军事、文化都立不住。毛主席说过，我们的国家在政治上已经独立，但要做到完全独立，还必须实现国家工业化。如果工业不发展，已经独立了的国家甚至还有可能变成人家的附庸国。对于社会主义国家，我们能不能有依赖心理呢？比如由苏联搞重工业、国防工业，我们搞轻工业，这样行不行呢？我看不行。我国是一个近六亿人口的大国，地下资源很丰富，如果不努力建设自己的工业，特别是建设重工业，那就不能立足于世界。旧中国的工业基础很薄弱。孙中山先生说过：我们要迎头赶上。现在我们有机会，要加紧赶，不赶就要全盘皆输，就站不住脚。今天的世界形势对我们是有利的。抗美援朝〔３１０〕的胜利，打乱和推迟了美帝国主义发动世界战争的时间表。但是，我们不能松懈，有备则无患。否则，帝国主义就要钻空子。我们必须在发展重工业的同时建设国防工业，这是不能推迟的。工业建设不是短时期的事，例如，基本建设一百四十一项要全部完成，就需要七年的时间。有人说："到那时也不过才赶上七七事变时日本的水平，算什么？"但就是达到这个水平也是不容易的事。如果不搞，连这个水平也达不到。总之，经济是基础，经济改造是一切改造的基础，而国家工业化又是实现经济改造的关键。国家面貌的改变要从经济面貌的改变做起。这样，我们的国家才能永远站立起来。这是一百多年来多少志士仁人所追求并为之流血奋斗的宏伟事业。不实现工业化和经济改造，我们的国家就不能完全独立，就不能持久，就不能避免遭受挫折。希望大家仔细地想想这个问题。

　　从中华人民共和国成立起，我国便进入一个过渡时期。过渡时期的中心内容，就是实行国家工业化和社会主义改造。

　　我国现在的国家制度，是属于社会主义性质的，完全不同于资本主义制度，但和社会主义制度也不完全相同。俄国十月革命是社会主义革命，我国革命则是由新民主 主义革命逐步转变为社会主义革命。两国情况不同。我国政治上居于领导地位的是工人阶级，经济上居于领导地位的是社会主义的国营经济。我们是以工人阶级为领导、工农联盟为基础、团结四个阶级建立人民民主专政，一直到完成向社会主义的过渡。集中地说，我国新民主主义建设时期，就是逐步向社会主义过渡的时期，也就是社会主义经济成分在国民经济比重中逐步增长的时期。一九四九年国营企业和私营企业的产值比重是公四私六，到去年底变成了公六私四。在绝对数字上公私都增加了，但国营增加得更多。这个趋势就说明了我国是在向社会主义过渡。我们不要隐讳这个趋势。

　　毛主席说："经过国家资本主义完成由资本主义到社会主义的改造"。就是说，国家资本主义是实现资本主义工商业社会主义改造的必经之路。现在要把这个问题明确化，肯定下来。至于具体化，还要做许多工作，这是今后的任务。目前，国家资本主义在工业方面有公私合营、加工定货和收购产品三种形式，以后或许还会创造其他的形式。商业方面的国家资本主义也出现了公私合营、代购代销、代批发等形式，但现在还很不成熟，还需要摸索经验，总结提高。

　　国家资本主义并不就是将私人企业收归国家所有。在资产阶级专政的国家里，国家资本主义仍然是资本主义，而我国的国家资本主义则是《共同纲领》中所规定的，国家资本和私人资本合作的经济。至于这种经济的社会主义成分占多少，那要看国家资本主义形式的高低而有所不同。因此，不能说实现了国家资本主义就已经完成了社会主义改造。国家资本主义并没有取消资本主义所有制，它只是有限制的资本主义，还需继续改造和提高。当然，我国的国家资本主义和西欧的自由资本主义是不同的，它不能自由泛滥。即使未参加国家资本主义的私人工商业，也不容许自由泛滥，随便关厂、让工人失业就不行，囤积居奇或销毁产品也不行，投机倒把的那就一定要受到惩治。资本家的企业所有权、用人权、经营管理权也不是绝对的，而是相对的，如果资本家要辞退工人，必须到劳动局打招呼，生产管理也要和工人协商。有人说这种资本主义是新型的资本主义，这个说法不完全，如果科学地加以解释，应该说，这是一种受国营经济领导的、受限制的、不完全的资本主义。

　　经过国家资本主义来改造私营工商业，四年来的经验证明是正确的，可行的。毛主席说："将全国私营工商业基本上引上国家资本主义轨道，至少需要三年至五年的时间"。这里所说的"至少需要三年至五年"，就是说，不少于三年但可以多过五年，搞不成还可以推迟，不能急躁。所说的"基本上"就是说不是全部，从数量上讲，总要达到百分之六十以上。现在国家资本主义的数量已经不少，凡是和国家经济联系合作的私营企业，就带有国家资本主义的性质。据七个城市一九五二年底的不完全统计，国家资本主义从高级到低级的各种形式，上海占当地大型私营工业生产总值的百分之五十八，武汉占百分之六十五，西安占百分之七十，哈尔滨占百分之七十六，杭州占百分之六十三，沈阳占百分之五十五点九，广州占百分之三十二。据国家计划委员会估计，全国带有国家资本主义性质的企业，占整个私营工业生产总值百分之三十五到四十。以户数来说，上海大小工厂二万多，其中国家资本主义工厂有七千多。从以上这些数字看，国家资本主义的百分比已属不小。实现国家资本主义，决定的方面是大、中企业，而不是小企业。只有大、中企业纳入了国家计划轨道，全国经济建设才能更有计划有秩序地进行。小企业的数量虽大，但不起决定作用。对于夫妻商店和摊贩，还要研究办法，帮助他们逐步纳入计划轨道，逐步提高。目前各种形式都要有，一般可以维持原来的形式，不要急于改变。逐步提高的内容很多，如降低成本、提高质量、进行生产改革和增加生产等。

　　荣毅仁〔３５０〕先生关于工商界对待国家资本主义的六种态度，分析得很好。对于抵抗的一类，还要加以分析。有的是由于不了解情况，怕国家把什么都拿去，他们还要看一个时候。对这些人就需要我们去教育、帮助。另一种，他们只喜欢自由发展、垄断居奇、投机取巧、牟取暴利，甚至和国家对立。对这些人就要给以限制，进行斗争。限制也不困难，国家的办法很多，比如他要垄断，国家就可以多开个同类的厂。当然，如果不居奇、不垄断，国家就应该允许他们获得一定的利润。

　　个体农业、手工业，是两个大海，要做的工作还很多。因此，需要相当长的时间，才能走完过渡时期。



　　＊　这是在中国人民政治协商会议第一届全国委员会第四十九次常委扩大会上总结发言的节录。



