# 关于政协章程和政协第二届全国委员会委员名单问题

中文马克思主义文库 -> 周恩来
关于政协章程和政协第二届全国委员会委员名单问题
（一九五四年十二月四日）

这次政协常委会，是要协商第二届政协委员名单和讨论召开政协第二届全国委员会的问题。

今天提请大家讨论的文件有三个：中国人民政治协商会议章程（草案）；中国人民政治协商会议第一届全国委员会的工作报告；中国人民政治协商会议第二届全国委员会委员名单。

下面，就其中几个有关的重要问题作些说明。

关于政协章程的总纲。

上次常委会决定在政协章程中写一个总纲代替现在的《共同纲领》〔２８０〕。起草小组已经把政协章程写出来了。总纲写得很扼要，把应该包括的内容都包括进去了。一是指出政协第一届全体会议代行全国人民代表大会的职权，制定了《共同纲领》，组织了中央人民政府，宣告了中华人民共和国的成立，胜利地完成了它的历史任务。二是总结了政协五年来的工作。三是指出全国人民代表大会已经召开，人民政协不再代行全国人民代表大会的职权，但政协作为人民民主统一战线的组织仍将存在，今后还要继续发挥统一战线的作用。四是提出了今后的任务和奋斗目标，要广泛团结全国各族人民，共同努力，为实现国家在过渡时期的总任务而奋斗。这些内容都是很恰当的。

政协章程总纲还明确规定了参加政协的单位和个人共同遵守的七条准则，这就是：一、拥护中华人民共和国宪法，全力贯彻实施宪法。二、巩固工人阶级领导的人民民主制度，加强社会主义经济成分的领导地位。三、协助国家机关，推动社会力量，实现国家的社会主义工业化和社会主义改造事业。四、密切联系群众，反映群众的意见和提出建议。五、加强各族人民的团结，提高革命警惕性，坚持对国内外敌人的斗争。六、加强中国人民同世界爱好和平人民的友谊，反对侵略战争，保卫世界和平。七、在自愿的基础上学习马克思列宁主义和国家政策，开展批评和自我批评，努力进行思想改造。这七条准则是全国各族人民、各民主党派、各人民团体和其他爱国人士团结奋斗的共同政治基础。

关于人民政协的全国委员会和地方委员会。

经过一个月同各方面反复协商的结果，大家同意将原来的政协全体会议、全国委员会、常务委员会三层，改为全国委员会全体会议和常务委员会两层。地方委员会也是两层，即地方委员会全体会议和常务委员会。这样，减少了不必要的层次，又可以扩大全国委员会和地方委 员会的名额，有利于保持广泛的代表性，扩大团结面。

在全国委员会闭会期间，由常委会主持会务，领导日常工作，集中处理一般事情，这样更便于开展活动。过去五年中，政协常委会开了六十二次会议，比中央人民政府委员会开的会还多，并且习惯上是扩大的，在京委员都参加。按照政协章程规定，今后全国委员会全体会议每年召开一次，而政协常委会却可以多开一些。全国委员会每届任期四年，全体会议的会期，常委会根据需要可以提前或延期召集。章程还规定了参加政协的单位和个人都有遵守章程和决议的义务，并有退会的自由。

政协全国委员会和地方委员会是指导关系。上下之间有指导和被指导、指示和接受指示、报告和接受报告的关系。但是，各地设立地方委员会要因地制宜。因为在社会主义建设和社会主义改造中，各地情况不一样，工作发展不平衡，有的地方工业发展得快，国营、合作社企业很多，私营企业就比较少，如鞍山就与上海的情况不同，因此，两地政协的组成成员和工作重点也就不同。一定要因地制宜，这样才能合乎实际，合乎政协的原则。

关于参加政协的单位和个人。

参加政协第二届全国委员会的有十一个党派〔３５１〕、十七个团体〔３５２〕和特邀代表。

考虑到对人民事业的益处，合作社、医药卫生界、对外和平友好团体和社会救济福利团体都作为单独团体参加政协。

区域和军队不再作为参加政协的单位。因为全国人 民代表已经由地区产生，可参加全国人民代表大会。军队是国家的军队，受国家的指挥，也不需要作为政治团体参加政协。

关于第二届政协委员的安排原则。

政协委员的名单，经与各方面协商，由各党派自己提名。安排名单有四个原则：

（一）扩大团结，加强领导。这次全国委员会名单的人数、代表性、范围都比上届政协有所扩大，能够想到的都尽量包括进去了。全国人大代表绝大多数没有参加政协，这是因为全国人民代表大会是最高国家权力机关，既然已经是人大代表，就不一定参加政协了，特别是文化界、艺术界一些人大代表，平常写作、演出活动已经很忙，不能过多地参加会议，他们同意不再参加政协。这次政协增加了一些新人，团结面是扩大的。但扩大团结的同时必须加强领导。常委会领导要更集中一些，工作干部也要多一些。另外，党派参加政协的人数的增加，也有利于领导的加强。

（二）要有代表性。五百五十八名委员名单中，除兼人大代表的一百三十一人外，其他也都是各方面有代表性的人物。特邀代表的重点，放在加强反对国内外敌人的斗争，扩大团结面上，以影响台湾。对原国民党〔１４〕军队起义人员和其他起义的人物特别注意了安排。如这次特邀代表方面增加了翁文灏〔３３０〕。他是"戡乱"时期的行政院长，这次回来对他来说是个考验，也是个进步。有人批评政协名单里面什么人都有，我觉得好处就在这里。政协不是一盆清水，如果是一盆清水就没有意思了。政协就是要团结各个方面的人，只要他拥护宪法，立场站过来，我们就欢迎。当然也有立场还不是那么稳的，不一定能百分之百地执行七项准则，我们可以考察和帮助。

（三）方面多。在名单中各党派、各团体、各个方面都照顾到了。如工会方面，因劳动模范当人大代表的很多，政协委员就着重于新老工会工作者。农民也不都是生产合作社的社长或劳动模范，他们当人大代表的也很多，政协就着重吸收农村工作者。青年团方面，从青年角度出发，吸收了一些有代表性的人物。妇联的委员有妇女工作者、演员、小学教员、教授、少数民族等各方面的代表人物。工商联的委员名额也扩大了，凡在地方上有代表性的人物都照顾到了。文艺界有地方剧、音乐、舞蹈、美术、文学、电影等方面的人物，还有泥人张〔３５３〕。自然科学团体方面，设计工程、建筑工程、钻探等都有人参加。社会科学方面的代表性人物也不少。教育界、新闻界、医药卫生界、对外和平友好团体、外交学会、国际贸易、社会救济团体、少数民族、华侨、宗教界等方面，也各有自己的代表。

我们要吸收不同意见的人在一起，要善于和这些人一起协商，团结他们。这样，政治协商会议才能前进，才能有利于国家建设。

（四）份量够。每个方面都有带头的著名人物，他们的人数多少，要根据各种情况决定。

