# 不信教的和信教的要互相尊重

中文马克思主义文库 -> 周恩来
不信教的和信教的要互相尊重
（一九五六年五月三十日）

你们来中国访问很好。每年来一个代表团，考察考察，对我们提出批评，可以推动我们的工作。现在埃及已经和我们建交了，叙利亚等国和我们来往也很多。今后，我们和亚非伊斯兰教国家的来往将要更多。

我们的邻居不仅有信仰伊斯兰教的国家，还有很多信仰佛教的国家，他们的代表团来我国访问，对于我们的工作也是一种推动，会推动信仰佛教的少数民族地区的工作发展。

我们不愿意隐瞒自己的缺点，而是告诉大家，让大家批评。在座的都是宗教家。宗教在教义上有某些积极作用，对民族关系也可以起推动作用。

中国的民族很多，其中汉族的人口最多，约占我国人口的百分之九十四，其他民族只占百分之六左右。但是，少数民族居住的地方很大，大概占我国领土的百分之六十。人们都说中国"地大物博，人口众多"。其实汉族是"人口众多"，少数民族地区是"地大物博"，各占一条。所以，我们各民族必须互相合作，互相帮助，才能发展。而且，汉族应该更多地帮助少数民族。

要互相帮助，就要互相尊重，汉族要尊重少数民族的宗教信仰和风俗习惯。因为中国的少数民族大多信仰宗教，并且有不少的少数民族是整个民族信仰一种宗教的。回族、维吾尔族、乌孜别克族等都是整个民族信仰伊斯兰教。藏族全都信仰喇嘛教。这一点和你们的情况不同。你们信仰伊斯兰教，但你们民族中也有信仰基督教的，还有信仰印度教的。我国少数民族中信仰宗教的占很大比例。汉族当中也有很多人是信仰宗教的。汉族首先应该尊重少数民族的宗教信仰。其次是要尊重少数民族的风俗习惯。第三是要尊重少数民族的语言文字。对于没有文字的少数民族要帮助他们创制文字。但是，这些还不是根本的问题。最根本的问题是帮助少数民族发展生产，改善生活。如果少数民族在经济上不发展，那就不是真正的平等。所以，要使各民族真正平等，就必须帮助少数民族发展经济。

诸位是宗教家，可能担心宗教在中国的前途如何。我告诉大家一个事实：中国的宗教徒比共产党员多。中国共产党党员人数在世界上是最多的，现有九百多万；但是，中国的宗教徒有几千万，如果加上在家里信教而不到寺庙去的就更多，差不多有一亿了。所以，怎么能够取消宗教呢？况且，对全民族信仰一个宗教的少数民族来说，宗教对家庭关系、社会关系影响就更大些。中国的宗教信仰自由政策是在实实在在地执行着的。我们要造成这 样一种习惯：不信教的尊重信教的，信教的尊重不信教的，和睦相处，团结一致。这个话，我在万隆〔３６３〕说过，当时那里有很多宗教家。这不是忽然想起来的，而是我国的真实情况。这种政策是在实际行动中表现出来的。

你们都看了中央民族学院，那里有许多不同民族、信仰不同宗教的学生。我们在宗教上、风俗习惯上、饮食上都是尊重他们的。这个学校现在还办得不大好，今后要办得更好些。现在全国一共有八所民族学院，甘肃、广西、新疆等地都有。但是，我们觉得还少了些，和三千多万的少数民族还不相称，今后还要多办。我国的少数民族实行区域自治。自治机关主要应该由少数民族自己的干部组成，靠少数民族自己的干部去办事，不然就搞不好。多办学校，才能提高少数民族干部的水平。

高级的经学院办得也还少了些。为宗教服务的人员还不够，还要扩大。我们已经请了埃及的教师来讲课，埃及是伊斯兰教研究经学的权威地方。今后我们的事业发展了，别的国家愿意和我们交换教师、学生，我们也愿意考虑。

我们对于信仰佛教的民族也要帮助。最重要的地方是西藏，那里是喇嘛教。西藏的交通很不发达。我们去年修通了通往西藏的两条公路，从青海和四川都可以通到拉萨，这是很好的事情。今年飞机也通航了。在七千米以上的高空飞行，在三千米的高地上降落，这是新记录。航线是开始通了，但是还要试飞。明年，印尼和巴基斯坦的朋友们来，就可以乘坐飞机到西藏去看一看了。

我们虽然有很多建设，但是要摆脱落后状态，还需要很多时间。这种痛苦，我们这三个国家是相同的。我们都曾经遭受殖民主义的压迫，经济文化还很不发达。现在要赶上去，需要时间。因此，我们需要有一个长期的和平环境，这样有利于我们的建设。这也就是印尼苏加诺总统在美国所说的，亚非两洲人民不要殖民主义，而要独立；没有战争的要求，只有和平的要求。巴基斯坦总理今年就要到北京来访问了，我们要商谈合作和互相帮助的问题。我们不仅对印尼、巴基斯坦，就是对印度、缅甸、锡兰、泰国以至日本，都要和平共处，友好合作。我们的合作并不排斥任何国家，也不排斥美国。我们反对的只是美国的侵略政策。巴基斯坦和美国关系比较好。我们希望巴基斯坦总理劝劝美国，改变它的政策。世界人民要和平，不要战争。

我们经济上比较落后的国家要互相帮助，进行合作，并且我们也愿意和西方国家合作。但是，正象苏加诺总统所说的，不要有特权。这也就是亚非会议〔３６４〕的精神。

你们的邻国也是亚洲国家，应该共同团结起来。亚非国家内部的问题要靠自己的力量来解决。你们说中国是"长兄"，这是不妥当的。亚非国家不论大小，大家都是平等的。中国虽是大国，也不能居"长"，好居"长"是不好的。美国就是好居"长"，要领导世界，结果搞得大家都不高兴它。

作为六亿人口的国家，我们对世界的贡献还很小。比起我们的祖先来，我们做得还很差。一千三百多年以前，中国唐朝的首都长安，就是现在的西安，曾有十几万外国的居民。现在如果有一万个外国朋友同时来北京旅行，我们的房子就很成问题。所以，我们要做的和应该做的事情是太多了，而我们现在的力量是太小了。

杜勒斯〔３６５〕说中国要扩张。我们自己的事情还搞不完，哪里还会要扩张呢？我想和杜勒斯在一起谈谈，让他来中国看一看。但是，他不来，他坐在太平洋东岸说我们要扩张，这有什么办法呢？

我们亚非各国人民团结起来是个伟大的力量。这个力量是为人类服务的，而不是为了侵略别人。

我祝贺印度尼西亚、巴基斯坦两国繁荣。希望伊斯兰教友之间今后多多来往，每年开斋节〔３６６〕都应该彼此往来。

＊　这是同巴基斯坦伊斯兰教代表团和印度尼西亚伊斯兰教代表团的谈话节录。

