# 关于华侨的双重国籍问题

中文马克思主义文库 -> 周恩来
关于华侨的双重国籍问题
（一九五六年六月四日）


　　华侨的双重国籍问题，是侨胞感到困难的一个问题。但是侨胞们应该懂得，今天的中国是一个新的中国，一个已经逐步强大起来的中国，我们在国际关系上不能不解决这个问题。过去侨胞所在的国家，象印度尼西亚、菲律宾、缅甸、印度，都还不是独立的国家，都遭受着殖民主义国家的压迫，那时这个问题还可以马马虎虎。现在，我们彼此都是独立的国家，而且是友好的、平等相处的国家，我们怎么能够不妥善解决这个问题呢？

　　大家可以想一想，如果在我们国内，有几百万外国侨民，他们也是双重国籍，我们政府好不好办事呢？凡事都要推己及人。中国有一句老话叫做"己所不欲，勿施于人"。我们如果遇到这个情形，也不愿意，那么，我们在国外怎么能要求人家接受双重国籍呢？今天中国政府执行和平的、平等的外交政策，所以不能不解决这个问题。解决好这个问题，对双方都有利，也会提高我们国家在国际上的信誉。而且还要看到，过去中国弱，那时虽然也存在着双重国籍，但没有人拿这个问题来制造国际间的纠纷。现在中国强起来了，有的国家就会从中挑拨，说你们这样的大国，有一千多万华侨呆在海外，是不是想搞颠覆活动？当然你们诸位可以证明，这是毫无根据的。我代表政府也可以说明，我们绝不会干这种事情。可是，双重国籍问题如果不解决，人家还会感到有些不放心。

　　所以，这是一个涉及国家同国家之间关系的问题。不论从我们国家的对外政策上，还是从消除误会、解除怀疑、改善我们两国的关系上，都应该解决这个问题。这是大道理，要跟侨胞们讲清楚。这就是我们缔结关于解决双重国籍问题条约的根据。当然，这个条约实行的时候，还要做深入的宣传和解释，希望我们侨胞的领袖们好好地研究和推动这个事情。

　　在选择国籍时，最重要的一点就是要尊重本人的意愿。但是，具有双重国籍的人总是只能选一个国籍，要么选印度尼西亚国籍，要么选中华人民共和国国籍。这样，侨胞可能会发生一些波动和不安。我们应该注意到这一点，需要侨胞的领袖们去解释。特别是对年老的或者是在外地的，在农村的或者在工厂的，他们消息知道得晚，更需要侨胞领袖们到各地去宣传，在报纸上做解释。对于不识字的人，还需要别人读给他听，解释给他听。我们认为，快一点解释，快一点选择，有好处。

　　侨胞如果根据自己本身的利益，选择了印度尼西亚国籍，中国大使馆、领事馆将无保留地予以支持，不会有一点为难。有些侨胞可能会担心，选择了印度尼西亚国籍，华侨就看不起他了，说他忘掉祖国了。不，不应该采取那样的态度。我们应该采取赞助和友好的态度。选择了别的国籍，朋友仍然是朋友，兄弟仍然是兄弟。我们这两个国家可以说是亲戚的国家嘛！哥哥是印度尼西亚国籍，弟弟是中华人民共和国国籍，可以嘛，有什么不可以呀？有些人说，这样一家子分成了两个国籍，也不能来玩了。玩还是可以来玩，当朋友来玩。华侨总会，绍兴会馆，厦门、福建会馆，你可以作为印度尼西亚朋友，作为亲戚来玩。作朋友走亲戚照样可以，就是要把界限分清楚。这样，便于他工作。我今天跟印度尼西亚外交部长说，在印度尼西亚做部长的，做议员的，当然是印度尼西亚国籍，中华人民共和国绝不承认他还是双重国籍。都做了人家政府的部长，都当选了国会议员，还是双重国籍，道理就讲不过去。如果还承认双重国籍，那就是不尊重印度尼西亚的国家、政府和人民。今天的新中国不能这样，要讲道理。

　　我们尊重人家，划清界限，是为了便于工作。因为他作为一个印度尼西亚公民，就要根据印度尼西亚的宪法办事。双重国籍到底根据那一个宪法办事呢？把界限划清楚，就便于他的生活、工作和学习，便于他的一切。我告诉我们的大使馆和领事馆，对已经选择或将要选择印度尼西亚国籍的人，我们照样友好，尊重他们。只是一条，他到大使馆、领事馆来，我们以朋友相待，亲戚相待。

　　选择中华人民共和国国籍的，属于中国的侨民。他们要尊重所在国的法律，不参加所在国的政治活动，保持一个华侨的地位。这样，便于我们华侨同所在国人民友好相处。

　　总之，我们先友好地伸出手去，人家一定也会对我们友好的。中国有一句成语，叫做：投桃报李。就是说礼尚往来。我们对人家友好，一定也会得到友好的回答。所以这个问题虽然困难，但我们把它说透了就会很好地解决的。

　　我坦率论说，如果华侨有很多人选择了印度尼西亚国籍，我们中华人民共和国大使馆、领事馆不会说一个"不"字或者跟他们为难，不会的。可是反过来我们也要说明，我们不能向我们侨胞说，我们不要他们了，绝对不能说出这个话来。选择国籍是个人的自由，选择印度尼西亚国籍，或者选择中华人民共和国国籍，条约上都许可。所以，愿意选择印度尼西亚国籍的，我们赞助他，愿意选择中华人民共和国国籍的，我们欢迎他。

　　我们侨胞本身有许多事情，常常要找大使馆、领事馆，我们应该尽力帮助诸位解决困难。有的愿意回国参观，有的愿意回国学习，凡是我们能够做的，我们都要做。但是，新中国的建设刚刚开始，要赶上世界工业发达的国家，大约还需要半个世纪。我们人口多，困难也不少，建设的任务是艰巨的。国家的财力，现在首先用于建设重工业，这是为长远建设打基础。建国以后，学校虽然增加了很多，但一时还不能完全满足需要，有些事情要办得慢一点。我们这个民族能够忍受和克服艰难困苦。我们遭受了帝国主义一百多年的压迫，奋斗了一百多年，经过近三十年的努力，中国革命才取得了胜利。我们搞建设也要有这个耐心。所以，诸位侨胞对祖国的要求，一下子还不能完全满足，要逐步地实现。将来国内的条件好了，你们的子女回祖国去念书，还是有机会的，还可以学现代化的最新的科学，连原子能都可以学习嘛。

　　最后，希望诸位在海外要注意团结。不仅要团结侨胞，还要跟所在国家的人民团结在一起，跟他们友好相处。要尊重他们。要得到人家尊重，首先要尊重人家。我们丝毫不要骄傲。每个国家和民族都有自己的优点和长处。我们要善于学习。要提倡互相学习，互相尊重。如果发生了一些困难和纠纷，我们应该首先批评自己，这样就会更加团结，就会得到所在国政府和人民的尊重。



　　＊  这是在印度尼西亚雅加达对华侨的讲话节录。



