# 稳步地实现少数民族地区的民主改革

中文马克思主义文库 -> 周恩来
稳步地实现少数民族地区的民主改革
（一九五六年七月二十四日）

党中央认为，四川甘孜藏族自治州和凉山彝族自治州的改革是必要的。我国各民族都要过渡到社会主义，少数民族地区都要进行民主改革和社会主义改造，消灭剥削制度，这是我国宪法规定了的，我们应该遵照宪法办事。当前进行的改革是要把奴隶、农奴从旧制度下解放出来，使他们都有土地耕种。这种改革是民主性质的改革。

对于民主改革问题，去年大家在四川省人民代表大会上作了协商，下了改革的决心，这都是对的。我们说过，实行民主改革要和上层人士协商，要安排好上层人士，使他们的生活不比改革以前坏。在群众迫切要求改革的情况下，上层人士考虑到改革后，政府将给他们安排工作，生活不会比以往依靠剥削的时候坏，他们就会同意改革。这样，上层人士和群众认识基本一致了，改革就容易进行了。这就叫做和平改革。过去云南、新疆等少数民族地区的改革都是这样办的。这些 地区的经验证明，实行和平改革是可能的。

党和政府力求实现和平改革，但不能说和平改革就不会遇到一点阻碍。可以想到，会有一些过去站在群众头上的人，舍不得眼前的个人利益，对党和政府不相信，有怀疑，有顾虑，害怕安置工作后得不到好的结果，不听我们的话。也有些头人想和政府较量，四川凉山彝族自治州就因为有这类人，而发生了叛乱。甘孜藏族自治州也是这样。这是不好的事情，是不幸的事件，但是它已经发生了，就不能不设法补救。同时我们也要估计到，我们的工作不是没有缺点和错误的，有些缺点是工作中不可避免的，但也有些缺点是可以避免的。对能够避免的缺点而没有避免，就影响和加重了他们不相信政府的心理。并且这些缺点也很容易被叛乱分子当做反对改革的借口。但是发生叛乱的主要原因还是有些人掌握武装，想和政府较量较量。

叛乱发生后，政府和藏族、彝族人民一道来平息叛乱，同叛乱分子进行了武装斗争。这种斗争是阶级斗争性质的。但是，我们要注意到，叛乱分子会把这场阶级斗争说成民族斗争和保卫宗教的斗争。他们的目的是保护封建主和奴隶主的所有权；我们的目的是救出被包围的干部，解放被压迫的劳动人民，因而得到藏、彝族劳动人民的拥护。我们从来都主张和平改革，进行平息叛乱的武装斗争是被迫的。我们必须把工作做得更好，解除叛乱分子的种种借口。

那么，怎样把工作做好呢？我们提出以下几点意见：

一、力争实现和平改革。有关改革的问题，要根据群众的意愿，经过和少数民族上层人士协商，取得上层人士同意后再去进行。在协商过程中，必须用道理说服人，不要强加于人。汉族干部必须有耐心，要善于等待，少数民族不同意的，就不忙着去做。改革的内容不外两条：一条是使广大人民获得解放；一条是使上层人士失去对土地和奴隶或农奴的所有权，但得到政府的安置。在少数民族地区实行这样的民主改革，既有利于人民，也有利于上层人士。一般地说，少数民族上层人士的生活水平是不如汉族中的资本家的。汉族一些大资本家都得到了安置，少数民族中的封建主、奴隶主当然也可以得到安置。

二、地主、奴隶主多余的浮财可以不动。云南德宏傣族地区土改时，对于地主多余的耕畜、农具、粮食和房屋都没有动。我们认为，在四川藏区、彝区民主改革中，对地主和奴隶主的这四种多余的浮财也可以不动。不动就是不征收。地主、奴隶主多余的这些东西，当地劳动人民缺乏而又确实需要的，可以由政府出钱购买。详细办法请自治州政府和大家讨论协商决定。

三、对藏区的寺庙应该采取更慎重的态度。我们从来都是主张尊重兄弟民族的宗教信仰自由的。在改革中牵扯到寺庙的耕地等问题，必须慎重对待。中央在讨论这个问题的时候，桑吉悦希〔３６９〕同志主张寺庙所有的耕地等财产暂时不动，我们认为他的意见是对的。寺庙的耕地不动；寺庙的枪支也不动，但是不能拿枪去为非作歹；寺庙放的高利贷也可以不动，农民如果要求政府解决，政府可以帮助农民还债；群众对寺庙的差役负担，政府不干涉，但是农民如果不愿去做，寺庙也不要强迫他们。方才喜饶嘉错〔３０７〕代表对我说，青海农业合作化后，农民忙了，不去寺庙上布施了。这个问题，我想应该从两方面来看，一方面农民确实忙，另一方面农民个人所得还不多。今年秋天合作社收入分配后，有关省、县的人民委员会和合作社都不要干涉农民给寺庙上布施。当然，布施也许会比过去减少一些。如果寺庙的经费发生困难，政府可予以救济。

四、一定要处理好民族问题。在民族地区，处理任何事情都要考虑到民族问题，都要和少数民族干部商量，因为他们比汉族干部更懂得本民族的心理。他们点头，我们再干。他们不点头，我们就不要干。我们可以说服、等待，不能强加于人。毛主席说：外来干部要尊重本地干部，应当成为一条规矩。外来干部和本地干部尚且如此，何况不同民族的干部呢？

在少数民族地区，办事情要靠少数民族干部，因此我们必须培养少数民族干部，逐步使他们在各民族自治地方的自治机关、企业、学校中都占大多数，并且担任主要的领导职务。

民族自治地方应该享有宪法上规定的自治权利。关于财政管理权的方案，正在准备，将要提到最近就要召开的体制会议上研究。民族自治地方可组织本地方的公安部队，这在宪法上也有规定。压迫群众的人手中有武器，群众不放心。武器放在人民手中，就可以防坏人了。请在座的陈赓〔３７０〕副总参谋长召集会议研究一下。

少数民族地区经济生活比较落后。要改变这种落后的状态，首先必须发展交通事业。甘孜藏族自治州决定要修从康定到巴塘的公路，凉山彝族自治州也要修两条公路，我们已经请交通部研究修筑这几条公路的方案。

改革要更有准备、更有步骤地进行。在某些应该让步的问题上要让步。应该避免把改革问题同民族问题、宗教问题混淆起来，使改革做得更好。以上说的各种工作都做了，道理就全在我们方面。也许还有些人手中有武器，还想和政府较量较量，那时他们再闹起来，就更加得不到人们的同情，我们的损失就会减少。对付这些人我们应该是有准备的，但我们不主张用武力解决，我们主张用和平办法来解决问题。

五、对于现在还在山上叛乱的武装应该怎么办呢？办法是停战和谈。连蒋介石这样的人我们都肯跟他和谈，对于叛乱的地主、奴隶主又有什么不能和谈的理由呢？要反复跟他们和谈，允许来去自由。要他们来和谈，和谈不成，还要回去打，我们也不杀害他们。这样做，相信和谈可以成功。有关地方国家机关要认真地进行和谈，一次不行，再来二次，如果他们硬要打，我们就自卫。我们不是压迫者，只要叛乱分子停止叛乱，一律宽大处理，一个不杀。三国时诸葛亮七擒七纵〔３７１〕，我们要十擒十纵，百擒百纵。四川省的气魄应该大些，否则就要甘拜诸葛丞相的下风了。过去青海争取项谦〔３７２〕就是这样做的，这是一条很好的经验。

我们工作中是有缺点、错误和偏差的，如急躁、冲动，甚至在战争中出现报复情绪等。因此，我们要进行工作检查，要纠正偏差，改正错误，对于犯有严重错误的人要予以批评，对于违法乱纪的人要予以处分。出现缺点、偏差的责任大部分在中央，因为中央对下面的指示不那么具体。至于有些上层人士在改革中受了些委屈，也不要太生气，要想到群众过去一直是受压迫的，一旦翻身，做出这样举动是很自然的。

中央和四川省要组织慰问团到这两个自治州进行慰问。西藏过去曾经提出要组织一个代表团去甘孜藏族自治州参观，我们认为应该欢迎他们去那里考察。凡是工作中的缺点、错误要承认，工作中的好经验要坚持，好的坏的都让人民知道，这就是我国人民政权的特点。

以上是中央讨论四川藏区、彝区问题后的一些意见，现在向大家传达完了，大家有意见还可以提。这些意见，大家回去都可以向省、自治州人民委员会和省委、地委去谈一谈，还可以讨论。

＊  一九五六年七月二十二日中共中央讨论了四川甘孜藏区和凉山彝区的工作问题。这是周恩来召集在京的民族上层人士所做的传达报告。

