# 做一个守法的模范的侨民

中文马克思主义文库 -> 周恩来
做一个守法的模范的侨民
（一九五六年十二月十八日）


　　我很高兴有这个机会在仰光和这么多的侨胞代表见面。

　　你们已经多少代在这里生活了。过去缅甸和中国一样，遭受外国侵略者的压迫，因此两国在历史上的友谊被隔断了，侨胞们在这里也就遇到许多困难。现在，我们两国都获得了独立，两国兄弟般的友谊更加发展了。我们侨胞在缅甸，受到了独立的缅甸政府的优待。我们应该感谢缅甸政府。

　　侨胞在这里住久了，有的和缅甸朋友通婚，逐渐地成为缅甸公民了，所以我们两个国家是亲戚的国家。缅甸人民把中国人民叫作"胞波"，"胞波"就是同胞的意思，就象亲兄弟亲姊妹一样。侨胞在许多国家都有和当地人民通婚的，这是很好的事情。通过这种关系，可以撒下和平共处的种子。和平共处五项原则〔３７３〕早就在我们侨胞和缅甸人民的关系中播下种子了。你们有不少人或是自己或是自己的亲戚和缅甸朋友结婚了，有这样好的亲戚，我们应该祝福你们。

　　我们侨胞既然是长期在国外，就应该和所在国政府和人民搞好关系。从政治上说，侨胞应该遵守所在国家的法律。从社会关系上说，应该尊重所在国的风俗习惯，尊重他们的宗教信仰。从个人来说，应该建立良好友谊。这样，就能够使侨胞长期在这里居住，而且友好相处。所以，中国政府号召侨胞要遵守所在国的法律，尊重所在国的风俗习惯、宗教信仰，这是很重要的。如果有些侨胞居留的年代久了，取得所在国的国籍，成为所在国的公民了，这样，好不好呢？好。中国政府早在两三年前就公开宣布，华侨的双重国籍问题是必须解决的。只要根据自愿的选择，并得到当地法律许可，取得侨居国国籍后，就不再有中国国籍了。这些人是不是会受到同胞们和中国政府的歧视呢？不会的，因为我们还是亲戚。亲戚有什么不好呢？就好象女儿嫁出去后，不再是娘家的人，但是还是亲戚嘛。男的呢？男的也可以招赘嘛。我不晓得广东、福建有没有这样的习惯，北方就叫招赘，就是女婿跟媳妇过来了，这不也是很好吗？对缅甸来说是给他们添丁，对中国来说是增加一门亲戚。所以，有些侨胞在选择了缅甸国籍后，我们一律当成好亲戚看待。这是应该讲清楚的。当然，不可能人人都这样选择，总有一部分还是华侨。如果还是华侨，就应该做一个守法的、模范的侨民，不参加所在国的政治活动，比如不参加他们的政党、选举等。同时，我们也不在华侨中发展共产党和其他民主党派组织。这样，人家才会尊重你们。希望住在这个地方的侨胞，不论做工的、经商的、经营企业的，或是搞文化事业的，不管做哪一行，都要按照所在国的法律办事，都应该做一个守法的侨民，模范的侨民。

　　大多数的华侨，都是由于生活困难到海外谋生的，多数会做买卖，通俗一点来说，是会赚钱。赚钱有两种：应该赚的，我们就赚；不应该赚的，就不要赚。因为做买卖总是替人家互通有无，要远道运输，还要经营管理，这要费心血，费劳力，所以钱总是应该赚的，这是许可的。不应该赚的钱，就象抬高市价啦，搞黑市啦，这会使广大人民，特别是劳动人民吃亏。这是不应该的。中国有句老话：非义之财不可取。想通这个道理之后，就应该做一个正当的商人、模范的商人。

　　你们要在这里长久居留，安居乐业，总要有长远的打算。从事商业有时是不稳定的，而工业是有长远前途的。工业的利润来得慢一些，可是稳一些。真正的企业家应该把自己的游资用于经营工业、手工业。这对自己的事业是一个长期打算，对缅甸国家的建设也可以尽一份力量。希望侨胞们考虑、研究这个问题。缅甸政府表示愿意在这方面给予鼓励。

　　你们有从事文化事业的，比如办报纸、办教育，在这方面应该注意提倡学习缅甸文、缅甸话。有些侨胞在这一点上是很保守的，很多人在外国居住了几十年，都不懂得一句外国话。有的说：年纪老学不好。我看不见得。举个例子吧！你们一定很相信毛主席。毛主席年纪大了，他现在六十三岁了，还在学英文。他把全国人民代表大 会通过的五年计划、李富春〔１３１〕同志关于五年计划的报告和我们党八大的几个报告的英文译本都拿来读。他的英文单词比我记得还要多，我比他落后了。我有许多场合能碰到外国朋友，可以说几句英语，而毛主席没有机会讲，可是他也学。所以说，人是要活到老学到老，永远也学不完的。我奉劝在海外的侨胞，一定要学习外国语言。缅甸华侨的年轻一代，更应该懂得缅甸话。

　　华侨报纸增加缅文版就更好。华侨看汉文，也要看缅文。在华侨学校里，缅文应该成为必修课。侨胞一定要把侨居国的语言和文字学好，这样，才能直接沟通感情，促进文化交流。

　　中国人学外国话并不难，就是有一点保守和懒得学，这也许有点大国主义。在国与国之间，我们的国家大，就要反对大国主义；在国内的民族与民族之间，我们汉族是大民族，就要反对大汉族主义；在个人与群众之间，居于领导地位的人容易目空一切，就要反对官僚主义。反对这三种错误倾向都要反对自高自大。因此，奉劝我们的侨胞，不要有这种自高自大的思想，要谦虚、谨慎。采取这个态度，就能够把工作做好，把人的关系搞好，把国家的关系搞好。

　　最后讲一讲侨胞内部的关系。今天你们到大使馆来，是代表侨胞的多数。但是，侨胞中总有少数人不满意新中国，或者持怀疑态度。这大概可以分成三种人，一种是不了解情况，采取旁观态度；一种是有不满情绪的，暂时处于对立状态；一种是坏的。对于头一种人，应该对他们多做解释，不能怪他们落后。第二种人的不满，可能是由于国内有些事情做得不好。我国才独立了七八年，哪能事事都搞得很好呢！我国总的方向是好的，要建设社会主义国家。但是在具体工作中还存在很多错误和缺点，所以不能使他们都感到满意。我们有错误，要自己批评纠正。他们不改变，我们等待，也不要随便加一个帽子说他们是落后分子。第三种是坏人，坏人是极少数，但坏人也不是不能改变的。对于现在还是坏的人，我们也不要对他绝望，应该向他伸出手，争取他，希望他回心转意。只要他爱祖国，我们就和他团结起来，团结在爱国主义的旗帜下。

　　感谢你们代表各地的侨胞来欢迎我们。你们有人从很远的地方来到仰光，有的等了很久。你们都很辛苦，在海外也很辛苦，我向你们再一次表示感谢。



　　＊这是在缅甸华侨举行的欢迎周恩来总理大会上的讲话节录。



