# 民族区域自治有利于民族团结和共同进步

中文马克思主义文库 -> 周恩来
民族区域自治有利于民族团结和共同进步
（一九五七年三月二十五日）


　　这次座谈会开得好，收获很大，各方面的意见都听到了。在个别具体问题上，少数人的意见有些出入，这是难免的，因为各人从不同的角度看问题，意见总会有出入的。可是在基本问题上，即在壮族必须建立省一级的自治区的问题上，在合的方案比分的方案为好的问题上，绝大多数人的意见是一致了，这就是很大的成功。大的方面意见一致了，是不是可以认为建立壮族自治区的工作从此就完全顺利了呢？不是的。这个工作才开始，我们还要经过从上到下、从下到上的酝酿，把广大人民群众讨论的意见集中起来，经过国家权力机关审核批准，才能付诸实施。只有把工作做得成熟了，才会收到好的效果。

　　现在，我想就会议的内容讲几点意见。

一

　　这次座谈会所讨论的是关于处理民族问题的方针问题，所以有必要从原则上和历史上说一说。

　　广西境内，有苗、瑶、侗、壮好几个少数民族。民族问题很复杂，过去我们对少数民族的情况了解得也很少。在汉族史书上记载少数民族的名称，几乎都加个"犬"旁，说他们是"非我族类"，宣扬汉族至上。直到民国初年编的《辞源》上，还是那样写的。这就是大汉族主义的表现。

　　我国有些少数民族，原来是居住在中原的，后来汉族逐渐发展，就把他们挤到边疆去了。汉族人口多，所居住地区的地理气候条件好，经济、文化也比较先进，处在有利的地位，这样汉族就逐步地得到了较快的发展。在历史上，也有些少数民族进犯过汉族，史书上叫做"异族入侵"。各民族间互相侵扰，本来是件坏事情，但在客观上也产生过好的后果。它造成了民族杂居，进而互相通婚，文化交流，促进了各民族互相学习，取长补短，使各民族的长处容易结合起来。汉族在长期的历史发展过程中，就不断吸收了其他民族的优点，不断和其他民族混合，它不但没有衰落下去，反而更加发展了。这就是说，少数民族侵入汉族地区以后，在客观上对汉族的影响还有它的好的一方面。例如满族不过几十万人口，但是它建立的清朝统治中国长达二百多年，正说明它是一个有本领的民族，是值得佩服的。今天我国的版图这样广大，就是从清朝继承过来的。我国地大物博、人口众多，应该承认清朝对此是有贡献的。清朝有些政策对人民也是有益的。可是到后来，上层统治者腐化了，抵挡不住西方资本主义国家的侵略，并且加深了对人民的压迫，汉族再也不能忍受它的统治，才起来推翻了清朝。清末，鼓动革命的文章，例如邹容〔３７４〕写的《革命军》，现在读起来还会感到痛快淋漓。当时人们把满族说得坏些，这是可以理解的。可是，今天就不能再那样看待满族了。因为过去统治中国的是满族中的统治阶级，而不是满族整个民族。即使谈到满族统治阶级，他们在历史上的作用，有坏的一面，也有好的一面。清朝被推翻以后，情况变了，在北洋军阀〔１４４〕和后来的国民党统治的时代，汉族占了统治地位。国民党不承认少数民族，只提"边疆问题"，并且在政治、经济、文化上压迫少数民族，这样就更加深了民族隔阂。历史证明，旧统治者是永远不能够解决民族问题的。

　　现在，我国已经完成了民主革命，进入了社会主义时代，一定要彻底实现民族平等。我国的实际情况是，汉族无论在政治、经济、文化乃至军事各个方面都占绝对优势。例如在军队中，汉族军事工作人员占绝大多数。汉族中各方面的人才也很多，少数民族中各方面的人员就比较少。汉族要经常注意到这种情况。

　　人们常说，少数民族习惯于游牧、渔猎。事实上，他们不能不那样生活，这也是历史造成的。正如我在前面 讲过，汉族愈发展，就愈把许多少数民族挤到边疆，汉族统治者在政治上压迫他们，在经济上剥削他们。我们只要到内蒙古去作个调查，就知道过去汉族商人是怎样利用蒙族人民文化上的落后去盘剥他们的。现在全国有五十多个少数民族，他们的人口合计只占全国人口总数的百分之六，尽管汉族挤他们，可是他们居住地区的面积还占全国总面积的百分之六十。由于人口众多的汉族早就占据了有利于农业发展的地区，致使他们住的地方中有不少是高寒山区和沙漠地带，给他们的发展造成很大困难。

　　今天，汉族应该多多地替少数民族设身处地想一想，不要让他们再受委屈，应该使他们也能得到较好的发展条件。只有汉族主动地替少数民族着想，才能够团结好少数民族。不要一讲到壮族自治，就讲汉族的民族感情。我同意梁漱溟〔２９３〕先生在这次会议上说过的一句话，要"互相以对方为重"。

　　任何民族都有它的民族心理感情。汉族因为居于优势地位对少数民族的心理感情是不容易体会的。比如，在承认满族的问题上，就经历过一段曲折的过程。辛亥革命以后，由于推翻了清朝，整个满族也抬不起头来，他们用汉文，改满服，有些人还改了姓氏。从形式上来看，满族和汉族没有区别了，可是实际上，满族还是有它自己的民族感情的。不能设想，满族和汉族杂居了二百多年，今天满族就没有特点，完全和汉族一样了。在第一届政协第一次会议中满族没有作为民族单位被邀请，这是一个错误，当时以为满族已经没有什么特点了。到了召开第一届政协第二次会议的时候，才有了满族代表出席。当承认了他们的民族地位以后，满族人过去几十年来抑郁的感情才舒畅了。这就告诉我们汉族同志，尤其是担任领导工作的同志，应该注意了解兄弟民族的心理感情，应该学习研究兄弟民族的历史、文化。兄弟民族中有过一些有成绩的人物，对他们的历史遗迹，我们应该加以保护，例如颐和园中的耶律楚材〔３７５〕墓，西湖上的康熙〔３７６〕、乾隆〔３７７〕碑等等。我国的史书，总是按汉族的观点记录历史事实，把汉人压迫少数民族引起的反抗叫做叛乱。我们不能责备当时的历史学家，因为他们受时代和阶级的限制。但是，现在我们运用这些史料的时候，就要善于分析、研究，要有正确的观点，并且要多替少数民族设想，看有哪些历史问题还没有正确的结论。

　　我们主张把全国各民族都联合起来组成一个民族大家庭。在各民族相处中，第一，汉族一定要自觉，遇事应多责备自己，要严于责己，宽于待人。这样少数民族也就会跟着汉族的样子做，各个民族就会真正自愿地合起来。第二，要在民族大家庭中搞好团结，不能怕麻烦。一时怕麻烦，日后就会生出更多的麻烦来。民族问题本来就是个复杂的问题，麻烦的问题。每个民族都有它长期发展过程中遗留下来的历史痕迹。对待民族问题，要作历史的分析，并且要有阶级观点。在有阶级的社会里，民族问题离不开阶级问题，但是民族问题又不完全等于阶级问题，所以这两个问题既有联系又有区别。

　　有人说壮族特点少。壮族留下来的历史痕迹是比较少些，但壮族有自己的语言、文化，这些都是它的特点。我同意李维汉〔２３０〕同志对民族问题的意见。在我国，不能死套斯大林提出的民族定义。那个定义指的是资本主义上升时代的民族，不能用它解释前资本主义时代各个社会阶段中发生的有关的复杂问题。尤其在我国，封建社会历史很长，汉族和非汉族的冲突斗争很多，这说明民族之间的界限是存在着的。我国许多民族在解放前虽然没有发展到资本主义阶段，但是它们的民族特征都已不同程度地存在着，这种历史和现实的情况都应当正视、研究和照顾，否则就不能合起来。我们只要从事实出发，毫无疑问就应该承认壮族是一个民族。

二

　　从通过《共同纲领》的时候起，我们就根据马列主义关于民族问题的一般原理和我国民族关系的实际情况，采取了民族区域自治政策。我们不主张民族分立，也没有采用联邦制。我们采取这样的政策，主张合，不主张分，是适合我国的历史情况和社会环境的。我国是被帝国主义压迫过的国家，是从反殖民主义的斗争中，从民族解放运动中发展、成长起来的，因此，国内各民族宜合不宜分。我们采取民族区域自治政策得到了国内各民族的支持。他们都懂得，只有合起来组成一个民族大家庭--中华人民共和国，才能抵抗帝国主义的威胁和侵略。一九五四年公布的宪法更对民族区域自治作了明确的规定。我们全国各民族都团结起来了，连西藏也得到了和平解放。尽管目前帝国主义进行阴谋活动，指使西藏一些上层分子闹独立，我们按照十七条协议〔３７８〕办事，闹独立的阴谋是难以实现的。可见，民族区域自治适合于象中国这样的从民族解放运动中发展起来的国家，它可以防止帝国主义的挑拨，促进国内各民族的团结。

　　现在，我讲一讲大家提到的几个问题。

　　一、关于合与分的问题。不论是从全国来看，还是从一个省来看，都需要合。为了合，就要采取一些必要的照顾少数民族的办法。今天会上李济深〔８５〕副主席谈话的精神就是主张合，并且说汉族要对少数民族有所让步。合，就要多为少数民族着想，少数民族也才能为汉族着想。今天，要想一想少数民族的好处。汉族人口众多，经济文化比较发达，但地大、物博都在他们那里。从全国来说是这样，广西也是这样。将来发展工业，扩大农业，都要大力开发少数民族地区，都需要把地大、物博和人口众多、经济文化发达结合起来。可见，合则双利，分则两害。

　　二、可不可以讲还债的问题。不叫还债，叫赔不是也可以。讲还债这是个比喻。有些人害怕提还债会引起民族关系搞不好，这是不必要的顾虑，哪里会有这种事情？严格地批评自己，不但不会引起对方的反感，反而会促使对方对自己缺点的注意。历来的经验都证明了这一点。还有些人担心，讲还债就会被帝国主义利用。这种担心也是不必要的。讲还债有利于民族团结，这是符合马列主义真理的。真理是驳不倒的，敌人利用也不用害怕。

　　历史上汉族长期处于优势地位，汉族统治阶级要么把少数民族同化，要么就把少数民族挤到边疆和生产条件差的地区。处于劣势地位的少数民族得不到发展，因而落后了。当然不是说少数民族什么都落后，他们当中也出了许多先进人物，那是奋斗出来的。汉族如果承认这个历史事实，就应该向少数民族赔不是。这样说是不是会引起少数民族骄傲，引起少数民族来登门讨债呢？不会的。对人民的觉悟不能低估。我们不仅这样说，还要在实际上这样做，帮助少数民族和汉族一起发展。就是这样，他们的发展也是不容易的。如果汉族不去帮助，就合不好，少数民族受帝国主义挑拨，提出要分，那就很不利。例如，西藏就因为有帝国主义挑拨，而发生少数上层分子闹独立这么回事，我们就需要做很多的工作说服他们要爱祖国，不要被帝国主义利用。为了合得好，汉族应该帮助少数民族。但从汉族的角度说来，宁可说是赔不是、还债，而不说帮助，这样，少数民族就会说是帮助。我深信越是劳动人民就越讲道理。

　　必须看到，历史上有大汉族主义思想，现在也还有自觉的或不自觉的大汉族主义思想，当然，不自觉的多，自觉的少。这样说是不是就没有地方民族主义了呢？地方民族主义也是有的。例如藏族某些人就有。要少数民族克服地方民族主义，汉族首先就要克服大汉族主义。汉族是老大哥，应该作表率，这样才能促使他们自觉地克服地方民族主义。

　　三、民族感情问题。各民族都有自己的民族感情，它是长期历史发展形成的，并且在很长的时期里还要存在下去。民族感情有两面性，要加以分析。当帝国主义侵略的时候，民族感情可以发挥团结人民的作用。当年苏联打败希特勒德国的侵略，一个重要条件就是激发了社会主义感情和民族感情。但是还要承认民族感情也会被反动阶级利用，变成狭隘的民族主义。民族感情发展到对外排斥一切，向外扩张领土的时候，就带有反动性了。社会主义国家应该把民族感情和社会主义结合起来，不结合起来，不注意民族感情和民族特点，或者过分强调民族感情，都会犯错误。我们要注意这个问题。对民族感情要适当的重视，无视它是不对的。一个省，甚至一个县也会有地方感情，何况一个民族呢！民族感情也好，地方感情也好，都有两面性。它在阶级社会里，总是带着阶级的烙印。但是，如果把民族感情完全说成是阶级感情那也是不对的。民族感情运用得好，能成为推动进步的力量，反抗帝国主义的力量，运用得不好，就成为排它性的民族主义感情，分的感情。地方感情也是这样。

　　四、民族区域自治中的几个有关问题。

　　（１）我国和苏联的情况很不同。在我国，汉族人口多，占的地方少，少数民族人口少，占的地方大，悬殊很大；在苏联，俄罗斯人口多，但占的地方也大。中国如果采取联邦制，就会在各民族间增加界墙，增加民族纠纷。因为我国许多少数民族同汉族长期共同聚居在一个地区，有些地区，如内蒙古、广西、云南，汉族都占很大比重，若实行严格的单一民族的联邦制，很多人就要搬家，这对各民族的团结和发展都很不利。所以我们不采取这种办法，而要实行民族区域自治的政策。

　　我们的区域自治政策，利于合，利于团结，利于各民族的共同发展。但是要承认自治地方中有多数与少数的问题，即承认矛盾，然后取得统一，共同发展，合起来把我国建设成一个强大的工业化国家。要用事实证明，自治区的汉族和少数民族共同发展下去不会对少数民族不利，不会把他们挤掉。我们应该创造一些范例，使少数民族感到汉族人到少数民族地区去，不是压迫他们的，而是同他们合作的。在这方面，绥远并入内蒙古自治区就是个范例，广西也应该这样做。应该承认，这是一个复杂问题，必须交群众广泛讨论。

　　（２）在建立壮族自治区问题上，绝大多数人认为合有利，分不利。从坏的方面想，万一搞不好，也只好分。但是我们要争取合，合是方向。这个问题，还要提到人民群众中去讨论。在讨论的时候，可能有局部地区的群众由于一时不了解情况而赞成分，但是只要把道理跟他们讲清楚，他们还是会赞成合的。

　　（３）团结与制约的问题。几个民族居住在一起总会有矛盾。怎么办呢？要承认矛盾是客观存在的。在民族自治地方，少数民族自治，汉族又占多数，因而可以考虑将来在自治区的执行机关和权力机关中对各民族人员作适当的安排。既然是壮族自治区，行政领导人就应该由壮族人担任；因为汉族占多数，在人民代表中，汉族代表比例应该与人口比例相适应，人大常委会的委员长也可以考虑是汉族人。这样才符合实际情况，可以起互相制约的作用。这是可以研究的问题，不是今天说了就算决定了。有团结，有制约，政治运用上安排恰当，目的是为了团结。

　　（４）实质与形式问题。如果我前面所说的在少数民族地区占人口多数的汉族参加自治区，合比分好，有团结、有制约等问题，大家都同意，那么，基本问题即实质问题就解决了。仅仅剩下名称问题就好解决，因为这已经不是实质问题而是形式问题了。现在大多数人同意用"广西壮族自治区"这个名称。如果有比这更好的名称，未尝不可以考虑。这次可以不做结论。名称总要使少数民族感觉到是个自治区，不要为保留一个"省"字，把广西各民族人民共同前进的道路阻挡了，那样将来我们的子孙会笑话我们的。

三

　　再讲一讲实施民族区域自治的具体措施。

　　首先，要发动群众讨论。建立广西壮族自治区是一件大事情。广西建省的历史很长。绥远建省的历史比广西短得多，但是并入内蒙古自治区还花了五年功夫。因此，必须广泛地发动广西各族人民群众进行讨论。不仅要提到省人民代表大会、政协去展开讨论，而且还可以提到县、市人民代表大会去展开讨论。还可以选择一些汉族聚居的区、乡去讨论。一方面要发动各族人民群众进行讨论，一方面又要向他们进行宣传和教育工作。要确定建立壮族自治区，汉族和壮族合作，这些方针肯定了，发动群众讨论才有方向。

　　至于有人提出采取公民投票的方法，那是不妥当的。公民投票和民族自决口号一样，名字好听，但是容易被帝国主义利用。在座的都是爱国主义者，对于这一点是不能不深思熟虑的。如果在这个问题上搞公民投票，就可能对立起来，不利于团结，不利于社会主义建设。在建立壮族自治区问题上，还是应该有领导地确定一个方案，这个方案既要适合绝大多数人的利益，也要照顾到少数人的不同意见，目的是使广大人民群众能够接受。

　　广西讨论的时候，还可以组织参观团去那里参观和参加讨论，吸收在全国各地工作的有代表性的广西人和关心这个问题而又愿意去的人士参加。

　　其次，要做好筹备工作。在自治区成立以前，汉族要多负些责任，自治区经过全国人民代表大会批准以后，壮族就要多做工作。当然，汉族也不能旁观。建立自治区的有关问题，要设想得更细致些，要比李维汉同志发言中已经提到过的更加详细具体些。

　　再次，要做好宣传工作。从历史的阐明到各项具体政策的解释，都要认真做好。广西有上千年的历史，远的且不说它，近的从太平天国以来汉族和壮族就有亲密合作的历史。要用这些历史事实去向群众做宣传教育工作。

　　如果这些工作都做好了，建立自治区问题，就会瓜熟蒂落，水到渠成了。

　　最后，关于壮族名称使用哪个汉字的问题。"僮"字的确容易念错。依照本民族的自愿选择，改变一个好一点的汉字是可以的，这里不做结论。



　　＊　这是在中共浙江省委扩大会议上的讲话节录。



