# 长期共存，互相监督

中文马克思主义文库 -> 周恩来
长期共存，互相监督
（一九五七年四月二十四日）

长期共存，互相监督，主要是讲中国共产党跟其他民主党派的关系。党派的存在与否，不取决于任何政党或个人的主观愿望，而是由客观的历史发展所决定的。苏联在十月革命以后，列宁也曾经想争取同社会革命党〔３７９〕合作，同少数派孟什维克〔３８０〕合作，甚至想争取资产阶级能够赞成国家资本主义。但是，由于第一个社会主义国家的苏联当时正遭到十四个国家的武装干涉，同时又进行着国内战争，俄国资产阶级和其他党派都敌视苏维埃政权，只剩下一个俄国共产党继续把十月革命的胜利坚持下去，因此在苏联就没有完全实现列宁提出的跟各党派合作的设想。然而，在我国的具体历史条件下，列宁的设想实现了。这是因为我国革命的性质给了我们这个便利。我们的革命是反帝、反封建的资产阶级民主革命。民族资产阶级在帝国主义、封建主义和官僚资本主义的压迫下不能发展，他们想在反帝、反封建、反官僚资本主义的斗争中谋求自己的生存和发展。国民党实行一党专政，压迫民主党派，因此他们就要反对国民党的独裁。这种历史条件，使中国的民族资产阶级、各民主党派能够在民主革命时期逐步在国民党与共产党两个大党的对立斗争中选择了共产党。当然，单是有了历史发展的有利条件并不能解决问题，关键在于领导，在于党的政策。党领导得正确，才能使历史条件所提供的可能性变成现实。既然我们在民主革命时期和社会主义改造时期，都能和民族资产阶级、各民主党派共同合作，团结在一起，那么，怎么能够设想进入社会主义建设时期，就不能同民主党派、党外人士继续合作下去呢？这是说不出道理的。可是，共产党内总是有一部分人思想不那么通，好象讲到社会主义，就只应该有一个党才对。这是教条主义的态度。第二次世界大战以后，许多社会主义国家也并不都是一个党嘛！战后历史的发展已经不是象当年十月革命时的俄国那样了。

那么，民主党派究竟存在多长时间呢？能不能说共产党多活几年，其他党派少活几年？如果这样想，就是主观主义和宗派主义了。因为，这些民主党派还会有发展，还会有一部分人愿意参加，而这些党派的成员又很努力工作，大家团结在一起，只是思想上有些不同意见，那么，就没有理由说谁先结束，谁后结束。也有人会说，如果这些人都参加共产党，不是就变成一个党了吗？当然，这是可以设想的。但为什么一定要其他的民主党派都参加共产党呢？一些民主人士继续留在民主党派里面，和我们一道合作，有什么不好？

各民主党派联系群众的方面不同，可以听到一些不同意见，对中国革命和建设是有利的。比如民革〔２３６〕，它就是跟原国民党出身的、曾经当过政的一些人有联系，不管是上层的、中层的或下层的意见，它都可以听到，而这些正是共产党不大容易听到的。又如民盟〔２０８〕，它在知识分子圈里可以听到更多的意见。有一次我来杭州，回去时在飞机上看了费孝通〔３８１〕先生的一篇文章《知识分子的早春天气》，把知识分子心灵深处的一些想法都说出来了。共产党内也有不少能写文章的知识分子，但这样的文章我看是写不出来的，就是有这种想法也是不写的。再如九三学社〔２６６〕联系的科学家比较多；民建〔２３７〕主要是联系资产阶级工商业者；民进〔３０１〕联系中小学教员方面。它们都有各自不同的对象和特点。不仅在现在的社会主义建设时期，就是社会主义建成以后，由于成分来源的不同，人们的思想动态还会有不同的。工商业者在一起，总是可以把工商业者的心里话多说一些。小资产阶级出身的知识分子在一起，可以谈他们心灵深处的话。我也有一些党外朋友，而且过去很熟，我总希望通过他们知道一些不同意见。可是他们到了我面前，就是愿意说，也要保留几分。因为他们知道我是共产党的负责人，说话总不免要考虑考虑。甚至我的弟弟，他的心里话也不都跟我说。这是一种社会关系的反映。我们是从一个复杂的阶级社会来的。认为只要有一个共产党，问题就都可以解决了，这是一个简单化的想法。这样做必然会使我们的耳目闭塞起来。大家都是"王麻子"〔３８２〕，都是"张小泉"〔３８３〕，那就不行了。还是多几个牌号好一点。所以，从社会主义社会到共产主义社会，只要还有党派的时候，各民主党派同共产党长期共存，为一个共同的目标奋斗，求大同存小异，这并没有坏处。毛病虽然总会有一些，但这并不奇怪。就是共产党也不能保证不出问题，不但过去出了陈独秀〔１１８〕、张国焘〔５９〕、高岗〔３８４〕，就是将来也会出问题。因此，对民主党派来说，要不出一点毛病，那也不可能。所以，从种种方面看起来，我们这样的大国，多一点党派去联系各个方面的群众，对国家，对人民的事业，有好处。以共产党为核心，为领导，各党派团结合作，有什么不好？

中国共产党同民主党派长期共存、互相监督的方针，必须由共产党提出，而且必须要共产党真正做到。因为我们党不提，别的党派不好提；我们提了，大家就心安了。我们党的寿命有多长，民主党派的寿命就有多长，一直要共存到将来社会的发展不需要政党的时候为止。毛泽东同志在《论人民民主专政》一文中早就指出，从共产党成立的那天起，就准备将来的消亡。这是历史唯物主义和辩证唯物主义的真理。

互相监督，首先应该由共产党请人家监督。因为共产党是领导的党，它过去搞革命，为革命而奋斗，为人民立了功，人民拥护它，欢迎它。正是因为这样，也就带来了一个不利方面。毛泽东同志在我们党的七届二中全会上提出了这个问题。我们一旦取得了全国政权，就带来一个危险，就有一些人可能会被资产阶级的糖衣炮弹所腐蚀，被胜利冲昏头脑，滋长官僚主义，脱离群众，甚至会出现个人野心家，背叛群众。这方面的危险是随时存在的，每个共产党员都要警惕。这个问题怎么解决？最好的办法是有人监督。当然，共产党员首先要党的监督，可是整个党的工作，也还要其他党派来监督。同样，每个党员也要其他民主党派监督。因为，多一个监督，做起事来总要小心一点，谨慎一点。我们有一部分党员觉得天下是共产党打下来的。不错，共产党是有一份，但是，离开了人民，共产党有什么本事？天下是人民的天下嘛！你做得对，人民拥护，做得不对，人民就不拥护。民主党派参加了革命和建设，那么他就有一份功劳，他是人民的一分子，他就有权来说话。你要他监督，有什么不好？所以，不应该不服气。不服气就是骄傲，就是自满，这是危险的根源。应该服气，应该谦虚，应该愿意接受民主党派的监督。当然，反过来，民主党派也应该愿意接受共产党的监督，但这个问题并不怎么严重。重要的是共产党要承认长期共存、互相监督。我们只要是一个敢于面对现实的人，敢于揭露错误、批判错误、改正错误的人，那就不怕监督。越是监督我们，我们越是能进步。只有怕人家揭露错误，自己又没有勇气承认错误、改正错误的人，才怕人家监督。

长期共存、互相监督的方针，实际上是扩大民主。我们是六亿人口的国家。要把六亿人的生活搞好，建设社会主义，没有互相监督，不扩大民主，是不可能做得好的。因此，互相监督的面还要扩大，不能缩小。我们要加强各级人民代表大会及其常委会对政府工作的监督，并且使下级对上级也能够有监督的责任。这对我们的民主化有极大的好处。民主集中制是我们政治生活的基本原则。我们的民主是有领导的民主，这方面过去有足够的解释，现在要多强调民主的扩大。

＊　这是在中共浙江省委扩大会议上的讲话节录。

