# 关于香港问题

中文马克思主义文库 -> 周恩来
关于香港问题
（一九五七年四月二十八日）


　　我们不能把香港看成内地。对香港的政策同对内地是不一样的，如果照抄，结果一定搞不好。因为香港现在还在英国统治下，是纯粹的资本主义市场，不能社会主义化，也不应该社会主义化。香港要完全按资本主义制度办事，才能存在和发展，这对我们是有利的。香港的主权总有一天我们是要收回的，连英国也可能这样想。

　　香港是自由港，原料来得容易，联系的范围很广，购置设备可以分期付款，成本低，有市场，技术人才容易训练出来。所以，香港发展生产具备很多有利条件。我们在香港的企业，应该适应那里的环境，才能使香港为我所用。我们不是要动员一切可以动员的力量，化消极因素为积极因素吗？香港应该化为经济上对我们有用的港口。

　　现在国内的社会主义改造已经基本完成，私营企业已经全部公私合营，对其在香港的企业则不要去变动它。但过去已经公私合营的，如南洋烟厂，再转回私营也不必要。没有合营的不要合营，否则在原料、市场、销路上反而吃亏。保持和扩展香港这个阵地有好处。至于将来怎么办？我们不会来个七反八反的，不会象"三反"〔３３９〕、"五反"〔３３６〕那样的搞法。我们这样大的社会主义国家，经过几十年的工业化，经济力量会更加强大。所以在香港的人，一般不要回来，在那里发展这个阵地有好处。香港的企业家是我们的朋友，他们搞的是资本主义，不是帝国主义。过去我们同民族资产阶级合作过，将来同香港的企业家还是可以合作的。港澳的同胞不要担心前途。他们当中如果有些人主动坚决要求回来，可以同意。但不要动员他们回来，要让他们留在那里经营自己的企业。我们可以同他们内外合作，不使人家吃亏。至于有些人一时还不相信我们，对我们的政策有怀疑，可以让他们再看一看，看一二十年都可以。我们不要歧视他们，责怪他们。如果内地有一些人想出去，也是允许的。毛主席说，这一条我们过去就是不放心。现在应该是来去自由，不加歧视。香港的生活方式，当然是资本主义的生活方式，带有腐化性。有些朋友想要出去过一阵也可以，我们不要抓得那么紧，但也不是主动去号召。不要强留一些人在内地，有些人在外面过一阵还会回来的。凡有爱国心的人，我们就欢迎。对他们不要强劝回来，也不强留。

　　我们过去对有些事情处理方法上有些问题，但不能说大的方面做错了。有偏差可以纠正，如对外贸易，应该管制，但不能管得太严。现在我国社会主义革命已经基本上胜利了，要进行社会主义建设，香港可作为我们同国外进行经济联系的基地，可以通过它吸收外资，争取外汇。我们要打开局面，就得对香港的民族资产阶级讲清政策，使人家有利可图。过去我们搞得比较死，但总的说是对的，否则上不了轨道。现在既上了轨道，有些政策就要根据实际情况有所改变。



　　＊　这是在上海工商界人士座谈会上讲话的节录。



