# 不断加强人民民主统一战线是国家政治生活中的一个根本任务

中文马克思主义文库 -> 周恩来
不断加强人民民主统一战线是国家政治生活中的一个根本任务
（一九六二年三月二十八日）


　　不断地加强工人阶级领导的、以工农联盟为基础的人民民主统一战线，使全国各族人民紧紧地团结在一起，这是我们在国家政治生活中的一个根本任务。

　　在我们国家生活中起领导作用的中国共产党，一贯地执行同民主党派“长期共存、互相监督”的方针，一贯地坚持要团结一切可以团结的力量，为社会主义服务。近年来，各民主党派在为社会主义服务和进行自我教育、自我改造中，做出很大的成绩。

　　在中国共产党领导下，我国各民族的工人、农民、知识分子和其他劳动人民，各民主党派和民主人士，爱国的民族资产阶级分子，爱国侨胞，结成了广泛的人民民主统一战线。这个统一战线，在社会主义革命和社会主义建设中，已经发挥、并且将继续发挥它的重大作用。

　　这里要特别说一说团结知识分子的问题。

　　知识分子是社会主义建设事业取得胜利的不可缺少的重要力量。我国的知识分子，在社会主义建设的各个战线上，作出了宝贵的贡献，应当受到国家和人民的尊重。我国知识分子的状况，已经同解放初期有了很大的不同。新社会培养出来了大量年轻的知识分子，他们正在沿着“又红又专”的道路成长。从旧社会来的知识分子，经过十二年的锻炼，一般地说，已经起了根本的变化。知识分子中的绝大多数，都是积极地为社会主义服务，接受中国共产党的领导，并且愿意继续进行自我改造的。毫无疑问，他们是属于劳动人民的知识分子。我们应该信任他们，关心他们，使他们很好地为社会主义服务。如果还把他们看作是资产阶级知识分子，显然是不对的。也应该看到，知识分子中还有极少数的资产阶级知识分子，他们至今仍然保持着资产阶级的政治思想，怀疑或者不同意社会主义。但是，只要他们遵守国家的法令，从事正常的劳动，我们就应该团结他们，并且给他们以合适的工作，使他们对祖国有所贡献。

　　毛泽东主席说过：“为了建成社会主义，工人阶级必须有自己的技术干部的队伍，必须有自己的教授、教员、科学家、新闻记者、文学家、艺术家和马克思主义理论家的队伍。这是一个宏大的队伍，人少了是不成的。”我们现有的知识分子队伍，数量还小，水平还要提高，这是需要解决的一个大问题。

　　在我们社会主义的新社会中，知识分子应该加强团结，养成互相尊重、互相学习、互相帮助的新风气，特别是年轻的知识分子应该尊重年长的、有学识的知识分子，并且虚心地向他们学习。从政府方面来说，对于一切有专长的知识分子，应该让他们充分发挥所长，并且从各方面爱护他们。他们所掌握的科学知识，是我们国家的财富。应该保证他们有必要的工作条件和学习进修的条件，使他们享受适当的政治待遇，照顾他们的生活，并且帮助他们解决各种必须解决的问题，使他们在党的领导下，得以充分地发挥他们的才能。对于在他们职权范围内的事情，不要任意干涉，使他们勇于负责。毛泽东主席在一九五七年就指出：“我们有许多同志不善于团结知识分子，用生硬的态度对待他们，不尊重他们的劳动，在科学文化工作中不适当地干预那些不应当干预的事务。所有这些缺点必须加以克服。”

　　绝大多数的知识分子，包括许多在新社会中成长起来的知识分子，由于资产阶级的思想、作风和旧社会的习惯势力对他们还有程度不同的影响，所以他们必须密切同工农群众的联系，经常注意自我改造。为了帮助知识分子自我改造，应该创造条件，使他们能够心情舒畅地、自觉地、逐步地进行，而不应该采取任何简单粗暴的方式。应该看到，世界观的改造要有一个长期的过程。知识分子专家在世界观问题上的改造，除了学习马克思列宁主义和毛主席著作以外，往往要经过自己的科学的实践，经过带有一些自己的特点的道路。对知识分子的改造要求过高过急，是不适当的；把某些学术问题当做政治问题来处理，更是错误的。

　　百花齐放、百家争鸣的方针，是中国共产党在科学研究和文学艺术领域内的一个重要方针。事实证明，这个方针，是有利于科学和文教事业的繁荣发展的，是有利于团结广大知识分子的，也是有利于加强马克思列宁主义思想的领导地位的。有些单位、有些部门、有些地方，在工作中贯彻执行了这个方针，取得了很大的成绩。但是，也有一些单位和部门的负责干部，不懂得科学、文艺上的是非问题，只有通过科学界和文艺界的自由讨论，通过科学和文艺的实践，才能解决。他们违反百花齐放、百家争鸣的方针，在科学、文艺问题上不是鼓励自由探讨、自由辩论，而是加以限制，甚至进行粗暴的干涉，这种做法显然是错误的。

　　国家对知识分子的政策的出发点是，团结一切爱国的知识分子，逐步地建立起一支劳动人民的知识分子的宏大队伍。我们应该坚决地执行这个政策。

　　民族资产阶级分子的绝大多数是爱国的，在社会主义改造中已经取得新的进步。他们接受社会主义改造和为社会主义服务的积极性，有了进一步的提高；他们在改造成为社会主义劳动者的过程中是有成绩的，他们中间有一部分人已经成为自觉的社会主义的劳动者。我们应该继续加强同他们的团结和合作，并且很好地帮助他们进一步自我教育和自我改造。考虑到目前工商业者中，有一部分人对于取消定息还缺乏必要的准备，他们的生活也有必要加以照顾，政府已经决定，从一九六三年起，延长定息一个时期，暂定三年，到时再议。

　　这几年我们国家生活中一个重大事件，就是在西藏地区实现了民主改革。西藏人民已经从野蛮的农奴制度下解放出来，积极地参加祖国的建设。其他各少数民族地区的民主改革和社会主义改造，经济建设和文化建设，都有很大的成绩。但是，个别少数民族地区在民主改革和社会主义改造中，发生过违反党的民族政策和宗教政策忽视少数民族特点，损害少数民族平等权利和自治权利的偏向，使工作受到不应有的损失。这种错误，已经基本上得到纠正，还应该继续注意纠正。

　　在民族工作上，应该正确地贯彻执行党的民族政策，尊重少数民族的自治权利，尊重少数民族的风俗习惯和宗教信仰，注意培养少数民族干部。应该继续帮助少数民族进行社会建设和社会主义改造，大力发展农业、牧业生产。有关少数民族的重大问题，应该经过少数民族的人民和干部的充分讨论，按照他们的意愿作出决定。应该经常注意克服和防止干部中的大汉族主义的思想和地方民族主义的思想，不断地加强国内各民族的团结。

　　我们还应该做好侨务工作，进一步团结海外的一切爱国侨胞，妥善地照顾在国内的侨眷和安置归国的华侨。

　　应该做好宗教工作，正确地执行宗教信仰自由政策，进一步团结一切爱国的宗教徒。

　　在国家机关的工作人员中，有共产党员，有非共产党员，有民主党派的成员和无党派民主人士，他们都应该在自己的岗位上，充分地行使自己的职权，做好工作，并且很好地合作。毛泽东主席说过：共产党员只有对党外人士实行民主合作的义务，而无排斥别人、垄断一切的权利。他又说：在我们的各个国家机关和各项社会事业中，大量的工作要依靠党外的人员来作。如果我们不善于依靠人民群众，不善于同党外人员合作，那就无法把工作做好。



　　＊　这是在第二届全国人民代表大会第三次会议上所做的《政府工作报告》中“国内形势和我们的任务”部分的节录。



