# 春节祝词

中文马克思主义文库 -> 周恩来
春节祝词
（一九六三年一月二十八日）


　　今天在座的有科学家，有文艺界、新闻界、各党各派各方面的同志和朋友。借此机会，提出四句话来作为春节向大家的祝贺。这四句话是：

　　百家争鸣，薄古厚今；百花齐放，推陈出新；

　　各党各派，长期共存；同心同德，自力更生。

　　今年是第三个五年计划开始的第一年，我们要为实现我国的农业现代化、工业现代化、国防现代化和科学技术现代化的目标而奋斗。为达到这个目的，首先要贯彻百家争鸣的方针。百家争鸣要有个方向，这就是薄古厚今。我们对旧的文化遗产要批判继承，但只是批判继承还不够，现在世界上各方面的事业都在飞跃发展，我们要迎头赶上，就要着重研究现代的问题，就要厚今。二十世纪六十年代的今天，与十八世纪末叶、十九世纪的时代不同，世界的科学技术日新月异，第二次世界大战以后就比战前有了很大的发展。因此，我们要发展，就要努力实现四个现代化，要一代胜于一代，做出比前人更大的贡献。

　　第二句话是百花齐放，推陈出新。这是句老话，但有新的意义。全国解放十三年了，我们不能仅靠过去的遗产过日子。今天有许多新人新事、好人好事值得我们高兴和歌颂，也有一些坏的事情需要批评和纠正，同时还要学习和吸收国际上好的东西。历史上的好人好事可以激励我们，但这毕竟是过去的事，今天要靠我们自己创作出新的作品，歌颂好人好事来鼓舞人们。因此，不论文学、电影、音乐等各方面都要推陈出新，要把工作的重点放在这上面，不断扩大社会主义的思想阵地。

　　第三句话是各党各派，长期共存。这是毛主席提出来的。坚持这个原则，要靠大家共同努力。解放十几年了，我们和各民主党派已经结下了不解之缘。不仅在现阶段需要长期共存，而且一直要共存到共产主义。人类进步是无止境的，对人们的要求也在不断提高。因此，我们大家要互相帮助，互勉互励，很好地学习和改造。社会上有各种各样的人需要各党各派一起去做工作，大家共同为社会主义增一分光，添一分热。

　　第四句话是同心同德，自力更生。各党各派都做到同心同德，这不是一件容易的事情。要同心同德，就要共同过好五个关：思想关、政治关、生活关、亲属关、社会关。过思想关就是思想改造。共产党员也要改造，接受马列主义并不等于过了思想关。我也是中国共产党的负责人之一，但对马列主义的修养还不够，还要学习，还要改造。思想是行动的先导，但总是先有实践，后有认识。由于事物的发展是无止境的，所以思想认识和思想改造也是无止境的。其次是政治关。要按六条标准〔３９３〕去做，接受党的领导，跟共产党走，为社会主义服务。这些话说起来很容易，做起来就不那么简单。能不能站稳政治立场，需要长期的锻炼和考验。第三是生活关。要把个人生活放在第二位。国家要考虑到每个人的生活，但作为个人要把全部精力放到发展生产和攀登科学技术高峰上。只有生产发展了，生活才能得到改善。第四是亲属关。这个关最难过。我们知识分子多数是从旧社会过来的，千丝万缕的关系可多了。改造亲属要靠社会，个人力量是渺小的，人民的力量才是伟大的。这一关过不好，就会影响我们进步。有些亲属被镇压或管制，不要为他们难过。他们中的一些人能改造过来，我们表示欢迎。我们应当乐人民之乐，忧人民之忧。当然，对亲属也不是不管，他们经济上有困难帮助一些，也是人之常情，同时，也是为国家减轻一些负担。最后是社会关。旧中国是一个半殖民地、半封建的社会，各个社会阶层的情况很复杂，几千年的封建习惯一时还不容易改变。象上海这个过去被称为十里洋场的地方，随时都会受到各种腐朽思想的侵蚀。上海工人阶级是伟大的，是值得称颂的，但社会上的旧习惯对他们也会有影响。因此，克服旧习惯、旧势力的影响，改变整个社会风气，需要经过长期的斗争和努力。

　　要建设好我们的国家，主要靠自力更生。不要妄自菲薄，有些尖端技术我们已经找到了门路，可以依靠自己的力量，使科学技术赶上去，使工业、农业也赶上去。要增强信心，我们一定能够成功。尤其是上海，有上海党的领导，有广大的工人群众，有各方面的专家，一定可以搞上去。希望上海成为带动全国的先进城市。

　　当此春节，愿以这四句话来同大家共勉。



　　＊  这是在中共上海市委召开的各界民主人士春节座谈会上的讲话节录。



