# 接见首批特赦战犯溥仪等十一人时的谈话

中文马克思主义文库 -> 周恩来
接见首批特赦战犯溥仪等十一人时的谈话
（一九五九年十二月十四日）

你们出来几天了，有些问题先谈一谈好。

我们党和政府，是说话算话的，是有原则的。我们是根据民族利益、人民利益来释放你们的。现在和你们谈四个问题。

一、立场问题。

立场问题是个政治问题，就是人们在民族斗争和阶级斗争中站在哪一边的问题。你们在这个方面要经得起考验，要给人以好的印象。

首先，要站稳民族立场，热爱新中国。

从鸦片战争〔３８７〕到今天，经过将近一百二十年的斗争，中国人民翻了身，取得了伟大的胜利，这一事实连帝国主义也是承认的。溥仪〔４１０〕先生可以证明，现在我们的国家比你们过去搞得好吧。国民党统治二十多年也没有搞好。今天中国六亿五千万人民站起来了，生于斯，长于斯，这样的国家不爱还爱什么？以民族问题为例，过去是一个民族压迫另一些民族。溥仪先生，你在清末登基时才两三岁，那时你不能负责，但在伪满时代你要负责。宣统年间，我到过沈阳，那时满族人的气焰很高。后来清朝亡了，满族好象也亡了，许多满族人改名换姓，不敢说自己是满族人。而今天在共产党领导下，各民族平等了，他们也承认自己是满族了。今天的新中国，是各族人民的大家庭。

在今天，各民族都应该得到承认和尊重，各民族之间应该平等相处，互相帮助。特别是占全国人口百分之九十四的汉族，更有责任帮助少数民族，这样才能真正平等相处。

我们不仅主张国内各民族之间平等，而且主张国与国之间也应该平等。今天世界上有社会主义国家，有帝国主义国家，还有民族主义国家。对帝国主义的挑战，我们要反对。对民族主义国家，我们要争取。

民族立场很重要，我们对蒋介石还留有余地，就是因为他在民族问题上对美帝国主义还闹点别扭，他也反对托管〔４１１〕，反对搞两个中国。今天美帝国主义要把侵占台湾合法化，想把金门、马祖给我们，把台湾、澎湖留给自己，把蒋介石搞掉。我们认为台、澎留给蒋介石比留给美帝国主义好，将来这些地方总有一天会回到祖国怀抱。两害相权取其轻，我们不给美帝国主义以机会。在这里我们实际上支持了蒋介石。正如章行老〔２４８〕所说"现在真正支持蒋介石的是北京"。我们希望蒋介石、陈诚〔９０〕、蒋经国〔４１２〕团结起来反对美帝国主义。总之，要坚持民族立场。祖国的领土是完整的，不容许帝国主义分割，损害我们的一根毫毛也不行。

民族利益与劳动人民的利益是一致的。有了民族立场，还要进一步建立劳动人民的立场。

今天的人民包含工人阶级、农民阶级、小资产阶级和民族资产阶级。工人阶级是领导阶级，农民是集体农民，资产阶级和小资产阶级还有点尾巴。建立劳动人民立场，就是要去掉剥削阶级的立场，逐步站到劳动人民这一边来。这一点希望你们不断地加强思想改造，不断革命，过好社会主义关。

你们要读些书，读了书还要能够运用。要多读《毛泽东选集》，因为毛泽东思想是马列主义同中国革命实践相结合的产物，读起来容易理解。毛泽东思想对马列主义是有发展的。

一个人，一个社会，都要不断革命。我们的国家不仅要有经济建设，还要有政治建设和精神建设。我们的时代是向前发展的，你们也要不断进步。

二、观点问题。

你们有做新人的愿望，这很好。但还要继续树立和加强几个观点。

一是劳动观点。有机会劳动锻炼，对你们说来还有必要。现在你们的眷属能劳动是好事，要予以鼓励。

二是集体观点。你们出来以后，要把已有的集体主义观点巩固起来，不然个人主义思想就会抬头。你们个人主义的东西还不少，要常常过集体生活。所以现在把你们组织起来，与政协联系，经常进行学习。我们都是过集体生活的。家庭也可以说是一个集体。你们的子女可能会同你们争论并批评你们，你们要有思想准备。十年所得，不要抛于一旦。要认罪服罪，重新做人。

三是群众观点。这是中国革命最重要的问题。共产党人并没有三头六臂，就是因为坚定地依靠群众，才把蒋介石的反动统治推翻了。把群众发动起来，力量是无敌的。依靠群众，依靠六亿五千万人民，帝国主义和一切反动派都不足怕。我们搞经济建设，搞科学文化建设也要依靠六亿五千万人民。人民的力量是不可战胜的。

三、工作和生活问题。

工作、生活、劳动、学习、参观，要好好安排一下。参观学习的目的，是为了帮助你们进一步了解国内情况。要回家的、接眷属的都可以。这两个月里，可以参观，听报告，看看书报。两个月后再考虑安排工作。这些问题由统战部和政协负责。

与台湾有联系的，可以做点工作。但写信也不要太急，不要挖苦，要以民族利益为重。工作要从长计议。

四、前途问题。

走社会主义共产主义道路，做新人，有奔头。你们做得好，狱中人会感到更有希望。你们是头一批释放的，彼此要互相勉励，允许你们互相来往。既要勉励自己，也要勉励狱中的人。在狱中的人个别至死不悟的也会有，但大多数经过改造会有进步，会分批得到特赦，也是有前途的。这次出来三十三人，将来出来的会更多，都不要落伍。

你们也不要把现在的一切都看得那么好。北京的巷子里还有很多矮小房屋。全中国实现现代化，还需要几十年。精神面貌，也不一致，有的人进步比较慢。我希望你们：第一，要相信党和国家。党和国家对你们是信任的，你们要用自己的力量，为国家为民族多做贡献。第二，倘有不如意的事，可以写信，可以与中央统战部联系，有话就要说，不要积少成多，结成疙瘩。

你们是从旧社会来的，旧的社会联系多，可以用自己的亲身感受帮助改造社会上的死角。溥仪先生可以起到我们起不到的作用。你们到社会上，到你们的亲友中，有两个可能：一个是你们影响他们，一个是他们影响你们。好的影响要接受，坏的影响要挡回去。人的乐趣就在这里。宜生〔２５０〕参加水利工作，大家为了制定一个好的方案，争论不休，这是高尚的政治生活。

你们出来了，新的环境对你们是进一步的考验。你们要努力改造，努力工作，不断进步。

