# 同溥仪及其家属的谈话

中文马克思主义文库 -> 周恩来
同溥仪及其家属的谈话
（一九六○年一月二十六日）


　　周：你们的家族很大，今天请了你的几个妹妹来，没有请你的妹夫们，因为时间来不及了。春节后我要出去，今天和你谈谈对你的工作安排问题。你想搞什么工作？

　　溥：搞轻工业或在公社中工作都可以。

　　周：你自己想想到哪里工作合适。我看，到哪个部的研究所，一边学习，一边工作，这样对你的身体比较好。可以让研究人员教你。他们都很年轻，多数不知道历史，你们可以互相帮助。研究所有政治生活，你可以参加学习。你愿不愿这样做？

　　溥：可以。

　　周：你读了不少医书，但是你不要给人家治病，治坏了就会有闲言闲语，这样不好。

　　溥：我看的医书也不多，主要是因为自己身体不好才看的。按照过去宫廷生活那样下去，我的生命也保不住了。

　　周：你先检查身体。然后订个三年计划，学一点自然科学，学一点本事。毛选你看过吗？

　　溥：没有整本看过，只是挑着看了一些。

　　周：马列主义的书看过哪些？

　　溥：看过政治经济学和社会发展史。毛选现在因为买的人多，不容易买到。

　　周：我可能有两部，送给你一部。你写的那部《我的前半生》有二十万字，因为总有事，我还没看完。你的书基本上是要同旧社会宣战，这是不容易的事，末代皇帝肯这样暴露旧社会不容易。俄国沙皇和德国皇帝威廉写的书都是吹自己。你创造了历史上的一个新例子。但基础还不巩固，进行改造才十年，加上在苏联那段时间也不过十四五年，而且在抚顺战犯管理所的头几年你还不安心。这也很自然，是不奇怪的，怎么会一下子就相信人民政府？如你七叔现在是人民代表，（向载涛〔４１４〕）原来安排你做政协委员时，你就那么相信我们？（又向溥）你写那本书用了多少时间？

　　溥：一年多。

　　周：这证明你后几年进步了，但不能说已经巩固。改造思想，第一要有客观环境，第二要靠主观努力。过去你在那个环境中不那样做不可能。现在环境变了，但也不一定每个人都能把你当成平民看待，可能有的人还会向你下跪打恭。

　　溥：这次回来后，还有两个老头拿着写有清朝官衔的名片来见我。当时我说要出门，没见。我想没法说服他们。

　　周：一定要认识这环境，战胜这环境。

　　溥：自己的立场坚定就可以帮助落后，自己如不坚定就会受影响。

　　周：做到坚定不容易。共产党员革命了几十年，有的还犯错误。

　　（饭后继续谈。）

　　周：现在民族平等了，各民族共同发展。满汉要团结得更好。你要努力学习，搞出点成绩来，这对你个人有好处，对人民有贡献，对满族也有好处。你学得还不够，要努力学习。清朝的八旗制度〔４１５〕后来腐败了，实际上是削弱了自己。清朝被打倒了，满族倒复兴了。你们家属要帮助他。一个家庭也有左、中、右。要争取前进，帮助落后。家里的人到一起最容易谈老事，其实现在比那时好多了。比如画画现在名人也可以合作，只有新社会才能这样，过去哪里成！你改他一笔都不行。旧社会把人变成鬼，新社会把鬼变成人。

　　你写的东西有价值，作为未定稿，用四号字印出来后你再改，改得比较完善一些。这是旧社会的一面镜子。旧社会结束了，你也转变成了新人。这本书改好了，就站得住了。后代的人也会说，最后一代皇帝给共产党改造好了。

　　溥：我一定不辜负毛主席和总理的期望。 



