# 《周恩来统一战线文选》注释

中文马克思主义文库 -> 周恩来
注释
　　１　这里是指由穆斯塔法·基马尔领导的土耳其民族解放运动。第一次世界大战中，土耳 其政府追随德奥帝国主义集团，使土耳其经济遭到严重破坏，社会矛盾加剧。战败后，英、法、意等帝国主义国家瓜分土耳其，更激化了民族矛盾。一九一九年，以穆斯塔法·基马尔为代表的土耳其民族商业资产阶级，领导人民进行反帝民族解放斗争并取得胜利，于一九二三年成立了土耳其共和国。土耳其人民在这一斗争中，得到列宁和苏俄政府的同情和支持。一九二○年苏俄政府承认基马尔建立的安纳托利亚民族政权，次年三月又签定了苏俄土耳其友好条约。--第２页。

　　２　庚子之变即八国联军攻陷北京的事变。一九○○年（庚子年），英、美、法、德、俄、日、意、奥八个帝国主义国家，为了镇压义和团的反帝爱国运动，瓜分中国，借口清政府"排外"，组成侵华联军，于八月十四日攻陷北京，大肆烧杀抢掠，践踏中国主权。腐败无能的清政府，于同年十二月全盘接受各帝国主义国家提出的《议和大纲》，并于次年九月，签订了丧权辱国的《辛丑条约》。--第３页。

　　３　袁世凯（一八五九--一九一六），河南项城人。北洋军阀首领。清末曾任山东巡抚、直隶总督兼北洋大臣等职。一九一一年辛亥革命时，出任清政府内阁总理大臣。一九一二年在英、美、日等帝国主义支持下，窃取中华民国临时大总统职务，组织了代表大地主大买办阶级的第一个北洋军阀政府，对内专制独裁，对外投降卖国。一九一五年五月接受日本企图灭亡中国的"二十一条"。同年十二月称帝。一九一六年三月在全国人民的反对下被迫取消帝制。--第３、１４１、２１２、３９４页。

　　４　"二十一条"是日本帝国主义利用第一次世界大战的时机在一九一五年一月十八日向袁世凯政府提出的旨在独占中国的秘密条款。这些条款共有五号，分为二十一条。主要内容是：一、由日本接管德国在山东所掠夺的权利，并加以扩大；二、承认日本在南满洲和内蒙古东部享有各种特权；三、将汉冶萍公司改为中日合办；四、中国治海港湾岛屿概不让予或租予第三国；五、聘用日本人为顾问以控制中国的政治、财政、警察、军事，允许日本在湖北、江西、浙江、广东各省之间修筑重要铁路，并承认日本在福建享有投资修筑铁路、开采矿山、整顿海口等优先权。五月七日，日本提出最后通牒。五月九日，袁世凯政府对日本的这些要求，除声明第五号要求的一部分"容日后协商"外，一概加以承认。后来，因为全国人民的一致反对，以及各帝国主义国家在华利益上存在矛盾，日本的这些要求没有全部实现。--第３、２１２页。

　　５　段祺瑞（一八六五--一九三六），安徽合肥人。北洋军阀皖系首领。自一九一六年袁世凯死后到一九二六年期间，曾任国务总理、中华民国临时执政等职，几度把持北京政府的实权。他对内镇压人民，推行武力统一政策，对外出卖主权，投靠日本帝国主义。第一次世界大战期间，以参加欧战为名，向日本大量借款，仅西原龟三经办的借款，金额就达一亿四千五百万日元。--第３、１４１页。

　　６　曾锟（一八六二--一九三八），天津人。北洋军阀直系首领之一。一九一二年袁世凯窃取政权后，历任北洋军第三师师长、直隶督军、直鲁豫巡阅使等职。一九二二年第一次直奉战争后，他在英美帝国主义支持下，控制了北京政府。次年十月，他以五千元一票的价格收买国会议员，被选为"总统"。--第３、１４１页。

　　７　吴佩孚（一八七四--一九三九），山东蓬莱人。北洋军阀直系首领之一。一九二二年，依靠英美帝国主义支持，在第一次直奉战争中把张作霖赶出关外，与曹锟一起控制北京政府，先后任两湖巡阅使、直鲁豫巡阅使等职，操纵政局，提出武力统一中国的主张。一九二三年残酷镇压京汉铁路工人运动，一九二六年所部在湖北被国民革命军打败。--第３页。

　　８　华盛顿会议也称太平洋会议，一九二一年十一月十二日至一九二二年二月六日在美国首都华盛顿举行。参加者有美、英、法、意、日、葡、比、荷、中九国。这是第一次世界大战后，帝国主义国家重新划分远东及太平洋势力范围的会议。会议根据美国提出的所谓"各国在华机会均等"和"中国门户开放"的主张，缔结了帝国主义共同控制和掠夺中国的《九国公约》以及共同镇压远东人民，首先是镇压中国人民的美、英、法、日《四国公约》等。--第３页。

　　９　陈炯明（一八七八--一九三三），广东海丰人。早年加入同盟会。辛亥革命后，曾任广东都督、广东省长兼粤军总司令等职。一九二一年，暗中勾结英帝国主义和吴佩孚、赵恒惕等南北军阀，反对孙中山北伐主张。一九二二年六月公开叛变，炮轰总统府，谋害孙中山。次年一月孙中山领导的讨逆军攻克广州，陈率部退到东江后，继续勾结英帝国主义和南北军阀，多次进犯广州。--第３、４８、３９５页。

　　１０　辛亥革命　是以孙中山为首的资产阶级革命政党同盟会所领导的推翻清朝专制王朝的革命。一九一一年（辛亥年）十月十日，革命党人发动新军在湖北武昌举行起义。接着，各省热烈响应，外国帝国主义所支持的清朝反动统治迅速瓦解。一九一二年一月在南京成立了中华民国临时政府，孙中山就任临时大总统。二千多年的中国封建帝制从此结束，民主共和国的观念从此深入人心。但是资产阶级革命派力量很弱，并具有妥协性，没有能力发动广大人民的力量比较彻底地进行反帝反封建的革命。辛亥革命的成果迅即被北洋军阀袁世凯篡夺，中国仍然没有摆脱半殖民地、半封建的状态。--第３、５６、１３８、２２３、４０４页。

　　１１　保皇党　指清末资产阶级改良派在海外的政治团体保救大清皇帝会，简称"保皇会"。一八九八年戊戌变法失败后，康有为、梁启超等逃亡海外，次年七月在加拿大创立"保皇会"，并在南洋、美洲、日本等地建立组织，以保救光绪，反对慈禧和抵制革命为宗旨进行活动，拉拢华侨入会。一九○七年，为了迎合清政府预备立宪，保皇会改名国民宪政会，不久又改称帝国宪政会，成为推行君主立宪的政治团体。--第４页。

　　１２　同盟会　是中国资产阶级革命政党中国同盟会的简称。一九○五年八月，兴中会与华兴会等革命团体的成员在日本东京联合组成同盟会，采用了孙中山提出的"驱除鞑虏，恢复中华，创立民国，平均地权"的资产阶级革命政纲。孙中山被推选为总理。同盟会除了在国内各地建立支部和分会外，还分别在南洋、欧洲和檀香山等地建立支部和分会，积极联络华侨。在孙中山的领导下，同盟会积极进行革命宣传，并联合会党、新军发动多次武装起义。一九一一年（辛亥年）十月武昌起义爆发，很快形成推翻清王朝的辛亥革命运动。一九一二年八月，同盟会改组为国民党。--第４、２４２页。

　　１３　五四运动指一九一九年五月四日发生的反帝反封建的爱国运动。当时，第一次世界大战刚刚结束，英、美、法、日、意等战胜国在巴黎召开对德和会，决定由日本继承德国在中国山东的特权。中国是参加对德宣战的战胜国之一，但北洋军阀政府却准备接受这个决定。五月四日，北京学生举行游行示威，反对帝国主义的这一无理决定和北洋军阀政府的妥协。这次运动迅速地获得了全国人民的响应，到六月三日以后，发展成为有工人阶级、城市小资产阶级和民族资产阶级参加的广大群众性的反帝反封建的爱国运动。五四运动也是反对封建文化的新文化运动。以一九一五年《青年杂志》（后改名《新青年》）创刊为起点的新文化运动，竖起"民主"和"科学"的旗帜，反对旧道德，提倡新道德，反对旧文学，提倡新文学。五四运动中的先进分子接受了马克思主义，使新文化运动发展成为马克思主义思想运动。他们致力于马克思主义同中国工人运动相结合，在思想上和干部上为中国共产党的成立做了准备。--第４、１３５、２０８、３５８页。

　　１４　中国国民党是孙中山创立的政党。前身为同盟会。一九一二年同盟会联合几个小党派改组为国民党，和北洋军阀袁世凯实行妥协，基本上成了官僚政客集团。一九一四年，为了反对袁世凯的统治，孙中山领导一部分国民党员组织中华革命党，一九一九年十月，又改为中国国民党（简称国民党）。一九二四年一月在中国共产党的帮助下，孙中山改组了中国国民党。改组后的中国国民党接受中国共产党提出的反帝反封建的政治主张，重新解释三民主义，确定联俄、联共、扶助农工三大政策，从而实现了第一次国共合作，并依靠这一合作进行了北伐战争。这个时期的国民党，具有工人、农民、小资产阶级、民族资产阶级的民主革命联盟的性质。一九二七年四月蒋介石发动反革命政变后，国民党基本上变成代表大地主、大资产阶级的反动集团。--第５、６、２２、４６、５３、６７、７３、７７、１１１、１１８、１２５，１３０、１７１、２２０、２６１页。

　　１５　指由北洋封建军阀集团在袁世凯死后分裂成的直、皖、奉三派旧军阀，和南方的背叛孙中山投靠帝国主义成为新军阀的陈炯明。这四派新旧军阀势力，得到帝国主义的金钱和武器的支持，扩充实力，互相勾结又互相争夺，妄图以武力消灭南方各省的革命力量。--第５页。

　　１６　当时党中央的一些文件，把军阀、官僚、洋行买办、地主土豪等统称为半封建势力。这里沿用了这一提法。--第６页。

　　１７　五卅运动指一九二五年上海五卅惨案激起的全国人民的反帝爱国运动。一九二五年五月三十日，上海群众近万人到"公共租界"进行反对帝国主义的游行示威，遭到英帝国主义的血腥屠杀。这次惨案激起了全国人民的公愤，广大的工人、学生、商人和农民在各地举行游行示威和罢工、罢市、罢课，形成了全国规模的反帝爱国运动。--第７、２１、５９页。

　　１８　指一九二五年八月二十日，国民党右派在帝国主义指使下，在广州暗杀了坚持国共合作的国民党左派领袖廖仲恺。为了调查这一重大暗杀事件的真象，由有关方面人士组成了"廖案检查委员会"。周恩来是这一委员会的委员。--第７、５８、７４页。

　　１９　见《共产党宣言》（《马克思恩格斯选集》第１卷第２８５页）。新的译文是："共产党人不屑于隐瞒自己的观点和意图。"--第９页。

　　２０　见《国民周刊》第３期（一九二六年十月二十三日出版）所载范谔写的《从海康案说到农运问题》一文。这篇文章揭露和谴责了广东海康县军政当局勾结地方土豪劣绅枪杀农民运动工作人员程庚的罪行。--第１０页。

　　２１　福建人民革命政府是国民党内反对蒋介石的李济深、陈铭枢、蒋光鼐、蔡廷锴等人于一九三三年十一月在福州成立的中华共和国人民革命政府。这年十月，蒋光鼐、蔡廷锴领导的十九路军同红军签订了抗日反蒋协定。福建人民革命政府成立后又同中华苏维埃共和国临时中央政府和工农红军签订了停战协定。在蒋介石的军事压力下，福建人民革命政府在一九三四年一月间失败。--第１２、７８页。

　　２２　苏维埃中央政府，全称中华苏维埃共和国临时中央政府，也称中央工农民主政府，一九三一年十一月在江西瑞金成立。它是第二次国内革命战争时期，中国共产党在中央革命根据地建立的中央政权机关。--第１２页。

　　２３　张伯苓（一八七六--一九五一），天津人。教育家。北洋水师学堂毕业，一九○四年在天津创办敬业中学堂，三年后改称南开学校。一九一九年至一九三七年任南开大学校长。一九三八年初任西南联大校务委员会常委，同年出任国民参政会副议长。一九四八年任国民党政府考试院院长。中华人民共和国成立后，他从重庆致电周恩来总理，表示祝贺。--第１４、２１９页。

　　２４　阎氏　指阎锡山（一八八三--一九六○），山西五台人。早年参加同盟会，辛亥革命后曾任山西省都督、督军、省长、督办等职，是长期统治山西的军阀。一九三六年五月时任国民党政府军事委员会副委员长、太原绥靖公署主任。抗日战争时期任国民党军第二战区司令长官。解放战争中，追随蒋介石打内战，一九四九年三月逃离太原。--第１４、１５１页。

　　２５　蒋　指蒋介石。--第１４页。

　　２６　一九三五年五月，日本帝国主义进一步派兵侵犯我国华北，国民党政府继续推行其"攘外必先安内"的不抵抗政策，同日本进行谈判，谋求妥协。同年十月，日本外相广田弘毅提出了所谓"对华三原则"，后称"广田三原则"，其内容是：中国取缔一切排日运动；建立中、日、"满"经济合作；中日共同防共。--第１４页。

　　２７　谌小岑，一八九七年生，湖南安化人。五四运动时期曾参加周恩来等领导的觉悟社。一九二○年八月谌去武汉，同年十一月，周赴法国，直到写此信时，二人已分别将近十六年。一九三六年五月谌任国民党政府铁道部劳工科长。--第１６页。

　　２８　黄君　指张子华，原名王绪祥（一九一四--一九四二），宁夏中宁人。一九三○年参加中国共产党，一九三五年任中共上海临时中央局组织部秘书和豫、鄂、陕边区特派员。当时作为中共联络员为商谈国共合作，多次往返于陕北、南京之间。--第１６、１７页。

　　２９　养甫　即曾养甫（一八九八--一九六九），广东平远人。曾任国民党中央执行委员、铁道部政务次长，当时任国民党广东省政府委员兼广州特别市市长。一九三五年底至一九三六年，曾作为国民党方面的代表与中共代表谈判。--第１６、１７页。

　　３０　陈果夫（一八九二--一九五一），浙江吴兴人。一九二六年任国民党中央监察委员、组织部代部长。一九三六年时任国民党中央执行委员会常务委员、江苏省政府主席。--第１７、６５页。

　　３１　陈立夫，一九○○年生，浙江吴兴人。当时任国民党第五届中央执行委员、中央党部组织部主任。--第１７页。

　　３２　指一九三六年八月日本帝国主义指使伪蒙军进犯绥远东北地区。当地驻军傅作义等部，在全国人民抗日救亡运动的推动下奋起抵抗，击溃了敌人的进攻。--第１７、１９页。

　　３３　定远营也称定远城，俗称王爷府。位于贺兰山西麓，当时属宁夏省管辖。解放后改名为巴彦浩特（蒙语为富饶的城市），划归内蒙古自治区。--第１７、１９页。

　　３４　胡宗南（一八九六--一九六二），浙江孝丰（今属安吉县）人。一九三六年九月任国民党军第一军军长。--第１９页。

　　３５　黄埔指黄埔军官学校，是一九二四年孙中山在中国共产党和苏联的帮助下，在广州黄埔创办的军官学校。中国共产党先后派周恩来、恽代英、肖楚女、聂荣臻等在该校担任过各种职务，学员中也有很多共产党员和共青团员。一九二七年蒋介石背叛革命以前，这是一所国共合作的学校。--第１９、５５、７５、３９５页。

　　３６　西南事变即两广事变。一九三六年六月，广东军阀陈济棠和广西军阀李宗仁、白崇禧以抗日为名发出通电，组织西南联军，并出兵企图争夺南京国民党政权。七月陈济棠因部下为蒋介石收买而被迫下台，九月李宗仁、白崇禧与蒋妥协。--第２１页。

　　３７　指一九二四年一月在中国共产党的帮助下，孙中山改组中国国民党。改组后的中国国民党，接受了中国共产党提出的反帝反封建的政治主张，重新解释三民主义，确立了联俄、联共、扶助农工三大政策，从而实现了第一次国共合作，并成功地进行了北伐战争。--第２１页。

　　３８　一九三一年九月十八日，日本驻在中国东北境内的关东军进攻沈阳。这次事件被称为九一八事变。随后，日军向辽宁、吉林、黑龙江三省全面进犯。驻守沈阳和东北其他地方的中国军队，执行蒋介石的不抵抗的命令，使日军得以迅速占领了这三个省。--第２２、７５、７８、３５９页。

　　３９　哥老会　是旧中国民间的一种秘密结社。它的一般成员多系手工业者、农民、士兵和游民等，上层人物不少是豪绅地主、军人官吏；它的条规和组织形式带着浓厚的封建的迷信的和保守的反动的色彩。辛亥革命时期，有些会众接受革命党人的领导，多次参加武装起义。抗日战争时期，陕甘地区哥老会多数会众在中国共产党的团结争取下，参加了抗日活动。--第２４页。

　　４０　指一九三六年十月在陕西省志丹县境内的马头山召开的全国哥老代表会议，它不同于一般哥老会内部集会议事的开山堂。为了推动和吸引哥老会会员参加抗日救国的统一战线，中国共产党在一九三六年广泛开展了对哥老会的团结、争取工作。这年七月中华苏维埃中央政府向全国哥老会发出宣言，提出"在共同抗日的要求下联合起来"；八月中华苏维埃中央政府西北办事处设立哥老会招待处，成立中华江湖抗日救国委员会筹备处，八月十九日该筹备处向全国哥老会发出召开代表会议的通函，同年十月十五日全国哥老代表会议在马头山召开。会议订立了抗日救国十大条规，其主要内容有：打倒日本帝国主义，援助红军抗日等。--第２４页。

　　４１　高桂滋（一八九一--一九五九），字培五，陕西定边人。当时任国民党军第八十四师师长。--第２６页。

　　４２　高双成（一八八二--一九四五），陕西渭南人。当时任国民党军第八十六师师长。--第２６页。

　　４３　指一九三六年八月中华苏维埃中央政府西北办事处为了接待各地哥老会代表和被国民党政府迫害的哥老会会员而设立的哥老会招待处。--第２７页。

　　４４　张云衢（一九○六--一九八二），陕西蒲城人。当时任国民党军第八十六师第五一一团团长。--第２９页。

　　４５　宋子文（一八九四--一九七一），广东文昌人。当时任国民党中央执行委员、国民党政府经济委员会主席。

　　宋美龄，一九○一年生，蒋介石的妻子。

　　蒋鼎文（一八九五--一九七四），浙江诸暨人。当时任国民党政府福建绥靖公署主任。西安事变前蒋介石准备调他任西北"剿总"前敌总司令。--第３１、８０页。

　　４６　张　即张学良，一九○一年生，辽宁海城人。东北军爱国将领。当时任国民党西北"剿总"副司令。一九三六年十二月和杨虎城一起发动西安事变，要求蒋介石停止内战，一致抗日。后被蒋介石长期扣押。--第３１、８０页。

　　４７　杨　即杨虎城（一八九三--一九四九），陕西蒲城人。西北军爱国将领。当时任国民党军第十七路军总指挥、西安绥靖公署主任等职。一九三六年十二月和张学良一起发动西安事变，要求蒋介石停止内战，一致抗日。一九三七年四月，被蒋介石迫令去职出国。同年十一月回国参加抗日工作，随即被蒋介石长期囚禁。一九四九年九月在重庆国民党集中营惨遭杀害。--第３１、８０页。

　　４８　何应钦，一八八九年生，贵州兴义人。当时任国民党政府军政部长、军事委员会总参谋长。

　　张群，一八八九年生，四川华阳人。当任国民党政府外交部长。

　　张嘉璈（一八八八--一九七九），江苏宝山（今属上海）人。当时任国民党政府铁道部长。

　　吴鼎昌（一八八四--一九五○），原籍浙江吴兴，生于四川华阳。当时任国民党政府实业部长。

　　陈绍宽（一八八八--一九六九），福建闽侯人。当时任国民党政府海军部长。--第３２页。

　　４９　孔祥熙（一八八○--一九六七），山西太谷人。当时任国民党政府行政院代院长兼财政部长。

　　徐新六（一八九○--一九三八），浙江杭州人。当时任浙江兴业银行总经理、复旦大学校长。

　　颜惠庆（一八七七--一九五○），上海人。曾任北洋政府的外交总长和中国出席国联第十六届大会的首席代表。

　　赵戴文（一八六七--一九四三），山西五台人。当时任国民党山西省政府主席。

　　邵力子（一八八一--一九六七），浙江绍兴人。当时任国民党陕西省政府主席。

　　严重（一八九二--一九四四），湖北麻城人。曾任黄埔军校教官、总教官，北伐战争时任国民革命军第二十一师师长。"四一二"反革命政变后，拒绝蒋介石任命的职务。抗日战争期间被国民党反动派谋害。

　　胡宗南（一八九六--一九六二），浙江孝丰（今属安吉县）人。当时任国民党军第一军军长。

　　陈季良（一八八三--一九四四），福建福州人。当时任国民党政府海军部政务次长。

　　沈鸿烈（一八八二--一九六九），湖北天门人。当时任国民党政府青岛市长。

　　孙科（一八九一--一九七三），广东香山（今中山）人。当时任国民党政府立法院长。

　　曾养甫（一八九八--一九六九），广东平远人。当时任国民党政府广州市长。

　　朱家骅（一八九三--一九六三），浙江吴兴人。当时任国民党浙江省政府主席兼民政厅长。

　　俞飞鹏（一八八四--一九六六），浙江奉化人。当时任国民党政府交通部代理部长。

　　卢作孚（一八九四--一九五二），四川合川人。当时任民生实业公司总经理。

　　张伯苓（一八七六--一九五一），天津人。当时任南开大学校长。

　　王世杰（一八九二--一九八一），湖北崇阳人。当时任国民党政府教育部长。

　　宋庆龄，当时任国民党中央执行委员、全国各界救国联合会执行委员。

　　杜重远（一八九七--一九四三），吉林怀德人。当时任上海进步刊物《新生周刊》主编，一九三五年五月，曾因刊登爱国文章，被国民党政府判刑。西安事变前曾帮助张学良接受我党提出的抗日民族统一战线政策。抗日战争时期在新疆被军阀盛世才秘密杀害。

　　沈钧儒（一八七五--一九六三），当时是上海文化界救国会和全国各界救国联合会主要领导人之一。

　　章乃器（一八九七--一九七七），当时是全国各界救国联合会主要领导人之一。--第３２页。

　　５０　七领袖　指当时在上海领导各界抗日救亡运动被国民党反动派逮捕的沈钧儒、章乃器、邹韬奋、李公朴、沙千里、史良、王造时等七人，也称"七君子"。--第３２、７９页。

　　５１　西安事变和平解决以后，由于张学良送蒋介石回南京被蒋扣留，东北军内部在如何营救张的问题上发生分歧。部分少壮派军官主张用武力解决，六十七军军长王以哲等主张和平解决。在反动势力的挑动下，少壮派军官于一九三七年二月二日晨刺杀了王以哲。因为事变 发生在二月二日，故称"双二"杀王事变。--第３８、８０页。

　　５２　宋　即宋黎，一九一一年生，吉林梨树人。当时任东北军中地下党组织的东北军工作委员会委员、宣传部长、代理书记。袁指袁晓轩。信中拟定"宋、袁"到北方局参加东北军工作，后来又改为宋黎和刘澜波，袁并没有去。--第４０页。

　　５３　东委　即东北军工作委员会。一九三六年初，为在东北军中广泛开展抗日民族统一战线工作，争取东北军广大官兵团结一致、共同抗日，中共中央设立了东北军工作委员会。在东北军内部也设有党的组织东北军工作委员会，简称"东工委"。此处"东委"是指东北军内部的"东工委"。--第４０页。

　　５４　汪逆汉奸　指汪精卫（一八八三--一九四四），原籍浙江山阴（今绍兴），生于广东番禺（今属广州市）。一九二五年任广州国民政府主席。一九二七年在武汉发动七一五反革命政变。一九三一年九一八事变后主张与日本帝国主义妥协。抗日战争爆发后任国民党副总裁。一九三八年底公开投降日本。一九四○年在南京成立傀儡政权。--第４３、４６、５６、７２、８７页。

　　５５　戴季陶（一八九一--一九四九），原籍浙江吴兴，生于四川广汉。早年参加中国同盟会，一九二四年任国民党中央执行委员。一九二五年孙中山逝世后，积极参加西山会议派的反革命活动，并发表《国民革命与中国国民党》、《孙文主义的哲学基础》等文章，歪曲孙中山的三民主义，反对孙中山联俄、联共、扶助农工的三大政策；散布反对共产党、反对工农运动的谬论，为蒋介石发动反革命政变制造舆论。一九二七年南京国民党政府成立后，历任国民政府委员、考试院院长等职，长期充当蒋介石的谋士。--第４６、５５、７４页。

　　５６　淮南　即张冲（一九○四--一九四一），浙江温州人。曾任国民党中央执行委员、中央组织部代理副部长等职，当时作为国民党代表参加国共谈判。--第４８、１１１页。

　　５７　参政会　即国民参政会，是抗日战争时期国民党政府被迫成立的最高谘询机关。参政员由国民党政府"聘请"，形式上包容各抗日党派的代表，但实际上国民党党员占绝大多数。该会对国民党政府的政策、措施没有任何约束力。为了促进团结抗日，中国共产党也派代表参加了参政会。第一届第一次国民参政会于一九三八年七月在武汉召开，以后随着国民党日趋反动，参政会越来越成为国民党政府的御用工具。一九四一年皖南事变以后，中共参政员董必武等为抗议国民党的反动政策曾进行了坚决斗争，并多次拒绝出席参政会。抗日战争胜利后，国民党政府召开"国民大会"，国民参政会便于一九四七年五月第四届第三次大会后撤销。--第４８、５１、７８页。

　　５８　叶青　即任卓宣，一八九五年生，四川南充人。曾参加中国共产党，一九二八年被捕后叛变，从事反共宣传活动。曾任国民党中央宣传部副部长等职。--第４８页。

　　５９　张国焘（一八九七--一九七九），江西萍乡人。一九二一年参加中国共产党第一次全国代表大会。后曾任中共中央委员、政治局委员、政治局常委。一九三一年任中共鄂豫皖中央分局书记、中华苏维埃共和国临时中央政府副主席等职。一九三五年六月红军第一、第四方面军在四川懋功地区会师后任红军总政治委员。他反对中央关于红军北上的决定，进行分裂党和红军的活动，另立中央。一九三六年六月被迫取消第二中央，随后与红军第二、第四方面军一起北上，十二月到达陕北。一九三七年九月起，任陕甘宁边区政府副主席、代主席。一九三八年四月，他乘祭黄帝陵之机，逃出陕甘宁边区，经西安到武汉，投入国民党特务集团，成为中国革命的叛徒，随即被开除出党。一九七九年死于加拿大。--第４８、６１、１０２、２０２、３５０页。

　　６０　《新年日报》是中国共产党在国民党统治区公开出版的报纸。一九三八年一月十一日在汉口创刊，同年十月二十五日迁到重庆继续出版。一九四七年二月二十八日被国民党反动派强迫停刊。--第４９、８８页。

　　６１　抢米案　指"成都抢米事件"。在一九三九年底到一九四○年春第一次反共高潮中，国民党顽固派为了扑灭成都地区的抗日救亡烈火，打击我党和一切进步势力并破坏四川地方实力派与我党结成的统战关系，派特务头子康泽到成都策划了"抢米事件"。一九四○年三月，康泽指使二三百人化装成贫民闯进有地方实力派潘文华大量资本的重庆银行，抢劫了一个米仓库，砸毁了银行，并诬陷共产党策划饥民抢米、妄图暴动，从而胁迫地方军阀实行白色恐怖政策，逮捕了中共川康特委书记、八路军驻成都代表罗世文同志等共产党员和进步人士。--第４９页。

　　６２　车耀先（一八九四--一九四六），四川大邑人。一九二九年加入中国共产党，曾任中共川西特委军委委员。抗日战争爆发后，在成都领导抗日救亡运动。一九三八年发起成立中苏文化协会成都分会。一九四○年三月"抢米事件"发生后被国民党反动派逮捕，在狱中坚贞不屈、坚持斗争。一九四六年十月在重庆中美合作所被国民党特务杀害。--第４９页。

　　６３　李鹤龄　即李品仙，一八九二年生，广西苍梧人。当时任国民党二十一集团军总司令兼安徽省主席等职。--第５０页。

　　６４　指当时受聘担任国民参政会参政员的中国职业教育社、中国人民救国会、中国乡村建设学会、中国青年党、中国国家社会党的领导人及无党派人士：黄炎培、沈钧儒、李璜、冷遹、梁漱溟、张君劢、张澜、褚辅成、周士观、章伯钧、邹韬奋、左舜生、罗隆基、江问渔、杨赓陶、张申府。--第５１页。

　　６５　一九四一年皖南事变后，中共方面向国民党方面提出《解决时局善后办法十二条》作为出席参政会的条件；为了顾全大局，于三月二日又提出《临时解决办法十二条》。即：一、立即停止全国向我军事进攻；二、立即停止全国的政治压迫，承认中共及各党派之合法地位，释放西安、重庆、贵阳各地之被捕人员，启封各地被封书店，解除扣寄各地抗战书报之禁令；三、立即停止对《新华日报》之一切压迫；四、承认陕甘宁边区之合法地位；五、承认敌后之抗日民主政权；六、华北、华中及西北防地，均维持现状；七、于十八集团军外，再成立一个集团军，共应辖有六个军；八、释放叶挺，回任军职；九、释放所有皖南被捕干部，拨款抚恤死难家属；十、退还皖南所有被获人枪；十一、成立各党派联合委员会，每党派出一人，国民党代表为主席，中共代表副之；十二、中共代表加入参政会主席团。--第５１页。

　　６６　董必武（一八八六--一九七五），湖北黄安（今红安）人。清末曾考中秀才。一九一一年加入同盟会，参加了辛亥革命和反对北洋军阀的斗争。在俄国十月革命和中国五四运动的影响下，一九二○年在武汉组织共产主义小组，是中国共产党创始人之一。一九二四年任中共武汉地委书记、湖北省委委员，领导筹建了中国国民党湖北省党部，任常务委员。抗日战争时期，是中共参加国民参政会的参政员之一。一九六二年时任中华人民共和国副主席。--第５１、５３、９１、４１２页。

　　６７　邓颖超，一九○四年生，河南光山人。一九一九年五四运动时，在天津和周恩来等一起组织觉悟社。抗日战争时期是中国共产党参加国 民参政会的参政员之一。书中第４１１页的一段话是一九四九年她回答《中国青年》杂志记者提问时说的。参见一九四九年五月《中国青年》第七期上的邓颖超《五四运动的回忆》一文。--第５１、９１、１１６、４１１页。

　　６８　陈潭秋（一八九六--一九四三），湖北黄冈人。中国共产党创始人之一。一九二四年后历任中共武汉地委书记、湖北区委委员兼组织部长，曾参加中国国民党湖北省党部的筹建工作。一九三九年任中国共产党驻新疆代表和八路军新疆办事处主任。一九四二年被军阀盛世才逮捕，一九四二年九月被秘密杀害。由于情况隔绝，在一九四五年党的第七次全国代表大会上被选为中央委员。--第５３页。

　　６９　何叔衡（一八七六--一九三五），湖南宁乡人。中国共产党创始人之一。当时是中共湘区委员会负责人之一，湘江中学校长，曾参加改组中国国民党湖南省党部的工作。一九三一年任中华苏维埃共和国临时中央政府工农监察委员、最高法院院长等职。一九三四年红军长征后留根据地坚持斗争。一九三五年二月在福建长汀突围战斗中牺牲。--第５３页。

　　７０　夏曦（一九○一--一九三六），湖南益阳桃江镇（今属桃江县）人。一九二一年参加中国共产党。北伐战争时任中共湘区委员会委员，在国民党第二次全国代表大会上当选为候补中央执行委员。参加中国国民党湖南省党部的筹建工作，任常务委员。--第５３页。

　　７１　宣中华（一八九八--一九二七），浙江诸暨人。一九二四年参加中国共产党，是中共杭州地委负责人之一，同年参加筹建中国国民党浙江省党部，当选为执行委员和常务委员。一九二七年四月在上海被蒋介石反动派杀害。--第５３页。

　　７２　侯绍裘（一八九六--一九二七），江苏松江（今属上海市）人。一九二三年参加中国共产党。一九二六年任中国国民党江苏省党部常务委员。一九二七年四月十日在南京被捕就义。--第５３页。

　　７３　李大钊（一八八九--一九二七），河北乐亭人。一九一六年起投身新文化运动，曾任《新青年》杂志编辑，并与陈独秀创办《每周评论》，是最早在我国传播马克思主义的先进分子之一。一九一八年参加筹组少年中国学会。一九二○年在北京组织共产主义小组，是中国共产党的主要创始人之一。党成立后，曾任中共北方区执行委员会负责人，一九二四年在中国国民党第一次全国代表大会上当选为国民党中央执行委员，领导筹建国民党北京市、天津市、直隶省党部，主持国民党在北方的最高领导机关--国民党中央政治委员会的工作。一九二七年四月六日在北京被军阀张作霖逮捕，二十八日就义。--第５３、２１２页。

　　７４　于树德（一八九四--一九八二），河北静海人。一九二二年曾参加中国共产党。当时是北京大学教授。中华人民共和国成立后，曾任中国人民政治协商会议全国委员会常务委员等职。--第５３页。

　　７５　李永声（一八七二--一九五二），又名李锡九，河北安平人。一九二二年参加中国共产党。一九二四年出席中国国民党第一次全国代表大会。会后参加筹建和领导国民党直隶省党部。中华人民共和国成立后，曾任中央人民政府委员等职。--第５４页。

　　７６　于方舟（一九○○--一九二八），河北宁河（今属天津市）人。一九二二年参加中国共产党。一九二四年出席中国国民党第一次全国代表大会，被选为候补中央执行委员。会后参加筹建和领导中国国民党直隶省党部。一九二七年秋领导河北玉田农民暴动时被俘，一九二八年春就义。--第５４页。

　　７７　一九二四年十一月，孙中山从广州经上海到北京，准备同当时战胜了直系军阀、控制了北京政府的段祺瑞、张作霖等谈判。他在北上宣言中主张对内"推倒军阀"，对外"推倒帝国主义，废除不平等条约"，并主张召集国民会议来解决这些问题。他在到达天津时已病重，一九二五年三月十二日在北京逝世。--第５４页。

　　７８　一九二三年八月和一九二四年十一月，中国共产党先后两次发表宣言，提出召开国民会议，以代替北洋军阀的反动统治。这一号召得到全国人民的响应，孙中山对此采取积极支持态度。在全国范围内很快形成了一个以"召集国民会议"、"废除不平等条约"为内容的人民运动。各地先后成立了国民会议促成会。一九二五年三月间，国民会议促成会代表大会在北京召开。--第５４页。

　　７９　冯自由（一八八二--一九五八），广东南海人。当时是国民党临时中央候补执行委员。

　　谢持（一八七六--一九三九），四川富顺人。当时是国民党党务部长。一九二四年六月与张继等联名发出"弹劾共产党书"。一九二五年与邹鲁等发起西山会议。--第５４页。

　　８０　一九二五年十一月，国民党右派邹鲁、谢持、居正、张继、林森等十余人，在北京西山碧云寺召开所谓国民党一届四中全会，通过反苏、反共、反对国共合作等反动议案，随后在上海成立国民党"中央党部"，在北京成立"地方党部"。这批人被称为西山会议派。--第５４页。

　　８１　廖仲恺（一八七七--一九二五），广东惠阳人。国民党左派。出身于美国华侨家庭，一八九三年回国。一九○五年参加同盟会，为最早的会员之一。辛亥革命后，任广东都督府总参议。一九二二年后，积极协助孙中山确定联俄、联共、扶助农工的三大政策。一九二四年国民党改组后，被选为中央执行委员会常务委员，并先后担任工人部部长、农民部部长、黄埔军官学校党代表、广东省省长、财政部长、军需总监等职。孙中山逝世后，他坚决执行革命的三大政策。--第５４、７５页。

　　８２　孙文主义学会　是国民党内的一批右派分子为对抗黄埔军校革命军人团体--青年军人联合会而建立的反动组织。主要头目有戴季陶、王柏龄、陈诚、贺衷寒、缪斌等。--第５５、７５页。

　　８３　孙科（一八九一--一九七三），广东香山（今中山）人。一九二二年任广州市市长。一九二四年国民党第一次全国代表大会后，曾提出弹劾共产党。抗日战争时期，任国民党政府立法院长。--第５５、７３、８１页。

　　８４　"五五宪草"是一九三六年五月五日国民党政府颁布的《宪法草案》的简称。这个"宪草"的主旨是维护国民党一党专政。--第５５页。

　　８５　李济深（一八八五--一九五九），字任潮，广西苍梧人。早年曾任粤军第一师参谋长、师长。北伐战争时任国民革命军总司令部参谋长、第四军军长，留守广州，一九二七年参加国民党反动派反共反人民的活动。一九三三年联合十九路军在福建组织反蒋抗日的中华共和国人民革命政府。抗日战争爆发后，支持中国共产党一致抗日的主张，联络国民党内的爱国民主力量，反对蒋介石的独裁政策。一九四八年组织中国国民党革命委员会，任主席。中华人民共和国成立后，任中央人民政府副主席等职。--第５６、２４１、３４０页。

　　８６　邓铿（一八八六--一九二二），广东惠阳人。早年参加同盟会。一九一七年起任粤军参谋长、第一师师长等职。--第５６页。

　　８７　张发奎（一八九六--一九八○），广东始兴人。曾任粤军第一师团长，一九二五年任国民革命军第四军第十二师师长。--第５６页。

　　８８　叶挺（一八九六--一九四六），广东惠阳人。中国人民解放军创始人之一。一九二五年参加中国共产党。同年冬任国民革命军第四军参谋处长和独立团团长。北伐战争中率部在湖北汀泗桥和贺胜桥两次战斗中获胜，为第四军赢得了"铁军"的称号。一九二六年十月任第十一军二十四师师长兼武昌卫戍司令。一九二七年参加领导八一南昌起义，任前敌总指挥兼第十一军军长。同年十二月又参加领导广州起义，任起义军总司令。广州起义失败后出国。抗日战争爆发后回国。一九三七年底到延安，后任新四军军长。一九四一年一月在皖南事变中被扣。一九四六年三月四日出狱，七日由中共中央批准重新入党。--第５６、９０、１０２页。

　　８９　邓演达（一八九五--一九三一），字择生，广东惠阳人。国民党左派领袖之一。一九二○年参加孙中山组织的粤军，历任营长、团长。一九二六年任黄埔军校教育长。北伐战争期间任国民革命军总政治部主任、湖北省政府主席等职。一九二七年三月与宋庆龄、何香凝、吴玉章等在武汉召开国民党二届三中全会，这次会议通过了限制蒋介石权力的决定。四一二反革命政变后，被蒋介石下令通缉。汪精卫和蒋介石合流后，邓流亡苏、德等国。一九三○年回国。一九三一年十一月，被蒋介石秘密杀害于南京。--第５６、７５、１５１页。

　　９０　陈诚（一八九八--一九六五），浙江青田人。一九二三年在粤军任连长。西安事变时任国民党政府军政部常务次长。一九四八年去台湾，后曾任国民党政府行政院长、副总统等职。--第５６、８０、３９７页。

　　９１　新军　指清朝末年编练的新式陆军。辛亥革命前夕，由于革命党人的积极活动，各省新军中的下级军官和士兵倾向革命的人日益增多，新军成为武昌和各地起义的重要力量。--第５６页。

　　９２　会党　指哥老会等旧中国的民间秘密团体。孙中山领导的同盟会曾利用会党举行武装起义。--第５６页。

　　９３　陈其美（一八七八--一九一六），浙江吴兴人。早年参加同盟会，曾在江浙一带策动反清革命运动，同时在上海加入青帮为大头目。--第５６页。

　　９４　中华革命党，参见本书注〔１４〕。--第５６页。

　　９５　胡汉民（一八七九--一九三六），广东番禺（今属广州市）人。第一次国内革命战争时期曾任代理广州大元帅府大元帅兼广东省省长等职，右派首领，是一九二七年蒋介石发动四一二反革命政变的同盟者。后来同蒋介石集团争权夺利，长期对立。--第５６、７２页。

　　９６　黄克强　即黄兴（一八七四--一九一六），湖南善化（今长沙）人。一九○四年组织反清革命团体华兴会，任会长。一九○五年华兴会与兴中会、光复会联合组成中国同盟会，黄是同盟会中仅次于孙中山的重要领袖。一九○七年起，多次参与或领导反清的武装起义。武昌起义后任革命军总司令。一九一二年任南京临时政府陆军总长，一九一三年任江苏讨袁军总司令。--第５６页。

　　９７　永丰舰是广州革命政府的最大军舰。一九二二年陈炯明叛乱时，孙中山曾在此舰避难。孙中山逝世后改名"中山舰"。--第５６页。

　　９８　一九二二年六月十六日，陈炯明勾结英帝国主义和直系军阀，背叛孙中山，炮击设在广州的总统府。--第５６页。

　　９９　王柏龄（一八八九--一九四二），江苏江都人。当时任黄埔军校教授部主任，积极反对孙中山的三大政策，是孙文主义学会的发起人之一。一九二五年代理黄埔军校教育长。--第５７页。

　　１００　王懋功（一八九一--一九六一），江苏铜山人。一九二五年任国民革命军第一军第二师师长，不久兼任广州卫戍总司令，一九二六年二月被蒋介石免职。后投靠蒋介石，任国民党中央委员、江苏省政府主席、第十战区副司令长官等职。--第５７、８９页。

　　１０１　鲁易（一九○○--一九三二），湖南常德人。一九二一年参加少年共产党，一九二二年转入中国共产党。第一次国内革命战争期间历任黄埔军校政治部副主任、国民革命军第一军第三师党代表。一九三二年八月在洪湖战斗中被俘就义。--第５７页。

　　１０２　青年军人联合会是周恩来在黄埔军校领导组织的革命军人团体。成立于一九二五年二月一日。以黄埔军校的共产党员和共青团员为骨干，联合粤军讲武学校、滇军干部学校、桂军军官学校等校的青年军人组成，主要成员有蒋先云、周逸群等。联合会积极宣传革命理论和共产党的统一战线政策，团结革命力量，打击国民党右派势力，同反动的孙文主义学会进行了针锋相对的斗争。一九二六年三月二十日中山舰事件后被蒋介石解散。--第５７、７５页。

　　１０３　一九二四年，英帝国主义用大量金钱、军火支持广州大买办陈廉伯所控制的反革命武装组织商团，企图颠覆广东革命政府。八月，广东革命政府扣留了陈廉伯为组织武装叛乱而偷运的军火。陈指使商团向孙中山请愿，并在全省各地煽动罢市。十月十日，广州群众为庆祝辛亥革命举行游行，遭到商团的射击，参加游行的十六个团体成立了工农兵学革命大同盟，发表宣言，坚决要求解散商团，严惩凶手。在中国共产党、广大工农群众和国民党左派的影响和支持下，孙中山采取断然措施，调集工农武装、黄埔学生及其他军队，在十五日消灭了这一反革命武装。--第５８页。

　　１０４　为了声援五卅运动，香港工人在一九二五年六月十九日开始举行总罢工，参加人数达二十五万；六月二十一日，广州沙面租界的中国工人也开始举行罢工。这两处反英的罢工合称为省（指省城广州）港罢工。六月二十三日，两处罢工工人合组省港罢工委员会，并成立纠察队，封锁香港和沙面租界，使英帝国主义在政治上和经济上受到严重打击。这次罢工坚持了一年零四个月。一九二六年十月北伐军占领武汉后胜利结束。--第５８页。

　　１０５　谭延闿（一八八○--一九三○），湖南茶陵人。一九二四年任国民党中央执行委员、中央政治委员会主席。一九二五年任国民政府常务委员兼军事委员会委员、国民革命军第二军军长。一九二七年任国民党中央常务委员、中央政治委员会主席团成员、武汉国民政府常务委员等职。--第５８、７３页。

　　１０６　朱培德（一八八九--一九三七），云南盐兴（今禄丰县）人。当时任国民党中央执行委员、中央政治委员会委员、国民革命军第三军军长等职。--第５８页。

　　１０７　程潜（一八八二--一九六八），湖南醴陵人。北伐时任国民革命军第六军军长。抗日战争和解放战争时期曾任国民党第一战区司令长官、湖南省政府主席等职。一九四九年八月在湖南宣布起义。中华人民共和国成立后，任全国人民代表大会常务委员会副委员长、湖南省省长、中国国民党革命委员会中央副主席。--第５８、１３２页。

　　１０８　这里指一九二四年创办于广州的农民运动讲习所。第一期至第五期分别由彭湃、阮啸仙、罗绮园、谭植棠等任主任。一九二六年五月的第六期由毛泽东任所长，这一期学员来自全国二十个省区，共三百多人，同年九月结业。一九二七年三月，毛泽东又在武昌举办了一期农民运动讲习所。--第５９页。

　　１０９　为了巩固广东革命根据地，准备北伐，一九二五年二月至三月，中国共产党和国民党合作组织的以黄埔军校学生为骨干的革命军从广州出发东征，打败了盘踞在东江的军阀陈炯明的主力。六月回师广州，平息了盘踞广州的滇、桂军阀杨希闵、刘震寰的叛乱。十月至十一月举行第二次东征，最后消灭了陈炯明的军队。--第５９页。

　　１１０　刘震寰，当时任驻粤桂军总司令兼广西省长、广州革命政府委员。杨希闵，当时任驻粤滇军总司令兼第一军军长、广州革命政府委员。一九二五年六月，刘、杨勾结在一起，发动叛乱，企图颠覆广州革命政府。国民革命军从东江回师广州，迅速平定了这一叛乱。--第５９页。

　　１１１　一九二五年六月二十三日，广州各界人民和黄埔学生军约十万人为抗议帝国主义在上海制造五卅惨案，举行声势浩大的游行示威。游行队伍行经沙基时，遭到沙面租界内英法军队机枪扫射，当场被打死五十二人，重伤一百七十多人。这次事件被称为沙基惨案。--第５９页。

　　１１２　许崇智（一八八七--一九六五），广东番禺（今属广州市）人。当时任粤军总司令。--第５９页。

　　１１３　参见本书注〔１０９〕。--第５９页。

　　１１４　彭湃（一八九六--一九二九），广东海丰人。我党最早的农民运动领袖。一九二二年七月在海丰县赤山创建了全国第一个农会。一九二三年一月当选为海丰总农会会长。一九二四年参加中国共产党。同年创办广州农民运动讲习所，并任中共广东区委委员。一九二五年五月当选为广东省农民协会副委员长。一九二七年参加南昌起义，任中共前敌委员会委员。南昌起义失败后，领导了海陆丰第三次武装起义，创立了海陆丰苏维埃，任委员长和中共东江特委书记。一九二八年任中共中央农委书记兼江苏省委军委书记。在党的第五次、第六次全国代表大会上当选为中央委员，在八七会议上被选为政治局委员，在党的第六次全国代表大会上当选为政治局候补委员。--第５９页。

　　１１５　彭湃同志的哥哥彭汉垣，受彭湃的影响投身革命，一九二五年第一次东征后任海丰县县长。一九二八年三月被捕，后在广州就义。--第５９页。

　　１１６　陈延年（一八九八--一九二七），安徽怀宁人。一九二二年参加中国共产党。一九二五年任中共广东区委书记。一九二七年四月在党的第五次全国代表大会上当选为中央委员、中央政治局候补委员。五大后，任中共江苏省委书记。一九二七年六月被捕，七月在上海龙华就义。--第６０页。

　　１１７　鲍罗廷（一八八四--一九五一），第一次国共合作时苏联政府派到广州革命政府的代表和国民党的政治顾问。一九二三年十月来华，一九二七年七一五政变后回国。--第６０、７４页。

　　１１８　陈独秀（一八七九--一九四二），安徽怀宁人。一九一五年九月起主编《青年杂志》（后改名《新青年》），一九一八年和李大钊创办《每周评论》，提倡新文化，是五四新文化运动的主要领导人之一。五四运动后，接受和宣传马克思主义，是中国共产党的主要创始人之一。在党成立以后的最初六年中是党的主要领导人。在第一次国内革命战争后期，犯了严重的右倾机会主义错误。其后，对于革命前途悲观失望，否认无产阶级应继续完成中国民主革命的任务，在党内成立小组织，进行反党活动，一九二九年十一月被开除出党。后和托派组织相结合，一九三一年五月曾被自称为"中国共产党左派反对派"的托派组织推为总书记。一九三二年被国民党逮捕，一九三七年八月出狱。--第６１、９８、２１１、３５０页。

　　１１９　加伦　即布留赫尔（一八八九--一九三八），当时是苏联政府派到广州革命政府的军事总顾问。一九二四年来华，一九二七年七一五政变后回国。--第６１页。

　　１２０　冯玉祥（一八八二--一九四八），安徽巢县人。北洋军阀时期曾任旅长、师长、督军、督办等职。一九二四年十月发动北京政变，并将部队改组为国民军。十一月五日取消清废帝溥仪的皇帝称号，将溥仪逐出皇宫。一九二六年九月宣布脱离北洋军阀参加国民革命。一九二七年四一二政变后曾参加蒋介石、汪精卫反对共产党的活动。一九三一年九一八事变后赞成抗日。一九三三年五月同共产党合作，在察哈尔省（现在分属山西、河北和内蒙）组织民众抗日同盟军，抵抗日本帝国主义的侵略。以后，继续采取和共产党合作的立场。一九四八年初参加中国国民党革命委员会，任中央政治委员会主席。同年九月一日在由美国回国参加新政协途中遭遇火灾逝世。--第６１、８１、１００页。

　　１２１　张静江（一八七七--一九五○），浙江吴兴人。当时任国民党中央监察委员。一九二七年帮助蒋介石筹划了四一二反革命政变，并促成了蒋、汪（精卫）间的反革命联合。--第６１页。

　　１２２　中山舰事变也称三二○事变，是第一次国内革命战争时期蒋介石为排挤共产党人而制造的反共阴谋事件。一九二六年三月十八日，蒋介石指使其亲信以黄埔军校驻省办事处的名义，向海军局代理局长李之龙（当时是共产党员）传达命令，要他调中山舰到黄埔待命。当中山舰抵达黄埔后，他们又造谣说中山舰要炮轰黄埔军校、共产党要赶走蒋介石。三月二十日，蒋介石借口共产党阴谋暴动，逮捕了李之龙，扣留了中山舰，并派兵包围省港罢工委员会。随后又强迫共产党员从国民革命军第一军以及黄埔军校中撤出。由于当时中共中央的主要领导人陈独秀、张国焘等人主张妥协退让，不敢反击蒋介石，遂使他的阴谋得逞。--第６１、７４、９７、３９５页。

　　１２３　张太雷（一八九八--一九二七），江苏武进（今常州市）人。一九二○年参加共产主义小组。一九二五年在党的第四次全国代表大会上当选为候补中央委员，同年在共青团第三次全国代表大会上当选为书记，并任中共广东区委常委、宣传部部长、苏联顾问鲍罗廷的翻译。一九二七年四月在党的第五次全国代表大会上当选为中央委员，八月出席八七会议当选为中共临时中央政治局候补委员，十月主持中共中央南方局工作兼任广东省委书记，十二月领导广州起义时牺牲。--第６２页。

　　１２４　李福林（一八七四--一九五三），广东番禺（今属广州市）人。当时任国民革命军第五军军长。--第６２页。

　　１２５　欧阳格，当时任国民革命军海军总指挥、舰队司令。--第６３页。

　　＃Ｂ４７４＃１２６　古应芬（一八七三--一九三一），生于广东番禺（今属广州市）。一九二五年起任国民党广东省政府民政厅厅长、国民党中央监察委员会委员等职。一九二七年参与镇压广州起义。--第６３、７４页。

　　１２７　蒋先云（一九○二--一九二七），湖南新田人。一九二一年参加中国共产党。一九二二年领导湖南水口山铅锌矿罢工。一九二四年入黄埔军官学校，毕业后留校任秘书，是青年军人联合会主要负责人之一。一九二六年任国民革命军总部秘书、补充第五团团长、湖北省总工会工人纠察队总队长。一九二七年任第十一军二十六师七十七团团长兼党代表，五月二十八日在河南临颍战役中牺牲。--第６３页。

　　１２８　李默庵，一九○四年生，湖南长沙人。当时任国民革命军第一军第一师第三团党代表办公室少校干事。--第６３页。

　　１２９　彭述之（一八九五--一九八三），湖南邵阳人。一九二一年参加中国共产党。一九二四年在上海大学任教并任《新青年》、《向导》编辑。第一次国内革命战争后期，执行陈独秀的右倾机会主义路线。革命失败后，成为取消主义分子，采取了托洛茨基的反动立场，在党内成立小组织，进行反党活动。一九二九年十一月被开除出党，后成为托洛茨基分子。--第６４、１０５页。

　　１３０　丁惟汾、王法勤当时均为国民党中央执行委员、北京执行部秘书处常务委员。大同盟是丁惟汾在五四运动以后组织的。一九二四年国民党改组后，大同盟一度成为国民党北京执行部领导的组织。孙中山逝世后，大同盟逐步走上拥蒋反共的道路。--第６５页。

　　１３１　李富春（一九○○--一九七五），湖南长沙人。一九二二年参加中国共产党。北伐战争期间，任国民革命军第二军党代表兼政治部主任。一九五六年任国务院副总理兼国家计划委员会主任。--第６５、１７０、３３２页。

　　１３２　朱克靖（一八九五--一九四七），湖南醴陵人。一九二二年参加中国共产党。北伐战争期间任国民革命军第三军党代表。抗日战争期间任新四军政治部顾问、苏浙行署主任等职。抗日战争胜利后任新四军联络部部长。一九四六年在我党争取郝鹏举部起义后任该部政治委员。一九四七年郝叛变时被扣，同年秋被国民党反动派在南京秘密杀害。--第６５页。

　　１３３　罗汉，湖南浏阳人。曾参加中国共产党，一九二七年在莫斯科学习时参加托派组织。--第６５页。

　　１３４　林伯渠（一八八六--一九六○），湖南临澧人。一九二一年参加中国共产党。北伐战争期间任国民革命军第六军党代表。从一九三七年到一九四八年任陕甘宁边区政府主席。抗日战争期间曾作为中国共产党代表与国民党进行谈判。--第６５、８２页。

　　１３５　一九二六年七月，为了推翻北洋军阀的统治，国民革命军从广州出师北伐。由于有中国共产党的政治领导和广大工农群众的积极支持，国民革命军迅速地占领了长江中下游广大地区，严重地打击了帝国主义和封建势力。一九二七年四月十二日，以蒋介石为代表的国民党右派发动反革命政变，第一次国内革命战争遭到失败。--第６５、１００、１３５、１４４页。

　　１３６　一九一一年（辛亥）十月十日，武昌起义取得胜利。一九一二年中华民国参议院议定将这一天作为国庆节，通称双十节。--第６６页。

　　１３７　缪斌，当时任国民革命军第一军党代表。--第６６页。

　　１３８　一九三七年五月二日至十四日在延安举行中国共产党苏区代表大会，毛泽东在会上做了题为《中国共产党在抗日时期的任务》的报告。报告中指出："一九二四年至一九二七年的经验，表明了当资产阶级追随着无产阶级的政治领导的时候，革命是如何地前进了；及至无产阶级（由共产党负责）在政治上变成了资产阶级的尾巴的时候，革命又是如何地遭到了失败。这种历史不应当重复了。"（《毛泽东选集》第１卷第２４１页）--第６８页。

　　１３９　季米特洛夫（一八八二--一九四九），保加利亚人。国际共产主义运动著名活动家。一九二一年任工会国际中央理事会理事，一九三五年至一九四三年任共产国际执行委员会总书记。一九四五年十一月回国后，任保加利亚共产党总书记和部长会议主席。--第６８、１７３页。

　　１４０　法西斯主义的四种特征，见《在共产国际第七次代表大会上》，原文是："法西斯是资本家对劳动人民大众的最猖狂的进攻；法西斯是肆无忌惮的沙文主义和侵略战争（旧的译文是："法西斯主义--就是横行无忌的民族侵略主义和强盗的战争"。本文引用的是旧译文。--编者注）；法西斯是疯狂的反动和反革命；法西斯主义是工人阶级和全体劳动人民的最恶毒的敌人！"（《季米特洛夫选集》，人民出版社一九五三年版第４５-４６页）--第６８页。

　　１４１　我国边疆的少数民族在历史上往往被称为"藩部"，历代都有职官专管或兼管民族事务，例如清代专设了理藩院，掌管蒙古、西藏、新疆等地的少数民族事务。历代封建统治阶级主要是用镇压和笼络的两手政策对待边疆各少数民族。蒋介石在民族问题上继承了这种政策，甚至否定少数民族的存在，把各少数民族称之为汉族的大小宗支。--第６９页。

　　１４２　见斯大林《在第十七次党代表大会上关于联共（布）中央工作的总结报告》（《列宁主义问题》，人民出版社一九五三年版第５６６页）。--第６９页。

　　１４３　六大指一九二八年六月十八日至七月十一日在苏联的莫斯科召开的中国共产党第六次全国代表大会。会上，瞿秋白做了《中国革命与共产党》的报告，周恩来做了组织问题和军事问题的报告，刘伯承做了军事问题的补充报告。会议通过了政治、军事、组织等问题的决议案。这次大会肯定了中国社会是半殖民地半封建社会，中国当时的革命依然是资产阶级民主革命，指出了当时的政治形势是在两个革命高潮之间和革命发展的不平衡，党在当时的总任务不是进攻，不是组织起义，而是争取群众。会议在批判右倾机会主义的同时，特别指出了当时党内最主要的危险倾向是脱离群众的盲动主义、军事冒险主义和命令主义。这次大会的主要方面是正确的，但也有缺点和错误。它对于中间阶级的两面性和反动势力内部的矛盾缺乏正确的估计和适当的政策；对于大革命失败后党所需要的策略上的有秩序的退却，对于农村根据地的重要性和民主革命的长期性，也缺乏必要的认识。--第７１页。

　　１４４　北洋军阀是清末袁世凯在北方几省首先建立起来的封建军阀集团。一八九五年清政府命袁世凯在天津小站编练"新建陆军"，归北洋大臣节制。一九○一年袁世凯任直隶总督兼北洋大臣以后，培植党羽，自成派系。辛亥革命后，袁世凯窃取中华民国临时大总统职务，组织了代表大地主大买办阶级的第一个北洋军阀政府。一九一六年袁死后，这个集团在英、日等帝国主义国家支持下分化为直、皖、奉三系，为争权夺利彼此间进行过多次混战。一九二六年皖系军阀段祺瑞下台，一九二七年直系军阀被国民革命军消灭，一九二八年奉系军阀政府垮台。至此，北洋军阀反动统治时期结束。--第７１、２１２、２２４、３３６、３７４、３９３、４１０页。

　　１４５　南四行　指当时的中国银行（总经理张嘉璈）、上海商业储蓄银行（总经理陈光甫）、浙江兴业银行（总经理徐寄庼）、浙江实业银行（总经理李铭）。--第７１页。

　　１４６　这里指一九二七年四月十二日，蒋介石反动派在上海血腥屠杀共产党人和革命群众，公开背叛了革命。一九二七年四月十五日，国民党反动派在广州发动反革命政变，逮捕、屠杀共产党员和工人积极分子。--第７１页。

　　１４７　共产国际即第三国际，成立于一九一九年三月，是各国共产党的联合组织。一九二二年中国共产党参加共产国际成为它的一个支部。一九四三年五月，共产国际执委会主席团提议解散共产国际，经各国共产党一致同意，在六月正式宣布解散。--第７１、１７３页。

　　１４８　改组派是二十年代末期到三十年代初期的国民党派系之一。一九二七年七一五反革命政变后，武汉汪精卫的国民党和南京蒋介石的国民党合流。汪精卫、陈公博、顾孟余等不满蒋介石独揽权力，一九二八年底在上海成立中国国民党改组同志会，形成了国民党中的改组派。--第７１页。

　　１４９　第三党即一九二七年七一五反革命政变后，邓演达等国民党左派分子在上海组织的中国国民党临时行动委员会。他们反对蒋介石控制的国民党，同时也不赞成中国共产党。一九三五年第三党改名为中华民族解放行动委员会，响应中国共产党关于各党各派合作抗日、共赴国难的号召，积极参加抗日活动。一九四一年参加发起中国民主政团同盟。一九四七年改称农工民主党。一九四九年参加中国人民政治协商会议第一届全体会议。中华人民共和国成立后，农工民主党拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。--第７１、１５１页。

　　１５０　史量才（一八七八--一九三四），江苏江宁（今属南京市）人。一九一三年起任《申报》总经理。蒋介石统治初期采取拥蒋立场，"九一八"以后政治态度逐步改变。上海一二八抗战时，曾捐款支持抗日，并任抗日群众组织上海地方协会会长，后来又积极支持中国民权保障同盟。一九三四年十一月十三日被蒋介石特务暗杀。

　　杨杏佛（一八八三--一九三三），江西清江人。一九二五年随孙中山北上，任秘书。后任东南大学工学院院长、国民党政府中央研究院总干事等职。一九三二年同宋庆龄、蔡元培、鲁迅等在上海发起组织中国民权保障同盟，任总干事，进行反蒋抗日的进步活动。一九三三年六月十八日被蒋介石特务暗杀。--第７２页。

　　１５１　唐生智（一八八九--一九七○），湖南东安人。当时任国民革命军第八军军长、第四集团军总司令、湖南省主席、国民党中央执行委员等职。中华人民共和国成立后，任全国人民代表大会常务委员会委员等职。--第７３、１００页。

　　１５２　机器工会原名广东机器研究公会，后改名为广东机器工会，是国民党右派利用的工具。一九二四年国共合作后，反对和破坏共产党领导的工人运动。一九二六年一月公开发表宣言反对共产党。一九二七年四一五反革命政变时，协助反革命政权搜捕共产党员和进步群众。同年十二月参与镇压广州起义。--第７４页。

　　１５３　吴铁城（一八八八--一九五三），广东香山（今中山）人。一九二四年任广东革命政府东路讨贼军第一路军司令、广东警卫军司令、国民党广州市党部执行委员，一九二六年任国民党候补中央执行委员、国民革命军第六军第十七师师长，一九四六年九月是国共谈判改组政府问题五人小组中的国民党代表。--第７４、１１９页。

　　１５４　马超俊（一八八六--一九七七），广东台山人。第一次国内革命战争期间是国民党控制的黄色工会头子。--第７４页。

　　１５５　胡毅生（一八八三--一九五七），广东番禺（今属广州市）人。胡汉民堂弟。一九二五年在广州参加创办国民党右派报纸《国民新闻日报》，积极反共。廖仲恺被刺后，潜逃香港。--第７４页。

　　１５６　一九二七年四月十二日蒋介石反动派在上海血腥屠杀共产党人和革命群众，公开背叛革命，投降帝国主义和封建势力，这个政变被称为四一二反革命政变。--第７４页。

　　１５７　参见孙中山《致蒋介石手札》（见《孙中山选集》第８７６页）。精卫即汪精卫；展堂即胡汉民。--第７４页。

　　１５８　瞿秋白（一八九九--一九三五），江苏常州人。一九二二年参加中国共产党，是党的早期主要领导人之一。曾主编中共中央机关刊物《新青年》。在中国共产党第四、五、六次全国代表大会上均当选为中央委员。一九二七年国民党叛变后，主持了八月七日的中共中央紧急会议，这次会议结束了陈独秀右倾机会主义在党内的统治。会后任中共临时中央政治局常委，主持中央工作。一九二七年冬至一九二八年春主持中央工作时，犯过"左"倾盲动主义错误。一九二八年当选为共产国际执行委员会委员和主席团委员。一九三○年九月主持召开的六届三中全会，纠正了李立三"左"倾机会主义错误。在一九三一年一月六届四中全会上，遭到王明等"左"倾教条主义宗派主义分子的打击，被排斥于党的中央领导机关之外。此后，在上海同鲁迅合作从事革命文化运动。一九三四年到江西革命根据地，担任中华苏维埃共和国临时中央政府教育人民委员。同年十月红军主力长征后，被留在江西革命根据地坚持斗争。一九三五年二月在福建游击区被国民党军逮捕，六月十八日在福建长汀就义。--第７４页。

　　１５９　汪陈宣言指一九二七年四月五日汪精卫和陈独秀在上海发表的联合宣言。这个宣言极力掩盖国民党右派的反革命活动，声称"国民党......决无驱逐友党摧残工会之事"，同时又表示"中国共产党无论如何错误，也不至于主张打倒自己的友党......国民党"。宣言使工人阶级解除思想上的武装，放松对蒋介石背叛革命的警惕。--第７４页。

　　１６０　吴稚晖（一八六五--一九五三），江苏武进（今常州市）人。当时任国民党中央监察委员，一贯支持蒋介石的反革命活动，坚决反苏反共。--第７５页。

　　１６１　西安事变　也称双十二事变。在日本帝国主义加紧侵略中国，要把中国变为它的殖民地的危急形势下，以张学良将军为首的国民党东北军和以杨虎城将军为首的国民党第十七路军，在中国共产党的抗日民族统一战线政策和全国人民抗日运动的影响和推动下，要求蒋介石停止内战，一致抗日。蒋介石拒绝了这个要求，并亲自赶到西安积极部署"剿共"。一九三六年十二月十二日，张、杨联合行动，在西安附近的临潼扣押了蒋介石，这就是著名的西安事变。事变发生后，国民党内以何应钦为首的亲日派准备乘机发动大规模内战，牺牲蒋介石以便取而代之。由于中国共产党坚持和平解决西安事变的方针，并经过中共代表周恩来、博古（秦邦宪）、叶剑英等的艰苦工作，西安事变终于和平解决，促进了抗日民族统一战线的形成。--第７８页。

　　１６２　指一九三三年五月冯玉祥和中国共产党合作在察哈尔省组织的民众抗日同盟军。主要领导人还有吉鸿昌、方振武等。同盟军在张北、沽源等地与日本侵略军进行了激烈战斗，把日伪军完全逐出察哈尔省境。由于蒋介石和日本侵略军的双重压迫，同盟军的抗战活动于同年十月失败。--第７８页。

　　１６３　这封信指一九三六年八月二十五日《中国共产党致中国国民党书》。信中对国民党的反动统治和国民党五届二中全会决定的反动方针，作了义正词严的批判，同时申明了中国共产党关于建立抗日民族统一战线和准备重新实行国共合作的政策。--第７９页。

　　１６４　中国共产党为了以实际行动促成全国抗日的实现，由工农红军第一军团和第十五军团组成中国人民红军抗日先锋军，在一九三六年二月二十日东渡黄河抗日，遭到了蒋介石、阎锡山的武力阻拦。中华苏维埃人民共和国中央政府和中国人民红军革命军事委员会鉴于国难当前，应以实现全国抗战为根本，不愿和阻拦我抗日去路的国民党部队进行战斗，五月五日发表回师通电，将抗日东征军撤回黄河西岸。--第７９页。

　　１６５　一九三五年十二月九日，北平学生数千人，在中国共产党领导下举行爱国示威游行，提出"停止内战，一致对外"、"打倒日本帝国主义"等口号。游行的学生遭到国民党政府镇压。次日，北平各校学生宣布总罢课。十六日，学生和市民一万余人，再度举行示威游行。这次爱国运动得到全国人民的热烈响应，形成了中国人民抗日救亡运动的新高潮。--第７９、３５９页。

　　１６６　一九三六年十一月二十一日在甘肃环县山城堡，红军第一军团和第十五军团一部歼灭国民党军胡宗南部七十八师二三二旅全部和二三四旅两个团，这是第二次国内革命战争时期的最后一战。--第７９页。

　　１６７　潘汉年（一九○六--一九七七），江苏宜兴人。一九二五年加入中国共产党。一九三六至一九三七年间，任我党与国民党谈判停止内战、合作抗日的代表。抗日战争和解放战争时期，在上海等地领导对 敌隐蔽斗争和开展统战工作。一九四九年夏至一九五五年春，先后任中共中央华东局和上海市委社会部部长、统战部部长、上海市副市长等职。一九五五年被关押审查，一九六三年被错定为"内奸分子"，一九八二年中共中央予以平反昭雪。--第７９、１１６页。

　　１６８　蒋鼎文，参见本书法〔４５〕。--第８０页。

　　１６９　指毛泽东一九三七年五月三日所做题为《中国共产党在抗日时期的任务》的报告，见《毛泽东选集》第１卷。文内所说毛泽东在五月代表会上做的报告，也是指这篇文章。--第８１页。

　　１７０　指《我们对修改国民大会法规的意见》一文。载一九三七年五月一日出版的《解放周刊》第１卷第２期。--第８２页。

　　１７１　指一九三七年七月国民党政府在庐山召开的"各党派及无党派人士"座谈会。--第８２页。

　　１７２　王世杰（一八九一--一九八一），湖北崇阳人。当时任国民党中央宣传部长。--第８２页。

　　１７３　博古　即秦邦宪（一九○七--一九四六），江苏无锡人。一九二五年参加中国共产党。一九三一年四月任中国共产主义青年团中央书记，同年九月至一九三五年一月为中共临时中央局和中央局的主要负责人，犯过严重的"左"倾冒险主义错误。遵义会议后任中国工农红军野战政治部主任。一九三六年同周恩来、叶剑英等作为中共中央代表参加和平解决西安事变。一九三七年任党中央组织部部长、中共中央长江局委员等职。抗日战争爆发后任中共驻南京代表。一九四一年起在延安主持《解放日报》和新华通讯社。一九四五年在党的第七次全国代表大会上当选为中央委员。--第８２页。

　　１７４　一九三七年二月中旬至三月中旬，中国共产党代表周恩来、叶剑英在西安同国民党代表顾祝同、贺衷寒、张冲谈判，重申了中共中央致国民党五届三中全会电中提出的五项要求和四项保证。五项要求是：（一）停止一切内战，集中国力，一致对外；（二）保障言论、集会、结社之自由，释放一切政治犯；（三）召集各党各派各界各军的代表会议，集中全国人材，共同救国；（四）迅速完成对日抗战之一切准备工作；（五）改善人民生活。四项保证是：（一）在全国范围内停止推翻国民政府之武装暴动方针；（二）苏维埃政府改名为中华民国特区政府，红军改名为国民革命军（改编为一个军四个师，每师一万五千人），直接受南京中央政府与军事委员会之指导；（三）在特区政府区域内，实行普选的民主制度；（四）停止没收土地之政策，坚决执行抗日民族统一战线之共同纲领。在谈判中周恩来还提出恢复张学良的自由、复职授权等问题。因国民党的阻挠，谈判无结果，最后只达成了在西安设中共办事处的协议。

　　三月周恩来到杭州同蒋介石谈判，就我党的五项要求和四项保证，提出具体实施方案，蒋介石则要求拟定民族统一战线纲领和确认他的领袖地位。双方商定谈判继续进行。

　　六月周恩来到庐山同蒋介石、宋子文谈判。在红军改编后的总指挥部、军队和边区的人事任命等问题上，双方争论很久未得解决。

　　七月十五日中共中央向国民党递送了《中国共产党为公布国共合作宣言》，十七日周恩来、博古、林伯渠同蒋介石、邵力子、张冲在庐山继续谈判。国民党承认陕甘宁边区，同意红军改编为八路军。"八一三"以后，蒋介石被迫在九月二十二日公布上述宣言并同意八路军设立总部。--第８２页。

　　１７５　顾祝同，一八九三年生，江苏涟水人。一九三七年任国民党军事委员会委员长重庆行营主任兼西安行营主任。皖南事变时任第三战区司令长官。--第８２页。

　　１７６　一九三七年九、十月间，八路军的三个师先后开抵山西抗日前线。九月二十五日，一一五师在平型关伏击日军，歼敌板垣师团一部约一千多人。这是抗战开始后中国军队所取得的第一个大胜利。--第８２页。

　　１７７　这个协定指一九三七年八月苏联和国民党政府签订的中苏互不侵犯条约。--第８４页。

　　１７８　徐向前，一九○一年生，山西五台人。一九三九年被中共中央派往山东，任第一纵队司令、中共中央山东分局委员。--第８６页。

　　１７９　鹿钟麟（一八八四--一九六六），河北定县人。当时任国民党政府河北省主席，在蒋介石的指令下曾和八路军进行磨擦。中华人民共和国成立后，任国防委员会委员等职。

　　张荫梧（一八九一--一九四九），河北博野人。当时任国民党河北省民军总指挥，不断制造磨擦，进攻八路军。一九三九年六月率部袭击河北深县八路军的后方机关，惨杀八路军干部和战士四百余人。--第８６页。

　　１８０　朱怀冰（一八九二--一九六八），湖北黄冈人。当时是国民党军第九十七军军长。一九四○年二三月间，蒋介石指令其纠合庞炳勋、张荫梧、侯如墉等部，三路进攻太行区域的八路军，被八路军彻底击败。--第８７页。

　　１８１　石友三（一八九一--一九四○），吉林长春人。当时任国民党军第三十九集团军总司令，在河北省南部联合日军进攻八路军，摧残抗日民主政权，屠杀共产党员和进步分子。--第８７页。

　　１８２　高树勋（一八九八--一九七二），河北盐山人。当时任国民党军新八军军长。曾奉蒋介石命令在河北一带同八路军磨擦。一九四五年十月三十日率领一个军和一个纵队在邯郸内战前线起义。一九四六年参加中国共产党。中华人民共和国成立后，任国防委员会委员等职。--第８７页。

　　１８３　汤恩伯（一八九九--一九五四），浙江武义人。当时任第一战区副司令长官、国民党军豫鲁苏皖边区总司令，驻守河南，积极推行反共反人民政策。--第８７页。

　　１８４　一九三九年六月十二日，国民党第二十七集团军奉蒋介石的密令，派兵包围新四军设在湖南平江嘉义镇的通讯处，惨杀新四军参议涂正坤、八路军少校副官罗梓铭等六人，这就是平江惨案。--第８８页。

　　１８５　一九三九年十一月十一、十二两日，河南确山、信阳、泌阳等县的国民党反动武装一千八百余人，围攻确山县竹沟镇新四军留守处，惨杀新四军伤员和他们的家属以及群众共二百余人，这就是竹沟惨案。--第８８页。

　　１８６　一九三九年十二月，阎锡山在蒋介石的指使下集中六个军的兵力，向驻在山西西部的新军进攻。这次进攻被新军的反击所粉碎。同时，阎军又在山西东南部进攻新军，摧残阳城、晋城、长治、沁水等地抗日民主政府和人民团体，屠杀大批共产党员和进步分子。--第８８页。

　　１８７　卫立煌（一八九六--一九六○），安徽合肥人。当时任第二战区副司令长官。一九五五年由香港回到北京，曾任国防委员会副主席等职。--第８８页。

　　１８８　指一九四○年六月在重庆同国民党进行的谈判。--第８８页。

　　１８９　"投畀有北"，参看《诗经·小雅·巷伯》："取彼谮人，投畀豺虎；豺虎不食，投畀有北。"谮，进谗言，说人的坏话；畀，给予；北，指北方寒冷的不毛之地。--第８９页。

　　１９０　何白《皓电》是蒋介石以国民党政府军事委员会正副参谋总长何应钦、白崇禧的名义，在一九四○年十月十九日（皓）发给八路军和新四军领导人的电报。《皓电》对坚持敌后抗战的八路军、新四军大肆诬蔑，强迫命令黄河以南的抗日部队限期撤到黄河以北。为了顾全大局，中共中央以十八集团军总司令朱德、副总司令彭德怀和新四军军长叶挺、副军长项英的名义，在十一月九日（佳）电复何、白，除据实驳斥《皓电》的造谣以外，答应将皖南新四军部队移到长江以北。--第８９页。

　　１９１　指一九四○年七月十六日国民党提出的所谓《中央提示案》。主要内容是：取消陕甘宁边区，代以陕北行政区公署，归陕西省政府领导；缩编八路军、新四军，并限制其防地。十月十九日蒋介石以何应钦、白崇禧的名义，在《皓电》中将所谓《中央提示案》以最后决定的形式向我党提出。--第８９页。

　　１９２　指国民党军苏鲁战区副司令韩德勤所属苏鲁皖游击总队总指挥李明扬的部队和李守维的八十九军。--第８９页。

　　１９３　项英（一八九八--一九四一），湖北武汉人。抗日战争爆发后任中共中央东南局书记兼新四军副军长。一九四一年一月，皖南事变时牺牲。--第８９页。

　　１９４　陈毅（一九○一--一九七二），四川乐至人。一九三八年至一九四六年先后任新四军第一支队司令员、代理军长、军长等职。中华人民共和国成立后，曾任上海市市长、国务院副总理兼外交部部长、中国人民政治协商会议全国委员会副主席。--第８９、１９０、３９１、４４３页。

　　１９５　一九四一年一月，取得国民党当局同意由皖南北移的新四军，在安徽泾县茂林镇遭到国民党军队发动的突然围攻。经过七个昼夜的浴血战斗，叶挺军长被扣，九千多名指战员大部英勇牺牲。这就是震惊中外的皖南事变。蒋介石在一月十七日宣布新四军"叛乱"，取消新四军番号，将叶挺军长交"军法审判"。二十日中共中央革命军事委员会发布命令，任命陈毅为新四军代理军长，张云逸为副军长，刘少奇为政治委员，赖传珠为参谋长，邓子恢为政治部主任。同日中共中央革命军事委员会发言人发表谈话，针锋相对地驳斥了国民党反动派对新四军的诬蔑，提出取消一月十七日的反动命令、惩办皖南事变祸首等十二条严正要求。--第８９、１０９、３９５页。

　　１９８　指一九四一年四月十三日苏日双方代表在莫斯科签订的《苏日中立条约》。一九四五年四月五日苏联政府发表声明废除这一条约。--第９０页。

　　１９７　一九四一年六月二十二日，法西斯德国片面撕毁苏德互不侵犯条约，未经宣战向苏联发动突然进攻。苏联人民在斯大林为首的党和政府领导下，开始了卫国战争。--第９０页。

　　１９８　一九四一年十二月七日晨，日本未经宣战，以海空军突然袭击美国在太平洋地区的主要海空军基地珍珠港，使美国太平洋舰队遭到惨重损失。十二月八日，美英对日正式宣战，太平洋战争从此开始。十二月十日，日本空军又在新加坡附近海面袭击英国远东舰队，使英舰队遭到重大损失。--第９０页。

　　１９９　指一九四二至一九四三年间，新疆独裁统治者盛世才为了投靠蒋介石，抛弃革命伪装，大肆逮捕和杀害在新疆工作的共产党员和进步人士的反革命事件。--第９０页。

　　２００　张群，一八八九年生，四川华阳人。从一九四○年起任国民党军事委员会委员长成都行辕主任、四川省政府主席。--第９０页。

　　２０１　戴笠（一八九七--一九四六），浙江江山人。黄埔军官学校毕业。曾任蒋介石侍从副官，后任国民党特务机关中华民族复兴社所属特务处处长、军事委员会调查统计局局长和中美特种技术合作所主任。--第９１、２４１页。

　　２０２　林彪（一九○七--一九七一），湖北黄冈人。抗日战争时期任八路军一一五师师长。一九六六年后组织反革命阴谋集团，企图篡党夺权，阴谋败露后，一九七一年九月十三日叛国出逃，机毁丧命。--第９１页。

　　２０３　张治中（一八九○--一九六九），字文白，安徽巢县人。抗日战争时期，历任国民党湖南省政府主席、军事委员会政治部部长、三民主义青年团书记长等职。一九四六年任国民党军西北行营主任兼新疆省主席，代表国民党参加国共谈判的军事三人小组。一九四九年任国民党政府和谈代表团首席代表，同中国共产党代表团在北平进行谈判。双方代表拟定的国内和平协定为国民党政府拒绝后，张留住北平。中华人民共和国成立后，任全国人民代表大会常务委员会副委员长等职。--第９１、１２８、１３２、３９２页。

　　２０４　参见本书注〔１４７〕。--第９１页。

　　２０５　一九四四年春，国民党统治区的民主党派和民主人士先后在重庆、成都、昆明、桂林、西安等地组织各种群众团体，利用报刊和集会讨论宪政，抨击国民党的法西斯专政，要求民主自由，主张开放政权，实行宪政，得到全国各界人士的广泛响应。--第９２页。

　　２０６　赫尔利（一八八三--一九六三），美国共和党政客。一九四四年九月以美国总统私人代表身份来华，十一月间曾到延安同我党商讨和国民党成立联合政府等问题。同年底任美国驻中国大使，因支持蒋介石的反共政策，遭到中国人民的坚决反对，一九四五年十一月离职。--第９３页。

　　２０７　一九四四年十一月十一日和一九四五年一月二十四日，周恩来两次由延安赴重庆，同国民党进行谈判。--第９３页。

　　２０８　民主同盟　即中国民主同盟，简称"民盟"。一九四一年成立，原名中国民主政团同盟，一九四四年改今名。成员主要是文教界知识分子。一九四七年被国民党政府宣布为非法团体。一九四八年一月在香港重建组织。同年五月响应中国共产党提出的召开新政治协商会议的号召，一九四九年参加了中国人民政治协商会议。中华人民共和国成立后，民盟拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。--第９３、１１８、１２５、１３４、１５０、１７１、２０５、３４９页。

　　２０９　国民党政府曾决定在一九三六年召开"国民大会"。一九三六年五月五日颁布了"宪法草案"（即五五宪草），并规定自七月起选举国大代表，十一月十二日开会。但这次大会没有开成。--第９４页。

　　２１０　斯科比，英国人。第二次世界大战后期驻希腊盟军司令。一九四四 年十月，德军在欧陆败退，斯科比率领英军，带着流亡在国外的希腊反动政府进入希腊，指使并协助希腊反动政府向长期英勇抵抗德军的希腊人民解放军进攻，屠杀希腊爱国人民。--第９５页。

　　２１１　"宁"指南京政府，"汉"指武汉政府。一九二七年蒋介石发动四一二反革命政变，在南京另组国民政府，自任主席，并通过"清党"等反革命决议案，通缉共产党员，宣布武汉国民政府及在武汉的国民党中央一切决议为非法。同年五月汪精卫为首的武汉国民政府逐步公开走上反共的道路。七月十五日汪精卫举行"分共"会议，正式决定与共产党分裂，公开屠杀共产党员，从此"宁汉合作"，蒋汪反革命合流。--第９６页。

　　２１２　陈赞贤（一八九六--一九二七），江西南康人。一九二五年参加中国共产党。一九二七年一月任赣州总工会委员长和江西省总工会副委员长。同年三月六日在赣州被蒋介石反动派杀害。--第９８页。

　　２１３　瓦窑堡会议指一九三五年十二月中共中央在陕北子长县瓦窑堡举行的政治局会议，二十五日通过了《关于目前政治形势与党的任务决议》。这个决议全面地分析了当时国内外的形势和阶级关系的变化，确定了建立抗日民族统一战线的政策，批判了成为当时党内主要危险的关门主义，同时也指出了在新的革命时期预防右倾机会主义复活的必要性。--第９８页。

　　２１４　一九二七年十二月十一日至十三日，在张太雷、苏兆征、叶挺、恽代英、叶剑英、杨殷等领导下，以国民革命军第四军教导团和广州工人赤卫队为主力在广州发动起义，起义部队曾占据市内绝大部分地区，一度成立了中国共产党领导的人民政权--广州苏维埃政府。起义失败后，起义武装中的一部分与彭湃领导的东江农民起义武装会合；一部分转移到广西，以后参加了左、右江的农民武装起义；一部分参加朱德、陈毅率领的南昌起义部队转战到了井冈山。--第１０１页。

　　２１５　第一次国内革命战争期间，上海工人在一九二六年十月二十二日，一九二七年二月二十一日两次举行武装起义，均遭失败。一九二七年三月二十一日在周恩来、罗亦农、赵世炎、汪寿华等领导下举行第三次武装起义，推翻了北洋军阀在上海的统治，建立了上海市民代表政府。--第１０１页。

　　２１６　这是针对王明一九三七年十二月九日在中共中央政治局会议报告中的错误观点的批评。--第１０３页。

　　２１７　七个统一，是王明在一九三八年三月十一日中共中央政治局会议的总结中提出的主张。--第１０９页。

　　２１８　一九三八年八月二十日国民党武汉卫戍司令部政治部宣布解散中国共产党领导的中华民族解放先锋队和进步的群众组织青年救国团、蚁社。--第１０９页。

　　２１９　两个时期的商谈是指国共两党在抗战开始之前和抗战胜利之后两个时期举行的会谈。在抗战开始前的一九三六年至一九三七年，为了停止内战，团结抗日，国共两党代表举行了会谈。通过会谈，实现了国共合作、团结抗日的局面。在抗日战争胜利后的一九四五年八月下旬至十月上旬，为了停止内战，和平建国，国共两党的代表再度举行会谈。这次会谈结果，虽然签订了"双十协定"十二条，但墨迹未干，国民党政府便在美帝国主义的支持下，发动了新的内战。--第１１１页。

　　２２０　翰笙　即阳翰笙，一九○二年生，四川高县人。一九二五年加入中国共产党。第一次国内革命战争时期，先后在黄埔军官学校和北伐军中做党的工作。抗日战争时期任国民政府政治部第三厅主任秘书、文化工作委员会副主任，并先后担任文协理事、影协常务理事等，长期在国民党统治区，参与领导党在文化界的统一战线工作。--第１１５页。

　　２２１　陶行知（一八九一--一九四六），安徽歙县人。人民教育家，爱国民主人士。早年留学美国。一九一六年回国，先后任南京高等师范学校教务主任、中华教育改进社总干事，发起组织中华平民教育促进会，在南京、上海郊区创办晓庄学校和山海工学团，推行平民教育和乡村教育运动。一九三五年一二九运动后，参加发起组织上海文化界抗日救国联合会、上海各界抗日救国联合会。抗日战争期间，积极参加抗日斗争和国民党统治区反独裁反内战的政治活动，并在重庆创办育才学校和社会大学。一九四五年春参加中国民主同盟，被选为中央常务委员兼教育委员会主任委员。抗战胜利后在国民党统治区继续从事民主运动。--第１１５页。

　　２２２　沈钧儒（一八七五--一九六三），号衡山，浙江嘉兴人。清末曾考中进士。参加过辛亥革命和反对北洋军阀的斗争，后在上海任律师。抗战前组织上海文化界救国会和全国各界救国联合会。抗战期间，倡议组织中国民主政团同盟（后改称中国民主同盟）。抗战胜利后，任中国人民救国会主席，积极参加争取和平民主的斗争，反对国民党的内战政策。中华人民共和国成立后，曾任中央人民政府委员、全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席、最高人民法院院长、中国民主同盟中央主席。--第１１６、１４２、１５３、１５５、４１２页。

　　２２３　邹韬奋（一八九五--一九四四），江西余江人。杰出的新闻记者、政论家和出版家。从一九二六年在上海主编《生活》周刊起，毕生从事新闻出版工作。一九三一年九一八事变后，反对蒋介石的不抵抗政策。一九三二年创办生活书店。一九三三年初参加中国民权保障同盟，七月被迫流亡国外。一九三五年回国，参加中国共产党领导的救亡运动，先后在上海、香港主编《大众生活》周刊、《生活日报》、《生活星期刊》，并担任上海各界救国会和全国各界救国联合会的领导工作。一九三六年与沈钧儒等被国民党反动派逮捕。抗日战争开始后获释，先后在上海、武汉、重庆主编《抗战》、《全民抗战》等刊物，积极参加反对蒋介石反动政策的政治斗争。皖南事变后被迫流亡香港，重新刊行《大众生活》。日军侵占香港后赴广东东江游击区，一九四二年到苏北解放区。一九四四年七月二十四日因病逝世。中共中央接受他遗书中的申请，追认他为中共正式党员。--第１１６页。

　　２２４　伍云甫（一九○四--一九六九），湖南耒阳人。一九二六年参加中国共产党。一九四六年任解放区救济总会秘书长。--第１１６页。

　　２２５　马歇尔（一八八○--一九五九），美国职业军人，政客。一九四五年十二月任美国总统杜鲁门的驻中国特使，以"调处"为名，参与国共谈判，支持国民党政府发动反共反人民的内战。一九四六年八月宣布"调处"失败，一九四七年一月八日离华回国。--第１１７、１１８页。

　　２２６　司徒雷登（一八七六--一九六二），当时任美国驻中国大使。--第１１７、１１８页。

　　２２７　张奚若（一八八九--一九七三），陕西朝邑（今大荔）人。爱国民主人士。抗日战争时期为西南联合大学政治学系教授。抗战胜利后，反对国民党召开所谓国民大会，拥护中国共产党提出的成立联合政府的主张，支持国民党统治区的学生民主运动。中华人民共和国成立后，曾任中央人民政府委员、政务院政法委员会副主任、教育部长、对外文化联络委员会主任、中国人民外交学会会长等职。--第１１８页。

　　２２８　钱端升，一九○○年生，上海市人。抗日战争时期，为西南联大政治学系教授。中华人民共和国成立后，曾任中国人民政治协商会议全国委员会委员、外交学会副会长、北京政法学院院长、中国民主同盟中央常务委员。--第１１８页。

　　２２９　黄炎培（一八七八--一九六五），字任之（故又称黄任老），上海川沙人。清末曾考中举人。一九○五年加入同盟会。一九一七年在上海创办中华职业教育社。一九四一年参与组织中国民主政团同盟。一九四五年发起建立中国民主建国会。中华人民共和国成立后，曾任中央人民政府委员、政务院副总理兼轻工业部部长、全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席等职。--第１１８、１７５、２０６、２３１、３５６、４１２页。

　　２３０　罗迈　即李维汉（一八九六--一九八四），湖南长沙人。一九二二年参加中国共产党。一九四六年参加政协中共代表团，在重庆、南京、上海等地广泛接触各方面人士。一九五七年任中共中央统战部部长。--第１１８、３３９、３５６页。

　　２３１　三国公告指一九四五年十二月二十七日在莫斯科召开的苏、英、美三国外长会议发表的公报。其中有关中国方面的内容是重申三国坚持不干涉中国内政的政策，苏美外长一致同意苏美两国军队尽早撤离中国。此后苏联政府履行了这个协议，而美国政府却违背了自己的诺言。--第１１９页。

　　２３２　张厉生，生于一九○○年，河北乐亭人。当时是国共谈判改组政府问题五人小组中的国民党代表。--第１１９页。

　　２３３　五条指一九四六年七月二十五日国民党政府向中共代表团提出的五项条件。其内容是：要求共产党领导的军队"一、撤出苏皖边区；二、撤出胶济线；三、撤出承德与承德以南地区；四、东北在十月半前退至黑龙江、兴安两省及嫩江北半省与延吉；五、山东山西两省须撤出六月七日后中共占领地区。"这是国民党政府为阻挠和破坏全面停战和商谈改组政府而提出的无理要求，因而当即遭到中共代表团的断然拒绝。--第１１９页。

　　２３４　一九四九年四月一日起，国共双方代表在北平举行和平谈判。南京国民党政府和平谈判代表团的成员是：张治中、邵力子、黄绍竑、章士钊、李蒸、刘斐，张治中为首席代表。中国共产党代表团的成员是：周恩来、林伯渠、林彪、叶剑英、李维汉、聂荣臻，周恩来为首席代表。--第１２３页。

　　２３５　见《联共（布）党史简明教程》，人民出版社一九七五年版第１１７页。--第１２３页。

　　２３６　国民党革命委员会简称"民革"。成立于一九四八年一月。主要成员是原国民党中的爱国民主分子。一九四八年五月，响应中国共产党提出的召开新政治协商会议的号召，一九四九年九月参加中国人民政治协商会议。中华人民共和国成立后，民革拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。--第１２５、１３４、１７１、２０５、２４０、２４２、３４９页。

　　２３７　民主建国会　即中国民主建国会，简称"民建"。一九四五年成立。主要由民族工商业者组成。一九四八年响应中国共产党提出的召开新政治协商会议的号召，一九四九年参加中国人民政治协商会议。中华人民共和国成立后，拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。--第１２５、１７１、１７９、２０５、３４９页。

　　２３８　秘密组织指中国民主革命同盟，通称"小民革"，是我党影响下的国民党内部反蒋的秘密政治团体。一九四一年夏在重庆成立，主要领导者有王昆仑、王炳南、许宝驹、屈武等。一九四九年九月新政治协商会议召开之前，接受我党提议，该盟宣告结束。--第１２５页。

　　２３９　郭沫若（一八九二--一九七八），四川乐山人。历史学家、文学家和革命活动家。从"五四"时期起，积极从事反帝反封建的革命文化运动。抗日战争中，在周恩来直接领导下，任国民政府军事委员会政治部第三厅厅长、文化工作委员会主任，组织国民党统治区的进步文化人士从事抗日救亡工作。抗战胜利后，站在反独裁、反内战的民主运动前列，同蒋介石的反动统治进行了针锋相对的斗争。中华人民共和国成立后，曾任中央人民政府政务院副总理、中国科学院院长、全国人民代表大会常务委员会副委员长。--第１２５、４１０页。

　　２４０　马寅初（一八八二--一九八二），浙江嵊县人。经济学家。一九一五至一九四八年先后任北京大学、重庆大学等校教授。中华人民共和国成立后，曾任全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会委员、中国科学院哲学社会科学部委员、北京大学校长。--第１２５、２０８页。

　　２４１　李达（一八九○--一九六六），湖南零陵人。哲学家。一九二七年大革命失败后，长期从事教育工作，曾先后任上海法政学院、暨南大学、北平大学、广西大学、湖南大学等校教授。中华人民共和国成立后，任湖南大学、武汉大学校长，中国人民政治协商会议全国委员会委员。--第１２５页。

　　２４２　符定一（一八七七--一九五八），湖南衡山人。文字学家。辛亥革命后，曾任湖南省教育总会会长、湖南全省高等中学校长、北京政府财政部次长等职。一九四六年夏，他应毛泽东的邀请访问过延安，返北平后曾遭到国民党当局的无理拘捕。中华人民共和国成立后，任中央文史研究馆馆长、中国人民政治协商会议全国委员会委员。--第１２５页。

　　２４３　吴耀宗（一八九三--一九七九），广东顺德人。宗教界爱国民主人士。曾任中华基督教青年会全国协会校会坦主任、青年协会书局主任。中华人民共和国成立后，带头发起基督教自治、自养、自传的三自爱国运动，号召全国基督教会摆脱帝国主义控制。他先后当选为全国人民代表大会常务委员会委员，中国人民政治协商会议全国委员会委员，中国基督教三自爱国运动委员会主席。--第１２５、１８７页。

　　２４４　社会贤达指参加一九四六年一月在重庆召开的政治协商会议的无党派人士。其中有著名革命活动家郭沫若等，也包括一些以无党无派面目出现、实际上依附国民党政府的政客，如王云五、傅斯年等。--第１２６页。

　　２４５　指一九四六年十一月十五日至十二月二十五日在南京由国民党一党包办召开的所谓国民大会。国民党为了维持它的独裁统治，收买青年党、民社党和极少数所谓社会贤达参加了大会，并非法制定了《中华民国宪法》。由于它根本违背了政协协议和全国人民的意志，因而遭到中国共产党和民盟等民主党派的抵制和否认，故称伪国民大会。--第１２６、１５２页。

　　２４６　指一九四八年四月三十日中共中央发布纪念五一劳动节口号，提出："各民主党派、各人民团体、各社会贤达迅速召开政治协商会议，讨论并实现召集人民代表大会，成立民主联合政府。"这个号召立即得到国民党统治区域的民主党派、人民团体和无党派民主人士的热烈响应。--第１２６、１３０页。

　　２４７　颜惠庆（一八七七--一九五○），上海人。曾任北洋政府国务总理、外交总长和国民党政府驻美公使、驻苏大使。一九四九年春，为反对蒋介石继续内战，曾往北平、石家庄与中国共产党代表商谈和平。中华人民共和国成立后，任华东军政委员会副主席，中央人民政府政治法律委员会委员。--第１２８、１３２页。

　　２４８　章士钊（一八八一--一九七三），字行严，湖南长沙人。北洋军阀统治时期曾任段祺瑞执政府司法总长兼教育总长。一九四九年国共和平谈判时，是南京国民党政府代表团成员之一，因国民党政府拒绝在国内和平协定上签字，遂留在北平。中华人民共和国成立后，曾任全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员、中央文史馆馆长。--第１２８、３９７页。

　　２４９　江庸（一八七八--一九六○），福建长汀人。法学家。一九四九年春和颜惠庆、章士钊、邵力子等北上同中国共产党商议和谈问题。中华人民共和国成立后，曾任中央人民政府政治法律委员会委员、上海市文史研究馆副馆长。--第１２８页。

　　２５０　傅作义（一八九五--一九七四），字宜生，山西临猗人。曾任国民党绥远省政府主席、国民党华北"剿总"总司令。一九四九年一月率部接受和平改编，对北平和绥远的和平解放做出了贡献。中华人民共和国成立后，曾任中央人民政府委员、中国人民政治协商会议全国委员会副主席、水利电力部部长。--第１２８、１７５、４００页。

　　２５１　邓宝珊（一八九四--一九六八），甘肃天水人。曾任国民党军第二十一军团军团长兼新一军军长、晋陕绥边区总司令。一九四九年初起义。中华人民共和国成立后，曾任甘肃省人民政府主席。--第１２８页。

　　２５２　邵力子（一八八二--一九六七），浙江绍兴人。曾任国民党陕西省政府主席、国民党中央宣传部部长、驻苏联大使等职。一九四九年作为国民党政府和平谈判代表团成员参加国共和谈，后留北平未返。中华人民共和国成立后，曾任全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员、中国国民党革命委员会中央常务委员。--第１２８、１３２页。

　　２５３　孙夫人即孙中山夫人宋庆龄（一八九三--一九八一），广东文昌人。抗日战争时期，她先后在广州、香港发起组织保卫中国同盟，致力于战时医药工作和儿童保育工作。一九四五年抗日战争胜利后，在上海创建中国福利基金会，在十分困难的条件下，为中国人民解放事业做出重大贡献。中华人民共和国成立后，曾任中央人民政府副主席、全国人民代表大会常务委员会副委员长、中华人民共和国副主席、名誉主席。--第１３２页。

　　２５４　陶孟和（一八八八--一九六○），天津人。曾任北京大学教授、北平社会调查所所长、南京中央研究院社会科学研究所所长。中华人民共和国成立后，任全国人民代表大会代表、中国人民政治协商会议全国委员会常务委员、中国科学院副院长等职。--第１３２页。

　　２５５　钱昌照，一八九九年生，江苏常熟人。一九三二年至一九四七年先后任国民党政府资源委员会副秘书长、主任委员、委员长。中华人民共和国成立后，任全国人民代表大会代表、政务院财政经济委员会委员兼计划局副局长、中国人民政治协商会议全国委员会委员、副主席等职。--第１３２页。

　　２５６　萨镇冰（一八五九--一九五二），福建福州人。曾任清末海军统制、北洋政府海军总长等职。一九三三年十一月参加福建人民革命政府。中华人民共和国成立后，任中国人民政治协商会议全国委员会委员、中央人民政府人民革命军事委员会委员。--第１３２页。

　　２５７　张难先（一八七四--一九六八），湖北沔阳人。曾任国民党政府铨叙部长、浙江省政府主席、湖北省民政厅长和国民参政员等职。抗日战争后期，在中国共产党抗日民族统一战线政策的影响下，逐渐转向支持民主运动。中华人民共和国成立后，任中央人民政府委员、中南军政委员会副主席、全国人民代表大会常务委员会委员。--第１３２页。

　　２５８　陈瑾昆（一八八七--一九五九），湖南常德人。法学家。曾任北京大学教授。一九四六年从北平到延安，后任中共中央法律委员会委员、华北人民法院院长。--第１３２页。

　　２５９　吴奇伟（一八九○--一九五三），广东大埔人。曾任国民党第四、第六战区副司令长官、湖南省政府主席等职。一九四九年五月在粤东、闽西率部起义。中华人民共和国成立后，任中国人民政治协商会议全国委员会委员、广东省人民政府委员。--第１３２页。

　　２６０　曾泽生（一九○二--一九七三），云南永善人。曾任国民党军第一兵团副司令兼六十军军长。一九四八年十月在长春率部起义。中华人民共和国成立后，任中国人民解放军第五十军军长、国防委员会委员等职。--第１３３页。

　　２６１　张轸（一八九四--一九八一），河南罗山人。曾任国民党中央候补监察委员、第五绥靖区司令兼河南省政府主席等职。一九四九年五月在武昌起义。后任中国人民解放军第五十一军军长、湖北省军区副司令员、河南省副省长、中国人民政治协商会议全国委员会委员。--第１３３页。

　　２６２　周信芳（一八九五--一九七五），浙江慈溪人。京剧表演艺术家，艺名麒麟童，京剧"麒派"艺术的创立者。中华人民共和国成立后，曾任中国戏曲研究院副院长、华东戏曲研究院院长、上海京剧院院长、中国戏剧家协会副主席等职。一九五九年加入中国共产党。--第１３３页。

　　２６３　梅兰芳（一八九四--一九六一），原籍江苏泰州，生于北京。京剧表演艺术家，京剧"梅派"艺术的创立者。中华人民共和国成立后，曾任中国京剧院院长、中国戏曲研究院院长、中国文学艺术联合会副主席、中国戏剧家协会副主席、中国人民政治协商会议全国委员会常务委员。一九五九年加入中国共产党。--第１３３页。

　　２６４　程砚秋（一九○四--一九五八），北京人。京剧表演艺术家，京剧"程派"艺术的创立者。中华人民共和国成立后，任中国戏曲研究院副院长。一九五七年加入中国共产党。--第１３３、３９２页。

　　２６５　戎冠秀，生于一八八七年，河北平山人。抗日战争时期任村妇女救国会主任，在晋察冀边区第一届群英会上获得"子弟兵的母亲"的光荣称号。中华人民共和国成立后，曾任全国人民代表大会代表，中华全国妇女联合会执行委员。--第１３３页。

　　２６６　九三学社，原名民主科学社，一九四四年在重庆成立。后为纪念一九四五年九月三日抗日战争胜利日改称现名。其主要成员是文教、科技界的知识分子。一九四九年一月响应中国共产党提出的召开新政治协商会议的号召，同年参加中国人民政治协商会议。中华人民共和国成立后，拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。--第１３３、２０５、３９４页。

　　２６７　台湾民主自治同盟，简称"台盟"。是爱国民主党派之一。一九四七年由台湾省籍的爱国民主人士组成。一九四八年响应中国共产党提出的召开新政治协商会议的号召，一九四九年九月参加中国人民政治协商会议。中华人民共和国成立后，拥护中国共产党的领导，参加社会主义革命和社会主义建设，为统一祖国而努力。--第１３３页。

　　２６８　青年救国会是抗日战争时期解放区团结各界青年一致抗日的青年群众组织。一九三七年四月在延安成立西北青年救国联合会。一九三八年又在延安成立中华青年救国团体联合办事处，作为领导全国青年工作的机关。以后各解放区普遍建立了青年救国会，中华民族解放先锋队也于一九四○年后并入。任务是在中国共产党领导下，进行抗日救国宣传，动员青年积极参军参战，支援前线，开展减租减息和生产运动等工作。--第１３３页。

　　２６９　民主青年同盟，简称"民青"。抗日战争后期（一九四五年）在国民党统治区成立的以新民主主义为政治纲领的先进青年的地下组织。成员主要是学生及部分职业青年。任务是团结青年，在中国共产党领导下，积极参加反美反蒋斗争。解放后，大部分盟员转入中国新民主主义青年团。--第１３３页。

　　２７０　孙文主义革命同盟，成立于一九四八年春。主要由国民党内一部分不满蒋介石反动统治的人结合而成。主要负责人有许闻天、邓昊民等，曾参加过一些反蒋活动。一九四九年秋自行宣告解散。--第１３４页。

　　２７１　民社党革新派，成立于一九四七年五月。由反对张君劢的民社党党员所组成。政治主张鼓吹中间路线。一九四九年新政治协商会议筹备会议期间，其上层个别领导人如汪世铭、沙彦楷因曾参加反蒋反美民主活动，被允许以个人身份参加中国人民政治协商会议第一届全体会议。其组织于同年宣告解散。--第１３４页。

　　２７２　汪世铭（一八九六--一九七七），安徽桐城人。原民社党革新派负责人之一。一九四八年在香港拥护中国共产党发出的五一号召。一九四九年九月，作为特邀人士参加中国人民政治协商会议第一届全体会议。同年加入中国民主同盟。中华人民共和国成立后，任全国人民代表大会代表，国务院参事、中国民主同盟中央委员会常务委员。--第１３４页。

　　２７３　彭德怀（一八九八--一九七四），湖南湘潭人。当时任中国人民解放军副总司令、第一野战军司令员兼政治委员、中共中央西北局第一书记。--第１３５页。

　　２７４　旧的政治协商会议指一九四六年一月十日至三十一日在重庆召开的政治协商会议。这次会议是蒋介石在全国人民要求和平的压力下被迫召开的，参加会议的有国民党、共产党以及其他党派和社会贤达的代表。会议通过了关于政府组织问题的协议、和平建国纲领、关于国民大会问题的协议、关于宪法草案问题的协议、关于军事问题的协议等五项决议。为了区别于一九四九年六月在北平召开的新政治协商会议（一九四九年九月改称中国人民政治协商会议），故称"旧政协"。--第１３５页。

　　２７５　夷通彝，夷族即彝族。--第１３９页。

　　２７６　陈嘉庚（一八七四--一九六一），福建同安集美镇（今属厦门市）人。爱国华侨领袖。抗日战争时期，任南洋华侨筹赈祖国难民总会（简称南侨总会）主席，积极支持国内的抗战事业，拥护中国共产党的抗日民族统一战线政策，曾到延安慰劳边区抗战军民。解放战争时期，积极参加反蒋爱国民主运动。中华人民共和国成立后，任中央人民政府委员、中华全国归国华侨联合会主席、全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会副主席。--第１４０页。

　　２７７　中央人民政府委员会即中华人民共和国中央人民政府委员会。一九四九年十月一日成立。由中国人民政治协商会议全体会议选出主席一人，副主席六人，委员五十六人，并由中央人民政府委员会互选秘书长一人组成。至一九五四年九月十五日全国人民代表大会召开前，是我国行使最高国家权力的机关。--第１４１页。

　　２７８　陈叔通（一八七六--一九六六），浙江杭州人。清末翰林。参加过反对袁世凯的斗争。一九二七年后担任浙江兴业银行董事。抗日战争时期，支持抗日救亡活动。抗战胜利后，参加上海各界人民团体联合会，从事反蒋民主活动。中华人民共和国成立后，历任全国人民代表大会常务委员会副委员长、中国人民政治协商会议全国委员会副主席、中华全国工商业联合会主任委员等职。--第１４２、３９１、４３４、４４３页。

　　２７９　伪宪法　指蒋介石撕毁政协决议、发动全面内战后，在一九四六年十一月非法召开的"国民大会"上通过的反共反人民的《中华民国宪法》。--第１４２页。

　　２８０　一九四九年九月二十九日中国人民政治协商会议第一届全体会议通过的《中国人民政治协商会议共同纲领》。《共同纲领》确定了当时我国在政治、军事、经济、文化教育、民族、外交等各方面的基本政策。它是在中国共产党领导下，各民主党派、各人民团体和各族各界人民的代表共同制定的建国纲领，是全国人民在一定时期内共同的奋斗目标和统一行动的政治基础，在我国正式颁布宪法，以前起过临时宪法的作用。--第１４４、１５４、１６１、１８２、２２８、２３４、２５８页。

　　２８１　新政治协商会议　即中国人民政治协商会议。一九四八年四月三十日中共中央发布的纪念"五一"劳动节口号中，号召"各民主党派、各人民团体、各社会贤达迅速召开政治协商会议，讨论并实现召集人民代表大会，成立民主联合政府"。这里提出的政治协商会议，当时被称为"新政协"，以区别于一九四六年一月国民党召开的那次政治协商会议。一九四九年九月中国人民政治协商会议举行第一届全体会议，代行全国人民代表大会的职权，制定了《中国人民政治协商会议组织法》、《中国人民政治协商会议共同纲领》、《中华人民共和国中央人民政府组织法》，选举了以毛泽东主席为首的中央人民政府委员会，宣告了中华人民共和国的成立。一九五四年九月召开第一届全国人民代表大会第一次会议之后，中国人民政治协商会议不再代行全国人民代表大会的职权，但仍然是在中国共产党领导下，团结全国各民族、各民主党派、各人民团体、国外华侨和其他爱国民主人士的人民民主统一战线组织。--第１４４页。

　　２８２　三次反共高潮指一九三九年至一九四三年国民党蒋介石连续发动的三次反共高潮。第一次是在一九三九年冬季至一九四○年春季，那时国民党军队侵占了陕甘宁边区的宁县、镇原等县城；阎锡山发动了十二月事变，进攻决死队等山西新军；石友三、朱怀冰等部进攻冀南和太行抗日根据地的八路军。第二次是在一九四○年秋季至一九四一年春季，在这期间，国民党军七、八万人包围袭击了从皖南北移的新四军部队，制造了震惊中外的皖南事变。第三次是从一九四三年春季至秋季，蒋介石发表了反共反人民的《中国之命运》一书，又乘共产国际解散之机，指使特务假冒民众团体，叫嚣"解散共产党"、"取消陕北特区"，调集大量河防部队准备闪击陕甘宁边区。中国共产党及其领导的军队有力地打退了这三次反共高潮，克服了当时的危机。--第１４５页。

　　２８３　杨杰（一八八八--一九四九），国民党爱国将领。解放战争期间参加反内战、反独裁活动。一九四九年应邀参加中国人民政治协商会议第一届全体会议，九月十九日由云南赴北平途中，在香港被国民党特务暗杀。--第１４７页。

　　２８４　这里指的是消灭剥削阶级。一九三六年十一月，斯大林在全苏苏维埃第八次非常代表大会上所做的《关于苏联宪法草案》的报告中指出："地主阶级已因国内战争胜利结束而完全消灭了。其它剥削阶级也遭到了与地主阶级同样的命运。在工业方面已经没有资本家阶级了。在农业方面已经没有富农阶级了。......因而，所有的剥削阶级都被消灭了。"--第１４７页。

　　２８５　新民主主义五种经济，指社会主义的国营经济、私人资本主义经济、农民和手工业者的个体经济、半社会主义性质的合作社经济、国家与私人合作的国家资本主义经济。--第１４８、２３０页。

　　２８６　青年党　是中国青年党的简称，其成员是一些地主、资本家、政客和知识分子。一九二三年在法国成立，公开名称是中国国家主义青年团，一九二九年改用中国青年党名义进行活动，鼓吹国家主义，反对共产主义。抗日战争期间曾参加中国民主同盟，后又依附国民党，参加了一九四六年十一月国民党包办的"国民大会"。一九四九年随国民党去台湾省。--第１５１页。

　　２８７　民、青两党指民社党、青年党。民社党是中国民主社会党的简称。一九四六年由国家社会党与民主宪政党合并组成。其主要成员是地主、资产阶级的代表人物。一九四六年十一月参加了国民党包办的"国民大会"，一九四九年五月在香港召开常务委员会议，宣布继续追随国民党，同年随国民党去台湾省。--第１５１页。

　　２８８　张君劢（一八八七--一九六九），江苏宝山（今属上海市）人。曾任燕京大学、中山大学教授。一九三三年发起成立国家社会党，鼓吹"国家社会主义"，主张改良，反对革命。一九四一年以组织调解国共两党关系的党派为名，加入中国民主政团同盟。一九四六年将国家社会党与民主宪政党合并为中国民主社会党，公开投靠蒋介石，参加了非法的分裂的"国民大会"，被民盟开除盟籍。后任中国民主社会党主席。一九四九年去澳门，一九六九年死于美国旧金山。--第１５１页。

　　２８９　政学系是北洋军阀统治时期形成的政治集团。其成员由一部分进步党人和国民党人所组成。一九一六年袁世凯死后，这个集团勾结南北军阀，反对孙中山。一九二七年南京国民党政府成立，该系积极追随蒋介石，从事反革命活动，成为国民党内的一个反动派系。--第１５１页。

　　２９０　左舜生（一八九三--一九六九），湖南长沙人。曾参加少年中国学会，是中国青年党发起人和主要负责人之一。一九三五年至一九三八年曾在国民党中央政治学校任教。一九四六年参加国民党一手操纵的"国民大会"。一九四七年任国民党政府农林部部长。一九四九年去香港。--第１５１、２１２页。

　　２９１　救国会，全称中国人民救国会。前身为全国各界救国联合会，成立于一九三六年五月。一九四一年参加中国民主政团同盟，是民主同盟内部的进步力量。主要负责人为沈钧儒、邹韬奋等。抗日战争胜利后，改称中国人民救国会，致力民主和平爱国运动。中华人民共和国成立后，该会于１９４９年１２月１８日宣告结束。--第１５１页。

　　２９２　闻一多（一八九九--一九四六），湖北浠水人。爱国民主人士。曾任清华大学、西南联合大学教授。抗日战争期间，痛恨国民党政府的独裁和腐败，积极参加争取民主的斗争。一九四五年任中国民主同盟中央委员。一九四六年七月十五日在昆明被国民党特务暗杀。--第１５１、１５２页。

　　２９３　梁漱溟，一八九三年生，广西桂林人。一九四一年参与组织中国民主政团同盟（后改称中国民主同盟），任中央委员、秘书长。抗日战争初期，提倡过"一多相容，透明政权"的政治主张，宣扬政府不能带有党派色彩，应当成为超阶级的"无色透明体"。解放战争时期，在国共谈判中，他以民盟代表的身份参加调解。中华人民共和国成立后，任中国人民政治协商会议全国委员会委员、常务委员。--第１５２、２１７、３３７页。

　　２９４　表方　即张澜（一八七二--一九五五），四川南充人。一九四一年参加组织中国民主政团同盟，被推为主席。一九四四年中国民主政团同盟改为中国民主同盟，长期担任主席。中华人民共和国成立后，曾任中央人民政府副主席、全国人民代表大会常务委员会副委员长。--第１５２页。

　　２９５　李公朴（一九○○--一九四六），原籍江苏扬州，生于镇江。爱国民主人士。一九三一年九一八事变后积极参加抗日救国运动和群众文化教育工作。一九三六年参加全国各界救国联合会，被推为负责人之一。同年十一月与沈钧儒等一起被国民党反动派逮捕，抗战开始后获释。一九四五年任中国民主同盟中央委员。一九四六年七月十一日在昆明被国民党特务暗杀。--第１５２页。

　　２９６　张申府，一八九三年生，河北献县人。一九二○年去法国、德国留学。一九二一年加入中国共产党。一九二五年脱离共产党。一九四三年加入中国民主政团同盟（后改称中国民主同盟），任常务委员。一九四七年十月国民党政府宣布民主同盟为"非法团体"，同年十一月八日，张申府以个人名义登报声明解散民盟华北总支部和华北各地民盟组织。一九四八年十月二十三日，张又发表《呼吁和平》一文，主张用"协议恢复和平"。中华人民共和国成立后，任北京图书馆研究员、中国人民政治协商会议第五届、第六届全国委员会委员。--第１５３、４１１页。

　　２９７　章伯钧（一八九五--一九六九），安徽桐城人。抗日战争期间，曾任国民参政会参政员，并于一九四一年参与组织中国民主政团同盟（后改称中国民主同盟）。一九四九年出席中国人民政治协商会议第一届全体会议。中华人民共和国成立后，曾任中央人民政府委员、交通部部长、中国人民政治协商会议全国委员会副主席、中国农工民主党主席、中国民主同盟中央副主席等职。--第１５３页。

　　２９８　建国初期，我们党从我国一些基本上是全民族信教的少数民族聚居地区的实际情况出发，对于要求入党、而又一时不愿放弃宗教信仰的人，只要其他方面已够入党条件，便允许吸收入党。在入党以后，再从教育和革命实践中帮助他们逐步清除宗教信仰和宗教感情。随着我国社会情况的发展变化，一九八二年中央进一步明确规定："共产党员不得信仰宗教，不得参加宗教活动，长期坚持不改的要劝其退党。"同时指出"在那些基本上是全民族信教的少数民族当中，这项规定的执行，需要按照实际情况，采取适当步骤，不宜简单从事。"但是，"在新发展党员时，必须注意严格掌握，凡属笃信宗教和有浓厚宗教感情的，不勉强吸收。"--第１６４页。

　　２９９　劳协即中国劳动协会，一九三五年二月成立。一九四八年八月，以朱学范为首的劳协成员代表劳协参加中国第六次劳动大会，宣布劳协作为团体会员参加中华全国总工会。一九四九年十一月劳协召开代表会议，通过决议结束劳协组织活动，其工作人员和部分会员参加中华全国总工会所属组织。--第１７３页。

　　３００　陈云，一九○五年生，上海青浦人。中华人民共和国成立后，任中央人民政府委员、政务院副总理兼财政经济委员会主任，主持全国的财政经济工作。一九五○年六月任中共中央书记处书记。一九五四年任国务院副总理。先后兼任过商业部部长、国家基本建设委员会主任。--第１７５、２２７、２３７、２６８页。

　　３０１　民进即中国民主促进会。一九四五年成立，主要由从事爱国民主运动的文教界知识分子组成。一九四八年响应中国共产党提出的召开新政治协商会议的号召，一九四九年九月参加中国人民政治协商会议。中华人民共和国成立后，拥护中国共产党的领导，是参加社会主义革命和社会主义建设的民主党派之一。--第１７９、３４９页。

　　３０２　职教社　即中华职业教育社，一九一七年黄炎培等发起创立，是倡导和从事职业教育的人民团体。新中国成立后，继续从事职业教育，为社会主义建设培养人才。--第１７９、３５６页。

　　３０３　马丁·路德（一四八三--一五四六），德国人。曾任德国维登堡大学神学教授，是十六世纪宗教改革运动的发起者，基督教新教路德宗的创始人。一五一七年发表《九十五条论纲》，抨击教皇出售赎罪券，以后又多次发表论说，否定教皇权威，主张建立没有教阶制度、没有繁缛仪式、适合市民阶级要求的廉俭教会。他的改革主张，反映了德国正在形成中的资产阶级的需要，在宗教改革初期，起了一定的积极作用。--第１８０页。

　　３０４　非宗教大同盟是一九二二年三月在北京成立的反帝爱国群众组织。其起因是，世界基督教学生同盟定于这年四月在北京召开第十一届年会，讨论所谓资本主义在中国发展问题。这一消息激起北京知识界的强烈反对，遂于同年三月纷纷举行集会，联名发表宣言和通电，揭露帝国主义的侵略罪行，并成立非宗教大同盟组织与之相对抗。这一反帝爱国斗争，在全国各地引起极大的反响，许多城市成立了非宗教大同盟组织，有的还出版非基督教刊物，开展宣传活动，揭露帝国主义者利用宗教对中国进行文化侵略的罪行。--第１８０页。

　　３０５　刘良模，一九○九年生，浙江镇海人。一九四○年赴美留学，一九四九年八月应周恩来邀请回国作为宗教界民主人士代表，参加中国人民政治协商会议。一九五○年五月出席周恩来总理主持的基督教问题座谈会，曾协助吴耀宗起草中国基督教革新宣言，并参与发起中国基督教三自爱国运动。当时任中华基督教青年会全国协会事工组主任。--第１８６页。

　　３０６　犹大是圣经故事中的人物。原为耶稣十二门徒之一，常列于十二门徒名字末尾。后以三十块银币将耶稣出卖给犹太教当权者，并为拘捕耶稣带路。西方常用犹大作为叛徒的代称。--第１８６、２０２页。

　　３０７　喜饶嘉错（一八八四--一九六八），青海循化人。藏族，佛教界学者。曾获"格西"（博士）学位。中华人民共和国成立后，任全国人民代表大会代表，中国人民政治协商会议全国委员会常务委员、青海省副省长、中国佛教协会会长。--第１９３、３２６页。

　　３０８　解放初期，上海、天津等地投机资本家利用国家经济困难，多次掀起金银、外币的涨风，银元价格在很短的时期内成倍上涨。银元暴涨引起了整个物价的上涨。投机资本的猖獗活动严重地威胁着广大人民生活和社会经济的稳定。人民政府于一九四九年六月至一九五○年初，连续不断地对扰乱金融，坚持违法活动的首要投机分子，依法予＃Ｂ５０４＃以惩处。同时，人民政府公布了关于金银、外币的管理法令，并决定统一全国财政收支、统一全国物资调度、统一全国现金管理。这一系列的经济斗争和行政管理，有力打击了投机势力，使金融物价趋于稳定。--第１９４页。

　　３０９　土地改革，简称土改，这里指中华人民共和国成立后，中国共产党领导广大农民废除封建的土地所有制，实现农民的土地所有制的革命运动。一九五○年六月，中央人民政府颁布《中华人民共和国土地改革法》，同年冬起，在新解放区陆续开展了土地改革运动。到一九五二年冬，除台湾省和一部分少数民族地区以外，全国的土地改革基本结束，使三亿无地或少地的农民分得了约七亿亩土地和其他生产资料。--第１９６、２００、２１３、２２２、２７７、３８１页。

　　３１０　一九五○年六月二十五日朝鲜内战爆发后，美帝国主义发动侵朝战争，同时派军队侵略我国领土台湾。九月十五日又打着联合国军的旗号，派兵在朝鲜西海岸仁川登陆，随后越过"三八线"大举北犯，并且轰炸、扫射中国东北边境城市和村庄，严重威胁中国的安全。为了援助朝鲜人民的抗美救国战争、保卫刚刚诞生的新中国，中国人民响应毛泽东主席发出的抗美援朝、保家卫国的号召，组织了以彭德怀为司令员兼政治委员的中国人民志愿军，开赴朝鲜前线同朝鲜人民军并肩作战，抗击美国侵略军。十一月四日，中国各民主党派发表联合宣言，坚决支持志愿军的正义行动。全国人民以增产节约、报名参加志愿军、捐献武器等各种方式全力支援朝鲜前线的作战。在中朝人民军队的沉重打击下，美帝国主义连遭失败，被迫于一九五三年七月二十七日在朝鲜停战协定上签字。至此，朝鲜停战实现，中国人民的抗美援朝战争取得了伟大胜利。--第１９９、２２２、２４０、２５４、２７８页。

　　３１１　镇压反革命指一九五○年至一九五三年在全国开展的镇压反革命运动。中华人民共和国成立初期，全国各地残存着大量的土匪、恶霸、特务、反动党团骨干和反动会道门头子等反革命分子。他们进行各种破坏活动，危害人民的革命和建设事业。为了迅速建立和巩固革命秩序，根据中共中央《关于镇压反革命活动的指示》和中央人民政府公布的《中华人民共和国惩治反革命条例》，全国开展了镇压反革命运动。这次运动沉重打击了反革命残余势力，巩固了人民民主专政。--第２００、２２２、２７８页。

　　３１２　梵蒂冈，罗马教廷所在地，在罗马城西北角，面积零点四四平方公里，属梵蒂冈国籍的居民七百二十六人（一九七六年）。境内有圣彼得大教堂和梵蒂冈宫等宫院建筑，藏有中世纪和文艺复兴时代以来的著名文物和艺术作品。这里原为中世纪教皇国的中心，一八七○年教皇国的领土并入意大利王国后，教皇退居到这里；一九二九年同意大利的墨索里尼政府签订《拉特兰条约》后成为独立的国家，同许多国家有外交关系。--第２０１页。

　　３１３　于斌（一九○一--一九七八），黑龙江兰西人。早年入罗马传信大学留学，回国后任北平中国公教进行会总监督、中国公教学校视察主任等职。一九四六年任天主教南京区总主教、国民党一手操纵的"国民大会"代表。全国解放时去台湾，后去美国，一九七八年死于罗马。--第２０２页。

　　３１４　农工民主党，参见本书注〔１４９〕。--第２０５页。

　　３１５　一九五一年九月起，北京、天津各高等学校的教师进行了有系统的思想改造的学习运动。为了统一领导这一运动，教育部成立了京津高等学校教师学习委员会，北京大学教师学习会是这个学习委员会的分会。--第２０８页。

　　３１６　章太炎　即章炳麟（一八六九--一九三六），浙江余杭人。早年参加戊戌维新运动，一九○四年和蔡元培等发起成立光复会，一九○六年加入同盟会。辛亥革命前，先后在《苏报》、《国粹学报》、《民报》等报刊上发表文章，宣传革命思想，公开提出推翻清朝统治。--第２１１页。

　　３１７　《国粹学报》是一九○四年成立的学术团体国学保存会的机关刊物，一九○五年二月在上海创刊。它以"发明国学，保存国粹"、"爱国保种，存学救世"为宗旨，是一个既阐发民族学术传统、宣传反清思想但有复古主义倾向的刊物。一九一一年武昌起义后停刊。--第２１１页。

　　３１８　指一九一八年五月段祺瑞政府与日本政府在北京先后秘密签订的中日《陆军共同防敌军事协定》和《海军共同防敌军事协定》。协定以"共同防敌"为由，保证日本军队可以在共同进行反苏战争的名义下进入中国境内，并支配中国的有关军队。--第２１２页。

　　３１９　国家主义是以抽象的国家概念来掩盖国家的阶级本质的一种资产阶级思想。于十九世纪开始在欧洲流行。它标榜"国家至上"，主张放弃阶级斗争，效忠于剥削阶级的国家；有些国家主义者还鼓吹"民族优越论"，制造民族间的矛盾对立，并用保卫祖国的名义鼓动侵略战争。二十世纪二十年代，中国的一些大地主大资产阶级的政治代表，组织了奉行国家主义的中国青年党，进行反对共产党和反对苏联的活动。--第２１２页。

　　３２０　少年中国学会是"五四"时期建立的一个社团。由李大钊、王光祈等人发起，一九一九年七月在北京正式成立。这个学会兼容了共产主义知识分子、小资产阶级知识分子和资产阶级知识分子。出版刊物有《少年中国》、《少年世界》等。由于会员思想的分化日趋明显，一九二五年底停止活动。--第２１２页。

　　３２１　曾琦（一八九二--一九五一），四川隆昌人。一九一八年参加发起筹组少年中国学会。一九二三年在法国留学期间与李璜等建立中国青年党。一九二四年回国，创办《醒狮》周报，鼓吹国家主义。一九二六年任中国青年党中央执行委员会委员长，一九四五年任该党主席。解放战争时期参加国民党一手操纵的"国民大会"，并任国民党政府委员、总统府资政等职。--第２１２页。

　　３２２　李璜，一八九五年生，四川成都人。曾参加少年中国学会。一九二三年在法国留学期间与曾琦等建立中国青年党。一九二六年任该党中央执行委员，一九四八年任该党代理主席。--第２１２页。

　　３２３　基马尔（一八八一--一九三八）是土耳其民族商业资产阶级的代表人物。一九一九年起领导土耳其的民族解放运动和资产阶级民主革命。一九二三年土耳其共和国成立后，当选为第一任总统。基马尔主义是以基马尔为代表的、主张在半殖民地半封建的国家建立资产阶级专政的思潮。中国一些资产阶级分子在一九二七年革命失败后曾高唱基马尔主义，企图在中国建立资产阶级专政的国家。--第２１３页。

　　３２４　洪秀全（一八一四--一八六四），广东花县人。十九世纪中叶太平天国农民革命运动的领袖。一八五一年，他和冯云山等领导群众在广西桂平县的金田村起义，建号太平天国，同清朝的封建统治坚持斗争十四年之久。--第２１３、３５９页。

　　３２５　严复（一八五四--一九二一），福建闽侯人。曾在英国海军学校留学。一八九四年中日战争后，主张君主立宪，变法维新。曾译赫胥黎 《天演论》、亚当·斯密《原富》、穆勒《名学》和孟德斯鸠《法意》等书，传播了欧洲资产阶级的思想。--第２１３页。

　　３２６　康有为（一八五八--一九二七），广东南海人。一八九五年中国在甲午战争中被日本帝国主义打败后，他联合一千三百多个在北京参加科举考试的举人联名向光绪皇帝上"万言书"，要求"变法维新"。他主张改君主专制制度为君主立宪制度。一八九八年光绪皇帝任用他和谭嗣同、梁启超等人参预政事，试图变法。后来顽固派的代表慈禧太后重揽政权，维新运动遂告失败。康、梁逃亡海外，组织保皇会，和孙中山所代表的资产阶级、小资产阶级的革命派相对立，成为反动的政治派别。康有为的著作有《新学伪经考》、《孔子改制考》、《大同书》等书。--第２１３页。

　　３２７　法国大革命指一七八九年至一七九四年法国推翻封建专制制度、确立资本主义制度的资产阶级革命。它是各国资产阶级革命中一次规模最大、最彻底的革命。--第２１３、２２３页。

　　３２８　明治是日本天皇睦仁的年号。明治维新是从一八六八年起在日本明治年间发生的资产阶级性质的改革运动。这次改革虽未彻底消灭封建制度，但废除了封建割据的幕府制度，建立了统一的中央集权国家，并通过一系列措施发展资本主义，使日本很快成为资本主义国家。--第２１３页。

　　３２９　胡乔木，一九一二年生，江苏盐城人。当时任毛泽东的秘书。--第２１４页。

　　３３０　翁文灏（一八八九--一九七一），浙江鄞县人。地质学家。一九四八年曾任国民党政府行政院院长。不久辞职赴法。一九五一年回国，后任中国人民政治协商会议全国委员会委员、中国国民党革命委员会中央委员会常务委员。--第２２０、２６１、４１２页。

　　３３１　王芸生（一九○一--一九八○），河北静海人。曾任天津《商报》总编辑、上海《大公报》总编辑等职。中华人民共和国成立后，任中国人民政治协商会议全国委员会常务委员、中华全国新闻工作者协会副主席。一九五二年二月九日在上海《大公报》上发表了《资产阶级有没有猖狂进攻？是我们"制造阶级斗争"吗？》一文。此文经毛泽东作了个别修改后，同年二月十三日为《人民日报》转载。--第２２２页。

　　３３２　文艺复兴是十四世纪至十六世纪欧洲部分国家在资本主义生产关系逐渐形成的条件下，思想和文化范围内发生的反映新兴资产阶级利益和要求的大变革。十六世纪资产阶级史学家认为它是古代希腊、罗马文化艺术的复兴，所以称为"文艺复兴"。这个时期表现在科学、哲学、文学、艺术、教育方面的人文主义思想，提倡人性，反对神性；提倡人权，反对神权；提倡个性自由，反对中古的宗教桎梏，冲击了腐朽的封建文化，在当时历史上起了很大的进步作用。文艺复兴为近代文学、艺术、教育、哲学和实验科学的发展开辟了道路。--第２２３、４０８页。

　　３３３　美国独立战争也称北美独立战争。一七七五年起北美十三个殖民地的人民先后进行推翻英国殖民统治、争取独立的资产阶级革命战争。一七七六年七月四日发表了《独立宣言》，正式宣告脱离英国。英国战败后，被迫在一七八三年签订《巴黎和约》，承认美国独立。--第２２３页。

　　３３４　美国南北战争也称美国内战，是一八六一年至一八六五年由美国南部种植园主奴隶制与北部资产阶级雇佣劳动制之间的矛盾所引起的资产阶级民主革命战争。在战争过程中，代表北部资产阶级利益的联邦政府总统林肯颁布了《宅地法》和《解放黑奴宣言》，并采取其他民主措施，激发了工人、农民和黑人的革命斗志，因而联邦政府取得了战争的胜利。经过这次战争，进一步促进了美国资本主义的发展。--第２２３页。

　　３３５　人民代表会议即地方各界人民代表会议，是解放初期人民参政的一种形式。在地方各级人民代表大会召开之前，它曾代行人民代表大会的职权。--第２２５页。

　　３３６　"五反"指一九五二年在全国资本主义工商业中开展的反对行贿、反对偷税漏税、反对盗骗国家财产、反对偷工减料和反对盗窃经济情报的斗争。--第２２６、２３４、２６４、２７８、３５４页。

　　３３７　"五毒"指中华人民共和国成立初期一些资本家的行贿、偷税漏税、盗骗国家财产、偷工减料和盗窃经济情报的五种违法行为。--第２２６、２３５、２４９页。

　　３３８　一九五二年一月五日，周恩来在中国人民政治协商会议全国委员会常务委员会第三十四次会议上报告了正在全国范围内开展的反对贪污、反对浪费，反对官僚主义斗争和思想改造运动的情况，号召工商界人士积极参加这一运动，进行自我改造。一月八日的《人民日报》摘要报道了周恩来这次讲话的内容。--第２２６页。

　　３３９　"三反"指一九五一年底至一九五二年十月在国家机关、部队和国营企业等单位中开展的反对贪污、反对浪费、反对官僚主义的斗争。--第２２７、２３４、２６４、２７８、３５４页。

　　３４０　这是唐代初期政治家魏征说过的话，见《资治通鉴·唐太宗贞观二年》："兼听则明，偏信则暗。"毛泽东在《矛盾论》等著作中，曾多次引用过这句话。--第２３３页。

　　３４１　施复亮（一八九九--一九七○），浙江金华人。当时任劳动部副部长、中国民主建国会副主任委员、全国工商联常务委员。--第２３７页。

　　３４２　资方的三权指资本家的财产权、经营管理权、人事调配权。--第２３７页。

　　３４３　郑介民（一八九八--一九五九），广东文昌人。曾任蒋介石侍从副官，国民党特务机关军事委员会调查统计局主任秘书、局长，国民党国防部政务次长。一九四九年去台湾，任国民党国家安全局局长。--第２４１页。

　　３４４　余心清（一八九八--一九六六），安徽合肥人。早年任冯玉祥部开封训政学院院长，民众抗日同盟军政训处处长，保定绥靖公署设计委员会副主任等职。一九四七年，因联络美国领事馆，策动国民党第十一战区司令孙连仲搞反蒋兵变，遭到国民党反动派逮捕。一九四九年获释。中华人民共和国成立后，曾任全国人民代表大会常务委员会副秘书长，中央人民政府办公厅副主任，国家民族事务委员会副主任，中国国民党革命委员会中央常务委员。--第２４１页。

　　３４５　孙连仲，一八九一年生，河北雄县人。曾任冯玉祥部旅长、师长。一九四五年至一九四七年任国民党第十一战区司令长官兼河北省主席。一九四八年任南京卫戍总司令，后任总统府参军长。一九四九年去台湾。--第２４１页。

　　３４６　顾顺章，上海人。一九二七年参加上海工人武装起义，任武装纠察队队长。党的第五次全国代表大会上当选为中央委员。一九三○年党 的六届三中全会上当选为中央政治局候补委员。一九三一年被捕叛变，一九三五年被国民党处决。--第２４１页。

　　３４７　张东荪（一八八六--一九七三），浙江杭州人。曾任燕京大学教授、民盟中央委员、民盟总部秘书长等职。解放战争后期充当美特机关情报人员，一九五一年六月被破获。随后，撤销了他的中央人民政府委员、中国人民政治协商会议全国委员会委员、民盟中央常务委员等职务。--第２４２页。

　　３４８　头山满（一八五五--一九四四），日本福冈人。玄洋社首领之一。明治初年参加不平土族的反政府运动。一八八一年与平冈浩太郎等创立玄洋社，标榜"大亚细亚主义"，极力策动政府侵略中国和朝鲜。他不仅在玄洋社、黑龙会、大日本生产党等右翼团体中拥有势力，而且在政界、财界和军界也有影响。--第２４２页。

　　３４９　新"三反"运动是继"三反"、"五反"运动之后，一九五三年在全国范围内和各级机关中开展的反对官僚主义、反对命令主义和反对违法乱纪的斗争。--第２４６页。

　　３５０　荣毅仁，一九一六年生，江苏无锡人。当时任申新纺织公司管理处总经理、华东军政委员会财经委员会委员、上海市副市长、上海市工商联副主任委员。--第２５７页。

　　３５１　十一个党派指中国共产党、中国国民党革命委员会、中国民主同盟、中国民主建国会、无党派民主人士、中国民主促进会、中国农工民主党、中国致公党、九三学社、台湾民主自治同盟、中国新民主主义青年团。--第２６０页。

　　３５２　十七个团体指中华全国总工会、农民、中华全国民主妇女联合会、中华全国民主青年联合会、合作社、中华全国工商业联合会、中国文学艺术界联合会、自然科学团体、社会科学团体、教育界、新闻出版界、医药卫生界、对外和平友好团体、社会救济福利团体、少数民族、华侨、宗教界。--第２６０页。

　　３５３　泥人张即张景祜（一八九二--一九六七），天津人。出身泥人世家，九岁学艺做泥人。擅长《红楼梦》、《水浒》人物泥塑。中华人民共和国成立后，在中央工艺美术学院研究室工作，曾任中国人民政治协商会议全国委员会委员，中国美术家协会会员。--第２６２页。

　　３５４　指陈云同志于一九五五年十一月十六日在中共中央召开的各省、市、自治区党委代表会议上做的题为《资本主义工商业改造的新形势和新任务》的报告，见《陈云文选》（一九四九--一九五六）人民出版社１９８４年版第２８０-２９２页。--第２６３页。

　　３５５　指陈云同志一九五五年十一月十六日在中共中央召开的各省、市、自治区党委代表会议上的报告中，就资本主义工商业社会主义改造问题提出的六点意见：第一，要对各行各业的生产进行全国范围的统筹安排；第二，各个行业内部，必须有或大或小的改组；第三，实行全行业的公私合营；第四，应该推广定息的办法；第五，组织专业公司；第六，全面规划，加强领导。--第２６３页。

　　３５６　定息　是我国在资本主义工商业实行全行业公私合营后，对民族资本家的生产资料进行赎买的一种形式，即不论企业盈亏，统一由国家每年按照资本额发给资本家固定的利息（一般是年息百分之五）。定息从一九五六年起支付，后来在一九六六年九月停止支付。一九五六年社会主义改造高潮期间，经过清产核资，参加公私合营的私营工商业者的全部资金约为二十四亿元，国家每年付出的定息为一亿二千万元。若给救济款，则要数亿元。--第２６７、４１４、４４２页。

　　３５７　参见恩格斯《法德农民问题》（《马克思恩格斯全集》第２２卷，人民出版社１９６５年版第５８５页）。--第２６７页。

　　３５８　一九五六年到一九六七年全国农业发展纲要草案是中共中央根据毛泽东的倡议提出的，一九五六年一月公布。一九五七年十月公布修正草案。一九六○年四月经第二届全国人民代表大会第二次会议通过并作为正式文件颁发。纲要全文共四十条，提出了我国农业、畜牧业、林业、渔业、副业以及农村商业、信贷、交通、邮电、广播、科学、文化、教育、卫生等方面的发展规划。关于粮食每亩平均年产量，纲要规定从一九五六年开始，在十二年内，在黄河、秦岭、白龙江、黄河（青海境内）以北地区，要达到四百斤；黄河以南、淮河以北地区，要达到五百斤；淮河、秦岭、白龙江以南地区，要达到八百斤。--第２７５页。

　　３５９　即毛泽东《大量吸收知识分子》一文（《毛泽东选集》第２卷，人民出版社１９６４年版，第５８１-５８３页）。--第２７７页。

　　３６０　胡风，一九○二年生，湖北蕲春人。文艺理论家和诗人。一九三三年七月在上海参加中国左翼作家联盟。中华人民共和国成立后，曾任中国作家协会理事、中国文联全国委员会委员等职。一九五五年胡风等人被错定为胡风反革命集团。一九八○年九月，中共中央发出通知并经过法律程序，为"胡风反革命集团"和胡风本人平反。一九八一年胡风任中国人民政治协商会议全国委员会常务委员、中国作家协会顾问等职。--第２７８页。

　　３６１　布尔加宁（一八九五--一九七五），当时任苏联部长会议主席。文中引的是一九五五年七月四日他在苏联共产党中央委员会全体会议上所做《关于在工业的进一步高涨、技术的进步和生产组织的改进方面的任务》的报告中说的一段话。--第２９８页。

　　３６２　见毛泽东《中国人民站起来了》（《毛泽东选集》第５卷，人民出版社１９７７年版，第６页）。--第３０７页。

　　３６３　万隆，印度尼西亚城市。一九五五年四月十八日至二十四日，曾在这里举行亚非会议，周恩来率中华人民共和国代表团出席了这次会议，并在会上做了重要发言。--第３１０页。

　　３６４　亚非会议也称万隆会议，一九五五年四月十八日至二十四日在印度尼西亚万隆举行。参加会议的有缅甸、锡兰（今斯里兰卡）、印度、印度尼西亚和巴基斯坦五个发起国，以及阿富汗、柬埔寨、中华人民共和国、埃及等二十九个亚非国家。会议广泛讨论了民族主权、反殖民主义斗争、世界和平以及与会国之间的经济、文化合作等问题，发表了《亚非会议最后公报》，提出了著名的关于促进世界和平与合作的十项原则。--第３１１页。

　　３６５　杜勒斯（一八八八--一九五九），美国共和党人。当时任美国国务卿。--第３１２页。

　　３６６　开斋节，伊斯兰教主要节日之一。中国新疆地区称为"肉孜节"。该教规定教徒每年在伊斯兰教历太阴年九月斋戒一个月，叫做"斋月"。斋戒期满，十月一日为开斋节。每逢此日，教徒们沐浴盛装，举行会礼，相互祝贺。--第３１２页。

　　３６７　指一九五六年一月三十日周恩来在《中国人民政治协商会议第二届全国委员会常务委员会工作报告》中提出的"为争取和平解放台湾，实现祖国的完全统一而奋斗"的号召。他代表中国人民和中国政府宣布："凡是愿意回到大陆省亲会友的，都可以回到大陆上来。凡是愿意到大陆来参观和学习的，也都可以到大陆上来。凡是愿意走和平解放台湾道路的，不管任何人，也不管他们过去犯过多大罪过，中国人民都将宽大对待，不究既往。凡是在和平解放台湾这个行动中立了功的，中国人民都将按照立功大小给以应得的奖励。凡是通过和平途径投向祖国的，中国人民都将在工作上给以适当的安置。"--第３１９页。

　　３６８　指中国和美国一九五五年八月开始在瑞士日内瓦举行的大使级会谈。双方商定会谈包括两项议程：一是双方平民回国问题；二是双方有争执的其他实际问题。前项议程在同年九月十日达成协议，后项议程一直没有达成任何协议。一九五八年九月至一九七○年二月，中美大使级会谈改在波兰首都华沙举行。--第３１９页。

　　３６９　桑吉悦希即天宝，一九一六年生，四川阿坝人。藏族。当时任四川省副省长兼中共康定地委第一书记。--第３２５页。

　　３７０　陈赓（一九○三--一九六一），湖南湘乡人。当时任中国人民解放军副总参谋长。--第３２７页。

　　３７１　指三国时期蜀国丞相诸葛亮七次俘捉孟获，又七次将他放回的故事。孟获是当时蜀汉南中地区的少数民族首领，公元二二三年起兵反蜀，数次为诸葛亮所败。为争取孟获，诸葛亮曾经捉住他后，又将他放走，允许再战。这样几捉几放，反复至七次，终于使孟获信服，率众归附蜀汉政权。--第３２７页。

　　３７２　项谦（一九一三--一九五九），青海尖扎人。藏族。原贵德县昂拉藏族部落千户。一九五一年秋聚众叛乱。为了加强民族团结，青海省人民政府遵照中央指示，对其采取了反复说服、争取来归的方针。在人民政府正确政策的感召下，项谦于一九五二年七月放下武器，归向人民。以后曾任尖扎县县长、黄南藏族自治州副州长、青海省政协常委等职。--第３２８页。

　　３７３　和平共处五项原则即互相尊重主权和领土完整，互不侵犯、互不干涉内政、平等互利、和平共处。一九五三年十二月至一九五四年四月，中国政府代表团和印度政府代表团就两国在中国西藏地方的关系问题在北京举行谈判。这五项原则是周恩来总理在谈判开始时同印度政府代表团的谈话中提出的，后正式写入双方达成的《关于中国西藏地方和印度之间的通商和交通协定》的序言中。由于一九五四年六月在中印、中缅两国总理的联合声明中，以及此后的许多国际性文件中都采用了和平共处五项原则的提法，这个提法已在世界上得到广泛的承认和使用。--第３２９页。

　　３７４　邹容（一八八五--一九○五），原名绍陶，字蔚丹，四川巴县人。清末革命家。一九○二年留学日本，参加中国留日学生爱国运动。一九○三年回到上海，出版《革命军》，风行全国。书中揭露清政府腐败和卖国，号召民众起来推翻清王朝封建专制统治，建立中华共和国。清政府勾结帝国主义于同年七月将他监禁，一九○五年死于狱中。--第３３６页。

　　３７５　耶律楚材（一一九○--一二四四），契丹族，辽皇族子孙，后为成吉思汗、窝阔台汗时期大臣。深受成吉思汗信任。窝阔台汗（太宗）即位后，他劝亲王察合台（太宗兄）行君臣礼，以尊君权。建议军民分治，使州郡长吏专理民事，万户府总军政。反对以汉地为牧场之说，建立赋税制度。立十路征收课税使，专掌钱谷。破金汴京时废除屠城制。奏封孔子后裔袭爵衍圣公，设立经籍所、编修所，渐兴文教。一二三七年以守成必用文臣为理由，开科取士，释放被俘为奴的汉族儒人。他在成吉思汗、窝阔台汗时期任事近三十年，官至中书令，元代立国规模多由其奠定，对元代社会经济的发展起过积极作用。--第３３８页。

　　３７６　康熙指清圣祖爱新觉罗玄烨，清朝第二代皇帝，一六六二--一七二二年在位。--第３３８页。

　　３７７　乾隆　指清高宗爱新觉罗弘历，清朝第四代皇帝，一七三六--一七九五年在位。--第３３８页。

　　３７８　指一九五一年中央人民政府全权代表与西藏地方政府全权代表经过多次谈判后于同年五月二十三日签订的《中央人民政府和西藏地方政府关于和平解放西藏办法的协议》，全文共十七条。协议号召西藏人民团结起来，驱逐帝国主义势力出西藏，回到祖国的大家庭中来。规定在中央人民政府的统一领导下，西藏人民有实行民族区域自治的权利。--第３４０页。

　　３７９　社会革命党，俄国小资产阶级政党。一九○二年由各种民粹派小组和团体合并而成。主张在联邦制的基础上建立民主共和国，反对无产阶级在民主革命中的领导作用。第一次世界大战期间，多数成员采取社会沙文主义立场，支持帝国主义战争。一九一七年成为资产阶级临时政府的主要支柱。十月革命后同外国武装干涉者和国内白卫分子勾结，反对苏维埃政权，在苏维埃政府打击下瓦解。--第３４７页。

　　３８０　孟什维克是俄文的音译，意即少数派。是俄国社会民主工党内的右倾机会主义派别。一九○三年俄国社会民主工党第二次代表大会制定党纲、党章时，马尔托夫等机会主义者反对以列宁为首的马克思主义者的主张，在投票选举党中央机关时，该派只获得少数选票，被称为孟什维克。--第３４７页。

　　３８１　费孝通，一九一○年生，江苏吴江人。曾任云南大学、清华大学社会学系教授、系主任。一九四二年参加中国民主同盟。中华人民共和国成立后，任中国人民政治协商会议全国委员会委员、副主席，国家民族事务委员会副主任，中国民主同盟中央副主席等职。--第３４９页。

　　３８２　王麻子　指北京王麻子剪刀牌号。--第３４９页。

　　３８３　张小泉　指杭州张小泉剪刀牌号。--第３５０页。

　　３８４　高岗（一九○五--一九五四），陕西横山人。曾任中共中央政治局委员、中共中央东北局书记、中央人民政府副主席。一九五三年调中央任国家计划委员会主席后，进行反党分裂活动。一九五四年被揭露。一九五五年三月，中国共产党全国代表会议通过决议开除他的党籍。--第３５０页。

　　３８５　《国讯》是中华职业教育社办的刊物。创刊于一九三一年十二月，原名《救国通讯》，一九三四年一月改为《国讯》。一九四八年四月被国民党反动派勒令停刊。--第３５６页。

　　３８６　几老指黄炎培、江恒源、杨卫玉、冷遹。黄炎培，参见本书注〔２２９〕。江恒源（一八八五--一九六一），江苏灌云人，曾任职教社办事部主任。中华人民共和国成立后，任中央人民政府政务院文化教育委员会委员。杨卫玉（一八八八--一九五六），江苏嘉定（今属上海市）人，曾任职教社办事部副主任、总干事、副理事长。中华人民共和国成立后，曾任中国人民政治协商会议全国委员会委员、轻工业部副部长。冷遹（一八八二--一九五九），江苏镇江人。曾任职教社常务理事。中华人民共和国成立后，曾任中国人民政治协商会议全国委员会委员、江苏省副省长、中国民主建国会江苏省工作委员会主任委员。--第３５６页。

　　３８７　鸦片战争是一八四○年至一八四二年资本主义的英国对中国发动的侵略战争。从十八世纪末期起，英国把大量鸦片走私输入中国，毒害中国人民，并使中国白银大量外流。一八三八年底清政府派林则徐为钦差大臣去广州禁烟。一八三九年六月林则徐下令当众销毁从英、美等国不法商人手中缴获的鸦片二百三十多万斤。一八四○年，英国借口保护通商，发动侵华战争。清政府在战争中动摇妥协，只有部分军队和人民群众奋起抵抗侵略者。英军除先后在广东、福建、浙江沿海骚扰并入侵外，又攻占吴淞，闯进长江，直逼南京，迫使清政府在一八四二年八月签订了丧权辱国的《南京条约》。从此，中国逐步变成半殖民地半封建国家。--第３５８、３９６、４０８页。

　　３８８　基尔特社会主义也称行会社会主义（基尔特是英文"行会"一词的音译），是二十世纪初英国工人运动中出现的一种资产阶级改良主义思潮。主要代表人物是潘蒂、柯尔等。他们主张一个社会应设立两个平行的组织：一个是由工人、工程师等按行业联合组成的产业基尔特，领导和管理生产；一个是作为消费者的国家，负责产品分配和保证全民消费。他们幻想等到基尔特发展到包括全体人民时，它就可以和平地代替资本主义国家，从而实现社会主义。--第３６０、４１１页。

　　３８９　东土耳其斯坦指一九三三年十一月英帝国主义在中国直接策动新疆大伊斯兰主义分子萨比提大毛拉在喀什成立的"东土耳其斯坦伊斯兰共和国"。这个政权因分裂祖国，投靠帝国主义，受到新疆各族人民的反对，一九三四年二月瓦解。--第３７５页。

　　３９０　一九一一年武昌起义后，湖北军政府提出改政体为五族共和。孙中山曾经一度宣传这种思想，他主张汉、满、蒙、回、藏五族一家，立于平等地位，通过五大民族平等参与国家政权，实现国家统一和民族统一。--第３８０页。

　　３９１　一九四三年蒋介石在《中国之命运》一书中，认为从民族成长的历史来说，中华民族是多数宗族融和而成的；各地的宗族，同源于一个始祖，是同一血统的大小宗支，它们在长期的历史发展过程中，由于生活的互相依赖、文化的交流和累世的婚姻关系，逐渐同化、融和为一个"中华大民族"。蒋介石在这里实质上只承认有汉族，否定少数民族的存在，把各少数民族称之为汉族的大小宗支。--第３８０页。

　　３９２　农业合作社即农业生产合作社，是当时我国劳动农民在中国共产党领导下自愿联合组成的集体经济组织。按照集体化程度的不同，分为初级农业生产合作社和高级农业生产合作社。初级农业生产合作社实行土地入股、统一经营；收益按土地和劳力比例分配；牲畜、农具等生产资料入股，也取得合理的代价。高级农业生产合作社，土地取消了报酬，归集体所有，牲畜、农具等生产资料作价入社，完全实行按劳分配的原则。--第３８１页。

　　３９３　"六条政治标准"是毛泽东在一九五七年《关于正确处理人民内部矛盾的问题》中提出的。原文是："在我国人民的政治生活中，应当怎样来判断我们的言论和行动的是非呢？我们以为，根据我国的宪法的原则，根据我国最大多数人民的意志和我国各党派历次宣布的共同的政治主张，这种标准可以大致规定如下：（一）有利于团结全国各族人民，而不是分裂人民；（二）有利于社会主义改造和社会主义建设，而不是不利于社会主义改造和社会主义建设；（三）有利于巩固人民民主专政，而不是破坏或者削弱这个专政；（四）有利于巩固民主集中制，而不是破坏或者削弱这个制度；（五）有利于巩固共产党的领导，而不是摆脱或者削弱这种领导；（六）有利于社会主义的国际团结和全世界爱好和平人民的国际团结，而不是有损于这些团结。这六条标准中，最重要的是社会主义道路和党的领导两条。"--第３８９、４３２、４４９页。

　　３９４　彭真，一九○二年生，山西曲沃人。当时任中共中央政治局委员、中央书记处书记、中国人民政治协商会议全国委员会副主席。--第３９１页。

　　３９５　老舍（一八九九--一九六六），北京人。作家。当时任中国文学艺术界联合会副主席、中国作家协会副主席等职。--第３９２页。

　　３９６　甲午战争是一八九四年（甲午年）中国和日本发生的战争。这次战争是日本军国主义者蓄意挑起的。日本军队先向朝鲜发动侵略并对中国的陆海军进行挑衅，继而大举侵入中国的东北。由于清朝政府的腐败，中国方面在陆上和海上都遭到失败，一八九五年被迫签订了《马关条约》。--第３９３页。

　　３９７　戊戌变法是一八九八年（戊戌年）发生的资产阶级性质的维新运动。当时，中国面临被帝国主义列强瓜分的严重危机。康有为、梁启超、谭嗣同等人，在清朝光绪皇帝的支持下，企图通过自上而下的变法维新，逐步地在中国推行地主阶级和资产阶级联合统治的君主立宪制度，发展民族资本主义，以挽救民族危亡。但是，当时还没有强有力的资产阶级，以慈禧太后为首的顽固派坚决反对变法维新。在宣布变法三个多月以后，慈禧太后发动政变，幽禁光绪皇帝，杀害谭嗣同等六人，变法遭到失败。--第３９３页。

　　３９８　顾颉刚（一八九三--一九八○），江苏吴县人。历史学家。当时是中国人民政治协商会议全国委员会委员、历史研究所研究员。--第３９４页。

　　３９９　这里指八旗兵。清代常备军之一。它是分别以正黄、镶黄、正白、镶白、正红、镶红、正蓝、镶蓝军旗为标志的八支军队的统称。每旗七千五百人，设都统一人和副都统二人为正副统帅。八旗兵又分满洲八旗、蒙古八旗、汉军八旗。--第３９４页。

　　４００　指绿营兵，也称绿旗兵，是清朝政府按明代军队建制建立的常备军。因这些由汉人组成的军队使用绿色军旗，所以称绿营。--第３９４页。

　　４０１　湘军是曾国藩为镇压太平天国农民革命运动，于一八五二年在其家乡湖南招募、训练的封建军阀武装。因士兵和将领多是湘乡人，所以称湘军。--第３９４页。

　　４０２　淮军是李鸿章为镇压太平天国农民革命运动，在曾国藩的支持下，于一八六一年将其家乡安徽的地主武装按湘军的组织形式加以改编组成的封建军阀武装。因士兵多是淮南一带人，所以称淮军。--第３９４页。

　　４０３　指一八九四年（甲午年）中日战争后清朝政府仿照西方资本主义国家军制编练的新式陆军。--第３９４页。

　　４０４　一九五七年十月，苏联发射了第一颗人造地球卫星，这是当时世界上最新的科学成就。我国在一九五八年"大跃进"运动中，有人用放"卫星"来比喻各行各业出现的"高产指标"和"最新成就"。但是当时在浮夸风的影响下，不少部门和单位宣布的"高产指标"和"新技术"、"新产品"是不切实际和不合标准的。--第３９４页。

　　４０５　梁思成（一九○一--一九七二），广东新会人。建筑学家。清末维新派著名人物梁启超之子。当时任清华大学土木建筑系主任、中国人民政治协商会议常务委员会委员。一九五九年加入中国共产党。--第３９５页。

　　４０６　康同璧（一八八一--一九六九），广东南海人。清末维新派著名人物康有为之女。当时任中国人民政治协商会议全国委员会委员。--第３９５页。

　　４０７　维新派指中日甲午战争前后主张向西方学习、实行维新变法的资产阶级政治派别，主要代表人物有康有为、梁启超、谭嗣同、严复等。--第３９５页。

　　４０８　一九五八年九月二十八日，中国史学会和中国科学院历史研究所第三所（今中国社会科学院近代史研究所），在北京联合举行学术讨论会，纪念戊戌变法六十周年。会议由范文澜主持。参加会议的有北京的史学工作者和吴玉章、李济深、黄炎培、陈叔通、陈垣、潘梓年、章士钊、康同璧、梁思成等六十余人。参加会议的同志在发言中谈到，一八九八年的戊戌变法是改良主义运动，但在当时代表着中国社会的发展趋势，具有进步的意义，是中国近代史上的一次思想解放运动。--第３９５页。

　　４０９　首批特赦战犯溥仪等十一人是：溥仪（原伪满洲国皇帝）、杜聿明（原国民党东北保安长官司令部司令长官、徐州"剿总"副总司令）、王耀武（原国民党第二绥靖区司令官兼山东省政府主席）、曾扩情（原国民党四川省党部主任委员）、郑庭笈（原国民党第四十九军军长）、宋希濂（原国民党川湘鄂边区绥靖公署主任）、杨伯涛（原国民党第十八军军长）、陈长捷（原国民党天津市警备司令部司令）、丘行湘（原国民党青年军第二○六师师长）、周振强（原国民党浙西师管区司令）、卢浚泉（原国民党第六兵团司令官）。--第３９６页。

　　４１０　溥仪　即爱新觉罗·溥仪（一九○六--一九六七），清朝末代皇帝。一九一二年中华民国建立后被迫退位。一九三二年任日本帝国主义一手策划的伪满洲国"执政"，一九三四年改称"满洲帝国皇帝"。一九四五年日本投降后被苏军俘虏，一九五○年八月被移交给中华人民共和国政府。一九五九年十二月被特赦释放。一九六四年任中国人民政治协商会议全国委员会委员。--第３９６页。

　　４１１　托管，这里是指美国政府企图长期霸占我国台湾的一项计划。在中国人民解放战争取得全国胜利的前夕，美国国务院为把台湾从中国大陆分离出去，多次提出通过联合国把台湾置于美国的托管之下。因为蒋介石不同意，英法两国也不支持，美国的托管计划没有实现。--第３９７页。

　　４１２　蒋经国，一九一○年生，浙江奉化人。蒋介石的长子。当时任国民党中央委员及中央常务委员、行政院政务委员会委员等职。--第３９７页。

　　４１３　指溥仪的叔父载涛，弟金友之，妹金欣如、金蕊秀、金韫馨、溥韫娱、金志坚等。--第４０１页。

　　４１４　载涛（一八八七--一九七○），清末曾任军谘大臣。中华人民共和国成立后，任全国人民代表大会代表，中国人民政治协商会议全国委员会委员。--第４０２、４１２页。

　　４１５　八旗制度　是清代满族实行的军事、生产、行政合一的制度。一六○一年努尔哈赤初建黄，白、红、蓝四旗。二六一五年又增建镶黄、镶白、镶红、镶蓝四旗。凡满族成县均入旗籍，平时生产，战时打仗。以后皇太极又增设蒙古八旗和汉军八旗。此制创建初期，在加强军事力量，提高满族社会生产力等方面，起过积极作用。入关后，八旗制度实际变成纯粹的军事制度，旗民同样受到清朝统治者役使，军力日益衰颓。鸦片战争以后，八旗制度逐渐解体。--第４０３页。

　　４１６　范文澜（一八九三--一九六九），浙江绍兴人。当时任中共中央候补委员、中国科学院哲学社会科学部委员、中国近代史研究所所长。--第４１０页。

　　４１７　我国封建社会传统教育以"天地君亲师"五者为人类至尊，所以并举表示崇敬的意思。--第４１０页。

　　４１８　无政府主义是十九世纪中叶出现于欧洲的一种小资产阶级思潮。主要代表人物有法国的蒲鲁东、俄国的巴枯宁和克鲁泡特金等。它否认任何国家和政权，否认任何权力和权威，鼓吹绝对自由、极端民主，主张建立一个"无命令、无权力、无服从、无制裁"的无政府状态的社会。"五四"时期，无政府主义思想在中国青年中曾有过较大的影响。一些地方先后出现了无政府主义的小团体。最初它们也表现过某些反帝反封建的意愿，但随着马克思主义的传播，特别是中国共产党的成立，一些具有无政府主义思想的青年转而信奉科学社会主义，无政府主义的团体则愈来愈趋于反动。--第４１１页。

　　４１９　觉悟社是一九一九年九月周恩来等在天津组织的进步青年学生团体。成员有邓颖超、郭隆真、马骏、刘清扬等二十余人。主要活动是出版《觉悟》杂志，讨论研究新思潮，抨击孔孟之道，积极领导青年学生的爱国运动，反对帝国主义和封建军阀。一九二○年冬，觉悟社社员分散各地，社的活动无形停顿。以后，它的主要成员大部分加入了中国共产党。--第４１１页。

　　４２０　费边社会主义是以英国费边社的主张为代表的资产阶级改良主义思潮。费边社是英国资产阶级知识分子一八八四年创立的团体，以善于等待时机、实行拖延缓进战术著称的古罗马统帅费边命名。其主要代表人物有维伯夫妇、肖伯纳等。他们以为用温和缓进的办法，通过细小的改良就能使资本主义制度逐步过渡到社会主义。--第４１１页。

　　４２１　刘清扬（一八九四--一九七七），天津人。一九二一年在巴黎勤工俭学时加入中国共产党。一九二七年脱离共产党。一九三一年后从事抗日救亡运动。一九四四年加入中国民主同盟。一九四八年进入华北解放区。中华人民共和国成立后，历任中国人民政治协商会议全国委员会常务委员、中国民主同盟中央常务委员、中华全国妇女联合会副主席、中国红十字会总会副会长。一九六一年重新加入中国共产党。--第４１１页。

　　４２２　罗素（一八七二--一九七○），英国唯心主义哲学家、逻辑学家。一九二○年至一九二一年曾来中国讲学，在旧中国学术界有相当影响。--第４１１页。

　　４２３　弗洛依德（一八五六--一九三九），奥地利心理学家、精神分析学派创始人。--第４１１页。

　　４２４　爱因斯坦（一八七九--一九五五），犹太人，出生于德国乌尔姆城。 是著名的物理学家。他创建的相对论是现代物理学的理论基础之一。--第４１１页。

　　４２５　溥杰即爱新觉罗·溥杰，一九○七年生，清朝末代皇帝溥仪的胞弟。一九三○年至一九四四年先后三次留学日本，曾任伪满宫廷侍从武官等职。一九四五年日本投降后被苏军俘虏，一九五○年八月被移交中华人民共和国。一九五九年十二月被特赦释放。后任中国人民政治协商会议全国委员会文史资料研究委员会专员、第六届全国人民代表大会常务委员。--第４１２页。

　　４２６　李根源（一八七九--一九六五），云南腾越（今腾冲）人。一九○五年加入同盟会。辛亥革命后任云南省军政府军政部总长兼参议院议长，在一九一八年护法战争中被推为驻粤滇军总司令。一九二三年在北洋政府农商总长任内兼署过国务总理。--第４１２页。

　　４２７　胡适（一八九一--一九六二），安徽绩溪人。早年留学美国。一九一七年回国，任北京大学教授，宣扬实用主义哲学。五四新文化运动时，主张文学改革，提倡白话文。一九一九年七月发表《多研究些问题，少谈些"主义"》，公开反对马克思主义。随后追随蒋介石，反对人民革命运动。一九三八年任国民光政府驻美国大使，一九四六年任北京大学校长。一九四九年去美国，后到台湾。--第４１２页。

　　４２８　见列宁《"关于用自由平等口号欺骗人民"出版序言》（《列宁全集》第２９卷，人民出版社１９５６年版，第３４３-３４４页）。--第４１３页。

　　４２９　延安整风是中国共产党自一九四二年起首先在延安开始，以后在全党范围内开展的一个马克思列宁主义的思想教育运动。主要内容是：反对主观主义以整顿学风，反对宗派主义以整顿党风，反对党八股以整顿文风。经过这个运动，全党进一步地掌握了马克思列宁主义的普遍真理与中国革命的具体实践的统一这样一个基本的方向。--第４１４页。

　　４３０　定股是指资本主义工商业实行公私合营时，对原来私营企业的资产和负债，根据公平合理、实事求是的原则，进行清理、估价，以核定私股股额。--第４１４页。

　　４３１　指极少数反党反社会主义的资产阶级右派分子。一九五七年四月，中共中央决定在全党进行一次反对官僚主义、宗派主义和主观主义的整风运动。在整风过程中，极少数资产阶级右派分子乘机向党和新生的社会主义制度进攻，妄图取代共产党的领导。中国共产党领导广大人民对右派的进攻进行了坚决的斗争，但在斗争中犯了严重的扩大化的错误。一九七八年，中共中央决定对被划为右派分子的人进行复查，把错划的改正过来。--第４１７页。

　　４３２　毛泽东在一九五七年四月三十日和民主党派负责人、无党派民主人士谈话中以及后来的一些场合讲到知识分子问题时，曾引用"皮之不存，毛将焉附"（参见《左传·僖公十四年》）和"梁上君子"（参见《后汉书·陈寔传》）作比喻，来说明在生产资料私有制的社会主义改造基本完成以后，从旧社会过来的知识分子所依附的经济基础那几张旧"皮"已经不存在了，因此他们不能不依附在公有制这张新"皮"上，即站在无产阶级方面，而不能象"梁上君子"（原意指躲藏在梁上的小偷，这里是借用）那样，上不着天，下不着地。--第４１８页。

　　４３３　指一九六一年六月国家科学技术委员会党组和中国科学院党组提出、同年七月中共中央批准试行的《关于自然科学研究机构当前工作的十四条意见（草案）》。中央批准这个草案的批语中指出："做好知识分子工作，很关紧要。""近几年来，有不少的同志，在对待知识、对待知识分子的问题上，有一些片面的认识，简单粗暴的现象也有所滋长，必须引起严重的注意，以端正方向，正确地贯彻执行党的政策。"草案就正确理解对自然科学工作者的红与专的要求，正确贯彻执行百花齐放、百家争鸣的方针和理论联系实际的原则，明确科学研究机构的根本任务（出成果，出人才），保持科学研究工作的相对稳定，保证科学研究工作的时间，改进研究机构中党的领导方法等问题，作出了一系列具体的政策规定。中央认为，这个文件的精神对于一切有知识分子工作的部门和单位都是适用的。--第４２０页。

　　４３４　指一九六一年九月中共中央原则批准的《中华人民共和国教育部直属高等学校暂行工作条例（草案）》，全文共六十条。条例草案总结了一九五八年后三年来高等教育工作的经验和教训，针对当时学校教学质量降低，忽视知识分子作用以及劳动过多等主要问题，规定了高等学校必须以教学为主，努力提高教学质量；正确执行党的知识分子政策和百花齐放、百家争鸣的方针；实行党委领导下的以校长为首的校务委员会负责制；做好总务工作，保证教学和生活的物质条件；以及改进党的领导方法和领导作风，加强思想政治工作等。--第４２０页。

　　４３５　指一九六一年九月中共中央制定的《国营工业企业工作条例（草案）》，全文共有七十条。一九五八年"大跃进"以来，由于许多企业没有实行严格的责任制，不讲究经济核算，工资、奖励制度上存在平均主义，以及党委包揽企业的日常行政事务等等，相当普遍地出现了生产秩序混乱，瞎指挥、乱操作，设备损坏严重，经济效果很差等问题。针对这些情况，工业七十条草案明确规定了国营工业企业的性质和基本任务，重新肯定了党委领导下的厂长负责制，要求建立和健全必要的责任制和各项规章制度，强调计划管理、按劳分配、企业经济效果和职工物质利益等项原则。这个条例草案的讨论和试行，对于总结国营工业企业管理工作的经验，贯彻执行当时提出的调整、巩固、充实、提高的方针，促进我国的工业的恢复和发展，起到了积极的作用。--第４２０页。

　　４３６　胡先骕（一八九四--一九六八），江西新建人。植物学家。当时是中国科学院植物研究所研究员，应邀列席中国人民政治协商会议第三届全国委员会第三次会议。--第４３４页。

　　４３７　指一九五六年基本完成的国家对农业、对手工业和对资本主义工商业的社会主义改造。--第４３９页。

　　４３８　在一九五八年的"大跃进"过程中，由于"左"倾思想的影响，曾把一些坚持实事求是、反对浮夸的人，以及一些所谓具有资产阶级学术观点的人都作为有"右倾保守思想"的人物，作为"资产阶级白旗"加以批判、斗争甚至处分。当时把这种作法叫做"拔白旗"，也叫"拔白旗，插红旗"。一九六二年四月，中共中央发出通知，要求为在"拔白旗"、"反右倾"等运动中被错误地批判和处分的人进行甄别平反。--第４４４页。

　　４３９　张际春（一九○○--一九六八），湖南宜章人。当时任国务院文教办公室主任、中共中央宣传部副部长。--第４４４页。

　　４４０　邓初民（一八八九--一九八一），湖北石首人。当时任中国民主同盟中央副主席、全国人民代表大会常务委员会委员、中国人民政治协商会议全国委员会常务委员。--第４５１页。

　　４４１　指到成都、渡口、昆明、贵阳、韶山等地参观学习的在北京的全国人民代表大会常务委员会委员和中国人民政治协商会议常务委员会委员中的部分人士。--第４５２页。

　　４４２　林巧稚（一九○一--一九八三），福建厦门人。妇产科专家。曾任全国人民代表大会常务委员会委员、中国医学科学院副院长等职。--第４５２页。

　　４４３　张孝骞，一八九七年生，湖南长沙人。当时任中国人民政治协商会议常务委员会委员，首都医院内科主任、教授。--第４５２页。

　　４４４　钟惠澜，一九○一年生，广东梅县人。当时任中国人民政治协商会议常务委员会委员、北京友谊医院院长。--第４５２页。

　　４４５　指到延安、西安、洛阳、郑州、辉县等地参观学习的原国民党军政人员和先后特 赦释放的人员。--第４５２页。



