# 序

中文马克思主义文库 -> 周恩来
序
熊复

 
　　周恩来同志，作为伟大的马克思主义者和无产阶级革命家，不仅是我们党的卓越的政治家、军事家和外交家，也是一位杰出的马克思主义政论家。在半个多世纪的革命生涯中，他把党的政治领导、组织领导和思想宣传领导工作集于一身，长期关心和指导革命报刊活动，并且亲自执笔撰写了大量的政论文章。这些政论文章，对各个历史时期的重大政治事件，国内外形势及其变化，党的斗争任务和方针政策，都作了科学的分析和论述。无论谁作为后辈，只要读到这些政论文章，都会亲切地感受到：它们是时代的镜子，是历史的跫音，是党的战斗历程的投影，不仅具有历史价值，也是具有理论价值和文学价值。因为从根本上说，它们是周恩来的革命实践活动和革命理论活动的组成部分，因而是他留给世世代代的一份极其珍贵的精神遗产。现在，《周恩来政论选》一书，从周恩来一生中发表的数百篇政论文章和讲演辞中，选出百余篇，汇编成册，公诸于世，这是做了一件有重大意义的好事。
 
　　周恩来的革命生涯，可以说是从报刊活动开始的，也可以说是同报刊活动分不开的。也就是说，从一开始，他就数十年如一日，始终非常重视通过报刊开展革命宣传。

　　早在五四运动时期，他就在南开大学主编过《天津学生联合会报》和《觉悟》杂志，发表了充满革命激情的文章。

　　１９２１年至１９２４年旅欧期间，他先是为天津《益世报》撰写欧洲通讯，有时每周就写两三篇，向国人报道和评述第一次世界大战后欧洲的社会危机和帝国主义列强的政治外交动向。接着又在共产主义青年团刊物《少年》和《赤光》杂志上发表几十篇论文和短评，宣传马克思主义和十月社会主义革命，揭露帝国主义和封建军阀在中国的黑暗统治，推动中国革命运动向前发展。

　　１９２４年回国后，周恩来立即投身于中国革命斗争的洪流，并且站在这个洪流的潮头。在第一次国内革命战争和第二次国内革命战争时期，在风云变幻、戎马倥偬的岁月，他仍然不断执笔写作并发表大量政治演说，支持孙中山先生的三大政策，驳斥国民党右派的反共谰言，反击帝国主义及其走狗的反革命政变，坚持反帝反封建的革命纲领。

　　抗日战争前夕，在国土沦丧、民族危亡的严重关头，周恩来为建立和发展民族统一战线而大声疾呼，从理论上和政策上系统地阐明了党的统一战线思想和主张。在整个抗日战争时期和解放战争初期，特别是他在重庆担任中共中央南方局书记时期，在局势复杂多变、政治环境险恶的情况下，他亲自领导《新华日报》和《群众》周刊的活动，并亲自执笔撰写了大量政论文章和讲演辞，仅为《新华日报》写的代论就有１８篇。这是周恩来写作政论文章的高潮时期。他在这些议论风发的政论文章和讲演辞中，分析形势，辨明是非，揭露敌人，团结朋友，教育人民，鼓舞士气，成为团结抗战的伟大号角。

　　新中国成立以后，周恩来作为党和国家的主要领导人，内政外交集于一身，日理万机，为国操劳，他执笔写作的机会少了，但他在国务活动中所作的大量演讲、报告，包括在国际会议上所作的重要发言，也都是优秀的政论，体现了周恩来的政治风度和外交艺术，受到国内外的普遍赞誉。

　　周恩来的政论文章旗帜鲜明，论证严谨，说理透彻，见解精辟，辩而不华，质而不俚，兼有机智和犀利的锋芒，而又有情理并重、平易近人的气度，具有他自己独特的风格，即周恩来风格。他的政论，体现了无产阶级革命家博大的胸怀，广阔的视野，科学的态度和战略家的眼光，是摆事实讲道理进行科学分析的典范，是原则的坚定性和策略的灵活性相结合的典范，也是坚持运用马克思主义的立场、观点和方法观察和研究政治问题这一原则的典范。从这个意义上说，这些政论不仅是党在当时进行思想政治斗争的锐利武器，也是我们今天学习无产阶级政治科学特别是战略和策略的教科书。

　　我是曾经在周恩来同志领导下从事党报工作和宣传工作，亲聆过他的多年教诲的人，今天捧读他的这些名垂当世而为后世效法的政论文章，更是倍感亲切。遥想当年在重庆时期，周恩来为指导党报党刊工作，培养党报党刊工作人员，不知花了多少心血。我在《坚持团结抗战的号角--新华日报代论集》序言（重庆出版社出版）和《周恩来和新华日报》一文（见《南方局党史资料》１９８８年第二期）中，对此有详尽的论述，不在这里赘言。我只是在这里提到一点："党的喉舌，人民的向导"这个当年周恩来为《新华日报》和《群众》杂志规定的方针，体现了他坚持党报党刊的党性原则的立场和观点，至今仍然是指导我们党领导下的一切报刊活动的唯一正确的方针。又想到全国解放以后，他在领导党和国家活动的整个时期，在他工作到凌晨四、五时的每天深夜，他都要审阅由人民日报和新华社送到他办公室的重要报道和评论。据不完全统计，１９５０年至１９７５年间，他为《人民日报》审阅修改的文章就有７００多篇。他在审阅稿件时，总是用毛笔，按照文法和逻辑一字一句，圈圈点点，一丝不苟，仔细认真地进行修改。他不只改内容，改提法，还改正文法，改正错字，直至每一个标点符号都不放过。所有接触到他的这一活动的人们无不为他的这种极端负责的工作精神所感动。他的言传和身教，使我们受到终生难忘的极大教益。崔奇同志和中央文献出版社、人民日报出版社的编辑同志正是出于学习周恩来、研究周恩来的心愿，汇编了这本《周恩来政论选》，把它奉献给广大读者，并以此书的编辑出版来纪念周恩来同志诞生九十五周年。



