# 欧战后之欧洲危机（伦敦通信）

中文马克思主义文库 -> 周恩来
欧战后之欧洲危机（伦敦通信）
（一九二一年二月一日）

吾人初旅欧土，第一印象感触于吾人眼帘者，即大战后欧洲社会所受巨大之影响，及其显著之不安现状也。影响维何？曰：生产力之缺乏，经济界之恐慌，生活之窘困。凡此种种，均足以使社会上一般人民饥寒失业交困于内外，而复益之以战争中精神文明所得间接之损失，社会之现状，遂乃因之以不安。吾人未出国前，虽屡震夫欧战影响巨大之论，然终以为欧洲物质文明发达甚盛，数年来之摧残，特不过数部分耳，何能碍及全体之发展？比以实验证之，方知昔日之理想乃等诸梦呓。欧洲一切组织非如吾国散沙可比，一切工商业咸有关联。而生产力之集中厥维工厂、运输、保险、分配，又济之以密如蛛网铁路航路、互有联属之银行、公司、商店，虽曰生产贸易自由，而其关系之深，计算之周，固已趋于集中之势矣。乃至欧战一起，人力之征役，生产力之损失，生产品之耗费，商业隔断，已不可计算。一地之牺牲，乃倾全国精锐之牺牲也。一战之牺牲，乃倾全欧精锐之牺牲也，四年来影响所及，欲求其免于穷困也难矣。故游于巴黎伦敦之市，虽觉繁华远过东亚，然物质文明之享受，如煤也、电也、面包也、糖也，已不能如我国上海京津之取给均足矣。至失业者之多，固不能与我国北省饥民之数与景况相较。然即以英伦苏格兰论之，见失业者已超过百万上矣，是固不及吾两省之大，而所得之失业人数也。然其中有一事宜正告国人者，吾国之饥馑由于天时者半，由于人力不自振兴、不思求免于水旱之苦者亦半，故一经水旱则唯有坐以待毙。若欧洲失业之人，彼自身固非无一技一艺者，置之工厂中，彼之运用机器之巧，窃恐有过于吾国之专门学校毕业生，中学生更无论矣。是验之于留法勤工俭学生入厂勤工而知也。且欧洲失业之人，均怀有技能而无地可施，吾国则不但无业之人无技能之可言，即得业之人亦属技能仅见。是欧洲曰失业，在吾中国仅可名曰无业。欧洲无事之人既如此其多，则其一人（欧洲工人多无家者）一家之生活，将从何而得以维持？是固今日社会上所最为骚扰之问题也。
 

不仅此也。欧洲多工业国，其工人组织之完备、与夫自谋协力之热心，在我国今日都未曾梦见，而其结果尚不能得完善之救济，则中等阶级人既无团体之协助，又受经济现状之压迫，其失业与窘困者又不知若干人矣。

推求其原，失业者之所以增多，由于商务之停滞，生货之缺乏，资财之不足，税则之重敛，物价之腾贵，工厂之倒闭，凡此种种，均互为因果，以至于产业不能振兴，而工人失业也。是种现状，不仅英法为然，欧洲各国莫不然也，而尤以战败国为尤甚。于此各国执政者求所以解决之道者，除俄罗斯已为工人苏维埃另有解决方法外，其大旨均不外农业之开拓，求所以自给之道；商业之恢复，求收回战前地位；并谋所以扩充各工业之奖励，以图外输货物之增加。凡此数事，固各国全国一致所主张者，然为谋一国百年大计诚得矣，非所以语于今日之窘困、与夫各国之交相迫也。皆若目前之救济、则欧洲联合国〔１〕方面有一共同目标焉，曰定德国之赔款确数，约束德国履行条约，救济中欧，恢复以前商务状态，是不仅欧洲联合国方面渴欲解决，即德意志、即中欧各国，亦何莫不盼其下文作如何分解也。而英人于此犹有一独得秘方，是曰与俄通商。各国之所踌躇恐惧莫能决者，英政府乃竟于前一星期，将对俄通商协定条文与驻英俄代表决定，交莫斯科方面议复矣。舍此暂不论，前所举各国政府所视荦荦诸大端者，固已经诸国讨论二年之久，于上一星期（一月二十三日至二十九日）在巴黎联合国最高会议决定矣。此次最高会议负重大责任者，除美代表未参与外，殆莫英法若。法首相白里安〔２〕，新任也。登台第一声，竟将两年来法人所渴望之赔款确定。其周旋于列国间者，有足多焉。盖法主多赔，英主少赔。兹次会议英首相劳合乔治〔３〕亲身往法，带去代表至四十多人，亦可谓兴师动众，视为极大问题，而竟不能胜其少赔之主张。此盖证之于会议中。彼曾对外人言德国赔款总数为五十万万金镑，而结果竟不然也。然则赔款总数究若何耶？试观下列之所记：

巴黎联合国最高会议开会，讨论一星期。经星期五（二十八日）之长久讨论，于星期六定为下列之决议："协约国相信他们的坚固联合，是必须去保持和平，为同他们换此以胜战争，并且决定不许别的事件来损害他。他们相信这个联合是世界平和、同修约实行的坚实保证，用国际间聚合同签定的忠实来证明他。"至于条文的内容，关于善后协定，德国应赔偿协约国一百一十三万万金镑，合现今金马克为二千二百六十万万。其赔偿方法，分为四十二年。头二年每年交十万万金镑，继之以交一万五千万者三年，交二万万者三年，交二万五千万者又三年，其余三十一年则年交三万万金谤。此外德国尚应每年交出其出口税百分之十二与协约国，亦继续至四十二年为止。斯项在第一年可希冀得七千五百万镑。对于别项罚款，其所谓宽待条件者，则在应引交款时期前，转将赔款交出。第一、二年可得百分之八折扣，继之四年可得百分之五折扣，又有罚约，如德至期不付赔款，由联合国取其关税偿还，并定其新税则于国内。至赔款之分配，则法得五十八万七千六百万为最多，英得二十四万八千六百万，意得十一万三千万，比利时得九万零四百万，葡、日各得八千四百七十五万，其他各国得余数七万三千四百五十万。

关于德国履行条约之规定，德国解除武装务于本年七月一号实行完了，而重费兵器尤宜于近三月内完全交出。同时最高会议又采福煦〔４〕元帅等之提议，谓德国再不履行此种条约，则立行下列之四种罚约：（一）占领新德国之领土；（二）延长现今的领域；（三）设税关测算处在莱茵河的左岸；（四）非至德国能保持他的倾向去实行以前一切的条约，不许其加入国际联盟。〔５〕

对奥问题，各国佥同劳合乔治之提议，暂缓取偿于奥，并决定将在的里亚斯特〔６〕有一会议讨论此事，且将遣委员团至奥调查其经济现状。因据报告云，欲创立奥国经济组合，必须助奥以八百万镑。所有决议均由巴黎最高会议于一月二十九日晚间致公文于柏林政府，征其同意，俟本月二十八日预定之伦敦会议正式决定之。

以上记录发表于前日英法各报，全欧人民足资为谈料矣，隐泣者有之，欢呼者有之，德人反对无论矣。而英国社会间不满之声亦群起，是实大可异焉。夫以多索赔款以救济国内经济现状，以陷德人于穷蹙之境，解除武装，限制兵备，以保国内和平，以减敌人危险，此法国多数人共同一致之主张也。至于英国政府或以此为救济战后之急需，而民间有识者及劳动工人，固未尝视此为良药。于此请进论赔款确定后所生之影响如何。

赔款总数为一百一十三万万金镑，此种巨大偿额在历史上既为创见，而在今日新创难复、百无一存之德国，尤无力偿此。证之德国现今国家收入，而断其不易偿还者一也。英法意等国之定此偿额，不但为一方面之主张，且多属政府派之主张。一旦内阁易人，此等条款是否能接续赞成？且偿期延长至四十二年之久，在此期内英法意等国内情之骚扰，及德国将来变化之不测，此种苛约，谁能保其于社会改造时有延长之生命！此对于偿还时期而易致疑者也。至出口税扣留百分之十二，则协约国之取偿于德，无异于取偿于本国国民也。盖德既因扣其出口税，此后货物为力求广售，方得增加国家收入，以偿国债，使其货物价低，则各国货高者难与竞争，资本家受直接之害，各国工人受间接失业低薪之苦，是欲求调解战后状态，反益之以纠纷不安。此于扣税方法是否合宜而不能无疑者也。若限德高其物价，则售出不易，国家收入因之减少，偿债维艰，且欲求足其偿额，则必奖励出口，减少入口，以今日情状论，德之入口货远过于出口，而其所需又为食料原料，禁食既有所不能，断绝原料之输入，则输出又奚从其增加？是使德左右维艰，而决无法以负此巨债。夫罚在能行，而协约之所需亦在得款以济急，以调解现状，如是而曰德能应承，是犹不能不令人致疑者也。

然则结局果何如乎？是曰欧洲经济状况紊乱之起点也。若曰本月二十八日之伦敦会议，便可解决此种问题，亦犹梦呓耳。总之今日欧洲之危机在物质，换言之即经济上的面包问题也。全欧人民之生活窘困，而乃夺德人之食以救协约国人，是岂根本解决耶？且夺来之食，未必便救济无食之人，取之以增兵饷、制兵械、造军舰者泰半，取之以饵资本家之口者又半，逮饥饿待救者则已无缘分润矣。不仅此，德人之食为人所夺，必思有以济其饿，则内以减薪裁人取之于工人，外以贱售夺之他国；他国亦反以减薪裁人贱售之道报之。于是辗转而全欧工人拜"夺食"之赐矣。是欲图现状之安，而终无以易不安也。

但欧洲工人非盲目者。且社会党人复从而鼓吹之、宣传之。今非仅英国劳动党职工组合声言反对矣，即法国ＣＧＴ〔７〕之工人亦倡言反对，使其国民知多索赔偿固无益也。美国消息谓，其政府已以未出代表会议，声言扣德出口税款于对美商业有直接损害，提起抗议矣。

至若吾人或于此等问题如隔岸观火，不甚关切。然使欧洲危机终不可免而至于爆裂也，则社会革命潮流东向，吾国又何能免？使赔款而终有济也，则德人取偿之术，又岂能外于奖励产业，辟新商场于欧土以外，而同时协约国得其偿款，其奖励产业与辟新商场，其法亦正相同，吾中国必为其消化之所，固无用致疑。吾人又焉能不推论其根源，记其近况，以为国人告。

＊一九二一年一月五日，周恩来到达英国首都伦敦。这是他给天津《益世报》写的第一篇通信，刊载于一九二一年三月二十二日、二十三日天津《益世报》。

注释：

〔１〕本文中的联合国均指协约国。协约国是第一次世界大战期间与同盟国（以德国和奥匈帝国为核心的帝国主义集团）相对抗的另一帝国主义集团，由英、法、俄三国于一九○四～一九○七年期间签订一系列协议而组成。第一次世界大战期间，日、意、美等二十五国先后加入。十月革命后，苏俄宣布退出。其后因协约国间矛盾加深，逐步瓦解。

〔２〕白里安（一八六二～一九三二），一九○九至一九二九年间曾历任法国总理。原业律师和新闻工作，早年投入工人运动，曾为各左翼出版物撰稿。一九○一年任社会党总书记。一九○二年以社会党人身份入众议院。一九○四年同饶勒斯创办《人道报》。一九二一～一九二二年参加华盛顿海军裁军会议。一九二五年参加缔结洛迦诺公约。一九二八年参加缔结《凯洛格-白里安公约》。

〔３〕劳合·乔治（一八六三～一九四五），一九一六～一九二二年期间任英国首相和自由党领袖。首相任内曾镇压殖民地、附属国的民族解放运动，他也是武装干涉苏俄的积极策划者之一。第二次世界大战全面爆发前，曾谴责张伯伦政府的绥靖政策。

〔４〕福煦（一八五一～一九二九），法国元帅。一九一八年五月任协约国军总司令。八月升为法国元帅，十一月十一日接受德军投降。被认为是第一次世界大战中协约国军胜利的主要领导者。

〔５〕国际联盟简称国联，是第一次世界大战后建立的国际组织。主要机构有：大会、行政院、秘书处、附设国际法庭、国际劳工局等。总部设在日内瓦。先后加入的国家有六十三个。美国为倡议国之一，但因同英、法争夺领导权失败而未参加。国联标榜"促进国际合作，维持国际和平与安全"，实际上是英法等资本主义大国维护凡尔赛-华盛顿体系，争夺世界霸权的工具。一九四六年四月宣告解散，所有财产和档案均移交联合国。

〔６〕的里亚斯特位于亚得里亚海北岸、伊斯的里亚半岛西北部，是南欧各国通向亚得里亚海的主要港口。住在市区的居民主要是意大利人、城区以外为斯洛文尼亚人。原属奥匈帝国。第二次世界大战后，的里亚斯特建为自由区并分为甲乙两区，分别由意、南两国管辖。

〔７〕ＣＧＴ是法国总工会的法文缩略字。

