# 伦敦会议再开幕之经过（西欧通信）

中文马克思主义文库 -> 周恩来
伦敦会议再开幕之经过（西欧通信）
（一九二一年五月六日）

三月初伦敦会议，是为协约国对德要求承认赔款总额，结果归于决裂，而有侵城占地之举。今也伦敦会议再开，讨论之事项仍为对德赔款，而结果又将以占城侵地闻，不祥哉伦敦会议也。西欧外交之中心，野心家争权攘利之场，亦世界祸乱之策源地也。前旬通信，曾叙及德国之新提议与夫英法诸邦之态度，其结论谓将待决于四月三十日开始之伦敦会议。今结果将实现矣，请言此次会议之内容，以为邦人告。伦敦会议之开，决于上次英法两总理在林圃里之会面。彼时英法意见悬而未决者，即法主严厉、英主缓和，两方相持不下，遂商定留待今次会议之再审。
 

会期定四月三十日开始。先一日法总理暨福煦元帅等渡海往英。意大利外交总长亦于三十日果继至。法总理离法时，曾言"吾人此去，必求于此一次解决所有问题，而得一最终之办法。吾人主张严惩德人，英虽不能助吾以实力，苟许吾道义上精神上之援助、吾法可以以独力行之而有余。德国新提出之办法，吾人断难承认。苟德人有诚意履行条约，何必远隔重洋求助于人，而不为直接之磋商......"其言甚壮，而意有所向，不满意于德固无待言，所注意者盖在对岸之英及远隔重洋之美也。临行福煦尤叱咤不可一世，其视报复之机，盖千载之时也。三十日会议开于下午，五月一日继开，两日间所争持者在赔款总数之修改。英之意见，主张较上次伦敦会议所要求德国承认之数减少。法之意见，则主张维持原额不变。附议英者为意，附法者为比。原来一月底巴黎会议英相主少索，法人主多索，结果劳合乔治竟屈于白里安氏，定赔款之总额为一百一十三万万金镑，外附以四十二年之出口货税百分之十二有半，如法人之愿也。总额既定，扰攘至今仍未得德人丝毫之保证与承诺，是知数目过巨，德人终难屈就也。于是英相乃复提其旧日主张，减少赔额，以冀德国能俯首听命。至于法则以为德固无诚意，无论少赔与多赔，彼终希图延缓，不欲承诺也。与其虚与周旋，毋宁进占德地之为愈，英法意见既异，磋商乃大不易。然时期紧迫，五月一日之期既过，倘无最后之办法宣示于德，是授德人以隙，而暴露协约国不协之状于外，故协约国又不得不力求融洽，以图此会议之良结果。于是有所谓折中办法传于外者，为减低赔款总额，增加出口税则，倘德国仍不承认，则协约国之军队将进占西弗利亚〔１〕各产业区域矣。

五月一日会议曾两开，即为磋商此事之内容。当日晚间，法总理电告法京陆军总长，令其速行招回一九一九年级后备兵，以备迅占德地之用。是知情势之急，亦所以内示协约外示德人，表法人持议之坚也。二日，会议继开。据当日公报，则声言三日仍将继开会议，且邀海陆军鉴定员列席。至于当日情形，则仅言实质协定已至一期限问题，而未言及商定之内容如何，此所谓外交秘密也。据各报所载，则云总赔款数目已改为每年赔款一万万金镑，外加以出口货百分之二十五税则，总数为六十六万万金镑，均须即行债券，其中有须立即印行者，有定于十一月中印行者，有视其力能支给之数随时印行者。此种债券，当以百分之五行息，至三日会议结果，则重要者多属于惩罚问题，其大旨不外法国素所主持者，使德国果拒绝协约国此次提议，协约国将进占鲁尔〔２〕产业区域。同时，莱茵流域凡尔赛条约〔３〕规定占时十五年者，亦将延长至德国偿还赔款之日为止。设鲁尔占领、仍不足惩戒德人，即协约国军舰将投锚于汉堡、卢卑克、斯特丁、不来梅诸港之滨矣。鲁尔区域，据鲁尔河南北两岸，当三月初协约国占领德国三城之东，包含名地极多，为德国产业兴盛地。鲁尔河属莱茵河支流，在莱茵河右岸东西流，昔日联军占领地限在莱茵河左岸者，自进占三城后已越河而东，今则欲更进一步。且前述诸港均为德国要地，汉堡、不来梅当入北海河口，卢卑克、斯特丁当入波罗的海口。使此地亦见联军舰队，则影响于德商业、航务者，岂属浅鲜！果协约国甘犯不韪，强制执行，德人恐终不能默尔忍受也。三日会议犹有磋商者，则二日所定之六十六万万金镑总赔款额，增改为六十七万五千万金镑，首期印行之债券定为六万万金榜，是盖本于五月一日应交之数，而要求其立即实行也。此两日总额之审定，多本诸巴黎赔偿委员会上次所发出通告，定战争损失为六十六万万镑之数。惟法国意见仍在多争，故遂有三日之增改，而同时巴黎赔偿委员会亦被最高会议召往过海，参与赔款额数之审定。此亦多赔少赔争执之结果所致也。四日会议乃以赔偿委员会为中心，详审赔款总数之内容，而调解英法两方之争执，结果经一日之核勘，英卒胜法六十七万五千万金镑之偿额、复减回为六十六万万金镑。此事既解，重要问题乃都告妥协。五日晨协约各国签字于致德哀的美敦书〔４〕上，于是协约内部之交涉终，协约各邦对德之新交涉又开始矣。

＊原载一九二一年六月二十七日天津《益世报》。

注释：

〔１〕西弗利亚位于德国西部，多煤铁矿。

〔２〕鲁尔，地区名，在德国中部。主要部分在莱茵河右岸支流鲁尔河下游和利珀河中下游之间。面积四千六百多平方公里。人口五百六十万（一九七一年）。是德国最重要的工业区。集中了很大一部分机器制造、电力、化学、石油、提炼、车辆、军火生产等工业。境内城市工厂密集，煤矿林立。水陆交通方便。主要城市有埃森、多特蒙德、杜伊斯堡等。

〔３〕凡尔赛条约全称《协约国和参战各国对德和约》。是结束第一次世界大战的帝国主义条约。一九一九年六月二十八日，英、法、美、日、意等战胜国与战败国德国在巴黎凡尔赛宫签订。一九二○年一月二十日生效。和约共分十五部分，四百四十条。国际联盟盟约为第一部分。其他部分主要规定：德国将阿尔萨斯-洛林交还法国；萨尔煤矿归法国，萨尔由国联管理十五年，期满后经公民投票决定归属。莱茵河左岸由协约国占领十五年，右岸五十公里为不设防地区。德国殖民地由英、法、日等国瓜分。其在中国山东的权益转交日本。德国须支付巨额赔款，并可保留十万官兵。美国代表虽在和约上签字，但美国国会未予批准。中国代表因中国人民抗议，未在和约上签字。由于凡尔赛和约是在帝国主义大国反对苏俄、宰割战败国和牺牲弱小民族利益的基础上订立的，它本身就埋下了第二次世界大战的祸根。

〔４〕哀的美敦书即拉丁文"最后通牒"一字的音译。

