# 万目睽睽之日皇储来英纪（西欧通信）

中文马克思主义文库 -> 周恩来
万目睽睽之日皇储来英纪（西欧通信）
（一九二一年五月十四日）

两月前，日皇太子因离国问题，惹起其国内绝大政潮。军阀元老，受此事之影响，且以归隐为退步，一方关心皇室之士、复惧太子行后，将有人不利于皇妃，百计阻太子之行，以冀弭此未来隐忧。然事卒未果，太子终成行。是知政变虽剧，终仅关系太子一身。至太子来英之目的，则关系英日同盟〔１〕前途者甚重，非太子一行无以收其功也。日太子行矣。在东京驿出发之盛况，方传其消息于吾人，而一帆风顺，英伦维多利亚车站，竟迎其同盟国之嘉宾矣。此数日东西两太子驰车伦敦道上，开佳筵于宫廷，杯酒联欢，其中之外交作用，政治家所恃以操纵者，又不知凡几。直接及于英日同盟，间接及于中日问题、日美问题、中英问题。名为游历，实质上确欲借此虚名，收极大之实效也。
 

日太子到英之日为五月九日。当日清晨日军舰载太子抵普茨茅斯海口，英皇太子亲身往迎。上午十点两太子乘专车入京，英皇乔治整队迎之于维多利亚车站。除军队官吏外，英皇族至者亦极多。出站后，英皇与两太子及此次随侍日太子来英之侍从长官珍田伯爵共乘一车，往白金汉宫午餐。至时英皇后及玛利公主均出迎。餐后日太子出宫赴一日人死事塔行吊仪，继复往威斯特敏士修道院，瞻仰名人坟墓。晚间英皇族开大宴会，集者约一百三十人。英皇及皇后夹日太子坐。餐时英皇有演说，大旨谓英日以地理政治上关系，日增亲密。今后情势，仍愿因日太子之来而愈加友善。大战中日本助英者甚多，英甚感谢。而英国受战争之影响，产业工艺上之窳败甚多，英将以同盟之故，使太子得尽兴参观，毫无隐藏，甚望日太子加以批评指正。日太子亦有答辞，大多祝福英皇室及赞美英国国况之语。其最后数语，有特致谢意于英皇太子者，此日皇太子得意之笔也。

兹番日太子出国，扈从之盛，为从来日本所未有。出国之费，不惜预筹数百万，以求承认于国会，而国会无论政府党及反对政府党，均一致赞助之，其朝野上下之重视太子之行可知。出国后沿途所经，凡英国属地，大都停舰登陆，遍览其同盟经营胜况，英国官吏亦铺张扬厉欢迎之，以显其外交手腕，同盟厚谊于此未来君临六千万人民之太子之前。抵英伦后，各方面铺张盛况，尤不待言。然此不过表面事也，内幕之变化，则两方政治家方在台后磋商，日皇太子亦不过登台之傀儡耳！世界皇室，自二十世纪开幕以来，实权已无多存在。欧战后中欧北俄皇室继倒，所余之君主，尤甚寥寥。今英日两皇室，方恃此虚荣，彼此縻羁笼络，究其实，乃不过政治家策略上之运用，人等机械，殊无谓也。

美日关系本甚复杂，自哈定〔２〕总统就任后，对日政策尤特别引世人注意。驻英美大使因总统更换之故，已辞职回国，新大使哈维君本非急急来英者，现因日太子至，已于十日赶来，其视英日之进行关系于日美者甚重。而一方日太子此来，其侍从长官不以他人而以向日使英之珍田伯爵充之，其不能虚此一行也尤明。英日同盟续约之决定在六月后，磋商之结果其定于今日耶。美既因是急遣其大使来监督矣。吾国之外交公使及国人，不知亦重视此事也未？

＊原载一九二一年七月八日天津《益世报》。

注释：

〔１〕英日同盟是英日两国为联合对付俄国在远东的扩张而结成的同盟。第一次同盟条约于一九○二年一月三十日在伦敦签订，规定缔约国的一方在遭到第三国进攻时，另一方应保持中立；在第三国得到其他国家支持的情况下，则应提供军事援助。条约还保障英国在中国、日本在中国及朝鲜的非法利益。第二次同盟条约于一九○五年签订，承认日本对朝鲜的"保护权"，并规定在遭到任何第三国进攻时，即应提供军事援助。一九一一年又签订第三次同盟条约。华盛顿会议期间，在美国的压力下，英日同盟于一九二一年十二月十三日宣告终止，为《四国协定》所代替。

〔２〕哈定（一八六五～一九二三），美国共和党人，一九二一至一九二三任美国总统。在任期间召开关于限制海军军备和远东及太平洋区域问题的华盛顿会议，缔结《四国公约》、《五国公约》和《九国公约》构成的"华盛顿体系"。

