# 英法最近之意见龃龉（西欧通信）

中文马克思主义文库 -> 周恩来
英法最近之意见龃龉（西欧通信）
 （一九二一年五月十六日）


　　德国赔款问题，自上星期柏林政府承认协约国最近之要求后，可谓暂告一结束矣。法国占领鲁尔流域之计划，坐视竟未能达，其遗憾为何如，而内幕则又为英法外交策略互异之结果也。德法本世仇，历史上往迹，历历可数，近五十年来因普法战役〔１〕结果，法人尤恨德入骨。大战开始，德人之残虐法人、毁践法土者，亦无不为已甚。远仇犹可忘，近恨实不易解除。故胜德以后，对德人之一切要求，咸含有报复与箝制两种用意。法人之用心良苦，而怨毒之结亦愈深。但此犹可曰，是德人自取之咎也。德人负战事之责最多，故应受和约之惩罚，无诚意履行和约，便当以严重警戒继其后，以监视德人之跳梁脱绊，是理或然矣。惟法人将何以自解于今日暗助波兰，违反和约规定，夺取上西里西亚〔２〕之举耶？
 
　　上西里西亚本德地也。巴黎议和时，以其地居民多波兰人，经波兰代表一意要求割并，乃定为由居民投票公决，此盖适用民族自决主义于德国领土内也。在未投票公决以前，由协约国派兵镇守，保护秩序，惟不侵其人民自治权。今岁三月二十日实行投票，结果赞成属德者七十万四千五百七十九票，赞成属波者四十七万一千五百二十三票。依和约规定，德既以多数属意，上西里西亚当然为德旧土无疑矣。然内情殊复杂非易决者，当上西里西亚之定为民族自决也，本非新兴之波兰所能争得，内幕之关系乃在协约国之私心别有所注。波兰之得独立，其自动之精神，与长久之奋斗，因有以玉成。而协约国利用之北蔽赤俄，西分德势，亦为最要原因。故上西里西亚之票决，亦协约国用波兰分德势之余音也。主此事最力者，自以法为首。上西里西亚居民为数不及二百万。据德之调查，云德人多于波人，波人之调查乃反是。兹事本难定，上西里西亚属于普鲁士，数百年于兹矣。波兰人数不易与德人敌，乃意中事。波人所以倾全力以争之者，在其地为产业极盛之区，煤矿尤富。是区面积约六千平方英里，包含十数城，地当德国极东端，波兰之南，捷克之北，三国交界中心也。投票结果，德人虽得多数，然波人殊不平。其所争执，云德人之投票者，多有由柏林及其他区域赶至者，其在上西里西亚并无住所及职业，不应允其投票，其实此类德人均生于上西里西亚，于故乡当然有公决权，此固协约国承认者也。且波兰人有生于上西里西亚而转至他处者，亦都归来投票，特其数不及德人之多耳，故有是异议。波人又云，投票之总数虽属德，地方分决则有数处波票多于德票者，是类地方应属波人。其意盖指是区中产业兴盛诸地，因上西里西亚之波人多为劳动者，产业兴盛地多工人，波人视之殊有把握也。惟利之所在，赴之者争先恐后，波人重视是区，德人讵甘退让耶？三月初伦敦赔款会议，德代表且以得是区为赔款应允之一条件，其亦重视是区可知。逮票决结果既属德，德人要求按和约规定施行，更振振有词。协约国虽欲助波，亦苦于不易反汗。最终结果，乃迟迟未能实现。有持调停之道者，主分上西里西亚邻近波兰之璞里斯、锐白利克二地与波，此外再将邻边界略为改正，其所根据则在此诸处之波人实较德为多故也。但波人视此殊不足偿其欲望，其所希冀在得全上西里西亚之煤产区域。使此议确定，其所获仅十之一二耳。争之既不得，波人乃取破坏激烈手段以进行。近一周中，上西里西亚乃大不安，波籍工人罢工，波人暴动，劫杀德人，甚至伤害协约国军人。凡兹事件，日日有所闻见，戍守上西里西亚之军队本为法意两国人，上级军官则英法意诸国均有也。波人暴动本非自今日始，票决时便已发现。协约国军队既以保护秩序为名，胡不负镇压之责耶？曰镇压固镇压矣，然愈压愈乱，是盖有暗中为之助者。

　　当五月一日伦敦会议，法总理曾主张德人果再不承诺此次通牒，当占领鲁尔及上西里西亚两区。惟以不得英意等国之同意，遂将占领上西里西亚之动议取消。然上西里西亚非属德即属波也。法既主占是区，是表示好意于波兰，波人乌能不倾全力以争之。故入月以来，上西里西亚之暴动，乃益剧烈。且动乱之发，非纯由群众随意而为，实有人指使操纵，为之首者波兰官吏高尔方狄也。高氏居上西里西亚，以执行公务之身，亲自与闻暴动之举。是其所恃，不仅在波政府，且有强国为助也明矣。上西里西亚邻波境界，其守卒为法人者，波人入境，多少护照之盘查，其故意放纵可知。暴动群众，多为此新来自波兰之人。伤害之事，德人既首当其冲，死伤自不待言。英意军人为执行职务故，亦多蒙损害。而法人则被害者甚少，且常坐视不问。英意军官，对此殊愤愤。德人因死伤之事日有所闻，协约国军队既无法镇压，声言将遣德兵入境。最近数日，各国戍西军官，乃连电各国政府请示办法。各国政府意见何若耶，是不得不一言今日西欧外交之枢纽。

　　今之西欧，一英法争雄之场也。两国同以为是者，他人不得以为非；两国同以为非者，他人不得以为是。两国果异其趋者，则拥其他各国赞同之意见以为抗，或折中而定之，或竟屈一方以从之，常不易得其平也。一月底巴黎会议，赔款数目，英主少而法主多，结果法胜英。一百一十三万万金镑赔款，外附征出口货税百分之十二又半之通牒送达柏林，经一月之考量，三月初伦敦会议，德代表态度强硬，不允协约所求，谈判决裂，于是占城略地之举，征收德税之议，一一见诸实行。是盖德法之主张也，英又负矣。惟英素以外交手腕狡猾胜世界，劳合乔治又为其中之翘楚，是岂易与者？英之让法，盖有待耳。果法占德城后，一月有半，德人应交纳之定期赔款又至期矣。德人四方呼援，声诉其苦情，求协约国减削款额，以冀力能担负。而英人亦若即若离以应之。同时大西洋对岸亦有作同情之声者，其音虽微，然足动此岸政治家之听。故哈定氏对德回答，有希望德国提议果能顺乎情理，当易于得协约国之赞同，达圆满解决之途等言，劳合乔治乃得凭藉之以操英国之胜利。四月下旬林圃里会议未决，五月一日伦敦再会议，卒达英人少索之目的，改赔款额为六十六万万金镑，于五月五日以哀的美敦书送达柏林，结果德遂屈服。是役也，法志在占地，以赔款之定，德人决无诚意交纳，与其徒费口舌，莫若取直接手段为愈。此报复箝制之念有以使之也。英人则不然，其于德也，非如法之有深仇者，其恨德在争霸，将夺其世界商权。今德既败，竞争者别有人在，眼光遂亦别有所注，故对德态度乃不若法之强硬，转而折中于其间，以示好德人。再英人重利，以为与其定庞大无垠之赔额，不得德人之承诺，曷若减少赔额，而能得德人之真实担保为佳。且占地事，乃最后不得已之手段，强取德税，徒增德人之怨毒，成功与否尚未敢料。因是劳氏对法占地之意见，以其气盛不易抑服，乃转而一意图偿额之削减。法总理白里安氏，虽明知减款非法人之愿，然因法人需英助者甚多，且太固执易遭美人之訾议，失协约诸国同情，遂不得不屈于英。但法犹未及料德之遽尔承诺也，故月初议定后，法人尚亟亟召还退伍兵役，遣派守戍莱茵军士，一若德国仍将拒绝要求，鲁尔流域转瞬可得者。反观英国，则通牒致德后，劳氏曾为一度之国会报告，此外并无所谓最后预备，岂英人视赔款之重不及法人耶，亦英人胸有成竹耳。此法总理白氏之智终在劳氏下矣。英既胜法，法人又岂能甘其积怒，乃不得志于西者转而泄之于东，阴助波兰，在西区暴动，以冀达其上西里西亚归波之主张。然此变更和约之事，法虽可以一手掩弱小诸邦之目，终不能无所忌惮于英也，其注意英政府之态度，自在意中。



　　＊原载一九二一年七月九日至十日天津《益世报》。

　　注释：

　　〔１〕普法战役是一八七○～一八七一年法国和普鲁士的统治集团为扩张领土，争夺欧洲霸权而进行的战争。拿破仑三世力图通过战争阻止德意志统一，扩大它在欧洲的势力，于一八七○年七月十九日对普鲁士宣战。战争开始后，法军迭次失败。九月二日拿破仑三世率十万军队在色当投降。九月四日巴黎爆发革命，推翻第二帝国，宣布成立共和国。但普鲁士军队仍长驱直入，包围巴黎；战争性质在普鲁士方面由防御转变为侵略。法国资产阶级政府于一八七一年一月二十八日同普鲁士签订屈辱的停战协定。三月十八日巴黎无产阶级举行起义，宣布成立巴黎公社。资产阶级政府迁到凡尔赛，于五月十日同德国缔结《法兰克福和约》，割让阿尔萨斯和洛林，赔款五十亿法郎。五月二十八日，凡尔赛政府在普鲁士军队帮助下，镇压了巴黎公社。通过这次战争，普鲁士完成德意志统一，建立了德意志帝国。

　　〔２〕西里西亚是东欧奥得河中、上游地区的总称，在波兰西南部，捷克斯洛伐克北部和德国东南部。在波德境内的东南部叫上西里西亚，西北部叫下西里西亚。西里西亚矿产丰富，是欧洲最大的煤田之一，农业发达，盛产小麦和甜菜。



