# 大西洋上之太平洋问题（旅欧通信）

中文马克思主义文库 -> 周恩来
大西洋上之太平洋问题（旅欧通信）
 （一九二一年十月三十日）

（一）林权助大放厥词
 

系人想念之华盛顿会议〔１〕，十数日后便将在美京开幕。群雄毕至，会聚一堂，其重要自无待言。西欧社会间当此会议初发起时，态度上之表示，殊甚冷静，不若美日哄传之盛。近者因大西洋对岸卷来浪急，各方面受其波动之影响，亦渐渐移其对德对土对匈对俄之视线，转而西向。于是外交上具有作用之表面活动，乃亦乘时而起，大事宣传，其中旗鼓最明响而目的又最简单者，自以日本为最。日本政府在欧之外交，于欧事则持一置于事外之态度，丝毫不苟，而又不即不离，常能调停和解于英法意诸国意见不合之时，以是日本在欧大使，乃有仲裁之目。惟其对欧事态度如此，同时遂又兼负解释东亚事务之责。凡日政府在东亚方面所施行之种种侵略政策，彼等无不尽力为之隐瞒辩护，隐瞒辩护之不足，则必设词污蔑他人，以证日本政府之所以如此，实由于情形之相迫，而尤召不得不如此之势。此日本政府在欧之外交策略也。不仅其驻欧各大使守此义不变，即日本旅欧"臣民"，亦咸负有宣传此种策略之使命。故旅欧日人，在欧洲社会间之交际，无不含有外交作用在内，其唯一之作用，尤为表白日本之苦衷及中国之贫弱。国际间交际本多含有深心，然国民外交而亦时时不忘作用，是则为今日日本人独擅之技矣。华盛顿会议号召后，于东亚问题更有密切关系。日人在欧之活动亦愈形紧张，其行动分两段落，初则一切奔走均极秘密，务使西欧各国政治界舆论界于黑幕中得来的报告，信以为实，且更生先入为主之见，至是根基已固。而社会间对于华盛顿会议亦渐由冷静的变为热烈的相待。日人遂一改以前之秘密中活跃情形为公开的活跃，向大多数群众攫取同情，盖后援已固，更不惧舆论之不我助也。日昨伦敦外国新闻记者联合会午餐席上，驻英日大使林权助男爵，曾有一长演说，即为此最近公开活跃之一证。其演说辞大要如下：

十四日后，吾人将群集于华盛顿。吾人中即或有不克前往者，吾人之心亦必随往。此种责任，各国之人物与其代表，甚至吾人之全体，均负有使此会议成功之期待，使吾人均得趋赴于共同赞助精神下，则吾信此会议之令人满意，初不仅为吾人之友之合众国，且更将被益于全体。

大战中吾人已为良友，此时更无有假设之原因，而必谓彼此间已有界限。其界限乃为吾人破裂种种束缚与彼此攻击而成。吾尤喜为指出者，即国际友谊信将增于美英之间，吾亦希冀吾所信此同样之感情，将必有同时之转移，发生于美日之间。关于中国问题，亦将在华盛顿讨论，并加入其全权大使。惟其国内之纷争，殊令人视之不胜遗憾。吾深信英美法日皆与中国有直接关系者，苟能至一协定地步，并寻出某种共同根据，则其国内平和，始可重图恢复。

停止中国内争，实为今日之必需。因其内争其国内一切活动都为停滞，无限之愁苦日以加增，且更将使欧洲全体在中国市场上之商业，受其战争之波及蒙极大之损失，吾人甚愿举所有诚心以助中国。吾人所冀之诚实通信社岂仅为少数，吾人并望各国外交人物及新闻记者，勿于此好意之热诚上加以阻力。

此种阻力在美国在日本均有人从事扩充、在此邦亦然，而更以在中国为甚。今早吾方阅报中载有吾老友伍廷芳〔２〕博士语瑙尔斯克利夫勋爵（瑙氏为英国新闻界大王，现方东游历中日，国人当已聆其议论，记者注），彼殊不信中国代表之参与华盛顿会议者将有若何用处。因彼等已甘居于日本势力笼罩之下，果尔殊甚不佳，使具有权威之人如瑙尔斯克利夫勋爵者亦信此语为真，则千百以上之人民居于此邦者，亦将随之以信从，但吾终希望彼等将不如是。

在英美中国代表中，将无人能信日本据有特殊之权力于华盛顿。所有报告，均无根据，吾人实期望平和。

华盛顿会议闭幕之日，吾信其必能使吾人之友之合众国获得极大之满意，而吾人彼此间亦将如此。但吾甚望有许多问题如吾人之所听闻者，将不复在此会议中讨论，因此类问题将另俟解决于来日。如此，则各国之外交代表，必不至于虚费，其一年半载之长时间，从事于难以十分安定之问题，而未经多年之牺牲与设备者，但彼此共同之根基，却极易建立普通之主要条文于合理事实之讨论中。在所有情形之中，吾敢有一事为诸君告者，日本必能举其国家之可能以协助英美法诸国，谋人间之永久和平。

林大使之言大概如此。吾人于其议论中，可获得下列之数项用意：

第一、极力表示美日联络之可能；

第二、宣传中国内乱之危险；

第三、禁止中国提出中日间一切交涉。

此三事乃为日本人对于华盛顿会议未开幕前所竭力从事之工作。林权助之言，不过为此种工作之一幕耳。

（二）共管说盛倡美国之由来

日本政府对于作战计划，布置得亦极周密。彼明知大战中日本在太平洋上所获得之种种优先权利，深为英美所忌。今当战后休息之期，英以同盟故，不便直接向日有所表示，乃引出美国，以解决太平洋及远东之纷争为名，而欲日本于种种独占政策上有所让步。所谓让步者，普通说法，即恢复昔日利益均沾条件，切实言之，即英美欲与日本平分东亚一切权利，互不侵犯，保持彼此间暂时之和平。英日本为同盟国，续盟之事日尤急于英，英苟向日有所请益，原无不可能，惟日既许英在东亚占有更优之位置，则续盟条件必更受束缚，影响之恶，于英美交谊上殊为不利。故七月间英帝国会议时，加拿大南非两首相极力反对英日续盟之实现。一方英本国又与日本为不即不离之表示，暗中则怂恿美国催开华盛顿会议，以太平洋及远东与裁减军备问题为主要，如此则事成英美日必立于同一水平上，在东亚谋尽量之发展，更不受日本任何之束缚。对美国亦无若何之不安。使所图难成，则争执之烈，必以美日为甚，英政府仍得立于中立地位为排难解纷之人，以见好于双方。此种外交策略，可谓狡猾老练已极。美政府亦明知之，然失此时机不图，则世界盟主之资格难保，而太平洋风云将愈趋迫切。日美之争执既无弥补之方，英日续盟若成，必更益日人猖狂之气，因此美政府宁循英政府之请，以和平手段谋太平洋上一时之相安。至所谓和平永久，乃不过外交官口头上之一种辞令，岂真十数年来不能安定之猜忌排挤，一旦经华盛顿会议便可悉化为云烟耶？国际间对待心理与其所处之环境，断无若是之易变者。英美之观念既如此，其于太平洋上所欲解决之国，吾国实首当其冲。西伯利亚及太平洋上诸岛犹其次焉者。其所注重对手国则为日本，在英美之意见上，现方有一共同之点，即对于吾国一切施设概取一共同管理态度。自大战终了后，世界强国已属无几。东亚问题，更握于四强英美日法之手，虽意大利亦难望有若何发言机会。惟关系之国家愈少，彼此之利害冲突亦愈多。使无一共同调解之道，则终难免于破裂。故"门户开放"、"利益均沾"之呼声，自战后益高。但呼声中之成分，与战前却已大异。战前之所谓"开放"，所谓"均沾"，不过彼此以此为监视要挟之具，而成相持不下之局。结果监视稍一懈弛，则强而有力且有余勇可用者，必乘机破此均势之局。大战中日本之行动，已足为此举之佐证，使英美领受极大教训。是以今兹策略，均一变向日彼此监视态度为共同管理。此实进一步之主张，较彼此相持之局实已获利多多，而所谓"均沾"，所谓"开放"，更能十分做到。战后之新银行团，即本此意旨而发起者。日本本为反对此种策略之国，因共管之局实现，则特殊利益与特殊地位即难存在。英美本忌其特殊，故以共同管理之说制之。乃日本于此决不放松，致新银行团代表在日本赞许多解说，始获将此计划之初步实现。然而日本已往所得之特殊利益与特殊地位，新银行团固已默许其存在矣。新银行团特不过一经济侵略政策之初步，其成立尚费如许周折，则今日英美所欲谋之共管办法其实现之期，彼必更难于新银行团之存立。日本政府于此知之甚审，论县衷曲，彼必不愿共管说之实现，而有碍其单独侵略之进行。然大势所趋，苟难于阻挠，彼亦必顺水推舟，另谋相当交换条件，如其加入新银行团时之态度。八九月间共管说之盛传于日本，固为日本人藉此以挑拨中美之友谊，然其用心，更别有所在。在日本方面着想，彼以共管说若得实现，必须经日本之赞助方得畅行无碍，果尔，则日本必有所得。否则亦可于此大行宣传之时，使英美知有所惮，而不复提交华盛顿会议，则东亚问题，彼必可仍继续居其主宰之地位。故共管说云日人赞成亦可，云日人不赞成亦可。观林权助"至一协定地步，并寻某种共同根据"之言，则知其说得含含糊糊，正所以表示其半推半就之态度也。且中国之内乱，成于日本人之手者十之七八。日本一方于世界尽情宣传中国内乱之危险，一方又竭力助中国内乱之延长，其用心之险，自无与比。其所以极力向世界宣传者，重要意旨无非欲破坏中国在列强中之信用，使华盛顿会议中国代表不得有所声诉。然宣传过甚，则益足以使共管说愈获有有力之根据。故谓日人纯粹不赞成共管说者，亦非事实上之真相。国人于国内苟注意于东邻之各种舆论，即知吾之所推测者非尽谬误。至有人谓共管说系属日人造谣，此亦不免武断太甚。"共同管理中国"之名词或系日本人造出，若共管之起意，则实起自英美。国人倘于两年来新银行团内部之组织与其运用上有所考虑，则共管说之发生，便知其不为无因。英美共管中国意旨，首重经济，实则战后亦惟有此经济之消长为能制人死命。至于政治军事等，彼等皆认为是乃枝叶问题。其于新银行团之组成固已费几许心血，惟其于运用上殊感不便。观两年来该团之不获发展，与不足以转移中国政府之施设便可证明。故彼等现在所谓之"共管"，乃求进一步而能获有指挥中国财政之全权。爽直言之，便是共同管理中国财政。

以今日中国财政之紊乱，据新银行团之核计，至民国十四年六月便将破产，迟早终须受列强之处分，则彼等今日之见地，亦正有其根据。前昨两日英法报纸遍载华盛顿传来消息，谓中国代表团九十余人已将抵华盛顿。同时美国半官式之报告，已谓共同管理中国财政事必将于此次会议中解决。此信果属真耶？吾人为民族存亡之念所动，当含满眶眼泪，而希冀此信之不确。若细察此近两月英美外交界人论调，与其年来对于东亚事件之存心，则此议或终难免。吾人处此，已属最险期中！稍一不慎，便有覆国之虞。共管说为吾人绝对难承认之事，然持之过激、则日本必乘隙而入，助吾人以反对，而保其固特殊情势，是结果必不免亲日之嫌。而山东问题，二十一条亡国条约〔３〕，更将因之葬送，无丝毫抗争之余地也。若用光只及于山东问题与二十一条款，结果必致日本以此两事为承认共同管理中国财政之交换条件，而吾将两失。前日加拿大传来消息，云日本代表领袖德川公爵已于本月二十九日抵彼，其重要之宣言，即云中日间之单独问题，为留待彼此直接磋商，毋须提交华盛顿会议。林大使之演说亦云，"有许多问题如吾人之所听闻者将不复在此会议中讨论，因此问题将另俟解决于来日。"是非专对吾国所欲提交之山东问题与二十一条款而发者耶。吾人今日之态度非常难处，盖已立于四面楚歌中。昔日巴黎和会〔４〕，尚为专对日本一国，已竭吾全国之力，始获有不签和约之效果，今则对日为一事，对英美诸国又一事。对日问题，无法争回，则东亚永无宁日；对英美之共管说无法打消，中国一切施设，更永无自由之可言。此两事不幸而均无争回之望，则英美日法必已打通一气。彼等所视之太平洋风波将因以小静，而吾东亚一片土必将遭大劫矣！故华盛顿会议所以能予人以抱乐观者绝少，证之以吾国代表之人选，更不免于亲日派之插足，是前途尤多黑暗之恐惧。兹以吾意先断日本代表在华盛顿会议所取之手段如下。

对于列强者：

（一）必极力赞助裁减军备之提议，且日本愿为首倡者，但必须获得交换条件及一切保证。此事日本代表德川公爵及加藤海军大将均已有类此意见之言论。

（二）对于英美整理中国财政意见，取赞否不明态度，以冀从中获得他项利益。

（三）对于列强在东亚利益均沾之主张，表面上极力赞成，暗中则以保留其所已得之特殊利益为要挟。

（四）对于英日续盟问题，第一步要求美国加入，成为三角协商，使蓝辛石井之协定〔５〕更加一层保证；不成，则必求得美国之谅解，而使续盟之事得以于此次会议中决定。

对于吾国者：

（一）极力破坏吾国国际间之信用。

（二）勾结吾国亲日派之外交代表，挑拨中国与列强之友谊。

（三）反对山东问题与二十一条款问题之提出。

（四）利用种种国际间不利于吾国之机会，施行威吓利诱之策略。

日本政府外交策略向以目的单纯、手段复杂见称。今兹会议，彼必仍不免于运用此种惯例。如吾上所列举八项，概括言之，仍一对华问题耳。其四方八面之呼应，已足供其指挥而有余，正不必如欧和会中提出人种差别案以为抵制而惹美人之反感也。吾此通信至国内时，华盛顿会议已将开会月余，则吾之所预测者，必可得一证明，是耶非耶？吾固不能预知，但吾甚希冀吾言之过当，而中国终得获有发展之机也。然吾终不免一最终之恐惧，即会议开后，如非共管财政说之提出，即中日交涉案暗中打消，其甚者便为迫中国代表签字于列强均势之协定上也。

＊原载一九二一年十二月十六日、十七日天津《益世报》。

注释：

〔１〕华盛顿会议又称"太平洋会议"，是第一次世界大战后，美、英、日等帝国主义国家为重新瓜分远东和太平洋地区的殖民地和势力范围由美国建议召开的国际会议。一九二一年十一月十二日至一九二二年二月六日在华盛顿举行。参加者有美、英、日、法、意、葡、比、荷、中九国。会议根据美国提出的所谓"各国在华机会均等"和"中国门户开放"的主张，缔结了帝国主义共同控制和掠夺中国的《九国公约》以及共同镇压远东人民，首先是镇压中国人民的美、英、法、日《四国公约》等。

〔２〕伍廷芳（一八四二～一九二二），广东新会人。一八七四年留学英国。一八八二年起入直隶总督李鸿章幕府十余年，多次参加清政府的外交谈判。辛亥革命时由起义各省推为外交总代表。中华民国临时政府成立，任司法总长。一九一六年黎元洪委任为外交总长。曾任孙中山的护法军政府外交部长。

〔３〕"二十一条"是日本帝国主义利用第一次世界大战的时机在一九一五年一月十八日向袁世凯政府提出的旨在独占中国的秘密条款。这些条款共有五号，分为二十一条。主要内容是：一、由日本接管德国在山东所掠夺的权利，并加以扩大；二、承认日本在南满洲和内蒙古东部享有各种特权；三、将汉冶萍公司改为中日合办；四、中国沿海港湾岛屿概不让予或租予第三国；五、由日本控制中国的政治，财政、警察、军事大权，允许日本在湖北、江西、浙江、广东各省之间修筑重要铁路，并承认日本在福建享有投资修筑铁路、开采矿山、整顿海口等优先权。五月七日，日本提出最后通牒。五月九日，袁世凯政府对日本的这些要求，除声明第五号要求的一部分"容日后协商"外，一概加以承认。后来，因为全国人民的一致反对，以及各帝国主义国家在华利益上存在矛盾，日本的这些要求没有全部实现。

〔４〕巴黎和会指第一次世界大战结束在巴黎举行的国际和会（一九一八年一月十八日～六月二十八日）。参加者有英、法、美、日、意等二十七国，中国作为战胜国亦参加了和会，苏俄未被邀请参加。会议由美、英、法三国操纵，经过激烈的争吵，签订了《凡尔赛和约》、《国联盟约》，还秘密拟定了武装干涉苏俄、瓜分苏俄领土的计划。当时中国人民为反对和会无理地将战前德国在山东的特权转交给日本，掀起了伟大的"五四"爱国运动，中国代表没有在和约上签字。

〔５〕蓝辛-石井协定是一九一七年十一月美国国务卿蓝辛和日本全权代表石井菊次郎间的外交换文。换文中美国承认日本在中国的"特殊利益"和两国重申关于中国的门户开放政策和机会均等原则。它是在中国问题上美国和日本达成的交易。

