# 华府会议中之英法战略（一）（巴黎通信）

中文马克思主义文库 -> 周恩来
华府会议中之英法战略（一）（巴黎通信）
（一九二一年十一月二十日）


英法两政府之抱负
 
　　月初通讯，吾曾预测英法两国政府代表临华府会议后所持之态度。今会议开幕将三周矣，其所作为，殆皆不出吾人之所逆料。原英政府兹次计划，早于华府会议初开幕时昭然揭示于世界。而法政府之所希冀，尤根据于其战后之国际政策，无或改变。吾人苟稍留意英法两国间一年来表现之政情，便知此次华府会议中英法两政府代表所给予世界之印象，为无足怪矣。印象中之最大者，为英法政策之冲突，换言之即英法大陆政策之不谐是也。

　　一年来英法两政府于欧洲大陆上所施行之政策，殆无不此是彼非，此非彼是，极其冲突之能事。此类事变，吾已于过去通信中，数数言之。今兹华府会议主动者为美国，讨论问题之范围又多着眼于远东，西欧舆论于英法彼此间之态度，在开会前多略而不论。盖以为裁兵问题英法无冲突，东亚问题，英法无龃龉，会议场中当能互相提携，以求太平洋上之风波安定。希望如此，不图事实上终因两方根本见解之不同，一经接触，仍复格格不能相入，不仅不能相入，且更不能相容矣。华府之会议未终，裁兵与远东问题，百未决一，而英法之不谐，已喧腾于大西洋两岸。社会间舆论之不平声浪，近一周中，盖已充满于巴黎伦敦市上。而两国执政要人又复从而助长之。欧洲诚属多事之场，其事由来，近因为裁兵问题，而远因仍本于大陆政策之互异。当会议将开时，法总理挟其满腔热望，远临华府，其最大之希冀，在以欧事烦美政府加入解决。于裁兵一层，则视英美能担保其防御与否为交换条件。简言之，即财力与军力均盼望有一确实之国际保证，自华府携归也。法政府此种观念及其企图，已守之经年而未变，此次白里安氏亲自出席，实欲乘机一展其抱负。其所以成此观念者，根本动机由于惧德及国内经济界之恐慌。因惧德遂欲以暴制暴，因经济恐慌遂强迫德人交纳多数赔偿金，以谋救济。此种极不经济不安定之防御办法，在吾外人观之，实病其至不彻底。在法政府自身，按其平日施设而论，似甚以此为满意者。然他方观其求助于美之急，则又似其亦颇知此种举措为不甚可靠，但在他人未必相助之先。法政府乃仍不得不保持此种愚策，其嫌疑所及，穷兵黩武之行动，遂深为世所诟病，美人因之，更不欲多所过问于欧事，英人因之，乃常以极相反之政策与之相追逐、相煎逼，相持既久，至兹次会议遂益显明。本来华府会议之标题，虽为裁兵与太平洋两问题，但在欧洲人眼光视之，总希望会议中能加入欧洲事件，而以财政状况为最急。法政府为此盼望不待论矣，即在英政府亦未尝无此想望。观开会前英伦银行家及英政府中一二要人所发之言论，便知其然。会议既开，美国务卿休士〔１〕首以裁减海军军备之议案提出，且详述英美日三国应减应留之吨数，其手腕之敏捷，颇足以震动一时。隔三日会议再开，英总代表贝尔福〔２〕氏代表英政府为接受美国提议之演说，干预定之减留吨数上，云将略有变动，至潜艇则主张多加裁减。日本代表同时亦声言为议案大体之接受。自是以后，公开之会议遂暂停止，而日日筹议于特别委员会中。又数日英政府忽有停造现在建筑中四大主要战舰之通告，又惹起世人之一时注意。此数场开幕剧，颇似英美于事先曾略有商榷者。以表面之外交经过论，英伦政府曾数次要求美政府于华府会议召集前，在英伦先开一太平洋问题预议会，美政府却之，议卒未成。今会议开至十余日，闻于太平洋及远东问题，日聚九国代表议于秘密式之特别委员会中，为"利益均沾"变相之谋，至今犹未能将具体之大纲议出，是知公共集议而各有所谋之难。然裁兵会议开后，不过三五日，便已粗有头绪。此中实有可寻之线索，英美既有所商榷，对象中，日本乃为难处之国。观其争论于主要战舰三国比例之当改变，便知日政府心中已极不满意于将来五与五与三之比例矣。

　　日本东京各报之舆论，闻多斤斤较量各舰吨之多寡。且日政府又极力催促现在建筑中之三大主要战舰急速造成，以图幸免议题解决后停造之损失。此种态度，既极招物议，且亦足证其心中有所怯矣。日本当此难关，其惟一之希望，乃在英美能容许日本增加比例吨数之要求。所谓拒绝裁减，继续建造，已难出诸日代表口矣。日政府受英美联合之"强迫实行"、其不能直言反对者，乃由其无辞可借之故。故裁兵问题会议，在日政府之心中实不愿加入。此固不仅裁兵问题，即太平洋及远东问题又何莫不然。但在吾个人观之，彼对此两问题之怀疑与恐惧，前者实较后者为甚。缘后者为解决他人之事，尚容其借词要挟或拒绝，而前者乃其本身问题，英美且又合演此剧，宁不使其心中忐忑。日政府既不愿加入，热情势所逼，却又不得不加入，此实日政府外交最困难之时。

　　日政府如是矣，其他方尚有急于加入讨论，而竟为英美视线所未及者，则法国是也。法总理携其热望以临华府，美英乃以裁减海军问题冷淡之。关于陆地裁兵事，美代表又暂置不议，专俟法代表自为提出。论陆军军力，以四千余万之法人，拥有八十余万之陆军，今世实无一国足以与之比拟。此巨大之军额，使法国不躬自倡导，他国何能言裁？各国对待法国之心理如是，在法政府自视，则裁兵非易，须贵有列强间坚确之保证以为其后盾。兹议非法国所愿提出者，宁待他人提议减裁陆地军额时，持此以作交换条件。法人平日主张，本多直率无隐，此事美政府尤深知之，故益隐忍不发。美政府代表之能忍待，由于事不关己，而法代表远临万里，开会十数日，一无建树，问心岂能自安。终于不复忍待，愤而有本月二十一日之演说。由此一场演说后，英法间政策之冲突，遂益形显著矣。

白里安氏之裁兵演说

　　法代表之演说，属于白里安氏。演说之所在，则为第三次裁兵会议之正式大会也。先数日，白氏已宣告其行期定于十月二十五日，会议未终，法兰西所欲提议之议案，尚一无所成，白氏便欲匆匆上归国之道，其悻悻然不满意于此次会议之态度，已可想见。白氏既将去矣，则是番公开之演说，必大有用意在，事前已为一般舆论所公认。二十一日开会，白氏首致词曰：

　　吾今得于诸君之前有所陈述，吾及吾国代表实觉有无上快慰。吾人所携以赴华盛顿者，实为广大之牺牲，吾人颇觉此为吾人保护之必需。吾人解除吾人之武器，将于平和安定之再造为快乐的贡献。不幸，吾人竟不克言此；不幸，吾人终不得以言此。欲图平和，于此当从两方作起，其一为吾人，其一乃为吾人之邻人也。且欲图平和，吾仅就陆地裁兵而言，若仅谋减少精锐，限制军械，是犹嫌未足，必于此外另有一不可轻视之考虑，而其事实为平和之意图，即吾人必当有平和之空气是也。裁减军备，道德方面当与实质方面并重，且吾尤希望为君等证明者，欧洲之于今日，实已陷于不安之重大成分中。而法兰西尤因其本身安定之观感，益受此种情况之束缚。

　　此开场数语，已足表示其论锋所指，与法兰西不允裁兵之态度矣。其下更进一步指明德祸口亟与法国所以不得不保持现有军额之苦衷。其大致如下：

　　有人固曾试为传说，法国若永久保持其现有军力，其内幕中必欲计划一军国霸权之建立，以袭帝国主义德意志之后。此种诬词，或足使美人坚信，唯对于吾法人则实为一残忍而又悲惨之担负，设于此有一国愿倾其全心，施其全力以图贡献此平和，则吾法兰而实足以当此。

　　概自休战以来，彼曾经历几多之不幸，而犹静待彼所希望者实现，一年中彼曾冷观德意志辩护其责任，拒绝赔偿，拒绝裁兵，于此种种可怒之情状下，彼均守其平静之态度。缘彼本无所恨怨于其心中，而尤愿从事于法德间血战纪录告终之事业。

　　吾人有所警告者，德意志至今实犹有一不安之势力，其初名为保安警察，其人数十五万人，其组织约为全体有职守之官吏。吾人曾要求其解散，嗣既解散，而其他之组织又起而为之代，其名曰保卫队，具有精密之同样登录簿，其数当已具有二十五万人，日日从事于战争再起之准备训练。犹有言者，他德意志自战场归去，投入私人生活中之七万军人，至今固犹有团结，且日夜希望其组织中之计划，使此伟大之德意志再生时能有所实现。有一事实足以使君等获一极敏捷之观念，知此等军力实有可动之势。当上西里西亚问题未决时，德人于数日间即集至四万八千携有旋条枪、机关枪、且获有装甲车之人，此实为不可侮之精锐。故德至今日，苟遇有变故，仍能于数星期间，立集其旧有之六七百万军人，彼实有登录簿足以核计彼等。

　　白氏声诉至此，盖已将其惧德要点悉行披露，于乃转而向美人曰，吾今将转语此伟大之美利坚人民，君等已将转君等之眼，以离此种危难耶？君等已将抛弃所有权力以救君等之生命耶？但何者为再进，以完成君等之荣誉，君等更将何为？于此使有"人将不为，美亦不为"之言者，吾知其必非美利坚之市民。此数语实极力表其希望美人勿抛弃欧事不问之至意。其后又转而叙述德国军人势力犹存之实况。其取以为证者，乃为德意志旧帝国之参谋次长鲁登道夫〔３〕，彼言鲁氏犹为今日德国不可侮之人。且彼深信鲁氏足以煽动未来之战祸，而德国旧日之军人更人人具有好战之野心。彼言德国今日之军额虽为十万，而暗中实仍具有七百万精锐之军力。其军械虽限制，然黑幕中难保无私藏私造之事。声诉德人之野心既毕，终乃归论其不能裁兵之主张：

　　吾已引吾国入于和平之道，惟设使吾行之过急，则吾必不免为一犯嫌之卖国者，于将来据法政府之计划，必可使裁减军额之事证实，至其时当能减低一半军额。

　　法兰西满心愿望此平和，但彼不能尽力于无所防御之中。设使其前日在战中之同盟国与联合国已向彼宣言："使汝再有所抵抗，吾人仍当助汝防御"，则此时地位或将有所变异，然法国终不能希此，彼必当自恃其力，彼尤不应与道德上有所隔离。

　　白氏演说之大概，略如上述。其最后一段固已明明宣布法人非不能减兵者，特须列国肯为之保证耳。其所谓道德上之隔离，乃自掩之辞。白氏言毕，英代表贝尔福氏起为酬应之答辞，其言大意谓法总理之演说，彼实具有无限之同情，今日英人得以优游重理其旧业，实出于法人不辞防御之赐。言虽誉扬，然都空泛不着实际，是法总理最后保证之希望，英代表已暗示拒绝矣。次之为美代表休士之答辞，休氏谓"为防护世界自由之国家，无所谓与道德上有所隔离"，其言虽似稍近一层，然不着实际则一也。次日美国舆论于白氏之演说，大为赞扬，于暂时不能裁兵之苦衷，亦深表同情。法人获此，其怨愤之气，自可稍解。但此种舆论，究空洞不足恃也。会议中列强之态度，果能容法国崛强坚持到底耶，是又在难测之数。保证希望若绝，则法政府惟有实行其不能裁兵之坚决主张，于此法政府固认为势所迫也，非出于自愿。然隔岸之英人却不复为法人谅矣。法总理演说传出，英报在美访员殆无不有讥刺论调传达本国，而英伦岛上之舆论，更肆意攻击。有谓法人欲于欧陆建立伟大之霸权者，有谓法人此举实足激德人之怒，而隐伏将来之祸根者，有谓法人不裁兵英人减少军舰为无用者，更有谓法人穷兵黩武之念，非尽防德其心目中盖有英国在也。此最后一论，华府会议特别通信员魏尔斯即持此论调以发表于英美各报。斯不免有神经过敏之嫌。法固有所不慊于英，英亦何尝无所怨于法，两国间之龃龉，一年中几成寻常茶饭。两国政府虽防忌甚严，然必谓有借重武力于将来之意，不但法今日断非英敌，即使当日拿破仑〔４〕时代之雄心犹存于法人心理中，吾恐其惧德之念，亦足以使其抗英之念打消而有余也。英既讥法，法乌能忍？于是两方之笔战乃又开一幕。笔战未终，而更有舌战继之。掉此舌者，且更为两国政府之要人。英法真为好起冲突者矣。今夜已深，吾明日当继叙此舌战之事实于第二篇中也。



　　＊原载一九二二年一月二十日、二十一日天津《益世报》。

　　注释：

　　〔１〕休士（一八六二～一九四八），美国共和党人，曾任美国最高法院首席法官。一九二一～一九二五年任国务卿，曾主持华盛顿海军裁军会议。

　　〔２〕贝尔福（一八四八～一九三○），曾任英国首相（一九○二～一九○五）和外交大臣（一八四八～一九三○）。首相任内曾策划缔结《英日同盟条约》和《英法协议》。外交大臣任内曾致函犹太复国主义者联盟副主席、银行家洛希尔，表示英国政府支持犹太复国主义者在巴勒斯坦建立犹太国家。这一信件后被称为《贝尔福宣言》。

　　〔３〕鲁登道夫（一八六五～一九三七），德国将军、军国主义者，法西斯总体战理论创始人。第一次世界大战时，一九一六年任作战参谋次长，协助总参谋长兴登堡掌握德军指挥权。一九一八年被解职。一九二三年与希特勒共同发动"啤酒店暴动"。著有《战争回忆录》、《总体战》等。

　　〔４〕拿破仑即拿破仑·波拿巴（一七六九～一八二一）。法国资产阶级政治家和军事家。一八○四年称帝，建立法兰西第一帝国。他的一生征服过欧洲的许多国家，但一八一二年进攻俄国遭到失败，一八○四年反法联军攻陷巴黎，被放逐于厄尔巴岛。一八一五年再返巴黎，建立百日王朝。滑铁卢战役失败后，被流放于圣赫勒那岛。一八二一年病死该岛。



