# 华府会议中之英法战略（二）（巴黎通信）

中文马克思主义文库 -> 周恩来
华府会议中之英法战略（二）（巴黎通信）
（一九二一年十一月二十九日）

白里安之最后主张

本月二十一日华府公开之会议，白里安氏既代表法政府将其对于裁兵会议之意见宣布后，一般舆论咸谓此乃法人声诉苦衷之演说，然犹不得谓为法政府向裁兵会议提出之议案也。且二十一日裁兵会议之开，美总代表休士固明明声言此为陆地裁兵会议，而美政府于此当继续保持其旧有之少数军额。国务卿休士氏并云，美国当欧战初停时，美国陆军实有四百二十万人。然自休战条约签订后，即起首解散，一年中便已陆续归田，现时合格之军额，只限在十六万人以内，故美国于陆地裁兵事，其自事实无可裁减。美代表之为此言，意在促他国军额众多者之反省，首当其冲者乃为法兰西。唯法自白里安氏一场演说后，其不保证便不裁兵之主张，已昭然若揭，使美国能慨然予以保证者，则法国政府之态度，当亦能随之改变。然而今日之美国执政者，终未易言此，于是法国最后之议案与其坚决之表示，遂终不得不出于裁兵委员会中。白里安之声明有云：

吾可使吾之军队减至百分之三十三，以当君等减少舰队至百分之一，即此已足为法兰西对于此次会议之问题，吾甚欲使其完全而又绝对的实现。且吾犹有一同样意义之愿望为诸君告者，即设使诸君必立一特别委员会以研究其效力，则吾将不复代表于此，诸君可自为讨论于法兰西缺席之时。然此外亦有一法，足以使吾法政府接受履行裁减军额之提议，即君等当求得一同盟与保护之条文于吾人也。使君等而果有此种提议，则吾法兰西当倾耳以听。

此外法政府对于裁减海军之主张，本非重要之国，初无足动世人之听闻。惟自会议开幕后，既遭美政府之冷淡，复受英人之讥刺，遂忍无可忍，别开生面，于保持陆军巨大军额外，又有海军吨数之声明。其主张乃以主要战舰与日本同其比例，而潜航艇则以英国为其比例。此论一出，不仅英美讶其要求无厌，即日代表亦疑其有临日本而上之野心。法目前海军之劲敌为意，意代表因亦有海军吨数与法相埒之要求，是英美日之海军问题未决，而又益之以法意之相搅，解决声中又多一层困难矣。

捕获沙丁之诮语

法国之海军吨数比例案提出后，英美舆论多讶为意外，而英国舆论尤多下攻击之论调。于是白里安氏于其去华盛顿之前一日，复为此事有所宣言曰：当不列颠国欲保留其主要战舰至五十万吨时，吾固不能言此为对法用也，英吉利固有美利坚为友，而日本为其同盟，且又当俄德无海军舰队之时，假使英人愿用其主要战舰以捕获沙丁（鱼名），则吾人当用此潜航艇以研究海底植物，否则英国殆为反对一未知数之Ｘ，以留此为保护者。则吾法国亦当以此为保护而反对Ｘ。主要战舰值钱甚巨，彼等当为其富者，潜航艇需费不多，吾人乃为其贫者，英国极愿毁减潜航艇，吾人殊不能赞成，若英国愿毁弃主要战舰，则吾人当立予以同意。

此一段话，完全为针对英人而发。盖法国之海军计划，重在增筑潜航艇，此英人大不愿者。美国务卿休士规定潜航艇为八万吨之提议，英国犹嫌其多，岂能愿法人亦增至此数？英国于大战中，备受德国潜航艇之苦，致其巨大军舰多无用武之地。而各洲商业上之联络，亦因之蒙极大之损失。今德舰消灭，各国潜航艇又建造不多，乘此裁减军备之机，一举而毁弃之，乃其大愿。惟所难望实现者，乃美日之观念不同，潜航艇之功用，于英虽为害多而利少，于美日之对待，则颇具效力于太平洋上。因此英国极力主张减少其吨数，而美国则持之甚坚，不稍退让。法国睹其利，乃以八万吨之同样比例请。此举不仅显示与英国为难，且就英人眼光观来，直谓法人有防英之嫌。其主要着眼点，乃谓德俄已无舰队，法人筑此潜航艇果将何用，非对英而谁归？此论在英国几乎一致承认，普通报纸多著论相诘，偶有三四表面表示联法之报纸，尚能为法之原谅。因此英国文学家威尔斯之华府通信，遂为英伦巴黎两《每日邮报》停止登载。盖威氏攻击法人处，过嫌激烈，亦可谓过嫌率直，颇妨其报纸之营业也。

英人谓法为对英，而在法人自解，则谓法人亦非无海权须保护者。以地中海情势论，北非与小亚细亚在在足以引起争端，使无巨大海军力以镇慑之，法国属地之前途殊甚危险。法人此言，自亦实情。惟地中海之风云，又岂仅一法国属地之危险？其所关联者，法希问题也，法土问题也，法意问题也，何一不足以激动风云。今法土交绥矣，法希之关系当更恶。法意于地中海亦非能相安者，法意两国代表且公然指出之。彼此相忌相防如是，然则法国之不能忘情于海军力之增长也可知。惟必谓法国此举，一无防英用意，则地中海之最大势力范围，果为谁属？法意希之争，断不能逃于英人关系以外，而近者意国联英政策，又日进不已，此亦足使法人生惧者。

总之，欧事乱如麻，各国除自身外，其彼此相交相攻之点，迄无一定。吾人欲于其中，必寻出防御联络所向之迹，则舍德法世仇，可以略明其对待方法，他均不易言也。英法今日之不谐，已彰彰明甚，然一旦苟有变动，仍可复为大战中亲密之联络，此亦可敢断言者，惟今日尚非其时耳。

英外相之愤言

白里安氏在美既因极力表白法国所持之态度，故对于英人之讥诮与攻击，遂不能不有所回报。而同时与此回报作响应者，则有英外相克寇松〔１〕之演说。寇氏于本月二十四日在伦敦联合监护会午餐席上发表其个人政见，中有云：

设使吾人熟视此陆上巨大军额之堆积支持如故，则海上裁减军备之事将归无用。一种公例，必不当仅使一国实则，或虽多至两三国，当使各国按其地位与能力为比例，以追随此公例之下，此决不应仅使大不列颠接受允许为此牺牲，而任他人之逸去。设使吾人真愿裁减吾人之海军力者，则亦当使永无其他国家可以被允许以建筑其他攻人之机械于空中或海下，因此种机械足以使吾人之牺牲为无效，尤足以远离吾人当世立法之自豪地位，而予吾人以蒙有冒险之危境。

况此海峡，吾人伟大同盟国之实力与其保御，实当包有一种情状，即世界之良知与世界之联合实力。......吾人应导引德意志人为国际场中之平和人员，假使诸强亦已结合，尤无须强迫此条约，但求廓清此报复政策不再为彼等所默认，则彼等之助此德意志以偿付其赔额者，必克表示其真实与信用。大不列颠与法兰西、意大利之互相团结，固已如是其长矣，吾尤愿此结束之长存。

寇氏此言，虽非纯官式，但彼以外交要人发此议论，是知英政府对法国裁兵意见，已明示极端之不满意矣。

白里安氏之回声

英外相之言既出，好事之新闻记者，乃持以叩诸白里安氏，渠将作如何回答。时白氏已由华盛顿之纽约，其答此问之言曰：吾将无所回答于寇松氏之演说，困吾固未获得寇氏演说之正式全文也。此为外交官慎重发言之惯技。白氏盖鉴于前此因上西里西亚问题与劳合乔治一场舌战之不利，故不复再以恶声反报矣。同时彼又声言曰：吾终坚吾信心于贝尔福氏在最近华府公开会议时之声言，彼因与其他代表同为坚决之承认，知法兰西之地位其所需以保护其安全者为例外，吾英国诸友应知实在情形。德国舰队已沉海底，而七百万之德意志军士，固仍得复生而现其效用也。此数语反诘，亦颇饶趣味。当二十一日白氏演说之后，贝尔福氏因曾声言英代表对法国之苦衷，实抱无限同情。而英伦方面，竟于数日后出以反对之论调，是英政府中各人之政见不和邪，抑外交家欲擒故纵之惯技邪？证以数日间之情形，乃知当日贝氏之言，实出于应酬，且事出仓猝，事前既无磋商，乃不得不以空洞不着实际之语慰法人也。至寇氏于英伦之言，殆有所为而发，其言一出，法国舆论界为之哄传，而英代表之在华府会议中者，其态度亦骤变。此关于英法之外交策略者至大。法总理虽以未得寇氏演说之正式全文为辞，不发表若何批评，然其声言中，所谓德国舰队已沉海底之言，固已明明诘英人保留主要战舰究作何用矣。于此英人或亦不难答曰，吾人之保有主要战舰，盖为保护吾人之商业用者，非若法国之保留增筑潜航艇，舍战事外殆一无用处。此议英国报纸已有持之者，英伦《星期日时报》即持此论以攻击白氏，两国舌战笔战同时开场矣。舌战因外交作用故，或小试其锋便止。今白里安氏已在道中俟其归来后之第一声，便知今后两国于华府会议中所取之态度究何苦矣。至笔战情形，则英国报纸除少数保守联法政策者不事攻击外，其他报纸殆无不认法政府之恐德系根于军国热狂者。法国舆论则除作恶声回报外，多为其自己解说，然亦有攻击政府政策之不当者，是又属之于社会主义者所为矣。两国关系之究竟如何，亦决非此次华府会议中所能解决、所能确定，是则又由其数百年来之历史关系，有以养成此若即若离之情状也。

＊原载一九二二年一月二十二日、二十三日天津《益世报》。

注释：

〔１〕寇松（一八五九～一九二五），英国保守党领袖之一。一九一九～一九二四年任外交大臣，曾参加策划武装干涉苏俄。

