# 无产阶级革命的俄罗斯

中文马克思主义文库 -> 周恩来
无产阶级革命的俄罗斯
（一九二二年）


　　世界革命的钟声自从在北欧之野响起来后，到现在整是五个年头了。在这五年中，俄罗斯无产阶级努力创始的功绩和孤军转战的精神很值得我们予以极大之注意。现在我们当这五周纪念声里，特将往事追论一番，此盖不仅能使我们知而生敬，且更将闻风兴起，好来完成这世界革命的伟大工程。
 
十月革命的使命

　　在过去历史中，革命的事件本屡见不一，最大的如法兰西革命，美利坚独立，也颇能震动一时，各有其历史上的相当价值，但一持与俄国十月革命相较，则广狭远暂的不同，又不难立见。前二者革命的范围只限于谋各个民族的有产阶级的利益，而后者便转向全世界无产阶级身上 来了。有产阶级的革命，他对内要推倒封建制度或君主独裁政治而建立民主主义的代议政治，垄断资本，运用工业革命后的科学能力来图私利；对外实行侵略的政策，以维持其本阶级在国际间的优越地位。如此情形，支持了一百多年，现已算入到他的崩溃期了，过去四年多的大战，近四年的世界破烂情形，便是他的实证。恰巧在这期中，俄罗斯的无产阶级革命便应时而起，这个革命所负的使命整个与民主革命相反，在历史上只有一八七一年巴黎共治团能取来与他相比，只是巴黎共治团不过是无产阶级革命史上的一朵昙花，稍现即灭，而俄国十月革命确为全世界的无产阶级奠定了革命始基了。再，十月革命之所以能与旧日革命相异的，乃因其立足之点在于全般的社会革命，而非仅限于一国一种一阶级的革命。无产阶级革命起首，本含有阶级争斗重大意义，且因其发动于一种民族，战国力的运用，也并不可缺少，但他的革命进程，却决不以此自封，且不得以自封。共产社会完全实现时，人人都是无产者，还有什么阶级界限可说？世界革命完成时，全世界的无产者都联合起来，他们还要什么国和政府？这样子一个革命，经济和政治革命实做了全社会革命的先锋两翼，除掉无产阶级外，谁能担当起来！俄罗斯十月革命实在是负有重大使命，不过他才做得世界革命的起首罢了！季诺维也夫〔１〕说得好："在俄国并不是一个共和问题，只是一个革命问题。""俄罗斯革命的不朽之功事实上在他为世界革命的起首啊！"

革命的原因与其成功之道

　　一个革命的爆发，其内幕总要含有生产状况变动和阶级争斗的重大意义在内：这本是马克思的唯物史观和革命学说所尝召示我们的。俄国十月革命之先有三月革命〔２〕，此两个革命的来源甚远，从产业观点上看来，十九世纪的农奴制和其后的地主制，与工业发达后的生产力变化和外资竞入有极大关系。其在阶级观点上，则俄国历来的政权都只是操于俄皇和贵族高僧之手，中等阶级和小资产阶级除掉依附权贵，阿其所好外，很少能崛起自组成一雄厚的有产阶级以与俄皇贵族对抗的。农民虽是占全俄人民的最大多数，但他们因产业情势和大地主的压迫终不能有什么组织，不过他们反抗地主的心却总是热烈的。至劳动阶级则自工业盛兴以来，他们的组织和活动能力，的确是日见进步，外方更加以俄皇专制的压力与他们以种种练习反抗的机会，他们的战斗力遂益加伟大，终成为俄国各阶级中的最强阶级了。此两点既明，我们再归论到革命近因，则俄皇穷兵黩武，劳民伤财，三年大战实与以直接影响。俄皇室的亲德嫌疑，在民族间的憎恶性上又适足以增其助力，三月革命本此遂抢得民主革命的一时胜利。惟是另一方考之实际，当俄皇尚未宣告退位之时，彼得格勒实已有劳兵苏维埃的兴起，继之者为莫斯科苏维埃。三月革命告成后，各地苏维埃蜂起，于四月中旬便开成全俄苏维埃会议，自是革命临时政府的举动乃常为苏维埃的向背所转移了。五月初皇冠城苏维埃宣言承认临时政府，克伦斯基〔３〕遂据之入阁而为陆长。其后，叶喀德琳堡苏维埃开始反对战争，农民会议赞助苏维埃，皇冠城苏维埃亦继起不服从临时政府，民主革命的根基乃见动摇。至七月，彼得格勒的工兵先后声言"政权归苏维埃"，形势更见紧迫，克伦斯基显出他的反革命本领，捕获些多数派的首领，镇压一时空气，更改组了内阁，他改坐在第一把交椅之上。但这种情势终是不稳的，接着便是莫斯科工人为反抗民治会议而罢工，九月中彼得格勒苏维埃更接受了多数派抢夺政权的动议，黑海舰队继着有同样的主张，至十月北方劳兵苏维埃和莫斯科苏维埃又相继响应，最后乃由彼得格勒兵工发动，于是政权终归苏维埃了。

　　这种劳动阶级组织和活动的发展情势，与农民兵士赞助之功，在三月革命至十月革命中间我们既已找出如许痕迹，惟其成功之因，尚不止此，尚有更远的肇端可说。在一九○五年的俄国革命中盛称的赤星期日便是俄都造船工人的血染成的，同时接着起的各地骚扰，造船所的破坏，彼得格勒等城和波兰诸市的兵工血战，巴库煤油矿工的大规模同盟罢工，十月底八十万铁路邮电工人的大罢工，十月立宪令发布后的普选运动，殆没有一事不是劳动阶级为之主的。且苏维埃的制度，也是彼时创生的，兵工联立的情势也由那次黑海舰队的变动而立其始基。彼时革命骚扰，差不多延长到一年之久，事虽未成，但其与人心上的刺激和旧势力的打击，已给一九一七年的革命暗伏下不少助力了，其中自更以无产阶级所得之教训为最大。总这十三年前后三番革命的因果关系来看，我们当知俄国革命中含的阶级争斗意义至为明显了，且每次革命都是劳动阶级为其中的主动力，农兵从旁赞助，而中等阶级和小资产阶级既无真实力量又无团结训练，以致宪运动民主革命均无建树，国力政权终落到无产阶级手里，使十月革命独著其功勋了。

十月革命与马克思学说

　　当十月革命成功后世人尝说共产革命不先出现于工业发达的英美，而首见于俄国，乃是马克思学说上所未曾料到的事；但这是只见其一未见其二的话，也可说人还未懂得将马克思唯物史观和阶级争斗两说打成一片来看。一般工业发达的国家，他的资本制度已不能再与生产力适合，崩坏之期本已很近，但是他国中一般有自觉性有组织力的有产阶级却不甘束手待毙，他必要千方百计来救济这个恐慌，过得一时算一时。他方，无产阶级在这决战期中，困于种种情势，一时也还未能取胜，然而这决不是无胜之可望，只是暂时的相持不下。俄罗斯虽是个工业后进国，惟他生产状况的变动已不复能与君主独裁、地主专横的制度相适合，于是乃必然地需要一个革命。恰巧应这革命而起的阶级，只有劳动者是富有阶级争斗性较有训练的战士，他们眼看着这资本战争的惨祸从恐惧的自觉中，乃终能一跃而握住了政权，造成无产阶级专政的局面，超过了欧美先进国中兄弟们向来成就的纪录。但这样，不过仅是一个革命的起首。我们当知工业发达之国共产革命虽难，革命之期实短，半开化之国则革命易而革命期长，换句话解说，便是：共产社会的真实完成总是要先见于工业发达之国的。但，这话却不是说工业后进国必须等到资本主义将国内实业发展够了的时候才去革命，我们一方也当知道在共产革命期中以无产阶级专政的国家资本来发展实业，其成效当超过有产阶级竞争的资本主义万万；后进的许能赛过先进的早成为工业极发达之国，且一方也不当忽视易于革命和无产阶级易于握得政权的时机，因此才更易促成全世界资本制度的崩坏，全世界革命的实现。俄罗斯现在已是这样地一个领路者了，工业后进之国焉得不从而效法？又焉得不看清马克思学说的真实价值？

十月革命中的一个忠实的指导者

　　十月革命成功之因已如前述了，但我们还当追想下俄国三次革命既都是劳动阶级为其中的主动力，为什么偏等到十月革命才成功呢？这不难回答，并且是很简单的回答：这是因为有了多数派--共产党--在其中做了忠实的指导，唯一的指导。俄罗斯的劳动阶级中也实只有共产党称得起他的忠党，这不独俄国为然，各国的劳动阶级中也无不皆然。当着一九○五年的俄国革命，立宪党人也多是运动中的参与者，但等到俄皇《十月敕令》下了之后，他们便都弃了劳动阶级，眼巴巴等着次年的国民议会召集了。一九一七年的三月革命成了功后，社会民主党和少数派又复卖尽劳动阶级，大踏步地走入联合内阁，讲起民主共和来了。剩下来的只有多数派他始终是百折不挠，以无产阶级的利益为他自己的利益，一九○五年，他的党员也多参加在运动中，托洛茨基〔４〕且做了一时的劳兵会长，惜因人少势弱，终归失败。他们饱受了这种经验，加以十余年亡命国外时的奔走，三月革命一来，他们便极力注意到劳动阶级的指导和苏维埃制度的运用上头。革命初起时，各地苏维埃内部政党派分子还很复杂，四月中列宁初归，便向社会民主党提出革命中无产阶级的任务以清党略。自此后，各地苏维埃的会议中，遂渐渐增加了多数派从中指导的分子，最显著的例是七月一日彼得格勒工人示威运动中所发出的"一切权力归苏维埃"口号，那确为多数派取得胜利的象征。这个口号且立时传遍了全俄，克伦斯基着了忙，竟诬多数派为德探机关，赶走了列宁，擒获了托洛茨基及其他党员。但这种压迫终无效果。九月十七日托洛茨基出狱，次日彼得格勒苏维埃便接受了多数派《抢夺政权》的动议，因是执行委员会辞了职，再选举，多数派变成多数，他开始宣布"抢夺政权"的时候已经来到。接着，列宁、季诺维也夫被选为彼得格勒苏维埃赴民治会议的代表，要求政权归诸苏维埃。十月俄都市政选举，多数派又获多数，托洛茨基做了彼得格勒苏维埃的会长。从此，革命的酝酿日熟，各地苏维埃的响应也均以多数派之动议是从；最后红旗一挥，无产阶级专政之局开始，多数派忠实指导的功勋乃得大白于世，十月革命遂得在历史上建了不朽之功了。



　　＊原载旅欧《少年》杂志第五号。

　　注释：

　　〔１〕季诺维也夫（一八八三～一九三六），一九一○年参加俄国社会民主工党（俄国无产阶级政党）。俄国二月革命后参加编辑《真理报》、《无产者报》和《工人报》。曾任苏共中央政治局委员、彼得格勒苏维埃主席。一九一九年任共产国际执行委员会主席。一九二四年列宁病逝后，与加米涅夫结成"新反对派"。一九二六年与托洛茨基结成联盟。同年被开除出政治局，共产国际亦免除其职务。一九二七年被开除出党，一九三四年被捕，一九三六年被处决。一九八八年，苏联最高法院为季诺维也夫恢复名誉。

　　〔２〕三月革命发生于一九一七年三月（俄历二月），是十月革命前俄国的第二次资产阶级民主革命，今通称为俄国二月革命。

　　〔３〕克伦斯基（一八八一～一九七○），一九一七年俄国资产阶级临时政府总理。一九一七年二月革命后加入社会革命党，任彼得格勒苏维埃副主席、国家杜马临时委员会委员。同年七月起任第二届临时政府总理，九月起兼俄军最高总司令。执政期间代表资产阶级、地主利益，对内残酷镇压革命运动，对外继续进行帝国主义战争。十月革命时，化装逃出首都，发动武装叛乱。一九一八年亡命法国。一九四○年起定居美国。

　　〔４〕托洛茨基（一八七九～一九四○），十月革命时，任俄国社会民主工党中央政治局委员、彼得格勒苏维埃主席，十月革命胜利后，曾任最高军事委员会主席等职，在一九一二年联络过孟什维克等机会主义派别，组织八月联盟，反对列宁领导的布尔什维克。第一次世界大战期间和十月革命后，托洛茨基在战争、和平以及革命等基本问题上以"左"的立场反对列宁的正确方针政策。一九二三年秋集结同伙，提出反对派纲领，要求派别活动的自由。列宁逝世后，反对列宁关于在苏联建设社会主义的理论和路线，进行反党的派别活动和破坏活动。一九二七年十一月，托洛茨基和托洛茨基分子在联共（布）第十五次代表大会上被清除出党。一九二九年托洛茨基被驱逐出苏联。在国际共产主义运动中，托洛茨基进行了许多分裂和破坏活动。



