# 俄国革命是失败了么？——质工余社三泊君

中文马克思主义文库 -> 周恩来
俄国革命是失败了么？——质工余社三泊君
（一九二二年）


　　在九月号的《工余》上有三泊君一文，名《俄国共产主义失败之原因及其补救的方法》。此文题及其内容颇能惑昧于俄事之人于一时，本志对此似不可不一加驳论。
 
　　在三泊君文题中最足惑人的便是"俄国共产主义失败"八字。俄国自从革命后直到今日纯是在共产主义革命中讨生活，这谁也不能否认。取例来说，大产业、银行、铁路等收归国有，土地交给能自种的农人耕种，废除遗产制和土地占有权，消灭有产阶级遗留下的恶制，......凡此种种，全是过去五年中俄罗斯无产阶级以革命的活动换得来的。因此活动，所以才引起内部皇党、有产阶级、自私的农人的反革命结合和国外资本主义国家的压迫行为。并且他们更互相勾结起，继续不断地来图捣乱，而各国的无产阶级又因困于情势，都按兵不动，于是俄国无产阶级的革命遂不得不独自地持续下去了。革命事业本是要经长期努力长期奋斗才能保住成效的。一国一种的民主革命，如法国革命，美国独立都是经过极长期的血战争斗才得使共和奠定，更何况无产阶级的共产革命，须全世界劳动者联合起来世界革命呢！我们若因要急观事的成效，便忘掉革命的时效，或更忽视了四周反革命的空气，则只能怪我们性急，若硬加俄国以"共产主义失败"之言是不当的。且俄国今日实行无产阶级专政，劳动会议掌握政权，从阶级争斗的根本见地来理解共产主义只有说他是成功，何得反谓之失败？我们应知俄国现正在从资本主义走向共产主义的过渡期中，换言之，便是正处在共产革命期中。

　　在革命期中，最初建设是要少于破坏的，五年来苏俄的努力多一半是用在铲除旧毒，内防叛乱，外拒强敌的工作上头。我们若肯平心静气地研究研究俄罗斯五年革命的记录，则知他们并不是不图建设的，也不是没有建设的，只是旧势力的反动迫得他们不得不在破坏上多下功夫。且他们从事破坏，又岂无意义？扫除了旧的障碍，新的制度方得逐渐实施。未来共产社会的实现，须要有共产制度为他做保障，俄国无产阶级今日的努力，乃正因要立此保障之基，所以他们的破坏才非盲目。

　　明乎此，乃知三泊君"俄国共产主义失败"一言，是极不合于事实的闲话。

　　三泊君既错立了题目，因是他开宗明义第一句便以俄国施行新经济政策为"共产主义在俄国试验失败"的佐证，这真太背事理。俄国之施行新经济政策，其在事的根据上实有极重要的来源可说。１．俄国在革命前工农业上的生产机关和工具都太腐败。２．大战发生后，生产运输机关的破坏和壮丁的损失更是直接地增加经济恐慌。３．十月革命过后反革命派的骚扰，一方既使大战中的情状愈加延长，一方更使无产阶级无暇修补此危急的灾害。４．全世界资本主义政府所与的压迫。５．落后工人在工作纪律上的怠弛。６．政府因经济的恐慌，无法供给农民以工业品。７．无知识而只图私利的农民不仅不肯供给麦子并且还因受反革命派的煽动要图反抗。总此诸因，生产状况遂呈现出一个极大的不稳，最后且更激出皇冠城和唐波省的农民军暴动，于是新经济政策乃在这种事实的要求上势所必至地产生出来。

　　事实是不可侮了，我们且再转向理的根据方面来看。在新经济政策中最受世人非难的要算是重建私人间小工商业一事。他们常爱以废除私有制一义来反证俄国今日共产主义已经失败，其实他们却未尝明白俄国今日尚是在共产革命期中，离着共产制度的全部建设尚属很远。私人间小工商业的恢复在共产社会中自然是不容留，容留了便是还没到共产社会，但在共产革命过渡期中，遇到此种情形却不足为惧。新近英报访员兰沙末曾问列宁，说有了这般小商人，他们不将觊觎政权么？并且买卖兑换的利大，握在商人手中，国家多管些无利的事件，此无论从资本主义或共产主义的见地上，全可看出有后退之虞。列宁回答他的大意是说这些小商人犹之伦敦市上的小贩，买卖虽然极好，究离着政治很远。若说他们利大，则未免忘了俄国尚是个农业之国。本年政府收入，粮税乃为大宗，农业丰收，更影响到卢布价格近来的安定。轻便工业已多振兴，国家银行近又有余裕可计，行将用他来振兴机械工业。这样情形，不仅从资本主义见地看来可以乐观，便是从共产主义见地看来，也可抱同样乐观，因为现在俄国的政权固握在工人阶级的手中啊！后退是不可能了，俄国今日已决不能走回"封建专政"之局，他只是要以国家资本主义来领路好走向共产主义（兰、列两人的问答，全文见曼彻斯特卫报十一月二十二日份）。列宁此言很可指明新经济政策在理论上也决不会妨害共产革命进行的。并且就一年多实施的效果看，也的确可以增加无产阶级国家的财富。在政策中征收农民粮税是与农民自种其地据为己有相呼应的，若农业共治园之以产业归公，则其组织自与国有的工场相同无所用其粮税了。对外通商，是现状所必须，且大权握在苏维埃政府之手，更无所恐慌于资本主义国家的诱惑，热那亚〔１〕和海牙〔２〕两会议的结果与乌尔圭哈突〔３〕对英商约的延签，不已明示我们了么？

　　以上的事理我们皆根据于经济状况的必然性和共产革命的可能性而来断定新经济政策决非能作三泊君所谓的"俄国共产主义失败"佐证。且不但不能为其佐证，我们更信这是完成共产革命促进共产主义的一条捷径呢！三泊君也肯研究此事实么？

　　上述两点既明，三泊君文中一切论点遂多失了根据，其所谓乐观派的话，我们既可置诸不论，便是悲观派之言，也多受了各国有产阶级蒙蔽、社会党人欺骗而后发出来的"杞忧"，其实俄国今日的劳动阶级岂真是"除了换过几个统治者外实际上一无所获"么！凡稍注意俄事的人，当皆知其谬！

　　三泊君闻也是赞成阶级争斗的人，严格说来，既赞成阶级争斗，则因缘而生的无产阶级专政与专政期中一切必然的设施，有何可以反对呢？除非他是站在"有智识的人仍然多属于资本阶级"的地位来说话。

　　三泊君所最批难俄事之点是"中央集权"与"产业国有"。中央集权为无产阶级革命期中所必不能免的事实，这是凡稍懂革命战略的人都知道的。且全俄苏维埃所集的是什么权；各邦苏维埃所分的又是什么权，我们若不加以实在考察细心地研究，便笼统地以"集权"二字来反对，亦嫌未当。至说权力集中是多数党争权的结果，不是革命的必要条件，尤属武断。多数党当三月革命方发生后，便力嚷"所有权力归苏维埃"，十月革命是全俄苏维埃应着这个口号而起的，要说争权，便是俄国无产阶级来与有产阶级争权，要说无政府党、社会革命左党不赞成无产阶级专政，退出联合，那是他们昧于阶级争斗之义，却怪不得多数党。

　　产业国有

　　是生产集中的必然现象，俄国这几年的经济恐慌正因为他生产运输机关的集中还未作到十分好处，不是因为他不能碎分产业而生出的反动结果，此就经济现象与原理看来，都能证其无误。依三泊君意，总以"饥则耕而食，寒则织而衣，劳则筑而居"的自由境界与产业国有相反，此话说来何尝不好听，其实就生产趋向说，历史是不重复的，如要硬来碎分生产机关，返之上古部落生活状况，则因实质的条件难合，必要引起更大的经济恐慌。如此人必有不得食，不得衣，不得居的了，更何从言其自由！



　　＊本文原载旅欧《少年》杂志第六号。

　　注释：

　　〔１〕热那亚会议是一九二二年四月十日～五月十九日在意大利召开的讨论欧洲经济问题的国际会议。参加会议的有英、德、意、苏俄、波、法、日等二十九个国家的代表。苏俄代表团列宁为团长（后未出席）、契切林为副团长。会上，资本主义列强提出了旨在苏俄恢复资本主义并进而变苏俄为殖民地的备忘录。苏俄代表坚决拒绝了帝国主义者的无理要求，并要求西方列强赔偿因武装干涉和封锁苏维埃国家带来的损失。会上未达成任何协议，只决定将部分问题移交海牙会议审查。苏俄通过这次会议第一次登上国际外交舞台，并成功地利用协约国与德国的矛盾结束了外交孤立的局面，扩大了国际影响，打开了同资本主义国家在和平共处原则基础上建立外交关系的新局面。

　　〔２〕海牙会议是一九二二年六月十五日～七月十九日在荷兰海牙召开的国际会议，是热那亚会议的继续。有二十七个国家的代表出席了会议。各资本主义国家代表团成员主要由工商界代表和专家组成。苏俄代表团团长是李维诺夫。会上，资本主义国家代表拒绝了苏俄代表关于建立国际合作的一切建议以及向苏俄贷款的问题。他们坚持要苏俄政府偿还沙皇政府的债务和归还已被没收的外国企业与财产。苏俄代表坚决拒绝了这些要求。最后，会议在美国操纵下通过了比利时代表的一项建议，即禁止各国代表同苏俄进行谈判和签订协定，于是会议失败。

　　〔３〕乌尔圭哈突，也译作乌尔卡尔特，是当年参加海牙会议英国代表团中曾任十月革命前开发乌拉尔和四伯利亚富源的俄亚银行经理处经理的大企业主。他在海牙会议上投票赞成禁止与苏维埃俄国签订个别双边协定的协议，而另一方面却于一九二二年九月九日在柏林商妥了关于乌拉尔和连那金矿的承租权。苏维埃政府鉴于英国政府对苏维埃俄国所采取的敌对政策，没有批准这个协定。



