# 军阀统治下的中国

中文马克思主义文库 -> 周恩来
军阀统治下的中国
（一九二四年二月一日）

北洋军阀〔１〕的势力在中国历史上已占有二十多年纵的地位。近数年来，吴佩孚〔２〕更以北洋正统为号召，打倒段祺瑞〔３〕，赶走张作霖〔４〕，傀儡一阵黎元洪〔５〕，然后以先宪后选的手段拥曹锟〔６〕进了三海。他自己也随即正位直鲁豫巡阅使。吴秀才这样一气呵成的北洋正统之争，浩浩荡荡地南征北伐四五年，似乎北洋派正统横的地盘又可继袁世凯〔７〕之后而更行扩张了。但这不过是吴秀才一种梦想吧！我们且先看看曹锟窃取总统、吴佩孚作了"传统长子"后祸国殃民的成绩：

一、曹锟贿买猪仔议员用了一千三百多万元资本。这笔大选费的来路是，王承斌从直隶各县摊款，金丹罚款〔８〕，直隶省公债二百万元，预征直省地丁二百万元和井径矿务局向外国银行抵借现款九百万元等项中支出的。

二、曹锟为要博得列强的欢心，列强也以交换觐见为名，于是临城案〔９〕的通牒北京伪政府全部承认了。

三、曹锟的总统本是英美帝国主义者一手造成的。伪政府深恐日本吃醋，竟于曹锟登台旬日之间承认了日商擅发的俄发债票利息和参战借款的转期。

四、威海卫退还交涉经山东人民再四奋争，而结果洋奴顾维钧〔１０〕回答山东人民的批示竟说："......归还威海卫系属英国善意，故无条件交还，自难强英人以必从。"于是威海卫又继青岛而去了。

五、吴佩孚为要贯彻他的武力统一迷梦，不惜指使北政府卖国以快己意。美国军舰助赵恒惕〔１１〕，在长沙示威，日本宜阳丸替吴佩孚运军火入川，北政府暗示外舰占据粤海关。这全是此事铁证。

六、王克敏〔１２〕为要替曹家政府买好于法国，竟收买报纸三十家，以图金法郎案〔１３〕得于暗中恢复。

七、直军入川入湘，孙传芳〔１４〕攻入浙境，陈炯明〔１５〕、沈鸿英〔１６〕在广东骚扰，山西阎锡山〔１７〕将受直派的排挤，这全是吴大将军殖兵政策的德政。

八、外交系以孙宝琦〔１８〕老板作幌子的卖国内阁于本年一月中组成了。开台第一出戏便是顾维钧演。他的拿手好戏卖了三条铁路--山东的烟潍，直隶的津赤和沧石--给英国财团借英金二千万镑，成为袁世凯后的第一次大借款（事载《工人旬报》三十七期）。

够了，够了！这些祸国殃民的强盗洋奴，我们若不将他们赶走净尽，无法无天的罪恶将更从此层出不穷了。

※　　　　　※　　　　　※

是的，但赶走他们是反直派诸人们能胜任的么？我们知道黎元洪为要过足总统瘾而南下，于是托庇日人，勾结政学会，接近唐绍仪〔１９〕，收买议员南下。但结果竟因金钱势力远不及曹吴，弄成买空卖空的僵局，而自己也不得不跑到日本去藏拙。次之，皖系奉系都只为日本受了九月一日地震的影响，不能尽力助段祺瑞、张作霖的饷械，于是马厂誓师〔２０〕的活戏乃不得不于曹锟贿选成功后演出。虽说现在浙卢沪何有蠢然欲动之势，但孙传芳若不逼之于南，齐燮元〔２１〕若不以淞沪警察厅长事逼何丰林〔２２〕，则老奸巨滑的卢永祥〔２３〕决不会点起反直之师。再次，则四川的熊但、滇唐、贵刘〔２４〕都在自顾不暇，而且更是不足与谋之人。总之，这一干军阀官僚政客们的反直运动，不但一时不是曹吴对手，而且即使真能倒曹倒吴，他们又何尝不可继续曹吴的卖国工作。这种循环的军阀祸国之局，真将我们教训够了！

新旧军阀既都不足恃，所可恃者，能救中国的只有全中国的工人农民商人学生联合起来实行国民革命。而现时中国国民党〔２５〕实在领袖此国民革命群众的地位上。我们试看年来孙中山及其革命党人在广东奋斗的经过，便知全中国中真能集实力与北洋军阀抗争的实仅此一支孤军。假使陈炯明不几次阻挠北伐，现时南方革命势力至少也可伸张到长江南北。即就最近说，曹锟贿选成后，孙中山方将举兵北伐，陈炯明又出死力将中山困住。虽近报广州已转危为安，陈军已败退下去，但死灰尚可复燃，况甘心从贼媚外的陈炯明后方又有英政府、吴秀才作靠山，前途的胜负亦正未可预料，然而孤军转战的孙中山却已疲于奔命了，负有革命使命的国民，果忍长此作壁上观么？

不，国民革命运动亦将兴起了。

第一，全国有觉悟的工人，自从京汉路流血后，大都看透了北方军阀和外国强盗的恶毒，表同情于革命派国民党的日见其多，因为他们深知香港海员罢工胜利得到南方政府助力不少。

第二，自曹锟图谋总统开始，全国学生总会即通电否认北京国会政府，并请孙中山指日北伐。及曹锟贿选告成，安徽学生对猪仔议员首先激起了群众的惩戒运动。

第三，中国农民本来是最称驯良的，但近因迫于军阀的祸害，亦渐渐知道团结反抗了。上年广东海丰农民因飓风大水为灾要求地主减租，田主竟勾结陈家军捕去农会职员二十五人，遂激起十余万农民的反抗运动。又湖南衡山的岳北农会已拥有会员四万余人复能四出宣传，颇引起地主的极大恐慌。这两桩事实全是证明中国农民是可以在不久的将来走上革命战线的。

第四，《响导》报载："最近山东省政府强迫征收产销税，税则之苛及于青菜大蒜，于是激起沿胶济路十余县人民剧烈的反抗，全体罢市，殴毙税吏，拒绝官厅，结果停止征收才没有酿成大变。"其后"山东奸商丁敬臣以三百万元运动包办青岛一带盐田，与日人狼狈为奸，事为盐户侦悉，即起反抗。"又有"吕某在山东财政厅承揽山果税，遂引起历城、长清、滕县、南山......等处山果商贩之反对，以性命为孤注阻止征税之进行。"及年底十二月，山东滋阳、泰安、宁阳等七县花生商人又因财政厅私委省议员王某包办津浦路济南段的花生税，举行全体罢市，反对增长印花税价。这几件事一方面足以证明列强欺凌、军阀压迫最甚的山东商人已涌起革命潮了，他方面也实足与全国商人一个团结反抗的暗示。

好了！如许多的革命潮头已渐涌起于冷静无波的中国民众海中。我们相信，不久全中国的工人、农民、商人、学生均将会冲上前锋，来做弄潮人。

＊这是在旅欧期间写的，原载一九二四年二月一日出版的《赤光》第一期。

注释

〔１〕北洋军阀是清末袁世凯在北方几省首先建立起来的封建军阀集团。一八九五年清政府命袁世凯在天津小站编练"新建陆军"，归北洋大臣节制。一九○一年袁世凯任直隶总督兼北洋大臣以后，培植党羽，自成派系。辛亥革命后，袁世凯窃取中华民国临时大总统职务，组织了代表大地主大买办阶级的第一个北洋军阀政府。一九一六年袁死后，这个集团分别在英、日等帝国主义国家支持下分化为直、皖、奉三系，为争权夺利彼此间进行过多次混战。一九二六年皖系军阀段祺瑞下台，一九二七年直系军阀被国民革命军消灭，一九二八年奉系军阀政府垮台。至此，北洋军阀反动统治时期结束。

〔２〕吴佩孚（一八七四～一九三九），山东蓬莱人，北洋军阀直系首领之一。一九一八年反对皖系首领段祺瑞的"武力统一"政策，主张南北议和。五四运动时，曾以"爱国军人"姿态，通电反对在巴黎和约上签字。一九二○年联合奉系推翻段祺瑞政府，随后曾与苏俄政府建立联系。一九二二年将奉系逐出关外后，支持曹锟控制北京政府。一九二三年残酷镇压京汉铁路工人运动。一九二六年所部在湖北被北伐军击溃。

〔３〕段祺瑞（一八六五～一九三六）北洋皖系军阀首预。安徽合肥人。一八九六年协助袁世凯创办北洋军，曾任江北提督等职。一九一二～一九一六年历任北京政府陆军总长、参谋总长和国务总理。袁世凯死后，他在日本帝国主义支持下，以国务总理把持北洋军阀政府。一九二○年被直系军阀曹锟，吴佩孚打败下台。一九二四年直系政权垮台，段被奉系及冯玉祥推为北京临时政府执政。一九二六年屠杀北京爱国群众，造成三一八惨案。同年四月又被冯玉祥驱逐下台。

〔４〕张作霖（一八七五～一九二八），北洋奉系军阀首领。辽宁海城人。一九一六年起任奉天督军、东三省巡阅使等职。一九二四年打败直系军阀后，他的势力伸入关内。一九二六年又联系直系军阀吴佩孚入据北京。后来和日本帝国主义发生利害冲突，一九二八年六月在退回东北的路上，被日本关东军预埋炸弹炸死。

〔５〕黎元洪（一八六四～一九二八），北洋军阀政府总统。湖北黄陂人。北洋水师学堂毕业。随德国教官训练湖北新军，曾任第二十一混成协统领。在新军中多次破坏湖北革命党人的活动。一九一一年武昌起义后，被迫出任军政府鄂军大都督。南京临时政府成立时当选为副总统。袁世凯篡政后，又伙同袁镇压革命。一九一四年袁世凯解散国会，篡改约法，设参政院，他被任为院（议）长。袁死后，由副总统继任大总统，与国务总理段祺瑞发生府院之争。段利用张勋将他驱走，由冯国璋代理大总统。一九二二年受直系军阀支使，复任总统。次年被直系军阀驱走。

〔６〕曹锟（一八六二～一九三八），北洋直系军阀首领。直隶天津（今天津市）人，北洋武备学堂毕业。清末为袁世凯北洋第三镇统制。辛亥革命后，历任北洋军第三师师长、直隶督军、直鲁豫三省巡阅使。在英美帝国主义支持下，与吴佩孚同为直系军阀首领。一九二三年第一次直奉战争打败奉系后，曹锟以五千银元一票的价格收买国会议员五百九十人，被选为大总统，世称贿选总统。一九二四年冯玉祥发动北京政变时，被囚禁，后直奉两系联合，获释。

〔７〕袁世凯（一八五九～一九一六），北洋军阀首领，河南项城人。清末曾任山东巡抚、直隶总督兼北洋大臣等职。一九一一年辛亥革命时，出任清政府内阁总理大臣。一九一二年在英、美、日等帝国主义国家支持下，窃取中华民国临时大总统职务，组织了代表大地主，大买办阶级的第一个北洋军阀政府，对内专制独裁，对外投降卖国。一九一五年五月接受日本企图灭亡中国的"二十一条"。同年十二月称帝，一九一六年三月在全国人民的反对下被迫取消帝制，仍称大总统。六月六日在全国人民声讨中，忧惧而死。

〔８〕一九二三年曹锟公开贿选总统工作逐步展开，直隶省长王承斌想出一个"捉财神"的办法，派出密查员二十余人，分赴各地逮捕了制造金丹、白丸的制毒犯百余人，把他们解到天津来，组织特别法庭审理。选择其中无力缴款的"小鱼"数人枪决示威，其余则令缴纳数千元至数万元予以释放。

〔９〕临城案指临城劫车案。一九二三年五月五日夜，土匪孙美瑶在山东临城（今枣庄）至沙沟站抢劫由浦口开往天津的客车，将车上行李财物悉数抢去后，把二百余名旅客（内二十六名外国人）虏至峄县（今枣庄）抱犊崮，作为"肉票"。帝国主义乘机对北洋政府进行要挟，扬言出兵干涉和"共管中国"。曹锟政府向帝国主义屈节谢罪，允许外国人干涉中国路政，并将山东第六混成旅长兼兖州镇守使何峰珏革职查办，收编匪兵而"和平"解决。

〔１０〕顾维钧是当时的中国驻美公使，也是参加一九一九年巴黎和会的中国代表团成员之一。

〔１１〕赵恒惕，湖南湘潭人。清举人。曾肄业武备学堂，继入日本陆军仕官学校炮兵科学习。一九一六年任湖南第一师师长，不久任湖南水陆军总司令。一九二一年任湖南省长。一九二三年前后，镇压湖南地区农民运动，破坏农会。

〔１２〕王克敏（一八七三～一九四五），浙江杭县人。北洋军阀政府时期历任中法实业银行总经理、中国银行总裁、财政总长等职。一九三七年抗日战争爆发后，在日本帝国主义指使下，成立伪华北临时政府，任行政委员会委员长，后又两度担任伪华北政务委员会委员长。一九四五年抗日战争胜利后被捕，畏罪服毒自杀。

〔１３〕一九○一年辛丑条约签订，帝国主义向中国勒索四亿五千万两白银的巨额赔款，按当时中国人口计算，平均每人摊派一两白银。欧战后，法国金融混乱，通货膨胀，法郎暴跌，纸币一法郎只值现金三分之一。按一九○五年换文规定的赔款偿付方法，中国用较少的银两，即足偿付法国之庚款。但是，法帝国主义以恢复中法实业银行为诱饵，炮制了所谓金法郎案。法国根本没有金法郎这种货币，如果按照金法郎偿付，中国将损失关银六千二百多万两。紧随着法国之后，美、比、意等国也向中国提出照会，要求各国赔款一律按硬金计算。在帝国主义的联合压力下，一九二三年十一月十二日曹锟任命与金法郎案有密切关系的王克敏为财政总长，打算秘密承认此案，不再提交国会审议。由于全国人民和"反直同盟"再接再厉地发出反直的呼声，曹锟不敢一意孤行。此后，北京当权人物再也没有人敢于出面来主张承认金法郎案了。

〔１４〕孙传芳（一八八五～一九三五），山东历城人。北洋直系军阀。一九二四年江浙战争爆后，驱逐了皖系卢永祥，任浙江军务善后督理兼闽浙巡阅使。一九二五年又起兵驱逐了苏皖等地奉系势力，称浙闽苏皖赣五省联军总司令，成为直系后期最大的军阀。一九二六年镇压上海工人的武装起义。同年冬其主力在江西的南昌，九江被北阀军打垮，后投奔奉系军阀张作霖，任安国军第一军团长。一九二七年八月率部渡江反扑，在南京龙潭被国民党军打败。一九三五年在天津被刺死。

〔１５〕陈炯明（一八七八～一九三三），广东军阀。广东海丰人。一九一一年参加辛亥革命，被推为广东副都督，后任都督。一九一七年任援闽粤军总司令。一九二○年驱逐桂系军阀莫荣新，任广东省长兼粤军总司令。一九二二年六月，勾结英帝国主义和直系军阀，背叛孙中山。一九二三年被粤军许崇智击败，率部退守东江。一九二五年所部被广东革命军消灭。

〔１６〕沈鸿英（一八七四～一九三八），桂系主力之一。广西雒容（今鹿寨人）。一九二一年乘孙中山讨伐陆廷荣之机，宣布自治，所部称"救桂军"，欲取陆廷荣而代之。阴谋败露后，退入湖南，投靠吴佩孚。一九二三年逐走陈炯明后，再次背叛孙中山，进攻广州大元帅府，一九二四年二月被击败请降，率残部返桂。

〔１７〕阎锡山（一八八三～一九六○），山西五台人。辛亥革命时任山西都督，从此长期盘踞山西，依违于北洋军阀皖、直、奉三系之间，投机自保。九一八事变后，支持蒋介石的不抵抗政策，并阻挠中国工农红军开赴抗日前线。抗日战争结束后，积极参加蒋介石的反人民内战。一九六○年死于台湾。

〔１８〕孙宝琦（一八六七～一九三一），浙江杭州人。一九一三年～一九一四年三月连任熊希龄、徐世昌内阁的外交总长，一度兼任国务总理。一九二四年一月任国务总理兼外交委员会委员长。

〔１９〕唐绍仪（一八六○～一九三八），广东香山（今中山）人。辛亥革命时代表袁世凯参加南北议和。一九一二年三月袁世凯就任临时大总统，他任国务总理，六月辞职。一九一七年参加护法军政府，一九一九年任护法军政府代表，与北洋军阀政府代表朱启钤在上海议和。此后任国民党政府的国府委员、西南政务委员会委员兼中山县长。一九三八年在上海被刺死。

〔２０〕一九一七年六月张勋入京解散国会，驱走总统黎元洪，拥清废帝溥仪复辟。七月，段祺瑞借助全国人民反复辟的声势，在日本的支持下，组成"讨逆军"，自任总司令。三日在天津附近的马厂"誓师"，宣布讨伐张勋。十二日讨伐军五万余人沿京津、京汉两路分兵进攻北京，张勋兵败。段以"再造民国"的"功臣"，复任国务总理，兼陆军总长，重掌政权。

〔２１〕齐燮元（一八七九～一九四六），直隶宁河（今属天津市）人。直系军阀，曾任江苏督军、苏皖赣巡阅使等职。一九二四年与盘踞浙江的皖系军阀卢永祥混战获胜。同年因直系在第二次直奉战争中失败，被北洋军阀政府免职。一九三七年抗日战争爆发后投敌，配合日军"扫荡"，残杀中国人民。抗战胜利后被捕，一九四六年枪决。

〔２２〕何丰林，山东平阴人。原为袁世凯新军教练官，一九二三年任浙江宁台镇守使。一九二四年九月江浙战争爆发，任浙沪联军第一军司令。一九三五年左右任东北边防军司令长官公署首席参议。

〔２３〕卢永祥（一八六七～一九三三），山东济阳人。原系曹锟旧部，后投靠段祺瑞，成为皖系干将之一，曾任北洋军师长和淞沪护军使。一九一九年任浙江督军，一九二二年标榜"废督裁军"，改称浙江军务善后督办。一九二四年因争夺上海地盘与江苏督军齐燮元发生战争（江浙战争），兵败下野。第二次直奉战争后，段祺瑞上台，被任命为苏皖宣抚使，借奉系军力逐走齐燮元，占据江苏，后又被奉系排挤下台。

〔２４〕这里指的是西南军阀，即四川的熊克武、但懋辛，云南的唐继尧和贵州的刘显世。

〔２５〕中国国民党是孙中山创立的政党。一九○五年，孙中山领导的兴中会与华兴会、光复会联合组成同盟会，由孙中山任总理。同盟会领导了辛亥革命。一九一二年同盟会联合四个小党派改组为国民党，和北洋军阀袁世凯实行妥协，基本上成了官僚政客集团。一九一四年，为了反对袁世凯的统治，孙中山领导一部分国民党员组织中华革命党，一九一九年十月，又改为中国国民党（简称国民党）。一九二四年一月在中国共产党的帮助下，孙中山改组了中国国民党。改组后的中国国民党接受中国共产党提出的反帝反封建的政治主张，重新解释三民主义，确定联俄、联共、扶助农工三大政策，从而实现了第一次国共合作，并依靠这一合作进行了北伐战争。一九二七年四月蒋介石发动反革命政变，国民党变成为代表大地主、大资产阶级的反动集团。

