# 革命救国论

中文马克思主义文库 -> 周恩来
革命救国论
（一九二四年二月十五日）

国的界限，自从各民族间开始商业交通后，各个统治阶级，遂都用它作成对内号召统一、对外兼并他国的武器。及资本主义勃兴，各国的资产阶级更是挟其方兴之势，运用这个武器--国--对内压迫被统治阶级的一切反抗和革命，对外抵御强敌并凌辱那产业未曾发达的各弱小民族。于是，全世界凡经资本主义铁蹄所践踏的地方，概都形成了同样的两大阶级：一是压迫阶级，一便是被压迫阶级。
 

压迫阶级是以各强国的资产阶级为中心，各产业落后国的封建军阀只不过是他们的爪牙；至被压迫阶级即工业先进国中的无产阶级和各殖民地半殖民地的弱小民族，都是站在同一被剥夺被欺凌境地的。且在他们中间，以经济地位论，不说无产阶级，便是各殖民地半殖民地的小资产阶级，也都为国际资本帝国主义侵略压迫之故，迟早都要走入无产阶级队伍中来。所以全世界的被压迫阶级，若是看明白了此事，正宜速行运用这个国的利器来攻打敌人。殖民地半殖民地的弱小民族要群起来做国民运动，推翻国际帝国主义，工业先进国的无产阶级要日夕图谋阶级争斗，以便打倒国内资本主义；同时更应联合起来一齐向压迫阶级进攻，也正如压迫阶级以国际的资本进攻被压迫阶级而不分国界的一样，而且当着他们自己引起不可免的国际战争时，被压迫阶级的解放日子便到了。只要弱小民族的国民力量胜过一时的侵略者，无产阶级的团结力胜过当时的统治者，则一个革命的爆发，也成了自然之势。前者的例子呈土耳其〔１〕，后者便是俄罗斯。而俄、土在土耳其国民运动中的相互关系，更足证明全世界被压迫阶级实有联合的必要和可能，且世界革命的伟大工作，也正要在这个联合中期待实现。

至我们中国呢，凡是稍明事理、稍识事实的人，大都能承认中国已夷为列强的半殖民地，非革命不足以图存了。且就世界的情势、国际的地位来说，弱小的民族若不从国民运动企图国民革命入手，而仅右倾于振兴实业图谋救国，或竟"左"倾于毁坏一切自由行动，则结果转不过为在其国内无可发展的列强资本主义延长其遁在尾闾的生命而已。有志气而不甘堕落的中国人，何能忍此！

革命是无疑而且确定了！但我们须看清我们的敌人和我们国民革命的势力究竟何在，且谁又是我们真实的友人。

我们的敌人，帝国主义的列强--特别是英、美、日、法--自是我们最大的仇雠。他们挟其工业先进国的机械力，奴役了我们农业国的散乱民众，掠夺我们的原料，强销他们的货物，以金钱诱惑中国的军阀官僚，于是借款约成，继海关共管、邮政代管后，有盐税共管、铁路共管、江河共管，驯至全部财政共管，乃便要完全实现共管中国了。但不有内贼，外贼何能张牙舞爪地一无忌惮！要不是清廷昏庸，庚子之变〔２〕何致损失如斯之巨！袁世凯〔３〕若不急图帝制，"二十一条"〔４〕何致签成！段祺瑞〔５〕苟非志在卖国，中国人民的肩上何致压上一笔巨大的参战借款！曹锟〔６〕、吴佩孚〔７〕若不是一志在总统，一志在武力统一维持什么北洋正统，又何致开门揖盗，自华盛顿会议〔８〕席上迎来些自家承认的太上政府！陈炯明〔９〕果非志在排斥国民革命领袖，又何致勾结英国香港政府，延长广东内部的战祸至今未熄！有了这一干图私的新旧军阀--封建余孽--再加以专做牵线人的外交系，做掮客的洋行买办和趋炎附势的滥官僚，于是卖国的勾当乃越发做得兴旺，而帝国主义的列强亦遂特加他们以青睐。有时几个帝国主义者吃起醋来，或是几个军阀恃宠而骄，于是军阀相互间的战争，乃遂在列强的嗔笑中一来一往，而中国人民遂匍伏在枪弹底下讨生活了。总之，他们的罪恶祸害是数不尽的，我们只要认清这全是国际帝国主义者从中作祟，我们便能找到我们共同的敌人，而且相信，他们进攻我们--全中国民众--是永远站在同一战线上的。

我们既做国民运动，我们必须先认清国民革命的势力，然后才能有团结之可能。在中国，民主革命的工作已有二十多年的历史了，而且辛亥革命〔１０〕又曾将共和招牌挂张起来，但我们如要从中找出一派可靠的革命势力，则我们相信只有海外华侨可足当得起一支革命的主力军。因为只有他们接触国际帝国主义强盗为最早，故他们希望一个必须保护侨民的民治国来做他们海外发展的后援，乃属当然的需要。无论入保皇党〔１１〕或同盟会〔１２〕，其心理上的希望皆属一样，不过清廷政治的教训使他们倾向革命的心易于胜过改良的错误观念就是了。第二派革命势力直至一九二二年香港海员罢工时起，始渐渐从工人阶级队伍中涌出，一年多的膨胀，至一九二三年"二七"京汉工人大流血后，北方的劳动势力，虽稍受一时挫折，但全中国的劳动阶级--特别是交通机关、矿山、工厂常与列强资本势力接触，备受中国军阀凌辱的中国劳动阶级--终将为国民革命中一派最可靠的主力，这是毫无疑义的。第三派中国的知识界，自从五四运动〔１３〕后，顿呈活气，中间虽因受新文化运动中的恶影响消沉了两三年，但近一年来又复现出蓬蓬勃勃的朝气，其中尤以青年学生为最能无所忌惮地反对列强，反对军阀。第四派便是新兴的工商业家，依他们现时的阶级地位论，自然很难单独去号召一种革命，虽说是他们也渐觉悟到军阀不打倒，列强不赶开，他们的工商业是万难独立振兴的，除非他们甘于卖国，甘与外人合办。但他们中间的开明分子也渐能与革命派表同情了，自己也知要起来过问政治，这不能不说是好的现象。而不久的将来终会有一部分人来走入救国的革命队中。第五派革命势力现在方在酝酿期中，这便是庞大的农民阶级。农民的势力果成与否，全视努力之人多寡为断；至农民本身，国际强盗之为害，他们或还感觉较少，但军阀的祸国殃民，他们已是确信无疑了。

上述的五派是中国国民运动中最值得注意的革命势力。若能合此五派的革命分子于一个革命的政党统率之下，则国民革命的成功，必不至太为辽远。在历史的使命上说，中国国民党〔１４〕是负有这个革命统率之责的。过去它因为忽略了革命势力真实的存在和各派的经济地位，以致革命十二年，不但新的革命势力未能集中到国民党旗帜之下，便是国民党唯一的后援海外华侨也有动摇之虞，这不能不算是国民党至大的失计。

我们知道国民党近来已起首改组了，我们且深信此次改组后必有可观。但我们所最切望而且不惮重复申说的，便是国民党今后当注意于国民运动中五派可靠的革命势力之发展团结和引导，千万再不要误认新旧军阀的四派势力〔１５〕之调和可以得到那骗人的和平统一！

最后，我们要说道，在国民革命运动中我们可引为友之国，自不外与我们立在同一境地下的殖民地半殖民地的弱小民族和无产阶级之国的苏联俄罗斯。这些，我们是要与他们以统一前敌的国际联合来企图世界革命而促成我们国民革命成功的。

如此，我们才不致染上旧日列强所运用的国的武器的祸害，而能使我们革命救国的主张发现了新的意义，人类历史上展开了新的记录。

＊这是在旅欧期间写的，刊于一九二四年二月十五日出版的《赤光》第二期。原载《周恩来统一战线文选》。

注释：

〔１〕这里是指由穆斯塔法·基马尔领导的土耳其民族解放运动。第一次世界大战中，土耳其政府追随德奥帝国主义集团，使土耳其经济遭到严重破坏，社会矛盾加剧。战败后，英、法、意等帝国主义国家瓜分土耳其，更激化了民族矛盾。一九一九年，以穆斯塔法·基马尔为代表的土耳其民族商业资产阶级，领导人民进行反帝民族解放斗争并取得胜利，于一九二三年成立了土耳其共和国。土耳其人民在这一斗争中，得到列宁和苏俄政府的同情和支持。一九二○年苏俄政府承认基马尔建立的安纳托利亚民族政权，次年三月又签定了苏俄土耳其友好条约。

〔２〕庚子之变即八国联军攻陷北京的事变。一九○○（庚子年），英、美、法、德、俄、日、意、奥八个帝国主义国家，为了镇压义和团的反帝爱国运动，瓜分中国，借口清政府"排外"，组成侵华联军，于八月十四日攻陷北京，大肆烧杀抢掠，践踏中国主权。腐败无能的清政府，于同年十二月全盘接受各帝国主义国家提出的《议和大纲》，并于次年九月，签订了丧权辱国的《辛丑条约》。

〔３〕袁世凯，参见本书《军阀统治下的中国》一文注〔７〕。

〔４〕二十一条，参见本书《大西洋上之太平洋问题》一文注〔３〕。

〔５〕段祺瑞，参见本书《军阀统治下的中国》一文注〔３〕。

〔６〕曹锟，参见本书《军阀统治下的中国》一文注〔６〕。

〔７〕吴佩孚，参见本书《军阀统治下的中国》一文注〔２〕。

〔８〕华盛顿会议，参见本书《大西洋上之太平洋问题》一文注〔１〕。

〔９〕陈炯明，参见本书《军阀统治下的中国》一文注〔１５〕。

〔１０〕辛亥革命是以孙中山为首的资产阶级革命政党同盟会所领导的推翻清朝专制王朝的革命。一九一一年（辛亥年）十月十日，革命党人发动新军在湖北武昌举行起义。接着，各省热烈响应，外国帝国主义所支持的清朝反动统治迅速瓦解。一九一二年一月在南京成立了中华民国临时政府，孙中山就任临时大总统。二千多年的中国封建帝制从此结束，民主共和国的观念从此深入人心。但是资产阶级革命派力量很弱，并具有妥协性，没有能力发动广大人民的力量比较彻底地进行反帝反封建的革命。辛亥革命的成果迅即被北洋军阀袁世凯篡夺，中国仍然没有摆脱半殖民地、半封建的状态。但是，辛亥革命是中国近代史上的一个伟大的里程碑，是在比较完全的意义上开始的反帝反封建的民族民主革命，为以后一系列历史发展开辟了道路。

〔１１〕保皇党指清末资产阶级改良派在海外的政治团体保救大清皇帝会，简称"保皇会"。一八九八年戊戌变法失败后，康有为、梁启超等逃亡海外，次年七月在加拿大创立"保皇会"，并在南洋、美洲、日本等地建立组织，以保救光绪，反对慈禧和抵制革命为宗旨进行活动，拉拢华侨入会。一九○七年为了迎合清政府预备立宪，保皇会改名国民宪政会，不久又改称帝国宪政会，成为推行君主立宪的政治团体。

〔１２〕同盟会是中国资产阶级革命政党中国同盟会的简称。一九○五年八月，兴中会与华兴会等革命团体的成员在日本东京联合组成同盟会，采用了孙中山提出的"驱除鞑虏，恢复中华，创立民国，平均地权"的资产阶级革命政纲。孙中山被推选为总理。同盟会除了在国内各地建立支部和分会外，还分别在南洋、欧洲和檀香山等地建立支部和分会，积极联络华侨。在孙中山的领导下，同盟会积极进行革命宣传，并联合会党、新军发动多次武装起义。一九一一年（辛亥年）十月武昌起义爆发，很快形成推翻清王朝的辛亥革命运动。

〔１３〕五四运动指一九一九年五月四日发生的反帝反封建的爱国运动。当时，第一次世界大战刚刚结束，英、美、法、日、意等战胜国在巴黎召开对德和会，决定由日本继承德国在中国山东的特权。中国是参加对德宣战的战胜国之一，但北洋军阀却准备接受这个决定。五月四日，北京学生举行游行示威，反对帝国主义的这一无理决定和北洋军阀政府的妥协。这次运动迅速地获得了全国人民的响应，到六月三日以后，发展成为有工人阶级、城市小资产阶级和民族资产阶级参加的广大群众性的反帝反封建的爱国运动。五四运动也是反对封建文化的新文化运动。以一九一五年《青年杂志》（后改名《新青年》）创刊为起点的新文化运动，竖起"民主"和"科学"的旗帜，反对旧道德，提倡新道德，反对旧文学，提倡新文学。五四运动中的先进分子接受了马克思主义，使新文化运动发展成为马克思主义思想运动。他们致力于马克思主义同中国工人运动相结合，在思想上和干部上为中国共产党的成立做了准备。

〔１４〕中国国民党，参见本书《军阀统治下的中国》一文注〔２５〕。

〔１５〕指由北洋封建军阀集团在袁世凯死后分裂成的直、皖、奉三派旧军阀，和南方的背叛孙中山投靠帝国主义成为新军阀的陈炯明。这四派新旧军阀势力，得到帝国主义的金钱和武器的支持，扩充实力，互相勾结又互相争夺，妄图以武力消灭南方各省的革命力量。

