# 北洋军阀的内哄

中文马克思主义文库 -> 周恩来
北洋军阀的内哄
（一九二四年五月十五日）

封建阶级的武人因各谋私利争为雄长演成互相征伐之事，常较资本阶级因自由竞争而引起的国内战争多得无算。此其故：一由于封建武人利在兼并土地，横征暴敛，好广积金钱；而资本阶级则利在图谋其本阶级在政治上的权力分配及经济上的自由竞争或携手合作；二由于封建武人所恃者武力，资本阶级则恃资本。本此，现时中国的封建余孽军阀乃遂兵祸连年，互相残杀，成为不可避免的内哄，非至覆灭不止了。

在中国军阀中，自以北洋军阀为主干，自曾李练兵湘淮〔２〕，满清帝制的金瓯便已生了裂痕，及袁世凯小站练兵〔３〕，更树立了北洋军阀的始基。至帝制倒，袁世凯兴，随袁氏而起的"王龙段虎冯狗子"〔４〕便顿时有各树一帜的异心。惟王士珍〔５〕手无重兵，虽一试国务卿两试总理，终无多大发展，卒让冯国璋〔６〕段祺瑞〔７〕造成了直皖两系以争北洋正统。袁世凯死，冯段互相争霸，结果军师徐世昌〔８〕虽坐收了一时渔人之利，但重要政务仍不得不仰鼻息于皖系军阀。继着吴秀才〔９〕捧着曹锟〔１０〕为直系军阀复仇，于是一战胜段，再战胜张，驱徐驱黎，终至浩浩荡荡地将曹锟拥进了三海。这样一气呵成的直系天下，宜可以使北洋正统的招牌在曹锟手中稍延时日了，殊不知四围的军阀还未倒，而直系的内部亦起了正统之争。本来，此次拥曹首功为保津两系的冯玉祥〔１１〕、王承斌〔１２〕和王毓芝〔１３〕、高凌蔚〔１４〕、吴景濂、〔１５〕、边守靖〔１６〕等，洛系吴佩孚、宁系齐燮元〔１７〕不过尽赞襄之助，乃论功行赏吴佩孚、萧耀南〔１８〕、齐燮元各得一巡阅使，王承斌得副使，而冯玉祥"竟不与焉"。及组阁，高凌蔚又排吴景濂，终至吴景濂连一议长也失掉逃津。孙宝琦〔１９〕阁成，知孤立无援可危，乃内联津系外结段卢以张声势，然因此却得罪保系要人，于是内王（王毓芝）外王（王克敏）〔２０〕协以排之。但孙宝琦亦自不弱，居然能两使国会提出查办王克敏案，而金佛郎案〔２１〕与中俄交涉亦遂成了他们政争的武器。金佛郎案王克敏实主大谋，近日，王更以非金佛郎案解决中国财政将无办法为言，以暗示孙阁非承认不可。至中俄交涉则因东交民巷日、法、美太上政府之反对，法国在道胜银行收头的中东路股票事和苏俄在蒙古撤兵条件与冯玉祥垦边雄图有碍故，顾维钧〔２２〕、陆锦〔２３〕、王克敏、王敏芝、冯玉祥乃在外院内府大事挑剔，硬行延搁中俄协定不与通过。北京城中的内哄是如此了，至外方呢？吴秀才自拥曹登位以来，隐然以长子将承正统自居，这种态度自然醋起了与他平日比肩事曹的直系军阀，而他所提拔的后辈亦知急起直追模仿昔日吴对曹的态度，渐欲自成一系。好个奸阴狠毒的吴佩孚如何不看懂此剧，于是撤王承斌、张福来〔２４〕、郑士琦〔２５〕、萧耀南的师长兼任，使他们各自成个光杆督军；留蔡成勋〔２６〕督赣赞助，安徽设军务帮办，遣使赴浙联卢，助温树德〔２７〕与杜锡圭〔２８〕争衡以牵制苏齐新起的势力，尊段所以制奉；联陈降赵所以制粤；重用周荫人〔２９〕，驱逐两王（王永泉〔３０〕、王永彝）正所以防闲孙传芳〔３１〕；用杨森〔３２〕、刘湘〔３３〕、刘存厚〔３４〕、邓锡侯〔３５〕协以图川。及成都重庆既下，而又以刘存厚督川，邓锡侯长川，以启刘湘杨森之争，俾北军得以长久留蜀，此与以北军驻扎岳州同一心事。吴秀才的锦囊妙计如此，但一般军阀也非尽是蠢才，吴既以撤师长兼任倡，于是大家也就请君入瓮，吴亦不得不辞兼第三师师长，而各个督军更眼灵手快，师长由旅长升，旅长依旧补了亲信之人；冯玉祥、王承斌、齐燮元更谋保津宁，三系的亲密联合。在长江流域，萧耀南、马联甲〔３６〕、齐燮元更有联盟的传说。在豫，张福来为换省长师长事已曾一度负气至京与冯玉祥有所联络。山东郑士琦为换师长熊炳琦〔３７〕为换青岛商埠督办与吴佩孚强占胶济路收入事亦对吴极感不快。似此种种，直系的内部未等曹锟"龙归北海"便已破裂得如此之甚，一旦曹真死了，吴有何力能进三海？且就广义的北洋派看，皖派在浙在闽力尚不薄，臧致平〔３８〕近已连克漳泉二州了。奉派虽在养稍蓄锐时，但不久必为直系的劲敌。在山西，阎锡山〔３９〕虽无四略野心，但直系终不能指挥自如，故今春有京遣刺客的秘案发现。在陕西，刘镇华〔４０〕坐镇关西，近已不复为直系所有。四川湖南的军阀虽多降直，但北军如长久留川，吴佩孚如迫令湖南取消省宪，或迫令赵恒惕〔４１〕供给军饷，则夔门以内和三湘七泽间的反直风云必仍层出不已。论滇黔，虽唐氏兄弟〔４２〕和刘显世〔４３〕已为新兴军阀，但必为直祸无疑。广西陆荣廷〔４４〕、马济固又已降直，然因此迫得沈鸿英〔４５〕、林俊廷近又向孙中山输诚，虽其成否不可知，要亦属于直为不利。至破坏革命最力的陈炯明〔４６〕，虽与洛吴早已私通，只是他终不敢揭破他的联省自治假面具，亦适足为将来不能真正助直之证。

由此一段军阀祸国史上看来，北洋军阀的内哄，非但直系无术自解，即反直系亦同样无法解脱。今日的反直军阀，又何一非当年曾一度当权的军阀！总之，时至今日--亦即是生产力发展到这个时代--封建军阀的末运已至。北洋军阀的内哄亦不过证明此混乱之局，军阀自身决无能力整理，尤其是受帝国主义列强煽动勾结的军阀更无能力整理。代之兴的，只有国民革命派。

只是军阀内哄是他们自身的事，一旦国民革命派苟稍抬头，他们必会捐弃前嫌，一致来压迫国民革命势力，正如资本阶级在彼此的竞争期中时刻会转来一致压迫工人阶级一般。因此，我们国民革命派在此北洋军阀内哄的混战中，须要严密我们的战线，严防我们的敌人--军阀和其所勾结的帝国主义的列强--才不致为敌所乘而打散我们的集中势力。

＊这是在旅欧期间写的。原载一九二四年五月十五日出版的《赤光》第八期。

注释

〔１〕北洋军阀，参见本书《军阀统治下的中国》一文注〔１〕

〔２〕曾国藩（一八一一～一八七二）为清末湘军首领。一八五三年初为对抗太平天国革命，以吏部侍郎身份在湖南办团练，后扩展为湘军。李鸿章（一八二三～一九○一）为清末淮军军阀。一八六一年编练淮军，次年调至上海、在英法美侵略军的支持下与太平军作战。

〔３〕一八九四年（清光绪二十年）中日甲午战争期间，清政府为试练新式陆军，派胡燏棻在离天津七十里的新农镇即小站地方训练"定武军"。后由袁世凯接办扩编，分步、骑、炮、工、辎重五个兵种，聘德国人任教习。袁世凯掌握这一支新式军队后，支持那拉氏发动戊戌政变，勾结帝国主义镇压义和团，被擢为直隶总督。此后扩充为六镇（相当于师），形成为北洋军阀势力。

〔４〕王士珍、段祺瑞、冯国璋是袁世凯在军事方面的重要助手，有"北洋三杰"之称。有人对这种形象化的说法解释道：王士珍在政治舞台上是个时隐时现的人物，喻之为龙；段祺瑞常发虎威喻之为虎；冯国璋狗头狗脑喻之为狗亦无不宜。

〔５〕王士珍（一八六一～一九三○），直隶正定人。一八九六年投靠袁世凯为督操营务处帮办兼讲武堂总教习。辛亥革命后，在袁政府任陆海军大元帅统率办事处坐办和陆军总长。袁死后以北洋派元老身份调停皖系、直系、奉系的冲突。

〔６〕冯国璋（一八五八～一九一九），直隶河间人。袁世凯小站创办新建陆军时，被任为督练营务处总办。一八九九年随袁至山东参与镇压义和团。辛亥革命爆发后，被清政府任为第一军总统，率领北洋军至湖北镇压革命。一九一三年国民党发动讨袁战争时，袁命攻下南京，任江苏都督。袁死后北洋军阀分化，他为直系首领，与湖北督军王占元、江西督军李纯联合对抗控制北洋军阀政府的皖系首领段祺瑞，称"长江三督"。一九一六年当选副总统，一九一七年代理总统，一九一八年被段祺瑞胁迫下台。

〔７〕段祺瑞，参见本书《军阀统治下的中国》一文注〔３〕。

〔８〕徐世昌（一八五五～一九三九），直隶天津人。一八九五年袁世凯在小站练兵时，兼管营务处，成为袁的主要策士。武昌起义时，助袁窃取总统职位。一九一八年十月总统冯国璋下台，由安福国会选为总统。第一次世界大战结束后，标榜"偃武修文"，主张南北议和与段祺瑞发生矛盾。一九二○年段下台，企图依靠奉系军阀张作霖的支持。一九二二年奉系在第一次直奉战争中失败，遂被直系军阀曹锟、吴佩孚赶下台。

〔９〕吴佩孚，参见本书《军阀统治下的中国》一文注〔２〕。

〔１０〕曹锟，参见本书《军阀统治下的中国》一文注〔６〕。

〔１１〕冯玉祥（一八八二～一九四八），安徽巢县人。北洋军阀时期曾任旅长、师长、督军、督办等职。一九二四年十月发动北京政变，并将部队改组为国民军。十一月五日取消清废帝溥仪的皇帝称号，将溥仪逐出皇宫。一九二六年九月宣布脱离北洋军阀参加国民革命。一九二七年四一二政变后曾参加蒋介石、汪精卫反对共产党的活动。一九三一年九一八事变后赞成抗日。一九三三年五月同共产党合作，在察哈尔（现在分属山西、河北和内蒙古）组织民众抗日同盟军，抵抗日本帝国主义的侵略。以后，继续采取和共产党合作的立场。一九四八年初参加中国国民党革命委员会，任中央政治委员会主席。同年九月一日在由美国回国参加新政协途中遭遇火灾逝世。

〔１２〕王承斌，今辽宁兴城人。一九二二年任直隶省长。一九二三年曹锟贿选总统时，总管贿选工作。后任直隶督军，直鲁豫巡阅副使兼直隶督军、省长。

〔１３〕王毓芝，以前是军中的老"司书"，随着曹锟的升迁，做到巡阅使署秘书长。

〔１４〕高凌蔚（一八七○～一九三九），直隶天津人。一九二一年任内务总长，后助曹锟贿选，代国务总理。一九三七年任伪天津治安维持会委员长、"中华民国临时政府"议政委员会委员、"天津特别市"市长兼"河北省"省长等职。一九三八年五月因附敌卖国遇刺，次年死于北京。

〔１５〕吴景濂，今辽宁兴城人。一九二二年第一次直奉战争后，投靠直系军阀，为众议院议长。帮助曹锟贿选总统，遭到全国抨击。

〔１６〕边守靖，曾任直隶省议会议长。

〔１７〕齐燮元，参见本书《军阀统治下的中国》一文注〔２１〕。

〔１８〕萧耀南（一八七七～一九二六），湖北黄冈人。一九一八年追随吴佩孚进攻湖南。一九二三年，参与镇压京汉铁路工人大罢工，制造二七惨案。同年十一月继吴佩孚任两湖巡阅使。

〔１９〕孙宝琦，参见本书《军阀统治下的中国》一文注〔１８〕。

〔２０〕王克敏，参见本书《军阀统治下的中国》一文注〔１２〕。

〔２１〕金佛郎案，参见本书《军阀统治下的中国》一文注〔１３〕。

〔２２〕顾维钧，参见本书《军阀统治下的中国》一文注〔１０〕。

〔２３〕陆锦，直隶天津人。一九二四年任北京政府陆军总长。

〔２４〕张福来，直隶交河人。北洋军阀曹锟部第二十四师师长。一九二四年第二次直奉战争时任直军援军司令。

〔２５〕郑士琦，安徽定远人。历任北洋第五镇军官，后升任第五师旅长、师长。

〔２６〕蔡成勋，直隶天津人。直系骨干。一九二二年被吴佩孚派往江西，任江西督军。

〔２７〕〔２８〕驻粤海军舰队司令温树德投降北方前，吴佩孚许以不受海军总司令的节制，后又保荐他为渤海舰队司令，直接隶属北京政府。这一事件引起海军总司令杜锡的不满，因此忿而辞职。海军总司令部设在南京，齐燮元的态度完全站在杜的一边，杜、温之争演进而为吴、齐之争。

〔２９〕周荫人，直隶武强人。北洋军阀直系将领。历任福建护军使、福建军务督办、五省联军福建总司令。

〔３０〕王永泉，直隶天津人。一九二一年与徐树铮合作在福建成立军政制置府，同年十一月任省长。一九二三年三月任福建军务督办。王永泉与孙传芳是结拜弟兄。

〔３１〕孙传芳，参见本书《军阀统治下的中国》一文注〔１４〕。

〔３２〕杨森（一八八四～一九七七），四川广安人。一九二四年任陆军上将，督理四川军务。一九二五年与刘湘、刘文辉、邓锡侯等部发生冲突，杨兵败出川，被昊佩孚委为讨贼联军川军第一路总司令。

〔３３〕刘湘（一八八八～一九三八），四川大邑人。一九二一年被推为四川各军总司令。

〔３４〕刘存厚，四川简州（今简阳）人。毕业于日本陆军士官学校步兵科，归国任云南武备学堂堂长。依附北洋军阀为争夺四川督军职务，与滇黔军进行长期混战。一九二七年投靠蒋介石，任国民革命军第二十三军军长。一九三三年在四川堵截红军，兵败被撤职。

〔３５〕邓锡侯（一八八八～一九六四），四川营山人。四川军阀刘存厚的部属。一九二五年，吴佩孚任邓为川黔讨贼联军副司令兼四川联军第二路总司令。一九二七年蒋介石叛变革命后，曾参与蒋介石的反共活动。一九三七年任第一十二集团军总司令，率部出川抗日。抗日战争胜利后，任国民党政府四川省主席，西南公署副长官。一九四九年十二月十日在四川彭县起义。起义后任西南行政委员会副主席兼水利部部长，四川省副省长，国防委员会委员，全国人民代表大会代表。

〔３６〕马联甲，安徽军阀，曾任安徽军务督办。

〔３７〕熊炳琦，山东人。曾任禁卫军参谋、直隶都督署参谋、江苏都督署军务课长、直鲁豫巡阅使署参谋长、山东省长等职。

〔３８〕臧致平，安徽太和人。一九二四年江浙战争时，任浙沪联军第一路副司令。一九二五年一月任江苏宣抚使署参谋长。

〔３９〕阎锡山，参见本书《军阀统治下的中国》一文注〔１７〕。

〔４０〕刘镇华（一八八二～一九五五），河南巩县人。一九二四年直奉战争时，任陕西后方筹备总司令。一九二五年任陕西军务督办。

〔４１〕赵恒惕，参见本书《军阀统治下的中国》一文注〔１１〕

〔４２〕唐氏兄弟指唐继尧和唐继虞。唐氏兄弟为云南会泽人。唐继尧（一八八二～一九二七），一九一七年参加护法运动，借护法自保，排挤孙中山，暗通北洋军阀。为了称霸西南，多次出兵川黔，并召开联省军会议，自称"联帅"。一九二七年被胡若愚、龙云威迫去职。唐继虞（一八九○～一九二四），一九一八年先后任滇黔靖国联军总参谋长、昆明卫戍总司令，权重一时。后历任东南巡阅使、贵州督军等职。

〔４３〕刘显世（一八七一～一九二七），贵州兴义人。一九二○年追随滇系军阀唐继尧任滇黔靖国军副司令，参与川滇黔三省军队混战。战败后为部属驱赶下台。

〔４４〕陆荣廷（一八五九～一九二八），广西武陵人。原系桂系军阀，一九二○年直皖战争爆发，投靠吴佩孚。是年孙中山重回广州就任非常大总统。他企图依靠直系支持，进行反对，因桂系溃败，所部倒戈，逃上海。一九二二年陈炯明发动叛乱时，又潜回龙州，北洋政府任之为"广西军务督理"。

〔４５〕沈鸿英，参见本书《军阀统治下的中国》一文注〔１６〕。

〔４６〕陈炯明，参见本书《军阀统治下的中国》一文注〔１５〕。

