# 美国帝国主义者的对华政策

中文马克思主义文库 -> 周恩来
美国帝国主义者的对华政策
（一九二四年六月十五日）

美政府自华府会议成功，得了列强在中国共同行动的保证后，对华政策即一变其向来阳示亲善的面孔，大踏步地赶上英日帝国主义政府在中国实行侵略的故道。两年多的经历，已使我们饱尝美国帝国主义者的在华一切设施，殆无不备有钱臭和血腥的混合滋味。尤其露骨的，便是美国工商业的资本家，张家口的克门案〔１〕，临城案〔２〕，宜昌的大来案，浙江纸烟捐案，长江舰队联防案，上海美国侨商会议案，无不与他们息息相关。最近沪报载美国在华商务总会的报告有云："......去年本会与美国协会曾致电国务卿，要求增加美国在华利益之保障，所幸本国政府，尚未认为极端主张，已由海军部准添长江巡舰六艘，且已先由檀香山派鱼雷两艘来华。此各国已暂停关税会议，并闻对华债务将有所措置。凡此，未始非吾人要求所生之结果。至国务卿休士亦认定中国时局之严重，并有具体对华政策之决定云。"但什么是"具体对华政策"？请看四月中美国众议院海军委员会所通过的议案：许造一万吨之快巡舰八艘，每艘需费一千一百万元，军装经费在外，并造炮舰六艘，每艘需费七十万元，此炮舰乃供中国海面之用。这个议案审查至六月五日美国上下议院完全通过。美国国务卿的"具体对华政策"实现了，美国工商业资本家的"要求"得到"结果"了，被压迫的中国人从此将更增受了六艘炮舰的射击。
 

然而聪明点的美国人究竟知道这不是个万全的侵略政策。有个美记者李查得·哈顿竟在报上公开说道："溯自一八四一年中国在英国枪尖之下被迫割让香港于英之不幸之日起，以迄华盛顿举行所谓裁军及远东问题会议之日止，中国人民对于西方任何强国始终无可爱可敬之理由。而美政府于兹会中辜负中国人民可靠之友谊，殆为此不幸关系之最后大结束，亦为一号称友邦者对其友之最重打击，且此可谓为中国历史上之转捩点。盖当美国因欲取悦英日两强而出卖中国之前，中国颇有步武西方诸大共和国所取途径之势。今自被卖于美国之后，彼乃觉悟中国必须自立不赖外助，且必须抵抗西方资本主义国家之反对。盖此等国家之唯一目的类为掠夺中国之富饶天产也。......美国最近联合他国，在广州为海军示威运动而以保护条约权利之脆薄理由为根据。此项疯狂举动，可谓铸造中国对西方各国及其蕞尔东邻一串怨恨锁链之最后一环。欲迫中国群众投身于布尔塞维克主义而试行苏维埃制度，美国此举，殆已有充分之效力矣。......西方诸共和国果欲挽回中国，使仍为彼等之姊妹国急超直追或由未晚。但为时已甚迫促，受苦已久之中国人民正在力图自救，无暇久待。若彼等竟断然效法俄罗斯者，则西方世界之烦闷将从此开始矣。"这位美国记者的议论，毕竟有超越美国普通工商业资本家的卓识。设无最后一段话，至少我们会疑心他是个社会主义者。但从"西方诸共和国......使仍为彼等之姊妹国......"数语看来，便知道这是一位不着侵略痕迹的巧妙的新闻记者，会这样说话的人，美国向中国做文化宣传的教育家、传教师、新闻记者、旅行家都惯为之。我们，尤其是从事国民革命独立运动的我们应将他们看成和主持武力侵略的美国帝国主义者是一流人物，严防受他们甜言蜜语的诱惑。

又，美国总统将于本年年底改选了，代表大工商业资本家、大地主的共和党若胜，则柯立芝〔３〕联任，军事的对华政策自然具体的继续施行。否则代表小资产阶级的民主党胜，他们或要采取旧日阳示亲善的对华政策以缓和国人对美恶感。这个，在外表虽有缓急之分实则同一样子有帝国主义从中作祟，我们切须紧紧记牢，一律反对。

＊这是在旅欧期间写的。原载一九二四年六月十五日出版的《赤光》第十期。

注释：

〔１〕张家口克门案发生于一九二二年十二月十一日。美商人乘自用汽车四辆，搭载外人三名，华人十一名自张家口驶出，未遵守当他规则出验护照，拒绝检查，强行开车，并向岗兵连发六枪。岗兵出于自卫还击两枪，伤及美商人克门。一九二三年一月，美使舒尔曼为克门案向外交总长王正廷面致抗议，提出道歉，惩处，赔偿六项要求。一九二三年五月，察哈尔都统张锡元来到美使馆谢罪，克门案全部照美要求解决。

〔２〕临城案参见本书《军阀统治下的中国》一文注〔９〕。

〔３〕柯立芝（一八七二～一九三三），一九二三至一九二九年任美国总统，共和党人。任内反对"侵犯"私有财产，两次否决麦克纳里-霍根农场救济法案；对外推行"新孤立主义"，不愿与外国签订政治协定、参加国联和承担国际义务，但鼓励大企业对外贷款和投资。利用道威斯计划加强美国势力对欧洲的渗入。

