# 勿忘党仇！

中文马克思主义文库 -> 周恩来
勿忘党仇！
（一九二五年八月）

总理去世不到半年，中央党部门前竟演出空前的惨剧！我们的党代表廖仲恺〔１〕先生被刺死了。

廖先生是我们国民党中历史上仅存的有数领袖之一，总理的革命志愿之承继者，孙文主义之最真实的信徒。总理在时，廖先生已担起党中大部分的工作，总理死后，廖先生更成为党中的重心。而今党之重心竟遭惨死，我们岂仅哭我们的党代表，我们更哀痛全党之失却重心！

廖先生一生苦斗，革命为党，牺牲为国，数十年来自种了不少政敌。但是此次死廖先生的决不是普通的政敌，至少我们可以断定这个暗杀案的后边藏有极大的黑幕阴谋。

党代表惨死了，我们最痛心的是党代表不死于他数十年之革命奔走中，不死于东江讨逆〔２〕之棉湖视师中，不死于杨刘作乱〔３〕之恶险空气中，而竟死于国民政府改组后正在秉承总理遗志努力图谋统一广东军政财政以便发展国民革命之进行中，是党代表之惨死，简直为承继总理遗志而牺牲！

廖先生是总理熏陶下一个最有担当者。十余年的革命历史中，他是一个最服从党律而热心作事者，英士执信〔４〕两先生外，我们找不出第三人可以较他再勇往直前凌厉无比。廖先生惨死，使我们同时联想到英士执信两先生之惨死，足以证明死廖先生的敌人竟不容国民党中有最能负责最能工作之领袖存在。

且我党自改组后，最显著的革命势力便是革命军之组织和工农群众之参加革命，这两种伟大事业的做成，多部分的功绩要属之于廖先生。廖先生亦因此而愈加见忌见恨于反革命反工农群众的分子。而且最近几次反帝国主义运动，廖先生更是唯一的急先锋。招帝国主义者--尤其是香港政府之忌，最烈的也莫过于廖先生。廖先生既为反革命反工农群众分子及帝国主义者所忌视，于是廖先生遂为反帝国主义运动、革命运动工农运动而牺牲。

一句话，在总理死后，我们国民党是绝对须要一个承继总理遗志为党最能负责最能工作而又勇于革命运动、工农运动及反帝国主义运动的积极领袖。而今廖先生竟因适当其选之故惨遭那卑鄙狠毒万恶的仇人暗算，在廖先生为党牺牲，求仁得仁，在我们却痛失其领袖。

为党牺牲的领袖死了，我们要认定这是党仇，不是私仇，仇人是来毁党的，不仅仅毁廖先生个人而已。

黄埔党军党校的同志啊！我们为爱党而敬党代表，我们更要为爱党而痛党代表，杀党代表者必是毁党之人。我们要勿忘党仇，誓报党仇！

＊原载《革命军》杂志第八期。

注释：

〔１〕廖仲恺（一八七七～一九二五），广东惠阳人。国民党左派。出身于美国华侨家庭，一八九三年回国。一九○五年参加同盟会，为最早的会员之一。辛亥革命后，任广东都督府总参议。一九二二年后，积极协助孙中山确定联俄、联共、扶助农工的三大政策。一九二四年国民党改组后，被选为中央执行委员会常务委员，并先后担任工人部部长、农民部部长、黄埔军官学校党代表、广东省省长、财政部长、军需总监等职。孙中山逝世后，他坚决执行革命的三大政策。一九二五年八月二十日在广州被国民党右派暗杀。

〔２〕一九二二年六月陈炯明勾结英帝国主义和直系军阀背叛孙中山。一九二三年阵炯明被粤军许崇智击败，率部退守广东东江（惠州、潮汕一带）。一九二五年十月第二次东征之役，"陈家军"全部被广东革命军消灭。

〔３〕刘杨作乱指杨希闵、刘震寰叛乱事件。杨刘是最早投入孙中山旗帜之下的滇桂军将领，他们对革命事业并不抱有热情，而是在广东称雄道霸，并准备借口反对廖仲恺等发动武装叛乱，以实现其推翻广州政府的阴谋。由于共产党的坚强领导，工人阶级和人民群众在与反革命军阀的斗争中显示了无比巨大的威力，一九二五年六月，杨刘作乱被平定。

〔４〕陈其美（一八七八～一九一六），字英士，浙江吴兴人。一九○六年入日本东京警监学校，同年加入同盟会。一九○八年回国。武昌起义爆发，率部光复上海，被推为沪军都督。一九一五年被推为上海讨袁军总司令。同年十二月，陈和杨虎城等发动肇和兵舰起义，失败。一九一六年曾计划在上海发动陆军起事，未成。同年五月十八日被袁世凯暗杀于上海萨坡宝路寓所。

朱执信（一八八五～一九二○），广东番禺人，原籍浙江萧山。一九四○年留学日本攻读法政。次年加入同盟会，被选为评议部议员兼书记。积极参加孙中山领导的反袁（世凯）斗争，并加入中华革命党。五四运动后，在上海协助孙中山撰写《革命方略》，任《建设》杂志和《民国日报》编辑，坚持革命，参加新文化运动，提倡白话文，思想激进。一九二○年为驱逐桂系军阀赴广东联络民军，被桂系军阀杀害于虎门。

