# 国民革命及国民革命势力的团结

中文马克思主义文库 -> 周恩来
国民革命及国民革命势力的团结
（一九二六年十二月十日）


　　近来有人颇怀疑目前许多民众运动违反了国民革命的方式，颇误会许多革命分子在做非国民革命的工作；这个问题极其严重。我们为国民革命利益与其前途计，有以下的话要说。

　　不错，某个时代的革命方式必须"应时代的需要合环境的要求"。否则，便是"反革命"。

　　所以我们很久就肯定国民革命是目前中国唯一的革命。在这革命运动中，任何被压迫阶级的要求都超不出打倒他们共同的敌人国际帝国主义和国内半封建势力以图政治上经济上的民主解放。质言之，就是要求一个民主政纲的实现。

　　理论上既无冲突了，我们且看实际上目前民众运动有无超过国民革命的要求，违反了国民革命的方式。

　　首先说到工人。现时工人运动最易引起非难的，大半是工会擅自捕人，封闭工厂商店，工人持械游行，强取商店什物。这几件事，我们须研究事实真相。广东职工运动要没有行东厂主工贼流氓做分裂工会运动，实际上早已团结坚固，很坦平的向前发展了。怎奈工人要求工会统一，行东厂主却设立了行东工会从事破坏商议，工人因生活痛苦举行罢工，行东厂主却收买工贼从事捣乱。等到破坏捣乱还不足，便雇用流氓殴杀工人，威迫利诱，拆散群众。工人受着这种客观的痛苦于无可如何之中乃不得不组织纠察队自卫队以图自卫，逮捕流氓免遭毒打，防守工厂商店门口以免工贼破坏罢工。这些问题久已成为劳资间工人间的纠纷，国民政府只要设法处理，使工人得到生活保障，他们本无须取这种形式。强取商店什物，果使属诸事实，可以窃盗论罪。罢工事件，原是工人受经济压迫过甚出于不得已之举，条件太高，行动太骤，都有磋商改善的余地；最好就事论事，不必牵动工人运动全体。至于因梧州潮州惨案而引起的工人同情运动，其实在原在几个不法军人，工人的要求仍不出生命保障。

　　在乡村，土匪劣绅贪官污吏实是应该肃清的。只要看到近来农民运动人员被害事件之多，便知乡村反动势力之大。实际上农民目前的要求，不过是减租以维持生活，剿匪以保护生命而已。

　　总之，工农运动并未超过国民革命的要求，而只是国民革命的初步要求：工农的集会自由，工人罢工权，工农生活改善，生命保障等等。至其行动，外间流言说工人要打倒国民政府，打倒某某，实行劳工专政，完全为反动派离间工农与政府之休戚关系。革命的工农知识虽低，但他们需要国民革命之成功，比任何人都感觉急切，决不至如此荒谬以违反国民革命的方式。且工农群众对于国民政府自始即竭诚拥护，在去岁风雨飘摇之中，更会出其死力，他们岂有不要这种给民众以政治自由的政府，而要压迫民众的陈炯明或张作霖的政府么？不过这类流言，自有工农运动以来便有。但因政府与工农群众的团结一致，故流言亦无伤于我们的毫末。

　　学生运动原也有些纠纷，但始终未出国民革命范围。拿一年来的现象比较，现在总算进步了。若还有不完善处，可从教育机关方面图整顿，从青年运动方面谋改善，这种整顿改善，应从革命的利益方面着想。

　　商人方面如除暴安良保护河道等要求，更显而易见乃是民主政治的初步利益。

　　讲到整个民众运动，不管依据孙中山先生的训政方案，或是依据最近政纲关于人民团体的解释，目前广东的民众组织，大家都承认有集议和建议权了。在党政府方面，须指导这些民众团体的集议和建议，在民众方面，亦因晓得国民党的最近政纲为各阶级民众目前最急迫的需要，故决不会有什么超出国民革命的要求。民众团体除掉接受这个政纲，护拥执行这个政纲的国民政府，并无第二条出路。故民众团体应帮助党政府积极宣传这个政纲及次第施行这个政纲。

　　第一点说过了，我们再进而问实际上有无许多革命分子在做非国民革命的工作。

　　在解释国民革命的性质上，人人都承认国民革命是世界革命的一部分。因为如此，关闭的国家主义派所以为反革命，国际性的中国共产派所以加入国民党实行国民革命而成为革命分子。目前的中国政治状况，不但帝国主义的锁链--不平等条约在中国丝毫没有动摇，军阀尚占有全国三分之二的领土，便是在国民政府领域中半封建势力--贪官污吏买办大地主土豪劣绅土匪等还遍地皆是。这时候除掉团结各派民主势力--民族资产阶级、小资产阶级、工农阶级以集中于国民党领导之下向共同的敌人进攻，再没有其他的争斗。在这争斗中，我们可以公然说共产党人不管在反帝国主义的上海省港罢工中，在东征北伐抗军阀的血战中，在北中各部为办国民党遭遇的囚杀中，在工农运动的牺牲中，他们总是最忠实地站在前线。他们所流的血，总是洒向国民革命，无一点迟疑，无一点吝惜。一切工作上他们尚找不出非国民革命的证据。我们更很坚确地认定现时方式国民革命的起首，离成功的逸程还很辽远。所以这时我们希望民主政纲之实现比任人都感觉急切。或正因望之急而肯之切，遂引起许多人的误会，也是意中之事。惟当此北向军阀，外向帝国主义，内向半封建势力作决死战的时候，所有革命分子都应团结起来，何况站在革命前线的共产分子，自应与国民党密切的合作才有打倒我们共同敌人的可能，才能引导工农上解放之路。否则，除帝国主义及国民革命的敌人得到利益外，一切革命分子以至国民革命只有归于失败。

　　我们高呼：

　　一切革命势力团结起来！



　　＊原载中共广东区委机关刊物《人民周刊》第三十四期。



