# 彭杨颜邢四同志被敌人捕杀经过

中文马克思主义文库 -> 周恩来
彭杨颜邢四同志被敌人捕杀经过
（一九二九年九月十四日）

帝国主义、国民党是时时合作以压迫工农群众，以屠杀革命领袖的。尤其是上海的十里洋场，自"四一二"〔２〕以来，在帝国主义强盗与国民党军阀铁蹄之下牺牲的已经有几万人；现时关闭在西牢，在漕河泾，在公安局与警备司令部的，还有成千以上的工农群众、革命战士，过着那无期徒刑的岁月。

近来因世界大战危机日益紧迫，军阀战争还在继续，而群众斗争又在日益开展，于是帝国主义与国民党乃更加紧地合作，向着革命群众与革命的先锋队伍--中国共产党施行更残酷的进攻。彭、杨诸同志便是在他们这种密切的合作、残酷的进攻之下的牺牲者，便是在他们共同的阴谋计算之下遭了暗杀！

彭湃、杨殷、颜昌颐、邢士贞四同志之被捕，日期在一九二九年八月二十四日下午四时许。那时，帝国主义的武装巡捕与公安局的中国包探，驾着几辆红皮钢甲车，如临大敌地到沪西叛徒白鑫夫妇的住家。彼等于弄堂内外布置妥帖后，登楼捕人如像预知的一样，按名拘捕共五人（除彭、杨、颜、邢外，还有张际春〔３〕同志），而对白鑫夫妇则置诸不问。人捕齐后，于白鑫床下搜出一些革命刊物，如《布尔塞维克》、《红旗》〔４〕及共产党的中央通告等。被捕五同志当即为警探拥上汽车，直驶向新闸捕房。此事发生后，各报均禁止登载，因此广大的群众直不知其领袖有此被捕的事件。

二十五日为星期日，临时法院不办公。二十六日法院开审，合作的帝国主义走狗法官与公安局代表故意做作一番，然后判交公安局引渡带去。在审问时，只被捕五同志到案，照片已于被捕当日弄好，按名询问，显然叛徒白鑫已在暗中作证指明。引渡时，公安局亦以铁甲汽车武装解入城内公安局。审问与引渡情形，曾载在当日晚报，但未将其真姓名宣布。这是统治阶级故意如此，为的是避免广大群众严厉的直接反抗。

彭、杨五同志至公安局，当晚即开审，问官一无所得。而彭、杨五同志在看守所中即开始宣传，许多保安队员为之感动。二十七日下午复开审，审问历四五小时。问至彭湃同志，有人出为证明，彭湃同志公开承认。问官询其经过历史，彭同志慷慨而谈，历时一点多钟，从未入党以前在海陆丰做农民运动起，直谈至在海陆丰建立苏维埃的经过。当谈至在海陆丰惩办反革命时，彭同志向审问官抗声说道：似你们这班反革命党，我们在海陆丰不知杀了好多，你现在不必再问了，将我枪毙好了。问官亦为之动容。问至杨殷同志，杨殷同志亦公开承认自己的经过。审问毕，回至看守所，五同志齐唱国际歌，以赋同仇，直影响了全所。

第二审过后，公安局深惧有意外，至二十八日清晨即转解警备司令部。适当晚发生了蒋介石被刺事，一切嫌疑卫兵统押至司令部。上至熊式辉〔５〕，下至司法科，统忙得屁滚尿流。被押卫兵，经严刑拷打，血肉横飞，骨折肢断，无一肯供出刺蒋来源。于是五同志在押的三天中（二十八-三十日）未经一审，只是手铐脚镣，铁链钉铛，被严重地看管在司令部看守所中。在这三天中，五同志没放过一刻机会，不断向在狱群众与司令部内的士兵宣传。当彭、杨诸同志与士兵谈至痛切处，士兵中竟有捶胸落泪，痛骂国民党军阀非杀尽不可的。当他们说至激昂处，便齐唱国际歌与少年先锋歌〔６〕，士兵与狱中群众亦高呼口号和之，于是愁苦惨淡的狱中，一变而为激昂慷慨的沙场。有些因贫穷而走入抢劫的盗犯，他们都感动而觉悟道：只有跟共产党走，才是我们穷人的正当出路！有些因革命嫌疑而下狱的群众乃更加坚决说：我们今后只有革命的一条路了！有些被难的同志则说道：到底是我们的中央领袖，能做我们的表率！有些久闻彭湃大名的人，闻得彭湃在此，均争相来看；还有几个识得彭湃的人，均以旧时相识为荣。

他们入警备司令部后，已知必死，故他们传出书信多是遗嘱之辞。他们嘱咐党中同志不要因他们被捕而伤痛，要继续努力谋得革命的发展。他们嘱咐党中重要负责同志要为党惜身。他们望党内对于反对派〔７〕的斗争要多从教育上做功夫，以教育全党。他们相聚谈话时，亦曾谈及许多政治问题，可惜未曾传出他们所谈的内容。他们都是谈笑自如，杨殷同志曾笑说："朝闻道，夕死可矣。"他们对于自己爱人的遗嘱，都是勉其为党努力。

在三十日这天，临时法院忽又故意票传五人复审。司令部遂亦于当天午后，在形式上将五人严密地解送至法院。到法院时有步兵一排，公安局包探多人，司令部副官几个，并有捕房巡捕携手提机关枪两架跟着警戒。法院在特别法庭开审，不许人旁听，问辞与供辞如上次。法官与陪审之帝国主义领事及捕房律师都含糊其辞地说了一些，并未将彭、杨等同志罪状究是些什么公开宣布。被告律师虽说了一些，法官等并不注意，最后判决文亦无人能听见法官究竟读了些什么。直至彭、杨等四同志已经枪毙了，上海英文报上忽皇皇地登着法院判决文是处彭、杨等同志以八年的有期徒刑。这一复审，简直是帝国主义强盗与国民党军阀合作的一出滑稽的杀人剧。他们想以法律的手续来欺骗群众，但又深恐怕群众晓得。其实，广大的革命群众老早就不相信你们这种鸟法律了！从一九二七年的"四一二"到现在，帝国主义者与国民党不知暗杀了冤杀了几多群众。屠杀成河的血，早已染红了工农劳苦群众的心，他们只知道以群众的斗争力量来回答你们的白色恐怖，谁还管你们的鸟法律！

在临时法院审后，即刻又武装紧严地解回警备司令部。当由法庭回至囚车时，颜昌颐同志举手呼共产党万岁，五人相视而笑。至司令部，先回看守所，当即送进一桌酒饭，五同志都知是死期已届，谁还肯吃这一桌劳什子"赏饭"！约一小时，便提彭湃、杨殷、颜昌颐、邢士贞四同志行刑。他们四人慷慨地向士兵及在狱群众说了最后的赠言，唱着国际歌，呼着口号出了狱门，引得一般士兵及狱犯都痛哭失声，甚至看守所员都为之掩面。行刑是秘密的，枪毙地点并未出司令部，开熊式辉任内之先例，其严重与畏惧之情可想而知。四同志死时的枪声，狱中群众隐约闻见。有一狱犯特杀鸡一只望空致祭，可见其感动之诚！四同志死时特留下内衣三件作为纪念，成为最后的遗物！死后，司令部又秘密地派人掩埋，以图灭迹。但是，广大的革命群众虽看不见他们领袖的英勇遗体，然他们领袖之英勇的战绩，却永远光明地纪念在每一个人的心中，永远不会湮灭。

当着彭、杨五同志初被捕时，南京国民党中央便得到上海国民党市党部的夸功报告。他们的回电是命令熊式辉着即枪毙，加以刺蒋案件忙得这班走狗们寝食不安，所以枪毙的执行乃更加迅速。

阶级斗争剧烈的今日中国，革命的群众、革命的领袖死在敌人的明枪暗箭中的不知几多！这原是革命成功前所难免的事变，而且是革命成功之血的基础，没有前仆后继的革命战士，筑不起伟大的革命的胜利之途！每一个革命战士牺牲，不管是在前线，是在后方，都有他伟大的代价。尤其是革命领袖的牺牲，更有他不可磨灭的战绩，照耀在千万群众的心中，熔成伟大革命的推动之力，燃烧着每一个被压迫群众的革命热情，一齐奔向革命的火原！所以我们在死难的烈士前面，不需要流泪的悲哀，而需要更痛切更坚决地继续着死难烈士的遗志，踏看死难烈士的血迹，一直向前努力，一直向前斗争！

的确，彭、杨、颜、邢四烈士的牺牲是中国革命、中国党之很大的损失！革命的领袖是积了无数次的斗争与战绩，从广大的群众中涌现而锻炼出来的。敌人可以在几分钟内毁灭了我们革命的领袖，我们却不能在几分钟内锻炼出我们新的领袖。故敌人消灭我们肉体的办法，是压迫革命之最殊酷最恶毒的办法。我们只有努力于群众的斗争，加紧群众的斗争，使群众的斗争力量足以消灭白色恐怖，消灭敌人的屠杀，则革命的胜利便将临近，敌人的统治便届末日！只有这样，我们才能偿赎今日的损失！只有这样，我们才尽了彭、杨四烈士的遗志！才报了我们被压迫阶级的大恨深仇！

国民党、帝国主义一班强盗用鬼蜮的伎俩、卑鄙的手段来谋害革命，来暗杀革命领袖，我们革命群众对他们的回答，却永远是赤裸裸的公开的阶级斗争！仅只这一点差别，便是我们战胜敌人的利器。因为只有公开斗争才能争取广大群众，只有群众力量才能消灭敌人！惯于阴谋暗杀的国民党、帝国主义一班强盗，便要在这公开的阶级斗争中一齐消灭，一齐死绝！

工农兵士劳苦群众们！革命先锋战士们！烈士的革命精神不死！我们的奋斗不绝！踏着烈士的血迹前进！前进！努力地前进！直进到革命的最后胜利！

＊本文发表于一九三○年八月三十日中共中央机关报《红旗日报》。原载《周恩来选集》上卷。

注释

〔１〕彭，即彭湃；杨，即杨殷；颜，即颜昌颐；邢，即邢士贞。他们是一九二七年八月三十日在上海龙华被敌人杀害的烈士。

彭湃（一八九六～一九二九），我党最早的农民运动领袖。一九二二年七月在海丰县赤山创建了全国第一个农会。一九二三年一月当选为海丰总农会会长。一九二四年参加中国共产党。同年创办广州农民运动讲习所，并任中共两广区委委员。一九二五年五月当选为广东省农民协会副委员长。一九二七年参加南昌起义，任中共前敌委员会委员。南昌起义失败后，领导了海陆丰第三次武装起义，创立海陆丰苏维埃，任委员长和东江特委书记。一九二八年任中共中央农委书记兼江苏省委军委书记。在党的第五、六次全国代表大会上当选为中央委员，在"八七"会议上被选为政治局委员，在党的第六次全国代表大会上当选为政治局候补委员。

杨殷（一八九三～一九二九），早年参加同盟会。一九二三年参加中国共产党。第一次国内革命战争时期担任中共两广区委委员，是省港罢工的领导者之一。一九二七年十二月十一日广州起义时任广州苏维埃政府人民委员会代理主席和肃清反革命委员会主席。一九二八年在党的第六次全国代表大会上当选为中央委员、政治局候补委员、中央常委，并任中央军事部长。

颜昌颐（一八九八～一九二九），一九二一年参加中国共产党。一九二五年在中共中央军委、湖南省委军委工作。一九二六年十月到一九二七年三月参加上海工人三次武装起义。一九二七年参加南昌起义，任二十四师党代表。南昌起义失败后，和澎湃一起发动海陆丰第三次起义，创建海陆丰苏维埃，任红军党代表。一九二八年任中共中央军委委员兼江苏省委军委委员。

邢士贞（？～一九二九），一九二七年参加中国共产党。当时是中共江苏省委军委干部、士兵运动负责人。

〔２〕"四一二"，指蒋介石一九二七年四月十二日在上海发动的反革命政变。参见本书《迅速出师讨伐蒋介石》一文注〔３〕。

〔３〕张际春（？～一九三三），共产党员。一九二九年任上海总工会纠察队副总指挥，同年领导上海五月三十日和八月一日两次反帝大示威，八月二十四日被捕，一九三一年冬出狱。

〔４〕《布尔塞维克》杂志，中共中央机关刊物。一九二七年十月二十四日创刊，一九二八年十一月前为周刊，后改为半月刊。现在查到的最后一期是一九三二年七月出版的第五卷第一期。

《红旗》，中共中央机关报。一九二八年十一月二十日创刊。共出一二六期，前二十三期是周报，后一○三期是三日报。一九三○年八月二日停刊，同月十五日和《上海报》合并为《红旗日报》。一九三一年二月十四日《红旗日报》改为中共中央和中共江苏省委机关报。同年三月九日改名《红旗周报》，为中共中央机关报。现在查到的最后一期是一九三四年三月一日出版的第六十四期。

〔５〕熊式辉（一八九三～一九七四），当时任国民党军第五师师长兼淞沪警备司令。

〔６〕《少年先锋队歌》，苏联诗人别塞勉斯基填词的革命歌曲，原名《青年近卫军》，一九二二年定为苏联共产主义青年团团歌。第一次国内革命战争时期传入中国，改称《少年先锋队歌》。

〔７〕反对派，指当时中国共产党内出现的由一小批托洛茨基分子组成的反党小集团。第一次国内革命战争失败后，中国的托洛茨基分子以"左"的面目出现，不承认当时中国革命的性质是资产阶级民主革命，主张立即没收资本家的工厂企业，进行社会主义革命。他们在组织上进行分裂党的派别活动。一九二八年八月，党中央决定开展反对托派的斗争，号召全党在思想理论上驳斥托派的谬论，对托派骨干分子一律清除出党，对一般分子，主要采取教育方法，争取他们放弃托派观点，回到马克思主义立场上来。

