# 托洛茨基反对派在中国发生的原因及其前途

中文马克思主义文库 -> 周恩来
托洛茨基反对派在中国发生的原因及其前途
（一九二九年十月）


　　中央第四十四号通告〔２〕上说：固然我们不必夸大反对派〔３〕在中国党内之政治上组织上的作用，但是他们的活动情形与反党现象的发展，实不容许党丝毫忽视。
 
　　反对派在中国发生的主要原因，是中国大革命之失败与新的革命浪潮之复兴，存留在党内落后的小资产阶级"同路者"形成了反对派发展的基础。有人说，反对派在中国的发生是因为有了"莫斯科回来的学生"。这是错误的，他们只是起了反对派的介绍作用。现在，我们指出反对派发生的几种主要的客观的原因。

　　第一，南京政府在初成立时，很注意如何引俄国反对派到中国来，以分裂中国共产党。托洛茨基反对派这个"宝贝"不但为欧洲的资产阶级所利用，即中国的统治阶级也一样地看上了。在联共的反对派坚决地固执他们的路线时，欧洲资产阶级即非常之注意，想利用他们分裂联共的组织，破坏联共的正确路线。在中国，胡汉民〔４〕、戴季陶〔５〕、周佛海〔６〕，都企图借着宣传反对派以分裂中国党。中国的统治阶级恨不得抓住中国党内的这一工具，以达到消灭中国革命领导者的目的。中国的政治环境的确容许反对派在中国活动。这是反对派在中国发生的第一个客观原因。

　　第二，在革命失败之后，必然有许多失败的情绪，引起许多争论的问题。俄国在一九○五年以后，德国在革命失败后，都有过这样的情形。中国大革命失败后，亦是如此。中国党自"八七"会议〔７〕以后，对于机会主义的纠正，在组织上有相当成功，但在理论上思想上的斗争，并未完成，直到六次大会〔８〕，才有相当成功；然党内种种不良的倾向，以及大革命失败以来的不同的政治倾向，尤其是机会主义的倾向，还都是待机而动。这是中国发生反对派的第二个原因，也就是所以形成中国党内机会主义--反对派结合之思想上组织上的根本原因。

　　第三，中国党的党内生活，到现在还不能说是完全健全。虽然在组织上肃清机会主义，引进工人分子入党，但尚未把支部生活坚固地建立起来。因此，党的生活上，常发生动摇的现象。党的正确路线还未得到有些支部全体热烈的讨论，因之，党的政治路线在组织上遂尚未得到完全巩固。有些支部对某一问题，常不能在正确路线下予以回答，常因某一问题不能回答而表现动摇。在上海，有些中心的产业支部并不巩固，有些产业支部非常缺乏政治生活，因此，斗争胜利了，支部就活跃；斗争失败了，支部就消沉，甚至有瓦解的。这表明政治路线还没有得到组织上的完全巩固，不但反对派可以借此活动，即机会主义者亦容易去活动。这是第三个客观原因。

　　第四，大革命失败以后，许多国共合作时代的动摇分子，有脱离工作的，有坚持地方观念的，有固执自己错误的，这些在组织上并未克服。他们专以个人的小问题闹无原则的纠纷，而反对派就抓住了这些不满意党的路线的分子，利用这种无原则的斗争，以进行其反党的活动。这是第四个客观原因。

　　尽管过去没有发生过反对派的活动，然而有了这四个原因，就必不可免地使中国有反对派暂时活动的可能。自然直接的原因，还是回国的学生与机会主义的复活。

　　至于托洛茨基反对派活动的策略路线，我们可以看出有下列四点：

　　第一，必然不可免地要与统治阶级勾结。《新生命》〔９〕已经登过关于反对派的文章。将来反对派更要利用统治阶级的宣传机关，以进行其帮助统治阶级反党的活动。如果在党内斗争中失败，他们必然会整个卖给统治阶级。这是必不可免的前途。

　　第二，在一切当前实际问题上表现他们的反党路线的宣传与活动。他们在"五卅"〔１０〕纪念时，宣言号召同志向党斗争，要比反帝国主义斗争更重要，客观上毫无疑义地是帮助敌人。"八一"示威〔１１〕，他们又认为是盲动主义，反映出许多失败的情绪。有论调上表现出极右的悲观的取消主义。

　　第三，利用某些不健全的支部生活，以实行其停留在支部内活动的策略。他们借着停留在支部内，以动摇下层群众，并专门找斗争失败的支部，专利用失败的事实，以攻击党的路线。当斗争困难时，反对派在宣传上可以说出极左的口号，如"没收工厂"，以使工人阶级孤立，并引导工人群众幻想未来的天国而忽略了目前斗争的实际意义；反之，在实际问题上却又提出极右的策略，使工人支部走到无出路的消沉状态。

　　第四，与中国的机会主义者结合。这些机会主义分子因为固执自己的路线，现在既不能深入群众，又不能不找一新的政纲，以掩饰自己的错误。这样，反对派的政纲，正好在掩饰自己过去的错误上，在口头上"左"的革命口号而实际上右的革命形势的估计与策略上，恰恰脾胃相合，于是就被他们利用了。而反对派的策略，也正是要利用这些分子帮助他们进行反党的活动。机会主义者与反对派在"惺惺惜惺惺"〔１２〕的情形之下，便结合起来了。

　　此外，托洛茨基反对派抛开原则，专门利用些小的问题小的纠纷，进行非事实的毁谤与有意的造谣诬蔑，企图用这些卑劣无耻的手段以破坏同志对党的指导机关的信仰。这除了帮助敌人破坏革命的指导者以外，简直没有任何意义。

　　在上海、香港、北方，都发现有反对派的活动。他们在组织上对党是秘密的。惟其如此，就更应该将这一问题提到下层去，指导同志们讨论与坚决地肃清一切机会主义--反对派的活动。反对派有些并不公开表示自己的意见，有些我们已知道他们有反对派的倾向，有些尚不知道。因此，这一问题必须提到支部中，运用这一机会教育同志，树立党的正确路线的基础。务使每个同志认识以正确的路线同不正确的路线斗争之必要，使党的正确路线得到组织上的巩固。所以，除了组织上的制裁之外，思想上理论上的斗争是绝对必要的，这是目前巩固党的很重要的武器！



　　＊这是在中共中央直属支部干事会上所做的报告。原载《周恩来选集》上卷。

　　注释：

　　〔１〕托洛茨基反对派，参见本书《无产阶级革命的俄罗斯》一文注〔４〕。

　　〔２〕中央第四十四号通告，指一九二九年八月十二日中共中央发布的《关于中国党内反对派问题》的通告。

　　〔３〕反对派，指当时中国共产党内出现的由一小批托洛茨基分子组成的反党小集团。第一次国内革命战争失败后，中国的托洛茨基分子以"左"的面目出现，不承认当时中国革命的性质是资产阶级民主革命，主张立即没收资本家的工厂企业，进行社会主义革命。他们在组织上进行分裂党的派别活动。一九二八年八月，党中央决定开展反对托派的斗争，号召全党在思想理论上驳斥托派的谬论，对托派骨干分子一律清除出党，对一般分子，主要采取教育方法，争取他们放弃托派观点，回到马克思主义立场上来。

　　〔４〕胡汉民（一八七九～一九三六），第一次国内革命战争时期曾任代理广州大元帅府大元帅兼广东省长等职，著名的右派首领，是一九二七年蒋介石发动"四一二"反革命政变的同盟者。后来同蒋介石集团争权夺利，长期对立。

　　〔５〕戴季陶（一八九○～一九四九），第一次国内革命战争期间，歪曲孙中山学说的革命内容，散布反对共产党、反对工农运动的谬论，为蒋介石发动反革命政变进行思想上的准备。"四一二"反革命政变后继续忠实追随蒋介石。

　　〔６〕周佛海（一八九七～一九四八），一九二一年曾参加中共第一次全国代表大会，一九二四年叛党。蒋介石叛变后曾任国民党中央宣传部长等职。抗日战争开始后随汪精卫叛国投降日本侵略者，任汪伪政府行政院长等职。

　　〔７〕"八七"会议，即一九二七年八月七日在汉口召开的中国共产党中央紧急会议。出席这次会议的有党的中央委员、监察委员等二十一人。瞿秋白在会上作了《将来工作方针》的报告。会议通过了《告全党党员书》和农运、工运及组织问题等决议案，改选了中央领导机构。这次会议在中国革命的危急关头坚决地纠正和结束了陈独秀的投降主义，确定了土地革命和武装反抗国民党反动派屠杀政策的总方针，号召党和人民群众坚持革命斗争，这些都是正确的，是它的主要方面。但是，在反对右倾投降主义的时候，不认识当时应当根据各地不同情况，组织恰当的反攻或必要的策略上的退却，在组织上开始了宗派主义的过火的党内斗争，因而为后来的"左"倾错误开辟了道路。

　　〔８〕"六大"指一九二八年六月十八日至七月十日在莫斯科召开的中国共产党第六次全国代表大会。会上，瞿秋白作了《中国革命与共产党》的报告，周恩来作了组织问题和军事问题的报告，刘伯承作了军事问题的补充报告。会议通过了政治、军事、组织等问题的决议案。这次大会肯定了中国社会是半殖民地半封建社会，中国当时的革命依然是资产阶级民主革命，指出了当时的政治形势是在两个革命高潮之间和革命发展的不平衡，党在当时的总任务不是进攻，不是组织起义，而是争取群众。会议在批判右倾机会主义的同时，特别指出了当时党内最主要的危险倾向是脱离群众的盲动主义、军事冒险主义和命令主义。这次大会的主要方面是正确的，但也有缺点和错误。它对于中间阶级的两面性和反动势力的内部矛盾缺乏正确的估计和适当的政策；对于大革命失败后党所需要的策略上的有秩序的退却，对于农村根据地的重要性和民主革命的长期性，也缺乏必要的认识。

　　〔９〕《新生命》是周佛海主编的反动月刊，一九二八年在上海创刊。

　　〔１０〕"五卅"，参见本书《现时政治斗争中之我们》一文注〔３〕。

　　〔１１〕一九一九年七月，在第一次世界大战中支持帝国主义战争的第二国际，议决八月一日在瑞士卢赛恩召开代表大会。共产国际执行委员会号召全世界工人在这一天举行游行，向第二国际示威。一九二九年七月，共产国际执行委员会第十次全会决定八月一日为国际反对帝国主义战争日。这一天，中国共产党在上海组织了反帝示威。

　　〔１２〕惺惺惜惺惺，原意是聪慧的人爱惜聪慧的人。这里借用这句成语，形容机会主义者和反对派同类相聚。



