# 决心扫此两军间合作之障碍——致张学良

中文马克思主义文库 -> 周恩来
决心扫此两军间合作之障碍——致张学良
（一九三六年四月二十二日）


汉卿先生：
 
　　坐谈竟夜，快慰平生。归语诸同志并电前方，咸服先生肝胆照人，诚抗日大幸。惟别后事变益亟，所得情报，蒋氏〔２〕出兵山西原为接受广田三原则〔３〕之具体步骤，而日帝更进一步要求中、日、"满"实行军事协定，同时复以分裂中国与倒蒋为要挟。蒋氏受此挟持，屈服难免，其两次抗议蒙苏协定〔４〕尤见端倪。为抗日固足惜蒋氏，但不能以抗日殉蒋氏。为抗日战线计，为东北军前途计，先生当有以准备之也。

　　敝军在晋，日有进展，眷念河西，颇以与贵军互消抗日实力为憾。及告以是乃受日帝与蒋氏之目前压迫所致，则又益增其敌忾，决心扫此两军间合作之障碍。先生闻之得毋具有同感？兹如约遣刘鼎〔５〕同志趋前就教，随留左右，并委其面白一切，商行前订各事。寇深祸急，浑忘畛域，率直之处，诸维鉴察。

　　并颂勋祺！

　　周恩来拜

　　四月二十二日晨

　　以哲〔６〕军长处恕不另笺。



　　＊原载《周恩来书信选集》。

　　注释：

　　〔１〕张学良，一九○一年生，字汉卿，辽宁海城人。东北军爱国将领。一九三五年十月起任国民党政府军西北"剿总"副司令。一九三六年四月九日邀周恩来到肤施（今延安），就停止内战、联合抗日以及双方通商和互派代表等问题进行谈判。同年十二月十二日和杨虎城一起以国家民族利益为重，以忘我的大无畏精神，毅然发动了西安事变，支持中国共产党关于"停止内战，一致对外"的主张，促成了挽救国家民族危亡的统一战线，推动了国共第二次合作，奠定了全民抗战的基础。周恩来盛赞张杨两将军为"千古功臣"。西安事变和平解决后，张学良被蒋介石长期关押。

　　〔２〕蒋氏，指蒋介石。一九三六年二月，中国共产党为了以实际行动促成全国抗日的实现，由中国工农红军第一方面军以中国人民红军抗日先锋军的名义东渡黄河抗日。这一行动遭到阎锡山、蒋介石的武力阻拦。蒋介石先后派遣约十个师进入山西，协助阎锡山进攻抗日先锋军，并命令西北军、东北军等部进攻陕北根据地。

　　〔３〕一九三五年十月，日本外相广田弘毅对中国驻日大使提出所谓"对华三原则"，作为日本政府同国民党政府进行谈判的基础。其主要内容是：一、中国取缔一切抗日运动，放弃依赖英美的政策；二、中国承认伪"满洲国"，树立中日"满"经济合作；三、中日共同防共。

　　〔４〕在日本帝国主义屡次侵犯蒙古人民共和国边境的形势下，一九三六年三月十二日苏联政府和蒙古人民共和国政府签订互助议定书，即蒙苏协定。协定规定如苏联或蒙古人民共和国遭受任何第三国攻击时互相支持。国民党政府外交部对此曾以"侵害中国主权"为由，于同年四月七日和十一日两次提出抗议。

　　〔５〕刘鼎（一九○三～一九八六），四川南溪人。当时受中国共产党委派，在红军与东北军之间做联络工作，后任中共驻东北军代表。

　　〔６〕以哲，即王以哲（一八九六～一九三七），吉林宾县（今属黑龙江）人。东北军爱国将领。西安事变时任东北军第六十七军军长。由于张学良被蒋介石扣留，东北军内部在如何营救张的问题上发生分歧。部分少壮军官主张用武力解决，王以哲等主张和平解决。在反动势力的挑动下，一九三七年二月二日王以哲被少壮派刺杀。



