# 请撤兵释张实践诺言——致蒋介石

中文马克思主义文库 -> 周恩来
请撤兵释张实践诺言——致蒋介石
（一九三七年一月十一日）


蒋先生：
 
　　自汉卿〔１〕先生陪送先生回都后，此间一切安然，静候先生实践诺言，完成和平统一大计。及撤兵令下，特赦呈文发表，愈使大家认识先生顾全大局之心，钦佩无所。乃事未及周，先生请假归里，中央军竟重复开入陕境，特赦令转为扣留，致群情愤激不可终日。尤以处置西北善后之部令〔２〕与先生意图完全相违，虎城〔３〕先生虽力持慎重，但一般将士实已愤慨万分。来居此仍本共产党红军历来主张之对内和平、对外抗战之一贯方针，尽力调处。来敢保证，只要中央军不向此间部队进攻，红军决不参加内战。但默察现状，中央军进入潼关者已达十二师，正向西安迈进，窥敬之〔４〕部长意图似有非逼成内战不止之势。现先生虽假中，但战机危迫，先生以一系全国安危，待先生力排众议，坚持前令，尽撤入陕甘之兵，立释汉卿先生回西北主持，则内战可弭，和平可坚，一切人事组织、政府主张、抗战筹备均将循先生预定之方针前进，统一御侮之大业必可速就。虽然者，一部分主战之士将不顾大局，挑起内战，不仅西北糜烂，全国亦将波及尤疑，而垂成之统一局面又复归于破碎。此事之痛，除日寇及少数亲日分子称快外，不特为全国同胞所反对，想亦为先生所不忍见不愿为也。

　　来承召谈，只以大兵未撤，汉卿先生未返，暂难抽身。一俟大局定，当即入都应约。如先生认为事宜速决，请先生以手书见示，保证撤兵释张，则来为促进和平、赞助统一，赴汤蹈火亦所不辞。至一切西北赤化谎言，先生及汉卿先生均知之审，必能辨其诬。凡来为先生及夫人与张、宋〔５〕诸先生言者，我方均绝对保证实践。且为外交计，来及党人在此遵先生约，均守秘密，更无向外广播之可能。盖凡能为对内和平、对外抗战尽力者，我方愿举全力为先生助也！专此奉达，伫候回教，并颂

　　起居佳胜！不一。

　　蒋夫人均此不另。

　　周恩来

　　一月十一日午



　　＊原载《周恩来书信选集》。

　　注释：

　　〔１〕汉卿即张学良，参见本书《决心扫此两军间合作之障碍》一文注〔１〕。

　　〔２〕西安事变和平解决后，国民党政府行政院和军政部于一九三七年月五日分别发表陕甘整理办法，主要内容是：派顾祝同为军事委员会委员长西安行营主任；西安绥靖主任杨虎城撤职留任，调整陕甘地区部队驻地。一月六日，国民党政府又颁令撤销由张学良任副司令的西北"剿匪"总司令部。

　　〔３〕杨虎城（一八九三～一九四九），陕西蒲城人。西北军爱国将领。当时任国民党政府军第十七路军总指挥、西安绥靖公署主任。一九三六年十二月和张学良一起发动西安事变，要求蒋介石停止内战、一致抗日。后被蒋介石长期囚禁。一九四九年在重庆被杀害。

　　〔４〕敬之，即何应钦（一八九○～一九八七），贵州兴义人。当时任国民党政府军政部部长。

　　〔５〕宋，指宋子文，当时任国民党中央执行委员、国民党政府经济委员会主席。



