# 国内问题应迅速解决——致蒋介石

中文马克思主义文库 -> 周恩来
国内问题应迅速解决——致蒋介石
（一九三七年七月十五日）


蒋先生赐鉴：
 
　　来庐后所陈宣言〔１〕，已荷阅正，从此露布四方，当能使举国同慰。现在华北炮火正浓，国内问题更应迅速解决，其最急者为苏区改制与红军改编之具体实施。昨蒙面示张淮南〔２〕君转达各节，其中关于同盟会纲领〔３〕，承允讨论，极为欣慰。惟关于军队统率问题，与前次庐山所示又有出入，实使来惶惑，无以自解于党中同志。缘上次在庐，承面告三师以上不能设指挥部时，来即陈说红军在改编后无统率机关以管理人事、经理教育、指挥等事的困难。先生当答以可由政治机关如政治主任来管理联络。来彼时曾反问政治机关如何能指挥军事，先生曾说："我要你们指挥，你们亦实能指挥，这是没有问题的。"面谒后，来以政治名义管理军队究嫌不妥，曾向子文〔４〕先生及蒋夫人再三陈说三个师以上的统率机关应给军事名义，因先生坚持未允，来乃归陕北磋商，中间并一度来电重申前请，得慕尹〔５〕主任代复亦仍嘱以庐山所谈办法解决。来即据此再三向党中军中诸同志解释，告以只要政治机关能够统辖人事、经理教育、指挥各事，名义如何应勿计较，各同志始不再争。乃昨据张君转告，部队在改编后各师须直隶行营，政治机关只管联络。此与来上次在庐所面聆及归陕向党中诸同志所面告者出入甚大，不仅事难做通，且使来一再失信于党中同志，恐碍此后各事之进行。

　　林、秦〔６〕两同志若能同时晋谒，更所切盼。专肃。

　　敬颂

　　崇祺！

　　周恩来启

　　七月十五日



　　＊原载《周恩来书信选集》。

　　注释：

　　〔１〕指《中共中央为公布国共合作宣言》，参见本书《宣言》全文。

　　〔２〕张淮南，即张冲（一九○四～一九四一），字淮南。浙江温州人。曾任国民党执行委员、中央组织部代理副部长等职。抗战期间作为国民党代表参加国共谈判。在抗战中，张冲坚决赞成国共合作，共御外侮，同周恩来建立了良好的合作矢系。一九四一年八月，张冲病逝，周恩来深为哀悼，除在《新华日报》发表《悼张淮南先生》一文，亲自参加追悼会，并致送挽联："安危谁与具；风雨忆同舟。"对张冲在团结抗战中的作用，给予了充分肯定的评价。

　　〔３〕为了控制、削弱和溶化中国共产党，一九三七年六月，蒋介石在国共两党庐山谈判期间，提出由国民党与共产党选派同等数量人员合组国民革命同盟会，作为国共合作的方式。蒋介石为该会主席，有最后决定权；两党一切对外行动及宣传，由同盟会讨论决定，然后执行；该会可代替中国共产党直接与第三国际发生关系。此外，还要制定一个同盟会的纲领。经过几次磋商，中共代表最后拒绝了这一提案。

　　〔４〕子文，即宋子文。参见本书《请撤兵释张实践诺言--致蒋介石》一文注〔５〕。

　　〔５〕慕尹，即钱大钧（一八九三～一九八二），江苏吴县人。当时任蒋介石侍从室第一处主任兼侍卫长。

　　〔６〕林，指林伯渠。当时任陕甘宁边区政府主席。秦，指秦邦宪。当时任中共中央组织部部长。他们作为中共代表，在庐山与国民党谈判。



