# 目前抗战危机与坚持华北抗战的任务

中文马克思主义文库 -> 周恩来
目前抗战危机与坚持华北抗战的任务
（一九三七年十一月十六日）

一　目前抗战形势及其危机

在上海太原相继失陷后，目前抗战局势，正遇着一个新的危机，这个危机的特点，是政府军队抗战颇难为继而全民抗战犹未兴起的青黄不接，国内外调停的空气相当抬头。具体的分析来看：

甲、在战局方面--日寇已占领上海，突破松江，我军防线已退至嘉善苏州昆山浏河之线。华北方面，自占领太原后，敌人已进逼汾阳介休子洪镇之线。平汉津浦亦有前进消息。日寇企图是想在稍加整理后，压迫我大军退过黄河南岸，以便其向全世界宣告：华北战事已告段落，上 海亦已占领。他将从事于华北自治，上海中立，分化蒙回，捣乱华中华南的计划。这一计划可以在口头的停战协定掩护之下来进行，以欺蒙列强，利诱汉奸，这比明枪真火来得毒辣！

乙、在国际方面--九国公约〔１〕会议，虽表示了英美的接近与积极，但他们中心仍在调停。他们不愿考虑制裁手段，因此日本愈强硬他们愈无办法，而其调停中心，仍在企图苟安。这只有损害中华民族利益才能做到，因此，驻沪领事团公开从事和平运动，德意完全赞成日本说话，日本不但拒绝参加九国公约会议，并提出他的六项要求，英美并预言如果日本态度强硬，中国坚持抗战，他们将使九国公约会议延续下去，准备觅取新机从事调停。苏联因英美态度如此，自不能单独行动，虽说他在道义上、在实际上已给了中国以有力的帮助。

丙、在军事上--中国正规军队，现已用到相当的数目，而全民全面的动员，军队的改造，战略战术的改变，后方工作的改善，在全国范围内依然没有开始。战争的失利，部队的损伤，给养的不充，这使部分的军人发生颓丧失望的心理。如恃着现有的正规军持久抗战，其胜利信心确已锐减。

丁、在民众动员方面--三四月来，不但政权没有开放，民运也没有开放，直到现在，党部仍固执其统制民运的政策。因此，包而不办，是普遍现象。于是许多大城市民运，反不如过去局部抗战时的活跃，前线则不得民众的响应，后方得不到民众的援助，民众武装不能组织。这是给日本造顺民给自己造反对者。不怕战争失利，最怕战争失了人心！失掉民众--这是万劫不复的。

由于上述的严重现象，遂至国内外妥协调解空气渐渐抬头而发生了下列的危机：

（１）汉奸政权的活跃--华北自治政府，上海华北维持会，内蒙独立，汉奸的活跃等等。

（２）投降主义的生长--亲日派的活跃，主张对日直接谈判，英美系的软弱，主张依靠英美谈判条件，没有自力更生的信心。对苏联失望的人，主张结束战争。这一切都是投降主义的变相。汪说主和者是汉奸，蒋亦说抗战到底，目前讲妥协者是汉奸。政府给中国代表团的训令，亦说日军不从中国撤退，没有调解的余地--这是反对投降主义的当头棒！

（３）特殊化思想的增长--从冀察特殊化的影响，至今尚引诱着许多人企图在此特殊化之下苟安。这是可能吗？绝对不可能，而且是创造汉奸，颓丧民气，出卖正义的过渡政治机构。故对日绝交，十分必要，战败不能使中国民族屈服，特殊化，可使中国民族万劫不复！

（４）"失败主义"情绪的发生--认为军事失败，一切都无办法，不是幸求一拼，便是退求自保；拼而求幸，胜已不可能，便更倾向于退过黄河以自保。果真在华北已无战的可能吗？如无可能，退过黄河也不能自保。故无命令自由退过黄河的是等于让日寇来便利统治华北。

我们为要消灭这一切现象与克服这一切危机而奋斗，而战斗到底。要如此，就必须坚持抗战到底，只有全民众起来抗战，抗战才能持久；只有坚持抗战，才能得到国际友邦的赞助，才能拒绝任何不利于我们的调停，才能最后战胜敌人！

二　坚持华北抗战的可能及其前途

抗战危机发生了，日寇更集中全力来加深我们的危机。但其中心的一环，仍在压迫我军迅速退过黄河，拿着华北，好做文章。上海原是其牵制方面，次作战线，谁知沪战中的损失出乎敌人意料之外，因而进迫苏州，现正向南京前进。但日寇的战略中心，第一步仍在取得华北，故华北的抗战，如真告一段落，抗战的危机，便严重到万分。而且日寇也可以喘一口气再干。

因此坚持抗战，必须以坚持华北战争为中心，华北抗战能持久，日寇将无法实现其全部阴谋。目前太原已失，华北抗战能继续么？能持久么？我们回答绝对的能。

第一、假使中央能有得力的生力军开来，能实行各线配合的出击，能增加生力军到敌人后侧，改变过去专守防御的战略战术，能动员广大民众参战，则华北战争，可转变目前的危机，进入胜利的反攻！

第二、如果上述这些条件一时做不到，甚至于敌人继续前进，占领了我们的渡河点--风陵渡，晋城，企图占领我们黄河要口，我们也还是有办法。在华北在山西进行持久抗战，这持久战有下列各条件：

（１）敌人的兵力，没有可能统治全华北，不仅是村子占不了，城市也占据不了。即使是铁路公路要道，也不能普遍占据。因之，敌人不能不用汉奸部队来统治许多城镇，用他的重兵火力，巩固他的交通要道，用他的主力，来和我们的部队作战。正好，我们便以游击部队消灭汉奸，武装民众，以一部轻装部队袭击，截断敌人大道交通，劫夺敌人辎重弹药，并以主力部队在山地寻求敌人一部而消灭之--这是完全有可能的。证以八路军在敌人后方恢复了十四个县城，烧毁了二十二架飞机，最近又夺回了南怀化，击败了敌人许多前进的部队，就可以相信。

（２）在地形上，持久战也是可能的。因为敌人兵力的准备，只能适用于铁路公路线上，最不适应于山地；且不熟识中国内地道路。而山西全境，冀察西部，热冀边地。都是山地，最便于我军的活动、存在与扩大。

（３）在气候上，外国人总不能较中国人适宜。尤其是冬春两季，更于日军不利。

（４）民众的条件是基本的。日寇侵略中国，不论他怎样欺骗利诱，只能收买少数汉奸，大多数人民的财产是遭蹂躏的。故民众的反抗，是持久战的最主要的条件，敌人愈摧残，群众将愈觉醒起来，为民族的最后生存而奋斗。

（５）民众武装已有了初步的发展。特别是晋冀察边的广大发展，将是我华北持久战的模范根据地。

（６）政府领袖和军队的决心成为争取华北持久抗战的主要条件。现在蒋阎及不少军队，正在加强着这个战争。我们还望他们有进一步的全局的布置。

（７）最后，八路军留在华北作战，也为推动和领导华北持久抗战的重要因素，因为八路军是红军改编的，他有着长期运动战及游击战的素养。他将要发挥他在这方面的特长，来影响友军，来组织和领导广大民众齐来抗战。

这一切有利的条件，将决定着华北持久抗战的极大可能。这个抗战的性质，在极困难的时候，将成为以游击战争的主体，来坚持华北抗战。这虽然会有一个时候，但他决不同于六年来的东北四省。他的持久战，将影响和推动着全国抗战的开展，掩护全国新的军队的组织，全国抗战的开展，也正支持着他，同时也使着日本无法结束他的战争，而要影响着全世界援助中国抗战的运动。因此这个游击战，将有胜利的前途。他要在持久战中，壮大了自己，武装了人民，恢复了许多城镇，破坏了敌人交通，消灭部分敌人，最后得到了全国生力军的参加，可以转到胜利的反攻，收复失地，驱逐日寇帝国主义出中国！

三　坚持华北抗战中我们的任务

怎样来坚持华北抗战呢？这是我们现在要说的问题，也就是实现华北持久战的任务如何？最主要的我提出四项问题：

第一、军队的改造。原有的正规军，虽越打越少，但打仗要用组织好了的军队来打，因此，改造旧军成立新军，便成为目前迫切的任务了。改造军队，目的不是在换一批人而是在改造他的组织制度。在这里，今后在华北作战的部队，其组织必须适合山地运动战和游击战，应采用三三制，而附有游击队，及轻便后方辎重与多数的通讯资材的编制。其次，政治工作制度必须建立，而且要成为军队的生命线来巩固部队。提倡自觉纪律，保障部队与人民密切关系。其三，部队的生活必须改善，政治生活要平等，连队经济要公开，士兵生活要提高，官兵要团结一致。其四，部队的指挥要给以独断专行的权力，要使其能独立作战，分区活动，不怕留在敌人背后，不怕被敌人切断。其五，作战的战略战术要改变，要认识现在是野战，是运动战，是游击战，争人不争地。其六，要建立各部队的后方，要有源源不绝的后方接济，在国难时也要独立自给。这样的军队是活的，是人民的，是革命的军队。这样的军队，这样的指挥，便能坚持华北抗战到最后的胜利！

第二、开放政权。现在全华北，已不是中华民国的统一政权，而是日寇汉奸的政权。日寇的自治是伪自治，我们应该以真自治来活动民众，开放政权。因此，目前华北的政权，应该是国民政府一部分的地方政权。首先他在制度上应该是民主政治，应该团结全华北的抗日人民，不论何党何派何军，均应容纳他们的代表，来共同担当国事，主持救亡大计。其二、在组织上应该从县区分上施行地方自治自给，以坚持中华民国的正统，然后及于省区。其三、在政策上，应实行抗日的纲领。我们提议应该根据共产党提出的十大纲领来实施战区的救亡政策。

第三、开放民运。华北要再不开放民运，军队就无法补充，作战将无人援助，民众武装扔无法建立。强悍者将受日寇的屠杀，懦弱者将变为日本顺民，狡黠者将变为汉奸，而奸商劣绅将首先悬挂日旗，担任维持。我们如不愿意这样，只有无丝毫迟疑的宣传民众，发动民众，组织民众，武装民众起来，共同来担当华北的持久游击战，首先应向民众作广大深入的抗日宣传。其二、要组织广大的民众在工会，商会，农会，学生会之中，并吸引他们到政治团体中来。其三、要发动民众为保护其自身利益而斗争，并联系到民族利益上来。其四、要组织他们在武装训练之中，引导其参加人民自卫队，游击队，义勇军，并吸引到部队中来。

第四、肃清汉奸，坚决反对投降主义、失败主义及特殊化的倾向，是争取持久战的先决条件。只有反对这些汉奸，才能团结全华北人民，全华北军队，影响全中国，乃至全世界，坚持华北持久战争，而取得最后胜利。

＊这是在临汾党政军民联欢大会上的一篇演讲纪录。原载《群众周刊》第一卷第二期。

注释

〔１〕九国公约，全称《九国关于中国事件应适用各原则及政策之条约》，是一九二二年二月六日美、英、法、日、意、比，荷、葡与中国北洋军阀政府在华盛顿会议上签订的。公约主要反映美、英帝国主义和日本帝国主义在中国问题上的矛盾，提出"中国门户开放"、列强在华利益"机会均等"。一九三七年十一月在布鲁塞尔召开了"九国公约"缔约国会议，日本拒绝参加。出席会议的除原缔约国家外，还有苏联、印度等共十九个国家。由于美英对日采取绥靖政策，拒绝讨论苏联提出的集体安全原则，会议没有取得积极结果，助长了日本的侵略气焰。

