# 怎样进行持久抗战？

中文马克思主义文库 -> 周恩来
怎样进行持久抗战？
（一九三八年一月七日）


一
 
　　只有持久抗战，才能争取最后胜利，这是抗战五个月中最主要的教训！

　　五个月前，抗战初起，我们即主张坚持长期抗战，决定最后胜负的方针，但当时未尝不有人设想：上海战役可以幸胜，日寇侵略可以限于局部，国际大战可以立即牵动。等到抗战经过五个月，察绥沦亡，保定太原上海相继失守，最后首都亦复陷落，证明抗战既不可幸胜，国际大战亦非轻易可以牵动，于是这些人便设想调解或可找到出路，屈服或可停止日寇前进，日寇汉奸又从而利用之，因此，和平妥协的主张，便一时甚嚣尘上。然而日寇的贪欲，却是无止境的。日本阁议对于中国的屈服主义者的幻想，算是给了当头一棒，而蒋先生的告国民书（十二月十 七日），更安定了浮动惶惑的人心，击破了一切和平妥协自甘退屈的主张，坚持着贯彻抗战到底求得最后胜利的变化，由于对于怎样进行这个基本方针，过去没有很好的阐明和执行，以致一部分人对于这一基本方针发生动摇，失去信心，并表示无办法，另有一部分人便因之发生埋怨和愤慨，于是抗日阵线内部，生长着离心和动摇的现象。现在为消灭这些现象，贯彻持久抗战的基本方针，就必须对于怎样进行持久抗战，提出更积极更具体的任务，号召和动员全中国的同胞，为实现这些任务而奋斗。

二

　　要回答怎样进行持久抗战的问题，首先须认清：抗战五个月中的主要的经验和教训是些甚么？

　　第一，这次对日抗战是中国海禁开后近百年来所没有的。以两个敌对的党--国民党和共产党，武装斗争了十年，一旦团结御侮，走在一条战线上杀敌；以一个尚未完全统一的政府，一个尚未完全统一的军队，一旦决心抗战，无间南北东西，都一致行动，一致奔赴前线，以许多装备不完的军队，许多尚无组织训练的新兵，继续向前线输送，前仆后继的牺牲；这种统一团结的意志，英勇战斗的精神，是我们抗战中的伟大成绩。如果从此长期坚持下去，并扩大和发扬起来，将基本的保障看中华民族战胜日本帝国主义的强盗。

　　第二，这次抗战几乎可以说以无甚准备的中国，抵抗准备四十多年的日本，毫无疑问的在战争初期，日寇是尽量发挥他们准备好了的长处，而我们则到处都发现我们没有准备或是没有准备好的短处，以致遭受军事上的失利。这从军事对比上看来，中国国防力量与技术条件，就大大落后于日本，经济对比，亦不相称，尤其是军事工业与运输，我国居绝对劣势，在政治上日本取得了中国汉奸托派和亲日分子的内应，而中国则还没有取得日本内部反战运动的响应。本来我们并不反对抗战需要准备，只是内战不停，抗战无从准备，即有准备，也要对消掉了。内战停后，日寇又不让我们准备。故我们对抗战的准备，只能在长期抗战中来完成，一边抗战，一边准备。以西班牙那样国家，被佛郎哥〔１〕一直打到马德里，还能在坚持战中，组成了新式军队五十万，构筑起新式防御工事，建立了现代化的军事工业，并且能做到制造飞机，自装坦克。我国地大物博人多，战争的条件还没险恶到马德里被困的状态，我们的长处是可以在持久战中发扬和增加起来的。特别是民众动员，愈因战争延长会愈加深入，军队作战，愈因持久，会经验愈丰，改正愈多，军事工业和军事交通，愈因持久，会成就愈大。在日寇方面，则因他的短处，在于财政困难，军事工业原料缺乏，国内矛盾增长，后方不巩固，远东形势陷于孤立等等，如果战争持久，战线延长，他的兵力，将不够分配，他的短处，将日益暴露，他的长处，将逐渐减少。

　　第三，这次抗战以中国军队装备技术的落后，竟能给敌以极大的损伤（敌我伤亡约一与三之比），使敌人不能依其预定计划实现，直到现在，日寇在中国的北方及东部，仅占有沿铁路和公路的城市，而广大的北方及沿海地区，仍在我手，这不能不归功于中国军队将士的英勇和某些军队（如八路军等）的机动，以及日本军队不善于山地战与不够分配等原因。但我们虽不赞成唯武器论的观点，然而军队技术的提高，装备的现代化，是迫切需要的。没有装备好的技术高的政治坚定的现代化的几十个师，是不能最后驱逐日本帝国主义出中国的。

　　第四，这次抗战，我国军队能在狭窄的上海地区，吸引敌军至十余师之众，坚持至三个月之久，引起全中国民众全世界同情我们人士的拥护和称赞，这是伟大的成绩。但以我军的装备和技术条件的落后，阵地战尚非我们特长，当时我军如能抽出相当数量和质量好的部队，转移到北方的战场上去，则在运动战中消灭敌人的把握，当较东战场为多，北方的战局，也许更能开展。现在沪宁失陷，我军今后作战，将更便于发挥我中国军队在山地战运动战中的特长，但这并不是说阵地战就不要了，没有某些支点和要塞的顽强防御，便不能吸引和暴露敌人的兵力，阻止敌人前进，使我主力部队得以进行突击；但这也不是说将以游击战争为主了，运动战是正规战的一种，并不是游击战，游击战是配合正规战的一种主要的辅助战术。只有在敌人占领和包围区域，主力部队不易立足和不易集中行动的条件下，才以游击战争为主，游击战争本身是不能驱逐日本帝国主义出中国的。要最后战胜日本帝国主义，不仅要发挥我军在运动战中的特长，并且要在提高技术条件和军队现代化的基础上，使我军重新转入阵地战的壕沟工事里去。

　　第五，这次抗战表示出我国军事指挥的开始统一和集中，我国最高统帅决心的坚强，与许多高级将领指挥的坚决，是值得称赞和尊敬的。但是现代的战争，是一个有组织的科学战争，特别在中国的军队复杂，地区辽阔，交通不便，补给不济的条件下，在敌我军事力量强弱的对比下，更需要有计划的组织战争。因此，在指挥上，一方面需要全国的统一和集中，另一方面需要分工，需要依据一定的战略计划，授权与各战区，使之能机断专行的独当一面。小而至于一师一旅一团一营，都要能依据当前情况，授以机断专行的权力。在补给上，依据敌人深入的情况，也要有分区自给的办法，尤其在敌人占领区域及其周围，更要有独立专行的作战区分。这一切都是过去抗战期中没有完满进行的，并且有时候，因为指挥系统的混乱、重复、无权和受限制，使某些战役遭受不应有的损失，这是应当立即改正的。

　　第六，这次抗战，我们应当称赞某些部队补充的迅速，新兵参加前线的勇敢，与某些民众团体及个人参加战地服务的勤劳，但我们同时应当指出：过去民众运动，还没有以动员参战为一切工作的中心。首先征募兵役的机关，便有保安司令，师管区，军训委员会等等的重复组织，征募的方法，多带强迫性而缺少宣传鼓动与解决优待抗日军人家属的具体办法。在民众运动中，不论指导机关，民众团体与个人，对于动员新兵上前线，动员青年学生受军训入军校，动员一切民众参加战地服务，推销公债，都还没有造成广大的动员热潮，这不能不说是抗战五个月中的一个损失。

　　第七，由于抗战的英勇与坚持，已经使国际同情中国的运动发展，使友邦的赞助增加，但应当指出：过去我们还没有尽量运用国际的有利条件，来增强自己抗战的力量，反而有时散布一些不应有的幻想和依赖，转至丧失了中华民族自力更生的信心。目前最能运用的有利条件，一方面是扩大国际宣传，取得全世界工人阶级及一切爱好和平人民的精神上物质上乃至技术上的援助，另一方面应加紧建立军事工业，加速军事交通，以便尽量利用友邦的援助，更强的武装起来。

　　第八，这次抗战是进行了肃清汉奸的工作，并取得部分成绩的，但严重的问题，却不在于肃清一般的小汉奸，而在于某些特殊化的思想，汉奸的理论，亲日派的活动，的制裁，这就使我们抗日民族统一战线内部容易受人利用挑拨，发生误会磨擦，特别是抗日的前线和后方，容易被日寇所利用，进行军事上的阴谋，张慕陶在山西的行动，和王公度等匪徒在广西的阴谋，便是明证。

三

　　根据上述的这些主要的经验和教训，很清楚的可以看出：决定持久抗战争取最后胜利的基本条件是获得了，现在的困难是要依据与发展现有的力量和基础，阻止敌人的深入，以渡过这一青黄不接的难关，以准备决定胜负的战斗。具体的办法，我们认为应当是：

　　第一，巩固前线--在蒋委员长坚决意志之下，要坚强北方津浦及东南各战线将士在那里持久抗战的决心，要认识敌人愈深入愈困难的真理，确定各战线的作战部队作战地区与作战基地，确定全国统一的作战计划，并严格遵守各作战地区在统一计划下的相互配合行动。残破的部队，应调在后方整补。留在战区的，应缩小庞杂的单位，使之适宜于发挥运动战山地战的特长，改变过去某些时候专守防御的战略战术，尽一切可能求得在广大地区以运动战消灭敌人，阻止敌人的前进。万一敌人突破某些支点，必须抛弃过去全线后撤的办法，在正面留下箝制部队，坚守纵深配备的支点，将突击兵力转移到敌人的侧面后方，寻求新的机动，以迟阻敌人的继续深入。只有这样，才能避免我们全线溃退，敌人跟踪而入的危险。只有这样，才能避免被敌人各个击破的危险。只有这样，才能争取时机，渡过目前的难关。太原失陷后，两个月来，敌人不敢南下临汾，主要的因为有八路军十三军及一部分晋绥军在他的侧面后方威胁吸引所致，这是最值得效法的例子。

　　第二，建设新的军备--在最短期内，在现有的军队基础上，要决心建立几十个有新式武装的和政治坚定的国防师。为达到这一目的，这些国防师的编制，必须适合于对日作战和新的技术条件。这些国防师的干部，必须以有抗战经验的军官作骨干，并迅速培养和训练大批的青年军政干部。这些国防师及其干部的教育，必须特别着重于实战经验的联系，技术条件的提高，与政治训练的加紧。这些国防帅的生活和待遇，必须从健全政治工作上，做到政治上官兵平等，军民一致，连队上经济公开，废除打骂制度，实行自觉的严格纪律。只有这样，才能造成坚强的革命军队。只有这样，才能最后的完成统一指挥，统一武装，统一纪律，统一待遇，统一补给，和统一的作战计划。只有这样，才能与敌人进行决定胜负的战斗。

　　第三，建立军事工业--为提高军事技术，最后战胜日寇，必须集中各种专门人材，建立统一的国防工业。依据目前可能的条件，我们应迅速的适当的分布军事工厂于一些安全而便于制造和运输的地区，应有计划的集中生产于某些急需的部门，应加强国防工业各部门对于这些生产必要的配合，应集中现金负责的购置必要的军火与制造兵工的器材，应利用国内外专门技术人才，迅速建立制造或装置新式的军事器械，特别重要的，应迅速打通和巩固西北与西南的军事交通，以便利和加速一切军事上的运输。

　　第四，发展敌人占领地区的广大游击战争--依据敌人现有的兵力，不论其在北方，在津浦，在东南，只能占领我国交通要道及重要城市，如敌继续前进，其后方将愈加薄弱。因此，我们应抓紧敌人这一弱点，派遣某些得力部队，到敌人占领地区的侧面后方，做游击战争的骨干，去动员组织和武装被敌摧残压迫或被欺骗的民众，首先以自立的原则，一直发展到脱离自己乡村城镇的武装队伍，去发展广大的游击战争，以袭击、扰乱、疲惫、分散和吸引敌人，并配合我主力作战。只有这样，才能使敌人不易在其占领地区，树立汉奸组织和汉奸部队，更难于统治起来。

　　第五，进行广大的征募兵役运动--动员新兵上前线，应成为今天动员工作的中心。在政府方面，应由上而下将一切征兵机关统一起来，组成各级征募兵役的委员会，号召指导和进行征兵运动。各种民众团体，应抓住这一中心工作，有组织的有计划的到乡村中去，直接召集群众大会，响应政府这一号召，动员壮丁自动的参加前线，讨论优待这些抗日军人家属的具体办法，使有钱的人，担负他们家属的救济，有力的人，帮助解决他们家属的劳动，并发动群众，举行盛大的庆贺与欢送，务使这一运动形成上前线杀敌的广大热潮，更经过这一运动，成立各乡村群众选举出的动员委员会及优待抗日军人家属委员会，使这一运动扩大到全国范围中去，使这一运动深入到各种动员工作--募捐、运输、慰劳、救护、自卫的工作中去。

　　第六，巩固后方--这首先须从政治上军事上进行保卫武汉的工作，要巩固江防，要加强平汉粤汉两路及其两侧的保卫力量，要动员大江南北的群众，参加这一保卫大武汉的计划。但这不是说，巩固后方的中心，只放在保卫武汉方面。为准备长期抗战，我们应同样在其他重要城市，构筑和加强全国必要的要塞和支点，巩固全国的交通运输，特别是宣传和组织各地民众，使之适合于军事抗战的需要，和参加一切有利于抗日的工作，肃清一切汉奸敌探托匪的组织和活动，以造成统一的强固的后方。

　　第七，加强国防机构--为使全国政治的军事的机构，能适合抗战胜利的需要，必须使过去不适合战时需要的重复的庞大的分散的一切政治机构，加以适当的改变，务使各级政府组织，能适合于领导全国战争，尤其是军事组织，更要有适当的科学的集权与分工，以便于指挥战争，组织战争。在人力上，要不受人事的牵掣，能集中全国确能代表民意和有能力的各方人才，参加各种工作，以充实统一政府，加强国防机构，这是目前最有利于巩固政府团结御侮的工作。

　　第八，运用国际的有利条件--因为抗战要建立在自力更生的基础上，我们固反对幻想出兵式的外援，但我们并不反对运用国际环境中存在着和发展着的有利条件。过去因幻想出兵式的外援，痴等外国出兵，致许多国际的有利条件，反被忽视了，反而没被运用。现在我们应估计到国际上的同情增长，要以全国统一的对外宣传，有计划有系统有组织的材料，向全世界供给，要以各党派各团体联名的通电、联合的组织，派遣到海外去，并配合华侨的活动，取得各国人民物质上技术上的援助。特别重要的是要利用各国可能的赞助，加紧推动，加速进行，务使这种可能扩大起来，畅利起来，而不要像现在已经获得的某些可能，停顿和迟缓起来，这是于长期抗战的支持和发展极为不利的。

　　以上这一切具体办法，都为着实现一个目的--即是争取持久抗战的最后胜利的一个目的！重复的说，要能贯彻抗战到底的方针，必须首先加强和巩固中华民族能够支持长期抗战的信心和决心，反对一切动摇，反对一切妥协屈服投降的思想。次之，必须坚决相信进行这些持久抗战的具体办法，是能够渡过目前难关，准备进行决定的战斗的。有了坚强的信心，有了实行这一切具体办法的意志，有了实行这一切具体办法的长期努力，日本帝国主义强盗的进攻，必然会遭受到最后的惨败，中华民族的独立解放事业，必然会达到最后的成功！



　　＊本文原载《群众周刊》第一卷第五期。

　　注释：

　　〔１〕佛郎哥（一八九二～一九七五），西班牙独裁者，长枪党首领，军人出身。一九二○年因镇压摩洛哥人起义有功，升上将。一九三五年任陆军参谋长。一九三六年二月，西班牙大选中，人民阵线获胜，成立共和政府。同年七月，佛郎哥在德、意法西斯的支持下发动了反共和政府的叛乱。西班牙人民在人民阵线政府领导之下，进行了保卫民主反对侵略的英勇抗战。这个战争，以京城马德里的保卫战最为激烈。保卫马德里的战争，从一九三六年十月起，前后坚持两年又五个月的时间。由于英法等帝国主义国家用虚伪的所谓"不干涉"政策帮助侵略者，又由于人民阵线内部发生了分化，一九三九年三月二十八日马德里陷落，共和国政府倾覆，开始了佛郎哥的独裁统治。



