# 争取更大的新的胜利

中文马克思主义文库 -> 周恩来
争取更大的新的胜利
（一九三八年四月十七日）

一　这次胜利的意义
 

我首先来说明这次鲁南胜利〔１〕的意义。鲁南胜利是我们二期抗战〔２〕的初步胜利。这个胜利虽然是初步的，但它的意义却很伟大。

第一，我们摧毁了日本强盗最精锐的两个师团--坂垣与矶谷。

第二，我们缴获了日本强盗许多新式武器，如大炮，坦克车，步枪，轻重机关枪及其他的战利品。

第三，证明了我们二期抗战中战略战术的进步和成功。

第四，证明了我们部队战斗力的提高，和战斗情绪的旺盛。

第五，证明了我们各战区各战线以及各战场上的配合动作收了成效。

第六，证明了战区中军民合作的成绩与游击战争的发展。

第七，愈加暴露了敌人兵力不够，军纪败坏与战斗力不强等等弱点。

所以这次胜利虽然在一个地方，但，他的意义却影响战斗全局，影响全国，影响敌人，影响世界。

二　日寇正准备新的进攻

敌人的情况将要发生怎样的变化呢？这是我们跟着要回答的。日本强盗虽然无耻的否认这次台儿庄的惨败〔３〕，但上海、天津两方面的增兵，却不能掩盖它的实际恐慌，同时也证明敌人的冒险进攻，还要继续。

本来敌人自从开始第二期进攻计划以来，满以为依靠原有的在华兵力，便能实现它的第二期进攻计划。它这种轻视我国的狂妄举动，完全没有认识愈深入中国愈加困难的真理。因之，第一步打通津浦夺取徐州的计划，在二月中便遭受了初次失败。继着，第二步突入晋南，扫荡黄河以北的计划，又在二月中开始的碰了壁。接着，第三步又回转方向，仍从津浦南进，并且增加了两师兵，企图重新实现它打通津浦的计划，不料这次失败更大，竟使它弃甲曳兵而逃。现在敌人决不会认输，它只有从国内增加兵来。敌人开在中国内地的军队番号，大约已达到廿九个师团，在国内约尚有八个师团，在我国东北四省约尚有八个师团，台湾尚有二个师团，高丽也有两个师团。据估计敌人向上海天津方面增加的兵力最大限度可达到八个师团。如果这个做得到，则敌人留在国内及在东北四省台湾朝鲜现有的兵力，只剩十二个师团了。并且自开战到现在，敌人在华损失的兵力，已经超过廿万，已经不止八个师团，所以即使八个师团全能开来，也不能弥补过去的损失。何况愈进攻，兵力愈分，愈深入，兵力愈少，愈持久，兵力愈消耗疲惫。再加上敌人的纪律败坏，也是有加无已，甚至敌人自己的报纸--中央公论，都不免泄露这种残暴无耻的消息。这种量与质综合起来的弱点，随着战事发展下去，将使敌人的战斗力逐渐减弱。

不过敌人目前的冒险进攻，是必然要继续的，并且会依靠增加的兵力，根据失败的教训，采取更有力的进攻步骤。

敌人将从那个方向进行新的进攻呢？

大约估计，可能从下述的三个方向：

第一，使用更集团的兵力，仍从津浦南下，但主力可能使用在敌人的右翼；

第二，更可能的从津浦南段北上，但主力使用在迂回合肥方面；

第三，沿平汉线两侧，突过黄河，切断陇海，使津浦线我国大军放在敌人的外翼。

在新的进攻中，敌人根据失败的教训，可能有下述的改变：

第一，敌人将会更集团的使用它的兵力，改正一些过去轻视我军的观念；

第二，敌人从有进无退的锥形直入的战术，可能改正为更灵活的使用包围迂回，使用有进退的运动战；

第三，敌人有可能改变过去专攻一方面的作战方针，与逐渐增加的弱点而向各方试攻，控制强大的突击兵力于待机位置，等到发现我军弱点在哪一方面时，再直向哪方突破。

第四，敌人在各战线上的配合动作，也必会较前加强。

估计到敌人将要发生的这些情况，我们全国军民才能懂得注意敌人新的进攻，才能争取更大的新的胜利。

三　争取更大的新的胜利

更大的新的胜利怎样争取呢？

我认为首先要更加巩固全国的团结。抗战九个月来，我们中国有了空前的统一的政府，统一的军队，统一的最高统帅和民族的觉醒，结成了不分党派，不分信仰，不分地域，不分种族的全民族的大团结，这是抗战必胜，建国必成的基本条件。尤其二期抗战后，全国各政治党派中心力量集于武汉，最近国民党临时代表大会，又发布了战时的抗敌建国纲领〔４〕及其宣言决议等等，更能推动全国的团结，趋于巩固。我们热望这种团结，一直巩固下去，一直发展到全国，一直团结到抗战胜利以后。

次之，我们更加努力争取前线上的胜利。二期抗战虽还不是决定最后胜负的战斗，但我们的胜利，如果能一次一次的增加，一线一线的开展，我们定能阻止敌人的深入，保卫我们抗战的中心--武汉，以便争取时间，准备新的力量，进行决定最后胜负的战斗。因此，我们热望前线上的将领更能坚持以运动战为主的战略方针，发挥野战军灵活的运动战与歼灭敌人的特长；派遣有力部队挺进和坚留在敌人后方去进行战斗，坚守必要的支线工事，广大的发展群众的自卫武装和游击战争，取得各战线上更好的配合，以争取更大的新的各战线上的胜利，以粉碎敌人整个二期的进攻计划。

再次，我们要努力争取时间，建立新军，以准备决定的战斗。建军，不仅是抗战必胜的保障，而且是建国必成的保障。我们热望全国军民都努力来参加建军的伟大工程。要做好这伟大工程，就须有好的自愿的自觉的人民来当兵，就须有政治坚强的有战斗经验的干部，就须有统一的适合抗战需要的编制，就须有自觉的严格的军队纪律，就须有近代化的技术条件高的武装配备，就须有新的军事政治的训练，尤其须有能使官兵一体军民一致的政治工作。有了这样的国防军，才能保障新的胜利的到来，保障最后胜利必属于我们。

最后，我们要努力于抗战期中的建国。抗战期中的建国纲领，国民党的临时代表大会已经规定明白，无疑的将要成为国民政府抗战期中的施政方针。我们热望全国军民要努力实行这个纲领，最重要的，是训练全国军队，一致为国效命，动员全国力量参加抗战，实现国民参政的职权，充分保障纲领中规定的人民权利给广大民众以武装的组织和训练，推行战时教育，集中主要生产力于建立军事工业，树立重工业基础和发展农村经济，同时注意改善人民生活，并坚持联合世界上同情于我之国家及民族的外交方针。这一切努力，都是为的在抗战中树立起建国的基础，保证抗战的最后胜利！

全国同胞们！前线上的官长士兵们！我们从这四个基本工作上，就是说要从巩固全民族的团结，争取前线上的胜利与建国的工作上，来争取更大的新的胜利，以粉碎敌人第二期的进攻计划。保卫我们抗战的中心--武汉，准备最后决定的战斗，以打倒日本帝国主义的强盗，复兴我们中华民族！

＊这是在武汉各界第二期抗战扩大宣传周第五日的广播词。原载一九三八年四月十七日《新华日报》。

注释：

〔１〕鲁南胜利指日军占领济南及山东广大地区后，中共山东省党组织、领导人民举行了一系列武装起义。起义成功后，即分别组成抗日武装，开展游击战争，逐步开辟了以鲁南为中心的大片抗日游击根据地。

〔２〕毛泽东在一九三八年五月发表的《论持久战》中指出，中国的抗日战争须经过持久战的三个阶段，即"第一个阶段，是敌之战略进攻、我之战略防御的时期。第二个阶段，是敌之战略保守、我之准备反攻的时期。第三个阶段，是我之战略反攻、敌之战略退却的时期。"见《毛泽东选集》第二版第二卷第４６２页。

〔３〕台儿庄在山东省枣庄市东南、大运河北岸。是大运河沿岸物资集散地之一。一九三八年三月下旬，日军第十师团向台儿庄进攻，一度被中国守军击退。四月三日，中国军队以四十万优势兵力包围进攻台儿庄之敌，并击退由临沂增援之敌第五师团一部，至四月六日取得了歼敌两万余人的胜利。

〔４〕一九三八年三月国民党在汉口召开的临时全国代表大会上通过了抗战建国纲领，内容包括抗战的军事、政治、经济、外交等方面的政策。这是一个两面性的纲领。一方面被迫对人民作了某些形式上的让步，如规定组织国民参政机关，许诺给予人民言论、出版、集会、结社自由；同时又继续坚持国民党一党专政。由于蒋介石推行消极抗战、积极反共的政策，纲领中对人民的某些形式上的让步也成为一纸空文。

