# 论保卫武汉及其发展前途

中文马克思主义文库 -> 周恩来
论保卫武汉及其发展前途
（一九三八年七月六日）

中国抗战已一周年。目前正当着日寇沿着大江南北，向武汉方向进行水陆空联合进攻的时候，我想全中国乃至全世界人士都正关心着两个问题：第一，保卫武汉的可能如何？第二，抗战的发展前途如何？

我现在联系起来回答这两个问题。

首先，我要回答敌情如何？一年来敌人速战速决的方针，经过一战再战，虽已占领了我们沿海城市和交通要道，但其聚歼我军，逼我屈服的企图，终未达到。最近敌阁改组，其中心方针，仍在速战速决，但又惧战事不易速了，消耗不易持久，故对内乃以准备长期战争动员，对外故造调停和解谣言，企图动摇我国内外抗日阵线，从政治上压我屈服。因此，敌人的三斯作战，乃是在矛盾的发展中继续作冒险的进攻。其战略方针，必然是集主力以包围武汉，切断粤汉平汉陇海，逼我退出一切铁路交通，以便最后的威胁广州兰州。其作战计划，可能估计的为由东向南，由北向西的迂回武汉，切断粤汉平汉，企图聚歼我军主力于湖沼地区，陷断我军一部于东北山地，并压退我军一部于武汉以西及其以南的地区，以造成武汉大混乱的局面。目前黄河汉水泛滥，江淮间山地起伏，敌人大兵又出现于马当湖口之间，其主攻方向，显已着重江南，但我们亦不应忽视敌人在其他方面的乘虚而入。同时，敌人对扫荡黄河南北两岸，夺取潼关西安以及沿南浔浙赣两路，夺取南昌长沙的计划，亦有可能相机而行。

敌人的企图既如上述，但敌人的困难并未减轻，相反的还在发展，最重要的为：（一）敌人兵力愈因深入而愈分散愈单薄，新的部队未见大增，原有部队且因我挺进军深入热冀边境而有调出关外的；（二）敌人的配合动作较前更差，同一进攻武汉，江南紧急，豫东皖西沉寂，同一增援同蒲，道清敌进，晋北晋东受阻，这都证明敌人兵力不够，指挥不灵；（三）敌人战斗力在野战场中脱离其飞机大炮坦克的掩护，不论进攻退却与被我攻击，都较在阵地战中为弱，都易为我军所败；（四）敌人军纪败坏，影响其士气至大，思家自杀反战逃亡等等现象已渐发生；（五）敌人一年来追加之军事预算七十三万万，已渐用光，新年度的军事预算，将更加重日本人民的相负。板垣之准备作战十年的大言，将不知吓退几多日本人民；（六）敌人的交通运输，将愈因深入而愈感困难，保护接济，将因我游击战争沿江沿铁路的破坏扰乱而愈感苦恼；（七）敌人后方愈大，将愈感空虚，我挺进游击部队将利用之以恢复失地，恢复政权，敌人如调兵回击，则又利于我阻敌深入；（八）敌人的政治矛盾，不论是陆军与海军，关东军与派遣军，华北敌军与华中敌军，军阀与财阀，军火商与轻工业家，政党与政党间，统治者与广大人民，帝国政府与属地人民，无不反映其冲突的增长。综合这各种困难的发展，将给敌人作战企图的实现可能性以极大的阻碍。因此，结论是：敌人的三期作战，不仅在矛盾的发展中，而且在困难的增长中，继续作冒险的进攻。

次之，我要回答我们抗战力量如何？一年来我们坚持了长期抗战的方针，击破了敌人速战速决的计划，拒绝了敌人和解诱降的活动，这是我们基本的成功。成功的原因在于抗战以来，我们有了下述的基本的进步：（一）我们全民族有了空前的觉醒，空前的团结；（二）我们有了统一的国民政府；（三）我们有了统一的国民革命军及英勇牺牲的前线将士；（四）我们有了国民党共产党以及其他党派的精诚团结，共赴国难；（五）我们更有了全国最高统帅，领导全国军民，抗战建国。这些成功和进步，我们要拥护他，坚持他，才能使成功和进步继续发展。

但既有了基本的成功和进步，为什么还不能阻敌深入？这主要原因由于我抗战力量还不够坚强，还不够广大，还不够持久。还不能改变敌我的强弱对比，还不能使敌我强弱的差异大大减低。第一，从军事上看来，抗战初期我们的弱点很多，二期抗战，战略上，作战上，均有极大的进步，给敌人有相当大的损伤，但部队的编制，作战的区分和指挥，兵员的补充，军火给养的接济，干部的训练，伤兵的治疗，政治工作的建立，游击战争的发动，民众武装的领导，尚有许多可商榷和应改善的地方。第二，从政治方面说，抗战建国纲领的产生，国民参政会的召集，各党派的公开与合作，救济工作的重视，这都是一年来最大的成就，但行政机构之欠调整，地方自治急需实行，保甲制度急需改革，抗战自由急需保障，民众团体急需领导，青年教育急需改善，财政金融急需整顿，经济生产急需发展，交通运输急需统一，均为目前应兴应革之事。有了军事上政治上这些弱点，自然抗战力量便不足以阻敌深入。所以一年来我们在上海华北，虽相当大的消耗敌人，台儿庄虽获得重大胜利，在华北虽破坏了敌人的扫荡计划，在全国虽调动了敌人百万以上，消耗敌人达三分之一，但所有这些，还只是局部的胜利，还不能粉碎敌人的每期进攻，还未能产生出足以决定最后胜负的力量。我们指出这些弱点，决不能说我们是在灭自己志气，长他人威风，更不能说是在攻击政府。因为拥护政府是抗战以来，全民族基本的立场，大家决无二致，而这些弱点，正因为我们是弱国，在抗战初期，不能尽免，只有尽情指出，不断改善，才能化弱为强，转败为胜。因此，结论是：中国抗战，已有了基本的成功和进步，但抗战力量，因有种种弱点，还不够坚强，广大和持久，这需要我们在坚持长期抗战中，改正这些弱点，克服这些困难，争取胜利的前进。

再次，我要回答保卫武汉的条件到底如何？

第一，有人问：保卫武汉的有利条件，已经有了些什么？我的回答是：最高统帅坚守武汉的公开声明，卫戍武汉及其以外地区的主力部队，全国战场的战斗配合，武汉三镇及其附近地区的广大民众，全中国民众的后援，全世界人士的关心，最后还加上武汉以外的有利地形，敌人的困难和弱点，都给了我们保卫武汉以坚强的信心，动员的力量，与争取胜利的兴奋和鼓励。

第二，有人问：条件虽然有利但还不足，且目前战况已日见紧张，弱点还仍然存在，新的努力，新的胜利，是否还来得及保卫武汉？我的回答是：诚然条件有利而不足，时机已极紧迫，但只要不再延误一刻，依据我们基本的成功和进步，努力改正弱点，争取胜利，保卫武汉的条件，一定可以在战斗的发展中更加生长起来的。试看，首都陷落以后，谁能保证津浦会战，支持五六月之久，这正因为战略的改进，战斗的努力，使得敌人遭受意外的损伤和阻碍，同时又因为许多弱点还未改正，所以敌人终于切断陇海打通津浦。现在我们要为保卫武汉而动员一切力量，改正一切足以妨碍保卫武汉战斗的弱点，战斗就一定能够持久，由持久的胜利中，又可产生出长期保卫武汉的新的条件。这是由战斗的发展中求得解决，而不是以机械的定命论来预测的。

因此，结论是：保卫武汉的有利条件是有的，但还不足，且时机紧迫、急切需要政府与人民，一致的改正弱点，争取胜利，才能够生长出保卫武汉的胜利的条件。

复次，我要回答保卫武汉的具体方案如何？我在这里只打算说最主要而最紧急的问题。

第一，在战略上，我以为必须确定两个战线，亦即内外线夹击敌人的方针。在武汉卫戍地区，是处于内线作战地位的，而沿黄河、平汉线以东及长江下游，已全处于敌人外翼侧，成为外线作战的形势。敌人愈进攻愈深入，我们在敌人外线的活动地区将愈大；敌人如退守后方向我游击地区围攻，则我内线作战部队的活动范围及出击机会将愈多。因此，内外线作战部队的机断专行与协同动作，关系非常重大。凡在敌人进攻正面，及已在和将在敌人翼侧后方的战区，应重新划分，前者应有其固定的和预定的后方，后者应规定为若干游击战区，坚持留在敌后作战，其后方，只能依靠不经常与不固定的运输线与补给基地，在前一种战区中作战，尤其是保卫武汉战役中，运动战、阵地战应成为密切配合，游击战要准备发动。因此，这里要有足够数量的坚强的野战军，装备完整的守备队，责任要分明，指挥要统一，然后才能在敌人每一个方面，每一次的进攻中，给敌人以严重的打击或消灭之，最好是能击败和阻止敌人于进攻武汉的山地之外。次之，也要能侧击和消灭敌人于进攻武汉的山地之中，最后，还要能截击和歼灭敌人于湖沼地带，这样才能达到直接保卫武汉的任务。在后一种游击战区，运动战与游击战，应广泛的配合使用。因此，这里要有确定任务，坚留敌后政治强的得力的挺进部队，应赋给该战区高级将领，以广泛的组织游击队与发动游击战争之权，一切党政军及民众领导均应统一，然后才能在敌人进攻正面的近后方，以运动战配合被进攻的部队，夹击敌人，在敌人的远后方，以广大的游击战，切实截断铁路及沿江交通，困惫敌人，调动敌人，以便将敌人后方变为前线，在那里恢复失地，恢复政权，创造出新的游击根据地，以便与敌人持久作战，准备将来战略的反攻。这是间接的保卫武汉的胜利条件，同时也正是直接的破坏了敌人扫荡黄河南北，深入江西湖南的计划。

第二，在建军上，我们要不失任何时机的培养新的力量，以便能继续战斗，并培养出将来足以担当决定胜负的战斗的力量。这就必须：（一）在兵役法上，要能改善征兵制为征募两用的兵役制，使及龄壮丁，能自觉的入伍，以提高部队的质量。（二）部队编制，要能根据抗战经验及上述战略方针加以修正。（三）部队及干部教育，要能依据抗战经验，补订教令教程，加强政治及技术教育，对新兵训练，尤须注意于野外战斗教练，务使其能完成一定时间的教育计划，不因战况紧张，轻易调动，因其于战事既无补而有害，于建军本身将更困难完成。（四）部队装备补给，要能依照任务而规定其统一办法，如野战军应多配备山炮，迫击炮，轻机关枪；挺进游击部队，应多配备轻兵器，工兵器材及打战车炮；守备部队应配备足够数量的重兵器；机械化部队，应集中使用等等。（五）政治工作，要能从基本上加强，政治部要普遍设立，连队政治工作要开始，干部要重新训练审查，薪俸要减低，巡视检查制度要建立，政治工作更要求做到保障命令执行，提高官长威信，巩固战斗情绪，加强士兵教育，注意伤兵工作，提倡自觉纪律，改善军民关系，进行对敌工作，以代替过去政训工作的不良传统。

第三，在动员上，我们要求，要用最大的决心发动民众，组织民众，训练民众，武装民众。国民党临时代表大会宣言所说："抗战之胜负，不仅取决于兵力，尤取决于民力"，这在今日保卫武汉的动员中，尤为至理。有人说："战况吃紧，兵力尚且不行，民力有何用处？"不知战况愈紧，兵民相关的作用，相需的情形，更重要于平时。兵员扩充、工役、运输、担架、向导、慰劳、办粮、侦察等等，是兵需于民。组训、武装、保卫、疏散、救济、领导，是民需于兵。因此，凡属战区，动员工作，比任何其他行政工作为急要，同时动员工作能做得好，一切政治问题中的困难和弱点，已解决大半。动员工作的方针，应该是统一领导，统一计划，联合组织，分工合作，各级动员委员会的组织，不应只是建议的机关，而应是执行的机关。他们的成分，一方面应包括党政军各机关的代表，另方面应有民众团体的代表参加，后者代表总数超过前者。动员组织的领导，在战区的属之于政治部，在省则属之于省政府，在县区两级，应由战区和省动员委员会派人主持，或由县区长兼为动员委员会主席。动员委员会，应实行民主集中制，并吸引广大民众团体及人民参加工作，以扩大动员基础。动员工作的内容，应分兵役动员、参战动员、物资动员、自卫动员、人物疏散及组训工作等。只有用一切力量，动员全武汉及其附近的民众，参加保卫武汉的战斗，不必要的人员和物资，迅速的向外疏散，才能使人力物力为兵力所用，不致为兵力之累，甚至转为敌用。

因此，结论是：保卫武汉具体的方案，最中心的是：动员一切兵力、人力、物力，争取保卫武汉的直接胜利，争取变敌人后方为前线的外线胜利，同时争取一切时机建立新军，以便继续战斗和准备最后决定胜负的战斗。

最后，我要回答抗战发展的前途究竟如何？

第一，有人问：武汉的重要，政治上不如南京，经济上不如上海，军事上不如徐州，文化上不如北平，即使不守，也不会影响大局。我的回答是：（一）诚然，分开来看，武汉或者不如南京和上海北平的重要，但在南京上海徐州北平失陷以后，在政治上经济上军事上乃至文化上，都集中于一地--武汉，其重要性就胜过过去任何一个城市的陷落。（二）如果武汉不经许多严重战斗，不给敌人以极大损伤，便就发生问题，即使敌人聚歼我军企图不能完全达到，但将武汉造成大混乱的局面的企图，这不能说无实现可能。因此，坚守武汉的决心和布置，是消灭敌人战略主要企图的实际步骤。

第二，有人问：保卫武汉的具体方案即使如前项所述，均在实施，而仍不能阻敌深入，则前途又将如何？我的回答是：只要全国军民在坚守武汉的方针下，对于上项方案作最善之努力，则我消耗敌人必多，在敌后的发展必大，敌人的困难必增，我们的抗战力量必日益坚强扩大，民众的动员必日益深入，即使敌我力量的对比，尚未达到质的变化，不得不在万一不利的情况下，转移作战地区，但敌人所能取偿于武汉的，将是焦土荒墟，那我们增长的力量，不仅能继续抗战，而且能在更大范围更大规模的运动战与游击战的配合中，日益接近于力量对比之质的变化，最后能转弱为强，反败为胜，进行决战。这中间，需要经过多长过程，主要的要看我们持久抗战的努力，更千百倍的加强我们国内的团结，政治上军事上的进步，乃至国际条件的变化。一切妥协投降，悲观失望的动摇，在现在，在将来，在整个长期抗战中，都应该遭到我们的反对。

因此，结论是：只有坚守武汉，才能保卫武汉。只有以保卫武汉的口号和决心，来动员一切，来坚强和扩大抗战力量，才能争取不断胜利，才能使抗战持久，抗战前途争取到最后的胜利。

＊本文原载《群众周刊》第二卷第五期。

