# 今年的八一

中文马克思主义文库 -> 周恩来
今年的八一
（一九三八年八月一日）

今年的八一，正当着东西侵略主义者在全世界人类面前演着空前的残暴的屠杀。这三个法西斯国家，在中国，在西班牙，不仅以残酷的战争，来摧残中西两国的文化经济，而且以大量飞机轰炸中西两国的平民和不设防的城市，要在广大范围内屠杀更多的反法西斯的种子，并且对于所谓中立的友邦船只，也毫不客气的施行轰炸。法西斯的日德意为贯彻其侵略野心，不惜向全世界挑衅。
 

因此，今年的八一，全世界爱好和平的人类，一切维持和平的国家，决不能再像往年一样，仅仅开会示威，而需要采取更有效的方法，来制裁侵略者。我们中国人民，我们西班牙弟兄，站在反侵略战争的前线，正以浴血的自卫战争，来扑灭法西斯侵略的魔鬼。我们中国抗战已经一年，我们以坚持长期抗战的方针，反对一切妥协动摇，击破日寇一战而胜中国的国策。在一年战斗中，我们以空前的团结，以持久战消耗战的战略方针，揭穿日寇一切挑拨离间的诡计，击破日寇速战速决的企图，敌人愈深入愈困难，我军愈打愈强，信心愈坚，愈能深入游击到敌人后方，创立出许多新的抗日根据地。但我们弱点缺点还多，因此我们还没能阻止敌人前进，更还没能与敌人决最后胜负。我们共产党人，现正与当权的国民党谋进一步的团结，坚持动员民众，坚持统一战线的发展，坚持保卫武汉的战斗，坚持深入到敌人占领区域，变敌人后方为前线，坚持建立现代化的军备，以便继续战斗，准备决战的力量，坚持建立民主共和的新中国。坚持长期抗战，不达收复一切失地不止，这是我们纪念八一，反对侵略战争，实现世界和平之最有效的办法。我们已经以一年抗战的收获，吸引敌人百万，损伤敌人三十万，消耗敌人弹药到去年储存，击落敌机六百架以上，击坏敌舰三十五艘，损坏敌人战车汽车过万，来作给国际反侵略日的献礼。我们愿以更大的收获，击退敌人的侵略，来做来年八一的预约。

苏联是世界和平的支柱，他的存在，他的发展，已给了和更要给世界法西斯阵线以更大的威胁。我们更希望全世界爱好和平的人类，维持和平的国家，反战支柱的世界无产阶级及被压迫民族，在今年八一，要巩固世界的和平阵线，强化国联机构，实施世界集体安全制度，给侵略者以实际制裁，抵货，不卖军火给日德意，反对法西斯屠杀平民、轰炸不设防城市，援助中西两国反法西斯的自卫战争，给我们以更多的同情和援助：军火，借款，药品，及一切资材，一切技术人员，一切志愿战士。

全世界爱好和平的国家和人类，团结起来，联合起来，东西法西斯的侵略魔鬼，一定能在中国、西班牙的战场上失败。看呵！中西两国的政府和人民，永远站在反侵略战争的前线，誓死抗战到底！

＊这是在国际反侵略战争纪念日为各国共产党报纸撰写的纪念短文。原载一九三八年八月一日武汉《新华日报》。

