# 论目前抗战形势

中文马克思主义文库 -> 周恩来
论目前抗战形势
（一九三八年十月）


一
 
　　中国抗战，经过了十五个月的英勇战斗，完全证实了一个真理，即是：只有坚持长期抗战，才能争取中华民族解放战争的最后胜利。一切对中国抗战之速亡论或速胜论，均已从事实上宣告破产。因为速亡论者只看到中日军事的强弱悬殊，没有看到其他许多政治、经济、自然因素及国际等条件不利于日本，所以他们不能预见也不能相信中国抗战能支持十五个月之久，而武汉还能保持在我们手中，华北广大的地区仍飘扬着中华民国的国旗，创造出许多游击运动的根据地，津浦沿线及长江下游同样能发展游击战争。速胜论者则存在着另外一种心理，或者错误的过低的估计敌人的力量，过高的夸大自己的力量，而忽视自己的弱点，以为一战再战就可以使日本精疲力尽，承认失败，或者希望外援，想倚靠国际的变化，来替中国打胜日本，这是一种侥幸心理。十五个月的抗战史迹，已证明中华民族主要的靠着自力更生的国策和信心，支持了这一血战，一切速亡论的悲观心理与速胜论的侥幸心理，已被粉碎无遗。

　　但是，现在抗战正处在紧要关头，武汉又告危急，新的悲观动摇的心理，新的幸胜幸得的企图，或者会在另一种形式上出现。因此，我们认为对目前抗战形势，有更加阐明的必要。

　　首先我们应该认明的，中国抗战是长期的不是短期的，持久战的方针是确定的。日本强盗既不可能一下子把我们赶到中国的"堪察加"〔１〕，迫上昆仑山〔２〕，我们也不能很快的转弱为强，反守为攻，将日本强盗赶出中国。因此，中日战争的形势，正如毛泽东同志所说：须经过持久战的三个阶段，才能争取最后胜利。他描写这三个阶段的特点，即是："第一个阶段，是敌之战略进攻、我之战略防御的时期。第二个阶段，是敌之战略保守、我之准备反攻的时期。第三个阶段，是我之战略反攻、敌之战略退却的时期。"换一句话说，中日战争既不是一个阶段被敌人一直进攻到我们亡了国，也不是两个阶段敌人进攻中止后被我们一个反攻打出了中国，而是三个阶段，先是敌进我退，继着彼此相持，最后我进敌退，争取我们的最后胜利。

　　这三个阶段如何演进，如何转变呢？我们回答：抗战愈持久，才能愈向有利于我们方面演进，抗战愈胜利，才能愈有利的转入新的阶段。第一阶段敌进我退，我们虽遭受颇大的损失，但因为我们的英勇抗战，同时也给了敌人颇大的损失。我们更得了颇大的进步，这种敌人的损失和我们的进步，达到一定的程度，我们就可胜利的转入第二个阶段，造成相持的局面。但相持决非已经造成军事上的势均力敌，而是军事、政治、经济、地理、交通及日本国内、国际诸条件的相配合和相互因果，使得敌人再难继续大举进攻和深入，不得不转向敌后回攻我游击部队及其根据地，这便是相持局面之具体表现。这就是说要使我们防御的正面，能够基本上阻止敌人前进，我们在敌后的游击战争和根据地的创造，能够抓住敌人，使其基本上不得不以主力回攻和保持已得之战略据点大城市及军事要道，我们新的力量能够继续生长，支持长期抗战。而敌人的兵力，因其长期作战重大的损丧及其他不利于敌人诸条件的增长，使敌人不得不退到战略保守，回攻敌后的形势。这种形势继续发展下去，只要我们能坚持敌后广泛的游击战争，坚守防御的正面，特别要培养出相当数量的近代化的国防师，大量的消耗敌人，改变敌我的强弱异势，我们一定能胜利的转入反攻、完成第三阶段的任务。

　　依据上述形势的预测，目前三期抗战，显然是处在第一阶段尚未完结的时期，但应当指出：我们要争取三期抗战成为过渡阶段，即是说要使保卫武汉的战斗，能胜利的持久下去，使敌人的进攻难以继续深入，而过渡到第二阶段的相持局面。然而敌人是不容许这一阶段迅速来到的，他的政策是一方面，无论如何要拿下武汉，并图继续进攻，加强其军事分割；另一方面，在拿下武汉前后，更加紧其政治分化的阴谋，以击破我们拿着武汉或在武汉失守以后造成相持的局面。

　　因此，保卫武汉的战斗，从整个抗战的形势看来，它只是第一阶段能否即过渡到第二阶段的关键，而决不是能否继续长期抗战的关键。因为我们要使武汉保卫得住，能即过渡到第二阶段，就必须使直接保卫武汉的战斗，能持久的阻止敌人前进，在敌人后方的游击战争，能广泛的发展到大江南北，直接的抓住敌人，新的力量能够继续生长，准备反攻，这才能胜利的有效的过渡到第二阶段。如果这些条件不能具备，我们不能保卫武汉到最后，那我们就不能在保卫武汉的战斗当中过渡到相持的局面。然而，决不是说，没有了武汉，失去了三期抗战的中心，我们就没有可能继续作战，争取胜利的转入相持的局面。因为上述的转入相持局面的各种条件，并不会因武汉的失去而完全改变了性质，这在军事上最主要的是：第一，我们正面防御敌人的兵力只要存在，敌人愈深入，一切地形交通条件，是愈有利于我们防御的；第二，在敌后的游击战争，只要我们部队坚决的留在敌后领导，在敌人愈深入，则兵力愈分散，后方愈空虚的条件下，是愈能够广大发展的；第三，我们新的力量，只要有作战英勇经验丰富的军队作骨干，依据一年多的抗战经验，尽一切可能保持我国不被完全封锁，争取国外帮助，并尽最善的努力去建立自己的国防工业，则虽在最困难的条件下，我们还可生长出新的近代化的部队以备反攻的。所以，在目前形势下，我们坚持保卫武汉愈久愈好的主张，要求从各方面配合的战斗中生长出长期保卫武汉的力量，以便能够过渡到战略相持的第二阶段。但同时指出武汉的得失，决不能解释为能否长期抗战的关键，而发生新的悲观动摇的心理，或孤注一掷幸胜幸得的企图。我们要认识抗战是长期的，只要我们在保卫武汉当中尽了最善的努力，即使武汉不保，我们也还有可能继续长期抗战，争取第二阶段的到来的。

　　因此，我们基本的口号是：坚持持久战！我们目前的战斗任务是：争取愈久愈好的保卫武汉！

二

　　根据上篇的分析，我们指出目前三期抗战及保卫武汉的战斗，正处在一个紧要的关头，即是说或者保卫武汉的战斗持久下去，生长出长期保卫武汉的力量，或者我们尽了最善的努力以后，而仍不能保有武汉。在这样一个紧要关头的前后，新的一时期的困难的发生，是可以遇见的。

　　抗战既是长期，我们决不畏惧困难，但必须认识困难才能克服困难。什么是可以遇见的困难呢？

　　首先，看到敌人方面，他将以军事分割和政治分化加强我们的困难。敌人目前进攻武汉的步骤已经加重其山地迂回和切断平汉、粤汉的作用，其企图系在发展向南北两方深入的步骤。现在敌人在黄河北岸沿风陵渡、垣曲之线，企图渡河，便是响应信阳以东敌人切断平汉、陇海的准备。敌机在粤汉沿线的继续狂炸，敌军在台湾，敌舰在南海的故作声势，便是向我华南进攻及向香港政府威胁的预兆。总之，敌军夺取武汉的计划，是包含着继续进攻，实行军事上分割华北、华中、江南、华南及西北和西南的企图的。配合着这一军事进攻，敌人必更加强其政治分化的阴谋，土肥原〔３〕的特务机关的加强，对支（中国）院的成立，在香港敌人策动机关的活跃，过去意、英调停的传说，对中国国内团结的各种挑拨造谣，均证明敌人久已在组织上工作上进行了若干准备步骤。今后战况愈急，武汉愈危，愈会看到敌人这种阴谋及其走狗应声虫的加紧活动。尤其是武汉如果不保，则敌人必配合其军事分割，更要扩大傀儡政权的建立，加深其威迫利诱的阴谋，挑拨离间的诡计，特别会助长地方分裂倾向，策动反对抗战领袖的私图，暗中勾引局部妥协，以图达到其政治分化的目的。

　　次之，看到我们自己方面，将要遇到的困难是：（一）一部分人将因为不了解武汉的得失并不关系于能否长期抗战而发生动摇悲观的心理，慌乱逃避的现象；（二）如果战斗激烈，会发生短时间军事转移和兵力补充的困难；（三）在敌后的游击运动，会因敌人抽兵回攻，将遇到一时发展的困难，目前敌人在华北以主力围攻晋冀察边区，便是首先想以打击晋冀察游击根据地，来阻止各战区在敌后游击战争的发展；（四）因为敌人在军事上分割我们的领土，全国政权在联系上的困难，会有人怀疑到政权的统一是否可能，地方分裂的倾向会在小范围内发展，政治上的保守倾向，或在某些地方，某些部门，会强化起来；（五）因为大城市更多的失陷，铁路交通的割断，财政经济会有突增的困难；〔六）汉奸亲日分子的活跃，敌探托派〔４〕的挑拨，会在一个时期内增长，以破坏全国的团结和统一。

　　再次从国际形势方面看，日本强盗既然会利用欧洲紧张形势的间隙，加速的向武汉进攻，则欧洲暂时的妥协局面，张伯伦〔５〕的妥协政策，不能不相当的影响某些国家。当然这不是说欧美的民主国家会完全屈服于日本强盗面前，这是与国联〔６〕引用盟约十六条的决议不符的，但是，一种半妥协的状态，或者一种不更积极援助中国的状态是可能的。这样，将会引起一部分的人对于国际的援助表示失望，而更减低其自力更生的信心。

　　以上，这一切可以遇见的困难，并非危言耸听，而是使我们认识在战斗激烈和战况不利条件下可能到来的。这些困难，是长期抗战中不完全可以避免的困难，是过渡到新的阶段的关头常常会遇到的困难，正如胎儿降生时的困难一般。

　　现在问题的中心，是在估计和认识这些困难之后，有无可能克服这些困难？我们的回答是：在十五个月抗战的进步和成功中，我们已有了可能的基础来克服这些困难。我们看：

　　第一，战争是烈火，是洪流。十五个月的抗战，它已将中华民族的生活起了剧烈的变化，它已将半数以上的中国人民或沦陷在敌人占领区域，或流亡在四方的，起了根本的生活变化，它已将千千万万的中国人民组织起来，武装起来，在战区，在敌后，与敌人进行长期的浴血战争！这种民族的觉醒，民族的愤怒，民族的斗争，区域之广，数目之多，动员之深，是中国史上空前所未有的！这种力量的伟大团结和发展是敌人任何的军事分割和政治分化所不能分解的，它将保证着中国抗战的继续，它将保证着中华民族的胜利！在这种伟大的斗争前面，一切动摇悲观的心理，慌乱逃避的现象，将要消失下去。一切地方分裂的倾向，一切秘密的局部妥协，将会受到严重的打击。因此，只有全民族的生动的力量，首先是敌后战区的一切力量，都能团结起来，一定能继续长期抗战，争取最后胜利。

　　第二，全民族的领袖蒋委员长一年多对于抗战的领导和坚持，是保证长期抗战的中心。日本强盗想用一切阴谋诡计，挑拨离间，将灭亡全中华民族的侵略战争，故意解释成为反对蒋委员长的个人及其领导。我们应该以全民族的力量，用一切方法，拥护蒋委员长及国家的统一，去反对日本强盗及其汉奸走狗的任何阴谋诡计、妥协投降，反对任何地方分裂倾向，反对任何反对抗战领袖的私图。要认识敌人所怕的，所恨的，正是我们应该拥护的。敌人所要分割的，所要分化的，正是我们应该统一的。当着敌人正在进行军事分割、政治分化的前面，最高统帅抗战到底的决心，国家的统一与团结，才更证明对于克服困难有决定的意义。

　　第三，抗战造成中国进步，首先是几百万的军队，在抗战的烈火中经过了巨大的锻炼。现在全国的军队，不论东西南北，都已在战斗中认识：只有抗战到底，才是生路，中途妥协投降，便是死路一条！坚持抗战才能增强战斗力，生长出新的力量和发展敌后广大的游击运动，才能击破敌人继续进攻和军事分割的计划，才能使敌人的政治分化归于失败。敌人以山地迂回，切断铁路，包围武汉和继续深入，来困难我们，我们只有以更坚强的正面守卫，更多的野战部队，迂回敌人侧翼，才能战胜敌人，消耗敌人，破坏敌人的分割，转而分割敌人。敌人以强渡黄河，割断西北来困难我们，我们应以黄河两岸的积极行动，敌后的更多活动，抓住敌人，不使深入。敌人以进攻和封锁华南来围困我们，我们应以加强华南防卫力量，增多和增强国外交通，来回答敌人。敌人以首先打击晋冀察边区，来沮丧我们对于发展敌后游击战争的决心和信心，我们应以坚持华北游击战争，保卫晋冀察边区，特别是在全国战区敌后发展更多的游击根据地，来回答敌人的围攻，来吸引更多的敌人回攻敌后。敌人以缩小我们的地区，切断我们的铁路交通，来困难我们的补充和运输，我们应控制更多的兵力在敌人的后方，来扩大我们的补充，以保证我们的交通。敌人以夺取我们的大城市，捣乱我们的金融生产来困难我们，我们应以广泛的游击战争，肃清汉奸部队，以包围敌占的城市，切断它们水陆交通，断绝它们经济流通，增强我们自给能力，来孤立敌人。特别是敌人以控制一切战略据点，交通要道，想从分割地区，走到分割我们的武装，使之成为零星分散的部队，便于他逐渐消灭，我们应以坚持长期抗战，在作战的正面，继续补充正规部队，在广大的敌后游击区域生长出更多的正规部队，尤其是在自己保有的后方，尽一切可能成立新的近代化的部队，准备反攻。我们相信这一切新的困难，在战斗的努力当中，是一定能够克服的。

　　第四，国民党是处在政权和军队的领导地位，它的进步，决定着中国长期抗战及其胜利的前途。应该特别指出：国民党有孙先生的三民主义作基础，有辛亥〔７〕及北伐〔８〕两期革命传统，有孙先生、蒋先生的先后领导，在其发动抗战后，又颁布了抗战建国纲领〔９〕，这在基本上，已给了国民党向前进步的基础。发展这个基础，不仅是国民党员而且是全中华民族的任务。我们号召全国人民诚心诚意的为实现三民主义及其抗战建国纲领而工作，就一定能够解决当前许多新的困难。民族主义的实行，会使全中华民族更加团结起来，参加抗战，日寇树立的傀儡政权就会更加缩小，满蒙伪军，就会更多的过来。民权主义是包含着尊重各抗日党派独立性的，它的实行就会使参政会〔１０〕的制度普及到省、县、市各级，它就会更广大地动员民众，组织民众，使之投身军队，参加战争，实行自卫，供给资财，以保证人民抗日权利的扩大。民生主义的实行，它就会实现有力出力，有钱出钱的真正合理负担，并会满足民众社会的及物质的要求。尤其是抗战建国纲领的实施，更能适应抗战的紧急需要，一切旧的数千百年分裂国家的屏障，在战争的烈火中已被破坏，新的民权制度必会起来代替。旧的组织机构及行政实务，不适合抗战紧急需要的，就会依据抗战建国纲领加以改造。贪污浪费，腐化堕落，妨碍廉洁政治及战时生活的，就会改进。财政、经济、教育、民运等政策，不合抗战利益的，就会改以抗战建国纲领的规定实施。尤其是战时财政经济政策，更会坚决彻底的执行。对外政策，就会坚持自力更生的原则，运用外援，而不是依赖外援。这一切三民主义及抗战建国纲领的政策，应首先在恢复的沦陷区域实施；在那里，旧的基础被敌人摧毁了，我们只有依靠三民主义的模型，才能真正建立起中华民国。建国是在抗战中开始，这在敌后游击区域才更看得真切，才更能击破敌人分裂我们统一政权，分化我国政治的阴谋。

　　第五，巩固和扩大统一战线，特别是国共两党的长期合作，是回答敌人及其汉奸走狗分裂中国破坏团结的最好办法。敌人一切造谣中伤，挑拨离间，禁不住实际团结的回答。国民党领袖的屡次宣言谈话，共产党抗战前后的主张，各抗日党派的公开表示，参政会全体的宣言，都证明中华民族是团结的，统一战线是形成了的。在这统一战线的面前，一切历史的痕迹，应当消失，一切小的磨擦，地方的冲突，某些党部不妥的做法，均应受到批评。一般的说，战场的团结，经过血汗交流的凝结，以及八路军的模范作用，是坚固到后方。上层的了解和来往，能够影响着下层合作的扩大。因此，要巩固和扩大统一战线，必须首先在敌后战区做出统一战线的模范。拿那里的统一战线的成绩，国共两党的良好关系，来证明给自己的后方看，国共两党长期合作是有保证的，统一战线的巩固和扩大，是有可能的，尤其是可以给敌人及汉奸托派看，一切破坏是枉然的，更给一切怀着历史成见及顽固分子看，一切担心疑虑是不应有的。

　　综上所述，在全民族的团结前面，在民族领袖坚决领导抗战前面，在全国军队戮力抗战前面，在国民党及政府的进步前面，在统一战线的巩固和扩大，尤其在国共长期因此，我们在将要遇到的困难前面，不是畏惧困难而悲观失望，也不是轻视困难反而增加困难，而要勇敢的坚定的克服困难。

三

　　我们分析了目前抗战形势及其趋势，特别指出了可以遇见的困难及克服这些困难的条件和方针，现在我们还应再进一步说明相持局面的第二阶段，是否有到来的可能。因为保持武汉在我手中，来胜利的过渡到相持局面，这是大家所能了解的。但长期保卫武汉的条件并未具备，这不能不使我们着重的估计到即使武汉不保，也还有可能争取第二阶段的到来，不过中间却须经过一个时期的困难。克服这些困难，就一定能够造成相持的局面。然而在这种事实没有来到之先，武汉既濒危急，新的困难又已开始，许多悲观论者会怀疑这个前途，一部分侥幸论者，想从孤注一掷中来挽救这个危机。这两种观点，都是对武汉失守后失去前途，而缺乏坚持长期抗战的决心。因此，我们更须进一步说明相持局面到来的可能性问题。

　　一，一般人如只从单纯军事上的势均力敌，来认识相持局面，则不仅武汉失去后一个期间不会有此可能，即在武汉在我手时，亦无此条件。中日军事上的势均力敌，不到接近于我之反攻阶段，是不会来到的。因此，敌我的相持局面，是靠着军事、政治、经济、地理、交通及日本国内、国际诸条件相互配合，相互因果而组成的。武汉在我手中，这些条件固然可以向着有利于我方面发展；武汉不在我手，这些条件也不会起基本上的变化。但一个条件，我们必须保有可以继续抗战的力量。力量存在，一时期不利于我们的条件，是可以在继续的战斗中改变过来的。

　　二，许多人在军事上只看到武汉一点，而没有看到全国，只看到敌人在进攻武汉时所集中的兵力占优势，而没有看到敌人兵力在中国各战区分布的情形；只看到我们目前尚不能以更强的兵力和装备保障武汉不失，而没有看到我国军队在全国范围内所生长出的力量。敌人可以在进攻武汉较狭窄的地区，以优势的兵力压倒我们，但不能在全国战区及敌后处处集中优势兵力压倒我们。目前华北五省敌人分布的师团计十一个，兵力过三十万，但不论他进占风陵渡和垣曲，回攻晋冀察边区，都不能抽出过五万人的部队。如果敌人想以同样的兵力布置于华中、江南、华南，则平汉、粤汉以东的广大区域，非两倍以上如其在华北的兵力不为功。从地形上看，不论敌人在得武汉后，向南向西或向西北，都要经过更多的山地和西北的高原草地，这是使敌人困难加深，消耗加多的。从交通上看，敌人在华北拥有全部铁路、公路线，既不能阻止我们游击战争的发展，相反的，还经常被我们切断破坏，即使敌人深入武汉，有长江水路可通，但向西南、西北深入，铁路、航路都将无法利用。因此，只要我们正面防御保有继续作战的部队，后方能迅速加紧建立新的近代化的国防军，特别在战区敌后，派遣着得力的部队，发展广大的游击运动，使每一个区域都像晋冀察，则军事上正面堵着，后面抓着，新的力量生长着，以准备反攻的相持局面，是一定可以胜利的到来的。

　　三，不仅从军事上看，我们还应从政治上看，敌人侵入中国内地，并不能达到其统治中国的妄想。华北五省三分之二以上的城市，在中国军队和人民的手里，广大的民众被组织起来参加游击战争，许多汉奸维持会被摧毁了，许多伪军保安队反正了，唐山矿工暴动了，甚至平津的人民都偷着帮助中国游击队。这一种燎原的战火是日寇点起来的，它将燃烧到华中华南。只要我们能绝对相信这种政治优势，努力发展这种政治力量，特别是争取伪军，摧毁伪政权，反对汉奸敌探及任何亲日投降活动，不使敌人得到任何中国人的帮助，则敌人虽然深入了我们内地，直等于进入墓道。

　　四，在经济上，有人以为敌人占领了武汉，且占领沿海各口岸，可以恢复长江及沿海商务，来从中国吸取金钱、原料，支持他的侵略战争。这种可能虽有，但是很少，很难，并且很慢。我们不要忘记日寇占领东三省三年后才得到收入上的利益。我们更不要忘记中国还是农业国，今天敌人所占的大城市要道，其工厂、矿山、铁路，有的被敌人炸毁了，有的被我们迁移了，能够保存的，只能作敌人军事上的若干补助，决不能作为日本军事生产上的最大依靠。大城市的商业，是靠吸收中国农村的原料和货币来贸易的，今天的华北日货，已不能推销到平津百里以外，晋察冀边区及冀中竟禁绝了日本香烟的输入，这是游击战争锁住了城市。只要我们在敌后的游击战争普遍发展，处处包围城市，并配合着正规军作战，则敌人即使占领了沿江沿海各口岸，其作用决不会如预想那样大。而我们自己如果能坚决的实行战时财政经济政策，加紧的建立国防工业及军事交通，限制国内的法币的外流，广泛地发展内地小生产，增加农业生产，加强内地的交通运输，则我们在相当范围内的经济自给，是可以对抗敌人的。

　　五，在日本国内方面，不论敌人的内阁如何改组，外交如何强化，思想如何统制，长期作战如何强调，但其速战速决的方针，是始终没有改变的。敌人国小人少，资源不富，而又野蛮暴虐到极点，国外树敌既多，国内矛盾又大，因此，敌人自开战迄今，始终没有决心进行长期战争。显明的是：每次用兵，都是逐渐增加，常常失去时机；兵力分散，又不协同；在动员上，常是临时抽调；在财政上，更是挖肉补疮；在军事生产上，消耗既多，大的长期设备，也还未见；使用满蒙伪军，更多顾虑；而其本国军队，反战空气，也渐增长。这是日本国内条件，并不利于支持长期战争而有利于我们造成相持局面的。

　　六，国际条件，目前当然会被日寇利用，加紧压迫中国，威胁英法，求得局部妥协。但张伯伦的妥协政策，虽其基本上在东方在西方都是一样的，然而欧洲没有大战，欧洲人民怕战争好和平的心理异常浓厚；而中国却不是捷克，中国已处在日寇侵略战争的屠杀底下，抗战年余，英、法等国的在华利益是被日寇侵占着、摧毁着。张伯伦既不能也不会使中国完全变成捷克。日本今天也决不会恢复卢沟桥事变以前的要求，而且，它的外交政策正在强化。所以只要我们坚持抗战，欧、美民主国家，尚不会完全改变态度，也还不会反对其他国家在它们所许可的条件下援助中国。并且，只要我们抗战有力，日寇侵占摧毁各国在华甚至远东的利益愈多，各国援华制日的行动，也不是不可以增强的。

　　以上这些条件的生长与发展，使之互相配合，互相因果，相持局面的到来，不是不可能的。因此，保卫武汉的战斗，固然愈久愈好，但决不能在长期保卫武汉的条件尚未具备的今天，想作孤注一掷的侥幸的尝试。这不仅对于保卫武汉并无大的帮助，而且对于继续长期抗战是有害的，是不利于转入相持局面之过渡阶段的。

　　力量是保证长期抗战的决定条件！保卫武汉重要，坚持持久战更重要！

　　只有坚持长期抗战，加强国内团结，才是克服困难，争取胜利的转入相持局面的基本方针！



　　＊这是为武汉《新华日报》写的社论。刊载于一九三八年十月七、八、九三日武汉《新华日报》。

　　注释：

　　〔１〕堪察加是苏联最大的半岛，在亚洲东北部，面积约三十七万平方公里。

　　〔２〕昆仑山横贯我国新疆、西藏间，东延入青海境内，长约二千五百公里。

　　〔３〕土肥原，即土肥原贤二（一八八二～一九四八），日本军事特务头子，陆军大将。一九三一年任奉天特务机关长，为发动九一八事变、炮制满洲国的主犯之一。七七事变后，拉拢吴佩孚，拥立汪精卫，制造傀儡政权。日本投降后，以甲级战犯被捕，一九四八年被远东国际军事法庭判处绞刑。

　　〔４〕敌探托派，参见本书《无产阶级革命的俄罗斯》一文注〔４〕。

　　〔５〕张伯伦（一八六九～一九四○），英国首相，保守党领袖。一九三七～一九四○年首相任内纵容德、意法西斯侵略的"绥靖政策"。一九三八年承认意大利墨索里尼侵占埃塞俄比亚，默认希特勒德国吞并奥地利，并与德国缔结《慕尼黑协定》，出卖了捷克斯洛伐克。第二次世界大战爆发，英国被迫卷入战争，绥靖政策破产。

　　〔６〕国联，参见本书《欧战后之欧洲危机》（伦敦通信）一文注〔５〕。

　　〔７〕辛亥革命，参见本书《革命救国论》一文注〔１０〕。

　　〔８〕一九二六年七月，为了推翻北洋军阀的统治，国民革命军从广州出师北伐。由于有中国共产党的政治领导和广大工农群众的积极支持，国民革命军迅速地占领了长江中下游广大地区，严重地打击了帝国主义和封建势力。一九二七年四月十二日，以蒋介石为代表的国民党右派发动反革命政变，第一次国内革命战争遭到失败。

　　〔９〕抗战建国纲领，参见本书《争取更大的新胜利》一文注〔４〕。

　　〔１０〕国民参政会是抗日战争时期国民党政府被迫成立的最高咨询机关。参政员由国民党政府"聘请"，形式上包容了各抗日党派的代表，但国民党党员占绝大多数。该会对于国民党政府的政策措施，没有任何约束的权力。为了表示团结抗日，中国共产党也派代表出席了参政会。第一届第一次国民参政会于一九三八年七月在武汉召开。以后由于国民党日趋反动，言论更受束缚，该会日益成为国民党政府的御用工具。一九四一年皖南事变后，中国共产党参政员董必武等为抗议国民党的反动政策，曾进行了坚决斗争并多次拒绝出席参政会。抗日战争胜利后，国民党政府召开国民大会，国民参政会于一九四七年五月举行第四届第三次大会后撤消。



