# 辛亥，北伐与抗战

中文马克思主义文库 -> 周恩来
辛亥，北伐与抗战
（一九三八年十月十日）

在武汉濒于危急的今天，来纪念中华民国二十七年的双十节--武昌起义〔１〕，我们抚今追昔，比任何一年都应有不同而严重的感想和希望。

第一，武汉是中华民国的诞生地，是大革命北伐〔２〕时代的最高峰，现在又是全中华民族抗战的中心。这个历史的城市，革命的城市，今天正被东亚的狂兽--日本帝国主义强盗进攻着、轰炸着。全武汉的人民，全中国的同胞，将生着如何感想？我们悲哀吗？不！我们怯却吗？不能！我们只有以更大的动员，来保卫武汉到最后！更展开保卫武汉的血战，到全湖北，全中国！武汉三镇的人民，不应该让辛亥革命〔３〕，北伐时代，两次光荣的历史空空过去，而应该发扬光大这个革命传统，来作武汉三镇的卫士！今天是保卫武汉的最后时机了。做工的，我们不能让日本强盗来到武汉屠杀我们，奴役我们，我们要勇敢的投身军队，参加各种战时工作队，去筑工事，去做担架，去任运输！做买卖的，我们不应该设想日本强盗来后可以安居乐业，赚钱发财，我们要更慷慨的实行献金竞赛，捐助寒衣，募集药品，发动慰劳！开工厂的，我们不应该设想可以在日本强盗底下讨生活，不论大的工厂，小的作坊，我们都要有决心的向内地迁移，一方面可便利军事行动，另一方面可便利内地的经济流通！武汉附近种庄稼的，我们决不能幻想在日寇铁蹄下可以当顺民，要避免日寇的摧残烧杀，好淫掳掠，只有投身军队，武装自卫，要使日本强盗死在我们面前，不让他们压在我们头上！有知识的，念书的，我们不要散乱的往后跑，跑得到的地方，敌人追得到，我们要成群结队的上前线，往敌人的后方走，去战地服务，去救护伤兵，去组训民众，去发展游击战争！今天是武汉三镇人民的最后关头，敌人向着武汉猛攻，武汉人民要站在全国人民的先头，拿我们的力，拿我们的钱，拿我们的知识，做全国人民参战的模范！全国人民将在我们的影响和兴奋之下，共同动员起来，保卫大武汉，保卫全中国！

第二，辛亥起义，是发源于新军〔４〕暴动。北伐战争，也正是十五年双十节前北伐军打到了武昌城。今年双十节，又正当着全国主力部队激烈的进行着保卫武汉的血战！这些军队，多少都经过北伐的洗礼，有着革命战争的光荣传统，而又在当年北伐统帅蒋委员长领导之下，现在黄鹤楼头的国旗，武昌城下的血迹，正被他们光荣的保卫着。中国革命军队，从辛亥，到北伐，到抗战，在武汉不仅有史的联系，而且有血的联系。光荣的任务，落在光荣的革命军队身上，我们正应发挥革命军队的特长，坚决，勇敢，迅速，机动，来击破敌人的进攻，挽救武汉的危急。我们更应发挥革命军队的优点，政治工作，造成上下一心，军民一体，来巩固我们的战斗，扩大我们的部队，发展全民族的抗战，建立起新的中华民国！

第三，辛亥革命，是在中华民族伟大领袖孙中山先生领导之下创造的。十二年前的北伐战争，现时的抗战，又正是蒋委员长所领导的。三民主义是这三次革命的旗帜。同盟会、国民党，是具有这个历史传统的政党。不论辛亥革命后来失败，北伐后又有内战，但三民主义的历史发展，孙先生的遗教，蒋委员长今天的领导，国民党今天在政权中、军队中的领导地位，都成为今天全民族抗战中所决不能少的胜利因素，我们希望国民党同志，在其信仰的主义、领袖和党的领导下，更加发挥其光荣的历史传统，为着中华民族的解放事业，为着抗战建国纲领，领导着全中华民族，向着坚持抗战，巩固团结的胜利之道前进！辛亥革命，是多少革命烈士的头颅筑成的，是多少革命先辈的心血造成的，彭刘杨三烈士的纪念碑〔５〕，至今还矗立在武昌城内，国民党中现在还有不少辛亥革命时代的斗士，应该本着推翻满清，至死不屈的精神，领导我们中华民族后起的儿女，向着民族革命的大道前进！北伐精神，更是今天许多国民党员所能回忆的，当时国民党改组不到三年，便打下了半个中国。现今日寇占领了半个中国，历史的任务要求国民党恢复辛亥及北伐的精神，来完成辛亥革命以来未竟的事业！特别是，国民党历史值得回忆的是：辛亥革命成功，同盟会扩大成为国民党，被官僚分子窜入，革命失败，于是，孙先生有中华革命党的改组。倒袁护法〔６〕，国府〔７〕两广，陈炯明〔８〕僭乱，孙先生离粤，于是，有民十三国民党之改组。北伐到建都南京，中经内战，革命又败，于是，抗战起，而有蒋先生领导召开国民党临时代表大会，发布抗战建国纲领，发起三民主义青年团之举。这一历史的发展，需要国民党在武汉危急，抗战发生新的困难的紧要关头，在孙先生伟大坚强，蒋先生艰苦卓绝的感召之下，将改造国民党，重建中华民国的艰巨任务担负起来！我们共产党人，愿追随国民党之后，号召全国人民帮助国民党，一致的为战胜日寇，建立三民主义的新中国而奋斗到底！

第四，辛亥革命前，孙先生联合了当时革命团体，如兴中会，华兴会，光复会等组成了同盟会，并联络会党，联合当时咨议局立宪派中革命分子，于是，有辛亥革命的成功。这是中国统一战线之最初形式。国民党改组，国共合作，要算是第二次统一战线，于是，造成北伐胜利。现在，全国抗战，在蒋先生领导之下，于是，又有第三次统一战线，包含着新的国共合作，及其它抗日党派的参加。但是，抗战是长期的，我们需要更坚强的，更扩大的民族统一战线，来战胜全副武装的凶恶的日寇！因此，我们不仅要回忆历史的成功，更要回忆历史的教训！辛亥革命的失败，北伐时国共的分裂，不能不使我们承认：当时统一战线的基础还不巩固，还不扩大，特别是北伐时国共两党的政策，还没有取得一致。今天在反对日本强盗的自卫战争面前，我们的统一战线是全民族的，不分任何种族、阶级、党派、信仰、性别，都应该联合起来。我们统一战线的政治基础是三民主义。我们奋斗的目标，不仅在共同抗战，并更要共同建国。国民党，共产党，及其它各抗日党派，全中国人民，谁也不能在抗战中有异图，闹分裂。谁这样做，谁就是帮助敌人！抗战胜利后，建设艰难，更需要大家合作，共同努力。谁要想独霸，想分立，谁便会再度招致失败！中国抗战，非全中华民族团结起来，不能成功。抗战胜利后，只能是统一的民主共和国，这是客观历史决定的真理。谁违背这个真理，本身的失败事小，中华民族的失败事大！今天在辛亥革命二十七周年，全中华民族之爱国各抗日党派，应该宣誓：使中国不再闹分裂，使统一战线永远的巩固和发展下去，使大中华民族永远地团结起来，一直达到抗战胜利，建国成功！

辛亥、北伐、抗战，这三个历史时期，将造成中华民族复兴的大业。长白山的雪，黄河扬子江的水，南海的波涛，蒙古西藏的高原，西北的风霜，将永远伴着中华民族青天白日满地红的国徽，雄立于世界，万世无疆，这应该是我们对双十节永远的颂祷！

＊原载《新华日报》和《群众》周刊史学会编《坚持团结抗战的号角》（１９３８～１９４９年代论集）。

注释

〔１〕武昌起义是辛亥革命的导火线。一九一一年（宣统三年）五月，清政府借铁路国有名义，将民办的川汉、粤汉铁路收归国有，并以铁路修筑权为抵押，向英、法、德、美四国银行团借款，激起川、鄂、湘、粤各省人民的反抗。六月十七日，四川成立保路同志会，举行请愿，遭到镇压。在同盟会的影响下，早已在湖北新军和会党中积蓄了力量的文学社和共进会组成领导机构，决定于十月九日起义。九日上午，共进社领导人孙武在汉口俄租界试制炸弹失慎爆炸，在汉口的机关暴露，文学社领导人蒋翊武闻讯，改定当夜发动。因送信人未传达到炮营，号炮未响，各营未动，而武昌的机关又被破获，十日上午，清湖广总督瑞澄和第八镇统制张彪将按名册捕人，形势紧迫，革命党人暗中联络在当晚起义。晚七时，新军工程第八营的革命党人熊秉坤和金兆龙等首先发难，率队占领楚望台军械局，各营奋起向总督署进攻，瑞澄、张彪等逃走，革命军遂占领武昌。时孙武、蒋翊武均不在场，革命党人强推清协统黎元洪出任军政府都督，发表宣言号召各省起义。湖南、陕西、江西等省相继响应，形成全国规模的辛亥革命。

〔２〕北伐，参见本书《论目前抗战形势》一文注〔８〕。

〔３〕辛亥革命，参见本书《革命救国论》一文注〔１０〕。

〔４〕新军，指清朝末年编练的新式陆军。辛亥革命前夕，由于革命党人的积极活动，各省新军中的下级军官和士兵倾向革命的人日益增多，新军就成为武昌和各地起义的重要力量。

〔５〕彭刘杨三烈士纪念碑即彭楚藩、刘复基和杨宏胜遇害纪念碑。一九一一年十月九日是革命党人原定的起义之日。这天晚上十一点，起义领导人彭刘杨等正在武昌小朝街总指挥部楼上部署起义，迎候南湖起义的炮声，突然遭到清宪兵队和巡警的包围和搜查，彭刘等二十多位革命党人被捕。同时，为起义部队传递消息和运送弹药的杨宏胜也遭不幸。彭刘杨三人很快被押到湖广总督署大厅受审。三位革命者大义凛然，不惧酷刑，坚贞不屈，于次日凌晨就义于东辕门。三烈士殉难，激起了革命党人的无比义愤，成了武昌起义的催化剂。如今三烈士纪念碑位于武昌造船厂后院，烈士就义处建立了纪念碑亭。

〔６〕一九一五年，袁世凯伪造民意，准备称帝，改次年为"洪宪"。孙中山和全国人民积极进行反袁运动。同年十二月蔡锷组织护国军，发动护国战争。一九一六年三月二十二日，袁世凯被迫取消帝制，要求停战。北洋军将领冯国璋、段祺瑞别有意图，不肯为袁作战。六月六日，袁世凯忧惧病死。

一九一七年七月，孙中山反对北洋军阀解散国会，提出拥护"临时约法"、恢复国会的主张，率驻沪海军到广东，组织护法军政府，发起护法战争，孙中山被选为大元帅。一九一八年五月，桂系军阀分裂护法军政府，排斥孙中山。孙中山辞职，护法战争宣告失败。

〔７〕国府即国民政府，其前身是一九二三年在广州成立的以孙中山为首的大元帅府。一九二五年孙中山逝世后，在中国共产党的推动下，于七月一日改组为国民政府，通称"广东革命政府"。一九二七年一月，随着北伐战争的胜利发展，国民政府从广东迁至武汉，通称"武汉政府"。同年四月，蒋介石发动四一二反革命政变，十八日在南京另立所谓"国民政府"。从此，"国民政府"便成为代表帝国主义、封建主义和官僚资本主义利益的反动政权。

〔８〕陈炯明，参见本书《军阀统治下的中国》一文注〔１５〕。

