# 在鲁迅逝世二周年纪念会上的讲话

中文马克思主义文库 -> 周恩来
在鲁迅逝世二周年纪念会上的讲话
（一九三八年十月十九日）


　　我想在今天鲁迅先生逝世二周年纪念会上大家都是诚心诚意的来纪念鲁迅先生的。我自己不是文学作家，然而却参加了文艺协会，同时在血统上我也或许是鲁迅先生的本家，因为都是出身浙江绍兴城的周家，所以并不如主席所说以来宾资格讲话。然而我却不愿意如景行严口口声声"吾家太炎先生"似的而也说"吾家树人先生"，我只能如古诗所说："疾风知劲草，板荡识忠臣"似的来怀念鲁迅先生。

　　确实是的看到田汉〔１〕先生的文章，想到去年纪念鲁迅先生，正是上海抗战危急，而今年纪念鲁迅先生，又是武汉危急的时候，所以使我们更易想到劲草忠臣的鲁迅先生，因为鲁迅先生不论在政治上，文学上，人格上，都有值得我们纪念的地方，鲁迅先生生时，在国难当头或局势摇荡时，绝未动摇或妥协过，无论在今天明天都本其一贯精神，崛强奋斗，至死不屈，同时，又启示出来的光明，把握住光明的前途。

　　在文艺上，鲁迅先生一贯地对旧社会给以无情的批判与揭露，不妥协，不苟且，指示我们一个光明的前途。即使在反映中国社会腐朽的阿Ｑ正传上也显示出伟大的奋斗前途，而鼓励着大众反抗腐恶势力，这是在先生早期到后期都是如此的。

　　在先生为人上，对于社会改革、政治运动，是深切地关心着，而反映在他的文学作品中。他的个人生活、社交来往也是丝毫不苟且不屈服的。他看出未来的光明，然而却没有离开社会、离开现实。特别在晚年对中华民族解放之努力，回答一个托派的信上，不容情地揭露托派之阴谋，赞同抗日民族统一战线，指出中华民族解放之大道，是值得我们钦佩他的政治远见的。

　　到今天，抗战已经一年有余，更走到一个艰苦困难的阶段，纪念鲁迅先生，更应该学习这种倔强奋斗至死不屈的鲁迅，不退让，不妥协。困难愈大，要愈加努力，以克服困难，坚持抗战，特别要紧的是要有最后胜利的信心，伟大前途的认识，为达此目的而努力。非有如此信心，即不能坚持长期抗战，向前奋斗，反而会随时因困难而动摇屈服，妥协投降。只有坚信未来之胜利，同时又努力于克服现实的困难，而艰苦奋斗，这才是中华民族之伟大精神要素，也正是鲁迅精神之所代表。

　　在文学创作上，也可如此了解。一般常常争论的现实主义与理想主义的问题，在鲁迅作品中可得到正确的解答。一种写实的作品，没有不受环境的影响和加以主观见解的。只有主观上抓住最现实的生动材料，起了极深刻的反映，能产生出成功的作品。现实离不开环境及物质的支配，而同时又须有主观的选择，包含了理想的见解，并暗示着光明--奋斗目标，这必然是个好作品，正是鲁迅作品的精神。这理想在今天民族抗战的烈火中，便是争求民族解放胜利，一切以此为目标而奋斗着。今天读抗战文学，读现实文学，也便是需要这样的作品，才能动员大众，深入人心，而后在方法上、技巧上，也便能更适合现在，更大众化、更通俗化。这种作风，需要我们今天学习的。

　　所以，不论在政治上、文学上、或为人道德上，都需要我们学习鲁迅先生的精神和作风，发挥鲁迅先生的精神，有着强烈的现实反映，未来的光明追求，是我们今天在武汉更加危急，抗战遇到困难，同时也是战争更加扩大时，我们应有的抱负。我们应坚苦不拔，克服困难，为实现最后胜利而奋斗到底！



　　＊鲁迅逝世二周年纪念会于一九三八年十月十九日在武汉青年会举行。本文原载一九三八年十月二十日武汉《新华日报》。

　　注释：

　　〔１〕田汉（一八九八-一九六八），湖南长沙人。自"五四"运动起，投身于反帝反封建的新文化运动。抗日战争时期，组织抗敌演剧队，开展抗日宣传活动。建国后，对新中国的戏剧事业作出了重要贡献。他是中国现代话剧的开拓者、戏曲改革运动的先驱和中国早期革命音乐、电影事业的领导人。



