# 论今后敌人的动向

中文马克思主义文库 -> 周恩来
论今后敌人的动向
（一九三八年十二月十八日）


　　目前战局正处在一期战争已经结束、二期战争将要到来之过渡阶段。从战略的意义看来，一期战争的特点，敌人是在企图速战速决，求得聚歼我军，逼我屈服，我们则在坚持长期抗战，诱敌深入，以图击破敌人的速战速决。这一战略任务，在敌人是失败了，在我们是成功了。因为敌人过去既然没有歼灭我军主力，今后更没有可以聚歼我军的机会。速战速决的可能既已没有，敌人将被逼进行长期战争，这是敌人战略上的失败。在我们则经过这十七个月的战斗，证明给全中国和全世界的人看，中国的长期抗战，不仅是必须，而且是绝对的可能。敌人愈陷愈深，我们愈战愈强，已成为中日战争中的真理，这是我们战略上的成功。
 
　　二期战争的特点将是什么呢？在敌人方面，将因深入困难，后方威胁，不得不停止进攻，回攻敌后，在我们方面，则由防御与退却转入正面相持，深入敌后发展，以准备反攻。这种相持局面的来到是可能的，但必须以力量来争取，而目前还没到达这种时机，还没具备这种条件。因为敌人速战速决的企图虽被击破，今后虽没有任何一个城市可以诱致我军主力进行歼灭战斗，深入我方以后的兵力虽然不够分配，士气虽然日渐颓丧，地形交通财政生产等等条件虽然日渐困难，但敌人继续进攻的力量还有，进攻的企图并未中止。而我们虽已树立长期抗战的信念，最高统帅告国民书中所指示的持久抗战，全面战争，争取主动的一贯方针，虽已为全国军民所共守，但敌我力量的对比，究还未达到相持的程度。我们在正面的战斗，还未能完全阻止敌人的前进，在敌后游击战争的发展，更未达到吸引和分散敌人使之难以前进的地步，在我新的力量的补整与训练，也还未达到足以击破敌人进攻的程度。因此，我们必须承认：在一期战争中我们虽获得政略与战略上的成功和胜利，但由于许多政治军事上的错误和缺点所造成，使我们在一期战争已告结束之后，还不能不经过相当时间的过渡阶段。即是说，敌人的困难正在增长，我们的困难须待克服的过渡阶段。

　　过渡阶段的长短，决定于战斗。敌人的进攻无疑是继续的，它不仅在正面准备继续进攻和深入，并封锁和切断我西南西北的国外交通，并且在敌后也正在分兵进攻我游击区域和我游击部队，企图消灭我在敌后的活动。即在政治上，也正在扩大傀儡政权的组织，加紧汉奸的活动，特别是造谣挑拨，企图分化我国内团结，削弱我国际影响。而我们只有加紧国内团结，提高民族仇恨，扩大战斗意志，反对一切挑拨离间和动摇悲观的观念，特别在政治上，加强政治机构，实施战时动员，集中全民族的生动力量，供献战争，以克服当前困难。在军事上，更应加强正面的战斗，加紧敌后游击战争的发展，加快我后方的力量的补整和训练，以争取相持局面的到来。只有这样，才能胜利的进入二期战争。

　　敌人新的进攻将向哪一方面发展呢？在广州陷落，武汉撤退之后，敌人的行动，在长江流域是扩张战果，在华南是集结兵力，在华北是企图打击和缩小我国游击力量，这一切都为的准备继续进攻。具体的情形，敌人陆军是在补整与调动，海空军则加强活动，以扰乱我之南海，轰炸我之后方。在敌人准备继续进攻中，可看出一特点，即是敌人今后进攻的方向，有时将不复限于一点，而将同时进攻两个或两个以上的方向。因为，战区之广，交通之长，兵力之分散，不仅我们战区被敌人分割，不可能集中主力保卫一点，即敌人也不易集中全力进攻一方。故敌人今后的行动有可能向平汉粤汉同时进攻。为达到这一战略任务，敌人更有可能先攻广西，以破坏我西南局势，先攻陇海西段以切断我平汉联系。同时，敌人有进攻我国西北的可能。但不论怎样，敌人进攻必有重心，在南在北，将决定于敌人兵力转移的动向和战斗的发展。故目前战局虽较沉寂，但决不应以为敌人已停止进攻，而忘记利用敌人这一准备时间，加紧我们的布置，提高我们的注意，使敌人今后的行动再不能有以前的便利，到处要受到我们的打击，以增加敌人的困难，而争取有利于我的时机的到来。这是目前过渡阶段的战略中国抗战的严重时机和目前任务＊（一九四○年三月）



　　＊原载一九三八年十二月十八日重庆《新华日报》。



