# 二期抗战的重心

中文马克思主义文库 -> 周恩来
二期抗战的重心
（一九三九年五月三十一日）


　　全国同胞们，抗战将近两年，二期抗战也进行了半年多，目前抗战形势究竟怎样？这是大家急于要知道的，但为要了解目前抗战形势，必须先弄清二期抗战的重心究在哪里？依我的见解，二期抗战的重心是在敌后。不论从敌我及国际哪一方面来看，二期作战的重心都在敌后。武汉陷落以后，敌人指出新阶段的战争，是建设战争，这证明重心是在敌后。我们南岳会议，最高统帅的指示，如“政治重于军事”“民众重于士兵”“宣传重于作战”“精神重于物质”“节约重于生产”等等以及决定以几分之几的人力兵力财力深入游击区域，也都是重视敌后的明证。在国际方面，他们认为我们失去这样多的大城市，还能不能继续抗战，尤其是在沦陷的区域中，敌人能不能利用我们的人力物力财力来补偿他的损失，来打我们自己？这种关心，也正是重视敌后。我们看，假使一期作战，敌我争夺的重心是在正面，那末二期作战，敌我争夺的重心便在敌后，因为一期作战，敌人的目的，是在以其强盛的兵力求得速战速决，从正面压倒我们，不图打了十五六个月，敌人消耗兵力六七十万，并不能歼灭我们主力，占领了我们许多城市及交通要道，分散兵力过百万，也并不能控制我们，尤其是我们战斗意志并不因屡屡撤退而丧失，反而愈打愈强，敌人速战速决的方针既归失败，于是进而便以诱降的手段，发表近卫〔1〕声明，企图速和速结。这个声明虽然勾引了卖国贼汪精卫〔2〕的响应，但禁不住蒋委员长驳斥近卫声明的当头一棒，打得近卫下台，精卫显露了卖国投降的原形。速和速结既又失败，敌人知道即使再进占两三个大的城市，也不能歼灭我们主力，更不能解决战争，但敌人的兵力却会更加消耗，更加分散，诱降的企图，反会更加无望。要是决心进行长期战争吧，敌人又决没这个把握，兵力的不够，财力的不济，物力的缺乏，人心的厌战，都使日寇军阀决不能作真正长期战争的打算，因此，这半年来敌人的方针，便转向以战养战，作战重心便转向敌后，所谓以战养战，便是企图拿中国的人力财力物力，补偿他的损失，继续来打中国，以敌人的想法，假使将敌人占领的区域真正为敌人所用，则敌人今日所侵入的十四省区，的确是中国人口最密，物产最丰，财富最多，交通最便的沿海各省，以此资敌，当然敌人困难会减少，而我们困难会加多，敌我相持的条件，也会发生变化。但是敌人是不是能如愿以偿呢？我们的回答是决定于战斗，决定于各方面的斗争。我们现在看敌人是怎样在进行以战养战的企图，首先军事方面，半年来敌人是扫荡重于进攻。敌人在华兵力，约卅六个师团番号，除南昌枣阳两次战役，敌人使用了五六个师团向正面推进外，其他约百分之八十五的兵力都使用在敌人占领区域之防卫与扫荡。所以这半年来，我们在正面只看到南昌枣阳两次较大的战役，而在敌后则敌之扫荡战与我之反扫荡，几于到处都有。从华北到华南，每天都在血战。次之，在经济方面，敌人是开发重于封锁，建设重于破坏。这半年来，敌人自兴亚院〔3〕成立之后，尽力企图经营在华占领地区的经济，如恢复工厂矿山，收买原料粮食，推销仇货，发行伪币，建设交通海港等等，都是想从中国来补偿损失，维持战争。再次，在政治方面，敌人已知南北傀儡政权，全无作用，故极力勾引汪精卫，企图由汪来组织伪党伪政府来分化我国。最近汪逆精卫跑到上海去，组织所谓“世界和平会”即是这种叛国逆谋的具体步骤。另一方面，敌人还企图勾引吴佩孚〔4〕组织伪军，以中国人来杀中国人，但吴佩孚究竟胜过汪精卫，至今不屈。于是日寇不得不利用落伍军人土匪流氓来组织皇协军、绥靖队这些不堪一击的伪军。更次在精神方面，敌人是欺骗怀柔已渐渐重于残暴屠杀。作战近两年，敌人已知其残暴政策只能增强我国人更大的同仇敌忾，决不能压服我国人心，因此，敌人乃不得不提倡对华新认识。但不管怎样，仍然是建设东亚新秩序，东亚意识，东洋思想，共同防共那一类话。以上这一套法宝，便是敌人重视敌后以战养战的具体计划。计划实施的效果怎样呢？我们可以说基本上半年来敌人并还未达到他以战养战的预期效果。扫荡战愈因扫荡而兵力更散，更加无力进攻。经济开发遇到我们抵制封锁，建设遇到我们破坏，收效也就会极微。汪精卫叛迹愈著，他的欺骗作用也就愈小，死期也就愈近。精神欺骗，只要我们随时揭穿，警觉着大家不要上当，则和平便是投降，反共即是灭华的至理名言，将永远为我们抗战的戒条。并且汪精卫叛国的勾当做得愈多，敌人的一切阴谋诡计，也愈易暴露，愈难收效。即使过去敌人有一些收获，也都因为我们自己有些弱点，有些缺点，并非敌人之强所致。我们要知道，一期作战，敌人还凭着他自己的国力来进攻我们，故我们当时在争取主动，现在二期作战，敌人要利用我们的人力物力财力来打我们，其主动已操在我。只要我们努力，不让敌人利用我们人力物力财力，则敌人便无法达到以战养战的目的，而只有继续失败。所以我说，二期作战，争夺的重心在敌后，便是这个道理！ 
　　认清这个道理，争夺敌后的方针便是广大发展游击战争，也可说是展开敌后的全面战争。敌后游击战争的任务有二：一个是建立游击根据地，一个是消耗敌人的有生力量。建立游击根据地，不仅是军事任务，而且是政治上经济上精神上的任务。要与敌人展开全面战争和各方面的斗争，必须在敌后有根据地的建立，才能依靠那里的土地人民和生产与敌人进行精神动员，武装斗争，经济封锁抵制和破坏，推翻敌伪政权，瓦解伪军，动摇敌军，恢复自己政权等等工作。没有根据地，便没有一定的土地人民和生产，便无法与敌人进行长期的敌后争夺，而敌人以战养战的危险便会增长。而以变敌后为前方，必须以建立游击根据地为最具体的要求。消耗敌人有生力量，是游击战争的直接任务。游击战不拒绝必要时机袭占敌人占领的大城市，不反对在有利条件下集中力量消灭敌人主力，但经常的任务是在不断的杀伤敌人，破坏敌后，只要我们深入敌后的作战部队，不断的消耗敌人，则积小胜成大胜，便是今天的战略任务。假使我们在敌后创造出一二十个游击根据地，每一个根据地像五台山中条山一样牵制敌人四五万，则二十个根据地，我们可以牵制敌人侵华的全部兵力。假使我们每一游击部队每天平均能消耗敌人十个，则全国里一百个这样游击队，便可以消耗敌人一千，一年便可消耗敌人三四十万。敌人最基本的弱点是兵力不够，怕损失。我们如能牵制敌人向后，而又消耗极大，则变敌后为前方，积小胜成大胜的战略方针，可完全达到成功，争夺敌后的任务，也可完成大事，重心认定。二期抗战，一定可进入有利于我的相持阶段，以争取最后反攻的到来。因此，我们今天的要求是全国最好的兵力，最优秀的人材，都应该深入敌后，争夺敌后，在那里去建立根据地，到那里去消灭敌人，以争取二期抗战的胜利。 



　　＊这是在重庆中央广播电台的讲话。原载《群众周刊》第三卷第五期。

　　〖注释〗 

　　〔1〕近卫，即近卫文麿（一八九一——一九四五），日本首相（一九三七——一九三九；一九四○——一九四一〕。一九三七年六月四日组阁，发动侵略中国的“七七事变”，“八一三事变”，扩大侵华战争。一九三九年一月辞职，任枢密院长。一九四○年七月再度组阁，对内组织大政翼赞会，推进“新体制运动”，对外与德、意缔结军事同盟，并同美国进行谈判。一九四一年七月第三次组阁，因对美谈判陷于僵局，阁内意见不一，十月十六日宣布总辞职。一九四五年十二月六日被指名为甲级战犯，十六日服毒自杀。 
　　〔2〕汪精卫（一八八三——一九四四），原籍浙江山阴（今绍兴），生于广东番禺。一九二六年时是国民党中央执行委员会常务委员、广东国民政府主席。抗日战争爆发后，任国民党副总裁。一九三八年底公开投降日本帝国主义，后任日本帝国主义扶植的南京傀儡政府主席。 
　　〔3〕兴亚院是日本政治经济侵略的主要机关，成立于一九三八年，举凡所有对华根本方针，都须经兴亚院会议议决才能付诸实施。所谓兴亚院会议，系五相（即首相、财相、外相、陆相、海相）加上总务长官的会议。兴亚院从其性质上看来，属于殖民地化的建设，它所包括的部门为政治、经济、文化、技术等。 
　　〔4〕吴佩孚，参见本书《军阀统治下的中国》一文注〔2〕。



