# 中国抗战的严重时机和目前任务

中文马克思主义文库 -> 周恩来
中国抗战的严重时机和目前任务
（一九四○年三月）

一

中日战争已经进行快三年了。这是一个持久的战争。中国人民为谋其民族解放的彻底成功，只有将战争进行到底。然而由于长期战争的关系，特别是对于日本的消耗，不能不影响战争的双方，尤其是由于西欧帝国主义战争开始以来，整个的国际形势有了变动，这就给中日战争更带来了新的影响。于是在日寇，英法美帝国主义者及一部分中国地主资产阶级，特别是买办阶级中间，正发展着一种共同的趋势，即是企图从牺牲和出卖中国人民的利益上，从分裂中国民族统一战线及引导中国投降上，找到彼此妥协的出路。但是中国的广大人民和抗战军队，则正增长着坚持抗战，反对投降，坚持团结，反对分裂，坚持进步，反对倒退的要求，以期达到胜利的出路。

这正是一个严重的危机。中华民族及其英勇的军队，在这个严重的转变的时机中所进行的反对投降、分裂和争取民族解放战争胜利的斗争，正关系于全中国人民的命运，同样对于世界劳动人民尤其是日本人民及东方被压迫民族有着重大的意义。

二

在中日战争的整个过程中，中国抗战营垒中存在着的投降危险，再没有比现在更尖锐化了。这种危险的来源，要从三方面看：

第一，要从帝国主义列强方面来看这种投降危险的来源。

在国际新形势下，世界反和平、反人民利益、反苏联、反弱小民族的先锋，已经是英法反动政府。它们正在企图牺牲全世界劳动人民及被压迫民族的利益，将它们拉入两欧帝国主义的战火中去。美国政府表面上虽讲和平，虽主中立，但实际上是支持英法帝国主义这一倾向的。因此，这就不能不使他们对于中国的立场有了新的变化，这种变化正在重大的影响着中国的抗战营垒。

假使在欧战开始以前，英法帝国主义者利于中日战争延长，双方削弱，以便后来它们好出头仲裁，那末，在现在它们便利于迅速结束中日战争，以便利用中国资源人力到欧战中去，吸引日本加入英法联盟，并诱引中国去反对苏联。显然，目前英法在远东的地位是减弱了，因此，它们更趋向于对日妥协，相当的承认日本在中国的所得，以换取它们在远东利益的保持。美国在远东的比重虽然加强，但它一方面既怕中国民族解放战争走向彻底胜利的道路，另一方面又因为战争谋利者的重要主顾已经转在西欧，所以最近它在远东问题上的积极，正是要寻找妥协的途径，以便好出头调停中日战争。

不管英法美帝国主义者彼此之间在远东问题上有何矛盾，不管它们对日寇的矛盾多么大，它们对中国政府及中国人民所加强的压力，正是一致的趋向于引导中国走向投降，并企图从挑拨中国抗战内部的分裂上开始，以便取消中国人民对于日寇的抵抗。

同时，它们这种取消中国抗战的企图，又正是与它们压制其本国人民的反战运动，压制其殖民地半殖民地的民族解放运动密切联系着的。

三

第二，要从日寇方面来看这种投降危险的来源。

日本帝国主义在近三年侵华战争的消耗中，造成它国内困难的日益增长。日寇在两年半的时间，动员到中国战场作战的人数，已经达到一百五十万人以上，其中伤亡数目便近七十万人。照专家估计，日寇在其保留的壮丁中，只能再组织三十个优秀的师团（包含已组成在后方的十三个师团在内）。这样就使日寇感觉它准备用以应付其他事变的兵力大大的不够了。日寇三年来关于军事性质的用费已达到一百六十万万日元，其中属于战争的追加费用已达一百二十万万日元。本年度的国家预算，已超过一百万万日元，较战前一九三五年度预算增高到百分之四六九。这一切费用的增加，完全依靠于榨压人民的捐税及巨额公债的弥补，而公债推销不出的情形，已一天天严重起来。日本的军火及其军用品原料，大部分是依靠国外输入。单一九三八年便输入十一万万日元。因是，在战争中，日本贸易每年都入超五万万--六万万日元。而为弥补入超，便须输出现金，现存的金子在一九三九年底，不过两万万日元左右了。由于这些空前的战争负担，加以轻工业的衰落，农产品的缺乏，物价的昂贵及战时的一切征发，使得日本人民的生活严重的恶化了，尤其是日本军队士气的低落，日本人民厌战心理的增长，更加使日本帝国主义内在的困难尖锐化了，这是一方面。

另一方面，日本帝国主义在中国人民及其军队的抵抗方面所遇到的困难，也是它完全没有料到的。它在侵华战争中的速战速决计划，是早已失败的了。但战争愈延长，它的消耗愈大，困难愈多，危机愈深，单靠军事力量解决中国问题的企图，它就会愈加无望。当着战争的第一年，日寇用兵达三十七个师团，在中国领土上前进了一千八百多公里，第二年减成三十三个师团，只前进了三百一十公里；第三年的上半年，军队无大增减，亦只前进了二百多公里。显然，日寇单靠军事进攻，是很难大有作为的。因此，它在最后一年中，便着重于政治进攻，企图用"以华制华"的办法，树立傀儡政权的中央，分裂中国内部，引诱中国当局投降，并企图用"以战养战"的办法，开发中国经济，将战争的担负放在中国人民身上，放在其占领地区。然而由于汪精卫的无耻卖国，使中国军民反更增加对于傀儡政权的鄙弃和愤恨。关于敌占区成的经济开发，日寇虽有它的在华北、华中增加工厂企业和吸收中国资源的计划，并企图以中日合股公司来引诱中国资产者做它助手，以便共同榨压中国的劳苦人民，但因为在日寇占领区域之中国游击战争的发展和破坏，除掉几个大城市如上海、天津、青岛等外，这些计划也还难于实施，而中国的资产者也常常因此发生踌躇。两年半中，日寇侵入中国十四个省区，在其所包含的九百多县中，因为无中国正规部队及游击队的活动而能完全实施敌伪政权的只一百多县。最近一年多，日寇也曾用其在华百分之八十以上的兵力（约二十七八个师团）担任其占领区的保卫和"扫荡"，但结果，只在某些中国部队不熟练于游击战术或与人民关系还不好的情况下，才收到一些"扫荡"的效果。同样，日货的倾销，伪币的滥发及其对我金融的捣乱，也正因为中国某些地区的封锁不严，抵制不力，尤其因为买办奸商的无耻投机，才给了日本帝国主义以某些收获。

由于上述两方面的原因，日本帝国主义便更加懂得：如果战争继续延长和单靠军事力量解决中国问题，它会有一天在中国完全破产，并促成其国内矛盾的爆发。所以日本帝国主义就更加急于要结束战争。

同样，由于上述的原因，日本帝国主义也更加懂得：如果不从中国抗战营垒内部，布置内奸，制造分裂，则它单凭从外面实施政治进攻，也还难于收效。所以日本帝国主义就更加要用全力来破坏中国人民的抗战力量和引诱中国当局投降。

还有，由于欧战的发生，日本帝国主义希望利用其他帝国主义忙于欧战的机会，加紧巩固其在华掠夺的所得，并希望能从欧战中获取利益，以补偿它在侵华战争中的损失。所以日本帝国主义也很希望能从速诱成中国当局的投降，以便造成其征服中国称霸东亚之更优越的条件。

因此，不管日本统治阶级的内阁更换多少次，他们内部的矛盾多么大，但他们这一引诱中国当局投降迅速结束侵华战争的方针，是确定的了。并且这一方针，又正是与其压制本国人民军队的反战运动密切的联系着的。

四

第三，主要的更要从中国自己方面来看这种投降危险的来源。

在中国内部，抗战的困难不是没有的，然而并非不能克服的困难。一部分人在长期战争中感到疲倦，这也是事实。然而广大人民及前线军队却正前仆后继的奋勇争先走上民族革命的战场。可是正因为这个缘故，中国地主资产阶级的一部分就深怕中国人民之民族解放斗争的高涨，宁愿在困难面前投降，去与日寇勾结，企图从中日合股公司中乞得榨压中国劳动人民的利润残余，并企图从欧战得利中也能分得一些赃物。

这些人，一部分已直接的去向日寇投降，去与汪精卫及其他汉奸勾搭一起，这种公开的出卖，是中国人民所能看见的危险，是汪精卫一流的投降分子。但现在最大的危险尚不仅此，还有更严重的是今天尚暗藏在抗战营垒中的投降妥协分子，他们口头上说要实行孙中山先生的三民主义，而实际上则准备对日本帝国主义投降，分裂民族统一战线，破坏人民的抗战力量，以放弃中华民族对于日本帝国主义之最坚决的、最一致的斗争。

这种危险主要的是反映在国民党中。投降分子与国民党的抗战领袖及其群众是有严重区别的，与广大人民及抗战军队是对立的。今天的中国人民及抗战军队主张抗战到底，他们却希望对日妥协，或者经过帝国主义列强的仲裁，尤其是希望美帝国主义出头仲裁。今天的中国人民及抗战军队要求政治进步，他们却压制进步的抗战组织、抗战言论、抗战分子，尤其是共产党。今天的中国人民及抗战军队要求全国抗战军队的团结和一致，他们却挑拨抗战军队内讧，阴谋叛变。今天的中国人民及抗战军队欢迎中共领导的陕甘宁边区实行了民主制度，最广大的动员了人民的抗战力量以推动全国的进步，他们却主张取消边区，并给以军事压迫。今天的中国人民及抗战军队欢迎中共领导的八络军、新四军在敌后坚持抗战，创造了许多游击根据地，他们却主张削弱八路军、新四军，取消游击区域，并进行武装冲突。今天的中国人民及抗战军队拥护国共及其他抗日党派合作，拥护统一战线，他们却不承认国共及其他抗日党派合作，并破坏统一战线。

这一切抗战营垒中的投降分子、顽固分子，是在企图以自己的造谣污蔑，陷害全国进步分子，陷害中共及其领导的边区和军队，而展开武装的冲突，以分裂中国抗战的力量。这样，正是铺设投降的道路，正是适应日寇及其他帝国主义列强的要求，而造成目前投降危险的主要根源。

五

根据以上的分析，中华民族处在今天的严重时机，只能是继续抗战，决没有和平可言。今天中日间所讲的和平，不管是汪精卫所解释的、或者是抗战营垒中投降妥协分子所活动的，或者是幻想经过其他帝国主义列强的仲裁得来的，只能是对于日本帝国主义的投降，不能有其他的意义。

和平

就是投降，乃是今天中国抗战中的真理。投降必然引导中华民族走上不可挽救的悲惨结局。

汪精卫所解释的和平，就是完全接受日本帝国主义的要求。实质呢？日本帝国主义要建立的东亚新秩序，就是奴役中国人民的秩序。日本帝国主义所说的东亚协同体，就是要把中国完全变成它的殖民地。日本帝国主义所要实现的中日"满"经济提携，就是要在殖民地化中国的基础上，繁荣起日本帝国。日本帝国主义所高喊的共同防共，是要分散中国的抗战力量，便于它宰割中国人民。显然，在这些基础上所接受的和平，只能是亡国的和平，中国人民所万万不能接受的和平。

抗战营垒中投降妥协分子所活动的和平，就是一方面在中国抗战内部打击抗战力量，并对抗战怠工；另一方面则解释日本帝国主义既然希望迅速结束战争，必能使它适可而止，以求得彼此和平。结果呢？我们知道：打击抗战力量，就是要压制中国进步力量，消灭八路军、新四军及边区；对抗战怠工，就是要使中国抗战的有生力量不能源源增长，一切抗战的资源不能拿来利用，在日寇占领区域的人民抗日游击运动，不能得到中国政府的支持。这样，正是解除中国自己的抗战武装，而适应日本帝国主义所要求的和平。同时，我们也知道：所谓适可而止的和平，就是要让日本帝国主义拿稳了它在中国的占领区域，以便它好从这些最富饶的区域取得中国的人力资源的补偿，并且还可利用这些补偿，一方面继续征服全中国，另一方面好向亚洲的南部发展。最后，日本帝国主义还可利用中国人力资源去做它在将来帝国主义战争中的牺牲品。显然，这样的和平，不仅要今天的中国人民变成服服贴贴的奴隶、牛马和炮灰，而且还要中国人民的子子孙孙都变成服服贴贴的奴隶、牛马和炮灰。

还有，对于其他帝国主义列强出头仲裁的幻想，以为经过它们可得到日本帝国主义让步的和平。实际呢？在现在西欧战争的条件下，英法美帝国主义不仅难于从日寇方面得到多少让步，即使得到什么让步，也是对英法美帝国主义的利益让步。现在美帝国主义正以要求日本帝国主义开放中国扬子江航路及赔偿美国在日本侵华战争中的损失，做为日美商务谈判的交换条件，这就可以看出美帝国主义的目的是在哪里了。并且，在今天，日本帝国主义不仅不会对中国有任何实际上的让步，即使有一些名义上的让步，也是为的引诱中国当局，麻痹中国人民，从思想上解除中国人民的抗日武装，以便其分裂中国和继续征服中国。显然，这种幻想的和平，只能加深日本帝国主义宰相中国和其他帝国主义列强牺牲中国的危险。

这一切的和平，在中国的广大人民及抗战军队眼中看来，都是投降。中国的广大人民及抗战军队，决不容许把中国变成日本帝国主义的殖民地，决不容许把自己及自己的子子孙孙变成日本帝国主义的奴隶牛马，决不容许投降妥协分子出卖中国，决不容许其他帝国主义列强牺牲中国。中国的广大人民及抗战军队懂得：要取得中国人民的真正和平，只有把抗战进行到底，把日本帝国主义强盗赶出中国去。汪精卫式的投降，已经被全中国人民及抗战军队所反对所唾弃了。不管今后任何人主动投降，采取任何新的方式投降，中国人民及抗战军队总要继续反对他们、唾弃他们的。即使日本帝国主义在中国抗战营垒中经过投降妥协分子，打击抗战力量，分裂抗战中国的阴谋，万一得到某些成功，中国的人民群众及抗日党派，武装力量，也一定要继续抗战下去的。不达到胜利的目的决不休止的。

六

并且，目前中日战争的形势，正处在这样的情形，就是谁能够将战争坚持下去，谁就能够取得战争中的优势，以便于争取最后胜利。中国在战争初期，虽然失地很多，损失很大，但许多条件，却利于持久战；即使在现在，这些条件，也大多存在，并且还有新的条件的增加。

首先，中国是以人多优越于日本的。日本帝国主义动员了超过它预定计划四倍以上的兵力（三十三个--三十七个步兵师团）进行侵华战争，中国却以三倍于它的兵力抵抗它。战争近三年，中国军队伤亡的数目，虽然超过日本，但中国抗战的主力军，却仍然保存，抗战的情绪却仍然高涨。中国土地的损失，虽使中国人力的动员受到影响，但现在中央政府能够实施动员计划的区域还包含二万万七千七百万人口，过去的动员还只达到中国人口百分之一，即在敌人占领区域，中国游击部队也还能进行动员，这证明中国人民对于抗战军队的补充，还有着无限的可能。

次之，中国是以地大优越于日本的。日本帝国主义虽占了中国许多领土，但直到今天，也还是点与线的占领，即是说，它只占了一些城市，靠着铁路、公路、航线来联络，更靠着庞大的军队来保护，此外广大的乡村，仍然为中国的抗战军队及人民游击队所占有所活动。所以中国抗战的战场，不仅在正面，而且在敌后。同时因为中国的地形复杂，所以日寇近代化的兵力便难于到处施展，而中国军队运动战、游击战的优点，却能到处发扬。

再次，中国的资源也是优越于日本的。日本帝国主义在其国内资源动员方面，已感到了相当枯竭。而中国则正相反，许多能够制胜日本的资源，还没有动员起来。中国虽失去许多工业中心和铁路矿山，中国的海口虽尽被日寇占领或封锁，并且日寇还正在继续进攻，企图达到它从广西切断西南、从宁夏切断西北之中国对外交通的计划，但是，中国军队最低限度的需要，中国现在是能够生产能够供给的。中国的粮食不缺，去年还是丰收。中国的棉花、羊毛是有的，困难在织造不够。中国的通货膨胀是在敌占的沿海口岸，而内地却是货币不够周转。中国国防工业的资源也是具有的。

还有，更主要的中国人民所进行的战争是民族解放和保卫祖国的战争，是抵抗日本强盗侵入中国领土的战争，所以它最能动员广大的人民。在战争中，英勇的中国人民，特别是工农群众，几百万人的补充到军队中去，千百万群众为参加战地服务，担任临时工役，在后方增加生产，动员征募，这都是中华民族的光荣。尤其是在日寇占领区域，有无数的中国人民游击队。他们在敌后，成为一种武装的统一战线，在他们中间及其周围，聚集着不分党派、不分阶级、不分民族，只要是抗日的老少男女，一致的进行反对日寇的斗争。他们不仅与敌人作战，担任牵制、消耗和破坏敌人的任务，而且还与敌人进行政治的、经济的斗争，摧毁敌伪政权，封锁敌人经济，为的是要打破敌人利用中国人力资源的企图。

另一方面，日寇所进行的战争，却是帝国主义侵入他人领土的掠夺战争。成百万的中国劳苦人民和青年学生，受着日寇的压迫，在各地流亡，失业失学，成千成万在战区、在后方的中国人民，已经在日寇炮火炸弹之下做了牺牲，这些都不断在增加着中国人民对于日本帝国主义的仇恨。同时，日本人民特别是在士兵中，由厌战心理已渐渐生长起反战情绪，开始了小部分的反战活动，最近日寇枪杀其反战士兵甚至其下级军官的事，已在广东山西等许多战线发生。因此，日寇军队在中国作战，外部既已孤立，内部又有隐忧，这正是日本帝国主义将要发展起来的致命伤。

最后，中国人民在自己方面还有伟大的苏联人民和全世界进步力量的同情和援助，而日本帝国主义方面则恰恰相反。尤其是欧战发生，它已从远东吸引去了英法美帝国主兴的主要力量，这更便于中国人民依靠自力更生，走向彻底的民族解放。并且这一帝国主义战争，必然要引起这些国家内反战运动和工人运动的高涨，引起殖民地的民族解放运动的高涨。中国的民族革命战争，正是与这些革命运动有着密切的世界联系。

以上这一切优越条件，再加上一个时间的延长，便会更加有利于中国而不利于日本帝国主义。战争每一月每一季的持续，对于日寇是一天天陷入难境，对于中国是正好拿来增强自己的各种优越条件。

七

所以在目前严重的转变的时机中，克服投降危险，坚持抗战继续和争取抗战胜利，是全中国人民的中心任务。

全中国人民及抗战军队，应该警觉起来，为着克服这种投降危险，并约制这种危险的发展而斗争。投降分子在中国散布和平空气，我们要揭穿他们在这种和平空气下所进行的投降阴谋。投降分子故意扩大宣传中国在抗战中的弱点，我们要发扬那些有利于中国持久战的优越条件，以坚强政府和人民继续抗战的信心。投降分子对抗战怠工，我们要暴露他们的阴谋，以抗战的胜利行动来打击他们。投降分子与顽固分子合力压制中国的进步，我们要团结全国进步的力量反对他们的倒退。投降分子结合顽固分子向中共及其军队和边区进攻，我们要站在全中国人民的利益上，反对他们破坏民族抗战中最坚决的力量，停止他们这种进攻。投降分子正在企图从抗战营垒中，分裂统一战线，以扫清达到投降的道路，我们要孤立这些投降分子，排除这些投降分子，以巩固抗战营垒，使抗战能够继续，能更有利于争取最后胜利。

全中国人民及抗战军队，应该更广泛的动员起来，为着继续抵抗日本帝国主义的侵略而战斗到底。中国的军队在其保卫祖国的战争中，已经写下了空前的英勇战绩，最近一年，在湖北、在河北、在山西、在长沙附近，最后有广东、广西都曾经击退了敌人的战役进攻，取得了我们局部反攻的胜利。现在我们要展开这种胜利到各个战线上去。我们要改善动员工作，使广大的中国人民能够更多的到军队中去，参加前线服务，参加游击运动，尽他们的一切力量，用他们一切所能做到的办法，去进行反对日寇的斗争。正面的中国军队，要能够更加坚强起来，阻止敌人的前进，并取得更多的战役反攻的胜利。敌区的中国游击部队，要能够更好的配合正规部队作战，更密切的结合战地广大居民，更多的得到中央政府的帮助，以便更有力的击破敌人的"扫荡"，吸引和分散敌人的主力，使敌人难以继续深入中国内地。同时要反对一切破坏游击队的阴谋。后方的中国预备队，要能够更加紧于近代化的装备和训练，以便能源温不绝的补充前线，加强前线，并准备将来的反攻力量。这一切动员，都为着战斗力的提高，都为着中国抗战的继续发展，同时，也正是给投降阴谋分子以实际的打击。

全中国人民及抗战军队，应该把注意力放在敌人占领区域中去。在那里，我们不仅要发展游击战争，并且要破坏日寇"以华制华"和"以战养战"的政策。在那里，军事的行动要与政治的、经济的斗争配合起来。我们要破坏敌伪政权，要揭穿日寇的一切欺骗宣传。我们要破坏敌人在占领区域的开发经济计划，抵制它掠夺中国的资源和向中国倾销日货，破坏它在中国的交通运输和一切军事建设，拒绝使用它的伪币和供给它的食品原料。为着达到这些目的，我们特别要组织起敌人占领区的城市工人、交通工人、矿山工人，广大的乡村农民，以及城市的小资产阶级，他们都是反对日寇斗争的基本群众。为着达到这些目的，我们也要坚决的反对那些与日寇在政治上、经济上合作的汉奸买办。

全中国人民及抗战军队，应该为着便利于抵抗日寇的斗争，要求政府实施一些必要的政治的、经济的改革。我们要求民主，是为的使人民代表能够参预国事，便于动员民众到抗战中来，同样也是为的使抗日的言论集会和团体得到自由保障，而破坏抗战阴谋投降的言论集会和团体得到制裁。我们要求国民大会的民主选举，是为的能够把国民大会变为巩固全国统一和动员全国人民力量以反对日本帝国主义的有力保障。我们要求实施战时财政经济政策，是为的使政府的财政设施不是为着少数财政巨头和贪污分子的利益，而是为着抗战的利益，使政府的经济建设能够向着一个最主要的目标，即是动员全中国一切资源，以最快的速度来建立和发展自己的国防工业。

全中国人民及抗战军队，应该认清，在反对日本帝国主义的斗争中，谁是中国人民最可靠的同盟者和同情者，谁是为着自己的帝国主义目的来利用中国的。我们必须依靠自力更生，反对对于任何帝国主义首先是美帝国主义出头调停中日战争的幻想。我们信赖全世界劳动人民和被压迫民族给予我们的同情和援助。我们更要首先注意到援助日本人民的反战运动，尤其是瓦解日军的工作。日本帝国主义的内在危机是一天一天增长，我们要使中国的抗战与日本人民的反战运动联系起来，我们要使中国人民和军队对于日本军队的宣传和破坏工作与日本军队内部的反战运动配合起来，以便能给日本帝国主义以最后的致命的打击。

最后，我们中国共产党人更坚决相信：为要实现这上述一切任务，就必须依靠于中国抗日统一战线的巩固和发展，首先是中国国民党和共产党的亲密合作。三年来，中国共产党无日不从抗战的利益出发，为着全国的团结而奋斗。中国共产党及其领导的军队的发展，陕甘宁边区的巩固，敌后游击运动的扩大，都是有利于抗战的重大因素。同样，只要与抗战有利，中国共产党也曾采取过而且还要采取一切必须的步骤，以巩固全国的团结。但是必须指出，那种取消边区，削弱八路军、新四军的计策，是与中国人民抗战的利益不相容的，是中国共产党所不能接受的。在今天，投降分子还企图分裂中国民族统一战线，他们却忘记这已为中国人民连国民党的抗战领袖和群众在内所反对的了。在今天，投降分子还企图挑拨起中国抗战军队中自相残杀的战争，他们却忘记这些军队已经不是抗战前的军队了。所以某些顽固分子勾结投降派，曾利用军队挑衅，但结果却受到应有的膺惩。

中国人民今天已经懂得：凡有利于中国抗战的，他们拥护；凡有利于日本帝国主义的，他们反对。中国共产党坚决的站在这一立场上，愿意与国民党的抗战领袖及其群众亲密合作，愿意与中国的抗战军队戮力同心，一致的为着中华民族的解放事业而奋斗到底。

我们相信贤明的国民党的抗战领袖，英勇的中国的抗战军队和我们一样想法。只有团结，才能击破投降分子的阴谋！只有坚持抗战，才能最后的战胜日本帝国主义强盗！

＊原载一九四○年五月三十日出版的延安《解放》杂志第一○八期。

