# 国际形势与中国抗战

中文马克思主义文库 -> 周恩来
国际形势与中国抗战
（一九四○年九月二十九日）

摆在每一个人面前的国际局势与中国抗战的问题，很显然地这是每个人都在考虑着的问题。兄弟个人提出九个问题和答案供献大家参考。第一个，世界往哪个方向走；第二个，中国向哪个方面走；第三个，欧战向哪个方向发展；第四个，日美关系向什么方向发展；第五个，苏联保持什么立场；第六个，中国采取什么立场；第七个，日本能否结束中国事件；第八个，中国有没有严重的困难和妥协投降的危机。最后，第九个答案是中国怎样才能使抗战进步？

关于第一个问题，世界上现在正进行着广泛的战争，在这里一共有三个不同的体系和范畴，一，帝国主义争夺世界霸权的战争体系，由德国和英法的战争发展到德意日与英美的对立。是帝国主义走向削弱和崩溃的过程。二，是进行着解放战争的被压迫民族的革命运动，主要的代表就是中国的抗战。三，是坚持和平政策，站在战争以外的社会主义的苏联，他正日益坚强与壮大着，他增加着摧毁帝国主义体系援助民族解放运动的力量。这三种体系的发展，就是整个世界趋势的答案。

关于第二个问题，中国在目前的局势下，我们主要的斗争目标仍旧是日本帝国主义，我们应该来应付世界大变动的局面，坚持独立的立场。这个不仅要使我们自己得到解放，而且将要引导全世界半数以上的被压迫民族走上民族解放的道路。这就要遵照蒋委员长自力更生，抗战到底的指示。

第三个关于欧战趋势的问题，欧战可分为几个不同的阶段。第一阶段，在战争开始前后，英法帝国主义始终是怀着把自己的战争转变为反苏战争的幻想，但是失败了。接着第二阶段便是持久战与速决战的斗争，在英法方面，那时有两套法宝以争取持久，一是扩大战争，二是争取与国；而在德国方面的两个法宝则是，一是闪电战术，二是各个击破，以求速战速决。但这双方的法宝都遭遇了失败，在法国屈服〔１〕，近卫〔２〕登台，美国积极支持英国特别是德国攻英不甚顺利以后，德国的政策显然要利用日本在远东牵制英美，英美也更需要站在一起，因此，形成现在德意日和英美两大帝国主义阵线的对立。这说明帝国主义战争必然要持久下去，扩大下去。也就是全世界人民遭受的灾害将更大，人类文明的损害必要多。

第四个关于日美关系发展的前途问题，应强调自力更生和利用帝国主义间前矛盾。不应对任何帝国主义外援存着幻想，但亦不应抱那种忽视利用国际有利于中国的每一个变化的态度。日寇在其解决中国问题的迷梦幻灭以后，日寇不得不更积极南进，以求解决国内矛盾，和国防上的资源供给，同时也因为德国现在局势的需要，于是订立了德意日的三国同盟〔３〕，这总是拖日寇下南洋并且主要的是防美制美的一着，但日美矛盾尖锐的发展并不一定急转直下，立刻发生大冲突，他们还尽可以走着曲折的道路。但这种矛盾发展的前途，终于会走上冲突的道路的。

关于第五个问题，首先应指出，苏联为了要脱离帝国主义战争的漩涡，为了防止反苏阴谋的爆发，为了要巩固社会主义国家的力量，他是坚持着和平中立政策的。但援助被压迫民族的革命运动和善邻友好的政策是一个和平政策的两面，而且援助中国更是由其革命政策出发的。同时，苏联对美日的冲突和中日战争的看法是完全两样的，他对美日冲突的态度显然是中立的，而对中日战争是同情中国，因此他一定能不断地给我们以援助。

第六个问题是中国自己在目前应采取的立场。一、如上面所说，必须坚持最高统帅的自力更生，抗战到底的主张，对日美冲突不要幻想。二、应利用日美冲突反对日本，要坚持我们抗战立场，不要使抗战变质，甚至成为帝国主义战争的工具。对美国二千五百万的借款，我们诚然感奋，但这是三千万钨矿换来的，我们熟知美国的朋友张彭春先生就说过："英美对中国的帮助是使我们吃不饱也饿不死！"同时更要求把这笔钱完全用到抗战上去，不要再加在那存在美国银行的一万七千万美金上去！三、对德意态度，在欧战上我们是中立的，但在太平洋上，他们如以政治的经济的军事的力量支持日寇，我们则坚持反对。四、对苏联我们应祛除疑虑，如果日美冲突更大，苏联是不是还会帮助中国？只要中国进步，是可以的。有人问中国会不会全像波罗的海几个国家的命运，归并给苏联？关于这，这是没出息的想法。

第七个问题"日本帝国主义能不能结束侵华战争"？这是不可能的，这原因在于我们能够不无端悲观，不过分乐观。我们要紧紧地把住现实，克服一切困难。在近卫登台后，日寇的企图，是想结束中国事变，以便抽身南进。他的企图最可以有三个：即是一，如果我们屈服，他就抽身南进，否则二，截断西南交通增加抗战困难，以便分兵南进，三，如果上面两个都不可能，而时间又迫不及待，他就只能不顾一切，放手南进了。只要我们能够坚持抗战争取时间延长下去，日寇终会追不及待的放手前进的。只要我们撑得下去，日本就拖不下去。

关于第八个问题，中国有没有投降的危险和空前的困难呢？投降的危机是有的，但这是局部的，在全国人民的坚持和最高统帅的英明领导下，可以保证我们不会投降。同时因为西南交通不是完全由我们来决定，必须要看英美有没有决心。所以我们可能遭受到这种困难，但如果我们能够忘掉北平，天津，上海的糜烂的生活，想起我们几十年前老祖宗的生活，我们现在并不苦。

最后一个问题是怎样才能使抗战进步？抗战本身就是推动进步的基本力量。在这里关于兵员的补充，粮米的筹储，金融的调节等等的进步方法，到了紧急的关头，将要为各方面逐渐采取的。所以坚持抗战就是解决进步问题的前提。比方团结问题有人认为进步太慢，但中日战争的发展本来就是慢慢的。我们不必性急，在患难中一定能够抱头痛哭，也就能够看出谁是真正的朋友。只要全国的人民一致要求团结，齐心对付敌人，团结是没有问题的，胜利一定是我们的！

＊这是应重庆中华职业学校邀请发表的时事演说节录。演说原定在实验剧场举行，因听众过分拥挤，临时改在巴蜀小学广场上进行。参加听讲的各界群众约有三千人左右。原载一九四○年九月三十日重庆《新华日报》。

注释

〔１〕一九四○年六月，法用斯德国侵占巴黎，法国贝当政府投降，七月，日迁都法国中南部城市维希，组织维希傀儡政府。赖伐尔，佛兰亭、达尔朗等先后主持维希政府。一九四八年八月，在反法西斯联盟国家军队和法国游击队的联合打击下，宣告垮台。

〔２〕近卫，参见本书《二期抗战的重心》一文注〔１〕。

〔３〕三国同盟，即德意日三国同盟条约又称《柏林公约》。第二次世界大战期间，德、意日三个法西斯国家为扩大侵略战争，于一九四○年九月二十七日在柏林签订。主要内容是：日本承认德、意在欧洲建立新秩序的统治权；德、意承认日本在"大东亚"建立新秩序的统治权；缔约国以一切政治、经济和军事手段互相援助。条约标志了德意日三国轴心军事同盟的正式形成。后匈牙利、罗马尼亚、斯洛伐克、保加利亚、芬兰、西班牙、泰国以及克罗地亚，伪满洲国和汪精卫傀儡政权也相继加入这一条约。第二次世界大战中，德、意、日失败，条约遂亦废除。

