# 答《大公报》社论——致张季鸾、王芸生

中文马克思主义文库 -> 周恩来
答《大公报》社论——致张季鸾、王芸生
（一九四一年五月二十一日）


季鸾芸生两先生：

　　读贵报今日社论--《为晋南战事〔２〕作一种呼吁》，爱国之情，溢于言表，矧在当事，能不感奋！惟贵报所引传说，既泰半为敌人谣言，一部又为《华盛顿明星报》之毫无根据的社评，不仅贵报"不愿相信"，即全国同胞亦皆不能置信。盖美国虽为助我国家，但美国报纸论断通信社消息，却不能尽据为信，例如华盛顿十九日合众电，竟称"据拥护政府最力之参议员多玛斯对台众社记者谈称......彼素即主张以逐渐之方法调解中日战事"，我们能因此便信美国政府已接受日本之和平提议么？况中共与汪逆〔３〕，久成"汉贼不两立"之势，国内某小部分人或可与汪逆重谈合作，中共及绝大多数之中国军民，吾敢断言，虽战至死，亦决不会与汪逆同流合污，投降日寇。至敌人谣言，则所造者不止一端，即单就晋南战事论，南京二十日同盟电，亦曾说："当晋南、豫北战事发生之前，胡宗南〔４〕为奉命包围红（？）军计，曾自晋南抽出所部五师调至陕甘宁三省......以致晋南渝（？）军实力大减。"我想贵报对于此种说法，当同样"不愿相信"。

　　再贵报所引事实，一则谓："十八集团军集中晋北，迄今尚未与友军协同作战。"再则谓："我们相信统帅部必然已有命令，要十八集团军参加战斗。"但我可负责敬告贵报，贵报所据之事实，并非事实。在贵报社论发表一周前，晋南白晋公路一段即为第十八集团军部队袭占，停止通车；其它地区战事正在发展，只因远在敌后，电讯联络困难，此间遂不得按时报道，而中枢及前线旬余军事磋商，与夫配合作战之计划，皆因军机所限，既不便且不得公诸报端，亦不宜在此函告，于是惯于造谣者流，曾公开向人指摘第十八集团军拒绝与友军配合作战。我曾为此事一再向中枢请求更正，不意市虎之言，竟亦影响于贵报，当自承同业联络之差。惟环境限人，贤者当能谅我等处境之苦。

　　最后，贵报更寄其希望谓："在国家民族的大义名分之下，十八集团军应该立即参加晋南战役；在其向所服膺的团结抗战精神之下，十八集团军更应该立即赴援中条山。"贵报的热忱，我们感奋，贵报的热望，我们永远不会辜负。我们一向主张团结抗战，而且永远实践团结抗战。去年华北百团大战〔５〕，战中未得到任何配合，战后未得到任何补充，虽中外电讯竞传捷音，贵报备致奖誉，而犹为人诬为虚构战绩，然我们并不因此抱怨。今年皖南事变〔６〕后，正当着敌人从信阳出击我友军东进之侧后，而李长江〔７〕又适于此际叛变于苏北，我们在苏北、皖北的部队，决没有丝毫放松与友军配合打敌，并且还追击了叛军李长江，这也证明我们并不是抱怨者。今年二三月日寇在华北分区扫荡，由五台而太行而冀南而山东，我们决没有丝毫放弃华北抗战的根据。尽管十八集团军饷弹俱断，尽管无任何友军可以配合，尽管有人造谣说十八集团军已撤回陕北，然事实胜于雄辩，十八集团军终于击破了敌人扫荡。虽弹药越打越少，但我们更不会以此抱怨别人。并且，也不如敌人谣传十八集团军主力是以中条山为中心（自去年漳河划线〔８〕以来，我们严遵军令，中条山并无十八集团军一兵一卒），而是远处在敌人重围中的。不过我们可负责向贵报及全国军民同胞声明：只要和日寇打仗，十八集团军永远不会放弃配合友军作战的任务，并且会给敌人以致命的打击的。同时，十八集团军作战地界，奉命不与友军混杂，免致引起误会。我们现在仍守漳河之线，未入林县一步，犹为敌人故意挑拨，说十八集团军袭击林县某总司令部队，而此地亦有人据此为言者，想见情况之杂。

　　诚然，"山西是北方的高原，有山西可以控制北方数省，中条山是山西的锁钥......"但山西高原并非仅限于中条山，管涔山可以俯瞰塞外，五台山可以连接冀察，太行山可以东出河北平原，吕梁山既可屏障大河以西又可配合太岳山，控制汾河流域。临汾失守以后，不仅因中条山留有中央大军，握此北方锁钥，且因山西所有高原，都控制在我军手中，方使敌寇三年多屡试渡河，屡遭失败。尤其因二十七年春晋东南反敌扫荡一战〔９〕，早奠定了中条山锁钥之基。回想彼时各军协同作战之盛，诚愿能复见于今日。

　　敌所欲者我不为，敌所不欲者我为之。四五年来，常持此语自励励人。今敌欲于积极准备南进之际，先给我以重击，并以封锁各方困我。力不足则辅之以挑拨流言，和平空气。我虑友邦人士不察，易中敌谣，故曾向美国通讯社作负责声明，已蒙其十九日在上海广播，不图今日在此复须作又一次声明。我信贵报此文是善意的督责，但事实不容抹杀，贵报当能一本大公，将此信公诸读者，使贵报的希望得到回应，敌人的谣言从此揭穿。我欲言者虽未尽万一，但个中况味，亦雅不欲再公之笔端，为敌人造挑拨资料。惟信不久战况揭晓，捷报传来，当必较千言万语为能作更有力的证明。匆匆书此。敬颂

　　撰安！不一。

　　周恩来谨启

　　五月二十一日夜

　　＊原载《周恩来书信选集》。



　　注释：

　　〔１〕张季鸾（一八八八～一九四一），原籍陕西榆林，生于山东邹平。当时任《大公报》总编辑。

　　王芸生〔一九○一～一九八○），河北静海（今属天津市）人。当时任《大公报》重庆版总编辑。

　　〔２〕一九四一年五月，日军在山西省西南部中条山地区发动进攻，后国民党政府军溃退，日军随即占领中条山地区。

　　〔３〕汪逆，指汪精卫。参见本书《二期抗战的重心》一文注〔２〕。

　　〔４〕胡宗南，当时任国民党政府军第三十四集团军总司令。

　　〔５〕百团大战是抗日战争时期八路军在华北敌后对日本侵略军发动的一次大规模的战役。一九四○年八月二十日至十二月五日，八路军出动一百多个团四十万兵力，在广大民兵和群众的配合下，向华北敌后主要的交通线发动攻击，并配合各根据地军民进行反"扫荡"作战。这次战役持续三个半月，进行大小战斗一千八百多次，攻克敌人据点二千九百多个，歼灭日、伪军四万六千多人。

　　〔６〕皖南事变，参见本书《皖南事变题词》一文注〔１〕。

　　〔７〕李长江，原是国民党政府军鲁苏皖边游击总指挥部副总指挥。一九四一年初率部投降日本侵略者，随即被汪精卫伪政权委任为第二集团军总司令。不久，其主力被新四军击垮。

　　〔８〕一九四○年三月，在粉碎国民党发动的第一次反共高潮之后，中共中央为争取国民党蒋介石继续抗日，命令第十八集团军总部与第一战区司令长官卫立煌谈判。三月中旬，双方议定沿漳河以临（汾）屯（留）公路和长治、平顺、磁县之线为界，该线以南为国民党政府军驻区，该线以北为第十八集团军驻区。这就是漳河划线。

　　〔９〕指一九三八年四月晋东南军民粉碎日军"九路围攻"。一九三八年四月初，日军以三万金人的兵力，分九路向晋东南地区之八路军，山西新军（决死队）等进行围攻。这一地区的军民与日军展开坚决的斗争，至二十七日，共消灭日军四千余人，收复辽县、黎城等十八座县城，彻底粉碎敌之围攻。



