# 论目前战局

中文马克思主义文库 -> 周恩来
论目前战局
（一九四一年五月二十五日）

目前帝国主义战争正向着扩大和持久的道路着着迈进。战争的范围正由欧洲非洲发展到亚洲，由地中海大西洋发展到太平洋。战争的时间，在今年春季后的整个时期中，将充满着激烈的决斗，并且会继续下去。

目前战况，正在地中海和地中海沿岸向前发展，大西洋中的封锁战与反封锁战亦日益激化。虽然最后的决战还没到来，最后的胜负谁属，抑或两败俱伤，都还未定，但这种空前的屠杀和灾害，已经降落到和将要降落到世界所有爱好和平的人民和被压迫民族的身上。而遭受屠杀灾害的世界和平人民和被压迫民族也正在发展着和将要发展着反抗运动、革命酝酿乃至革命战争。只有苏联是屹然站在这个战争烽火之外，坚持其和平中立政策，建设其伟大社会主义，并给国外革命运动和革命战争以同情和援助。但同时苏联仍然处在世界资本主义包围之中，他不能不严重的提防着"种种惊人巨变"，以阻止"意外事件"的发生。

帝国主义战争自去年法国降德〔１〕以后，显然已分成两个集团。在三国同盟〔２〕方面，德国是主角，意大利是配角，日寇则在太平洋上发挥其半独立性的助威作用。在英美集团方面，美国是跟在英国后边，一步一步的进入实际参战。德意日是要先打垮英国，英美则是先对德，后对日，故目前战事重心在大西洋，并非太平洋。纳粹德国的战略企图有两点：一点是切断苏伊士，封锁地中海，使大英帝国的殖民地带解体；一点是封锁北大西洋，将英伦三岛困住，然后一举而在三岛登陆。英国政府的战略企图也有两点：一点是扩大战场，拖长时间，消耗和分散德国兵力；一点是尽力拖住美国，争取美国直接参战。这两方面战略斗争，在现在，在将来，各有他们的成功，也各有他们的失败。德国可能将苏伊士切断，地中海封锁，并且可能在北大西洋使英国的海上输入一天天减少，但是他的后果，将是时间的拖长，兵力的消耗和分散，美国的直接参战，德国的不利，正是英国的利之所在。但是苏伊士的切断，地中海的封锁，英国将遭受无可补偿的损失，而争取美国直接参战，英国必要付出难以收回的巨大代价，所以将来的结局，不论胜负谁属，纳粹德国所侵占的弱小民族国家及殖民地半殖民地，决难长治久安，而大英帝国的海上霸权和世界统治，即在美国直接参战之后，亦难维持原状。因之，美德胜负之外，还有个两败俱伤的前途，而引起的将是这些国家内的和平运动和革命酝酿，以及被压迫民族国家的独立解放运动。这一前途，是今天许多人所不愿承认和不敢设想的。

美国在这个局面的发展中，他所争取的是如何有利的进入直接参战，多多的接受英国的利益，而又不致使英国倒台，这是他考虑的条件之一。使德国消耗得更多一些，美国国防工业生产得更充足一些，这是他考虑的条件之二。推迟太平洋上的日美冲突，避开两洋作战，这是他考虑的条件之三，最好能挑动起苏德冲突，使苏联代他们火中取栗，这是他考虑的条件之四。但是客观的局势下不容美国的算盘打得那样精，英国隔洋又叫得那样急，所以美国便由巡逻代替护航，海上自由代替中立法，而一步一步的实际参战了。

有人执拗的说，并且不停止的希望德苏一定会冲突。诚然，德苏的立国制度完全两样，德国的向东发展，有碍于苏联国防利益，但是由于苏联坚持其和平中立政策，由于苏联严重警戒其国家防卫，纳粹德国如果不是改变他的对英政策，便很难设想他今天可以采取这种冒险的两面战争。不过挑拨者终不会停止挑拨，而苏联防止"意外事件"的国防戒备，更不会丝毫松懈罢了。

伴着世界战争的发展，太平洋上的风云也就更加紧张了，但绝对不可忽略的有个条件，始终影响着太平洋上风云的变化。一个条件是中国反抗日本帝国主义的解放战争已经坚持了四年。另一个条件便是英美作战的重心尚在大西洋不在太平洋。如果能推迟太平洋上的冲突，而又能使中国抗战拖住日本，以便其先对德后对日，英美是会不惜任何代价以缓和的，但这两个条件的配合运用，又需要辩证的发展。假使因为缓和对日的冲突而牺牲中国利益，固然可以引起中国抗战的失望和失败，但假使因为援助中国抗战而引起日本更加积极的发动武力南进，这更是英美所顾虑的。所以英国在保住新加坡，美国在推迟太平洋冲突的主要要求下，暂时的对日和缓不是不可能的，不过也不会和去年一样主动的封锁滇缅路〔３〕和承认东亚门罗主义，损害中国利益到那样程度，因为时代不同，去年是三国同盟以前，而现在已经是三国同盟的缔结半年以后了。因之，他们对中国的援助是渐渐增加了，但同时却更希望中国多靠自己的力量拖住日本。假使他们在这上面失望，别的打算也不是不可能的。

日寇呢？他在苏日中立条约〔４〕以后，正利用各方对这个条约的猜疑，以及反映他统治内部的矛盾，进行这样的政策。首先是积极的准备武力南进。次之，是加紧对中国的两面政策，一方面展开军事进攻，企图封锁中国，另一方面散布挑拨谣言和平空气，企图分化中国，以达其迅速解决中国事件的目的。再次，对英美荷印〔５〕，也同样展开两面政策，一方面加紧进行外交攻势，另一方面，又采取一些威胁姿态，企图取得英美某些暂时的和缓和让步。最后，要看希特勒〔６〕的作战结果如何来决定日本是否发动武力南进，而其对象，又在英不在美。日寇这些政策的发展和配合，他必然以封锁中国和取得南洋的经济利益为目前中心，因为中国如果真被他封锁住，则英美的援助，便要客观上受到阻碍，而南洋经济利益的取得，在日本也可暂时的和缓其武力南进。等到苏伊士切断，地中海封锁一旦成功，日本仍然可以图穷而匕首见，发动军事南进。到那时，英国亦仍然被迫得要应战，而美国至少也不得不实行经济封锁和以军舰租英作战。这在我们看来，当然要认英美目前的暂时和缓政策是多余的事了，因为太平洋上的冲突是迟早不可避免的，但在英美政府主观看来，他们不能听任地中海失败，而且要用全力来转变目前局势，所以暂时和缓太平洋上的冲突，也是他们政策的当然逻辑。

最后，在这个世界的战局中，中国的抗战是坚持着自己的民族解放战争的立场，反抗日本帝国主义的侵略。所以我们对于战争的政策，是独立自主，决不介入和附属于世界帝国主义的争夺战争，而放弃我们民族独立自由的立场的，但这决不能解释为我们不去运用帝国主义中间的矛盾，尤其不能解释为我们不去运用英美对日的对立和可能冲突，这犹之我们讲自力更生并不等于取消争取外援一样。但必须弄清主从，独立自主和自力更生是我们抗战的基本国策，运用友邦对日矛盾及争取外援，是服从于基本国策的对外政策。只要抗战的基本国策不动摇，即使在某种可能和战争必要上，在日寇的战争火焰已经侵入别国领土，甚至是英美的殖民地时，一定战场上的战争配合行动是许可的，而这其间并不发生战争的变质问题。如果放弃我们独立自主的立场，即使没有一定战场上的战争的配合行动，也依然得不到民族的彻底解放。至于目前战局，我们更不应该寄其希望和等待太平洋上的冲突，这不仅不合于目前战局发展的实际，而且对于动员英美人民援助中国抗战，也成为一种不合理的想头。

我们现在只有号召全国军民，坚持独立自主的抗战，用民主和团结的力量，克服我们当前以及将要来到的更大困难，击破敌人的封锁和分化，以准备我们的反攻。拿我们这样自信的和坚决的抗战方针，来争取外援，适当的运用外援，使日寇动摇于灭华与南进之间永远得不到出路，最后葬送于帝国主义大战火焰之中。这些，便是我们对于目前战局应有的认识和态度。

＊这是为重庆《新华日报》写的代论。载同日该报。

注释：

〔１〕法国降德，参见本书《国际形势与中国抗战》一文注〔１〕。

〔２〕三国同盟，参见本书《国际形势与中国抗战》一文注〔３〕。

〔３〕太平洋战争爆发初期，缅甸是东南亚唯一未被占领的国家。从仰光到昆明的滇缅公路是美国向中国国民党政府运输战争物资的唯一陆上通道。滇缅公路在我国境内从昆明经楚雄、下关、保山、潞西到畹町，长九百五十八公里，一九三八年全线通车。

〔４〕一九四一年四月十三日，苏日双方代表在莫斯科签订《苏日中立条约》。一九四五年四月五日，苏联政府发表声明废除这一条约。

〔５〕印度尼西亚在独立前于十六世纪末遭荷兰殖民者侵入，一八○○年正式设立殖民政府，称荷属东印度，简称荷印。一九四二年荷印被日军占领。日本投降后，一九四五年八月十七日印度尼西亚宣布独立。一九五○年印度尼西亚取消联邦制，成立统一的印度尼西亚共和国。

〔６〕希特勒（一八八九～一九四五），德国法西斯头子。一九一三年参加德意志工人党（次年改为国社党），其后成为该党党魁。一九三三年在德国垄断资产阶级支持下出任总理，次年总统兴登堡死后自称国家元首，实行法西斯统治，积极扩军备战。一九三九年入侵波兰，挑起第二次世界大战。一九四一年六月大举进攻苏联。一九四五年苏军解放柏林时自杀。

