# 关于中央社发表谈话的事实真相的声明

中文马克思主义文库 -> 周恩来
关于中央社发表谈话的事实真相的声明
（一九四一年六月一日）


　　中央社所发表之谈话，共有三点。前两点皆证明我在五月二十一日夜致大公报函中所举之事实确有根据。惟第三点，即"截至今日止，尚未据报与敌军正式接触"一点，则与事实不符。盖在中条山战事〔１〕发生以后，中枢以作战相同，我即表示抗战到底为我们索志，十八集团军必能协同作战无疑。嗣得十八集团军朱彭总副司令先后电告协同作战决心及配合作战计划，我均呈报最高统帅部，并定由朱彭总副司令向战区长官部直接电陈作战意图及经过。自是以后前方战况紧张，且又远在敌后，其首要之联络为前线，次之则为长官部，我处辗转收得战报如白晋公路之战况，不仅业已呈报统帅部，且已公诸报端（见五月二十三日本报）。根据此点，决不能谓为"尚未据报"。至战报少，更不能谓为"尚未......与敌军正式接触"，因最近一周，单就中央社之洛阳专电，便有六次提及晋东我军或十八集团军作战地区之战况的，而大公报两次西安专电，更证明太行山及晋北我军均在与敌作战。大家均知道太行山晋东晋北无其他部队，同蒲路白晋路正太路平绥路平汉路大部均为十八集团军作战地区，通讯社限于规定不得以作战部队之番号标出，但不能以此便谓无十八集团军在内。再此等电讯发自前方，见闻自更翔实，既经前方军事机关检查于先，又经后方军事机关复审于后，揭诸报端，已历多日，岂能谓为非战报？！且四年来，所有各部队战报，皆赖中央社为之报导，何以独苛求于十八集团军？

　　大公报说得好："我们愿声明，只要有此事实，就满意了，且并不苛求或奢望一定有大的战果。"但我们当然并不以此等战果为满足，我们愿意接受国人善意的督责和更多的希望。我们期待着更大的战果的来临。我敢负责声明：十八集团军是敢于接受敌人回头扫荡的挑战，以求得阻止敌人之冒险渡河的。但同时我却企求国人注意，在我上次致大公报公函发表以后，敌人挑拨的谰言，已停止了，但最近两日却又广播起来了。我们应勉励勿为敌人流言所动，更勿为敌人挑拨所中。我们全中国军民应团结成一个铁拳一样，好击碎敌人的进攻，也击碎敌人的挑拨流言！



　　＊一九四一年五月三十日，中央社发表关于十八集团军"尚未据报与敌军正式接触"的谈话。周恩来针对此项谈话发表事实真相的声明。声明中引用的《中央日报》和《大公报》所发表消息的例证六则从略。本文原载一九四一年六月一日重庆《新华日报》。

　　注释：

　　〔１〕中条山战事，即晋南战役。一九四一年五月，日本侵略军以约十万人的兵力进犯黄河以北位于晋南、豫北的中条山地区。集结在这个地区的国民党军队约十五六万人。这些国民党军队，本来以反共为主要任务，对日军缺乏作战准备，在日军进犯时，大部分采取避战方针。因此，虽然华北各地的八路军主动出击，截断了同蒲路、正太路、平汉路、白晋路等日军的交通线，给国民党军队以积极配合，国民党军仍然全部溃败，在三周之内损失兵力约七万余人，丧失了中条山及附近地区的大片国土。



