# 论时局中的暗流

中文马克思主义文库 -> 周恩来
论时局中的暗流
（一九四一年六月一日）

目前帝国主义战争正走向扩大和持久，英德走向决战，美国一步一步的进入实际参战，日寇则伺机南进，这是世界战争中的主流。

在中国，日寇正展开以封锁中国为中心的军事进攻，我全国军民正坚持团结抗战的国策，准备用自己的力量驱逐日本帝国主义出中国；这是中日战争中的主流。

但在战争主流前进之中，并不是没有暗流或逆流的，暗流不仅是自然界难免的现象，而且是人类政治活动中必不可免的现象。暗流不一定每次都成为巨流，更不一定每次都冲破了或淹没了主流，然而人们必须认识和提防暗流，在中国更须反对暗流，才能使我抗战主流更加汹涌澎湃的前进。

什么是目前战局中的暗流呢？

在西方，英德妥协共同反苏，是世界战争中一股暗流，而赫斯奔英〔１〕，正是这股暗流中的契机。我曾说过，纳粹德国如果不改变他的对英政策，便很难在今天发生对苏战争，然而存着这种希望的人，在英德两方在全世界都还不少。有人说，德国可以采取对英又对苏的两面战争，甚至有人说，纳粹德国可以在两个月之内打到莫斯科，并且有人证明，连统治莫斯科的人选都已内定了。其实这都是烟幕，内心是在希望以德苏战争代替英德战争。不错，赫斯奔英正是揭露了这股暗流，他的行动曾否得到希特勒的默许，这是次要问题，重要的在证明西方和英共同反苏的意见，在纳粹德国已渐渐的增长起来，并且得到了英国一部分人的支持。为什么这种企图和活动在战争扩大的进程中增长起来，很明显的是由于战争愈扩大愈持久，将愈给帝国主义的世界统治带来可怕的后果（这里包含着这些国家的政治经济危机和革命酝酿，被压迫民族国家的独立解放运动以及超然于战争之外的苏联力量的增强）。于是在赫斯奔英后，纳粹德国宣布了他神经失常之后，便无下文，丘吉尔〔２〕曾准备在国会宣布此事经过，以后也杳无消息，甚至罗斯福的炉边闲话〔３〕也曾为他延期。同时苏联由于处在世界资本主义包围之中，而纳粹德国也正在着着东进，影响到苏联的国防利益，所以在最近一两个月，更着重其提防"种种惊人巨变"的动员，由此看来这股暗流的增长与提防这股暗流的动员，是很显然的，然而却不能说这股暗流已经成为巨流。因为摆在德国面前的，地中海的封锁、苏伊士的切断和大西洋的反封锁，已一天天的增加其可能，而对苏战争的把握还在未可知之数，并且苏联的严紧国防更使他无懈可击。两面战争既不可能，希特勒总是向着较易的方面发展。而摆在英国面前的，地中海的危急，近东问题的紧张，大西洋上的运输，都是最现实的问题，稍一不慎便会失利，而且稍一松懈，便会延缓美国直接参战的过程。忽视目前的危急，憧憬未来的幻想，这是现实主义的英国政府所不敢冒险尝试的。因之，在赫斯奔英，英德甚至美国都经过一度摆动之后，克里特岛的争夺战〔４〕，大西洋上的海战都更激烈化起来，胡特号和俾斯麦号都彼此击沉了，李德〔５〕的声明，罗斯福炉边闲话，也终于发表了。

战争仍然循着最直接的战争轨道前进，暗流总是暗流。但必须了解美国是这个问题中的枢纽。如果美国失利更多，美国直接对德开火，日寇又在东方趁火打劫，则帝国主义战争必然更加循着世界的范围扩大和持久下去，如果地中海大西洋的战局照现状僵持下去，日寇对武力南进踌躇，美国仍留有游刃的余地，则暗流的继长增高，也会更加可能。况且资本主义世界总不会忘怀苏联。所以终世界战争之局，暗流总不会停止的，不过战争越扩大持久，苏联的力量越增强，这种暗流的增长，也越发会增加它的困难。

在东方，中日直接妥协的暗流久成过去，而新的一股暗流却在日美的少数人中渐渐的生长起来。他们企图或承认以美国为中介来调解中日战事，这在日本是有它的基础的。中国的坚持抗战，在客观上久已证明日寇很难于独力解决所谓"中日事件"。过去的近卫〔６〕，现在的本多〔７〕及一部分侵华军人，都曾经或仍在想加强对汪逆的扶持，以便从中国得到解决"中日事件"的内应，其实这种前途是会失败的。另一部分日本人包含近卫松冈〔８〕及一部分军阀在内，他们却想配合着军事进攻放出与国民政府直接谈判的和平空气，及分化中国内部的挑拨流言，企图以此来结束"中国事件"；这又必然要遭受中国军民的坚决反对，而得不到任何结果。因此，日本维持现状派中的保守分子即所谓实业界老外交界人士，鉴于上述两种企图都会归于失败，于是便想经过美国来调解中日战事，为着达此目的，更须先和缓日美关系。我们看，在罗斯福炉边闲话发表之后，日本报纸"除少数外，一般均认为罗总统演说内并未提到远东战事，甚有意义"（二十九日同盟电）。中外商业新报竟公开说："苟美国重新考虑实际情势，则日美关系之改进并非不可能"（三十日同盟电）。而前任首届近卫内阁外次之松本忠雄〔９〕更公开说："日美冲突之危机，并非如所想象之紧迫。美国甚有见地不肯向日本挑战，日本也不至向美挑衅。......"（三十日合众电）。且在罗斯福发表谈话以前，所谓日本请美国出面调停中日战争之说，已甚嚣尘上，据十九日合众电也承认："此讯之来源为东京，后在纽约报纸上发表，恐系日本之半官方故意发出，以测验中美两国之态度。"这派人在今天近卫内阁中虽未占若何势力。但他们已渐渐抬头活动，已渐渐成为近卫松冈外交政策运用中之一面，这与运用军部乃至海军系少壮军人向美挑衅的为另一面的，正起着一拉一打的作用。单单日寇这种态度尚不值得我们重视，所可重视的是这种意见在美国的反映，首先反映这种意见的是美国的少数人士，然而却是重要的人士。据十九日合众电："拥护政府最力之参议员多马斯对合众社记者谈称，不论和平条件是否如真理报所载，调解之本身是为有价值之努力。彼又谓，彼素即主张以逐渐之方法调解中日战事。......"合众社并且更进一步说："其他方面......咸认为目前为一九三八年以来调停最有利之机会。"而"芝加哥论坛报华盛顿记者韩宁关于罗斯福炉边闲话之意见，认为罗斯福演说中未提及日本，系对日修好新政策之结果"（卅日同盟电）。这句话牵涉到罗斯福总统了。大公报说得好："本报昨论罗斯福总统的广播演说，以其未提及太平洋情势，也未曾特别提及日本，是在精神上留了罅隙。兹据华盛顿路透社讯，国会某负责人士谓：罗总统演说未提及太平洋问题，系政府根据情报推断，认为日本实业界渐得势，或将压倒军部势力，而减弱依附轴心之程度云云，可见美政府一时似为日本的烟幕所迷。"有了罅隙，日美两国人士中的暗流，便会流了进来。我们很懂得，罗斯福所以留此罅隙，美国所以没有全面对日禁运，全是为的以太平洋舰队一部调往大西洋，以便先对德后对日。然而罅隙愈大，时间愈长，大西洋的战争愈陷于僵局，日美暂时妥协和经过美国调解中日战事的念头便不会不被人想了出来。在中国，也不能说无一响应之人。到那时，东西两暗流便会桴鼓相应。

因此，我们在东方，指出这种暗流，反对这种暗流，是绝对必需的。在实际上，只要德国切断苏伊士封锁地中海的可能一天天的增加，日寇武力南进的准备也会一天天的积极，对美暂时和缓，将成为他最后发动武力南进的烟幕。所以在今天，日寇对中国的进攻，也以封锁中国和摧毁中国军事力量经济基础为中心，而不一定过于深入，这便是他要兼顾南进的准备所致。配合着军事进攻，特别加紧散布挑拨流言和平空气，这又是他动摇中国抗战决心和英美援华信念的另一阴谋。这也就是日寇今天在侵华和南进中所运用的复杂矛盾而又狡猾的两面政策。

敌寇的这种两面政策，东方的这股暗流，我们将它指出，不仅不会动摇我们坚持团结抗战的决心，而且会因为认识他的危险更加坚定我们独立自主的民族解放战争的立场，来揭破敌人的烟幕和阴谋，来争取和稳定友邦对我们援助的信念，以便毫不动摇的走向三民主义新中国的胜利大道。

＊原载一九四一年六月一日重庆《新华日报》。

注释：

〔１〕赫斯是希特勒最亲近的心腹、纳粹党的副领袖、仅次于戈林的第二号接班人。他在一九四一年五月十日晚乘一架战斗机独自飞往苏格兰。他的这一行动在战争进行的整个期间一直是一个谜。一九四五年十月十日英国人把他作为战俘释放，以便他能在纽伦堡受审。他被国际法庭判处无期徒刑，主要由于他神经失常而免受死刑。

〔２〕丘吉尔（一八七四～一九六五），英国首相，保守党领袖。一九三三年希特勒在德国执政后，提出联苏抗德的主张，反对张伯伦推行的绥靖政策，反对签订《慕尼黑协定》。一九四一年六月德军入侵苏联后，立即发表声明援助苏联，后与苏联缔结盟约。一九四六年三月五日在美国发表演说，主张美英联盟对抗苏联，揭开战后"冷战"序幕。一九五一年重任首相后，对苏采取强硬政策。

〔３〕罗斯福的炉边谈话，指第二次世界大战期间美国总统发表的几次广播演说。一九四○年十二月间，美国尚未参战，罗斯福在其白宫屋内的火炉旁，用谈家常的口吻向全国发表了几次广播演说。表示美国愿意成为"民主国家的伟大兵工厂"，向英法等国提供大量军火，这样既支持英法的反法西斯战争，又促进美国经济发展。号召美国人民支持其对外政策。以后被新闻界称为"炉边谈话"。

〔４〕德军入侵克里特岛是第二次世界大战中巴尔干战局的最后一个战役。一九四一年四月二十五日，希特勒下达了在克里特岛实施空降的命令。克里特岛的守军共约四万四千人，其中英联邦军队三万人，希军一万四千人。德军攻打克里岛历时十二天，虽夺占了该岛，但损失惨重。希特勒对此大为震惊，错误地认为伞兵的时代已经过去了。与此相反，盟军却从这次失败中总结了教训，大力加强空降兵的建设。

〔５〕李德（一八八七～一九二○〕，美国记者，社会主义者。一九一七年作为随军记者赴俄，目睹十月革命，撰写了《震撼世界的十天》。回国后参加美国社会党，编辑《纽约共产党人》，成为党内著名左派。一九一九年八月，同一部分左派组成美国共产主义劳工党，担任党机关报《工人之声》主笔。同年十月被选为共产国际执行委员，再访苏俄，不久病死于莫斯科。

〔６〕近卫，参见本书《二期抗战的重心》一文注〔１〕。

〔７〕本多，即本多熊太郎（一八七四～一九四八），日本外交官。一九四○年十一月三十日代表日本与汪伪政权签订《日华基本条约》后至盟年十月任所谓"驻华大使"。

〔８〕松冈，即松冈洋右（一八八○～一九四六），日本外务大臣（一九四○～一九四一）。一九三三年任全权代表出席日内瓦国际联盟会议，当国联通过不承认"满洲国"议案时，宣布日本退出国联。一九三五年任满铁总裁，配合军部推行侵华政策。一九四○年任第二届近卫内阁外务大臣，九月负责缔结《德意日三国同盟条约》。翌年三月出访德意，四月在莫斯科与苏联签订《日苏中立条约》，但六月德国进攻苏联时，主张对苏作战，并反对日美谈判，迫使近卫内阁于七月总辞职。第二次世界大战后以甲级战犯被捕，在远东国际军事法庭审判期间病死。

〔９〕松本忠雄（一八八七一？），日本外交官和国会议员。一九三七年任第一届近卫内阁的外务政务次官。七次当选国会众议院议员。

