# 论敌寇两面政策

中文马克思主义文库 -> 周恩来
论敌寇两面政策
（一九四一年六月八日）

孙子说："知彼知己，百战不殆。"我们对于敌寇知之者固然很多，但欲求真能不带感情不偏主观，具有真知灼见的人也并不易。大概在敌人的国际环境较好而又能集中力量进攻我们的时候，我们便常易发生悲观的论调或情绪；在敌人的国际环境较坏而又在其休整兵力的时候，我们便常易过分乐观，且常喜夸大敌人的困难，好像敌人已时时的处在崩溃之中。其实这种悲观与过分乐观，都是长期抗战中所不应有和不必要的。尤其是轻敌观念更易松懈自己的战斗意志和对敌人的警惕，反而使对内重于对外，抗战更受损失了。

前事不忘，后事之师。我们回想一下去年，从法国失败一直到三国同盟缔约之前，敌人的国际环境是较有利的（德意与英美双方都在争取日本，英国不惜封闭滇缅路，美国不惜承认东亚门罗主义以迁就日本），敌人亦正在集中力量攻我宜昌，于是我们国内的悲观情绪，彷徨心理，一时大盛。但我们当时曾一再指出，新的国际变化就要到来，敌人的困难很大，我们的办法还多，我们不应悲观，而应检讨错误，克服困难。中共中央更于七七纪念三周年宣言中，就指出世界帝国主义已走向两个集团，德意日站在一边，英美站在另一边。果然不多几天，近卫第二次登台，日本加入轴心〔１〕以与英美对立的倾向便最后确定了，而中日战事，也并不如一般人所想象的那样悲观，重庆依然是抗战的陪都，敌人并没有敢来窥探。接着，从三国同盟到日苏协定为止，敌人的国际环境转坏了（英美对日的对立，意大利在欧非战争的失利，滇缅路的重开，美国的对华借款等等）。敌人的兵力亦正在休整与补调之中，对我侵战没有大的进展，甚至在开始还采取从龙州南宁撤退以节约兵力便于南进之步骤。于是我们国内过分乐观的情绪便大大增长，甚至一时忘其所以，竟以为天下莫敢予毒。但我们当三国同盟一开始，便警告国人，切勿因一时国际形势好转过分乐观。而应发扬蹈厉，加紧团结，加强力量，以利反攻力量的准备。哪知短视的人，却在此时作了一些亲痛仇快之事，反而使天下惶惑，敌人乘机，沿南海沿长江之战，便从敌人在信阳的出击开始了。而国人的情绪，也又为之一变。

其实这种变化，敌人是根据其国内外情势的变化而产生的。敌人国际环境的好转，固然不会好到举世强国皆为敌助，但敌人国际环境的坏转，也还没有坏到一无与国，就是真正孤立了，也会逼得敌人的政策在这方面改变。敌人的内部困难，诚然因为长期的侵华战争，愈打愈多，但敌人也还没有进入崩溃之中，就是真正进入或接近于崩溃，也会逼得敌人的政策在这方面力图挽救的。

因此，敌人的侵华战争，其产生固然根据其灭亡中国的国策，其发展固然是愈陷愈深，愈久愈难结束，但敌人决不会听任自己在战争中淹没，他必然要采取其他方法，以企图达到其战争的目的的。所以，敌人于军事进攻之外，还使用政治进攻的法宝，企图以诱降和分化，来动摇我们抗战的意志，瓦解我们抗战的力量，以便利其征服中国，这就是敌人侵华的两面政策。这种两面政策，从战争开始就出来了，有时先后运用，有时同时配合，战争愈久，尤其是敌人需要南进，就愈使敌人急于要解决"中国事件"，于是两面政策的行使，也就配合得愈加密切了。

同时，敌人的南进政策，其产生固然根据其独霸东亚的国策，其发展固然会走向武力发动与英美造成不可避免的冲突，但敌人也决不会在不利于武力南进的条件之下，不去采取其他方法，以企图达到其南进的目的的。所以敌人在实施南进政策的开始，便采取政治军事双管齐下的办法，一方面是武力的威胁和占领，另一方面又是外交的谈判和妥协。这就是敌人南进的两面政策。这不仅对于安南〔２〕泰国如此，对于荷印对于英美也莫不如此，尤其在英德战争变化甚多的发展中，在现在在将来都要如此。

要了解敌人这种两面政策的根源，当然是由其国内外复杂而矛盾的条件所产生。也正因为敌人所处的国际环境，特别是太平洋上的环境极端复杂，也正因为敌人国内情况的复杂和矛盾，也更因为中国抗战已经坚持了四年，这就使敌人的政策更带矛盾性和摇摆性，也就是敌人的政策困难所在。但是敌人这种两面政策，既不是对立政策，而是一个政策的两面，也不是平均政策，而是在实施的时候有主从，也有重心。譬如不论军事进攻或政治进攻，其目的总在侵华和南进。譬如侵华战争已经打了四年，军事进攻便是主，政治进攻便是从，但重心有时放在军事，有时也可放在政治。而南进对于荷印及英美属地，既尚未发动军事进攻，其政治进攻自然是属于目前南进政策的主体了。

要击破敌人这种两面政策，不仅要了解敌人这种政策的目的、主从和重心，并且还要了解敌人所处的国内国外环境的复杂和变化，以及敌人在侵华和南进两政策中的相互联系和影响，尤其要采取针锋相对的政策。

什么是针锋相对的政策？就是敌人以军事的进攻和扫荡来，我们以各线出击和破击战回答他。敌人以政治的诱降和分化来，我们以反对投降和巩固团结回答他。敌人以军事政治双管齐下来进攻我们，我们便以团结抗战来回答他，敌人要抽身南进，我们便坚持抗战发展力量，求得中华民族的彻底解放。敌人想通过美国调解中日战争，我们便坚持独立自主抗战到底的立场，来击破敌人这一阴谋。简单一句话，便是：敌人所欲者我不为，敌人所不欲者我为之。

目前的敌人两面政策又怎样呢？

联系起来看，敌人最圆满的想头是侵华与南进的利益都要得到。但其客观的环境和主观的力量，是否能容许呢？自从松冈访欧与缔结苏日中立条约以来，一方面说明日寇要从复杂而变化的西方战争中解放出来，发挥其对于轴心同盟之半独立的作用，另一方面说明日寇要暂时撇开苏联，以便先用全力解决太平洋上的问题。但是如果单纯依靠武力，即使抽调国内及关东之兵，也不过增加若干师团，既不能单凭他解决中国战事，而且如作深入的进攻，必归旷日持久，坐失南进良机（当利于敌人武力南进的时候）。尤其是在中国消耗兵力愈大，对南进的威力也就会愈益减弱。如果先解决"中国事件"，然后抽身南进，则扶汪既成画饼，而直接妥协又为全中国军民所坚决反对，必致徒延时日，得不到任何结果。如果放着中国事件暂不解决而先行南进（日本统治阶级中，有一部分人曾作此想），这在敌人既难以放下，而且会有可能使中国抗战力量更加发展，使敌人难于两面应付，因此，目前敌人最狡猾的两面政策，就是一方面在军事上，增加一小部兵力，配合和集中在华相当大的兵力，发动对华军事进攻，将中心放在封锁我们交通运输和摧毁我们有生力量与经济基础上面，其步骤则由东南而华北，而沿黄河沿长江，如果可能更会封锁到西南西北。为此便可控制一部兵力，尤其可节约大部海军作为准备南进的姿态。另一方面，在政治上却企图以"远东慕尼黑"〔３〕的引诱来和缓美国，并经过美国调解中日战事，同时又放出挑拨流言，企图以此分化中国内部团结，便于实施其诱降的诡计。这是一箭双雕的两面政策，在军事上先求困住中国，然而又决不放松对于武力南进的积极准备，在政治上却转到以美国为中心对象来解决中国和太平洋上的问题。后者较前更为毒辣，虽然在目前还是暗流，但在日寇方面，这种暗流已在增长，已非完全烟幕作用，而是有其政治基础的。

有人说，日本统治阶级中尽管有人作此想，然而实际妥协很难找到中美日的共同点。尤其是日本的少壮派，更是好大喜功，决不肯放弃其征服中国和武力南进的企图。不错，日本少壮派中，诚多鲁莽之徒。但今天日寇内阁中掌舵的，却并非这流人物。我们只要看自从平沼〔４〕加入近卫内阁后，内阁的革新色彩，已有褪色的印象（日本《国民新闻》语），继着来的，大政翼赞会〔５〕改组了，小仓〔６〕入阁了，中野正刚〔７〕等退出翼赞会，嚷出"昭和维新""放逐金融资本"之类的口号了。这就说明近卫内阁虽然建立在国内革新派及国外轴心同盟的基础上，但近来这种基础却已随着国外国内的变动而动摇起来，于是也就反映出日本政局正处在一个彷徨不定的趋势上。彷徨不定，最后总会有新的归宿。果使西方英德战争大有利于日本武力南进，日本政局的摇摆，便会更多的倾向于革新派。就是这样，也不能说日美没有暂时和缓的可能。而现在日本政局彷徨不定的趋势，正好给美国方面某些人士制造日美妥协空气的机会。最近一周来，不仅寇使野村〔８〕在美大放厥词，不仅美国某些报纸记者公开讨论日美无战争而有友好之必要，并且还有人甚至讨论到调解中日战争的条件问题；这就是要在中美日中间找到妥协的共同点。日美愿意避免战争，而且愿意友好，这是他人的自由，但是如果以调解中日战争换取日美的妥协，那便是侵犯了中国的自由。因为在今天，中日战争的解决，只有凭中华民族自己的抗战力量，打出日本帝国主义去，美国如出头调解，在缓和日美冲突的条件下，必然会牺牲中华民族独立解放的利益的。就连美国的外交界也认为"......此种解决办法，等于牺牲中国，欲造成远东慕尼黑，故美国乃拒绝此议"（华盛顿三日国际电）。我们很欢迎美国外交界这种消息，但我们更希望美国政府公开的拒绝这种提议，我们尤希望我国政府公开的申斥这种阴谋，那末，远东慕尼黑的暗流，也才会受到有力的打击。

总之，敌寇的两面政策，不论在侵华或南进上，他不遭遇到最后的失败，他是会一直发展下去的。我们认清他目前两面政策的重心所在，我们便应一方面加强我们军事力量，协同我们军事动作，以粉碎敌人的进攻和封锁。另一方面，坚持我们独立自主的抗战立场，加紧我们全国的团结，以粉碎敌人的诱降分化和远东慕尼黑的阴谋。

只有这样针锋相对的政策，才能彻底的粉碎敌人的两面政策，一直到最后胜利！

＊原载一九四一年六月八日重庆《新华日报》。

注释：

〔１〕轴心，指轴心国，是第二次世界大战前夕和在大战期间结成同盟的法西斯德、意、日三国。

〔２〕一八○二年，安南改国号为越南。在新中国成立以前，中国民间仍沿称其为安南。

〔３〕慕尼黑是德国东南部拜恩州首府。一九三八年九月二十九日至三十日，英国首相张伯伦、法国总理达拉第同德国的希特勒、意大利的莫索里尼在慕尼黑举行会议，签订了《关于捷克斯洛伐克割让苏台德领土给德国的协定》，英法企图以出卖捷克斯洛伐克为代价，促使法西斯德国侵略苏联。在英法绥靖政策的纵容下，一九三九年三月德国出兵占领捷克斯洛伐克全部领土，并在九月进攻波兰，挑起了第二次世界大战。后把为了自私目的而牺牲其他国家利益，纵容侵略的行为称为慕尼黑。东方慕尼黑或远东慕尼黑指在日本侵华战争时期，英美帝国主义妄图牺牲中国，与日本达成妥协的阴谋。

〔４〕平沼，即平沼骐太郎（一八六七～一九五二），日本著名的法西斯官僚。一九三九年一月组阁，任首相。因诺门坎事件日军惨败，加以受纳粹德国背着日本与苏联签订互不侵犯条约的冲击，不足八个月便下台。一九四○～一九四一年任第二届近卫内阁的内务大臣和国务大臣。日本投降后以甲级战犯被捕，一九四八年被远东国际军事法庭判处无期徒刑，一九五二年病死狱中。

〔５〕大政翼赞会是第二次世界大战时期，日本近卫内阁为推进"新体制运动"而建立的法西斯政治组织。一九四○年十月成立。总裁由首相担任，支部长由道、府、县地方长官兼任，并在中央和地方，仿照意大利法西斯的职业代表协议会建立"大政翼赞协议会"，议会由总裁、支部长任命。它积极协助政府实行国民精神总动员，强化军国主义体制。一九四五年六月解散。

〔６〕小仓，即小仓正恒（一八七五～一九六一），日本财阀兼官僚。一九四一年四月任第二届近卫文内阁国务大臣和第三届近卫内阁大藏大臣。此外，还担任战时重要金融机关"金融金库"总裁和国会贵族院议员。

〔７〕中野正刚〔一八八六～一九四三），日本法西斯政客。一九三六年组织法西斯政治团体东方会，任总裁，大力推进法西斯主义运动。一九三七年访问德、意，崇拜希特勒和墨索里尼。对内鼓吹"昭和维新"，对外叫嚷完成"大东亚战争"。一九四○年任"大政翼赞会"常任总务，翌年辞去。自一九四二年因与东条英机矛盾不断加深，一九四三年十月以反东条首相和策略倒阁活动遭宪兵队逮捕，被释放后在家中自杀身亡。

〔８〕野村，即野村吉三郎（一八七七～一九六四），日本海军将领和外交家。一九三二年任海军中将、第三舰队司令官，率舰队参加，一二八事变，进犯上海。四月二十九日在上海发生的天长节（天皇诞辰）爆炸事件中被炸瞎一只眼。翌年晋升海军大将。一九三九年任阿部信行内阁（一九三九年八月三十日～一九四○年一月四日）外务大臣。一九四○年十一月二十七日受命担任驻美特命全权大使，主持日美会谈，直到日本偷袭珍珠港发动太平洋战争。

