# 民族至上与国家至上

中文马克思主义文库 -> 周恩来
民族至上与国家至上
（一九四一年六月十五日上篇，二十二日下篇）

民族至上,国家至上的口号，在抗战四年中已为全中国人民所接受所实行了，我们只要一想到前线军民浴血抗战，敌区民众忍辱苦斗，后方人民出力出钱，就可认识出"民族至上""国家至上"的意义的伟大。然而"民族至上""国家至上"的口号虽其单纯，但其真正的含义却常被人曲解或误解，作为攻击别人或批评别人的口头禅。我们于此，愿对"民族至上""国家至上"的含义有所阐明和声明。

一个口号的提出和被大众所接受所实行，必其口号的本身合乎此时此地的具体环境和大众具体要求。"民族至上""国家至上"虽其所含义已不仅限于单纯的口号，但如果这种口号用之于纳粹德国或大英帝国，其所含义将完全不同于中国，其所动员的能力也就大有差异了。

什么是"民族至上"在中国的含义呢？

我们认为首先应该认清中华民族是处在被压迫民族的地位，他要从国际帝国主义的压迫下自求解放，尤其在今天，他要从日本帝国主义的铁蹄下，自力更生，从抗战中达到解放之路。所以"民族至上"的口号就等于民族利益高于一切，他是被用来动员全中国被压迫民族向着主要的民族敌人--日寇，作生死存亡的决斗的。在这个意义上，一切个人利益，阶级利益，党派利益，都应该服从总的民族利益。为民族利益而奋斗而牺牲，是中华儿女今天最光荣最主要的任务。

次之，应该认清：中华民族解放的任务是什么？依照国父孙中山先生对民族主义的解释，"国民党之民族主义有两方面之意义：一则中国民族自求解放，二则中国境内各民族一律平等。"（中国国民党第一次全国代表大会宣言）这两方面的意义，应该成为我们民族解放的任务和目的。

在第一方面，孙先生又解释"国民党之民族主义，其目的在使中国民族得自由独立于世界"。从这些解释上，中国的民族主义在对外方面可得出三个解释：一是中华民族依靠自力更生，求得独立解放；二是反对别人侵略，也不侵略别人；三是联合世界上以平等待我之民族。第一，正因为我们要自求解放，所以对于日寇侵入中国，我们主张抗战到底，决不在敌人威力之下屈服，决不在敌人挑拨之下分裂，决不在敌人利诱之下妥协投降。只有这样，我们才算是不出卖民族利益。也正因为我们要自求解放，所以我们民族独立解放的命运，决不能依附于别的国家。我们在独立自主的民族解放立场上，并不拒绝外援，而且争取外援，但我们决不能因为需要外援，便放弃我们进行民族解放战争的立场，而介入或附属于世界帝国主义的争夺战争中去。同时，我们也并不拒绝运用帝国主义中间的矛盾，尤其是英美与日寇的对立和可能冲突，甚至在某种可能和必要时，一定战场上的军事配合行动，都是许可的，但这种运用，这种配合，必须求得有利于我们民族解放战争的进行。这，不仅不能损害我们民族独立的利益，而且要在这个运用和配合上，取得和奠定中华民族从一切侵略和压迫下完全解放出来的始基。如果有些国家完全站在日寇方面帮凶，我们反对。如果有些国家想牺牲中国利益而与日寇妥协，我们也反对；如果有些国家更想引诱中国为他们火中取栗，如过去日寇及德意劝我们加入三国反共同盟一样，我们更反对。只有这样，我们才能够不牺牲民族利益。抗战四年，说明我们民族是能够自力更生独立自主以坚持长期抗战的，也只有在这个意义上，在这个经验中，才能懂得什么是不出卖民族利益，什么是不让人家牺牲中国民族利益。第二，正因为我们反对别人侵略，所以我们也反对侵略别人；这一方面说明中华民族在自求解放的抗战中，并无侵略别人（连日本在内）野心，另一方面又说明中国民族也反对别的帝国主义侵略其他国家，压迫其他民族之非正义的行动。也正因为我们反对别人侵略，所以我们必须同情于其他民族国家的独立解放运动；这不仅朝鲜、台湾的反日运动，巴尔干非洲民族国家的反德意侵略，我们应该赞助，便连印度、南洋等地的民族解放运动，我们也应同情。固然我们应该集中和争取一切反日的力量，反对我们主要的敌人，同时我们也应警惕南洋印度等地被压迫民族不要中日寇之计，为他利用的工具，但我们决不能站在这些被压迫民族的宗主国方面，要他们牺牲民族解放的利益，一味的为帝国主义利益服务，这，不仅不近人情，而且置我们民族利益于何地？！第三，正因为我们要联合世界上以平等待我之民族，所以必须弄清什么民族能以平等待我，并须弄清我们怎样以平等待人。以平等待我的民族，必须他自己不是侵略别人依靠殖民地为生的国家，必须他自己有鲜明的反对侵略别人同情被压迫民族的国策，必须他与中国有着传统的平等友谊，而且证明给中国人民看，他曾经是现在也是将来必是赞助中国革命最力的友人。合乎这种条件的，当然是苏联。我们以平等待人，决不能照别有用心的人所解释，牺牲自己利益，服从人家利益，因为这根本是不平等。何况苏联的国家利益，决没有建立在侵略中国的利益之上，而中国的民族利益，也决不会从反苏中求得，并且双方站在反帝国主义侵略的立场上，更有他们共同的利害，所以中国联苏是绝对平等的。只要我们彼此尊重各自立国的立场，不时而赞成，时而反对，不公开称道，暗中怀疑，不一面联合一面仇视，而一贯的坚守孙先生的遗嘱，则平等的结合，革命的友谊，必能大大的有助于我们民族解放的成功。总起来说，不出卖民族利益，不让人家牺牲中国民族利益，不侵犯别的民族利益，也同情别的民族自求解放，更平等的尊重民族间的彼此利益，这便是国际间真正的民族平等，也就是孙先生民族主义在对外方面的精华。

在第二方面，孙先生又解释"国民党敢郑重宣言，承认中国以内各民族之自决权，在反对帝国主义及军阀之革命获得胜利以后，当组织自由统一的（各民族自由联合的）中华民国"。从这个解释及孙先生其他著作上，中国的民族主义，在对内方面，可得出四个解释：一是中国境内各民族应一律平等；二是中国各阶级应合作对外；三是中华民族是能自立能奋斗的民族；四是中国的民族道德，民族气节，应该发扬光大。第一，正因为中国境内各民族应一律平等，所以我们主张尊重各民族间的风俗习惯，语言文字，历史宗教，并尊重他们自己的领袖干部和一切人材，尤其要反对我们汉族中的藩属观念和自大主义，然后才能更有力的动员他们联合一起。共同抗战；同时我们更主张承认各民族的自治权和自决权，而不是简单的称少数民族为边民，然后才能更有力的取得他们同意，共同努力于中华民族的解放事业，以建立自由联合的中华民国。第二，正因为中国各阶级应合作对外，所以我们主张除汉奸外，全中国人民都应团结起来，共同抗日。就连汉奸除绝对坚决不愿悔悟者外，都应争取之，宽恕之。我们认为在中国，阶级利益并不与民族利益矛盾。除掉极端自私自利大发国难财的极少数分子外，任何阶级欲维持其整个阶级利益，只有从民族解放的利益中取得。日寇不打走，民族解放达不到。尤其是对于中国工农劳苦大众，民族解放达不到，阶级解放也无出路。但这并不是说，在为民族解放奋斗的过程中，便不能相当的解决阶级利益和相当的改善工农生活，其实这不仅是可能的，而且在增强民族解放战争的力量上，也是有利的。譬如，许多民族工业家迁厂内地，如果政府给以应有的资助和保护，他们一方面可更多的生产出国防上及人民中的急需品，另一方面也可得到他们合理的利润。譬如沦陷区域的地主，因为政府和军队广大的组织了民众的游击战争，使这些地主的土地不致落于敌手，或荒芜起来，于是他们便觉悟到只有捐出一些游击军费或者减低一些租息，方能使劳苦农民得以参加那些游击队，保卫乡土。同时，从另一方面看，为得适合目前物价高涨，增加工资，以增强工人的劳动力，为得适应目前粮食需要，减低农民租息，实行农村借贷，以增加农民的生产量，这都是与抗战有利，与其他阶级并无损害的。这里有一个共同的最高原则，就是一切阶级利益都不能超过民族利益，都应该服从民族利益。因此，我们反对那些少数极端谋私利的分子借口国难期中，加紧剥削工农劳苦大众。我们也反对那些不从改善劳动生活中求增加生产出路，而一贯以强迫虐待为能事的干法，我们更反对那些拥有特权的人，利用国家企业，大分红利，而不肯增加工资，甚至减少生产，以便高抬市价，而不顾社会需要。第三，正因为中华民族在历史上，是能自立能奋斗的民族，所以我们主张只要发动抗战，中国人民的民族意识必空前的增涨，中国人民的抗战意志，必前仆后继，至死不屈，中国人民的胜利信心，必愈因敌人的失道寡助而积久弥坚，中国人民的奋斗苦干，必愈因不断的困难需要克服而愈显其坚韧不拔。抗战四年，证明这一估计完全合乎实际的发展，这是汪逆精卫之流的投降妥协分子所不能认识的，而应成为我们民族革命精神之所寄；并应在这上边建立起我们自力更生的精神基础。第四，正因为中国的民族道德民族气节应该发扬光大，所以我们主张民族传统的忠孝仁爱信义和平，便应该大大发扬，尤其是礼义廉耻，更是民族气节之所系，必须不折不扣的实行。忠孝施于国家民族，仁爱施于同胞，信义施于友邦，和平施于人类，这都是最高的道德标准，但我们并不能因此不分清敌我友恶。对敌人，要集中火力去攻击；对自己，要紧严抗战的阵线；对朋友，要明辨，要争取；对怙恶不悛的人，要戒备。我们要重气节，才能挽颓风、清贪污、建革命的秩序、止投降的倾向。尤其要尊老敬贤，重视他们的经验学问，爱护青年，要提拔教导他们，不要摧残他们，更不要特务化他们，而对于寡廉鲜耻的人，却不应该使他们篡据高位，阻塞贤路。这都是中华民族的优良传统，在目前抗战中，特别需要。总起来说，民族平等、阶级合作，自立奋斗、守道德、重气节，这便是孙先生民族主义在对内方面的精华。

这一切，就是中国民族主义的全部纲领，也就是民族至上在中国的全部含义。我们中国共产党人，就是在这样的纲领上，在这样的含义中，拥护"民族至上"的口号，实行"民族至上"的口号。违背这种原则的，我们认为不是误解，便是故意的曲解来破坏中国的民族阵线。这将是抗战的罪人，民族解放的罪人。

什么是"国家至上"在中国的涵义呢？

我们认为首先应该弄清国家的定义。"按马克思的学说，国家是阶级统治的机关。"（列宁：《国家与革命》）这个定义，原则上对于一切国家都适用的，而现在处在帝国主义国家与社会主义国家并立的时代，尤其是处在目前战争与革命的时代，这个国家的作用，便更有它新的发展。一切帝国主义的国家，都是资产阶级统治的机关，而法西斯的国家，或因为战争而亦极权化了的国家，更是极少数大资产阶级统治的机关；在这样的国家中，被统治的工人阶级（连家属在内），已成为这些国家中的大多数，他们除掉因为被压迫的或者被欺骗的在"保护祖国"的口号下走上战场，去为统治阶级牺牲而外，如何能心悦诚服的热爱这个资产阶级的国家呢？！马克思"工人无祖国"的说法，便是指他们而言。在苏联，他是无产阶级统治的国家，现在已经进入无对立阶级的社会，但是因为它还处在资本主义世界的严重包围之中，这个无产阶级的国家便须用来对抗世界帝国主义的统治，而成为世界的无产阶级解放运动的灯塔，所以它被认为是社会主义的祖国。还有，在帝国主义侵略下的殖民地和半殖民地以及被帝国主义战争所蹂躏的一些弱小国家，他们所要建立的或者要恢复的国家形式，将是一种民族国家。虽然这种国家中，仍会有统治阶级与被统治阶级之分，但当他们整个民族需要合力御侮的时候，这个国家的作用，便成为对抗外来帝国主义侵略以求自己民族独立解放的统一机关了，并且在今天战争与革命的时代，殖民地半殖民地以及弱小国家的民族解放运动，一定要在民族的人民的统一战线及其所建立的联合政权领导之下，才能得到彻底胜利。所以在这些国家中民族解放的利益，是各阶级所共有的，"保护祖国"的口号，也就适用，而"国家至上"也就有他严重的历史意义。我们中国共产党人，便在这个意义上提出"保护祖国"的口号，拥护"国家至上"的口号。这与在资本主义国家的工人阶级中提出"工人无祖国"的口号，反对"保护祖国"的口号，并无矛盾之处，相反的，还有相辅相成的作用。很显明的，在中日战争中，我们共产党人在中国是拥护抗战，"保护祖国"，而在日本则是反对战争，则是"工人无祖国"。这种事实，难道还不够寒造谣者之口，解怀疑者的忧虑么？

次之，应该弄清：我们要建立怎样一个国家？大家都承认，我们的抗战建国，是为的要打退日寇，建立三民主义的新中国。依照我们的认识，这个三民主义的国家，既不应该成为资产阶级专政的国家，也更不是无产阶级专政的国家，而应该是抗日各革命阶级统一战线的国家，因为它要从坚决反对日本帝国主义的革命战争中建立起来。孙中山先生在这个政权的问题上说得很明白："近世各国所谓民权制度，往往为资产阶级所专有，适成为压迫平民之工具，若国民党之民权主义，则为一般平民所共有，非少数人所得而私也。......盖民国之民权，唯民国之国民乃能享之，必不轻授此权于反对民国之人，使得藉以破坏民国。详言之，则凡真正反对帝国主义之个人及团体，均得享有一切自由及权利，而凡卖国罔民以效忠于帝国主义及军阀者，无论其为团体或个人，皆不得享有此等自由及权利。"（国民党第一次全国代表大会宣言）所以三民主义的政权，是一种新民主制度。它在政治上，是要建立革命各阶级联合的政权，而不是一阶级一党的政权，它只推翻帝国主义的统治和侵略以及汉奸反动势力，并不推翻参加抗日反帝的任何统治成份。它在经济上，是要实行耕者有其田，把日寇汉奸企业财产及有独占性质的大企业，收归国家所有和经营，同时保护工商业的发展，扶助私人的中小企业，也并不废除富农经济。因此，这种新的民主国家，既不完全是欧美式的资本主义民主国家，也并不是苏联式的社会主义民主国家。这种新的民主制度，虽然是替资本主义的发展扫清道路，但同时又是替社会主义的生长创造前提。这样的国家，这样的政权，在现在帝国主义战争及社会主义苏联日益强大的时期中，只有坚持抗战到最后胜利，才有实现的可能，别的取巧的办法，是没有的。而且一经妥协，不仅日寇的势力赶不走，便连从别的帝国主义的势力下解放出来取得平等的机会，也会失去。所以为着"国家至上"，必须抗战到底，必须努力建立三民主义的新中国。

再次，新的民主制度，究竟是怎样内容？依照孙先生的解释："国民党之民权主义于间接民权之外，复行直接民权，即为国民者，不但有选举权，且兼有创制复决罢官诸权也。"（同上），而在国民党政纲上，孙先生又规定："确定县为自治单位"，"各省人民得自定宪法，自举省长"，"关于中央及地方之权限，采均权主义"，"实行普通选举制，废除以资产为标准之阶级选举"，"确定人民有集会结社言论出版居住信仰之完全自由权。"（均同上）根据这种主张，我们提议和要求在目前抗战期中政治的民主，至少限度应做到：承认各抗日党派的合法地位，容许各抗日团体的合法活动，保护各抗日书报书店的出版发行和营业的权利，扩大国民参政会及省县参议会的权限，筹备真正的普选的民意机关，并禁止特务机关的非法逮捕，这总不能算丝毫过分，根据这种主张，我们更于陕甘宁区及敌后游击区，在不违背国宪（实际是三民主义党纲及政纲）的原则下，试行省县自治及直接创制（举例如最近陕甘宁区施政纲领），并请求中央批准和指导，这也不能算丝毫过分。有人说，在陕甘宁区及敌后游击区，也同样没有民主自由。我们回答说，根据中共提出的选举纲领，我们欢迎各抗日党派及一切爱国人士去边区参加选举，参加政权，办报纸，开书店，组织团体，开发实业，并负责担任保护，但关键却须得到中央政府许可和批准，否则，任何个人和团体都无从进入边区。我们更欢迎各方面对于边区游击区的一切设施给以善意的严格的批评和指教，但我们却希望大家亲身去看看，不要只凭道听途说，易失真相。譬如国民党部过去在延安虽未办日报，但在其公开的壁报上却大谈一个主义，反对马列主义，并未受到任何干涉和检查，可见民主自由在延安是有的。拿大后方来说，即使现在仍在训政时期没到宪政时期，地方自治总该开始实行。那末，县区乡的人民直接选举，并非难事，罢官权可先从有权控告任何公务人员之非法行为开始，以肃清地方的贪官污吏，创制权可先从改善兵役制度和粮食动员开始，以增加国家兵员的补充和粮食的接济，复决权可先从审查地方政府的预决算开始，以树立地方廉洁政治的楷模。这样的地方自治，在今天决不会妨碍抗战，而只是有助于抗战，但有一个先决条件，必须真正动员地方民众直接参加，而不是听任少数官吏包办地方自治。只有这样，民主政治才真正向前走了一步，抗战的困难，也才能依靠这个基础去克服。

又次，在进行民族解放战争的今天，国家需要有中心，这是谁都不能否认的。三民主义，国民政府，最高统帅以及国民党在全中国的领导地位，都是四年来抗战中国的中心。只要坚持团结抗战，坚持建立三民主义的国家，谁都会拥护这中心，珍重这中心。我们共产党人，四年来始终承认这中心，拥护这中心。我们不仅为三民主义的实现而努力，我们并为尊重国民政府的领导而无数次的请求其承认陕甘宁边区为中央政府所管辖的一部分行政区域，以便更有力的打破对于中共要建立第三个中央政府的造谣。我们更为尊重最高统帅作战意旨，最近不待命令的下达，不顾以往的创痕，不计饷弹的两缺，便发动了华北的破击战，以协同友军抗战，以击破敌寇及傀儡者的挑拨和污蔑。同时，我们始终认为国民党的进步和发展，对于抗战胜利建国成功有极重要的关系。我们所反对的只是国民党中极少数的对于抗战的动摇分子，和仇视中共的顽固分子，绝对没有反对国民党的全体。有人硬说我们要另建一个国家中心，要推翻国民党领导的国民政府，要破坏抗战的军队，这都是无稽之谈。我们深知道，在抗战建国过程中，团结则存，分裂则亡，合作则胜，独霸则败。但我们希望国民党人士也要了解，大家既拥护这国家中心，自己便应更珍重这国家中心，倾听群众的意见，接受善意的批评，这对于巩固这国家中心只有好处，没有坏处。古语云，以国士待之者，必以国士报之，凡愿他人拥护这国家中心者，自己亦应以国士待人。尤其是人家并未不拥护这国家中心，而自己先肯定人家要推翻这国家中心，甚至不给人家以拥护这国家中心之可能，其结果，只有逼得人家自力更生。就是这样，也还不能视为另建中心，因为人家固无时无刻不在承认这国家中心。所以拥护国家中心者，不应有"彼可取而代之"的念头，而负此国家中心责任者，亦不容有"天下莫敢予毒"的想法，而天下为公，才是"国家至上"的最好保证。

这一切，就是中国民族的民主的国家的重要内容，也就是"国家至上"在中国的全部涵义。我们中国共产党人，就在这样的内容和涵义中，拥护"国家至上"的口号，实行"国家至上"的口号。

最后，我们还得说明：中国民族主义与国际主义并不矛盾，也不冲突。国际主义者在中国必须坚决实行中国民族主义，才能使中华民族得到独立解放，走上国际舞台。同时，中国的民族主义者，必须同情和联合国际主义的运动，才能共同打倒国际帝国主义的统治，求得国际上真正的民族平等，中华民族的彻底解放。我们反对法西斯主义的民族观念，因为他们认为只有他们自己的民族是统治世界的特殊民族，而其他民族都是被统治者。我们也反对其他帝国主义的民族优越观念，或人种优越观念，因为他们认为被他们统治的殖民地半殖民地的民族或其国内的有色人种，都是劣等民族，或将被淘汰的人种。这两种观念，与我们中国的民族主义，并无丝毫相同之处，因为帝国主义国家的统治民族已经不是整个利害相同的民族，而其中的阶级矛盾早已超过民族矛盾，故我们决不能同意和赞许帝国主义国家也用"民族至上"的口号，维持和扩张他们对于其他被压迫民族及人种的统治和蹂躏。

中国民权主义亦即民主主义与社会主义亦即共产主义并不矛盾，也不冲突。社会主义者亦即共产主义者，在中国必须坚决实行中国民权主义，才能使中国成为独立的民主国家，走向非资本主义前途的发展，亦即走向社会主义的前提。同样，中国的民权主义者，必须同情和联合世界社会主义的运动，才能共同打倒国际帝国主义的统治，走向世界大同。我们反对法西斯的国家社会主义，因为他们为极少数的大资产阶级，即取消民主，还加重的剥削劳动群众。我们也反对社会民主党的社会爱国主义，因为他们的社会爱国主义，是要欺骗他们国内的劳动群众为帝国主义的利益牺牲。这两种主义，与我们中国的民权主义并无可以联合之处，因为帝国主义的国家是资产阶级统治的机关，被统治的阶级决非有爱于这种国家机关，故我们决不能同意和赞许帝国主义国家也用"国家至上"的口号，维持和加紧他们对于被统治阶级的剥削并压迫他们去当战争中的炮灰。

因此，"民族至上""国家至上"的口号，在中国，在一切殖民地半殖民地及被侵略的弱小国家是革命的，而在一切资本主义国家则是反革命的，我们共产党人拥护前者而反对后者。这决不是矛盾和不一致，而是根据不同的环境不同的历史条件，必须采取不同的态度。只有糊涂的人，或者故意不去辨别差异的人，才会说"民族至上""国家至上"这类口号，是放之四海而皆准，被诸万世而不变的呢！

＊原载一九四一年六月十五日和二十二日重庆《新华日报》。

