# 纳粹德国反苏战争爆发！

中文马克思主义文库 -> 周恩来
纳粹德国反苏战争爆发！
（一九四一年六月二十三日）

一月来盛传的德国反苏暗流，由于纳粹德国向苏联进攻和轰炸，已于昨（二十二）日晨四时爆发成为反苏战争了。这个战争诚如莫洛托夫〔１〕所说，并不是德国人民、德国工农和知识分子要向苏联进攻，乃是德国血腥的法西斯统治者要向苏联进攻。苏联军民在保卫其社会主义祖国的神圣责任前面，已动员起来应战了。

苏联历来是一惯的坚守其和平中立政策，并忠实的履行了苏德协定〔２〕中所规定的义务，一直至昨日德国反苏战争爆发前，犹可见苏联是在努力维持其和平中立政策，绝未向德国以及德国所侵占的一切国家作任何的挑衅。但是苏联对于纳粹德国的态度是严守限度的，苏联绝不容希特勒有超于苏德协定的要求，更不容希特勒对于苏联有任何领土主权的侵犯。现在，苏联元帅铁木辛哥〔３〕在五一节所指的"种种惊人巨变"，已在苏芬和苏罗边境爆发了，苏联全国军民必然会在斯大林领导之下，发挥其空前团结和巨大无比的力量，以击败此凶顽残暴的法西斯者的进攻。

目前战争方在开始，以一个进行战争将近两年而又侵占屈服了十四个国家的纳粹德国，一旦对占全世界六分之一土地有两万万人口而又将近完成第三个五年计划的社会主义苏联开战，其战果决不是短时期所可看出，更不是几个仗便见分晓，而且此变所系，影响之大，会要超过任何战争，国际风云，也将为之变色。不过有一件事，我们可以预见的，即是苏联方面站着的有全苏联的军民和全世界的无产阶级以及愿和苏联友好的人民、民族和国家，而纳粹德国方面站着的只有统治阶级法西斯和愿意参加对苏联的侵略者以及被法西斯蒂所欺骗所驱使的军队，而其中将要发现在纳粹统治下的反法西斯的人民革命运动和民族解放运动的兴起。

我们中国抗战四年，苏联给予我们的同情和援助，是人所共知，今天苏联正遭遇着惊人巨变的纳粹侵略，这与我们在东方遭遇的性质正复相同。患难见真情，我们伟大的中华民族，将必以关注的心怀寄以无限的同情，并预祝着苏联的最后胜利！

＊这是为重庆《新华日报》写的社论。刊载于一九四一年六月二十三日重庆《新华日报》。

注释：

〔１〕莫洛托夫（一八九○～一九八六），苏联政治家和外交家。一九三○～一九四一年任人民委员会主席（即苏联的总理〕。第二次世界大战爆发前不久，他还兼任外交人民委员，谈判签订苏德互不侵犯条约。在德国侵入苏联后，他还在国防委员会中工作，组织苏联与英美结盟的工作，曾出席同盟国在德黑兰、雅尔塔和波茨坦的会议，以及创立联合国的旧金山会议。一九四九年三月，辞去外交部长职务。斯大林逝世后，他又担当这个职务，直到他与赫鲁晓夫因政见不同于一九五六年六月被免职为止。

〔２〕苏德协定即苏德互不侵犯条约，签订于一九三九年八月二十三日。主要内容是：缔约双方互不使用武力；不参加直接或间接反对缔约国另一方的国家集团；就彼此有关问题，密切接触，交换情报；和平解决相互间的一切争端。有效期十年。但条约签订不到两年，一九四一年六月法西斯德国即发动侵苏战争。

〔３〕铁立辛哥（一八九五～一九七○），苏联元帅。一九三七年起任北高加索和哈尔科夫军区司令。一九四○年起任苏联国防人民委员。卫国战争期间任副国防委员，最高统帅部代表，西部战线、西南战线军总司令，斯大林格勒方面军和西北方面军司令。

