# 论苏德战争及反法西斯的斗争

中文马克思主义文库 -> 周恩来
论苏德战争及反法西斯的斗争
（一九四一年六月二十九日）


　　世界的惊人巨变，已因纳粹德国毫无信义的突向苏联进攻而爆发了。二万万伟大的苏联人民，已在苏联政府及斯大林的号召之下立即起来应战。战争就这样于六月二十二日在苏联西线开始，战线之长达二千五百英里，双方动员兵力之多之强，将成为全世界空前的一战。这不仅在数量上说是空前的，而且在质量上说也成为世界战争的转换点。这一战争，一方面站着纳粹德国及一切法西斯的同谋者，另一方面站着全苏联的军民，全世界的无产阶级以及一切和苏联站在一条战线上的人民民族和国家；前者是企图在击败苏联的基础上，继续扩张和达到他侵略和奴役全世界人民的血腥统治的目的，而后者则是为保护苏联，也同时为保护全世界人民和民族的独立自由而战。前者是非正义的侵略战争，后者是正义的自卫战争。这一战的胜负，关系于全苏联并且是全世界人民和民族的命运。苏联胜了，不仅苏联而且全世界被奴役的人民和民族都要得到自由和解放；纳粹德国胜了，将使全世界陷于黑暗的深渊。所以世界战争进入到苏德战争的新阶段，已经是历史上的新时期了。在过去，在西方，英德的争夺战是主体，而许多弱小民族国家却被法西斯侵略者所侵略所蹂躏了。在现在，法西斯侵略者的战火已转向苏联，苏德战争已成为主体，苏联已站在全世界反抗法西斯奴役斗争的最前线，背负着保卫全世界自由的重任，而被法西斯奴役的人民和民族，将得到恢复自由独立的机会，甚至被纳粹攻打的英国，也得到喘息的机会，这些事实，显然成为世界战争中新的分水线。因此，全世界一切痛恨法西斯主义和压迫的人民民族和国家，都会认识苏联人民的奋斗，也就是他们应该参加的奋斗。丘吉尔说得好，"苏联的危机，即是英国的危机，同时亦为美国的危机"，扩大来说，也就是全世界的危机。苏联的人民已在前线，继着而起的，我们已看见来自全世界的同情苏联的呼声，这是一种新气象，新的反法西斯主义的高潮。我们伟大的中华民族，四年来久已站在反日本法西斯强盗的前线，更会不落人后的将自己抗战的胜利和苏联抗战的胜利亲密的联在一起，共同努力于全世界反法西斯主义的事业的成功。

　　这次苏德战争的爆发，完全由于希特勒背弃国际信义撕毁德苏条约的一手所造成，而苏联则一贯的坚守信约，履行协定，决未向纳粹德国作任何的军事挑衅，这已为举世所公认。但苏联这种履行条约的精神，并非自缚其手足。苏联的国策一向是为阻止战争制裁侵略而斗争。当慕尼黑会议，集体安全制度被破坏以后，帝国主义战争已成为不可避免，于是苏联仍坚持其和平中立政策，与德意日先后缔结协定，以避免战争扩大。但这并不是说苏联便减轻了对于法西斯国家的警戒，两年来，苏联国防力量的加强，尤其是最近半年苏联政府的重要措施，铁木辛哥"五一"的文告和演说，都证明苏联并未忽视在此资本主义世界的包围中，谁将是越境窥伺的侵略者。这也更不是说苏联便因此改变其对于为民族独立自由而奋斗的民族的援助政策，两年来苏联对波兰境内白俄罗斯乌克兰以及犹太民族的解放，对波罗的海三小国及比萨拉比亚等地之归还苏联版图，决没问纳粹德国是否愿意，而苏土宣言，苏南互不侵犯协定，以及对于罗马尼亚，对于保加利亚，对于匈牙利之出卖民族独立利益和追随纳粹德国之后的谴责声明，更不管纳粹德国是否高兴。这犹之苏联缔结了苏日中立协定，并不改变他援助中国的政策一样。谁说苏联两年来是在助长侵略而不援助被法西斯奴役的人民，这完全不是事实。并且也正因为这种原因，希特勒始终不能放心苏联立于战争之外。但是希特勒何以不在德苏协定以前反而在欧战进行了将近两年之后进攻苏联呢？两年前，慕尼黑会议，暴露了英法不仅没有制裁侵略的决心，而且还破坏了集体安全的可能，以自俯于侵略者，这自然使希特勒向易于进攻的方向动手。现在战争扩大了，美国一天天的走入战争，希特勒不能马上渡海攻英，而向埃及或近东发展，更有重兵远出的顾虑，于是遂不顾一切的先想从扫除苏联的威胁入手，这是一。战争走向持久，纳粹德国虽侵占了十四个国家，但其资源并不够纳粹德国的持久消耗，而欧洲粮食的恐慌，亦已造成大多数国家的饥馑，于是希特勒便迫不及待的向苏联伸手，企图夺取乌克兰的仓库和高加索的油田，奴役苏联的人民，以便继续他征服全世界的长期战争，这是二。两年来，法西斯蒂的黑流，和其血腥的统治，已经引起法国人民中尤其是被奴役的民族中的深刻不满和革命觉醒，而日益趋向于迅速结束战争，为人民的和平独立自由而斗争，于是希特勒便因为恐惧于此反法西斯的革命运动的生长，而迫不及待的想先从打击为人民的和平而斗争的大本营入手，以阻止革命发展，这是三。还有"英美上层阶级的反苏情绪"（《大公报》语）的存在，也颇利于希特勒的煽动，以便他转过头来先打苏后打英美，而收各个击破之效，于是赫斯奔英，便揭露了这个阴谋，而成为反苏暗流的最高峰，这是四。所有这些，都是大家意料中事，而所成为意外的乃是希特勒何以在英德并未妥协之前，敢于两面作战？这由于没有估计到希特勒在军事上，如果不在夏季动手，延到秋冬之间他便无法东进，只有等到明年，但在经济上又不容他等到明年，而政治上英美亦非一无弱点不能供其利用者。在英国，有所谓达维斯多克对德媾和的计划（二十五日伦敦合众电），在美国，斯克利泼霍华德的报纸，在德苏战争开始前就宣称，"这就是我们可以赞许的一种战争"。因此，希特勒就在这些基础上，爆发其最大的冒险的反苏战争。希特勒的意思是在说，我先打给你们看。实际上不管其战争进行得如何，只要战争还在进行之中，希特勒总不会放弃其对其他国家的和平攻势的。暗流虽是暗流，但我们总应该警戒这一暗流，才能使新的反法西斯主义的世界主流，得以汹涌澎湃的前进。

　　现在战争已爆发了一周，根据莫洛托夫的文告，根据全苏联人民热烈的响应，和对于敌人的愤怒，根据苏联红军红海军空军在前线的英勇抗战，证明苏联全国军民在斯大林领导之下，是有准备有力量能击退纳粹德国疯狂进攻的。苏联民族历史上屡次击退外来侵略的英勇传统，十多年来伟大的社会主义建设和国防力量，苏联全国军民坚固的团结，苏联布尔塞维克党、政府及斯大林的领导，全世界同情苏联的人民、民族和国家的后盾，都是保证苏联在战争中取得胜利的重要条件。但是苏联的人民知道，进攻苏联的敌人是强大的敌人，苏联并不希望轻易致胜。苏联人民很勇敢的面向法西斯蒂，在世界反法西斯战争中，当着最艰巨的阵势。他虽不愿为帝国主义的争夺去火中取栗，但他为苏联的存在和发展，为全世界人民的独立自由，却不惜重大牺牲，以争取人类的真正和平，这是社会主义的侠义行为。

　　战争的发展方在开始，我们已经说过："其战果决不是短时期所可看出，更不是几个仗便见分晓"，但是我们可预言的是时间有利于苏联。纳粹德国利在速决，故一开始便攻势甚猛，企图仍以闪击战达到其两个月征服苏联的狂言。苏联的战法，不论是拒之于国门之外，或是引之深入，只要苏联的主力在，人力在，物力在，时间一久，法西斯侵略者必然要遭受最后的惨败。故我们对苏德战争，不能以一时的出入胜负为断。同情苏联的人，因为不知苏联的究竟实力，有为苏联着急担心的，这是一种好意，应该向他们解释。然而也有幸灾乐祸的人，以苏联败了为高兴的，那真是别有用心，应该归入法西斯之流。还有认为不管苏联胜败如何，都于我们有利的，那更是有害的思想。试问纳粹德国如果胜了，他将与其东西盟友日意法西斯强盗共同征服世界，我们何能幸免？

　　我曾说而且也很希望："战争仍然循着最直接的战争轨道前进，暗流总是暗流。"虽然将来的变化还多，而且我们还应时刻提防着暗流的生长，但是目前英美的态度还总是反法西斯主义的。尤其是英相丘吉尔的态度很坦白，他知道对德妥协，不仅欧洲霸权无法取回，便连非亚属地在德胜苏之后，仍然有被侵入的危险，而苏联作战，不仅可以利用目前喘息的机会巩固英伦及北非近东的阵地，而且在反法西斯蒂的斗争中，还可维持英国某些利益。我们认为英国这种态度应该更求彻底，对于过去一贯反苏而又亲德的分子应该肃清出去，以免中途变卦，对于国内人民应恢复其民主权利，对于其属地人民，应给以解放可能，以便真正有力的动员人民的力量反对法西斯的侵入。对于苏联，英国正在进行其援助的协商，但最有效的还是军事上的协同动作，而空军的轰炸，海军的牵制，又为最重要的步骤。美国方面，确实是松了很大一口气，海长诺克斯既说德苏战争对于美国有利，而孤立派议员更大叫美国从此更无须参战，还就使罗斯福的对苏态度和援苏政策来得更加慎重，太平洋上的变化，也使得罗斯福要有所待。

　　然而不管怎样，站在反法西斯主义的立场上，英美应该与苏联建立共同的阵线，这首先必须求得政治上的谅解，大家向着一个目标，向着为消灭法西斯统治以求得各民族的独立自由而斗争。为着这个目的，必须号召广大的人民起来参加，才能保障其实现。

　　在轴心国方面，法西斯意大利已经成为纳粹德国的附庸，亦步亦趋的跟着希特勒走。而东方法西斯强盗，则向具有半独立性的作用，尤其因为缔结了苏日中立协定，所以连德国进攻苏联的消息，事先都不知道，事后松冈所受到的打击，可以想见。现在日寇正处焦急彷徨等待之中。目前最大的可能是北进攻苏，这由于亲德派及反苏分子现在正好集中在这一焦点上，而维持现状派之反对武力南进，也正可作为他们转向北进的根据。但是北进也并不是没有困难和顾虑的，第一，中国问题将因此更陷于不能解决之境；第二，西伯利亚并没有像南洋那样多的国防资源；第三，时间上不很易于侥幸成功，万一拖长，则日寇的另一泥足又要陷于冰天雪地之中；第四，万一英美在其发动攻苏后，实行太平洋上的封锁，岂不陷于前后绝境？！并且武力南进虽然暂时搁起，但是经济妥协并非不可能的。何况在英美人士中，也并非无人主张对日妥协以拉其疏远或退出轴心者，这点也颇能眩惑日寇，使其想先拿住南洋资源然后再图北进，可是时间上又何能许？！因此，遂形成日寇目前的焦急彷徨和等待，而近卫松冈内阁也便在动摇不定之中，不过，德意法西斯蒂，却策动其北进不遗馀力，所以日寇攻苏的危机是增长的，我们应该严重注意他的政治军事动态。然而不管日寇发动北进与否，对于已在他侵略下的我国，绝对不会忘怀，不会罢手，这是很显然的。他对我们的政策仍然是两面兼施，一打一拉。打的方面，有可能在配合其准备北进的步骤上，加紧华北的"扫荡"战，渡河侵犯郑、洛、潼关，或沿长江出击，以便在压迫我们之后转移兵力北进。拉的方面，有可能采取一些形式上的让步，诱我投降，引我分裂，以便其先集中力量北进，然后再回师灭我，这是最毒的一着，也是我最应警惕的一着。

　　总之，世界风云变得这样急，这样大，我们伟大的中华民族，在抗战中已屹然不动的坚持了四年，现在更不应受这个风浪波动。在这个意义上，我们应该是"以不变应万变"，并运用我们站在东方反日本法西斯强盗的前线地位，联合东方一切反法西斯的人民民族和国家，结成更广大的反法西斯的国际统一战线，肃清一切反苏反共及对日妥协的有害思想，以打倒东方法西斯蒂头子的日本强盗。在东方，英美的地位也显然增高了。过去，我们因为了解英国对德作战的困难，故只望英国不再对日妥协，而现在则较有可能加强其远东反日的力量，加增其对我的援助了。过去，我们因为了解美国不愿两洋作战，要先对德后对日，故也只望美国对日禁运，不再妥协，而现在则更有可能断绝一切对日妥协的念头，彻底对日禁运，加强对我的援助了。有人提议，中美英苏应该结成同盟，当然是很好的，但我想在今天的英美政府，是不会接受，不能实现的。不过我们最小限度的主张：不再对日妥协，实行对日全面禁运，加强对我援助，准备太平洋上反法西斯主义的自卫力量，"共同制裁日寇"一个要求，这总应该可以作到，而我们更应联合起英美人民结成太平洋上反法西斯阵线，以求其作到。

　　还有，因为苏德战争及日本有北进可能而引起的一些过分乐观心理，这在我们四年抗战中已屡次证明是有害的心理。德苏战争，德国法西斯主义者所打击的正是四年来助我最多的友邦，而遭到战争惨祸的正是二万万为世界和平民族自由奋斗的人民，我们不仅在患难之交上同情这个朋友，便在援我的意义上，我们也要受到一些影响，但这里我们要声明一句，苏联的援助历来是助我整个民族，给我国民政府，而决不如上海哈瓦斯电讯〔１〕所说，中国共产党系依靠于苏联的援助而存在的。至于估计到日寇北进，我们更不应因此过分乐观，致使放松对外，转而对内。我们应该乘机努力，加紧国内的团结，改善政治上的设施，克服经济上的困难，尤其是要加强军事的力量，国防的生产，以便一方面能有力的抗击敌人的进攻，收复一些据点，另一方面，在敌人果然北进时，我们也可配合友邦，实行反攻，击败敌人。

　　只有这样，我们的抗战，才有胜利的前途，只有这样，我们才能在东方坚持反法西斯大纛，团结一切反法西斯的力量。也只有这样，我们才能够与苏联成为反法西斯的战斗共鸣，才配称得起伟大的国父孙中山先生的革命儿女。



　　＊原载一九四一年六月二十九日重庆《新华日报》。

　　注释

　　〔１〕哈瓦斯通讯社是世界上最早的新闻通讯社。一八三五年由法国人查理·哈瓦斯在巴黎创办。一九四○年由法国政府收买。德国占领后，附庸于纯官方通讯社。第二次世界大战结束后，由法国政府接收，改组为法国通讯社。



