# “七七”四年

中文马克思主义文库 -> 周恩来
“七七”四年
（一九四一年七月七日）


（一）

　　抗战四年，我们遭遇了空前的局面，我们打出了空前的场面。这个局面，是日本法西斯强盗在侵占我东北四省之后，又侵占我十四个省区的土地，奴役和屠杀我千千万万的人民。这个场面，是我四万万五千万人的长期抗战。

　　我们伟大的中华民族本是爱好和平的民族，但敌人既已侵入我们国土，杀戮我们人民，我们只有起来自卫，起来应战。战鼓既然响了，四年来我们便义无反顾，非打到将敌寇驱出国境，决不罢手。敌人企图速决，我们便应之以持久。敌人欲歼灭我主力，我们便分散而消耗他。敌人只能正规战，我们便发动游击战困他。敌人占领我点线，我们便以面来包围他。敌人建立傀儡政权，我们便以敌后抗日政权对抗他。敌人欲以战养战，我们便以封锁和抵制破坏他。敌人封锁我们，我们加强生产，自力更生。敌人轰炸我们，我们不怕炸，不怕烧。要从焦土中建起新中国。敌人杀戮我们，我们仇恨更深，杀敌更坚。敌人怀柔我们，我们誓死不做顺民。敌人诱降我们，我们坚持抗战到底。敌人分化我们，我们坚持团结统一，共御外侮。敌人派敌探，放谣言，企图动摇我们，我们紧严壁垒，决不做敌人的应声虫。敌人利用汪精卫组织南京伪政府，我们开除他，通缉他，誓不与之两立。敌人利用德意等轴心同盟承认汪逆伪政权，我们便撤回使领，对他们绝交。敌人欲孤立我们，我们便加紧争取外援，结成世界反法西斯阵线以孤立敌人。四年中，我们牺牲了无数的英勇将士和在敌人残杀下的同胞，取得了各个战线上的抗敌胜利，杀伤近二百万的敌伪军队，消耗了敌人二百万万日元以上的军费，建立起深入敌后的抗日根据地，巩固了中国西部的抗战大后方，结果，不仅强固了我们自己抗敌的胜利信心，并且也使敌人不得不承认"中国事件"已陷于无法解决。因此，四年抗战，证明了我们中华民族是永远征服不了的民族。长期抗战，已不仅是可能，而且已成为活生生的事实，已成为我们中华民族唯一的胜利的解放道路。

　　我们伟大的中华民族，一向是多难能够兴邦的民族。敌人打进中国来这一事实，使全中国人民认识：只有团结，才能外御其侮，只有统一，才能众志成城，打到最后。四年抗战，我们国家有了从来所没有的统一，我们人民有了从来所没有的团结和民族觉醒，我们军队有了从来所没有的指挥统一和意志集中。抗战的领导者--国民政府和蒋委员长，成为全中国人民所拥戴的中心。抗战的经典--三民主义和抗战建国纲领，成为全中国人民所愿为其彻底实现而奋斗的目标。抗战的武装--数百万的正规军队，敌后的游击部队和广大人民的自卫武装，成为全中国人民所信赖的力量。抗战的各党派--国民党、共产党、青年党、国家社会党、第三党、救国会以及一切其他的政治集团，成为全中国人民所仰望的团结中心。抗战的后方--中国的整个西部和各战区的后方，成为全中国人民所重视的国防生产和战争动员的根据地。四年来，我们看见前线上将士视死如归英勇杀敌的伟大战绩，我们看见在敌人铁蹄下被蹂躏被杀戮的同胞之可歌可泣的壮烈行为，我们看见沦陷区域被敌人奴役的同胞那种忍泣吞声不忘祖国的精神和热望，我们看见在后方千百万的壮丁走上前线，劳苦的同胞日夜不息的增加生产，有知识的男女从事各方面的动员和服务，我们更看见海外侨胞的踊跃输将和回国服务，我们还看见各友邦及世界爱好和平的人民给予我们的热烈同情和物质援助，最后我们更看见战场上伪军的不断反正和敌军反战情绪的生长。这一切，都是我们抗战四年的空前成绩和伟大收获。四年抗战，证明了中国四万万五千万人的力量，是永不可侮的力量，四万万五千万人的团结，是我们争取抗战胜利的最大保障。

（二）

　　抗战四年，我们还遭遇了国际间空前的变化，我们也打出了国际间患难相共的朋友。

　　本来，二十世纪四十年代的侵略战争，是发端于一九三一年的九一八，日寇作了世界的祸首。因为当时欧美列强放任祸首，于是引起西方法西斯国家的贪欲，意大利强占了阿比西尼亚，德意发动了西班牙战争，而日寇复要求华北特殊化；这时形势，已显然是三个法西斯国家采取共同行动，然而反法西斯侵略的集体安全制度，却不为列强所重视。接着七七事变便在中国爆发了，日寇又放了侵略战争的第二次信号，可是共同制裁侵略者的主张，仍不能为欧美列强所接受，反而使绥靖政策成为一时风尚，于是奥国被兼并了，匈牙利附德了，捷克灭亡了，阿尔巴尼亚被占领了，侵略气焰日高万丈，最后连英法自己也不能不投入战争，形成彼此的争夺战。在不到两年的功夫，十四个欧陆国家先后沦亡或屈服，这才引起美国的不安和全世界的震动，这才使中国反东方法西斯侵略的领导地位为英美当局所重视。

　　另一方面，苏联在法西斯侵略开始，便提出集体安全制度共同制裁侵略的主张，然而，曲高寡和，接二连三的在西班牙战争中，在慕尼黑会议中，在捷克灭亡中，不断被人出卖，最后，更因濒于反苏战争威胁的前夜，才缔结了与邻邦维持和平友好的苏德协定。苏联缔结这个协定，一方面根据于不得违背苏联维持国家的领土完整独立和荣誉的国策，另一方面也决未束缚苏联同情和援助世界和平民族的独立自由与解放运动。关于前者，苏联争取了时间，保证自己力量的准备；关于后者，苏联始终站在同情和援助世界被压迫民族解放运动的领导地位，这不仅对于欧洲诸小国如此，尤其对于抗战四年的中国的援助，更是信守不渝。现在，希特勒因为西向发展有待，便不讲信义的撕毁条约向着苏联开火了。伟大的苏联军民立即起而应战，于是世界战争乃进入新的时期。这就是以苏德战争为主体的世界反法西斯战争的新阶段。这一战争，关系于全苏联并且是全世界爱好和平民主自由的人民的命运。

　　四年的战争，已使日寇完全出乎意外的拖得兵力疲惫，困难百出，四年的世界变化，已使日寇不能预见的失去许多机会，不得抽身南进，现在日寇在此次事变刺激下，更加反映出他在侵华战争中的巨大消耗，他国内物资的缺乏和财政的困难，他国内统治阶级各派的矛盾以及国际间错综复杂的关系，而表现出他的焦急彷徨和等待。他的决策虽说是定了，但并未宣布，据估计，北进是他最大的可能，但困难重重，还想有所期待，武力南进虽暂时搁起，但仍想和缓美荷，取得经济妥协，并且在北进和南进尚未揭晓之先，更有先行向中国加紧军事政治进攻企图解决"中国事件"之可能。不过，有一个问题是很清楚的，就是日寇基本上尚是站在德意方面，所以德意也就以承认南京伪政权来鼓励他。这种行动，说德意推动其北进也可，说德意拉紧其离开英美也可，说德意企图帮助解决"中国事件"也可。然而中华民族的抗战，却决不会因为德意的帮凶而气馁，而停止。要是有这样的人，就不配做中华民族的优秀儿女。

　　世界显然是向着两个集团两个阵线的方向走的。虽然世界战争的变化正多，法西斯挑拨英美反苏的阴谋不会停止，法西斯国家对世界的进攻还没有遇着最后的致命的打击，纳粹德国在苏联还会有一些暂时的军事收获，但是中苏英美日益站在一起，已为明显事实。我们坚信：世界反法西斯阵线终会形成，苏联终将在反对纳粹德国的战争中获得胜利，而世界的法西斯强盗终将失败，世界各国人民争取民族独立解放，争取民主自由的战争，也终将得到胜利。

　　我们中国，十年来首先遭到法西斯日本的侵略和蹂躏，四年来又坚决站在反对东方法西斯的战争最前线，经验使我们坚信：日本法西斯强盗必败，抗战的中国必胜。

（三）

　　然而，胜利是我们的前途，要达到最后胜利，还须经历和克服许多困难过程。我们曾说过，抗战第四年是我们最困难的一年。在这一年中，我们曾经遇到法兰西失败后国际上的困难，我们也经历了国内的种种困难。这些困难，有的已成过去，有的尚未克服，有的还在继续增长。我们必须认识：四年抗战，胜利的基础是打定了，长期抗战的信心是更加坚强了，但我们不能讳言的，是抗战中的困难还多，弱点还大。

　　首先在敌我两方，日寇虽然失道寡助，但也不是一无帮手，德意法西斯及其所豢养的傀儡国家，至少还在那里为他虚张声势；我们虽然得道多助，但同情我们的友邦，如英美，对日寇还有人存着若干幻想，援助我们还有若干困难，而他们与苏联的接近也还在开始。

　　次之，在战争方面，我们的原则是军事第一，胜利第一。但我们民族中间，也还有一小部分人存在着对于抗战的动摇观念，他们对于长期抗战，有些不耐，对于敌人诱降，发生动摇，对于敌伪挑拨，表示响应，对于国际调解，发生幻想：这都是极有害于抗战的观念和分子。同时，我们还有人存在着等待胜利的观念，他们等待敌人撤退而不努力准备反攻，等待外援而不重视自力更生，等待敌人南进或北进，而疏忽我们自己的警戒，等待有利于我的世界变局，因而悲喜随人，失去独立自主的精神。尤其在皖南事变后，我们更忽略敌人进攻，于是信阳出击，沿海进攻，中条山扫荡，敌人便利用我们这种弱点乘虚而入了。军事是最大意不得的，一疏忽，一放松，一等待，便会涣散我们的战斗意志，减弱我们的军事戒备，忽视我们的训练学习，松懈我们的战斗生活，动摇我们的抗战信心，这是十分值得警惕的。

　　再次，在政治上，我们的弱点更大。中国政治既称民主，战时又应集权，但我们在应该民主的地方，如人民的合法权利却常受非法干涉，人民的战时动员却常没有发动广大群众参加，而在应该集权的地方，如政府组织却尚不合战时体制，国家政令又常受着党部的干涉和特务机关的破坏。国民参政会及省县参议会，如果使他们成为民意机关，便应提高职权，试行民选，以扩大政府的基础；如果使他们成为政府集权的辅助机关，便应选拔各党各派无党无派的真正人材，辅佐政府，赞襄国事，这便需要人少、任重、会勤、议事务其大并务其精，以巩固政府的威信。党派的团结是全民族团结的杠杆，但在野党的公开合法尚成问题，时被特务机关非法捕杀。武力是用于对外的，但不幸事件却接连发生，至今还有抗战而得不到公平待遇的部队。服兵役是中国男同胞应负的天职，但因为办理未得其人，未得其门，致使群众未能自觉的从军，使四万万五千万人的国家，还发生兵役的困难，这是我们应该自责的。还有，战时的政治机构，贵简单而不贵复杂；机关应集中而不应重床叠屋；职权应专而不应一事分作数人，或一人又管数事，致相互矛盾，相互牵制，一事难成；业务应找专家而不应用非所学，或无所不管；用人应用而不疑，疑而不用，而不应善善而不能用，恶恶而不能去。我们承认：政府是抗战的政府，领袖是抗战的领袖，我们应该拥护，但是这些政治的弱点和历史遗留下的官僚制度残余，还障碍着我们抗战的政治设施，要求我们必须予以坚决的改善。

　　更次，在经济上，我们的困难还多。国防工业是我们最重要的部门，但也是我们最弱的部门。我们一切生产计划，交通运输，国外输入，专门人材的培养，还不能配合着国防工业的需要。在抗战初期，我们便主张建立国防工业，直至最近始被重视，然而，实际上国防工业的生产并未加多，甚至连国防工业所最需要的原料，都在市场上堆集着，这不能不说是一种奇异现象。主要的原因，实由于建立国防工业的信心，在政府中甚至于在主管部门中还没有坚强的建立起来。自给自足的小工业和农业的生产的增加，也还未能大大的发展起来，这一方面由于政府在这上边所用的人力财力，还没达到应有的程度，另一方面则由于官僚资本障碍了中国民族资本及合作事业的发展，官僚资本的危害，最主要的是投机事业，他利用一切权位和便利，破坏了民族工业的正常发展，破坏了银行的正常业务和资金内流，破坏了商业市场的正常贸易，造成了恶性的通货膨胀，影响了物价的昂贵，助长了营私舞弊和贪污腐化，破坏了国家的紧急需要及其财政经济政策。在粮食上，我们如集中主要火力于反对土豪大户的囤集居奇，那末，我们在国民经济上，便应集中火力反对这种危害最大的官僚资本。我想，政府机关中的高级官吏，军队中的高级将领，如果能彻头彻尾的不进行投机事业，不囤积居奇，那将是大有助于抗战中国国民经济的发展。

　　以上这一切，都是我们抗战四年中未能克服的主要困难和弱点。我们希望，抗战的第五年，将是我们克服困难的一年，也是真正准备反攻的一年。这一年将决定世界的命运，也将决定中国的命运。

（四）

　　为着克服困难，准备反攻，我们在进入抗战第五年的开始，必须认识我们长期抗战的胜利基础。尤其是我们四万万五千万人的坚固团结，这是我们战胜日寇的基本力量，同时也必须检讨我们抗战的经验、缺点和弱点，以便我们能在克服这些困难中胜利前进。

　　我们必须继续坚持长期抗战，直到驱逐日本法西斯强盗出中国为止。我们必须反对中途妥协和对于抗战动摇的一切观念，反对等待胜利而不努力于自力更生的苟安心理，反对专靠外援而不加强自己反攻力量的依赖心理。

　　我们必须努力于全世界人民反法西斯阵线的联合，最大的同情寄予苏联，声援苏联，努力争取英美的援助，要求美国对日全面禁运，共同制裁侵略，以孤立日寇，以打击世界的法西斯集团，并加紧对于苏联英美的联合。

　　我们必须加强军事的力量和装备，提高军事技术的教育，号召我们的壮丁和青年，服兵役、进军校、习航空、学驾驶坦克车装甲汽车，学一切军事技术。我们必须加强各个战线上的戒备，提高我们的士气，进行军队中及居民中的抗战教育，组织战役上的反攻力量，以便击退敌人从任何方面的进攻，并收复一些据点。我们必须加强对于敌后游击区域游击部队的领导和帮助，承认他们抗日政权及一切抗日政策，以便有力的打击敌伪扫荡，破坏敌伪政权和瓦解敌伪军队。我们一切服从于国防生产，健全国防工业的领导权，动员一切人力物力财力，增加国防工业的生产。只有这样，才能真正的准备起我们的反攻力量，才能保障我们最后的战胜敌人。

　　我们必须坚持抗日民族统一战线，坚持各党派的合作。我们愿尽一切努力，拥护国家的统一和进步，反对国内的分裂倾向和军事行动。我们要求抗战中的民主，人民的合法权利，各党派的公开存在，思想自由和学术自由，反对一切非法的秘密的捕杀，反对摧残青年。我们主张战时的政治集权，但不是包办，更不许党部和特务机关的无理干涉。我们要求政治上的平等，对各地方政权、对各军队、对各种抗日的人民团体，应不分党派关系，一律平等待遇，不得有任何歧视。我们要求彻底的动员和组织群众，依靠群众的基础，进行一切征调劝募和动员的工作，以保证抗战力量源源不断的补充。我们主张政府机构合理化。专责、专业、专人、专信，以巩固和灵活政府对抗战的领导，以肃清官僚制度的残余。

　　我们认为一切应为着国防工业，反对将目前战时的财政经济政策与国防建设分立起来，或仅仅看成是他的一部分。我们主张扶助民族资本，反对官僚资本。我们必须有效的控制通货膨胀，严格的统制对外贸易，保护工商业的发展，以大力扶助中小企业和合作事业，发展农村经济，以力求自给自足。我们必须依靠农民的组织和动员，反对土豪大户的囤积居奇，彻底的解决粮食问题。我们必须相当的改善劳动者职教员及公务人员的生活，以增加生产，增强教育和行政的效能，以利抗战。

　　这就是总结四年抗战的主要经验，这就是对于抗战进入第五年的希望。我们号召全中国人民应为这个希望努力，我们中国共产党人，更愿为这个希望奋斗不懈！

　　最后的胜利是一定属于我们伟大的中华民族的！



　　＊原载一九四一年七月七日重庆《新华日报》。 



