# 团结起来打敌人！

中文马克思主义文库 -> 周恩来
团结起来打敌人！
（一九四一年七月二十日）

中共中央为抗战四周年纪念宣言上曾指出，法西斯日本"反苏之危机固已增长，灭华之方针，则决不放弃，南进以侵略英美荷澳之野心，亦依然存在"。现在日寇内阁又改组了，不管其是在积极准备北进，或者南进，或者南北并进，但其灭华之方针决不会有任何变更，而且还会先来个西进。且即使日寇北进的方针定了，甚至先来个对海参崴的海上封锁，他也要先行或者同时扫荡华北，甚至突入西北，以巩固其北进攻苏的陆上根据，假使敌人不北而南，或者兼行南进，他也要以加强安南的军事根据地和扰乱甚至切断我西南交通为先决条件，或者说作为与英美讲价的条件。因此，不论在任何情况下，我们总应准备敌人西进，乃至迎头打击敌人西进，这才是万全之策。等待胜利，总是一种最有害的心理，尤其是专门希望日寇打别人，最是一种没出息的想头，而且对于联合友邦，争取外援，也颇不合乎情理。并且我们已经单独的打了四年，即使敌人已经发动了北进和南进，我们也应更加努力作战，反攻敌人，以配合友邦行动，这不仅称得起患难相共的朋友，并且也才能争得出我们独立解放的胜利前途。所以不论敌阁如何改组，敌人的行动如何改变，我们的任务总是打敌人。那些天天争论于敌人究意北进还是南进，天天希望敌人北进或是南进，甚至天天等待敌人北进或是南进以解决我们困难，以决定我们对内政策的人，在现实的演进中，不仅有时会使希望落空，有时会使高兴过度，并且根本上最有害于自力更生，最有害于争取胜利。

这种思想，便是从国际反法西斯侵略的任务上看，也是不妥的。我们抗战四年，久已成了东方反法西斯的先锋。现在全世界都正在或将要走上反法西斯的战场，而纳粹德国正是法西斯头子，日意是其帮凶，苏德战争又是世界战争的主体，中国抗战则已经起了牵制世界法西斯帮凶的作用。因此，为着使全世界集中目标，集中力量，打击世界法西斯头子，不仅苏联，不仅英国，便连美国也要用极大的力量去作战，去协助，而对于日本如果它还不北进南进，我们更应继续担任牵制日本的光荣任务。这是中华民族值得自豪的侠义行为，这是中华民族见义勇为的优良传统。所以我们现在对于英美苏联，不是要求他们对日作战，而是要求他们加紧援华，对日禁运，共同制裁法西斯侵略。如果敌人一旦北进或南进，我们更应努力牵制敌人，使其陷于两面乃至多面作战的困难，以尽国际反法西斯侵略阵线的主员之一的责任，那才不愧为东方反法西斯的先锋，才真能以中苏英美为中心结成全世界反法西斯侵略的阵线。

还有，从中国抗战内部来说，也只有团结起来打敌人之一道。中国抗战的对象，是要驱逐日寇出中国，现在更加上与世界反法西斯战争连接一起。如此巨大任务，非团结起全中国人民，全中国军队，不能达到。中国抗战的目的，是要实现三民主义的新中国。如此巨大任务，也非集合全中国人民的努力，各抗日党派的才智，通力合作，不能达到。

为要打倒这个对象，达到这个目的，首先必须加强军事力量，这就须全中国的武装力量，不论前线后方，不论战区敌区，不论中央地方，不论属于任何系统，都应团结于最高统帅指挥之下，一致杀敌，而不容有任何摩擦，任何歧视。如果有人说，最近第十八集团军，又在晋鲁等地擅自行动了，我可负责答复他们：为配合中条山作战，十八集团军部队，曾向白晋路平汉路南段袭击敌人，但任务完成后，便立即退还原防，而山东荏平，乐陵，惠民等县，原属十八集团军作战地区，友军何以开入，何故发生冲突，而究竟有无其事，十八日电十九日便登报，不仅朱总司令不及呈覆，连我也未得到事前任何通知，这就是事实真相，这就叫"擅自行动"。不过我们总是要求团结，而不是要求分裂；要求一心杀敌，而不是要求分心对内。只有这样，才能团结杀敌，而不致给敌人造任何分化机会。

次之，必须加紧国防建设，这也须团结起一切建设的力量，以建立国防工业的始基。尽管今天建立国防工业的可能性很低，但并非一无可能，一无所有。我们纵观世界战局，法西斯侵略国家，杀人凶器之多且强，奴役人类之残且暴，直欲将世界文明一齐毁灭。如果我们再不从此得出教训，再不从此努力国防工业的建立，而仍听其自然，诿诸客观困难，那真是自暴自弃，甘为人奴。没有自力更生的力量，不要说不会将敌人赶走，即使敌人自己崩溃了，或者友邦把它打败了，我们也不会得到彻底解放，强盛的立于世界。所以我们自始就应该不分国营私营，不分厂方工方，不分技师专家，都应团结一起，集中力量，为着加紧国防生产建立国防工业而斗争。

再次，必须加强政治民主化，这更须不分种族、阶级、党派信仰、性别，而团结在民主旗帜之下，一致努力。有人说，以中国之大，各党派外还有着最大多数无党无派的人民，他们最能表现出中国人民的公正意志。这是非常正确的。唯有最能尊重人民公意的人，才是最富于民主思想的人，才是最能团结的人。要想从政治上动员民力，参加抗战，就必须团结起中国的广大人民，听取他们的意见，顾及他们的生活，发展他们的组织，给他们以合法自由，然后才能得到他们踊跃从军，努力服务，加增生产，热心献粮的好处。又有人说，政府应与现有纠纷之党派提议协商，劝告合作。这也是非常正确的。我们所望的也正是"加强各抗日党派合作，调整国共关系"（中共中央七七四周年宣言），而不是肃清异党分子，或者说，对共政策已确定，只需待时而动，无再行考察之必要。我们所望的是调整关系，而不是制造纠纷。我再重复说一次："团结则存，分裂则亡；合作则胜，独霸则败。"这是今天中国抗战的铁则。谁不遵守这个铁则，谁将成为万世的罪人。

总之，今天的国际形势，今天的国内情况，都须要我们团结起来打敌人。不打敌人，我们没有别的出路。不团结起来，我们无法打败敌人。

我们号召全中国的人民，全中国的军队，全中国的党派，大家向着一个目标前进，这就是：团结起来打敌人！

＊原载一九四一年七月二十日重庆《新华日报》。 

