# “九一八”十年

中文马克思主义文库 -> 周恩来
“九一八”十年
（一九四一年九月十八日）

东北沦陷，整整十年了！十年沉痛，在今天，对于全国同胞，对于抗战将士，特别是对于在敌蹄蹂躏下过着奴隶牛马生活的东北同胞，不能不从悲惨的回忆中发问：我们什么时候才能打到鸭绿江边，驱逐日寇，消灭伪满，将青天白日满地红的国徽，重新插在白山黑水之间？尤其是流亡在关内的东北同胞，十年风霜，使壮者老了，年青的变成壮年，孩提之意也长大了；他们更会慷慨悲歌："哪年哪月才能够回到我那可爱的故乡！？"真的，没有一个热恋着故乡的东北人士，不想"打回老家去"的，也没有一个坚持抗战到底的全国同胞，不想"收复东北失地"的。家国之痛，流亡之惨，切齿之恨，复土之念，诚十年如一日。我们于此，敢以最大的关怀和眷念，遥寄给在苦难中的东北同胞和在苦斗中的东北义勇军。我们更以最大的同情和热忱，致敬于在苦干中的东北流亡人士：你们是东北的孑遗，你们是东北的孤臣孽子。海可枯，石可烂，你们的民族正气，是永远不会磨灭的！

九一八是世界侵略战争的导火线，而七七事变，更是日寇在世界侵略战争中的第二次信号。我们抗战也四年多了，抗战目的，是要达到中国领土主权的完整，这就是说：起码要恢复九一八以前的状态。不赶走日寇出境，不恢复东北失地，决不能停止抗战。这是全国军民一致的呼声，这也是东北同胞日夜萦思十年奔波的目的。民国二十七年九一八纪念，蒋委员长在其告东北同胞书中指出："这整整七年中间，尤其是去年全国抗战以来，我全国同胞和将士所受无限的牺牲和无比的痛苦，为的什么？为的是我们的东北和我们东北的同胞；为的是要求得中国独立自由，要恢复我们东北的失土，拯救我们东北的同胞。"民国二十九年九一八纪念，蒋委员长在其告全国同胞书中，更指出："我们九年来艰苦奋斗，三年余奋勇抗战的目的，就要为恢复我们国家的独立主权和领土，要解救我们三千余万东北同胞。......我们今天多抗战一天，就是恢复我们国家独立自由和达到我们雪耻复仇目的的日子更接近一天，也就是收复东北和解放东北同胞的日子愈接近一天。"今年九一八纪念，蒋委员长在其告全国国民书中又指出："我们流血的目的，自始至终，就是要保障我们中华民族的独立生存和领土主权与行政的完整，亦就是誓万死，排万难，要恢复我们东北的失土，与拯救我们东北的同胞，来洗雪'九一八'以来的仇恨和耻辱。""如在中国境内还残留着敌军之一兵一卒，而我们中国的领土，主权与行政的完整还没有完全恢复以前，我们的抗战，就一日不容停止。"这一切，都是抗战四年来取得全国统一团结共同奋斗的国策，也就是九一八十年来全国爱国同胞奔走呼号所坚持的救国方针。民族领袖说出全国人民心坎中所要说的话，谁能不拥护我们的民族领袖？现在的问题，便在如何使这些主张坚持下去，实现起来，好日益接近于"驱逐日寇出境，援救东北同胞"的胜利。

今年九一八前夜的国际形势，从苏德战争到罗丘宣言〔１〕，本已澄清了国际反法西斯蒂反侵略的阵线，不意日美谈判一起，又复使太平洋上的疑云密布。日美的基本矛盾，本是无可调和的，我们尤觉得在罗丘宣言之后，美国政府更不能以牺牲沿太平洋各国的民族利益，尤其是中华民族的利益，换取对日的妥协，而使宣言中的八项主张成为骗人的空谈，因为这不仅会使东方求解放的民族失望，而且也会使正在纳粹铁蹄下喋血奋斗的十四个民族国家同样感到失望。但我们却也不能轻于置信日美谈判一无妥协可能。假使日寇表面接受海洋自由、门户开放的原则，甚至伪装承认停止武力南进的要求，难道他不可以设想骗取南洋的利益均沾吗？假使日寇在答应不妨碍美国援苏，难道他不可以设想从美国骗取同样的物资输日，以便待机北进吗？这在表面上，或者会有人竟解释与罗丘宣言第四项"对于贸易及原料之取得俱享受平等的待遇"之原则并不冲突，而实际上，日寇骗取这些物资，一方面正好如过去四年一样，用在侵华战争的火线上，并轰炸到中国的后方，另一方面，正好拿来加强日寇的国防力量和生产，转去威胁英美，待机南进。此不仅大失中国人民同情，抑且养虎噬人，自食其报，以美国今日之处境，罗斯福总统何致必欲步张伯伦〔２〕之后尘？！或谓罗斯福对日的试探谈判，意在拖延时日，一方面可以打破国内孤立派对日妥协的幻想，以便逐渐的增强太平洋上的国防戒备，另一方面，可以加强日寇内部矛盾，求其远离轴心，好拆散他们目前的东西策应。这种用心虽苦，但我们可以断言必致得不偿失。一月来，日美谈判在全世界所造的印象，不能不是罗丘宣言后的损失，谈判中的妥协气氛，更给美国一部分上层分子以幻想，而减弱太平洋上的戒备，同时，更可使日本少壮派感觉美国易与和可欺，而愈加肆无忌惮。所以，不论从九一八日寇侵华的痛史中，不论从世界法西斯侵略的教训中，我们都可看出，日美谈判是罗丘宣言之后一件不智之举，而且有上日寇大当的危险。我们认为：在德苏战争已经打了快三个月的今天，英勇坚强的苏联军民，已经为英美苏在西方奠定了灭亡纳粹统治的胜利基础，在东方，英美正应用其余力，援助中国，对付日寇。以封锁代替谈判，以制裁代替妥协，使一时日美谈判的疑云消散，这是全世界反法西斯蒂反侵略人民的一致愿望。

然而不管怎样，日美谈判决不能影响我们独立自主的抗战，决不能动摇我们抗战到底的决心。蒋委员长在廿九年双十节告全国军民书中说得很清楚："我们抱定信心，不问环境如何，国际形势有利的时候固然要努力，就是在过程中间，国际上对我抗战形势不利的时候，我们更是要奋斗到底。"何况现在国际形势，在前途上看来，显然是有利于反侵略的国家，而日美谈判甚至妥协，不过是一时阴霾，世界上反侵略胜利的光明，并非遥远。只要我们坚持东方反侵略的大纛，我们是东亚反侵略的先锋，谁也不能改变我们的地位，谁也不能使我们屈服。去年九一八纪念，蒋委员长曾指出："由于这九年来尤其是欧洲战事发动以来的国际事实，可以证明，任何民族只要他能自力图强，则辛苦复国，多难兴邦，真是计日可待。而转弱为强，更是常见的事实。另一方面，更证明精神不屈，为克敌制胜的要素，如果精神一经屈服，这个国家就要万劫沉沦，不可挽救。所以我们今天要外察事变，内省天职，要知道世界上没有比屈服更痛苦的事，屈服的结果，只有灭亡。"（告全国同胞书）这个指示，在今天更显出他的重要。我们不仅不应该因为国际形势一时一地的不利，而动摇，而灰心，甚至精神屈服，并且更重要的还在于认识多难兴邦，自力图强之可贵。世界上没有不靠自力更生，专靠外援而能战胜强寇收复失地的。我们固然决不能离开世界而孤立，而独干，但我们更不应将我们最大的甚至于一切的注意力，放在国际的变动上面，将我们全民族的命运，押输赢于他人的赌博场中；这是无可救药的奴隶根性，决不是我大中华民族抗战四年来所发扬的独立自尊的精神；所以欲纠正目前因日美谈判所引起一种惶惑和屈服的心理，必须从加强自力更生的信念入手。四年来，直到今春为止，美国何常以军火援华，美国输日的飞机汽油和军火原料何常停止，但中国的抗战，并未因之中断，并未因之屈服，现在即使情况有变，也不会恢复到今春以前的状况，我们何至于反而无力抗战？如果我们肯从加紧团结入手，排斥一切挑拨分裂的企图，则日寇的政治攻势，将必归于失败。如果我们更加强军事力量，扩大国防生产，在"军事第一""胜利第一"的原则下，改善一切政治经济财政教育的设施，进行民众动员，采用民主制度，以便集中全国的人力财力，用于反攻的准备，则某些地区的恢复，二三重要据点的夺回，在目前并不是不可能的事。我们果能在事实上日益收获胜果，而谓反侵略的友邦，仍不愿助我拖住日寇，反而逼我屈服，宁有是理？！因此，我们认为：一切须返求诸己。我们也很同意郭外长〔３〕本月十五日谈话中所指："近来关于美日试探性质之谈话，颇多不同之传说，有些是推测性的，有些吾人相信是具有作用的，而此种具有作用之传说，其目的欲在引起中国人民之疑虑。"推测性的传说，是反映某些人对于日美谈判将影响中日战争的忧虑或悲观，这应该以自力更生的信念回答之。具有作用的传说，是有意或无意的传播了敌伪乃至某些分子的谣言攻势，以动摇我们抗战阵容，这必须以揭穿这种阴谋，打击之。这在今天纪念九一八十周年坚持"消灭伪满，收复东北"的时候，尤其有严重的意义。

我们中共党人，历来是坚持自力更生抗战到底的方针。十年来，我们呼吁团结御侮，抗日救国。抗战后，我们更主张加紧团结，加强国力，坚持抗战到底，反对中途妥协，打到鸭绿江边，收复东北失地。在今天，我们更应强调自力更生，准备反攻，反对俯仰依人，反对悲观失望。

在纪念"九一八"十年的今天，我们中共党人，再一次向全国声明：不论国际形势如何变化，我们总是坚持抗战到底，不达到驱逐日寇出境，决不罢休！任何困难，任何敌人的进攻，包围，封锁和烧杀，都不能丝毫动摇我们抗战的意志！即使没有任何的援助和接济，我们都决心与敌人血战到底，坚持敌后的一切抗日根据地。最近第十八集团军在华北华中敌后特别是在晋冀察区的反敌"扫荡"的血战，便是明证，他们是蒋委员长"喋血抗战"号召之最响亮的响应者。

在纪念"九一八"十年的今天，我们更向东北同胞声明，特别向流亡的东北人士声明：我们誓愿和你们肩并肩的抗战下去，一直打到东北原野，一直打到鸭绿江边，把东北人民从敌伪铁蹄之下解放出来，把东北领土归还到中华民国的版图，这是我们纪念"九一八"十年的决心，也正是愿大家一齐努力，东北四省永远是我们^^^^们必须依靠农民的组织和动员，反对土豪大户的囤积居奇，彻底的解决粮食问题。我们族的！

＊原载一九四一年九月十八日重庆《新华日报》。

注释

〔１〕罗丘宣言指美国总统罗斯福同英国首相丘吉尔一九四一年八月十四日在大西洋的纽芬兰海面会谈后发表的联合宣言。当时德、日法西斯的侵略已使英、美两国受到损失，中国、苏联和全世界人民的反法西斯斗争空前高涨。英美两国在宣言中宣称：两国不追求领土或其他方面的扩张；尊重各民族自由，选择其政府形式的权利；赞同摧毁德国纳粹暴政和解除侵略国家的武装等。宣言的发表有利于世界反法西斯联盟的形成，为日后建立联合国打下基础。这个联合宣言也被称为《大西洋宪章》。

〔２〕张伯伦参见本书《论目前抗战形势》一文注〔５〕。

〔３〕郭外长指郭泰祺。郭于一九四一年四月十日至一九四一年十二月二十七日任国民党政府外长。

