# 太平洋的新危机

中文马克思主义文库 -> 周恩来
太平洋的新危机
（一九四一年十月十九日）


　　近卫〔１〕下台，东条〔２〕上台，滚的快，上的也快。其人其事其时，都说明日本法西斯军人再也不能忍耐目前沉闷拖延的局面，而必须自己出马，采取冒险的行动了。

　　本来，苏德战争起，近卫三次组阁，牺牲松冈〔３〕及政党人物，实行财政经济新的措施，派遣大兵入我东北，加紧扫荡华北，已经表示其是在积极准备北进。不过，要北进，必须稳定南洋，妥协英美，避免两面作战。要北进，必须骗和中国，免致腹背受敌。要北进，必须等待时机，免致损失过大。这就是近卫第三次组阁的方针，也就是据此以说服法西斯军人，据此以取得现状维持派支持的法宝。因此，这三个月中，近卫内阁除加紧准备北进外，首先便与维希政府〔４〕缔结越南联防协定，增兵入越，虽因此引起英美封存日寇资金，亦仍然故作隐忍的进行日美谈判，期待有利于己的妥协之到来。不料谈判两月余，毫无成就，且反使美国窥破日寇用心，造成僵持局面。对我中国，在日美谈判开始时，日寇故造日美妥协将逼成中日妥协的谣言，企图以此动摇我抗战阵线，不料竟遭到我民族领袖蒋委员长在"九一八"十周年纪念告国民书中的迎头痛击。蒋委员长申明"非完全驱逐寇军于我们国境以外，彻底消灭他侵略的野心，我们的抗战，是决不能停止的。"这一申明，实代表了我们四万万五千万人民的公意，亦代表了我们全国将士的战志和决心。日寇因此恼羞成怒，发动了长沙郑州两战役。不料一由其南进北进之举棋未定，二由其轻视我军过甚，竟演成长沙惨败宜昌被攻郑州胶着及华北扫荡无功的状态，影响于其国际的威信至大。接着，纳粹德国又在进行对苏的第四次猛攻，苏联人民正面临着严重的危机，似乎日寇北进的时机已等到了，于是在平沼〔５〕被刺中野〔６〕狂吠之后，纳粹德国压力之下日本法西斯军人便不能再耐，终于将军人内阁抬出场了。

　　日寇新阁名单虽尚未揭晓（截至写稿时止），但从东条英机担任新阁首相及其登台之原因和背景看来，已可知新阁之大概趋势。这一趋势，便是太平洋新危机之到来。新危机的范围，决不会止于北进，日寇必然是以占领西伯利亚，囊括南太平洋，解决"中国事变"为其连贯的方针。本月十七日东京电，权威方面评论东条之组阁，亦说：日本之政策，为解决"中国事变"，建立"共荣圈"〔７〕及依附三国公约〔８〕之精神。建立"共荣圈"，就是包括南太平洋，排斥英美势力；依附三国公约，就是敌视苏联；"解决中国事变"，更是"万变不离其宗"了。在第三近卫内阁时，是想将这三项政策分别解决的，所以他一面积极准备北进，另一面则企图以日美谈判分散美苏联合，离间中美关系，以便其各个击破。但结果弄巧成拙，日美谈判陷于僵局，中国抗战更加坚持，英美援苏援华日趋积极，甚至影响泰国亲日态度亦渐有变，这不能不使第三近卫内阁归于失败，而代之以完全的军人内阁。东条于此，至少必有一个新认识，即是欲建立"东亚共荣圈"，必须使大陆与海洋一道解决，至少要连贯解决。东条原有对华对苏两面作战的主张，现在恐更有三面乃至多面作战的主张了。这就是太平洋的新危机。

　　有人会说，东条是旧阁的一员，且参与近卫对外政策的密议，故新阁对外政策尤其是对美政策，将无变更。这个意见是不对的。日寇政府每次改组所持以不变者，是其基本国策，亦即吞并中国独霸东亚的国策，至若实行这基本国策的方针或方案，则每次日阁改组均有变更，何况这次近卫倒台，内阁情报局已公开宣布"系由各阁员对执行国策之方针，缺乏一致之见解所致"，更何能谓无变更？！所谓缺乏一致者，很明显是在对内尤其是对外的方针上，有了现状维持派与法西斯军人派之间的分歧，而东条显然属于后者。现状维持派的方针，重在妥协英美，法西斯军人派的方针，重在依附轴心，近卫想利用两者的分歧，引前者骗取英美妥协，导后者积极准备北进，以便时机一到，他好对外各个击破。现在近卫既失败下台，东条继起，必将有所改变，可断言无疑。

　　又有人会说，东条的军人内阁意在威胁英美，实际上，他仍将继续对美谈判，求得妥协。这个意见，似是而实非。东条虽系法西斯军人，但向以智称，况希特勒虽在多面作战之中，仍懂得运用各个击破的战术，东条也不会一无所学，故他在组阁后，可能不仅不会取消对美谈判，而且还会继续运用亲美分子对美故示好意，同时，他也会摆出反美阵势，故作先行南进准备，以便软硬兼施，眩惑美国，使之犹疑不定，等到一旦北进，日寇便可少受美国海上的牵制。日本法西斯军人这种可能的做法，显然与近卫内阁的方针是有区别的。近卫想与英美成立真正的妥协，即使是一时的，也可使他达到孤立中国，放手北进的目的。现在法西斯军人内阁，于近卫失败之后，必然是要在准备多面作战的方针下，欺骗英美，先行北进。故近卫是以对外各个击破为战略，畏惧多面作战，而法西斯军人，则不怕多面作战，是以各个击破为战术的。从发展上看来，只要英美不上当，近卫的失败是必然的，而日本法西斯军人，则不管英美上当不上当，总是要向着冒险路上走的。所以太平洋的新危机，在日本法西斯军人内阁出现之后，是必然要到来的。

　　还有人会说，东条内阁，既重北进，对华侵占，必将减弱，或者说，将使我们易于反攻。这种看法，也很危险的。因为这不仅从日寇对华对苏战争之不可分性上看来，是不完全对的，便单从军事力量的对比和部署上看来，也是不完全对的。敌寇为着北进，可能从侵华的某些地区抽兵，甚至从某些城市撤退，但必须明白：撤退决不会影响对该地区的封锁（如福州之例），同时还要起动摇我抗战意志，涣散我反攻准备的作用；而抽兵更不等于放弃，也并不一定使我们易于反攻。宜昌之役，一方面，证明在敌人调动兵力时，我们有反攻而占领之的可能，但另一方面，又证明我们的力量也还没有长成到足以保住这种胜利的地步。故若认侵华战争将要减弱，不仅会松懈我们目前正在进行的战斗，并且会减弱我们对于反攻的积极准备，尤其会给动摇妥协分子以活动的机会。至谓易于反攻，也会不合事实，因敌人一旦北进，则我们所要反攻之点，亦必为敌人坚守之地，如果我们不从加强自己的军事力量着手，而误于易于反攻之说，必至坐失良机，不仅难于配合苏联作战，而且会堕入敌人麻醉的陷阱，给敌人造成顺序解决的各个击破条件。何况在敌人实行北进之先，也还有可能先图摧毁我们一些主力，破坏我们一些地区，然后再转锋北上呢？华北"扫荡"及长沙郑州诸役，便是明证。敌寇以轻敌致败，造成阁潮，我们却不可轻敌自骄，转滋国内纷扰。

　　因是，在苏德战争空前激化，日美矛盾愈加尖锐，中国反攻局部胜利，ＡＢＣＤ〔９〕的南洋封锁越发强化的时候，太平洋的新危机是异常的紧张了，而近卫坍台，东条组阁，更成为这一新危机的导火线，假使说，第三近卫内阁"为置日本于全面战争基础上之一步"，则东条内阁将要置日本于全面战争之更进一步了。不管东条新阁组成后，是先从北进开始，或是先行继续对美谈判，甚至先作南进姿态，或是先从压迫甚至诱降中国入手，或是先从解决其国内矛盾开始，其以武力建立"东亚共荣圈"的冒险方针，是确定不移的了。诚然，东条英机也并非日本法西斯军人十分得力的头目，其组阁也并非一定可以长命，而且必然的会反映其国内诸种矛盾，发生许多波折，甚至又为他人所代，这原是日本法西斯军人的必然命运。但必须弄明的是，这次日本军人内阁的出现，是日寇大冒险行动的信号，不论新阁是否属于法西斯一派，或是否全部属于军人，他的冒险行动，非遭到碰壁的失败，或是日本帝国主义的倒台是决不会停止的。日本的现状维持派虽也有若干的潜伏力量，虽也曾极力企图和缓一面，进攻一面，以避开多面作战的危险，但他们本身力量既敌不过法西斯军人派的嚣张，加以他们并不反对侵略的国策，又何能阻止法西斯军人之铤而走险？因此，对内也就无从取得广大反战人民的热诚拥护，对外也就无从取得反侵略国家的真正赞助，这在阵势上也就难以对抗在纳粹德国影响和推动之下的日本法西斯军人。所以日本的现状维持派，在第三近卫内阁中，只能起和缓的作用，并不能起决定的作用。今后他们如果不改变其侵略立场，他们只有愈益成为法西斯军人的附庸，而与之同归于尽，但也可看出在日本法西斯军人横冲直撞日趋失败之时，日本的现状维持派，也会有或多或少的觉悟分子产生，日益与日本反战人民相结合，与世界反侵略阵线相联系，以求日本的新生。

　　然而，日寇法西斯军人决不会自甘失败，太平洋的危机也不会自己消失，转变这一局势的关键，是在太平洋沿岸反侵略国家的共同奋斗。过去十年，许多国家已经放松了对于日寇的制裁，现在日寇侵略的火焰，快烧到大家的眉毛，太平洋沿岸的任何国家，都不应再存姑息之心，等待之念了。目前是大家一齐动手的时候了！英国远东军总司令波普翰将军说得好："吾人固不愿对日作战，但日本如坚欲作战，则吾人亦将准备应付。"美国政府派参议员泼贝尔谈话，美国应设法使日本军力无法调动，至少亦应准备实行还击。美国助理国务卿格拉第称，荷印已准备应付一切意外。我们希望这些意见，都成为英美荷印政府的意见，而将那些企图妥协轴心动摇和破坏国际反法西斯阵线的分子肃清出去。我们中国军民，在最高统帅坚持抗战到底的决心领导之下，只有加紧目前战斗，加强军事力量，巩固国内团结，积极准备反攻，以牵制和打击日寇任何新的冒险行动，其他任何轻视敌人等待胜利的观点，都不应许其存在。

　　日本法西斯军人新的冒险目标，当然以西伯利亚为最大可能，尤其是苏联在海滨省及北库页岛，更成为其首先要攻击的对象，但其进攻的究竟日期，则仍要看苏德战争最近的发展。日寇侵苏的战争如果发动，则其在开始时必企图以海陆空军之联合闪击，取得东海滨省，以便英美不及增援，中国不及配合，而战局已定。当然日寇这种妄想，定要遭遇苏联红军致命的打击。但是英美如能加紧准备，及时行动，我国军队如果积极战斗，则日寇慑于包围之势已成，环攻之局已定，纵使德国压力甚大，也未尝不可增加其犹疑顾虑的时间。时间总是有利于反侵略国家的。只要时间一长，欧战的局势会变，英美的准备会强，中国的力量会长，苏联的准备会多，而西伯利亚的严寒虽不能完全限制机械化部队的运动，但困难的增加，日寇是可以想到的。所以，太平洋沿岸各国，积极的准备，事前的制裁，虽不足以戢止日寇冒险的野心，但却可以延缓日寇冒险的行动，这便于大家有利，而且更有利于苏联集中主力，粉碎纳粹德国的第四次进攻。

　　目前英美与纳粹的斗争和援苏的行动，实不仅在西线，并已发展到东方，东方与西方的反法西斯阵线，已快联成一片了。现在一切反侵略反法西斯国家，胜利则同胜，败则同败，谁要躲避先后，谁将要成为反侵略战线中的罪人。中国独力抗战了四年多，苏联正处在抵抗纳粹德国进攻的主线，英国也打了两年，其他许多国家，亡的亡，降的降，欧洲的地图早已变色，非洲的战火也未熄过，只有美国隔着两洋，暂时尚置身于烽火之外，也就使美国的孤立派，只图私利，感觉不到国家的危急，人类的浩劫，而甘于接受纳粹第五纵队〔１０〕的蛊惑，反对援苏援华，主张妥协轴心，表面上则说反对参战。殊不知现在已没有战争以外的世外桃源了。希特勒主义如果统治了全欧，则以其优越的人力物力和技术生产，必然会侵入美洲，这点罗斯福及其领导的美国人民已经知道，但美国的孤立派及不少的大资产者却故作不知。现在日寇又要在太平洋作新的冒险了，如果美国仍然放任不管，则欧亚的烽火连成一片，孤立的美国，决不能在两洋的夹攻之中，再保持其光荣的独立战争的历史了。

　　我们认为，日阁的改组，应该警醒我们，使一切反侵略反法西斯的国家，更加团结，更加联合行动起来，而不应该让东西法西斯国家联成一片，将侵略烽火烧遍世界，贻祸无穷。

　　全世界的正义人士，一切反侵略国家，要对文明的世界负责，要对人类的子子孙孙负责，群起扑灭人类的公敌--东西法西斯蒂，现在是时候了。



　　＊原载一九四一年十月十九日重庆《新华日报》。

　　注释

　　〔１〕近卫，即近卫文，参见本书《二期抗战的重心》一文注〔１〕。

　　〔２〕东条英机（一八八四～一九四八）日本法西斯首领。一九三七年三月任关东军参谋长，残酷镇压中国东北人民抗日斗争。"七七"事变后，率领兵团侵入中国承德、张家口、大同等地。一九三八年五月任陆军次官，积极扩大侵华战争。一九四○年七月任第二、第三届近卫内阁陆军大臣，一九四一年十月组阁，兼任陆相、内相。十二月发动太平洋战争后，又曾兼任外相、文相、商工相、参谋总长等职。后因战局不利，引起重臣和海军等不满，一九四四年七月内阁垮台。日本投降后，美占领军以其为甲级战犯前往逮捕时自杀未遂，一九四八年经远东国际军事法庭判处绞刑。

　　〔３〕松冈，即松冈洋右，参见本书《论时局中之暗流》一文注〔８〕。

　　〔４〕维希政府，参见本书《国际形势与中国抗战》一文注〔１〕。

　　〔５〕平沼，即平沼骐太郎，参见本书《论敌寇两面政策》一文法〔４〕。

　　〔６〕中野正刚，参见本书《论敌寇两面政策》一文注〔７〕。

　　〔７〕第二次世界大战期间日本帝国主义妄图奴役亚洲各国、建立殖民大帝国的侵略扩张计划。一九四○年八月，近卫文内阁决定的《基本国策纲要》正式提出建立"以皇国为核心，以日、满、华的强国结合为基础的大东亚新秩序"，"确立包括整个大东亚的经济协同圈"。同年八月外相松冈洋右首次使用"大东亚共荣圈"一词。被列入"共荣圈"的国家和地区有：中国、朝鲜、印度支那，缅甸、泰国、马来亚、菲律宾、荷属东印度（今印度尼西亚）、澳大利亚、新西兰、英属印度（今印度、巴基斯坦、孟加拉）、阿富汗以及太平洋的许多岛屿等。中国和亚洲人民抗日战争的胜利，彻底地粉碎了这一计划。

　　〔８〕德意日三国同盟条约，参见本书《国际形势与中国抗战》一文注〔３〕

　　〔９〕ＡＢＣＤ的南洋封锁。Ａ＝Ａｍｅｒｉｃａ（美国）、Ｂ＝Ｂｒｉｔａｉｎ（英国）、Ｃ＝Ｃｈｉｎａ（中国）、Ｄ＝Ｄｕｔｃｈ（荷兰），即美英中荷四国。封锁，具体地指一九四○年日本强行武力侵占法属印度支那（今越南）北部后，美国谴责日本的这一行动，同时宣布冻结日本在美资产及限制以至禁止对日石油出口等措施。

　　〔１０〕第五纵队是一九二六～一九三九年西班牙内战期间隐藏在后方的反共和政府的间谍、叛徒等内奸的总称。一九三六年十月，西班牙和德、意干涉军联合进攻马德里时，叛军将领摩拉在广播中扬言，现有四个纵队正在进攻，并有一个第五纵队在马德里等着。以后，"第五纵队"便成为帝国主义在其他国家收买的叛徒和派入的间谍的通称。



