# 悼张淮南先生

中文马克思主义文库 -> 周恩来
悼张淮南先生
（一九四一年十一月九日）

淮南〔１〕先生逝世将三月了。每念公谊，迄难忘怀，而且也永不能忘怀。

我识淮南先生甚晚，西安事变〔２〕后，始相往来，然自相识之日始，直到临终前四日，我与淮南先生往来何止二三百次，有时一日两三见，有时且于一地共起居，而所谈所为辄属于团结御侮。坚持国策，至死不移，淮南先生诚五年如一日，五年来国内外风波频起，淮南先生尤首当其冲，而内波之险，谣诼之多，甚且侵及先生，但淮南先生辄处之泰然，绝未以一时"行情"，动其心志，变其神态。且困难愈甚，而先生之努力亦愈多，奔走亦愈勤。这种至死不息的卫道精神，淮南先生也是五年如一日。我与淮南先生初无私交，且隶两党，所往来者亦悉属公事，然由公谊而增友谊，彼此之间辄能推诚相见，绝未以一时恶化，疏其关系，更未以勤于往还，丧及党格。这种两党间相忍相重的精神，淮南先生是保持到最后一口气的。淮南先生为国民党的青年中委，但从未以此骄人，且曾任中央组织部调查科总干事，亦从未染近日"调查统计"工作的习气，在平日待人接物，尤极谦和，而青年英俊之气，亦未稍衰，这种动定咸宜的守身立世之道，淮南先生也是守之至死不渝的。综合先生生平，蒋委员长挽之为"赴义至勇，秉节有力"，可谓深知其人。在我印象中的张淮南先生，尚可续上"临事有恒，持躬至谨"两语，以为之赞。

两年来，我与友党人士相识，无虑数百，惟因工作关系，始终安危与共的淮南先生实为其最。今逢开会追悼之日，怆痛之表，不能自抑我对于往事的回忆。

我识淮南先生，虽在西安事变之后，但淮南先生奔走两党团结，却早在西安事变之前，临潼变作，淮南先生亦被羁留近两旬，我于事后知之，以不及谋面为憾。事平，先生复入陕，遂得相见。为商两党团结事，几朝夕往还，达三四月。彼时，甚至以后，参与其事者固不仅先生一人，唯先生为能始终其事。先生与我，并非无党见者，惟站在民族利益之上的党见，非私见私利可比，故无事不可谈通，无问题不可解决。先生与我，各以此自信，亦以此互信。每当问题争执之际，我辄以"敌人所欲者我不为，敌人所不欲者我为之"之义陈诸先生，先生亦常以此义相督责，故问题终得解决。先生这种忠于民族国家利益的精神，直贯注到他临终前致某先生书及我的谈话中，犹殷殷以两党团结为念，可见他在一开始奔走团结时所表现出的忠诚，并非偶然了。

其后，淮南先生伴我一登莫干，两至匡庐，凡所奔走，靡不与闻。因先生之力，两党得更接近，合作之局以成。"七七"变作，"八一三"继之，先生不仅忙于团结，且复奔走坛坫，未几，即出国赴苏，完成树立强援使命，而国内团结少先生参加者却近半年。接替之人意至，翻成议，肇成以后纠纷不解之局。迨先生归来，虽一再图谋挽救，终因事态已成，难于根本改变，居常引为憾事。然亦正因先生归，武汉之局，得以开展。于此，亦可见先生一身关系之重，在国，国内合作成，出国，国际强援树，去国事顿，回国势转，先生虽非决最后大计者，然其任事之勇，奔走之劳，已匪异人任了。

由武汉而重庆，淮南先生更是辛劳备至，一方面既忙于国际团结，另一方面又忙于国内团结。其时，国内一部分人士转移其眼光对内，而先生独持正义，力主以团结御侮为尚。民二十八年春，我有江南之行，是夏，复北返延安，均赖先生助其成，不幸，抵延后，我因臂出国就医，不与先生共安危者几及一年。此一年中，国内风波迭起，赖先生斡旋其间，得使局势未臻恶化，而我则养伤国外，真觉愧对先生。

去岁夏初来渝，复与淮南先生往还，而团结之局，亦日入险境，但先生努力不稍懈。今岁一月事起，二月报事〔３〕随之，三月为参政会〔４〕期，四五月有中条山战役〔５〕，此中风浪之险，环境之恶，为五年来所创见，先生劳神焦思，力维大局，备极憔悴。六月苏德战争起，方冀先生不得施展于国内者，将偿志于国际之活动，不意竟先一日而病倒。病榻相慰，初尚以纳粹第五纵队作祟戏语先生，孰料一病缠绵，竟致不起。数次视先生病，辄蒙以两党关系为问，临末一面，犹殷殷嘱我与某先生保持联络。先生既逝，联络乃似中断。嗣每遇风波，辄增先生不在之思，而每念先生，更兴安危谁共之感。

然而，抗战还在坚持，团结更须加紧，再求一如淮南先生者出而继任巨艰，赓续前功，应早在国民党贤明当局的选择之中了。可是，淮南先生已不愧为国家民族之栋梁，已不负于蒋委员长特达之知，即在吾党，亦深痛丧此良朋，何况国民党失此忠贞，其损失何可计算？！但我们相信，国民党尽多英才，尤多关心团结致力御侮之人，淮南先生虽死，其至勇至谨有恒有方的精神，犹照后人，必有许多继起者补其岗位，替其职守，这是我们最所企祷，也是全中国人民最所热望的了。

目前形势正如吾党毛泽东同志所说："全世界人类的任务，是团结起来反对法西斯，而全中国人民的任务，则是团结起来反对日本的进攻。现在这两种团结都有大大加强的必要。"而民族领袖蒋委员长更号召全世界反侵略各国联合奋斗，团结制敌。在这种国际团结的任务面前，我们国内团结，如不加紧，如再恶化，不仅无以兴奋世界反侵略各国的联合奋斗，抑且无以对前方将士被难同胞的流血牺牲，更无以继淮商先生五年来奔走团结戮力御侮的遗志。果如此，追悼又有何用？

但是，淮南先生的精神尚在，这是团结的象征。前线的血还在流，怎能分得出属于何党何派？碧血丹心，精忠报国，都是我们中华民族的优秀儿女，而淮南先生是其中杰出的一个。

我们追悼淮南先生，我们便应踏着淮南先生的道路前进。淮南先生的道路，就是团结的道路！

张淮南先生精神不死！

国际与国内团结万岁！

＊原载一九四一年十一月九日重庆《新华日报》。

注释

〔１〕张淮南，即张冲。参见本书《国内问题应迅速解决--致蒋介石》一文注〔２〕

〔２〕西安事变，又称"双十二事变"。在日本帝国主义加紧侵略中国，要把中国变为它的殖民地的危急形势下，以张学良将军为首的国民党东北军和以杨虎城为首的国民党第十七路军，在中国共产党的抗日民族统一战线政策和全国人民抗日运动的影响和推动下，要求蒋介石停止内战，一致抗日。蒋介石拒绝了这个要求，并亲自赶到西安积极部署"剿共"。一九三六年十二月十二日，张、杨联合行动，在西安附近的临潼扣押了蒋介石，实行兵谏。事变发生后，国民党内以何应钦为首的亲日派准备乘机发动大规模内战。中国共产党坚持和平解决西安事变的方针，并经过中共代表周恩来以及博古（秦邦宪〕、叶剑英等的艰苦工作，终于同张学良、杨虎城等一道使西安事变和平解决，促进了抗日民族统一战线的形成。

〔３〕从"皖南事变"以后，国民党反动派进一步迫害《新华日报》，报纸上的社论、专论和重要新闻全被扣押，以致每天的报纸都无法出版；他们还又按照国民党中央的特种会议对《新华日报》作出的"只准印，不准卖"的决定，扣留报纸，殴打报童。《新华日报》不得不在二月一日发表《本报重要启事》："本报因命令免登之稿件过多，难于编排，若勉强维持原有篇幅，既虚耗同人之精力，亦难副读者之雅望，因此，特定二月一日起改出一半张，诸希鉴谅是幸！"二月四日，国民党反动派殴捕报社的四名报童，无理没收报纸，五日，《新华日报》发表了《法纪何在！本报横遭压迫》的新闻和《我们的抗议！》的时评，但都被禁止刊登，只剩下标题。经过报社在三、五两日的抗议，才迫使国民党卫戍司令部在两份批件上分别签出了"已分令宪警机关严加制止"和"已分警宪查究，并对该报予以保护"的空文。

〔４〕国民参政会，参见本书《论目前抗战形势》一文注〔１０〕。

〔５〕中条山战役，即晋南战役。参见本书《关于中央社发表谈话的事实真相的声明》一文注〔１〕。

