# 我要说的话

中文马克思主义文库 -> 周恩来
我要说的话
（一九四一年十一月十六日）


　　为纪念郭沫若先生创作生活满二十五年，并庆祝他的五十生辰，我原打算写一篇专文献给他的。这个志愿立了好久，五个月前，我还拿了他的一部分著作，想在乡居期间，读他几本，然后好写出一篇有根据的文章来。不料今年夏天，敌机轰炸的次数特别多，人又病，事又忙，不仅文章没做，书也没读。时间是一天天的过去，书因为别人要读，也还了主人，可是，我的文章却依然没做。时间更一天天的逼紧，许多朋友的纪念诗文，也拿来读了，许多报纸的庆祝诗文，也提前发表了，于是使我志愿要做的文章几乎转成了急待偿还的文债。这一急，直临到郭先生生辰的前夕。这一急，直临到纪念日特刊发稿的最后关头。可是我面前铺着的依然是一张白纸，打破了我一向做文的惯例，然而我却决不能以偿债的心情，来做献给郭先生的纪念文章。

　　最后关头终于突破了，书既不能读，专文也不能写，但是临着这个日子，我却不愿"无言"，我还是说我平常所常说的话罢！

　　在朋友中间，在文坛上，通常喜欢将鲁迅和郭沫若相提并论。这原是一件好事，而且是应当做的事，可是有时候也成为多事。多事就是将无作有，将小作大，张冠李戴，歪曲事实，甚至分门别户，发展成为偏向，这便不应该了。

　　要并论鲁迅和郭沫若，我以为首先要弄明两人的时代背景和两人的经历，是多少有些不同的。

　　鲁迅的时代，是一半满清，一半民国的时代。他出身于破产的士大夫家庭，他受过封建社会很深的洗礼，他受过戊戌政变后的洋务教育，嗣后，留学东洋，又受教于章太炎先生，并参加了光复会。入民国后，他又做过多年北方官僚社会的小京官，也可说是闲差事。直到"五四"的前夜，他才得参加思想革命的运动，这就是新文化运动的骨干。从此以后，他就公开的成为宗法社会的逆子，士大夫阶级的叛徒，逐渐养成他在新文化运动中的领导地位，可是他自己却又那样谦诚的愿意做一个"革命军马前卒"。瞿秋白同志说得好："鲁迅从进化论进到阶级论，从绅士阶级的逆子贰臣进到......群众的真正友人，以至于战士，他是经历了辛亥革命以前直到现在的四分之一世纪的战斗，从痛苦的经验和深刻的观察之中，带着宝贵的革命传统到新的阵营里来的。"（瞿秋白：《鲁迅杂感选集序言》）所以毛泽东同志说："鲁迅的方向，就是中华民族新文化的方向。"蔡孑民先生也说："为新文化开山的，有周豫才先生，即鲁迅先生。"（蔡元培：《鲁迅先生全集序》）鲁迅所努力的，拿他自己的话来说，就是："自己背着因袭的重担，肩住了黑暗的闸门，放他们到宽阔光明的地方去，......"（鲁迅：《坟》）这就是鲁迅为大众而牺牲的精神。他自己愿做"桥梁中的一木一石"（同前），其实他就是这过渡时代的伟大的桥梁。

　　郭沫若的时代，却稍为异样了。他虽在少年时代，也是关在四川宗法社会里面的，但是二十岁以后，他走出夔门，几乎成为无羁绊的自由知识分子了，虽然他也如同时代的知识分子一样，过着贫困和流浪的生活。他的半商半读的家庭，虽也给他一些影响，但是三十年来大时代所给予他的影响，却有着异常不同的比重。就拿经历说，他既没有在满清时代做过事，也没有去北洋政府下任过职，一出手他就已经在"五四"前后。他的创作生活，是同着新文化运动一道起来的，他的事业发端，是从"五四"运动中孕育出来的。我们不能把郭沫若看成是前一辈子的人，而应看成是我们这一辈子的人，虽然他比鲁迅也不过只小了十一岁。我们也不能把郭沫若看成是两个时代的人物，而应看成是新文化时代的人物，虽然他在少年时代也曾舞文弄墨过一番。

　　因此，我说：郭沫若创作生活二十五年，也就是新文化运动的二十五年。鲁迅自称是"革命军马前卒"，郭沫若就是革命队伍中人。鲁迅是新文化运动的导师，郭沫若便是新文化运动的主将。鲁迅如果是将没有路的路开辟出来的先锋，郭沫若便是带着大家一道前进的向导。鲁迅先生已不在世了，他的遗范尚存，我们会愈感觉到在新文化战线上，郭先生带着我们一道奋斗的亲切，而且我们也永远祝福他带着我们奋斗到底的。

　　从这样观点出发，自然在并论鲁迅和郭沫若的时候，便不会发生不必要和不应有的牵连和误会了。

　　鲁迅先生在思想斗争和新文化运动上之非常可珍贵的革命传统，秋白同志在《鲁迅杂感选集序言》中已经指出四点：第一是最清醒的现实主义，第二是"韧"的战斗，第三是反自由主义，第四是反虚伪的精神。这都是非常之对的，我在这里不想再多说了。要说的是郭先生在新文化运动二十五年当中，所给予我的印象和我所认识的特点是些什么？

　　第一是丰富的革命热情。郭先生是革命的诗人，同时，又是革命的战士。他心中笔下充满着革命的愤火，也充满着对于人类的热爱。当"五四"觉醒时期，当创造社草创时期，他的革命热情的奔放，自然还带着很浓厚的浪漫谛克，这正是当时知识青年的典型代表。但是经过前一次大革命炉火的锤炼，经过十年海外的研究生活，他的革命热情已经受了革命理智的规范，然而他内在革命烈火，却决没有消失，相反的，愈蕴藏便愈丰富。一旦抗战号响，他便奔回祖国，他的革命热情，也就重新爆发出来了。四年多抗战，不论在他的著作上，在他的行动上，都可看出郭沫若仍然是充满着革命热力，保有着当年热情的郭沫若。可是时代究竟不同了，客观的事实不断的教训着我们充满了革命热情的郭先生，于是郭先生有时竟沉默起来了。革命的现实主义久已代替了革命的浪漫谛克主义，郭先生已到"炉火纯青"的时候了。

　　第二是深邃的研究精神。有人说学术家与革命行动家不能兼而为之，其实这在中国也是过时代的话，郭先生就是兼而为之的人。他不但在革命高潮时挺身而出，站在革命行列的前头，他还懂得在革命退潮时怎样保存活力，埋头研究，补充自己，也就是为革命作了新的贡献，准备了新的力量。他的海外十年，充分证明了这一真理。十年内，他的译著之富，人所难及。他精研古代社会，甲骨文字，殷周青铜器铭文，两周金文以及古代铭刻等等，用科学的方法，发现了古代的许多真实。这是一种新的努力，也是革命的努力，虽然有些论据，还值得推敲。如果说，连卢那察尔斯基〔１〕都不免在退潮时期入了迷途，那我们的郭先生却正确的走了他应该走的唯物主义的研究的道路。现在郭先生似乎又清闲了，恰好为纪念他的二十五年创作生活，大家主张集资建立沫若研究所，我想这是最好不过的事。复活过去的研究生活，指导这一代青年，提倡起研究学习的精神，以充实自己，以丰富我们民族的文化。郭先生，现在是时候了。

　　第三是勇敢的战斗生活。郭先生是富于战斗性的，不仅在北伐抗战两个伟大的时代，郭先生是站在战斗的前线，号召全国军民，反对北洋军阀，反对日本强盗和逆伪的；便在二十五年的文化生活中，郭先生也常常以斗士的姿态出现的。正因为这样，他才能成为今日革命文化的班头。也正因为这样，初期创造社才能为革命文学开辟了一条新的道路，才影响了后期创造社在思想意识上的一些论争。自然后期创造社的争论已多少表现着"文人的小集团主义"（秋白语），可是鲁迅先生也说"我有一件事要感谢创造社的，是他们'挤'我看了几种科学的文艺论，明白了先前的文学史家们说了一大堆还是纠缠不清的问题......以救正我--还因我而及于别人--的只信进化论的偏颇"（《三闲集序言》）同时，这里必须为周郭两先生辩白的，他们在北伐期中，谁都没有"文人相轻"的意思，而且还有"同声同应，同气相求"的事实。周先生在《两地书》中明说："其实我也还有一点野心，也想到广州后，......第二是与创造社联合起来，选一条战线，更向旧社会进攻。我再勉力写些文章。"在广州发表的文学家宣言，周郭两先生均列了名的。广州事件后，郭先生曾邀鲁迅先生参加创造刊物，列名发表宣言，不幸因新从日本归来的分子的反对联合，遂致合而复分，引起了后来数年两种倾向斗争的发展。这从"切磋"的观点上看来，未尝不是一件有收获的事，但是，因此而引起许多不必要的误会和无聊的纠葛，一直影响到在鲁迅晚年时候的争论，那真是不应该的了。有人说，鲁迅先生"韧"性的战斗多表现在他的著作上，郭先生的战斗性，多表现在他的政治生活上，我想，这种分法，并不尽当的。因为一个人的战斗性是发源于他的思想性格和素养的，文字和行为，不过是他的表现的方面罢了，并不能说这是差别的所在。真正的差别是鲁迅先生韧性的战斗，较任何人都持久都有恒，这是连郭先生都会感到要加以发扬的。

　　这些，也就是郭先生在革命的文化生活中最值得提出的三点，也就是最值得我们大家学习的三点。

　　我这不是故意要将鲁迅拿来与郭沫若并论，而是要说明鲁迅是鲁迅，郭沫若是郭沫若，"各人自有千秋"。

　　鲁迅先生死了，鲁迅的方向就是大家的方向！

　　郭沫若先生今尚健在，五十岁仅仅半百，决不能称老，抗战需要他的热情、研究和战斗，他的前途还很远大，光明也正照耀着他。我祝他前进，永远的前进，更带着我们大家一道前进！



　　＊原载一九四一年十一月十六日重庆《新华日报》。

　　注释

　　〔１〕卢那察尔斯基（一八七五～一九三三），苏联政治家，文艺评论家。一八九五年加入俄国社会民主工党。一九○三年第三次党代表大会后站在布尔什维克一边，参加一九○五年革命。斯托雷平反动时期一度接近马赫派。一九一七年十月革命后至一九二九年任教育人民委员，一九三三年任苏联驻西班牙全权代表。写了不少有关俄国文学、音乐、戏剧等方面的论文，并著有历史剧和剧本。



