# 太平洋战争与世界战局

中文马克思主义文库 -> 周恩来
太平洋战争与世界战局
（一九四一年十二月十三日）


一

　　太平洋战争〔１〕终于爆发了。自去年德日意轴心协定签订以来，日寇久已与德意法西斯东西呼应，遥相声援，今更承九一八的故智，学希特勒的惯技，不顾信义，竟在其大使野村来栖〔２〕会见赫尔〔３〕国务卿之前一小时，空袭英美各国属地，且远及于夏威夷和马来半岛。这种残暴的海盗行为，显然与希特勒征服世界的计划相配合，而且行为之无耻和讹诈，实较希特勒为尤甚。我们抗战四年半的中国人民，对此实增无限的愤慨和仇恨，同时，对我英美友邦及其属地的军民以及海外侨胞突受日寇袭击的损害，更寄予最大的同情和怀念。

　　现在战幕已展开了，英美及其属地的军民在日寇突袭之时，便已立即奋起应战。再没有疑问的，日寇从九一八以来，就是世界侵略战争的戎首，现在又做了太平洋大战的罪魁，他所进行的战争，完全是侵略的非正义的战争，而英美及其属地今日进行的保卫战，正如中国抗战一样，是正义的解放的战争。立在正义方面的，继着英美对日作战之后，截至昨日止，已有十九个国家对日宣战，四个国家对日绝交，范围之广，已遍及五大洲。这正是正义的洪流，太平洋上反日的民族统一战线伟大结合的开始。在侵略者方面，德意法西斯亦继日寇之后，对美宣战，美国乃最后的宣布对德意的战争，于是世界战争的壁垒最后分明了，侵略与反侵略的阵线最后形成了。我中国政府，不仅对日正式宣战，且对德意毅然宣战，这表示我们中国不仅为东方反侵略的先锋，且愿为东西反侵略阵线的枢纽。我政府领袖这种英明果断之举，实代表了全国人民的公意；这正如蒋委员长在其告全国军民书中所说："今日以前，吾人之牺牲奋斗，在于扫除侵入国境之敌寇，而今日以后，且将与英美苏联以及世界上爱好正义自由之各友邦，共同一致，并肩作战，以彻底消灭人类之蟊贼，共奠世界永久之和平。"

　　诚然，现在世界战争的战场虽有两个，但战争最后的归宿，却只能有一个：不是反侵略国家的全部胜利，便是侵略者的凶焰烧遍世界，中间的可能，亦即是侵略者与反侵略国家妥协并存的可能，是没有的。日寇这次冒险行动，虽是向南，但决非放松中国，亦非忘情北进，而是由于一方面受其轴心伙伴急如星火的催促，另方面又遇到反侵略国家日益紧密的包围，同时还受到其内部法西斯军人的叫嚣和责难，于是不得不南进，以牵制美英，以声援纳粹，以打开僵局。而德意法西斯，亦正因对苏攻势的失败，急欲阻止英国开辟欧洲第二战场，配合苏联反攻，更欲拆散苏联兵力，以便其得在冬季调动主力补整，准备明春再攻，所以他们在挑起日寇冒险以后，首先便放出暂停对苏攻势的烟幕弹，继着又宣布对美战争。这一方面是在挑动苏联东向，另方面又在动摇英美对日抗战的部署，这是希特勒的神经战，也正是东西法西斯的配合动作。于此，我们应该认清：东西法西斯早已勾结一起，我们反法西斯侵略的国家，更应联成一体，休戚相关。要知太平洋的胜利，亦即大西洋的胜利；欧洲的失败，亦即亚洲的失败。

　　今天的战争，已经是世界人类绝续存亡的战争，亦即是侵略者与反侵略者你死我活的斗争。今天的世界，正处在光明与黑暗的分野，文明与野蛮的对立，民主与极权的斗争，和平与暴力的对抗，我们坚信：只要全世界万众一心，胜利是一定属于正义方面的。

二

　　太平洋战争爆发方始一周，全世界正义人士及爱好和平的民族，都深信最后的胜利，必属于抵抗日寇的民族国家，而且也深信这一胜利与欧洲反德意法西斯的胜利是不可分的。我们相信这一最后胜利，不是盲目的乐观，而是有充分根据的。

　　第一，在民族自卫战争的立场上，只要是一个不甘心沦为法西斯奴隶的民族，都必会牺牲一切，奋斗到底，以求解放。只要看中国抗战的长期，苏联作战的彻底，英国的百折不挠，中国及南斯拉夫等国在敌占区域游击战争的发展，波兰、捷克、自由法国等流亡在外的奋斗不息，以及美荷等国今日的奋起作战，都表示了这一宁亡而不降，宁毁而再生的精神。这是人类的正义，有此正义，孰能亡之？反观法西斯国家，侵人国，毁人居，杀人盈野，抢掠一空，将统治放在刺刀之上，这样的局面，只能胜，不能败，只能无止境的流血战争，不容有任何的和平休息，因为只要败下来或者歇下来，内部问题就要发生，所以侵略者的战争，在终极是必败无疑。

　　第二，轴心国家以优种之说，耸动和驱使其国内人民，投身战争，向外侵略，然这究竟是全人类的最少数，而全人类之最大多数，正如蒋委员长所说十之九几全被认为侵略的对象，应该奴役的民族。以十分之一的人类欲征服十分之九的人类，其势决不可能，何况这十分之一中还充满了被东西法西斯所压迫的本国人民，一旦觉醒，其势必不可当。

　　第三，轴心国家的资源是贫乏的，即加上其所灭亡的欧亚十五六个国家，其资源也不足与中英美苏荷印及一切反侵略国家对比。从战争的直接需要说，一切主要资源，如煤、铁、汽油、橡皮、粮食、棉花、羊毛，大都握在反侵略国家的手里。单就太平洋上各国对比，日本对于上述一切资源，均大都仰仗于太平洋沿岸各国的输入。以资源贫乏的国家，向外作战，持久便是他最后的致命伤。

　　第四，轴心国的生产力和技术条件，在德国是向居前列的，加以他又统治了欧洲十四个国家，所以他能支持了两年多的战争，尤其最近五个月的对苏恶战，而尚未达到最后崩溃。但是，如果以英美苏生产力的总和对抗德国，则法西斯德国只有走向死路，这也就足以说明为什么希特勒要在罗斯托夫〔４〕失败之后，极力挑起太平洋战争，以引美国向西，以消耗英美更多的生产，以企图断绝英美对苏的援助。然而，如果单以美日的生产力来对比，只产钢一项，美国便十三倍于日本，更不论汽油及其他了，而生产力的高低，正是决定现代战争胜利与否的主要因素。

　　第五，军事力量的对比，就现状说，彼此各有短长，而轴心国家，恰恰善于发挥其长处，以致在战争初期，都能有若干收获，但必须指出：反侵略国家潜在的后备力是强大的，只要战争持续下去，两方军事力量的对比，是必然会改变的。如分开来看，在欧洲战场上，苏德军事力量的对比，现在正处在转换的关头；而在太平洋上，美国是海空军占优势，日本是陆军占优势，可是太平洋战争，主要的正依靠海空军。

　　第六，在世界的联系上，轴心国家是处在被隔断和封锁的境况中，而反侵略国家，则握有海上空中及大陆三方面的可能交通，这也是客观上一个致胜的要素。

　　第七，反侵略的国家民族，是站在民族自卫，民主自由和人类和平的立场上的结合，他们应该而且能够团结到底的。轴心国家，是由于一时利害而相互勾结，而且都要向外侵占，一旦利害相反，冲突必起。故全世界一切反侵略国家和民族团结起来，便是战胜德日意法西斯的政治保证。

　　上述这些有利条件的发展，将保证全世界反侵略国家和民族，走向最后的全部的彻底的胜利，走向人类的和平。

三

　　然而必须指出：这一胜利与和平，只是前途的瞻望。由今天争取到前途的实现，还须要经过若干过程，才能由漫漫长夜中渡过黑暗，走向光明。这其中主要的原因，是由于民主国家尚存在若干弱点和困难，大家的长处，还没有能发挥尽致，而轴心国家的弱点，也还未全部暴露。简单的说，即是各民主国家的人力、物力、财力、生产力，还没能全部动员，使用尽当，也还没有做到完全团结和信赖无间；这就给轴心国家以各个击破和挑拨分化之机。如果分开来看，我们首先要指出，各民主国家内部，还不够坚固一致，而战争的动员也还做得不够，特别在我们友邦美国，孤立派的组织直到战争开始后，方表面宣告解散，德日意第五纵队〔５〕的活动，不论在美国本土，在夏威夷、菲律宾以及在中南美，都值得严重注意，而人民习于和平的精神，更须迅速转变。在这里，苏联内部坚固的团结和坚强的战志，应该成为大家的模范。

　　次之，全世界许多反侵略国家的人力，还没有完全动员起来，尤其是太平洋沿岸各国及其属地的民族，乃至印度、非洲、近东各民族，都未能大大动员起来，既未信赖他们去武装自卫，也未依靠他们去组织国防生产，更未团结他们结成巩固的反法西斯战线。这就使反侵略国家的广大后备军，置于闲散无用之地，转易为敌人所挑拨利用。

　　再次，有些反侵略国家的资源，还未完全开发，而有些地方，如荷印、马来、菲律宾，又有被侵入危险。在生产力发展国家如美国，开战之前，也还未能高度的使用于国防生产（如福特公司仅以百分之二十生产力制造坦克），这就使他目前军事生产大大落后于军事需要。

　　又次，世界运输联络，客观上虽利于反侵略国家，但主观的弱点还很多（如美国到新西兰的航空，去年才建立，两大陆北部的航线也未建立），现在太平洋东西大门（夏威夷和新加坡）又有被封之虞，而大西洋中法属西非洲和巴西的遥遥相对，又正为希特勒垂涎之地，这都是尚未克服的困难。

　　更次，反侵略国家在军事上的弱点，也是存在的。苏联正以其全部力量对付世界上最顽强的法西斯德国，而欧陆上尚没有第二条战线出现。美国是太平洋上抗日的主角，但他的两洋舰队，距初步完成尚差一年，而空军分布，也未达到压倒的多数，陆军更有待于训练。英国则受制于两面作战。中国的陆上反攻能力，亦有待于加强。特别值得提醒的是维希法国〔６〕所保有的海军，仍有被纳粹德国占用的危险。

　　这一切弱点和困难，都不容我们忽视和盲目乐观，而应联合友邦，奋起急追，全力以赴，共同去克服这些弱点，解决这些困难，以担负太平洋上伟大艰苦的抗日任务。

四

　　我们还须指出：太平洋战争，在初期还会有若干挫败，这正如中日战争，英德战争，苏德战争在初期的一样。这种挫败的可能，无疑问的是由于存在下列的原因：

　　一，日寇是无耻海盗，惯于乘人准备不周，袭人领土。

　　二，日寇如其他侵略者一样，操着进攻的主动权，随时都在准备挑衅，随时都可发动战争，故战火一起，日寇行动可远及三千海里之外，而继续扩张战果。

　　三，日寇已全身武装，有了对付战争的长期经验，有了全国上下的战争动员，最近且加紧进行其大规模的临战体制，故其行动的迅速，资材的储存，我们不能作过低的估计。

　　四，日寇海空军，虽较英美为劣势，但在太平洋上却握有军略的优势。东起夏威夷，西抵马来亚，北自日本海，南抵大洋洲，都为他海空军活动的范围。在这个活动圈内，英美的海空军，显然还处于劣势而且分散。

　　五，英美虽非全无准备，但究因企图和缓太平洋上的目前冲突，在精神上，物质上，总还准备未周。

　　这种初期的挫败，也许会丧失若干岛屿，某些土地以及某些交通线，然而决不足以悲观，而应更加动员起太平洋沿岸的各友邦、各民族，团结一致，互信互助，牺牲一切，坚持最后，必能改变目前太平洋的不利局面。尤其重要的，必须弄清太平洋战争的特征，以免发生不应有的认识和错误的估计。这些特征是：

　　一，太平洋战争是持久战，决非速决战，日寇所要求的，是迅速的各个击破英美分散的海空军主力，以便囊括上述的太平洋活动圈，掠取其中丰富的资源。而在英、美、澳、荷准备未成，布置未周以前，决不能冒取攻势，自陷错误，这在贤明的英美当局中，亦已说到，毋待解释。

　　二，解决日本，海军为主，空军陆军只能为辅。必须明白：单单空军的轰炸，即使从阿拉斯加之阿留申群岛，从中国本部乃至从海参崴，不断轰炸日本三岛，而没有海军的配合进攻，这在动摇日本战志，炸坏日本建设的作用上，是不小的，但并不能解决战事，而美国海军，目前即设想远征三岛的计划，还是过早的事。以德国那样强大的空军和陆军，没有海军的登陆协助，虽仅一海峡之隔，亦无奈英伦三岛何，这就是单靠空军和陆军，不能解决拥有海军的岛国的明证。不错，岛国是最怕海上封锁的，但单单肃清太平洋上日本海军活动的力量和范围，便须相当大的力量和相当长的时间。这里必须指出：新华日报九、十两日所载美日海军力量的比较，在日本方面，都是根据旧的材料，而主力舰只十只，最新的还是一九二一年入水，这是不完全的。

　　三，英美今天还不能且不宜对日立即采取攻势，而须先巩固南太平洋圈内要塞的守卫，如新加坡、达尔文港、马尼拉等地，同时还须巩固印度、夏威夷及阿拉斯加的根据地，及苏伊士、巴拿马两条主要交通线，然后才能设想进攻。罗斯福总统曾说世界战争将在一九四三年结束，这句话不是毫无根据的。

　　四，由于上述客观原因的存在，日寇虽弱于纳粹德国，而所遇的对手，又为ＡＢＣＤ〔７〕及太平洋其他各国，但仍能暂时肆虐，这必须以持久的消耗战和太平洋上联合的力量打击他，才能制他最后的死命。因此，太平洋反日各国的军事同盟和配合作战，中国的反攻，南洋各要塞的坚守，南洋各民族及华侨的动员和武装组织，太平洋上可能被敌占领区域之资源破坏和游击战争发展的准备，在被日本奴役的民族中以及日本国内人民和军队中的工作，这都是给目前敌人最有利的打击。另一方面，在美国以及一切抗日的国家，必须高度的动员人力，物力，财力，尤其是美国，更须改变全国的生产机构，生产军事工业，以适应全世界兵工厂的需要，好最后发出制日本死命的炮火。必需记着：生产能力是决定现代战争的主要因素，决不能再让日寇从南洋取得战争的主要资源，必需百倍的生产最后解决日本的军火，然后再加上人力的运用，日本帝国主义的死亡，是一定的！

五

　　但为了明了太平洋战争与世界战局的关系，我们还须进一步认识整个世界反法西斯的解放战争的特点：

　　一，是长期性。这由于法西斯侵略国家有了多年的战争准备，但苦于资源缺少，故志在速决，而被侵略各国家各民族，除了苏联以外，都是事前很少或者完全没有足够的自卫的准备，但却人多，地大，物博，故必须持久，方能胜利。

　　二，是不平衡性。这由于被侵略各国家各民族过去对于法西斯战争的威胁的了解，有很大的不同，故易为法西斯国家所分化，致战争的发展极不平衡，这很有碍于目前胜利的争取，但如加以补救，也还能使各方力量做到不断的增长。

　　三，是全面性。现代战争决定于人力，物力，生产力的总和，没有这三种力量全部的动员，或动员不够，世界法西斯的消灭是不可能的。

　　四，是一致性，也就是不可分割性。世界各国的反侵略战争，必然会打成一片，变成一体，然后才能阵线扩大，同时也必须坚持最后的全部的胜利，不容中途妥协，单独议和，才能阵线巩固。

　　五，是阶段性。因为是持久战，所以一般的说来，大致都要经过初期的防御和退却阶段，继之以相持和准备阶段，终之以反攻和胜利阶段，但由于各国和各战场的条件不同，各阶段的时间久暂和变化也将有所不同。

　　六，是主从性。在世界战局上说，德为主，日意为辅。对德意须用主力，苏联已付其全力，英国辅之，而对日则有ＡＢＣＤ等国联合力量，美国且为其主。这在世界反法西斯力量的分配上，太平洋已颇不弱，但这也是环境使然。如果能速战解决日本，则移西于东，未尝不可使世界反法西斯的战略部署一时改变，但证之于前段所说，这是不可能的，而且也必然会中纳粹诡计，使主战场上遭受难于挽救的损失。所以即使日寇敢于同时北进，我们太平洋上现有的联合力量，也应防止这一着，以共同保卫东方反法西斯的阵线。

　　懂得了以上所说的目前世界战局的规律，我们便能正确的认识太平洋战争在世界反法西斯阵线中的任务，同时，也必须从世界反法西斯的任务的分担上来解决太平洋战争问题。这里就必须从作战任务的分担上，从一切人力的动员上，从世界资源的分配上，从军事生产的加紧和分担上，从国际交通的建立和维护上，经过太平洋各国的会议和决定，以确定共同的计划，只有这样，太平洋的反日战争，才能有组织的，有配合的，有把握的进行。

　　然而，欲实现这一计划，必须以我们中国来推动英美荷澳及太平洋上其他国家民族的联合，并密切与世界所有反侵略国家和民族的联系。因为只有中国，只有中国的抗战，才能削弱和牵制日寇四年多，才能实行反攻以与英美等国并肩作战，才能影响和推动南洋各地民族和侨胞援助英、美、荷、澳，实行自卫的战争，才能了解苏联是全世界反法西斯的主力，而更懂得怎样善用这一主力，以共同消灭世界法西斯蒂。



　　＊原载一九四一年十二月十四日重庆《新华日报》。

　　注释

　　〔１〕太平洋战争指第二次世界大战期间反法西斯联盟国家与日本在太平洋地区进行的战争。一九四一年十二月七日，日本未经宣战，以强大的海军、空军突然袭击美国在太平洋地区的主要海、空军基地珍珠港，使美国太平洋舰队遭到惨重失败。十二月八日，美、英对日宣战。同日，德、意对美宣战。日本军队先后侵占了东南亚的许多国家和地区以及太平洋上的一些岛屿，后来在太平洋地区各反法西斯国家武装力量的沉重打击下，不断遭到失败。一九四五年八月，日本无条件投降，结束战争。

　　〔２〕来栖三郎（一八八六～一九四五），日本外交官。一九三九年任驻德国大使，负责同德意日法西斯三国军事同盟条约的签订工作。一九四一年十一月初，受东条英机内阁外务大臣东乡茂德委派，作为特使专程赴美，协助野村吉三郎（参见本书《论敌寇两面政策》一文注〔８〕大使处理僵持中的日美谈判事宜。实际上的使命是，以加强谈判为幌子，掩盖日本加紧发动大规模战争的准备活动。同年十二月八日太平洋战争爆发后回国。

　　〔３〕赫尔（一八七一～一九五五），美国国务卿（一九三三～一九四四）。民主党人。国务卿任内，缓和保守社会势力对"新政"的不满；对拉丁美洲地区推行"睦邻政策"；主张援助英、法对抗法西斯德国；主持对日谈判，对美国外交有重大影响。一九四四年十一月辞职，次年获得诺贝尔和平奖金。

　　〔４〕罗斯托夫是苏联罗斯托夫州首府，位于顿河下游右岸，十九世纪已成为沙俄南方大港。一九四一年十一月十七日至十二月二日，罗斯托夫的进攻战役是苏联卫国战争中第一次实施的大规模进攻战役，具有重要的军事意义。这次战役将德军坦克第一军团从罗斯托夫向西击退六十至八十公里，制止了德军向高加索的突进，稳定了苏联战场南翼，为苏军一九四一年冬季反攻奠定了基础。

　　〔５〕第五纵队，参见本书《太平洋的新危机》一文注〔１０〕。

　　〔６〕维希法国，参见本书《国际形势与中国抗战》一文注〔１〕。

　　〔７〕ＡＢＣＤ，参见本书《太平洋的新危机》一文注〔９〕。



