# 在列宁斯大林旗帜之下，苏联红军胜利的前进！

中文马克思主义文库 -> 周恩来
在列宁斯大林旗帜之下，苏联红军胜利的前进！
（一九四二年二月二十三日）

在全世界都受着法西斯强盗的侵略和威胁当中，在全人类几乎都卷入战争的烈火当中，我们来过苏联红军二十四周年的纪念节，自有其特别重大的意义

苏联红军降生在一九一八年德国侵略者逼近彼得格勒的危难当中。由于工农群众的无比英勇，由于布尔塞维克党和苏维埃政府的坚强领导，特别由于列宁斯大林的亲自号召和指挥，当时年幼的红军终于阻止了全副武装的德国强盗的攻击。现在，二十四年后，德国法西斯强盗又以其世界上最残酷最无耻的军队，装备了世界上最新式的武器，背信弃义的闯进了苏维埃的领土，逼近了不只是列宁格勒而且是莫斯科和高加索的大门。但是，今天年青的红军，却更以其至大的英勇和流血的牺牲，保卫了苏维埃的每一寸土，击退了希特勒匪徒对于侵占列宁格勒莫斯科和高加索的一切尝试。战争已这样进行了八个多月，红军在战斗的烈火中已炼成永远不可战胜的力量，在他的后边有着全苏联人民的动员做后盾，有着全世界反法西斯的人类做后援，尤其是领导他的有世界上最坚强最前进的布尔塞维克党和苏维埃政府，而伟大的斯大林更亲自指挥他向着胜利的道路上前进。

难道我们还可以怀疑，我们可以而且一定能够战胜德国强盗么？

（斯大林语）我想，一点也不用怀疑。便连我们敌人--法西斯强盗也都已承认，他们是估计错了。希特勒匪徒在席卷十四个国家之后，遇到了红军，他那种所向无敌的奇谈，是完全破产了。摧毁世界文明成为人类不共戴天之敌的法西斯强盗，在红军的重击下，实力是日渐削弱，生产是日渐减少，士气是日渐消沉，统治是日渐动摇，而最后则必不免于崩溃。但法西斯德国决不会自行崩溃的，何况他的兵力还未被完全摧毁，他正在高谈春季攻势。可是战争的主动性已经转到红军手里，红军必然会继续把握住这个主动权，节节的进攻敌人，不断的歼灭敌人，不让敌人喘息，不让敌人整顿，不达到最后胜利，绝不罢手。即使希特勒真组织起春季攻势，其力量也要较去年脆弱，其后援也要较去年单薄，只要苏联红军奋其无上的英勇，苏联人民动员其全部力量和生产，则纳粹匪军的春季攻势，不论其向着何方，必再度失败无疑。即使更有其他的侵略者敢于再向苏联挑衅，也必然要遭受到同样的失败。现在，正处在红军纪念节中，英勇机动的红军，想更会以庆贺自己生日的热忱和兴奋，来给纳粹匪军以迎头痛击罢。我们愿在此遥致贺忱，预祝胜利！

苏联红军既担负起世界上歼灭法西斯渠魁的艰巨任务，我们全世界反法西斯阵线中的各民族各国家，便都应各就本位，尽其力之所能，或以物资援助苏联，或加强其本身战斗力量，以配合红军作战，如我中国，则更应加强对当面之敌的战斗，以负起牵制和消灭东方法西斯的主要任务。世界战场虽在两方，世界战争已属一个，不论在西方在东方，我们都是对法西斯侵略者作战。只要我们努力于反法西斯的战斗，我们便是最好的配合红军作战，最实际的庆贺红军纪念节。

尤其重要的，我们还应从红军的伟大胜利中，学得一些宝训，以争取全世界反法西斯战争的胜利。

苏联红军所遇到的敌人，是世界上最大最强最恶的军队，而且握有全欧（苏联英伦除外）的生产力以闪击苏联，然而红军从没有一秒钟丧失其自信力，也从没有一次放下其武器，停止其斗志。确信最后胜利，确信自力可以歼灭顽敌，这是苏联红军永远不可攻破的信念。

法西斯德国的侵略战，一开始便攻入苏联领土，而苏联红军的保卫战虽处在防御地位，但决未丧失其积极性，亦即是积极防御或攻势防御。消极防御或守势防御在红军的战斗条令中是没有他的地位的。纳粹匪军的胜利是以攻城略地多少为标志，而红军的胜利则以歼灭俘获敌人多少为标志。因此，希特勒去年虽组织了五次攻势，但一而再，再而衰，三而竭。红军却拥有雄厚的后备力量，所以在纳粹匪军衰竭之后，便能立即转入主动的攻势。

红军掌握了主动权之后，一直在向敌推进，决没停止过他消灭敌人的战斗。只有战斗，才能使敌人无从稳住他最后的防线。只有战斗，才能继续掌握着战争的主动之权。

红军的英勇，表现出至高无上的自我牺牲的精神，他们从个人的英雄主义长成到群众的英雄主义。红军战士在战斗中，真正实行了他们流尽最后一滴血的誓言。只有毁灭的城市，没有挂起白旗的城市。只有寸土必争的国防，没有不设防的领土。只有拚到最后一个人，最后一颗子弹，最后一口气，没有成千成万的投降和缴械。

苏联红军和人民是彻底遵守了焦土抗战的决策。二十年来苏联人民亲手建设起的繁华都市和美丽乡村，在纳粹匪徒将要侵入之前甚至已经占领之后，都又亲手将他们毁了，决不让纳粹匪徒有任何所得，而只留给他一片焦土，一堆残骸。这是凤凰自焚了而再生的精神，最值得反侵略者效法。

游击战争本是苏联人民和红军的优良传统之一，这次经过斯大林的号召，更普遍发展于敌占区域，并深入到被法西斯强盗奴役的各国人民当中。到了将来消灭德国匪军的决定胜利时，必可看出人民游击战争的更大作用。

苏联红军和人民的合作，人民为红军的后盾，已胶结成为不可分解的力量，人民也就成为红军不竭的源泉。苏联的领土虽辽阔，人民的感觉虽有别，但广泛深入的动员，已经使红军的补充不缺，供给适时，运输便利，后方巩固，而现在还要更进一步的动员人力，动员生产，实行竞赛，还要以更多的兵员新工作者，更多的飞机坦克大炮，更多的粮秣服装用具，供给前方。

苏联红军的教育，也是最能使之掌握现代技术的。他的军事政治教育不仅养成于军队或军校中，而且早就培养他的基础于人民的普通教育和日常生活中了。

苏联红军之所以如此坚强的，其基本原因，还由于军队中政治工作的深入。政治工作是红军的生命线，是巩固部队的灵魂，而决非是部队中的特务，或是一些装饰品。

最后，苏联红军之所以胜利，所以必能得到完全的胜利，主要的还因为有着红军昨日的创造者和红军今日的指挥者斯大林同志在领导他们。斯大林就是胜利的旗帜。

在列宁斯大林的旗帜之下，苏联红军是永远不可战胜的力量！

在反法西斯战争的烈火中，苏联红军已成为保卫全世界人类自由解放的力量！

庆祝苏联红军纪念节，就是庆祝反法西斯战争的胜利，也就是庆祝全世界反法西斯的团结！

＊原载一九四二年二月二十三日重庆《新华日报》。 

