# 左权同志精神不死！

中文马克思主义文库 -> 周恩来
左权同志精神不死！
（一九四二年六月二十三日）


　　几天前，从华北战场上传来了一个哀讯，我英勇忠贞的左权〔１〕同志--第十八集团军副参谋长，在反扫荡战中，悲壮的殉国了。这一哀讯，震动了十八集团军的全体将士，打动了华北敌后广大人民的心弦，同时，也必然会引起全国抗战军民的注意和悼念。

　　在抗战中，中华民族的优秀儿女牺牲在敌人炮火烧杀中的，已不知有多少，更何况左权是抗战军人，身临前线，战死疆场，正是尽了他的天职，也是革命军人之荣。只是左权同志死在壮年，以他的志行才力，经验学识，所能贡献于国家民族，尽力于革命军队者正大，今一旦壮烈牺牲，对于抗战事业，尤其是对于十八集团军和敌后人民，真是一个无可补偿的损失。概自抗战军兴，高级将领牺牲于前线者前有郝梦龄、王铭章诸将军，后有张自忠、唐淮源诸将军，今左权同志以十八集团军副参谋长之地位，于敌后支撑抗战，将近五年，终至以身殉国，斯真不愧跻于高级将领之列，且足为高级幕僚争光。

　　左权同志湘人，早岁习军事于广东湘军讲武堂。时湘军在谭组庵程颂云两先生领导下参加国民革命，故有讲武堂的训练组织，颂云先生实为之长。讲武堂中多二湘七泽间子弟，以湖南的革命前辈训练湖南的革命青年于革命的策源地广东，真所谓相得益彰。左权同志的革命信念，便由此起。不久，湘军讲武堂归并于黄埔军校〔２〕，全体学生编为第五队，与前期队同为一期生毕业。在一期同学中，湖南人特多，知名者如蒋先云（战死于北伐时代河南战役中）、李默庵、宋希濂、贺衷寒、刘云、刘戡、霍揆彰、陈启科、陈赓、赵自选诸同学，而左权同志便为其中之一员。缅怀当年同学，今日同袍，风雨同舟，能无故人之感！？

　　左权同志毕业黄埔军校后，即参加东征及回师广州诸役。未几，与陈启科同志在广州考入莫斯科中山大学，遂转往苏联留学。其后左权同志又与刘伯承、刘云、陈启科转入苏联陆军大学攻读。民国十九年毕业归来，刘陈两同志相继牺牲，左权、刘伯承两同志则先后驰抵江西军中。从此时起，整整十一年，左权同志未尝一日离开军队，而抗战五年，左权同志更未尝一日离开前线。在近二十年的军事生活中，由军校到军队，最后更战死军中，左权同志是真能与革命军队共始终者。他这种革命军人自我牺牲的精神，实无忝于黄埔同学，更配称得起蒋委员长的抗战部属，革命学生。

　　抗战五年了，中经多变，太平洋战争起后，敌人既有事于南洋，亦未放松于北进的准备，但同时却在华中进攻长沙，在华北扫荡山地。缅甸既陷，敌人立即转其凶焰，侵我滇边，同时更用兵于浙赣，转移扫荡于华北平原。可见敌人一日不退出中国，我固不能止抗战之火，即敌人亦不能熄侵略毒焰。

　　又有人想，敌人在中国战场上可以有所选择，即是说有所打，亦有所不打。这种想法，更是有毒索的。固然，敌人时常在想分化中国内部，挑拨中国内乱。但敌人终究是敌人，中国人终究是中国人，当敌决意进攻之时，他又何尝分别过你是哪类的中国人，我是哪类的中国人，他又是哪类的中国人！？这次晋豫冀边太行南端的战斗，恰发生在缅甸方陷，浙赣战争紧张之际，而战斗激烈直逼至十八集团军总部指挥所在。左权同志就在这九天的战斗中，亲自指挥所部突破敌人的重围，而自己却光荣的牺牲了。左权同志的战死，正足以说明这一真理：在敌人心目中，不论于你属于何党何派，只要你不投降日寇，他就需要消灭你。

　　敌人既无所选择，我们岂容有所规避，而且岂忍有所规避？（被略十一句）五年来十八集团军在敌后的战绩，伤亡及其所遇到的困难，拿左副参谋长五年苦战的功劳和最后殉国的壮烈为印证，就可以例其余了。我们谨在此向全世界反法西斯的战友，向全中国的同胞同袍申明：我们是至死不会离开敌后抗日根据地的，我们决心要将沦陷的河山从百战中夺回的。无论如何，我们要战胜敌人，我们要准备流尽最后一滴血来争取它，左权同志便是我们最好的榜样。

　　左权同志不仅是革命军人，而且是革命党员。他加入中国共产党在黄埔时代，这成为他以后近二十年政治生活中的准绳。他之牺牲，证明他无愧于他所信仰者，而且足以为党之模范。左权同志又是一个有理论修养同时有实践经验的军事家。他在军中，经常喜欢研究，喜欢译著，同时，他又勤于工作，忠于职守。他习于游击战争，但他也不忘正规战术，所以他在军队正规化的口号下，尽了他最大的责任。沉毅坚忍，是他个性中的特长，也就成为他在党内在军中在社会上读书治事，练兵作战，立身处世时的特点。在这方面，足供同志们战友们追念回忆之事甚多，于此不及备述。

　　我与左权同志相识近二十年，不幸抗战以还，我因远离前线，不克与其同生死共患难者竟达四年之久。今左权同志殉国了。遥望大河以北，请缨有愿；困处夔门之内，杀敌无缘。这虽因岗位有别，但髀肉复生的我，遥闻哀耗，究不能无动于中。

　　左权同志已作先驱了，万千个左权同志的化身将继着起来，千百万的人民和军队将踏着他的血迹前进。华北抗战已近五年，胜利之期已不在远，行见太行之巅，高树起左权同志的胜利旗帜，数十万八路健儿，北下平津，东出榆关，那便是我们的复仇期了。

　　左权同志精神不死！

　　中国抗战胜利万岁！

　　民国卅一年六月廿一日



　　＊原载一九四二年六月二十三日重庆《新华日报》。

　　注释

　　〔１〕左权（一九○六～一九四二），湖南醴陵人。一九二五年加入中国共产党。黄埔军校第一期毕业后，去苏联陆军大学学习。一九三○年回国，历任中国工农红军第十五军政治委员和军长，第一军团参谋长和代军团长等职。抗日战争爆发后，任八路军副参谋长。一九四二年六月二日在山西辽县（今左权县）麻田指挥部队与日本侵略军作战中牺牲。

　　〔２〕黄埔军校，是一九二四年孙中山在中国共产党和苏联的帮助下，在广州黄埔创办的军官学校。中国共产党派周恩来、恽代英、肖楚女、聂荣臻等在该校担任过各种职务，学员中也有很多共产党员和共青团员。一九二七年蒋介石背叛革命以前，这是一所国共合作的学校。



